#!/bin/bash

if [ $(uname -a | grep -ci Ubuntu) -ge 1 ]; then
    #for topotests under ubuntu host
    sudo modprobe mpls-router mpls-iptunnel
    sudo /etc/init.d/openvswitch-switch start
fi
while true ; do sleep 365d ; done
