/*NHRPpeerfunctions*Copyright(c)2014-2015TimoTeräs**Thisfileisfreesoftware:youma
ycopy,redistributeand/ormodify*itunderthetermsoftheGNUGeneralPublicLicenseaspubl
ishedby*theFreeSoftwareFoundation,eitherversion2oftheLicense,or*(atyouroption)an
ylaterversion.*/#include<netinet/if_ether.h>#include"zebra.h"#include"memory.h"#
include"thread.h"#include"hash.h"#include"nhrpd.h"#include"nhrp_protocol.h"#incl
ude"os.h"DEFINE_MTYPE_STATIC(NHRPD,NHRP_PEER,"NHRPpeerentry")structipv6hdr{uint8
_tpriority_version;uint8_tflow_lbl[3];uint16_tpayload_len;uint8_tnexthdr;uint8_t
hop_limit;structin6_addrsaddr;structin6_addrdaddr;};staticvoidnhrp_packet_debug(
structzbuf*zb,constchar*dir);staticvoidnhrp_peer_check_delete(structnhrp_peer*p)
{structnhrp_interface*nifp=p->ifp->info;if(p->ref||notifier_active(&p->notifier_
list))return;THREAD_OFF(p->t_fallback);hash_release(nifp->peer_hash,p);nhrp_inte
rface_notify_del(p->ifp,&p->ifp_notifier);nhrp_vc_notify_del(p->vc,&p->vc_notifi
er);XFREE(MTYPE_NHRP_PEER,p);}staticintnhrp_peer_notify_up(structthread*t){struc
tnhrp_peer*p=THREAD_ARG(t);structnhrp_vc*vc=p->vc;structinterface*ifp=p->ifp;str
uctnhrp_interface*nifp=ifp->info;p->t_fallback=NULL;if(nifp->enabled&&(!nifp->ip
sec_profile||vc->ipsec)){p->online=1;nhrp_peer_ref(p);notifier_call(&p->notifier
_list,NOTIFY_PEER_UP);nhrp_peer_unref(p);}return0;}staticvoid__nhrp_peer_check(s
tructnhrp_peer*p){structnhrp_vc*vc=p->vc;structinterface*ifp=p->ifp;structnhrp_i
nterface*nifp=ifp->info;unsignedonline;online=nifp->enabled&&(!nifp->ipsec_profi
le||vc->ipsec);if(p->online!=online){THREAD_OFF(p->t_fallback);if(online&&notifi
er_active(&p->notifier_list)){/*IfwerequestedtheIPsecconnection,delay*theupnotif
icationabittoallowthings*settledown.ThisallowsIKEtoinstall*SPDsandSAs.*/thread_a
dd_timer_msec(master,nhrp_peer_notify_up,p,50,&p->t_fallback);}else{nhrp_peer_re
f(p);p->online=online;if(online){notifier_call(&p->notifier_list,NOTIFY_PEER_UP)
;}else{p->requested=p->fallback_requested=0;notifier_call(&p->notifier_list,NOTI
FY_PEER_DOWN);}nhrp_peer_unref(p);}}}staticvoidnhrp_peer_vc_notify(structnotifie
r_block*n,unsignedlongcmd){structnhrp_peer*p=container_of(n,structnhrp_peer,vc_n
otifier);switch(cmd){caseNOTIFY_VC_IPSEC_CHANGED:__nhrp_peer_check(p);break;case
NOTIFY_VC_IPSEC_UPDATE_NBMA:nhrp_peer_ref(p);notifier_call(&p->notifier_list,NOT
IFY_PEER_NBMA_CHANGING);nhrp_peer_unref(p);break;}}staticvoidnhrp_peer_ifp_notif
y(structnotifier_block*n,unsignedlongcmd){structnhrp_peer*p=container_of(n,struc
tnhrp_peer,ifp_notifier);structnhrp_interface*nifp;structnhrp_vc*vc;nhrp_peer_re
f(p);switch(cmd){caseNOTIFY_INTERFACE_UP:caseNOTIFY_INTERFACE_DOWN:__nhrp_peer_c
heck(p);break;caseNOTIFY_INTERFACE_NBMA_CHANGED:/*SourceNBMAchanged,rebindtonewV
C*/nifp=p->ifp->info;vc=nhrp_vc_get(&nifp->nbma,&p->vc->remote.nbma,1);if(vc&&p-
>vc!=vc){nhrp_vc_notify_del(p->vc,&p->vc_notifier);p->vc=vc;nhrp_vc_notify_add(p
->vc,&p->vc_notifier,nhrp_peer_vc_notify);__nhrp_peer_check(p);}/*fallthru*//*to
postconfigupdate*/caseNOTIFY_INTERFACE_ADDRESS_CHANGED:notifier_call(&p->notifie
r_list,NOTIFY_PEER_IFCONFIG_CHANGED);break;caseNOTIFY_INTERFACE_MTU_CHANGED:noti
fier_call(&p->notifier_list,NOTIFY_PEER_MTU_CHANGED);break;}nhrp_peer_unref(p);}
staticunsignedintnhrp_peer_key(void*peer_data){structnhrp_peer*p=peer_data;retur
nsockunion_hash(&p->vc->remote.nbma);}staticintnhrp_peer_cmp(constvoid*cache_dat
a,constvoid*key_data){conststructnhrp_peer*a=cache_data;conststructnhrp_peer*b=k
ey_data;returna->ifp==b->ifp&&a->vc==b->vc;}staticvoid*nhrp_peer_create(void*dat
a){structnhrp_peer*p,*key=data;p=XMALLOC(MTYPE_NHRP_PEER,sizeof(*p));if(p){*p=(s
tructnhrp_peer){.ref=0,.ifp=key->ifp,.vc=key->vc,.notifier_list=NOTIFIER_LIST_IN
ITIALIZER(&p->notifier_list),};nhrp_vc_notify_add(p->vc,&p->vc_notifier,nhrp_pee
r_vc_notify);nhrp_interface_notify_add(p->ifp,&p->ifp_notifier,nhrp_peer_ifp_not
ify);}returnp;}structnhrp_peer*nhrp_peer_get(structinterface*ifp,constunionsocku
nion*remote_nbma){structnhrp_interface*nifp=ifp->info;structnhrp_peerkey,*p;stru
ctnhrp_vc*vc;if(!nifp->peer_hash){nifp->peer_hash=hash_create(nhrp_peer_key,nhrp
_peer_cmp,"NHRPPeerHash");if(!nifp->peer_hash)returnNULL;}vc=nhrp_vc_get(&nifp->
nbma,remote_nbma,1);if(!vc)returnNULL;key.ifp=ifp;key.vc=vc;p=hash_get(nifp->pee
r_hash,&key,nhrp_peer_create);nhrp_peer_ref(p);if(p->ref==1)__nhrp_peer_check(p)
;returnp;}structnhrp_peer*nhrp_peer_ref(structnhrp_peer*p){if(p)p->ref++;returnp
;}voidnhrp_peer_unref(structnhrp_peer*p){if(p){p->ref--;nhrp_peer_check_delete(p
);}}staticintnhrp_peer_request_timeout(structthread*t){structnhrp_peer*p=THREAD_
ARG(t);structnhrp_vc*vc=p->vc;structinterface*ifp=p->ifp;structnhrp_interface*ni
fp=ifp->info;p->t_fallback=NULL;if(p->online)return0;if(nifp->ipsec_fallback_pro
file&&!p->prio&&!p->fallback_requested){p->fallback_requested=1;vici_request_vc(
nifp->ipsec_fallback_profile,&vc->local.nbma,&vc->remote.nbma,p->prio);thread_ad
d_timer(master,nhrp_peer_request_timeout,p,30,&p->t_fallback);}else{p->requested
=p->fallback_requested=0;}return0;}intnhrp_peer_check(structnhrp_peer*p,intestab
lish){structnhrp_vc*vc=p->vc;structinterface*ifp=p->ifp;structnhrp_interface*nif
p=ifp->info;if(p->online)return1;if(!establish)return0;if(p->requested)return0;i
f(!nifp->ipsec_profile)return0;if(sockunion_family(&vc->local.nbma)==AF_UNSPEC)r
eturn0;p->prio=establish>1;p->requested=1;vici_request_vc(nifp->ipsec_profile,&v
c->local.nbma,&vc->remote.nbma,p->prio);thread_add_timer(master,nhrp_peer_reques
t_timeout,p,(nifp->ipsec_fallback_profile&&!p->prio)?15:30,&p->t_fallback);retur
n0;}voidnhrp_peer_notify_add(structnhrp_peer*p,structnotifier_block*n,notifier_f
n_tfn){notifier_add(n,&p->notifier_list,fn);}voidnhrp_peer_notify_del(structnhrp
_peer*p,structnotifier_block*n){notifier_del(n);nhrp_peer_check_delete(p);}voidn
hrp_peer_send(structnhrp_peer*p,structzbuf*zb){charbuf[2][256];nhrp_packet_debug
(zb,"Send");if(!p->online)return;debugf(NHRP_DEBUG_KERNEL,"PACKET:Send%s->%s",so
ckunion2str(&p->vc->local.nbma,buf[0],sizeofbuf[0]),sockunion2str(&p->vc->remote
.nbma,buf[1],sizeofbuf[1]));os_sendmsg(zb->head,zbuf_used(zb),p->ifp->ifindex,so
ckunion_get_addr(&p->vc->remote.nbma),sockunion_get_addrlen(&p->vc->remote.nbma)
);zbuf_reset(zb);}staticvoidnhrp_handle_resolution_req(structnhrp_packet_parser*
p){structzbuf*zb,payload;structnhrp_packet_header*hdr;structnhrp_cie_header*cie;
structnhrp_extension_header*ext;structnhrp_interface*nifp;structnhrp_peer*peer;i
f(!(p->if_ad->flags&NHRP_IFF_SHORTCUT)){debugf(NHRP_DEBUG_COMMON,"Shortcutsdisab
led");/*FIXME:Senderrorindication?*/return;}if(p->if_ad->network_id&&p->route_ty
pe==NHRP_ROUTE_OFF_NBMA&&p->route_prefix.prefixlen<8){debugf(NHRP_DEBUG_COMMON,"
Shortcuttomoregenericthan/8dropped");return;}debugf(NHRP_DEBUG_COMMON,"Parsingan
dreplyingtoResolutionReq");if(nhrp_route_address(p->ifp,&p->src_proto,NULL,&peer
)!=NHRP_ROUTE_NBMA_NEXTHOP)return;#if0/*FIXME:UpdaterequestorsbindingifCIEspecif
iesholdingtime*/nhrp_cache_update_binding(NHRP_CACHE_CACHED,&p->src_proto,nhrp_p
eer_get(p->ifp,&p->src_nbma),htons(cie->holding_time));#endifnifp=peer->ifp->inf
o;/*Createreply*/zb=zbuf_alloc(1500);hdr=nhrp_packet_push(zb,NHRP_PACKET_RESOLUT
ION_REPLY,&p->src_nbma,&p->src_proto,&p->dst_proto);/*Copiedinformationfromreque
st*/hdr->flags=p->hdr->flags&htons(NHRP_FLAG_RESOLUTION_SOURCE_IS_ROUTER|NHRP_FL
AG_RESOLUTION_SOURCE_STABLE);hdr->flags|=htons(NHRP_FLAG_RESOLUTION_DESTINATION_
STABLE|NHRP_FLAG_RESOLUTION_AUTHORATIVE);hdr->u.request_id=p->hdr->u.request_id;
/*CIEpayload*/cie=nhrp_cie_push(zb,NHRP_CODE_SUCCESS,&nifp->nbma,&p->if_ad->addr
);cie->holding_time=htons(p->if_ad->holdtime);cie->mtu=htons(p->if_ad->mtu);if(p
->if_ad->network_id&&p->route_type==NHRP_ROUTE_OFF_NBMA)cie->prefix_length=p->ro
ute_prefix.prefixlen;elsecie->prefix_length=8*sockunion_get_addrlen(&p->if_ad->a
ddr);/*Handleextensions*/while((ext=nhrp_ext_pull(&p->extensions,&payload))!=NUL
L){switch(htons(ext->type)&~NHRP_EXTENSION_FLAG_COMPULSORY){caseNHRP_EXTENSION_N
AT_ADDRESS:if(sockunion_family(&nifp->nat_nbma)==AF_UNSPEC)break;ext=nhrp_ext_pu
sh(zb,hdr,NHRP_EXTENSION_NAT_ADDRESS);if(!ext)gotoerr;cie=nhrp_cie_push(zb,NHRP_
CODE_SUCCESS,&nifp->nat_nbma,&p->if_ad->addr);if(!cie)gotoerr;nhrp_ext_complete(
zb,ext);break;default:if(nhrp_ext_reply(zb,hdr,p->ifp,ext,&payload)<0)gotoerr;br
eak;}}nhrp_packet_complete(zb,hdr);nhrp_peer_send(peer,zb);err:nhrp_peer_unref(p
eer);zbuf_free(zb);}staticvoidnhrp_handle_registration_request(structnhrp_packet
_parser*p){structinterface*ifp=p->ifp;structzbuf*zb,payload;structnhrp_packet_he
ader*hdr;structnhrp_cie_header*cie;structnhrp_extension_header*ext;structnhrp_ca
che*c;unionsockunioncie_nbma,cie_proto,*proto_addr,*nbma_addr,*nbma_natoa;inthol
dtime,prefix_len,hostprefix_len,natted=0;size_tpaylen;void*pay;debugf(NHRP_DEBUG
_COMMON,"ParsingandreplyingtoRegistrationReq");hostprefix_len=8*sockunion_get_ad
drlen(&p->if_ad->addr);if(!sockunion_same(&p->src_nbma,&p->peer->vc->remote.nbma
))natted=1;/*Createreply*/zb=zbuf_alloc(1500);hdr=nhrp_packet_push(zb,NHRP_PACKE
T_REGISTRATION_REPLY,&p->src_nbma,&p->src_proto,&p->if_ad->addr);/*Copiedinforma
tionfromrequest*/hdr->flags=p->hdr->flags&htons(NHRP_FLAG_REGISTRATION_UNIQUE|NH
RP_FLAG_REGISTRATION_NAT);hdr->u.request_id=p->hdr->u.request_id;/*CopypayloadCI
Es*/paylen=zbuf_used(&p->payload);pay=zbuf_pushn(zb,paylen);if(!pay)gotoerr;memc
py(pay,zbuf_pulln(&p->payload,paylen),paylen);zbuf_init(&payload,pay,paylen,payl
en);while((cie=nhrp_cie_pull(&payload,hdr,&cie_nbma,&cie_proto))!=NULL){prefix_l
en=cie->prefix_length;if(prefix_len==0||prefix_len>=hostprefix_len)prefix_len=ho
stprefix_len;if(prefix_len!=hostprefix_len&&!(p->hdr->flags&htons(NHRP_FLAG_REGI
STRATION_UNIQUE))){cie->code=NHRP_CODE_BINDING_NON_UNIQUE;continue;}/*Wecurrentl
ysupportonlyuniqueprefixregistrations*/if(prefix_len!=hostprefix_len){cie->code=
NHRP_CODE_ADMINISTRATIVELY_PROHIBITED;continue;}proto_addr=(sockunion_family(&ci
e_proto)==AF_UNSPEC)?&p->src_proto:&cie_proto;nbma_addr=(sockunion_family(&cie_n
bma)==AF_UNSPEC)?&p->src_nbma:&cie_nbma;nbma_natoa=NULL;if(natted){nbma_natoa=nb
ma_addr;}holdtime=htons(cie->holding_time);if(!holdtime)holdtime=p->if_ad->holdt
ime;c=nhrp_cache_get(ifp,proto_addr,1);if(!c){cie->code=NHRP_CODE_INSUFFICIENT_R
ESOURCES;continue;}if(!nhrp_cache_update_binding(c,NHRP_CACHE_DYNAMIC,holdtime,n
hrp_peer_ref(p->peer),htons(cie->mtu),nbma_natoa)){cie->code=NHRP_CODE_ADMINISTR
ATIVELY_PROHIBITED;continue;}cie->code=NHRP_CODE_SUCCESS;}/*Handleextensions*/wh
ile((ext=nhrp_ext_pull(&p->extensions,&payload))!=NULL){switch(htons(ext->type)&
~NHRP_EXTENSION_FLAG_COMPULSORY){caseNHRP_EXTENSION_NAT_ADDRESS:ext=nhrp_ext_pus
h(zb,hdr,NHRP_EXTENSION_NAT_ADDRESS);if(!ext)gotoerr;zbuf_copy(zb,&payload,zbuf_
used(&payload));if(natted){nhrp_cie_push(zb,NHRP_CODE_SUCCESS,&p->peer->vc->remo
te.nbma,&p->src_proto);}nhrp_ext_complete(zb,ext);break;default:if(nhrp_ext_repl
y(zb,hdr,ifp,ext,&payload)<0)gotoerr;break;}}nhrp_packet_complete(zb,hdr);nhrp_p
eer_send(p->peer,zb);err:zbuf_free(zb);}staticintparse_ether_packet(structzbuf*z
b,uint16_tprotocol_type,unionsockunion*src,unionsockunion*dst){switch(protocol_t
ype){caseETH_P_IP:{structiphdr*iph=zbuf_pull(zb,structiphdr);if(iph){if(src)sock
union_set(src,AF_INET,(uint8_t*)&iph->saddr,sizeof(iph->saddr));if(dst)sockunion
_set(dst,AF_INET,(uint8_t*)&iph->daddr,sizeof(iph->daddr));}}break;caseETH_P_IPV
6:{structipv6hdr*iph=zbuf_pull(zb,structipv6hdr);if(iph){if(src)sockunion_set(sr
c,AF_INET6,(uint8_t*)&iph->saddr,sizeof(iph->saddr));if(dst)sockunion_set(dst,AF
_INET6,(uint8_t*)&iph->daddr,sizeof(iph->daddr));}}break;default:return0;}return
1;}voidnhrp_peer_send_indication(structinterface*ifp,uint16_tprotocol_type,struc
tzbuf*pkt){unionsockuniondst;structzbuf*zb,payload;structnhrp_interface*nifp=ifp
->info;structnhrp_afi_data*if_ad;structnhrp_packet_header*hdr;structnhrp_peer*p;
charbuf[2][SU_ADDRSTRLEN];if(!nifp->enabled)return;payload=*pkt;if(!parse_ether_
packet(&payload,protocol_type,&dst,NULL))return;if(nhrp_route_address(ifp,&dst,N
ULL,&p)!=NHRP_ROUTE_NBMA_NEXTHOP)return;if_ad=&nifp->afi[family2afi(sockunion_fa
mily(&dst))];if(!(if_ad->flags&NHRP_IFF_REDIRECT)){debugf(NHRP_DEBUG_COMMON,"Sen
dTrafficIndicationto%saboutpacketto%signored",sockunion2str(&p->vc->remote.nbma,
buf[0],sizeofbuf[0]),sockunion2str(&dst,buf[1],sizeofbuf[1]));return;}debugf(NHR
P_DEBUG_COMMON,"SendTrafficIndicationto%s(online=%d)aboutpacketto%s",sockunion2s
tr(&p->vc->remote.nbma,buf[0],sizeofbuf[0]),p->online,sockunion2str(&dst,buf[1],
sizeofbuf[1]));/*Createreply*/zb=zbuf_alloc(1500);hdr=nhrp_packet_push(zb,NHRP_P
ACKET_TRAFFIC_INDICATION,&nifp->nbma,&if_ad->addr,&dst);hdr->hop_count=0;/*Paylo
adisthepacketcausingindication*/zbuf_copy(zb,pkt,zbuf_used(pkt));nhrp_packet_com
plete(zb,hdr);nhrp_peer_send(p,zb);nhrp_peer_unref(p);zbuf_free(zb);}staticvoidn
hrp_handle_error_ind(structnhrp_packet_parser*pp){structzbuforigmsg=pp->payload;
structnhrp_packet_header*hdr;structnhrp_reqid*reqid;unionsockunionsrc_nbma,src_p
roto,dst_proto;charbuf[2][SU_ADDRSTRLEN];hdr=nhrp_packet_pull(&origmsg,&src_nbma
,&src_proto,&dst_proto);if(!hdr)return;debugf(NHRP_DEBUG_COMMON,"ErrorIndication
from%saboutpacketto%signored",sockunion2str(&pp->src_proto,buf[0],sizeofbuf[0]),
sockunion2str(&dst_proto,buf[1],sizeofbuf[1]));reqid=nhrp_reqid_lookup(&nhrp_pac
ket_reqid,htonl(hdr->u.request_id));if(reqid)reqid->cb(reqid,pp);}staticvoidnhrp
_handle_traffic_ind(structnhrp_packet_parser*p){unionsockuniondst;charbuf[2][SU_
ADDRSTRLEN];if(!parse_ether_packet(&p->payload,htons(p->hdr->protocol_type),NULL
,&dst))return;debugf(NHRP_DEBUG_COMMON,"TrafficIndicationfrom%saboutpacketto%s:%
s",sockunion2str(&p->src_proto,buf[0],sizeofbuf[0]),sockunion2str(&dst,buf[1],si
zeofbuf[1]),(p->if_ad->flags&NHRP_IFF_SHORTCUT)?"tryingshortcut":"ignored");if(p
->if_ad->flags&NHRP_IFF_SHORTCUT)nhrp_shortcut_initiate(&dst);}enumpacket_type_t
{PACKET_UNKNOWN=0,PACKET_REQUEST,PACKET_REPLY,PACKET_INDICATION,};staticstruct{e
numpacket_type_ttype;constchar*name;void(*handler)(structnhrp_packet_parser*);}p
acket_types[]={[0]={.type=PACKET_UNKNOWN,.name="UNKNOWN",},[NHRP_PACKET_RESOLUTI
ON_REQUEST]={.type=PACKET_REQUEST,.name="Resolution-Request",.handler=nhrp_handl
e_resolution_req,},[NHRP_PACKET_RESOLUTION_REPLY]={.type=PACKET_REPLY,.name="Res
olution-Reply",},[NHRP_PACKET_REGISTRATION_REQUEST]={.type=PACKET_REQUEST,.name=
"Registration-Request",.handler=nhrp_handle_registration_request,},[NHRP_PACKET_
REGISTRATION_REPLY]={.type=PACKET_REPLY,.name="Registration-Reply",},[NHRP_PACKE
T_PURGE_REQUEST]={.type=PACKET_REQUEST,.name="Purge-Request",},[NHRP_PACKET_PURG
E_REPLY]={.type=PACKET_REPLY,.name="Purge-Reply",},[NHRP_PACKET_ERROR_INDICATION
]={.type=PACKET_INDICATION,.name="Error-Indication",.handler=nhrp_handle_error_i
nd,},[NHRP_PACKET_TRAFFIC_INDICATION]={.type=PACKET_INDICATION,.name="Traffic-In
dication",.handler=nhrp_handle_traffic_ind,}};staticvoidnhrp_peer_forward(struct
nhrp_peer*p,structnhrp_packet_parser*pp){structzbuf*zb,extpl;structnhrp_packet_h
eader*hdr;structnhrp_extension_header*ext,*dst;structnhrp_cie_header*cie;structn
hrp_interface*nifp=pp->ifp->info;structnhrp_afi_data*if_ad=pp->if_ad;unionsockun
ioncie_nbma,cie_protocol;uint16_ttype,len;if(pp->hdr->hop_count==0)return;/*Crea
teforwardpacket-copyheader*/zb=zbuf_alloc(1500);hdr=nhrp_packet_push(zb,pp->hdr-
>type,&pp->src_nbma,&pp->src_proto,&pp->dst_proto);hdr->flags=pp->hdr->flags;hdr
->hop_count=pp->hdr->hop_count-1;hdr->u.request_id=pp->hdr->u.request_id;/*Copyp
ayload*/zbuf_copy(zb,&pp->payload,zbuf_used(&pp->payload));/*Copyextensions*/whi
le((ext=nhrp_ext_pull(&pp->extensions,&extpl))!=NULL){type=htons(ext->type)&~NHR
P_EXTENSION_FLAG_COMPULSORY;len=htons(ext->length);if(type==NHRP_EXTENSION_END)b
reak;dst=nhrp_ext_push(zb,hdr,htons(ext->type));if(!dst)gotoerr;switch(type){cas
eNHRP_EXTENSION_FORWARD_TRANSIT_NHS:caseNHRP_EXTENSION_REVERSE_TRANSIT_NHS:zbuf_
put(zb,extpl.head,len);if((type==NHRP_EXTENSION_REVERSE_TRANSIT_NHS)==(packet_ty
pes[hdr->type].type==PACKET_REPLY)){/*CheckNHSlistforforwardingloop*/while((cie=
nhrp_cie_pull(&extpl,pp->hdr,&cie_nbma,&cie_protocol))!=NULL){if(sockunion_same(
&p->vc->remote.nbma,&cie_nbma))gotoerr;}/*Appendourselvestothelist*/cie=nhrp_cie
_push(zb,NHRP_CODE_SUCCESS,&nifp->nbma,&if_ad->addr);if(!cie)gotoerr;cie->holdin
g_time=htons(if_ad->holdtime);}break;default:if(htons(ext->type)&NHRP_EXTENSION_
FLAG_COMPULSORY)/*FIXME:RFCsaystojustcopy,butnot*appendourselvestothetransitNHSl
ist*/gotoerr;/*fallthru*/caseNHRP_EXTENSION_RESPONDER_ADDRESS:/*Supportedcompuls
oryextensions,andany*non-compulsorythatisnotexplicitlyhandled,*shouldbejustcopie
d.*/zbuf_copy(zb,&extpl,len);break;}nhrp_ext_complete(zb,dst);}nhrp_packet_compl
ete(zb,hdr);nhrp_peer_send(p,zb);zbuf_free(zb);return;err:nhrp_packet_debug(pp->
pkt,"FWD-FAIL");zbuf_free(zb);}staticvoidnhrp_packet_debug(structzbuf*zb,constch
ar*dir){charbuf[2][SU_ADDRSTRLEN];unionsockunionsrc_nbma,src_proto,dst_proto;str
uctnhrp_packet_header*hdr;structzbufzhdr;intreply;if(likely(!(debug_flags&NHRP_D
EBUG_COMMON)))return;zbuf_init(&zhdr,zb->buf,zb->tail-zb->buf,zb->tail-zb->buf);
hdr=nhrp_packet_pull(&zhdr,&src_nbma,&src_proto,&dst_proto);sockunion2str(&src_p
roto,buf[0],sizeofbuf[0]);sockunion2str(&dst_proto,buf[1],sizeofbuf[1]);reply=pa
cket_types[hdr->type].type==PACKET_REPLY;debugf(NHRP_DEBUG_COMMON,"%s%s(%d)%s->%
s",dir,packet_types[hdr->type].name?:"Unknown",hdr->type,reply?buf[1]:buf[0],rep
ly?buf[0]:buf[1]);}staticintproto2afi(uint16_tproto){switch(proto){caseETH_P_IP:
returnAFI_IP;caseETH_P_IPV6:returnAFI_IP6;}returnAF_UNSPEC;}structnhrp_route_inf
o{intlocal;structinterface*ifp;structnhrp_vc*vc;};voidnhrp_peer_recv(structnhrp_
peer*p,structzbuf*zb){charbuf[2][SU_ADDRSTRLEN];structnhrp_packet_header*hdr;str
uctnhrp_vc*vc=p->vc;structinterface*ifp=p->ifp;structnhrp_interface*nifp=ifp->in
fo;structnhrp_packet_parserpp;structnhrp_peer*peer=NULL;structnhrp_reqid*reqid;c
onstchar*info=NULL;unionsockunion*target_addr;unsignedpaylen,extoff,extlen,reals
ize;afi_tnbma_afi,proto_afi;debugf(NHRP_DEBUG_KERNEL,"PACKET:Recv%s->%s",sockuni
on2str(&vc->remote.nbma,buf[0],sizeofbuf[0]),sockunion2str(&vc->local.nbma,buf[1
],sizeofbuf[1]));if(!p->online){info="peernotonline";gotodrop;}if(nhrp_packet_ca
lculate_checksum(zb->head,zbuf_used(zb))!=0){info="badchecksum";gotodrop;}realsi
ze=zbuf_used(zb);hdr=nhrp_packet_pull(zb,&pp.src_nbma,&pp.src_proto,&pp.dst_prot
o);if(!hdr){info="corruptheader";gotodrop;}pp.ifp=ifp;pp.pkt=zb;pp.hdr=hdr;pp.pe
er=p;nbma_afi=htons(hdr->afnum);proto_afi=proto2afi(htons(hdr->protocol_type));i
f(hdr->type>NHRP_PACKET_MAX||hdr->version!=NHRP_VERSION_RFC2332||nbma_afi>=AFI_M
AX||proto_afi==AF_UNSPEC||packet_types[hdr->type].type==PACKET_UNKNOWN||htons(hd
r->packet_size)>realsize){zlog_info("From%s:error:packettype%d,version%d,AFI%d,p
roto%x,size%d(realsize%d)",sockunion2str(&vc->remote.nbma,buf[0],sizeofbuf[0]),(
int)hdr->type,(int)hdr->version,(int)nbma_afi,(int)htons(hdr->protocol_type),(in
t)htons(hdr->packet_size),(int)realsize);gotodrop;}pp.if_ad=&((structnhrp_interf
ace*)ifp->info)->afi[proto_afi];extoff=htons(hdr->extension_offset);if(extoff){i
f(extoff>=realsize){info="extofflargerthanpacket";gotodrop;}paylen=extoff-(zb->h
ead-zb->buf);}else{paylen=zbuf_used(zb);}zbuf_init(&pp.payload,zbuf_pulln(zb,pay
len),paylen,paylen);extlen=zbuf_used(zb);zbuf_init(&pp.extensions,zbuf_pulln(zb,
extlen),extlen,extlen);if(!nifp->afi[proto_afi].network_id){info="nhrpnotenabled
";gotodrop;}nhrp_packet_debug(zb,"Recv");/*FIXME:Checkauthenticationhere.Thisext
ensionneedstobe*pre-handled.*//*Figureoutifthisislocal*/target_addr=(packet_type
s[hdr->type].type==PACKET_REPLY)?&pp.src_proto:&pp.dst_proto;if(sockunion_same(&
pp.src_proto,&pp.dst_proto))pp.route_type=NHRP_ROUTE_LOCAL;elsepp.route_type=nhr
p_route_address(pp.ifp,target_addr,&pp.route_prefix,&peer);switch(pp.route_type)
{caseNHRP_ROUTE_LOCAL:nhrp_packet_debug(zb,"!LOCAL");if(packet_types[hdr->type].
type==PACKET_REPLY){reqid=nhrp_reqid_lookup(&nhrp_packet_reqid,htonl(hdr->u.requ
est_id));if(reqid){reqid->cb(reqid,&pp);break;}else{nhrp_packet_debug(zb,"!UNKNO
WN-REQID");/*FIXME:senderror-indication*/}}/*fallthru*//*FIXME:doublecheck,isthi
scorrect?*/caseNHRP_ROUTE_OFF_NBMA:if(packet_types[hdr->type].handler){packet_ty
pes[hdr->type].handler(&pp);break;}break;caseNHRP_ROUTE_NBMA_NEXTHOP:nhrp_peer_f
orward(peer,&pp);break;caseNHRP_ROUTE_BLACKHOLE:break;}drop:if(info){zlog_info("
From%s:error:%s",sockunion2str(&vc->remote.nbma,buf[0],sizeofbuf[0]),info);}if(p
eer)nhrp_peer_unref(peer);zbuf_free(zb);}