/*NHRProutingfunctions*Copyright(c)2014-2015TimoTeräs**Thisfileisfreesoftware:yo
umaycopy,redistributeand/ormodify*itunderthetermsoftheGNUGeneralPublicLicenseasp
ublishedby*theFreeSoftwareFoundation,eitherversion2oftheLicense,or*(atyouroption
)anylaterversion.*/#include"nhrpd.h"#include"table.h"#include"memory.h"#include"
stream.h"#include"log.h"#include"zclient.h"DEFINE_MTYPE_STATIC(NHRPD,NHRP_ROUTE,
"NHRProutingentry")staticstructzclient*zclient;staticstructroute_table*zebra_rib
[AFI_MAX];structroute_info{unionsockunionvia;structinterface*ifp;structinterface
*nhrp_ifp;};staticstructroute_node*nhrp_route_update_get(conststructprefix*p,int
create){structroute_node*rn;afi_tafi=family2afi(PREFIX_FAMILY(p));if(!zebra_rib[
afi])returnNULL;if(create){rn=route_node_get(zebra_rib[afi],p);if(!rn->info){rn-
>info=XCALLOC(MTYPE_NHRP_ROUTE,sizeof(structroute_info));route_lock_node(rn);}re
turnrn;}else{returnroute_node_lookup(zebra_rib[afi],p);}}staticvoidnhrp_route_up
date_put(structroute_node*rn){structroute_info*ri=rn->info;if(!ri->ifp&&!ri->nhr
p_ifp&&sockunion_family(&ri->via)==AF_UNSPEC){XFREE(MTYPE_NHRP_ROUTE,rn->info);r
n->info=NULL;route_unlock_node(rn);}route_unlock_node(rn);}staticvoidnhrp_route_
update_zebra(conststructprefix*p,unionsockunion*nexthop,structinterface*ifp){str
uctroute_node*rn;structroute_info*ri;rn=nhrp_route_update_get(p,(sockunion_famil
y(nexthop)!=AF_UNSPEC)||ifp);if(rn){ri=rn->info;ri->via=*nexthop;ri->ifp=ifp;nhr
p_route_update_put(rn);}}voidnhrp_route_update_nhrp(conststructprefix*p,structin
terface*ifp){structroute_node*rn;structroute_info*ri;rn=nhrp_route_update_get(p,
ifp!=NULL);if(rn){ri=rn->info;ri->nhrp_ifp=ifp;nhrp_route_update_put(rn);}}voidn
hrp_route_announce(intadd,enumnhrp_cache_typetype,conststructprefix*p,structinte
rface*ifp,constunionsockunion*nexthop,uint32_tmtu){structzapi_routeapi;structzap
i_nexthop*api_nh;if(zclient->sock<0)return;memset(&api,0,sizeof(api));api.type=Z
EBRA_ROUTE_NHRP;api.safi=SAFI_UNICAST;api.vrf_id=VRF_DEFAULT;api.prefix=*p;switc
h(type){caseNHRP_CACHE_NEGATIVE:zapi_route_set_blackhole(&api,BLACKHOLE_REJECT);
ifp=NULL;nexthop=NULL;break;caseNHRP_CACHE_DYNAMIC:caseNHRP_CACHE_NHS:caseNHRP_C
ACHE_STATIC:/*Regularroute,sotheseareannounced*tootherroutingdaemons*/break;defa
ult:SET_FLAG(api.flags,ZEBRA_FLAG_FIB_OVERRIDE);break;}SET_FLAG(api.flags,ZEBRA_
FLAG_ALLOW_RECURSION);SET_FLAG(api.message,ZAPI_MESSAGE_NEXTHOP);api.nexthop_num
=1;api_nh=&api.nexthops[0];api_nh->vrf_id=VRF_DEFAULT;switch(api.prefix.family){
caseAF_INET:if(nexthop){api_nh->gate.ipv4=nexthop->sin.sin_addr;api_nh->type=NEX
THOP_TYPE_IPV4;}if(ifp){api_nh->ifindex=ifp->ifindex;if(api_nh->type==NEXTHOP_TY
PE_IPV4)api_nh->type=NEXTHOP_TYPE_IPV4_IFINDEX;elseapi_nh->type=NEXTHOP_TYPE_IFI
NDEX;}break;caseAF_INET6:if(nexthop){api_nh->gate.ipv6=nexthop->sin6.sin6_addr;a
pi_nh->type=NEXTHOP_TYPE_IPV6;}if(ifp){api_nh->ifindex=ifp->ifindex;if(api_nh->t
ype==NEXTHOP_TYPE_IPV6)api_nh->type=NEXTHOP_TYPE_IPV6_IFINDEX;elseapi_nh->type=N
EXTHOP_TYPE_IFINDEX;}break;}if(mtu){SET_FLAG(api.message,ZAPI_MESSAGE_MTU);api.m
tu=mtu;}if(unlikely(debug_flags&NHRP_DEBUG_ROUTE)){charbuf[2][PREFIX_STRLEN];pre
fix2str(&api.prefix,buf[0],sizeof(buf[0]));zlog_debug("Zebrasend:route%s%snextho
p%smetric%u""count%ddev%s",add?"add":"del",buf[0],nexthop?inet_ntop(api.prefix.f
amily,&api_nh->gate,buf[1],sizeof(buf[1])):"<onlink>",api.metric,api.nexthop_num
,ifp?ifp->name:"none");}zclient_route_send(add?ZEBRA_ROUTE_ADD:ZEBRA_ROUTE_DELET
E,zclient,&api);}intnhrp_route_read(intcmd,structzclient*zclient,zebra_size_tlen
gth,vrf_id_tvrf_id){structzapi_routeapi;structzapi_nexthop*api_nh;structinterfac
e*ifp=NULL;unionsockunionnexthop_addr;charbuf[2][PREFIX_STRLEN];intadded;if(zapi
_route_decode(zclient->ibuf,&api)<0)return-1;/*wecompletelyignoresrcdestroutesfo
rnow.*/if(CHECK_FLAG(api.message,ZAPI_MESSAGE_SRCPFX))return0;sockunion_family(&
nexthop_addr)=AF_UNSPEC;if(CHECK_FLAG(api.message,ZAPI_MESSAGE_NEXTHOP)){api_nh=
&api.nexthops[0];nexthop_addr.sa.sa_family=api.prefix.family;switch(nexthop_addr
.sa.sa_family){caseAF_INET:nexthop_addr.sin.sin_addr=api_nh->gate.ipv4;break;cas
eAF_INET6:nexthop_addr.sin6.sin6_addr=api_nh->gate.ipv6;break;}if(api_nh->ifinde
x!=IFINDEX_INTERNAL)ifp=if_lookup_by_index(api_nh->ifindex,VRF_DEFAULT);}added=(
cmd==ZEBRA_REDISTRIBUTE_ROUTE_ADD);debugf(NHRP_DEBUG_ROUTE,"if-route-%s:%svia%sd
ev%s",added?"add":"del",prefix2str(&api.prefix,buf[0],sizeofbuf[0]),sockunion2st
r(&nexthop_addr,buf[1],sizeofbuf[1]),ifp?ifp->name:"(none)");nhrp_route_update_z
ebra(&api.prefix,&nexthop_addr,ifp);nhrp_shortcut_prefix_change(&api.prefix,!add
ed);return0;}intnhrp_route_get_nexthop(constunionsockunion*addr,structprefix*p,u
nionsockunion*via,structinterface**ifp){structroute_node*rn;structroute_info*ri;
structprefixlookup;afi_tafi=family2afi(sockunion_family(addr));charbuf[PREFIX_ST
RLEN];sockunion2hostprefix(addr,&lookup);rn=route_node_match(zebra_rib[afi],&loo
kup);if(!rn)return0;ri=rn->info;if(ri->nhrp_ifp){debugf(NHRP_DEBUG_ROUTE,"lookup
%s:nhrp_if=%s",prefix2str(&lookup,buf,sizeofbuf),ri->nhrp_ifp->name);if(via)sock
union_family(via)=AF_UNSPEC;if(ifp)*ifp=ri->nhrp_ifp;}else{debugf(NHRP_DEBUG_ROU
TE,"lookup%s:zebraroutedev%s",prefix2str(&lookup,buf,sizeofbuf),ri->ifp?ri->ifp-
>name:"(none)");if(via)*via=ri->via;if(ifp)*ifp=ri->ifp;}if(p)*p=rn->p;route_unl
ock_node(rn);return1;}enumnhrp_route_typenhrp_route_address(structinterface*in_i
fp,unionsockunion*addr,structprefix*p,structnhrp_peer**peer){structinterface*ifp
=in_ifp;structnhrp_interface*nifp;structnhrp_cache*c;unionsockunionvia[4];uint32
_tnetwork_id=0;afi_tafi=family2afi(sockunion_family(addr));inti;if(ifp){nifp=ifp
->info;network_id=nifp->afi[afi].network_id;c=nhrp_cache_get(ifp,addr,0);if(c&&c
->cur.type==NHRP_CACHE_LOCAL){if(p)memset(p,0,sizeof(*p));returnNHRP_ROUTE_LOCAL
;}}for(i=0;i<4;i++){if(!nhrp_route_get_nexthop(addr,p,&via[i],&ifp))returnNHRP_R
OUTE_BLACKHOLE;if(ifp){/*Departingfromnbmanetwork?*/nifp=ifp->info;if(network_id
&&network_id!=nifp->afi[afi].network_id)returnNHRP_ROUTE_OFF_NBMA;}if(sockunion_
family(&via[i])==AF_UNSPEC)break;/*Resolvevianode,butreturntheprefixoffirstmatch
*/addr=&via[i];p=NULL;}if(ifp){c=nhrp_cache_get(ifp,addr,0);if(c&&c->cur.type>=N
HRP_CACHE_DYNAMIC){if(p)memset(p,0,sizeof(*p));if(c->cur.type==NHRP_CACHE_LOCAL)
returnNHRP_ROUTE_LOCAL;if(peer)*peer=nhrp_peer_ref(c->cur.peer);returnNHRP_ROUTE
_NBMA_NEXTHOP;}}returnNHRP_ROUTE_BLACKHOLE;}staticvoidnhrp_zebra_connected(struc
tzclient*zclient){zclient_send_reg_requests(zclient,VRF_DEFAULT);zebra_redistrib
ute_send(ZEBRA_REDISTRIBUTE_ADD,zclient,AFI_IP,ZEBRA_ROUTE_ALL,0,VRF_DEFAULT);ze
bra_redistribute_send(ZEBRA_REDISTRIBUTE_ADD,zclient,AFI_IP6,ZEBRA_ROUTE_ALL,0,V
RF_DEFAULT);}voidnhrp_zebra_init(void){zebra_rib[AFI_IP]=route_table_init();zebr
a_rib[AFI_IP6]=route_table_init();zclient=zclient_new_notify(master,&zclient_opt
ions_default);zclient->zebra_connected=nhrp_zebra_connected;zclient->interface_a
dd=nhrp_interface_add;zclient->interface_delete=nhrp_interface_delete;zclient->i
nterface_up=nhrp_interface_up;zclient->interface_down=nhrp_interface_down;zclien
t->interface_address_add=nhrp_interface_address_add;zclient->interface_address_d
elete=nhrp_interface_address_delete;zclient->redistribute_route_add=nhrp_route_r
ead;zclient->redistribute_route_del=nhrp_route_read;zclient_init(zclient,ZEBRA_R
OUTE_NHRP,0,&nhrpd_privs);}voidnhrp_zebra_terminate(void){zclient_stop(zclient);
zclient_free(zclient);route_table_finish(zebra_rib[AFI_IP]);route_table_finish(z
ebra_rib[AFI_IP6]);}