/*NHRPeventmanager*Copyright(c)2014-2015TimoTeräs**Thisfileisfreesoftware:youmay
copy,redistributeand/ormodify*itunderthetermsoftheGNUGeneralPublicLicenseaspubli
shedby*theFreeSoftwareFoundation,eitherversion2oftheLicense,or*(atyouroption)any
laterversion.*/#include<string.h>#include<sys/socket.h>#include<sys/un.h>#includ
e"thread.h"#include"zbuf.h"#include"log.h"#include"nhrpd.h"constchar*nhrp_event_
socket_path;structnhrp_reqid_poolnhrp_event_reqid;structevent_manager{structthre
ad*t_reconnect,*t_read,*t_write;structzbufibuf;structzbuf_queueobuf;intfd;uint8_
tibuf_data[4*1024];};staticintevmgr_reconnect(structthread*t);staticvoidevmgr_co
nnection_error(structevent_manager*evmgr){THREAD_OFF(evmgr->t_read);THREAD_OFF(e
vmgr->t_write);zbuf_reset(&evmgr->ibuf);zbufq_reset(&evmgr->obuf);if(evmgr->fd>=
0)close(evmgr->fd);evmgr->fd=-1;if(nhrp_event_socket_path)thread_add_timer_msec(
master,evmgr_reconnect,evmgr,10,&evmgr->t_reconnect);}staticvoidevmgr_recv_messa
ge(structevent_manager*evmgr,structzbuf*zb){structzbufzl;uint32_teventid=0;size_
tlen;charbuf[256],result[64]="";while(zbuf_may_pull_until(zb,"\n",&zl)){len=zbuf
_used(&zl)-1;if(len>=sizeof(buf)-1)continue;memcpy(buf,zbuf_pulln(&zl,len),len);
buf[len]=0;debugf(NHRP_DEBUG_EVENT,"evmgr:msg:%s",buf);if(sscanf(buf,"eventid=%d
",&eventid)!=1)continue;if(sscanf(buf,"result=%63s",result)!=1)continue;}debugf(
NHRP_DEBUG_EVENT,"evmgr:received:eventid=%dresult=%s",eventid,result);if(eventid
&&result[0]){structnhrp_reqid*r=nhrp_reqid_lookup(&nhrp_event_reqid,eventid);if(
r)r->cb(r,result);}}staticintevmgr_read(structthread*t){structevent_manager*evmg
r=THREAD_ARG(t);structzbuf*ibuf=&evmgr->ibuf;structzbufmsg;evmgr->t_read=NULL;if
(zbuf_read(ibuf,evmgr->fd,(size_t)-1)<0){evmgr_connection_error(evmgr);return0;}
/*Processallmessagesinbuffer*/while(zbuf_may_pull_until(ibuf,"\n\n",&msg))evmgr_
recv_message(evmgr,&msg);thread_add_read(master,evmgr_read,evmgr,evmgr->fd,&evmg
r->t_read);return0;}staticintevmgr_write(structthread*t){structevent_manager*evm
gr=THREAD_ARG(t);intr;evmgr->t_write=NULL;r=zbufq_write(&evmgr->obuf,evmgr->fd);
if(r>0){thread_add_write(master,evmgr_write,evmgr,evmgr->fd,&evmgr->t_write);}el
seif(r<0){evmgr_connection_error(evmgr);}return0;}staticvoidevmgr_hexdump(struct
zbuf*zb,constuint8_t*val,size_tvallen){staticconstcharxd[]="0123456789abcdef";si
ze_ti;char*ptr;ptr=zbuf_pushn(zb,2*vallen);if(!ptr)return;for(i=0;i<vallen;i++){
uint8_tb=val[i];*(ptr++)=xd[b>>4];*(ptr++)=xd[b&0xf];}}staticvoidevmgr_put(struc
tzbuf*zb,constchar*fmt,...){constchar*pos,*nxt,*str;constuint8_t*bin;constunions
ockunion*su;intlen;va_listva;va_start(va,fmt);for(pos=fmt;(nxt=strchr(pos,'%'))!
=NULL;pos=nxt+2){zbuf_put(zb,pos,nxt-pos);switch(nxt[1]){case'%':zbuf_put8(zb,'%
');break;case'u':zb->tail+=snprintf((char*)zb->tail,zbuf_tailroom(zb),"%u",va_ar
g(va,uint32_t));break;case's':str=va_arg(va,constchar*);zbuf_put(zb,str,strlen(s
tr));break;case'U':su=va_arg(va,constunionsockunion*);if(sockunion2str(su,(char*
)zb->tail,zbuf_tailroom(zb)))zb->tail+=strlen((char*)zb->tail);elsezbuf_set_werr
or(zb);break;case'H':bin=va_arg(va,constuint8_t*);len=va_arg(va,int);evmgr_hexdu
mp(zb,bin,len);break;}}va_end(va);zbuf_put(zb,pos,strlen(pos));}staticvoidevmgr_
submit(structevent_manager*evmgr,structzbuf*obuf){if(obuf->error){zbuf_free(obuf
);return;}zbuf_put(obuf,"\n",1);zbufq_queue(&evmgr->obuf,obuf);if(evmgr->fd>=0)t
hread_add_write(master,evmgr_write,evmgr,evmgr->fd,&evmgr->t_write);}staticintev
mgr_reconnect(structthread*t){structevent_manager*evmgr=THREAD_ARG(t);intfd;evmg
r->t_reconnect=NULL;if(evmgr->fd>=0||!nhrp_event_socket_path)return0;fd=sock_ope
n_unix(nhrp_event_socket_path);if(fd<0){zlog_warn("%s:failureconnectingnhrp-even
tsocket:%s",__PRETTY_FUNCTION__,strerror(errno));zbufq_reset(&evmgr->obuf);threa
d_add_timer(master,evmgr_reconnect,evmgr,10,&evmgr->t_reconnect);return0;}zlog_i
nfo("ConnectedtoEventManager");evmgr->fd=fd;thread_add_read(master,evmgr_read,ev
mgr,evmgr->fd,&evmgr->t_read);return0;}staticstructevent_managerevmgr_connection
;voidevmgr_init(void){structevent_manager*evmgr=&evmgr_connection;evmgr->fd=-1;z
buf_init(&evmgr->ibuf,evmgr->ibuf_data,sizeof(evmgr->ibuf_data),0);zbufq_init(&e
vmgr->obuf);thread_add_timer_msec(master,evmgr_reconnect,evmgr,10,&evmgr->t_reco
nnect);}voidevmgr_set_socket(constchar*socket){if(nhrp_event_socket_path){free((
char*)nhrp_event_socket_path);nhrp_event_socket_path=NULL;}if(socket)nhrp_event_
socket_path=strdup(socket);evmgr_connection_error(&evmgr_connection);}voidevmgr_
terminate(void){}voidevmgr_notify(constchar*name,structnhrp_cache*c,void(*cb)(st
ructnhrp_reqid*,void*)){structevent_manager*evmgr=&evmgr_connection;structnhrp_v
c*vc;structnhrp_interface*nifp=c->ifp->info;structzbuf*zb;afi_tafi=family2afi(so
ckunion_family(&c->remote_addr));if(!nhrp_event_socket_path){cb(&c->eventid,(voi
d*)"accept");return;}debugf(NHRP_DEBUG_EVENT,"evmgr:sendingevent%s",name);vc=c->
new.peer?c->new.peer->vc:NULL;zb=zbuf_alloc(1024+(vc?(vc->local.certlen+vc->remo
te.certlen)*2:0));if(cb){nhrp_reqid_free(&nhrp_event_reqid,&c->eventid);evmgr_pu
t(zb,"eventid=%u\n",nhrp_reqid_alloc(&nhrp_event_reqid,&c->eventid,cb));}evmgr_p
ut(zb,"event=%s\n""type=%s\n""old_type=%s\n""num_nhs=%u\n""interface=%s\n""local
_addr=%U\n",name,nhrp_cache_type_str[c->new.type],nhrp_cache_type_str[c->cur.typ
e],(unsignedint)nhrp_cache_counts[NHRP_CACHE_NHS],c->ifp->name,&nifp->afi[afi].a
ddr);if(vc){evmgr_put(zb,"vc_initiated=%s\n""local_nbma=%U\n""local_cert=%H\n""r
emote_addr=%U\n""remote_nbma=%U\n""remote_cert=%H\n",c->new.peer->requested?"yes
":"no",&vc->local.nbma,vc->local.cert,vc->local.certlen,&c->remote_addr,&vc->rem
ote.nbma,vc->remote.cert,vc->remote.certlen);}evmgr_submit(evmgr,zb);}