/* confdefs.h */
#define PACKAGE_NAME "Quagga"
#define PACKAGE_TARNAME "quagga"
#define PACKAGE_VERSION "0.99.24+cl3u4"
#define PACKAGE_STRING "Quagga 0.99.24+cl3u4"
#define PACKAGE_BUGREPORT "https://bugzilla.quagga.net"
#define PACKAGE_URL ""
#define PACKAGE "quagga"
#define VERSION "0.99.24+cl3u4"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define __EXTENSIONS__ 1
#define _ALL_SOURCE 1
#define _GNU_SOURCE 1
#define _POSIX_PTHREAD_SEMANTICS 1
#define _TANDEM_SOURCE 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define HAVE_JSON_C_JSON_H 1
#define CONSUMED_TIME_CHECK 5000000
#define HAVE_V6_RR_SEMANTICS /**/
#define HAVE_RTADV /**/
#define QUAGGA_USER "quagga"
#define QUAGGA_GROUP "quagga"
#define CONFIGFILE_MASK 0600
#define LOGFILE_MASK 0600
#define MULTIPATH_NUM 4
#define restrict __restrict
#define STDC_HEADERS 1
#define TIME_WITH_SYS_TIME 1
#define HAVE_SYS_WAIT_H 1
#define HAVE__BOOL 1
#define HAVE_STDBOOL_H 1
#define HAVE_STROPTS_H 1
#define HAVE_SYS_TIMES_H 1
#define HAVE_SYS_SELECT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_LINUX_VERSION_H 1
#define HAVE_NETDB_H 1
#define HAVE_ASM_TYPES_H 1
#define HAVE_SYS_CDEFS_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_LIMITS_H 1
#define HAVE_SIGNAL_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_NETINET_IN_H 1
#define HAVE_TIME_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_NET_IF_H 1
#define HAVE_SYS_UN_H 1
#define HAVE_NETINET_IN_SYSTM_H 1
#define HAVE_NET_ROUTE_H 1
#define HAVE_ARPA_INET_H 1
#define HAVE_NETINET_IP_ICMP_H 1
#define HAVE_FCNTL_H 1
#define HAVE_STDDEF_H 1
#define HAVE_SYS_IOCTL_H 1
#define HAVE_SYSLOG_H 1
#define HAVE_WCHAR_H 1
#define HAVE_WCTYPE_H 1
#define HAVE_SYS_SYSCTL_H 1
#define HAVE_UCONTEXT_H 1
#define HAVE_UCONTEXT_T_UC_MCONTEXT_GREGS 1
#define GNU_LINUX /**/
#define VTYSH /**/
