#! /bin/sh
#
# When local system does not have the latest autoconf/automake
#        -- Kunihiro Ishiguro <kunihiro@zebra.org>
#
rm -f config.cache Makefile.in aclocal.m4 config.h.in configure
rm -rf autom4te.cache
aclocal
autoheader
autoconf
libtoolize
automake --foreign
