/**EIGRPMainRoutine.*Copyright(C)2013-2015*Authors:*DonnieSavage*JanJanovic*Mate
jPerina*PeterOrsag*PeterPaluch*FrantisekGazo*TomasHvorkovy*MartinKontsek*LukasKo
ribsky**ThisfileispartofGNUZebra.**GNUZebraisfreesoftware;youcanredistributeitan
d/ormodifyit*underthetermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftw
areFoundation;eitherversion2,or(atyouroption)any*laterversion.**GNUZebraisdistri
butedinthehopethatitwillbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwar
rantyof*MERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLic
enseformoredetails.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong
*withthisprogram;seethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,
51FranklinSt,FifthFloor,Boston,MA02110-1301USA*/#include<zebra.h>#include<lib/ve
rsion.h>#include"getopt.h"#include"thread.h"#include"prefix.h"#include"linklist.
h"#include"if.h"#include"vector.h"#include"vty.h"#include"command.h"#include"fil
ter.h"#include"plist.h"#include"stream.h"#include"log.h"#include"memory.h"#inclu
de"privs.h"#include"sigevent.h"#include"zclient.h"#include"keychain.h"#include"d
istribute.h"#include"libfrr.h"#include"routemap.h"//#include"if_rmap.h"#include"
eigrpd/eigrp_structs.h"#include"eigrpd/eigrpd.h"#include"eigrpd/eigrp_dump.h"#in
clude"eigrpd/eigrp_interface.h"#include"eigrpd/eigrp_neighbor.h"#include"eigrpd/
eigrp_packet.h"#include"eigrpd/eigrp_vty.h"#include"eigrpd/eigrp_zebra.h"#includ
e"eigrpd/eigrp_network.h"#include"eigrpd/eigrp_snmp.h"#include"eigrpd/eigrp_filt
er.h"//#include"eigrpd/eigrp_routemap.h"/*eigprdprivileges*/zebra_capabilities_t
_caps_p[]={ZCAP_NET_RAW,ZCAP_BIND,ZCAP_NET_ADMIN,};structzebra_privs_teigrpd_pri
vs={#ifdefined(FRR_USER)&&defined(FRR_GROUP).user=FRR_USER,.group=FRR_GROUP,#end
if#ifdefined(VTY_GROUP).vty_group=VTY_GROUP,#endif.caps_p=_caps_p,.cap_num_p=arr
ay_size(_caps_p),.cap_num_i=0};/*EIGRPdoptions.*/structoptionlongopts[]={{0}};/*
Masterofthreads.*/structthread_master*master;/*SIGHUPhandler.*/staticvoidsighup(
void){zlog_info("SIGHUPreceived");}/*SIGINT/SIGTERMhandler.*/staticvoidsigint(vo
id){zlog_notice("Terminatingonsignal");eigrp_terminate();exit(0);}/*SIGUSR1handl
er.*/staticvoidsigusr1(void){zlog_rotate();}structquagga_signal_teigrp_signals[]
={{.signal=SIGHUP,.handler=&sighup,},{.signal=SIGUSR1,.handler=&sigusr1,},{.sign
al=SIGINT,.handler=&sigint,},{.signal=SIGTERM,.handler=&sigint,},};FRR_DAEMON_IN
FO(eigrpd,EIGRP,.vty_port=EIGRP_VTY_PORT,.proghelp="ImplementationoftheEIGRProut
ingprotocol.",.signals=eigrp_signals,.n_signals=array_size(eigrp_signals),.privs
=&eigrpd_privs,)/*EIGRPdmainroutine.*/intmain(intargc,char**argv,char**envp){frr
_preinit(&eigrpd_di,argc,argv);frr_opt_add("",longopts,"");while(1){intopt;opt=f
rr_getopt(argc,argv,NULL);if(opt==EOF)break;switch(opt){case0:break;default:frr_
help_exit(1);break;}}eigrp_sw_version_initialize();/*EIGRPmasterinit.*/eigrp_mas
ter_init();eigrp_om->master=frr_init();master=eigrp_om->master;vrf_init(NULL,NUL
L,NULL,NULL);/*EIGRPdinit*/eigrp_if_init();eigrp_zebra_init();eigrp_debug_init()
;/*Getconfigurationfile.*//*EIGRPVTYinits*/eigrp_vty_init();keychain_init();eigr
p_vty_show_init();eigrp_vty_if_init();#ifdefHAVE_SNMPeigrp_snmp_init();#endif/*H
AVE_SNMP*//*Accesslistinstall.*/access_list_init();access_list_add_hook(eigrp_di
stribute_update_all_wrapper);access_list_delete_hook(eigrp_distribute_update_all
_wrapper);/*Prefixlistinitialize.*/prefix_list_init();prefix_list_add_hook(eigrp
_distribute_update_all);prefix_list_delete_hook(eigrp_distribute_update_all);/**
XXX:ThisisjusttogettheCLIinstalledtosuppressVTYSHerrors.*RoutemapsinEIGRParenoty
etfunctional.*/route_map_init();/*eigrp_route_map_init();route_map_add_hook(eigr
p_rmap_update);route_map_delete_hook(eigrp_rmap_update);*//*if_rmap_init(EIGRP_N
ODE);if_rmap_hook_add(eigrp_if_rmap_update);if_rmap_hook_delete(eigrp_if_rmap_up
date);*//*Distributelistinstall.*/distribute_list_init(EIGRP_NODE);distribute_li
st_add_hook(eigrp_distribute_update);distribute_list_delete_hook(eigrp_distribut
e_update);frr_config_fork();frr_run(master);/*Notreached.*/return(0);}