/**EIGRPDefinitionofDataStructures.*Copyright(C)2013-2016*Authors:*DonnieSavage*
JanJanovic*MatejPerina*PeterOrsag*PeterPaluch*FrantisekGazo*TomasHvorkovy*Martin
Kontsek*LukasKoribsky**ThisfileispartofGNUZebra.**GNUZebraisfreesoftware;youcanr
edistributeitand/ormodifyit*underthetermsoftheGNUGeneralPublicLicenseaspublished
bythe*FreeSoftwareFoundation;eitherversion2,or(atyouroption)any*laterversion.**G
NUZebraisdistributedinthehopethatitwillbeuseful,but*WITHOUTANYWARRANTY;withoutev
entheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*G
eneralPublicLicenseformoredetails.**YoushouldhavereceivedacopyoftheGNUGeneralPub
licLicensealong*withthisprogram;seethefileCOPYING;ifnot,writetotheFreeSoftware*F
oundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-1301USA*/#ifndef_ZEBRA_EIG
RP_STRUCTS_H_#define_ZEBRA_EIGRP_STRUCTS_H_#include"filter.h"#include"eigrpd/eig
rp_const.h"#include"eigrpd/eigrp_macros.h"/*EIGRPmasterforsystemwideconfiguratio
nandvariables.*/structeigrp_master{/*EIGRPinstance.*/structlist*eigrp;/*EIGRPthr
eadmaster.*/structthread_master*master;/*Zebrainterfacelist.*/structlist*iflist;
/*EIGRPstarttime.*/time_tstart_time;/*VariousEIGRPglobalconfiguration.*/uint8_to
ptions;#defineEIGRP_MASTER_SHUTDOWN(1<<0)/*deferred-shutdown*/};structeigrp_metr
ics{uint32_tdelay;uint32_tbandwidth;unsignedcharmtu[3];uint8_thop_count;uint8_tr
eliability;uint8_tload;uint8_ttag;uint8_tflags;};structeigrp{uint16_tAS;/*Autono
moussystemnumber*/uint16_tvrid;/*VirtualRouterID*/uint8_tk_values[6];/*ArrayforK
valuesconfiguration*/uint8_tvariance;/*Metricvariancemultiplier*/uint8_tmax_path
s;/*Maximumallowedpathsfor1prefix*//*NameofthisEIGRPinstance*/char*name;/*EIGRPR
outerID.*/uint32_trouter_id;/*Configuredautomatically.*/uint32_trouter_id_static
;/*Configuredmanually.*/structlist*eiflist;/*eigrpinterfaces*/uint8_tpassive_int
erface_default;/*passive-interfacedefault*/unsignedintfd;unsignedintmaxsndbuflen
;uint32_tsequence_number;/*GlobalEIGRPsequencenumber*/structstream*ibuf;structli
st*oi_write_q;/*Threads*/structthread*t_write;structthread*t_read;structthread*t
_distribute;/*timerfordistributelist*/structroute_table*networks;/*EIGRPconfigne
tworks.*/structroute_table*topology_table;uint64_tserno;/*Globalserialnumbercoun
terfortopologyentrychanges*/uint64_tserno_last_update;/*Highestserialnumberofinf
ormationsendbylastupdate*/structlist*topology_changes_internalIPV4;structlist*to
pology_changes_externalIPV4;/*Neighborself*/structeigrp_neighbor*neighbor_self;/
*Configuredmetricforredistributedroutes*/structeigrp_metricsdmetric[ZEBRA_ROUTE_
MAX+1];intredistribute;/*Numofredistributedprotocols.*//*Access-list.*/structacc
ess_list*list[EIGRP_FILTER_MAX];/*Prefix-list.*/structprefix_list*prefix[EIGRP_F
ILTER_MAX];/*Route-map.*/structroute_map*routemap[EIGRP_FILTER_MAX];/*Forredistr
ibuteroutemap.*/struct{char*name;structroute_map*map;intmetric_config;uint32_tme
tric;}route_map[ZEBRA_ROUTE_MAX];QOBJ_FIELDS};DECLARE_QOBJ_TYPE(eigrp)structeigr
p_if_params{uint8_tpassive_interface;uint32_tv_hello;uint16_tv_wait;uint8_ttype;
/*typeofinterface*/uint32_tbandwidth;uint32_tdelay;uint8_treliability;uint8_tloa
d;char*auth_keychain;/*Associatedkeychainwithinterface*/intauth_type;/*EIGRPauth
enticationtype*/};enum{MEMBER_ALLROUTERS=0,MEMBER_MAX,};/*EIGRPinterfacestructur
e*/structeigrp_interface{structeigrp_if_paramsparams;/*multicastgrouprefcnts*/bo
olmember_allrouters;/*Thisinterface'sparenteigrpinstance.*/structeigrp*eigrp;/*I
nterfacedatafromzebra.*/structinterface*ifp;/*Packetsendbuffer.*/structeigrp_fif
o*obuf;/*Outputqueue*//*Towhichmulticastgroupsdowecurrentlybelong?*/uint8_tmulti
cast_memberships;/*EIGRPNetworkType.*/uint8_ttype;structprefix*address;/*Interfa
ceprefix*/structconnected*connected;/*Pointertoconnected*//*Neighborinformation.
*/structlist*nbrs;/*EIGRPNeighborList*//*Threads.*/structthread*t_hello;/*timer*
/structthread*t_distribute;/*timerfordistributelist*/inton_write_q;/*Statisticsf
ields.*/uint32_thello_in;/*Hellomessageinputcount.*/uint32_tupdate_in;/*Updateme
ssageinputcount.*/uint32_tquery_in;/*Querrymessageinputcount.*/uint32_treply_in;
/*Replymessageinputcount.*/uint32_thello_out;/*Hellomessageoutputcount.*/uint32_
tupdate_out;/*Updatemessageoutputcount.*/uint32_tquery_out;/*Querymessageoutputc
ount.*/uint32_treply_out;/*Replymessageoutputcount.*/uint32_tsiaQuery_in;uint32_
tsiaQuery_out;uint32_tsiaReply_in;uint32_tsiaReply_out;uint32_tack_out;uint32_ta
ck_in;uint32_tcrypt_seqnum;/*CryptographicSequenceNumber*//*Access-list.*/struct
access_list*list[EIGRP_FILTER_MAX];/*Prefix-list.*/structprefix_list*prefix[EIGR
P_FILTER_MAX];/*Route-map.*/structroute_map*routemap[EIGRP_FILTER_MAX];};/*Deter
minesifitisfirstorlastpacket*whenpacketconsistsofmultiplepacket*chunksbecauseofm
anyrouteTLV*(allwon'tfitintoonepacket)*/enumPacket_part_type{EIGRP_PACKET_PART_N
A,EIGRP_PACKET_PART_FIRST,EIGRP_PACKET_PART_LAST};/*NeighborDataStructure*/struc
teigrp_neighbor{/*Thisneighbor'sparenteigrpinterface.*/structeigrp_interface*ei;
/*EIGRPneighborInformation*/uint8_tstate;/*neigborstatus.*/uint32_trecv_sequence
_number;/*LastreceivedsequenceNumber.*/uint32_tinit_sequence_number;/*Ifpacketis
unacknowledged,wetrytosenditagain16times*/uint8_tretrans_counter;structin_addrsr
c;/*NeighborSrcaddress.*/uint8_tos_rel_major;//systemversion-justforshowuint8_to
s_rel_minor;//systemversion-justforshowuint8_ttlv_rel_major;//eigrpversion-tells
uswhatTLVformatto//useuint8_ttlv_rel_minor;//eigrpversion-tellsuswhatTLVformatto
//useuint8_tK1;uint8_tK2;uint8_tK3;uint8_tK4;uint8_tK5;uint8_tK6;/*Timervalues.*
/uint16_tv_holddown;/*Threads.*/structthread*t_holddown;structthread*t_nbr_send_
gr;/*threadforsendingmultipleGRpacketchunks*/structeigrp_fifo*retrans_queue;stru
cteigrp_fifo*multicast_queue;uint32_tcrypt_seqnum;/*CryptographicSequenceNumber.
*//*prefixesnotreceivedfromneighborduringGracefulrestart*/structlist*nbr_gr_pref
ixes;/*prefixesnotyetsendtoneighborduringGracefulrestart*/structlist*nbr_gr_pref
ixes_send;/*ifpacketisfirstorlastduringGracefulrestart*/enumPacket_part_typenbr_
gr_packet_type;};//-------------------------------------------------------------
--------------------------------------------------------------------------------
structeigrp_packet{structeigrp_packet*next;structeigrp_packet*previous;/*Pointer
todatastream.*/structstream*s;/*IPdestinationaddress.*/structin_addrdst;/*Packet
retransmissionthread*/structthread*t_retrans_timer;/*Packetretransmissioncounter
*/uint8_tretrans_counter;uint32_tsequence_number;/*EIGRPpacketlength.*/uint16_tl
ength;structeigrp_neighbor*nbr;};structeigrp_fifo{structeigrp_packet*head;struct
eigrp_packet*tail;unsignedlongcount;};structeigrp_header{uint8_tversion;uint8_to
pcode;uint16_tchecksum;uint32_tflags;uint32_tsequence;uint32_tack;uint16_tvrid;u
int16_tASNumber;char*tlv[0];}__attribute__((packed));/***GenericTLVtypeusedforpa
cketdecoding.**+-----+------------------+*||||*|Type|Len|Vector|*||||*+-----+---
---------------+*/structeigrp_tlv_hdr_type{uint16_ttype;uint16_tlength;uint8_tva
lue[0];}__attribute__((packed));structTLV_Parameter_Type{uint16_ttype;uint16_tle
ngth;uint8_tK1;uint8_tK2;uint8_tK3;uint8_tK4;uint8_tK5;uint8_tK6;uint16_thold_ti
me;}__attribute__((packed));structTLV_MD5_Authentication_Type{uint16_ttype;uint1
6_tlength;uint16_tauth_type;uint16_tauth_length;uint32_tkey_id;uint32_tkey_seque
nce;uint8_tNullpad[8];uint8_tdigest[EIGRP_AUTH_TYPE_MD5_LEN];}__attribute__((pac
ked));structTLV_SHA256_Authentication_Type{uint16_ttype;uint16_tlength;uint16_ta
uth_type;uint16_tauth_length;uint32_tkey_id;uint32_tkey_sequence;uint8_tNullpad[
8];uint8_tdigest[EIGRP_AUTH_TYPE_SHA256_LEN];}__attribute__((packed));structTLV_
Sequence_Type{uint16_ttype;uint16_tlength;uint8_taddr_length;structin_addr*addre
sses;}__attribute__((packed));structTLV_Next_Multicast_Sequence{uint16_ttype;uin
t16_tlength;uint32_tmulticast_sequence;}__attribute__((packed));structTLV_Softwa
re_Type{uint16_ttype;uint16_tlength;uint8_tvender_major;uint8_tvender_minor;uint
8_teigrp_major;uint8_teigrp_minor;}__attribute__((packed));structTLV_IPv4_Intern
al_type{uint16_ttype;uint16_tlength;structin_addrforward;/*Metrics*/structeigrp_
metricsmetric;uint8_tprefix_length;unsignedchardestination_part[4];structin_addr
destination;}__attribute__((packed));structTLV_IPv4_External_type{uint16_ttype;u
int16_tlength;structin_addrnext_hop;structin_addroriginating_router;uint32_torig
inating_as;uint32_tadministrative_tag;uint32_texternal_metric;uint16_treserved;u
int8_texternal_protocol;uint8_texternal_flags;/*Metrics*/structeigrp_metricsmetr
ic;uint8_tprefix_length;unsignedchardestination_part[4];structin_addrdestination
;}__attribute__((packed));/*EIGRPPeerTerminationTLV-usedforhardrestart*/structTL
V_Peer_Termination_type{uint16_ttype;uint16_tlength;uint8_tunknown;uint32_tneigh
bor_ip;}__attribute__((packed));/*WhoexecutedGracefulrestart*/enumGR_type{EIGRP_
GR_MANUAL,EIGRP_GR_FILTER};//---------------------------------------------------
--------------------------------------------------------------------------------
----------/*EIGRPTopologytablenodestructure*/structeigrp_prefix_entry{structlist
*entries,*rij;uint32_tfdistance;//FDuint32_trdistance;//RDuint32_tdistance;//Dst
ructeigrp_metricsreported_metric;//RDforsendinguint8_tnt;//networktypeuint8_tsta
te;//routefsmstateuint8_taf;//addressfamilyuint8_treq_action;//requiredactionstr
uctprefix*destination;//IfnetworktypeisREMOTE_EXTERNAL,pointerwillhavereferencet
o//itsexternalTLVstructTLV_IPv4_External_type*extTLV;uint64_tserno;/*Serialnumbe
rforthisentry.Increasedwitheachchangeofentry*/};/*EIGRPTopologytablerecordstruct
ure*/structeigrp_nexthop_entry{structeigrp_prefix_entry*prefix;uint32_treported_
distance;//distancereportedbyneighboruint32_tdistance;//sumofreporteddistanceand
linkcostto//advertisedneighborstructeigrp_metricsreported_metric;structeigrp_met
ricstotal_metric;structeigrp_neighbor*adv_router;//ipaddressofadvertisingneighbo
ruint8_tflags;//usedformarkingsuccessorandFSstructeigrp_interface*ei;//pointerfo
rcaseofconnectedentry};//-------------------------------------------------------
--------------------------------------------------------------------------------
------typedefenum{EIGRP_CONNECTED,EIGRP_INT,EIGRP_EXT,}msg_data_t;/*EIGRPFiniteS
tateMachine*/structeigrp_fsm_action_message{uint8_tpacket_type;//UPDATE,QUERY,SI
AQUERY,SIAREPLYstructeigrp*eigrp;//whichthreadsentmesgstructeigrp_neighbor*adv_r
outer;//advertisingneighborstructeigrp_nexthop_entry*entry;structeigrp_prefix_en
try*prefix;msg_data_tdata_type;//internalorexternaltlvtypestructeigrp_metricsmet
rics;enummetric_changechange;};#endif/*_ZEBRA_EIGRP_STRUCTURES_H_*/