/**EIGRPdFiniteStateMachine(DUAL).*Copyright(C)2013-2014*Authors:*DonnieSavage*J
anJanovic*MatejPerina*PeterOrsag*PeterPaluch**ThisfileispartofGNUZebra.**GNUZebr
aisfreesoftware;youcanredistributeitand/ormodifyit*underthetermsoftheGNUGeneralP
ublicLicenseaspublishedbythe*FreeSoftwareFoundation;eitherversion2,or(atyouropti
on)any*laterversion.**GNUZebraisdistributedinthehopethatitwillbeuseful,but*WITHO
UTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTIC
ULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldhavereceived
acopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;ifnot,w
ritetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-130
1USA**Thisfilecontainsfunctionsforexecutinglogicoffinitestatemachine**+---------
---+*|(7)|*|v*+=====================================+*||*|Passive|*||*+=========
============================+*^|^^^|*(3)||(1)||(1)||*|(0)||(3)||(2)|*|||||+-----
----------+*|||||\*+--------+|||+-----------------+\*///|\\*///+----+\\*||||||*|
v|||v*+===========+(6)+===========++===========+(6)+===========+*||------->||(5)
||-------->||*||(4)||------>||(4)||*|ACTIVE0|<-------|ACTIVE1||ACTIVE2|<--------
|ACTIVE3*|*+--||+--||+--||+--||*|+===========+|+===========+|+===========+|*+===
========+*|^|(5)|^|^^|^*||+---------|------|------------|----+|||*+-------++----
--++---------++---------+*(7)(7)(7)(7)**0-inputeventotherthanqueryfromsuccessor,
FCnotsatisfied*1-lastreply,FDisreset*2-queryfromsuccessor,FCnotsatisfied*3-lastr
eply,FCsatisfiedwithcurrentvalueofFDij*4-distanceincreasewhileinactivestate*5-qu
eryfromsuccessorwhileinactivestate*6-lastreply,FCnotsatisfiedwithcurrentvalueofF
Dij*7-statenotchanged,usuallybyreceivingnotlastreply*/#include<thread.h>#include
<zebra.h>#include"prefix.h"#include"table.h"#include"memory.h"#include"log.h"#in
clude"linklist.h"#include"vty.h"#include"eigrpd/eigrp_structs.h"#include"eigrpd/
eigrpd.h"#include"eigrpd/eigrp_interface.h"#include"eigrpd/eigrp_neighbor.h"#inc
lude"eigrpd/eigrp_packet.h"#include"eigrpd/eigrp_zebra.h"#include"eigrpd/eigrp_v
ty.h"#include"eigrpd/eigrp_network.h"#include"eigrpd/eigrp_dump.h"#include"eigrp
d/eigrp_topology.h"#include"eigrpd/eigrp_fsm.h"/**Prototypes*/inteigrp_fsm_event
_keep_state(structeigrp_fsm_action_message*);inteigrp_fsm_event_nq_fcn(structeig
rp_fsm_action_message*);inteigrp_fsm_event_q_fcn(structeigrp_fsm_action_message*
);inteigrp_fsm_event_lr(structeigrp_fsm_action_message*);inteigrp_fsm_event_dinc
(structeigrp_fsm_action_message*);inteigrp_fsm_event_lr_fcs(structeigrp_fsm_acti
on_message*);inteigrp_fsm_event_lr_fcn(structeigrp_fsm_action_message*);inteigrp
_fsm_event_qact(structeigrp_fsm_action_message*);//-----------------------------
----------------------------------------/**NSM-fieldoffieldsofstructcontainingon
efunctioneach.*WhichfunctionisuseddependsonactualstateofFSMandoccurred*event(arr
owindiagram).Usage:*NSM[actual/startingstate][occurredevent].func*Functionsaresh
ouldbeexecutedwithinseparatethread.*/struct{int(*func)(structeigrp_fsm_action_me
ssage*);}NSM[EIGRP_FSM_STATE_MAX][EIGRP_FSM_EVENT_MAX]={{//PASSIVESTATE{eigrp_fs
m_event_nq_fcn},/*Event0*/{eigrp_fsm_event_keep_state},/*Event1*/{eigrp_fsm_even
t_q_fcn},/*Event2*/{eigrp_fsm_event_keep_state},/*Event3*/{eigrp_fsm_event_keep_
state},/*Event4*/{eigrp_fsm_event_keep_state},/*Event5*/{eigrp_fsm_event_keep_st
ate},/*Event6*/{eigrp_fsm_event_keep_state},/*Event7*/},{//Active0state{eigrp_fs
m_event_keep_state},/*Event0*/{eigrp_fsm_event_keep_state},/*Event1*/{eigrp_fsm_
event_keep_state},/*Event2*/{eigrp_fsm_event_lr_fcs},/*Event3*/{eigrp_fsm_event_
keep_state},/*Event4*/{eigrp_fsm_event_qact},/*Event5*/{eigrp_fsm_event_lr_fcn},
/*Event6*/{eigrp_fsm_event_keep_state},/*Event7*/},{//Active1state{eigrp_fsm_eve
nt_keep_state},/*Event0*/{eigrp_fsm_event_lr},/*Event1*/{eigrp_fsm_event_keep_st
ate},/*Event2*/{eigrp_fsm_event_keep_state},/*Event3*/{eigrp_fsm_event_dinc},/*E
vent4*/{eigrp_fsm_event_qact},/*Event5*/{eigrp_fsm_event_keep_state},/*Event6*/{
eigrp_fsm_event_keep_state},/*Event7*/},{//Active2state{eigrp_fsm_event_keep_sta
te},/*Event0*/{eigrp_fsm_event_keep_state},/*Event1*/{eigrp_fsm_event_keep_state
},/*Event2*/{eigrp_fsm_event_lr_fcs},/*Event3*/{eigrp_fsm_event_keep_state},/*Ev
ent4*/{eigrp_fsm_event_keep_state},/*Event5*/{eigrp_fsm_event_lr_fcn},/*Event6*/
{eigrp_fsm_event_keep_state},/*Event7*/},{//Active3state{eigrp_fsm_event_keep_st
ate},/*Event0*/{eigrp_fsm_event_lr},/*Event1*/{eigrp_fsm_event_keep_state},/*Eve
nt2*/{eigrp_fsm_event_keep_state},/*Event3*/{eigrp_fsm_event_dinc},/*Event4*/{ei
grp_fsm_event_keep_state},/*Event5*/{eigrp_fsm_event_keep_state},/*Event6*/{eigr
p_fsm_event_keep_state},/*Event7*/},};staticconstchar*packet_type2str(uint8_tpac
ket_type){if(packet_type==EIGRP_OPC_UPDATE)return"Update";if(packet_type==EIGRP_
OPC_REQUEST)return"Request";if(packet_type==EIGRP_OPC_QUERY)return"Query";if(pac
ket_type==EIGRP_OPC_REPLY)return"Reply";if(packet_type==EIGRP_OPC_HELLO)return"H
ello";if(packet_type==EIGRP_OPC_IPXSAP)return"IPXSAP";if(packet_type==EIGRP_OPC_
ACK)return"Ack";if(packet_type==EIGRP_OPC_SIAQUERY)return"SIAQuery";if(packet_ty
pe==EIGRP_OPC_SIAREPLY)return"SIAReply";return"Unknown";}staticconstchar*prefix_
state2str(enumeigrp_fsm_statesstate){switch(state){caseEIGRP_FSM_STATE_PASSIVE:r
eturn"Passive";caseEIGRP_FSM_STATE_ACTIVE_0:return"Activeoij0";caseEIGRP_FSM_STA
TE_ACTIVE_1:return"Activeoij1";caseEIGRP_FSM_STATE_ACTIVE_2:return"Activeoij2";c
aseEIGRP_FSM_STATE_ACTIVE_3:return"Activeoij3";}return"Unknown";}staticconstchar
*fsm_state2str(enumeigrp_fsm_eventsevent){switch(event){caseEIGRP_FSM_KEEP_STATE
:return"KeepStateEvent";caseEIGRP_FSM_EVENT_NQ_FCN:return"NonQueryEventFeasabili
tynotsatisfied";caseEIGRP_FSM_EVENT_LR:return"LastReplyEvent";caseEIGRP_FSM_EVEN
T_Q_FCN:return"QueryEventFeasabilitynotsatisified";caseEIGRP_FSM_EVENT_LR_FCS:re
turn"LastReplyEventFeasabilitysatisified";caseEIGRP_FSM_EVENT_DINC:return"Distan
ceIncreaseEvent";caseEIGRP_FSM_EVENT_QACT:return"QueryfromSuccessorwhileinactive
state";caseEIGRP_FSM_EVENT_LR_FCN:return"LastReplyEvent,Feasibilitynotsatisfied"
;};return"Unknown";}staticconstchar*change2str(enummetric_changechange){switch(c
hange){caseMETRIC_DECREASE:return"Decrease";caseMETRIC_SAME:return"Same";caseMET
RIC_INCREASE:return"Increase";}return"Unknown";}/**Mainfunctioninwhicharemakedec
isionswhicheventoccurred.*msg-argumentoftypestructeigrp_fsm_action_messagecontai
n*detailsaboutwhathappen**Returnnumberofoccurredevent(arrowindiagram).**/statice
numeigrp_fsm_eventseigrp_get_fsm_event(structeigrp_fsm_action_message*msg){//Loa
dingbaseinformationfrommessage//structeigrp*eigrp=msg->eigrp;structeigrp_prefix_
entry*prefix=msg->prefix;structeigrp_nexthop_entry*entry=msg->entry;uint8_tactua
l_state=prefix->state;enummetric_changechange;if(entry==NULL){entry=eigrp_nextho
p_entry_new();entry->adv_router=msg->adv_router;entry->ei=msg->adv_router->ei;en
try->prefix=prefix;msg->entry=entry;}/**Calculateresultantmetricsandinserttocorr
ectposition*inentrieslist*/change=eigrp_topology_update_distance(msg);/*Storefor
displaylater*/msg->change=change;switch(actual_state){caseEIGRP_FSM_STATE_PASSIV
E:{structeigrp_nexthop_entry*head=listnode_head(prefix->entries);if(head->report
ed_distance<prefix->fdistance){returnEIGRP_FSM_KEEP_STATE;}/**ifbestentrydoesn't
satisfyfeasibilityconditionitmeans*movetoactivestate*dependentlyifitwasqueryfrom
successor*/if(msg->packet_type==EIGRP_OPC_QUERY){returnEIGRP_FSM_EVENT_Q_FCN;}el
se{returnEIGRP_FSM_EVENT_NQ_FCN;}break;}caseEIGRP_FSM_STATE_ACTIVE_0:{if(msg->pa
cket_type==EIGRP_OPC_REPLY){structeigrp_nexthop_entry*head=listnode_head(prefix-
>entries);listnode_delete(prefix->rij,entry->adv_router);if(prefix->rij->count)r
eturnEIGRP_FSM_KEEP_STATE;zlog_info("Allreplyreceived\n");if(head->reported_dist
ance<prefix->fdistance){returnEIGRP_FSM_EVENT_LR_FCS;}returnEIGRP_FSM_EVENT_LR_F
CN;}elseif(msg->packet_type==EIGRP_OPC_QUERY&&(entry->flags&EIGRP_NEXTHOP_ENTRY_
SUCCESSOR_FLAG)){returnEIGRP_FSM_EVENT_QACT;}returnEIGRP_FSM_KEEP_STATE;break;}c
aseEIGRP_FSM_STATE_ACTIVE_1:{if(msg->packet_type==EIGRP_OPC_QUERY&&(entry->flags
&EIGRP_NEXTHOP_ENTRY_SUCCESSOR_FLAG)){returnEIGRP_FSM_EVENT_QACT;}elseif(msg->pa
cket_type==EIGRP_OPC_REPLY){listnode_delete(prefix->rij,entry->adv_router);if(ch
ange==METRIC_INCREASE&&(entry->flags&EIGRP_NEXTHOP_ENTRY_SUCCESSOR_FLAG)){return
EIGRP_FSM_EVENT_DINC;}elseif(prefix->rij->count){returnEIGRP_FSM_KEEP_STATE;}els
e{zlog_info("Allreplyreceived\n");returnEIGRP_FSM_EVENT_LR;}}elseif(msg->packet_
type==EIGRP_OPC_UPDATE&&change==METRIC_INCREASE&&(entry->flags&EIGRP_NEXTHOP_ENT
RY_SUCCESSOR_FLAG)){returnEIGRP_FSM_EVENT_DINC;}returnEIGRP_FSM_KEEP_STATE;break
;}caseEIGRP_FSM_STATE_ACTIVE_2:{if(msg->packet_type==EIGRP_OPC_REPLY){structeigr
p_nexthop_entry*head=listnode_head(prefix->entries);listnode_delete(prefix->rij,
entry->adv_router);if(prefix->rij->count){returnEIGRP_FSM_KEEP_STATE;}else{zlog_
info("Allreplyreceived\n");if(head->reported_distance<prefix->fdistance){returnE
IGRP_FSM_EVENT_LR_FCS;}returnEIGRP_FSM_EVENT_LR_FCN;}}returnEIGRP_FSM_KEEP_STATE
;break;}caseEIGRP_FSM_STATE_ACTIVE_3:{if(msg->packet_type==EIGRP_OPC_REPLY){list
node_delete(prefix->rij,entry->adv_router);if(change==METRIC_INCREASE&&(entry->f
lags&EIGRP_NEXTHOP_ENTRY_SUCCESSOR_FLAG)){returnEIGRP_FSM_EVENT_DINC;}elseif(pre
fix->rij->count){returnEIGRP_FSM_KEEP_STATE;}else{zlog_info("Allreplyreceived\n"
);returnEIGRP_FSM_EVENT_LR;}}elseif(msg->packet_type==EIGRP_OPC_UPDATE&&change==
METRIC_INCREASE&&(entry->flags&EIGRP_NEXTHOP_ENTRY_SUCCESSOR_FLAG)){returnEIGRP_
FSM_EVENT_DINC;}returnEIGRP_FSM_KEEP_STATE;break;}}returnEIGRP_FSM_KEEP_STATE;}/
**Functionmadetoexecuteinseparatethread.*LoadargumentfromthreadandexecuteproperN
SMfunction*/inteigrp_fsm_event(structeigrp_fsm_action_message*msg){enumeigrp_fsm
_eventsevent=eigrp_get_fsm_event(msg);zlog_info("EIGRPAS:%dState:%sEvent:%sNetwo
rk:%sPacketType:%sReplyRIJCount:%dchange:%s",msg->eigrp->AS,prefix_state2str(msg
->prefix->state),fsm_state2str(event),eigrp_topology_ip_string(msg->prefix),pack
et_type2str(msg->packet_type),msg->prefix->rij->count,change2str(msg->change));(
*(NSM[msg->prefix->state][event].func))(msg);return1;}/**Functionofevent0.**/int
eigrp_fsm_event_nq_fcn(structeigrp_fsm_action_message*msg){structeigrp*eigrp=msg
->eigrp;structeigrp_prefix_entry*prefix=msg->prefix;structlist*successors=eigrp_
topology_get_successor(prefix);structeigrp_nexthop_entry*ne;assert(successors);/
/IfthisisNULLwehaveshitthebed,funhuh?ne=listnode_head(successors);prefix->state=
EIGRP_FSM_STATE_ACTIVE_1;prefix->rdistance=prefix->distance=prefix->fdistance=ne
->distance;prefix->reported_metric=ne->total_metric;if(eigrp_nbr_count_get()){pr
efix->req_action|=EIGRP_FSM_NEED_QUERY;listnode_add(eigrp->topology_changes_inte
rnalIPV4,prefix);}else{eigrp_fsm_event_lr(msg);//inthecasethattherearenomore//ne
ighborsleft}list_delete_and_null(&successors);return1;}inteigrp_fsm_event_q_fcn(
structeigrp_fsm_action_message*msg){structeigrp*eigrp=msg->eigrp;structeigrp_pre
fix_entry*prefix=msg->prefix;structlist*successors=eigrp_topology_get_successor(
prefix);structeigrp_nexthop_entry*ne;assert(successors);//IfthisisNULLsomebodypo
kedusintheeye.ne=listnode_head(successors);prefix->state=EIGRP_FSM_STATE_ACTIVE_
3;prefix->rdistance=prefix->distance=prefix->fdistance=ne->distance;prefix->repo
rted_metric=ne->total_metric;if(eigrp_nbr_count_get()){prefix->req_action|=EIGRP
_FSM_NEED_QUERY;listnode_add(eigrp->topology_changes_internalIPV4,prefix);}else{
eigrp_fsm_event_lr(msg);//inthecasethattherearenomore//neighborsleft}list_delete
_and_null(&successors);return1;}inteigrp_fsm_event_keep_state(structeigrp_fsm_ac
tion_message*msg){structeigrp_prefix_entry*prefix=msg->prefix;structeigrp_nextho
p_entry*ne=listnode_head(prefix->entries);if(prefix->state==EIGRP_FSM_STATE_PASS
IVE){if(!eigrp_metrics_is_same(prefix->reported_metric,ne->total_metric)){prefix
->rdistance=prefix->fdistance=prefix->distance=ne->distance;prefix->reported_met
ric=ne->total_metric;if(msg->packet_type==EIGRP_OPC_QUERY)eigrp_send_reply(msg->
adv_router,prefix);prefix->req_action|=EIGRP_FSM_NEED_UPDATE;listnode_add((eigrp
_lookup())->topology_changes_internalIPV4,prefix);}eigrp_topology_update_node_fl
ags(prefix);eigrp_update_routing_table(prefix);}if(msg->packet_type==EIGRP_OPC_Q
UERY)eigrp_send_reply(msg->adv_router,prefix);return1;}inteigrp_fsm_event_lr(str
ucteigrp_fsm_action_message*msg){structeigrp*eigrp=msg->eigrp;structeigrp_prefix
_entry*prefix=msg->prefix;structeigrp_nexthop_entry*ne=listnode_head(prefix->ent
ries);prefix->fdistance=prefix->distance=prefix->rdistance=ne->distance;prefix->
reported_metric=ne->total_metric;if(prefix->state==EIGRP_FSM_STATE_ACTIVE_3){str
uctlist*successors=eigrp_topology_get_successor(prefix);assert(successors);//It'
slikeNapoleanandWaterloone=listnode_head(successors);eigrp_send_reply(ne->adv_ro
uter,prefix);list_delete_and_null(&successors);}prefix->state=EIGRP_FSM_STATE_PA
SSIVE;prefix->req_action|=EIGRP_FSM_NEED_UPDATE;listnode_add(eigrp->topology_cha
nges_internalIPV4,prefix);eigrp_topology_update_node_flags(prefix);eigrp_update_
routing_table(prefix);eigrp_update_topology_table_prefix(eigrp->topology_table,p
refix);return1;}inteigrp_fsm_event_dinc(structeigrp_fsm_action_message*msg){stru
ctlist*successors=eigrp_topology_get_successor(msg->prefix);structeigrp_nexthop_
entry*ne;assert(successors);//Trumpandhisbighandsne=listnode_head(successors);ms
g->prefix->state=msg->prefix->state==EIGRP_FSM_STATE_ACTIVE_1?EIGRP_FSM_STATE_AC
TIVE_0:EIGRP_FSM_STATE_ACTIVE_2;msg->prefix->distance=ne->distance;if(!msg->pref
ix->rij->count)(*(NSM[msg->prefix->state][eigrp_get_fsm_event(msg)].func))(msg);
list_delete_and_null(&successors);return1;}inteigrp_fsm_event_lr_fcs(structeigrp
_fsm_action_message*msg){structeigrp*eigrp=msg->eigrp;structeigrp_prefix_entry*p
refix=msg->prefix;structeigrp_nexthop_entry*ne=listnode_head(prefix->entries);pr
efix->state=EIGRP_FSM_STATE_PASSIVE;prefix->distance=prefix->rdistance=ne->dista
nce;prefix->reported_metric=ne->total_metric;prefix->fdistance=prefix->fdistance
>prefix->distance?prefix->distance:prefix->fdistance;if(prefix->state==EIGRP_FSM
_STATE_ACTIVE_2){structlist*successors=eigrp_topology_get_successor(prefix);asse
rt(successors);//Havingaspoonandallyouneedisa//knifene=listnode_head(successors)
;eigrp_send_reply(ne->adv_router,prefix);list_delete_and_null(&successors);}pref
ix->req_action|=EIGRP_FSM_NEED_UPDATE;listnode_add(eigrp->topology_changes_inter
nalIPV4,prefix);eigrp_topology_update_node_flags(prefix);eigrp_update_routing_ta
ble(prefix);eigrp_update_topology_table_prefix(eigrp->topology_table,prefix);ret
urn1;}inteigrp_fsm_event_lr_fcn(structeigrp_fsm_action_message*msg){structeigrp*
eigrp=msg->eigrp;structeigrp_prefix_entry*prefix=msg->prefix;structeigrp_nexthop
_entry*best_successor;structlist*successors=eigrp_topology_get_successor(prefix)
;assert(successors);//Routingwithoutastackprefix->state=prefix->state==EIGRP_FSM
_STATE_ACTIVE_0?EIGRP_FSM_STATE_ACTIVE_1:EIGRP_FSM_STATE_ACTIVE_3;best_successor
=listnode_head(successors);prefix->rdistance=prefix->distance=best_successor->di
stance;prefix->reported_metric=best_successor->total_metric;if(eigrp_nbr_count_g
et()){prefix->req_action|=EIGRP_FSM_NEED_QUERY;listnode_add(eigrp->topology_chan
ges_internalIPV4,prefix);}else{eigrp_fsm_event_lr(msg);//inthecasethatthereareno
more//neighborsleft}list_delete_and_null(&successors);return1;}inteigrp_fsm_even
t_qact(structeigrp_fsm_action_message*msg){structlist*successors=eigrp_topology_
get_successor(msg->prefix);structeigrp_nexthop_entry*ne;assert(successors);//Cat
sandnoDogsne=listnode_head(successors);msg->prefix->state=EIGRP_FSM_STATE_ACTIVE
_2;msg->prefix->distance=ne->distance;list_delete_and_null(&successors);return1;
}