/**EIGRPGeneralSendingandReceivingofEIGRPPackets.*Copyright(C)2013-2014*Authors:
*DonnieSavage*JanJanovic*MatejPerina*PeterOrsag*PeterPaluch**ThisfileispartofGNU
Zebra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodifyit*underthetermso
ftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eitherversion
2,or(atyouroption)any*laterversion.**GNUZebraisdistributedinthehopethatitwillbeu
seful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFI
TNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Yousho
uldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefile
COPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Bos
ton,MA02110-1301USA*/#include<zebra.h>#include"thread.h"#include"memory.h"#inclu
de"linklist.h"#include"vty.h"#include"keychain.h"#include"prefix.h"#include"if.h
"#include"table.h"#include"sockunion.h"#include"stream.h"#include"log.h"#include
"sockopt.h"#include"checksum.h"#include"md5.h"#include"sha256.h"#include"eigrpd/
eigrp_structs.h"#include"eigrpd/eigrpd.h"#include"eigrpd/eigrp_interface.h"#incl
ude"eigrpd/eigrp_neighbor.h"#include"eigrpd/eigrp_packet.h"#include"eigrpd/eigrp
_zebra.h"#include"eigrpd/eigrp_vty.h"#include"eigrpd/eigrp_dump.h"#include"eigrp
d/eigrp_network.h"#include"eigrpd/eigrp_topology.h"#include"eigrpd/eigrp_fsm.h"#
include"eigrpd/eigrp_memory.h"/*PacketTypeString.*/conststructmessageeigrp_packe
t_type_str[]={{EIGRP_OPC_UPDATE,"Update"},{EIGRP_OPC_REQUEST,"Request"},{EIGRP_O
PC_QUERY,"Query"},{EIGRP_OPC_REPLY,"Reply"},{EIGRP_OPC_HELLO,"Hello"},{EIGRP_OPC
_IPXSAP,"IPX-SAP"},{EIGRP_OPC_PROBE,"Probe"},{EIGRP_OPC_ACK,"Ack"},{EIGRP_OPC_SI
AQUERY,"SIAQuery"},{EIGRP_OPC_SIAREPLY,"SIAReply"},{0}};staticunsignedcharzeropa
d[16]={0};/*Forwardfunctionreference*/staticstructstream*eigrp_recv_packet(int,s
tructinterface**,structstream*);staticinteigrp_verify_header(structstream*,struc
teigrp_interface*,structip*,structeigrp_header*);staticinteigrp_check_network_ma
sk(structeigrp_interface*,structin_addr);staticinteigrp_retrans_count_exceeded(s
tructeigrp_packet*ep,structeigrp_neighbor*nbr){return1;}inteigrp_make_md5_digest
(structeigrp_interface*ei,structstream*s,uint8_tflags){structkey*key=NULL;struct
keychain*keychain;unsignedchardigest[EIGRP_AUTH_TYPE_MD5_LEN];MD5_CTXctx;uint8_t
*ibuf;size_tbackup_get,backup_end;structTLV_MD5_Authentication_Type*auth_TLV;ibu
f=s->data;backup_end=s->endp;backup_get=s->getp;auth_TLV=eigrp_authTLV_MD5_new()
;stream_set_getp(s,EIGRP_HEADER_LEN);stream_get(auth_TLV,s,EIGRP_AUTH_MD5_TLV_SI
ZE);stream_set_getp(s,backup_get);keychain=keychain_lookup(ei->params.auth_keych
ain);if(keychain)key=key_lookup_for_send(keychain);else{eigrp_authTLV_MD5_free(a
uth_TLV);returnEIGRP_AUTH_TYPE_NONE;}memset(&ctx,0,sizeof(ctx));MD5Init(&ctx);/*
Generateadigest.Eachsituationneedsdifferenthandling*/if(flags&EIGRP_AUTH_BASIC_H
ELLO_FLAG){MD5Update(&ctx,ibuf,EIGRP_MD5_BASIC_COMPUTE);MD5Update(&ctx,key->stri
ng,strlen(key->string));if(strlen(key->string)<16)MD5Update(&ctx,zeropad,16-strl
en(key->string));}elseif(flags&EIGRP_AUTH_UPDATE_INIT_FLAG){MD5Update(&ctx,ibuf,
EIGRP_MD5_UPDATE_INIT_COMPUTE);}elseif(flags&EIGRP_AUTH_UPDATE_FLAG){MD5Update(&
ctx,ibuf,EIGRP_MD5_BASIC_COMPUTE);MD5Update(&ctx,key->string,strlen(key->string)
);if(strlen(key->string)<16)MD5Update(&ctx,zeropad,16-strlen(key->string));if(ba
ckup_end>(EIGRP_HEADER_LEN+EIGRP_AUTH_MD5_TLV_SIZE)){MD5Update(&ctx,ibuf+(EIGRP_
HEADER_LEN+EIGRP_AUTH_MD5_TLV_SIZE),backup_end-20-(EIGRP_HEADER_LEN+EIGRP_AUTH_M
D5_TLV_SIZE));}}MD5Final(digest,&ctx);/*Appendmd5digesttotheendofthestream.*/mem
cpy(auth_TLV->digest,digest,EIGRP_AUTH_TYPE_MD5_LEN);stream_set_endp(s,EIGRP_HEA
DER_LEN);stream_put(s,auth_TLV,EIGRP_AUTH_MD5_TLV_SIZE);stream_set_endp(s,backup
_end);eigrp_authTLV_MD5_free(auth_TLV);returnEIGRP_AUTH_TYPE_MD5_LEN;}inteigrp_c
heck_md5_digest(structstream*s,structTLV_MD5_Authentication_Type*authTLV,structe
igrp_neighbor*nbr,uint8_tflags){MD5_CTXctx;unsignedchardigest[EIGRP_AUTH_TYPE_MD
5_LEN];unsignedcharorig[EIGRP_AUTH_TYPE_MD5_LEN];structkey*key=NULL;structkeycha
in*keychain;uint8_t*ibuf;size_tbackup_end;structTLV_MD5_Authentication_Type*auth
_TLV;structeigrp_header*eigrph;if(ntohl(nbr->crypt_seqnum)>ntohl(authTLV->key_se
quence)){zlog_warn("interface%s:eigrp_check_md5badsequence%d(expect%d)",IF_NAME(
nbr->ei),ntohl(authTLV->key_sequence),ntohl(nbr->crypt_seqnum));return0;}eigrph=
(structeigrp_header*)s->data;eigrph->checksum=0;auth_TLV=(structTLV_MD5_Authenti
cation_Type*)(s->data+EIGRP_HEADER_LEN);memcpy(orig,auth_TLV->digest,EIGRP_AUTH_
TYPE_MD5_LEN);memset(digest,0,EIGRP_AUTH_TYPE_MD5_LEN);memset(auth_TLV->digest,0
,EIGRP_AUTH_TYPE_MD5_LEN);ibuf=s->data;backup_end=s->endp;keychain=keychain_look
up(nbr->ei->params.auth_keychain);if(keychain)key=key_lookup_for_send(keychain);
if(!key){zlog_warn("Interface%s:Expectedkeyvaluenotfoundinconfig",nbr->ei->ifp->
name);return0;}memset(&ctx,0,sizeof(ctx));MD5Init(&ctx);/*Generateadigest.Eachsi
tuationneedsdifferenthandling*/if(flags&EIGRP_AUTH_BASIC_HELLO_FLAG){MD5Update(&
ctx,ibuf,EIGRP_MD5_BASIC_COMPUTE);MD5Update(&ctx,key->string,strlen(key->string)
);if(strlen(key->string)<16)MD5Update(&ctx,zeropad,16-strlen(key->string));}else
if(flags&EIGRP_AUTH_UPDATE_INIT_FLAG){MD5Update(&ctx,ibuf,EIGRP_MD5_UPDATE_INIT_
COMPUTE);}elseif(flags&EIGRP_AUTH_UPDATE_FLAG){MD5Update(&ctx,ibuf,EIGRP_MD5_BAS
IC_COMPUTE);MD5Update(&ctx,key->string,strlen(key->string));if(strlen(key->strin
g)<16)MD5Update(&ctx,zeropad,16-strlen(key->string));if(backup_end>(EIGRP_HEADER
_LEN+EIGRP_AUTH_MD5_TLV_SIZE)){MD5Update(&ctx,ibuf+(EIGRP_HEADER_LEN+EIGRP_AUTH_
MD5_TLV_SIZE),backup_end-20-(EIGRP_HEADER_LEN+EIGRP_AUTH_MD5_TLV_SIZE));}}MD5Fin
al(digest,&ctx);/*comparethetwo*/if(memcmp(orig,digest,EIGRP_AUTH_TYPE_MD5_LEN)!
=0){zlog_warn("interface%s:eigrp_check_md5checksummismatch",IF_NAME(nbr->ei));re
turn0;}/*saveneighbor'scrypt_seqnum*/nbr->crypt_seqnum=authTLV->key_sequence;ret
urn1;}inteigrp_make_sha256_digest(structeigrp_interface*ei,structstream*s,uint8_
tflags){structkey*key=NULL;structkeychain*keychain;charsource_ip[PREFIX_STRLEN];
unsignedchardigest[EIGRP_AUTH_TYPE_SHA256_LEN];unsignedcharbuffer[1+PLAINTEXT_LE
NGTH+45+1]={0};HMAC_SHA256_CTXctx;void*ibuf;size_tbackup_get,backup_end;structTL
V_SHA256_Authentication_Type*auth_TLV;ibuf=s->data;backup_end=s->endp;backup_get
=s->getp;auth_TLV=eigrp_authTLV_SHA256_new();stream_set_getp(s,EIGRP_HEADER_LEN)
;stream_get(auth_TLV,s,EIGRP_AUTH_SHA256_TLV_SIZE);stream_set_getp(s,backup_get)
;keychain=keychain_lookup(ei->params.auth_keychain);if(keychain)key=key_lookup_f
or_send(keychain);if(!key){zlog_warn("Interface%s:Expectedkeyvaluenotfoundinconf
ig",ei->ifp->name);eigrp_authTLV_SHA256_free(auth_TLV);return0;}inet_ntop(AF_INE
T,&ei->address->u.prefix4,source_ip,PREFIX_STRLEN);memset(&ctx,0,sizeof(ctx));bu
ffer[0]='\n';memcpy(buffer+1,key,strlen(key->string));memcpy(buffer+1+strlen(key
->string),source_ip,strlen(source_ip));HMAC__SHA256_Init(&ctx,buffer,1+strlen(ke
y->string)+strlen(source_ip));HMAC__SHA256_Update(&ctx,ibuf,strlen(ibuf));HMAC__
SHA256_Final(digest,&ctx);/*Puthmac-sha256digesttoit'splace*/memcpy(auth_TLV->di
gest,digest,EIGRP_AUTH_TYPE_SHA256_LEN);stream_set_endp(s,EIGRP_HEADER_LEN);stre
am_put(s,auth_TLV,EIGRP_AUTH_SHA256_TLV_SIZE);stream_set_endp(s,backup_end);eigr
p_authTLV_SHA256_free(auth_TLV);returnEIGRP_AUTH_TYPE_SHA256_LEN;}inteigrp_check
_sha256_digest(structstream*s,structTLV_SHA256_Authentication_Type*authTLV,struc
teigrp_neighbor*nbr,uint8_tflags){return1;}inteigrp_write(structthread*thread){s
tructeigrp*eigrp=THREAD_ARG(thread);structeigrp_header*eigrph;structeigrp_interf
ace*ei;structeigrp_packet*ep;structsockaddr_insa_dst;structipiph;structmsghdrmsg
;structioveciov[2];uint32_tseqno,ack;intret;intflags=0;structlistnode*node;#ifde
fWANT_EIGRP_WRITE_FRAGMENTstaticuint16_tipid=0;#endif/*WANT_EIGRP_WRITE_FRAGMENT
*/#defineEIGRP_WRITE_IPHL_SHIFT2eigrp->t_write=NULL;node=listhead(eigrp->oi_writ
e_q);assert(node);ei=listgetdata(node);assert(ei);#ifdefWANT_EIGRP_WRITE_FRAGMEN
T/*seedipidstaticwithloworderbitsoftime*/if(ipid==0)ipid=(time(NULL)&0xffff);#en
dif/*WANT_EIGRP_WRITE_FRAGMENT*//*Getonepacketfromqueue.*/ep=eigrp_fifo_next(ei-
>obuf);if(!ep){zlog_err("%s:Interface%snopacketonqueue?",__PRETTY_FUNCTION__,ei-
>ifp->name);gotoout;}if(ep->length<EIGRP_HEADER_LEN){zlog_err("%s:Packetjusthasa
header?",__PRETTY_FUNCTION__);eigrp_header_dump((structeigrp_header*)ep->s->data
);eigrp_packet_delete(ei);gotoout;}if(ep->dst.s_addr==htonl(EIGRP_MULTICAST_ADDR
ESS))eigrp_if_ipmulticast(eigrp,ei->address,ei->ifp->ifindex);memset(&iph,0,size
of(structip));memset(&sa_dst,0,sizeof(sa_dst));/**Webuildandschedulepacketstogoo
ut*inthefuture.Inthemeantimewemay*processsomeupdatepacketsfromthe*neighbor,thusm
akingitnecessary*toupdatetheackweareusingfor*thisoutgoingpacket.*/eigrph=(struct
eigrp_header*)STREAM_DATA(ep->s);seqno=ntohl(eigrph->sequence);ack=ntohl(eigrph-
>ack);if(ep->nbr&&(ack!=ep->nbr->recv_sequence_number)){eigrph->ack=htonl(ep->nb
r->recv_sequence_number);ack=ep->nbr->recv_sequence_number;eigrph->checksum=0;ei
grp_packet_checksum(ei,ep->s,ep->length);}sa_dst.sin_family=AF_INET;#ifdefHAVE_S
TRUCT_SOCKADDR_IN_SIN_LENsa_dst.sin_len=sizeof(sa_dst);#endif/*HAVE_STRUCT_SOCKA
DDR_IN_SIN_LEN*/sa_dst.sin_addr=ep->dst;sa_dst.sin_port=htons(0);/*SetDONTROUTEf
lagifdstisunicast.*/if(!IN_MULTICAST(htonl(ep->dst.s_addr)))flags=MSG_DONTROUTE;
iph.ip_hl=sizeof(structip)>>EIGRP_WRITE_IPHL_SHIFT;/*it'dbeverystrangeforheadert
onotbe4byte-wordalignedbut..*/if(sizeof(structip)>(unsignedint)(iph.ip_hl<<EIGRP
_WRITE_IPHL_SHIFT))iph.ip_hl++;/*wepresumesizeofstructipcantoverflowip_hl..*/iph
.ip_v=IPVERSION;iph.ip_tos=IPTOS_PREC_INTERNETCONTROL;iph.ip_len=(iph.ip_hl<<EIG
RP_WRITE_IPHL_SHIFT)+ep->length;#ifdefined(__DragonFly__)/**DragonFly'srawsocket
expectsip_len/ip_offinnetworkbyteorder.*/iph.ip_len=htons(iph.ip_len);#endifiph.
ip_off=0;iph.ip_ttl=EIGRP_IP_TTL;iph.ip_p=IPPROTO_EIGRPIGP;iph.ip_sum=0;iph.ip_s
rc.s_addr=ei->address->u.prefix4.s_addr;iph.ip_dst.s_addr=ep->dst.s_addr;memset(
&msg,0,sizeof(msg));msg.msg_name=(caddr_t)&sa_dst;msg.msg_namelen=sizeof(sa_dst)
;msg.msg_iov=iov;msg.msg_iovlen=2;iov[0].iov_base=(char*)&iph;iov[0].iov_len=iph
.ip_hl<<EIGRP_WRITE_IPHL_SHIFT;iov[1].iov_base=stream_pnt(ep->s);iov[1].iov_len=
ep->length;/*sendfinalfragment(couldbefirst)*/sockopt_iphdrincl_swab_htosys(&iph
);ret=sendmsg(eigrp->fd,&msg,flags);sockopt_iphdrincl_swab_systoh(&iph);if(IS_DE
BUG_EIGRP_TRANSMIT(0,SEND)){eigrph=(structeigrp_header*)STREAM_DATA(ep->s);zlog_
debug("Sending[%s][%d/%d]to[%s]via[%s]ret[%d].",lookup_msg(eigrp_packet_type_str
,eigrph->opcode,NULL),seqno,ack,inet_ntoa(ep->dst),IF_NAME(ei),ret);}if(ret<0)zl
og_warn("***sendmsgineigrp_writefailedto%s,""id%d,off%d,len%d,interface%s,mtu%u:
%s",inet_ntoa(iph.ip_dst),iph.ip_id,iph.ip_off,iph.ip_len,ei->ifp->name,ei->ifp-
>mtu,safe_strerror(errno));/*Nowdeletepacketfromqueue.*/eigrp_packet_delete(ei);
out:if(eigrp_fifo_next(ei->obuf)==NULL){ei->on_write_q=0;list_delete_node(eigrp-
>oi_write_q,node);}/*Ifpacketsstillremaininqueue,callwritethread.*/if(!list_isem
pty(eigrp->oi_write_q)){eigrp->t_write=NULL;thread_add_write(master,eigrp_write,
eigrp,eigrp->fd,&eigrp->t_write);}return0;}/*Startingpointofpacketprocessfunctio
n.*/inteigrp_read(structthread*thread){intret;structstream*ibuf;structeigrp*eigr
p;structeigrp_interface*ei;structip*iph;structeigrp_header*eigrph;structinterfac
e*ifp;structeigrp_neighbor*nbr;uint16_topcode=0;uint16_tlength=0;/*firstofallget
interfacepointer.*/eigrp=THREAD_ARG(thread);/*preparefornextpacket.*/eigrp->t_re
ad=NULL;thread_add_read(master,eigrp_read,eigrp,eigrp->fd,&eigrp->t_read);stream
_reset(eigrp->ibuf);if(!(ibuf=eigrp_recv_packet(eigrp->fd,&ifp,eigrp->ibuf))){/*
ThisrawpacketisknowntobeatleastasbigasitsIP*header.*/return-1;}/*Notethattheresh
ouldnotbealignmentproblemswiththisassignmentbecausethisisatthebeginningofthestre
amdatabuffer.*/iph=(structip*)STREAM_DATA(ibuf);//SubstractIPv4headersizefromEIG
RPPacketitselfif(iph->ip_v==4)length=(iph->ip_len)-20U;/*IPHeaderdump.*/if(IS_DE
BUG_EIGRP_TRANSMIT(0,RECV)&&IS_DEBUG_EIGRP_TRANSMIT(0,PACKET_DETAIL))eigrp_ip_he
ader_dump(iph);/*Notethatsockopt_iphdrincl_swab_systohwascalledin*eigrp_recv_pac
ket.*/if(ifp==NULL){structconnected*c;/*Handlecaseswheretheplatformdoesnotsuppor
tretrievingtheifindex,andalsoplatforms(suchasSolaris8)thatclaimtosupportifindexr
etrievalbutdonot.*/c=if_lookup_address((void*)&iph->ip_src,AF_INET,VRF_DEFAULT);
if(c==NULL)return0;ifp=c->ifp;}/*associatepacketwitheigrpinterface*/ei=ifp->info
;/*eigrp_verify_header()reliesonavalid"ei"andthuscanbecalledonlyafterthechecksbe
lowarepassed.Thesechecksinturnaccessthefieldsofunverified"eigrph"structureforthe
irownpurposesandmustremainveryaccurateindoingthis.*/if(!ei)return0;/*Self-origin
atedpacketshouldbediscardedsilently.*/if(eigrp_if_lookup_by_local_addr(eigrp,NUL
L,iph->ip_src)||(IPV4_ADDR_SAME(&iph->ip_src,&ei->address->u.prefix4))){if(IS_DE
BUG_EIGRP_TRANSMIT(0,RECV))zlog_debug("eigrp_read[%s]:Droppingself-originatedpac
ket",inet_ntoa(iph->ip_src));return0;}/*AdvancefromIPheadertoEIGRPheader(iph->ip
_hlhasbeenverifiedbyeigrp_recv_packet()tobecorrect).*/stream_forward_getp(ibuf,(
iph->ip_hl*4));eigrph=(structeigrp_header*)stream_pnt(ibuf);if(IS_DEBUG_EIGRP_TR
ANSMIT(0,RECV)&&IS_DEBUG_EIGRP_TRANSMIT(0,PACKET_DETAIL))eigrp_header_dump(eigrp
h);//if(MSG_OK!=eigrp_packet_examin(eigrph,stream_get_endp(ibuf)-//stream_get_ge
tp(ibuf)))//return-1;/*Ifincominginterfaceispassiveone,ignoreit.*/if(ei&&eigrp_i
f_is_passive(ei)){charbuf[3][INET_ADDRSTRLEN];if(IS_DEBUG_EIGRP_TRANSMIT(0,RECV)
)zlog_debug("ignoringpacketfromrouter%ssentto%s,""receivedonapassiveinterface,%s
",inet_ntop(AF_INET,&eigrph->vrid,buf[0],sizeof(buf[0])),inet_ntop(AF_INET,&iph-
>ip_dst,buf[1],sizeof(buf[1])),inet_ntop(AF_INET,&ei->address->u.prefix4,buf[2],
sizeof(buf[2])));if(iph->ip_dst.s_addr==htonl(EIGRP_MULTICAST_ADDRESS)){eigrp_if
_set_multicast(ei);}return0;}/*elseitmustbealocaleigrpinterface,checkitwasreceiv
edon*correctlink*/elseif(ei->ifp!=ifp){if(IS_DEBUG_EIGRP_TRANSMIT(0,RECV))zlog_w
arn("Packetfrom[%s]receivedonwronglink%s",inet_ntoa(iph->ip_src),ifp->name);retu
rn0;}/*VerifymoreEIGRPheaderfields.*/ret=eigrp_verify_header(ibuf,ei,iph,eigrph)
;if(ret<0){if(IS_DEBUG_EIGRP_TRANSMIT(0,RECV))zlog_debug("eigrp_read[%s]:Headerc
heckfailed,dropping.",inet_ntoa(iph->ip_src));returnret;}/*calcualtetheeigrppack
etlength,andmovethepountertothestartoftheeigrpTLVs*/opcode=eigrph->opcode;if(IS_
DEBUG_EIGRP_TRANSMIT(0,RECV)){charsrc[PREFIX_STRLEN],dst[PREFIX_STRLEN];strlcpy(
src,inet_ntoa(iph->ip_src),sizeof(src));strlcpy(dst,inet_ntoa(iph->ip_dst),sizeo
f(dst));zlog_debug("Received[%s][%d/%d]length[%u]via[%s]src[%s]dst[%s]",lookup_m
sg(eigrp_packet_type_str,opcode,NULL),ntohl(eigrph->sequence),ntohl(eigrph->ack)
,length,IF_NAME(ei),src,dst);}/*Readrestofthepacketandcalleachsortofpacketroutin
e.*/stream_forward_getp(ibuf,EIGRP_HEADER_LEN);/*Newtestingblockofcodeforhandlin
gAcks*/if(ntohl(eigrph->ack)!=0){structeigrp_packet*ep=NULL;nbr=eigrp_nbr_get(ei
,eigrph,iph);//neighbormustbevalid,eigrp_nbr_getcreatesifnoneexistedassert(nbr);
ep=eigrp_fifo_next(nbr->retrans_queue);if((ep)&&(ntohl(eigrph->ack)==ep->sequenc
e_number)){ep=eigrp_fifo_pop(nbr->retrans_queue);eigrp_packet_free(ep);if((nbr->
state==EIGRP_NEIGHBOR_PENDING)&&(ntohl(eigrph->ack)==nbr->init_sequence_number))
{eigrp_nbr_state_set(nbr,EIGRP_NEIGHBOR_UP);zlog_info("Neighbor(%s)adjacencybeca
mefull",inet_ntoa(nbr->src));nbr->init_sequence_number=0;nbr->recv_sequence_numb
er=ntohl(eigrph->sequence);eigrp_update_send_EOT(nbr);}elseeigrp_send_packet_rel
iably(nbr);}ep=eigrp_fifo_next(nbr->multicast_queue);if(ep){if(ntohl(eigrph->ack
)==ep->sequence_number){ep=eigrp_fifo_pop(nbr->multicast_queue);eigrp_packet_fre
e(ep);if(nbr->multicast_queue->count>0){eigrp_send_packet_reliably(nbr);}}}}swit
ch(opcode){caseEIGRP_OPC_HELLO:eigrp_hello_receive(eigrp,iph,eigrph,ibuf,ei,leng
th);break;caseEIGRP_OPC_PROBE://eigrp_probe_receive(eigrp,iph,eigrph,ibuf,ei,//l
ength);break;caseEIGRP_OPC_QUERY:eigrp_query_receive(eigrp,iph,eigrph,ibuf,ei,le
ngth);break;caseEIGRP_OPC_REPLY:eigrp_reply_receive(eigrp,iph,eigrph,ibuf,ei,len
gth);break;caseEIGRP_OPC_REQUEST://eigrp_request_receive(eigrp,iph,eigrph,ibuf,e
i,//length);break;caseEIGRP_OPC_SIAQUERY:eigrp_query_receive(eigrp,iph,eigrph,ib
uf,ei,length);break;caseEIGRP_OPC_SIAREPLY:eigrp_reply_receive(eigrp,iph,eigrph,
ibuf,ei,length);break;caseEIGRP_OPC_UPDATE:eigrp_update_receive(eigrp,iph,eigrph
,ibuf,ei,length);break;default:zlog_warn("interface%s:EIGRPpacketheadertype%duns
upported",IF_NAME(ei),opcode);break;}return0;}staticstructstream*eigrp_recv_pack
et(intfd,structinterface**ifp,structstream*ibuf){intret;structip*iph;uint16_tip_
len;unsignedintifindex=0;structioveciov;/*Headeranddatabothrequirealignment.*/ch
arbuff[CMSG_SPACE(SOPT_SIZE_CMSG_IFINDEX_IPV4())];structmsghdrmsgh;memset(&msgh,
0,sizeof(structmsghdr));msgh.msg_iov=&iov;msgh.msg_iovlen=1;msgh.msg_control=(ca
ddr_t)buff;msgh.msg_controllen=sizeof(buff);ret=stream_recvmsg(ibuf,fd,&msgh,0,(
EIGRP_PACKET_MAX_LEN+1));if(ret<0){zlog_warn("stream_recvmsgfailed:%s",safe_stre
rror(errno));returnNULL;}if((unsignedint)ret<sizeof(iph))/*retmustbe>0now*/{zlog
_warn("eigrp_recv_packet:discardingruntpacketoflength%d""(ipheadersizeis%u)",ret
,(unsignedint)sizeof(iph));returnNULL;}/*Notethatthereshouldnotbealignmentproble
mswiththisassignmentbecausethisisatthebeginningofthestreamdatabuffer.*/iph=(stru
ctip*)STREAM_DATA(ibuf);sockopt_iphdrincl_swab_systoh(iph);ip_len=iph->ip_len;#i
f!defined(GNU_LINUX)&&(OpenBSD<200311)&&(__FreeBSD_version<1000000)/**Kernelnetw
orkcodetouchesincomingIPheaderparameters,*beforeprotocolspecificprocessing.**1)C
onvertbyteordertohostrepresentation.*-->ip_len,ip_id,ip_off**2)Adjustip_lentostr
ipIPheadersize!*-->IfuserprocessreceivesentireIPpacketviaRAW*socket,itmustconsid
eraddingIPheadersizeto*the"ip_len"fieldof"ip"structure.**Formoredetails,see<neti
net/ip_input.c>.*/ip_len=ip_len+(iph->ip_hl<<2);#endif#ifdefined(__DragonFly__)/
**inDragonFly'srawsocket,ip_len/ip_offareread*innetworkbyteorder.*AsOpenBSD<2003
11adjustip_lentostripIPheadersize!*/ip_len=ntohs(iph->ip_len)+(iph->ip_hl<<2);#e
ndififindex=getsockopt_ifindex(AF_INET,&msgh);*ifp=if_lookup_by_index(ifindex,VR
F_DEFAULT);if(ret!=ip_len){zlog_warn("eigrp_recv_packetreadlengthmismatch:ip_len
is%d,""butrecvmsgreturned%d",ip_len,ret);returnNULL;}returnibuf;}structeigrp_fif
o*eigrp_fifo_new(void){structeigrp_fifo*new;new=XCALLOC(MTYPE_EIGRP_FIFO,sizeof(
structeigrp_fifo));returnnew;}/*Freeeigrppacketfifo.*/voideigrp_fifo_free(struct
eigrp_fifo*fifo){structeigrp_packet*ep;structeigrp_packet*next;for(ep=fifo->head
;ep;ep=next){next=ep->next;eigrp_packet_free(ep);}fifo->head=fifo->tail=NULL;fif
o->count=0;XFREE(MTYPE_EIGRP_FIFO,fifo);}/*Freeeigrpfifoentrieswithoutdestroying
fifoitself*/voideigrp_fifo_reset(structeigrp_fifo*fifo){structeigrp_packet*ep;st
ructeigrp_packet*next;for(ep=fifo->head;ep;ep=next){next=ep->next;eigrp_packet_f
ree(ep);}fifo->head=fifo->tail=NULL;fifo->count=0;}structeigrp_packet*eigrp_pack
et_new(size_tsize,structeigrp_neighbor*nbr){structeigrp_packet*new;new=XCALLOC(M
TYPE_EIGRP_PACKET,sizeof(structeigrp_packet));new->s=stream_new(size);new->retra
ns_counter=0;new->nbr=nbr;returnnew;}voideigrp_send_packet_reliably(structeigrp_
neighbor*nbr){structeigrp_packet*ep;ep=eigrp_fifo_next(nbr->retrans_queue);if(ep
){structeigrp_packet*duplicate;duplicate=eigrp_packet_duplicate(ep,nbr);/*Addpac
kettothetopoftheinterfaceoutputqueue*/eigrp_fifo_push(nbr->ei->obuf,duplicate);/
*Startretransmissiontimer*/thread_add_timer(master,eigrp_unack_packet_retrans,nb
r,EIGRP_PACKET_RETRANS_TIME,&ep->t_retrans_timer);/*Incrementsequencenumbercount
er*/nbr->ei->eigrp->sequence_number++;/*Hookthreadtowritepacket.*/if(nbr->ei->on
_write_q==0){listnode_add(nbr->ei->eigrp->oi_write_q,nbr->ei);nbr->ei->on_write_
q=1;}thread_add_write(master,eigrp_write,nbr->ei->eigrp,nbr->ei->eigrp->fd,&nbr-
>ei->eigrp->t_write);}}/*CalculateEIGRPchecksum*/voideigrp_packet_checksum(struc
teigrp_interface*ei,structstream*s,uint16_tlength){structeigrp_header*eigrph;eig
rph=(structeigrp_header*)STREAM_DATA(s);/*Calculatechecksum.*/eigrph->checksum=i
n_cksum(eigrph,length);}/*MakeEIGRPheader.*/voideigrp_packet_header_init(inttype
,structeigrp*eigrp,structstream*s,uint32_tflags,uint32_tsequence,uint32_tack){st
ructeigrp_header*eigrph;stream_reset(s);eigrph=(structeigrp_header*)STREAM_DATA(
s);eigrph->version=(uint8_t)EIGRP_HEADER_VERSION;eigrph->opcode=(uint8_t)type;ei
grph->checksum=0;eigrph->vrid=htons(eigrp->vrid);eigrph->ASNumber=htons(eigrp->A
S);eigrph->ack=htonl(ack);eigrph->sequence=htonl(sequence);//if(flags==EIGRP_INI
T_FLAG)//eigrph->sequence=htonl(3);eigrph->flags=htonl(flags);if(IS_DEBUG_EIGRP_
TRANSMIT(0,PACKET_DETAIL))zlog_debug("PacketHeaderInitSeq[%u]Ack[%u]",htonl(eigr
ph->sequence),htonl(eigrph->ack));stream_forward_endp(s,EIGRP_HEADER_LEN);}/*Add
newpackettoheadoffifo.*/voideigrp_fifo_push(structeigrp_fifo*fifo,structeigrp_pa
cket*ep){ep->next=fifo->head;ep->previous=NULL;if(fifo->tail==NULL)fifo->tail=ep
;if(fifo->count!=0)fifo->head->previous=ep;fifo->head=ep;fifo->count++;}/*Return
lastfifoentry.*/structeigrp_packet*eigrp_fifo_next(structeigrp_fifo*fifo){return
fifo->tail;}voideigrp_packet_delete(structeigrp_interface*ei){structeigrp_packet
*ep;ep=eigrp_fifo_pop(ei->obuf);if(ep)eigrp_packet_free(ep);}voideigrp_packet_fr
ee(structeigrp_packet*ep){if(ep->s)stream_free(ep->s);THREAD_OFF(ep->t_retrans_t
imer);XFREE(MTYPE_EIGRP_PACKET,ep);ep=NULL;}/*EIGRPHeaderverification.*/staticin
teigrp_verify_header(structstream*ibuf,structeigrp_interface*ei,structip*iph,str
ucteigrp_header*eigrph){/*Checknetworkmask,Silentlydiscarded.*/if(!eigrp_check_n
etwork_mask(ei,iph->ip_src)){zlog_warn("interface%s:eigrp_readnetworkaddressisno
tsame[%s]",IF_NAME(ei),inet_ntoa(iph->ip_src));return-1;}/////*Checkauthenticati
on.Thefunctionhandlesloggingactions,where//required.*///if(!eigrp_check_auth(ei,
eigrph))//return-1;return0;}/*UnboundsocketwillacceptanyRawIPpacketsifprotoismat
ched.Topreventit,comparesrcIPaddressandi/faddresswithmaskingi/fnetworkmask.*/sta
ticinteigrp_check_network_mask(structeigrp_interface*ei,structin_addrip_src){str
uctin_addrmask,me,him;if(ei->type==EIGRP_IFTYPE_POINTOPOINT)return1;masklen2ip(e
i->address->prefixlen,&mask);me.s_addr=ei->address->u.prefix4.s_addr&mask.s_addr
;him.s_addr=ip_src.s_addr&mask.s_addr;if(IPV4_ADDR_SAME(&me,&him))return1;return
0;}inteigrp_unack_packet_retrans(structthread*thread){structeigrp_neighbor*nbr;n
br=(structeigrp_neighbor*)THREAD_ARG(thread);structeigrp_packet*ep;ep=eigrp_fifo
_next(nbr->retrans_queue);if(ep){structeigrp_packet*duplicate;duplicate=eigrp_pa
cket_duplicate(ep,nbr);/*Addpackettothetopoftheinterfaceoutputqueue*/eigrp_fifo_
push(nbr->ei->obuf,duplicate);ep->retrans_counter++;if(ep->retrans_counter==EIGR
P_PACKET_RETRANS_MAX)returneigrp_retrans_count_exceeded(ep,nbr);/*Startretransmi
ssiontimer*/ep->t_retrans_timer=NULL;thread_add_timer(master,eigrp_unack_packet_
retrans,nbr,EIGRP_PACKET_RETRANS_TIME,&ep->t_retrans_timer);/*Hookthreadtowritep
acket.*/if(nbr->ei->on_write_q==0){listnode_add(nbr->ei->eigrp->oi_write_q,nbr->
ei);nbr->ei->on_write_q=1;}thread_add_write(master,eigrp_write,nbr->ei->eigrp,nb
r->ei->eigrp->fd,&nbr->ei->eigrp->t_write);}return0;}inteigrp_unack_multicast_pa
cket_retrans(structthread*thread){structeigrp_neighbor*nbr;nbr=(structeigrp_neig
hbor*)THREAD_ARG(thread);structeigrp_packet*ep;ep=eigrp_fifo_next(nbr->multicast
_queue);if(ep){structeigrp_packet*duplicate;duplicate=eigrp_packet_duplicate(ep,
nbr);/*Addpackettothetopoftheinterfaceoutputqueue*/eigrp_fifo_push(nbr->ei->obuf
,duplicate);ep->retrans_counter++;if(ep->retrans_counter==EIGRP_PACKET_RETRANS_M
AX)returneigrp_retrans_count_exceeded(ep,nbr);/*Startretransmissiontimer*/ep->t_
retrans_timer=NULL;thread_add_timer(master,eigrp_unack_multicast_packet_retrans,
nbr,EIGRP_PACKET_RETRANS_TIME,&ep->t_retrans_timer);/*Hookthreadtowritepacket.*/
if(nbr->ei->on_write_q==0){listnode_add(nbr->ei->eigrp->oi_write_q,nbr->ei);nbr-
>ei->on_write_q=1;}thread_add_write(master,eigrp_write,nbr->ei->eigrp,nbr->ei->e
igrp->fd,&nbr->ei->eigrp->t_write);}return0;}/*Getpacketfromtailoffifo.*/structe
igrp_packet*eigrp_fifo_pop(structeigrp_fifo*fifo){structeigrp_packet*ep=NULL;ep=
fifo->tail;if(ep){fifo->tail=ep->previous;if(fifo->tail==NULL)fifo->head=NULL;el
sefifo->tail->next=NULL;fifo->count--;}returnep;}structeigrp_packet*eigrp_packet
_duplicate(structeigrp_packet*old,structeigrp_neighbor*nbr){structeigrp_packet*n
ew;new=eigrp_packet_new(nbr->ei->ifp->mtu,nbr);new->length=old->length;new->retr
ans_counter=old->retrans_counter;new->dst=old->dst;new->sequence_number=old->seq
uence_number;stream_copy(new->s,old->s);returnnew;}staticstructTLV_IPv4_Internal
_type*eigrp_IPv4_InternalTLV_new(){structTLV_IPv4_Internal_type*new;new=XCALLOC(
MTYPE_EIGRP_IPV4_INT_TLV,sizeof(structTLV_IPv4_Internal_type));returnnew;}struct
TLV_IPv4_Internal_type*eigrp_read_ipv4_tlv(structstream*s){structTLV_IPv4_Intern
al_type*tlv;tlv=eigrp_IPv4_InternalTLV_new();tlv->type=stream_getw(s);tlv->lengt
h=stream_getw(s);tlv->forward.s_addr=stream_getl(s);tlv->metric.delay=stream_get
l(s);tlv->metric.bandwidth=stream_getl(s);tlv->metric.mtu[0]=stream_getc(s);tlv-
>metric.mtu[1]=stream_getc(s);tlv->metric.mtu[2]=stream_getc(s);tlv->metric.hop_
count=stream_getc(s);tlv->metric.reliability=stream_getc(s);tlv->metric.load=str
eam_getc(s);tlv->metric.tag=stream_getc(s);tlv->metric.flags=stream_getc(s);tlv-
>prefix_length=stream_getc(s);if(tlv->prefix_length<=8){tlv->destination_part[0]
=stream_getc(s);tlv->destination.s_addr=(tlv->destination_part[0]);}elseif(tlv->
prefix_length>8&&tlv->prefix_length<=16){tlv->destination_part[0]=stream_getc(s)
;tlv->destination_part[1]=stream_getc(s);tlv->destination.s_addr=((tlv->destinat
ion_part[1]<<8)+tlv->destination_part[0]);}elseif(tlv->prefix_length>16&&tlv->pr
efix_length<=24){tlv->destination_part[0]=stream_getc(s);tlv->destination_part[1
]=stream_getc(s);tlv->destination_part[2]=stream_getc(s);tlv->destination.s_addr
=((tlv->destination_part[2]<<16)+(tlv->destination_part[1]<<8)+tlv->destination_
part[0]);}elseif(tlv->prefix_length>24&&tlv->prefix_length<=32){tlv->destination
_part[0]=stream_getc(s);tlv->destination_part[1]=stream_getc(s);tlv->destination
_part[2]=stream_getc(s);tlv->destination_part[3]=stream_getc(s);tlv->destination
.s_addr=((tlv->destination_part[3]<<24)+(tlv->destination_part[2]<<16)+(tlv->des
tination_part[1]<<8)+tlv->destination_part[0]);}returntlv;}uint16_teigrp_add_int
ernalTLV_to_stream(structstream*s,structeigrp_prefix_entry*pe){uint16_tlength;st
ream_putw(s,EIGRP_TLV_IPv4_INT);switch(pe->destination->prefixlen){case0:case1:c
ase2:case3:case4:case5:case6:case7:case8:length=EIGRP_TLV_IPV4_SIZE_GRT_0_BIT;st
ream_putw(s,length);break;case9:case10:case11:case12:case13:case14:case15:case16
:length=EIGRP_TLV_IPV4_SIZE_GRT_8_BIT;stream_putw(s,length);break;case17:case18:
case19:case20:case21:case22:case23:case24:length=EIGRP_TLV_IPV4_SIZE_GRT_16_BIT;
stream_putw(s,length);break;case25:case26:case27:case28:case29:case30:case31:cas
e32:length=EIGRP_TLV_IPV4_SIZE_GRT_24_BIT;stream_putw(s,length);break;default:zl
og_err("%s:Unexpectedprefixlength:%d",__PRETTY_FUNCTION__,pe->destination->prefi
xlen);return0;}stream_putl(s,0x00000000);/*Metric*/stream_putl(s,pe->reported_me
tric.delay);stream_putl(s,pe->reported_metric.bandwidth);stream_putc(s,pe->repor
ted_metric.mtu[2]);stream_putc(s,pe->reported_metric.mtu[1]);stream_putc(s,pe->r
eported_metric.mtu[0]);stream_putc(s,pe->reported_metric.hop_count);stream_putc(
s,pe->reported_metric.reliability);stream_putc(s,pe->reported_metric.load);strea
m_putc(s,pe->reported_metric.tag);stream_putc(s,pe->reported_metric.flags);strea
m_putc(s,pe->destination->prefixlen);stream_putc(s,pe->destination->u.prefix4.s_
addr&0xFF);if(pe->destination->prefixlen>8)stream_putc(s,(pe->destination->u.pre
fix4.s_addr>>8)&0xFF);if(pe->destination->prefixlen>16)stream_putc(s,(pe->destin
ation->u.prefix4.s_addr>>16)&0xFF);if(pe->destination->prefixlen>24)stream_putc(
s,(pe->destination->u.prefix4.s_addr>>24)&0xFF);returnlength;}uint16_teigrp_add_
authTLV_MD5_to_stream(structstream*s,structeigrp_interface*ei){structkey*key;str
uctkeychain*keychain;structTLV_MD5_Authentication_Type*authTLV;authTLV=eigrp_aut
hTLV_MD5_new();authTLV->type=htons(EIGRP_TLV_AUTH);authTLV->length=htons(EIGRP_A
UTH_MD5_TLV_SIZE);authTLV->auth_type=htons(EIGRP_AUTH_TYPE_MD5);authTLV->auth_le
ngth=htons(EIGRP_AUTH_TYPE_MD5_LEN);authTLV->key_sequence=0;memset(authTLV->Null
pad,0,sizeof(authTLV->Nullpad));keychain=keychain_lookup(ei->params.auth_keychai
n);if(keychain)key=key_lookup_for_send(keychain);else{free(ei->params.auth_keych
ain);ei->params.auth_keychain=NULL;eigrp_authTLV_MD5_free(authTLV);return0;}if(k
ey){authTLV->key_id=htonl(key->index);memset(authTLV->digest,0,EIGRP_AUTH_TYPE_M
D5_LEN);stream_put(s,authTLV,sizeof(structTLV_MD5_Authentication_Type));eigrp_au
thTLV_MD5_free(authTLV);returnEIGRP_AUTH_MD5_TLV_SIZE;}eigrp_authTLV_MD5_free(au
thTLV);return0;}uint16_teigrp_add_authTLV_SHA256_to_stream(structstream*s,struct
eigrp_interface*ei){structkey*key;structkeychain*keychain;structTLV_SHA256_Authe
ntication_Type*authTLV;authTLV=eigrp_authTLV_SHA256_new();authTLV->type=htons(EI
GRP_TLV_AUTH);authTLV->length=htons(EIGRP_AUTH_SHA256_TLV_SIZE);authTLV->auth_ty
pe=htons(EIGRP_AUTH_TYPE_SHA256);authTLV->auth_length=htons(EIGRP_AUTH_TYPE_SHA2
56_LEN);authTLV->key_sequence=0;memset(authTLV->Nullpad,0,sizeof(authTLV->Nullpa
d));keychain=keychain_lookup(ei->params.auth_keychain);if(keychain)key=key_looku
p_for_send(keychain);else{free(ei->params.auth_keychain);ei->params.auth_keychai
n=NULL;eigrp_authTLV_SHA256_free(authTLV);return0;}if(key){authTLV->key_id=0;mem
set(authTLV->digest,0,EIGRP_AUTH_TYPE_SHA256_LEN);stream_put(s,authTLV,sizeof(st
ructTLV_SHA256_Authentication_Type));eigrp_authTLV_SHA256_free(authTLV);returnEI
GRP_AUTH_SHA256_TLV_SIZE;}eigrp_authTLV_SHA256_free(authTLV);return0;}structTLV_
MD5_Authentication_Type*eigrp_authTLV_MD5_new(){structTLV_MD5_Authentication_Typ
e*new;new=XCALLOC(MTYPE_EIGRP_AUTH_TLV,sizeof(structTLV_MD5_Authentication_Type)
);returnnew;}voideigrp_authTLV_MD5_free(structTLV_MD5_Authentication_Type*authTL
V){XFREE(MTYPE_EIGRP_AUTH_TLV,authTLV);}structTLV_SHA256_Authentication_Type*eig
rp_authTLV_SHA256_new(){structTLV_SHA256_Authentication_Type*new;new=XCALLOC(MTY
PE_EIGRP_AUTH_SHA256_TLV,sizeof(structTLV_SHA256_Authentication_Type));returnnew
;}voideigrp_authTLV_SHA256_free(structTLV_SHA256_Authentication_Type*authTLV){XF
REE(MTYPE_EIGRP_AUTH_SHA256_TLV,authTLV);}voideigrp_IPv4_InternalTLV_free(struct
TLV_IPv4_Internal_type*IPv4_InternalTLV){XFREE(MTYPE_EIGRP_IPV4_INT_TLV,IPv4_Int
ernalTLV);}structTLV_Sequence_Type*eigrp_SequenceTLV_new(){structTLV_Sequence_Ty
pe*new;new=XCALLOC(MTYPE_EIGRP_SEQ_TLV,sizeof(structTLV_Sequence_Type));returnne
w;}