/**EIGRPSendingandReceivingEIGRPHelloPackets.*Copyright(C)2013-2016*Authors:*Don
nieSavage*JanJanovic*MatejPerina*PeterOrsag*PeterPaluch*FrantisekGazo*TomasHvork
ovy*MartinKontsek*LukasKoribsky**ThisfileispartofGNUZebra.**GNUZebraisfreesoftwa
re;youcanredistributeitand/ormodifyit*underthetermsoftheGNUGeneralPublicLicensea
spublishedbythe*FreeSoftwareFoundation;eitherversion2,or(atyouroption)any*laterv
ersion.**GNUZebraisdistributedinthehopethatitwillbeuseful,but*WITHOUTANYWARRANTY
;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.S
eetheGNU*GeneralPublicLicenseformoredetails.**YoushouldhavereceivedacopyoftheGNU
GeneralPublicLicensealong*withthisprogram;seethefileCOPYING;ifnot,writetotheFree
Software*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-1301USA*/#includ
e<zebra.h>#include"thread.h"#include"memory.h"#include"linklist.h"#include"prefi
x.h"#include"if.h"#include"table.h"#include"sockunion.h"#include"stream.h"#inclu
de"log.h"#include"sockopt.h"#include"checksum.h"#include"vty.h"#include"md5.h"#i
nclude"eigrpd/eigrp_structs.h"#include"eigrpd/eigrpd.h"#include"eigrpd/eigrp_int
erface.h"#include"eigrpd/eigrp_neighbor.h"#include"eigrpd/eigrp_packet.h"#includ
e"eigrpd/eigrp_zebra.h"#include"eigrpd/eigrp_vty.h"#include"eigrpd/eigrp_dump.h"
#include"eigrpd/eigrp_macros.h"/*PacketTypeString.*/staticconststructmessageeigr
p_general_tlv_type_str[]={{EIGRP_TLV_PARAMETER,"PARAMETER"},{EIGRP_TLV_AUTH,"AUT
H"},{EIGRP_TLV_SEQ,"SEQ"},{EIGRP_TLV_SW_VERSION,"SW_VERSION"},{EIGRP_TLV_NEXT_MC
AST_SEQ,"NEXT_MCAST_SEQ"},{EIGRP_TLV_PEER_TERMINATION,"PEER_TERMINATION"},{EIGRP
_TLV_PEER_MTRLIST,"PEER_MTRLIST"},{EIGRP_TLV_PEER_TIDLIST,"PEER_TIDLIST"},{0}};/
**@fneigrp_hello_timer**@param[in]threadcurrentexecutionthreadtimerisassociatedw
ith**@returnintalwaysreturns0**@par*Calledonceper"hello"timeinterval,default5sec
onds*Sendshellopacketviamulticastforallinterfaceseigrp*isconfiguredfor*/inteigrp
_hello_timer(structthread*thread){structeigrp_interface*ei;ei=THREAD_ARG(thread)
;ei->t_hello=NULL;if(IS_DEBUG_EIGRP(0,TIMERS))zlog_debug("StartHelloTimer(%s)Exp
ire[%u]",IF_NAME(ei),ei->params.v_hello);/*Sendinghellopacket.*/eigrp_hello_send
(ei,EIGRP_HELLO_NORMAL,NULL);/*Hellotimerset.*/ei->t_hello=NULL;thread_add_timer
(master,eigrp_hello_timer,ei,ei->params.v_hello,&ei->t_hello);return0;}/***@fnei
grp_hello_parameter_decode**@param[in]nbrneighbortheACKshouldbesentto*@param[in]
parampointerpacketTLVisstoredto**@returnuint16_tnumberofbytesaddedtopacketstream
**@par*EncodeParameterTLV,usedtoconveymetricweightsandtheholdtime.**@usage*Notet
headditionofK6forthenewextendedmetrics,anddoesnotapplyto*olderTLVpacketformats.*
/staticstructeigrp_neighbor*eigrp_hello_parameter_decode(structeigrp_neighbor*nb
r,structeigrp_tlv_hdr_type*tlv){structeigrp*eigrp=nbr->ei->eigrp;structTLV_Param
eter_Type*param=(structTLV_Parameter_Type*)tlv;/*copyoverthevaluespassedinbythen
eighbor*/nbr->K1=param->K1;nbr->K2=param->K2;nbr->K3=param->K3;nbr->K4=param->K4
;nbr->K5=param->K5;nbr->K6=param->K6;nbr->v_holddown=ntohs(param->hold_time);/**
CheckK1-K5havethecorrectvaluestobeabletobecomeneighbors*K6doesnothavetomatch*/if
((eigrp->k_values[0]==nbr->K1)&&(eigrp->k_values[1]==nbr->K2)&&(eigrp->k_values[
2]==nbr->K3)&&(eigrp->k_values[3]==nbr->K4)&&(eigrp->k_values[4]==nbr->K5)){if(e
igrp_nbr_state_get(nbr)==EIGRP_NEIGHBOR_DOWN){zlog_info("Neighbor%s(%s)ispending
:newadjacency",inet_ntoa(nbr->src),ifindex2ifname(nbr->ei->ifp->ifindex,VRF_DEFA
ULT));/*Expeditedhellosent*/eigrp_hello_send(nbr->ei,EIGRP_HELLO_NORMAL,NULL);//
if(ntohl(nbr->ei->address->u.prefix4.s_addr)>//ntohl(nbr->src.s_addr))eigrp_upda
te_send_init(nbr);eigrp_nbr_state_set(nbr,EIGRP_NEIGHBOR_PENDING);}}else{if(eigr
p_nbr_state_get(nbr)!=EIGRP_NEIGHBOR_DOWN){if((param->K1&param->K2&param->K3&par
am->K4&param->K5)==255){zlog_info("Neighbor%s(%s)isdown:InterfacePEER-TERMINATIO
Nreceived",inet_ntoa(nbr->src),ifindex2ifname(nbr->ei->ifp->ifindex,VRF_DEFAULT)
);eigrp_nbr_delete(nbr);returnNULL;}else{zlog_info("Neighbor%s(%s)goingdown:Kval
uemismatch",inet_ntoa(nbr->src),ifindex2ifname(nbr->ei->ifp->ifindex,VRF_DEFAULT
));eigrp_nbr_state_set(nbr,EIGRP_NEIGHBOR_DOWN);}}}returnnbr;}staticuint8_teigrp
_hello_authentication_decode(structstream*s,structeigrp_tlv_hdr_type*tlv_header,
structeigrp_neighbor*nbr){structTLV_MD5_Authentication_Type*md5;md5=(structTLV_M
D5_Authentication_Type*)tlv_header;if(md5->auth_type==EIGRP_AUTH_TYPE_MD5)return
eigrp_check_md5_digest(s,md5,nbr,EIGRP_AUTH_BASIC_HELLO_FLAG);elseif(md5->auth_t
ype==EIGRP_AUTH_TYPE_SHA256)returneigrp_check_sha256_digest(s,(structTLV_SHA256_
Authentication_Type*)tlv_header,nbr,EIGRP_AUTH_BASIC_HELLO_FLAG);return0;}/***@f
neigrp_sw_version_decode**@param[in]nbrneighbortheACKshoudlbesentto*@param[in]pa
rampointertoTLVsoftwareversioninformation**@returnvoid**@par*Readthesoftwarevers
ioninthespecifiedlocation.*ThisconsistsoftwobytesofOSversion,andtwobytesofEIGRP*
revisionnumber.*/staticvoideigrp_sw_version_decode(structeigrp_neighbor*nbr,stru
cteigrp_tlv_hdr_type*tlv){structTLV_Software_Type*version=(structTLV_Software_Ty
pe*)tlv;nbr->os_rel_major=version->vender_major;nbr->os_rel_minor=version->vende
r_minor;nbr->tlv_rel_major=version->eigrp_major;nbr->tlv_rel_minor=version->eigr
p_minor;return;}/***@fneigrp_peer_termination_decode**@param[in]nbrneighbortheAC
Kshoudlbesentto*@param[in]tlvpointertoTLVsoftwareversioninformation**@returnvoid
**@par*ReadtheaddressintheTLVandmatchtooutaddress.If*amatchisfound,movethesendin
gneighbortothedownstate.If*outaddressisnotintheTLV,thenignorethepeertermination*
/staticvoideigrp_peer_termination_decode(structeigrp_neighbor*nbr,structeigrp_tl
v_hdr_type*tlv){structTLV_Peer_Termination_type*param=(structTLV_Peer_Terminatio
n_type*)tlv;uint32_tmy_ip=nbr->ei->address->u.prefix4.s_addr;uint32_treceived_ip
=param->neighbor_ip;if(my_ip==received_ip){zlog_info("Neighbor%s(%s)isdown:PeerT
erminationreceived",inet_ntoa(nbr->src),ifindex2ifname(nbr->ei->ifp->ifindex,VRF
_DEFAULT));/*setneighbortoDOWN*/nbr->state=EIGRP_NEIGHBOR_DOWN;/*deleteneighbor*
/eigrp_nbr_delete(nbr);}}/***@fneigrp_peer_termination_encode**@param[in,out]spa
cketstreamTLVisstoredto*@param[in]nbr_addrpointertoneighboraddressforPeer*Termin
ationTLV**@returnuint16_tnumberofbytesaddedtopacketstream**@par*Functionusedtoen
codePeerTerminationTLVtoHellopacket.*/staticuint16_teigrp_peer_termination_encod
e(structstream*s,structin_addr*nbr_addr){uint16_tlength=EIGRP_TLV_PEER_TERMINATI
ON_LEN;/*fillintypeandlength*/stream_putw(s,EIGRP_TLV_PEER_TERMINATION);stream_p
utw(s,length);/*fillinunknownfield0x04*/stream_putc(s,0x04);/*finallyneighborIPa
ddress*/stream_put_ipv4(s,nbr_addr->s_addr);return(length);}/**@fneigrp_hello_re
ceive**@param[in]eigrpeigrproutingprocess*@param[in]iphpointertoipheader*@param[
in]eigrphpointertoeigrpheader*@param[in]sinputipstream*@param[in]eieigrpinterfac
epacketarrivedon*@param[in]sizesizeofeigrppacket**@returnvoid**@par*Thisisthemai
nworkerfunctionforprocessinghellopackets.It*willvalidatethepeerassociatedwiththe
srcipaddressoftheip*header,andthendecodeeachofthegeneralTLVswhichthepacket*mayco
ntain.**@usage*NotallTLVsarecurrentdecoder.Thisisaworkinprogress..*/voideigrp_he
llo_receive(structeigrp*eigrp,structip*iph,structeigrp_header*eigrph,structstrea
m*s,structeigrp_interface*ei,intsize){structeigrp_tlv_hdr_type*tlv_header;struct
eigrp_neighbor*nbr;uint16_ttype;uint16_tlength;/*getneighborstruct*/nbr=eigrp_nb
r_get(ei,eigrph,iph);/*neighbormustbevalid,eigrp_nbr_getcreatesifnoneexisted*/as
sert(nbr);if(IS_DEBUG_EIGRP_PACKET(eigrph->opcode-1,RECV))zlog_debug("Processing
Hellosize[%u]int(%s)nbr(%s)",size,ifindex2ifname(nbr->ei->ifp->ifindex,VRF_DEFAU
LT),inet_ntoa(nbr->src));size-=EIGRP_HEADER_LEN;if(size<0)return;tlv_header=(str
ucteigrp_tlv_hdr_type*)eigrph->tlv;do{type=ntohs(tlv_header->type);length=ntohs(
tlv_header->length);if((length>0)&&(length<=size)){if(IS_DEBUG_EIGRP_PACKET(0,RE
CV))zlog_debug("GeneralTLV(%s)",lookup_msg(eigrp_general_tlv_type_str,type,NULL)
);//determinewhatGeneralTLVisbeingprocessedswitch(type){caseEIGRP_TLV_PARAMETER:
nbr=eigrp_hello_parameter_decode(nbr,tlv_header);if(!nbr)return;break;caseEIGRP_
TLV_AUTH:{if(eigrp_hello_authentication_decode(s,tlv_header,nbr)==0)return;elseb
reak;break;}caseEIGRP_TLV_SEQ:break;caseEIGRP_TLV_SW_VERSION:eigrp_sw_version_de
code(nbr,tlv_header);break;caseEIGRP_TLV_NEXT_MCAST_SEQ:break;caseEIGRP_TLV_PEER
_TERMINATION:eigrp_peer_termination_decode(nbr,tlv_header);return;break;caseEIGR
P_TLV_PEER_MTRLIST:caseEIGRP_TLV_PEER_TIDLIST:break;default:break;}}tlv_header=(
structeigrp_tlv_hdr_type*)(((char*)tlv_header)+length);size-=length;}while(size>
0);/*IfreceivedpacketishellowithParameterTLV*/if(ntohl(eigrph->ack)==0){/*increm
entstatistics.*/ei->hello_in++;if(nbr)eigrp_nbr_state_update(nbr);}if(IS_DEBUG_E
IGRP_PACKET(0,RECV))zlog_debug("HelloPacketreceivedfrom%s",inet_ntoa(nbr->src));
}uint32_tFRR_MAJOR;uint32_tFRR_MINOR;voideigrp_sw_version_initialize(void){charv
er_string[]=VERSION;char*dash=strstr(ver_string,"-");intret;if(dash)dash[0]='\0'
;ret=sscanf(ver_string,"%d.%d",&FRR_MAJOR,&FRR_MINOR);if(ret!=2)zlog_err("Didnot
Properlyparse%s,pleasefixVERSIONstring",VERSION);}/***@fneigrp_sw_version_encode
**@param[in,out]spacketstreamTLVisstoredto**@returnuint16_tnumberofbytesaddedtop
acketstream**@par*Storethesoftwareversioninthespecifiedlocation.*Thisconsistsoft
wobytesofOSversion,andtwobytesofEIGRP*revisionnumber.*/staticuint16_teigrp_sw_ve
rsion_encode(structstream*s){uint16_tlength=EIGRP_TLV_SW_VERSION_LEN;//setupthet
lvfieldsstream_putw(s,EIGRP_TLV_SW_VERSION);stream_putw(s,length);stream_putc(s,
FRR_MAJOR);//!<majorosversionstream_putc(s,FRR_MINOR);//!<minorosversion/*andthe
coreeigrpversion*/stream_putc(s,EIGRP_MAJOR_VERSION);stream_putc(s,EIGRP_MINOR_V
ERSION);return(length);}/***@fneigrp_tidlist_encode**@param[in,out]spacketstream
TLVisstoredto**@returnvoid**@par*Ifdoingmutli-topology,thenstorethesupportedTIDl
ist.*Thisiscurrentlyaplaceholderfunction*/staticuint16_teigrp_tidlist_encode(str
uctstream*s){//uint16_tlength=EIGRP_TLV_SW_VERSION_LEN;return0;}/***@fneigrp_seq
uence_encode**@param[in,out]spacketstreamTLVisstoredto**@returnuint16_tnumberofb
ytesaddedtopacketstream**@par*Partofconditionalreceiveprocess**/staticuint16_tei
grp_sequence_encode(structstream*s){uint16_tlength=EIGRP_TLV_SEQ_BASE_LEN;struct
eigrp*eigrp;structeigrp_interface*ei;structlistnode*node,*node2,*nnode2;structei
grp_neighbor*nbr;size_tbackup_end,size_end;intfound;eigrp=eigrp_lookup();if(eigr
p==NULL){return0;}//addintheparametersTLVbackup_end=stream_get_endp(s);stream_pu
tw(s,EIGRP_TLV_SEQ);size_end=s->endp;stream_putw(s,0x0000);stream_putc(s,IPV4_MA
X_BYTELEN);found=0;for(ALL_LIST_ELEMENTS_RO(eigrp->eiflist,node,ei)){for(ALL_LIS
T_ELEMENTS(ei->nbrs,node2,nnode2,nbr)){if(nbr->multicast_queue->count>0){length+
=(uint16_t)stream_put_ipv4(s,nbr->src.s_addr);found=1;}}}if(found==0){stream_set
_endp(s,backup_end);return0;}backup_end=stream_get_endp(s);stream_set_endp(s,siz
e_end);stream_putw(s,length);stream_set_endp(s,backup_end);returnlength;}/***@fn
eigrp_sequence_encode**@param[in,out]spacketstreamTLVisstoredto**@returnuint16_t
numberofbytesaddedtopacketstream**@par*Partofconditionalreceiveprocess**/staticu
int16_teigrp_next_sequence_encode(structstream*s){uint16_tlength=EIGRP_NEXT_SEQU
ENCE_TLV_SIZE;structeigrp*eigrp;eigrp=eigrp_lookup();if(eigrp==NULL){return0;}//
addintheparametersTLVstream_putw(s,EIGRP_TLV_NEXT_MCAST_SEQ);stream_putw(s,EIGRP
_NEXT_SEQUENCE_TLV_SIZE);stream_putl(s,eigrp->sequence_number+1);returnlength;}/
***@fneigrp_hello_parameter_encode**@param[in]eipointertointerfacehellopacketcam
einon*@param[in,out]spacketstreamTLVisstoredto**@returnuint16_tnumberofbytesadde
dtopacketstream**@par*EncodeParameterTLV,usedtoconveymetricweightsandtheholdtime
.**@usage*NotetheadditionofK6forthenewextendedmetrics,anddoesnotapplyto*olderTLV
packetformats.*/staticuint16_teigrp_hello_parameter_encode(structeigrp_interface
*ei,structstream*s,uint8_tflags){uint16_tlength=EIGRP_TLV_PARAMETER_LEN;//addint
heparametersTLVstream_putw(s,EIGRP_TLV_PARAMETER);stream_putw(s,EIGRP_TLV_PARAME
TER_LEN);//ifgracefulshutdownisneededtobeannounced,sendall255inK//valuesif(flags
&EIGRP_HELLO_GRACEFUL_SHUTDOWN){stream_putc(s,0xff);/*K1*/stream_putc(s,0xff);/*
K2*/stream_putc(s,0xff);/*K3*/stream_putc(s,0xff);/*K4*/stream_putc(s,0xff);/*K5
*/stream_putc(s,0xff);/*K6*/}else//setkvalues{stream_putc(s,ei->eigrp->k_values[
0]);/*K1*/stream_putc(s,ei->eigrp->k_values[1]);/*K2*/stream_putc(s,ei->eigrp->k
_values[2]);/*K3*/stream_putc(s,ei->eigrp->k_values[3]);/*K4*/stream_putc(s,ei->
eigrp->k_values[4]);/*K5*/stream_putc(s,ei->eigrp->k_values[5]);/*K6*/}//andseth
oldtimevalue..stream_putw(s,ei->params.v_wait);returnlength;}/***@fneigrp_hello_
encode**@param[in]eipointertointerfacehellopacketcameinon*@param[in]spacketstrea
mTLVisstoredto*@param[in]ackifnon-zero,neigborssequencepackettoack*@param[in]fla
gstypeofhellopacket*@param[in]nbr_addrpointertoneighboraddressforPeer*Terminatio
nTLV**@returneigrp_packetpointerinitializehellopacket**@par*AllocateanEIGRPhello
packet,andaddinthetheapproperateTLVs**/staticstructeigrp_packet*eigrp_hello_enco
de(structeigrp_interface*ei,in_addr_taddr,uint32_tack,uint8_tflags,structin_addr
*nbr_addr){structeigrp_packet*ep;uint16_tlength=EIGRP_HEADER_LEN;//allocateanewp
ackettobesentep=eigrp_packet_new(ei->ifp->mtu,NULL);if(ep){//encodecommonheaderf
eildseigrp_packet_header_init(EIGRP_OPC_HELLO,ei->eigrp,ep->s,0,0,ack);//encodeA
uthenticationTLVif((ei->params.auth_type==EIGRP_AUTH_TYPE_MD5)&&(ei->params.auth
_keychain!=NULL)){length+=eigrp_add_authTLV_MD5_to_stream(ep->s,ei);}elseif((ei-
>params.auth_type==EIGRP_AUTH_TYPE_SHA256)&&(ei->params.auth_keychain!=NULL)){le
ngth+=eigrp_add_authTLV_SHA256_to_stream(ep->s,ei);}/*encodeappropriateparameter
stoHellopacket*/if(flags&EIGRP_HELLO_GRACEFUL_SHUTDOWN)length+=eigrp_hello_param
eter_encode(ei,ep->s,EIGRP_HELLO_GRACEFUL_SHUTDOWN);elselength+=eigrp_hello_para
meter_encode(ei,ep->s,EIGRP_HELLO_NORMAL);//figureouttheversionofcodewe'rerunnin
glength+=eigrp_sw_version_encode(ep->s);if(flags&EIGRP_HELLO_ADD_SEQUENCE){lengt
h+=eigrp_sequence_encode(ep->s);length+=eigrp_next_sequence_encode(ep->s);}//add
intheTIDlistifdoingmulti-topologylength+=eigrp_tidlist_encode(ep->s);/*encodePee
rTerminationTLVifneeded*/if(flags&EIGRP_HELLO_GRACEFUL_SHUTDOWN_NBR)length+=eigr
p_peer_termination_encode(ep->s,nbr_addr);//Setpacketlengthep->length=length;//s
etsoruceaddressforthehellopacketep->dst.s_addr=addr;if((ei->params.auth_type==EI
GRP_AUTH_TYPE_MD5)&&(ei->params.auth_keychain!=NULL)){eigrp_make_md5_digest(ei,e
p->s,EIGRP_AUTH_BASIC_HELLO_FLAG);}elseif((ei->params.auth_type==EIGRP_AUTH_TYPE
_SHA256)&&(ei->params.auth_keychain!=NULL)){eigrp_make_sha256_digest(ei,ep->s,EI
GRP_AUTH_BASIC_HELLO_FLAG);}//EIGRPChecksumeigrp_packet_checksum(ei,ep->s,length
);}return(ep);}/***@fneigrp_hello_send**@param[in]nbrneighbortheACKshouldbesentt
o**@returnvoid**@par*Send(unicast)ahellopacketwiththedestinationaddress*associat
edwiththeneighbor.TheeigrpheaderACKfeildwillbe*updatedtotheneighbor'ssequencenum
bertoacknolodgeany*outstandingpackets*/voideigrp_hello_send_ack(structeigrp_neig
hbor*nbr){structeigrp_packet*ep;/*ifpacketsuccesfullycreated,addittotheinterface
queue*/ep=eigrp_hello_encode(nbr->ei,nbr->src.s_addr,nbr->recv_sequence_number,E
IGRP_HELLO_NORMAL,NULL);if(ep){if(IS_DEBUG_EIGRP_PACKET(0,SEND))zlog_debug("Queu
eing[Hello]AckSeq[%u]nbr[%s]",nbr->recv_sequence_number,inet_ntoa(nbr->src));/*A
ddpackettothetopoftheinterfaceoutputqueue*/eigrp_fifo_push(nbr->ei->obuf,ep);/*H
ookthreadtowritepacket.*/if(nbr->ei->on_write_q==0){listnode_add(nbr->ei->eigrp-
>oi_write_q,nbr->ei);nbr->ei->on_write_q=1;}thread_add_write(master,eigrp_write,
nbr->ei->eigrp,nbr->ei->eigrp->fd,&nbr->ei->eigrp->t_write);}}/***@fneigrp_hello
_send**@param[in]eipointertointerfacehelloshouldbesent*@param[in]flagstypeofhell
opacket*@param[in]nbr_addrpointertoneighboraddressforPeer*TerminationTLV**@retur
nvoid**@par*Buildandenqueueageneric(multicast)periodichellopacketfor*sending.Ifn
opacketsarecurrentlyqueues,thepacketwillbe*sentimmadiatly*/voideigrp_hello_send(
structeigrp_interface*ei,uint8_tflags,structin_addr*nbr_addr){structeigrp_packet
*ep=NULL;/*Ifthisispassiveinterface,donotsendEIGRPHello.if((EIGRP_IF_PASSIVE_STA
TUS(ei)==EIGRP_IF_PASSIVE)||(ei->type!=EIGRP_IFTYPE_NBMA))return;*/if(IS_DEBUG_E
IGRP_PACKET(0,SEND))zlog_debug("Queueing[Hello]Interface(%s)",IF_NAME(ei));/*ifp
acketwassuccesfullycreated,thenaddittotheinterfacequeue*/ep=eigrp_hello_encode(e
i,htonl(EIGRP_MULTICAST_ADDRESS),0,flags,nbr_addr);if(ep){//Addpackettothetopoft
heinterfaceoutputqueueeigrp_fifo_push(ei->obuf,ep);/*Hookthreadtowritepacket.*/i
f(ei->on_write_q==0){listnode_add(ei->eigrp->oi_write_q,ei);ei->on_write_q=1;}if
(ei->eigrp->t_write==NULL){if(flags&EIGRP_HELLO_GRACEFUL_SHUTDOWN){thread_execut
e(master,eigrp_write,ei->eigrp,ei->eigrp->fd);}else{thread_add_write(master,eigr
p_write,ei->eigrp,ei->eigrp->fd,&ei->eigrp->t_write);}}}}