/**PIMforQuagga*Copyright(C)2008EvertondaSilvaMarques**Thisprogramisfreesoftware
;youcanredistributeitand/ormodify*itunderthetermsoftheGNUGeneralPublicLicenseasp
ublishedby*theFreeSoftwareFoundation;eitherversion2oftheLicense,or*(atyouroption
)anylaterversion.**Thisprogramisdistributedinthehopethatitwillbeuseful,but*WITHO
UTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTIC
ULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldhavereceived
acopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;ifnot,w
ritetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-130
1USA*/#ifndefPIM_IGMP_JOIN_H#definePIM_IGMP_JOIN_H/*requiredheaders#include'dbyc
aller*/#ifndefSOL_IP#defineSOL_IPIPPROTO_IP#endif#ifndefMCAST_JOIN_SOURCE_GROUP#
defineMCAST_JOIN_SOURCE_GROUP46structgroup_source_req{uint32_tgsr_interface;stru
ctsockaddr_storagegsr_group;structsockaddr_storagegsr_source;};#endifstaticintpi
m_igmp_join_source(intfd,ifindex_tifindex,structin_addrgroup_addr,structin_addrs
ource_addr){structgroup_source_reqreq;structsockaddr_ingroup;structsockaddr_inso
urce;memset(&req,0,sizeof(req));memset(&group,0,sizeof(group));group.sin_family=
AF_INET;group.sin_addr=group_addr;group.sin_port=htons(0);memcpy(&req.gsr_group,
&group,sizeof(structsockaddr_in));memset(&source,0,sizeof(source));source.sin_fa
mily=AF_INET;source.sin_addr=source_addr;source.sin_port=htons(0);memcpy(&req.gs
r_source,&source,sizeof(structsockaddr_in));req.gsr_interface=ifindex;returnsets
ockopt(fd,SOL_IP,MCAST_JOIN_SOURCE_GROUP,&req,sizeof(req));return0;}#endif/*PIM_
IGMP_JOIN_H*/