/**PIMforQuagga*Copyright(C)2008EvertondaSilvaMarques*Thisprogramisfreesoftware;
youcanredistributeitand/ormodify*itunderthetermsoftheGNUGeneralPublicLicenseaspu
blishedby*theFreeSoftwareFoundation;eitherversion2oftheLicense,or*(atyouroption)
anylaterversion.**Thisprogramisdistributedinthehopethatitwillbeuseful,but*WITHOU
TANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTICU
LARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldhavereceiveda
copyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;ifnot,wr
itetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-1301
USA*/#include<zebra.h>#include"if.h"#include"log.h"#include"vty.h"#include"memor
y.h"#include"prefix.h"#include"vrf.h"#include"linklist.h"#include"plist.h"#inclu
de"hash.h"#include"ferr.h"#include"pimd.h"#include"pim_instance.h"#include"pim_z
ebra.h"#include"pim_iface.h"#include"pim_igmp.h"#include"pim_mroute.h"#include"p
im_oil.h"#include"pim_str.h"#include"pim_pim.h"#include"pim_neighbor.h"#include"
pim_ifchannel.h"#include"pim_sock.h"#include"pim_time.h"#include"pim_ssmpingd.h"
#include"pim_rp.h"#include"pim_nht.h"#include"pim_jp_agg.h"staticvoidpim_if_igmp
_join_del_all(structinterface*ifp);staticintigmp_join_sock(constchar*ifname,ifin
dex_tifindex,structin_addrgroup_addr,structin_addrsource_addr);voidpim_if_init(s
tructpim_instance*pim){inti;for(i=0;i<MAXVIFS;i++)pim->iface_vif_index[i]=0;}voi
dpim_if_terminate(structpim_instance*pim){//Nothingtodoatthismomentreturn;}stati
cvoid*if_list_clean(structpim_interface*pim_ifp){structpim_ifchannel*ch;if(pim_i
fp->igmp_join_list)list_delete_and_null(&pim_ifp->igmp_join_list);if(pim_ifp->ig
mp_socket_list)list_delete_and_null(&pim_ifp->igmp_socket_list);if(pim_ifp->pim_
neighbor_list)list_delete_and_null(&pim_ifp->pim_neighbor_list);if(pim_ifp->upst
ream_switch_list)list_delete_and_null(&pim_ifp->upstream_switch_list);if(pim_ifp
->sec_addr_list)list_delete_and_null(&pim_ifp->sec_addr_list);while(!RB_EMPTY(pi
m_ifchannel_rb,&pim_ifp->ifchannel_rb)){ch=RB_ROOT(pim_ifchannel_rb,&pim_ifp->if
channel_rb);pim_ifchannel_delete(ch);}XFREE(MTYPE_PIM_INTERFACE,pim_ifp);return0
;}staticvoidpim_sec_addr_free(structpim_secondary_addr*sec_addr){XFREE(MTYPE_PIM
_SEC_ADDR,sec_addr);}staticintpim_sec_addr_comp(constvoid*p1,constvoid*p2){const
structpim_secondary_addr*sec1=p1;conststructpim_secondary_addr*sec2=p2;if(sec1->
addr.family==AF_INET&&sec2->addr.family==AF_INET6)return-1;if(sec1->addr.family=
=AF_INET6&&sec2->addr.family==AF_INET)return1;if(sec1->addr.family==AF_INET){if(
ntohl(sec1->addr.u.prefix4.s_addr)<ntohl(sec2->addr.u.prefix4.s_addr))return-1;i
f(ntohl(sec1->addr.u.prefix4.s_addr)>ntohl(sec2->addr.u.prefix4.s_addr))return1;
}else{returnmemcmp(&sec1->addr.u.prefix6,&sec2->addr.u.prefix6,sizeof(structin6_
addr));}return0;}structpim_interface*pim_if_new(structinterface*ifp,intigmp,intp
im){structpim_interface*pim_ifp;zassert(ifp);zassert(!ifp->info);pim_ifp=XCALLOC
(MTYPE_PIM_INTERFACE,sizeof(*pim_ifp));if(!pim_ifp){zlog_err("PIMXCALLOC(%zu)fai
lure",sizeof(*pim_ifp));return0;}pim_ifp->options=0;pim_ifp->pim=pim_get_pim_ins
tance(ifp->vrf_id);pim_ifp->mroute_vif_index=-1;pim_ifp->igmp_version=IGMP_DEFAU
LT_VERSION;pim_ifp->igmp_default_robustness_variable=IGMP_DEFAULT_ROBUSTNESS_VAR
IABLE;pim_ifp->igmp_default_query_interval=IGMP_GENERAL_QUERY_INTERVAL;pim_ifp->
igmp_query_max_response_time_dsec=IGMP_QUERY_MAX_RESPONSE_TIME_DSEC;pim_ifp->igm
p_specific_query_max_response_time_dsec=IGMP_SPECIFIC_QUERY_MAX_RESPONSE_TIME_DS
EC;/*RFC3376:8.3.QueryResponseIntervalThenumberofsecondsrepresentedbythe[QueryRe
sponseInterval]mustbelessthanthe[QueryInterval].*/zassert(pim_ifp->igmp_query_ma
x_response_time_dsec<pim_ifp->igmp_default_query_interval);if(pim)PIM_IF_DO_PIM(
pim_ifp->options);if(igmp)PIM_IF_DO_IGMP(pim_ifp->options);PIM_IF_DO_IGMP_LISTEN
_ALLROUTERS(pim_ifp->options);pim_ifp->igmp_join_list=NULL;pim_ifp->igmp_socket_
list=NULL;pim_ifp->pim_neighbor_list=NULL;pim_ifp->upstream_switch_list=NULL;pim
_ifp->pim_generation_id=0;/*listofstructigmp_sock*/pim_ifp->igmp_socket_list=lis
t_new();if(!pim_ifp->igmp_socket_list){zlog_err("%s:failure:igmp_socket_list=lis
t_new()",__PRETTY_FUNCTION__);returnif_list_clean(pim_ifp);}pim_ifp->igmp_socket
_list->del=(void(*)(void*))igmp_sock_free;/*listofstructpim_neighbor*/pim_ifp->p
im_neighbor_list=list_new();if(!pim_ifp->pim_neighbor_list){zlog_err("%s:failure
:pim_neighbor_list=list_new()",__PRETTY_FUNCTION__);returnif_list_clean(pim_ifp)
;}pim_ifp->pim_neighbor_list->del=(void(*)(void*))pim_neighbor_free;pim_ifp->ups
tream_switch_list=list_new();if(!pim_ifp->upstream_switch_list){zlog_err("%s:fai
lure:upstream_switch_list=list_new()",__PRETTY_FUNCTION__);returnif_list_clean(p
im_ifp);}pim_ifp->upstream_switch_list->del=(void(*)(void*))pim_jp_agg_group_lis
t_free;pim_ifp->upstream_switch_list->cmp=pim_jp_agg_group_list_cmp;pim_ifp->sec
_addr_list=list_new();if(!pim_ifp->sec_addr_list){zlog_err("%s:failure:secondary
addresslist",__PRETTY_FUNCTION__);returnif_list_clean(pim_ifp);}pim_ifp->sec_add
r_list->del=(void(*)(void*))pim_sec_addr_free;pim_ifp->sec_addr_list->cmp=(int(*
)(void*,void*))pim_sec_addr_comp;RB_INIT(pim_ifchannel_rb,&pim_ifp->ifchannel_rb
);ifp->info=pim_ifp;pim_sock_reset(ifp);pim_if_add_vif(ifp);returnpim_ifp;}voidp
im_if_delete(structinterface*ifp){structpim_interface*pim_ifp;structpim_ifchanne
l*ch;zassert(ifp);pim_ifp=ifp->info;zassert(pim_ifp);if(pim_ifp->igmp_join_list)
{pim_if_igmp_join_del_all(ifp);}pim_ifchannel_delete_all(ifp);igmp_sock_delete_a
ll(ifp);pim_neighbor_delete_all(ifp,"Interfaceremovedfromconfiguration");pim_if_
del_vif(ifp);list_delete_and_null(&pim_ifp->igmp_socket_list);list_delete_and_nu
ll(&pim_ifp->pim_neighbor_list);list_delete_and_null(&pim_ifp->upstream_switch_l
ist);list_delete_and_null(&pim_ifp->sec_addr_list);if(pim_ifp->boundary_oil_plis
t)XFREE(MTYPE_PIM_INTERFACE,pim_ifp->boundary_oil_plist);while(!RB_EMPTY(pim_ifc
hannel_rb,&pim_ifp->ifchannel_rb)){ch=RB_ROOT(pim_ifchannel_rb,&pim_ifp->ifchann
el_rb);pim_ifchannel_delete(ch);}XFREE(MTYPE_PIM_INTERFACE,pim_ifp);ifp->info=NU
LL;}voidpim_if_update_could_assert(structinterface*ifp){structpim_interface*pim_
ifp;structpim_ifchannel*ch;pim_ifp=ifp->info;zassert(pim_ifp);RB_FOREACH(ch,pim_
ifchannel_rb,&pim_ifp->ifchannel_rb){pim_ifchannel_update_could_assert(ch);}}sta
ticvoidpim_if_update_my_assert_metric(structinterface*ifp){structpim_interface*p
im_ifp;structpim_ifchannel*ch;pim_ifp=ifp->info;zassert(pim_ifp);RB_FOREACH(ch,p
im_ifchannel_rb,&pim_ifp->ifchannel_rb){pim_ifchannel_update_my_assert_metric(ch
);}}staticvoidpim_addr_change(structinterface*ifp){structpim_interface*pim_ifp;p
im_ifp=ifp->info;zassert(pim_ifp);pim_if_dr_election(ifp);/*router'sownDRPriorit
y(addr)changes--DoneTODOT30*/pim_if_update_join_desired(pim_ifp);/*dependsonDR*/
pim_if_update_could_assert(ifp);/*dependsonDR*/pim_if_update_my_assert_metric(if
p);/*dependsoncould_assert*/pim_if_update_assert_tracking_desired(ifp);/*depends
onDR,join_desired*//*RFC4601:4.3.1.SendingHelloMessages1)Beforeaninterfacegoesdo
wnorchangesprimaryIPaddress,aHellomessagewithazeroHoldTimeshouldbesentimmediatel
y(withtheoldIPaddressiftheIPaddresschanged).--FIXMESeeCAVEATC132)Afteraninterfac
ehaschangeditsIPaddress,itMUSTsendaHellomessagewithitsnewIPaddress.--DONEbelow3)
IfaninterfacechangesoneofitssecondaryIPaddresses,aHellomessagewithanupdatedAddre
ss_Listoptionandanon-zeroHoldTimeshouldbesentimmediately.--FIXMESeeTODOT31*/pim_
ifp->pim_ifstat_hello_sent=0;/*resethellocounter*/if(pim_ifp->pim_sock_fd<0)retu
rn;pim_hello_restart_now(ifp);/*sendhelloandrestarttimer*/}staticintdetect_prima
ry_address_change(structinterface*ifp,intforce_prim_as_any,constchar*caller){str
uctpim_interface*pim_ifp=ifp->info;structin_addrnew_prim_addr;intchanged;if(forc
e_prim_as_any)new_prim_addr.s_addr=INADDR_ANY;elsenew_prim_addr=pim_find_primary
_addr(ifp);changed=new_prim_addr.s_addr!=pim_ifp->primary_address.s_addr;if(PIM_
DEBUG_ZEBRA){charnew_prim_str[INET_ADDRSTRLEN];charold_prim_str[INET_ADDRSTRLEN]
;pim_inet4_dump("<new?>",new_prim_addr,new_prim_str,sizeof(new_prim_str));pim_in
et4_dump("<old?>",pim_ifp->primary_address,old_prim_str,sizeof(old_prim_str));zl
og_debug("%s:old=%snew=%soninterface%s:%s",__PRETTY_FUNCTION__,old_prim_str,new_
prim_str,ifp->name,changed?"changed":"unchanged");}if(changed){pim_ifp->primary_
address=new_prim_addr;}returnchanged;}staticstructpim_secondary_addr*pim_sec_add
r_find(structpim_interface*pim_ifp,structprefix*addr){structpim_secondary_addr*s
ec_addr;structlistnode*node;for(ALL_LIST_ELEMENTS_RO(pim_ifp->sec_addr_list,node
,sec_addr)){if(prefix_cmp(&sec_addr->addr,addr)){returnsec_addr;}}returnNULL;}st
aticvoidpim_sec_addr_del(structpim_interface*pim_ifp,structpim_secondary_addr*se
c_addr){listnode_delete(pim_ifp->sec_addr_list,sec_addr);pim_sec_addr_free(sec_a
ddr);}staticintpim_sec_addr_add(structpim_interface*pim_ifp,structprefix*addr){i
ntchanged=0;structpim_secondary_addr*sec_addr;sec_addr=pim_sec_addr_find(pim_ifp
,addr);if(sec_addr){sec_addr->flags&=~PIM_SEC_ADDRF_STALE;returnchanged;}sec_add
r=XCALLOC(MTYPE_PIM_SEC_ADDR,sizeof(*sec_addr));if(!sec_addr)returnchanged;chang
ed=1;sec_addr->addr=*addr;listnode_add_sort(pim_ifp->sec_addr_list,sec_addr);ret
urnchanged;}staticintpim_sec_addr_del_all(structpim_interface*pim_ifp){intchange
d=0;if(!list_isempty(pim_ifp->sec_addr_list)){changed=1;/*removeallnodesandfreeu
pthelistitself*/list_delete_all_node(pim_ifp->sec_addr_list);}returnchanged;}sta
ticintpim_sec_addr_update(structinterface*ifp){structpim_interface*pim_ifp=ifp->
info;structconnected*ifc;structlistnode*node;structlistnode*nextnode;structpim_s
econdary_addr*sec_addr;intchanged=0;for(ALL_LIST_ELEMENTS_RO(pim_ifp->sec_addr_l
ist,node,sec_addr)){sec_addr->flags|=PIM_SEC_ADDRF_STALE;}for(ALL_LIST_ELEMENTS_
RO(ifp->connected,node,ifc)){structprefix*p=ifc->address;if(PIM_INADDR_IS_ANY(p-
>u.prefix4)){continue;}if(pim_ifp->primary_address.s_addr==p->u.prefix4.s_addr){
/*don'taddtheprimaryaddressintothesecondary*addresslist*/continue;}if(pim_sec_ad
dr_add(pim_ifp,p)){changed=1;}}/*Dropstaleentries*/for(ALL_LIST_ELEMENTS(pim_ifp
->sec_addr_list,node,nextnode,sec_addr)){if(sec_addr->flags&PIM_SEC_ADDRF_STALE)
{pim_sec_addr_del(pim_ifp,sec_addr);changed=1;}}returnchanged;}staticintdetect_s
econdary_address_change(structinterface*ifp,intforce_prim_as_any,constchar*calle
r){structpim_interface*pim_ifp=ifp->info;intchanged=0;if(force_prim_as_any){/*if
primaryaddressisbeingforcedtozerojustflushthe*secondaryaddresslist*/changed=pim_
sec_addr_del_all(pim_ifp);}else{/*re-evaluatethesecondaryaddresslist*/changed=pi
m_sec_addr_update(ifp);}returnchanged;}staticvoiddetect_address_change(structint
erface*ifp,intforce_prim_as_any,constchar*caller){intchanged=0;structpim_interfa
ce*pim_ifp;pim_ifp=ifp->info;if(!pim_ifp)return;if(detect_primary_address_change
(ifp,force_prim_as_any,caller)){changed=1;}if(detect_secondary_address_change(if
p,force_prim_as_any,caller)){changed=1;}if(changed){if(!PIM_IF_TEST_PIM(pim_ifp-
>options)){return;}pim_addr_change(ifp);}/*XXX:ifwehaveunnumberedinterfaceswenee
dtorundetectaddress*addresschangeonallofthemwhentheloaddresschanges*/}intpim_upd
ate_source_set(structinterface*ifp,structin_addrsource){structpim_interface*pim_
ifp=ifp->info;if(!pim_ifp){returnPIM_IFACE_NOT_FOUND;}if(pim_ifp->update_source.
s_addr==source.s_addr){returnPIM_UPDATE_SOURCE_DUP;}pim_ifp->update_source=sourc
e;detect_address_change(ifp,0/*force_prim_as_any*/,__PRETTY_FUNCTION__);returnPI
M_SUCCESS;}voidpim_if_addr_add(structconnected*ifc){structpim_interface*pim_ifp;
structinterface*ifp;structin_addrifaddr;zassert(ifc);ifp=ifc->ifp;zassert(ifp);p
im_ifp=ifp->info;if(!pim_ifp)return;if(!if_is_operative(ifp))return;if(PIM_DEBUG
_ZEBRA){charbuf[BUFSIZ];prefix2str(ifc->address,buf,BUFSIZ);zlog_debug("%s:%sifi
ndex=%dconnectedIPaddress%s%s",__PRETTY_FUNCTION__,ifp->name,ifp->ifindex,buf,CH
ECK_FLAG(ifc->flags,ZEBRA_IFA_SECONDARY)?"secondary":"primary");}ifaddr=ifc->add
ress->u.prefix4;detect_address_change(ifp,0,__PRETTY_FUNCTION__);//if(ifc->addre
ss->family!=AF_INET)//return;if(PIM_IF_TEST_IGMP(pim_ifp->options)){structigmp_s
ock*igmp;/*lookupIGMPsocket*/igmp=pim_igmp_sock_lookup_ifaddr(pim_ifp->igmp_sock
et_list,ifaddr);if(!igmp){/*ifaddrnew,addIGMPsocket*/if(ifc->address->family==AF
_INET)pim_igmp_sock_add(pim_ifp->igmp_socket_list,ifaddr,ifp,false);}elseif(igmp
->mtrace_only){igmp_sock_delete(igmp);pim_igmp_sock_add(pim_ifp->igmp_socket_lis
t,ifaddr,ifp,false);}/*ReplayStaticIGMPgroups*/if(pim_ifp->igmp_join_list){struc
tlistnode*node;structlistnode*nextnode;structigmp_join*ij;intjoin_fd;for(ALL_LIS
T_ELEMENTS(pim_ifp->igmp_join_list,node,nextnode,ij)){/*Closesocketandreopenwith
SourceandGroup*/close(ij->sock_fd);join_fd=igmp_join_sock(ifp->name,ifp->ifindex
,ij->group_addr,ij->source_addr);if(join_fd<0){chargroup_str[INET_ADDRSTRLEN];ch
arsource_str[INET_ADDRSTRLEN];pim_inet4_dump("<grp?>",ij->group_addr,group_str,s
izeof(group_str));pim_inet4_dump("<src?>",ij->source_addr,source_str,sizeof(sour
ce_str));zlog_warn("%s:igmp_join_sock()failureforIGMPgroup%ssource%soninterface%
s",__PRETTY_FUNCTION__,group_str,source_str,ifp->name);/*warningonly*/}elseij->s
ock_fd=join_fd;}}}/*igmp*/else{structigmp_sock*igmp;/*lookupIGMPsocket*/igmp=pim
_igmp_sock_lookup_ifaddr(pim_ifp->igmp_socket_list,ifaddr);if(ifc->address->fami
ly==AF_INET){if(igmp)igmp_sock_delete(igmp);/*ifaddrnew,addIGMPsocket*/pim_igmp_
sock_add(pim_ifp->igmp_socket_list,ifaddr,ifp,true);}}/*igmpmtraceonly*/if(PIM_I
F_TEST_PIM(pim_ifp->options)){if(PIM_INADDR_ISNOT_ANY(pim_ifp->primary_address))
{/*Interfacehasavalidsocket?*/if(pim_ifp->pim_sock_fd<0){if(pim_sock_add(ifp)){z
log_warn("FailurecreatingPIMsocketforinterface%s",ifp->name);}}structpim_nexthop
_cache*pnc=NULL;structpim_rpfrpf;structzclient*zclient=NULL;zclient=pim_zebra_zc
lient_get();/*RPconfigmightcomepriorto(localRP'sinterface)IFUPevent.Inthiscase,p
ncwouldnothavepimenablednexthops.OnceInterfaceisUPandpiminfoisavailable,reregist
erwithRNHaddresstoreceiveupdateandaddtheinterfaceasnexthop.*/memset(&rpf,0,sizeo
f(structpim_rpf));rpf.rpf_addr.family=AF_INET;rpf.rpf_addr.prefixlen=IPV4_MAX_BI
TLEN;rpf.rpf_addr.u.prefix4=ifc->address->u.prefix4;pnc=pim_nexthop_cache_find(p
im_ifp->pim,&rpf);if(pnc)pim_sendmsg_zebra_rnh(pim_ifp->pim,zclient,pnc,ZEBRA_NE
XTHOP_REGISTER);}}/*pim*//*PIMorIGMPisenabledoninterface,andthereisatleastoneadd
ressassigned,thentrytocreateavif_index.*/if(pim_ifp->mroute_vif_index<0){pim_if_
add_vif(ifp);}pim_ifchannel_scan_forward_start(ifp);}staticvoidpim_if_addr_del_i
gmp(structconnected*ifc){structpim_interface*pim_ifp=ifc->ifp->info;structigmp_s
ock*igmp;structin_addrifaddr;if(ifc->address->family!=AF_INET){/*non-IPv4address
*/return;}if(!pim_ifp){/*IGMPnotenabledoninterface*/return;}ifaddr=ifc->address-
>u.prefix4;/*lookupIGMPsocket*/igmp=pim_igmp_sock_lookup_ifaddr(pim_ifp->igmp_so
cket_list,ifaddr);if(igmp){/*ifaddrfound,delIGMPsocket*/igmp_sock_delete(igmp);}
}staticvoidpim_if_addr_del_pim(structconnected*ifc){structpim_interface*pim_ifp=
ifc->ifp->info;if(ifc->address->family!=AF_INET){/*non-IPv4address*/return;}if(!
pim_ifp){/*PIMnotenabledoninterface*/return;}if(PIM_INADDR_ISNOT_ANY(pim_ifp->pr
imary_address)){/*Interfacekeepsavalidprimaryaddress*/return;}if(pim_ifp->pim_so
ck_fd<0){/*Interfacedoesnotholdavalidsocketanylonger*/return;}/*pim_sock_delete(
)closesthesocket,stopsreadandtimerthreads,andkillsallneighbors.*/pim_sock_delete
(ifc->ifp,"lastaddresshasbeenremovedfrominterface");}voidpim_if_addr_del(structc
onnected*ifc,intforce_prim_as_any){structinterface*ifp;zassert(ifc);ifp=ifc->ifp
;zassert(ifp);if(PIM_DEBUG_ZEBRA){charbuf[BUFSIZ];prefix2str(ifc->address,buf,BU
FSIZ);zlog_debug("%s:%sifindex=%ddisconnectedIPaddress%s%s",__PRETTY_FUNCTION__,
ifp->name,ifp->ifindex,buf,CHECK_FLAG(ifc->flags,ZEBRA_IFA_SECONDARY)?"secondary
":"primary");}detect_address_change(ifp,force_prim_as_any,__PRETTY_FUNCTION__);p
im_if_addr_del_igmp(ifc);pim_if_addr_del_pim(ifc);}voidpim_if_addr_add_all(struc
tinterface*ifp){structconnected*ifc;structlistnode*node;structlistnode*nextnode;
intv4_addrs=0;intv6_addrs=0;structpim_interface*pim_ifp=ifp->info;/*PIM/IGMPenab
led?*/if(!pim_ifp)return;for(ALL_LIST_ELEMENTS(ifp->connected,node,nextnode,ifc)
){structprefix*p=ifc->address;if(p->family!=AF_INET)v6_addrs++;elsev4_addrs++;pi
m_if_addr_add(ifc);}if(!v4_addrs&&v6_addrs&&!if_is_loopback(ifp)){if(PIM_IF_TEST
_PIM(pim_ifp->options)){/*Interfacehasavalidprimaryaddress?*/if(PIM_INADDR_ISNOT
_ANY(pim_ifp->primary_address)){/*Interfacehasavalidsocket?*/if(pim_ifp->pim_soc
k_fd<0){if(pim_sock_add(ifp)){zlog_warn("FailurecreatingPIMsocketforinterface%s"
,ifp->name);}}}}/*pim*/}/**PIMorIGMPisenabledoninterface,andthereisatleastone*ad
dressassigned,thentrytocreateavif_index.*/if(pim_ifp->mroute_vif_index<0){pim_if
_add_vif(ifp);}pim_ifchannel_scan_forward_start(ifp);pim_rp_setup(pim_ifp->pim);
pim_rp_check_on_if_add(pim_ifp);}voidpim_if_addr_del_all(structinterface*ifp){st
ructconnected*ifc;structlistnode*node;structlistnode*nextnode;structvrf*vrf=vrf_
lookup_by_id(ifp->vrf_id);structpim_instance*pim;if(!vrf)return;pim=vrf->info;/*
PIM/IGMPenabled?*/if(!ifp->info)return;for(ALL_LIST_ELEMENTS(ifp->connected,node
,nextnode,ifc)){structprefix*p=ifc->address;if(p->family!=AF_INET)continue;pim_i
f_addr_del(ifc,1/*force_prim_as_any=true*/);}pim_rp_setup(pim);pim_i_am_rp_re_ev
aluate(pim);}voidpim_if_addr_del_all_igmp(structinterface*ifp){structconnected*i
fc;structlistnode*node;structlistnode*nextnode;/*PIM/IGMPenabled?*/if(!ifp->info
)return;for(ALL_LIST_ELEMENTS(ifp->connected,node,nextnode,ifc)){structprefix*p=
ifc->address;if(p->family!=AF_INET)continue;pim_if_addr_del_igmp(ifc);}}voidpim_
if_addr_del_all_pim(structinterface*ifp){structconnected*ifc;structlistnode*node
;structlistnode*nextnode;/*PIM/IGMPenabled?*/if(!ifp->info)return;for(ALL_LIST_E
LEMENTS(ifp->connected,node,nextnode,ifc)){structprefix*p=ifc->address;if(p->fam
ily!=AF_INET)continue;pim_if_addr_del_pim(ifc);}}structin_addrpim_find_primary_a
ddr(structinterface*ifp){structconnected*ifc;structlistnode*node;structin_addrad
dr={0};intv4_addrs=0;intv6_addrs=0;structpim_interface*pim_ifp=ifp->info;structv
rf*vrf=vrf_lookup_by_id(ifp->vrf_id);if(!vrf)returnaddr;if(pim_ifp&&PIM_INADDR_I
SNOT_ANY(pim_ifp->update_source)){returnpim_ifp->update_source;}for(ALL_LIST_ELE
MENTS_RO(ifp->connected,node,ifc)){structprefix*p=ifc->address;if(p->family!=AF_
INET){v6_addrs++;continue;}if(PIM_INADDR_IS_ANY(p->u.prefix4)){zlog_warn("%s:nul
lIPv4addressconnectedtointerface%s",__PRETTY_FUNCTION__,ifp->name);continue;}v4_
addrs++;if(CHECK_FLAG(ifc->flags,ZEBRA_IFA_SECONDARY))continue;returnp->u.prefix
4;}/**Ifwehavenov4_addrsandv6isconfigured*Weprobablyareusingunnumbered*Solet'sgr
abtheloopbacksv4address*andusethatastheprimaryaddress*/if(!v4_addrs&&v6_addrs&&!
if_is_loopback(ifp)){structinterface*lo_ifp;//DBS-Comebackandcheckhereif(ifp->vr
f_id==VRF_DEFAULT)lo_ifp=if_lookup_by_name("lo",vrf->vrf_id);elselo_ifp=if_looku
p_by_name(vrf->name,vrf->vrf_id);if(lo_ifp)returnpim_find_primary_addr(lo_ifp);}
addr.s_addr=PIM_NET_INADDR_ANY;returnaddr;}staticintpim_iface_next_vif_index(str
uctinterface*ifp){structpim_interface*pim_ifp=ifp->info;structpim_instance*pim=p
im_ifp->pim;inti;/**Thepimregvifisalwaysgoingtobeinindex0*ofthetable.*/if(ifp->i
findex==PIM_OIF_PIM_REGISTER_VIF)return0;for(i=1;i<MAXVIFS;i++){if(pim->iface_vi
f_index[i]==0)returni;}returnMAXVIFS;}/*pim_if_add_vif()usesifindexasvif_indexse
ealsopim_if_find_vifindex_by_ifindex()*/intpim_if_add_vif(structinterface*ifp){s
tructpim_interface*pim_ifp=ifp->info;structin_addrifaddr;unsignedcharflags=0;zas
sert(pim_ifp);if(pim_ifp->mroute_vif_index>0){zlog_warn("%s:vif_index=%d>0oninte
rface%sifindex=%d",__PRETTY_FUNCTION__,pim_ifp->mroute_vif_index,ifp->name,ifp->
ifindex);return-1;}if(ifp->ifindex<0){zlog_warn("%s:ifindex=%d<1oninterface%s",_
_PRETTY_FUNCTION__,ifp->ifindex,ifp->name);return-2;}ifaddr=pim_ifp->primary_add
ress;if(ifp->ifindex!=PIM_OIF_PIM_REGISTER_VIF&&PIM_INADDR_IS_ANY(ifaddr)){zlog_
warn("%s:couldnotgetaddressforinterface%sifindex=%d",__PRETTY_FUNCTION__,ifp->na
me,ifp->ifindex);return-4;}pim_ifp->mroute_vif_index=pim_iface_next_vif_index(if
p);if(pim_ifp->mroute_vif_index>=MAXVIFS){zlog_warn("%s:Attemptingtoconfiguremor
ethanMAXVIFS=%donpimenabledinterface%s",__PRETTY_FUNCTION__,MAXVIFS,ifp->name);r
eturn-3;}if(ifp->ifindex==PIM_OIF_PIM_REGISTER_VIF)flags=VIFF_REGISTER;#ifdefVIF
F_USE_IFINDEXelseflags=VIFF_USE_IFINDEX;#endifif(pim_mroute_add_vif(ifp,ifaddr,f
lags)){/*pim_mroute_add_vifreportederror*/return-5;}pim_ifp->pim->iface_vif_inde
x[pim_ifp->mroute_vif_index]=1;return0;}intpim_if_del_vif(structinterface*ifp){s
tructpim_interface*pim_ifp=ifp->info;if(pim_ifp->mroute_vif_index<1){zlog_warn("
%s:vif_index=%d<1oninterface%sifindex=%d",__PRETTY_FUNCTION__,pim_ifp->mroute_vi
f_index,ifp->name,ifp->ifindex);return-1;}pim_mroute_del_vif(ifp);/*Updatevif_in
dex*/pim_ifp->pim->iface_vif_index[pim_ifp->mroute_vif_index]=0;pim_ifp->mroute_
vif_index=-1;return0;}//DBS-VRFReviststructinterface*pim_if_find_by_vif_index(st
ructpim_instance*pim,ifindex_tvif_index){structinterface*ifp;FOR_ALL_INTERFACES(
pim->vrf,ifp){if(ifp->info){structpim_interface*pim_ifp;pim_ifp=ifp->info;if(vif
_index==pim_ifp->mroute_vif_index)returnifp;}}return0;}/*pim_if_add_vif()usesifi
ndexasvif_index*/intpim_if_find_vifindex_by_ifindex(structpim_instance*pim,ifind
ex_tifindex){structpim_interface*pim_ifp;structinterface*ifp;ifp=if_lookup_by_in
dex(ifindex,pim->vrf_id);if(!ifp||!ifp->info)return-1;pim_ifp=ifp->info;returnpi
m_ifp->mroute_vif_index;}intpim_if_lan_delay_enabled(structinterface*ifp){struct
pim_interface*pim_ifp;pim_ifp=ifp->info;zassert(pim_ifp);zassert(pim_ifp->pim_nu
mber_of_nonlandelay_neighbors>=0);returnpim_ifp->pim_number_of_nonlandelay_neigh
bors==0;}uint16_tpim_if_effective_propagation_delay_msec(structinterface*ifp){if
(pim_if_lan_delay_enabled(ifp)){structpim_interface*pim_ifp;pim_ifp=ifp->info;re
turnpim_ifp->pim_neighbors_highest_propagation_delay_msec;}else{returnPIM_DEFAUL
T_PROPAGATION_DELAY_MSEC;}}uint16_tpim_if_effective_override_interval_msec(struc
tinterface*ifp){if(pim_if_lan_delay_enabled(ifp)){structpim_interface*pim_ifp;pi
m_ifp=ifp->info;returnpim_ifp->pim_neighbors_highest_override_interval_msec;}els
e{returnPIM_DEFAULT_OVERRIDE_INTERVAL_MSEC;}}intpim_if_t_override_msec(structint
erface*ifp){inteffective_override_interval_msec;intt_override_msec;effective_ove
rride_interval_msec=pim_if_effective_override_interval_msec(ifp);t_override_msec
=random()%(effective_override_interval_msec+1);returnt_override_msec;}uint16_tpi
m_if_jp_override_interval_msec(structinterface*ifp){returnpim_if_effective_propa
gation_delay_msec(ifp)+pim_if_effective_override_interval_msec(ifp);}/*RFC4601:4
.1.6.StateSummarizationMacrosThefunctionNBR(I,A)usesinformationgatheredthroughPI
MHellomessagestomaptheIPaddressAofadirectlyconnectedPIMneighborrouteroninterface
ItotheprimaryIPaddressofthesamerouter(Section4.3.4).TheprimaryIPaddressofaneighb
oristheaddressthatitusesasthesourceofitsPIMHellomessages.*/structpim_neighbor*pi
m_if_find_neighbor(structinterface*ifp,structin_addraddr){structlistnode*neighno
de;structpim_neighbor*neigh;structpim_interface*pim_ifp;structprefixp;zassert(if
p);pim_ifp=ifp->info;if(!pim_ifp){zlog_warn("%s:multicastnotenabledoninterface%s
",__PRETTY_FUNCTION__,ifp->name);return0;}p.family=AF_INET;p.u.prefix4=addr;p.pr
efixlen=IPV4_MAX_PREFIXLEN;for(ALL_LIST_ELEMENTS_RO(pim_ifp->pim_neighbor_list,n
eighnode,neigh)){/*primaryaddress?*/if(neigh->source_addr.s_addr==addr.s_addr)re
turnneigh;/*secondaryaddress?*/if(pim_neighbor_find_secondary(neigh,&p))returnne
igh;}if(PIM_DEBUG_PIM_TRACE){charaddr_str[INET_ADDRSTRLEN];pim_inet4_dump("<addr
?>",addr,addr_str,sizeof(addr_str));zlog_debug("%s:neighbornotfoundforaddress%so
ninterface%s",__PRETTY_FUNCTION__,addr_str,ifp->name);}returnNULL;}longpim_if_t_
suppressed_msec(structinterface*ifp){structpim_interface*pim_ifp;longt_suppresse
d_msec;uint32_tramount=0;pim_ifp=ifp->info;zassert(pim_ifp);/*joinsuppressiondis
abled?*/if(PIM_IF_TEST_PIM_CAN_DISABLE_JOIN_SUPRESSION(pim_ifp->options))return0
;/*t_suppressed=t_periodic*rand(1.1,1.4)*/ramount=1100+(random()%(1400-1100+1));
t_suppressed_msec=qpim_t_periodic*ramount;returnt_suppressed_msec;}staticvoidigm
p_join_free(structigmp_join*ij){XFREE(MTYPE_PIM_IGMP_JOIN,ij);}staticstructigmp_
join*igmp_join_find(structlist*join_list,structin_addrgroup_addr,structin_addrso
urce_addr){structlistnode*node;structigmp_join*ij;zassert(join_list);for(ALL_LIS
T_ELEMENTS_RO(join_list,node,ij)){if((group_addr.s_addr==ij->group_addr.s_addr)&
&(source_addr.s_addr==ij->source_addr.s_addr))returnij;}return0;}staticintigmp_j
oin_sock(constchar*ifname,ifindex_tifindex,structin_addrgroup_addr,structin_addr
source_addr){intjoin_fd;join_fd=pim_socket_raw(IPPROTO_IGMP);if(join_fd<0){retur
n-1;}if(pim_socket_join_source(join_fd,ifindex,group_addr,source_addr,ifname)){c
lose(join_fd);return-2;}returnjoin_fd;}staticstructigmp_join*igmp_join_new(struc
tinterface*ifp,structin_addrgroup_addr,structin_addrsource_addr){structpim_inter
face*pim_ifp;structigmp_join*ij;intjoin_fd;pim_ifp=ifp->info;zassert(pim_ifp);jo
in_fd=igmp_join_sock(ifp->name,ifp->ifindex,group_addr,source_addr);if(join_fd<0
){chargroup_str[INET_ADDRSTRLEN];charsource_str[INET_ADDRSTRLEN];pim_inet4_dump(
"<grp?>",group_addr,group_str,sizeof(group_str));pim_inet4_dump("<src?>",source_
addr,source_str,sizeof(source_str));zlog_warn("%s:igmp_join_sock()failureforIGMP
group%ssource%soninterface%s",__PRETTY_FUNCTION__,group_str,source_str,ifp->name
);return0;}ij=XCALLOC(MTYPE_PIM_IGMP_JOIN,sizeof(*ij));if(!ij){chargroup_str[INE
T_ADDRSTRLEN];charsource_str[INET_ADDRSTRLEN];pim_inet4_dump("<grp?>",group_addr
,group_str,sizeof(group_str));pim_inet4_dump("<src?>",source_addr,source_str,siz
eof(source_str));zlog_err("%s:XCALLOC(%zu)failureforIGMPgroup%ssource%soninterfa
ce%s",__PRETTY_FUNCTION__,sizeof(*ij),group_str,source_str,ifp->name);close(join
_fd);return0;}ij->sock_fd=join_fd;ij->group_addr=group_addr;ij->source_addr=sour
ce_addr;ij->sock_creation=pim_time_monotonic_sec();listnode_add(pim_ifp->igmp_jo
in_list,ij);returnij;}ferr_rpim_if_igmp_join_add(structinterface*ifp,structin_ad
drgroup_addr,structin_addrsource_addr){structpim_interface*pim_ifp;structigmp_jo
in*ij;pim_ifp=ifp->info;if(!pim_ifp){returnferr_cfg_invalid("multicastnotenabled
oninterface%s",ifp->name);}if(!pim_ifp->igmp_join_list){pim_ifp->igmp_join_list=
list_new();if(!pim_ifp->igmp_join_list){returnferr_cfg_invalid("Insufficientmemo
ry");}pim_ifp->igmp_join_list->del=(void(*)(void*))igmp_join_free;}ij=igmp_join_
find(pim_ifp->igmp_join_list,group_addr,source_addr);/*Thisinterfacehasalreadybe
enconfiguredtojointhisIGMPgroup*/if(ij){returnferr_ok();}ij=igmp_join_new(ifp,gr
oup_addr,source_addr);if(!ij){returnferr_cfg_invalid("Failuretocreatenewjoindata
structure,seelogfileformoreinformation");}if(PIM_DEBUG_IGMP_EVENTS){chargroup_st
r[INET_ADDRSTRLEN];charsource_str[INET_ADDRSTRLEN];pim_inet4_dump("<grp?>",group
_addr,group_str,sizeof(group_str));pim_inet4_dump("<src?>",source_addr,source_st
r,sizeof(source_str));zlog_debug("%s:issuedstaticigmpjoinforchannel(S,G)=(%s,%s)
oninterface%s",__PRETTY_FUNCTION__,source_str,group_str,ifp->name);}returnferr_o
k();}intpim_if_igmp_join_del(structinterface*ifp,structin_addrgroup_addr,structi
n_addrsource_addr){structpim_interface*pim_ifp;structigmp_join*ij;pim_ifp=ifp->i
nfo;if(!pim_ifp){zlog_warn("%s:multicastnotenabledoninterface%s",__PRETTY_FUNCTI
ON__,ifp->name);return-1;}if(!pim_ifp->igmp_join_list){zlog_warn("%s:noIGMPjoino
ninterface%s",__PRETTY_FUNCTION__,ifp->name);return-2;}ij=igmp_join_find(pim_ifp
->igmp_join_list,group_addr,source_addr);if(!ij){chargroup_str[INET_ADDRSTRLEN];
charsource_str[INET_ADDRSTRLEN];pim_inet4_dump("<grp?>",group_addr,group_str,siz
eof(group_str));pim_inet4_dump("<src?>",source_addr,source_str,sizeof(source_str
));zlog_warn("%s:couldnotfindIGMPgroup%ssource%soninterface%s",__PRETTY_FUNCTION
__,group_str,source_str,ifp->name);return-3;}if(close(ij->sock_fd)){chargroup_st
r[INET_ADDRSTRLEN];charsource_str[INET_ADDRSTRLEN];pim_inet4_dump("<grp?>",group
_addr,group_str,sizeof(group_str));pim_inet4_dump("<src?>",source_addr,source_st
r,sizeof(source_str));zlog_warn("%s:failureclosingsock_fd=%dforIGMPgroup%ssource
%soninterface%s:errno=%d:%s",__PRETTY_FUNCTION__,ij->sock_fd,group_str,source_st
r,ifp->name,errno,safe_strerror(errno));/*warningonly*/}listnode_delete(pim_ifp-
>igmp_join_list,ij);igmp_join_free(ij);if(listcount(pim_ifp->igmp_join_list)<1){
list_delete_and_null(&pim_ifp->igmp_join_list);pim_ifp->igmp_join_list=0;}return
0;}staticvoidpim_if_igmp_join_del_all(structinterface*ifp){structpim_interface*p
im_ifp;structlistnode*node;structlistnode*nextnode;structigmp_join*ij;pim_ifp=if
p->info;if(!pim_ifp){zlog_warn("%s:multicastnotenabledoninterface%s",__PRETTY_FU
NCTION__,ifp->name);return;}if(!pim_ifp->igmp_join_list)return;for(ALL_LIST_ELEM
ENTS(pim_ifp->igmp_join_list,node,nextnode,ij))pim_if_igmp_join_del(ifp,ij->grou
p_addr,ij->source_addr);}/*RFC4601Transitionsfrom"IamAssertLoser"StateCurrentWin
ner'sGenIDChangesorNLTExpiresTheNeighborLivenessTimerassociatedwiththecurrentwin
nerexpiresorwereceiveaHellomessagefromthecurrentwinnerreportingadifferentGenIDfr
omtheoneitpreviouslyreported.Thisindicatesthatthecurrentwinner'sinterfaceorroute
rhasgonedown(andmayhavecomebackup),andsowemustassumeitnolongerknowsitwasthewinne
r.*/voidpim_if_assert_on_neighbor_down(structinterface*ifp,structin_addrneigh_ad
dr){structpim_interface*pim_ifp;structpim_ifchannel*ch;pim_ifp=ifp->info;zassert
(pim_ifp);RB_FOREACH(ch,pim_ifchannel_rb,&pim_ifp->ifchannel_rb){/*Is(S,G,I)asse
rtloser?*/if(ch->ifassert_state!=PIM_IFASSERT_I_AM_LOSER)continue;/*Deadneighbor
waswinner?*/if(ch->ifassert_winner.s_addr!=neigh_addr.s_addr)continue;assert_act
ion_a5(ch);}}voidpim_if_update_join_desired(structpim_interface*pim_ifp){structp
im_ifchannel*ch;/*clearoffflagfrominterface'supstreams*/RB_FOREACH(ch,pim_ifchan
nel_rb,&pim_ifp->ifchannel_rb){PIM_UPSTREAM_FLAG_UNSET_DR_JOIN_DESIRED_UPDATED(c
h->upstream->flags);}/*scanper-interface(S,G,I)stateonthisIinterface*/RB_FOREACH
(ch,pim_ifchannel_rb,&pim_ifp->ifchannel_rb){structpim_upstream*up=ch->upstream;
if(PIM_UPSTREAM_FLAG_TEST_DR_JOIN_DESIRED_UPDATED(up->flags))continue;/*updatejo
in_desiredfortheglobal(S,G)state*/pim_upstream_update_join_desired(pim_ifp->pim,
up);PIM_UPSTREAM_FLAG_SET_DR_JOIN_DESIRED_UPDATED(up->flags);}}voidpim_if_update
_assert_tracking_desired(structinterface*ifp){structpim_interface*pim_ifp;struct
pim_ifchannel*ch;pim_ifp=ifp->info;if(!pim_ifp)return;RB_FOREACH(ch,pim_ifchanne
l_rb,&pim_ifp->ifchannel_rb){pim_ifchannel_update_assert_tracking_desired(ch);}}
/**PIMwantstohaveaninterfacepointerforeverythingitdoes.*Thepimregisaspecialinter
facethatwehavethatisnot*quiteanintefacebutaVIFiscreatedforit.*/voidpim_if_create
_pimreg(structpim_instance*pim){charpimreg_name[INTERFACE_NAMSIZ];if(!pim->regif
ace){if(pim->vrf_id==VRF_DEFAULT)strlcpy(pimreg_name,"pimreg",sizeof(pimreg_name
));elsesnprintf(pimreg_name,sizeof(pimreg_name),"pimreg%u",pim->vrf->data.l.tabl
e_id);pim->regiface=if_create(pimreg_name,pim->vrf_id);pim->regiface->ifindex=PI
M_OIF_PIM_REGISTER_VIF;pim_if_new(pim->regiface,0,0);}}intpim_if_connected_to_so
urce(structinterface*ifp,structin_addrsrc){structlistnode*cnode;structconnected*
c;structprefixp;if(!ifp)return0;p.family=AF_INET;p.u.prefix4=src;p.prefixlen=IPV
4_MAX_BITLEN;for(ALL_LIST_ELEMENTS_RO(ifp->connected,cnode,c)){if((c->address->f
amily==AF_INET)&&prefix_match(CONNECTED_PREFIX(c),&p)){return1;}}return0;}intpim
_if_is_loopback(structpim_instance*pim,structinterface*ifp){if(if_is_loopback(if
p))return1;if(strcmp(ifp->name,pim->vrf->name)==0)return1;return0;}intpim_if_is_
vrf_device(structinterface*ifp){structvrf*vrf;RB_FOREACH(vrf,vrf_name_head,&vrfs
_by_name){if(strncmp(ifp->name,vrf->name,strlen(ifp->name))==0)return1;}return0;
}intpim_if_ifchannel_count(structpim_interface*pim_ifp){structpim_ifchannel*ch;i
ntcount=0;RB_FOREACH(ch,pim_ifchannel_rb,&pim_ifp->ifchannel_rb){count++;}return
count;}