/**PIMforFRR-PIMInstance*Copyright(C)2017CumulusNetworks,Inc.*DonaldSharp**Thisp
rogramisfreesoftware;youcanredistributeitand/ormodify*itunderthetermsoftheGNUGen
eralPublicLicenseaspublishedby*theFreeSoftwareFoundation;eitherversion2oftheLice
nse,or*(atyouroption)anylaterversion.**Thisprogramisdistributedinthehopethatitwi
llbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILIT
YorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Y
oushouldhavereceivedacopyoftheGNUGeneralPublicLicense*alongwiththisprogram;seeth
efileCOPYING;ifnot,writetothe*FreeSoftwareFoundation,Inc.,51FranklinSt,FifthFloo
r,Boston,*MA02110-1301USA*/#include<zebra.h>#include"hash.h"#include"vrf.h"#incl
ude"pimd.h"#include"pim_ssm.h"#include"pim_rpf.h"#include"pim_rp.h"#include"pim_
mroute.h"#include"pim_oil.h"#include"pim_static.h"#include"pim_ssmpingd.h"#inclu
de"pim_vty.h"staticvoidpim_instance_terminate(structpim_instance*pim){/*Traverse
andcleanuprpf_hash*/if(pim->rpf_hash){hash_clean(pim->rpf_hash,(void*)pim_rp_lis
t_hash_clean);hash_free(pim->rpf_hash);pim->rpf_hash=NULL;}if(pim->ssm_info){pim
_ssm_terminate(pim->ssm_info);pim->ssm_info=NULL;}if(pim->static_routes)list_del
ete_and_null(&pim->static_routes);pim_rp_free(pim);pim_upstream_terminate(pim);p
im_oil_terminate(pim);pim_if_terminate(pim);pim_msdp_exit(pim);XFREE(MTYPE_PIM_P
IM_INSTANCE,pim);}staticstructpim_instance*pim_instance_init(structvrf*vrf){stru
ctpim_instance*pim;charhash_name[64];pim=XCALLOC(MTYPE_PIM_PIM_INSTANCE,sizeof(s
tructpim_instance));if(!pim)returnNULL;pim_if_init(pim);pim->keep_alive_time=PIM
_KEEPALIVE_PERIOD;pim->rp_keep_alive_time=PIM_RP_KEEPALIVE_PERIOD;pim->vrf_id=vr
f->vrf_id;pim->vrf=vrf;pim->spt.switchover=PIM_SPT_IMMEDIATE;pim->spt.plist=NULL
;pim_msdp_init(pim,master);snprintf(hash_name,64,"PIM%sRPFHash",vrf->name);pim->
rpf_hash=hash_create_size(256,pim_rpf_hash_key,pim_rpf_equal,hash_name);if(PIM_D
EBUG_ZEBRA)zlog_debug("%s:NHTrpfhashinit",__PRETTY_FUNCTION__);pim->ssm_info=pim
_ssm_init();if(!pim->ssm_info){pim_instance_terminate(pim);returnNULL;}pim->stat
ic_routes=list_new();if(!pim->static_routes){zlog_err("%s%s:failure:static_route
s=list_new()",__FILE__,__PRETTY_FUNCTION__);pim_instance_terminate(pim);returnNU
LL;}pim->static_routes->del=(void(*)(void*))pim_static_route_free;pim->send_v6_s
econdary=1;if(vrf->vrf_id==VRF_DEFAULT)pimg=pim;pim_rp_init(pim);pim_oil_init(pi
m);pim_upstream_init(pim);pim->last_route_change_time=-1;returnpim;}structpim_in
stance*pim_get_pim_instance(vrf_id_tvrf_id){structvrf*vrf=vrf_lookup_by_id(vrf_i
d);if(vrf)returnvrf->info;returnNULL;}staticintpim_vrf_new(structvrf*vrf){struct
pim_instance*pim=pim_instance_init(vrf);zlog_debug("VRFCreated:%s(%u)",vrf->name
,vrf->vrf_id);if(pim==NULL){zlog_err("%s%s:pimclassinitfailure",__FILE__,__PRETT
Y_FUNCTION__);/**Wewillcrashandburnotherwise*/exit(1);}vrf->info=(void*)pim;if(v
rf->vrf_id==VRF_DEFAULT)pimg=pim;pim_ssmpingd_init(pim);return0;}staticintpim_vr
f_delete(structvrf*vrf){structpim_instance*pim=vrf->info;zlog_debug("VRFDeletion
:%s(%u)",vrf->name,vrf->vrf_id);pim_ssmpingd_destroy(pim);pim_instance_terminate
(pim);return0;}/**Codetoturnonthepiminstancethat*wehavecreatedwithnew*/staticint
pim_vrf_enable(structvrf*vrf){structpim_instance*pim=(structpim_instance*)vrf->i
nfo;zlog_debug("%s:for%s",__PRETTY_FUNCTION__,vrf->name);pim_mroute_socket_enabl
e(pim);return0;}staticintpim_vrf_disable(structvrf*vrf){/*Note:Thisisacallback,t
heVRFwillbedeletedbythecaller.*/return0;}staticintpim_vrf_config_write(structvty
*vty){structvrf*vrf;structpim_instance*pim;RB_FOREACH(vrf,vrf_name_head,&vrfs_by
_name){pim=vrf->info;if(!pim)continue;if(vrf->vrf_id!=VRF_DEFAULT)vty_frame(vty,
"vrf%s\n",vrf->name);pim_global_config_write_worker(pim,vty);if(vrf->vrf_id!=VRF
_DEFAULT)vty_endframe(vty,"!\n");}return0;}voidpim_vrf_init(void){vrf_init(pim_v
rf_new,pim_vrf_enable,pim_vrf_disable,pim_vrf_delete);vrf_cmd_init(pim_vrf_confi
g_write,&pimd_privs);}voidpim_vrf_terminate(void){vrf_terminate();}