/**PIMforQuagga*Copyright(C)2008EvertondaSilvaMarques**Thisprogramisfreesoftware
;youcanredistributeitand/ormodify*itunderthetermsoftheGNUGeneralPublicLicenseasp
ublishedby*theFreeSoftwareFoundation;eitherversion2oftheLicense,or*(atyouroption
)anylaterversion.**Thisprogramisdistributedinthehopethatitwillbeuseful,but*WITHO
UTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTIC
ULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldhavereceived
acopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;ifnot,w
ritetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-130
1USA*/#include<zebra.h>#include<stdio.h>#include<errno.h>#include<string.h>#incl
ude"log.h"#include"pim_str.h"voidpim_addr_dump(constchar*onfail,structprefix*p,c
har*buf,intbuf_size){intsave_errno=errno;if(!inet_ntop(p->family,&p->u.prefix,bu
f,buf_size)){zlog_warn("pim_addr_dump:inet_ntop(buf_size=%d):errno=%d:%s",buf_si
ze,errno,safe_strerror(errno));if(onfail)snprintf(buf,buf_size,"%s",onfail);}err
no=save_errno;}voidpim_inet4_dump(constchar*onfail,structin_addraddr,char*buf,in
tbuf_size){intsave_errno=errno;if(addr.s_addr==INADDR_ANY)strcpy(buf,"*");else{i
f(!inet_ntop(AF_INET,&addr,buf,buf_size)){zlog_warn("pim_inet4_dump:inet_ntop(AF
_INET,buf_size=%d):errno=%d:%s",buf_size,errno,safe_strerror(errno));if(onfail)s
nprintf(buf,buf_size,"%s",onfail);}}errno=save_errno;}char*pim_str_sg_dump(const
structprefix_sg*sg){charsrc_str[INET_ADDRSTRLEN];chargrp_str[INET_ADDRSTRLEN];st
aticcharsg_str[PIM_SG_LEN];pim_inet4_dump("<src?>",sg->src,src_str,sizeof(src_st
r));pim_inet4_dump("<grp?>",sg->grp,grp_str,sizeof(grp_str));snprintf(sg_str,PIM
_SG_LEN,"(%s,%s)",src_str,grp_str);returnsg_str;}char*pim_str_sg_set(conststruct
prefix_sg*sg,char*sg_str){charsrc_str[INET_ADDRSTRLEN];chargrp_str[INET_ADDRSTRL
EN];pim_inet4_dump("<src?>",sg->src,src_str,sizeof(src_str));pim_inet4_dump("<gr
p?>",sg->grp,grp_str,sizeof(grp_str));snprintf(sg_str,PIM_SG_LEN,"(%s,%s)",src_s
tr,grp_str);returnsg_str;}