/**IPMSDPforQuagga*Copyright(C)2016CumulusNetworks,Inc.**Thisprogramisfreesoftwa
re;youcanredistributeitand/ormodify*itunderthetermsoftheGNUGeneralPublicLicensea
spublishedby*theFreeSoftwareFoundation;eitherversion2oftheLicense,or*(atyouropti
on)anylaterversion.**Thisprogramisdistributedinthehopethatitwillbeuseful,but*WIT
HOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPART
ICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldhavereceiv
edacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;ifnot
,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-1
301USA*/#ifndefPIM_MSDP_H#definePIM_MSDP_Henumpim_msdp_peer_state{PIM_MSDP_DISAB
LED,PIM_MSDP_INACTIVE,PIM_MSDP_LISTEN,PIM_MSDP_CONNECTING,PIM_MSDP_ESTABLISHED};
/*SAandKATLVsareprocessed;restignored*/enumpim_msdp_tlv{PIM_MSDP_V4_SOURCE_ACTIV
E=1,PIM_MSDP_V4_SOURCE_ACTIVE_REQUEST,PIM_MSDP_V4_SOURCE_ACTIVE_RESPONSE,PIM_MSD
P_KEEPALIVE,PIM_MSDP_RESERVED,PIM_MSDP_TRACEROUTE_PROGRESS,PIM_MSDP_TRACEROUTE_R
EPLY,};/*MSDPerrorcodes*/enumpim_msdp_err{PIM_MSDP_ERR_NONE=0,PIM_MSDP_ERR_OOM=-
1,PIM_MSDP_ERR_PEER_EXISTS=-2,PIM_MSDP_ERR_MAX_MESH_GROUPS=-3,PIM_MSDP_ERR_NO_PE
ER=-4,PIM_MSDP_ERR_MG_MBR_EXISTS=-5,PIM_MSDP_ERR_NO_MG=-6,PIM_MSDP_ERR_NO_MG_MBR
=-7,PIM_MSDP_ERR_SIP_EQ_DIP=-8,};#definePIM_MSDP_STATE_STRLEN16#definePIM_MSDP_U
PTIME_STRLEN80#definePIM_MSDP_TIMER_STRLEN12#definePIM_MSDP_TCP_PORT639#definePI
M_MSDP_SOCKET_SNDBUF_SIZE65536enumpim_msdp_sa_flags{PIM_MSDP_SAF_NONE=0,/*Therea
retwocaseswherewecanpickupanactivesourcelocally-*1.WeareRPandgotasource-register
fromtheFHR*2.WeareRPandFHRandlearntanewdirectlyconnectedsourceona*DRinterface*/P
IM_MSDP_SAF_LOCAL=(1<<0),/*WegotthisintheMSDPSATLVfromapeer(andthispassedpeer-RP
F*checks)*/PIM_MSDP_SAF_PEER=(1<<1),PIM_MSDP_SAF_REF=(PIM_MSDP_SAF_LOCAL|PIM_MSD
P_SAF_PEER),PIM_MSDP_SAF_STALE=(1<<2),/*localentriescangetkickedouton*miscpimeve
ntssuchasRPchange*/PIM_MSDP_SAF_UP_DEL_IN_PROG=(1<<3)};structpim_msdp_sa{structp
im_instance*pim;structprefix_sgsg;charsg_str[PIM_SG_LEN];structin_addrrp;/*LastR
PaddressassociatedwiththisSA*/structin_addrpeer;/*lastpeerfromwhoweheardthisSA*/
enumpim_msdp_sa_flagsflags;/*rfc-3618ismissingdefaultvalueforSA-hold-down-Period
.pulled*thisnumberfromindustry-standards*/#definePIM_MSDP_SA_HOLD_TIME((3*60)+30
)structthread*sa_state_timer;//5.6int64_tuptime;structpim_upstream*up;};enumpim_
msdp_peer_flags{PIM_MSDP_PEERF_NONE=0,PIM_MSDP_PEERF_LISTENER=(1<<0),#definePIM_
MSDP_PEER_IS_LISTENER(mp)(mp->flags&PIM_MSDP_PEERF_LISTENER)PIM_MSDP_PEERF_SA_JU
ST_SENT=(1<<1)};structpim_msdp_peer{structpim_instance*pim;/*configuration*/stru
ctin_addrlocal;structin_addrpeer;char*mesh_group_name;charkey_str[INET_ADDRSTRLE
N];/*state*/enumpim_msdp_peer_statestate;enumpim_msdp_peer_flagsflags;/*TCPsocke
tinfo*/unionsockunionsu_local;unionsockunionsu_peer;intfd;/*protocoltimers*/#def
inePIM_MSDP_PEER_HOLD_TIME75structthread*hold_timer;//5.4#definePIM_MSDP_PEER_KA
_TIME60structthread*ka_timer;//5.5#definePIM_MSDP_PEER_CONNECT_RETRY_TIME30struc
tthread*cr_timer;//5.6/*packetthreadandbuffers*/uint32_tpacket_size;structstream
*ibuf;structstream_fifo*obuf;structthread*t_read;structthread*t_write;/*stats*/u
int32_tconn_attempts;uint32_test_flaps;uint32_tsa_cnt;/*numberofSAsattributedtot
hispeer*/#definePIM_MSDP_PEER_LAST_RESET_STR20charlast_reset[PIM_MSDP_PEER_LAST_
RESET_STR];/*packetstats*/uint32_tka_tx_cnt;uint32_tsa_tx_cnt;uint32_tka_rx_cnt;
uint32_tsa_rx_cnt;uint32_tunk_rx_cnt;/*timestamps*/int64_tuptime;};structpim_msd
p_mg_mbr{structin_addrmbr_ip;structpim_msdp_peer*mp;};/*PIMMSDPmesh-group*/struc
tpim_msdp_mg{char*mesh_group_name;structin_addrsrc_ip;uint32_tmbr_cnt;structlist
*mbr_list;};enumpim_msdp_flags{PIM_MSDPF_NONE=0,PIM_MSDPF_ENABLE=(1<<0),PIM_MSDP
F_LISTENER=(1<<1)};structpim_msdp_listener{intfd;unionsockunionsu;structthread*t
hread;};structpim_msdp{enumpim_msdp_flagsflags;structthread_master*master;struct
pim_msdp_listenerlistener;uint32_trejected_accepts;/*MSDPpeerinfo*/structhash*pe
er_hash;structlist*peer_list;/*MSDPactive-sourceinfo*/#definePIM_MSDP_SA_ADVERTI
SMENT_TIME60structthread*sa_adv_timer;//5.6structhash*sa_hash;structlist*sa_list
;uint32_tlocal_cnt;/*keepascratchpadforbuildingSATLVs*/structstream*work_obuf;st
ructin_addroriginator_id;/*currentlyonlyonemesh-groupissupported-sojuststashithe
re*/structpim_msdp_mg*mg;};#definePIM_MSDP_PEER_READ_ON(mp)\thread_add_read(mp->
pim->msdp.master,pim_msdp_read,mp,mp->fd,\&mp->t_read)#definePIM_MSDP_PEER_WRITE
_ON(mp)\thread_add_write(mp->pim->msdp.master,pim_msdp_write,mp,mp->fd,\&mp->t_w
rite)#definePIM_MSDP_PEER_READ_OFF(mp)THREAD_READ_OFF(mp->t_read)#definePIM_MSDP
_PEER_WRITE_OFF(mp)THREAD_WRITE_OFF(mp->t_write)//structpim_msdp*msdp;structpim_
instance;voidpim_msdp_init(structpim_instance*pim,structthread_master*master);vo
idpim_msdp_exit(structpim_instance*pim);enumpim_msdp_errpim_msdp_peer_add(struct
pim_instance*pim,structin_addrpeer,structin_addrlocal,constchar*mesh_group_name,
structpim_msdp_peer**mp_p);enumpim_msdp_errpim_msdp_peer_del(structpim_instance*
pim,structin_addrpeer_addr);char*pim_msdp_state_dump(enumpim_msdp_peer_statestat
e,char*buf,intbuf_size);structpim_msdp_peer*pim_msdp_peer_find(structpim_instanc
e*pim,structin_addrpeer_addr);voidpim_msdp_peer_established(structpim_msdp_peer*
mp);voidpim_msdp_peer_pkt_rxed(structpim_msdp_peer*mp);voidpim_msdp_peer_stop_tc
p_conn(structpim_msdp_peer*mp,boolchg_state);voidpim_msdp_peer_reset_tcp_conn(st
ructpim_msdp_peer*mp,constchar*rc_str);intpim_msdp_write(structthread*thread);ch
ar*pim_msdp_peer_key_dump(structpim_msdp_peer*mp,char*buf,intbuf_size,boollong_f
ormat);intpim_msdp_config_write(structvty*vty);intpim_msdp_config_write_helper(s
tructpim_instance*pim,structvty*vty,constchar*spaces);voidpim_msdp_peer_pkt_txed
(structpim_msdp_peer*mp);voidpim_msdp_sa_ref(structpim_instance*pim,structpim_ms
dp_peer*mp,structprefix_sg*sg,structin_addrrp);voidpim_msdp_sa_local_update(stru
ctpim_upstream*up);voidpim_msdp_sa_local_del(structpim_instance*pim,structprefix
_sg*sg);voidpim_msdp_i_am_rp_changed(structpim_instance*pim);boolpim_msdp_peer_r
pf_check(structpim_msdp_peer*mp,structin_addrrp);voidpim_msdp_up_join_state_chan
ged(structpim_instance*pim,structpim_upstream*xg_up);voidpim_msdp_up_del(structp
im_instance*pim,structprefix_sg*sg);enumpim_msdp_errpim_msdp_mg_mbr_add(structpi
m_instance*pim,constchar*mesh_group_name,structin_addrmbr_ip);enumpim_msdp_errpi
m_msdp_mg_mbr_del(structpim_instance*pim,constchar*mesh_group_name,structin_addr
mbr_ip);enumpim_msdp_errpim_msdp_mg_src_del(structpim_instance*pim,constchar*mes
h_group_name);enumpim_msdp_errpim_msdp_mg_src_add(structpim_instance*pim,constch
ar*mesh_group_name,structin_addrsrc_ip);enumpim_msdp_errpim_msdp_mg_del(structpi
m_instance*pim,constchar*mesh_group_name);#endif