/**PIMforQuagga*Copyright(C)2008EvertondaSilvaMarques**Thisprogramisfreesoftware
;youcanredistributeitand/ormodify*itunderthetermsoftheGNUGeneralPublicLicenseasp
ublishedby*theFreeSoftwareFoundation;eitherversion2oftheLicense,or*(atyouroption
)anylaterversion.**Thisprogramisdistributedinthehopethatitwillbeuseful,but*WITHO
UTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTIC
ULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldhavereceived
acopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;ifnot,w
ritetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-130
1USA*/#include<zebra.h>#include"log.h"#include"if.h"#include"pimd.h"#include"pim
_pim.h"#include"pim_str.h"#include"pim_tlv.h"#include"pim_util.h"#include"pim_he
llo.h"#include"pim_iface.h"#include"pim_neighbor.h"#include"pim_upstream.h"stati
cvoidon_trace(constchar*label,structinterface*ifp,structin_addrsrc){if(PIM_DEBUG
_PIM_TRACE){charsrc_str[INET_ADDRSTRLEN];pim_inet4_dump("<src?>",src,src_str,siz
eof(src_str));zlog_debug("%s:from%son%s",label,src_str,ifp->name);}}staticvoidtl
v_trace_bool(constchar*label,constchar*tlv_name,constchar*ifname,structin_addrsr
c_addr,intisset,intvalue){if(isset){charsrc_str[INET_ADDRSTRLEN];pim_inet4_dump(
"<src?>",src_addr,src_str,sizeof(src_str));zlog_debug("%s:PIMhellooptionfrom%son
interface%s:%s=%d",label,src_str,ifname,tlv_name,value);}}staticvoidtlv_trace_ui
nt16(constchar*label,constchar*tlv_name,constchar*ifname,structin_addrsrc_addr,i
ntisset,uint16_tvalue){if(isset){charsrc_str[INET_ADDRSTRLEN];pim_inet4_dump("<s
rc?>",src_addr,src_str,sizeof(src_str));zlog_debug("%s:PIMhellooptionfrom%sonint
erface%s:%s=%u",label,src_str,ifname,tlv_name,value);}}staticvoidtlv_trace_uint3
2(constchar*label,constchar*tlv_name,constchar*ifname,structin_addrsrc_addr,inti
sset,uint32_tvalue){if(isset){charsrc_str[INET_ADDRSTRLEN];pim_inet4_dump("<src?
>",src_addr,src_str,sizeof(src_str));zlog_debug("%s:PIMhellooptionfrom%soninterf
ace%s:%s=%u",label,src_str,ifname,tlv_name,value);}}staticvoidtlv_trace_uint32_h
ex(constchar*label,constchar*tlv_name,constchar*ifname,structin_addrsrc_addr,int
isset,uint32_tvalue){if(isset){charsrc_str[INET_ADDRSTRLEN];pim_inet4_dump("<src
?>",src_addr,src_str,sizeof(src_str));zlog_debug("%s:PIMhellooptionfrom%soninter
face%s:%s=%08x",label,src_str,ifname,tlv_name,value);}}#if0staticvoidtlv_trace(c
onstchar*label,constchar*tlv_name,constchar*ifname,structin_addrsrc_addr,intisse
t){if(isset){charsrc_str[INET_ADDRSTRLEN];pim_inet4_dump("<src?>",src_addr,src_s
tr,sizeof(src_str));zlog_debug("%s:PIMhellooptionfrom%soninterface%s:%s",label,s
rc_str,ifname,tlv_name);}}#endifstaticvoidtlv_trace_list(constchar*label,constch
ar*tlv_name,constchar*ifname,structin_addrsrc_addr,intisset,structlist*addr_list
){if(isset){charsrc_str[INET_ADDRSTRLEN];pim_inet4_dump("<src?>",src_addr,src_st
r,sizeof(src_str));zlog_debug("%s:PIMhellooptionfrom%soninterface%s:%ssize=%dlis
t=%p",label,src_str,ifname,tlv_name,addr_list?((int)listcount(addr_list)):-1,(vo
id*)addr_list);}}#defineFREE_ADDR_LIST\if(hello_option_addr_list){\list_delete_a
nd_null(&hello_option_addr_list);\}#defineFREE_ADDR_LIST_THEN_RETURN(code)\{\FRE
E_ADDR_LIST\return(code);\}intpim_hello_recv(structinterface*ifp,structin_addrsr
c_addr,uint8_t*tlv_buf,inttlv_buf_size){structpim_interface*pim_ifp;structpim_ne
ighbor*neigh;uint8_t*tlv_curr;uint8_t*tlv_pastend;pim_hello_optionshello_options
=0;/*bitarrayrecordingoptionsfound*/uint16_thello_option_holdtime=0;uint16_thell
o_option_propagation_delay=0;uint16_thello_option_override_interval=0;uint32_the
llo_option_dr_priority=0;uint32_thello_option_generation_id=0;structlist*hello_o
ption_addr_list=0;if(PIM_DEBUG_PIM_HELLO)on_trace(__PRETTY_FUNCTION__,ifp,src_ad
dr);pim_ifp=ifp->info;zassert(pim_ifp);++pim_ifp->pim_ifstat_hello_recv;/*ParseP
IMhelloTLVs*/zassert(tlv_buf_size>=0);tlv_curr=tlv_buf;tlv_pastend=tlv_buf+tlv_b
uf_size;while(tlv_curr<tlv_pastend){uint16_toption_type;uint16_toption_len;intre
main=tlv_pastend-tlv_curr;if(remain<PIM_TLV_MIN_SIZE){if(PIM_DEBUG_PIM_HELLO){ch
arsrc_str[INET_ADDRSTRLEN];pim_inet4_dump("<src?>",src_addr,src_str,sizeof(src_s
tr));zlog_debug("%s:shortPIMhelloTLVsize=%d<min=%dfrom%soninterface%s",__PRETTY_
FUNCTION__,remain,PIM_TLV_MIN_SIZE,src_str,ifp->name);}FREE_ADDR_LIST_THEN_RETUR
N(-1);}option_type=PIM_TLV_GET_TYPE(tlv_curr);tlv_curr+=PIM_TLV_TYPE_SIZE;option
_len=PIM_TLV_GET_LENGTH(tlv_curr);tlv_curr+=PIM_TLV_LENGTH_SIZE;if((tlv_curr+opt
ion_len)>tlv_pastend){if(PIM_DEBUG_PIM_HELLO){charsrc_str[INET_ADDRSTRLEN];pim_i
net4_dump("<src?>",src_addr,src_str,sizeof(src_str));zlog_debug("%s:longPIMhello
TLVtype=%dlength=%d>left=%tdfrom%soninterface%s",__PRETTY_FUNCTION__,option_type
,option_len,tlv_pastend-tlv_curr,src_str,ifp->name);}FREE_ADDR_LIST_THEN_RETURN(
-2);}if(PIM_DEBUG_PIM_HELLO){charsrc_str[INET_ADDRSTRLEN];pim_inet4_dump("<src?>
",src_addr,src_str,sizeof(src_str));zlog_debug("%s:parseleft_size=%d:PIMhelloTLV
type=%dlength=%dfrom%son%s",__PRETTY_FUNCTION__,remain,option_type,option_len,sr
c_str,ifp->name);}switch(option_type){casePIM_MSG_OPTION_TYPE_HOLDTIME:if(pim_tl
v_parse_holdtime(ifp->name,src_addr,&hello_options,&hello_option_holdtime,option
_len,tlv_curr)){FREE_ADDR_LIST_THEN_RETURN(-3);}break;casePIM_MSG_OPTION_TYPE_LA
N_PRUNE_DELAY:if(pim_tlv_parse_lan_prune_delay(ifp->name,src_addr,&hello_options
,&hello_option_propagation_delay,&hello_option_override_interval,option_len,tlv_
curr)){FREE_ADDR_LIST_THEN_RETURN(-4);}break;casePIM_MSG_OPTION_TYPE_DR_PRIORITY
:if(pim_tlv_parse_dr_priority(ifp->name,src_addr,&hello_options,&hello_option_dr
_priority,option_len,tlv_curr)){FREE_ADDR_LIST_THEN_RETURN(-5);}break;casePIM_MS
G_OPTION_TYPE_GENERATION_ID:if(pim_tlv_parse_generation_id(ifp->name,src_addr,&h
ello_options,&hello_option_generation_id,option_len,tlv_curr)){FREE_ADDR_LIST_TH
EN_RETURN(-6);}break;casePIM_MSG_OPTION_TYPE_ADDRESS_LIST:if(pim_tlv_parse_addr_
list(ifp->name,src_addr,&hello_options,&hello_option_addr_list,option_len,tlv_cu
rr)){return-7;}break;casePIM_MSG_OPTION_TYPE_DM_STATE_REFRESH:if(PIM_DEBUG_PIM_H
ELLO){charsrc_str[INET_ADDRSTRLEN];pim_inet4_dump("<src?>",src_addr,src_str,size
of(src_str));zlog_debug("%s:ignoringPIMhellodense-modestaterefreshTLVoptiontype=
%dlength=%dfrom%soninterface%s",__PRETTY_FUNCTION__,option_type,option_len,src_s
tr,ifp->name);}break;default:if(PIM_DEBUG_PIM_HELLO){charsrc_str[INET_ADDRSTRLEN
];pim_inet4_dump("<src?>",src_addr,src_str,sizeof(src_str));zlog_debug("%s:ignor
ingunknownPIMhelloTLVtype=%dlength=%dfrom%soninterface%s",__PRETTY_FUNCTION__,op
tion_type,option_len,src_str,ifp->name);}}tlv_curr+=option_len;}/*CheckreceivedP
IMhellooptions*/if(PIM_DEBUG_PIM_HELLO){tlv_trace_uint16(__PRETTY_FUNCTION__,"ho
ldtime",ifp->name,src_addr,PIM_OPTION_IS_SET(hello_options,PIM_OPTION_MASK_HOLDT
IME),hello_option_holdtime);tlv_trace_uint16(__PRETTY_FUNCTION__,"propagation_de
lay",ifp->name,src_addr,PIM_OPTION_IS_SET(hello_options,PIM_OPTION_MASK_LAN_PRUN
E_DELAY),hello_option_propagation_delay);tlv_trace_uint16(__PRETTY_FUNCTION__,"o
verride_interval",ifp->name,src_addr,PIM_OPTION_IS_SET(hello_options,PIM_OPTION_
MASK_LAN_PRUNE_DELAY),hello_option_override_interval);tlv_trace_bool(__PRETTY_FU
NCTION__,"can_disable_join_suppression",ifp->name,src_addr,PIM_OPTION_IS_SET(hel
lo_options,PIM_OPTION_MASK_LAN_PRUNE_DELAY),PIM_OPTION_IS_SET(hello_options,PIM_
OPTION_MASK_CAN_DISABLE_JOIN_SUPPRESSION));tlv_trace_uint32(__PRETTY_FUNCTION__,
"dr_priority",ifp->name,src_addr,PIM_OPTION_IS_SET(hello_options,PIM_OPTION_MASK
_DR_PRIORITY),hello_option_dr_priority);tlv_trace_uint32_hex(__PRETTY_FUNCTION__
,"generation_id",ifp->name,src_addr,PIM_OPTION_IS_SET(hello_options,PIM_OPTION_M
ASK_GENERATION_ID),hello_option_generation_id);tlv_trace_list(__PRETTY_FUNCTION_
_,"address_list",ifp->name,src_addr,PIM_OPTION_IS_SET(hello_options,PIM_OPTION_M
ASK_ADDRESS_LIST),hello_option_addr_list);}if(!PIM_OPTION_IS_SET(hello_options,P
IM_OPTION_MASK_HOLDTIME)){if(PIM_DEBUG_PIM_HELLO){charsrc_str[INET_ADDRSTRLEN];p
im_inet4_dump("<src?>",src_addr,src_str,sizeof(src_str));zlog_debug("%s:PIMhello
missingholdtimefrom%soninterface%s",__PRETTY_FUNCTION__,src_str,ifp->name);}}/*N
ewneighbor?*/neigh=pim_neighbor_find(ifp,src_addr);if(!neigh){/*Addasnewneighbor
*/neigh=pim_neighbor_add(ifp,src_addr,hello_options,hello_option_holdtime,hello_
option_propagation_delay,hello_option_override_interval,hello_option_dr_priority
,hello_option_generation_id,hello_option_addr_list,PIM_NEIGHBOR_SEND_DELAY);if(!
neigh){if(PIM_DEBUG_PIM_HELLO){charsrc_str[INET_ADDRSTRLEN];pim_inet4_dump("<src
?>",src_addr,src_str,sizeof(src_str));zlog_warn("%s:failurecreatingPIMneighbor%s
oninterface%s",__PRETTY_FUNCTION__,src_str,ifp->name);}FREE_ADDR_LIST_THEN_RETUR
N(-8);}/*actualaddrlisthasbeensavedunderneighbor*/return0;}/*ReceivedgenerationI
D?*/if(PIM_OPTION_IS_SET(hello_options,PIM_OPTION_MASK_GENERATION_ID)){/*GenIDmi
smatch?*/if(!PIM_OPTION_IS_SET(neigh->hello_options,PIM_OPTION_MASK_GENERATION_I
D)||(hello_option_generation_id!=neigh->generation_id)){/*GenIDmismatch,thenrepl
aceneighbor*/if(PIM_DEBUG_PIM_HELLO){charsrc_str[INET_ADDRSTRLEN];pim_inet4_dump
("<src?>",src_addr,src_str,sizeof(src_str));zlog_debug("%s:GenIdmismatchnew=%08x
old=%08x:replacingneighbor%son%s",__PRETTY_FUNCTION__,hello_option_generation_id
,neigh->generation_id,src_str,ifp->name);}pim_upstream_rpf_genid_changed(pim_ifp
->pim,neigh->source_addr);pim_neighbor_delete(ifp,neigh,"GenIDmismatch");neigh=p
im_neighbor_add(ifp,src_addr,hello_options,hello_option_holdtime,hello_option_pr
opagation_delay,hello_option_override_interval,hello_option_dr_priority,hello_op
tion_generation_id,hello_option_addr_list,PIM_NEIGHBOR_SEND_NOW);if(!neigh){if(P
IM_DEBUG_PIM_HELLO){charsrc_str[INET_ADDRSTRLEN];pim_inet4_dump("<src?>",src_add
r,src_str,sizeof(src_str));zlog_debug("%s:failurere-creatingPIMneighbor%soninter
face%s",__PRETTY_FUNCTION__,src_str,ifp->name);}FREE_ADDR_LIST_THEN_RETURN(-9);}
/*actualaddrlistissavedunderneighbor*/return0;}/*GenIdmismatch:replaceneighbor*/
}/*GenIdreceived*//*Updateexistingneighbor*/pim_neighbor_update(neigh,hello_opti
ons,hello_option_holdtime,hello_option_dr_priority,hello_option_addr_list);/*act
ualaddrlistissavedunderneighbor*/return0;}intpim_hello_build_tlv(structinterface
*ifp,uint8_t*tlv_buf,inttlv_buf_size,uint16_tholdtime,uint32_tdr_priority,uint32
_tgeneration_id,uint16_tpropagation_delay,uint16_toverride_interval,intcan_disab
le_join_suppression){uint8_t*curr=tlv_buf;uint8_t*pastend=tlv_buf+tlv_buf_size;u
int8_t*tmp;structpim_interface*pim_ifp=ifp->info;structpim_instance*pim=pim_ifp-
>pim;/**Appendoptions*//*Holdtime*/curr=pim_tlv_append_uint16(curr,pastend,PIM_M
SG_OPTION_TYPE_HOLDTIME,holdtime);if(!curr){if(PIM_DEBUG_PIM_HELLO){zlog_debug("
%s:couldnotsetPIMhelloHoldtimeoptionforinterface%s",__PRETTY_FUNCTION__,ifp->nam
e);}return-1;}/*LANPruneDelay*/tmp=pim_tlv_append_2uint16(curr,pastend,PIM_MSG_O
PTION_TYPE_LAN_PRUNE_DELAY,propagation_delay,override_interval);if(!tmp){if(PIM_
DEBUG_PIM_HELLO){zlog_debug("%s:couldnotsetPIMLANPruneDelayoptionforinterface%s"
,__PRETTY_FUNCTION__,ifp->name);}return-1;}if(can_disable_join_suppression){*((u
int8_t*)(curr)+4)|=0x80;/*enableTbit*/}curr=tmp;/*DRPriority*/curr=pim_tlv_appen
d_uint32(curr,pastend,PIM_MSG_OPTION_TYPE_DR_PRIORITY,dr_priority);if(!curr){if(
PIM_DEBUG_PIM_HELLO){zlog_debug("%s:couldnotsetPIMhelloDRPriorityoptionforinterf
ace%s",__PRETTY_FUNCTION__,ifp->name);}return-2;}/*GenerationID*/curr=pim_tlv_ap
pend_uint32(curr,pastend,PIM_MSG_OPTION_TYPE_GENERATION_ID,generation_id);if(!cu
rr){if(PIM_DEBUG_PIM_HELLO){zlog_debug("%s:couldnotsetPIMhelloGenerationIDoption
forinterface%s",__PRETTY_FUNCTION__,ifp->name);}return-3;}/*SecondaryAddressList
*/if(ifp->connected->count){curr=pim_tlv_append_addrlist_ucast(curr,pastend,ifp-
>connected,AF_INET);if(!curr){if(PIM_DEBUG_PIM_HELLO){zlog_debug("%s:couldnotset
PIMhellov4SecondaryAddressListoptionforinterface%s",__PRETTY_FUNCTION__,ifp->nam
e);}return-4;}if(pim->send_v6_secondary){curr=pim_tlv_append_addrlist_ucast(curr
,pastend,ifp->connected,AF_INET6);if(!curr){if(PIM_DEBUG_PIM_HELLO){zlog_debug("
%s:couldnotsentPIMhellov6secondaryAddressListoptionforinterface%s",__PRETTY_FUNC
TION__,ifp->name);}return-4;}}}returncurr-tlv_buf;}/*RFC4601:4.3.1.SendingHelloM
essagesThus,ifarouterneedstosendaJoin/PruneorAssertmessageonaninterfaceonwhichit
hasnotyetsentaHellomessagewiththecurrentlyconfiguredIPaddress,thenitMUSTimmediat
elysendtherelevantHellomessagewithoutwaitingfortheHelloTimertoexpire,followedbyt
heJoin/PruneorAssertmessage.*/voidpim_hello_require(structinterface*ifp){structp
im_interface*pim_ifp;zassert(ifp);pim_ifp=ifp->info;zassert(pim_ifp);if(pim_ifp-
>pim_ifstat_hello_sent)return;pim_hello_restart_now(ifp);/*Sendhelloandrestartti
mer*/}