/*ripdmemorytypedefinitions**Copyright(C)2015DavidLamparter**ThisfileispartofQua
gga.**Quaggaisfreesoftware;youcanredistributeitand/ormodifyit*underthetermsofthe
GNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eitherversion2,or
(atyouroption)any*laterversion.**Quaggaisdistributedinthehopethatitwillbeuseful,
but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSF
ORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldhav
ereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYIN
G;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA
02110-1301USA*/#ifdefHAVE_CONFIG_H#include"config.h"#endif#include"rip_memory.h"
DEFINE_MGROUP(RIPD,"ripd")DEFINE_MTYPE(RIPD,RIP,"RIPstructure")DEFINE_MTYPE(RIPD
,RIP_INFO,"RIProuteinfo")DEFINE_MTYPE(RIPD,RIP_INTERFACE,"RIPinterface")DEFINE_M
TYPE(RIPD,RIP_PEER,"RIPpeer")DEFINE_MTYPE(RIPD,RIP_OFFSET_LIST,"RIPoffsetlist")D
EFINE_MTYPE(RIPD,RIP_DISTANCE,"RIPdistance")