/*RIPSNMPsupport*Copyright(C)1999KunihiroIshiguro<kunihiro@zebra.org>**Thisfilei
spartofGNUZebra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodifyit*unde
rthetermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eit
herversion2,or(atyouroption)any*laterversion.**GNUZebraisdistributedinthehopetha
titwillbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTA
BILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetail
s.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;
seethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,Fift
hFloor,Boston,MA02110-1301USA*/#include<zebra.h>#include<net-snmp/net-snmp-confi
g.h>#include<net-snmp/net-snmp-includes.h>#include"if.h"#include"vrf.h"#include"
log.h"#include"prefix.h"#include"command.h"#include"table.h"#include"smux.h"#inc
lude"libfrr.h"#include"version.h"#include"ripd/ripd.h"/*RIPv2-MIB.*/#defineRIPV2
MIB1,3,6,1,2,1,23/*RIPv2-MIBrip2Globalsvalues.*/#defineRIP2GLOBALROUTECHANGES1#d
efineRIP2GLOBALQUERIES2/*RIPv2-MIBrip2IfStatEntry.*/#defineRIP2IFSTATENTRY1/*RIP
v2-MIBrip2IfStatTable.*/#defineRIP2IFSTATADDRESS1#defineRIP2IFSTATRCVBADPACKETS2
#defineRIP2IFSTATRCVBADROUTES3#defineRIP2IFSTATSENTUPDATES4#defineRIP2IFSTATSTAT
US5/*RIPv2-MIBrip2IfConfTable.*/#defineRIP2IFCONFADDRESS1#defineRIP2IFCONFDOMAIN
2#defineRIP2IFCONFAUTHTYPE3#defineRIP2IFCONFAUTHKEY4#defineRIP2IFCONFSEND5#defin
eRIP2IFCONFRECEIVE6#defineRIP2IFCONFDEFAULTMETRIC7#defineRIP2IFCONFSTATUS8#defin
eRIP2IFCONFSRCADDRESS9/*RIPv2-MIBrip2PeerTable.*/#defineRIP2PEERADDRESS1#defineR
IP2PEERDOMAIN2#defineRIP2PEERLASTUPDATE3#defineRIP2PEERVERSION4#defineRIP2PEERRC
VBADPACKETS5#defineRIP2PEERRCVBADROUTES6/*SNMPvaluehack.*/#defineCOUNTERASN_COUN
TER#defineINTEGERASN_INTEGER#defineTIMETICKSASN_TIMETICKS#defineIPADDRESSASN_IPA
DDRESS#defineSTRINGASN_OCTET_STR/*DefineSNMPlocalvariables.*/SNMP_LOCAL_VARIABLE
S/*RIP-MIBinstances.*/staticoidrip_oid[]={RIPV2MIB};/*Interfacecachetablesortedb
yinterface'saddress.*/staticstructroute_table*rip_ifaddr_table;/*Hookfunctions.*
/staticuint8_t*rip2Globals(structvariable*,oid[],size_t*,int,size_t*,WriteMethod
**);staticuint8_t*rip2IfStatEntry(structvariable*,oid[],size_t*,int,size_t*,Writ
eMethod**);staticuint8_t*rip2IfConfAddress(structvariable*,oid[],size_t*,int,siz
e_t*,WriteMethod**);staticuint8_t*rip2PeerTable(structvariable*,oid[],size_t*,in
t,size_t*,WriteMethod**);staticstructvariablerip_variables[]={/*RIPGlobalCounter
s.*/{RIP2GLOBALROUTECHANGES,COUNTER,RONLY,rip2Globals,2,{1,1}},{RIP2GLOBALQUERIE
S,COUNTER,RONLY,rip2Globals,2,{1,2}},/*RIPInterfaceTables.*/{RIP2IFSTATADDRESS,I
PADDRESS,RONLY,rip2IfStatEntry,3,{2,1,1}},{RIP2IFSTATRCVBADPACKETS,COUNTER,RONLY
,rip2IfStatEntry,3,{2,1,2}},{RIP2IFSTATRCVBADROUTES,COUNTER,RONLY,rip2IfStatEntr
y,3,{2,1,3}},{RIP2IFSTATSENTUPDATES,COUNTER,RONLY,rip2IfStatEntry,3,{2,1,4}},{RI
P2IFSTATSTATUS,COUNTER,RWRITE,rip2IfStatEntry,3,{2,1,5}},{RIP2IFCONFADDRESS,IPAD
DRESS,RONLY,rip2IfConfAddress,/*RIPInterfaceConfigurationTable.*/3,{3,1,1}},{RIP
2IFCONFDOMAIN,STRING,RONLY,rip2IfConfAddress,3,{3,1,2}},{RIP2IFCONFAUTHTYPE,COUN
TER,RONLY,rip2IfConfAddress,3,{3,1,3}},{RIP2IFCONFAUTHKEY,STRING,RONLY,rip2IfCon
fAddress,3,{3,1,4}},{RIP2IFCONFSEND,COUNTER,RONLY,rip2IfConfAddress,3,{3,1,5}},{
RIP2IFCONFRECEIVE,COUNTER,RONLY,rip2IfConfAddress,3,{3,1,6}},{RIP2IFCONFDEFAULTM
ETRIC,COUNTER,RONLY,rip2IfConfAddress,3,{3,1,7}},{RIP2IFCONFSTATUS,COUNTER,RONLY
,rip2IfConfAddress,3,{3,1,8}},{RIP2IFCONFSRCADDRESS,IPADDRESS,RONLY,rip2IfConfAd
dress,3,{3,1,9}},{RIP2PEERADDRESS,IPADDRESS,RONLY,rip2PeerTable,/*RIPPeerTable.*
/3,{4,1,1}},{RIP2PEERDOMAIN,STRING,RONLY,rip2PeerTable,3,{4,1,2}},{RIP2PEERLASTU
PDATE,TIMETICKS,RONLY,rip2PeerTable,3,{4,1,3}},{RIP2PEERVERSION,INTEGER,RONLY,ri
p2PeerTable,3,{4,1,4}},{RIP2PEERRCVBADPACKETS,COUNTER,RONLY,rip2PeerTable,3,{4,1
,5}},{RIP2PEERRCVBADROUTES,COUNTER,RONLY,rip2PeerTable,3,{4,1,6}}};externstructt
hread_master*master;staticuint8_t*rip2Globals(structvariable*v,oidname[],size_t*
length,intexact,size_t*var_len,WriteMethod**write_method){if(smux_header_generic
(v,name,length,exact,var_len,write_method)==MATCH_FAILED)returnNULL;/*Retrunglob
alcounter.*/switch(v->magic){caseRIP2GLOBALROUTECHANGES:returnSNMP_INTEGER(rip_g
lobal_route_changes);break;caseRIP2GLOBALQUERIES:returnSNMP_INTEGER(rip_global_q
ueries);break;default:returnNULL;break;}returnNULL;}staticintrip_snmp_ifaddr_add
(structconnected*ifc){structinterface*ifp=ifc->ifp;structprefix*p;structroute_no
de*rn;p=ifc->address;if(p->family!=AF_INET)return0;rn=route_node_get(rip_ifaddr_
table,p);rn->info=ifp;return0;}staticintrip_snmp_ifaddr_del(structconnected*ifc)
{structinterface*ifp=ifc->ifp;structprefix*p;structroute_node*rn;structinterface
*i;p=ifc->address;if(p->family!=AF_INET)return0;rn=route_node_lookup(rip_ifaddr_
table,p);if(!rn)return0;i=rn->info;if(rn&&!strncmp(i->name,ifp->name,INTERFACE_N
AMSIZ)){rn->info=NULL;route_unlock_node(rn);route_unlock_node(rn);}return0;}stat
icstructinterface*rip_ifaddr_lookup_next(structin_addr*addr){structprefix_ipv4p;
structroute_node*rn;structinterface*ifp;p.family=AF_INET;p.prefixlen=IPV4_MAX_BI
TLEN;p.prefix=*addr;rn=route_node_get(rip_ifaddr_table,(structprefix*)&p);for(rn
=route_next(rn);rn;rn=route_next(rn))if(rn->info)break;if(rn&&rn->info){ifp=rn->
info;*addr=rn->p.u.prefix4;route_unlock_node(rn);returnifp;}returnNULL;}staticst
ructinterface*rip2IfLookup(structvariable*v,oidname[],size_t*length,structin_add
r*addr,intexact){intlen;structinterface*ifp;if(exact){/*Checkthelength.*/if(*len
gth-v->namelen!=sizeof(structin_addr))returnNULL;oid2in_addr(name+v->namelen,siz
eof(structin_addr),addr);returnif_lookup_exact_address((void*)addr,AF_INET,VRF_D
EFAULT);}else{len=*length-v->namelen;if(len>4)len=4;oid2in_addr(name+v->namelen,
len,addr);ifp=rip_ifaddr_lookup_next(addr);if(ifp==NULL)returnNULL;oid_copy_addr
(name+v->namelen,addr,sizeof(structin_addr));*length=v->namelen+sizeof(structin_
addr);returnifp;}returnNULL;}staticstructrip_peer*rip2PeerLookup(structvariable*
v,oidname[],size_t*length,structin_addr*addr,intexact){intlen;structrip_peer*pee
r;if(exact){/*Checkthelength.*/if(*length-v->namelen!=sizeof(structin_addr)+1)re
turnNULL;oid2in_addr(name+v->namelen,sizeof(structin_addr),addr);peer=rip_peer_l
ookup(addr);if(peer->domain==(int)name[v->namelen+sizeof(structin_addr)])returnp
eer;returnNULL;}else{len=*length-v->namelen;if(len>4)len=4;oid2in_addr(name+v->n
amelen,len,addr);len=*length-v->namelen;peer=rip_peer_lookup(addr);if(peer){if((
len<(int)sizeof(structin_addr)+1)||(peer->domain>(int)name[v->namelen+sizeof(str
uctin_addr)])){oid_copy_addr(name+v->namelen,&peer->addr,sizeof(structin_addr));
name[v->namelen+sizeof(structin_addr)]=peer->domain;*length=sizeof(structin_addr
)+v->namelen+1;returnpeer;}}peer=rip_peer_lookup_next(addr);if(!peer)returnNULL;
oid_copy_addr(name+v->namelen,&peer->addr,sizeof(structin_addr));name[v->namelen
+sizeof(structin_addr)]=peer->domain;*length=sizeof(structin_addr)+v->namelen+1;
returnpeer;}returnNULL;}staticuint8_t*rip2IfStatEntry(structvariable*v,oidname[]
,size_t*length,intexact,size_t*var_len,WriteMethod**write_method){structinterfac
e*ifp;structrip_interface*ri;staticstructin_addraddr;staticlongvalid=SNMP_VALID;
if(smux_header_table(v,name,length,exact,var_len,write_method)==MATCH_FAILED)ret
urnNULL;memset(&addr,0,sizeof(structin_addr));/*Lookupinterface.*/ifp=rip2IfLook
up(v,name,length,&addr,exact);if(!ifp)returnNULL;/*Fetchrip_interfaceinformation
.*/ri=ifp->info;switch(v->magic){caseRIP2IFSTATADDRESS:returnSNMP_IPADDRESS(addr
);break;caseRIP2IFSTATRCVBADPACKETS:*var_len=sizeof(long);return(uint8_t*)&ri->r
ecv_badpackets;caseRIP2IFSTATRCVBADROUTES:*var_len=sizeof(long);return(uint8_t*)
&ri->recv_badroutes;caseRIP2IFSTATSENTUPDATES:*var_len=sizeof(long);return(uint8
_t*)&ri->sent_updates;caseRIP2IFSTATSTATUS:*var_len=sizeof(long);v->type=ASN_INT
EGER;return(uint8_t*)&valid;default:returnNULL;}returnNULL;}staticlongrip2IfConf
Send(structrip_interface*ri){#definedoNotSend1#defineripVersion12#definerip1Comp
atible3#defineripVersion24#defineripV1Demand5#defineripV2Demand6if(!ri->running)
returndoNotSend;if(ri->ri_send&RIPv2)returnripVersion2;elseif(ri->ri_send&RIPv1)
returnripVersion1;elseif(rip){if(rip->version_send==RIPv2)returnripVersion2;else
if(rip->version_send==RIPv1)returnripVersion1;}returndoNotSend;}staticlongrip2If
ConfReceive(structrip_interface*ri){#definerip11#definerip22#definerip1OrRip23#d
efinedoNotReceive4intrecvv;if(!ri->running)returndoNotReceive;recvv=(ri->ri_rece
ive==RI_RIP_UNSPEC)?rip->version_recv:ri->ri_receive;if(recvv==RI_RIP_VERSION_1_
AND_2)returnrip1OrRip2;elseif(recvv&RIPv2)returnrip2;elseif(recvv&RIPv1)returnri
p1;elsereturndoNotReceive;}staticuint8_t*rip2IfConfAddress(structvariable*v,oidn
ame[],size_t*length,intexact,size_t*val_len,WriteMethod**write_method){staticstr
uctin_addraddr;staticlongvalid=SNMP_INVALID;staticlongdomain=0;staticlongconfig=
0;staticunsignedintauth=0;structinterface*ifp;structrip_interface*ri;if(smux_hea
der_table(v,name,length,exact,val_len,write_method)==MATCH_FAILED)returnNULL;mem
set(&addr,0,sizeof(structin_addr));/*Lookupinterface.*/ifp=rip2IfLookup(v,name,l
ength,&addr,exact);if(!ifp)returnNULL;/*Fetchrip_interfaceinformation.*/ri=ifp->
info;switch(v->magic){caseRIP2IFCONFADDRESS:*val_len=sizeof(structin_addr);retur
n(uint8_t*)&addr;caseRIP2IFCONFDOMAIN:*val_len=2;return(uint8_t*)&domain;caseRIP
2IFCONFAUTHTYPE:auth=ri->auth_type;*val_len=sizeof(long);v->type=ASN_INTEGER;ret
urn(uint8_t*)&auth;caseRIP2IFCONFAUTHKEY:*val_len=0;return(uint8_t*)&domain;case
RIP2IFCONFSEND:config=rip2IfConfSend(ri);*val_len=sizeof(long);v->type=ASN_INTEG
ER;return(uint8_t*)&config;caseRIP2IFCONFRECEIVE:config=rip2IfConfReceive(ri);*v
al_len=sizeof(long);v->type=ASN_INTEGER;return(uint8_t*)&config;caseRIP2IFCONFDE
FAULTMETRIC:*val_len=sizeof(long);v->type=ASN_INTEGER;return(uint8_t*)&ifp->metr
ic;caseRIP2IFCONFSTATUS:*val_len=sizeof(long);v->type=ASN_INTEGER;return(uint8_t
*)&valid;caseRIP2IFCONFSRCADDRESS:*val_len=sizeof(structin_addr);return(uint8_t*
)&addr;default:returnNULL;}returnNULL;}staticuint8_t*rip2PeerTable(structvariabl
e*v,oidname[],size_t*length,intexact,size_t*val_len,WriteMethod**write_method){s
taticstructin_addraddr;staticintdomain=0;staticintversion;/*statictime_tuptime;*
/structrip_peer*peer;if(smux_header_table(v,name,length,exact,val_len,write_meth
od)==MATCH_FAILED)returnNULL;memset(&addr,0,sizeof(structin_addr));/*Lookupinter
face.*/peer=rip2PeerLookup(v,name,length,&addr,exact);if(!peer)returnNULL;switch
(v->magic){caseRIP2PEERADDRESS:*val_len=sizeof(structin_addr);return(uint8_t*)&p
eer->addr;caseRIP2PEERDOMAIN:*val_len=2;return(uint8_t*)&domain;caseRIP2PEERLAST
UPDATE:#if0/*Wedon'tknowtheSNMPagentstartuptime.Wehavetwochoiceshere:*-assumerip
dstartuptimeequalsSNMPagentstartuptime*-don'tsupportthisvariable,atall*Currently
,wedothelatter...*/*val_len=sizeof(time_t);uptime=peer->uptime;/*now-snmp_agent_
startup-peer->uptime*/return(uint8_t*)&uptime;#elsereturn(uint8_t*)NULL;#endifca
seRIP2PEERVERSION:*val_len=sizeof(int);version=peer->version;return(uint8_t*)&ve
rsion;caseRIP2PEERRCVBADPACKETS:*val_len=sizeof(int);return(uint8_t*)&peer->recv
_badpackets;caseRIP2PEERRCVBADROUTES:*val_len=sizeof(int);return(uint8_t*)&peer-
>recv_badroutes;default:returnNULL;}returnNULL;}/*RegisterRIPv2-MIB.*/staticintr
ip_snmp_init(structthread_master*master){rip_ifaddr_table=route_table_init();smu
x_init(master);REGISTER_MIB("mibII/rip",rip_variables,variable,rip_oid);return0;
}staticintrip_snmp_module_init(void){hook_register(rip_ifaddr_add,rip_snmp_ifadd
r_add);hook_register(rip_ifaddr_del,rip_snmp_ifaddr_del);hook_register(frr_late_
init,rip_snmp_init);return0;}FRR_MODULE_SETUP(.name="ripd_snmp",.version=FRR_VER
SION,.description="ripdAgentXSNMPmodule",.init=rip_snmp_module_init,)