/*RIPversion1and2.*Copyright(C)20056WIND<alain.ritoux@6wind.com>*Copyright(C)199
7,98,99KunihiroIshiguro<kunihiro@zebra.org>**ThisfileispartofGNUZebra.**GNUZebra
isfreesoftware;youcanredistributeitand/ormodifyit*underthetermsoftheGNUGeneralPu
blicLicenseaspublishedbythe*FreeSoftwareFoundation;eitherversion2,or(atyouroptio
n)any*laterversion.**GNUZebraisdistributedinthehopethatitwillbeuseful,but*WITHOU
TANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTICU
LARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldhavereceiveda
copyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;ifnot,wr
itetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-1301
USA*/#include<zebra.h>#include"vrf.h"#include"if.h"#include"command.h"#include"p
refix.h"#include"table.h"#include"thread.h"#include"memory.h"#include"log.h"#inc
lude"stream.h"#include"filter.h"#include"sockunion.h"#include"sockopt.h"#include
"routemap.h"#include"if_rmap.h"#include"plist.h"#include"distribute.h"#include"m
d5.h"#include"keychain.h"#include"privs.h"#include"ripd/ripd.h"#include"ripd/rip
_debug.h"DEFINE_QOBJ_TYPE(rip)/*UDPreceivebuffersize*/#defineRIP_UDP_RCV_BUF4160
0/*RIPStructure.*/structrip*rip=NULL;/*RIPneighboraddresstable.*/structroute_tab
le*rip_neighbor_table;/*RIProutechanges.*/longrip_global_route_changes=0;/*RIPqu
eries.*/longrip_global_queries=0;/*Prototypes.*/staticvoidrip_event(enumrip_even
t,int);staticvoidrip_output_process(structconnected*,structsockaddr_in*,int,uint
8_t);staticintrip_triggered_update(structthread*);staticintrip_update_jitter(uns
ignedlong);/*RIPoutputroutestype.*/enum{rip_all_route,rip_changed_route};/*RIPco
mmandstrings.*/staticconststructmessagerip_msg[]={{RIP_REQUEST,"REQUEST"},{RIP_R
ESPONSE,"RESPONSE"},{RIP_TRACEON,"TRACEON"},{RIP_TRACEOFF,"TRACEOFF"},{RIP_POLL,
"POLL"},{RIP_POLL_ENTRY,"POLLENTRY"},{0}};/*Utilityfunctiontosetboradcastoptiont
othesocket.*/staticintsockopt_broadcast(intsock){intret;inton=1;ret=setsockopt(s
ock,SOL_SOCKET,SO_BROADCAST,(char*)&on,sizeofon);if(ret<0){zlog_warn("can'tsetso
ckoptSO_BROADCASTtosocket%d",sock);return-1;}return0;}staticintrip_route_rte(str
uctrip_info*rinfo){return(rinfo->type==ZEBRA_ROUTE_RIP&&rinfo->sub_type==RIP_ROU
TE_RTE);}staticstructrip_info*rip_info_new(void){returnXCALLOC(MTYPE_RIP_INFO,si
zeof(structrip_info));}voidrip_info_free(structrip_info*rinfo){XFREE(MTYPE_RIP_I
NFO,rinfo);}/*RIProutegarbagecollecttimer.*/staticintrip_garbage_collect(structt
hread*t){structrip_info*rinfo;structroute_node*rp;rinfo=THREAD_ARG(t);rinfo->t_g
arbage_collect=NULL;/*Offtimeouttimer.*/RIP_TIMER_OFF(rinfo->t_timeout);/*Getrou
te_nodepointer.*/rp=rinfo->rp;/*Unlockroute_node.*/listnode_delete(rp->info,rinf
o);if(list_isempty((structlist*)rp->info)){list_delete_and_null((structlist**)&r
p->info);route_unlock_node(rp);}/*FreeRIProutinginformation.*/rip_info_free(rinf
o);return0;}staticvoidrip_timeout_update(structrip_info*rinfo);/*Addnewroutetoth
eECMPlist.*RETURN:thenewentryaddedinthelist,orNULLifitisnotthefirst*entryandECMP
isnotallowed.*/structrip_info*rip_ecmp_add(structrip_info*rinfo_new){structroute
_node*rp=rinfo_new->rp;structrip_info*rinfo=NULL;structlist*list=NULL;if(rp->inf
o==NULL)rp->info=list_new();list=(structlist*)rp->info;/*IfECMPisnotallowedandso
meentryalreadyexistsinthelist,*donothing.*/if(listcount(list)&&!rip->ecmp)return
NULL;rinfo=rip_info_new();memcpy(rinfo,rinfo_new,sizeof(structrip_info));listnod
e_add(list,rinfo);if(rip_route_rte(rinfo)){rip_timeout_update(rinfo);rip_zebra_i
pv4_add(rp);}/*Settheroutechangeflagonthefirstentry.*/rinfo=listgetdata(listhead
(list));SET_FLAG(rinfo->flags,RIP_RTF_CHANGED);/*Signaltheoutputprocesstotrigger
anupdate(seesection2.5).*/rip_event(RIP_TRIGGERED_UPDATE,0);returnrinfo;}/*Repla
cetheECMPlistwiththenewroute.*RETURN:thenewentryaddedinthelist*/structrip_info*r
ip_ecmp_replace(structrip_info*rinfo_new){structroute_node*rp=rinfo_new->rp;stru
ctlist*list=(structlist*)rp->info;structrip_info*rinfo=NULL,*tmp_rinfo=NULL;stru
ctlistnode*node=NULL,*nextnode=NULL;if(list==NULL||listcount(list)==0)returnrip_
ecmp_add(rinfo_new);/*Getthefirstentry*/rinfo=listgetdata(listhead(list));/*Lear
ntroutereplacedbyalocalone.Deleteitfromzebra.*/if(rip_route_rte(rinfo)&&!rip_rou
te_rte(rinfo_new))if(CHECK_FLAG(rinfo->flags,RIP_RTF_FIB))rip_zebra_ipv4_delete(
rp);/*Re-usethefirstentry,anddeletetheothers.*/for(ALL_LIST_ELEMENTS(list,node,n
extnode,tmp_rinfo))if(tmp_rinfo!=rinfo){RIP_TIMER_OFF(tmp_rinfo->t_timeout);RIP_
TIMER_OFF(tmp_rinfo->t_garbage_collect);list_delete_node(list,node);rip_info_fre
e(tmp_rinfo);}RIP_TIMER_OFF(rinfo->t_timeout);RIP_TIMER_OFF(rinfo->t_garbage_col
lect);memcpy(rinfo,rinfo_new,sizeof(structrip_info));if(rip_route_rte(rinfo)){ri
p_timeout_update(rinfo);/*TheADDmessageimpliesanupdate.*/rip_zebra_ipv4_add(rp);
}/*Settheroutechangeflag.*/SET_FLAG(rinfo->flags,RIP_RTF_CHANGED);/*Signaltheout
putprocesstotriggeranupdate(seesection2.5).*/rip_event(RIP_TRIGGERED_UPDATE,0);r
eturnrinfo;}/*DeleteoneroutefromtheECMPlist.*RETURN:*null-theentryisfreed,andoth
erentriesexistinthelist*theentry-theentryisthelastoneinthelist;itsmetricisset*to
INFINITY,andthegarbagecollectorisstartedforit*/structrip_info*rip_ecmp_delete(st
ructrip_info*rinfo){structroute_node*rp=rinfo->rp;structlist*list=(structlist*)r
p->info;RIP_TIMER_OFF(rinfo->t_timeout);if(listcount(list)>1){/*SomeotherECMPent
riesstillexist.Justdeletethisentry.*/RIP_TIMER_OFF(rinfo->t_garbage_collect);lis
tnode_delete(list,rinfo);if(rip_route_rte(rinfo)&&CHECK_FLAG(rinfo->flags,RIP_RT
F_FIB))/*TheADDmessageimpliestheupdate.*/rip_zebra_ipv4_add(rp);rip_info_free(ri
nfo);rinfo=NULL;}else{assert(rinfo==listgetdata(listhead(list)));/*Thisistheonly
entryleftinthelist.Wemustkeepitin*thelistforgarbagecollectiontime,withINFINITYme
tric.*/rinfo->metric=RIP_METRIC_INFINITY;RIP_TIMER_ON(rinfo->t_garbage_collect,r
ip_garbage_collect,rip->garbage_time);if(rip_route_rte(rinfo)&&CHECK_FLAG(rinfo-
>flags,RIP_RTF_FIB))rip_zebra_ipv4_delete(rp);}/*Settheroutechangeflagonthefirst
entry.*/rinfo=listgetdata(listhead(list));SET_FLAG(rinfo->flags,RIP_RTF_CHANGED)
;/*Signaltheoutputprocesstotriggeranupdate(seesection2.5).*/rip_event(RIP_TRIGGE
RED_UPDATE,0);returnrinfo;}/*TimeoutRIProutes.*/staticintrip_timeout(structthrea
d*t){rip_ecmp_delete((structrip_info*)THREAD_ARG(t));return0;}staticvoidrip_time
out_update(structrip_info*rinfo){if(rinfo->metric!=RIP_METRIC_INFINITY){RIP_TIME
R_OFF(rinfo->t_timeout);RIP_TIMER_ON(rinfo->t_timeout,rip_timeout,rip->timeout_t
ime);}}staticintrip_filter(intrip_distribute,structprefix_ipv4*p,structrip_inter
face*ri){structdistribute*dist;structaccess_list*alist;structprefix_list*plist;i
ntdistribute=rip_distribute==RIP_FILTER_OUT?DISTRIBUTE_V4_OUT:DISTRIBUTE_V4_IN;c
onstchar*inout=rip_distribute==RIP_FILTER_OUT?"out":"in";/*Inputdistribute-listf
iltering.*/if(ri->list[rip_distribute]){if(access_list_apply(ri->list[rip_distri
bute],(structprefix*)p)==FILTER_DENY){if(IS_RIP_DEBUG_PACKET)zlog_debug("%s/%dfi
lteredbydistribute%s",inet_ntoa(p->prefix),p->prefixlen,inout);return-1;}}if(ri-
>prefix[rip_distribute]){if(prefix_list_apply(ri->prefix[rip_distribute],(struct
prefix*)p)==PREFIX_DENY){if(IS_RIP_DEBUG_PACKET)zlog_debug("%s/%dfilteredbyprefi
x-list%s",inet_ntoa(p->prefix),p->prefixlen,inout);return-1;}}/*Allinterfacefilt
ercheck.*/dist=distribute_lookup(NULL);if(dist){if(dist->list[distribute]){alist
=access_list_lookup(AFI_IP,dist->list[distribute]);if(alist){if(access_list_appl
y(alist,(structprefix*)p)==FILTER_DENY){if(IS_RIP_DEBUG_PACKET)zlog_debug("%s/%d
filteredbydistribute%s",inet_ntoa(p->prefix),p->prefixlen,inout);return-1;}}}if(
dist->prefix[distribute]){plist=prefix_list_lookup(AFI_IP,dist->prefix[distribut
e]);if(plist){if(prefix_list_apply(plist,(structprefix*)p)==PREFIX_DENY){if(IS_R
IP_DEBUG_PACKET)zlog_debug("%s/%dfilteredbyprefix-list%s",inet_ntoa(p->prefix),p
->prefixlen,inout);return-1;}}}}return0;}/*Checknexthopaddressvalidity.*/statici
ntrip_nexthop_check(structin_addr*addr){structvrf*vrf=vrf_lookup_by_id(VRF_DEFAU
LT);structinterface*ifp;structlistnode*cnode;structconnected*ifc;structprefix*p;
/*Ifnexthopaddressmatcheslocalconfiguredaddressthenitisinvalidnexthop.*/FOR_ALL_
INTERFACES(vrf,ifp){for(ALL_LIST_ELEMENTS_RO(ifp->connected,cnode,ifc)){p=ifc->a
ddress;if(p->family==AF_INET&&IPV4_ADDR_SAME(&p->u.prefix4,addr))return-1;}}retu
rn0;}/*RIPaddroutetoroutingtable.*/staticvoidrip_rte_process(structrte*rte,struc
tsockaddr_in*from,structinterface*ifp){intret;structprefix_ipv4p;structroute_nod
e*rp;structrip_info*rinfo=NULL,newinfo;structrip_interface*ri;structin_addr*next
hop;intsame=0;unsignedcharold_dist,new_dist;structlist*list=NULL;structlistnode*
node=NULL;/*Makeprefixstructure.*/memset(&p,0,sizeof(structprefix_ipv4));p.famil
y=AF_INET;p.prefix=rte->prefix;p.prefixlen=ip_masklen(rte->mask);/*Makesuremaski
sapplied.*/apply_mask_ipv4(&p);/*Applyinputfilters.*/ri=ifp->info;ret=rip_filter
(RIP_FILTER_IN,&p,ri);if(ret<0)return;memset(&newinfo,0,sizeof(newinfo));newinfo
.type=ZEBRA_ROUTE_RIP;newinfo.sub_type=RIP_ROUTE_RTE;newinfo.nh.gate.ipv4=rte->n
exthop;newinfo.from=from->sin_addr;newinfo.nh.ifindex=ifp->ifindex;newinfo.nh.ty
pe=NEXTHOP_TYPE_IPV4_IFINDEX;newinfo.metric=rte->metric;newinfo.metric_out=rte->
metric;/*XXX*/newinfo.tag=ntohs(rte->tag);/*XXX*//*Modifyentryaccordingtotheinte
rfaceroutemap.*/if(ri->routemap[RIP_FILTER_IN]){intret;/*Theobjectshouldbeofthet
ypeofrip_info*/ret=route_map_apply(ri->routemap[RIP_FILTER_IN],(structprefix*)&p
,RMAP_RIP,&newinfo);if(ret==RMAP_DENYMATCH){if(IS_RIP_DEBUG_PACKET)zlog_debug("R
IP%s/%disfilteredbyroute-mapin",inet_ntoa(p.prefix),p.prefixlen);return;}/*Getba
cktheobject*/rte->nexthop=newinfo.nexthop_out;rte->tag=htons(newinfo.tag_out);/*
XXX*/rte->metric=newinfo.metric_out;/*XXX:theroutemapusesthemetric_outfield*/}/*
Oncetheentryhasbeenvalidated,updatethemetricbyaddingthecostofthenetworkonwichthe
messagearrived.Iftheresultisgreaterthaninfinity,useinfinity(RFC2453Sec.3.9.2)*//
*Zebraripdcanhandleoffset-listin.*/ret=rip_offset_list_apply_in(&p,ifp,&rte->met
ric);/*Ifoffset-listdoesnotmodifythemetricuseinterface'smetric.*/if(!ret)rte->me
tric+=ifp->metric?ifp->metric:1;if(rte->metric>RIP_METRIC_INFINITY)rte->metric=R
IP_METRIC_INFINITY;/*Setnexthoppointer.*/if(rte->nexthop.s_addr==0)nexthop=&from
->sin_addr;elsenexthop=&rte->nexthop;/*Checkifnexthopaddressismyself,thendonothi
ng.*/if(rip_nexthop_check(nexthop)<0){if(IS_RIP_DEBUG_PACKET)zlog_debug("Nexthop
address%sismyself",inet_ntoa(*nexthop));return;}/*Getindexfortheprefix.*/rp=rout
e_node_get(rip->table,(structprefix*)&p);newinfo.rp=rp;newinfo.nh.gate.ipv4=*nex
thop;newinfo.nh.type=NEXTHOP_TYPE_IPV4;newinfo.metric=rte->metric;newinfo.tag=nt
ohs(rte->tag);newinfo.distance=rip_distance_apply(&newinfo);new_dist=newinfo.dis
tance?newinfo.distance:ZEBRA_RIP_DISTANCE_DEFAULT;/*Checktoseewhetherthereisalre
adyRIProuteonthetable.*/if((list=rp->info)!=NULL)for(ALL_LIST_ELEMENTS_RO(list,n
ode,rinfo)){/*Needtocomparewithredistributedentryorlocal*entry*/if(!rip_route_rt
e(rinfo))break;if(IPV4_ADDR_SAME(&rinfo->from,&from->sin_addr)&&IPV4_ADDR_SAME(&
rinfo->nh.gate.ipv4,nexthop))break;if(!listnextnode(node)){/*Notfoundinthelist*/
if(rte->metric>rinfo->metric){/*Newroutehasagreatermetric.*Discardit.*/route_unl
ock_node(rp);return;}if(rte->metric<rinfo->metric)/*Newroutehasasmallermetric.*R
eplacetheECMPlist*withthenewoneinbelow.*/break;/*Metricsaresame.Wecomparethedist
ances.*/old_dist=rinfo->distance?rinfo->distance:ZEBRA_RIP_DISTANCE_DEFAULT;if(n
ew_dist>old_dist){/*Newroutehasagreaterdistance.*Discardit.*/route_unlock_node(r
p);return;}if(new_dist<old_dist)/*Newroutehasasmallerdistance.*ReplacetheECMPlis
t*withthenewoneinbelow.*/break;/*Metricsanddistancesarebothsame.Keep*"rinfo"null
and*thenewrouteisaddedintheECMPlistin*below.*/}}if(rinfo){/*Localstaticroute.*/i
f(rinfo->type==ZEBRA_ROUTE_RIP&&((rinfo->sub_type==RIP_ROUTE_STATIC)||(rinfo->su
b_type==RIP_ROUTE_DEFAULT))&&rinfo->metric!=RIP_METRIC_INFINITY){route_unlock_no
de(rp);return;}/*Redistributedroutecheck.*/if(rinfo->type!=ZEBRA_ROUTE_RIP&&rinf
o->metric!=RIP_METRIC_INFINITY){old_dist=rinfo->distance;/*Onlyroutesdirectlycon
nectedtoaninterface*(nexthop==0)*mayhaveavalidNULLdistance*/if(rinfo->nh.gate.ip
v4.s_addr!=0)old_dist=old_dist?old_dist:ZEBRA_RIP_DISTANCE_DEFAULT;/*Ifimportedr
outedoesnothaveSTRICTprecedence,markitasaghost*/if(new_dist<=old_dist&&rte->metr
ic!=RIP_METRIC_INFINITY)rip_ecmp_replace(&newinfo);route_unlock_node(rp);return;
}}if(!rinfo){if(rp->info)route_unlock_node(rp);/*Now,checktoseewhetherthereisalr
eadyanexplicitrouteforthedestinationprefix.Ifthereisnosuchroute,addthisroutetoth
eroutingtable,unlessthemetricisinfinity(thereisnopointinaddingaroutewhichunusabl
e).*/if(rte->metric!=RIP_METRIC_INFINITY)rip_ecmp_add(&newinfo);}else{/*Routeist
herebutwearenotsuretherouteisRIPornot.*//*Ifthereisanexistingroute,comparethenex
thopaddresstotheaddressoftherouterfromwhichthedatagramcame.Ifthisdatagramisfromt
hesamerouterastheexistingroute,reinitializethetimeout.*/same=(IPV4_ADDR_SAME(&ri
nfo->from,&from->sin_addr)&&(rinfo->nh.ifindex==ifp->ifindex));old_dist=rinfo->d
istance?rinfo->distance:ZEBRA_RIP_DISTANCE_DEFAULT;/*Next,comparethemetrics.Ifth
edatagramisfromthesamerouterastheexistingroute,andthenewmetricisdifferentthanthe
oldone;or,ifthenewmetricislowerthantheoldone,orifthetaghasbeenchanged;oriftherei
saroutewithaloweradministravedistance;oranupdateofthedistanceontheactualroute;do
thefollowingactions:*/if((same&&rinfo->metric!=rte->metric)||(rte->metric<rinfo-
>metric)||((same)&&(rinfo->metric==rte->metric)&&(newinfo.tag!=rinfo->tag))||(ol
d_dist>new_dist)||((old_dist!=new_dist)&&same)){if(listcount(list)==1){if(newinf
o.metric!=RIP_METRIC_INFINITY)rip_ecmp_replace(&newinfo);elserip_ecmp_delete(rin
fo);}else{if(newinfo.metric<rinfo->metric)rip_ecmp_replace(&newinfo);elseif(newi
nfo.metric>rinfo->metric)rip_ecmp_delete(rinfo);elseif(new_dist<old_dist)rip_ecm
p_replace(&newinfo);elseif(new_dist>old_dist)rip_ecmp_delete(rinfo);else{intupda
te=CHECK_FLAG(rinfo->flags,RIP_RTF_FIB)?1:0;assert(newinfo.metric!=RIP_METRIC_IN
FINITY);RIP_TIMER_OFF(rinfo->t_timeout);RIP_TIMER_OFF(rinfo->t_garbage_collect);
memcpy(rinfo,&newinfo,sizeof(structrip_info));rip_timeout_update(rinfo);if(updat
e)rip_zebra_ipv4_add(rp);/*-Settheroutechangeflagonthe*firstentry.*/rinfo=listge
tdata(listhead(list));SET_FLAG(rinfo->flags,RIP_RTF_CHANGED);rip_event(RIP_TRIGG
ERED_UPDATE,0);}}}else/*same&nochange*/rip_timeout_update(rinfo);/*Unlocktempola
rylockoftheroute.*/route_unlock_node(rp);}}/*DumpRIPpacket*/staticvoidrip_packet
_dump(structrip_packet*packet,intsize,constchar*sndrcv){caddr_tlim;structrte*rte
;constchar*command_str;charpbuf[BUFSIZ],nbuf[BUFSIZ];uint8_tnetmask=0;uint8_t*p;
/*Setcommandstring.*/if(packet->command>0&&packet->command<RIP_COMMAND_MAX)comma
nd_str=lookup_msg(rip_msg,packet->command,NULL);elsecommand_str="unknown";/*Dump
packetheader.*/zlog_debug("%s%sversion%dpacketsize%d",sndrcv,command_str,packet-
>version,size);/*Dumpeachroutingtableentry.*/rte=packet->rte;for(lim=(caddr_t)pa
cket+size;(caddr_t)rte<lim;rte++){if(packet->version==RIPv2){netmask=ip_masklen(
rte->mask);if(rte->family==htons(RIP_FAMILY_AUTH)){if(rte->tag==htons(RIP_AUTH_S
IMPLE_PASSWORD)){p=(uint8_t*)&rte->prefix;zlog_debug("family0x%Xtype%dauthstring
:%s",ntohs(rte->family),ntohs(rte->tag),p);}elseif(rte->tag==htons(RIP_AUTH_MD5)
){structrip_md5_info*md5;md5=(structrip_md5_info*)&packet->rte;zlog_debug("famil
y0x%Xtype%d(MD5authentication)",ntohs(md5->family),ntohs(md5->type));zlog_debug(
"RIP-2packetlen%dKeyID%d""AuthDatalen%d",ntohs(md5->packet_len),md5->keyid,md5->
auth_len);zlog_debug("SequenceNumber%ld",(unsignedlong)ntohl(md5->sequence));}el
seif(rte->tag==htons(RIP_AUTH_DATA)){p=(uint8_t*)&rte->prefix;zlog_debug("family
0x%Xtype%d(MD5data)",ntohs(rte->family),ntohs(rte->tag));zlog_debug("MD5:%02X%02
X%02X%02X%02X%02X%02X%02X""%02X%02X%02X%02X%02X%02X%02X%02X",p[0],p[1],p[2],p[3]
,p[4],p[5],p[6],p[7],p[8],p[9],p[10],p[11],p[12],p[13],p[14],p[15]);}else{zlog_d
ebug("family0x%Xtype%d(Unknownauthtype)",ntohs(rte->family),ntohs(rte->tag));}}e
lsezlog_debug("%s/%d->%sfamily%dtag%"ROUTE_TAG_PRI"metric%ld",inet_ntop(AF_INET,
&rte->prefix,pbuf,BUFSIZ),netmask,inet_ntop(AF_INET,&rte->nexthop,nbuf,BUFSIZ),n
tohs(rte->family),(route_tag_t)ntohs(rte->tag),(unsignedlong)ntohl(rte->metric))
;}else{zlog_debug("%sfamily%dtag%"ROUTE_TAG_PRI"metric%ld",inet_ntop(AF_INET,&rt
e->prefix,pbuf,BUFSIZ),ntohs(rte->family),(route_tag_t)ntohs(rte->tag),(unsigned
long)ntohl(rte->metric));}}}/*Checkifthedestinationaddressisvalid(unicast;notnet
0or127)(RFC2453Section3.9.2-Page26).Butwedon'tchecknet0becauseweacceptdefaultrou
te.*/staticintrip_destination_check(structin_addraddr){uint32_tdestination;/*Con
verttohostbyteorder.*/destination=ntohl(addr.s_addr);if(IPV4_NET127(destination)
)return0;/*Net0maymatchtothedefaultroute.*/if(IPV4_NET0(destination)&&destinatio
n!=0)return0;/*UnicastaddressmustbelongtoclassA,B,C.*/if(IN_CLASSA(destination))
return1;if(IN_CLASSB(destination))return1;if(IN_CLASSC(destination))return1;retu
rn0;}/*RIPversion2authentication.*/staticintrip_auth_simple_password(structrte*r
te,structsockaddr_in*from,structinterface*ifp){structrip_interface*ri;char*auth_
str=(char*)&rte->prefix;inti;/*rejectpasswordswithzerosinthemiddleofthestring*/f
or(i=strlen(auth_str);i<16;i++){if(auth_str[i]!='\0')return0;}if(IS_RIP_DEBUG_EV
ENT)zlog_debug("RIPv2simplepasswordauthenticationfrom%s",inet_ntoa(from->sin_add
r));ri=ifp->info;if(ri->auth_type!=RIP_AUTH_SIMPLE_PASSWORD||rte->tag!=htons(RIP
_AUTH_SIMPLE_PASSWORD))return0;/*Simplepasswordauthentication.*/if(ri->auth_str)
{if(strncmp(auth_str,ri->auth_str,16)==0)return1;}if(ri->key_chain){structkeycha
in*keychain;structkey*key;keychain=keychain_lookup(ri->key_chain);if(keychain==N
ULL)return0;key=key_match_for_accept(keychain,auth_str);if(key)return1;}return0;
}/*RIPversion2authenticationwithMD5.*/staticintrip_auth_md5(structrip_packet*pac
ket,structsockaddr_in*from,intlength,structinterface*ifp){structrip_interface*ri
;structrip_md5_info*md5;structrip_md5_data*md5data;structkeychain*keychain;struc
tkey*key;MD5_CTXctx;uint8_tdigest[RIP_AUTH_MD5_SIZE];uint16_tpacket_len;charauth
_str[RIP_AUTH_MD5_SIZE];if(IS_RIP_DEBUG_EVENT)zlog_debug("RIPv2MD5authentication
from%s",inet_ntoa(from->sin_addr));ri=ifp->info;md5=(structrip_md5_info*)&packet
->rte;/*Checkauthtype.*/if(ri->auth_type!=RIP_AUTH_MD5||md5->type!=htons(RIP_AUT
H_MD5))return0;/*Iftheauthenticationlengthislessthan16,thenitmustbewrong*for*any
interpretationofrfc2082.Someimplementationsalsointerpret*thisasRIP_HEADER_SIZE+R
IP_AUTH_MD5_SIZE,aka*RIP_AUTH_MD5_COMPAT_SIZE.*/if(!((md5->auth_len==RIP_AUTH_MD
5_SIZE)||(md5->auth_len==RIP_AUTH_MD5_COMPAT_SIZE))){if(IS_RIP_DEBUG_EVENT)zlog_
debug("RIPv2MD5authentication,strangeauthentication""lengthfield%d",md5->auth_le
n);return0;}/*grabandverifycheckpacketlength*/packet_len=ntohs(md5->packet_len);
if(packet_len>(length-RIP_HEADER_SIZE-RIP_AUTH_MD5_SIZE)){if(IS_RIP_DEBUG_EVENT)
zlog_debug("RIPv2MD5authentication,packetlengthfield%d""greaterthanreceivedlengt
h%d!",md5->packet_len,length);return0;}/*retrieveauthenticationdata*/md5data=(st
ructrip_md5_data*)(((uint8_t*)packet)+packet_len);memset(auth_str,0,RIP_AUTH_MD5
_SIZE);if(ri->key_chain){keychain=keychain_lookup(ri->key_chain);if(keychain==NU
LL)return0;key=key_lookup_for_accept(keychain,md5->keyid);if(key==NULL)return0;s
trncpy(auth_str,key->string,RIP_AUTH_MD5_SIZE);}elseif(ri->auth_str)strncpy(auth
_str,ri->auth_str,RIP_AUTH_MD5_SIZE);if(auth_str[0]==0)return0;/*MD5digestauthen
tication.*/memset(&ctx,0,sizeof(ctx));MD5Init(&ctx);MD5Update(&ctx,packet,packet
_len+RIP_HEADER_SIZE);MD5Update(&ctx,auth_str,RIP_AUTH_MD5_SIZE);MD5Final(digest
,&ctx);if(memcmp(md5data->digest,digest,RIP_AUTH_MD5_SIZE)==0)returnpacket_len;e
lsereturn0;}/*Pickcorrectauthstringforsends,prepareauth_strbufferforuse.*(leftju
stifiedandpadded).**presumesoneofriorkeyisvalid,andthattheauthstringstheypoint*t
oarenulterminated.Ifneitherarepresent,auth_strwillbefully*zeropadded.**/staticvo
idrip_auth_prepare_str_send(structrip_interface*ri,structkey*key,char*auth_str,i
ntlen){assert(ri||key);memset(auth_str,0,len);if(key&&key->string)strncpy(auth_s
tr,key->string,len);elseif(ri->auth_str)strncpy(auth_str,ri->auth_str,len);retur
n;}/*WriteRIPv2simplepasswordauthenticationinformation**auth_strispresumedtobe2b
ytesandcorrectlyprepared*(leftjustifiedandzeropadded).*/staticvoidrip_auth_simpl
e_write(structstream*s,char*auth_str,intlen){assert(s&&len==RIP_AUTH_SIMPLE_SIZE
);stream_putw(s,RIP_FAMILY_AUTH);stream_putw(s,RIP_AUTH_SIMPLE_PASSWORD);stream_
put(s,auth_str,RIP_AUTH_SIMPLE_SIZE);return;}/*writeRIPv2MD5"authenticationheade
r"*(usestheauthkeydatafield)**Digestoffsetfieldissetto0.**returns:offsetofthedig
estoffsetfield,whichmustbesetwhen*lengthtotheauth-dataMD5digestisknown.*/statics
ize_trip_auth_md5_ah_write(structstream*s,structrip_interface*ri,structkey*key){
size_tdoff=0;assert(s&&ri&&ri->auth_type==RIP_AUTH_MD5);/*MD5authentication.*/st
ream_putw(s,RIP_FAMILY_AUTH);stream_putw(s,RIP_AUTH_MD5);/*MD5AHdigestoffsetfiel
d.**Settoplaceholdervaluehere,totruevaluewhenRIP-2Packetlength*isknown.Actualval
ueissetin.....().*/doff=stream_get_endp(s);stream_putw(s,0);/*KeyID.*/if(key)str
eam_putc(s,key->index%256);elsestream_putc(s,1);/*AuthDataLen.Set16forMD5authent
icationdata.Olderripds*howeverexpectRIP_HEADER_SIZE+RIP_AUTH_MD5_SIZEsoweallowfo
r*this*tobeconfigurable.*/stream_putc(s,ri->md5_auth_len);/*SequenceNumber(non-d
ecreasing).*//*RFC2080:Thevalueusedinthesequencenumberisarbitrary,buttwosuggesti
onsarethetimeofthemessage'screationorasimplemessagecounter.*/stream_putl(s,time(
NULL));/*Reservedfieldmustbezero.*/stream_putl(s,0);stream_putl(s,0);returndoff;
}/*Ifauthenticationisinused,writetheappropriateheader*returnsstreamoffsettowhich
lengthmustlaterbewritten*or0ifthisisnotrequired*/staticsize_trip_auth_header_wri
te(structstream*s,structrip_interface*ri,structkey*key,char*auth_str,intlen){ass
ert(ri->auth_type!=RIP_NO_AUTH);switch(ri->auth_type){caseRIP_AUTH_SIMPLE_PASSWO
RD:rip_auth_prepare_str_send(ri,key,auth_str,len);rip_auth_simple_write(s,auth_s
tr,len);return0;caseRIP_AUTH_MD5:returnrip_auth_md5_ah_write(s,ri,key);}assert(1
);return0;}/*WriteRIPv2MD5authenticationdatatrailer*/staticvoidrip_auth_md5_set(
structstream*s,structrip_interface*ri,size_tdoff,char*auth_str,intauthlen){unsig
nedlonglen;MD5_CTXctx;unsignedchardigest[RIP_AUTH_MD5_SIZE];/*Makeitsurethisinte
rfaceisconfiguredasMD5authentication.*/assert((ri->auth_type==RIP_AUTH_MD5)&&(au
thlen==RIP_AUTH_MD5_SIZE));assert(doff>0);/*Getpacketlength.*/len=stream_get_end
p(s);/*Checkpacketlength.*/if(len<(RIP_HEADER_SIZE+RIP_RTE_SIZE)){zlog_err("rip_
auth_md5_set():packetlength%ldislessthanminimumlength.",len);return;}/*Setthedig
estoffsetlengthintheheader*/stream_putw_at(s,doff,len);/*Setauthenticationdata.*
/stream_putw(s,RIP_FAMILY_AUTH);stream_putw(s,RIP_AUTH_DATA);/*Generateadigestfo
rtheRIPpacket.*/memset(&ctx,0,sizeof(ctx));MD5Init(&ctx);MD5Update(&ctx,STREAM_D
ATA(s),stream_get_endp(s));MD5Update(&ctx,auth_str,RIP_AUTH_MD5_SIZE);MD5Final(d
igest,&ctx);/*Copythedigesttothepacket.*/stream_write(s,digest,RIP_AUTH_MD5_SIZE
);}/*RIProutinginformation.*/staticvoidrip_response_process(structrip_packet*pac
ket,intsize,structsockaddr_in*from,structconnected*ifc){caddr_tlim;structrte*rte
;structprefix_ipv4ifaddr;structprefix_ipv4ifaddrclass;intsubnetted;memset(&ifadd
r,0,sizeof(ifaddr));/*Wedon'tknowyet.*/subnetted=-1;/*TheResponsemustbeignoredif
itisnotfromtheRIPport.(RFC2453-Sec.3.9.2)*/if(from->sin_port!=htons(RIP_PORT_DEF
AULT)){zlog_info("responsedoesn'tcomefromRIPport:%d",from->sin_port);rip_peer_ba
d_packet(from);return;}/*Thedatagram'sIPv4sourceaddressshouldbecheckedtoseewheth
erthedatagramisfromavalidneighbor;thesourceofthedatagrammustbeonadirectlyconnect
ednetwork(RFC2453-Sec.3.9.2)*/if(if_lookup_address((void*)&from->sin_addr,AF_INE
T,VRF_DEFAULT)==NULL){zlog_info("Thisdatagramdoesn'tcamefromavalidneighbor:%s",i
net_ntoa(from->sin_addr));rip_peer_bad_packet(from);return;}/*Itisalsoworthcheck
ingtoseewhethertheresponseisfromoneoftherouter'sownaddresses.*/;/*Alredydoneinri
p_read()*//*UpdateRIPpeer.*/rip_peer_update(from,packet->version);/*SetRTEpointe
r.*/rte=packet->rte;for(lim=(caddr_t)packet+size;(caddr_t)rte<lim;rte++){/*RIPv2
authenticationcheck.*//*IftheAddressFamilyIdentifierofthefirst(andonlythefirst)e
ntryinthemessageis0xFFFF,thentheremainderoftheentrycontainstheauthentication.*//
*Ifthepacketgetshereitmeansauthenticationenabled*//*Checkisdoneinrip_read().So,j
ustskippingit*/if(packet->version==RIPv2&&rte==packet->rte&&rte->family==htons(R
IP_FAMILY_AUTH))continue;if(rte->family!=htons(AF_INET)){/*Addressfamilycheck.RI
PonlysupportsAF_INET.*/zlog_info("Unsupportedfamily%dfrom%s.",ntohs(rte->family)
,inet_ntoa(from->sin_addr));continue;}/*-isthedestinationaddressvalid(e.g.,unica
st;notnet0or127)*/if(!rip_destination_check(rte->prefix)){zlog_info("Networkisne
t0ornet127oritisnotunicastnetwork");rip_peer_bad_route(from);continue;}/*Convert
metricvaluetohostbyteorder.*/rte->metric=ntohl(rte->metric);/*-isthemetricvalid(
i.e.,between1and16,inclusive)*/if(!(rte->metric>=1&&rte->metric<=16)){zlog_info(
"Route'smetricisnotinthe1-16range.");rip_peer_bad_route(from);continue;}/*RIPv1d
oesnothavenexthopvalue.*/if(packet->version==RIPv1&&rte->nexthop.s_addr!=0){zlog
_info("RIPv1packetwithnexthopvalue%s",inet_ntoa(rte->nexthop));rip_peer_bad_rout
e(from);continue;}/*Thatis,iftheprovidedinformationisignored,apossiblysub-optima
l,butabsolutelyvalid,routemaybetaken.IfthereceivedNextHopisnotdirectlyreachable,
itshouldbetreatedas0.0.0.0.*/if(packet->version==RIPv2&&rte->nexthop.s_addr!=0){
uint32_taddrval;/*Multicastaddresscheck.*/addrval=ntohl(rte->nexthop.s_addr);if(
IN_CLASSD(addrval)){zlog_info("Nexthop%sismulticastaddress,skipthisrte",inet_nto
a(rte->nexthop));continue;}if(!if_lookup_address((void*)&rte->nexthop,AF_INET,VR
F_DEFAULT)){structroute_node*rn;structrip_info*rinfo;rn=route_node_match_ipv4(ri
p->table,&rte->nexthop);if(rn){rinfo=rn->info;if(rinfo->type==ZEBRA_ROUTE_RIP&&r
info->sub_type==RIP_ROUTE_RTE){if(IS_RIP_DEBUG_EVENT)zlog_debug("Nexthop%sisonRI
Pnetwork.Setnexthoptothepacket'soriginator",inet_ntoa(rte->nexthop));rte->nextho
p=rinfo->from;}else{if(IS_RIP_DEBUG_EVENT)zlog_debug("Nexthop%sisnotdirectlyreac
hable.Treatitas0.0.0.0",inet_ntoa(rte->nexthop));rte->nexthop.s_addr=0;}route_un
lock_node(rn);}else{if(IS_RIP_DEBUG_EVENT)zlog_debug("Nexthop%sisnotdirectlyreac
hable.Treatitas0.0.0.0",inet_ntoa(rte->nexthop));rte->nexthop.s_addr=0;}}}/*ForR
IPv1,therewon'tbeavalidnetmask.Thisisabestguessatthemasks.IfeveryonewasusingoldC
iscosbeforethe'ipsubnetzero'option,itwouldbealmostrighttoo:-)Ciscosummarizeripv1
advertismentstotheclassfulboundary(/16forclassB's)exceptwhentheRIPpacketdoestoin
sidetheclassfulnetworkinquestion.*/if((packet->version==RIPv1&&rte->prefix.s_add
r!=0)||(packet->version==RIPv2&&(rte->prefix.s_addr!=0&&rte->mask.s_addr==0))){u
int32_tdestination;if(subnetted==-1){memcpy(&ifaddr,ifc->address,sizeof(structpr
efix_ipv4));memcpy(&ifaddrclass,&ifaddr,sizeof(structprefix_ipv4));apply_classfu
l_mask_ipv4(&ifaddrclass);subnetted=0;if(ifaddr.prefixlen>ifaddrclass.prefixlen)
subnetted=1;}destination=ntohl(rte->prefix.s_addr);if(IN_CLASSA(destination))mas
klen2ip(8,&rte->mask);elseif(IN_CLASSB(destination))masklen2ip(16,&rte->mask);el
seif(IN_CLASSC(destination))masklen2ip(24,&rte->mask);if(subnetted==1)masklen2ip
(ifaddrclass.prefixlen,(structin_addr*)&destination);if((subnetted==1)&&((rte->p
refix.s_addr&destination)==ifaddrclass.prefix.s_addr)){masklen2ip(ifaddr.prefixl
en,&rte->mask);if((rte->prefix.s_addr&rte->mask.s_addr)!=rte->prefix.s_addr)mask
len2ip(32,&rte->mask);if(IS_RIP_DEBUG_EVENT)zlog_debug("Subnettedroute%s",inet_n
toa(rte->prefix));}else{if((rte->prefix.s_addr&rte->mask.s_addr)!=rte->prefix.s_
addr)continue;}if(IS_RIP_DEBUG_EVENT){zlog_debug("Resultantroute%s",inet_ntoa(rt
e->prefix));zlog_debug("Resultantmask%s",inet_ntoa(rte->mask));}}/*IncaseofRIPv2
,ifprefixinRTEisnotnetmaskappliedoneignoretheentry.*/if((packet->version==RIPv2)
&&(rte->mask.s_addr!=0)&&((rte->prefix.s_addr&rte->mask.s_addr)!=rte->prefix.s_a
ddr)){zlog_warn("RIPv2address%sisnotmask/%dappliedone",inet_ntoa(rte->prefix),ip
_masklen(rte->mask));rip_peer_bad_route(from);continue;}/*Defaultroute'snetmaski
signored.*/if(packet->version==RIPv2&&(rte->prefix.s_addr==0)&&(rte->mask.s_addr
!=0)){if(IS_RIP_DEBUG_EVENT)zlog_debug("Defaultroutewithnon-zeronetmask.Setzerot
onetmask");rte->mask.s_addr=0;}/*Routingtableupdates.*/rip_rte_process(rte,from,
ifc->ifp);}}/*MakesocketforRIPprotocol.*/staticintrip_create_socket(void){intret
;intsock;structsockaddr_inaddr;memset(&addr,0,sizeof(structsockaddr_in));addr.si
n_family=AF_INET;addr.sin_addr.s_addr=INADDR_ANY;#ifdefHAVE_STRUCT_SOCKADDR_IN_S
IN_LENaddr.sin_len=sizeof(structsockaddr_in);#endif/*HAVE_STRUCT_SOCKADDR_IN_SIN
_LEN*//*sendingportmustalwaysbetheRIPport*/addr.sin_port=htons(RIP_PORT_DEFAULT)
;/*Makedatagramsocket.*/sock=socket(AF_INET,SOCK_DGRAM,IPPROTO_UDP);if(sock<0){z
log_err("CannotcreateUDPsocket:%s",safe_strerror(errno));exit(1);}sockopt_broadc
ast(sock);sockopt_reuseaddr(sock);sockopt_reuseport(sock);setsockopt_ipv4_multic
ast_loop(sock,0);#ifdefRIP_RECVMSGsetsockopt_pktinfo(sock);#endif/*RIP_RECVMSG*/
#ifdefIPTOS_PREC_INTERNETCONTROLsetsockopt_ipv4_tos(sock,IPTOS_PREC_INTERNETCONT
ROL);#endifif(ripd_privs.change(ZPRIVS_RAISE))zlog_err("rip_create_socket:couldn
otraiseprivs");setsockopt_so_recvbuf(sock,RIP_UDP_RCV_BUF);if((ret=bind(sock,(st
ructsockaddr*)&addr,sizeof(addr)))<0){intsave_errno=errno;if(ripd_privs.change(Z
PRIVS_LOWER))zlog_err("rip_create_socket:couldnotlowerprivs");zlog_err("%s:Can't
bindsocket%dto%sport%d:%s",__func__,sock,inet_ntoa(addr.sin_addr),(int)ntohs(add
r.sin_port),safe_strerror(save_errno));close(sock);returnret;}if(ripd_privs.chan
ge(ZPRIVS_LOWER))zlog_err("rip_create_socket:couldnotlowerprivs");returnsock;}/*
RIPpacketsendtodestinationaddress,oninterfacedenotedby*byconnectedargument.NULLt
oargumentdenotesdestinationshouldbe*shouldbeRIPmulticastgroup*/staticintrip_send
_packet(uint8_t*buf,intsize,structsockaddr_in*to,structconnected*ifc){intret;str
uctsockaddr_insin;assert(ifc!=NULL);if(IS_RIP_DEBUG_PACKET){#defineADDRESS_SIZE2
0chardst[ADDRESS_SIZE];dst[ADDRESS_SIZE-1]='\0';if(to){strncpy(dst,inet_ntoa(to-
>sin_addr),ADDRESS_SIZE-1);}else{sin.sin_addr.s_addr=htonl(INADDR_RIP_GROUP);str
ncpy(dst,inet_ntoa(sin.sin_addr),ADDRESS_SIZE-1);}#undefADDRESS_SIZEzlog_debug("
rip_send_packet%s>%s(%s)",inet_ntoa(ifc->address->u.prefix4),dst,ifc->ifp->name)
;}if(CHECK_FLAG(ifc->flags,ZEBRA_IFA_SECONDARY)){/**ZEBRA_IFA_SECONDARYissetonli
nuxwhenaninterfaceis*configured*withmultipleaddressesonthesamesubnet:thefirstadd
ress*onthesubnetisconfigured"primary",andallsubsequent*addresses*onthatsubnetare
treatedas"secondary"addresses.*Inordertoavoidrouting-tablebloatonotherriplistene
rs,*wedonotsendoutRIPpacketswithZEBRA_IFA_SECONDARY*sourceaddrs.*XXXSinceLinuxis
theonlysystemforwhichthe*ZEBRA_IFA_SECONDARY*flagisset,wewouldendupsendingapacke
tfora*"secondary"*sourceaddressonnon-linuxsystems.*/if(IS_RIP_DEBUG_PACKET)zlog_
debug("duplicatedropped");return0;}/*Makedestinationaddress.*/memset(&sin,0,size
of(structsockaddr_in));sin.sin_family=AF_INET;#ifdefHAVE_STRUCT_SOCKADDR_IN_SIN_
LENsin.sin_len=sizeof(structsockaddr_in);#endif/*HAVE_STRUCT_SOCKADDR_IN_SIN_LEN
*//*Whendestinationisspecified,useit'sportandaddress.*/if(to){sin.sin_port=to->s
in_port;sin.sin_addr=to->sin_addr;}else{sin.sin_port=htons(RIP_PORT_DEFAULT);sin
.sin_addr.s_addr=htonl(INADDR_RIP_GROUP);rip_interface_multicast_set(rip->sock,i
fc);}ret=sendto(rip->sock,buf,size,0,(structsockaddr*)&sin,sizeof(structsockaddr
_in));if(IS_RIP_DEBUG_EVENT)zlog_debug("SENDto%s.%d",inet_ntoa(sin.sin_addr),nto
hs(sin.sin_port));if(ret<0)zlog_warn("can'tsendpacket:%s",safe_strerror(errno));
returnret;}/*AddredistributedroutetoRIPtable.*/voidrip_redistribute_add(inttype,
intsub_type,structprefix_ipv4*p,structnexthop*nh,unsignedintmetric,unsignedchard
istance,route_tag_ttag){intret;structroute_node*rp=NULL;structrip_info*rinfo=NUL
L,newinfo;structlist*list=NULL;/*Redistributeroute*/ret=rip_destination_check(p-
>prefix);if(!ret)return;rp=route_node_get(rip->table,(structprefix*)p);memset(&n
ewinfo,0,sizeof(structrip_info));newinfo.type=type;newinfo.sub_type=sub_type;new
info.metric=1;newinfo.external_metric=metric;newinfo.distance=distance;if(tag<=U
INT16_MAX)/*RIPonlysupports16bittags*/newinfo.tag=tag;newinfo.rp=rp;newinfo.nh=*
nh;if((list=rp->info)!=NULL&&listcount(list)!=0){rinfo=listgetdata(listhead(list
));if(rinfo->type==ZEBRA_ROUTE_CONNECT&&rinfo->sub_type==RIP_ROUTE_INTERFACE&&ri
nfo->metric!=RIP_METRIC_INFINITY){route_unlock_node(rp);return;}/*Manuallyconfig
uredRIProutecheck.*/if(rinfo->type==ZEBRA_ROUTE_RIP&&((rinfo->sub_type==RIP_ROUT
E_STATIC)||(rinfo->sub_type==RIP_ROUTE_DEFAULT))){if(type!=ZEBRA_ROUTE_RIP||((su
b_type!=RIP_ROUTE_STATIC)&&(sub_type!=RIP_ROUTE_DEFAULT))){route_unlock_node(rp)
;return;}}(void)rip_ecmp_replace(&newinfo);route_unlock_node(rp);}else(void)rip_
ecmp_add(&newinfo);if(IS_RIP_DEBUG_EVENT){zlog_debug("Redistributenewprefix%s/%d
",inet_ntoa(p->prefix),p->prefixlen);}rip_event(RIP_TRIGGERED_UPDATE,0);}/*Delet
eredistributedroutefromRIPtable.*/voidrip_redistribute_delete(inttype,intsub_typ
e,structprefix_ipv4*p,ifindex_tifindex){intret;structroute_node*rp;structrip_inf
o*rinfo;ret=rip_destination_check(p->prefix);if(!ret)return;rp=route_node_lookup
(rip->table,(structprefix*)p);if(rp){structlist*list=rp->info;if(list!=NULL&&lis
tcount(list)!=0){rinfo=listgetdata(listhead(list));if(rinfo!=NULL&&rinfo->type==
type&&rinfo->sub_type==sub_type&&rinfo->nh.ifindex==ifindex){/*Performpoisonedre
verse.*/rinfo->metric=RIP_METRIC_INFINITY;RIP_TIMER_ON(rinfo->t_garbage_collect,
rip_garbage_collect,rip->garbage_time);RIP_TIMER_OFF(rinfo->t_timeout);rinfo->fl
ags|=RIP_RTF_CHANGED;if(IS_RIP_DEBUG_EVENT)zlog_debug("Poison%s/%dontheinterface
%swithan""infinitymetric[delete]",inet_ntoa(p->prefix),p->prefixlen,ifindex2ifna
me(ifindex,VRF_DEFAULT));rip_event(RIP_TRIGGERED_UPDATE,0);}}route_unlock_node(r
p);}}/*Responsetorequestcalledfromrip_read().*/staticvoidrip_request_process(str
uctrip_packet*packet,intsize,structsockaddr_in*from,structconnected*ifc){caddr_t
lim;structrte*rte;structprefix_ipv4p;structroute_node*rp;structrip_info*rinfo;st
ructrip_interface*ri;/*Doesnotreponsetotherequestsontheloopbackinterfaces*/if(if
_is_loopback(ifc->ifp))return;/*CheckRIPprocessisenabledonthisinterface.*/ri=ifc
->ifp->info;if(!ri->running)return;/*Whenpassiveinterfaceisspecified,suppressres
ponses*/if(ri->passive)return;/*RIPpeerupdate.*/rip_peer_update(from,packet->ver
sion);lim=((caddr_t)packet)+size;rte=packet->rte;/*TheRequestisprocessedentrybye
ntry.Iftherearenoentries,noresponseisgiven.*/if(lim==(caddr_t)rte)return;/*There
isonespecialcase.Ifthereisexactlyoneentryintherequest,andithasanaddressfamilyide
ntifierofzeroandametricofinfinity(i.e.,16),thenthisisarequesttosendtheentirerout
ingtable.*/if(lim==((caddr_t)(rte+1))&&ntohs(rte->family)==0&&ntohl(rte->metric)
==RIP_METRIC_INFINITY){/*Allroutewithsplithorizon*/rip_output_process(ifc,from,r
ip_all_route,packet->version);}else{if(ntohs(rte->family)!=AF_INET)return;/*Exam
inethelistofRTEsintheRequestonebyone.Foreachentry,lookupthedestinationintheroute
r'sroutingdatabaseand,ifthereisaroute,putthatroute'smetricinthemetricfieldoftheR
TE.Ifthereisnoexplicitroutetothespecifieddestination,putinfinityinthemetricfield
.Oncealltheentrieshavebeenfilledin,changethecommandfromRequesttoResponseandsendt
hedatagrambacktotherequestor.*/p.family=AF_INET;for(;((caddr_t)rte)<lim;rte++){p
.prefix=rte->prefix;p.prefixlen=ip_masklen(rte->mask);apply_mask_ipv4(&p);rp=rou
te_node_lookup(rip->table,(structprefix*)&p);if(rp){rinfo=listgetdata(listhead((
structlist*)rp->info));rte->metric=htonl(rinfo->metric);route_unlock_node(rp);}e
lserte->metric=htonl(RIP_METRIC_INFINITY);}packet->command=RIP_RESPONSE;rip_send
_packet((uint8_t*)packet,size,from,ifc);}rip_global_queries++;}#ifRIP_RECVMSG/*S
etIPv6packetinfotothesocket.*/staticintsetsockopt_pktinfo(intsock){intret;intval
=1;ret=setsockopt(sock,IPPROTO_IP,IP_PKTINFO,&val,sizeof(val));if(ret<0)zlog_war
n("Can'tsetsockoptIP_PKTINFO:%s",safe_strerror(errno));returnret;}/*ReadRIPpacke
tbyrecvmsgfunction.*/intrip_recvmsg(intsock,uint8_t*buf,intsize,structsockaddr_i
n*from,ifindex_t*ifindex){intret;structmsghdrmsg;structioveciov;structcmsghdr*pt
r;charadata[1024];memset(&msg,0,sizeof(msg));msg.msg_name=(void*)from;msg.msg_na
melen=sizeof(structsockaddr_in);msg.msg_iov=&iov;msg.msg_iovlen=1;msg.msg_contro
l=(void*)adata;msg.msg_controllen=sizeofadata;iov.iov_base=buf;iov.iov_len=size;
ret=recvmsg(sock,&msg,0);if(ret<0)returnret;for(ptr=ZCMSG_FIRSTHDR(&msg);ptr!=NU
LL;ptr=CMSG_NXTHDR(&msg,ptr))if(ptr->cmsg_level==IPPROTO_IP&&ptr->cmsg_type==IP_
PKTINFO){structin_pktinfo*pktinfo;inti;pktinfo=(structin_pktinfo*)CMSG_DATA(ptr)
;i=pktinfo->ipi_ifindex;}returnret;}/*RIPpacketreadfunction.*/intrip_read_new(st
ructthread*t){intret;intsock;charbuf[RIP_PACKET_MAXSIZ];structsockaddr_infrom;if
index_tifindex;/*Fetchsocketthenregistermyself.*/sock=THREAD_FD(t);rip_event(RIP
_READ,sock);/*ReadRIPpacket.*/ret=rip_recvmsg(sock,buf,RIP_PACKET_MAXSIZ,&from,(
int*)&ifindex);if(ret<0){zlog_warn("Can'treadRIPpacket:%s",safe_strerror(errno))
;returnret;}returnret;}#endif/*RIP_RECVMSG*//*FirstentrypointofRIPpacket.*/stati
cintrip_read(structthread*t){intsock;intret;intrtenum;unionrip_bufrip_buf;struct
rip_packet*packet;structsockaddr_infrom;intlen;intvrecv;socklen_tfromlen;structi
nterface*ifp=NULL;structconnected*ifc;structrip_interface*ri;structprefixp;/*Fet
chsocketthenregistermyself.*/sock=THREAD_FD(t);rip->t_read=NULL;/*Addmyselftotne
nextevent*/rip_event(RIP_READ,sock);/*RIPdmanagesonlyIPv4.*/memset(&from,0,sizeo
f(structsockaddr_in));fromlen=sizeof(structsockaddr_in);len=recvfrom(sock,(char*
)&rip_buf.buf,sizeof(rip_buf.buf),0,(structsockaddr*)&from,&fromlen);if(len<0){z
log_info("recvfromfailed:%s",safe_strerror(errno));returnlen;}/*Checkisthispacke
tcommingfrommyself?*/if(if_check_address(from.sin_addr)){if(IS_RIP_DEBUG_PACKET)
zlog_debug("ignorepacketcomesfrommyself");return-1;}/*Whichinterfaceisthispacket
comesfrom.*/ifc=if_lookup_address((void*)&from.sin_addr,AF_INET,VRF_DEFAULT);if(
ifc)ifp=ifc->ifp;/*RIPpacketreceived*/if(IS_RIP_DEBUG_EVENT)zlog_debug("RECVpack
etfrom%sport%don%s",inet_ntoa(from.sin_addr),ntohs(from.sin_port),ifp?ifp->name:
"unknown");/*Ifthispacketcomefromunknowninterface,ignoreit.*/if(ifp==NULL){zlog_
info("rip_read:cannotfindinterfaceforpacketfrom%sport%d",inet_ntoa(from.sin_addr
),ntohs(from.sin_port));return-1;}p.family=AF_INET;p.u.prefix4=from.sin_addr;p.p
refixlen=IPV4_MAX_BITLEN;ifc=connected_lookup_prefix(ifp,&p);if(ifc==NULL){zlog_
info("rip_read:cannotfindconnectedaddressforpacketfrom%s""port%doninterface%s",i
net_ntoa(from.sin_addr),ntohs(from.sin_port),ifp->name);return-1;}/*Packetlength
check.*/if(len<RIP_PACKET_MINSIZ){zlog_warn("packetsize%dissmallerthanminimumsiz
e%d",len,RIP_PACKET_MINSIZ);rip_peer_bad_packet(&from);returnlen;}if(len>RIP_PAC
KET_MAXSIZ){zlog_warn("packetsize%dislargerthanmaxsize%d",len,RIP_PACKET_MAXSIZ)
;rip_peer_bad_packet(&from);returnlen;}/*Packetalignmentcheck.*/if((len-RIP_PACK
ET_MINSIZ)%20){zlog_warn("packetsize%diswrongforRIPpacketalignment",len);rip_pee
r_bad_packet(&from);returnlen;}/*SetRTEnumber.*/rtenum=((len-RIP_PACKET_MINSIZ)/
20);/*Foreasytohandle.*/packet=&rip_buf.rip_packet;/*RIPversioncheck.*/if(packet
->version==0){zlog_info("version0withcommand%dreceived.",packet->command);rip_pe
er_bad_packet(&from);return-1;}/*DumpRIPpacket.*/if(IS_RIP_DEBUG_RECV)rip_packet
_dump(packet,len,"RECV");/*RIPversionadjust.Thiscodeshouldrethinknow.RFC1058says
that"Version1implementationsaretoignorethisextradataandprocessonlythefieldsspeci
fiedinthisdocument.".SoRIPv3packetshouldbetreatedasRIPv1ignoringmustbezerofield.
*/if(packet->version>RIPv2)packet->version=RIPv2;/*IsRIPrunningoristhisRIPneighb
or?*/ri=ifp->info;if(!ri->running&&!rip_neighbor_lookup(&from)){if(IS_RIP_DEBUG_
EVENT)zlog_debug("RIPisnotenabledoninterface%s.",ifp->name);rip_peer_bad_packet(
&from);return-1;}/*RIPVersioncheck.RFC2453,4.6and5.1*/vrecv=((ri->ri_receive==RI
_RIP_UNSPEC)?rip->version_recv:ri->ri_receive);if(vrecv==RI_RIP_VERSION_NONE||((
packet->version==RIPv1)&&!(vrecv&RIPv1))||((packet->version==RIPv2)&&!(vrecv&RIP
v2))){if(IS_RIP_DEBUG_PACKET)zlog_debug("packet'sv%ddoesn'tfittoifversionspec",p
acket->version);rip_peer_bad_packet(&from);return-1;}/*RFC24535.2Iftherouterisno
tconfiguredtoauthenticateRIP-2messages,thenRIP-1andunauthenticatedRIP-2messagesw
illbeaccepted;authenticatedRIP-2messagesshallbediscarded.*/if((ri->auth_type==RI
P_NO_AUTH)&&rtenum&&(packet->version==RIPv2)&&(packet->rte->family==htons(RIP_FA
MILY_AUTH))){if(IS_RIP_DEBUG_EVENT)zlog_debug("packetRIPv%disdroppedbecauseauthe
nticationdisabled",packet->version);rip_peer_bad_packet(&from);return-1;}/*RFC:I
ftherouterisconfiguredtoauthenticateRIP-2messages,thenRIP-1messagesandRIP-2messa
geswhichpassauthenticationtestingshallbeaccepted;unauthenticatedandfailedauthent
icationRIP-2messagesshallbediscarded.Formaximumsecurity,RIP-1messagesshouldbeign
oredwhenauthenticationisinuse(seesection4.1);otherwise,theroutinginformationfrom
authenticatedmessageswillbepropagatedbyRIP-1routersinanunauthenticatedmanner.*//
*WemakeanexceptionforRIPv1REQUESTpackets,towhichwe'll*alwaysreplyregardlessofaut
henticationsettings,because:**-ifthereotherauthorisedrouterson-link,theREQUESTor
can*passivelyobtaintheroutingupdatesanyway*-iftherearenootherauthorisedrouterson
-link,RIPcan*easilybedisabledforthelinktopreventgivingoutinformation*onstateofth
isroutersRIProutingtable..**I.e.ifRIPv1hasanyplaceanymorethesedays,it'sasavery*s
implewaytodistributeroutinginformation(e.g.toembedded*hosts/appliances)andtheabi
litytogiveoutRIPv1*routing-informationfreely,whilestillrequiringRIPv2*authentica
tionforanyRESPONSEsmightbevaguelyuseful.*/if(ri->auth_type!=RIP_NO_AUTH&&packet-
>version==RIPv1){/*DiscardRIPv1messagesotherthanREQUESTs*/if(packet->command!=RI
P_REQUEST){if(IS_RIP_DEBUG_PACKET)zlog_debug("RIPv1""droppedbecauseauthenticatio
nenabled");rip_peer_bad_packet(&from);return-1;}}elseif(ri->auth_type!=RIP_NO_AU
TH){constchar*auth_desc;if(rtenum==0){/*Theredefinitelyisnoauthenticationinthepa
cket.*/if(IS_RIP_DEBUG_PACKET)zlog_debug("RIPv2authenticationfailed:noauthRTEinp
acket");rip_peer_bad_packet(&from);return-1;}/*FirstRTEmustbeanAuthenticationFam
ilyRTE*/if(packet->rte->family!=htons(RIP_FAMILY_AUTH)){if(IS_RIP_DEBUG_PACKET)z
log_debug("RIPv2""droppedbecauseauthenticationenabled");rip_peer_bad_packet(&fro
m);return-1;}/*CheckRIPv2authentication.*/switch(ntohs(packet->rte->tag)){caseRI
P_AUTH_SIMPLE_PASSWORD:auth_desc="simple";ret=rip_auth_simple_password(packet->r
te,&from,ifp);break;caseRIP_AUTH_MD5:auth_desc="MD5";ret=rip_auth_md5(packet,&fr
om,len,ifp);/*ResetRIPpacketlengthtotrimMD5data.*/len=ret;break;default:ret=0;au
th_desc="unknowntype";if(IS_RIP_DEBUG_PACKET)zlog_debug("RIPv2Unknownauthenticat
iontype%d",ntohs(packet->rte->tag));}if(ret){if(IS_RIP_DEBUG_PACKET)zlog_debug("
RIPv2%sauthenticationsuccess",auth_desc);}else{if(IS_RIP_DEBUG_PACKET)zlog_debug
("RIPv2%sauthenticationfailure",auth_desc);rip_peer_bad_packet(&from);return-1;}
}/*Processeachcommand.*/switch(packet->command){caseRIP_RESPONSE:rip_response_pr
ocess(packet,len,&from,ifc);break;caseRIP_REQUEST:caseRIP_POLL:rip_request_proce
ss(packet,len,&from,ifc);break;caseRIP_TRACEON:caseRIP_TRACEOFF:zlog_info("Obsol
etecommand%sreceived,pleasesentittorouted",lookup_msg(rip_msg,packet->command,NU
LL));rip_peer_bad_packet(&from);break;caseRIP_POLL_ENTRY:zlog_info("Obsoletecomm
and%sreceived",lookup_msg(rip_msg,packet->command,NULL));rip_peer_bad_packet(&fr
om);break;default:zlog_info("UnknownRIPcommand%dreceived",packet->command);rip_p
eer_bad_packet(&from);break;}returnlen;}/*Writeroutingtableentrytothestreamandre
turnnextindexoftheroutingtableentryinthestream.*/staticintrip_write_rte(intnum,s
tructstream*s,structprefix_ipv4*p,uint8_tversion,structrip_info*rinfo){structin_
addrmask;/*Writeroutingtableentry.*/if(version==RIPv1){stream_putw(s,AF_INET);st
ream_putw(s,0);stream_put_ipv4(s,p->prefix.s_addr);stream_put_ipv4(s,0);stream_p
ut_ipv4(s,0);stream_putl(s,rinfo->metric_out);}else{masklen2ip(p->prefixlen,&mas
k);stream_putw(s,AF_INET);stream_putw(s,rinfo->tag_out);stream_put_ipv4(s,p->pre
fix.s_addr);stream_put_ipv4(s,mask.s_addr);stream_put_ipv4(s,rinfo->nexthop_out.
s_addr);stream_putl(s,rinfo->metric_out);}return++num;}/*Sendupdatetotheifporspc
ifiedneighbor.*/voidrip_output_process(structconnected*ifc,structsockaddr_in*to,
introute_type,uint8_tversion){intret;structstream*s;structroute_node*rp;structri
p_info*rinfo;structrip_interface*ri;structprefix_ipv4*p;structprefix_ipv4classfu
ll;structprefix_ipv4ifaddrclass;structkey*key=NULL;/*thismightneedtomadedynamici
fRIPeversupportedauthmethodswithlargerkeystringsizes*/charauth_str[RIP_AUTH_SIMP
LE_SIZE];size_tdoff=0;/*offsetofdigestoffsetfield*/intnum=0;intrtemax;intsubnett
ed=0;structlist*list=NULL;structlistnode*listnode=NULL;/*Loggingoutputevent.*/if
(IS_RIP_DEBUG_EVENT){if(to)zlog_debug("updateroutestoneighbor%s",inet_ntoa(to->s
in_addr));elsezlog_debug("updateroutesoninterface%sifindex%d",ifc->ifp->name,ifc
->ifp->ifindex);}/*Setoutputstream.*/s=rip->obuf;/*ResetstreamandRTEcounter.*/st
ream_reset(s);rtemax=RIP_MAX_RTE;/*GetRIPinterface.*/ri=ifc->ifp->info;/*Ifoutpu
tinterfaceisinsimplepasswordauthenticationmode,weneedspaceforauthenticationdata.
*/if(ri->auth_type==RIP_AUTH_SIMPLE_PASSWORD)rtemax-=1;/*IfoutputinterfaceisinMD
5authenticationmode,weneedspaceforauthenticationheaderanddata.*/if(ri->auth_type
==RIP_AUTH_MD5)rtemax-=2;/*Ifoutputinterfaceisinsimplepasswordauthenticationmode
andstringorkeychainisspecifiedweneedspaceforauth.data*/if(ri->auth_type!=RIP_NO_
AUTH){if(ri->key_chain){structkeychain*keychain;keychain=keychain_lookup(ri->key
_chain);if(keychain)key=key_lookup_for_send(keychain);}/*tobepassedtoauthfunctio
nslater*/rip_auth_prepare_str_send(ri,key,auth_str,RIP_AUTH_SIMPLE_SIZE);}if(ver
sion==RIPv1){memcpy(&ifaddrclass,ifc->address,sizeof(structprefix_ipv4));apply_c
lassful_mask_ipv4(&ifaddrclass);subnetted=0;if(ifc->address->prefixlen>ifaddrcla
ss.prefixlen)subnetted=1;}for(rp=route_top(rip->table);rp;rp=route_next(rp))if((
list=rp->info)!=NULL&&listcount(list)!=0){rinfo=listgetdata(listhead(list));/*Fo
rRIPv1,ifwearesubnetted,outputsubnetsinour*network*//*thathavethesamemaskastheou
tput"interface".*Forother*//*networks,onlytheclassfullversionisoutput.*/if(versi
on==RIPv1){p=(structprefix_ipv4*)&rp->p;if(IS_RIP_DEBUG_PACKET)zlog_debug("RIPv1
maskcheck,%s/%dconsideredforoutput",inet_ntoa(rp->p.u.prefix4),rp->p.prefixlen);
if(subnetted&&prefix_match((structprefix*)&ifaddrclass,&rp->p)){if((ifc->address
->prefixlen!=rp->p.prefixlen)&&(rp->p.prefixlen!=32))continue;}else{memcpy(&clas
sfull,&rp->p,sizeof(structprefix_ipv4));apply_classful_mask_ipv4(&classfull);if(
rp->p.u.prefix4.s_addr!=0&&classfull.prefixlen!=rp->p.prefixlen)continue;}if(IS_
RIP_DEBUG_PACKET)zlog_debug("RIPv1maskcheck,%s/%dmadeitthrough",inet_ntoa(rp->p.
u.prefix4),rp->p.prefixlen);}elsep=(structprefix_ipv4*)&rp->p;/*Applyoutputfilte
rs.*/ret=rip_filter(RIP_FILTER_OUT,p,ri);if(ret<0)continue;/*Changedrouteonlyout
put.*/if(route_type==rip_changed_route&&(!(rinfo->flags&RIP_RTF_CHANGED)))contin
ue;/*Splithorizon.*//*if(split_horizon==rip_split_horizon)*/if(ri->split_horizon
==RIP_SPLIT_HORIZON){/**WeperformsplithorizonforRIPand*connectedroute.*Forriprou
tes,wewanttosuppresstheroute*ifwewould*endupsendingtheroutebackonthe*interfaceth
atwe*learneditfrom,withahighermetric.For*connectedroutes,*wesuppresstherouteifth
eprefixisa*subsetofthe*sourceaddressthatwearegoingtousefor*thepacket*(inordertoh
andlethecasewhenmultiple*subnetsare*configuredonthesameinterface).*/intsuppress=
0;structrip_info*tmp_rinfo=NULL;structconnected*tmp_ifc=NULL;for(ALL_LIST_ELEMEN
TS_RO(list,listnode,tmp_rinfo))if(tmp_rinfo->type==ZEBRA_ROUTE_RIP&&tmp_rinfo->n
h.ifindex==ifc->ifp->ifindex){suppress=1;break;}if(!suppress&&rinfo->type==ZEBRA
_ROUTE_CONNECT){for(ALL_LIST_ELEMENTS_RO(ifc->ifp->connected,listnode,tmp_ifc))i
f(prefix_match((structprefix*)p,tmp_ifc->address)){suppress=1;break;}}if(suppres
s)continue;}/*Preparationforroute-map.*/rinfo->metric_set=0;rinfo->nexthop_out.s
_addr=0;rinfo->metric_out=rinfo->metric;rinfo->tag_out=rinfo->tag;rinfo->ifindex
_out=ifc->ifp->ifindex;/*Inordertoavoidsomelocalloops,*iftheRIProutehasanexthopv
iathisinterface,*keepthenexthop,*otherwisesetitto0.Thenexthopshouldnotbe*propaga
ted*beyondthelocalbroadcast/multicastareainorder*toavoidanIGPmulti-levelrecursiv
elook-up.*see(4.4)*/if(rinfo->nh.ifindex==ifc->ifp->ifindex)rinfo->nexthop_out=r
info->nh.gate.ipv4;/*Interfaceroute-map*/if(ri->routemap[RIP_FILTER_OUT]){ret=ro
ute_map_apply(ri->routemap[RIP_FILTER_OUT],(structprefix*)p,RMAP_RIP,rinfo);if(r
et==RMAP_DENYMATCH){if(IS_RIP_DEBUG_PACKET)zlog_debug("RIP%s/%disfilteredbyroute
-mapout",inet_ntoa(p->prefix),p->prefixlen);continue;}}/*Applyredistributeroutem
ap-continue,ifdeny*/if(rip->route_map[rinfo->type].name&&rinfo->sub_type!=RIP_RO
UTE_INTERFACE){ret=route_map_apply(rip->route_map[rinfo->type].map,(structprefix
*)p,RMAP_RIP,rinfo);if(ret==RMAP_DENYMATCH){if(IS_RIP_DEBUG_PACKET)zlog_debug("%
s/%disfilteredbyroute-map",inet_ntoa(p->prefix),p->prefixlen);continue;}}/*Whenr
oute-mapdoesnotsetmetric.*/if(!rinfo->metric_set){/*Ifredistributemetricisset.*/
if(rip->route_map[rinfo->type].metric_config&&rinfo->metric!=RIP_METRIC_INFINITY
){rinfo->metric_out=rip->route_map[rinfo->type].metric;}else{/*Iftherouteisnotco
nnectedorlocalygeneratedone,usedefault-metricvalue*/if(rinfo->type!=ZEBRA_ROUTE_
RIP&&rinfo->type!=ZEBRA_ROUTE_CONNECT&&rinfo->metric!=RIP_METRIC_INFINITY)rinfo-
>metric_out=rip->default_metric;}}/*Applyoffset-list*/if(rinfo->metric!=RIP_METR
IC_INFINITY)rip_offset_list_apply_out(p,ifc->ifp,&rinfo->metric_out);if(rinfo->m
etric_out>RIP_METRIC_INFINITY)rinfo->metric_out=RIP_METRIC_INFINITY;/*Performspl
it-horizonwithpoisonedreverse*forRIPandconnectedroutes.**/if(ri->split_horizon==
RIP_SPLIT_HORIZON_POISONED_REVERSE){/**WeperformsplithorizonforRIPand*connectedr
oute.*Forriproutes,wewanttosuppresstheroute*ifwewould*endupsendingtheroutebackon
the*interfacethatwe*learneditfrom,withahighermetric.For*connectedroutes,*wesuppr
esstherouteiftheprefixisa*subsetofthe*sourceaddressthatwearegoingtousefor*thepac
ket*(inordertohandlethecasewhenmultiple*subnetsare*configuredonthesameinterface)
.*/structrip_info*tmp_rinfo=NULL;structconnected*tmp_ifc=NULL;for(ALL_LIST_ELEME
NTS_RO(list,listnode,tmp_rinfo))if(tmp_rinfo->type==ZEBRA_ROUTE_RIP&&tmp_rinfo->
nh.ifindex==ifc->ifp->ifindex)rinfo->metric_out=RIP_METRIC_INFINITY;if(rinfo->me
tric_out!=RIP_METRIC_INFINITY&&rinfo->type==ZEBRA_ROUTE_CONNECT){for(ALL_LIST_EL
EMENTS_RO(ifc->ifp->connected,listnode,tmp_ifc))if(prefix_match((structprefix*)p
,tmp_ifc->address)){rinfo->metric_out=RIP_METRIC_INFINITY;break;}}}/*Prepareprea
mble,authheaders,ifneedsbe*/if(num==0){stream_putc(s,RIP_RESPONSE);stream_putc(s
,version);stream_putw(s,0);/*authheaderfor!v1&&!no_auth*/if((ri->auth_type!=RIP_
NO_AUTH)&&(version!=RIPv1))doff=rip_auth_header_write(s,ri,key,auth_str,RIP_AUTH
_SIMPLE_SIZE);}/*WriteRTEtothestream.*/num=rip_write_rte(num,s,p,version,rinfo);
if(num==rtemax){if(version==RIPv2&&ri->auth_type==RIP_AUTH_MD5)rip_auth_md5_set(
s,ri,doff,auth_str,RIP_AUTH_SIMPLE_SIZE);ret=rip_send_packet(STREAM_DATA(s),stre
am_get_endp(s),to,ifc);if(ret>=0&&IS_RIP_DEBUG_SEND)rip_packet_dump((structrip_p
acket*)STREAM_DATA(s),stream_get_endp(s),"SEND");num=0;stream_reset(s);}}/*Flush
unwrittenRTE.*/if(num!=0){if(version==RIPv2&&ri->auth_type==RIP_AUTH_MD5)rip_aut
h_md5_set(s,ri,doff,auth_str,RIP_AUTH_SIMPLE_SIZE);ret=rip_send_packet(STREAM_DA
TA(s),stream_get_endp(s),to,ifc);if(ret>=0&&IS_RIP_DEBUG_SEND)rip_packet_dump((s
tructrip_packet*)STREAM_DATA(s),stream_get_endp(s),"SEND");stream_reset(s);}/*St
atisticsupdates.*/ri->sent_updates++;}/*SendRIPpackettotheinterface.*/staticvoid
rip_update_interface(structconnected*ifc,uint8_tversion,introute_type){structint
erface*ifp=ifc->ifp;structrip_interface*ri=ifp->info;structsockaddr_into;/*WhenR
IPversionis2andmulticastenableinterface.*/if(version==RIPv2&&!ri->v2_broadcast&&
if_is_multicast(ifp)){if(IS_RIP_DEBUG_EVENT)zlog_debug("multicastannounceon%s",i
fp->name);rip_output_process(ifc,NULL,route_type,version);return;}/*Ifwecan'tsen
dmulticastpacket,senditwithunicast.*/if(if_is_broadcast(ifp)||if_is_pointopoint(
ifp)){if(ifc->address->family==AF_INET){/*Destinationaddressandportsetting.*/mem
set(&to,0,sizeof(structsockaddr_in));if(ifc->destination)/*usespecifiedbroadcast
orpeerdestination*addr*/to.sin_addr=ifc->destination->u.prefix4;elseif(ifc->addr
ess->prefixlen<IPV4_MAX_PREFIXLEN)/*calculatetheappropriatebroadcastaddress*/to.
sin_addr.s_addr=ipv4_broadcast_addr(ifc->address->u.prefix4.s_addr,ifc->address-
>prefixlen);else/*donotknowwheretosendthepacket*/return;to.sin_port=htons(RIP_PO
RT_DEFAULT);if(IS_RIP_DEBUG_EVENT)zlog_debug("%sannounceto%son%s",CONNECTED_PEER
(ifc)?"unicast":"broadcast",inet_ntoa(to.sin_addr),ifp->name);rip_output_process
(ifc,&to,route_type,version);}}}/*Updatesendtoallinterfaceandneighbor.*/staticvo
idrip_update_process(introute_type){structvrf*vrf=vrf_lookup_by_id(VRF_DEFAULT);
structlistnode*ifnode,*ifnnode;structconnected*connected;structinterface*ifp;str
uctrip_interface*ri;structroute_node*rp;structsockaddr_into;structprefix*p;/*Sen
dRIPupdatetoeachinterface.*/FOR_ALL_INTERFACES(vrf,ifp){if(if_is_loopback(ifp))c
ontinue;if(!if_is_operative(ifp))continue;/*FetchRIPinterfaceinformation.*/ri=if
p->info;/*Whenpassiveinterfaceisspecified,suppressannouncetotheinterface.*/if(ri
->passive)continue;if(ri->running){/**Ifthereisnoversionconfigurationinthe*inter
face,*userip'sversionsetting.*/intvsend=((ri->ri_send==RI_RIP_UNSPEC)?rip->versi
on_send:ri->ri_send);if(IS_RIP_DEBUG_EVENT)zlog_debug("SENDUPDATEto%sifindex%d",
ifp->name,ifp->ifindex);/*sendupdateoneachconnectednetwork*/for(ALL_LIST_ELEMENT
S(ifp->connected,ifnode,ifnnode,connected)){if(connected->address->family==AF_IN
ET){if(vsend&RIPv1)rip_update_interface(connected,RIPv1,route_type);if((vsend&RI
Pv2)&&if_is_multicast(ifp))rip_update_interface(connected,RIPv2,route_type);}}}}
/*RIPsendupdatestoeachneighbor.*/for(rp=route_top(rip->neighbor);rp;rp=route_nex
t(rp))if(rp->info!=NULL){p=&rp->p;connected=if_lookup_address(&p->u.prefix4,AF_I
NET,VRF_DEFAULT);if(!connected){zlog_warn("Neighbor%sdoesnthaveconnectedinterfac
e!",inet_ntoa(p->u.prefix4));continue;}/*Setdestinationaddressandport*/memset(&t
o,0,sizeof(structsockaddr_in));to.sin_addr=p->u.prefix4;to.sin_port=htons(RIP_PO
RT_DEFAULT);/*RIPversionisrip'sconfiguration.*/rip_output_process(connected,&to,
route_type,rip->version_send);}}/*RIP'speriodicaltimer.*/staticintrip_update(str
uctthread*t){/*Cleartimerpointer.*/rip->t_update=NULL;if(IS_RIP_DEBUG_EVENT)zlog
_debug("updatetimerfire!");/*Processupdateoutput.*/rip_update_process(rip_all_ro
ute);/*Triggeredupdatesmaybesuppressedifaregularupdateisduebythetimethetriggered
updatewouldbesent.*/RIP_TIMER_OFF(rip->t_triggered_interval);rip->trigger=0;/*Re
gistermyself.*/rip_event(RIP_UPDATE_EVENT,0);return0;}/*WalkdowntheRIProutingtab
lethenclearchangedflag.*/staticvoidrip_clear_changed_flag(void){structroute_node
*rp;structrip_info*rinfo=NULL;structlist*list=NULL;structlistnode*listnode=NULL;
for(rp=route_top(rip->table);rp;rp=route_next(rp))if((list=rp->info)!=NULL)for(A
LL_LIST_ELEMENTS_RO(list,listnode,rinfo)){UNSET_FLAG(rinfo->flags,RIP_RTF_CHANGE
D);/*Thisflagcanbesetonlyonthefirstentry.*/break;}}/*Triggeredupdateintervaltime
r.*/staticintrip_triggered_interval(structthread*t){intrip_triggered_update(stru
ctthread*);rip->t_triggered_interval=NULL;if(rip->trigger){rip->trigger=0;rip_tr
iggered_update(t);}return0;}/*Executetriggeredupdate.*/staticintrip_triggered_up
date(structthread*t){intinterval;/*Clearthredpointer.*/rip->t_triggered_update=N
ULL;/*Cancelintervaltimer.*/RIP_TIMER_OFF(rip->t_triggered_interval);rip->trigge
r=0;/*Loggingtriggeredupdate.*/if(IS_RIP_DEBUG_EVENT)zlog_debug("triggeredupdate
!");/*SplitHorizonprocessingisdonewhengeneratingtriggeredupdatesaswellasnormalup
dates(seesection2.6).*/rip_update_process(rip_changed_route);/*Onceallofthetrigg
eredupdateshavebeengenerated,theroutechangeflagsshouldbecleared.*/rip_clear_chan
ged_flag();/*Afteratriggeredupdateissent,atimershouldbesetforarandomintervalbetw
een1and5seconds.Ifotherchangesthatwouldtriggerupdatesoccurbeforethetimerexpires,
asingleupdateistriggeredwhenthetimerexpires.*/interval=(random()%5)+1;rip->t_tri
ggered_interval=NULL;thread_add_timer(master,rip_triggered_interval,NULL,interva
l,&rip->t_triggered_interval);return0;}/*Withdrawredistributedroute.*/voidrip_re
distribute_withdraw(inttype){structroute_node*rp;structrip_info*rinfo=NULL;struc
tlist*list=NULL;if(!rip)return;for(rp=route_top(rip->table);rp;rp=route_next(rp)
)if((list=rp->info)!=NULL){rinfo=listgetdata(listhead(list));if(rinfo->type==typ
e&&rinfo->sub_type!=RIP_ROUTE_INTERFACE){/*Performpoisonedreverse.*/rinfo->metri
c=RIP_METRIC_INFINITY;RIP_TIMER_ON(rinfo->t_garbage_collect,rip_garbage_collect,
rip->garbage_time);RIP_TIMER_OFF(rinfo->t_timeout);rinfo->flags|=RIP_RTF_CHANGED
;if(IS_RIP_DEBUG_EVENT){structprefix_ipv4*p=(structprefix_ipv4*)&rp->p;zlog_debu
g("Poisone%s/%dontheinterface%swithaninfinitymetric[withdraw]",inet_ntoa(p->pref
ix),p->prefixlen,ifindex2ifname(rinfo->nh.ifindex,VRF_DEFAULT));}rip_event(RIP_T
RIGGERED_UPDATE,0);}}}/*CreatenewRIPinstanceandsetittoglobalvariable.*/staticint
rip_create(void){rip=XCALLOC(MTYPE_RIP,sizeof(structrip));/*Setinitialvalue.*/ri
p->version_send=RI_RIP_VERSION_2;rip->version_recv=RI_RIP_VERSION_1_AND_2;rip->u
pdate_time=RIP_UPDATE_TIMER_DEFAULT;rip->timeout_time=RIP_TIMEOUT_TIMER_DEFAULT;
rip->garbage_time=RIP_GARBAGE_TIMER_DEFAULT;rip->default_metric=RIP_DEFAULT_METR
IC_DEFAULT;/*InitializeRIProutigtable.*/rip->table=route_table_init();rip->route
=route_table_init();rip->neighbor=route_table_init();/*Makeoutputstream.*/rip->o
buf=stream_new(1500);/*Makesocket.*/rip->sock=rip_create_socket();if(rip->sock<0
)returnrip->sock;/*Createreadandtimerthread.*/rip_event(RIP_READ,rip->sock);rip_
event(RIP_UPDATE_EVENT,1);QOBJ_REG(rip,rip);return0;}/*SnedRIPrequesttothedestin
ation.*/intrip_request_send(structsockaddr_in*to,structinterface*ifp,uint8_tvers
ion,structconnected*connected){structrte*rte;structrip_packetrip_packet;structli
stnode*node,*nnode;memset(&rip_packet,0,sizeof(rip_packet));rip_packet.command=R
IP_REQUEST;rip_packet.version=version;rte=rip_packet.rte;rte->metric=htonl(RIP_M
ETRIC_INFINITY);if(connected){/**connectedisonlysentforripv1case,orwhen*interfac
edoesnotsupportmulticast.Callerloops*overeachconnectedaddressforthiscase.*/if(ri
p_send_packet((uint8_t*)&rip_packet,sizeof(rip_packet),to,connected)!=sizeof(rip
_packet))return-1;elsereturnsizeof(rip_packet);}/*sendrequestoneachconnectednetw
ork*/for(ALL_LIST_ELEMENTS(ifp->connected,node,nnode,connected)){structprefix_ip
v4*p;p=(structprefix_ipv4*)connected->address;if(p->family!=AF_INET)continue;if(
rip_send_packet((uint8_t*)&rip_packet,sizeof(rip_packet),to,connected)!=sizeof(r
ip_packet))return-1;}returnsizeof(rip_packet);}staticintrip_update_jitter(unsign
edlongtime){#defineJITTER_BOUND4/*Wewanttogetthejitterto+/-1/JITTER_BOUNDtheinte
rval.Giventhat,wecannotlettimebelessthanJITTER_BOUNDseconds.TheRIPv2RFCsaysjitte
rshouldbesmallcomparedtoupdate_time.Weconsider1/JITTER_BOUNDtobesmall.*/intjitte
r_input=time;intjitter;if(jitter_input<JITTER_BOUND)jitter_input=JITTER_BOUND;ji
tter=(((random()%((jitter_input*2)+1))-jitter_input));returnjitter/JITTER_BOUND;
}voidrip_event(enumrip_eventevent,intsock){intjitter=0;switch(event){caseRIP_REA
D:rip->t_read=NULL;thread_add_read(master,rip_read,NULL,sock,&rip->t_read);break
;caseRIP_UPDATE_EVENT:RIP_TIMER_OFF(rip->t_update);jitter=rip_update_jitter(rip-
>update_time);thread_add_timer(master,rip_update,NULL,sock?2:rip->update_time+ji
tter,&rip->t_update);break;caseRIP_TRIGGERED_UPDATE:if(rip->t_triggered_interval
)rip->trigger=1;elsethread_add_event(master,rip_triggered_update,NULL,0,&rip->t_
triggered_update);break;default:break;}}DEFUN_NOSH(router_rip,router_rip_cmd,"ro
uterrip","Enablearoutingprocess\n""RoutingInformationProtocol(RIP)\n"){intret;/*
Ifripisnotenabledbefore.*/if(!rip){ret=rip_create();if(ret<0){zlog_info("Can'tcr
eateRIP");returnCMD_WARNING_CONFIG_FAILED;}}VTY_PUSH_CONTEXT(RIP_NODE,rip);retur
nCMD_SUCCESS;}DEFUN(no_router_rip,no_router_rip_cmd,"norouterrip",NO_STR"Enablea
routingprocess\n""RoutingInformationProtocol(RIP)\n"){if(rip)rip_clean();returnC
MD_SUCCESS;}DEFUN(rip_version,rip_version_cmd,"version(1-2)","Setroutingprotocol
version\n""version\n"){intidx_number=1;intversion;version=atoi(argv[idx_number]-
>arg);if(version!=RIPv1&&version!=RIPv2){vty_out(vty,"invalidripversion%d\n",ver
sion);returnCMD_WARNING_CONFIG_FAILED;}rip->version_send=version;rip->version_re
cv=version;returnCMD_SUCCESS;}DEFUN(no_rip_version,no_rip_version_cmd,"noversion
[(1-2)]",NO_STR"Setroutingprotocolversion\n""Version\n"){/*SetRIPversiontothedef
ault.*/rip->version_send=RI_RIP_VERSION_2;rip->version_recv=RI_RIP_VERSION_1_AND
_2;returnCMD_SUCCESS;}DEFUN(rip_route,rip_route_cmd,"routeA.B.C.D/M","RIPstaticr
outeconfiguration\n""IPprefix<network>/<length>\n"){intidx_ipv4_prefixlen=1;intr
et;structnexthopnh;structprefix_ipv4p;structroute_node*node;memset(&nh,0,sizeof(
nh));nh.type=NEXTHOP_TYPE_IPV4;ret=str2prefix_ipv4(argv[idx_ipv4_prefixlen]->arg
,&p);if(ret<0){vty_out(vty,"Malformedaddress\n");returnCMD_WARNING_CONFIG_FAILED
;}apply_mask_ipv4(&p);/*Forrouterripconfiguration.*/node=route_node_get(rip->rou
te,(structprefix*)&p);if(node->info){vty_out(vty,"Thereisalreadysamestaticroute.
\n");route_unlock_node(node);returnCMD_WARNING;}node->info=(void*)1;rip_redistri
bute_add(ZEBRA_ROUTE_RIP,RIP_ROUTE_STATIC,&p,&nh,0,0,0);returnCMD_SUCCESS;}DEFUN
(no_rip_route,no_rip_route_cmd,"norouteA.B.C.D/M",NO_STR"RIPstaticrouteconfigura
tion\n""IPprefix<network>/<length>\n"){intidx_ipv4_prefixlen=2;intret;structpref
ix_ipv4p;structroute_node*node;ret=str2prefix_ipv4(argv[idx_ipv4_prefixlen]->arg
,&p);if(ret<0){vty_out(vty,"Malformedaddress\n");returnCMD_WARNING_CONFIG_FAILED
;}apply_mask_ipv4(&p);/*Forrouterripconfiguration.*/node=route_node_lookup(rip->
route,(structprefix*)&p);if(!node){vty_out(vty,"Can'tfindroute%s.\n",argv[idx_ip
v4_prefixlen]->arg);returnCMD_WARNING_CONFIG_FAILED;}rip_redistribute_delete(ZEB
RA_ROUTE_RIP,RIP_ROUTE_STATIC,&p,0);route_unlock_node(node);node->info=NULL;rout
e_unlock_node(node);returnCMD_SUCCESS;}#if0staticvoidrip_update_default_metric(v
oid){structroute_node*np;structrip_info*rinfo=NULL;structlist*list=NULL;structli
stnode*listnode=NULL;for(np=route_top(rip->table);np;np=route_next(np))if((list=
np->info)!=NULL)for(ALL_LIST_ELEMENTS_RO(list,listnode,rinfo))if(rinfo->type!=ZE
BRA_ROUTE_RIP&&rinfo->type!=ZEBRA_ROUTE_CONNECT)rinfo->metric=rip->default_metri
c;}#endifDEFUN(rip_default_metric,rip_default_metric_cmd,"default-metric(1-16)",
"Setametricofredistributeroutes\n""Defaultmetric\n"){intidx_number=1;if(rip){rip
->default_metric=atoi(argv[idx_number]->arg);/*rip_update_default_metric();*/}re
turnCMD_SUCCESS;}DEFUN(no_rip_default_metric,no_rip_default_metric_cmd,"nodefaul
t-metric[(1-16)]",NO_STR"Setametricofredistributeroutes\n""Defaultmetric\n"){if(
rip){rip->default_metric=RIP_DEFAULT_METRIC_DEFAULT;/*rip_update_default_metric(
);*/}returnCMD_SUCCESS;}DEFUN(rip_timers,rip_timers_cmd,"timersbasic(5-214748364
7)(5-2147483647)(5-2147483647)","Adjustroutingtimers\n""Basicroutingprotocolupda
tetimers\n""Routingtableupdatetimervalueinsecond.Defaultis30.\n""Routinginformat
iontimeouttimer.Defaultis180.\n""Garbagecollectiontimer.Defaultis120.\n"){intidx
_number=2;intidx_number_2=3;intidx_number_3=4;unsignedlongupdate;unsignedlongtim
eout;unsignedlonggarbage;char*endptr=NULL;unsignedlongRIP_TIMER_MAX=2147483647;u
nsignedlongRIP_TIMER_MIN=5;update=strtoul(argv[idx_number]->arg,&endptr,10);if(u
pdate>RIP_TIMER_MAX||update<RIP_TIMER_MIN||*endptr!='\0'){vty_out(vty,"updatetim
ervalueerror\n");returnCMD_WARNING_CONFIG_FAILED;}timeout=strtoul(argv[idx_numbe
r_2]->arg,&endptr,10);if(timeout>RIP_TIMER_MAX||timeout<RIP_TIMER_MIN||*endptr!=
'\0'){vty_out(vty,"timeouttimervalueerror\n");returnCMD_WARNING_CONFIG_FAILED;}g
arbage=strtoul(argv[idx_number_3]->arg,&endptr,10);if(garbage>RIP_TIMER_MAX||gar
bage<RIP_TIMER_MIN||*endptr!='\0'){vty_out(vty,"garbagetimervalueerror\n");retur
nCMD_WARNING_CONFIG_FAILED;}/*Seteachtimervalue.*/rip->update_time=update;rip->t
imeout_time=timeout;rip->garbage_time=garbage;/*Resetupdatetimerthread.*/rip_eve
nt(RIP_UPDATE_EVENT,0);returnCMD_SUCCESS;}DEFUN(no_rip_timers,no_rip_timers_cmd,
"notimersbasic[(0-65535)(0-65535)(0-65535)]",NO_STR"Adjustroutingtimers\n""Basic
routingprotocolupdatetimers\n""Routingtableupdatetimervalueinsecond.Defaultis30.
\n""Routinginformationtimeouttimer.Defaultis180.\n""Garbagecollectiontimer.Defau
ltis120.\n"){/*Seteachtimervaluetothedefault.*/rip->update_time=RIP_UPDATE_TIMER
_DEFAULT;rip->timeout_time=RIP_TIMEOUT_TIMER_DEFAULT;rip->garbage_time=RIP_GARBA
GE_TIMER_DEFAULT;/*Resetupdatetimerthread.*/rip_event(RIP_UPDATE_EVENT,0);return
CMD_SUCCESS;}structroute_table*rip_distance_table;structrip_distance{/*Distancev
aluefortheIPsourceprefix.*/uint8_tdistance;/*Nameoftheaccess-listtobematched.*/c
har*access_list;};staticstructrip_distance*rip_distance_new(void){returnXCALLOC(
MTYPE_RIP_DISTANCE,sizeof(structrip_distance));}staticvoidrip_distance_free(stru
ctrip_distance*rdistance){XFREE(MTYPE_RIP_DISTANCE,rdistance);}staticintrip_dist
ance_set(structvty*vty,constchar*distance_str,constchar*ip_str,constchar*access_
list_str){intret;structprefix_ipv4p;uint8_tdistance;structroute_node*rn;structri
p_distance*rdistance;ret=str2prefix_ipv4(ip_str,&p);if(ret==0){vty_out(vty,"Malf
ormedprefix\n");returnCMD_WARNING_CONFIG_FAILED;}distance=atoi(distance_str);/*G
etRIPdistancenode.*/rn=route_node_get(rip_distance_table,(structprefix*)&p);if(r
n->info){rdistance=rn->info;route_unlock_node(rn);}else{rdistance=rip_distance_n
ew();rn->info=rdistance;}/*Setdistancevalue.*/rdistance->distance=distance;/*Res
etaccess-listconfiguration.*/if(rdistance->access_list){free(rdistance->access_l
ist);rdistance->access_list=NULL;}if(access_list_str)rdistance->access_list=strd
up(access_list_str);returnCMD_SUCCESS;}staticintrip_distance_unset(structvty*vty
,constchar*distance_str,constchar*ip_str,constchar*access_list_str){intret;struc
tprefix_ipv4p;structroute_node*rn;structrip_distance*rdistance;ret=str2prefix_ip
v4(ip_str,&p);if(ret==0){vty_out(vty,"Malformedprefix\n");returnCMD_WARNING_CONF
IG_FAILED;}rn=route_node_lookup(rip_distance_table,(structprefix*)&p);if(!rn){vt
y_out(vty,"Can'tfindspecifiedprefix\n");returnCMD_WARNING_CONFIG_FAILED;}rdistan
ce=rn->info;if(rdistance->access_list)free(rdistance->access_list);rip_distance_
free(rdistance);rn->info=NULL;route_unlock_node(rn);route_unlock_node(rn);return
CMD_SUCCESS;}staticvoidrip_distance_reset(void){structroute_node*rn;structrip_di
stance*rdistance;for(rn=route_top(rip_distance_table);rn;rn=route_next(rn))if((r
distance=rn->info)!=NULL){if(rdistance->access_list)free(rdistance->access_list)
;rip_distance_free(rdistance);rn->info=NULL;route_unlock_node(rn);}}/*ApplyRIPin
formationtodistancemethod.*/uint8_trip_distance_apply(structrip_info*rinfo){stru
ctroute_node*rn;structprefix_ipv4p;structrip_distance*rdistance;structaccess_lis
t*alist;if(!rip)return0;memset(&p,0,sizeof(structprefix_ipv4));p.family=AF_INET;
p.prefix=rinfo->from;p.prefixlen=IPV4_MAX_BITLEN;/*Checksourceaddress.*/rn=route
_node_match(rip_distance_table,(structprefix*)&p);if(rn){rdistance=rn->info;rout
e_unlock_node(rn);if(rdistance->access_list){alist=access_list_lookup(AFI_IP,rdi
stance->access_list);if(alist==NULL)return0;if(access_list_apply(alist,&rinfo->r
p->p)==FILTER_DENY)return0;returnrdistance->distance;}elsereturnrdistance->dista
nce;}if(rip->distance)returnrip->distance;return0;}staticvoidrip_distance_show(s
tructvty*vty){structroute_node*rn;structrip_distance*rdistance;intheader=1;charb
uf[BUFSIZ];vty_out(vty,"Distance:(defaultis%d)\n",rip->distance?rip->distance:ZE
BRA_RIP_DISTANCE_DEFAULT);for(rn=route_top(rip_distance_table);rn;rn=route_next(
rn))if((rdistance=rn->info)!=NULL){if(header){vty_out(vty,"AddressDistanceList\n
");header=0;}sprintf(buf,"%s/%d",inet_ntoa(rn->p.u.prefix4),rn->p.prefixlen);vty
_out(vty,"%-20s%4d%s\n",buf,rdistance->distance,rdistance->access_list?rdistance
->access_list:"");}}DEFUN(rip_distance,rip_distance_cmd,"distance(1-255)","Admin
istrativedistance\n""Distancevalue\n"){intidx_number=1;rip->distance=atoi(argv[i
dx_number]->arg);returnCMD_SUCCESS;}DEFUN(no_rip_distance,no_rip_distance_cmd,"n
odistance(1-255)",NO_STR"Administrativedistance\n""Distancevalue\n"){rip->distan
ce=0;returnCMD_SUCCESS;}DEFUN(rip_distance_source,rip_distance_source_cmd,"dista
nce(1-255)A.B.C.D/M","Administrativedistance\n""Distancevalue\n""IPsourceprefix\
n"){intidx_number=1;intidx_ipv4_prefixlen=2;rip_distance_set(vty,argv[idx_number
]->arg,argv[idx_ipv4_prefixlen]->arg,NULL);returnCMD_SUCCESS;}DEFUN(no_rip_dista
nce_source,no_rip_distance_source_cmd,"nodistance(1-255)A.B.C.D/M",NO_STR"Admini
strativedistance\n""Distancevalue\n""IPsourceprefix\n"){intidx_number=2;intidx_i
pv4_prefixlen=3;rip_distance_unset(vty,argv[idx_number]->arg,argv[idx_ipv4_prefi
xlen]->arg,NULL);returnCMD_SUCCESS;}DEFUN(rip_distance_source_access_list,rip_di
stance_source_access_list_cmd,"distance(1-255)A.B.C.D/MWORD","Administrativedist
ance\n""Distancevalue\n""IPsourceprefix\n""Accesslistname\n"){intidx_number=1;in
tidx_ipv4_prefixlen=2;intidx_word=3;rip_distance_set(vty,argv[idx_number]->arg,a
rgv[idx_ipv4_prefixlen]->arg,argv[idx_word]->arg);returnCMD_SUCCESS;}DEFUN(no_ri
p_distance_source_access_list,no_rip_distance_source_access_list_cmd,"nodistance
(1-255)A.B.C.D/MWORD",NO_STR"Administrativedistance\n""Distancevalue\n""IPsource
prefix\n""Accesslistname\n"){intidx_number=2;intidx_ipv4_prefixlen=3;intidx_word
=4;rip_distance_unset(vty,argv[idx_number]->arg,argv[idx_ipv4_prefixlen]->arg,ar
gv[idx_word]->arg);returnCMD_SUCCESS;}/*UpdateECMProutestozebrawhenECMPisdisable
d.*/staticvoidrip_ecmp_disable(void){structroute_node*rp;structrip_info*rinfo,*t
mp_rinfo;structlist*list;structlistnode*node,*nextnode;if(!rip)return;for(rp=rou
te_top(rip->table);rp;rp=route_next(rp))if((list=rp->info)!=NULL&&listcount(list
)>1){rinfo=listgetdata(listhead(list));if(!rip_route_rte(rinfo))continue;/*Dropa
llotherentries,exceptthefirstone.*/for(ALL_LIST_ELEMENTS(list,node,nextnode,tmp_
rinfo))if(tmp_rinfo!=rinfo){RIP_TIMER_OFF(tmp_rinfo->t_timeout);RIP_TIMER_OFF(tm
p_rinfo->t_garbage_collect);list_delete_node(list,node);rip_info_free(tmp_rinfo)
;}/*Updatezebra.*/rip_zebra_ipv4_add(rp);/*Settheroutechangeflag.*/SET_FLAG(rinf
o->flags,RIP_RTF_CHANGED);/*Signaltheoutputprocesstotriggeranupdate.*/rip_event(
RIP_TRIGGERED_UPDATE,0);}}DEFUN(rip_allow_ecmp,rip_allow_ecmp_cmd,"allow-ecmp","
AllowEqualCostMultiPath\n"){if(rip->ecmp){vty_out(vty,"ECMPisalreadyenabled.\n")
;returnCMD_WARNING;}rip->ecmp=1;zlog_info("ECMPisenabled.");returnCMD_SUCCESS;}D
EFUN(no_rip_allow_ecmp,no_rip_allow_ecmp_cmd,"noallow-ecmp",NO_STR"AllowEqualCos
tMultiPath\n"){if(!rip->ecmp){vty_out(vty,"ECMPisalreadydisabled.\n");returnCMD_
WARNING;}rip->ecmp=0;zlog_info("ECMPisdisabled.");rip_ecmp_disable();returnCMD_S
UCCESS;}/*Printoutroutesupdatetime.*/staticvoidrip_vty_out_uptime(structvty*vty,
structrip_info*rinfo){time_tclock;structtm*tm;#defineTIME_BUF25chartimebuf[TIME_
BUF];structthread*thread;if((thread=rinfo->t_timeout)!=NULL){clock=thread_timer_
remain_second(thread);tm=gmtime(&clock);strftime(timebuf,TIME_BUF,"%M:%S",tm);vt
y_out(vty,"%5s",timebuf);}elseif((thread=rinfo->t_garbage_collect)!=NULL){clock=
thread_timer_remain_second(thread);tm=gmtime(&clock);strftime(timebuf,TIME_BUF,"
%M:%S",tm);vty_out(vty,"%5s",timebuf);}}staticconstchar*rip_route_type_print(int
sub_type){switch(sub_type){caseRIP_ROUTE_RTE:return"n";caseRIP_ROUTE_STATIC:retu
rn"s";caseRIP_ROUTE_DEFAULT:return"d";caseRIP_ROUTE_REDISTRIBUTE:return"r";caseR
IP_ROUTE_INTERFACE:return"i";default:return"?";}}DEFUN(show_ip_rip,show_ip_rip_c
md,"showiprip",SHOW_STRIP_STR"ShowRIProutes\n"){structroute_node*np;structrip_in
fo*rinfo=NULL;structlist*list=NULL;structlistnode*listnode=NULL;if(!rip)returnCM
D_SUCCESS;vty_out(vty,"Codes:R-RIP,C-connected,S-Static,O-OSPF,B-BGP\n""Sub-code
s:\n""(n)-normal,(s)-static,(d)-default,(r)-redistribute,\n""(i)-interface\n\n""
NetworkNextHopMetricFromTagTime\n");for(np=route_top(rip->table);np;np=route_nex
t(np))if((list=np->info)!=NULL)for(ALL_LIST_ELEMENTS_RO(list,listnode,rinfo)){in
tlen;len=vty_out(vty,"%c(%s)%s/%d",/*np->lock,Fordebugging.*/zebra_route_char(ri
nfo->type),rip_route_type_print(rinfo->sub_type),inet_ntoa(np->p.u.prefix4),np->
p.prefixlen);len=24-len;if(len>0)vty_out(vty,"%*s",len,"");switch(rinfo->nh.type
){caseNEXTHOP_TYPE_IPV4:caseNEXTHOP_TYPE_IPV4_IFINDEX:vty_out(vty,"%-20s%2d",ine
t_ntoa(rinfo->nh.gate.ipv4),rinfo->metric);break;caseNEXTHOP_TYPE_IFINDEX:vty_ou
t(vty,"0.0.0.0%2d",rinfo->metric);break;caseNEXTHOP_TYPE_BLACKHOLE:vty_out(vty,"
blackhole%2d",rinfo->metric);break;caseNEXTHOP_TYPE_IPV6:caseNEXTHOP_TYPE_IPV6_I
FINDEX:vty_out(vty,"V6AddressHidden%2d",rinfo->metric);break;}/*Routewhichexisti
nkernelroutingtable.*/if((rinfo->type==ZEBRA_ROUTE_RIP)&&(rinfo->sub_type==RIP_R
OUTE_RTE)){vty_out(vty,"%-15s",inet_ntoa(rinfo->from));vty_out(vty,"%3"ROUTE_TAG
_PRI"",(route_tag_t)rinfo->tag);rip_vty_out_uptime(vty,rinfo);}elseif(rinfo->met
ric==RIP_METRIC_INFINITY){vty_out(vty,"self");vty_out(vty,"%3"ROUTE_TAG_PRI"",(r
oute_tag_t)rinfo->tag);rip_vty_out_uptime(vty,rinfo);}else{if(rinfo->external_me
tric){len=vty_out(vty,"self(%s:%d)",zebra_route_string(rinfo->type),rinfo->exter
nal_metric);len=16-len;if(len>0)vty_out(vty,"%*s",len,"");}elsevty_out(vty,"self
");vty_out(vty,"%3"ROUTE_TAG_PRI,(route_tag_t)rinfo->tag);}vty_out(vty,"\n");}re
turnCMD_SUCCESS;}/*Vincent:formerly,itwasshow_ip_protocols_rip:"showipprotocols"
*/DEFUN(show_ip_rip_status,show_ip_rip_status_cmd,"showipripstatus",SHOW_STRIP_S
TR"ShowRIProutes\n""IProutingprotocolprocessparametersandstatistics\n"){structvr
f*vrf=vrf_lookup_by_id(VRF_DEFAULT);structinterface*ifp;structrip_interface*ri;e
xternconststructmessageri_version_msg[];constchar*send_version;constchar*receive
_version;if(!rip)returnCMD_SUCCESS;vty_out(vty,"RoutingProtocolis\"rip\"\n");vty
_out(vty,"Sendingupdatesevery%ldsecondswith+/-50%%,",rip->update_time);vty_out(v
ty,"nextduein%luseconds\n",thread_timer_remain_second(rip->t_update));vty_out(vt
y,"Timeoutafter%ldseconds,",rip->timeout_time);vty_out(vty,"garbagecollectafter%
ldseconds\n",rip->garbage_time);/*Filteringstatusshow.*/config_show_distribute(v
ty);/*Defaultmetricinformation.*/vty_out(vty,"Defaultredistributionmetricis%d\n"
,rip->default_metric);/*Redistributeinformation.*/vty_out(vty,"Redistributing:")
;config_write_rip_redistribute(vty,0);vty_out(vty,"\n");vty_out(vty,"Defaultvers
ioncontrol:sendversion%s,",lookup_msg(ri_version_msg,rip->version_send,NULL));if
(rip->version_recv==RI_RIP_VERSION_1_AND_2)vty_out(vty,"receiveanyversion\n");el
sevty_out(vty,"receiveversion%s\n",lookup_msg(ri_version_msg,rip->version_recv,N
ULL));vty_out(vty,"InterfaceSendRecvKey-chain\n");FOR_ALL_INTERFACES(vrf,ifp){ri
=ifp->info;if(!ri->running)continue;if(ri->enable_network||ri->enable_interface)
{if(ri->ri_send==RI_RIP_UNSPEC)send_version=lookup_msg(ri_version_msg,rip->versi
on_send,NULL);elsesend_version=lookup_msg(ri_version_msg,ri->ri_send,NULL);if(ri
->ri_receive==RI_RIP_UNSPEC)receive_version=lookup_msg(ri_version_msg,rip->versi
on_recv,NULL);elsereceive_version=lookup_msg(ri_version_msg,ri->ri_receive,NULL)
;vty_out(vty,"%-17s%-3s%-3s%s\n",ifp->name,send_version,receive_version,ri->key_
chain?ri->key_chain:"");}}vty_out(vty,"RoutingforNetworks:\n");config_write_rip_
network(vty,0);{intfound_passive=0;FOR_ALL_INTERFACES(vrf,ifp){ri=ifp->info;if((
ri->enable_network||ri->enable_interface)&&ri->passive){if(!found_passive){vty_o
ut(vty,"PassiveInterface(s):\n");found_passive=1;}vty_out(vty,"%s\n",ifp->name);
}}}vty_out(vty,"RoutingInformationSources:\n");vty_out(vty,"GatewayBadPacketsBad
RoutesDistanceLastUpdate\n");rip_peer_display(vty);rip_distance_show(vty);return
CMD_SUCCESS;}/*RIPconfigurationwritefunction.*/staticintconfig_write_rip(structv
ty*vty){intwrite=0;structroute_node*rn;structrip_distance*rdistance;if(rip){/*Ro
uterRIPstatement.*/vty_out(vty,"routerrip\n");write++;/*RIPversionstatement.Defa
ultisRIPversion2.*/if(rip->version_send!=RI_RIP_VERSION_2||rip->version_recv!=RI
_RIP_VERSION_1_AND_2)vty_out(vty,"version%d\n",rip->version_send);/*RIPtimerconf
iguration.*/if(rip->update_time!=RIP_UPDATE_TIMER_DEFAULT||rip->timeout_time!=RI
P_TIMEOUT_TIMER_DEFAULT||rip->garbage_time!=RIP_GARBAGE_TIMER_DEFAULT)vty_out(vt
y,"timersbasic%lu%lu%lu\n",rip->update_time,rip->timeout_time,rip->garbage_time)
;/*Defaultinformationconfiguration.*/if(rip->default_information){if(rip->defaul
t_information_route_map)vty_out(vty,"default-informationoriginateroute-map%s\n",
rip->default_information_route_map);elsevty_out(vty,"default-informationoriginat
e\n");}/*Redistributeconfiguration.*/config_write_rip_redistribute(vty,1);/*RIPo
ffset-listconfiguration.*/config_write_rip_offset_list(vty);/*RIPenablednetworka
ndinterfaceconfiguration.*/config_write_rip_network(vty,1);/*RIPdefaultmetriccon
figuration*/if(rip->default_metric!=RIP_DEFAULT_METRIC_DEFAULT)vty_out(vty,"defa
ult-metric%d\n",rip->default_metric);/*Distributeconfiguration.*/write+=config_w
rite_distribute(vty);/*Interfaceroutemapconfiguration*/write+=config_write_if_rm
ap(vty);/*Distanceconfiguration.*/if(rip->distance)vty_out(vty,"distance%d\n",ri
p->distance);/*RIPsourceIPprefixdistanceconfiguration.*/for(rn=route_top(rip_dis
tance_table);rn;rn=route_next(rn))if((rdistance=rn->info)!=NULL)vty_out(vty,"dis
tance%d%s/%d%s\n",rdistance->distance,inet_ntoa(rn->p.u.prefix4),rn->p.prefixlen
,rdistance->access_list?rdistance->access_list:"");/*ECMPconfiguration.*/if(rip-
>ecmp)vty_out(vty,"allow-ecmp\n");/*RIPstaticrouteconfiguration.*/for(rn=route_t
op(rip->route);rn;rn=route_next(rn))if(rn->info)vty_out(vty,"route%s/%d\n",inet_
ntoa(rn->p.u.prefix4),rn->p.prefixlen);}returnwrite;}/*RIPnodestructure.*/static
structcmd_noderip_node={RIP_NODE,"%s(config-router)#",1};/*Distribute-listupdate
functions.*/staticvoidrip_distribute_update(structdistribute*dist){structinterfa
ce*ifp;structrip_interface*ri;structaccess_list*alist;structprefix_list*plist;if
(!dist->ifname)return;ifp=if_lookup_by_name(dist->ifname,VRF_DEFAULT);if(ifp==NU
LL)return;ri=ifp->info;if(dist->list[DISTRIBUTE_V4_IN]){alist=access_list_lookup
(AFI_IP,dist->list[DISTRIBUTE_V4_IN]);if(alist)ri->list[RIP_FILTER_IN]=alist;els
eri->list[RIP_FILTER_IN]=NULL;}elseri->list[RIP_FILTER_IN]=NULL;if(dist->list[DI
STRIBUTE_V4_OUT]){alist=access_list_lookup(AFI_IP,dist->list[DISTRIBUTE_V4_OUT])
;if(alist)ri->list[RIP_FILTER_OUT]=alist;elseri->list[RIP_FILTER_OUT]=NULL;}else
ri->list[RIP_FILTER_OUT]=NULL;if(dist->prefix[DISTRIBUTE_V4_IN]){plist=prefix_li
st_lookup(AFI_IP,dist->prefix[DISTRIBUTE_V4_IN]);if(plist)ri->prefix[RIP_FILTER_
IN]=plist;elseri->prefix[RIP_FILTER_IN]=NULL;}elseri->prefix[RIP_FILTER_IN]=NULL
;if(dist->prefix[DISTRIBUTE_V4_OUT]){plist=prefix_list_lookup(AFI_IP,dist->prefi
x[DISTRIBUTE_V4_OUT]);if(plist)ri->prefix[RIP_FILTER_OUT]=plist;elseri->prefix[R
IP_FILTER_OUT]=NULL;}elseri->prefix[RIP_FILTER_OUT]=NULL;}voidrip_distribute_upd
ate_interface(structinterface*ifp){structdistribute*dist;dist=distribute_lookup(
ifp->name);if(dist)rip_distribute_update(dist);}/*Updateallinterface'sdistribute
list.*//*ARGSUSED*/staticvoidrip_distribute_update_all(structprefix_list*notused
){structvrf*vrf=vrf_lookup_by_id(VRF_DEFAULT);structinterface*ifp;FOR_ALL_INTERF
ACES(vrf,ifp)rip_distribute_update_interface(ifp);}/*ARGSUSED*/staticvoidrip_dis
tribute_update_all_wrapper(structaccess_list*notused){rip_distribute_update_all(
NULL);}/*Deletealladdedriproute.*/voidrip_clean(void){inti;structroute_node*rp;s
tructrip_info*rinfo=NULL;structlist*list=NULL;structlistnode*listnode=NULL;if(ri
p){QOBJ_UNREG(rip);/*ClearRIProutes*/for(rp=route_top(rip->table);rp;rp=route_ne
xt(rp))if((list=rp->info)!=NULL){rinfo=listgetdata(listhead(list));if(rip_route_
rte(rinfo))rip_zebra_ipv4_delete(rp);for(ALL_LIST_ELEMENTS_RO(list,listnode,rinf
o)){RIP_TIMER_OFF(rinfo->t_timeout);RIP_TIMER_OFF(rinfo->t_garbage_collect);rip_
info_free(rinfo);}list_delete_and_null(&list);rp->info=NULL;route_unlock_node(rp
);}/*CancelRIPrelatedtimers.*/RIP_TIMER_OFF(rip->t_update);RIP_TIMER_OFF(rip->t_
triggered_update);RIP_TIMER_OFF(rip->t_triggered_interval);/*Cancelreadthread.*/
THREAD_READ_OFF(rip->t_read);/*CloseRIPsocket.*/if(rip->sock>=0){close(rip->sock
);rip->sock=-1;}stream_free(rip->obuf);/*StaticRIProuteconfiguration.*/for(rp=ro
ute_top(rip->route);rp;rp=route_next(rp))if(rp->info){rp->info=NULL;route_unlock
_node(rp);}/*RIPneighborconfiguration.*/for(rp=route_top(rip->neighbor);rp;rp=ro
ute_next(rp))if(rp->info){rp->info=NULL;route_unlock_node(rp);}/*Redistributerel
atedclear.*/if(rip->default_information_route_map)free(rip->default_information_
route_map);for(i=0;i<ZEBRA_ROUTE_MAX;i++)if(rip->route_map[i].name)free(rip->rou
te_map[i].name);XFREE(MTYPE_ROUTE_TABLE,rip->table);XFREE(MTYPE_ROUTE_TABLE,rip-
>route);XFREE(MTYPE_ROUTE_TABLE,rip->neighbor);XFREE(MTYPE_RIP,rip);rip=NULL;}ri
p_clean_network();rip_passive_nondefault_clean();rip_offset_clean();rip_interfac
es_clean();rip_distance_reset();rip_redistribute_clean();}/*Resetallvaluestothed
efaultsettings.*/voidrip_reset(void){/*Resetglobalcounters.*/rip_global_route_ch
anges=0;rip_global_queries=0;/*Callripdrelatedresetfunctions.*/rip_debug_reset()
;rip_route_map_reset();/*Calllibraryresetfunctions.*/vty_reset();access_list_res
et();prefix_list_reset();distribute_list_reset();rip_interfaces_reset();rip_dist
ance_reset();rip_zclient_reset();}staticvoidrip_if_rmap_update(structif_rmap*if_
rmap){structinterface*ifp;structrip_interface*ri;structroute_map*rmap;ifp=if_loo
kup_by_name(if_rmap->ifname,VRF_DEFAULT);if(ifp==NULL)return;ri=ifp->info;if(if_
rmap->routemap[IF_RMAP_IN]){rmap=route_map_lookup_by_name(if_rmap->routemap[IF_R
MAP_IN]);if(rmap)ri->routemap[IF_RMAP_IN]=rmap;elseri->routemap[IF_RMAP_IN]=NULL
;}elseri->routemap[RIP_FILTER_IN]=NULL;if(if_rmap->routemap[IF_RMAP_OUT]){rmap=r
oute_map_lookup_by_name(if_rmap->routemap[IF_RMAP_OUT]);if(rmap)ri->routemap[IF_
RMAP_OUT]=rmap;elseri->routemap[IF_RMAP_OUT]=NULL;}elseri->routemap[RIP_FILTER_O
UT]=NULL;}voidrip_if_rmap_update_interface(structinterface*ifp){structif_rmap*if
_rmap;if_rmap=if_rmap_lookup(ifp->name);if(if_rmap)rip_if_rmap_update(if_rmap);}
staticvoidrip_routemap_update_redistribute(void){inti;if(rip){for(i=0;i<ZEBRA_RO
UTE_MAX;i++){if(rip->route_map[i].name)rip->route_map[i].map=route_map_lookup_by
_name(rip->route_map[i].name);}}}/*ARGSUSED*/staticvoidrip_routemap_update(const
char*notused){structvrf*vrf=vrf_lookup_by_id(VRF_DEFAULT);structinterface*ifp;FO
R_ALL_INTERFACES(vrf,ifp)rip_if_rmap_update_interface(ifp);rip_routemap_update_r
edistribute();}/*Allocatenewripstructureandsetdefaultvalue.*/voidrip_init(void){
/*Installtopnodes.*/install_node(&rip_node,config_write_rip);/*Installripcommand
s.*/install_element(VIEW_NODE,&show_ip_rip_cmd);install_element(VIEW_NODE,&show_
ip_rip_status_cmd);install_element(CONFIG_NODE,&router_rip_cmd);install_element(
CONFIG_NODE,&no_router_rip_cmd);install_default(RIP_NODE);install_element(RIP_NO
DE,&rip_version_cmd);install_element(RIP_NODE,&no_rip_version_cmd);install_eleme
nt(RIP_NODE,&rip_default_metric_cmd);install_element(RIP_NODE,&no_rip_default_me
tric_cmd);install_element(RIP_NODE,&rip_timers_cmd);install_element(RIP_NODE,&no
_rip_timers_cmd);install_element(RIP_NODE,&rip_route_cmd);install_element(RIP_NO
DE,&no_rip_route_cmd);install_element(RIP_NODE,&rip_distance_cmd);install_elemen
t(RIP_NODE,&no_rip_distance_cmd);install_element(RIP_NODE,&rip_distance_source_c
md);install_element(RIP_NODE,&no_rip_distance_source_cmd);install_element(RIP_NO
DE,&rip_distance_source_access_list_cmd);install_element(RIP_NODE,&no_rip_distan
ce_source_access_list_cmd);install_element(RIP_NODE,&rip_allow_ecmp_cmd);install
_element(RIP_NODE,&no_rip_allow_ecmp_cmd);/*Debugrelatedinit.*/rip_debug_init();
/*Accesslistinstall.*/access_list_init();access_list_add_hook(rip_distribute_upd
ate_all_wrapper);access_list_delete_hook(rip_distribute_update_all_wrapper);/*Pr
efixlistinitialize.*/prefix_list_init();prefix_list_add_hook(rip_distribute_upda
te_all);prefix_list_delete_hook(rip_distribute_update_all);/*Distributelistinsta
ll.*/distribute_list_init(RIP_NODE);distribute_list_add_hook(rip_distribute_upda
te);distribute_list_delete_hook(rip_distribute_update);/*Route-map*/rip_route_ma
p_init();rip_offset_init();route_map_add_hook(rip_routemap_update);route_map_del
ete_hook(rip_routemap_update);if_rmap_init(RIP_NODE);if_rmap_hook_add(rip_if_rma
p_update);if_rmap_hook_delete(rip_if_rmap_update);/*Distancecontrol.*/rip_distan
ce_table=route_table_init();}