/**IS-ISRout(e)ingprotocol-isisd.h**Copyright(C)2001,2002SampoSaaristo*TampereUn
iversityofTechnology*InstituteofCommunicationsEngineering**Thisprogramisfreesoft
ware;youcanredistributeitand/ormodifyit*underthetermsoftheGNUGeneralPublicLicens
easpublishedbytheFree*SoftwareFoundation;eitherversion2oftheLicense,or(atyouropt
ion)*anylaterversion.**Thisprogramisdistributedinthehopethatitwillbeuseful,butWI
THOUT*ANYWARRANTY;withouteventheimpliedwarrantyofMERCHANTABILITYor*FITNESSFORAPA
RTICULARPURPOSE.SeetheGNUGeneralPublicLicensefor*moredetails.**Youshouldhaverece
ivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;ifn
ot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110
-1301USA*/#ifndefISISD_H#defineISISD_H#include"vty.h"#include"isisd/isis_constan
ts.h"#include"isisd/isis_common.h"#include"isisd/isis_redist.h"#include"isis_fla
gs.h"#include"dict.h"#include"isis_memory.h"#include"qobj.h"externstructzebra_pr
ivs_tisisd_privs;/*uncommentifyouareadeveloperinbughunt*//*#defineEXTREME_DEBUG*
//*#defineEXTREME_DICT_DEBUG*/structisis{unsignedlongprocess_id;intsysid_set;uin
t8_tsysid[ISIS_SYS_ID_LEN];/*SystemIDforthisIS*/uint32_trouter_id;/*RouterIDfrom
zebra*/structlist*area_list;/*listofIS-ISareas*/structlist*init_circ_list;struct
list*nexthops;/*IPv4nexthopsfromthisIS*/structlist*nexthops6;/*IPv6nexthopsfromt
hisIS*/uint8_tmax_area_addrs;/*maximumAreaAdresses*/structarea_addr*man_area_add
rs;/*manualAreaAddresses*/uint32_tdebugs;/*bitmapfordebug*/time_tuptime;/*whendi
dwestart*/structthread*t_dync_clean;/*dynamichostnamecachecleanupthread*/uint32_
tcircuit_ids_used[8];/*256bitstotrackcircuitids1through255*/structroute_table*ex
t_info[REDIST_PROTOCOL_COUNT];QOBJ_FIELDS};externstructisis*isis;DECLARE_QOBJ_TY
PE(isis_area)structisis_area{structisis*isis;/*backpointer*/dict_t*lspdb[ISIS_LE
VELS];/*link-statedbs*/structisis_spftree*spftree[ISIS_LEVELS];/*Thev4SPTs*/stru
ctroute_table*route_table[ISIS_LEVELS];/*IPv4routes*/structisis_spftree*spftree6
[ISIS_LEVELS];/*Thev6SPTs*/structroute_table*route_table6[ISIS_LEVELS];/*IPv6rou
tes*/#defineDEFAULT_LSP_MTU1497unsignedintlsp_mtu;/*SizeofLSPstogenerate*/struct
list*circuit_list;/*IS-IScircuits*/structflagsflags;structthread*t_tick;/*LSPwal
ker*/structthread*t_lsp_refresh[ISIS_LEVELS];/*t_lsp_refreshisusedintwoways:*a)r
egularrefreshofLSPs*b)(possiblythrottled)updatestoLSPs**Thelsp_regenerate_pendin
gflagtrackswhetherthetimerisactive*forthea)ortheb)case.**Itisofutmostimportancet
oclearthisflagwhenthetimeris*rescheduledfornormalrefresh,becauseotherwise,update
swill*bedelayeduntilthenextregularrefresh.*/intlsp_regenerate_pending[ISIS_LEVEL
S];/**Configurables*/structisis_passwdarea_passwd;structisis_passwddomain_passwd
;/*dowesupportdynamichostnames?*/chardynhostname;/*dowesupportnewstylemetrics?*/
charnewmetric;charoldmetric;/*identifiestheroutinginstance*/char*area_tag;/*area
addressesforthisarea*/structlist*area_addrs;uint16_tmax_lsp_lifetime[ISIS_LEVELS
];charis_type;/*level-1level-1-2orlevel-2-only*//*areweoverloaded?*/charoverload
_bit;/*L1/L2routeridentifierforinter-areatraffic*/charattached_bit;uint16_tlsp_r
efresh[ISIS_LEVELS];/*minimumtimeallowedbeforelspretransmission*/uint16_tlsp_gen
_interval[ISIS_LEVELS];/*minintervalbetweenbetweenconsequtiveSPFs*/uint16_tmin_s
pf_interval[ISIS_LEVELS];/*thepercentageofLSPmtusizeused,beforegeneratinganewfra
g*/intlsp_frag_threshold;intip_circuits;/*loggingadjacencychanges?*/uint8_tlog_a
dj_changes;/*multitopologysettings*/structlist*mt_settings;intipv6_circuits;/*Co
unters*/uint32_tcircuit_state_changes;structisis_redistredist_settings[REDIST_PR
OTOCOL_COUNT][ZEBRA_ROUTE_MAX+1][ISIS_LEVELS];structroute_table*ext_reach[REDIST
_PROTOCOL_COUNT][ISIS_LEVELS];structspf_backoff*spf_delay_ietf[ISIS_LEVELS];/*St
ructurewithIETFSPFalgoparameters*/structthread*spf_timer[ISIS_LEVELS];QOBJ_FIELD
S};DECLARE_QOBJ_TYPE(isis_area)voidisis_init(void);voidisis_new(unsignedlong);st
ructisis_area*isis_area_create(constchar*);structisis_area*isis_area_lookup(cons
tchar*);intisis_area_get(structvty*vty,constchar*area_tag);voidprint_debug(struc
tvty*,int,int);voidisis_area_overload_bit_set(structisis_area*area,booloverload_
bit);voidisis_area_attached_bit_set(structisis_area*area,boolattached_bit);voidi
sis_area_dynhostname_set(structisis_area*area,booldynhostname);voidisis_area_met
ricstyle_set(structisis_area*area,boolold_metric,boolnew_metric);voidisis_area_l
sp_mtu_set(structisis_area*area,unsignedintlsp_mtu);voidisis_area_is_type_set(st
ructisis_area*area,intis_type);voidisis_area_max_lsp_lifetime_set(structisis_are
a*area,intlevel,uint16_tmax_lsp_lifetime);voidisis_area_lsp_refresh_set(structis
is_area*area,intlevel,uint16_tlsp_refresh);/*IS_LEVEL_1setsarea_passwd,IS_LEVEL_
2domain_passwd*/intisis_area_passwd_unset(structisis_area*area,intlevel);intisis
_area_passwd_cleartext_set(structisis_area*area,intlevel,constchar*passwd,uint8_
tsnp_auth);intisis_area_passwd_hmac_md5_set(structisis_area*area,intlevel,constc
har*passwd,uint8_tsnp_auth);voidisis_vty_init(void);/*Masterofthreads.*/externst
ructthread_master*master;#defineDEBUG_ADJ_PACKETS(1<<0)#defineDEBUG_CHECKSUM_ERR
ORS(1<<1)#defineDEBUG_LOCAL_UPDATES(1<<2)#defineDEBUG_PROTOCOL_ERRORS(1<<3)#defi
neDEBUG_SNP_PACKETS(1<<4)#defineDEBUG_UPDATE_PACKETS(1<<5)#defineDEBUG_SPF_EVENT
S(1<<6)#defineDEBUG_SPF_STATS(1<<7)#defineDEBUG_SPF_TRIGGERS(1<<8)#defineDEBUG_R
TE_EVENTS(1<<9)#defineDEBUG_EVENTS(1<<10)#defineDEBUG_ZEBRA(1<<11)#defineDEBUG_P
ACKET_DUMP(1<<12)#defineDEBUG_LSP_GEN(1<<13)#defineDEBUG_LSP_SCHED(1<<14)#define
lsp_debug(...)\do{\if(isis->debugs&DEBUG_LSP_GEN)\zlog_debug(__VA_ARGS__);\}whil
e(0)#definesched_debug(...)\do{\if(isis->debugs&DEBUG_LSP_SCHED)\zlog_debug(__VA
_ARGS__);\}while(0)#defineDEBUG_TE(1<<13)#defineIS_DEBUG_ISIS(x)(isis->debugs&x)
#endif/*ISISD_H*/