/**IS-ISRout(e)ingprotocol-isis_lsp.h*LSPprocessing**Copyright(C)2001,2002SampoS
aaristo*TampereUniversityofTechnology*InstituteofCommunicationsEngineering**This
programisfreesoftware;youcanredistributeitand/ormodifyit*underthetermsoftheGNUGe
neralPublicLicenseaspublishedbytheFree*SoftwareFoundation;eitherversion2oftheLic
ense,or(atyouroption)*anylaterversion.**Thisprogramisdistributedinthehopethatitw
illbeuseful,butWITHOUT*ANYWARRANTY;withouteventheimpliedwarrantyofMERCHANTABILIT
Yor*FITNESSFORAPARTICULARPURPOSE.SeetheGNUGeneralPublicLicensefor*moredetails.**
YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seet
hefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFlo
or,Boston,MA02110-1301USA*/#ifndef_ZEBRA_ISIS_LSP_H#define_ZEBRA_ISIS_LSP_H#incl
ude"isisd/isis_pdu.h"/*Structureforisis_lsp,thisstructurewillonlysupportthefixed
*SystemID(Currently6)(atleastfornow).Inordertosupportmore*Wewillhavetosplitthehe
aderintotwoparts,andforreadability*sakeitshouldbetterbeavoided*/structisis_lsp{s
tructisis_lsp_hdrhdr;structstream*pdu;/*fullpdulsp*/union{structlist*frags;struc
tisis_lsp*zero_lsp;}lspu;uint32_tSRMflags[ISIS_MAX_CIRCUITS];uint32_tSSNflags[IS
IS_MAX_CIRCUITS];intlevel;/*L1orL2?*/intscheduled;/*scheduledforsending*/time_ti
nstalled;time_tlast_generated;intown_lsp;/*usedfor60secondcountingwhenrem_lifeti
meiszero*/intage_out;structisis_area*area;structisis_tlvs*tlvs;};dict_t*lsp_db_i
nit(void);voidlsp_db_destroy(dict_t*lspdb);intlsp_tick(structthread*thread);intl
sp_generate(structisis_area*area,intlevel);intlsp_regenerate_schedule(structisis
_area*area,intlevel,intall_pseudo);intlsp_generate_pseudo(structisis_circuit*cir
cuit,intlevel);intlsp_regenerate_schedule_pseudo(structisis_circuit*circuit,intl
evel);structisis_lsp*lsp_new(structisis_area*area,uint8_t*lsp_id,uint16_trem_lif
etime,uint32_tseq_num,uint8_tlsp_bits,uint16_tchecksum,structisis_lsp*lsp0,intle
vel);structisis_lsp*lsp_new_from_recv(structisis_lsp_hdr*hdr,structisis_tlvs*tlv
s,structstream*stream,structisis_lsp*lsp0,structisis_area*area,intlevel);voidlsp
_insert(structisis_lsp*lsp,dict_t*lspdb);structisis_lsp*lsp_search(uint8_t*id,di
ct_t*lspdb);voidlsp_build_list(uint8_t*start_id,uint8_t*stop_id,uint8_tnum_lsps,
structlist*list,dict_t*lspdb);voidlsp_build_list_nonzero_ht(uint8_t*start_id,uin
t8_t*stop_id,structlist*list,dict_t*lspdb);voidlsp_search_and_destroy(uint8_t*id
,dict_t*lspdb);voidlsp_purge_pseudo(uint8_t*id,structisis_circuit*circuit,intlev
el);voidlsp_purge_non_exist(intlevel,structisis_lsp_hdr*hdr,structisis_area*area
);#defineLSP_EQUAL1#defineLSP_NEWER2#defineLSP_OLDER3#defineLSP_PSEUDO_ID(I)((I)
[ISIS_SYS_ID_LEN])#defineLSP_FRAGMENT(I)((I)[ISIS_SYS_ID_LEN+1])#defineOWNLSPID(
I)\memcpy((I),isis->sysid,ISIS_SYS_ID_LEN);\(I)[ISIS_SYS_ID_LEN]=0;\(I)[ISIS_SYS
_ID_LEN+1]=0intlsp_id_cmp(uint8_t*id1,uint8_t*id2);intlsp_compare(char*areatag,s
tructisis_lsp*lsp,uint32_tseqno,uint16_tchecksum,uint16_trem_lifetime);voidlsp_u
pdate(structisis_lsp*lsp,structisis_lsp_hdr*hdr,structisis_tlvs*tlvs,structstrea
m*stream,structisis_area*area,intlevel,boolconfusion);voidlsp_inc_seqno(structis
is_lsp*lsp,uint32_tseqno);voidlsp_print(structisis_lsp*lsp,structvty*vty,chardyn
host);voidlsp_print_detail(structisis_lsp*lsp,structvty*vty,chardynhost);intlsp_
print_all(structvty*vty,dict_t*lspdb,chardetail,chardynhost);/*setsSRMflagsforal
lactivecircuitsofanlsp*/voidlsp_set_all_srmflags(structisis_lsp*lsp);#endif/*ISI
S_LSP*/