/**IS-ISRout(e)ingprotocol-isis_te.c**ThisisanimplementationofRFC5305,RFC5307and
RFC7810**Copyright(C)2014OrangeLabs*http://www.orange.com**ThisfileispartofGNUZe
bra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodifyit*underthetermsoft
heGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eitherversion2,
or(atyouroption)any*laterversion.**GNUZebraisdistributedinthehopethatitwillbeuse
ful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITN
ESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshoul
dhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCO
PYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Bosto
n,MA02110-1301USA*/#ifndef_ZEBRA_ISIS_MPLS_TE_H#define_ZEBRA_ISIS_MPLS_TE_H/**Tr
afficEngineeringinformationaretransportthroughLSP:*-ExtendedISReachabilityTLV=22
*-TrafficEngineeringRouterIDTLV=134*-ExtendedIPReachabilityTLV=135*-Inter-ASReac
habilityInformationTLV=141**andsupportfollowingsub-TLV:**NameValueStatus*_______
__________________________________________*Administartivegroup(color)3RFC5305*Li
nkLocal/RemoteIdentifiers4RFC5307*IPv4interfaceaddress6RFC5305*IPv4neighboraddre
ss8RFC5305*Maximumlinkbandwidth9RFC5305*Reservablelinkbandwidth10RFC5305*Unreser
vedbandwidth11RFC5305*TEDefaultmetric18RFC5305*LinkProtectionType20RFC5307*Inter
faceSwitchingCapability21RFC5307*RemoteASnumber24RFC5316*IPv4RemoteASBRidentifie
r25RFC5316**//*NOTE:RFC5316isnotyetsupportedinthisversion*//*Followingdefinethet
ypeofTElinkregardingthevariousRFC*/#defineSTD_TE0x01#defineGMPLS0x02#defineINTER
_AS0x04#defineFLOOD_L10x10#defineFLOOD_L20x20#defineFLOOD_AS0x40#defineEMULATED0
x80#defineIS_STD_TE(x)(x&STD_TE)#defineIS_INTER_AS(x)(x&INTER_AS)#defineIS_EMULA
TED(x)(x&EMULATED)#defineIS_FLOOD_L1(x)(x&FLOOD_L1)#defineIS_FLOOD_L2(x)(x&FLOOD
_L2)#defineIS_FLOOD_AS(x)(x&FLOOD_AS)#defineIS_INTER_AS_EMU(x)(x&INTER_AS&EMULAT
ED)#defineIS_INTER_AS_AS(x)(x&INTER_AS&FLOOD_AS)/**FollowingsectiondefinessubTLV
(tag,length,value)structures,*usedforTrafficEngineering.*/structsubtlv_header{ui
nt8_ttype;/*sub_TLV_XXXtype(seeabove)*/uint8_tlength;/*Valueportiononly,inbyte*/
};#defineMAX_SUBTLV_SIZE256#defineSUBTLV_HDR_SIZE2/*(sizeof(structsub_tlv_header
))*/#defineSUBTLV_SIZE(stlvh)(SUBTLV_HDR_SIZE+(stlvh)->length)#defineSUBTLV_HDR_
TOP(lsph)(structsubtlv_header*)((char*)(lsph)+ISIS_LSP_HEADER_SIZE)#defineSUBTLV
_HDR_NEXT(stlvh)(structsubtlv_header*)((char*)(stlvh)+SUBTLV_SIZE(stlvh))#define
SUBTLV_TYPE(stlvh)stlvh.header.type#defineSUBTLV_LEN(stlvh)stlvh.header.length#d
efineSUBTLV_VAL(stlvh)stlvh.value#defineSUBTLV_DATA(stlvh)stlvh+SUBTLV_HDR_SIZE#
defineSUBTLV_DEF_SIZE4/*LinkSub-TLV:ResourceClass/Color-RFC5305*/#defineTE_SUBTL
V_ADMIN_GRP3structte_subtlv_admin_grp{structsubtlv_headerheader;/*Valuelengthis4
octets.*/uint32_tvalue;/*Admin.groupmembership.*/}__attribute__((__packed__));/*
LinkLocal/RemoteIdentifiers-RFC5307*/#defineTE_SUBTLV_LLRI4#defineTE_SUBTLV_LLRI
_SIZE8structte_subtlv_llri{structsubtlv_headerheader;/*Valuelengthis8octets.*/ui
nt32_tlocal;/*LinkLocalIdentifier*/uint32_tremote;/*LinkRemoteIdentifier*/}__att
ribute__((__packed__));/*LinkSub-TLV:LocalInterfaceIPAddress-RFC5305*/#defineTE_
SUBTLV_LOCAL_IPADDR6structte_subtlv_local_ipaddr{structsubtlv_headerheader;/*Val
uelengthis4xNoctets.*/structin_addrvalue;/*LocalIPaddress(es).*/}__attribute__((
__packed__));/*LinkSub-TLV:NeighborInterfaceIPAddress-RFC5305*/#defineTE_SUBTLV_
RMT_IPADDR8structte_subtlv_rmt_ipaddr{structsubtlv_headerheader;/*Valuelengthis4
xNoctets.*/structin_addrvalue;/*Neighbor'sIPaddress(es).*/}__attribute__((__pack
ed__));/*LinkSub-TLV:MaximumBandwidth-RFC5305*/#defineTE_SUBTLV_MAX_BW9structte_
subtlv_max_bw{structsubtlv_headerheader;/*Valuelengthis4octets.*/floatvalue;/*by
tes/sec*/}__attribute__((__packed__));/*LinkSub-TLV:MaximumReservableBandwidth-R
FC5305*/#defineTE_SUBTLV_MAX_RSV_BW10structte_subtlv_max_rsv_bw{structsubtlv_hea
derheader;/*Valuelengthis4octets.*/floatvalue;/*bytes/sec*/}__attribute__((__pac
ked__));/*LinkSub-TLV:UnreservedBandwidth-RFC5305*/#defineTE_SUBTLV_UNRSV_BW11#d
efineTE_SUBTLV_UNRSV_SIZE32structte_subtlv_unrsv_bw{structsubtlv_headerheader;/*
Valuelengthis32octets.*/floatvalue[8];/*Oneforeachprioritylevel.*/}__attribute__
((__packed__));/*LinkSub-TLV:TrafficEngineeringMetric-RFC5305*/#defineTE_SUBTLV_
TE_METRIC18#defineTE_SUBTLV_TE_METRIC_SIZE3structte_subtlv_te_metric{structsubtl
v_headerheader;/*Valuelengthis4octets.*/uint8_tvalue[3];/*LinkmetricforTEpurpose
.*/}__attribute__((__packed__));/*RemoteASNumbersub-TLV-RFC5316*/#defineTE_SUBTL
V_RAS24structte_subtlv_ras{structsubtlv_headerheader;/*Valuelengthis4octets.*/ui
nt32_tvalue;/*RemoteASnumber*/}__attribute__((__packed__));/*IPv4RemoteASBRIDSub
-TLV-RFC5316*/#defineTE_SUBTLV_RIP25structte_subtlv_rip{structsubtlv_headerheade
r;/*Valuelengthis4octets.*/structin_addrvalue;/*RemoteASBRIPaddress*/}__attribut
e__((__packed__));/*TEMetricExtensions-RFC7810*//*LinkSub-TLV:AverageLinkDelay*/
#defineTE_SUBTLV_AV_DELAY33structte_subtlv_av_delay{structsubtlv_headerheader;/*
Valuelengthis4bytes.*/uint32_tvalue;/*Averagedelayinmicro-secondsonly24bits=>0..
.16777215withAnomalousBit(A)asUppermostbit*/}__attribute__((__packed__));/*LinkS
ub-TLV:Low/HighLinkDelay*/#defineTE_SUBTLV_MM_DELAY34#defineTE_SUBTLV_MM_DELAY_S
IZE8structte_subtlv_mm_delay{structsubtlv_headerheader;/*Valuelengthis8bytes.*/u
int32_tlow;/*lowdelayinmicro-secondsonly24bits=>0...16777215withAnomalousBit(A)a
sUppermostbit*/uint32_thigh;/*highdelayinmicro-secondsonly24bits=>0...16777215*/
}__attribute__((__packed__));/*LinkSub-TLV:LinkDelayVariationi.e.Jitter*/#define
TE_SUBTLV_DELAY_VAR35structte_subtlv_delay_var{structsubtlv_headerheader;/*Value
lengthis4bytes.*/uint32_tvalue;/*intervalinmicro-secondsonly24bits=>0...16777215
*/}__attribute__((__packed__));/*LinkSub-TLV:RoutineUnidirectionalLinkPacketLoss
*/#defineTE_SUBTLV_PKT_LOSS36structte_subtlv_pkt_loss{structsubtlv_headerheader;
/*Valuelengthis4bytes.*/uint32_tvalue;/*inpercentageoftotaltrafficonly24bits(2^2
4-2)withAnomalousBit(A)asUppermostbit*/}__attribute__((__packed__));/*LinkSub-TL
V:UnidirectionalResidualBandwidth*//*Optional*/#defineTE_SUBTLV_RES_BW37structte
_subtlv_res_bw{structsubtlv_headerheader;/*Valuelengthis4bytes.*/floatvalue;/*ba
ndwidthinIEEEfloatingpointformatwithunitsinbytespersecond*/}__attribute__((__pac
ked__));/*LinkSub-TLV:UnidirectionalAvailableBandwidth*//*Optional*/#defineTE_SU
BTLV_AVA_BW38structte_subtlv_ava_bw{structsubtlv_headerheader;/*Valuelengthis4oc
tets.*/floatvalue;/*bandwidthinIEEEfloatingpointformatwithunitsinbytespersecond*
/}__attribute__((__packed__));/*LinkSub-TLV:UnidirectionalUtilizedBandwidth*//*O
ptional*/#defineTE_SUBTLV_USE_BW39structte_subtlv_use_bw{structsubtlv_headerhead
er;/*Valuelengthis4octets.*/floatvalue;/*bandwidthinIEEEfloatingpointformatwithu
nitsinbytespersecond*/}__attribute__((__packed__));#defineTE_SUBTLV_MAX40/*LastS
UBTLV+1*//*FollowingdeclarationconcernstheMPLS-TEandLINk-TEmanagement*/typedefen
um_status_t{disable,enable,learn}status_t;/*ModeforInter-ASLSP*//*TODO:Checkhowi
fLSPisfloodedinRFC5316*/typedefenum_interas_mode_t{off,region,as,emulate}interas
_mode_t;#defineIS_MPLS_TE(m)(m.status==enable)#defineIS_CIRCUIT_TE(c)(c->status=
=enable)/*Followingstructureareinternaluseonly.*/structisis_mpls_te{/*StatusofMP
LS-TE:enableordisable*/status_tstatus;/*L1,L1-L2,L2-Only*/uint8_tlevel;/*RFC5316
*/interas_mode_tinter_as;structin_addrinteras_areaid;/*CircuitlistonwhichTEareen
able*/structlist*cir_list;/*MPLS_TErouterID*/structin_addrrouter_id;};externstru
ctisis_mpls_teisisMplsTE;structmpls_te_circuit{/*StatusofMPLS-TEonthisinterface*
/status_tstatus;/*TypeofMPLS-TEcircuit:STD_TE(RFC5305),INTER_AS(RFC5316),*INTER_
AS_EMU(RFC5316emulated)*/uint8_ttype;/*Totalsizeofsub_tlvs*/uint8_tlength;/*Stor
esubTLVinnetworkbyteorder.*//*RFC5305*/structte_subtlv_admin_grpadmin_grp;/*RFC5
307*/structte_subtlv_llrillri;/*RFC5305*/structte_subtlv_local_ipaddrlocal_ipadd
r;structte_subtlv_rmt_ipaddrrmt_ipaddr;structte_subtlv_max_bwmax_bw;structte_sub
tlv_max_rsv_bwmax_rsv_bw;structte_subtlv_unrsv_bwunrsv_bw;structte_subtlv_te_met
ricte_metric;/*RFC5316*/structte_subtlv_rasras;structte_subtlv_riprip;/*RFC7810*
/structte_subtlv_av_delayav_delay;structte_subtlv_mm_delaymm_delay;structte_subt
lv_delay_vardelay_var;structte_subtlv_pkt_losspkt_loss;structte_subtlv_res_bwres
_bw;structte_subtlv_ava_bwava_bw;structte_subtlv_use_bwuse_bw;};/*Prototypes.*/v
oidisis_mpls_te_init(void);structmpls_te_circuit*mpls_te_circuit_new(void);struc
tsbuf;voidmpls_te_print_detail(structsbuf*buf,intindent,uint8_t*subtlvs,uint8_ts
ubtlv_len);voidset_circuitparams_local_ipaddr(structmpls_te_circuit*,structin_ad
dr);voidset_circuitparams_rmt_ipaddr(structmpls_te_circuit*,structin_addr);uint8
_tsubtlvs_len(structmpls_te_circuit*);uint8_tadd_te_subtlvs(uint8_t*,structmpls_
te_circuit*);uint8_tbuild_te_subtlvs(uint8_t*,structisis_circuit*);voidisis_link
_params_update(structisis_circuit*,structinterface*);voidisis_mpls_te_update(str
uctinterface*);voidisis_mpls_te_config_write_router(structvty*);#endif/*_ZEBRA_I
SIS_MPLS_TE_H*/