/**IS-ISRout(e)ingprotocol-iso_checksum.c*ISOchecksumrelatedroutines**Copyright(
C)2001,2002SampoSaaristo*TampereUniversityofTechnology*InstituteofCommunications
Engineering**Thisprogramisfreesoftware;youcanredistributeitand/ormodifyit*undert
hetermsoftheGNUGeneralPublicLicenseaspublishedbytheFree*SoftwareFoundation;eithe
rversion2oftheLicense,or(atyouroption)*anylaterversion.**Thisprogramisdistribute
dinthehopethatitwillbeuseful,butWITHOUT*ANYWARRANTY;withouteventheimpliedwarrant
yofMERCHANTABILITYor*FITNESSFORAPARTICULARPURPOSE.SeetheGNUGeneralPublicLicensef
or*moredetails.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*wit
hthisprogram;seethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51Fr
anklinSt,FifthFloor,Boston,MA02110-1301USA*/#include<zebra.h>#include"iso_checks
um.h"#include"checksum.h"/**CalculationsoftheOSIchecksum.*ISO/IEC8473definesthes
umas**L*suma(mod255)=0*1i**L*sum(L-i+1)a(mod255)=0*1i**//**Verifiesthatthechecks
umiscorrect.*Return0oncorrectand1oninvalidchecksum.*BasedonAnnexC.4ofISO/IEC8473
*/intiso_csum_verify(uint8_t*buffer,intlen,uint16_tcsum,intoffset){uint16_tcheck
sum;uint32_tc0;uint32_tc1;c0=csum&0xff00;c1=csum&0x00ff;/**Ifbotharezeroreturnco
rrect*/if(c0==0&&c1==0)return0;/**Ifeither,butnotbotharezeroreturnincorrect*/if(
c0==0||c1==0)return1;checksum=fletcher_checksum(buffer,len,offset);if(checksum==
htons(csum))return0;return1;}