#!/bin/sh

set -e -x

if ! [ -e $SNAP_DATA/fabricd.conf ]; then
    cp $SNAP/etc/frr/fabricd.conf.default $SNAP_DATA/fabricd.conf
fi
exec $SNAP/sbin/fabricd \
    -f $SNAP_DATA/fabricd.conf \
    --pid_file $SNAP_DATA/fabricd.pid \
    --socket $SNAP_DATA/zsock \
    --vty_socket $SNAP_DATA

