all:

install:
	mkdir -p $(DESTDIR)/bin
	install -D -m 0755 zebra-service $(DESTDIR)/bin/
	install -D -m 0755 bgpd-service $(DESTDIR)/bin/
	install -D -m 0755 ospfd-service $(DESTDIR)/bin/
	install -D -m 0755 ospf6d-service $(DESTDIR)/bin/
	install -D -m 0755 ripd-service $(DESTDIR)/bin/
	install -D -m 0755 ripngd-service $(DESTDIR)/bin/
	install -D -m 0755 isisd-service $(DESTDIR)/bin/
	install -D -m 0755 pimd-service $(DESTDIR)/bin/
	install -D -m 0755 ldpd-service $(DESTDIR)/bin/
	install -D -m 0755 nhrpd-service $(DESTDIR)/bin/
	install -D -m 0755 babeld-service $(DESTDIR)/bin/
	install -D -m 0755 eigrpd-service $(DESTDIR)/bin/
	install -D -m 0755 pbrd-service $(DESTDIR)/bin/
	install -D -m 0755 staticd-service $(DESTDIR)/bin/
	install -D -m 0755 bfdd-service $(DESTDIR)/bin/
	install -D -m 0755 fabricd-service $(DESTDIR)/bin/
	install -D -m 0755 vrrpd-service $(DESTDIR)/bin/
	install -D -m 0755 set-options $(DESTDIR)/bin/
	install -D -m 0755 show_version $(DESTDIR)/bin/

