#!/bin/sh

set -e -x

if ! [ -e $SNAP_DATA/nhrpd.conf ]; then
    cp $SNAP/etc/frr/nhrpd.conf.default $SNAP_DATA/nhrpd.conf
fi
exec $SNAP/sbin/nhrpd \
    -f $SNAP_DATA/nhrpd.conf \
    --pid_file $SNAP_DATA/nhrpd.pid \
    --socket $SNAP_DATA/zsock \
    --vty_socket $SNAP_DATA
