#!/bin/sh

set -e -x

if ! [ -e $SNAP_DATA/ospfd.conf ]; then
    cp $SNAP/etc/frr/ospfd.conf.default $SNAP_DATA/ospfd.conf
fi
exec $SNAP/sbin/ospfd \
    -f $SNAP_DATA/ospfd.conf \
    --pid_file $SNAP_DATA/ospfd.pid \
    --socket $SNAP_DATA/zsock \
    --vty_socket $SNAP_DATA

