#!/bin/sh

set -e -x

if ! [ -e $SNAP_DATA/pimd.conf ]; then
    cp $SNAP/etc/frr/pimd.conf.default $SNAP_DATA/pimd.conf
fi
exec $SNAP/sbin/pimd \
    -f $SNAP_DATA/pimd.conf \
    --pid_file $SNAP_DATA/pimd.pid \
    --socket $SNAP_DATA/zsock \
    --vty_socket $SNAP_DATA

