#!/bin/sh

set -e -x

if ! [ -e $SNAP_DATA/ripd.conf ]; then
    cp $SNAP/etc/frr/ripd.conf.default $SNAP_DATA/ripd.conf
fi
exec $SNAP/sbin/ripd \
    -f $SNAP_DATA/ripd.conf \
    --pid_file $SNAP_DATA/ripd.pid \
    --socket $SNAP_DATA/zsock \
    --vty_socket $SNAP_DATA

