#!/bin/sh

set -e -x

if ! [ -e $SNAP_DATA/ripngd.conf ]; then
    cp $SNAP/etc/frr/ripngd.conf.default $SNAP_DATA/ripngd.conf
fi
exec $SNAP/sbin/ripngd \
    -f $SNAP_DATA/ripngd.conf \
    --pid_file $SNAP_DATA/ripngd.pid \
    --socket $SNAP_DATA/zsock \
    --vty_socket $SNAP_DATA

