name: Bug report
description: Report a bug in the FRRouting software
labels: triage
body:
  - type: markdown
    attributes:
      value: >
        **This form is only for reporting a bug in the FRRouting software.**
        If you need help troubleshooting your configuration, have a problem
        building or installing the software, or want to ask a question or
        discuss the project, learn how to [connect with the FRRouting
        community](https://frrouting.org/community/).


        **Do not include sensitive information in this report.** IP addresses
        should be masked (example: 192.XXX.XXX.32/24).
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: >
        Run the `show version` command in the VTY shell, and provide the output
        here. (If possible, test the current development version of FRRouting
        for this bug.)
      render: text
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce
      description: >
        Give a list of steps that someone else can follow to observe
        the bug. Be as descriptive as possible, including any relevant
        configuration files and commands used. Topology diagrams are
        helpful when the bug involves more than one router.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: >
        What do you expect to happen when following the steps above?
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: >
        What actually happens when following the steps above? Include
        screenshots, log file snippets, and/or platform routing tables
        as appropriate. If a crash occurs, provide a backtrace.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: >
        Include any other relevant information about this bug here.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched the open issues for this bug.
          required: true
        - label: I have not included sensitive information in this report.
          required: true
