/***Copyright2009-2016,LabNConsulting,L.L.C.***Thisprogramisfreesoftware;youcanr
edistributeitand/or*modifyitunderthetermsoftheGNUGeneralPublicLicense*aspublishe
dbytheFreeSoftwareFoundation;eitherversion2*oftheLicense,or(atyouroption)anylate
rversion.**Thisprogramisdistributedinthehopethatitwillbeuseful,*butWITHOUTANYWAR
RANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTICULARPURP
OSE.Seethe*GNUGeneralPublicLicenseformoredetails.**Youshouldhavereceivedacopyoft
heGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;ifnot,writetoth
eFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-1301USA*//*
*File:rfapi_import.h*Purpose:HandleimportofroutesfromBGPtoRFAPI*/#ifndefQUAGGA_H
GP_RFAPI_IMPORT_H#defineQUAGGA_HGP_RFAPI_IMPORT_H#include"lib/thread.h"/**Thesea
reper-rt-import-list**routesarenotsegregatedbyRD-theRDisstoredinbgp_info_extra*a
ndisneededtodetermineiftwoprefixesarethesame.*/structrfapi_import_table{structrf
api_import_table*next;structrfapi_nve_group_cfg*rfg;structecommunity*rt_import_l
ist;/*copiedfromnvegrp*/intrefcount;/*nvegrpsandnves*/uint32_tl2_logical_net_id;
/*L2only:EVPNEthSegId*/structroute_table*imported_vpn[AFI_MAX];structrfapi_monit
or_vpn*vpn0_queries[AFI_MAX];structrfapi_monitor_eth*eth0_queries;structroute_ta
ble*imported_encap[AFI_MAX];structskiplist*monitor_exterior_orphans;intlocal_cou
nt[AFI_MAX];intremote_count[AFI_MAX];intholddown_count[AFI_MAX];intimported_coun
t[AFI_MAX];};#defineRFAPI_LOCAL_BI(bi)\(((bi)->type==ZEBRA_ROUTE_BGP)&&((bi)->su
b_type==BGP_ROUTE_RFP))#defineRFAPI_DIRECT_IMPORT_BI(bi)\(((bi)->type==ZEBRA_ROU
TE_BGP_DIRECT)\||((bi)->type==ZEBRA_ROUTE_BGP_DIRECT_EXT))#defineRFAPI_UPDATE_IT
ABLE_COUNT(bi,itable,afi,cnt)\if(RFAPI_LOCAL_BI(bi)){\(itable)->local_count[(afi
)]+=(cnt);\}else{\if(RFAPI_DIRECT_IMPORT_BI(bi))\(itable)->imported_count[(afi)]
+=(cnt);\else\(itable)->remote_count[(afi)]+=(cnt);\}externuint8_trfapiRfpCost(s
tructattr*attr);externvoidrfapiDebugBacktrace(void);externvoidrfapiCheckRouteCou
nt(void);/**PrintBIinanImportTable*/externvoidrfapiPrintBi(void*stream,structbgp
_info*bi);externvoidrfapiShowImportTable(void*stream,constchar*label,structroute
_table*rt,intisvpn);externstructrfapi_import_table*rfapiImportTableRefAdd(struct
bgp*bgp,structecommunity*rt_import_list,structrfapi_nve_group_cfg*rfg);externvoi
drfapiImportTableRefDelByIt(structbgp*bgp,structrfapi_import_table*it_target);/*
*Constructanrfapinexthoplistbasedontheroutesattachedto*thespecifiednode.**Ifther
eareanyroutesthatdoNOThaveBGP_INFO_REMOVEDset,*returnthoseonly.IfthereareONLYrou
teswithBGP_INFO_REMOVED,*thenreturnthose,andalsoincludeallthenon-removedroutesfr
omthe*nextless-specificnode(i.e.,thisnode'sparent)attheend.*/externstructrfapi_n
ext_hop_entry*rfapiRouteNode2NextHopList(structroute_node*rn,uint32_tlifetime,/*
putintonexthopentries*/structrfapi_ip_addr*exclude_vnaddr,/*omitroutestosameNVE*
/structroute_table*rfd_rib_table,/*preloadthisNVEribtable*/structprefix*pfx_targ
et_original);/*querytarget*/externstructrfapi_next_hop_entry*rfapiRouteTable2Nex
tHopList(structroute_table*rt,uint32_tlifetime,/*putintonexthopentries*/structrf
api_ip_addr*exclude_vnaddr,/*omitroutestosameNVE*/structroute_table*rfd_rib_tabl
e,/*preloadthisNVEribtable*/structprefix*pfx_target_original);/*querytarget*/ext
ernstructrfapi_next_hop_entry*rfapiEthRouteTable2NextHopList(uint32_tlogical_net
_id,structrfapi_ip_prefix*rprefix,uint32_tlifetime,/*putintonexthopentries*/stru
ctrfapi_ip_addr*exclude_vnaddr,/*omitroutestosameNVE*/structroute_table*rib_rout
e_table,/*preloadNVEribnode*/structprefix*pfx_target_original);/*querytarget*/ex
ternintrfapiEcommunitiesIntersect(structecommunity*e1,structecommunity*e2);exter
nvoidrfapiCheckRefcount(structroute_node*rn,safi_tsafi,intlockoffset);externintr
fapiHasNonRemovedRoutes(structroute_node*rn);externintrfapiProcessDeferredClose(
structthread*t);externintrfapiGetUnAddrOfVpnBi(structbgp_info*bi,structprefix*p)
;externvoidrfapiNexthop2Prefix(structattr*attr,structprefix*p);externvoidrfapiUn
icastNexthop2Prefix(afi_tafi,structattr*attr,structprefix*p);/*FilteredImportFun
ctionactions*/#defineFIF_ACTION_UPDATE0#defineFIF_ACTION_WITHDRAW1#defineFIF_ACT
ION_KILL2externvoidrfapiBgpInfoFilteredImportVPN(structrfapi_import_table*import
_table,intaction,structpeer*peer,void*rfd,/*setforloopedbackroutes*/structprefix
*p,structprefix*aux_prefix,/*AFI_ETHER:optionalIP*/afi_tafi,structprefix_rd*prd,
structattr*attr,/*partofbgp_info*/uint8_ttype,/*partofbgp_info*/uint8_tsub_type,
/*partofbgp_info*/uint32_t*label);/*partofbgp_info*/externstructrfapi_next_hop_e
ntry*rfapiEthRouteNode2NextHopList(structroute_node*rn,structrfapi_ip_prefix*rpr
efix,uint32_tlifetime,/*putintonexthopentries*/structrfapi_ip_addr*exclude_vnadd
r,/*omitroutestosameNVE*/structroute_table*rib_route_table,/*preloadNVEribtable*
/structprefix*pfx_target_original);/*querytarget*/externstructrfapi_import_table
*rfapiMacImportTableGetNoAlloc(structbgp*bgp,uint32_tlni);externstructrfapi_impo
rt_table*rfapiMacImportTableGet(structbgp*bgp,uint32_tlni);externintrfapiGetL2o(
structattr*attr,structrfapi_l2address_option*l2o);externintrfapiEcommunityGetLNI
(structecommunity*ecom,uint32_t*lni);externintrfapiEcommunityGetEthernetTag(stru
ctecommunity*ecom,uint16_t*tag_id);/*enablefordebugging;disableforperformance*/#
if0#defineRFAPI_CHECK_REFCOUNT(rn,safi,lo)rfapiCheckRefcount((rn),(safi),(lo))#e
lse#defineRFAPI_CHECK_REFCOUNT(rn,safi,lo){}#endif/*----------------------------
--------------*rfapiDeleteRemotePrefixes**UIhelper:Forusebythe"clearvncprefixes"
command**input:*unifset,tunnelmustmatchthisprefix*vnifset,nexthopprefixmustmatch
thisprefix*pifset,prefixmustmatchthisprefix*itifset,onlylookinthisimporttable**o
utput*pARcountnumberofactiveroutesdeleted*pAHcountnumberofactivenvesdeleted*pHRc
ountnumberofholddownroutesdeleted*pHHcountnumberofholddownnvesdeleted**returnval
ue:*void--------------------------------------------*/externvoidrfapiDeleteRemot
ePrefixes(structprefix*un,structprefix*vn,structprefix*p,structrfapi_import_tabl
e*it,intdelete_active,intdelete_holddown,uint32_t*pARcount,/*activeroutes*/uint3
2_t*pAHcount,/*activenves*/uint32_t*pHRcount,/*holddownroutes*/uint32_t*pHHcount
);/*holddownnves*//*------------------------------------------*rfapiCountAllItRo
utes**UIhelper:countVRFroutesfromBGPside**input:**output*pARcountcountofactivero
utes*pHRcountcountofholddownroutes*pIRcountcountofholddownroutes**returnvalue:*v
oid--------------------------------------------*/externvoidrfapiCountAllItRoutes
(int*pALRcount,/*activelocalroutes*/int*pARRcount,/*activeremoteroutes*/int*pHRc
ount,/*holddownroutes*/int*pIRcount);/*directimportedroutes*//*-----------------
-------------------------*rfapiGetHolddownFromLifetime**calculateholddownvalueba
sedonlifetime**input:*lifetimelifetime**returnvalue:*Holddownvaluebasedonlifetim
e,holddown_factor,*andRFAPI_LIFETIME_INFINITE_WITHDRAW_DELAY*-------------------
-------------------------*/externuint32_trfapiGetHolddownFromLifetime(uint32_tli
fetime);#endif/*QUAGGA_HGP_RFAPI_IMPORT_H*/