/***Copyright2009-2016,LabNConsulting,L.L.C.***Thisprogramisfreesoftware;youcanr
edistributeitand/or*modifyitunderthetermsoftheGNUGeneralPublicLicense*aspublishe
dbytheFreeSoftwareFoundation;eitherversion2*oftheLicense,or(atyouroption)anylate
rversion.**Thisprogramisdistributedinthehopethatitwillbeuseful,*butWITHOUTANYWAR
RANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTICULARPURP
OSE.Seethe*GNUGeneralPublicLicenseformoredetails.**Youshouldhavereceivedacopyoft
heGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;ifnot,writetoth
eFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-1301USA*//*
*File:vnc_zebra.c*Purpose:HandleexchangeofroutesbetweenVNCandZebra*/#include"lib
/zebra.h"#include"lib/prefix.h"#include"lib/table.h"#include"lib/log.h"#include"
lib/command.h"#include"lib/zclient.h"#include"lib/stream.h"#include"lib/ringbuf.
h"#include"lib/memory.h"#include"bgpd/bgpd.h"#include"bgpd/bgp_ecommunity.h"#inc
lude"bgpd/bgp_route.h"#include"bgpd/bgp_debug.h"#include"bgpd/bgp_advertise.h"#i
nclude"bgpd/rfapi/bgp_rfapi_cfg.h"#include"bgpd/rfapi/rfapi.h"#include"bgpd/rfap
i/rfapi_import.h"#include"bgpd/rfapi/rfapi_private.h"#include"bgpd/rfapi/vnc_zeb
ra.h"#include"bgpd/rfapi/rfapi_vty.h"#include"bgpd/rfapi/rfapi_backend.h"#includ
e"bgpd/rfapi/vnc_debug.h"staticstructrfapi_descriptorvncHD1VR;/*Single-VRexportd
ummynvedescr*/staticstructzclient*zclient_vnc=NULL;/****************************
********************************************REDISTRIBUTE:Zebrasendsupdates/withd
rawstoBGPD**********************************************************************
*//**RoutescomingfromzebragetaddedtoVNChere*/staticvoidvnc_redistribute_add(stru
ctprefix*p,uint32_tmetric,uint8_ttype){structbgp*bgp=bgp_get_default();structpre
fix_rdprd;structrfapi_ip_addrvnaddr;afi_tafi;uint32_tlocal_pref=rfp_cost_to_loca
lpref(metric>255?255:metric);if(!bgp)return;if(!bgp->rfapi_cfg){vnc_zlog_debug_v
erbose("%s:bgp->rfapi_cfgisNULL,skipping",__func__);return;}afi=family2afi(p->fa
mily);if(!afi){vnc_zlog_debug_verbose("%s:unknownprefixaddressfamily%d",__func__
,p->family);return;}if(!bgp->rfapi_cfg->redist[afi][type]){vnc_zlog_debug_verbos
e("%s:bgp->rfapi_cfg->redist[afi=%d][type=%d]is0,skipping",__func__,afi,type);re
turn;}if(!bgp->rfapi_cfg->rfg_redist){vnc_zlog_debug_verbose("%s:noredistnvegrou
p,skipping",__func__);return;}/**Assumenvegroup'sconfiguredVNaddressprefixisahos
t*routewhichalsohappenstogivetheNVEVNaddresstouse*forredistributingintoVNC.*/vna
ddr.addr_family=bgp->rfapi_cfg->rfg_redist->vn_prefix.family;switch(bgp->rfapi_c
fg->rfg_redist->vn_prefix.family){caseAF_INET:if(bgp->rfapi_cfg->rfg_redist->vn_
prefix.prefixlen!=32){vnc_zlog_debug_verbose("%s:redistnvegroupVNprefixlen(%d)!=
32,skipping",__func__,bgp->rfapi_cfg->rfg_redist->vn_prefix.prefixlen);return;}v
naddr.addr.v4=bgp->rfapi_cfg->rfg_redist->vn_prefix.u.prefix4;break;caseAF_INET6
:if(bgp->rfapi_cfg->rfg_redist->vn_prefix.prefixlen!=128){vnc_zlog_debug_verbose
("%s:redistnvegroupVNprefixlen(%d)!=128,skipping",__func__,bgp->rfapi_cfg->rfg_r
edist->vn_prefix.prefixlen);return;}vnaddr.addr.v6=bgp->rfapi_cfg->rfg_redist->v
n_prefix.u.prefix6;break;default:vnc_zlog_debug_verbose("%s:noredistnvegroupVNho
stprefixconfigured,skipping",__func__);return;}/**Assumenvegroup'sconfiguredUNad
dressprefixisahost*routewhichalsohappenstogivetheNVEUNaddresstouse*forredistribu
tingintoVNC.*//**SetUNaddressindummynvedescriptorsoadd_vnc_route*canuseitinVNCtu
nnelSubTLV*/{structrfapi_ip_prefixpfx_un;rfapiQprefix2Rprefix(&bgp->rfapi_cfg->r
fg_redist->un_prefix,&pfx_un);switch(pfx_un.prefix.addr_family){caseAF_INET:if(p
fx_un.length!=32){vnc_zlog_debug_verbose("%s:redistnvegroupUNprefixlen(%d)!=32,s
kipping",__func__,pfx_un.length);return;}break;caseAF_INET6:if(pfx_un.length!=12
8){vnc_zlog_debug_verbose("%s:redistnvegroupUNprefixlen(%d)!=128,skipping",__fun
c__,pfx_un.length);return;}break;default:vnc_zlog_debug_verbose("%s:noredistnveg
roupUNhostprefixconfigured,skipping",__func__);return;}vncHD1VR.un_addr=pfx_un.p
refix;if(!vncHD1VR.peer){/**Samesetupasinrfapi_open()*/vncHD1VR.peer=peer_new(bg
p);vncHD1VR.peer->status=Established;/*keepbgpcorehappy*/bgp_sync_delete(vncHD1V
R.peer);/*don'tneedthese*//**sincethispeerisnotontheI/Othread,thislock*isnotstri
ctlynecessary,butservesasareminder*tothosewhomaymeddle...*/pthread_mutex_lock(&v
ncHD1VR.peer->io_mtx);{//wedon'tneedanyI/Orelatedfacilitiesif(vncHD1VR.peer->ibu
f)stream_fifo_free(vncHD1VR.peer->ibuf);if(vncHD1VR.peer->obuf)stream_fifo_free(
vncHD1VR.peer->obuf);if(vncHD1VR.peer->ibuf_work)ringbuf_del(vncHD1VR.peer->ibuf
_work);if(vncHD1VR.peer->obuf_work)stream_free(vncHD1VR.peer->obuf_work);vncHD1V
R.peer->ibuf=NULL;vncHD1VR.peer->obuf=NULL;vncHD1VR.peer->obuf_work=NULL;vncHD1V
R.peer->ibuf_work=NULL;}pthread_mutex_unlock(&vncHD1VR.peer->io_mtx);/*basecodea
ssumeshavevalidhostpointer*/vncHD1VR.peer->host=XSTRDUP(MTYPE_BGP_PEER_HOST,".ze
bra.");/*MarkpeerasbelongingtoHD*/SET_FLAG(vncHD1VR.peer->flags,PEER_FLAG_IS_RFA
PI_HD);}}memset(&prd,0,sizeof(prd));prd=bgp->rfapi_cfg->rfg_redist->rd;prd.famil
y=AF_UNSPEC;prd.prefixlen=64;add_vnc_route(&vncHD1VR,/*cookie+UNaddr*/bgp,SAFI_M
PLS_VPN,p,&prd,&vnaddr,&local_pref,&(bgp->rfapi_cfg->redist_lifetime),NULL,/*RFP
options*/NULL,/*structrfapi_un_option*/NULL,/*structrfapi_vn_option*/bgp->rfapi_
cfg->rfg_redist->rt_export_list,NULL,NULL,/*label:default*/type,BGP_ROUTE_REDIST
RIBUTE,0);/*flags*/}/**RoutedeletionsfromzebrapropagatetoVNChere*/staticvoidvnc_
redistribute_delete(structprefix*p,uint8_ttype){structbgp*bgp=bgp_get_default();
structprefix_rdprd;afi_tafi;if(!bgp)return;if(!bgp->rfapi_cfg){vnc_zlog_debug_ve
rbose("%s:bgp->rfapi_cfgisNULL,skipping",__func__);return;}afi=family2afi(p->fam
ily);if(!afi){vnc_zlog_debug_verbose("%s:unknownprefixaddressfamily%d",__func__,
p->family);return;}if(!bgp->rfapi_cfg->redist[afi][type]){vnc_zlog_debug_verbose
("%s:bgp->rfapi_cfg->redist[afi=%d][type=%d]is0,skipping",__func__,afi,type);ret
urn;}if(!bgp->rfapi_cfg->rfg_redist){vnc_zlog_debug_verbose("%s:noredistnvegroup
,skipping",__func__);return;}memset(&prd,0,sizeof(prd));prd=bgp->rfapi_cfg->rfg_
redist->rd;prd.family=AF_UNSPEC;prd.prefixlen=64;del_vnc_route(&vncHD1VR,/*usedu
mmyptrascookie*/vncHD1VR.peer,bgp,SAFI_MPLS_VPN,p,&prd,type,BGP_ROUTE_REDISTRIBU
TE,NULL,0);}/**Flushallredistributedroutesoftype<type>*/staticvoidvnc_redistribu
te_withdraw(structbgp*bgp,afi_tafi,uint8_ttype){structprefix_rdprd;structbgp_tab
le*table;structbgp_node*prn;structbgp_node*rn;vnc_zlog_debug_verbose("%s:entry",
__func__);if(!bgp)return;if(!bgp->rfapi_cfg){vnc_zlog_debug_verbose("%s:bgp->rfa
pi_cfgisNULL,skipping",__func__);return;}/**LoopoveralltheRDs*/for(prn=bgp_table
_top(bgp->rib[afi][SAFI_MPLS_VPN]);prn;prn=bgp_route_next(prn)){memset(&prd,0,si
zeof(prd));prd.family=AF_UNSPEC;prd.prefixlen=64;memcpy(prd.val,prn->p.u.val,8);
/*Thisistheper-RDtableofprefixes*/table=prn->info;for(rn=bgp_table_top(table);rn
;rn=bgp_route_next(rn)){structbgp_info*ri;for(ri=rn->info;ri;ri=ri->next){if(ri-
>type==type){/*hasmatchingredisttype*/break;}}if(ri){del_vnc_route(&vncHD1VR,/*u
sedummyptrascookie*/vncHD1VR.peer,bgp,SAFI_MPLS_VPN,&(rn->p),&prd,type,BGP_ROUTE
_REDISTRIBUTE,NULL,0);}}}vnc_zlog_debug_verbose("%s:return",__func__);}/**Zebrar
outeaddanddeletetreatment.**Assumes1nexthop*/staticintvnc_zebra_read_route(intco
mmand,structzclient*zclient,zebra_size_tlength,vrf_id_tvrf_id){structzapi_routea
pi;intadd;if(zapi_route_decode(zclient->ibuf,&api)<0)return-1;/*wecompletelyigno
resrcdestroutesfornow.*/if(CHECK_FLAG(api.message,ZAPI_MESSAGE_SRCPFX))return0;a
dd=(command==ZEBRA_REDISTRIBUTE_ROUTE_ADD);if(add)vnc_redistribute_add(&api.pref
ix,api.metric,api.type);elsevnc_redistribute_delete(&api.prefix,api.type);if(BGP
_DEBUG(zebra,ZEBRA)){charbuf[PREFIX_STRLEN];prefix2str(&api.prefix,buf,sizeof(bu
f));vnc_zlog_debug_verbose("%s:Zebrarcvd:routedelete%s%smetric%u",__func__,zebra
_route_string(api.type),buf,api.metric);}return0;}/*****************************
*******************************************vnc_bgp_zebra_*:VNCsendsupdates/withd
rawstoZebra*********************************************************************
**//**low-levelmessagebuilder*/staticvoidvnc_zebra_route_msg(structprefix*p,unsi
gnedintnhp_count,void*nhp_ary,intadd)/*1=add,0=del*/{structzapi_routeapi;structz
api_nexthop*api_nh;inti;structin_addr**nhp_ary4=nhp_ary;structin6_addr**nhp_ary6
=nhp_ary;if(!nhp_count){vnc_zlog_debug_verbose("%s:emptynexthoplist,skipping",__
func__);return;}memset(&api,0,sizeof(api));api.vrf_id=VRF_DEFAULT;api.type=ZEBRA
_ROUTE_VNC;api.safi=SAFI_UNICAST;api.prefix=*p;/*Nexthops*/SET_FLAG(api.message,
ZAPI_MESSAGE_NEXTHOP);api.nexthop_num=MIN(nhp_count,multipath_num);for(i=0;i<api
.nexthop_num;i++){api_nh=&api.nexthops[i];api_nh->vrf_id=VRF_DEFAULT;switch(p->f
amily){caseAF_INET:memcpy(&api_nh->gate.ipv4,nhp_ary4[i],sizeof(api_nh->gate.ipv
4));api_nh->type=NEXTHOP_TYPE_IPV4;break;caseAF_INET6:memcpy(&api_nh->gate.ipv6,
nhp_ary6[i],sizeof(api_nh->gate.ipv6));api_nh->type=NEXTHOP_TYPE_IPV6;break;}}if
(BGP_DEBUG(zebra,ZEBRA)){charbuf[PREFIX_STRLEN];prefix2str(&api.prefix,buf,sizeo
f(buf));vnc_zlog_debug_verbose("%s:Zebrasend:route%s%s,nhp_count=%d",__func__,(a
dd?"add":"del"),buf,nhp_count);}zclient_route_send((add?ZEBRA_ROUTE_ADD:ZEBRA_RO
UTE_DELETE),zclient_vnc,&api);}staticvoidnve_list_to_nh_array(uint8_tfamily,stru
ctlist*nve_list,unsignedint*nh_count_ret,void**nh_ary_ret,/*returnedaddressarray
*/void**nhp_ary_ret)/*returnedpointerarray*/{intnve_count=listcount(nve_list);*n
h_count_ret=0;*nh_ary_ret=NULL;*nhp_ary_ret=NULL;if(!nve_count){vnc_zlog_debug_v
erbose("%s:emptynve_list,skipping",__func__);return;}if(family==AF_INET){structl
istnode*ln;structin_addr*iap;structin_addr**v;/**Arrayofnexthopaddresses*/*nh_ar
y_ret=XCALLOC(MTYPE_TMP,nve_count*sizeof(structin_addr));/**Arrayofpointerstonex
thopaddresses*/*nhp_ary_ret=XCALLOC(MTYPE_TMP,nve_count*sizeof(structin_addr*));
iap=*nh_ary_ret;v=*nhp_ary_ret;for(ln=listhead(nve_list);ln;ln=listnextnode(ln))
{structrfapi_descriptor*irfd;structprefixnhp;irfd=listgetdata(ln);if(rfapiRaddr2
Qprefix(&irfd->vn_addr,&nhp))continue;*iap=nhp.u.prefix4;*v=iap;vnc_zlog_debug_v
erbose("%s:ipadr:(%p)<-0x%x,ptr:(%p)<-%p",__func__,iap,nhp.u.prefix4.s_addr,v,ia
p);++iap;++v;++*nh_count_ret;}}elseif(family==AF_INET6){structlistnode*ln;*nh_ar
y_ret=XCALLOC(MTYPE_TMP,nve_count*sizeof(structin6_addr));*nhp_ary_ret=XCALLOC(M
TYPE_TMP,nve_count*sizeof(structin6_addr*));for(ln=listhead(nve_list);ln;ln=list
nextnode(ln)){structrfapi_descriptor*irfd;structin6_addr*iap=*nh_ary_ret;structi
n6_addr**v=*nhp_ary_ret;structprefixnhp;irfd=listgetdata(ln);if(rfapiRaddr2Qpref
ix(&irfd->vn_addr,&nhp))continue;*iap=nhp.u.prefix6;*v=iap;++iap;++v;++*nh_count
_ret;}}}staticvoidimport_table_to_nve_list_zebra(structbgp*bgp,structrfapi_impor
t_table*it,structlist**nves,uint8_tfamily){structlistnode*node;structrfapi_rfg_n
ame*rfgn;/**LoopoverthelistofNVE-Groupsconfiguredfor*exportingtodirect-bgp.**Bui
ldalistofNVEsthatusethisimporttable*/*nves=NULL;for(ALL_LIST_ELEMENTS_RO(bgp->rf
api_cfg->rfg_export_zebra_l,node,rfgn)){/**IfthisNVE-Group'simporttablematchesth
ecurrentone*/if(rfgn->rfg&&rfgn->rfg->nves&&rfgn->rfg->rfapi_import_table==it){n
ve_group_to_nve_list(rfgn->rfg,nves,family);}}}staticvoidvnc_zebra_add_del_prefi
x(structbgp*bgp,structrfapi_import_table*import_table,structroute_node*rn,intadd
)/*!0=add,0=del*/{structlist*nves;unsignedintnexthop_count=0;void*nh_ary=NULL;vo
id*nhp_ary=NULL;vnc_zlog_debug_verbose("%s:entry,add=%d",__func__,add);if(zclien
t_vnc->sock<0)return;if(rn->p.family!=AF_INET&&rn->p.family!=AF_INET6){zlog_err(
"%s:invalidroutenodeaddrfamily",__func__);return;}if(!zclient_vnc->redist[family
2afi(rn->p.family)][ZEBRA_ROUTE_VNC])return;if(!bgp->rfapi_cfg){vnc_zlog_debug_v
erbose("%s:bgp->rfapi_cfgisNULL,skipping",__func__);return;}if(!listcount(bgp->r
fapi_cfg->rfg_export_zebra_l)){vnc_zlog_debug_verbose("%s:nozebraexportnvegroup,
skipping",__func__);return;}import_table_to_nve_list_zebra(bgp,import_table,&nve
s,rn->p.family);if(nves){nve_list_to_nh_array(rn->p.family,nves,&nexthop_count,&
nh_ary,&nhp_ary);list_delete_and_null(&nves);if(nexthop_count)vnc_zebra_route_ms
g(&rn->p,nexthop_count,nhp_ary,add);}if(nhp_ary)XFREE(MTYPE_TMP,nhp_ary);if(nh_a
ry)XFREE(MTYPE_TMP,nh_ary);}voidvnc_zebra_add_prefix(structbgp*bgp,structrfapi_i
mport_table*import_table,structroute_node*rn){vnc_zebra_add_del_prefix(bgp,impor
t_table,rn,1);}voidvnc_zebra_del_prefix(structbgp*bgp,structrfapi_import_table*i
mport_table,structroute_node*rn){vnc_zebra_add_del_prefix(bgp,import_table,rn,0)
;}staticvoidvnc_zebra_add_del_nve(structbgp*bgp,structrfapi_descriptor*rfd,intad
d)/*0=del,!0=add*/{structlistnode*node;structrfapi_rfg_name*rfgn;structrfapi_nve
_group_cfg*rfg=rfd->rfg;afi_tafi=family2afi(rfd->vn_addr.addr_family);structpref
ixnhp;//structprefix*nhpp;void*pAddr;vnc_zlog_debug_verbose("%s:entry,add=%d",__
func__,add);if(zclient_vnc->sock<0)return;if(!zclient_vnc->redist[afi][ZEBRA_ROU
TE_VNC])return;if(afi!=AFI_IP&&afi!=AFI_IP6){zlog_err("%s:invalidvnaddrfamily",_
_func__);return;}if(!bgp)return;if(!bgp->rfapi_cfg){vnc_zlog_debug_verbose("%s:b
gp->rfapi_cfgisNULL,skipping",__func__);return;}if(rfapiRaddr2Qprefix(&rfd->vn_a
ddr,&nhp)){vnc_zlog_debug_verbose("%s:can'tconvertvnaddress,skipping",__func__);
return;}pAddr=&nhp.u.prefix4;/**LoopoverthelistofNVE-Groupsconfiguredfor*exporti
ngtozebraandseeifthisnewNVE's*groupisamongthem.*/for(ALL_LIST_ELEMENTS_RO(bgp->r
fapi_cfg->rfg_export_zebra_l,node,rfgn)){/**Yes,thisNVE'sgroupisconfiguredforexp
orttozebra*/if(rfgn->rfg==rfg){structroute_table*rt=NULL;structroute_node*rn;str
uctrfapi_import_table*import_table;import_table=rfg->rfapi_import_table;vnc_zlog
_debug_verbose("%s:thisnve'sgroupisinzebraexportlist",__func__);rt=import_table-
>imported_vpn[afi];/**WalktheNVE-Group'sVNCImporttable*/for(rn=route_top(rt);rn;
rn=route_next(rn)){if(rn->info){vnc_zlog_debug_verbose("%s:sending%s",__func__,(
add?"add":"del"));vnc_zebra_route_msg(&rn->p,1,&pAddr,add);}}}}}voidvnc_zebra_ad
d_nve(structbgp*bgp,structrfapi_descriptor*rfd){vnc_zebra_add_del_nve(bgp,rfd,1)
;}voidvnc_zebra_del_nve(structbgp*bgp,structrfapi_descriptor*rfd){vnc_zebra_add_
del_nve(bgp,rfd,0);}staticvoidvnc_zebra_add_del_group_afi(structbgp*bgp,structrf
api_nve_group_cfg*rfg,afi_tafi,intadd){structroute_table*rt=NULL;structroute_nod
e*rn;structrfapi_import_table*import_table;uint8_tfamily=afi2family(afi);structl
ist*nves=NULL;unsignedintnexthop_count=0;void*nh_ary=NULL;void*nhp_ary=NULL;vnc_
zlog_debug_verbose("%s:entry",__func__);import_table=rfg->rfapi_import_table;if(
!import_table){vnc_zlog_debug_verbose("%s:importtablenotdefined,returning",__fun
c__);return;}if(afi==AFI_IP||afi==AFI_IP6){rt=import_table->imported_vpn[afi];}e
lse{zlog_err("%s:badafi%d",__func__,afi);return;}if(!family){zlog_err("%s:comput
edbadfamily:%d",__func__,family);return;}if(!rfg->nves){/*avoidsegfaultbelowifli
stdoesn'texist*/vnc_zlog_debug_verbose("%s:noNVEsinthisgroup",__func__);return;}
nve_group_to_nve_list(rfg,&nves,family);if(nves){vnc_zlog_debug_verbose("%s:have
nves",__func__);nve_list_to_nh_array(family,nves,&nexthop_count,&nh_ary,&nhp_ary
);vnc_zlog_debug_verbose("%s:family:%d,nvecount:%d",__func__,family,nexthop_coun
t);list_delete_and_null(&nves);if(nexthop_count){/**WalktheNVE-Group'sVNCImportt
able*/for(rn=route_top(rt);rn;rn=route_next(rn)){if(rn->info){vnc_zebra_route_ms
g(&rn->p,nexthop_count,nhp_ary,add);}}}if(nhp_ary)XFREE(MTYPE_TMP,nhp_ary);if(nh
_ary)XFREE(MTYPE_TMP,nh_ary);}}voidvnc_zebra_add_group(structbgp*bgp,structrfapi
_nve_group_cfg*rfg){vnc_zebra_add_del_group_afi(bgp,rfg,AFI_IP,1);vnc_zebra_add_
del_group_afi(bgp,rfg,AFI_IP6,1);}voidvnc_zebra_del_group(structbgp*bgp,structrf
api_nve_group_cfg*rfg){vnc_zlog_debug_verbose("%s:entry",__func__);vnc_zebra_add
_del_group_afi(bgp,rfg,AFI_IP,0);vnc_zebra_add_del_group_afi(bgp,rfg,AFI_IP6,0);
}voidvnc_zebra_reexport_group_afi(structbgp*bgp,structrfapi_nve_group_cfg*rfg,af
i_tafi){structlistnode*node;structrfapi_rfg_name*rfgn;for(ALL_LIST_ELEMENTS_RO(b
gp->rfapi_cfg->rfg_export_zebra_l,node,rfgn)){if(rfgn->rfg==rfg){vnc_zebra_add_d
el_group_afi(bgp,rfg,afi,0);vnc_zebra_add_del_group_afi(bgp,rfg,afi,1);break;}}}
/************************************************************************CONTROL
INTERFACE***********************************************************************
//*OtherroutesredistributionintoBGP.*/intvnc_redistribute_set(structbgp*bgp,afi_
tafi,inttype){if(!bgp->rfapi_cfg){returnCMD_WARNING_CONFIG_FAILED;}/*SetflagtoBG
Pinstance.*/bgp->rfapi_cfg->redist[afi][type]=1;//bgp->redist[afi][type]=1;/*Ret
urnifalreadyredistributeflagisset.*/if(zclient_vnc->redist[afi][type])returnCMD_
WARNING_CONFIG_FAILED;vrf_bitmap_set(zclient_vnc->redist[afi][type],VRF_DEFAULT)
;//zclient_vnc->redist[afi][type]=1;/*Returnifzebraconnectionisnotestablished.*/
if(zclient_vnc->sock<0)returnCMD_WARNING_CONFIG_FAILED;if(BGP_DEBUG(zebra,ZEBRA)
)vnc_zlog_debug_verbose("Zebrasend:redistributeadd%s",zebra_route_string(type));
/*Senddistributeaddmessagetozebra.*/zebra_redistribute_send(ZEBRA_REDISTRIBUTE_A
DD,zclient_vnc,afi,type,0,VRF_DEFAULT);returnCMD_SUCCESS;}/*Unsetredistribution.
*/intvnc_redistribute_unset(structbgp*bgp,afi_tafi,inttype){vnc_zlog_debug_verbo
se("%s:type=%dentry",__func__,type);if(!bgp->rfapi_cfg){vnc_zlog_debug_verbose("
%s:return(norfapi_cfg)",__func__);returnCMD_WARNING_CONFIG_FAILED;}/*Unsetflagfr
omBGPinstance.*/bgp->rfapi_cfg->redist[afi][type]=0;/*Returnifzebraconnectionisd
isabled.*/if(!zclient_vnc->redist[afi][type])returnCMD_WARNING_CONFIG_FAILED;zcl
ient_vnc->redist[afi][type]=0;if(bgp->rfapi_cfg->redist[AFI_IP][type]==0&&bgp->r
fapi_cfg->redist[AFI_IP6][type]==0&&zclient_vnc->sock>=0){/*Senddistributedelete
messagetozebra.*/if(BGP_DEBUG(zebra,ZEBRA))vnc_zlog_debug_verbose("Zebrasend:red
istributedelete%s",zebra_route_string(type));zebra_redistribute_send(ZEBRA_REDIS
TRIBUTE_DELETE,zclient_vnc,afi,type,0,VRF_DEFAULT);}/*Withdrawredistributedroute
sfromcurrentBGP'sroutingtable.*/vnc_redistribute_withdraw(bgp,afi,type);vnc_zlog
_debug_verbose("%s:return",__func__);returnCMD_SUCCESS;}externstructzebra_privs_
tbgpd_privs;/**Modeledafterbgp_zebra.c'bgp_zebra_init()*Charriereasks,"Isitpossi
bletocarrytwo?"*/voidvnc_zebra_init(structthread_master*master){/*Setdefaultvalu
es.*/zclient_vnc=zclient_new_notify(master,&zclient_options_default);zclient_ini
t(zclient_vnc,ZEBRA_ROUTE_VNC,0,&bgpd_privs);zclient_vnc->redistribute_route_add
=vnc_zebra_read_route;zclient_vnc->redistribute_route_del=vnc_zebra_read_route;}
voidvnc_zebra_destroy(void){if(zclient_vnc==NULL)return;zclient_stop(zclient_vnc
);zclient_free(zclient_vnc);zclient_vnc=NULL;}