/***Copyright2009-2016,LabNConsulting,L.L.C.***Thisprogramisfreesoftware;youcanr
edistributeitand/or*modifyitunderthetermsoftheGNUGeneralPublicLicense*aspublishe
dbytheFreeSoftwareFoundation;eitherversion2*oftheLicense,or(atyouroption)anylate
rversion.**Thisprogramisdistributedinthehopethatitwillbeuseful,*butWITHOUTANYWAR
RANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTICULARPURP
OSE.Seethe*GNUGeneralPublicLicenseformoredetails.**Youshouldhavereceivedacopyoft
heGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;ifnot,writetoth
eFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-1301USA*/#i
fndef_QUAGGA_RFAPI_VNC_IMPORT_BGP_H_#define_QUAGGA_RFAPI_VNC_IMPORT_BGP_H_#inclu
de"lib/zebra.h"#include"lib/prefix.h"#include"bgpd/bgpd.h"#include"bgpd/bgp_rout
e.h"#defineVALID_INTERIOR_TYPE(type)\(((type)==ZEBRA_ROUTE_BGP)||((type)==ZEBRA_
ROUTE_BGP_DIRECT))externuint32_tcalc_local_pref(structattr*attr,structpeer*peer)
;externintvnc_prefix_cmp(void*pfx1,void*pfx2);externvoidvnc_import_bgp_add_route
(structbgp*bgp,structprefix*prefix,structbgp_info*info);externvoidvnc_import_bgp
_del_route(structbgp*bgp,structprefix*prefix,structbgp_info*info);externvoidvnc_
import_bgp_redist_enable(structbgp*bgp,afi_tafi);externvoidvnc_import_bgp_redist
_disable(structbgp*bgp,afi_tafi);externvoidvnc_import_bgp_exterior_redist_enable
(structbgp*bgp,afi_tafi);externvoidvnc_import_bgp_exterior_redist_disable(struct
bgp*bgp,afi_tafi);externvoidvnc_import_bgp_exterior_add_route(structbgp*bgp,/*ex
teriorinstance,wehope*/structprefix*prefix,/*unicastprefix*/structbgp_info*info)
;/*unicastinfo*/externvoidvnc_import_bgp_exterior_del_route(structbgp*bgp,struct
prefix*prefix,/*unicastprefix*/structbgp_info*info);/*unicastinfo*/externvoidvnc
_import_bgp_add_vnc_host_route_mode_resolve_nve(structbgp*bgp,structprefix_rd*pr
d,/*RD*/structbgp_table*table_rd,/*per-rdVPNroutetable*/structprefix*prefix,/*VP
Nprefix*/structbgp_info*bi);/*newVPNhostroute*/externvoidvnc_import_bgp_del_vnc_
host_route_mode_resolve_nve(structbgp*bgp,structprefix_rd*prd,/*RD*/structbgp_ta
ble*table_rd,/*per-rdVPNroutetable*/structprefix*prefix,/*VPNprefix*/structbgp_i
nfo*bi);/*oldVPNhostroute*/#endif/*_QUAGGA_RFAPI_VNC_IMPORT_BGP_H_*/