/**ThisfileispartofQuagga.**Quaggaisfreesoftware;youcanredistributeitand/ormodif
yit*underthetermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFounda
tion;eitherversion2,or(atyouroption)any*laterversion.**Quaggaisdistributedintheh
opethatitwillbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MER
CHANTABILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformore
details.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthispr
ogram;seethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinS
t,FifthFloor,Boston,MA02110-1301USA*/#include<zebra.h>#include<lib/version.h>#in
clude"getopt.h"#include"thread.h"#include"vty.h"#include"command.h"#include"memo
ry.h"#include"memory_vty.h"externvoidtest_init();structthread_master*master;stru
ctoptionlongopts[]={{"daemon",no_argument,NULL,'d'},{"config_file",required_argu
ment,NULL,'f'},{"help",no_argument,NULL,'h'},{"vty_addr",required_argument,NULL,
'A'},{"vty_port",required_argument,NULL,'P'},{"version",no_argument,NULL,'v'},{0
}};DEFUN(daemon_exit,daemon_exit_cmd,"daemon-exit","Makethedaemonexit\n"){exit(0
);}staticinttimer_count;staticinttest_timer(structthread*thread){int*count=THREA
D_ARG(thread);printf("run%doftimer\n",(*count)++);thread_add_timer(master,test_t
imer,count,5,NULL);return0;}staticvoidtest_timer_init(){thread_add_timer(master,
test_timer,&timer_count,10,NULL);}staticvoidtest_vty_init(){install_element(VIEW
_NODE,&daemon_exit_cmd);}/*Helpinformationdisplay.*/staticvoidusage(char*prognam
e,intstatus){if(status!=0)fprintf(stderr,"Try`%s--help'formoreinformation.\n",pr
ogname);else{printf("Usage:%s[OPTION...]\n\Daemonwhichdoes'slow'things.\n\n\-d,-
-daemonRunsindaemonmode\n\-f,--config_fileSetconfigurationfilename\n\-A,--vty_ad
drSetvty'sbindaddress\n\-P,--vty_portSetvty'sportnumber\n\-v,--versionPrintprogr
amversion\n\-h,--helpDisplaythishelpandexit\n\\n\Reportbugsto%s\n",progname,FRR_
BUG_ADDRESS);}exit(status);}/*mainroutine.*/intmain(intargc,char**argv){char*p;c
har*vty_addr=NULL;intvty_port=4000;intdaemon_mode=0;char*progname;structthreadth
read;char*config_file=NULL;/*Setumaskbeforeanythingforsecurity*/umask(0027);/*ge
tprogramname*/progname=((p=strrchr(argv[0],'/'))?++p:argv[0]);/*masterinit.*/mas
ter=thread_master_create(NULL);while(1){intopt;opt=getopt_long(argc,argv,"dhf:A:
P:v",longopts,0);if(opt==EOF)break;switch(opt){case0:break;case'f':config_file=o
ptarg;break;case'd':daemon_mode=1;break;case'A':vty_addr=optarg;break;case'P':/*
Dealwithatoi()returning0onfailure*/if(strcmp(optarg,"0")==0){vty_port=0;break;}v
ty_port=atoi(optarg);vty_port=(vty_port?vty_port:4000);break;case'v':print_versi
on(progname);exit(0);break;case'h':usage(progname,0);break;default:usage(prognam
e,1);break;}}/*Libraryinits.*/cmd_init(1);vty_init(master);memory_init();/*OSPFv
tyinits.*/test_vty_init();/*Changetothedaemonprogram.*/if(daemon_mode&&daemon(0,
0)<0){fprintf(stderr,"daemonfailed:%s",strerror(errno));exit(1);}/*CreateVTYsock
et*/vty_serv_sock(vty_addr,vty_port,"/tmp/.heavy.sock");/*Configurationfileread*
/if(!config_file)usage(progname,1);vty_read_config(config_file,NULL);test_timer_
init();test_init();/*Fetchnextactivethread.*/while(thread_fetch(master,&thread))
thread_call(&thread);/*Notreached.*/exit(0);}