/*Copyright2011byMatthieuBoutierandJuliuszChroboczekPermissionisherebygranted,fr
eeofcharge,toanypersonobtainingacopyofthissoftwareandassociateddocumentationfile
s(the"Software"),todealintheSoftwarewithoutrestriction,includingwithoutlimitatio
ntherightstouse,copy,modify,merge,publish,distribute,sublicense,and/orsellcopies
oftheSoftware,andtopermitpersonstowhomtheSoftwareisfurnishedtodoso,subjecttothef
ollowingconditions:Theabovecopyrightnoticeandthispermissionnoticeshallbeincluded
inallcopiesorsubstantialportionsoftheSoftware.THESOFTWAREISPROVIDED"ASIS",WITHOU
TWARRANTYOFANYKIND,EXPRESSORIMPLIED,INCLUDINGBUTNOTLIMITEDTOTHEWARRANTIESOFMERCH
ANTABILITY,FITNESSFORAPARTICULARPURPOSEANDNONINFRINGEMENT.INNOEVENTSHALLTHEAUTHO
RSORCOPYRIGHTHOLDERSBELIABLEFORANYCLAIM,DAMAGESOROTHERLIABILITY,WHETHERINANACTIO
NOFCONTRACT,TORTOROTHERWISE,ARISINGFROM,OUTOFORINCONNECTIONWITHTHESOFTWAREORTHEU
SEOROTHERDEALINGSINTHESOFTWARE.*//*includezebralibrary*/#include<zebra.h>#includ
e"getopt.h"#include"if.h"#include"log.h"#include"thread.h"#include"privs.h"#incl
ude"sigevent.h"#include"version.h"#include"command.h"#include"vty.h"#include"mem
ory.h"#include"libfrr.h"#include"babel_main.h"#include"babeld.h"#include"util.h"
#include"kernel.h"#include"babel_interface.h"#include"neighbour.h"#include"route
.h"#include"xroute.h"#include"message.h"#include"resend.h"#include"babel_zebra.h
"staticvoidbabel_fail(void);staticvoidbabel_init_random(void);staticvoidbabel_re
place_by_null(intfd);staticvoidbabel_exit_properly(void);staticvoidbabel_save_st
ate_file(void);structthread_master*master;/*quagga'sthreadshandler*/structtimeva
lbabel_now;/*currenttime*/unsignedcharmyid[8];/*uniqueid(macaddressofaninterface
)*/intdebug=0;intresend_delay=-1;constunsignedcharzeroes[16]={0};constunsignedch
arones[16]={0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xF
F,0xFF,0xFF};staticconstchar*state_file=DAEMON_VTY_DIR"/babel-state";unsignedcha
rprotocol_group[16];/*babel'slink-localmulticastaddress*/intprotocol_port;/*babe
l'sport*/intprotocol_socket=-1;/*socket:communicatewithothersbabeld*/staticcharb
abel_config_default[]=SYSCONFDIRBABEL_DEFAULT_CONFIG;staticchar*babel_config_fil
e=NULL;staticchar*babel_vty_addr=NULL;staticintbabel_vty_port=BABEL_VTY_PORT;/*b
abeldprivileges*/staticzebra_capabilities_t_caps_p[]={ZCAP_NET_RAW,ZCAP_BIND};st
ructzebra_privs_tbabeld_privs={#ifdefined(FRR_USER).user=FRR_USER,#endif#ifdefin
edFRR_GROUP.group=FRR_GROUP,#endif#ifdefVTY_GROUP.vty_group=VTY_GROUP,#endif.cap
s_p=_caps_p,.cap_num_p=array_size(_caps_p),.cap_num_i=0};staticvoidbabel_sigexit
(void){zlog_notice("Terminatingonsignal");babel_exit_properly();}staticvoidbabel
_sigusr1(void){zlog_rotate();}staticstructquagga_signal_tbabel_signals[]={{.sign
al=SIGUSR1,.handler=&babel_sigusr1,},{.signal=SIGINT,.handler=&babel_sigexit,},{
.signal=SIGTERM,.handler=&babel_sigexit,},};structoptionlongopts[]={{0}};FRR_DAE
MON_INFO(babeld,BABELD,.vty_port=BABEL_VTY_PORT,.proghelp="ImplementationoftheBA
BELroutingprotocol.",.signals=babel_signals,.n_signals=array_size(babel_signals)
,.privs=&babeld_privs,)intmain(intargc,char**argv){intrc;frr_preinit(&babeld_di,
argc,argv);frr_opt_add("",longopts,"");babel_init_random();/*settheBabel'sdefaul
tlink-localmulticastaddressandBabel'sport*/parse_address("ff02:0:0:0:0:0:1:6",pr
otocol_group,NULL);protocol_port=6696;/*getoptions*/while(1){intopt;opt=frr_geto
pt(argc,argv,NULL);if(opt==EOF)break;switch(opt){case0:break;default:frr_help_ex
it(1);break;}}/*createthethreadshandler*/master=frr_init();/*Libraryinits.*/zpri
vs_init(&babeld_privs);cmd_init(1);vty_init(master);resend_delay=BABEL_DEFAULT_R
ESEND_DELAY;change_smoothing_half_life(BABEL_DEFAULT_SMOOTHING_HALF_LIFE);babel_
replace_by_null(STDIN_FILENO);/*initsomequagga'sdependencies,andbabeld'scommands
*/babeld_quagga_init();/*initzebraclient'sstructureandit'scommands*//*thisreplac
ekernel_setup&&kernel_setup_socket*/babelz_zebra_init();/*Getzebraconfigurationf
ile.*/vty_read_config(babel_config_file,babel_config_default);/*initbuffer*/rc=r
esize_receive_buffer(1500);if(rc<0)babel_fail();schedule_neighbours_check(5000,1
);frr_config_fork();frr_run(master);return0;}staticvoidbabel_fail(void){exit(1);
}/*initializerandomvalue,andset'babel_now'bytheway.*/staticvoidbabel_init_random
(void){gettime(&babel_now);intrc;unsignedintseed;rc=read_random_bytes(&seed,size
of(seed));if(rc<0){zlog_err("read(random):%s",safe_strerror(errno));seed=42;}see
d^=(babel_now.tv_sec^babel_now.tv_usec);srandom(seed);}/*closefd,andreplaceitby"
/dev/null"exitiferror*/staticvoidbabel_replace_by_null(intfd){intfd_null;intrc;f
d_null=open("/dev/null",O_RDONLY);if(fd_null<0){zlog_err("open(null):%s",safe_st
rerror(errno));exit(1);}rc=dup2(fd_null,fd);if(rc<0){zlog_err("dup2(null,0):%s",
safe_strerror(errno));exit(1);}close(fd_null);}/*Loadthestatefile:checklastbabel
d'srunningstate,usefullincaseof"/etc/init.d/babeldrestart"*/voidbabel_load_state
_file(void){intfd;intrc;fd=open(state_file,O_RDONLY);if(fd<0&&errno!=ENOENT)zlog
_err("open(babel-state:%s)",safe_strerror(errno));rc=unlink(state_file);if(fd>=0
&&rc<0){zlog_err("unlink(babel-state):%s",safe_strerror(errno));/*Ifwecouldn'tun
linkit,it'sprobablystale.*/gotofini;}if(fd>=0){charbuf[100];charbuf2[100];ints;l
ongt;rc=read(fd,buf,99);if(rc<0){zlog_err("read(babel-state):%s",safe_strerror(e
rrno));}else{buf[rc]='\0';rc=sscanf(buf,"%99s%d%ld\n",buf2,&s,&t);if(rc==3&&s>=0
&&s<=0xFFFF){unsignedcharsid[8];rc=parse_eui64(buf2,sid);if(rc<0){zlog_err("Coul
dn'tparsebabel-state.");}else{structtimevalrealnow;debugf(BABEL_DEBUG_COMMON,"Go
t%s%d%ldfrombabel-state.",format_eui64(sid),s,t);gettimeofday(&realnow,NULL);if(
memcmp(sid,myid,8)==0)myseqno=seqno_plus(s,1);elsezlog_err("IDmismatchinbabel-st
ate.id=%s;old=%s",format_eui64(myid),format_eui64(sid));}}else{zlog_err("Couldn'
tparsebabel-state.");}}gotofini;}fini:if(fd>=0)close(fd);return;}staticvoidbabel
_exit_properly(void){debugf(BABEL_DEBUG_COMMON,"Exiting...");usleep(roughly(1000
0));gettime(&babel_now);/*Uninstallandflushallroutes.*/debugf(BABEL_DEBUG_COMMON
,"Uninstallroutes.");flush_all_routes();babel_interface_close_all();babel_zebra_
close_connexion();babel_save_state_file();debugf(BABEL_DEBUG_COMMON,"Removepidfi
le.");debugf(BABEL_DEBUG_COMMON,"Done.");frr_fini();exit(0);}staticvoidbabel_sav
e_state_file(void){intfd;intrc;debugf(BABEL_DEBUG_COMMON,"Savestatefile.");fd=op
en(state_file,O_WRONLY|O_TRUNC|O_CREAT,0644);if(fd<0){zlog_err("creat(babel-stat
e):%s",safe_strerror(errno));unlink(state_file);}else{structtimevalrealnow;charb
uf[100];gettimeofday(&realnow,NULL);rc=snprintf(buf,100,"%s%d%ld\n",format_eui64
(myid),(int)myseqno,(long)realnow.tv_sec);if(rc<0||rc>=100){zlog_err("write(babe
l-state):overflow.");unlink(state_file);}else{rc=write(fd,buf,rc);if(rc<0){zlog_
err("write(babel-state):%s",safe_strerror(errno));unlink(state_file);}fsync(fd);
}close(fd);}}voidshow_babel_main_configuration(structvty*vty){vty_out(vty,"state
file=%s\n""configurationfile=%s\n""protocolinformations:\n""multicastaddress=%s\
n""port=%d\n""vtyaddress=%s\n""vtyport=%d\n""id=%s\n""kernel_metric=%d\n",state_
file,babel_config_file?babel_config_file:babel_config_default,format_address(pro
tocol_group),protocol_port,babel_vty_addr?babel_vty_addr:"None",babel_vty_port,f
ormat_eui64(myid),kernel_metric);}