/*Copyright(c)2007,2008byJuliuszChroboczekPermissionisherebygranted,freeofcharge
,toanypersonobtainingacopyofthissoftwareandassociateddocumentationfiles(the"Soft
ware"),todealintheSoftwarewithoutrestriction,includingwithoutlimitationtherights
touse,copy,modify,merge,publish,distribute,sublicense,and/orsellcopiesoftheSoftw
are,andtopermitpersonstowhomtheSoftwareisfurnishedtodoso,subjecttothefollowingco
nditions:Theabovecopyrightnoticeandthispermissionnoticeshallbeincludedinallcopie
sorsubstantialportionsoftheSoftware.THESOFTWAREISPROVIDED"ASIS",WITHOUTWARRANTYO
FANYKIND,EXPRESSORIMPLIED,INCLUDINGBUTNOTLIMITEDTOTHEWARRANTIESOFMERCHANTABILITY
,FITNESSFORAPARTICULARPURPOSEANDNONINFRINGEMENT.INNOEVENTSHALLTHEAUTHORSORCOPYRI
GHTHOLDERSBELIABLEFORANYCLAIM,DAMAGESOROTHERLIABILITY,WHETHERINANACTIONOFCONTRAC
T,TORTOROTHERWISE,ARISINGFROM,OUTOFORINCONNECTIONWITHTHESOFTWAREORTHEUSEOROTHERD
EALINGSINTHESOFTWARE.*/#include<unistd.h>#include<fcntl.h>#include<string.h>#inc
lude<sys/ioctl.h>#include<sys/types.h>#include<sys/uio.h>#include<sys/socket.h>#
include<netinet/in.h>#include<netinet/in_systm.h>#include<netinet/ip.h>#include<
arpa/inet.h>#include<errno.h>#include"babeld.h"#include"util.h"#include"net.h"#i
nclude"sockopt.h"intbabel_socket(intport){structsockaddr_in6sin6;ints,rc;intsave
d_errno;intone=1,zero=0;s=socket(PF_INET6,SOCK_DGRAM,0);if(s<0)return-1;rc=setso
ckopt(s,IPPROTO_IPV6,IPV6_V6ONLY,&one,sizeof(one));if(rc<0)gotofail;rc=setsockop
t(s,SOL_SOCKET,SO_REUSEADDR,&one,sizeof(one));if(rc<0)gotofail;rc=setsockopt(s,I
PPROTO_IPV6,IPV6_MULTICAST_LOOP,&zero,sizeof(zero));if(rc<0)gotofail;rc=setsocko
pt(s,IPPROTO_IPV6,IPV6_UNICAST_HOPS,&one,sizeof(one));if(rc<0)gotofail;rc=setsoc
kopt(s,IPPROTO_IPV6,IPV6_MULTICAST_HOPS,&one,sizeof(one));if(rc<0)gotofail;setso
ckopt_ipv6_tclass(s,IPTOS_PREC_INTERNETCONTROL);rc=fcntl(s,F_GETFL,0);if(rc<0)go
tofail;rc=fcntl(s,F_SETFL,(rc|O_NONBLOCK));if(rc<0)gotofail;rc=fcntl(s,F_GETFD,0
);if(rc<0)gotofail;rc=fcntl(s,F_SETFD,rc|FD_CLOEXEC);if(rc<0)gotofail;memset(&si
n6,0,sizeof(sin6));sin6.sin6_family=AF_INET6;sin6.sin6_port=htons(port);rc=bind(
s,(structsockaddr*)&sin6,sizeof(sin6));if(rc<0)gotofail;returns;fail:saved_errno
=errno;close(s);errno=saved_errno;return-1;}intbabel_recv(ints,void*buf,intbufle
n,structsockaddr*sin,intslen){structioveciovec;structmsghdrmsg;intrc;memset(&msg
,0,sizeof(msg));iovec.iov_base=buf;iovec.iov_len=buflen;msg.msg_name=sin;msg.msg
_namelen=slen;msg.msg_iov=&iovec;msg.msg_iovlen=1;rc=recvmsg(s,&msg,0);returnrc;
}intbabel_send(ints,void*buf1,intbuflen1,void*buf2,intbuflen2,structsockaddr*sin
,intslen){structioveciovec[2];structmsghdrmsg;intrc;iovec[0].iov_base=buf1;iovec
[0].iov_len=buflen1;iovec[1].iov_base=buf2;iovec[1].iov_len=buflen2;memset(&msg,
0,sizeof(msg));msg.msg_name=(structsockaddr*)sin;msg.msg_namelen=slen;msg.msg_io
v=iovec;msg.msg_iovlen=2;again:rc=sendmsg(s,&msg,0);if(rc<0){if(errno==EINTR)got
oagain;elseif(errno==EAGAIN){intrc2;rc2=wait_for_fd(1,s,5);if(rc2>0)gotoagain;er
rno=EAGAIN;}}returnrc;}inttcp_server_socket(intport,intlocal){structsockaddr_in6
sin6;ints,rc,saved_errno;intone=1;s=socket(PF_INET6,SOCK_STREAM,0);if(s<0)return
-1;rc=setsockopt(s,SOL_SOCKET,SO_REUSEADDR,&one,sizeof(one));if(rc<0)gotofail;rc
=fcntl(s,F_GETFL,0);if(rc<0)gotofail;rc=fcntl(s,F_SETFL,(rc|O_NONBLOCK));if(rc<0
)gotofail;rc=fcntl(s,F_GETFD,0);if(rc<0)gotofail;rc=fcntl(s,F_SETFD,rc|FD_CLOEXE
C);if(rc<0)gotofail;memset(&sin6,0,sizeof(sin6));sin6.sin6_family=AF_INET6;sin6.
sin6_port=htons(port);if(local){rc=inet_pton(AF_INET6,"::1",&sin6.sin6_addr);if(
rc<0)gotofail;}rc=bind(s,(structsockaddr*)&sin6,sizeof(sin6));if(rc<0)gotofail;r
c=listen(s,2);if(rc<0)gotofail;returns;fail:saved_errno=errno;close(s);errno=sav
ed_errno;return-1;}