/**Copyright(C)2004PaulJakma**ThisfileispartofQuagga.**Quaggaisfreesoftware;youc
anredistributeitand/ormodifyit*underthetermsoftheGNUGeneralPublicLicenseaspublis
hedbythe*FreeSoftwareFoundation;eitherversion2,or(atyouroption)any*laterversion.
**Quaggaisdistributedinthehopethatitwillbeuseful,but*WITHOUTANYWARRANTY;withoute
ventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*
GeneralPublicLicenseformoredetails.**YoushouldhavereceivedacopyoftheGNUGeneralPu
blicLicensealong*withthisprogram;seethefileCOPYING;ifnot,writetotheFreeSoftware*
Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-1301USA*/#include<zebra.h
>#include<memory.h>#include<memory_vty.h>#include<buffer.h>structthread_master*m
aster;intmain(intargc,char**argv){structbuffer*b1,*b2;intn;charjunk[3];charc='a'
;memory_init();if((argc!=2)||(sscanf(argv[1],"%d%1s",&n,junk)!=1)){fprintf(stder
r,"Usage:%s<numberofcharstosimulate>\n",*argv);return1;}b1=buffer_new(0);b2=buff
er_new(1024);while(n-->0){buffer_put(b1,&c,1);buffer_put(b2,&c,1);if(c++=='z')c=
'a';buffer_reset(b1);buffer_reset(b2);}buffer_free(b1);buffer_free(b2);return0;}
