/**Circularbuffertests.*Copyright(C)2017CumulusNetworks*QuentinYoung**Thisprogra
misfreesoftware;youcanredistributeitand/ormodifyit*underthetermsoftheGNUGeneralP
ublicLicenseaspublishedbytheFree*SoftwareFoundation;eitherversion2oftheLicense,o
r(atyouroption)*anylaterversion.**Thisprogramisdistributedinthehopethatitwillbeu
seful,butWITHOUT*ANYWARRANTY;withouteventheimpliedwarrantyofMERCHANTABILITYor*FI
TNESSFORAPARTICULARPURPOSE.SeetheGNUGeneralPublicLicensefor*moredetails.**Yousho
uldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefile
COPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Bos
ton,MA02110-1301USA*/#include<zebra.h>#include<memory.h>#include"ringbuf.h"stati
cvoidvalidate_state(structringbuf*buf,size_tsize,size_tcontains){assert(buf->siz
e==size);assert(ringbuf_remain(buf)==contains);assert(ringbuf_space(buf)==buf->s
ize-contains);assert(buf->empty!=(bool)contains);}intmain(intargc,char**argv){st
ructringbuf*soil=ringbuf_new(BUFSIZ);validate_state(soil,BUFSIZ,0);/*verifyreset
functionalityoncleanbuffer*/printf("Validatingresetonemptybuffer...\n");ringbuf_
reset(soil);validate_state(soil,BUFSIZ,0);/*putonebyte*/printf("Validatingwrite.
..\n");uint8_twalnut=47;assert(ringbuf_put(soil,&walnut,sizeof(walnut))==1);vali
date_state(soil,BUFSIZ,1);/*validatereadlimitations*/printf("Validatingreadlimit
s...\n");uint8_tnuts[2];assert(ringbuf_get(soil,&nuts,sizeof(nuts))==1);/*reset*
/printf("Validatingresetonfullbuffer...\n");ringbuf_reset(soil);validate_state(s
oil,BUFSIZ,0);/*copystackgarbagetobuffer*/printf("Validatingbigwrite...\n");uint
8_tcompost[BUFSIZ];assert(ringbuf_put(soil,&compost,sizeof(compost))==BUFSIZ);va
lidate_state(soil,BUFSIZ,BUFSIZ);assert(soil->start==0);assert(soil->end==0);/*r
ead15bytesofgarbage*/printf("Validatingread...\n");assert(ringbuf_get(soil,&comp
ost,15)==15);validate_state(soil,BUFSIZ,BUFSIZ-15);assert(soil->start==15);asser
t(soil->end==0);/*putanother10bytesandvalidatewraparound*/printf("Validatingwrap
around...\n");assert(ringbuf_put(soil,&compost[BUFSIZ/2],10)==10);validate_state
(soil,BUFSIZ,BUFSIZ-15+10);assert(soil->start==15);assert(soil->end==10);/*putan
other15bytesandvalidatestate*/printf("Validatingsizelimits...\n");assert(ringbuf
_put(soil,&compost,15)==5);validate_state(soil,BUFSIZ,BUFSIZ);/*readentirebuffer
*/printf("Validatingbigread...\n");assert(ringbuf_get(soil,&compost,BUFSIZ)==BUF
SIZ);validate_state(soil,BUFSIZ,0);assert(soil->empty=true);assert(soil->start==
soil->end);assert(soil->start==15);/*reademptybuffer*/printf("Validatingemptyrea
d...\n");assert(ringbuf_get(soil,&compost,1)==0);validate_state(soil,BUFSIZ,0);/
*reset,validatestate*/printf("Validatingreset...\n");ringbuf_reset(soil);validat
e_state(soil,BUFSIZ,0);assert(soil->start==0);assert(soil->end==0);/*wipe,valida
testate*/printf("Validatingwipe...\n");memset(&compost,0x00,sizeof(compost));rin
gbuf_wipe(soil);assert(memcmp(&compost,soil->data,sizeof(compost))==0);/*validat
emaximumwrite*/printf("Validatingverybigwrite...\n");constcharflower[BUFSIZ*2];a
ssert(ringbuf_put(soil,&flower,sizeof(flower))==BUFSIZ);validate_state(soil,BUFS
IZ,BUFSIZ);/*wipe,validatestate*/printf("Validatingwipe...\n");memset(&compost,0
x00,sizeof(compost));ringbuf_wipe(soil);assert(memcmp(&compost,soil->data,sizeof
(compost))==0);/*validatesimpledataencode/decode*/constchar*organ="seed";printf(
"Encoding:'%s'\n",organ);assert(ringbuf_put(soil,organ,strlen(organ))==4);charwa
ter[strlen(organ)+1];assert(ringbuf_get(soil,&water,strlen(organ))==4);water[str
len(organ)]='\0';printf("Retrieved:'%s'\n",water);validate_state(soil,BUFSIZ,0);
/*validatesimpledataencode/decodeacrossringboundary*/soil->start=soil->size-2;so
il->end=soil->start;constchar*phloem="root";printf("Encoding:'%s'\n",phloem);ass
ert(ringbuf_put(soil,phloem,strlen(phloem))==4);charxylem[strlen(phloem)+1];asse
rt(ringbuf_get(soil,&xylem,100)==4);xylem[strlen(phloem)]='\0';printf("Retrieved
:'%s'\n",xylem);ringbuf_wipe(soil);/*validatesimpledatapeekacrossringboundary*/s
oil->start=soil->size-2;soil->end=soil->start;constchar*cytoplasm="tree";printf(
"Encoding:'%s'\n",cytoplasm);assert(ringbuf_put(soil,cytoplasm,strlen(cytoplasm)
)==4);charchloroplast[strlen(cytoplasm)+1];assert(ringbuf_peek(soil,2,&chloropla
st[0],100)==2);assert(ringbuf_peek(soil,0,&chloroplast[2],2)==2);chloroplast[str
len(cytoplasm)]='\0';assert(!strcmp(chloroplast,"eetr"));printf("Retrieved:'%s'\
n",chloroplast);printf("Deleting...\n");ringbuf_del(soil);printf("Creatingnewbuf
fer...\n");soil=ringbuf_new(15);soil->start=soil->end=7;/*validatedataencodeofex
cessivedata*/constchar*twenty="vascularplants----";charsixteen[16];printf("Encod
ing:%s\n",twenty);assert(ringbuf_put(soil,twenty,strlen(twenty))==15);assert(rin
gbuf_get(soil,sixteen,20));sixteen[15]='\0';printf("Retrieved:%s\n",sixteen);ass
ert(!strcmp(sixteen,"vascularplants"));printf("Deleting...\n");ringbuf_del(soil)
;printf("Done.\n");return0;}