/*Simplestreamtest.**Copyright(C)2006SunMicrosystems,Inc.**ThisfileispartofQuagg
a.**Quaggaisfreesoftware;youcanredistributeitand/ormodifyit*underthetermsoftheGN
UGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eitherversion2,or(a
tyouroption)any*laterversion.**Quaggaisdistributedinthehopethatitwillbeuseful,bu
t*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFOR
APARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldhaver
eceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;
ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02
110-1301USA*/#include<zebra.h>#include<stream.h>#include<thread.h>staticunsigned
longlongham=0xdeadbeefdeadbeef;structthread_master*master;staticvoidprint_stream
(structstream*s){size_tgetp=stream_get_getp(s);printf("endp:%zu,readable:%zu,wri
teable:%zu\n",stream_get_endp(s),STREAM_READABLE(s),STREAM_WRITEABLE(s));while(S
TREAM_READABLE(s)){printf("0x%x",*stream_pnt(s));stream_forward_getp(s,1);}print
f("\n");/*putgetpbacktowhereitwas*/stream_set_getp(s,getp);}intmain(void){struct
stream*s;s=stream_new(1024);stream_putc(s,ham);stream_putw(s,ham);stream_putl(s,
ham);stream_putq(s,ham);print_stream(s);stream_resize(s,stream_get_endp(s));prin
t_stream(s);printf("c:0x%hhx\n",stream_getc(s));printf("w:0x%hx\n",stream_getw(s
));printf("l:0x%x\n",stream_getl(s));printf("q:0x%"PRIx64"\n",stream_getq(s));re
turn0;}