/**SEGV/backtracehandlingtest.**copiedfromtest-sig.c**Copyright(C)2013byDavidLam
parter,OpenSourceRouting.*Copyright(C)2013byInternetSystemsConsortium,Inc.("ISC"
)**ThisfileispartofQuagga**Quaggaisfreesoftware;youcanredistributeitand/ormodify
it*underthetermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundat
ion;eitherversion2,or(atyouroption)any*laterversion.**Quaggaisdistributedintheho
pethatitwillbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERC
HANTABILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformored
etails.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthispro
gram;seethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt
,FifthFloor,Boston,MA02110-1301USA*/#include<zebra.h>#include<sigevent.h>#includ
e"lib/log.h"#include"lib/memory.h"structquagga_signal_tsigs[]={};structthread_ma
ster*master;staticintthreadfunc(structthread*thread){int*null=NULL;*null+=1;retu
rn0;}intmain(void){master=thread_master_create(NULL);signal_init(master,array_si
ze(sigs),sigs);openzlog("testsegv","NONE",0,LOG_CONS|LOG_NDELAY|LOG_PID,LOG_DAEM
ON);zlog_set_level(ZLOG_DEST_SYSLOG,ZLOG_DISABLED);zlog_set_level(ZLOG_DEST_STDO
UT,LOG_DEBUG);zlog_set_level(ZLOG_DEST_MONITOR,ZLOG_DISABLED);thread_execute(mas
ter,threadfunc,0,0);exit(0);}