/**Testprogramwhichmeasuresthetimeittakestoscheduleand*removetimers.**Copyright(
C)2013byOpenSourceRouting.*Copyright(C)2013byInternetSystemsConsortium,Inc.("ISC
")**ThisfileispartofQuagga**Quaggaisfreesoftware;youcanredistributeitand/ormodif
yit*underthetermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFounda
tion;eitherversion2,or(atyouroption)any*laterversion.**Quaggaisdistributedintheh
opethatitwillbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MER
CHANTABILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformore
details.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthispr
ogram;seethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinS
t,FifthFloor,Boston,MA02110-1301USA*/#include<zebra.h>#include<stdio.h>#include<
unistd.h>#include"thread.h"#include"pqueue.h"#include"prng.h"#defineSCHEDULE_TIM
ERS1000000#defineREMOVE_TIMERS500000structthread_master*master;staticintdummy_fu
nc(structthread*thread){return0;}intmain(intargc,char**argv){structprng*prng;int
i;structthread**timers;structtimevaltv_start,tv_lap,tv_stop;unsignedlongt_schedu
le,t_remove;master=thread_master_create(NULL);prng=prng_new(0);timers=calloc(SCH
EDULE_TIMERS,sizeof(*timers));/*createthreadstructuressotheywon'tbeallocatedduri
ngthe*timemeasurement*/for(i=0;i<SCHEDULE_TIMERS;i++){timers[i]=NULL;thread_add_
timer_msec(master,dummy_func,NULL,0,&timers[i]);}for(i=0;i<SCHEDULE_TIMERS;i++)t
hread_cancel(timers[i]);monotime(&tv_start);for(i=0;i<SCHEDULE_TIMERS;i++){longi
nterval_msec;interval_msec=prng_rand(prng)%(100*SCHEDULE_TIMERS);timers[i]=NULL;
thread_add_timer_msec(master,dummy_func,NULL,interval_msec,&timers[i]);}monotime
(&tv_lap);for(i=0;i<REMOVE_TIMERS;i++){intindex;index=prng_rand(prng)%SCHEDULE_T
IMERS;if(timers[index])thread_cancel(timers[index]);timers[index]=NULL;}monotime
(&tv_stop);t_schedule=1000*(tv_lap.tv_sec-tv_start.tv_sec);t_schedule+=(tv_lap.t
v_usec-tv_start.tv_usec)/1000;t_remove=1000*(tv_stop.tv_sec-tv_lap.tv_sec);t_rem
ove+=(tv_stop.tv_usec-tv_lap.tv_usec)/1000;printf("Scheduling%drandomtimerstook%
ld.%03ldseconds.\n",SCHEDULE_TIMERS,t_schedule/1000,t_schedule%1000);printf("Rem
oving%drandomtimerstook%ld.%03ldseconds.\n",REMOVE_TIMERS,t_remove/1000,t_remove
%1000);fflush(stdout);free(timers);thread_master_free(master);prng_free(prng);re
turn0;}