/**Copyright(C)2008SunMicrosystems,Inc.**ThisfileispartofQuagga.**Quaggaisfreeso
ftware;youcanredistributeitand/ormodifyit*underthetermsoftheGNUGeneralPublicLice
nseaspublishedbythe*FreeSoftwareFoundation;eitherversion2,or(atyouroption)any*la
terversion.**Quaggaisdistributedinthehopethatitwillbeuseful,but*WITHOUTANYWARRAN
TY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE
.SeetheGNU*GeneralPublicLicenseformoredetails.**YoushouldhavereceivedacopyoftheG
NUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;ifnot,writetotheFr
eeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-1301USA*/#incl
ude<zebra.h>#include<stdlib.h>#include<time.h>#include"checksum.h"structthread_m
aster*master;structacc_vals{intc0;intc1;};structcsum_vals{structacc_valsa;intx;i
nty;};staticstructcsum_valsospfd_vals,isisd_vals;typedefsize_ttestsz_t;typedefui
nt16_ttestoff_t;/*FletcherChecksum--RefertoRFC1008.*/#defineMODX4102U/*Thefinalr
eductionphase.*Thisoneshouldbetheoriginalospfdversion*/staticuint16_treduce_ospf
d(structcsum_vals*vals,testsz_tlen,testoff_toff){#definexvals->x#defineyvals->y#
definec0vals->a.c0#definec1vals->a.c1x=((len-off-1)*c0-c1)%255;if(x<=0)x+=255;y=
510-c0-x;if(y>255)y-=255;/*takecareendianissue.*/returnhtons((x<<8)+y);#undefx#u
ndefy#undefc0#undefc1}/*slightlydifferentconcatenation*/staticuint16_treduce_osp
fd1(structcsum_vals*vals,testsz_tlen,testoff_toff){#definexvals->x#defineyvals->
y#definec0vals->a.c0#definec1vals->a.c1x=((len-off-1)*c0-c1)%255;if(x<=0)x+=255;
y=510-c0-x;if(y>255)y-=255;/*takecareendianissue.*/returnhtons((x<<8)|(y&0xff));
#undefx#undefy#undefc0#undefc1}/*originalisisdversion*/staticuint16_treduce_isis
d(structcsum_vals*vals,testsz_tlen,testoff_toff){#definexvals->x#defineyvals->y#
definec0vals->a.c0#definec1vals->a.c1uint32_tmul;mul=(len-off)*(c0);x=mul-c0-c1;
y=c1-mul-1;if(y>0)y++;if(x<0)x--;x%=255;y%=255;if(x==0)x=255;if(y==0)y=1;returnh
tons((x<<8)|(y&0xff));#undefx#undefy#undefc0#undefc1}/*Isthe-1inywrongperhaps?*/
staticuint16_treduce_isisd_yfix(structcsum_vals*vals,testsz_tlen,testoff_toff){#
definexvals->x#defineyvals->y#definec0vals->a.c0#definec1vals->a.c1uint32_tmul;m
ul=(len-off)*(c0);x=mul-c0-c1;y=c1-mul;if(y>0)y++;if(x<0)x--;x%=255;y%=255;if(x=
=0)x=255;if(y==0)y=1;returnhtons((x<<8)|(y&0xff));#undefx#undefy#undefc0#undefc1
}/*Movethemodsyp*/staticuint16_treduce_isisd_mod(structcsum_vals*vals,testsz_tle
n,testoff_toff){#definexvals->x#defineyvals->y#definec0vals->a.c0#definec1vals->
a.c1uint32_tmul;mul=(len-off)*(c0);x=mul-c1-c0;y=c1-mul-1;x%=255;y%=255;if(y>0)y
++;if(x<0)x--;if(x==0)x=255;if(y==0)y=1;returnhtons((x<<8)|(y&0xff));#undefx#und
efy#undefc0#undefc1}/*Movethemodsup+fixy*/staticuint16_treduce_isisd_mody(struct
csum_vals*vals,testsz_tlen,testoff_toff){#definexvals->x#defineyvals->y#definec0
vals->a.c0#definec1vals->a.c1uint32_tmul;mul=(len-off)*(c0);x=mul-c0-c1;y=c1-mul
;x%=255;y%=255;if(y>0)y++;if(x<0)x--;if(x==0)x=255;if(y==0)y=1;returnhtons((x<<8
)|(y&0xff));#undefx#undefy#undefc0#undefc1}structreductions_t{constchar*name;uin
t16_t(*f)(structcsum_vals*,testsz_t,testoff_t);}reducts[]={{.name="ospfd",.f=red
uce_ospfd},{.name="ospfd-1",.f=reduce_ospfd1},{.name="isisd",.f=reduce_isisd},{.
name="isisd-yfix",.f=reduce_isisd_yfix},{.name="isisd-mod",.f=reduce_isisd_mod},
{.name="isisd-mody",.f=reduce_isisd_mody},{NULL,NULL},};/*Theoriginalospfdchecks
um*/staticuint16_tospfd_checksum(uint8_t*buffer,testsz_tlen,testoff_toff){uint8_
t*sp,*ep,*p,*q;intc0=0,c1=0;intx,y;uint16_tchecksum,*csum;csum=(uint16_t*)(buffe
r+off);*(csum)=0;sp=buffer;for(ep=sp+len;sp<ep;sp=q){q=sp+MODX;if(q>ep)q=ep;for(
p=sp;p<q;p++){c0+=*p;c1+=c0;}c0%=255;c1%=255;}ospfd_vals.a.c0=c0;ospfd_vals.a.c1
=c1;//printf("%s:len%u,off%u,c0%d,c1%d\n",//__func__,len,off,c0,c1);x=((int)(len
-off-1)*(int)c0-(int)c1)%255;if(x<=0)x+=255;y=510-c0-x;if(y>255)y-=255;ospfd_val
s.x=x;ospfd_vals.y=y;buffer[off]=x;buffer[off+1]=y;/*takecareendianissue.*/check
sum=htons((x<<8)|(y&0xff));return(checksum);}/*theoriginal,brokenisisdchecksum*/
staticuint16_tiso_csum_create(uint8_t*buffer,testsz_tlen,testoff_toff){uint8_t*p
;intx;inty;uint32_tmul;uint32_tc0;uint32_tc1;uint16_tchecksum,*csum;inti,init_le
n,partial_len;checksum=0;csum=(uint16_t*)(buffer+off);*(csum)=checksum;p=buffer;
c0=0;c1=0;init_len=len;while(len!=0){partial_len=MIN(len,MODX);for(i=0;i<partial
_len;i++){c0=c0+*(p++);c1+=c0;}c0=c0%255;c1=c1%255;len-=partial_len;}isisd_vals.
a.c0=c0;isisd_vals.a.c1=c1;mul=(init_len-off)*c0;x=mul-c1-c0;y=c1-mul-1;if(y>0)y
++;if(x<0)x--;x%=255;y%=255;if(x==0)x=255;if(y==0)y=1;isisd_vals.x=x;isisd_vals.
y=y;checksum=htons((x<<8)|(y&0xFF));*(csum)=checksum;/*returnthechecksumforuseru
sage*/returnchecksum;}staticintverify(uint8_t*buffer,testsz_tlen){uint8_t*p;uint
32_tc0;uint32_tc1;inti,partial_len;p=buffer;c0=0;c1=0;while(len){partial_len=MIN
(len,5803U);for(i=0;i<partial_len;i++){c0=c0+*(p++);c1+=c0;}c0=c0%255;c1=c1%255;
len-=partial_len;}if(c0==0&&c1==0)return0;return1;}staticint/*returnchecksuminlo
w-order16bits*/in_cksum_optimized(void*parg,intnbytes){unsignedshort*ptr=parg;re
gisterlongsum;/*assumeslong==32bits*/registerunsignedshortanswer;/*assumesunsign
edshort==16bits*/registerintcount;/**Ouralgorithmissimple,usinga32-bitaccumulato
r(sum),*weaddsequential16-bitwordstoit,andattheend,foldback*allthecarrybitsfromt
hetop16bitsintothelower16bits.*/sum=0;count=nbytes>>1;/*divby2*/for(ptr--;count;
--count)sum+=*++ptr;if(nbytes&1)/*Odd*/sum+=*(uint8_t*)(++ptr);/*onebyteonly*//*
*Addbackcarryoutsfromtop16bitstolow16bits.*/sum=(sum>>16)+(sum&0xffff);/*addhigh
-16tolow-16*/sum+=(sum>>16);/*addcarry*/answer=~sum;/*ones-complement,thentrunca
teto16bits*/return(answer);}staticint/*returnchecksuminlow-order16bits*/in_cksum
_rfc(void*parg,intcount)/*fromRFC1071*/{unsignedshort*addr=parg;/*ComputeInterne
tChecksumfor"count"bytes*beginningatlocation"addr".*/registerlongsum=0;while(cou
nt>1){/*Thisistheinnerloop*/sum+=*addr++;count-=2;}/*Addleft-overbyte,ifany*/if(
count>0){sum+=*(uint8_t*)addr;}/*Fold32-bitsumto16bits*/while(sum>>16)sum=(sum&0
xffff)+(sum>>16);return~sum;}intmain(intargc,char**argv){/*6001765629702179*/#de
fineMAXDATALEN60017#defineBUFSIZEMAXDATALEN+sizeof(uint16_t)uint8_tbuffer[BUFSIZ
E];intexercise=0;#defineEXERCISESTEP257srandom(time(NULL));while(1){uint16_tospf
d,isisd,lib,in_csum,in_csum_res,in_csum_rfc;inti,j;exercise+=EXERCISESTEP;exerci
se%=MAXDATALEN;for(i=0;i<exercise;i+=sizeof(longint)){longintrand=random();for(j
=sizeof(longint);j>0;j--)buffer[i+(sizeof(longint)-j)]=(rand>>(j*8))&0xff;}in_cs
um=in_cksum(buffer,exercise);in_csum_res=in_cksum_optimized(buffer,exercise);in_
csum_rfc=in_cksum_rfc(buffer,exercise);if(in_csum_res!=in_csum||in_csum!=in_csum
_rfc)printf("verify:in_chksumfailedin_csum:%x,in_csum_res:%x,""in_csum_rfc%x,len
:%d\n",in_csum,in_csum_res,in_csum_rfc,exercise);ospfd=ospfd_checksum(buffer,exe
rcise+sizeof(uint16_t),exercise);if(verify(buffer,exercise+sizeof(uint16_t)))pri
ntf("verify:ospfdfailed\n");isisd=iso_csum_create(buffer,exercise+sizeof(uint16_
t),exercise);if(verify(buffer,exercise+sizeof(uint16_t)))printf("verify:isisdfai
led\n");lib=fletcher_checksum(buffer,exercise+sizeof(uint16_t),exercise);if(veri
fy(buffer,exercise+sizeof(uint16_t)))printf("verify:libfailed\n");if(ospfd!=lib)
{printf("Mismatchinvaluesatsize%u\n""ospfd:0x%04x\tc0:%d\tc1:%d\tx:%d\ty:%d\n""i
sisd:0x%04x\tc0:%d\tc1:%d\tx:%d\ty:%d\n""lib:0x%04x\n",exercise,ospfd,ospfd_vals
.a.c0,ospfd_vals.a.c1,ospfd_vals.x,ospfd_vals.y,isisd,isisd_vals.a.c0,isisd_vals
.a.c1,isisd_vals.x,isisd_vals.y,lib);/*Investigatereductionphasediscrepencies*/i
f(ospfd_vals.a.c0==isisd_vals.a.c0&&ospfd_vals.a.c1==isisd_vals.a.c1){printf("\n
");for(i=0;reducts[i].name!=NULL;i++){ospfd=reducts[i].f(&ospfd_vals,exercise+si
zeof(uint16_t),exercise);printf("%20s:x:%02x,y%02x,checksum0x%04x\n",reducts[i].
name,ospfd_vals.x&0xff,ospfd_vals.y&0xff,ospfd);}}printf("\nuint8_ttestdata[]={\
n");for(i=0;i<exercise;i++){printf("0x%02x,%s",buffer[i],(i+1)%8?"":"\n");}print
f("\n}\n");exit(1);}}}