/**ASCIItablegenerator.*Copyright(C)2017CumulusNetworks*QuentinYoung**Thisprogra
misfreesoftware;youcanredistributeitand/ormodifyit*underthetermsoftheGNUGeneralP
ublicLicenseaspublishedbytheFree*SoftwareFoundation;eitherversion2oftheLicense,o
r(atyouroption)*anylaterversion.**Thisprogramisdistributedinthehopethatitwillbeu
seful,butWITHOUT*ANYWARRANTY;withouteventheimpliedwarrantyofMERCHANTABILITYor*FI
TNESSFORAPARTICULARPURPOSE.SeetheGNUGeneralPublicLicensefor*moredetails.**Yousho
uldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefile
COPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Bos
ton,MA02110-1301USA*/#include<zebra.h>#include<termtable.h>#include<memory.h>int
main(intargc,char**argv){char*table;structttable*tt=ttable_new(&ttable_styles[TT
STYLE_ASCII]);/*testprintfcompatibilityanddimensioncounters*/ttable_add_row(tt,"
%s|%s|%s","Column1","Column2","Column3");assert(tt->ncols==3);assert(tt->nrows==
1);table=ttable_dump(tt,"\n");fprintf(stdout,"%s\n",table);XFREE(MTYPE_TMP,table
);/*addnewrowwith1column,assertthatitisnotadded*/assert(ttable_add_row(tt,"%s","
Garbage")==NULL);assert(tt->ncols==3);assert(tt->nrows==1);table=ttable_dump(tt,
"\n");fprintf(stdout,"%s\n",table);XFREE(MTYPE_TMP,table);/*addnewrow,assertthat
itisadded*/assert(ttable_add_row(tt,"%s|%s|%s","a","b","c"));assert(tt->ncols==3
);assert(tt->nrows==2);table=ttable_dump(tt,"\n");fprintf(stdout,"%s\n",table);X
FREE(MTYPE_TMP,table);/*addemptyrow,assertthatitisadded*/assert(ttable_add_row(t
t,"||"));assert(tt->ncols==3);assert(tt->nrows==3);table=ttable_dump(tt,"\n");fp
rintf(stdout,"%s\n",table);XFREE(MTYPE_TMP,table);/*delete1strow,assertthatitisr
emoved*/ttable_del_row(tt,0);assert(tt->ncols==3);assert(tt->nrows==2);table=tta
ble_dump(tt,"\n");fprintf(stdout,"%s\n",table);XFREE(MTYPE_TMP,table);/*deletela
strow,assertthatitisremoved*/ttable_del_row(tt,0);assert(tt->ncols==3);assert(tt
->nrows==1);table=ttable_dump(tt,"\n");fprintf(stdout,"%s\n",table);XFREE(MTYPE_
TMP,table);/*deletetheremainingrow,checkdumpinganemptytable*/ttable_del_row(tt,0
);assert(tt->ncols==0);assert(tt->nrows==0);table=ttable_dump(tt,"\n");fprintf(s
tdout,"%s\n",table);XFREE(MTYPE_TMP,table);/*addnewrow*/ttable_add_row(tt,"%s|%s
||%s|%9d","slick","black","triple",1337);assert(tt->ncols==5);assert(tt->nrows==
1);table=ttable_dump(tt,"\n");fprintf(stdout,"%s\n",table);XFREE(MTYPE_TMP,table
);/*addbiggerrow*/ttable_add_row(tt,"%s|%s||%s|%s","nebuladusksessionstreetstwil
ight""pioneerbeatsyeah","prariedog","cornmeal",":O-*_-*");assert(tt->ncols==5);a
ssert(tt->nrows==2);table=ttable_dump(tt,"\n");fprintf(stdout,"%s\n",table);XFRE
E(MTYPE_TMP,table);/*insertnewrowatbeginning*/ttable_insert_row(tt,0,"%s|%s||%d|
%lf","converting","vegetarians",2,2015.0);assert(tt->ncols==5);assert(tt->nrows=
=3);table=ttable_dump(tt,"\n");fprintf(stdout,"%s\n",table);XFREE(MTYPE_TMP,tabl
e);/*insertnewrowatend*/ttable_insert_row(tt,tt->nrows-1,"%s|%s||%d|%ld","conver
ting","vegetarians",1,2003L);assert(tt->ncols==5);assert(tt->nrows==4);table=tta
ble_dump(tt,"\n");fprintf(stdout,"%s\n",table);XFREE(MTYPE_TMP,table);/*insertne
wrowatmiddle*/ttable_insert_row(tt,1,"%s|%s||%s|%ld","she","pioneer","aki",1l);a
ssert(tt->ncols==5);assert(tt->nrows==5);table=ttable_dump(tt,"\n");fprintf(stdo
ut,"%s\n",table);XFREE(MTYPE_TMP,table);/*setalignment*/ttable_align(tt,0,1,2,2,
LEFT);assert(tt->ncols==5);assert(tt->nrows==5);table=ttable_dump(tt,"\n");fprin
tf(stdout,"%s\n",table);XFREE(MTYPE_TMP,table);ttable_align(tt,0,1,5,1,RIGHT);as
sert(tt->ncols==5);assert(tt->nrows==5);table=ttable_dump(tt,"\n");fprintf(stdou
t,"%s\n",table);XFREE(MTYPE_TMP,table);/*setpadding*/ttable_pad(tt,0,1,1,1,RIGHT
,2);assert(tt->ncols==5);assert(tt->nrows==5);table=ttable_dump(tt,"\n");fprintf
(stdout,"%s\n",table);XFREE(MTYPE_TMP,table);ttable_pad(tt,0,0,5,4,LEFT,2);asser
t(tt->ncols==5);assert(tt->nrows==5);table=ttable_dump(tt,"\n");fprintf(stdout,"
%s\n",table);XFREE(MTYPE_TMP,table);/*restyle*/tt->style.cell.border.bottom_on=f
alse;tt->style.cell.border.top_on=false;tt->style.cell.border.right_on=false;tt-
>style.cell.border.left_on=false;ttable_restyle(tt);/*top&doublebottomborderfort
oprow*/ttable_rowseps(tt,0,BOTTOM,true,'-');ttable_rowseps(tt,1,TOP,true,'-');ta
ble=ttable_dump(tt,"\n");fprintf(stdout,"%s\n",table);XFREE(MTYPE_TMP,table);/*c
olumnseparatorsforleftmostcolumn*/ttable_colseps(tt,0,RIGHT,true,'|');table=ttab
le_dump(tt,"\n");fprintf(stdout,"%s\n",table);XFREE(MTYPE_TMP,table);/*deletetab
le*/ttable_del(tt);}