/*ASpathmanagementroutines.*Copyright(C)1996,97,98,99KunihiroIshiguro*Copyright(
C)2005SunMicrosystems,Inc.**ThisfileispartofGNUZebra.**GNUZebraisfreesoftware;yo
ucanredistributeitand/ormodifyit*underthetermsoftheGNUGeneralPublicLicenseaspubl
ishedbythe*FreeSoftwareFoundation;eitherversion2,or(atyouroption)any*laterversio
n.**GNUZebraisdistributedinthehopethatitwillbeuseful,but*WITHOUTANYWARRANTY;with
outeventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.Seethe
GNU*GeneralPublicLicenseformoredetails.**YoushouldhavereceivedacopyoftheGNUGener
alPublicLicensealong*withthisprogram;seethefileCOPYING;ifnot,writetotheFreeSoftw
are*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-1301USA*/#include<zeb
ra.h>#include"hash.h"#include"memory.h"#include"vector.h"#include"log.h"#include
"stream.h"#include"command.h"#include"jhash.h"#include"queue.h"#include"filter.h
"#include"bgpd/bgpd.h"#include"bgpd/bgp_aspath.h"#include"bgpd/bgp_debug.h"#incl
ude"bgpd/bgp_attr.h"/*Attr.FlagsandAttr.TypeCode.*/#defineAS_HEADER_SIZE2/*NowFO
URoctetsareusedforASvalue.*/#defineAS_VALUE_SIZEsizeof(as_t)/*Thisistheoldone*/#
defineAS16_VALUE_SIZEsizeof(as16_t)/*Maximumprotocolsegmentlengthvalue*/#defineA
S_SEGMENT_MAX255/*ThefollowinglengthandsizemacrosrelatespecificallytoQuagga's*in
ternalrepresentationofAS-Segments,notpersetotheon-wire*sizesandlengths.Atpresent
(200508)theysortofmatch,however*theONLYfunctionswhichshouldnowabouttheon-wiresyn
taxare*aspath_put,assegment_putandassegment_parse.**aspath_putreturnsbyteswritte
n,theonlydefinitiverecordof*sizeofwire-formatattribute..*//*Calculatedsizeinbyte
sofASNsegmentdatatoholdNASN's*/#defineASSEGMENT_DATA_SIZE(N,S)\((N)*((S)?AS_VALU
E_SIZE:AS16_VALUE_SIZE))/*CalculatedsizeofsegmentstructtoholdNASN's*/#defineASSE
GMENT_SIZE(N,S)(AS_HEADER_SIZE+ASSEGMENT_DATA_SIZE(N,S))/*ASsegmentoctetlength.*
/#defineASSEGMENT_LEN(X,S)ASSEGMENT_SIZE((X)->length,S)/*AS_SEQUENCEsegmentscanb
epackedtogether*//*CanthetypesofXandYbeconsideredforpacking?*/#defineASSEGMENT_T
YPES_PACKABLE(X,Y)\(((X)->type==(Y)->type)&&((X)->type==AS_SEQUENCE))/*Typesandl
engthofX,Ysuitableforpacking?*/#defineASSEGMENTS_PACKABLE(X,Y)\(ASSEGMENT_TYPES_
PACKABLE((X),(Y))\&&(((X)->length+(Y)->length)<=AS_SEGMENT_MAX))/*Assegmentheade
r-theon-wirerepresentation*NOTtheinternalrepresentation!*/structassegment_header
{uint8_ttype;uint8_tlength;};/*Hashforaspath.ThisisthetoplevelstructureofASpath.
*/staticstructhash*ashash;/*StreamforSNMP.Seeaspath_snmp_pathseg*/staticstructst
ream*snmp_stream;/*Callersarerequiredtoinitializethememory*/staticas_t*assegment
_data_new(intnum){return(XMALLOC(MTYPE_AS_SEG_DATA,ASSEGMENT_DATA_SIZE(num,1)));
}staticvoidassegment_data_free(as_t*asdata){XFREE(MTYPE_AS_SEG_DATA,asdata);}con
stchar*aspath_segment_type_str[]={"as-invalid","as-set","as-sequence","as-confed
-sequence","as-confed-set"};/*Getanewsegment.Notethat0isanallowedlength,*andwill
resultinasegmentwithnoallocateddatasegment.*thecallershouldimmediatelyassigndata
tothesegment,asthesegment*otherwiseisnotgenerallyvalid*/staticstructassegment*as
segment_new(uint8_ttype,unsignedshortlength){structassegment*new;new=XCALLOC(MTY
PE_AS_SEG,sizeof(structassegment));if(length)new->as=assegment_data_new(length);
new->length=length;new->type=type;returnnew;}staticvoidassegment_free(structasse
gment*seg){if(!seg)return;if(seg->as)assegment_data_free(seg->as);memset(seg,0xf
e,sizeof(structassegment));XFREE(MTYPE_AS_SEG,seg);return;}/*freeentirechainofse
gments*/staticvoidassegment_free_all(structassegment*seg){structassegment*prev;w
hile(seg){prev=seg;seg=seg->next;assegment_free(prev);}}/*Duplicatejustthegivena
ssegmentanditsdata*/staticstructassegment*assegment_dup(structassegment*seg){str
uctassegment*new;new=assegment_new(seg->type,seg->length);memcpy(new->as,seg->as
,ASSEGMENT_DATA_SIZE(new->length,1));returnnew;}/*Duplicateentirechainofassegmen
ts,returnthehead*/staticstructassegment*assegment_dup_all(structassegment*seg){s
tructassegment*new=NULL;structassegment*head=NULL;while(seg){if(head){new->next=
assegment_dup(seg);new=new->next;}elsehead=new=assegment_dup(seg);seg=seg->next;
}returnhead;}/*prependtheasnumbertogivensegment,givennumoftimes*/staticstructass
egment*assegment_prepend_asns(structassegment*seg,as_tasnum,intnum){as_t*newas;i
nti;if(!num)returnseg;if(num>=AS_SEGMENT_MAX)returnseg;/*wedon'tdohugeprepends*/
if((newas=assegment_data_new(seg->length+num))==NULL)returnseg;for(i=0;i<num;i++
)newas[i]=asnum;memcpy(newas+num,seg->as,ASSEGMENT_DATA_SIZE(seg->length,1));ass
egment_data_free(seg->as);seg->as=newas;seg->length+=num;returnseg;}/*appendgive
narrayofasnumberstothesegment*/staticstructassegment*assegment_append_asns(struc
tassegment*seg,as_t*asnos,intnum){as_t*newas;newas=XREALLOC(MTYPE_AS_SEG_DATA,se
g->as,ASSEGMENT_DATA_SIZE(seg->length+num,1));if(newas){seg->as=newas;memcpy(seg
->as+seg->length,asnos,ASSEGMENT_DATA_SIZE(num,1));seg->length+=num;returnseg;}a
ssegment_free_all(seg);returnNULL;}staticintint_cmp(constvoid*p1,constvoid*p2){c
onstas_t*as1=p1;constas_t*as2=p2;return(*as1==*as2)?0:((*as1>*as2)?1:-1);}/*norm
alisethesegment.*Inparticular,mergerunsofAS_SEQUENCEsintoonesegment*Internally,w
edonotcareaboutthewiresegmentlengthlimit,and*wewanteachdistinctAS_PATHstohavethe
exactsameinternal*representation-eg,sothatourhashingactuallyworks..*/staticstruc
tassegment*assegment_normalise(structassegment*head){structassegment*seg=head,*p
in;structassegment*tmp;if(!head)returnhead;while(seg){pin=seg;/*SortvaluesSETseg
ments,fordeterminisminpathstoaid*creationofhashvalues/pathcomparisons*andbecause
ithelpsotherlesserimplementations;)*/if(seg->type==AS_SET||seg->type==AS_CONFED_
SET){inttail=0;inti;qsort(seg->as,seg->length,sizeof(as_t),int_cmp);/*weedoutdup
es*/for(i=1;i<seg->length;i++){if(seg->as[tail]==seg->as[i])continue;tail++;if(t
ail<i)seg->as[tail]=seg->as[i];}/*seg->lengthcanbe0..*/if(seg->length)seg->lengt
h=tail+1;}/*readaheadfromthecurrent,pinnedsegmentwhilethe*segments*arepackable/m
ergeable.Appendallfollowingpackable*segments*tothesegmentwehavepinnedandremoveth
eseappended*segments.*/while(pin->next&&ASSEGMENT_TYPES_PACKABLE(pin,pin->next))
{tmp=pin->next;seg=pin->next;/*appendthenextsequencetothepinnedsequence*/pin=ass
egment_append_asns(pin,seg->as,seg->length);/*bypassthenextsequence*/pin->next=s
eg->next;/*getridofthenowreferencelesssegment*/assegment_free(tmp);}seg=pin->nex
t;}returnhead;}staticstructaspath*aspath_new(void){returnXCALLOC(MTYPE_AS_PATH,s
izeof(structaspath));}/*FreeASpathstructure.*/voidaspath_free(structaspath*aspat
h){if(!aspath)return;if(aspath->segments)assegment_free_all(aspath->segments);if
(aspath->str)XFREE(MTYPE_AS_STR,aspath->str);if(aspath->json){json_object_free(a
spath->json);aspath->json=NULL;}XFREE(MTYPE_AS_PATH,aspath);}/*Uninternaspathfro
mASpathbucket.*/voidaspath_unintern(structaspath**aspath){structaspath*ret;struc
taspath*asp=*aspath;if(asp->refcnt)asp->refcnt--;if(asp->refcnt==0){/*Thisaspath
mustexistinaspathhashtable.*/ret=hash_release(ashash,asp);assert(ret!=NULL);aspa
th_free(asp);*aspath=NULL;}}/*ReturnthestartorenddelimitersforaparticularSegment
type*/#defineAS_SEG_START0#defineAS_SEG_END1staticcharaspath_delimiter_char(uint
8_ttype,uint8_twhich){inti;struct{inttype;charstart;charend;}aspath_delim_char[]
={{AS_SET,'{','}'},{AS_CONFED_SET,'[',']'},{AS_CONFED_SEQUENCE,'(',')'},{0}};for
(i=0;aspath_delim_char[i].type!=0;i++){if(aspath_delim_char[i].type==type){if(wh
ich==AS_SEG_START)returnaspath_delim_char[i].start;elseif(which==AS_SEG_END)retu
rnaspath_delim_char[i].end;}}return'';}/*countupasnsfromthissegmentandindexonwar
d*/staticintassegment_count_asns(structassegment*seg,intfrom){intcount=0;while(s
eg){if(!from)count+=seg->length;else{count+=(seg->length-from);from=0;}seg=seg->
next;}returncount;}unsignedintaspath_count_confeds(structaspath*aspath){intcount
=0;structassegment*seg=aspath->segments;while(seg){if(seg->type==AS_CONFED_SEQUE
NCE)count+=seg->length;elseif(seg->type==AS_CONFED_SET)count++;seg=seg->next;}re
turncount;}unsignedintaspath_count_hops(conststructaspath*aspath){intcount=0;str
uctassegment*seg=aspath->segments;while(seg){if(seg->type==AS_SEQUENCE)count+=se
g->length;elseif(seg->type==AS_SET)count++;seg=seg->next;}returncount;}/*Estimat
esizeaspath/might/takeifencodedintoan*ASPATHattribute.**Thisisaquickestimate,not
definitive!aspath_put()*mayreturnadifferentnumber!!*/unsignedintaspath_size(stru
ctaspath*aspath){intsize=0;structassegment*seg=aspath->segments;while(seg){size+
=ASSEGMENT_SIZE(seg->length,1);seg=seg->next;}returnsize;}/*ReturnhighestpublicA
SNinpath*/as_taspath_highest(structaspath*aspath){structassegment*seg=aspath->se
gments;as_thighest=0;unsignedinti;while(seg){for(i=0;i<seg->length;i++)if(seg->a
s[i]>highest&&!BGP_AS_IS_PRIVATE(seg->as[i]))highest=seg->as[i];seg=seg->next;}r
eturnhighest;}/*Returntheleft-mostASNinpath*/as_taspath_leftmost(structaspath*as
path){structassegment*seg=aspath->segments;as_tleftmost=0;if(seg&&seg->length&&s
eg->type==AS_SEQUENCE)leftmost=seg->as[0];returnleftmost;}/*Return1ifthereareany
4-byteASesinthepath*/unsignedintaspath_has_as4(structaspath*aspath){structassegm
ent*seg=aspath->segments;unsignedinti;while(seg){for(i=0;i<seg->length;i++)if(se
g->as[i]>BGP_AS_MAX)return1;seg=seg->next;}return0;}/*Convertaspathstructuretost
ringexpression.*/staticvoidaspath_make_str_count(structaspath*as,boolmake_json){
structassegment*seg;intstr_size;intlen=0;char*str_buf;json_object*jaspath_segmen
ts=NULL;json_object*jseg=NULL;json_object*jseg_list=NULL;if(make_json){as->json=
json_object_new_object();jaspath_segments=json_object_new_array();}/*Emptyaspath
.*/if(!as->segments){if(make_json){json_object_string_add(as->json,"string","Loc
al");json_object_object_add(as->json,"segments",jaspath_segments);json_object_in
t_add(as->json,"length",0);}as->str=XMALLOC(MTYPE_AS_STR,1);as->str[0]='\0';as->
str_len=0;return;}seg=as->segments;/*ASNtakes5to10charsplusseperator,seebelow.*I
fthereisonedifferingsegmenttype,weneedanadditional*2charsforsegmentdelimiters,an
dthefinal'\0'.*Hopefullythisislargeenoughtoavoidhittingtherealloc*codebelowformo
stcommonsequences.**Thiswaschangedto10afterthewell-knownBGPassertion,which*hadhi
tsomepartsoftheInternetinMayof2009.*/#defineASN_STR_LEN(10+1)str_size=MAX(assegm
ent_count_asns(seg,0)*ASN_STR_LEN+2+1,ASPATH_STR_DEFAULT_LEN);str_buf=XMALLOC(MT
YPE_AS_STR,str_size);while(seg){inti;charseperator;/*CheckAStypevalidity.Setsepe
ratorforsegment*/switch(seg->type){caseAS_SET:caseAS_CONFED_SET:seperator=',';br
eak;caseAS_SEQUENCE:caseAS_CONFED_SEQUENCE:seperator='';break;default:XFREE(MTYP
E_AS_STR,str_buf);as->str=NULL;as->str_len=0;json_object_free(as->json);as->json
=NULL;return;}/*Wemightneedtoincreasestr_buf,particularlyifpathhas*differingsegm
entstypes,ourinitialguesstimateabovewill*havebeenwrong.Need10charsforASN,asepera
toreachand*potentiallytwosegmentdelimiters,plusaspacebetweeneach*segmentandtrail
ingzero.**Thisdefinitelydidn'tworkwiththevalueof5bytesand*32-bitASNs.*/#defineSE
GMENT_STR_LEN(X)(((X)->length*ASN_STR_LEN)+2+1+1)if((len+SEGMENT_STR_LEN(seg))>s
tr_size){str_size=len+SEGMENT_STR_LEN(seg);str_buf=XREALLOC(MTYPE_AS_STR,str_buf
,str_size);}#undefASN_STR_LEN#undefSEGMENT_STR_LENif(seg->type!=AS_SEQUENCE)len+
=snprintf(str_buf+len,str_size-len,"%c",aspath_delimiter_char(seg->type,AS_SEG_S
TART));if(make_json)jseg_list=json_object_new_array();/*writeouttheASNs,withthei
rseperators,barthelastone*/for(i=0;i<seg->length;i++){if(make_json)json_object_a
rray_add(jseg_list,json_object_new_int(seg->as[i]));len+=snprintf(str_buf+len,st
r_size-len,"%u",seg->as[i]);if(i<(seg->length-1))len+=snprintf(str_buf+len,str_s
ize-len,"%c",seperator);}if(make_json){jseg=json_object_new_object();json_object
_string_add(jseg,"type",aspath_segment_type_str[seg->type]);json_object_object_a
dd(jseg,"list",jseg_list);json_object_array_add(jaspath_segments,jseg);}if(seg->
type!=AS_SEQUENCE)len+=snprintf(str_buf+len,str_size-len,"%c",aspath_delimiter_c
har(seg->type,AS_SEG_END));if(seg->next)len+=snprintf(str_buf+len,str_size-len,"
");seg=seg->next;}assert(len<str_size);str_buf[len]='\0';as->str=str_buf;as->str
_len=len;if(make_json){json_object_string_add(as->json,"string",str_buf);json_ob
ject_object_add(as->json,"segments",jaspath_segments);json_object_int_add(as->js
on,"length",aspath_count_hops(as));}return;}voidaspath_str_update(structaspath*a
s,boolmake_json){if(as->str)XFREE(MTYPE_AS_STR,as->str);if(as->json){json_object
_free(as->json);as->json=NULL;}aspath_make_str_count(as,make_json);}/*Internallo
catedASpath.*/structaspath*aspath_intern(structaspath*aspath){structaspath*find;
/*AssertthisASpathstructureisnotinternedandhasthestringrepresentationbuilt.*/ass
ert(aspath->refcnt==0);assert(aspath->str);/*CheckASpathhash.*/find=hash_get(ash
ash,aspath,hash_alloc_intern);if(find!=aspath)aspath_free(aspath);find->refcnt++
;returnfind;}/*Duplicateaspathstructure.Createdsameaspathstructurebutreferenceco
untandASpathstringiscleared.*/structaspath*aspath_dup(structaspath*aspath){unsig
nedshortbuflen=aspath->str_len+1;structaspath*new;new=XCALLOC(MTYPE_AS_PATH,size
of(structaspath));new->json=NULL;if(aspath->segments)new->segments=assegment_dup
_all(aspath->segments);if(!aspath->str)returnnew;new->str=XMALLOC(MTYPE_AS_STR,b
uflen);new->str_len=aspath->str_len;/*copythestringdata*/if(aspath->str_len>0)me
mcpy(new->str,aspath->str,buflen);elsenew->str[0]='\0';returnnew;}staticvoid*asp
ath_hash_alloc(void*arg){conststructaspath*aspath=arg;structaspath*new;/*Malform
edASpathvalue.*/assert(aspath->str);/*Newaspathstructureisneeded.*/new=XMALLOC(M
TYPE_AS_PATH,sizeof(structaspath));/*Reusesegmentsandstringrepresentation*/new->
refcnt=0;new->segments=aspath->segments;new->str=aspath->str;new->str_len=aspath
->str_len;new->json=aspath->json;returnnew;}/*parseas-segmentbytestreaminstructa
ssegment*/staticintassegments_parse(structstream*s,size_tlength,structassegment*
*result,intuse32bit){structassegment_headersegh;structassegment*seg,*prev=NULL,*
head=NULL;size_tbytes=0;/*emptyaspath(ieiBGPorsomesuch)*/if(length==0)return0;if
(BGP_DEBUG(as4,AS4_SEGMENT))zlog_debug("[AS4SEG]Parseaspathsegment:gottotalbytel
ength%lu",(unsignedlong)length);/*basicchecks*/if((STREAM_READABLE(s)<length)||(
STREAM_READABLE(s)<AS_HEADER_SIZE)||(length%AS16_VALUE_SIZE))return-1;while(byte
s<length){inti;size_tseg_size;if((length-bytes)<=AS_HEADER_SIZE){if(head)assegme
nt_free_all(head);return-1;}/*softlysoftly,gettheheaderfirstonitsown*/segh.type=
stream_getc(s);segh.length=stream_getc(s);seg_size=ASSEGMENT_SIZE(segh.length,us
e32bit);if(BGP_DEBUG(as4,AS4_SEGMENT))zlog_debug("[AS4SEG]Parseaspathsegment:got
type%d,length%d",segh.type,segh.length);/*checkit..*/if(((bytes+seg_size)>length
)/*1771bis4.3b:seglengthcontainsoneormore*/||(segh.length==0)/*Paranoiaincasesom
eonechangestypeofsegmentlength.*Shiftbothvaluesby0x10tomakethecomparisonoperate*
onmore,than8bits(otherwiseit'sawarning,bug*#564).*/||((sizeofsegh.length>1)&&(0x
10+segh.length>0x10+AS_SEGMENT_MAX))){if(head)assegment_free_all(head);return-1;
}switch(segh.type){caseAS_SEQUENCE:caseAS_SET:caseAS_CONFED_SEQUENCE:caseAS_CONF
ED_SET:break;default:if(head)assegment_free_all(head);return-1;}/*nowitssafetotr
ustlengths*/seg=assegment_new(segh.type,segh.length);if(head)prev->next=seg;else
/*it'sthefirstsegment*/head=prev=seg;for(i=0;i<segh.length;i++)seg->as[i]=(use32
bit)?stream_getl(s):stream_getw(s);bytes+=seg_size;if(BGP_DEBUG(as4,AS4_SEGMENT)
)zlog_debug("[AS4SEG]Parseaspathsegment:Bytesnow:%lu",(unsignedlong)bytes);prev=
seg;}*result=assegment_normalise(head);return0;}/*ASpathparsefunction.pntisapoin
tertobytestreamandlengthislengthofbytestream.IfthereissameASpathinthetheASpathha
shthenreturnitelsemakenewASpathstructure.OnerrorNULLisreturned.*/structaspath*as
path_parse(structstream*s,size_tlength,intuse32bit){structaspathas;structaspath*
find;/*Iflengthisoddit'smalformedASpath.*//*Nit-picking:if(use32bit==0)itismalfo
rmedifodd,*otherwiseitsmalformedwhenlengthislargerthan2and(length-2)*isnotdivida
bleby4.*But...thistimewe'relazy*/if(length%AS16_VALUE_SIZE)returnNULL;memset(&as
,0,sizeof(structaspath));if(assegments_parse(s,length,&as.segments,use32bit)<0)r
eturnNULL;/*Ifalreadysameaspathexistthenreturnit.*/find=hash_get(ashash,&as,aspa
th_hash_alloc);/*bug!shouldnothappen,letthedaemoncrashbelow*/assert(find);/*ifth
easpathwasalreadyhashedfreetemporarymemory.*/if(find->refcnt){assegment_free_all
(as.segments);/*aspath_key_make()alwaysupdatesthestring*/XFREE(MTYPE_AS_STR,as.s
tr);if(as.json){json_object_free(as.json);as.json=NULL;}}find->refcnt++;returnfi
nd;}staticvoidassegment_data_put(structstream*s,as_t*as,intnum,intuse32bit){inti
;assert(num<=AS_SEGMENT_MAX);for(i=0;i<num;i++)if(use32bit)stream_putl(s,as[i]);
else{if(as[i]<=BGP_AS_MAX)stream_putw(s,as[i]);elsestream_putw(s,BGP_AS_TRANS);}
}staticsize_tassegment_header_put(structstream*s,uint8_ttype,intlength){size_tle
np;assert(length<=AS_SEGMENT_MAX);stream_putc(s,type);lenp=stream_get_endp(s);st
ream_putc(s,length);returnlenp;}/*writeaspathdatatostream*/size_taspath_put(stru
ctstream*s,structaspath*as,intuse32bit){structassegment*seg=as->segments;size_tb
ytes=0;if(!seg||seg->length==0)return0;if(seg){/**Hey,whatdowedowhenwehave>STREA
M_WRITABLE(s)here?*Atthemoment,wewouldwriteoutapartialaspath,andour*peer*willcom
plainanddropthesession:-/**Thegeneralassumptionhereisthatmanythingstestedwill*ne
verhappen.And,inreallive,uptonow,theyhavenot.*/while(seg&&(ASSEGMENT_LEN(seg,use
32bit)<=STREAM_WRITEABLE(s))){structassegment*next=seg->next;intwritten=0;intasn
s_packed=0;size_tlenp;/*Overlengthsegmentshavetobesplitup*/while((seg->length-wr
itten)>AS_SEGMENT_MAX){assegment_header_put(s,seg->type,AS_SEGMENT_MAX);assegmen
t_data_put(s,seg->as,AS_SEGMENT_MAX,use32bit);written+=AS_SEGMENT_MAX;bytes+=ASS
EGMENT_SIZE(AS_SEGMENT_MAX,use32bit);}/*writethefinalsegment,probablyisalsothefi
rst*/lenp=assegment_header_put(s,seg->type,seg->length-written);assegment_data_p
ut(s,(seg->as+written),seg->length-written,use32bit);/*Sequence-typesegmentscanb
e'packed'together*Caseofasegmentwhichwasoverlengthandsplitup*willbemissedhere,bu
tthatdoesn'tmatter.*/while(next&&ASSEGMENTS_PACKABLE(seg,next)){/*NB:Weshouldnev
ernormallygetheregiven*we*normaliseaspathdatawhenparsethem.*However,better*safet
hansorry.Wepotentiallycouldcall*assegment_normalisehereinstead,butit's*cheaperan
d*easiertodoitontheflyhereratherthan*gothrough*thesegmentlisttwiceeverytimewewri
te*out*aspath's.*//*Nextsegment'sdatacanfitinthisone*/assegment_data_put(s,next-
>as,next->length,use32bit);/*updatethelengthofthesegmentheader*/stream_putc_at(s
,lenp,seg->length-written+next->length);asns_packed+=next->length;next=next->nex
t;}bytes+=ASSEGMENT_SIZE(seg->length-written+asns_packed,use32bit);seg=next;}}re
turnbytes;}/*ThisisforSNMPBGP4PATHATTRASPATHSEGMENT*Wehavenowaytomanagethestorag
e,soweuseastaticstream*wrapperaroundaspath_put.*/uint8_t*aspath_snmp_pathseg(str
uctaspath*as,size_t*varlen){#defineSNMP_PATHSEG_MAX1024if(!snmp_stream)snmp_stre
am=stream_new(SNMP_PATHSEG_MAX);elsestream_reset(snmp_stream);if(!as){*varlen=0;
returnNULL;}aspath_put(snmp_stream,as,0);/*use16bitfornowhere*/*varlen=stream_ge
t_endp(snmp_stream);returnstream_pnt(snmp_stream);}#definemin(A,B)((A)<(B)?(A):(
B))staticstructassegment*aspath_aggregate_as_set_add(structaspath*aspath,structa
ssegment*asset,as_tas){inti;/*IfthisisfirstASsetmember,createnewas-setsegment.*/
if(asset==NULL){asset=assegment_new(AS_SET,1);if(!aspath->segments)aspath->segme
nts=asset;else{structassegment*seg=aspath->segments;while(seg->next)seg=seg->nex
t;seg->next=asset;}asset->type=AS_SET;asset->length=1;asset->as[0]=as;}else{/*Ch
eckthisASvaluealreadyexistsornot.*/for(i=0;i<asset->length;i++)if(asset->as[i]==
as)returnasset;asset->length++;asset->as=XREALLOC(MTYPE_AS_SEG_DATA,asset->as,as
set->length*AS_VALUE_SIZE);asset->as[asset->length-1]=as;}returnasset;}/*Modifya
s1usingas2foraggregation.*/structaspath*aspath_aggregate(structaspath*as1,struct
aspath*as2){inti;intminlen=0;intmatch=0;intfrom;structassegment*seg1=as1->segmen
ts;structassegment*seg2=as2->segments;structaspath*aspath=NULL;structassegment*a
sset=NULL;structassegment*prevseg=NULL;/*Firstofallcheckcommonleadingsequence.*/
while(seg1&&seg2){/*Checksegmenttype.*/if(seg1->type!=seg2->type)break;/*Minimum
segmentlength.*/minlen=min(seg1->length,seg2->length);for(match=0;match<minlen;m
atch++)if(seg1->as[match]!=seg2->as[match])break;if(match){structassegment*seg=a
ssegment_new(seg1->type,0);seg=assegment_append_asns(seg,seg1->as,match);if(!asp
ath){aspath=aspath_new();aspath->segments=seg;}elseprevseg->next=seg;prevseg=seg
;}if(match!=minlen||match!=seg1->length||seg1->length!=seg2->length)break;/*Wear
emovingontothenextsegmenttoresetmatch*/elsematch=0;seg1=seg1->next;seg2=seg2->ne
xt;}if(!aspath)aspath=aspath_new();/*Makeas-setusingrestofallinformation.*/from=
match;while(seg1){for(i=from;i<seg1->length;i++)asset=aspath_aggregate_as_set_ad
d(aspath,asset,seg1->as[i]);from=0;seg1=seg1->next;}from=match;while(seg2){for(i
=from;i<seg2->length;i++)asset=aspath_aggregate_as_set_add(aspath,asset,seg2->as
[i]);from=0;seg2=seg2->next;}assegment_normalise(aspath->segments);aspath_str_up
date(aspath,false);returnaspath;}/*WhenaBGProuterreceivesanUPDATEwithanMP_REACH_
NLRIattribute,checktheleftmostASnumberintheAS_PATHattributeisornotthepeer'sASnum
ber.*/intaspath_firstas_check(structaspath*aspath,as_tasno){if((aspath==NULL)||(
aspath->segments==NULL))return0;if(aspath->segments&&(aspath->segments->type==AS
_SEQUENCE)&&(aspath->segments->as[0]==asno))return1;return0;}unsignedintaspath_g
et_first_as(structaspath*aspath){if(aspath==NULL||aspath->segments==NULL)return0
;returnaspath->segments->as[0];}unsignedintaspath_get_last_as(structaspath*aspat
h){inti;unsignedintlast_as=0;conststructassegment*seg;if(aspath==NULL||aspath->s
egments==NULL)returnlast_as;seg=aspath->segments;while(seg){if(seg->type==AS_SEQ
UENCE||seg->type==AS_CONFED_SEQUENCE)for(i=0;i<seg->length;i++)last_as=seg->as[i
];seg=seg->next;}returnlast_as;}/*ASpathloopcheck.Ifaspathcontainsasnothenreturn
>=1.*/intaspath_loop_check(structaspath*aspath,as_tasno){structassegment*seg;int
count=0;if((aspath==NULL)||(aspath->segments==NULL))return0;seg=aspath->segments
;while(seg){inti;for(i=0;i<seg->length;i++)if(seg->as[i]==asno)count++;seg=seg->
next;}returncount;}/*WhenallofASpathisprivateASreturn1.*/intaspath_private_as_ch
eck(structaspath*aspath){structassegment*seg;if(!(aspath&&aspath->segments))retu
rn0;seg=aspath->segments;while(seg){inti;for(i=0;i<seg->length;i++){if(!BGP_AS_I
S_PRIVATE(seg->as[i]))return0;}seg=seg->next;}return1;}/*ReturnTrueiftheentireAS
PATHconsistofthespecifiedASN*/intaspath_single_asn_check(structaspath*aspath,as_
tasn){structassegment*seg;if(!(aspath&&aspath->segments))return0;seg=aspath->seg
ments;while(seg){inti;for(i=0;i<seg->length;i++){if(seg->as[i]!=asn)return0;}seg
=seg->next;}return1;}/*ReplaceallinstancesofthetargetASNwithourownASN*/structasp
ath*aspath_replace_specific_asn(structaspath*aspath,as_ttarget_asn,as_tour_asn){
structaspath*new;structassegment*seg;new=aspath_dup(aspath);seg=new->segments;wh
ile(seg){inti;for(i=0;i<seg->length;i++){if(seg->as[i]==target_asn)seg->as[i]=ou
r_asn;}seg=seg->next;}aspath_str_update(new,false);returnnew;}/*Replaceallprivat
eASNswithourownASN*/structaspath*aspath_replace_private_asns(structaspath*aspath
,as_tasn){structaspath*new;structassegment*seg;new=aspath_dup(aspath);seg=new->s
egments;while(seg){inti;for(i=0;i<seg->length;i++){if(BGP_AS_IS_PRIVATE(seg->as[
i]))seg->as[i]=asn;}seg=seg->next;}aspath_str_update(new,false);returnnew;}/*Rem
oveallprivateASNs*/structaspath*aspath_remove_private_asns(structaspath*aspath){
structaspath*new;structassegment*seg;structassegment*new_seg;structassegment*las
t_new_seg;inti;intj;intpublic=0;new=XCALLOC(MTYPE_AS_PATH,sizeof(structaspath));
new->json=NULL;new_seg=NULL;last_new_seg=NULL;seg=aspath->segments;while(seg){pu
blic=0;for(i=0;i<seg->length;i++){//ASNispublicif(!BGP_AS_IS_PRIVATE(seg->as[i])
){public++;}}//Theentiresegmentisprivatesoskipitif(!public){seg=seg->next;contin
ue;}//Theentiresegmentispublicsocopyitelseif(public==seg->length){new_seg=assegm
ent_dup(seg);}//ThesegmentisamixofpublicandprivateASNs.Copyasmany//spotsas//ther
earepublicASNsthencomebackandfillinonlythe//publicASNs.else{new_seg=assegment_ne
w(seg->type,public);j=0;for(i=0;i<seg->length;i++){//ASNispublicif(!BGP_AS_IS_PR
IVATE(seg->as[i])){new_seg->as[j]=seg->as[i];j++;}}}//Thisisthefirstsegmentsoset
theaspathsegmentspointer//tothisoneif(!last_new_seg)new->segments=new_seg;elsela
st_new_seg->next=new_seg;last_new_seg=new_seg;seg=seg->next;}aspath_str_update(n
ew,false);returnnew;}/*ASpathconfedcheck.Ifaspathcontainsconfedsetorsequencethen
return*1.*/intaspath_confed_check(structaspath*aspath){structassegment*seg;if(!(
aspath&&aspath->segments))return0;seg=aspath->segments;while(seg){if(seg->type==
AS_CONFED_SET||seg->type==AS_CONFED_SEQUENCE)return1;seg=seg->next;}return0;}/*L
eftmostASpathsegmentconfedcheck.IfleftmostASsegmentisoftypeAS_CONFED_SEQUENCEorA
S_CONFED_SETthenreturn1.*/intaspath_left_confed_check(structaspath*aspath){if(!(
aspath&&aspath->segments))return0;if((aspath->segments->type==AS_CONFED_SEQUENCE
)||(aspath->segments->type==AS_CONFED_SET))return1;return0;}/*Mergeas1toas2.as2s
houldbeuninternedaspath.*/staticstructaspath*aspath_merge(structaspath*as1,struc
taspath*as2){structassegment*last,*new;if(!as1||!as2)returnNULL;last=new=assegme
nt_dup_all(as1->segments);/*findthelastvalidsegment*/while(last&&last->next)last
=last->next;last->next=as2->segments;as2->segments=new;aspath_str_update(as2,fal
se);returnas2;}/*Prependas1toas2.as2shouldbeuninternedaspath.*/structaspath*aspa
th_prepend(structaspath*as1,structaspath*as2){structassegment*seg1;structassegme
nt*seg2;if(!as1||!as2)returnNULL;seg1=as1->segments;seg2=as2->segments;/*Ifas2is
empty,onlyneedtodupeas1'schainontoas2*/if(seg2==NULL){as2->segments=assegment_du
p_all(as1->segments);aspath_str_update(as2,false);returnas2;}/*Ifas1isemptyAS,no
prependingtodo.*/if(seg1==NULL)returnas2;/*findthetailas1'ssegmentchain.*/while(
seg1&&seg1->next)seg1=seg1->next;/*DeleteanyAS_CONFED_SEQUENCEsegmentfromas2.*/i
f(seg1->type==AS_SEQUENCE&&seg2->type==AS_CONFED_SEQUENCE)as2=aspath_delete_conf
ed_seq(as2);/*Comparelastsegmenttypeofas1andfirstsegmenttypeofas2.*/if(seg1->typ
e!=seg2->type)returnaspath_merge(as1,as2);if(seg1->type==AS_SEQUENCE){/*Wehavetw
ochainsofsegments,as1->segmentsandseg2,*andwehavetoattachthemtogether,mergingthe
attaching*segmentstogetherintoone.**1.dupeas1->segmentsontoheadofas2*2.mergeseg2
'sasnsontolastsegmentofthisnewchain*3.attachchainafterseg2*//*dupeas1ontoas2'she
ad*/seg1=as2->segments=assegment_dup_all(as1->segments);/*refindthetailofas2,reu
singseg1*/while(seg1&&seg1->next)seg1=seg1->next;/*mergetheoldhead,seg2,intotail
,seg1*/seg1=assegment_append_asns(seg1,seg2->as,seg2->length);/*bypassthemergeds
eg2,andattachanychainafteritto*chaindescendingfromas2'shead*/seg1->next=seg2->ne
xt;/*seg2isnowreferencelessanduseless*/assegment_free(seg2);/*we'venowprependeda
s1'ssegmentchaintoas2,merging*theinbetweenAS_SEQUENCEofseg2intheprocess*/aspath_
str_update(as2,false);returnas2;}else{/*AS_SETmergecodeisneededathere.*/returnas
path_merge(as1,as2);}/*XXX:Ermmm,whatifas1hasmultiplesegments??*//*Notreached*/}
/*IterateoverAS_PATHsegmentsandwipealloccurencesofthe*listedASnumbers.Hencesomes
egmentsmaylosesomeoreven*alldataontheway,theoperationisimplementedasasmarter*ver
sionofaspath_dup(),whichallocatesmemorytoholdthenew*data,nottheoriginal.ThenewAS
pathisreturned.*/structaspath*aspath_filter_exclude(structaspath*source,structas
path*exclude_list){structassegment*srcseg,*exclseg,*lastseg;structaspath*newpath
;newpath=aspath_new();lastseg=NULL;for(srcseg=source->segments;srcseg;srcseg=src
seg->next){unsignedi,y,newlen=0,done=0,skip_as;structassegment*newseg;/*Findout,
howmuchASnsarewegoingtopickfromthis*segment.*Wecan'tperformfilteringrightinline,
becausethesizeof*thenewsegmentisn'tknownatthemomentyet.*/for(i=0;i<srcseg->lengt
h;i++){skip_as=0;for(exclseg=exclude_list->segments;exclseg&&!skip_as;exclseg=ex
clseg->next)for(y=0;y<exclseg->length;y++)if(srcseg->as[i]==exclseg->as[y]){skip
_as=1;//There'snosenseintesting//therestofexclusionlist,//bailout.break;}if(!ski
p_as)newlen++;}/*newlenisnowthenumberofASnstocopy*/if(!newlen)continue;/*Actualc
opying.Allocatememoryanditerateoncemore,*performingfiltering.*/newseg=assegment_
new(srcseg->type,newlen);for(i=0;i<srcseg->length;i++){skip_as=0;for(exclseg=exc
lude_list->segments;exclseg&&!skip_as;exclseg=exclseg->next)for(y=0;y<exclseg->l
ength;y++)if(srcseg->as[i]==exclseg->as[y]){skip_as=1;break;}if(skip_as)continue
;newseg->as[done++]=srcseg->as[i];}/*Athispointnewlenmustbeequaltodone,andbothmu
stbe*positive.Append*thefilteredsegmenttothegrossresult.*/if(!lastseg)newpath->s
egments=newseg;elselastseg->next=newseg;lastseg=newseg;}aspath_str_update(newpat
h,false);/*WearehappyreturningevenanemptyAS_PATH,becausethe*administrator*mighte
xpectthisverybehaviour.There'sameantoavoidthis,if*necessary,*byhavingamatchrulea
gainstcertainAS_PATHregexpsinthe*route-mapindex.*/aspath_free(source);returnnewp
ath;}/*AddspecifiedAStotheleftmostofaspath.*/staticstructaspath*aspath_add_asns(
structaspath*aspath,as_tasno,uint8_ttype,unsignednum){structassegment*assegment=
aspath->segments;unsignedi;if(assegment&&assegment->type==type){/*extendexisting
segment*/aspath->segments=assegment_prepend_asns(aspath->segments,asno,num);}els
e{/*prependwithnewsegment*/structassegment*newsegment=assegment_new(type,num);fo
r(i=0;i<num;i++)newsegment->as[i]=asno;/*insertpotentiallyreplacingemptysegment*
/if(assegment&&assegment->length==0){newsegment->next=assegment->next;assegment_
free(assegment);}elsenewsegment->next=assegment;aspath->segments=newsegment;}asp
ath_str_update(aspath,false);returnaspath;}/*AddspecifiedAStotheleftmostofaspath
numtimes.*/structaspath*aspath_add_seq_n(structaspath*aspath,as_tasno,unsignednu
m){returnaspath_add_asns(aspath,asno,AS_SEQUENCE,num);}/*AddspecifiedAStotheleft
mostofaspath.*/structaspath*aspath_add_seq(structaspath*aspath,as_tasno){returna
spath_add_asns(aspath,asno,AS_SEQUENCE,1);}/*CompareleftmostASvalueforMEDcheck.I
fas1'sleftmostASandas2'sleftmostASissamereturn1.*/intaspath_cmp_left(conststruct
aspath*aspath1,conststructaspath*aspath2){conststructassegment*seg1;conststructa
ssegment*seg2;if(!(aspath1&&aspath2))return0;seg1=aspath1->segments;seg2=aspath2
->segments;/*IfbothpathsareoriginatedinthisASthenwedowanttocompare*MED*/if(!seg1
&&!seg2)return1;/*findfirstnon-confedsegmentsforeach*/while(seg1&&((seg1->type==
AS_CONFED_SEQUENCE)||(seg1->type==AS_CONFED_SET)))seg1=seg1->next;while(seg2&&((
seg2->type==AS_CONFED_SEQUENCE)||(seg2->type==AS_CONFED_SET)))seg2=seg2->next;/*
Checkas1's*/if(!(seg1&&seg2&&(seg1->type==AS_SEQUENCE)&&(seg2->type==AS_SEQUENCE
)))return0;if(seg1->as[0]==seg2->as[0])return1;return0;}/*Truncateanaspathaftera
numberofhops,andputthehopsremaining*atthefrontofanotheraspath.NeededforAS4compat
.**Returnedaspathisa/new/aspath,whichshouldeitherbyfree'dor*internedbythecaller,
asdesired.*/structaspath*aspath_reconcile_as4(structaspath*aspath,structaspath*a
s4path){structassegment*seg,*newseg,*prevseg=NULL;structaspath*newpath=NULL,*mer
gedpath;inthops,cpasns=0;if(!aspath)returnNULL;seg=aspath->segments;/*CONFEDssho
uldgetreconciledtoo..*/hops=(aspath_count_hops(aspath)+aspath_count_confeds(aspa
th))-aspath_count_hops(as4path);if(hops<0){if(BGP_DEBUG(as4,AS4))zlog_warn("[AS4
]FewerhopsinAS_PATHthanNEW_AS_PATH");/*Something'sgonewrong.TheRFCsaysweshouldno
wignore*AS4_PATH,*whichisdaftbehaviour-itcontainsvitalloop-detection*information
whichmusthavebeenremovedfromAS_PATH.*/hops=aspath_count_hops(aspath);}if(!hops){
newpath=aspath_dup(as4path);aspath_str_update(newpath,false);returnnewpath;}if(B
GP_DEBUG(as4,AS4))zlog_debug("[AS4]gotAS_PATH%sandAS4_PATH%ssynthesizingnow",asp
ath->str,as4path->str);while(seg&&hops>0){switch(seg->type){caseAS_SET:caseAS_CO
NFED_SET:hops--;cpasns=seg->length;break;caseAS_CONFED_SEQUENCE:/*Shouldneverspl
itaconfed-sequence,ifhop-count*suggestswemustthensomething'sgonewrong*somewhere.
**MostimportantgoalistopreserveAS_PATHsprime*function*asloop-detector,sowefudget
henumberssothatthe*entire*confed-sequenceismergedin.*/if(hops<seg->length){if(BG
P_DEBUG(as4,AS4))zlog_debug("[AS4]AS4PATHmangle:AS_CONFED_SEQUENCEfalls""across2
/4ASNboundarysomewhere,broken..");hops=seg->length;}/*fallthru*/caseAS_SEQUENCE:
cpasns=MIN(seg->length,hops);hops-=seg->length;}assert(cpasns<=seg->length);news
eg=assegment_new(seg->type,0);newseg=assegment_append_asns(newseg,seg->as,cpasns
);if(!newpath){newpath=aspath_new();newpath->segments=newseg;}elseprevseg->next=
newseg;prevseg=newseg;seg=seg->next;}/*Wemaybeabletojoinsomesegmentshere,andwemu
st*dothisbecause...wewantnormalisedaspathsinouthash*andwedonotwanttostumbleinasp
ath_put.*/mergedpath=aspath_merge(newpath,aspath_dup(as4path));aspath_free(newpa
th);mergedpath->segments=assegment_normalise(mergedpath->segments);aspath_str_up
date(mergedpath,false);if(BGP_DEBUG(as4,AS4))zlog_debug("[AS4]resultofsynthesizi
ngis%s",mergedpath->str);returnmergedpath;}/*CompareleftmostASvalueforMEDcheck.I
fas1'sleftmostASandas2'sleftmostASissamereturn1.(confederationas-pathonly).*/int
aspath_cmp_left_confed(conststructaspath*aspath1,conststructaspath*aspath2){if(!
(aspath1&&aspath2))return0;if(!(aspath1->segments&&aspath2->segments))return0;if
((aspath1->segments->type!=AS_CONFED_SEQUENCE)||(aspath2->segments->type!=AS_CON
FED_SEQUENCE))return0;if(aspath1->segments->as[0]==aspath2->segments->as[0])retu
rn1;return0;}/*DeleteallAS_CONFED_SEQUENCE/SETsegmentsfromaspath.*RFC5065section
4.1.c.1**1)ifanypathsegmentsoftheAS_PATHareofthetype*AS_CONFED_SEQUENCEorAS_CONF
ED_SET,thosesegmentsMUSTbe*removedfromtheAS_PATHattribute,leavingthesanitized*AS
_PATHattributetobeoperatedonbysteps2,3or4.*/structaspath*aspath_delete_confed_se
q(structaspath*aspath){structassegment*seg,*prev,*next;charremoved_confed_segmen
t;if(!(aspath&&aspath->segments))returnaspath;seg=aspath->segments;removed_confe
d_segment=0;next=NULL;prev=NULL;while(seg){next=seg->next;if(seg->type==AS_CONFE
D_SEQUENCE||seg->type==AS_CONFED_SET){/*Thisisthefirstsegmentintheaspath*/if(asp
ath->segments==seg)aspath->segments=seg->next;elseprev->next=seg->next;assegment
_free(seg);removed_confed_segment=1;}elseprev=seg;seg=next;}if(removed_confed_se
gment)aspath_str_update(aspath,false);returnaspath;}/*AddnewASnumbertotheleftmos
tpartoftheaspathasAS_CONFED_SEQUENCE.*/structaspath*aspath_add_confed_seq(struct
aspath*aspath,as_tasno){returnaspath_add_asns(aspath,asno,AS_CONFED_SEQUENCE,1);
}/*Addnewasvaluetoaspathstructure.*/staticvoidaspath_as_add(structaspath*as,as_t
asno){structassegment*seg=as->segments;if(!seg)return;/*Lastsegmentsearchprocedu
re.*/while(seg->next)seg=seg->next;assegment_append_asns(seg,&asno,1);}/*Addnewa
ssegmenttotheaspath.*/staticvoidaspath_segment_add(structaspath*as,inttype){stru
ctassegment*seg=as->segments;structassegment*new=assegment_new(type,0);if(seg){w
hile(seg->next)seg=seg->next;seg->next=new;}elseas->segments=new;}structaspath*a
spath_empty(void){returnaspath_parse(NULL,0,1);/*32Bit;-)*/}structaspath*aspath_
empty_get(void){structaspath*aspath;aspath=aspath_new();aspath_make_str_count(as
path,false);returnaspath;}unsignedlongaspath_count(void){returnashash->count;}/*
Theoretically,oneaspathcanhave:OneBGPpacketsizeshouldbelessthan4096.OneBGPattrib
utesizeshouldbelessthan4096-BGPheadersize.OneBGPaspathsizeshouldbelessthan4096-B
GPheadersize-BGPmandantryattributesize.*//*ASpathstringlexicaltokenenum.*/enumas
_token{as_token_asval,as_token_set_start,as_token_set_end,as_token_confed_seq_st
art,as_token_confed_seq_end,as_token_confed_set_start,as_token_confed_set_end,as
_token_unknown};/*Returnnexttokenandpointforstringparse.*/staticconstchar*aspath
_gettoken(constchar*buf,enumas_token*token,unsignedlong*asno){constchar*p=buf;/*
Skipseperators(spaceforsequences,','forsets).*/while(isspace((int)*p)||*p==',')p
++;/*Checktheendofthestringandtypespecifycharacters(e.g.{}()).*/switch(*p){case'
\0':returnNULL;case'{':*token=as_token_set_start;p++;returnp;case'}':*token=as_t
oken_set_end;p++;returnp;case'(':*token=as_token_confed_seq_start;p++;returnp;ca
se')':*token=as_token_confed_seq_end;p++;returnp;case'[':*token=as_token_confed_
set_start;p++;returnp;case']':*token=as_token_confed_set_end;p++;returnp;}/*Chec
kactualASvalue.*/if(isdigit((int)*p)){as_tasval;*token=as_token_asval;asval=(*p-
'0');p++;while(isdigit((int)*p)){asval*=10;asval+=(*p-'0');p++;}*asno=asval;retu
rnp;}/*Thereisnomatchthenreturnunknowntoken.*/*token=as_token_unknown;p++;return
p;}structaspath*aspath_str2aspath(constchar*str){enumas_tokentoken=as_token_unkn
own;unsignedshortas_type;unsignedlongasno=0;structaspath*aspath;intneedtype;aspa
th=aspath_new();/*WestartdefaulttypeasAS_SEQUENCE.*/as_type=AS_SEQUENCE;needtype
=1;while((str=aspath_gettoken(str,&token,&asno))!=NULL){switch(token){caseas_tok
en_asval:if(needtype){aspath_segment_add(aspath,as_type);needtype=0;}aspath_as_a
dd(aspath,asno);break;caseas_token_set_start:as_type=AS_SET;aspath_segment_add(a
spath,as_type);needtype=0;break;caseas_token_set_end:as_type=AS_SEQUENCE;needtyp
e=1;break;caseas_token_confed_seq_start:as_type=AS_CONFED_SEQUENCE;aspath_segmen
t_add(aspath,as_type);needtype=0;break;caseas_token_confed_seq_end:as_type=AS_SE
QUENCE;needtype=1;break;caseas_token_confed_set_start:as_type=AS_CONFED_SET;aspa
th_segment_add(aspath,as_type);needtype=0;break;caseas_token_confed_set_end:as_t
ype=AS_SEQUENCE;needtype=1;break;caseas_token_unknown:default:aspath_free(aspath
);returnNULL;}}aspath_make_str_count(aspath,false);returnaspath;}/*Makehashvalue
byrawaspathdata.*/unsignedintaspath_key_make(void*p){structaspath*aspath=(struct
aspath*)p;unsignedintkey=0;if(!aspath->str)aspath_str_update(aspath,false);key=j
hash(aspath->str,aspath->str_len,2334325);returnkey;}/*Iftwoaspathhavesamevaluet
henreturn1elsereturn0*/intaspath_cmp(constvoid*arg1,constvoid*arg2){conststructa
ssegment*seg1=((conststructaspath*)arg1)->segments;conststructassegment*seg2=((c
onststructaspath*)arg2)->segments;while(seg1||seg2){inti;if((!seg1&&seg2)||(seg1
&&!seg2))return0;if(seg1->type!=seg2->type)return0;if(seg1->length!=seg2->length
)return0;for(i=0;i<seg1->length;i++)if(seg1->as[i]!=seg2->as[i])return0;seg1=seg
1->next;seg2=seg2->next;}return1;}/*ASpathhashinitialize.*/voidaspath_init(void)
{ashash=hash_create_size(32768,aspath_key_make,aspath_cmp,"BGPASPath");}voidaspa
th_finish(void){hash_clean(ashash,(void(*)(void*))aspath_free);hash_free(ashash)
;ashash=NULL;if(snmp_stream)stream_free(snmp_stream);}/*returnandaspathvalue*/co
nstchar*aspath_print(structaspath*as){return(as?as->str:NULL);}/*Printingfunctio
ns*//*FeedtheAS_PATHtothevty;thesuffixstringfollowsitonlyincase*AS_PATHwasn'temp
ty.*/voidaspath_print_vty(structvty*vty,constchar*format,structaspath*as,constch
ar*suffix){assert(format);vty_out(vty,format,as->str);if(as->str_len&&strlen(suf
fix))vty_out(vty,"%s",suffix);}staticvoidaspath_show_all_iterator(structhash_bac
ket*backet,structvty*vty){structaspath*as;as=(structaspath*)backet->data;vty_out
(vty,"[%p:%u](%ld)",(void*)backet,backet->key,as->refcnt);vty_out(vty,"%s\n",as-
>str);}/*Printallaspathandhashinformation.Thisfunctionisusedfrom`show[ip]bgppath
s'command.*/voidaspath_print_all_vty(structvty*vty){hash_iterate(ashash,(void(*)
(structhash_backet*,void*))aspath_show_all_iterator,vty);}