/*ASpathrelateddefinitions.*Copyright(C)1997,98,99KunihiroIshiguro**Thisfileispa
rtofGNUZebra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodifyit*underth
etermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;either
version2,or(atyouroption)any*laterversion.**GNUZebraisdistributedinthehopethatit
willbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABIL
ITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.*
*YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;see
thefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFl
oor,Boston,MA02110-1301USA*/#ifndef_QUAGGA_BGP_ASPATH_H#define_QUAGGA_BGP_ASPATH
_H#include"lib/json.h"/*ASpathsegmenttype.*/#defineAS_SET1#defineAS_SEQUENCE2#de
fineAS_CONFED_SEQUENCE3#defineAS_CONFED_SET4/*PrivateASrangedefinedinRFC2270.*/#
defineBGP_PRIVATE_AS_MIN64512U#defineBGP_PRIVATE_AS_MAX65535U/*Private4byteASran
gedefinedinRFC6996.*/#defineBGP_PRIVATE_AS4_MIN4200000000U#defineBGP_PRIVATE_AS4
_MAX4294967294U/*weleaveBGP_AS_MAXasthe16bitASMAXnumber.*/#defineBGP_AS_MAX65535
U#defineBGP_AS4_MAX4294967295U/*Transition16BitASasdefinedbyIANA*/#defineBGP_AS_
TRANS23456U#defineBGP_AS_IS_PRIVATE(ASN)\(((ASN)>=BGP_PRIVATE_AS_MIN&&(ASN)<=BGP
_PRIVATE_AS_MAX)\||((ASN)>=BGP_PRIVATE_AS4_MIN&&(ASN)<=BGP_PRIVATE_AS4_MAX))/*AS
_PATHsegmentdatainabstractedform,nolimitisplacedonlength*/structassegment{struct
assegment*next;as_t*as;unsignedshortlength;uint8_ttype;};/*ASpathmaybeincludesom
eAsSegments.*/structaspath{/*Referencecounttothisaspath.*/unsignedlongrefcnt;/*s
egmentdata*/structassegment*segments;/*ASpathasajsonobject*/json_object*json;/*S
tringexpressionofASpath.ThisstringisusedbyvtyoutputandASpathregularexpressionmat
ch.*/char*str;unsignedshortstr_len;};#defineASPATH_STR_DEFAULT_LEN32/*Prototypes
.*/externvoidaspath_init(void);externvoidaspath_finish(void);externstructaspath*
aspath_parse(structstream*,size_t,int);externstructaspath*aspath_dup(structaspat
h*);externstructaspath*aspath_aggregate(structaspath*,structaspath*);externstruc
taspath*aspath_prepend(structaspath*,structaspath*);externstructaspath*aspath_fi
lter_exclude(structaspath*,structaspath*);externstructaspath*aspath_add_seq_n(st
ructaspath*,as_t,unsigned);externstructaspath*aspath_add_seq(structaspath*,as_t)
;externstructaspath*aspath_add_confed_seq(structaspath*,as_t);externintaspath_cm
p(constvoid*,constvoid*);externintaspath_cmp_left(conststructaspath*,conststruct
aspath*);externintaspath_cmp_left_confed(conststructaspath*,conststructaspath*);
externstructaspath*aspath_delete_confed_seq(structaspath*);externstructaspath*as
path_empty(void);externstructaspath*aspath_empty_get(void);externstructaspath*as
path_str2aspath(constchar*);externvoidaspath_str_update(structaspath*as,boolmake
_json);externvoidaspath_free(structaspath*);externstructaspath*aspath_intern(str
uctaspath*);externvoidaspath_unintern(structaspath**);externconstchar*aspath_pri
nt(structaspath*);externvoidaspath_print_vty(structvty*,constchar*,structaspath*
,constchar*);externvoidaspath_print_all_vty(structvty*);externunsignedintaspath_
key_make(void*);externunsignedintaspath_get_first_as(structaspath*);externunsign
edintaspath_get_last_as(structaspath*);externintaspath_loop_check(structaspath*,
as_t);externintaspath_private_as_check(structaspath*);externintaspath_single_asn
_check(structaspath*,as_tasn);externstructaspath*aspath_replace_specific_asn(str
uctaspath*aspath,as_ttarget_asn,as_tour_asn);externstructaspath*aspath_replace_p
rivate_asns(structaspath*aspath,as_tasn);externstructaspath*aspath_remove_privat
e_asns(structaspath*aspath);externintaspath_firstas_check(structaspath*,as_t);ex
ternintaspath_confed_check(structaspath*);externintaspath_left_confed_check(stru
ctaspath*);externunsignedlongaspath_count(void);externunsignedintaspath_count_ho
ps(conststructaspath*);externunsignedintaspath_count_confeds(structaspath*);exte
rnunsignedintaspath_size(structaspath*);externas_taspath_highest(structaspath*);
externas_taspath_leftmost(structaspath*);externsize_taspath_put(structstream*,st
ructaspath*,int);externstructaspath*aspath_reconcile_as4(structaspath*,structasp
ath*);externunsignedintaspath_has_as4(structaspath*);/*ForSNMPBGP4PATHATTRASPATH
SEGMENT,mightbeusefulfordebug*/externuint8_t*aspath_snmp_pathseg(structaspath*,s
ize_t*);#endif/*_QUAGGA_BGP_ASPATH_H*/