/*BGPLargeCommunitiesAttribute**Copyright(C)2016KeyurPatel<keyur@arrcus.com>**Th
isfileispartofFreeRangeRouting(FRR).**FRRisfreesoftware;youcanredistributeitand/
ormodifyitunderthe*termsoftheGNUGeneralPublicLicenseaspublishedbytheFreeSoftware
*Foundation;eitherversion2,or(atyouroption)anylaterversion.**FRRisdistributedint
hehopethatitwillbeuseful,butWITHOUTANY*WARRANTY;withouteventheimpliedwarrantyofM
ERCHANTABILITYorFITNESS*FORAPARTICULARPURPOSE.SeetheGNUGeneralPublicLicenseformo
re*details.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthi
sprogram;seethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51Frankl
inSt,FifthFloor,Boston,MA02110-1301USA*/#include<zebra.h>#include"hash.h"#includ
e"memory.h"#include"prefix.h"#include"command.h"#include"filter.h"#include"jhash
.h"#include"stream.h"#include"bgpd/bgpd.h"#include"bgpd/bgp_lcommunity.h"#includ
e"bgpd/bgp_aspath.h"/*Hashofcommunityattribute.*/staticstructhash*lcomhash;/*All
ocateanewlcommunities.*/staticstructlcommunity*lcommunity_new(void){return(struc
tlcommunity*)XCALLOC(MTYPE_LCOMMUNITY,sizeof(structlcommunity));}/*Allocatelcomm
unities.*/voidlcommunity_free(structlcommunity**lcom){if((*lcom)->val)XFREE(MTYP
E_LCOMMUNITY_VAL,(*lcom)->val);if((*lcom)->str)XFREE(MTYPE_LCOMMUNITY_STR,(*lcom
)->str);XFREE(MTYPE_LCOMMUNITY,*lcom);lcom=NULL;}staticvoidlcommunity_hash_free(
structlcommunity*lcom){lcommunity_free(&lcom);}/*AddanewLargeCommunitiesvaluetoL
argeCommunitiesAttributestructure.Whenthevalueisalreadyexistsinthestructure,wedo
n'taddthevalue.Newlyaddedvalueissortedbynumericalorder.Whenthevalueisaddedtothes
tructurereturn1elsereturn0.*/staticintlcommunity_add_val(structlcommunity*lcom,s
tructlcommunity_val*lval){uint8_t*p;intret;intc;/*Whenthisisfistvalue,justaddit.
*/if(lcom->val==NULL){lcom->size++;lcom->val=XMALLOC(MTYPE_LCOMMUNITY_VAL,lcom_l
ength(lcom));memcpy(lcom->val,lval->val,LCOMMUNITY_SIZE);return1;}/*Ifthevalueal
readyexistsinthestructurereturn0.*/c=0;for(p=lcom->val;c<lcom->size;p+=LCOMMUNIT
Y_SIZE,c++){ret=memcmp(p,lval->val,LCOMMUNITY_SIZE);if(ret==0)return0;if(ret>0)b
reak;}/*Addthevaluetothestructurewithnumericalsorting.*/lcom->size++;lcom->val=X
REALLOC(MTYPE_LCOMMUNITY_VAL,lcom->val,lcom_length(lcom));memmove(lcom->val+(c+1
)*LCOMMUNITY_SIZE,lcom->val+c*LCOMMUNITY_SIZE,(lcom->size-1-c)*LCOMMUNITY_SIZE);
memcpy(lcom->val+c*LCOMMUNITY_SIZE,lval->val,LCOMMUNITY_SIZE);return1;}/*Thisfun
ctiontakespointertoLargeCommunitesstrucutrethencreateanewLargeCommunitiesstructu
rebyuniqandsorteachLargeCommunitiesvalue.*/structlcommunity*lcommunity_uniq_sort
(structlcommunity*lcom){inti;structlcommunity*new;structlcommunity_val*lval;if(!
lcom)returnNULL;new=lcommunity_new();for(i=0;i<lcom->size;i++){lval=(structlcomm
unity_val*)(lcom->val+(i*LCOMMUNITY_SIZE));lcommunity_add_val(new,lval);}returnn
ew;}/*ParseLargeCommunitesAttributeinBGPpacket.*/structlcommunity*lcommunity_par
se(uint8_t*pnt,unsignedshortlength){structlcommunitytmp;structlcommunity*new;/*L
engthcheck.*/if(length%LCOMMUNITY_SIZE)returnNULL;/*Preparetmporarystructureform
akinganewLargeCommunitiesAttribute.*/tmp.size=length/LCOMMUNITY_SIZE;tmp.val=pnt
;/*CreateanewLargeCommunitiesAttributebyuniqandsorteachLargeCommunitiesvalue*/ne
w=lcommunity_uniq_sort(&tmp);returnlcommunity_intern(new);}/*DuplicatetheLargeCo
mmunitiesAttributestructure.*/structlcommunity*lcommunity_dup(structlcommunity*l
com){structlcommunity*new;new=lcommunity_new();new->size=lcom->size;if(new->size
){new->val=XMALLOC(MTYPE_LCOMMUNITY_VAL,lcom_length(lcom));memcpy(new->val,lcom-
>val,lcom_length(lcom));}elsenew->val=NULL;returnnew;}/*Retrunstringrepresentati
onofcommunitiesattribute.*/char*lcommunity_str(structlcommunity*lcom){if(!lcom->
str)lcom->str=lcommunity_lcom2str(lcom,LCOMMUNITY_FORMAT_DISPLAY);returnlcom->st
r;}/*MergetwoLargeCommunitiesAttributestructure.*/structlcommunity*lcommunity_me
rge(structlcommunity*lcom1,structlcommunity*lcom2){if(lcom1->val)lcom1->val=XREA
LLOC(MTYPE_LCOMMUNITY_VAL,lcom1->val,lcom_length(lcom1)+lcom_length(lcom2));else
lcom1->val=XMALLOC(MTYPE_LCOMMUNITY_VAL,lcom_length(lcom1)+lcom_length(lcom2));m
emcpy(lcom1->val+lcom_length(lcom1),lcom2->val,lcom_length(lcom2));lcom1->size+=
lcom2->size;returnlcom1;}/*InternLargeCommunitiesAttribute.*/structlcommunity*lc
ommunity_intern(structlcommunity*lcom){structlcommunity*find;assert(lcom->refcnt
==0);find=(structlcommunity*)hash_get(lcomhash,lcom,hash_alloc_intern);if(find!=
lcom)lcommunity_free(&lcom);find->refcnt++;if(!find->str)find->str=lcommunity_lc
om2str(find,LCOMMUNITY_FORMAT_DISPLAY);returnfind;}/*UninternLargeCommunitiesAtt
ribute.*/voidlcommunity_unintern(structlcommunity**lcom){structlcommunity*ret;if
((*lcom)->refcnt)(*lcom)->refcnt--;/*Pullofffromhash.*/if((*lcom)->refcnt==0){/*
Largecommunitymustbeinthehash.*/ret=(structlcommunity*)hash_release(lcomhash,*lc
om);assert(ret!=NULL);lcommunity_free(lcom);}}/*Utilityfunctiontomakehashkey.*/u
nsignedintlcommunity_hash_make(void*arg){conststructlcommunity*lcom=arg;intsize=
lcom_length(lcom);returnjhash(lcom->val,size,0xab125423);}/*ComparetwoLargeCommu
nitiesAttributestructure.*/intlcommunity_cmp(constvoid*arg1,constvoid*arg2){cons
tstructlcommunity*lcom1=arg1;conststructlcommunity*lcom2=arg2;return(lcom1->size
==lcom2->size&&memcmp(lcom1->val,lcom2->val,lcom_length(lcom1))==0);}/*Returncom
munitieshash.*/structhash*lcommunity_hash(void){returnlcomhash;}/*InitializeLarg
eComminitiesrelatedhash.*/voidlcommunity_init(void){lcomhash=hash_create(lcommun
ity_hash_make,lcommunity_cmp,"BGPlcommunityhash");}voidlcommunity_finish(void){h
ash_clean(lcomhash,(void(*)(void*))lcommunity_hash_free);hash_free(lcomhash);lco
mhash=NULL;}/*LargeCommunitiestokenenum.*/enumlcommunity_token{lcommunity_token_
unknown=0,lcommunity_token_val,};/*GetnextLargeCommunitiestokenfromthestring.*/s
taticconstchar*lcommunity_gettoken(constchar*str,structlcommunity_val*lval,enuml
community_token*token){constchar*p=str;/*Skipwhitespace.*/while(isspace((int)*p)
){p++;str++;}/*Checktheendoftheline.*/if(*p=='\0')returnNULL;/*Communityvalue.*/
if(isdigit((int)*p)){intseparator=0;intdigit=0;uint32_tglobaladmin=0;uint32_tloc
aldata1=0;uint32_tlocaldata2=0;while(isdigit((int)*p)||*p==':'){if(*p==':'){if(s
eparator==2){*token=lcommunity_token_unknown;returnNULL;}else{separator++;digit=
0;if(separator==1){globaladmin=localdata2;}else{localdata1=localdata2;}localdata
2=0;}}else{digit=1;localdata2*=10;localdata2+=(*p-'0');}p++;}if(!digit){*token=l
community_token_unknown;returnNULL;}/**Copythelargecomm.*/lval->val[0]=(globalad
min>>24)&0xff;lval->val[1]=(globaladmin>>16)&0xff;lval->val[2]=(globaladmin>>8)&
0xff;lval->val[3]=globaladmin&0xff;lval->val[4]=(localdata1>>24)&0xff;lval->val[
5]=(localdata1>>16)&0xff;lval->val[6]=(localdata1>>8)&0xff;lval->val[7]=localdat
a1&0xff;lval->val[8]=(localdata2>>24)&0xff;lval->val[9]=(localdata2>>16)&0xff;lv
al->val[10]=(localdata2>>8)&0xff;lval->val[11]=localdata2&0xff;*token=lcommunity
_token_val;returnp;}*token=lcommunity_token_unknown;returnp;}/*Convertstringtola
rgecommunityattribute.Whentypeisalreadyknown,pleasespecifybothstrandtype.Whenstr
ingincludeskeywordforeachlargecommunityvalue.Pleasespecifykeyword_includedasnon-
zerovalue.*/structlcommunity*lcommunity_str2com(constchar*str){structlcommunity*
lcom=NULL;enumlcommunity_tokentoken=lcommunity_token_unknown;structlcommunity_va
llval;while((str=lcommunity_gettoken(str,&lval,&token))){switch(token){caselcomm
unity_token_val:if(lcom==NULL)lcom=lcommunity_new();lcommunity_add_val(lcom,&lva
l);break;caselcommunity_token_unknown:default:if(lcom)lcommunity_free(&lcom);ret
urnNULL;}}returnlcom;}intlcommunity_include(structlcommunity*lcom,uint8_t*ptr){i
nti;uint8_t*lcom_ptr;for(i=0;i<lcom->size;i++){lcom_ptr=lcom->val+(i*LCOMMUNITY_
SIZE);if(memcmp(ptr,lcom_ptr,LCOMMUNITY_SIZE)==0)return1;}return0;}/*Convertlarg
ecommunityattributetostring.Thelargecomswillbein65535:65531:0format.*/char*lcomm
unity_lcom2str(structlcommunity*lcom,intformat){inti;uint8_t*pnt;#defineLCOMMUNI
TY_STR_DEFAULT_LEN40intstr_size;intstr_pnt;char*str_buf;intlen=0;intfirst=1;uint
32_tglobaladmin,localdata1,localdata2;if(lcom->size==0){str_buf=XMALLOC(MTYPE_LC
OMMUNITY_STR,1);str_buf[0]='\0';returnstr_buf;}/*Preparebuffer.*/str_buf=XMALLOC
(MTYPE_LCOMMUNITY_STR,LCOMMUNITY_STR_DEFAULT_LEN+1);str_size=LCOMMUNITY_STR_DEFA
ULT_LEN+1;str_pnt=0;for(i=0;i<lcom->size;i++){/*Makeitsuresizeisenough.*/while(s
tr_pnt+LCOMMUNITY_STR_DEFAULT_LEN>=str_size){str_size*=2;str_buf=XREALLOC(MTYPE_
LCOMMUNITY_STR,str_buf,str_size);}/*Spacebetweeneachvalue.*/if(!first)str_buf[st
r_pnt++]='';pnt=lcom->val+(i*LCOMMUNITY_SIZE);pnt=ptr_get_be32(pnt,&globaladmin)
;pnt=ptr_get_be32(pnt,&localdata1);pnt=ptr_get_be32(pnt,&localdata2);(void)pnt;/
*consumevalue*/len=sprintf(str_buf+str_pnt,"%u:%u:%u",globaladmin,localdata1,loc
aldata2);str_pnt+=len;first=0;}returnstr_buf;}intlcommunity_match(conststructlco
mmunity*lcom1,conststructlcommunity*lcom2){inti=0;intj=0;if(lcom1==NULL&&lcom2==
NULL)return1;if(lcom1==NULL||lcom2==NULL)return0;if(lcom1->size<lcom2->size)retu
rn0;/*Everycommunityoncom2needstobeoncom1forthistomatch*/while(i<lcom1->size&&j<
lcom2->size){if(memcmp(lcom1->val+(i*LCOMMUNITY_SIZE),lcom2->val+(j*LCOMMUNITY_S
IZE),LCOMMUNITY_SIZE)==0)j++;i++;}if(j==lcom2->size)return1;elsereturn0;}/*Delet
eonelcommunity.*/voidlcommunity_del_val(structlcommunity*lcom,uint8_t*ptr){inti=
0;intc=0;if(!lcom->val)return;while(i<lcom->size){if(memcmp(lcom->val+i*LCOMMUNI
TY_SIZE,ptr,LCOMMUNITY_SIZE)==0){c=lcom->size-i-1;if(c>0)memmove(lcom->val+i*LCO
MMUNITY_SIZE,lcom->val+(i+1)*LCOMMUNITY_SIZE,c*LCOMMUNITY_SIZE);lcom->size--;if(
lcom->size>0)lcom->val=XREALLOC(MTYPE_LCOMMUNITY_VAL,lcom->val,lcom_length(lcom)
);else{XFREE(MTYPE_LCOMMUNITY_VAL,lcom->val);lcom->val=NULL;}return;}i++;}}