/*BGPflapdampening*Copyright(C)2001IPInfusionInc.**ThisfileispartofGNUZebra.**GN
UZebraisfreesoftware;youcanredistributeitand/ormodifyit*underthetermsoftheGNUGen
eralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eitherversion2,or(atyou
roption)any*laterversion.**GNUZebraisdistributedinthehopethatitwillbeuseful,but*
WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAP
ARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldhaverec
eivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;if
not,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA0211
0-1301USA*/#include<zebra.h>#include<math.h>#include"prefix.h"#include"memory.h"
#include"command.h"#include"log.h"#include"thread.h"#include"queue.h"#include"fi
lter.h"#include"bgpd/bgpd.h"#include"bgpd/bgp_damp.h"#include"bgpd/bgp_table.h"#
include"bgpd/bgp_route.h"#include"bgpd/bgp_attr.h"#include"bgpd/bgp_advertise.h"
/*Globalvariabletoaccessdampingconfiguration*/structbgp_damp_configbgp_damp_cfg;
staticstructbgp_damp_config*damp=&bgp_damp_cfg;/*UtilitymacrotoaddanddeleteBGPda
mpeninginformationtonousedlist.*/#defineBGP_DAMP_LIST_ADD(N,A)BGP_INFO_ADD(N,A,n
o_reuse_list)#defineBGP_DAMP_LIST_DEL(N,A)BGP_INFO_DEL(N,A,no_reuse_list)/*Calcu
latereuselistindexbypenaltyvalue.*/staticintbgp_reuse_index(intpenalty){unsigned
inti;intindex;i=(int)(((double)penalty/damp->reuse_limit-1.0)*damp->scale_factor
);if(i>=damp->reuse_index_size)i=damp->reuse_index_size-1;index=damp->reuse_inde
x[i]-damp->reuse_index[0];return(damp->reuse_offset+index)%damp->reuse_list_size
;}/*AddBGPdampeninginformationtoreuselist.*/staticvoidbgp_reuse_list_add(structb
gp_damp_info*bdi){intindex;index=bdi->index=bgp_reuse_index(bdi->penalty);bdi->p
rev=NULL;bdi->next=damp->reuse_list[index];if(damp->reuse_list[index])damp->reus
e_list[index]->prev=bdi;damp->reuse_list[index]=bdi;}/*DeleteBGPdampeninginforma
tionfromreuselist.*/staticvoidbgp_reuse_list_delete(structbgp_damp_info*bdi){if(
bdi->next)bdi->next->prev=bdi->prev;if(bdi->prev)bdi->prev->next=bdi->next;elsed
amp->reuse_list[bdi->index]=bdi->next;}/*Returndecayedpenaltyvalue.*/intbgp_damp
_decay(time_ttdiff,intpenalty){unsignedinti;i=(int)((double)tdiff/DELTA_T);if(i=
=0)returnpenalty;if(i>=damp->decay_array_size)return0;return(int)(penalty*damp->
decay_array[i]);}/*Handlerofreusetimerevent.Eachrouteinthecurrentreuse-listiseva
luated.RFC2439Section4.8.7.*/staticintbgp_reuse_timer(structthread*t){structbgp_
damp_info*bdi;structbgp_damp_info*next;time_tt_now,t_diff;damp->t_reuse=NULL;thr
ead_add_timer(bm->master,bgp_reuse_timer,NULL,DELTA_REUSE,&damp->t_reuse);t_now=
bgp_clock();/*1.saveapointertothecurrentzerothqueueheadandzerothelistheadentry.*
/bdi=damp->reuse_list[damp->reuse_offset];damp->reuse_list[damp->reuse_offset]=N
ULL;/*2.setoffset=moduloreuse-list-size(offset+1),therebyrotatingthecircularqueu
eoflist-heads.*/damp->reuse_offset=(damp->reuse_offset+1)%damp->reuse_list_size;
/*3.if(thesavedlistheadpointerisnon-empty)*/for(;bdi;bdi=next){structbgp*bgp=bdi
->binfo->peer->bgp;next=bdi->next;/*Sett-diff=t-now-t-updated.*/t_diff=t_now-bdi
->t_updated;/*Setfigure-of-merit=figure-of-merit*decay-array-ok*[t-diff]*/bdi->p
enalty=bgp_damp_decay(t_diff,bdi->penalty);/*Sett-updated=t-now.*/bdi->t_updated
=t_now;/*if(figure-of-merit<reuse).*/if(bdi->penalty<damp->reuse_limit){/*Reuset
heroute.*/bgp_info_unset_flag(bdi->rn,bdi->binfo,BGP_INFO_DAMPED);bdi->suppress_
time=0;if(bdi->lastrecord==BGP_RECORD_UPDATE){bgp_info_unset_flag(bdi->rn,bdi->b
info,BGP_INFO_HISTORY);bgp_aggregate_increment(bgp,&bdi->rn->p,bdi->binfo,bdi->a
fi,bdi->safi);bgp_process(bgp,bdi->rn,bdi->afi,bdi->safi);}if(bdi->penalty<=damp
->reuse_limit/2.0)bgp_damp_info_free(bdi,1);elseBGP_DAMP_LIST_ADD(damp,bdi);}els
e/*Re-insertintoanotherlist(SeeRFC2439Section*4.8.6).*/bgp_reuse_list_add(bdi);}
return0;}/*Aroutebecomesunreachable(RFC2439Section4.8.2).*/intbgp_damp_withdraw(
structbgp_info*binfo,structbgp_node*rn,afi_tafi,safi_tsafi,intattr_change){time_
tt_now;structbgp_damp_info*bdi=NULL;doublelast_penalty=0;t_now=bgp_clock();/*Pro
cessingUnreachableMessages.*/if(binfo->extra)bdi=binfo->extra->damp_info;if(bdi=
=NULL){/*Ifthereisnopreviousstabilityhistory.*//*RFC2439said:1.allocateadampings
tructure.2.setfigure-of-merit=1.3.withdrawtheroute.*/bdi=XCALLOC(MTYPE_BGP_DAMP_
INFO,sizeof(structbgp_damp_info));bdi->binfo=binfo;bdi->rn=rn;bdi->penalty=(attr
_change?DEFAULT_PENALTY/2:DEFAULT_PENALTY);bdi->flap=1;bdi->start_time=t_now;bdi
->suppress_time=0;bdi->index=-1;bdi->afi=afi;bdi->safi=safi;(bgp_info_extra_get(
binfo))->damp_info=bdi;BGP_DAMP_LIST_ADD(damp,bdi);}else{last_penalty=bdi->penal
ty;/*1.Sett-diff=t-now-t-updated.*/bdi->penalty=(bgp_damp_decay(t_now-bdi->t_upd
ated,bdi->penalty)+(attr_change?DEFAULT_PENALTY/2:DEFAULT_PENALTY));if(bdi->pena
lty>damp->ceiling)bdi->penalty=damp->ceiling;bdi->flap++;}assert((rn==bdi->rn)&&
(binfo==bdi->binfo));bdi->lastrecord=BGP_RECORD_WITHDRAW;bdi->t_updated=t_now;/*
Makethisrouteashistoricalstatus.*/bgp_info_set_flag(rn,binfo,BGP_INFO_HISTORY);/
*Removetheroutefromareuselistifitisonone.*/if(CHECK_FLAG(bdi->binfo->flags,BGP_I
NFO_DAMPED)){/*Ifdecayrateisn'tequalto0,reinsertbrn.*/if(bdi->penalty!=last_pena
lty){bgp_reuse_list_delete(bdi);bgp_reuse_list_add(bdi);}returnBGP_DAMP_SUPPRESS
ED;}/*Ifnotsuppressedbefore,doannonuncethiswithdrawandinsertintoreuse_list.*/if(
bdi->penalty>=damp->suppress_value){bgp_info_set_flag(rn,binfo,BGP_INFO_DAMPED);
bdi->suppress_time=t_now;BGP_DAMP_LIST_DEL(damp,bdi);bgp_reuse_list_add(bdi);}re
turnBGP_DAMP_USED;}intbgp_damp_update(structbgp_info*binfo,structbgp_node*rn,afi
_tafi,safi_tsafi){time_tt_now;structbgp_damp_info*bdi;intstatus;if(!binfo->extra
||!((bdi=binfo->extra->damp_info)))returnBGP_DAMP_USED;t_now=bgp_clock();bgp_inf
o_unset_flag(rn,binfo,BGP_INFO_HISTORY);bdi->lastrecord=BGP_RECORD_UPDATE;bdi->p
enalty=bgp_damp_decay(t_now-bdi->t_updated,bdi->penalty);if(!CHECK_FLAG(bdi->bin
fo->flags,BGP_INFO_DAMPED)&&(bdi->penalty<damp->suppress_value))status=BGP_DAMP_
USED;elseif(CHECK_FLAG(bdi->binfo->flags,BGP_INFO_DAMPED)&&(bdi->penalty<damp->r
euse_limit)){bgp_info_unset_flag(rn,binfo,BGP_INFO_DAMPED);bgp_reuse_list_delete
(bdi);BGP_DAMP_LIST_ADD(damp,bdi);bdi->suppress_time=0;status=BGP_DAMP_USED;}els
estatus=BGP_DAMP_SUPPRESSED;if(bdi->penalty>damp->reuse_limit/2.0)bdi->t_updated
=t_now;elsebgp_damp_info_free(bdi,0);returnstatus;}/*Removedampeninginformationa
ndhistoryroute.*/intbgp_damp_scan(structbgp_info*binfo,afi_tafi,safi_tsafi){time
_tt_now,t_diff;structbgp_damp_info*bdi;assert(binfo->extra&&binfo->extra->damp_i
nfo);t_now=bgp_clock();bdi=binfo->extra->damp_info;if(CHECK_FLAG(binfo->flags,BG
P_INFO_DAMPED)){t_diff=t_now-bdi->suppress_time;if(t_diff>=damp->max_suppress_ti
me){bgp_info_unset_flag(bdi->rn,binfo,BGP_INFO_DAMPED);bgp_reuse_list_delete(bdi
);BGP_DAMP_LIST_ADD(damp,bdi);bdi->penalty=damp->reuse_limit;bdi->suppress_time=
0;bdi->t_updated=t_now;/*NeedtoannounceUPDATEoncethisbinfoisusable*again.*/if(bd
i->lastrecord==BGP_RECORD_UPDATE)return1;elsereturn0;}}else{t_diff=t_now-bdi->t_
updated;bdi->penalty=bgp_damp_decay(t_diff,bdi->penalty);if(bdi->penalty<=damp->
reuse_limit/2.0){/*releasethebdi,bdi->binfo.*/bgp_damp_info_free(bdi,1);return0;
}elsebdi->t_updated=t_now;}return0;}voidbgp_damp_info_free(structbgp_damp_info*b
di,intwithdraw){structbgp_info*binfo;if(!bdi)return;binfo=bdi->binfo;binfo->extr
a->damp_info=NULL;if(CHECK_FLAG(binfo->flags,BGP_INFO_DAMPED))bgp_reuse_list_del
ete(bdi);elseBGP_DAMP_LIST_DEL(damp,bdi);bgp_info_unset_flag(bdi->rn,binfo,BGP_I
NFO_HISTORY|BGP_INFO_DAMPED);if(bdi->lastrecord==BGP_RECORD_WITHDRAW&&withdraw)b
gp_info_delete(bdi->rn,binfo);XFREE(MTYPE_BGP_DAMP_INFO,bdi);}staticvoidbgp_damp
_parameter_set(inthlife,intreuse,intsup,intmaxsup){doublereuse_max_ratio;unsigne
dinti;doublej;damp->suppress_value=sup;damp->half_life=hlife;damp->reuse_limit=r
euse;damp->max_suppress_time=maxsup;/*Initializeparamsperbgp_damp_config.*/damp-
>reuse_index_size=REUSE_ARRAY_SIZE;damp->ceiling=(int)(damp->reuse_limit*(pow(2,
(double)damp->max_suppress_time/damp->half_life)));/*Decay-arraycomputations*/da
mp->decay_array_size=ceil((double)damp->max_suppress_time/DELTA_T);damp->decay_a
rray=XMALLOC(MTYPE_BGP_DAMP_ARRAY,sizeof(double)*(damp->decay_array_size));damp-
>decay_array[0]=1.0;damp->decay_array[1]=exp((1.0/((double)damp->half_life/DELTA
_T))*log(0.5));/*Calculatedecayvaluesforallpossibletimes*/for(i=2;i<damp->decay_
array_size;i++)damp->decay_array[i]=damp->decay_array[i-1]*damp->decay_array[1];
/*Reuse-listcomputations*/i=ceil((double)damp->max_suppress_time/DELTA_REUSE)+1;
if(i>REUSE_LIST_SIZE||i==0)i=REUSE_LIST_SIZE;damp->reuse_list_size=i;damp->reuse
_list=XCALLOC(MTYPE_BGP_DAMP_ARRAY,damp->reuse_list_size*sizeof(structbgp_reuse_
node*));/*Reuse-arraycomputations*/damp->reuse_index=XCALLOC(MTYPE_BGP_DAMP_ARRA
Y,sizeof(int)*damp->reuse_index_size);reuse_max_ratio=(double)damp->ceiling/damp
->reuse_limit;j=(exp((double)damp->max_suppress_time/damp->half_life)*log10(2.0)
);if(reuse_max_ratio>j&&j!=0)reuse_max_ratio=j;damp->scale_factor=(double)damp->
reuse_index_size/(reuse_max_ratio-1);for(i=0;i<damp->reuse_index_size;i++){damp-
>reuse_index[i]=(int)(((double)damp->half_life/DELTA_REUSE)*log10(1.0/(damp->reu
se_limit*(1.0+((double)i/damp->scale_factor))))/log10(0.5));}}intbgp_damp_enable
(structbgp*bgp,afi_tafi,safi_tsafi,time_thalf,unsignedintreuse,unsignedintsuppre
ss,time_tmax){if(CHECK_FLAG(bgp->af_flags[afi][safi],BGP_CONFIG_DAMPENING)){if(d
amp->half_life==half&&damp->reuse_limit==reuse&&damp->suppress_value==suppress&&
damp->max_suppress_time==max)return0;bgp_damp_disable(bgp,afi,safi);}SET_FLAG(bg
p->af_flags[afi][safi],BGP_CONFIG_DAMPENING);bgp_damp_parameter_set(half,reuse,s
uppress,max);/*Registerreusetimer.*/thread_add_timer(bm->master,bgp_reuse_timer,
NULL,DELTA_REUSE,&damp->t_reuse);return0;}staticvoidbgp_damp_config_clean(struct
bgp_damp_config*damp){/*Freedecayarray*/XFREE(MTYPE_BGP_DAMP_ARRAY,damp->decay_a
rray);/*Freereuseindexarray*/XFREE(MTYPE_BGP_DAMP_ARRAY,damp->reuse_index);/*Fre
ereuselistarray.*/XFREE(MTYPE_BGP_DAMP_ARRAY,damp->reuse_list);}/*Cleanallthebgp
_damp_infostoredinreuse_list.*/voidbgp_damp_info_clean(void){unsignedinti;struct
bgp_damp_info*bdi,*next;damp->reuse_offset=0;for(i=0;i<damp->reuse_list_size;i++
){if(!damp->reuse_list[i])continue;for(bdi=damp->reuse_list[i];bdi;bdi=next){nex
t=bdi->next;bgp_damp_info_free(bdi,1);}damp->reuse_list[i]=NULL;}for(bdi=damp->n
o_reuse_list;bdi;bdi=next){next=bdi->next;bgp_damp_info_free(bdi,1);}damp->no_re
use_list=NULL;}intbgp_damp_disable(structbgp*bgp,afi_tafi,safi_tsafi){/*Ifitwasn
'tenabled,there'snothingtodo.*/if(!CHECK_FLAG(bgp->af_flags[afi][safi],BGP_CONFI
G_DAMPENING))return0;/*Cancelreusethread.*/if(damp->t_reuse)thread_cancel(damp->
t_reuse);damp->t_reuse=NULL;/*CleanBGPdampeninginformation.*/bgp_damp_info_clean
();/*Clearconfiguration*/bgp_damp_config_clean(&bgp_damp_cfg);UNSET_FLAG(bgp->af
_flags[afi][safi],BGP_CONFIG_DAMPENING);return0;}voidbgp_config_write_damp(struc
tvty*vty){if(bgp_damp_cfg.half_life==DEFAULT_HALF_LIFE*60&&bgp_damp_cfg.reuse_li
mit==DEFAULT_REUSE&&bgp_damp_cfg.suppress_value==DEFAULT_SUPPRESS&&bgp_damp_cfg.
max_suppress_time==bgp_damp_cfg.half_life*4)vty_out(vty,"bgpdampening\n");elseif
(bgp_damp_cfg.half_life!=DEFAULT_HALF_LIFE*60&&bgp_damp_cfg.reuse_limit==DEFAULT
_REUSE&&bgp_damp_cfg.suppress_value==DEFAULT_SUPPRESS&&bgp_damp_cfg.max_suppress
_time==bgp_damp_cfg.half_life*4)vty_out(vty,"bgpdampening%lld\n",bgp_damp_cfg.ha
lf_life/60LL);elsevty_out(vty,"bgpdampening%lld%d%d%lld\n",bgp_damp_cfg.half_lif
e/60LL,bgp_damp_cfg.reuse_limit,bgp_damp_cfg.suppress_value,bgp_damp_cfg.max_sup
press_time/60LL);}staticconstchar*bgp_get_reuse_time(unsignedintpenalty,char*buf
,size_tlen,uint8_tuse_json,json_object*json){time_treuse_time=0;structtm*tm=NULL
;inttime_store=0;if(penalty>damp->reuse_limit){reuse_time=(int)(DELTA_T*((log((d
ouble)damp->reuse_limit/penalty))/(log(damp->decay_array[1]))));if(reuse_time>da
mp->max_suppress_time)reuse_time=damp->max_suppress_time;tm=gmtime(&reuse_time);
}elsereuse_time=0;/*Makingformattedtimerstrings.*/if(reuse_time==0){if(use_json)
json_object_int_add(json,"reuseTimerMsecs",0);elsesnprintf(buf,len,"00:00:00");}
elseif(reuse_time<ONE_DAY_SECOND){if(use_json){time_store=(3600000*tm->tm_hour)+
(60000*tm->tm_min)+(1000*tm->tm_sec);json_object_int_add(json,"reuseTimerMsecs",
time_store);}elsesnprintf(buf,len,"%02d:%02d:%02d",tm->tm_hour,tm->tm_min,tm->tm
_sec);}elseif(reuse_time<ONE_WEEK_SECOND){if(use_json){time_store=(86400000*tm->
tm_yday)+(3600000*tm->tm_hour)+(60000*tm->tm_min)+(1000*tm->tm_sec);json_object_
int_add(json,"reuseTimerMsecs",time_store);}elsesnprintf(buf,len,"%dd%02dh%02dm"
,tm->tm_yday,tm->tm_hour,tm->tm_min);}else{if(use_json){time_store=(604800000*tm
->tm_yday/7)+(86400000*(tm->tm_yday-((tm->tm_yday/7)*7)))+(3600000*tm->tm_hour)+
(60000*tm->tm_min)+(1000*tm->tm_sec);json_object_int_add(json,"reuseTimerMsecs",
time_store);}elsesnprintf(buf,len,"%02dw%dd%02dh",tm->tm_yday/7,tm->tm_yday-((tm
->tm_yday/7)*7),tm->tm_hour);}returnbuf;}voidbgp_damp_info_vty(structvty*vty,str
uctbgp_info*binfo,json_object*json_path){structbgp_damp_info*bdi;time_tt_now,t_d
iff;chartimebuf[BGP_UPTIME_LEN];intpenalty;if(!binfo->extra)return;/*BGPdampenin
ginformation.*/bdi=binfo->extra->damp_info;/*Ifdampeningisnotenabledorthereisnod
ampeninginformation,returnimmediately.*/if(!damp||!bdi)return;/*Calculatenewpena
lty.*/t_now=bgp_clock();t_diff=t_now-bdi->t_updated;penalty=bgp_damp_decay(t_dif
f,bdi->penalty);if(json_path){json_object_int_add(json_path,"dampeningPenalty",p
enalty);json_object_int_add(json_path,"dampeningFlapCount",bdi->flap);peer_uptim
e(bdi->start_time,timebuf,BGP_UPTIME_LEN,1,json_path);if(CHECK_FLAG(binfo->flags
,BGP_INFO_DAMPED)&&!CHECK_FLAG(binfo->flags,BGP_INFO_HISTORY))bgp_get_reuse_time
(penalty,timebuf,BGP_UPTIME_LEN,1,json_path);}else{vty_out(vty,"Dampinfo:penalty
%d,flapped%dtimesin%s",penalty,bdi->flap,peer_uptime(bdi->start_time,timebuf,BGP
_UPTIME_LEN,0,json_path));if(CHECK_FLAG(binfo->flags,BGP_INFO_DAMPED)&&!CHECK_FL
AG(binfo->flags,BGP_INFO_HISTORY))vty_out(vty,",reusein%s",bgp_get_reuse_time(pe
nalty,timebuf,BGP_UPTIME_LEN,0,json_path));vty_out(vty,"\n");}}constchar*bgp_dam
p_reuse_time_vty(structvty*vty,structbgp_info*binfo,char*timebuf,size_tlen,uint8
_tuse_json,json_object*json){structbgp_damp_info*bdi;time_tt_now,t_diff;intpenal
ty;if(!binfo->extra)returnNULL;/*BGPdampeninginformation.*/bdi=binfo->extra->dam
p_info;/*Ifdampeningisnotenabledorthereisnodampeninginformation,returnimmediatel
y.*/if(!damp||!bdi)returnNULL;/*Calculatenewpenalty.*/t_now=bgp_clock();t_diff=t
_now-bdi->t_updated;penalty=bgp_damp_decay(t_diff,bdi->penalty);returnbgp_get_re
use_time(penalty,timebuf,len,use_json,json);}intbgp_show_dampening_parameters(st
ructvty*vty,afi_tafi,safi_tsafi){structbgp*bgp;bgp=bgp_get_default();if(bgp==NUL
L){vty_out(vty,"NoBGPprocessisconfigured\n");returnCMD_WARNING;}if(CHECK_FLAG(bg
p->af_flags[afi][safi],BGP_CONFIG_DAMPENING)){vty_out(vty,"Half-lifetime:%lldmin
\n",(longlong)damp->half_life/60);vty_out(vty,"Reusepenalty:%d\n",damp->reuse_li
mit);vty_out(vty,"Suppresspenalty:%d\n",damp->suppress_value);vty_out(vty,"Maxsu
ppresstime:%lldmin\n",(longlong)damp->max_suppress_time/60);vty_out(vty,"Maxsupr
esspenalty:%u\n",damp->ceiling);vty_out(vty,"\n");}elsevty_out(vty,"dampeningnot
enabledfor%s\n",afi==AFI_IP?"IPv4":"IPv6");returnCMD_SUCCESS;}