/*BGPNexthoptracking*Copyright(C)2013CumulusNetworks,Inc.**ThisfileispartofGNUZe
bra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodifyit*underthetermsoft
heGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eitherversion2,
or(atyouroption)any*laterversion.**GNUZebraisdistributedinthehopethatitwillbeuse
ful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITN
ESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshoul
dhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCO
PYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Bosto
n,MA02110-1301USA*/#ifndef_BGP_NHT_H#define_BGP_NHT_H/***bgp_parse_nexthop_updat
e()-parseanexthopupdatemessagefromZebra.*/externvoidbgp_parse_nexthop_update(int
command,vrf_id_tvrf_id);/***bgp_find_nexthop()-lookupthenexthopcachetablefortheb
ncobject*ARGUMENTS:*p-pathforwhichthenexthopobjectisbeinglookedup*connected-True
ifNHMUSTbeaconnectedroute*/externintbgp_find_nexthop(structbgp_info*p,intconnect
ed);/***bgp_find_or_add_nexthop()-lookupthenexthopcachetableforthebnc*object.Ifn
otfound,createanewobjectandregisterwithZEBRAfor*nexthopnotification.*ARGUMENTS:*
bgp-BGPinstance*a-afi:AFI_IPorAF_IP6*p-pathforwhichthenexthopobjectisbeinglooked
up*peer-TheBGPpeerassociatedwiththisNHT*connected-TrueifNHMUSTbeaconnectedroute*
/externintbgp_find_or_add_nexthop(structbgp*bgp,afi_ta,structbgp_info*p,structpe
er*peer,intconnected);/***bgp_unlink_nexthop()-Unlinkthenexthopobjectfromthepath
structure.*ARGUMENTS:*p-pathstructure.*/externvoidbgp_unlink_nexthop(structbgp_i
nfo*p);voidbgp_unlink_nexthop_by_peer(structpeer*);/***bgp_delete_connected_next
hop()-Resetthe'peer'pointerforaconnected*nexthopentry.Ifnopathsreferencethenexth
op,itwillbeunregistered*andfreed.*ARGUMENTS:*afi-afi:AFI_IPorAF_IP6*peer-Ptrtope
er*/externvoidbgp_delete_connected_nexthop(afi_tafi,structpeer*peer);/**Cleanupn
exthopregistrationandstatusinformationforBGPnexthops*pertainingtothisVRF.Thisisi
nvokeduponVRFdeletion.*/externvoidbgp_cleanup_nexthops(structbgp*bgp);#endif/*_B
GP_NHT_H*/