/*
 * BGP-specific error messages.
 * Copyright (C) 2018 Cumulus Networks, Inc.
 *               Don Slice
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; see the file COPYING; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 */



#include "ferr.h"

DECLARE_LOGCAT(BGP_ERR_ATTR_FLAG)
DECLARE_LOGCAT(BGP_ERR_ATTR_LEN)
DECLARE_LOGCAT(BGP_ERR_ATTR_ORIGIN)
DECLARE_LOGCAT(BGP_ERR_ATTR_MAL_AS_PATH)
DECLARE_LOGCAT(BGP_ERR_ATTR_FIRST_AS)
DECLARE_LOGCAT(BGP_ERR_ATTR_PMSI_TYPE)
DECLARE_LOGCAT(BGP_ERR_ATTR_PMSI_LEN)
DECLARE_LOGCAT(BGP_ERR_ATTR_MARTIAN_NH)
DECLARE_LOGCAT(BGP_ERR_ATTR_NH_SEND_LEN)
DECLARE_LOGCAT(BGP_ERR_PEER_GROUP)
DECLARE_LOGCAT(BGP_ERR_PEER_DELETE)
DECLARE_LOGCAT(BGP_ERR_TABLE_CHUNK)
DECLARE_LOGCAT(BGP_ERR_MACIP_LEN)
DECLARE_LOGCAT(BGP_ERR_LM_ERROR)
DECLARE_LOGCAT(BGP_ERR_JSON_MEM_ERROR)
DECLARE_LOGCAT(BGP_ERR_UPDGRP_ATTR_LEN)
DECLARE_LOGCAT(BGP_ERR_UPDGRP_CREATE)
DECLARE_LOGCAT(BGP_ERR_UPDATE_SND)
DECLARE_LOGCAT(BGP_ERR_PKT_OPEN)
DECLARE_LOGCAT(BGP_ERR_SND_FAIL)
DECLARE_LOGCAT(BGP_ERR_INVALID_STATUS)
DECLARE_LOGCAT(BGP_ERR_UPDATE_RCV)
DECLARE_LOGCAT(BGP_ERR_NO_CAP)
DECLARE_LOGCAT(BGP_ERR_NOTIFY_RCV)
DECLARE_LOGCAT(BGP_ERR_KEEP_RCV)
DECLARE_LOGCAT(BGP_ERR_RFSH_RCV)
DECLARE_LOGCAT(BGP_ERR_CAP_RCV)
DECLARE_LOGCAT(BGP_ERR_NH_UPD)
DECLARE_LOGCAT(BGP_ERR_LABEL)
DECLARE_LOGCAT(BGP_ERR_MULTIPATH)
DECLARE_LOGCAT(BGP_ERR_PKT_PROCESS)
DECLARE_LOGCAT(BGP_ERR_CONNECT)
DECLARE_LOGCAT(BGP_ERR_FSM)
DECLARE_LOGCAT(BGP_ERR_VNI)
DECLARE_LOGCAT(BGP_ERR_NO_DFLT)
DECLARE_LOGCAT(BGP_ERR_VTEP_INVALID)
DECLARE_LOGCAT(BGP_ERR_ES_INVALID)
DECLARE_LOGCAT(BGP_ERR_EVPN_ROUTE_DELETE)
DECLARE_LOGCAT(BGP_ERR_EVPN_FAIL)
DECLARE_LOGCAT(BGP_ERR_EVPN_ROUTE_INVALID)
DECLARE_LOGCAT(BGP_ERR_EVPN_ROUTE_CREATE)
DECLARE_LOGCAT(BGP_ERR_ES_CREATE)
DECLARE_LOGCAT(BGP_ERR_MULTI_INSTANCE)
DECLARE_LOGCAT(BGP_ERR_EVPN_AS_MISMATCH)
DECLARE_LOGCAT(BGP_ERR_EVPN_INSTANCE_MISMATCH)
DECLARE_LOGCAT(BGP_ERR_FLOWSPEC_PACKET)
DECLARE_LOGCAT(BGP_ERR_FLOWSPEC_INSTALLATION)
