/*BGPCommunitylist.*Copyright(C)1999KunihiroIshiguro**ThisfileispartofGNUZebra.*
*GNUZebraisfreesoftware;youcanredistributeitand/ormodifyit*underthetermsoftheGNU
GeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eitherversion2,or(at
youroption)any*laterversion.**GNUZebraisdistributedinthehopethatitwillbeuseful,b
ut*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFO
RAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldhave
receivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING
;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA0
2110-1301USA*/#ifndef_QUAGGA_BGP_CLIST_H#define_QUAGGA_BGP_CLIST_H/*MasterCommun
ity-list.*/#defineCOMMUNITY_LIST_MASTER0#defineEXTCOMMUNITY_LIST_MASTER1#defineL
ARGE_COMMUNITY_LIST_MASTER2/*Community-listdenyandpermit.*/#defineCOMMUNITY_DENY
0#defineCOMMUNITY_PERMIT1/*Numberandstringbasedcommunity-listname.*/#defineCOMMU
NITY_LIST_STRING0#defineCOMMUNITY_LIST_NUMBER1/*Community-listentrytypes.*/#defi
neCOMMUNITY_LIST_STANDARD0/*Standardcommunity-list.*/#defineCOMMUNITY_LIST_EXPAN
DED1/*Expandedcommunity-list.*/#defineEXTCOMMUNITY_LIST_STANDARD2/*Standardextco
mmunity-list.*/#defineEXTCOMMUNITY_LIST_EXPANDED3/*Expandedextcommunity-list.*/#
defineLARGE_COMMUNITY_LIST_STANDARD4/*StandardLargecommunity-list.*/#defineLARGE
_COMMUNITY_LIST_EXPANDED5/*ExpandedLargecommunity-list.*//*Community-list.*/stru
ctcommunity_list{/*Nameofthecommunity-list.*/char*name;/*Stringornumber.*/intsor
t;/*Linktoupperlist.*/structcommunity_list_list*parent;/*Linkedlistforothercommu
nity-list.*/structcommunity_list*next;structcommunity_list*prev;/*Community-list
entryinthiscommunity-list.*/structcommunity_entry*head;structcommunity_entry*tai
l;};/*Eachentryincommunity-list.*/structcommunity_entry{structcommunity_entry*ne
xt;structcommunity_entry*prev;/*Permitordeny.*/uint8_tdirect;/*Standardorexpande
d.*/uint8_tstyle;/*Anymatch.*/uint8_tany;/*Communitystructure.*/union{structcomm
unity*com;structecommunity*ecom;structlcommunity*lcom;}u;/*Configurationstring.*
/char*config;/*Expandedcommunity-listregularexpression.*/regex_t*reg;};/*Linkedl
istofcommunity-list.*/structcommunity_list_list{structcommunity_list*head;struct
community_list*tail;};/*Masterstructureofcommunity-listandextcommunity-list.*/st
ructcommunity_list_master{structcommunity_list_listnum;structcommunity_list_list
str;};/*Community-listhandler.community_list_init()returnsthisstructureashandler
.*/structcommunity_list_handler{/*Community-list.*/structcommunity_list_masterco
mmunity_list;/*Extededcommunity-list.*/structcommunity_list_masterextcommunity_l
ist;/*Largecommunity-list.*/structcommunity_list_masterlcommunity_list;};/*Error
codeofcommunity-list.*/#defineCOMMUNITY_LIST_ERR_CANT_FIND_LIST-1#defineCOMMUNIT
Y_LIST_ERR_MALFORMED_VAL-2#defineCOMMUNITY_LIST_ERR_STANDARD_CONFLICT-3#defineCO
MMUNITY_LIST_ERR_EXPANDED_CONFLICT-4/*Handler.*/externstructcommunity_list_handl
er*bgp_clist;/*Prototypes.*/externstructcommunity_list_handler*community_list_in
it(void);externvoidcommunity_list_terminate(structcommunity_list_handler*);exter
nintcommunity_list_set(structcommunity_list_handler*ch,constchar*name,constchar*
str,intdirect,intstyle);externintcommunity_list_unset(structcommunity_list_handl
er*ch,constchar*name,constchar*str,intdirect,intstyle,intdelete_all);externintex
tcommunity_list_set(structcommunity_list_handler*ch,constchar*name,constchar*str
,intdirect,intstyle);externintextcommunity_list_unset(structcommunity_list_handl
er*ch,constchar*name,constchar*str,intdirect,intstyle,intdelete_all);externintlc
ommunity_list_set(structcommunity_list_handler*ch,constchar*name,constchar*str,i
ntdirect,intstyle);externintlcommunity_list_unset(structcommunity_list_handler*c
h,constchar*name,constchar*str,intdirect,intstyle);externstructcommunity_list_ma
ster*community_list_master_lookup(structcommunity_list_handler*,int);externstruc
tcommunity_list*community_list_lookup(structcommunity_list_handler*,constchar*,i
nt);externintcommunity_list_match(structcommunity*,structcommunity_list*);extern
intecommunity_list_match(structecommunity*,structcommunity_list*);externintlcomm
unity_list_match(structlcommunity*,structcommunity_list*);externintcommunity_lis
t_exact_match(structcommunity*,structcommunity_list*);externstructcommunity*comm
unity_list_match_delete(structcommunity*,structcommunity_list*);externstructlcom
munity*lcommunity_list_match_delete(structlcommunity*lcom,structcommunity_list*l
ist);#endif/*_QUAGGA_BGP_CLIST_H*/