/*BGPI/O.*ImplementspacketI/Oinapthread.*Copyright(C)2017CumulusNetworks*Quentin
Young**Thisprogramisfreesoftware;youcanredistributeitand/ormodify*itundertheterm
softheGNUGeneralPublicLicenseaspublishedby*theFreeSoftwareFoundation;eitherversi
on2oftheLicense,or*(atyouroption)anylaterversion.**Thisprogramisdistributedinthe
hopethatitwillbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*ME
RCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformor
edetails.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicense*alongwiththisp
rogram;seethefileCOPYING;ifnot,writetothe*FreeSoftwareFoundation,Inc.,51Franklin
St,FifthFloor,Boston,*MA02110-1301USA*//*clang-formatoff*/#include<zebra.h>#incl
ude<pthread.h>//forpthread_mutex_unlock,pthread_mutex_lock#include"frr_pthread.h
"//forfrr_pthread_get,frr_pthread#include"linklist.h"//forlist_delete,list_delet
e_all_node,lis...#include"log.h"//forzlog_debug,safe_strerror,zlog_err#include"m
emory.h"//forMTYPE_TMP,XCALLOC,XFREE#include"network.h"//forERRNO_IO_RETRY#inclu
de"stream.h"//forstream_get_endp,stream_getw_from,str...#include"ringbuf.h"//for
ringbuf_remain,ringbuf_peek,ringbuf_...#include"thread.h"//forTHREAD_OFF,THREAD_
ARG,thread,thread...#include"zassert.h"//forassert#include"bgpd/bgp_io.h"#includ
e"bgpd/bgp_debug.h"//forbgp_debug_neighbor_events,bgp_type_str#include"bgpd/bgp_
fsm.h"//forBGP_EVENT_ADD,bgp_event#include"bgpd/bgp_packet.h"//forbgp_notify_sen
d_with_data,bgp_notify...#include"bgpd/bgpd.h"//forpeer,BGP_MARKER_SIZE,bgp_mast
er,bm/*clang-formaton*//*forwarddeclarations*/staticuint16_tbgp_write(structpeer
*);staticuint16_tbgp_read(structpeer*);staticintbgp_process_writes(structthread*
);staticintbgp_process_reads(structthread*);staticboolvalidate_header(structpeer
*);/*generici/ostatuscodes*/#defineBGP_IO_TRANS_ERR(1<<0)//EAGAINorsimilaroccurr
ed#defineBGP_IO_FATAL_ERR(1<<1)//somekindoffatalTCPerror/*ThreadexternalAPI-----
------------------------------------------------*/voidbgp_writes_on(structpeer*p
eer){structfrr_pthread*fpt=frr_pthread_get(PTHREAD_IO);assert(fpt->running);asse
rt(peer->status!=Deleted);assert(peer->obuf);assert(peer->ibuf);assert(peer->ibu
f_work);assert(!peer->t_connect_check_r);assert(!peer->t_connect_check_w);assert
(peer->fd);thread_add_write(fpt->master,bgp_process_writes,peer,peer->fd,&peer->
t_write);SET_FLAG(peer->thread_flags,PEER_THREAD_WRITES_ON);}voidbgp_writes_off(
structpeer*peer){structfrr_pthread*fpt=frr_pthread_get(PTHREAD_IO);assert(fpt->r
unning);thread_cancel_async(fpt->master,&peer->t_write,NULL);THREAD_OFF(peer->t_
generate_updgrp_packets);UNSET_FLAG(peer->thread_flags,PEER_THREAD_WRITES_ON);}v
oidbgp_reads_on(structpeer*peer){structfrr_pthread*fpt=frr_pthread_get(PTHREAD_I
O);assert(fpt->running);assert(peer->status!=Deleted);assert(peer->ibuf);assert(
peer->fd);assert(peer->ibuf_work);assert(peer->obuf);assert(!peer->t_connect_che
ck_r);assert(!peer->t_connect_check_w);assert(peer->fd);thread_add_read(fpt->mas
ter,bgp_process_reads,peer,peer->fd,&peer->t_read);SET_FLAG(peer->thread_flags,P
EER_THREAD_READS_ON);}voidbgp_reads_off(structpeer*peer){structfrr_pthread*fpt=f
rr_pthread_get(PTHREAD_IO);assert(fpt->running);thread_cancel_async(fpt->master,
&peer->t_read,NULL);THREAD_OFF(peer->t_process_packet);UNSET_FLAG(peer->thread_f
lags,PEER_THREAD_READS_ON);}/*Threadinternalfunctions---------------------------
--------------------*//**CalledfromI/Opthreadwhenafiledescriptorhasbecomereadyfo
rwriting.*/staticintbgp_process_writes(structthread*thread){staticstructpeer*pee
r;peer=THREAD_ARG(thread);uint16_tstatus;boolreschedule;boolfatal=false;if(peer-
>fd<0)return-1;structfrr_pthread*fpt=frr_pthread_get(PTHREAD_IO);pthread_mutex_l
ock(&peer->io_mtx);{status=bgp_write(peer);reschedule=(stream_fifo_head(peer->ob
uf)!=NULL);}pthread_mutex_unlock(&peer->io_mtx);/*noproblem*/if(CHECK_FLAG(statu
s,BGP_IO_TRANS_ERR)){}/*problem*/if(CHECK_FLAG(status,BGP_IO_FATAL_ERR)){resched
ule=false;fatal=true;}if(reschedule){thread_add_write(fpt->master,bgp_process_wr
ites,peer,peer->fd,&peer->t_write);}elseif(!fatal){BGP_TIMER_ON(peer->t_generate
_updgrp_packets,bgp_generate_updgrp_packets,0);}return0;}/**CalledfromI/Opthread
whenafiledescriptorhasbecomereadyforreading,*orhashungup.**Wereadasmuchdataaspos
sible,processasmanypacketsaswecanand*placethemonpeer->ibufforsecondaryprocessing
bythemainthread.*/staticintbgp_process_reads(structthread*thread){/*clang-format
off*/staticstructpeer*peer;//peertoreadfromuint16_tstatus;//bgp_readstatuscodebo
olmore=true;//whetherwegotmoredataboolfatal=false;//whetherfatalerroroccurredboo
ladded_pkt=false;//whetherwepushedonto->ibufboolheader_valid=true;//whetherheade
risvalid/*clang-formaton*/peer=THREAD_ARG(thread);if(peer->fd<0)return-1;structf
rr_pthread*fpt=frr_pthread_get(PTHREAD_IO);pthread_mutex_lock(&peer->io_mtx);{st
atus=bgp_read(peer);}pthread_mutex_unlock(&peer->io_mtx);/*errorcheckingphase*/i
f(CHECK_FLAG(status,BGP_IO_TRANS_ERR)){/*noproblem;justdon'tprocesspackets*/more
=false;}if(CHECK_FLAG(status,BGP_IO_FATAL_ERR)){/*problem;teardownsession*/more=
false;fatal=true;}while(more){/*staticbufferfortransferringpackets*/staticunsign
edcharpktbuf[BGP_MAX_PACKET_SIZE];/*shorteraliastopeer'sinputbuffer*/structringb
uf*ibw=peer->ibuf_work;/*packetsizeasgivenbyheader*/uint16_tpktsize=0;/*checktha
twehaveenoughdataforaheader*/if(ringbuf_remain(ibw)<BGP_HEADER_SIZE)break;/*vali
dateheader*/header_valid=validate_header(peer);if(!header_valid){fatal=true;brea
k;}/*headerisvalid;retrievepacketsize*/ringbuf_peek(ibw,BGP_MARKER_SIZE,&pktsize
,sizeof(pktsize));pktsize=ntohs(pktsize);/*ifthisfailsweareseriouslyscrewed*/ass
ert(pktsize<=BGP_MAX_PACKET_SIZE);/**Ifwehavethatmuchdata,chuckitintoitsown*stre
amandappendtoinputqueueforprocessing.*/if(ringbuf_remain(ibw)>=pktsize){structst
ream*pkt=stream_new(pktsize);assert(ringbuf_get(ibw,pktbuf,pktsize)==pktsize);st
ream_put(pkt,pktbuf,pktsize);pthread_mutex_lock(&peer->io_mtx);{stream_fifo_push
(peer->ibuf,pkt);}pthread_mutex_unlock(&peer->io_mtx);added_pkt=true;}elsebreak;
}assert(ringbuf_space(peer->ibuf_work)>=BGP_MAX_PACKET_SIZE);/*handleinvalidhead
er*/if(fatal){/*wipebufferjustincasesomeonescrewedup*/ringbuf_wipe(peer->ibuf_wo
rk);}else{thread_add_read(fpt->master,bgp_process_reads,peer,peer->fd,&peer->t_r
ead);if(added_pkt)thread_add_timer_msec(bm->master,bgp_process_packet,peer,0,&pe
er->t_process_packet);}return0;}/**Flushpeeroutputbuffer.**Thisfunctionpopspacke
tsoffofpeer->obufandwritesthemtopeer->fd.*Theamountofpacketswrittenisequaltothem
inimumofpeer->wpkt_quanta*andthenumberofpacketsontheoutputbuffer,unlessanerroroc
curs.**Ifwrite()returnsanerror,theappropriateFSMeventisgenerated.**Thereturnvalu
eisequaltothenumberofpacketswritten*(whichmaybezero).*/staticuint16_tbgp_write(s
tructpeer*peer){uint8_ttype;structstream*s;intnum;intupdate_last_write=0;unsigne
dintcount=0;uint32_tuo=0;uint16_tstatus=0;uint32_twpkt_quanta_old;wpkt_quanta_ol
d=atomic_load_explicit(&peer->bgp->wpkt_quanta,memory_order_relaxed);while(count
<wpkt_quanta_old&&(s=stream_fifo_head(peer->obuf))){intwritenum;do{writenum=stre
am_get_endp(s)-stream_get_getp(s);num=write(peer->fd,STREAM_PNT(s),writenum);if(
num<0){if(!ERRNO_IO_RETRY(errno)){BGP_EVENT_ADD(peer,TCP_fatal_error);SET_FLAG(s
tatus,BGP_IO_FATAL_ERR);}else{SET_FLAG(status,BGP_IO_TRANS_ERR);}gotodone;}elsei
f(num!=writenum)stream_forward_getp(s,num);}while(num!=writenum);/*RetrieveBGPpa
ckettype.*/stream_set_getp(s,BGP_MARKER_SIZE+2);type=stream_getc(s);switch(type)
{caseBGP_MSG_OPEN:atomic_fetch_add_explicit(&peer->open_out,1,memory_order_relax
ed);break;caseBGP_MSG_UPDATE:atomic_fetch_add_explicit(&peer->update_out,1,memor
y_order_relaxed);uo++;break;caseBGP_MSG_NOTIFY:atomic_fetch_add_explicit(&peer->
notify_out,1,memory_order_relaxed);/*Doublestarttimer.*/peer->v_start*=2;/*Overf
lowcheck.*/if(peer->v_start>=(60*2))peer->v_start=(60*2);/**HandleGracefulRestar
tcasewherethestatechanges*toConnectinsteadofIdle.*/BGP_EVENT_ADD(peer,BGP_Stop);
gotodone;caseBGP_MSG_KEEPALIVE:atomic_fetch_add_explicit(&peer->keepalive_out,1,
memory_order_relaxed);break;caseBGP_MSG_ROUTE_REFRESH_NEW:caseBGP_MSG_ROUTE_REFR
ESH_OLD:atomic_fetch_add_explicit(&peer->refresh_out,1,memory_order_relaxed);bre
ak;caseBGP_MSG_CAPABILITY:atomic_fetch_add_explicit(&peer->dynamic_cap_out,1,mem
ory_order_relaxed);break;}count++;stream_free(stream_fifo_pop(peer->obuf));updat
e_last_write=1;}done:{/**Updatelast_updateifUPDATEswerewritten.*Note:thatthesear
eonlyupdatedatend,*notpermessage(i.e.,perloop)*/if(uo)atomic_store_explicit(&pee
r->last_update,bgp_clock(),memory_order_relaxed);/*IfweTXedanyflavorofpacket*/if
(update_last_write)atomic_store_explicit(&peer->last_write,bgp_clock(),memory_or
der_relaxed);}returnstatus;}/**Readsachunkofdatafrompeer->fdintopeer->ibuf_work.
**@returnstatusflag(seetop-of-file)*/staticuint16_tbgp_read(structpeer*peer){siz
e_treadsize;//howmanybyteswewanttoreadssize_tnbytes;//howmanybytesweactuallyread
uint16_tstatus=0;staticuint8_tibw[BGP_MAX_PACKET_SIZE*BGP_READ_PACKET_MAX];reads
ize=MIN(ringbuf_space(peer->ibuf_work),sizeof(ibw));nbytes=read(peer->fd,ibw,rea
dsize);/*EAGAINorEWOULDBLOCK;comebacklater*/if(nbytes<0&&ERRNO_IO_RETRY(errno)){
SET_FLAG(status,BGP_IO_TRANS_ERR);/*Fatalerror;teardownsession*/}elseif(nbytes<0
){zlog_err("%s[Error]bgp_read_packeterror:%s",peer->host,safe_strerror(errno));i
f(peer->status==Established){if(CHECK_FLAG(peer->sflags,PEER_STATUS_NSF_MODE)){p
eer->last_reset=PEER_DOWN_NSF_CLOSE_SESSION;SET_FLAG(peer->sflags,PEER_STATUS_NS
F_WAIT);}elsepeer->last_reset=PEER_DOWN_CLOSE_SESSION;}BGP_EVENT_ADD(peer,TCP_fa
tal_error);SET_FLAG(status,BGP_IO_FATAL_ERR);/*ReceivedEOF/TCPsessionclosed*/}el
seif(nbytes==0){if(bgp_debug_neighbor_events(peer))zlog_debug("%s[Event]BGPconne
ctionclosedfd%d",peer->host,peer->fd);if(peer->status==Established){if(CHECK_FLA
G(peer->sflags,PEER_STATUS_NSF_MODE)){peer->last_reset=PEER_DOWN_NSF_CLOSE_SESSI
ON;SET_FLAG(peer->sflags,PEER_STATUS_NSF_WAIT);}elsepeer->last_reset=PEER_DOWN_C
LOSE_SESSION;}BGP_EVENT_ADD(peer,TCP_connection_closed);SET_FLAG(status,BGP_IO_F
ATAL_ERR);}else{assert(ringbuf_put(peer->ibuf_work,ibw,nbytes)==(size_t)nbytes);
}returnstatus;}/**CalledafterwehavereadaBGPpacketheader.Validatesmarker,message*
typeandpacketlength.Ifanyofthesearen'tcorrect,sendsanotify.**Assumesthatthereare
atleastBGP_HEADER_SIZEreadablebytesintheinput*buffer.*/staticboolvalidate_header
(structpeer*peer){uint16_tsize;uint8_ttype;structringbuf*pkt=peer->ibuf_work;sta
ticuint8_tm_correct[BGP_MARKER_SIZE]={0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x
ff,0xff,0xff,0xff,0xff,0xff,0xff,0xff};uint8_tm_rx[BGP_MARKER_SIZE]={0x00};if(ri
ngbuf_peek(pkt,0,m_rx,BGP_MARKER_SIZE)!=BGP_MARKER_SIZE)returnfalse;if(memcmp(m_
correct,m_rx,BGP_MARKER_SIZE)!=0){bgp_notify_send(peer,BGP_NOTIFY_HEADER_ERR,BGP
_NOTIFY_HEADER_NOT_SYNC);returnfalse;}/*Getsizeandtypeinnetworkbyteorder.*/ringb
uf_peek(pkt,BGP_MARKER_SIZE,&size,sizeof(size));ringbuf_peek(pkt,BGP_MARKER_SIZE
+2,&type,sizeof(type));size=ntohs(size);/*BGPtypecheck.*/if(type!=BGP_MSG_OPEN&&
type!=BGP_MSG_UPDATE&&type!=BGP_MSG_NOTIFY&&type!=BGP_MSG_KEEPALIVE&&type!=BGP_M
SG_ROUTE_REFRESH_NEW&&type!=BGP_MSG_ROUTE_REFRESH_OLD&&type!=BGP_MSG_CAPABILITY)
{if(bgp_debug_neighbor_events(peer))zlog_debug("%sunknownmessagetype0x%02x",peer
->host,type);bgp_notify_send_with_data(peer,BGP_NOTIFY_HEADER_ERR,BGP_NOTIFY_HEA
DER_BAD_MESTYPE,&type,1);returnfalse;}/*Minimumpacketlengthcheck.*/if((size<BGP_
HEADER_SIZE)||(size>BGP_MAX_PACKET_SIZE)||(type==BGP_MSG_OPEN&&size<BGP_MSG_OPEN
_MIN_SIZE)||(type==BGP_MSG_UPDATE&&size<BGP_MSG_UPDATE_MIN_SIZE)||(type==BGP_MSG
_NOTIFY&&size<BGP_MSG_NOTIFY_MIN_SIZE)||(type==BGP_MSG_KEEPALIVE&&size!=BGP_MSG_
KEEPALIVE_MIN_SIZE)||(type==BGP_MSG_ROUTE_REFRESH_NEW&&size<BGP_MSG_ROUTE_REFRES
H_MIN_SIZE)||(type==BGP_MSG_ROUTE_REFRESH_OLD&&size<BGP_MSG_ROUTE_REFRESH_MIN_SI
ZE)||(type==BGP_MSG_CAPABILITY&&size<BGP_MSG_CAPABILITY_MIN_SIZE)){if(bgp_debug_
neighbor_events(peer)){zlog_debug("%sbadmessagelength-%dfor%s",peer->host,size,t
ype==128?"ROUTE-REFRESH":bgp_type_str[(int)type]);}uint16_tnsize=htons(size);bgp
_notify_send_with_data(peer,BGP_NOTIFY_HEADER_ERR,BGP_NOTIFY_HEADER_BAD_MESLEN,(
unsignedchar*)&nsize,2);returnfalse;}returntrue;}