/**BGPMultipath*Copyright(C)2010GoogleInc.**ThisfileispartofQuagga**Quaggaisfree
software;youcanredistributeitand/ormodifyit*underthetermsoftheGNUGeneralPublicLi
censeaspublishedbythe*FreeSoftwareFoundation;eitherversion2,or(atyouroption)any*
laterversion.**Quaggaisdistributedinthehopethatitwillbeuseful,but*WITHOUTANYWARR
ANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTICULARPURPO
SE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldhavereceivedacopyofth
eGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;ifnot,writetothe
FreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-1301USA*/#in
clude<zebra.h>#include"command.h"#include"prefix.h"#include"linklist.h"#include"
sockunion.h"#include"memory.h"#include"queue.h"#include"filter.h"#include"bgpd/b
gpd.h"#include"bgpd/bgp_table.h"#include"bgpd/bgp_route.h"#include"bgpd/bgp_attr
.h"#include"bgpd/bgp_debug.h"#include"bgpd/bgp_aspath.h"#include"bgpd/bgp_commun
ity.h"#include"bgpd/bgp_ecommunity.h"#include"bgpd/bgp_lcommunity.h"#include"bgp
d/bgp_mpath.h"/**bgp_maximum_paths_set**Recordmaximum-pathsconfigurationforBGPin
stance*/intbgp_maximum_paths_set(structbgp*bgp,afi_tafi,safi_tsafi,intpeertype,u
int16_tmaxpaths,uint16_toptions){if(!bgp||(afi>=AFI_MAX)||(safi>=SAFI_MAX))retur
n-1;switch(peertype){caseBGP_PEER_IBGP:bgp->maxpaths[afi][safi].maxpaths_ibgp=ma
xpaths;bgp->maxpaths[afi][safi].ibgp_flags|=options;break;caseBGP_PEER_EBGP:bgp-
>maxpaths[afi][safi].maxpaths_ebgp=maxpaths;break;default:return-1;}return0;}/**
bgp_maximum_paths_unset**Removemaximum-pathsconfigurationfromBGPinstance*/intbgp
_maximum_paths_unset(structbgp*bgp,afi_tafi,safi_tsafi,intpeertype){if(!bgp||(af
i>=AFI_MAX)||(safi>=SAFI_MAX))return-1;switch(peertype){caseBGP_PEER_IBGP:bgp->m
axpaths[afi][safi].maxpaths_ibgp=multipath_num;bgp->maxpaths[afi][safi].ibgp_fla
gs=0;break;caseBGP_PEER_EBGP:bgp->maxpaths[afi][safi].maxpaths_ebgp=multipath_nu
m;break;default:return-1;}return0;}/**bgp_interface_same**Returntrueififindexfor
ifp1andifp2arethesame,elsereturnfalse.*/staticintbgp_interface_same(structinterf
ace*ifp1,structinterface*ifp2){if(!ifp1&&!ifp2)return1;if(!ifp1&&ifp2)return0;if
(ifp1&&!ifp2)return0;return(ifp1->ifindex==ifp2->ifindex);}/**bgp_info_nexthop_c
mp**Comparethenexthopsoftwopaths.Returnvalueislessthan,equalto,*orgreaterthanzer
oifbi1isrespectivelylessthan,equalto,*orgreaterthanbi2.*/intbgp_info_nexthop_cmp
(structbgp_info*bi1,structbgp_info*bi2){intcompare;structin6_addraddr1,addr2;com
pare=IPV4_ADDR_CMP(&bi1->attr->nexthop,&bi2->attr->nexthop);if(!compare){if(bi1-
>attr->mp_nexthop_len==bi2->attr->mp_nexthop_len){switch(bi1->attr->mp_nexthop_l
en){caseBGP_ATTR_NHLEN_IPV4:caseBGP_ATTR_NHLEN_VPNV4:compare=IPV4_ADDR_CMP(&bi1-
>attr->mp_nexthop_global_in,&bi2->attr->mp_nexthop_global_in);break;caseBGP_ATTR
_NHLEN_IPV6_GLOBAL:caseBGP_ATTR_NHLEN_VPNV6_GLOBAL:compare=IPV6_ADDR_CMP(&bi1->a
ttr->mp_nexthop_global,&bi2->attr->mp_nexthop_global);break;caseBGP_ATTR_NHLEN_I
PV6_GLOBAL_AND_LL:addr1=(bi1->attr->mp_nexthop_prefer_global)?bi1->attr->mp_next
hop_global:bi1->attr->mp_nexthop_local;addr2=(bi2->attr->mp_nexthop_prefer_globa
l)?bi2->attr->mp_nexthop_global:bi2->attr->mp_nexthop_local;if(!bi1->attr->mp_ne
xthop_prefer_global&&!bi2->attr->mp_nexthop_prefer_global)compare=!bgp_interface
_same(bi1->peer->ifp,bi2->peer->ifp);if(!compare)compare=IPV6_ADDR_CMP(&addr1,&a
ddr2);break;}}/*ThiscanhappenifoneIPv6peersendsyouglobaland*link-local*nexthopsb
utanotherIPv6peeronlysendsyouglobal*/elseif(bi1->attr->mp_nexthop_len==BGP_ATTR_
NHLEN_IPV6_GLOBAL||bi1->attr->mp_nexthop_len==BGP_ATTR_NHLEN_IPV6_GLOBAL_AND_LL)
{compare=IPV6_ADDR_CMP(&bi1->attr->mp_nexthop_global,&bi2->attr->mp_nexthop_glob
al);if(!compare){if(bi1->attr->mp_nexthop_len<bi2->attr->mp_nexthop_len)compare=
-1;elsecompare=1;}}}returncompare;}/**bgp_info_mpath_cmp**Thisfunctiondetermines
ourmultipathlistordering.Byordering*thelistwecandeterministicallyselectwhichpath
sareincluded*inthemultipathset.Theorderingalsohelpsindetectingchanges*inthemulti
pathselectionsowecandetectwhethertosendan*updatetozebra.**Theorderofpathsisdeter
minedfirstbyreceivednexthop,andthen*bypeeraddressifthenexthopsarethesame.*/stati
cintbgp_info_mpath_cmp(void*val1,void*val2){structbgp_info*bi1,*bi2;intcompare;b
i1=val1;bi2=val2;compare=bgp_info_nexthop_cmp(bi1,bi2);if(!compare){if(!bi1->pee
r->su_remote&&!bi2->peer->su_remote)compare=0;elseif(!bi1->peer->su_remote)compa
re=1;elseif(!bi2->peer->su_remote)compare=-1;elsecompare=sockunion_cmp(bi1->peer
->su_remote,bi2->peer->su_remote);}returncompare;}/**bgp_mp_list_init**Initializ
ethemp_list,whichholdsthelistofmultipaths*selectedbybgp_best_selection*/voidbgp_
mp_list_init(structlist*mp_list){assert(mp_list);memset(mp_list,0,sizeof(structl
ist));mp_list->cmp=bgp_info_mpath_cmp;}/**bgp_mp_list_clear**Clearsallentriesout
ofthemp_list*/voidbgp_mp_list_clear(structlist*mp_list){assert(mp_list);list_del
ete_all_node(mp_list);}/**bgp_mp_list_add**Addsamultipathentrytothemp_list*/void
bgp_mp_list_add(structlist*mp_list,structbgp_info*mpinfo){assert(mp_list&&mpinfo
);listnode_add_sort(mp_list,mpinfo);}/**bgp_info_mpath_new**Allocateandzeromemor
yforanewbgp_info_mpathelement*/staticstructbgp_info_mpath*bgp_info_mpath_new(voi
d){structbgp_info_mpath*new_mpath;new_mpath=XCALLOC(MTYPE_BGP_MPATH_INFO,sizeof(
structbgp_info_mpath));returnnew_mpath;}/**bgp_info_mpath_free**Releaseresources
forabgp_info_mpathelementandzerooutpointer*/voidbgp_info_mpath_free(structbgp_in
fo_mpath**mpath){if(mpath&&*mpath){if((*mpath)->mp_attr)bgp_attr_unintern(&(*mpa
th)->mp_attr);XFREE(MTYPE_BGP_MPATH_INFO,*mpath);*mpath=NULL;}}/**bgp_info_mpath
_get**Fetchthempathelementforthegivenbgp_info.Usedfor*doinglazyallocation.*/stat
icstructbgp_info_mpath*bgp_info_mpath_get(structbgp_info*binfo){structbgp_info_m
path*mpath;if(!binfo->mpath){mpath=bgp_info_mpath_new();if(!mpath)returnNULL;bin
fo->mpath=mpath;mpath->mp_info=binfo;}returnbinfo->mpath;}/**bgp_info_mpath_enqu
eue**Enqueueapathontothemultipathlistgiventhepreviousmultipath*listentry*/static
voidbgp_info_mpath_enqueue(structbgp_info*prev_info,structbgp_info*binfo){struct
bgp_info_mpath*prev,*mpath;prev=bgp_info_mpath_get(prev_info);mpath=bgp_info_mpa
th_get(binfo);if(!prev||!mpath)return;mpath->mp_next=prev->mp_next;mpath->mp_pre
v=prev;if(prev->mp_next)prev->mp_next->mp_prev=mpath;prev->mp_next=mpath;SET_FLA
G(binfo->flags,BGP_INFO_MULTIPATH);}/**bgp_info_mpath_dequeue**Removeapathfromth
emultipathlist*/voidbgp_info_mpath_dequeue(structbgp_info*binfo){structbgp_info_
mpath*mpath=binfo->mpath;if(!mpath)return;if(mpath->mp_prev)mpath->mp_prev->mp_n
ext=mpath->mp_next;if(mpath->mp_next)mpath->mp_next->mp_prev=mpath->mp_prev;mpat
h->mp_next=mpath->mp_prev=NULL;UNSET_FLAG(binfo->flags,BGP_INFO_MULTIPATH);}/**b
gp_info_mpath_next**Givenabgp_info,returnthenextmultipathentry*/structbgp_info*b
gp_info_mpath_next(structbgp_info*binfo){if(!binfo->mpath||!binfo->mpath->mp_nex
t)returnNULL;returnbinfo->mpath->mp_next->mp_info;}/**bgp_info_mpath_first**Give
nbestpathbgp_info,returnthefirstmultipathentry.*/structbgp_info*bgp_info_mpath_f
irst(structbgp_info*binfo){returnbgp_info_mpath_next(binfo);}/**bgp_info_mpath_c
ount**Giventhebestpathbgp_info,returnthenumberofmultipathentries*/uint32_tbgp_in
fo_mpath_count(structbgp_info*binfo){if(!binfo->mpath)return0;returnbinfo->mpath
->mp_count;}/**bgp_info_mpath_count_set**Setsthecountofmultipathsintobestpath'sm
pathelement*/staticvoidbgp_info_mpath_count_set(structbgp_info*binfo,uint32_tcou
nt){structbgp_info_mpath*mpath;if(!count&&!binfo->mpath)return;mpath=bgp_info_mp
ath_get(binfo);if(!mpath)return;mpath->mp_count=count;}/**bgp_info_mpath_attr**G
ivenbestpathbgp_info,returnaggregatedattributesetused*foradvertisingthemultipath
route*/structattr*bgp_info_mpath_attr(structbgp_info*binfo){if(!binfo->mpath)ret
urnNULL;returnbinfo->mpath->mp_attr;}/**bgp_info_mpath_attr_set**Setstheaggregat
edattributeintobestpath'smpathelement*/staticvoidbgp_info_mpath_attr_set(structb
gp_info*binfo,structattr*attr){structbgp_info_mpath*mpath;if(!attr&&!binfo->mpat
h)return;mpath=bgp_info_mpath_get(binfo);if(!mpath)return;mpath->mp_attr=attr;}/
**bgp_info_mpath_update**Compareandsyncupthemultipathlistwiththemp_listgenerated
by*bgp_best_selection*/voidbgp_info_mpath_update(structbgp_node*rn,structbgp_inf
o*new_best,structbgp_info*old_best,structlist*mp_list,structbgp_maxpaths_cfg*mpa
th_cfg){uint16_tmaxpaths,mpath_count,old_mpath_count;structlistnode*mp_node,*mp_
next_node;structbgp_info*cur_mpath,*new_mpath,*next_mpath,*prev_mpath;intmpath_c
hanged,debug;charpfx_buf[PREFIX2STR_BUFFER],nh_buf[2][INET6_ADDRSTRLEN];charpath
_buf[PATH_ADDPATH_STR_BUFFER];mpath_changed=0;maxpaths=multipath_num;mpath_count
=0;cur_mpath=NULL;old_mpath_count=0;prev_mpath=new_best;mp_node=listhead(mp_list
);debug=bgp_debug_bestpath(&rn->p);if(debug)prefix2str(&rn->p,pfx_buf,sizeof(pfx
_buf));if(new_best){mpath_count++;if(new_best!=old_best)bgp_info_mpath_dequeue(n
ew_best);maxpaths=(new_best->peer->sort==BGP_PEER_IBGP)?mpath_cfg->maxpaths_ibgp
:mpath_cfg->maxpaths_ebgp;}if(old_best){cur_mpath=bgp_info_mpath_first(old_best)
;old_mpath_count=bgp_info_mpath_count(old_best);bgp_info_mpath_count_set(old_bes
t,0);bgp_info_mpath_dequeue(old_best);}if(debug)zlog_debug("%s:startingmpathupda
te,newbest%snumcandidates%dold-mpath-count%d",pfx_buf,new_best?new_best->peer->h
ost:"NONE",listcount(mp_list),old_mpath_count);/**Weperformanorderedwalkthroughb
othlistsinparallel.*Thereasonfortheorderedwalkisthatiftherearepaths*thatwereprev
iouslymultipathsandarestillmultipaths,thewalk*shouldencountertheminbothlistsatth
esametime.Otherwise*therewillbepathsthatareinonelistoranother,andwe*willdealwith
theseseparately.**Notethatnew_bestmightbesomewhereinthemp_list,soweneed*toskipov
erit*/while(mp_node||cur_mpath){structbgp_info*tmp_info;/**Wecanbailoutofthisloo
pifallexistingpathsonthe*multipathlisthavebeenvisited(forcleanuppurposes)and*the
maxpathrequirementisfulfulled*/if(!cur_mpath&&(mpath_count>=maxpaths))break;mp_n
ext_node=mp_node?listnextnode(mp_node):NULL;next_mpath=cur_mpath?bgp_info_mpath_
next(cur_mpath):NULL;tmp_info=mp_node?listgetdata(mp_node):NULL;if(debug)zlog_de
bug("%s:comparingcandidate%swithexistingmpath%s",pfx_buf,tmp_info?tmp_info->peer
->host:"NONE",cur_mpath?cur_mpath->peer->host:"NONE");/**Ifequal,thepathwasamult
ipathandisstillamultipath.*Insertontonewmultipathlistifmaxpathsallows.*/if(mp_no
de&&(listgetdata(mp_node)==cur_mpath)){list_delete_node(mp_list,mp_node);bgp_inf
o_mpath_dequeue(cur_mpath);if((mpath_count<maxpaths)&&bgp_info_nexthop_cmp(prev_
mpath,cur_mpath)){bgp_info_mpath_enqueue(prev_mpath,cur_mpath);prev_mpath=cur_mp
ath;mpath_count++;if(debug){bgp_info_path_with_addpath_rx_str(cur_mpath,path_buf
);zlog_debug("%s:%sisstillmultipath,curcount%d",pfx_buf,path_buf,mpath_count);}}
else{mpath_changed=1;if(debug){bgp_info_path_with_addpath_rx_str(cur_mpath,path_
buf);zlog_debug("%s:removempath%snexthop%s,curcount%d",pfx_buf,path_buf,inet_nto
p(AF_INET,&cur_mpath->attr->nexthop,nh_buf[0],sizeof(nh_buf[0])),mpath_count);}}
mp_node=mp_next_node;cur_mpath=next_mpath;continue;}if(cur_mpath&&(!mp_node||(bg
p_info_mpath_cmp(cur_mpath,listgetdata(mp_node))<0))){/**Ifhere,wehaveanoldmulti
pathandeitherthe*mp_list*isfinishedorthenextmp_nodepointstoalater*multipath,sowe
needtopurgethispathfromthe*multipathlist*/bgp_info_mpath_dequeue(cur_mpath);mpat
h_changed=1;if(debug){bgp_info_path_with_addpath_rx_str(cur_mpath,path_buf);zlog
_debug("%s:removempath%snexthop%s,curcount%d",pfx_buf,path_buf,inet_ntop(AF_INET
,&cur_mpath->attr->nexthop,nh_buf[0],sizeof(nh_buf[0])),mpath_count);}cur_mpath=
next_mpath;}else{/**Ifhere,wehaveapathonthemp_listthatwasnot*previously*amultipa
th(duetonon-equivalanceormaxpaths*exceeded),*orthematchingmultipathissortedlater
inthe*multipath*list.Beforeweenqueuethepathonthenewmultipath*list,*makesureitsno
tontheold_bestmultipathlistor*referenced*vianext_mpath:*-Ifnext_mpathpointstothi
snewpath,update*next_mpathto*pointtothemultipathafterthisone*-Dequeuethepathfrom
themultipathlistjustto*makesure*/new_mpath=listgetdata(mp_node);list_delete_node
(mp_list,mp_node);if((mpath_count<maxpaths)&&(new_mpath!=new_best)&&bgp_info_nex
thop_cmp(prev_mpath,new_mpath)){if(new_mpath==next_mpath)bgp_info_mpath_next(new
_mpath);bgp_info_mpath_dequeue(new_mpath);bgp_info_mpath_enqueue(prev_mpath,new_
mpath);prev_mpath=new_mpath;mpath_changed=1;mpath_count++;if(debug){bgp_info_pat
h_with_addpath_rx_str(new_mpath,path_buf);zlog_debug("%s:addmpath%snexthop%s,cur
count%d",pfx_buf,path_buf,inet_ntop(AF_INET,&new_mpath->attr->nexthop,nh_buf[0],
sizeof(nh_buf[0])),mpath_count);}}mp_node=mp_next_node;}}if(new_best){if(debug)z
log_debug("%s:Newmpathcount(inclnewbest)%dmpath-change%s",pfx_buf,mpath_count,mp
ath_changed?"YES":"NO");bgp_info_mpath_count_set(new_best,mpath_count-1);if(mpat
h_changed||(bgp_info_mpath_count(new_best)!=old_mpath_count))SET_FLAG(new_best->
flags,BGP_INFO_MULTIPATH_CHG);}}/**bgp_mp_dmed_deselect**Cleanupmultipathinforma
tionforBGP_INFO_DMED_SELECTEDpaththat*isnotselectedasbestpath*/voidbgp_mp_dmed_d
eselect(structbgp_info*dmed_best){structbgp_info*mpinfo,*mpnext;if(!dmed_best)re
turn;for(mpinfo=bgp_info_mpath_first(dmed_best);mpinfo;mpinfo=mpnext){mpnext=bgp
_info_mpath_next(mpinfo);bgp_info_mpath_dequeue(mpinfo);}bgp_info_mpath_count_se
t(dmed_best,0);UNSET_FLAG(dmed_best->flags,BGP_INFO_MULTIPATH_CHG);assert(bgp_in
fo_mpath_first(dmed_best)==0);}/**bgp_info_mpath_aggregate_update**Setthemultipa
thaggregateattribute.Weneedtoseeifthe*aggregatehaschangedandthensettheATTR_CHANG
EDflagonthe*bestpathinfosothatapeerupdatewillbegenerated.The*changeisdetectedbyg
eneratingthecurrentattribute,*interningit,andthencomparingtheinternedpointerwith
the*currentvalue.Wecanskipthisgenerate/comparestepifthere*isnochangeinmultipaths
electionandnoattributechangein*anymultipath.*/voidbgp_info_mpath_aggregate_updat
e(structbgp_info*new_best,structbgp_info*old_best){structbgp_info*mpinfo;structa
spath*aspath;structaspath*asmerge;structattr*new_attr,*old_attr;uint8_torigin;st
ructcommunity*community,*commerge;structecommunity*ecomm,*ecommerge;structlcommu
nity*lcomm,*lcommerge;structattrattr={0};if(old_best&&(old_best!=new_best)&&(old
_attr=bgp_info_mpath_attr(old_best))){bgp_attr_unintern(&old_attr);bgp_info_mpat
h_attr_set(old_best,NULL);}if(!new_best)return;if(!bgp_info_mpath_count(new_best
)){if((new_attr=bgp_info_mpath_attr(new_best))){bgp_attr_unintern(&new_attr);bgp
_info_mpath_attr_set(new_best,NULL);SET_FLAG(new_best->flags,BGP_INFO_ATTR_CHANG
ED);}return;}bgp_attr_dup(&attr,new_best->attr);if(new_best->peer&&bgp_flag_chec
k(new_best->peer->bgp,BGP_FLAG_MULTIPATH_RELAX_AS_SET)){/*aggregateattributefrom
multipathconstituents*/aspath=aspath_dup(attr.aspath);origin=attr.origin;communi
ty=attr.community?community_dup(attr.community):NULL;ecomm=(attr.ecommunity)?eco
mmunity_dup(attr.ecommunity):NULL;lcomm=(attr.lcommunity)?lcommunity_dup(attr.lc
ommunity):NULL;for(mpinfo=bgp_info_mpath_first(new_best);mpinfo;mpinfo=bgp_info_
mpath_next(mpinfo)){asmerge=aspath_aggregate(aspath,mpinfo->attr->aspath);aspath
_free(aspath);aspath=asmerge;if(origin<mpinfo->attr->origin)origin=mpinfo->attr-
>origin;if(mpinfo->attr->community){if(community){commerge=community_merge(commu
nity,mpinfo->attr->community);community=community_uniq_sort(commerge);community_
free(commerge);}elsecommunity=community_dup(mpinfo->attr->community);}if(mpinfo-
>attr->ecommunity){if(ecomm){ecommerge=ecommunity_merge(ecomm,mpinfo->attr->ecom
munity);ecomm=ecommunity_uniq_sort(ecommerge);ecommunity_free(&ecommerge);}elsee
comm=ecommunity_dup(mpinfo->attr->ecommunity);}if(mpinfo->attr->lcommunity){if(l
comm){lcommerge=lcommunity_merge(lcomm,mpinfo->attr->lcommunity);lcomm=lcommunit
y_uniq_sort(lcommerge);lcommunity_free(&lcommerge);}elselcomm=lcommunity_dup(mpi
nfo->attr->lcommunity);}}attr.aspath=aspath;attr.origin=origin;if(community){att
r.community=community;attr.flag|=ATTR_FLAG_BIT(BGP_ATTR_COMMUNITIES);}if(ecomm){
attr.ecommunity=ecomm;attr.flag|=ATTR_FLAG_BIT(BGP_ATTR_EXT_COMMUNITIES);}if(lco
mm){attr.lcommunity=lcomm;attr.flag|=ATTR_FLAG_BIT(BGP_ATTR_LARGE_COMMUNITIES);}
/*Zapmultipathattrnexthopsowesetnexthoptoself*/attr.nexthop.s_addr=0;memset(&att
r.mp_nexthop_global,0,sizeof(structin6_addr));/*TODO:shouldwesetATOMIC_AGGREGATE
andAGGREGATOR?*/}new_attr=bgp_attr_intern(&attr);if(new_attr!=bgp_info_mpath_att
r(new_best)){if((old_attr=bgp_info_mpath_attr(new_best)))bgp_attr_unintern(&old_
attr);bgp_info_mpath_attr_set(new_best,new_attr);SET_FLAG(new_best->flags,BGP_IN
FO_ATTR_CHANGED);}elsebgp_attr_unintern(&new_attr);}