/*BGPRDdefinitionsforBGP-basedVPNs(IP/EVPN)*--broughtoverfrombgpd/bgp_mplsvpn.h*
Copyright(C)2000KunihiroIshiguro<kunihiro@zebra.org>**ThisfileispartofFRR.**FRRi
sfreesoftware;youcanredistributeitand/ormodifyit*underthetermsoftheGNUGeneralPub
licLicenseaspublishedbythe*FreeSoftwareFoundation;eitherversion2,or(atyouroption
)any*laterversion.**FRRisdistributedinthehopethatitwillbeuseful,but*WITHOUTANYWA
RRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTICULARPUR
POSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldhavereceivedacopyof
theGNUGeneralPublicLicense*alongwithFRR;seethefileCOPYING.Ifnot,writetotheFree*S
oftwareFoundation,Inc.,59TemplePlace-Suite330,Boston,MA*02111-1307,USA.*/#ifndef
_QUAGGA_BGP_RD_H#define_QUAGGA_BGP_RD_H/*RDtypes*/#defineRD_TYPE_AS0#defineRD_TY
PE_IP1#defineRD_TYPE_AS42#ifENABLE_BGP_VNC#defineRD_TYPE_VNC_ETH0xff00/*VNCL2VPN
*/#endif#defineRD_ADDRSTRLEN28structrd_as{uint16_ttype;as_tas;uint32_tval;};stru
ctrd_ip{uint16_ttype;structin_addrip;uint16_tval;};#ifENABLE_BGP_VNCstructrd_vnc
_eth{uint16_ttype;uint8_tlocal_nve_id;structethaddrmacaddr;};#endifexternuint16_
tdecode_rd_type(uint8_t*pnt);externvoidencode_rd_type(uint16_t,uint8_t*);externv
oiddecode_rd_as(uint8_t*pnt,structrd_as*rd_as);externvoiddecode_rd_as4(uint8_t*p
nt,structrd_as*rd_as);externvoiddecode_rd_ip(uint8_t*pnt,structrd_ip*rd_ip);#ifE
NABLE_BGP_VNCexternvoiddecode_rd_vnc_eth(uint8_t*pnt,structrd_vnc_eth*rd_vnc_eth
);#endifexternintstr2prefix_rd(constchar*,structprefix_rd*);externchar*prefix_rd
2str(structprefix_rd*,char*,size_t);#endif/*_QUAGGA_BGP_RD_H*/