/*BGProutingtable*Copyright(C)1998,2001KunihiroIshiguro**ThisfileispartofGNUZebr
a.**GNUZebraisfreesoftware;youcanredistributeitand/ormodifyit*underthetermsofthe
GNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eitherversion2,or
(atyouroption)any*laterversion.**GNUZebraisdistributedinthehopethatitwillbeusefu
l,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNES
SFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldh
avereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPY
ING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,
MA02110-1301USA*/#include<zebra.h>#include"prefix.h"#include"memory.h"#include"s
ockunion.h"#include"queue.h"#include"filter.h"#include"command.h"#include"bgpd/b
gpd.h"#include"bgpd/bgp_table.h"voidbgp_table_lock(structbgp_table*rt){rt->lock+
+;}voidbgp_table_unlock(structbgp_table*rt){assert(rt->lock>0);rt->lock--;if(rt-
>lock!=0){return;}route_table_finish(rt->route_table);rt->route_table=NULL;XFREE
(MTYPE_BGP_TABLE,rt);}voidbgp_table_finish(structbgp_table**rt){if(*rt!=NULL){bg
p_table_unlock(*rt);*rt=NULL;}}/**bgp_node_create*/staticstructroute_node*bgp_no
de_create(route_table_delegate_t*delegate,structroute_table*table){structbgp_nod
e*node;node=XCALLOC(MTYPE_BGP_NODE,sizeof(structbgp_node));returnbgp_node_to_rno
de(node);}/**bgp_node_destroy*/staticvoidbgp_node_destroy(route_table_delegate_t
*delegate,structroute_table*table,structroute_node*node){structbgp_node*bgp_node
;bgp_node=bgp_node_from_rnode(node);XFREE(MTYPE_BGP_NODE,bgp_node);}/**Functionv
ectortocustomizethebehavioroftheroutetable*libraryforBGProutetables.*/route_tabl
e_delegate_tbgp_table_delegate={.create_node=bgp_node_create,.destroy_node=bgp_n
ode_destroy};/**bgp_table_init*/structbgp_table*bgp_table_init(afi_tafi,safi_tsa
fi){structbgp_table*rt;rt=XCALLOC(MTYPE_BGP_TABLE,sizeof(structbgp_table));rt->r
oute_table=route_table_init_with_delegate(&bgp_table_delegate);/**Setupbackpoint
ertobgp_table.*/rt->route_table->info=rt;bgp_table_lock(rt);rt->afi=afi;rt->safi
=safi;returnrt;}