/*zebraclient*Copyright(C)1997,98,99KunihiroIshiguro**ThisfileispartofGNUZebra.*
*GNUZebraisfreesoftware;youcanredistributeitand/ormodifyit*underthetermsoftheGNU
GeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eitherversion2,or(at
youroption)any*laterversion.**GNUZebraisdistributedinthehopethatitwillbeuseful,b
ut*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFO
RAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldhave
receivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING
;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA0
2110-1301USA*/#include<zebra.h>#include"command.h"#include"stream.h"#include"net
work.h"#include"prefix.h"#include"log.h"#include"sockunion.h"#include"zclient.h"
#include"routemap.h"#include"thread.h"#include"queue.h"#include"memory.h"#includ
e"lib/json.h"#include"lib/bfd.h"#include"filter.h"#include"mpls.h"#include"vxlan
.h"#include"bgpd/bgpd.h"#include"bgpd/bgp_route.h"#include"bgpd/bgp_attr.h"#incl
ude"bgpd/bgp_nexthop.h"#include"bgpd/bgp_zebra.h"#include"bgpd/bgp_fsm.h"#includ
e"bgpd/bgp_debug.h"#include"bgpd/bgp_mpath.h"#include"bgpd/bgp_nexthop.h"#includ
e"bgpd/bgp_nht.h"#include"bgpd/bgp_bfd.h"#include"bgpd/bgp_label.h"#ifENABLE_BGP
_VNC#include"bgpd/rfapi/rfapi_backend.h"#include"bgpd/rfapi/vnc_export_bgp.h"#en
dif#include"bgpd/bgp_evpn.h"#include"bgpd/bgp_mplsvpn.h"/*Allinformationaboutzeb
ra.*/structzclient*zclient=NULL;/*Canweinstallintozebra?*/staticinlineintbgp_ins
tall_info_to_zebra(structbgp*bgp){if(zclient->sock<=0)return0;if(!IS_BGP_INST_KN
OWN_TO_ZEBRA(bgp))return0;return1;}intzclient_num_connects;/*Router-idupdatemess
agefromzebra.*/staticintbgp_router_id_update(intcommand,structzclient*zclient,ze
bra_size_tlength,vrf_id_tvrf_id){structprefixrouter_id;zebra_router_id_update_re
ad(zclient->ibuf,&router_id);if(BGP_DEBUG(zebra,ZEBRA)){charbuf[PREFIX2STR_BUFFE
R];prefix2str(&router_id,buf,sizeof(buf));zlog_debug("RxRouterIdupdateVRF%uId%s"
,vrf_id,buf);}bgp_router_id_zebra_bump(vrf_id,&router_id);return0;}/*Nexthopupda
temessagefromzebra.*/staticintbgp_read_nexthop_update(intcommand,structzclient*z
client,zebra_size_tlength,vrf_id_tvrf_id){bgp_parse_nexthop_update(command,vrf_i
d);return0;}staticintbgp_read_import_check_update(intcommand,structzclient*zclie
nt,zebra_size_tlength,vrf_id_tvrf_id){bgp_parse_nexthop_update(command,vrf_id);r
eturn0;}/*Setorclearinterfaceonwhichunnumberedneighborisconfigured.This*wouldint
urncauseBGPtoinitiateorturnoffIPv6RAsonthis*interface.*/staticvoidbgp_update_int
erface_nbrs(structbgp*bgp,structinterface*ifp,structinterface*upd_ifp){structlis
tnode*node,*nnode;structpeer*peer;for(ALL_LIST_ELEMENTS(bgp->peer,node,nnode,pee
r)){if(peer->conf_if&&(strcmp(peer->conf_if,ifp->name)==0)){if(upd_ifp){peer->if
p=upd_ifp;bgp_zebra_initiate_radv(bgp,peer);}else{bgp_zebra_terminate_radv(bgp,p
eer);peer->ifp=upd_ifp;}}}}staticintbgp_read_fec_update(intcommand,structzclient
*zclient,zebra_size_tlength){bgp_parse_fec_update();return0;}staticvoidbgp_start
_interface_nbrs(structbgp*bgp,structinterface*ifp){structlistnode*node,*nnode;st
ructpeer*peer;for(ALL_LIST_ELEMENTS(bgp->peer,node,nnode,peer)){if(peer->conf_if
&&(strcmp(peer->conf_if,ifp->name)==0)&&peer->status!=Established){if(peer_activ
e(peer))BGP_EVENT_ADD(peer,BGP_Stop);BGP_EVENT_ADD(peer,BGP_Start);}}}staticvoid
bgp_nbr_connected_add(structbgp*bgp,structnbr_connected*ifc){structlistnode*node
;structconnected*connected;structinterface*ifp;structprefix*p;/*Kick-offtheFSMfo
ranyrelevantpeersonlyifthereisa*validlocaladdressontheinterface.*/ifp=ifc->ifp;f
or(ALL_LIST_ELEMENTS_RO(ifp->connected,node,connected)){p=connected->address;if(
p->family==AF_INET6&&IN6_IS_ADDR_LINKLOCAL(&p->u.prefix6))break;}if(!connected)r
eturn;bgp_start_interface_nbrs(bgp,ifp);}staticvoidbgp_nbr_connected_delete(stru
ctbgp*bgp,structnbr_connected*ifc,intdel){structlistnode*node,*nnode;structpeer*
peer;structinterface*ifp;for(ALL_LIST_ELEMENTS(bgp->peer,node,nnode,peer)){if(pe
er->conf_if&&(strcmp(peer->conf_if,ifc->ifp->name)==0)){peer->last_reset=PEER_DO
WN_NBR_ADDR_DEL;BGP_EVENT_ADD(peer,BGP_Stop);}}/*Freeneighboralso,ifwe'reaskedto
.*/if(del){ifp=ifc->ifp;listnode_delete(ifp->nbr_connected,ifc);nbr_connected_fr
ee(ifc);}}/*Intefaceadditionmessagefromzebra.*/staticintbgp_interface_add(intcom
mand,structzclient*zclient,zebra_size_tlength,vrf_id_tvrf_id){structinterface*if
p;structbgp*bgp;ifp=zebra_interface_add_read(zclient->ibuf,vrf_id);if(!ifp)//une
xpectedreturn0;if(BGP_DEBUG(zebra,ZEBRA)&&ifp)zlog_debug("RxIntfaddVRF%uIF%s",vr
f_id,ifp->name);bgp=bgp_lookup_by_vrf_id(vrf_id);if(!bgp)return0;bgp_update_inte
rface_nbrs(bgp,ifp,ifp);return0;}staticintbgp_interface_delete(intcommand,struct
zclient*zclient,zebra_size_tlength,vrf_id_tvrf_id){structstream*s;structinterfac
e*ifp;structbgp*bgp;bgp=bgp_lookup_by_vrf_id(vrf_id);if(!bgp)return0;s=zclient->
ibuf;ifp=zebra_interface_state_read(s,vrf_id);if(!ifp)/*Thismayhappenifwe'vejust
unregisteredforaVRF.*/return0;if(BGP_DEBUG(zebra,ZEBRA))zlog_debug("RxIntfdelVRF
%uIF%s",vrf_id,ifp->name);bgp_update_interface_nbrs(bgp,ifp,NULL);if_set_index(i
fp,IFINDEX_INTERNAL);return0;}staticintbgp_interface_up(intcommand,structzclient
*zclient,zebra_size_tlength,vrf_id_tvrf_id){structstream*s;structinterface*ifp;s
tructconnected*c;structnbr_connected*nc;structlistnode*node,*nnode;structbgp*bgp
;bgp=bgp_lookup_by_vrf_id(vrf_id);if(!bgp)return0;s=zclient->ibuf;ifp=zebra_inte
rface_state_read(s,vrf_id);if(!ifp)return0;if(BGP_DEBUG(zebra,ZEBRA))zlog_debug(
"RxIntfupVRF%uIF%s",vrf_id,ifp->name);for(ALL_LIST_ELEMENTS(ifp->connected,node,
nnode,c))bgp_connected_add(bgp,c);for(ALL_LIST_ELEMENTS(ifp->nbr_connected,node,
nnode,nc))bgp_nbr_connected_add(bgp,nc);return0;}staticintbgp_interface_down(int
command,structzclient*zclient,zebra_size_tlength,vrf_id_tvrf_id){structstream*s;
structinterface*ifp;structconnected*c;structnbr_connected*nc;structlistnode*node
,*nnode;structbgp*bgp;bgp=bgp_lookup_by_vrf_id(vrf_id);if(!bgp)return0;s=zclient
->ibuf;ifp=zebra_interface_state_read(s,vrf_id);if(!ifp)return0;if(BGP_DEBUG(zeb
ra,ZEBRA))zlog_debug("RxIntfdownVRF%uIF%s",vrf_id,ifp->name);for(ALL_LIST_ELEMEN
TS(ifp->connected,node,nnode,c))bgp_connected_delete(bgp,c);for(ALL_LIST_ELEMENT
S(ifp->nbr_connected,node,nnode,nc))bgp_nbr_connected_delete(bgp,nc,1);/*Fastext
ernal-failover*/{structpeer*peer;if(CHECK_FLAG(bgp->flags,BGP_FLAG_NO_FAST_EXT_F
AILOVER))return0;for(ALL_LIST_ELEMENTS(bgp->peer,node,nnode,peer)){#ifdefined(HA
VE_CUMULUS)/*TakedowndirectlyconnectedEBGPpeersaswellas*1-hopBFD*tracked(directl
yconnected)IBGPpeers.*/if((peer->ttl!=1)&&(peer->gtsm_hops!=1)&&(!peer->bfd_info
||bgp_bfd_is_peer_multihop(peer)))#else/*TakedowndirectlyconnectedEBGPpeers*/if(
(peer->ttl!=1)&&(peer->gtsm_hops!=1))#endifcontinue;if(ifp==peer->nexthop.ifp){B
GP_EVENT_ADD(peer,BGP_Stop);peer->last_reset=PEER_DOWN_IF_DOWN;}}}return0;}stati
cintbgp_interface_address_add(intcommand,structzclient*zclient,zebra_size_tlengt
h,vrf_id_tvrf_id){structconnected*ifc;structbgp*bgp;bgp=bgp_lookup_by_vrf_id(vrf
_id);if(!bgp)return0;ifc=zebra_interface_address_read(command,zclient->ibuf,vrf_
id);if(ifc==NULL)return0;if(bgp_debug_zebra(ifc->address)){charbuf[PREFIX2STR_BU
FFER];prefix2str(ifc->address,buf,sizeof(buf));zlog_debug("RxIntfaddressaddVRF%u
IF%saddr%s",vrf_id,ifc->ifp->name,buf);}if(if_is_operative(ifc->ifp)){bgp_connec
ted_add(bgp,ifc);/*Ifwehavelearntofanyneighborsonthisinterface,*checktokickoffan
yBGPinterface-basedneighbors,*butonlyifthisisalink-localaddress.*/if(IN6_IS_ADDR
_LINKLOCAL(&ifc->address->u.prefix6)&&!list_isempty(ifc->ifp->nbr_connected))bgp
_start_interface_nbrs(bgp,ifc->ifp);}return0;}staticintbgp_interface_address_del
ete(intcommand,structzclient*zclient,zebra_size_tlength,vrf_id_tvrf_id){structco
nnected*ifc;structbgp*bgp;bgp=bgp_lookup_by_vrf_id(vrf_id);if(!bgp)return0;ifc=z
ebra_interface_address_read(command,zclient->ibuf,vrf_id);if(ifc==NULL)return0;i
f(bgp_debug_zebra(ifc->address)){charbuf[PREFIX2STR_BUFFER];prefix2str(ifc->addr
ess,buf,sizeof(buf));zlog_debug("RxIntfaddressdelVRF%uIF%saddr%s",vrf_id,ifc->if
p->name,buf);}if(if_is_operative(ifc->ifp)){bgp_connected_delete(bgp,ifc);}conne
cted_free(ifc);return0;}staticintbgp_interface_nbr_address_add(intcommand,struct
zclient*zclient,zebra_size_tlength,vrf_id_tvrf_id){structnbr_connected*ifc=NULL;
structbgp*bgp;ifc=zebra_interface_nbr_address_read(command,zclient->ibuf,vrf_id)
;if(ifc==NULL)return0;if(bgp_debug_zebra(ifc->address)){charbuf[PREFIX2STR_BUFFE
R];prefix2str(ifc->address,buf,sizeof(buf));zlog_debug("RxIntfneighboraddVRF%uIF
%saddr%s",vrf_id,ifc->ifp->name,buf);}if(if_is_operative(ifc->ifp)){bgp=bgp_look
up_by_vrf_id(vrf_id);if(bgp)bgp_nbr_connected_add(bgp,ifc);}return0;}staticintbg
p_interface_nbr_address_delete(intcommand,structzclient*zclient,zebra_size_tleng
th,vrf_id_tvrf_id){structnbr_connected*ifc=NULL;structbgp*bgp;ifc=zebra_interfac
e_nbr_address_read(command,zclient->ibuf,vrf_id);if(ifc==NULL)return0;if(bgp_deb
ug_zebra(ifc->address)){charbuf[PREFIX2STR_BUFFER];prefix2str(ifc->address,buf,s
izeof(buf));zlog_debug("RxIntfneighbordelVRF%uIF%saddr%s",vrf_id,ifc->ifp->name,
buf);}if(if_is_operative(ifc->ifp)){bgp=bgp_lookup_by_vrf_id(vrf_id);if(bgp)bgp_
nbr_connected_delete(bgp,ifc,0);}nbr_connected_free(ifc);return0;}/*VRFupdatefor
aninterface.*/staticintbgp_interface_vrf_update(intcommand,structzclient*zclient
,zebra_size_tlength,vrf_id_tvrf_id){structinterface*ifp;vrf_id_tnew_vrf_id;struc
tconnected*c;structnbr_connected*nc;structlistnode*node,*nnode;structbgp*bgp;ifp
=zebra_interface_vrf_update_read(zclient->ibuf,vrf_id,&new_vrf_id);if(!ifp)retur
n0;if(BGP_DEBUG(zebra,ZEBRA)&&ifp)zlog_debug("RxIntfVRFchangeVRF%uIF%sNewVRF%u",
vrf_id,ifp->name,new_vrf_id);bgp=bgp_lookup_by_vrf_id(vrf_id);if(!bgp)return0;fo
r(ALL_LIST_ELEMENTS(ifp->connected,node,nnode,c))bgp_connected_delete(bgp,c);for
(ALL_LIST_ELEMENTS(ifp->nbr_connected,node,nnode,nc))bgp_nbr_connected_delete(bg
p,nc,1);/*Fastexternal-failover*/{structpeer*peer;if(CHECK_FLAG(bgp->flags,BGP_F
LAG_NO_FAST_EXT_FAILOVER))return0;for(ALL_LIST_ELEMENTS(bgp->peer,node,nnode,pee
r)){if((peer->ttl!=1)&&(peer->gtsm_hops!=1))continue;if(ifp==peer->nexthop.ifp)B
GP_EVENT_ADD(peer,BGP_Stop);}}if_update_to_new_vrf(ifp,new_vrf_id);bgp=bgp_looku
p_by_vrf_id(new_vrf_id);if(!bgp)return0;for(ALL_LIST_ELEMENTS(ifp->connected,nod
e,nnode,c))bgp_connected_add(bgp,c);for(ALL_LIST_ELEMENTS(ifp->nbr_connected,nod
e,nnode,nc))bgp_nbr_connected_add(bgp,nc);return0;}/*Zebrarouteaddanddeletetreat
ment.*/staticintzebra_read_route(intcommand,structzclient*zclient,zebra_size_tle
ngth,vrf_id_tvrf_id){enumnexthop_types_tnhtype;structzapi_routeapi;uniong_addrne
xthop;ifindex_tifindex;intadd,i;structbgp*bgp;bgp=bgp_lookup_by_vrf_id(vrf_id);i
f(!bgp)return0;if(zapi_route_decode(zclient->ibuf,&api)<0)return-1;/*wecompletel
yignoresrcdestroutesfornow.*/if(CHECK_FLAG(api.message,ZAPI_MESSAGE_SRCPFX))retu
rn0;/*ignorelink-localaddress.*/if(api.prefix.family==AF_INET6&&IN6_IS_ADDR_LINK
LOCAL(&api.prefix.u.prefix6))return0;nexthop=api.nexthops[0].gate;ifindex=api.ne
xthops[0].ifindex;nhtype=api.nexthops[0].type;add=(command==ZEBRA_REDISTRIBUTE_R
OUTE_ADD);if(add){/**TheADDmessageisactuallyanUPDATEandthereisno*explicitDEL*for
apriorredistributedroute,ifany.So,performan*implicit*DELprocessingforthesameredi
stributedroutefromany*other*sourcetype.*/for(i=0;i<ZEBRA_ROUTE_MAX;i++){if(i!=ap
i.type)bgp_redistribute_delete(bgp,&api.prefix,i,api.instance);}/*Nowperformthea
dd/update.*/bgp_redistribute_add(bgp,&api.prefix,&nexthop,ifindex,nhtype,api.met
ric,api.type,api.instance,api.tag);}else{bgp_redistribute_delete(bgp,&api.prefix
,api.type,api.instance);}if(bgp_debug_zebra(&api.prefix)){charbuf[2][PREFIX_STRL
EN];prefix2str(&api.prefix,buf[0],sizeof(buf[0]));inet_ntop(api.prefix.family,&n
exthop,buf[1],sizeof(buf[1]));zlog_debug("Rxroute%sVRF%u%s[%d]%s""nexthop%smetri
c%utag%"ROUTE_TAG_PRI,(add)?"add":"delete",vrf_id,zebra_route_string(api.type),a
pi.instance,buf[0],buf[1],api.metric,api.tag);}return0;}structinterface*if_looku
p_by_ipv4(structin_addr*addr,vrf_id_tvrf_id){structvrf*vrf;structlistnode*cnode;
structinterface*ifp;structconnected*connected;structprefix_ipv4p;structprefix*cp
;vrf=vrf_lookup_by_id(vrf_id);if(!vrf)returnNULL;p.family=AF_INET;p.prefix=*addr
;p.prefixlen=IPV4_MAX_BITLEN;FOR_ALL_INTERFACES(vrf,ifp){for(ALL_LIST_ELEMENTS_R
O(ifp->connected,cnode,connected)){cp=connected->address;if(cp->family==AF_INET)
if(prefix_match(cp,(structprefix*)&p))returnifp;}}returnNULL;}structinterface*if
_lookup_by_ipv4_exact(structin_addr*addr,vrf_id_tvrf_id){structvrf*vrf;structlis
tnode*cnode;structinterface*ifp;structconnected*connected;structprefix*cp;vrf=vr
f_lookup_by_id(vrf_id);if(!vrf)returnNULL;FOR_ALL_INTERFACES(vrf,ifp){for(ALL_LI
ST_ELEMENTS_RO(ifp->connected,cnode,connected)){cp=connected->address;if(cp->fam
ily==AF_INET)if(IPV4_ADDR_SAME(&cp->u.prefix4,addr))returnifp;}}returnNULL;}stru
ctinterface*if_lookup_by_ipv6(structin6_addr*addr,ifindex_tifindex,vrf_id_tvrf_i
d){structvrf*vrf;structlistnode*cnode;structinterface*ifp;structconnected*connec
ted;structprefix_ipv6p;structprefix*cp;vrf=vrf_lookup_by_id(vrf_id);if(!vrf)retu
rnNULL;p.family=AF_INET6;p.prefix=*addr;p.prefixlen=IPV6_MAX_BITLEN;FOR_ALL_INTE
RFACES(vrf,ifp){for(ALL_LIST_ELEMENTS_RO(ifp->connected,cnode,connected)){cp=con
nected->address;if(cp->family==AF_INET6)if(prefix_match(cp,(structprefix*)&p)){i
f(IN6_IS_ADDR_LINKLOCAL(&cp->u.prefix6)){if(ifindex==ifp->ifindex)returnifp;}els
ereturnifp;}}}returnNULL;}structinterface*if_lookup_by_ipv6_exact(structin6_addr
*addr,ifindex_tifindex,vrf_id_tvrf_id){structvrf*vrf;structlistnode*cnode;struct
interface*ifp;structconnected*connected;structprefix*cp;vrf=vrf_lookup_by_id(vrf
_id);if(!vrf)returnNULL;FOR_ALL_INTERFACES(vrf,ifp){for(ALL_LIST_ELEMENTS_RO(ifp
->connected,cnode,connected)){cp=connected->address;if(cp->family==AF_INET6)if(I
PV6_ADDR_SAME(&cp->u.prefix6,addr)){if(IN6_IS_ADDR_LINKLOCAL(&cp->u.prefix6)){if
(ifindex==ifp->ifindex)returnifp;}elsereturnifp;}}}returnNULL;}staticintif_get_i
pv6_global(structinterface*ifp,structin6_addr*addr){structlistnode*cnode;structc
onnected*connected;structprefix*cp;for(ALL_LIST_ELEMENTS_RO(ifp->connected,cnode
,connected)){cp=connected->address;if(cp->family==AF_INET6)if(!IN6_IS_ADDR_LINKL
OCAL(&cp->u.prefix6)){memcpy(addr,&cp->u.prefix6,IPV6_MAX_BYTELEN);return1;}}ret
urn0;}staticintif_get_ipv6_local(structinterface*ifp,structin6_addr*addr){struct
listnode*cnode;structconnected*connected;structprefix*cp;for(ALL_LIST_ELEMENTS_R
O(ifp->connected,cnode,connected)){cp=connected->address;if(cp->family==AF_INET6
)if(IN6_IS_ADDR_LINKLOCAL(&cp->u.prefix6)){memcpy(addr,&cp->u.prefix6,IPV6_MAX_B
YTELEN);return1;}}return0;}staticintif_get_ipv4_address(structinterface*ifp,stru
ctin_addr*addr){structlistnode*cnode;structconnected*connected;structprefix*cp;f
or(ALL_LIST_ELEMENTS_RO(ifp->connected,cnode,connected)){cp=connected->address;i
f((cp->family==AF_INET)&&!ipv4_martian(&(cp->u.prefix4))){*addr=cp->u.prefix4;re
turn1;}}return0;}intbgp_nexthop_set(unionsockunion*local,unionsockunion*remote,s
tructbgp_nexthop*nexthop,structpeer*peer){intret=0;structinterface*ifp=NULL;mems
et(nexthop,0,sizeof(structbgp_nexthop));if(!local)return-1;if(!remote)return-1;i
f(local->sa.sa_family==AF_INET){nexthop->v4=local->sin.sin_addr;if(peer->update_
if)ifp=if_lookup_by_name(peer->update_if,peer->bgp->vrf_id);elseifp=if_lookup_by
_ipv4_exact(&local->sin.sin_addr,peer->bgp->vrf_id);}if(local->sa.sa_family==AF_
INET6){if(IN6_IS_ADDR_LINKLOCAL(&local->sin6.sin6_addr)){if(peer->conf_if||peer-
>ifname)ifp=if_lookup_by_name(peer->conf_if?peer->conf_if:peer->ifname,peer->bgp
->vrf_id);}elseif(peer->update_if)ifp=if_lookup_by_name(peer->update_if,peer->bg
p->vrf_id);elseifp=if_lookup_by_ipv6_exact(&local->sin6.sin6_addr,local->sin6.si
n6_scope_id,peer->bgp->vrf_id);}if(!ifp)return-1;nexthop->ifp=ifp;/*IPv4connecti
on,fetchandstoreIPv6localaddress(es)ifany.*/if(local->sa.sa_family==AF_INET){/*I
Pv6nexthop*/ret=if_get_ipv6_global(ifp,&nexthop->v6_global);if(!ret){/*Thereisno
globalnexthop.Uselink-localaddressas*boththe*globalandlink-localnexthop.Inthissc
enario,the*expectation*forinteropisthatthenetworkadminwouldusea*route-mapto*spec
ifytheglobalIPv6nexthop.*/if_get_ipv6_local(ifp,&nexthop->v6_global);memcpy(&nex
thop->v6_local,&nexthop->v6_global,IPV6_MAX_BYTELEN);}elseif_get_ipv6_local(ifp,
&nexthop->v6_local);if(if_lookup_by_ipv4(&remote->sin.sin_addr,peer->bgp->vrf_id
))peer->shared_network=1;elsepeer->shared_network=0;}/*IPv6connection,fetchandst
oreIPv4localaddressifany.*/if(local->sa.sa_family==AF_INET6){structinterface*dir
ect=NULL;/*IPv4nexthop.*/ret=if_get_ipv4_address(ifp,&nexthop->v4);if(!ret&&peer
->local_id.s_addr)nexthop->v4=peer->local_id;/*Globaladdress*/if(!IN6_IS_ADDR_LI
NKLOCAL(&local->sin6.sin6_addr)){memcpy(&nexthop->v6_global,&local->sin6.sin6_ad
dr,IPV6_MAX_BYTELEN);/*Ifdirectoryconnectedsetlink-localaddress.*/direct=if_look
up_by_ipv6(&remote->sin6.sin6_addr,remote->sin6.sin6_scope_id,peer->bgp->vrf_id)
;if(direct)if_get_ipv6_local(ifp,&nexthop->v6_local);}else/*Link-localaddress.*/
{ret=if_get_ipv6_global(ifp,&nexthop->v6_global);/*Ifthereisnoglobaladdress.Setl
ink-localaddressasglobal.IknowthisbreakRFCspecification...*//*Inthisscenario,the
expectationforinteropisthat*the*networkadminwouldusearoute-maptospecifythe*globa
l*IPv6nexthop.*/if(!ret)memcpy(&nexthop->v6_global,&local->sin6.sin6_addr,IPV6_M
AX_BYTELEN);/*Alwayssetthelink-localaddress*/memcpy(&nexthop->v6_local,&local->s
in6.sin6_addr,IPV6_MAX_BYTELEN);}if(IN6_IS_ADDR_LINKLOCAL(&local->sin6.sin6_addr
)||if_lookup_by_ipv6(&remote->sin6.sin6_addr,remote->sin6.sin6_scope_id,peer->bg
p->vrf_id))peer->shared_network=1;elsepeer->shared_network=0;}/*KAMEstackspecifi
ctreatment.*/#ifdefKAMEif(IN6_IS_ADDR_LINKLOCAL(&nexthop->v6_global)&&IN6_LINKLO
CAL_IFINDEX(nexthop->v6_global)){SET_IN6_LINKLOCAL_IFINDEX(nexthop->v6_global,0)
;}if(IN6_IS_ADDR_LINKLOCAL(&nexthop->v6_local)&&IN6_LINKLOCAL_IFINDEX(nexthop->v
6_local)){SET_IN6_LINKLOCAL_IFINDEX(nexthop->v6_local,0);}#endif/*KAME*//*Ifweha
veidentifiedthelocalinterface,thereisnoerrorfornow.*/return0;}staticstructin6_ad
dr*bgp_info_to_ipv6_nexthop(structbgp_info*info){structin6_addr*nexthop=NULL;/*O
nlyglobaladdressnexthopexists.*/if(info->attr->mp_nexthop_len==BGP_ATTR_NHLEN_IP
V6_GLOBAL)nexthop=&info->attr->mp_nexthop_global;/*Ifbothglobalandlink-localaddr
esspresent.*/if(info->attr->mp_nexthop_len==BGP_ATTR_NHLEN_IPV6_GLOBAL_AND_LL){/
*Checkifroute-mapissettopreferglobaloverlink-local*/if(info->attr->mp_nexthop_pr
efer_global)nexthop=&info->attr->mp_nexthop_global;else{/*WorkaroundforCisco'sne
xthopbug.*/if(IN6_IS_ADDR_UNSPECIFIED(&info->attr->mp_nexthop_global)&&info->pee
r->su_remote->sa.sa_family==AF_INET6)nexthop=&info->peer->su_remote->sin6.sin6_a
ddr;elsenexthop=&info->attr->mp_nexthop_local;}}returnnexthop;}staticintbgp_tabl
e_map_apply(structroute_map*map,structprefix*p,structbgp_info*info){route_map_re
sult_tret;ret=route_map_apply(map,p,RMAP_BGP,info);bgp_attr_flush(info->attr);if
(ret!=RMAP_DENYMATCH)return1;if(bgp_debug_zebra(p)){if(p->family==AF_INET){charb
uf[2][INET_ADDRSTRLEN];zlog_debug("Zebrarmapdeny:IPv4route%s/%dnexthop%s",inet_n
top(AF_INET,&p->u.prefix4,buf[0],sizeof(buf[0])),p->prefixlen,inet_ntop(AF_INET,
&info->attr->nexthop,buf[1],sizeof(buf[1])));}if(p->family==AF_INET6){charbuf[2]
[INET6_ADDRSTRLEN];zlog_debug("Zebrarmapdeny:IPv6route%s/%dnexthop%s",inet_ntop(
AF_INET6,&p->u.prefix6,buf[0],sizeof(buf[0])),p->prefixlen,inet_ntop(AF_INET6,bg
p_info_to_ipv6_nexthop(info),buf[1],sizeof(buf[1])));}}return0;}staticstructthre
ad*bgp_tm_thread_connect;staticboolbgp_tm_status_connected;staticintbgp_zebra_tm
_connect(structthread*t){structzclient*zclient;intdelay=10,ret=0;zclient=THREAD_
ARG(t);if(bgp_tm_status_connected&&zclient->sock>0)delay=60;else{bgp_tm_status_c
onnected=false;ret=tm_table_manager_connect(zclient);}if(ret<0){zlog_warn("Error
connectingtotablemanager!");bgp_tm_status_connected=false;}else{if(!bgp_tm_statu
s_connected)zlog_debug("Connectingtotablemanager.Success");bgp_tm_status_connect
ed=true;}thread_add_timer(bm->master,bgp_zebra_tm_connect,zclient,delay,&bgp_tm_
thread_connect);return0;}voidbgp_zebra_init_tm_connect(void){intdelay=1;/*ifalre
adyset,donothing*/if(bgp_tm_thread_connect!=NULL)return;bgp_tm_status_connected=
false;thread_add_timer(bm->master,bgp_zebra_tm_connect,zclient,delay,&bgp_tm_thr
ead_connect);}intbgp_zebra_get_table_range(uint32_tchunk_size,uint32_t*start,uin
t32_t*end){intret;if(!bgp_tm_status_connected)return-1;ret=tm_get_table_chunk(zc
lient,chunk_size,start,end);if(ret<0){zlog_err("BGP:Errorgettingtablechunk%u",ch
unk_size);return-1;}zlog_info("BGP:TableManagerreturnsrangefromchunk%uis[%u%u]",
chunk_size,*start,*end);return0;}voidbgp_zebra_announce(structbgp_node*rn,struct
prefix*p,structbgp_info*info,structbgp*bgp,afi_tafi,safi_tsafi){structzapi_route
api;structzapi_nexthop*api_nh;intnh_family;unsignedintvalid_nh_count=0;inthas_va
lid_label=0;uint8_tdistance;structpeer*peer;structbgp_info*mpinfo;uint32_tmetric
;structattrlocal_attr;structbgp_infolocal_info;structbgp_info*mpinfo_cp=&local_i
nfo;route_tag_ttag;mpls_label_tlabel;intnh_othervrf=0;/*Don'ttrytoinstallifwe're
notconnectedtoZebraorZebradoesn't*knowofthisinstance.*/if(!bgp_install_info_to_z
ebra(bgp))return;if(bgp->main_zebra_update_hold)return;/**vrfleakingsupport(will
haveonlyonenexthop)*/if(info->extra&&info->extra->bgp_orig)nh_othervrf=1;/*MakeZ
ebraAPIstructure.*/memset(&api,0,sizeof(api));memcpy(&api.rmac,&(info->attr->rma
c),sizeof(structethaddr));api.vrf_id=bgp->vrf_id;api.type=ZEBRA_ROUTE_BGP;api.sa
fi=safi;api.prefix=*p;SET_FLAG(api.message,ZAPI_MESSAGE_NEXTHOP);peer=info->peer
;if(info->type==ZEBRA_ROUTE_BGP&&info->sub_type==BGP_ROUTE_IMPORTED){structbgp_i
nfo*bi;/**Lookatparentchainforpeersort*/for(bi=info;bi->extra&&bi->extra->parent
;bi=bi->extra->parent){peer=((structbgp_info*)(bi->extra->parent))->peer;}}tag=i
nfo->attr->tag;/*WhenwecreateanaggregateroutewemustalsoinstallaNull0route*in*the
RIB*/if(info->sub_type==BGP_ROUTE_AGGREGATE)zapi_route_set_blackhole(&api,BLACKH
OLE_NULL);/*IfitisanEVPNroutemarkassuch.*Currentlypresenceofrmacinattrdenotes*th
isisanEVPNtype-2route*/if(info->sub_type==BGP_ROUTE_IMPORTED)SET_FLAG(api.flags,
ZEBRA_FLAG_EVPN_ROUTE);if(peer->sort==BGP_PEER_IBGP||peer->sort==BGP_PEER_CONFED
||info->sub_type==BGP_ROUTE_AGGREGATE){SET_FLAG(api.flags,ZEBRA_FLAG_IBGP);SET_F
LAG(api.flags,ZEBRA_FLAG_ALLOW_RECURSION);}if((peer->sort==BGP_PEER_EBGP&&peer->
ttl!=1)||CHECK_FLAG(peer->flags,PEER_FLAG_DISABLE_CONNECTED_CHECK)||bgp_flag_che
ck(bgp,BGP_FLAG_DISABLE_NH_CONNECTED_CHK))SET_FLAG(api.flags,ZEBRA_FLAG_ALLOW_RE
CURSION);/*Metriciscurrentlybasedonthebest-pathonly*/metric=info->attr->med;for(
mpinfo=info;mpinfo;mpinfo=bgp_info_mpath_next(mpinfo)){if(valid_nh_count>=multip
ath_num)break;*mpinfo_cp=*mpinfo;/*Getnexthopaddress-family*/if(p->family==AF_IN
ET&&!BGP_ATTR_NEXTHOP_AFI_IP6(mpinfo_cp->attr))nh_family=AF_INET;elseif(p->famil
y==AF_INET6||(p->family==AF_INET&&BGP_ATTR_NEXTHOP_AFI_IP6(mpinfo_cp->attr)))nh_
family=AF_INET6;elsecontinue;api_nh=&api.nexthops[valid_nh_count];api_nh->vrf_id
=nh_othervrf?info->extra->bgp_orig->vrf_id:bgp->vrf_id;if(nh_family==AF_INET){st
ructin_addr*nexthop;if(bgp_debug_zebra(&api.prefix)){charbuf_prefix[PREFIX_STRLE
N];prefix2str(&api.prefix,buf_prefix,sizeof(buf_prefix));if(mpinfo->extra){zlog_
debug("%s:p=%s,bgp_is_valid_label:%d",__func__,buf_prefix,bgp_is_valid_label(&mp
info->extra->label[0]));}else{zlog_debug("%s:p=%s,extraisNULL,nolabel",__func__,
buf_prefix);}}if(bgp->table_map[afi][safi].name||nh_othervrf){/*Copyinfoandattri
butes,sotheroute-mapapplydoesn'tmodifytheBGProuteinfo.*/local_attr=*mpinfo->attr
;mpinfo_cp->attr=&local_attr;if(nh_othervrf){/*allowroute-maptomodify*/local_att
r.nexthop=info->extra->nexthop_orig.u.prefix4;}}if(bgp->table_map[afi][safi].nam
e){if(!bgp_table_map_apply(bgp->table_map[afi][safi].map,p,mpinfo_cp))continue;/
*metric/tagisonlyallowedtobe*overriddenon1stnexthop*/if(mpinfo==info){metric=mpi
nfo_cp->attr->med;tag=mpinfo_cp->attr->tag;}}nexthop=&mpinfo_cp->attr->nexthop;a
pi_nh->gate.ipv4=*nexthop;/*EVPNtype-2routesareprogrammedasonlinkonl3-vniSVI*/if
(CHECK_FLAG(api.flags,ZEBRA_FLAG_EVPN_ROUTE))api_nh->type=NEXTHOP_TYPE_IPV4_IFIN
DEX;elseapi_nh->type=NEXTHOP_TYPE_IPV4;}else{ifindex_tifindex;structin6_addr*nex
thop;ifindex=0;if(bgp->table_map[afi][safi].name||nh_othervrf){/*Copyinfoandattr
ibutes,sotheroute-mapapplydoesn'tmodifytheBGProuteinfo.*/local_attr=*mpinfo->att
r;mpinfo_cp->attr=&local_attr;if(nh_othervrf){/*allowroute-maptomodify*/local_at
tr.mp_nexthop_global=info->extra->nexthop_orig.u.prefix6;local_attr.mp_nexthop_l
en=BGP_ATTR_NHLEN_IPV6_GLOBAL;}}if(bgp->table_map[afi][safi].name){/*Copyinfoand
attributes,sotheroute-mapapplydoesn'tmodifytheBGProuteinfo.*/local_attr=*mpinfo-
>attr;mpinfo_cp->attr=&local_attr;if(!bgp_table_map_apply(bgp->table_map[afi][sa
fi].map,p,mpinfo_cp))continue;/*metric/tagisonlyallowedtobe*overriddenon1stnexth
op*/if(mpinfo==info){metric=mpinfo_cp->attr->med;tag=mpinfo_cp->attr->tag;}}next
hop=bgp_info_to_ipv6_nexthop(mpinfo_cp);if((mpinfo==info)&&mpinfo->attr->mp_next
hop_len==BGP_ATTR_NHLEN_IPV6_GLOBAL_AND_LL)if(mpinfo->peer->nexthop.ifp)ifindex=
mpinfo->peer->nexthop.ifp->ifindex;if(!ifindex){if(mpinfo->peer->conf_if)ifindex
=mpinfo->peer->ifp->ifindex;elseif(mpinfo->peer->ifname)ifindex=ifname2ifindex(m
pinfo->peer->ifname,bgp->vrf_id);elseif(mpinfo->peer->nexthop.ifp)ifindex=mpinfo
->peer->nexthop.ifp->ifindex;}if(IN6_IS_ADDR_LINKLOCAL(nexthop)){if(ifindex==0)c
ontinue;}elseifindex=0;api_nh->gate.ipv6=*nexthop;api_nh->ifindex=ifindex;api_nh
->type=ifindex?NEXTHOP_TYPE_IPV6_IFINDEX:NEXTHOP_TYPE_IPV6;}if(mpinfo->extra&&bg
p_is_valid_label(&mpinfo->extra->label[0])&&!CHECK_FLAG(api.flags,ZEBRA_FLAG_EVP
N_ROUTE)){has_valid_label=1;label=label_pton(&mpinfo->extra->label[0]);api_nh->l
abel_num=1;api_nh->labels[0]=label;}valid_nh_count++;}/*ifthisisaevpnroutewedon'
thavetoincludethelabel*/if(has_valid_label&&!(CHECK_FLAG(api.flags,ZEBRA_FLAG_EV
PN_ROUTE)))SET_FLAG(api.message,ZAPI_MESSAGE_LABEL);if(info->sub_type!=BGP_ROUTE
_AGGREGATE)api.nexthop_num=valid_nh_count;SET_FLAG(api.message,ZAPI_MESSAGE_METR
IC);api.metric=metric;if(tag){SET_FLAG(api.message,ZAPI_MESSAGE_TAG);api.tag=tag
;}distance=bgp_distance_apply(p,info,afi,safi,bgp);if(distance){SET_FLAG(api.mes
sage,ZAPI_MESSAGE_DISTANCE);api.distance=distance;}if(bgp_debug_zebra(p)){charpr
efix_buf[PREFIX_STRLEN];charnh_buf[INET6_ADDRSTRLEN];charlabel_buf[20];inti;pref
ix2str(&api.prefix,prefix_buf,sizeof(prefix_buf));zlog_debug("Txroute%sVRF%u%sme
tric%utag%"ROUTE_TAG_PRI"count%d",valid_nh_count?"add":"delete",bgp->vrf_id,pref
ix_buf,api.metric,api.tag,api.nexthop_num);for(i=0;i<api.nexthop_num;i++){api_nh
=&api.nexthops[i];if(api_nh->type==NEXTHOP_TYPE_IPV4)nh_family=AF_INET;elsenh_fa
mily=AF_INET6;inet_ntop(nh_family,&api_nh->gate,nh_buf,sizeof(nh_buf));label_buf
[0]='\0';if(has_valid_label&&!CHECK_FLAG(api.flags,ZEBRA_FLAG_EVPN_ROUTE))sprint
f(label_buf,"label%u",api_nh->labels[0]);zlog_debug("nhop[%d]:%s%s",i+1,nh_buf,l
abel_buf);}}zclient_route_send(valid_nh_count?ZEBRA_ROUTE_ADD:ZEBRA_ROUTE_DELETE
,zclient,&api);}/*Announceallroutesofatabletozebra*/voidbgp_zebra_announce_table
(structbgp*bgp,afi_tafi,safi_tsafi){structbgp_node*rn;structbgp_table*table;stru
ctbgp_info*ri;/*Don'ttrytoinstallifwe'renotconnectedtoZebraorZebradoesn't*knowof
thisinstance.*/if(!bgp_install_info_to_zebra(bgp))return;table=bgp->rib[afi][saf
i];if(!table)return;for(rn=bgp_table_top(table);rn;rn=bgp_route_next(rn))for(ri=
rn->info;ri;ri=ri->next)if(CHECK_FLAG(ri->flags,BGP_INFO_SELECTED)&&(ri->type==Z
EBRA_ROUTE_BGP&&(ri->sub_type==BGP_ROUTE_NORMAL||ri->sub_type==BGP_ROUTE_IMPORTE
D)))bgp_zebra_announce(rn,&rn->p,ri,bgp,afi,safi);}voidbgp_zebra_withdraw(struct
prefix*p,structbgp_info*info,structbgp*bgp,safi_tsafi){structzapi_routeapi;struc
tpeer*peer;peer=info->peer;assert(peer);if(info->type==ZEBRA_ROUTE_BGP&&info->su
b_type==BGP_ROUTE_IMPORTED){structbgp_info*bi;/**Lookatparentchainforpeersort*/f
or(bi=info;bi->extra&&bi->extra->parent;bi=bi->extra->parent){peer=((structbgp_i
nfo*)(bi->extra->parent))->peer;}}/*Don'ttrytoinstallifwe'renotconnectedtoZebrao
rZebradoesn't*knowofthisinstance.*/if(!bgp_install_info_to_zebra(bgp))return;mem
set(&api,0,sizeof(api));memcpy(&api.rmac,&(info->attr->rmac),sizeof(structethadd
r));api.vrf_id=bgp->vrf_id;api.type=ZEBRA_ROUTE_BGP;api.safi=safi;api.prefix=*p;
/*IfitisanEVPNroutemarkassuch.*Currentlypresenceofrmacinattrdenotes*thisisanEVPN
type-2route*/if(info->sub_type==BGP_ROUTE_IMPORTED)SET_FLAG(api.flags,ZEBRA_FLAG
_EVPN_ROUTE);if(peer->sort==BGP_PEER_IBGP){SET_FLAG(api.flags,ZEBRA_FLAG_ALLOW_R
ECURSION);SET_FLAG(api.flags,ZEBRA_FLAG_IBGP);}if((peer->sort==BGP_PEER_EBGP&&pe
er->ttl!=1)||CHECK_FLAG(peer->flags,PEER_FLAG_DISABLE_CONNECTED_CHECK)||bgp_flag
_check(bgp,BGP_FLAG_DISABLE_NH_CONNECTED_CHK))SET_FLAG(api.flags,ZEBRA_FLAG_ALLO
W_RECURSION);if(bgp_debug_zebra(p)){charbuf[PREFIX_STRLEN];prefix2str(&api.prefi
x,buf,sizeof(buf));zlog_debug("TxroutedeleteVRF%u%s",bgp->vrf_id,buf);}zclient_r
oute_send(ZEBRA_ROUTE_DELETE,zclient,&api);}structbgp_redist*bgp_redist_lookup(s
tructbgp*bgp,afi_tafi,uint8_ttype,unsignedshortinstance){structlist*red_list;str
uctlistnode*node;structbgp_redist*red;red_list=bgp->redist[afi][type];if(!red_li
st)return(NULL);for(ALL_LIST_ELEMENTS_RO(red_list,node,red))if(red->instance==in
stance)returnred;returnNULL;}structbgp_redist*bgp_redist_add(structbgp*bgp,afi_t
afi,uint8_ttype,unsignedshortinstance){structlist*red_list;structbgp_redist*red;
red=bgp_redist_lookup(bgp,afi,type,instance);if(red)returnred;if(!bgp->redist[af
i][type])bgp->redist[afi][type]=list_new();red_list=bgp->redist[afi][type];red=(
structbgp_redist*)XCALLOC(MTYPE_BGP_REDIST,sizeof(structbgp_redist));red->instan
ce=instance;listnode_add(red_list,red);returnred;}staticvoidbgp_redist_del(struc
tbgp*bgp,afi_tafi,uint8_ttype,unsignedshortinstance){structbgp_redist*red;red=bg
p_redist_lookup(bgp,afi,type,instance);if(red){listnode_delete(bgp->redist[afi][
type],red);XFREE(MTYPE_BGP_REDIST,red);if(!bgp->redist[afi][type]->count)list_de
lete_and_null(&bgp->redist[afi][type]);}}/*OtherroutesredistributionintoBGP.*/in
tbgp_redistribute_set(structbgp*bgp,afi_tafi,inttype,unsignedshortinstance){/*Re
turnifalreadyredistributeflagisset.*/if(instance){if(redist_check_instance(&zcli
ent->mi_redist[afi][type],instance))returnCMD_WARNING;redist_add_instance(&zclie
nt->mi_redist[afi][type],instance);}else{if(vrf_bitmap_check(zclient->redist[afi
][type],bgp->vrf_id))returnCMD_WARNING;#ifENABLE_BGP_VNCif(bgp->vrf_id==VRF_DEFA
ULT&&type==ZEBRA_ROUTE_VNC_DIRECT){vnc_export_bgp_enable(bgp,afi);/*onlyenablesi
fmodebitscfg'd*/}#endifvrf_bitmap_set(zclient->redist[afi][type],bgp->vrf_id);}/
**Don'ttrytoregisterifwe'renotconnectedtoZebraorZebra*doesn'tknowofthisinstance.
**Whenwecomeuplaterwellresendifneeded.*/if(!bgp_install_info_to_zebra(bgp))retur
nCMD_SUCCESS;if(BGP_DEBUG(zebra,ZEBRA))zlog_debug("TxredistributeaddVRF%uafi%d%s
%d",bgp->vrf_id,afi,zebra_route_string(type),instance);/*Senddistributeaddmessag
etozebra.*/zebra_redistribute_send(ZEBRA_REDISTRIBUTE_ADD,zclient,afi,type,insta
nce,bgp->vrf_id);returnCMD_SUCCESS;}intbgp_redistribute_resend(structbgp*bgp,afi
_tafi,inttype,unsignedshortinstance){/*Don'ttrytosendifwe'renotconnectedtoZebrao
rZebradoesn't*knowofthisinstance.*/if(!bgp_install_info_to_zebra(bgp))return-1;i
f(BGP_DEBUG(zebra,ZEBRA))zlog_debug("Txredistributedel/addVRF%uafi%d%s%d",bgp->v
rf_id,afi,zebra_route_string(type),instance);/*Senddistributeaddmessagetozebra.*
/zebra_redistribute_send(ZEBRA_REDISTRIBUTE_DELETE,zclient,afi,type,instance,bgp
->vrf_id);zebra_redistribute_send(ZEBRA_REDISTRIBUTE_ADD,zclient,afi,type,instan
ce,bgp->vrf_id);return0;}/*Redistributewithroute-mapspecification.*/intbgp_redis
tribute_rmap_set(structbgp_redist*red,constchar*name){if(red->rmap.name&&(strcmp
(red->rmap.name,name)==0))return0;if(red->rmap.name)XFREE(MTYPE_ROUTE_MAP_NAME,r
ed->rmap.name);red->rmap.name=XSTRDUP(MTYPE_ROUTE_MAP_NAME,name);red->rmap.map=r
oute_map_lookup_by_name(name);return1;}/*Redistributewithmetricspecification.*/i
ntbgp_redistribute_metric_set(structbgp*bgp,structbgp_redist*red,afi_tafi,inttyp
e,uint32_tmetric){structbgp_node*rn;structbgp_info*ri;if(red->redist_metric_flag
&&red->redist_metric==metric)return0;red->redist_metric_flag=1;red->redist_metri
c=metric;for(rn=bgp_table_top(bgp->rib[afi][SAFI_UNICAST]);rn;rn=bgp_route_next(
rn)){for(ri=rn->info;ri;ri=ri->next){if(ri->sub_type==BGP_ROUTE_REDISTRIBUTE&&ri
->type==type&&ri->instance==red->instance){structattr*old_attr;structattrnew_att
r;bgp_attr_dup(&new_attr,ri->attr);new_attr.med=red->redist_metric;old_attr=ri->
attr;ri->attr=bgp_attr_intern(&new_attr);bgp_attr_unintern(&old_attr);bgp_info_s
et_flag(rn,ri,BGP_INFO_ATTR_CHANGED);bgp_process(bgp,rn,afi,SAFI_UNICAST);}}}ret
urn1;}/*Unsetredistribution.*/intbgp_redistribute_unreg(structbgp*bgp,afi_tafi,i
nttype,unsignedshortinstance){structbgp_redist*red;red=bgp_redist_lookup(bgp,afi
,type,instance);if(!red)returnCMD_SUCCESS;/*Returnifzebraconnectionisdisabled.*/
if(instance){if(!redist_check_instance(&zclient->mi_redist[afi][type],instance))
returnCMD_WARNING;redist_del_instance(&zclient->mi_redist[afi][type],instance);}
else{if(!vrf_bitmap_check(zclient->redist[afi][type],bgp->vrf_id))returnCMD_WARN
ING;vrf_bitmap_unset(zclient->redist[afi][type],bgp->vrf_id);}if(bgp_install_inf
o_to_zebra(bgp)){/*Senddistributedeletemessagetozebra.*/if(BGP_DEBUG(zebra,ZEBRA
))zlog_debug("TxredistributedelVRF%uafi%d%s%d",bgp->vrf_id,afi,zebra_route_strin
g(type),instance);zebra_redistribute_send(ZEBRA_REDISTRIBUTE_DELETE,zclient,afi,
type,instance,bgp->vrf_id);}/*WithdrawredistributedroutesfromcurrentBGP'srouting
table.*/bgp_redistribute_withdraw(bgp,afi,type,instance);returnCMD_SUCCESS;}/*Un
setredistribution.*/intbgp_redistribute_unset(structbgp*bgp,afi_tafi,inttype,uns
ignedshortinstance){structbgp_redist*red;/**vncandvpn->vrfchecksmustbebeforeredc
heckbecause*theyoperatewithinbgpdirrespectiveofzebraconnection*status.redlookupf
ailsifthereisnozebraconnection.*/#ifENABLE_BGP_VNCif(bgp->vrf_id==VRF_DEFAULT&&t
ype==ZEBRA_ROUTE_VNC_DIRECT){vnc_export_bgp_disable(bgp,afi);}#endifred=bgp_redi
st_lookup(bgp,afi,type,instance);if(!red)returnCMD_SUCCESS;bgp_redistribute_unre
g(bgp,afi,type,instance);/*Unsetroute-map.*/if(red->rmap.name)XFREE(MTYPE_ROUTE_
MAP_NAME,red->rmap.name);red->rmap.name=NULL;red->rmap.map=NULL;/*Unsetmetric.*/
red->redist_metric_flag=0;red->redist_metric=0;bgp_redist_del(bgp,afi,type,insta
nce);returnCMD_SUCCESS;}/*Updateredistributevrfbitmapduringtriggerslikerestartne
tworkingordelete/addVRFs*/voidbgp_update_redist_vrf_bitmaps(structbgp*bgp,vrf_id
_told_vrf_id){inti;afi_tafi;for(afi=AFI_IP;afi<AFI_MAX;afi++)for(i=0;i<ZEBRA_ROU
TE_MAX;i++)if((old_vrf_id==VRF_UNKNOWN)||vrf_bitmap_check(zclient->redist[afi][i
],old_vrf_id)){vrf_bitmap_unset(zclient->redist[afi][i],old_vrf_id);vrf_bitmap_s
et(zclient->redist[afi][i],bgp->vrf_id);}return;}voidbgp_zclient_reset(void){zcl
ient_reset(zclient);}/*RegisterthisinstancewithZebra.Invokeduponconnect(for*defa
ultinstance)andwhenotherVRFsarelearnt(orcreatedand*alreadylearnt).*/voidbgp_zebr
a_instance_register(structbgp*bgp){/*Don'ttrytoregisterifwe'renotconnectedtoZebr
a*/if(!zclient||zclient->sock<0)return;if(BGP_DEBUG(zebra,ZEBRA))zlog_debug("Reg
isteringVRF%u",bgp->vrf_id);/*Registerforrouter-id,interfaces,redistributedroute
s.*/zclient_send_reg_requests(zclient,bgp->vrf_id);/*Fordefaultinstance,register
tolearnaboutVNIs,ifappropriate.*/if(bgp->inst_type==BGP_INSTANCE_TYPE_DEFAULT&&i
s_evpn_enabled())bgp_zebra_advertise_all_vni(bgp,1);}/*Deregisterthisinstancewit
hZebra.Invokedupontheinstance*beingdeleted(defaultorVRF)anditisalreadyregistered
.*/voidbgp_zebra_instance_deregister(structbgp*bgp){/*Don'ttrytoderegisterifwe'r
enotconnectedtoZebra*/if(zclient->sock<0)return;if(BGP_DEBUG(zebra,ZEBRA))zlog_d
ebug("DeregisteringVRF%u",bgp->vrf_id);/*Fordefaultinstance,unregisterlearningab
outVNIs,ifappropriate.*/if(bgp->inst_type==BGP_INSTANCE_TYPE_DEFAULT&&is_evpn_en
abled())bgp_zebra_advertise_all_vni(bgp,0);/*Deregisterforrouter-id,interfaces,r
edistributedroutes.*/zclient_send_dereg_requests(zclient,bgp->vrf_id);}voidbgp_z
ebra_initiate_radv(structbgp*bgp,structpeer*peer){intra_interval=BGP_UNNUM_DEFAU
LT_RA_INTERVAL;/*Don'ttrytoinitiateifwe'renotconnectedtoZebra*/if(zclient->sock<
0)return;if(BGP_DEBUG(zebra,ZEBRA))zlog_debug("%u:InitiatingRAforpeer%s",bgp->vr
f_id,peer->host);zclient_send_interface_radv_req(zclient,bgp->vrf_id,peer->ifp,1
,ra_interval);}voidbgp_zebra_terminate_radv(structbgp*bgp,structpeer*peer){/*Don
'ttrytoterminateifwe'renotconnectedtoZebra*/if(zclient->sock<0)return;if(BGP_DEB
UG(zebra,ZEBRA))zlog_debug("%u:TerminatingRAforpeer%s",bgp->vrf_id,peer->host);z
client_send_interface_radv_req(zclient,bgp->vrf_id,peer->ifp,0,0);}intbgp_zebra_
advertise_subnet(structbgp*bgp,intadvertise,vni_tvni){structstream*s=NULL;/*Chec
ksocket.*/if(!zclient||zclient->sock<0)return0;/*Don'ttrytoregisterifZebradoesn'
tknowofthisinstance.*/if(!IS_BGP_INST_KNOWN_TO_ZEBRA(bgp))return0;s=zclient->obu
f;stream_reset(s);zclient_create_header(s,ZEBRA_ADVERTISE_SUBNET,bgp->vrf_id);st
ream_putc(s,advertise);stream_put3(s,vni);stream_putw_at(s,0,stream_get_endp(s))
;returnzclient_send_message(zclient);}intbgp_zebra_advertise_gw_macip(structbgp*
bgp,intadvertise,vni_tvni){structstream*s=NULL;/*Checksocket.*/if(!zclient||zcli
ent->sock<0)return0;/*Don'ttrytoregisterifZebradoesn'tknowofthisinstance.*/if(!I
S_BGP_INST_KNOWN_TO_ZEBRA(bgp))return0;s=zclient->obuf;stream_reset(s);zclient_c
reate_header(s,ZEBRA_ADVERTISE_DEFAULT_GW,bgp->vrf_id);stream_putc(s,advertise);
stream_put3(s,vni);stream_putw_at(s,0,stream_get_endp(s));returnzclient_send_mes
sage(zclient);}intbgp_zebra_advertise_all_vni(structbgp*bgp,intadvertise){struct
stream*s;/*Checksocket.*/if(!zclient||zclient->sock<0)return0;/*Don'ttrytoregist
erifZebradoesn'tknowofthisinstance.*/if(!IS_BGP_INST_KNOWN_TO_ZEBRA(bgp))return0
;s=zclient->obuf;stream_reset(s);zclient_create_header(s,ZEBRA_ADVERTISE_ALL_VNI
,bgp->vrf_id);stream_putc(s,advertise);stream_putw_at(s,0,stream_get_endp(s));re
turnzclient_send_message(zclient);}/*BGPhasestablishedconnectionwithZebra.*/stat
icvoidbgp_zebra_connected(structzclient*zclient){structbgp*bgp;zclient_num_conne
cts++;/*incrementevenifnotresponding*//*Atthispoint,wemayormaynothaveBGPinstance
sconfigured,but*we'reonlyinterestedinthedefaultVRF(otherswouldn'thavelearnt*theV
RFfromZebrayet.)*/bgp=bgp_get_default();if(!bgp)return;bgp_zebra_instance_regist
er(bgp);/*Sendtheclientregistration*/bfd_client_sendmsg(zclient,ZEBRA_BFD_CLIENT
_REGISTER);/*TODO-Whatifwehavepeersandnetworksconfigured,dowehaveto*kick-startth
em?*/}staticintbgp_zebra_process_local_l3vni(intcmd,structzclient*zclient,zebra_
size_tlength,vrf_id_tvrf_id){intfilter=0;charbuf[ETHER_ADDR_STRLEN];vni_tl3vni=0
;structethaddrrmac;structin_addroriginator_ip;structstream*s;memset(&rmac,0,size
of(structethaddr));memset(&originator_ip,0,sizeof(structin_addr));s=zclient->ibu
f;l3vni=stream_getl(s);if(cmd==ZEBRA_L3VNI_ADD){stream_get(&rmac,s,sizeof(struct
ethaddr));originator_ip.s_addr=stream_get_ipv4(s);stream_get(&filter,s,sizeof(in
t));}if(BGP_DEBUG(zebra,ZEBRA))zlog_debug("RxL3-VNI%sVRF%sVNI%uRMAC%sfilter%s",(
cmd==ZEBRA_L3VNI_ADD)?"add":"del",vrf_id_to_name(vrf_id),l3vni,prefix_mac2str(&r
mac,buf,sizeof(buf)),filter?"prefix-routes-only":"none");if(cmd==ZEBRA_L3VNI_ADD
)bgp_evpn_local_l3vni_add(l3vni,vrf_id,&rmac,originator_ip,filter);elsebgp_evpn_
local_l3vni_del(l3vni,vrf_id);return0;}staticintbgp_zebra_process_local_vni(intc
ommand,structzclient*zclient,zebra_size_tlength,vrf_id_tvrf_id){structstream*s;v
ni_tvni;structbgp*bgp;structin_addrvtep_ip={INADDR_ANY};vrf_id_ttenant_vrf_id=VR
F_DEFAULT;s=zclient->ibuf;vni=stream_getl(s);if(command==ZEBRA_VNI_ADD){vtep_ip.
s_addr=stream_get_ipv4(s);stream_get(&tenant_vrf_id,s,sizeof(vrf_id_t));}bgp=bgp
_lookup_by_vrf_id(vrf_id);if(!bgp)return0;if(BGP_DEBUG(zebra,ZEBRA))zlog_debug("
RxVNI%sVRF%sVNI%utenant-vrf%s",(command==ZEBRA_VNI_ADD)?"add":"del",vrf_id_to_na
me(vrf_id),vni,vrf_id_to_name(tenant_vrf_id));if(command==ZEBRA_VNI_ADD)returnbg
p_evpn_local_vni_add(bgp,vni,vtep_ip.s_addr?vtep_ip:bgp->router_id,tenant_vrf_id
);elsereturnbgp_evpn_local_vni_del(bgp,vni);}staticintbgp_zebra_process_local_ma
cip(intcommand,structzclient*zclient,zebra_size_tlength,vrf_id_tvrf_id){structst
ream*s;vni_tvni;structbgp*bgp;structethaddrmac;structipaddrip;intipa_len;charbuf
[ETHER_ADDR_STRLEN];charbuf1[INET6_ADDRSTRLEN];uint8_tflags;memset(&ip,0,sizeof(
ip));s=zclient->ibuf;vni=stream_getl(s);stream_get(&mac.octet,s,ETH_ALEN);ipa_le
n=stream_getl(s);if(ipa_len!=0&&ipa_len!=IPV4_MAX_BYTELEN&&ipa_len!=IPV6_MAX_BYT
ELEN){zlog_err("%u:RecvMACIP%swithinvalidIPaddrlength%d",vrf_id,(command==ZEBRA_
MACIP_ADD)?"Add":"Del",ipa_len);return-1;}if(ipa_len){ip.ipa_type=(ipa_len==IPV4
_MAX_BYTELEN)?IPADDR_V4:IPADDR_V6;stream_get(&ip.ip.addr,s,ipa_len);}flags=strea
m_getc(s);bgp=bgp_lookup_by_vrf_id(vrf_id);if(!bgp)return0;if(BGP_DEBUG(zebra,ZE
BRA))zlog_debug("%u:RecvMACIP%sflags0x%xMAC%sIP%sVNI%u",vrf_id,(command==ZEBRA_M
ACIP_ADD)?"Add":"Del",flags,prefix_mac2str(&mac,buf,sizeof(buf)),ipaddr2str(&ip,
buf1,sizeof(buf1)),vni);if(command==ZEBRA_MACIP_ADD)returnbgp_evpn_local_macip_a
dd(bgp,vni,&mac,&ip,flags);elsereturnbgp_evpn_local_macip_del(bgp,vni,&mac,&ip);
}staticvoidbgp_zebra_process_local_ip_prefix(intcmd,structzclient*zclient,zebra_
size_tlength,vrf_id_tvrf_id){structstream*s=NULL;structbgp*bgp_vrf=NULL;structpr
efixp;charbuf[PREFIX_STRLEN];memset(&p,0,sizeof(structprefix));s=zclient->ibuf;s
tream_get(&p,s,sizeof(structprefix));bgp_vrf=bgp_lookup_by_vrf_id(vrf_id);if(!bg
p_vrf)return;if(BGP_DEBUG(zebra,ZEBRA))zlog_debug("Recvprefix%s%sonvrf%s",prefix
2str(&p,buf,sizeof(buf)),(cmd==ZEBRA_IP_PREFIX_ROUTE_ADD)?"ADD":"DEL",vrf_id_to_
name(vrf_id));if(cmd==ZEBRA_IP_PREFIX_ROUTE_ADD){if(p.family==AF_INET)returnbgp_
evpn_advertise_type5_route(bgp_vrf,&p,NULL,AFI_IP,SAFI_UNICAST);elsereturnbgp_ev
pn_advertise_type5_route(bgp_vrf,&p,NULL,AFI_IP6,SAFI_UNICAST);}else{if(p.family
==AF_INET)returnbgp_evpn_withdraw_type5_route(bgp_vrf,&p,AFI_IP,SAFI_UNICAST);el
sereturnbgp_evpn_withdraw_type5_route(bgp_vrf,&p,AFI_IP6,SAFI_UNICAST);}}externs
tructzebra_privs_tbgpd_privs;voidbgp_zebra_init(structthread_master*master){zcli
ent_num_connects=0;/*Setdefaultvalues.*/zclient=zclient_new_notify(master,&zclie
nt_options_default);zclient_init(zclient,ZEBRA_ROUTE_BGP,0,&bgpd_privs);zclient-
>zebra_connected=bgp_zebra_connected;zclient->router_id_update=bgp_router_id_upd
ate;zclient->interface_add=bgp_interface_add;zclient->interface_delete=bgp_inter
face_delete;zclient->interface_address_add=bgp_interface_address_add;zclient->in
terface_address_delete=bgp_interface_address_delete;zclient->interface_nbr_addre
ss_add=bgp_interface_nbr_address_add;zclient->interface_nbr_address_delete=bgp_i
nterface_nbr_address_delete;zclient->interface_vrf_update=bgp_interface_vrf_upda
te;zclient->redistribute_route_add=zebra_read_route;zclient->redistribute_route_
del=zebra_read_route;zclient->interface_up=bgp_interface_up;zclient->interface_d
own=bgp_interface_down;zclient->nexthop_update=bgp_read_nexthop_update;zclient->
import_check_update=bgp_read_import_check_update;zclient->fec_update=bgp_read_fe
c_update;zclient->local_vni_add=bgp_zebra_process_local_vni;zclient->local_vni_d
el=bgp_zebra_process_local_vni;zclient->local_macip_add=bgp_zebra_process_local_
macip;zclient->local_macip_del=bgp_zebra_process_local_macip;zclient->local_l3vn
i_add=bgp_zebra_process_local_l3vni;zclient->local_l3vni_del=bgp_zebra_process_l
ocal_l3vni;zclient->local_ip_prefix_add=bgp_zebra_process_local_ip_prefix;zclien
t->local_ip_prefix_del=bgp_zebra_process_local_ip_prefix;}voidbgp_zebra_destroy(
void){if(zclient==NULL)return;zclient_stop(zclient);zclient_free(zclient);zclien
t=NULL;}intbgp_zebra_num_connects(void){returnzclient_num_connects;}