/*BGPcarryinglabelinformation*Copyright(C)2013CumulusNetworks,Inc.**Thisfileispa
rtofGNUZebra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodifyit*underth
etermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;either
version2,or(atyouroption)any*laterversion.**GNUZebraisdistributedinthehopethatit
willbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABIL
ITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.*
*YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;see
thefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFl
oor,Boston,MA02110-1301USA*/#include<zebra.h>#include"command.h"#include"thread.
h"#include"prefix.h"#include"zclient.h"#include"stream.h"#include"network.h"#inc
lude"log.h"#include"memory.h"#include"nexthop.h"#include"mpls.h"#include"bgpd/bg
pd.h"#include"bgpd/bgp_table.h"#include"bgpd/bgp_route.h"#include"bgpd/bgp_attr.
h"#include"bgpd/bgp_label.h"#include"bgpd/bgp_packet.h"#include"bgpd/bgp_debug.h
"externstructzclient*zclient;intbgp_parse_fec_update(void){structstream*s;struct
bgp_node*rn;structbgp*bgp;structbgp_table*table;structprefixp;uint32_tlabel;afi_
tafi;safi_tsafi;s=zclient->ibuf;memset(&p,0,sizeof(structprefix));p.family=strea
m_getw(s);p.prefixlen=stream_getc(s);stream_get(&p.u.prefix,s,PSIZE(p.prefixlen)
);label=stream_getl(s);/*hackforthebgpinstance&SAFI=havetosend/receiveit*/afi=fa
mily2afi(p.family);safi=SAFI_UNICAST;bgp=bgp_get_default();if(!bgp){zlog_debug("
nodefaultbgpinstance");return-1;}table=bgp->rib[afi][safi];if(!table){zlog_debug
("no%uunicasttable",p.family);return-1;}rn=bgp_node_lookup(table,&p);if(!rn){zlo
g_debug("nonodefortheprefix");return-1;}/*treatitasimplicitwithdraw-thelabelisin
valid*/if(label==MPLS_INVALID_LABEL)bgp_unset_valid_label(&rn->local_label);else
{label_ntop(label,1,&rn->local_label);bgp_set_valid_label(&rn->local_label);}SET
_FLAG(rn->flags,BGP_NODE_LABEL_CHANGED);bgp_unlock_node(rn);bgp_process(bgp,rn,a
fi,safi);return1;}mpls_label_tbgp_adv_label(structbgp_node*rn,structbgp_info*ri,
structpeer*to,afi_tafi,safi_tsafi){structpeer*from;mpls_label_tremote_label;intr
eflect;if(!rn||!ri||!to)returnMPLS_INVALID_LABEL;remote_label=ri->extra?ri->extr
a->label[0]:MPLS_INVALID_LABEL;from=ri->peer;reflect=((from->sort==BGP_PEER_IBGP
)&&(to->sort==BGP_PEER_IBGP));if(reflect&&!CHECK_FLAG(to->af_flags[afi][safi],PE
ER_FLAG_FORCE_NEXTHOP_SELF))returnremote_label;if(CHECK_FLAG(to->af_flags[afi][s
afi],PEER_FLAG_NEXTHOP_UNCHANGED))returnremote_label;returnrn->local_label;}void
bgp_reg_dereg_for_label(structbgp_node*rn,structbgp_info*ri,intreg){structstream
*s;structprefix*p;intcommand;uint16_tflags=0;size_tflags_pos=0;/*Checksocket.*/i
f(!zclient||zclient->sock<0)return;p=&(rn->p);s=zclient->obuf;stream_reset(s);co
mmand=(reg)?ZEBRA_FEC_REGISTER:ZEBRA_FEC_UNREGISTER;zclient_create_header(s,comm
and,VRF_DEFAULT);flags_pos=stream_get_endp(s);/*savepositionof'flags'*/stream_pu
tw(s,flags);/*initialflags*/stream_putw(s,PREFIX_FAMILY(p));stream_put_prefix(s,
p);if(reg){assert(ri);if(ri->attr->flag&ATTR_FLAG_BIT(BGP_ATTR_PREFIX_SID)){if(r
i->attr->label_index!=BGP_INVALID_LABEL_INDEX){flags|=ZEBRA_FEC_REGISTER_LABEL_I
NDEX;stream_putl(s,ri->attr->label_index);}}SET_FLAG(rn->flags,BGP_NODE_REGISTER
ED_FOR_LABEL);}elseUNSET_FLAG(rn->flags,BGP_NODE_REGISTERED_FOR_LABEL);/*Setleng
thandflags*/stream_putw_at(s,0,stream_get_endp(s));/**Weonlyneedtowritenewflagsi
fthisisaregister*/if(reg)stream_putw_at(s,flags_pos,flags);zclient_send_message(
zclient);}staticintbgp_nlri_get_labels(structpeer*peer,uint8_t*pnt,uint8_tplen,m
pls_label_t*label){uint8_t*data=pnt;uint8_t*lim=pnt+plen;uint8_tllen=0;uint8_tla
bel_depth=0;for(;data<lim;data+=BGP_LABEL_BYTES){memcpy(label,data,BGP_LABEL_BYT
ES);llen+=BGP_LABEL_BYTES;bgp_set_valid_label(label);label_depth+=1;if(bgp_is_wi
thdraw_label(label)||label_bos(label))break;}/*IfweRXmultiplelabelswewillendupke
epingonlythelast*one.Wedonotyetsupportalabelstackgreaterthan1.*/if(label_depth>1
)zlog_warn("%srcvdUPDATEwithlabelstack%ddeep",peer->host,label_depth);if(!(bgp_i
s_withdraw_label(label)||label_bos(label)))zlog_warn("%srcvdUPDATEwithinvalidlab
elstack-nobottomofstack",peer->host);returnllen;}intbgp_nlri_parse_label(structp
eer*peer,structattr*attr,structbgp_nlri*packet){uint8_t*pnt;uint8_t*lim;structpr
efixp;intpsize=0;intprefixlen;afi_tafi;safi_tsafi;intaddpath_encoded;uint32_tadd
path_id;mpls_label_tlabel=MPLS_INVALID_LABEL;uint8_tllen;pnt=packet->nlri;lim=pn
t+packet->length;afi=packet->afi;safi=packet->safi;addpath_id=0;addpath_encoded=
(CHECK_FLAG(peer->af_cap[afi][safi],PEER_CAP_ADDPATH_AF_RX_ADV)&&CHECK_FLAG(peer
->af_cap[afi][safi],PEER_CAP_ADDPATH_AF_TX_RCV));for(;pnt<lim;pnt+=psize){/*Clea
rprefixstructure.*/memset(&p,0,sizeof(structprefix));if(addpath_encoded){/*Whenp
acketoverflowoccursreturnimmediately.*/if(pnt+BGP_ADDPATH_ID_LEN>lim)return-1;ad
dpath_id=ntohl(*((uint32_t*)pnt));pnt+=BGP_ADDPATH_ID_LEN;}/*Fetchprefixlength.*
/prefixlen=*pnt++;p.family=afi2family(packet->afi);psize=PSIZE(prefixlen);/*sani
tycheckagainstpacketdata*/if((pnt+psize)>lim){zlog_err("%s[Error]Updatepacketerr
or/L-U(prefixlength%dexceedspacketsize%u)",peer->host,prefixlen,(uint)(lim-pnt))
;return-1;}/*Fillinthelabels*/llen=bgp_nlri_get_labels(peer,pnt,psize,&label);p.
prefixlen=prefixlen-BSIZE(llen);/*Thereneedstobeatleastonelabel*/if(prefixlen<24
){zlog_err("%s[Error]Updatepacketerror""(wronglabellength%d)",peer->host,prefixl
en);bgp_notify_send(peer,BGP_NOTIFY_UPDATE_ERR,BGP_NOTIFY_UPDATE_INVAL_NETWORK);
return-1;}if((afi==AFI_IP&&p.prefixlen>32)||(afi==AFI_IP6&&p.prefixlen>128))retu
rn-1;/*FetchprefixfromNLRIpacket*/memcpy(&p.u.prefix,pnt+llen,psize-llen);/*Chec
kaddress.*/if(afi==AFI_IP&&safi==SAFI_LABELED_UNICAST){if(IN_CLASSD(ntohl(p.u.pr
efix4.s_addr))){/*FromRFC4271Section6.3:**IfaprefixintheNLRIfieldissemantically*
incorrect*(e.g.,anunexpectedmulticastIPaddress),*anerrorSHOULD*beloggedlocally,a
ndtheprefixSHOULDbe*ignored.*/zlog_err("%s:IPv4labeled-unicastNLRIismulticastadd
ress%s,ignoring",peer->host,inet_ntoa(p.u.prefix4));continue;}}/*Checkaddress.*/
if(afi==AFI_IP6&&safi==SAFI_LABELED_UNICAST){if(IN6_IS_ADDR_LINKLOCAL(&p.u.prefi
x6)){charbuf[BUFSIZ];zlog_err("%s:IPv6labeled-unicastNLRIislink-localaddress%s,i
gnoring",peer->host,inet_ntop(AF_INET6,&p.u.prefix6,buf,BUFSIZ));continue;}if(IN
6_IS_ADDR_MULTICAST(&p.u.prefix6)){charbuf[BUFSIZ];zlog_err("%s:IPv6unicastNLRIi
smulticastaddress%s,ignoring",peer->host,inet_ntop(AF_INET6,&p.u.prefix6,buf,BUF
SIZ));continue;}}if(attr){bgp_update(peer,&p,addpath_id,attr,packet->afi,SAFI_UN
ICAST,ZEBRA_ROUTE_BGP,BGP_ROUTE_NORMAL,NULL,&label,1,0,NULL);}else{bgp_withdraw(
peer,&p,addpath_id,attr,packet->afi,SAFI_UNICAST,ZEBRA_ROUTE_BGP,BGP_ROUTE_NORMA
L,NULL,&label,1,NULL);}}/*Packetlengthconsistencycheck.*/if(pnt!=lim){zlog_err("
%s[Error]Updatepacketerror/L-U(%zudataremainingafterparsing)",peer->host,lim-pnt
);return-1;}return0;}