/*BGPadvertisementandadjacency*Copyright(C)1996,97,98,99,2000KunihiroIshiguro**T
hisfileispartofGNUZebra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodif
yit*underthetermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFounda
tion;eitherversion2,or(atyouroption)any*laterversion.**GNUZebraisdistributedinth
ehopethatitwillbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*M
ERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformo
redetails.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthis
program;seethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51Frankli
nSt,FifthFloor,Boston,MA02110-1301USA*/#include<zebra.h>#include"command.h"#incl
ude"memory.h"#include"prefix.h"#include"hash.h"#include"thread.h"#include"queue.
h"#include"filter.h"#include"bgpd/bgpd.h"#include"bgpd/bgp_table.h"#include"bgpd
/bgp_route.h"#include"bgpd/bgp_advertise.h"#include"bgpd/bgp_attr.h"#include"bgp
d/bgp_debug.h"#include"bgpd/bgp_aspath.h"#include"bgpd/bgp_packet.h"#include"bgp
d/bgp_fsm.h"#include"bgpd/bgp_mplsvpn.h"#include"bgpd/bgp_updgrp.h"/*BGPadvertis
eattributeisusedforpacksameattributeupdateintoonepacket.Todothatwemaintainattrib
utehashinstructpeer.*/structbgp_advertise_attr*baa_new(void){return(structbgp_ad
vertise_attr*)XCALLOC(MTYPE_BGP_ADVERTISE_ATTR,sizeof(structbgp_advertise_attr))
;}staticvoidbaa_free(structbgp_advertise_attr*baa){XFREE(MTYPE_BGP_ADVERTISE_ATT
R,baa);}staticvoid*baa_hash_alloc(void*p){structbgp_advertise_attr*ref=(structbg
p_advertise_attr*)p;structbgp_advertise_attr*baa;baa=baa_new();baa->attr=ref->at
tr;returnbaa;}unsignedintbaa_hash_key(void*p){structbgp_advertise_attr*baa=(stru
ctbgp_advertise_attr*)p;returnattrhash_key_make(baa->attr);}intbaa_hash_cmp(cons
tvoid*p1,constvoid*p2){conststructbgp_advertise_attr*baa1=p1;conststructbgp_adve
rtise_attr*baa2=p2;returnattrhash_cmp(baa1->attr,baa2->attr);}/*BGPupdateandwith
drawinformationisstoredinBGPadvertisestructure.ThisstructureisreferredfromBGPadj
acencyinformation.*/structbgp_advertise*bgp_advertise_new(void){return(structbgp
_advertise*)XCALLOC(MTYPE_BGP_ADVERTISE,sizeof(structbgp_advertise));}voidbgp_ad
vertise_free(structbgp_advertise*adv){if(adv->binfo)bgp_info_unlock(adv->binfo);
/*bgp_advertisebgp_inforeference*/XFREE(MTYPE_BGP_ADVERTISE,adv);}voidbgp_advert
ise_add(structbgp_advertise_attr*baa,structbgp_advertise*adv){adv->next=baa->adv
;if(baa->adv)baa->adv->prev=adv;baa->adv=adv;}voidbgp_advertise_delete(structbgp
_advertise_attr*baa,structbgp_advertise*adv){if(adv->next)adv->next->prev=adv->p
rev;if(adv->prev)adv->prev->next=adv->next;elsebaa->adv=adv->next;}structbgp_adv
ertise_attr*bgp_advertise_intern(structhash*hash,structattr*attr){structbgp_adve
rtise_attrref;structbgp_advertise_attr*baa;ref.attr=bgp_attr_intern(attr);baa=(s
tructbgp_advertise_attr*)hash_get(hash,&ref,baa_hash_alloc);baa->refcnt++;return
baa;}voidbgp_advertise_unintern(structhash*hash,structbgp_advertise_attr*baa){if
(baa->refcnt)baa->refcnt--;if(baa->refcnt&&baa->attr)bgp_attr_unintern(&baa->att
r);else{if(baa->attr){hash_release(hash,baa);bgp_attr_unintern(&baa->attr);}baa_
free(baa);}}intbgp_adj_out_lookup(structpeer*peer,structbgp_node*rn,uint32_taddp
ath_tx_id){structbgp_adj_out*adj;structpeer_af*paf;afi_tafi;safi_tsafi;intaddpat
h_capable;for(adj=rn->adj_out;adj;adj=adj->next)SUBGRP_FOREACH_PEER(adj->subgrou
p,paf)if(paf->peer==peer){afi=SUBGRP_AFI(adj->subgroup);safi=SUBGRP_SAFI(adj->su
bgroup);addpath_capable=bgp_addpath_encode_tx(peer,afi,safi);/*Matchonaspecifica
ddpath_tx_idifweare*usingaddpathfor*this*peerandifanaddpath_tx_idwasspecified*/i
f(addpath_capable&&addpath_tx_id&&adj->addpath_tx_id!=addpath_tx_id)continue;ret
urn(adj->adv?(adj->adv->baa?1:0):(adj->attr?1:0));}return0;}voidbgp_adj_in_set(s
tructbgp_node*rn,structpeer*peer,structattr*attr,uint32_taddpath_id){structbgp_a
dj_in*adj;for(adj=rn->adj_in;adj;adj=adj->next){if(adj->peer==peer&&adj->addpath
_rx_id==addpath_id){if(adj->attr!=attr){bgp_attr_unintern(&adj->attr);adj->attr=
bgp_attr_intern(attr);}return;}}adj=XCALLOC(MTYPE_BGP_ADJ_IN,sizeof(structbgp_ad
j_in));adj->peer=peer_lock(peer);/*adj_inpeerreference*/adj->attr=bgp_attr_inter
n(attr);adj->addpath_rx_id=addpath_id;BGP_ADJ_IN_ADD(rn,adj);bgp_lock_node(rn);}
voidbgp_adj_in_remove(structbgp_node*rn,structbgp_adj_in*bai){bgp_attr_unintern(
&bai->attr);BGP_ADJ_IN_DEL(rn,bai);peer_unlock(bai->peer);/*adj_inpeerreference*
/XFREE(MTYPE_BGP_ADJ_IN,bai);}intbgp_adj_in_unset(structbgp_node*rn,structpeer*p
eer,uint32_taddpath_id){structbgp_adj_in*adj;structbgp_adj_in*adj_next;adj=rn->a
dj_in;if(!adj)return0;while(adj){adj_next=adj->next;if(adj->peer==peer&&adj->add
path_rx_id==addpath_id){bgp_adj_in_remove(rn,adj);bgp_unlock_node(rn);}adj=adj_n
ext;}return1;}voidbgp_sync_init(structpeer*peer){afi_tafi;safi_tsafi;structbgp_s
ynchronize*sync;FOREACH_AFI_SAFI(afi,safi){sync=XCALLOC(MTYPE_BGP_SYNCHRONISE,si
zeof(structbgp_synchronize));BGP_ADV_FIFO_INIT(&sync->update);BGP_ADV_FIFO_INIT(
&sync->withdraw);BGP_ADV_FIFO_INIT(&sync->withdraw_low);peer->sync[afi][safi]=sy
nc;}}voidbgp_sync_delete(structpeer*peer){afi_tafi;safi_tsafi;FOREACH_AFI_SAFI(a
fi,safi){if(peer->sync[afi][safi])XFREE(MTYPE_BGP_SYNCHRONISE,peer->sync[afi][sa
fi]);peer->sync[afi][safi]=NULL;}}