/*BGPflapdampening*Copyright(C)2001IPInfusionInc.**ThisfileispartofGNUZebra.**GN
UZebraisfreesoftware;youcanredistributeitand/ormodifyit*underthetermsoftheGNUGen
eralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eitherversion2,or(atyou
roption)any*laterversion.**GNUZebraisdistributedinthehopethatitwillbeuseful,but*
WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAP
ARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldhaverec
eivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;if
not,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA0211
0-1301USA*/#ifndef_QUAGGA_BGP_DAMP_H#define_QUAGGA_BGP_DAMP_H/*Structuremaintain
edonaper-routebasis.*/structbgp_damp_info{/*Doublylinkedlist.Thisinformationmust
belinkedtoreuse_listorno_reuse_list.*/structbgp_damp_info*next;structbgp_damp_in
fo*prev;/*Figure-of-merit.*/unsignedintpenalty;/*Numberofflapping.*/unsignedintf
lap;/*Firstflaptime*/time_tstart_time;/*Lasttimepenaltywasupdated.*/time_tt_upda
ted;/*Timeofroutestarttobesuppressed.*/time_tsuppress_time;/*Backreferencetobgp_
info.*/structbgp_info*binfo;/*Backreferencetobgp_node.*/structbgp_node*rn;/*Curr
entindexinthereuse_list.*/intindex;/*Lasttimemessagetype.*/uint8_tlastrecord;#de
fineBGP_RECORD_UPDATE1U#defineBGP_RECORD_WITHDRAW2Uafi_tafi;safi_tsafi;};/*Speci
fiedparametersetconfiguration.*/structbgp_damp_config{/*Valueoverwhichroutessupp
ressed.*/unsignedintsuppress_value;/*Valuebelowwhichsuppressedroutesreused.*/uns
ignedintreuse_limit;/*Maxtimearoutecanbesuppressed.*/time_tmax_suppress_time;/*T
imeduringwhichaccumulatedpenaltyreducesbyhalf.*/time_thalf_life;/*Non-configurab
leparametersbutfixedatimplementationtime.*Tochangethisvalues,init_bgp_damp()shou
ldbemodified.*/time_ttmax;/*Maxtimepreviousinstabilityretained*/unsignedintreuse
_list_size;/*Numberofreuselists*/unsignedintreuse_index_size;/*Sizeofreuseindexa
rray*//*Non-configurableparameters.Mostofthesearecalculatedfrom*theconfigurablep
arametersabove.*/unsignedintceiling;/*Maxvalueapenaltycanattain*/unsignedintdeca
y_rate_per_tick;/*Calculatedfromhalf-life*/unsignedintdecay_array_size;/*Calcula
tedusingconfigparameters*/doublescale_factor;unsignedintreuse_scale_factor;/*Dec
ayarrayper-setbased.*/double*decay_array;/*Reuseindexarrayper-setbased.*/int*reu
se_index;/*Reuselistarrayper-setbased.*/structbgp_damp_info**reuse_list;intreuse
_offset;/*Alldampeninginformationwhichisnotonreuselist.*/structbgp_damp_info*no_
reuse_list;/*Reusetimerthreadper-setbase.*/structthread*t_reuse;};#defineBGP_DAM
P_NONE0#defineBGP_DAMP_USED1#defineBGP_DAMP_SUPPRESSED2/*Timegranularityforreuse
lists*/#defineDELTA_REUSE10/*Timegranularityfordecayarrays*/#defineDELTA_T5#defi
neDEFAULT_PENALTY1000#defineDEFAULT_HALF_LIFE15#defineDEFAULT_REUSE750#defineDEF
AULT_SUPPRESS2000#defineREUSE_LIST_SIZE256#defineREUSE_ARRAY_SIZE1024externintbg
p_damp_enable(structbgp*,afi_t,safi_t,time_t,unsignedint,unsignedint,time_t);ext
ernintbgp_damp_disable(structbgp*,afi_t,safi_t);externintbgp_damp_withdraw(struc
tbgp_info*,structbgp_node*,afi_t,safi_t,int);externintbgp_damp_update(structbgp_
info*,structbgp_node*,afi_t,safi_t);externintbgp_damp_scan(structbgp_info*,afi_t
,safi_t);externvoidbgp_damp_info_free(structbgp_damp_info*,int);externvoidbgp_da
mp_info_clean(void);externintbgp_damp_decay(time_t,int);externvoidbgp_config_wri
te_damp(structvty*);externvoidbgp_damp_info_vty(structvty*,structbgp_info*,json_
object*json_path);externconstchar*bgp_damp_reuse_time_vty(structvty*,structbgp_i
nfo*,char*,size_t,uint8_t,json_object*);externintbgp_show_dampening_parameters(s
tructvty*vty,afi_t,safi_t);#endif/*_QUAGGA_BGP_DAMP_H*/