/*BGPExtendedCommunitiesAttribute.*Copyright(C)2000KunihiroIshiguro<kunihiro@zeb
ra.org>**ThisfileispartofGNUZebra.**GNUZebraisfreesoftware;youcanredistributeita
nd/ormodifyit*underthetermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoft
wareFoundation;eitherversion2,or(atyouroption)any*laterversion.**GNUZebraisdistr
ibutedinthehopethatitwillbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwa
rrantyof*MERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLi
censeformoredetails.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealon
g*withthisprogram;seethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.
,51FranklinSt,FifthFloor,Boston,MA02110-1301USA*/#ifndef_QUAGGA_BGP_ECOMMUNITY_H
#define_QUAGGA_BGP_ECOMMUNITY_H/*High-orderoctetoftheExtendedCommunitiestypefiel
d.*/#defineECOMMUNITY_ENCODE_AS0x00#defineECOMMUNITY_ENCODE_IP0x01#defineECOMMUN
ITY_ENCODE_AS40x02#defineECOMMUNITY_ENCODE_OPAQUE0x03#defineECOMMUNITY_ENCODE_EV
PN0x06#defineECOMMUNITY_ENCODE_TRANS_EXP0x80/*FlowSpec*//*RFC7674*/#defineECOMMU
NITY_EXTENDED_COMMUNITY_PART_20x81#defineECOMMUNITY_EXTENDED_COMMUNITY_PART_30x8
2/*Low-orderoctetoftheExtendedCommunitiestypefield.*/#defineECOMMUNITY_ROUTE_TAR
GET0x02#defineECOMMUNITY_SITE_ORIGIN0x03#defineECOMMUNITY_TRAFFIC_RATE0x06/*Flow
Spec*/#defineECOMMUNITY_TRAFFIC_ACTION0x07#defineECOMMUNITY_REDIRECT_VRF0x08#def
ineECOMMUNITY_TRAFFIC_MARKING0x09#defineECOMMUNITY_REDIRECT_IP_NH0x00/*Low-order
octetoftheExtendedCommunitiestypefieldforEVPNtypes*/#defineECOMMUNITY_EVPN_SUBTY
PE_MACMOBILITY0x00#defineECOMMUNITY_EVPN_SUBTYPE_ESI_LABEL0x01#defineECOMMUNITY_
EVPN_SUBTYPE_ES_IMPORT_RT0x02#defineECOMMUNITY_EVPN_SUBTYPE_ROUTERMAC0x03#define
ECOMMUNITY_EVPN_SUBTYPE_DEF_GW0x0d#defineECOMMUNITY_EVPN_SUBTYPE_MACMOBILITY_FLA
G_STICKY0x01/*Low-orderoctetoftheExtendedCommunitiestypefieldforOPAQUEtypes*/#de
fineECOMMUNITY_OPAQUE_SUBTYPE_ENCAP0x0c/*Extendedcommunitiesattributestringforma
t.*/#defineECOMMUNITY_FORMAT_ROUTE_MAP0#defineECOMMUNITY_FORMAT_COMMUNITY_LIST1#
defineECOMMUNITY_FORMAT_DISPLAY2/*ExtendedCommunitiesvalueiseightoctetlong.*/#de
fineECOMMUNITY_SIZE8/*ExtendedCommunitiestypeflag.*/#defineECOMMUNITY_FLAG_NON_T
RANSITIVE0x40/*ExtendedCommunitiesattribute.*/structecommunity{/*Referencecounte
r.*/unsignedlongrefcnt;/*SizeofExtendedCommunitiesattribute.*/intsize;/*Extended
Communitiesvalue.*/uint8_t*val;/*Humanreadableformatstring.*/char*str;};structec
ommunity_as{as_tas;uint32_tval;};structecommunity_ip{structin_addrip;uint16_tval
;};/*Extendedcommunityvalueiseightoctet.*/structecommunity_val{charval[ECOMMUNIT
Y_SIZE];};#defineecom_length(X)((X)->size*ECOMMUNITY_SIZE)/**EncodeBGPRouteTarge
tAS:nn.*/staticinlinevoidencode_route_target_as(as_tas,uint32_tval,structecommun
ity_val*eval){eval->val[0]=ECOMMUNITY_ENCODE_AS;eval->val[1]=ECOMMUNITY_ROUTE_TA
RGET;eval->val[2]=(as>>8)&0xff;eval->val[3]=as&0xff;eval->val[4]=(val>>24)&0xff;
eval->val[5]=(val>>16)&0xff;eval->val[6]=(val>>8)&0xff;eval->val[7]=val&0xff;}/*
*EncodeBGPRouteTargetIP:nn.*/staticinlinevoidencode_route_target_ip(structin_add
rip,uint16_tval,structecommunity_val*eval){eval->val[0]=ECOMMUNITY_ENCODE_IP;eva
l->val[1]=ECOMMUNITY_ROUTE_TARGET;memcpy(&eval->val[2],&ip,sizeof(structin_addr)
);eval->val[6]=(val>>8)&0xff;eval->val[7]=val&0xff;}/**EncodeBGPRouteTargetAS4:n
n.*/staticinlinevoidencode_route_target_as4(as_tas,uint16_tval,structecommunity_
val*eval){eval->val[0]=ECOMMUNITY_ENCODE_AS4;eval->val[1]=ECOMMUNITY_ROUTE_TARGE
T;eval->val[2]=(as>>24)&0xff;eval->val[3]=(as>>16)&0xff;eval->val[4]=(as>>8)&0xf
f;eval->val[5]=as&0xff;eval->val[6]=(val>>8)&0xff;eval->val[7]=val&0xff;}externv
oidecommunity_init(void);externvoidecommunity_finish(void);externvoidecommunity_
free(structecommunity**);externstructecommunity*ecommunity_parse(uint8_t*,unsign
edshort);externstructecommunity*ecommunity_dup(structecommunity*);externstructec
ommunity*ecommunity_merge(structecommunity*,structecommunity*);externstructecomm
unity*ecommunity_uniq_sort(structecommunity*);externstructecommunity*ecommunity_
intern(structecommunity*);externintecommunity_cmp(constvoid*,constvoid*);externv
oidecommunity_unintern(structecommunity**);externunsignedintecommunity_hash_make
(void*);externstructecommunity*ecommunity_str2com(constchar*,int,int);externchar
*ecommunity_ecom2str(structecommunity*,int,int);externintecommunity_match(consts
tructecommunity*,conststructecommunity*);externchar*ecommunity_str(structecommun
ity*);externstructecommunity_val*ecommunity_lookup(conststructecommunity*,uint8_
t,uint8_t);externintecommunity_add_val(structecommunity*ecom,structecommunity_va
l*eval);/*forvpn*/externstructecommunity*ecommunity_new(void);externintecommunit
y_add_val(structecommunity*,structecommunity_val*);externintecommunity_strip(str
uctecommunity*ecom,uint8_ttype,uint8_tsubtype);externstructecommunity*ecommunity
_new(void);#endif/*_QUAGGA_BGP_ECOMMUNITY_H*/