/**OSPFInterfacefunctions.*Copyright(C)1999,2000ToshiakiTakada**Thisfileispartof
GNUZebra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodify*itundertheter
msoftheGNUGeneralPublicLicenseaspublished*bytheFreeSoftwareFoundation;eithervers
ion2,or(atyour*option)anylaterversion.**GNUZebraisdistributedinthehopethatitwill
beuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYo
rFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**You
shouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethef
ileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,
Boston,MA02110-1301USA*/#include<zebra.h>#include"thread.h"#include"linklist.h"#
include"prefix.h"#include"if.h"#include"table.h"#include"memory.h"#include"comma
nd.h"#include"stream.h"#include"log.h"#include"zclient.h"#include"bfd.h"#include
"ospfd/ospfd.h"#include"ospfd/ospf_spf.h"#include"ospfd/ospf_interface.h"#includ
e"ospfd/ospf_ism.h"#include"ospfd/ospf_asbr.h"#include"ospfd/ospf_lsa.h"#include
"ospfd/ospf_lsdb.h"#include"ospfd/ospf_neighbor.h"#include"ospfd/ospf_nsm.h"#inc
lude"ospfd/ospf_packet.h"#include"ospfd/ospf_abr.h"#include"ospfd/ospf_network.h
"#include"ospfd/ospf_dump.h"DEFINE_QOBJ_TYPE(ospf_interface)DEFINE_HOOK(ospf_vl_
add,(structospf_vl_data*vd),(vd))DEFINE_HOOK(ospf_vl_delete,(structospf_vl_data*
vd),(vd))intospf_interface_neighbor_count(structospf_interface*oi){intcount=0;st
ructroute_node*rn;structospf_neighbor*nbr=NULL;for(rn=route_top(oi->nbrs);rn;rn=
route_next(rn)){nbr=rn->info;if(nbr){/*Donotshowmyself.*/if(nbr==oi->nbr_self)co
ntinue;/*Downstateisnotshown.*/if(nbr->state==NSM_Down)continue;count++;}}return
count;}intospf_if_get_output_cost(structospf_interface*oi){/*Ifallelsefails,used
efaultOSPFcost*/uint32_tcost;uint32_tbw,refbw;/*ifpspeedandbwcanbe0insomeplatfor
ms,useospfdefaultbwifbwisconfiguredunderinterfaceitwouldbeused.*/if(!oi->ifp->ba
ndwidth&&oi->ifp->speed)bw=oi->ifp->speed;elsebw=oi->ifp->bandwidth?oi->ifp->ban
dwidth:OSPF_DEFAULT_BANDWIDTH;refbw=oi->ospf->ref_bandwidth;/*Aspecifedipospfcos
toverridesacalculatedone.*/if(OSPF_IF_PARAM_CONFIGURED(IF_DEF_PARAMS(oi->ifp),ou
tput_cost_cmd)||OSPF_IF_PARAM_CONFIGURED(oi->params,output_cost_cmd))cost=OSPF_I
F_PARAM(oi,output_cost_cmd);/*Seeifacostcanbecalculatedfromthezebraprocessesinte
rfacebandwidthfield.*/else{cost=(uint32_t)((double)refbw/(double)bw+(double)0.5)
;if(cost<1)cost=1;elseif(cost>65535)cost=65535;}returncost;}voidospf_if_recalcul
ate_output_cost(structinterface*ifp){uint32_tnewcost;structroute_node*rn;for(rn=
route_top(IF_OIFS(ifp));rn;rn=route_next(rn)){structospf_interface*oi;if((oi=rn-
>info)==NULL)continue;newcost=ospf_if_get_output_cost(oi);/*Isactualoutputcostch
anged?*/if(oi->output_cost!=newcost){oi->output_cost=newcost;ospf_router_lsa_upd
ate_area(oi->area);}}}/*Simulatedown/upontheinterface.Thisisneeded,forexample,wh
entheMTUchanges.*/voidospf_if_reset(structinterface*ifp){structroute_node*rn;for
(rn=route_top(IF_OIFS(ifp));rn;rn=route_next(rn)){structospf_interface*oi;if((oi
=rn->info)==NULL)continue;ospf_if_down(oi);ospf_if_up(oi);}}voidospf_if_reset_va
riables(structospf_interface*oi){/*Setdefaultvalues.*//*don'tclearthisflag.oi->f
lag=OSPF_IF_DISABLE;*/if(oi->vl_data)oi->type=OSPF_IFTYPE_VIRTUALLINK;else/*pres
ervenetwork-type*/if(oi->type!=OSPF_IFTYPE_NBMA)oi->type=OSPF_IFTYPE_BROADCAST;o
i->state=ISM_Down;oi->crypt_seqnum=0;/*Thismustbeshort,(lessthanRxmtInterval)-RF
C2328Section13.5para3.Setto1secondtoavoidAcksbeingheldbackfortoolong-MAG*/oi->v_
ls_ack=1;}/*lookupoiforspecifiedprefix/ifp*/structospf_interface*ospf_if_table_l
ookup(structinterface*ifp,structprefix*prefix){structprefixp;structroute_node*rn
;structospf_interface*rninfo=NULL;p=*prefix;p.prefixlen=IPV4_MAX_PREFIXLEN;/*rou
te_node_getimplicitelylocks*/if((rn=route_node_lookup(IF_OIFS(ifp),&p))){rninfo=
(structospf_interface*)rn->info;route_unlock_node(rn);}returnrninfo;}staticvoido
spf_add_to_if(structinterface*ifp,structospf_interface*oi){structroute_node*rn;s
tructprefixp;p=*oi->address;p.prefixlen=IPV4_MAX_PREFIXLEN;apply_mask(&p);rn=rou
te_node_get(IF_OIFS(ifp),&p);/*rn->infoshouldeitherbeNULLorequaltothisoi*asroute
_node_getmayreturnanexistingnode*/assert(!rn->info||rn->info==oi);rn->info=oi;}s
taticvoidospf_delete_from_if(structinterface*ifp,structospf_interface*oi){struct
route_node*rn;structprefixp;p=*oi->address;p.prefixlen=IPV4_MAX_PREFIXLEN;rn=rou
te_node_lookup(IF_OIFS(oi->ifp),&p);assert(rn);assert(rn->info);rn->info=NULL;ro
ute_unlock_node(rn);route_unlock_node(rn);}structospf_interface*ospf_if_new(stru
ctospf*ospf,structinterface*ifp,structprefix*p){structospf_interface*oi;if((oi=o
spf_if_table_lookup(ifp,p))==NULL){oi=XCALLOC(MTYPE_OSPF_IF,sizeof(structospf_in
terface));memset(oi,0,sizeof(structospf_interface));}elsereturnoi;/*Setzebrainte
rfacepointer.*/oi->ifp=ifp;oi->address=p;ospf_add_to_if(ifp,oi);listnode_add(osp
f->oiflist,oi);/*Initializeneighborlist.*/oi->nbrs=route_table_init();/*Initiali
zestaticneighborlist.*/oi->nbr_nbma=list_new();/*InitializeLinkStateAcknowledgme
ntlist.*/oi->ls_ack=list_new();oi->ls_ack_direct.ls_ack=list_new();/*Setdefaultv
alues.*/ospf_if_reset_variables(oi);/*SetpseudoneighbortoNull*/oi->nbr_self=NULL
;oi->ls_upd_queue=route_table_init();oi->t_ls_upd_event=NULL;oi->t_ls_ack_direct
=NULL;oi->crypt_seqnum=time(NULL);ospf_opaque_type9_lsa_init(oi);oi->ospf=ospf;Q
OBJ_REG(oi,ospf_interface);if(IS_DEBUG_OSPF_EVENT)zlog_debug("%s:ospfinterface%s
vrf%sid%ucreated",__PRETTY_FUNCTION__,ifp->name,ospf_vrf_id_to_name(ospf->vrf_id
),ospf->vrf_id);returnoi;}/*RestoreaninterfacetoitspreUPstateUsedfromism_interfa
ce_downonly*/voidospf_if_cleanup(structospf_interface*oi){structroute_node*rn;st
ructlistnode*node,*nnode;structospf_neighbor*nbr;structospf_nbr_nbma*nbr_nbma;st
ructospf_lsa*lsa;/*oi->nbrsandoi->nbr_nbmashouldbedeletedonInterfaceDownevent*//
*deleteallstaticneighborsattachedtothisinterface*/for(ALL_LIST_ELEMENTS(oi->nbr_
nbma,node,nnode,nbr_nbma)){OSPF_POLL_TIMER_OFF(nbr_nbma->t_poll);if(nbr_nbma->nb
r){nbr_nbma->nbr->nbr_nbma=NULL;nbr_nbma->nbr=NULL;}nbr_nbma->oi=NULL;listnode_d
elete(oi->nbr_nbma,nbr_nbma);}/*sendNeighboreventKillNbrtoallassociatedneighbors
.*/for(rn=route_top(oi->nbrs);rn;rn=route_next(rn))if((nbr=rn->info)!=NULL)if(nb
r!=oi->nbr_self)OSPF_NSM_EVENT_EXECUTE(nbr,NSM_KillNbr);/*CleanupLinkStateAcknow
legdmentlist.*/for(ALL_LIST_ELEMENTS(oi->ls_ack,node,nnode,lsa))ospf_lsa_unlock(
&lsa);/*oi->ls_ack*/list_delete_all_node(oi->ls_ack);oi->crypt_seqnum=0;/*Emptyl
inkstateupdatequeue*/ospf_ls_upd_queue_empty(oi);/*Resetpseudoneighbor.*/ospf_nb
r_self_reset(oi,oi->ospf->router_id);}voidospf_if_free(structospf_interface*oi){
ospf_if_down(oi);assert(oi->state==ISM_Down);ospf_opaque_type9_lsa_term(oi);QOBJ
_UNREG(oi);/*FreePseudoNeighbour*/ospf_nbr_delete(oi->nbr_self);route_table_fini
sh(oi->nbrs);route_table_finish(oi->ls_upd_queue);/*Freeanyliststhatshouldbefree
d*/list_delete_and_null(&oi->nbr_nbma);list_delete_and_null(&oi->ls_ack);list_de
lete_and_null(&oi->ls_ack_direct.ls_ack);if(IS_DEBUG_OSPF_EVENT)zlog_debug("%s:o
spfinterface%svrf%sid%udeleted",__PRETTY_FUNCTION__,oi->ifp->name,ospf_vrf_id_to
_name(oi->ifp->vrf_id),oi->ifp->vrf_id);ospf_delete_from_if(oi->ifp,oi);listnode
_delete(oi->ospf->oiflist,oi);listnode_delete(oi->area->oiflist,oi);thread_cance
l_event(master,oi);memset(oi,0,sizeof(*oi));XFREE(MTYPE_OSPF_IF,oi);}intospf_if_
is_up(structospf_interface*oi){returnif_is_up(oi->ifp);}structospf_interface*osp
f_if_exists(structospf_interface*oic){structlistnode*node;structospf*ospf;struct
ospf_interface*oi;if(!oic)returnNULL;ospf=oic->ospf;if(ospf==NULL)returnNULL;for
(ALL_LIST_ELEMENTS_RO(ospf->oiflist,node,oi))if(oi==oic)returnoi;returnNULL;}/*L
ookupOSPFinterfacebyrouterLSAposistion*/structospf_interface*ospf_if_lookup_by_l
sa_pos(structospf_area*area,intlsa_pos){structlistnode*node;structospf_interface
*oi;for(ALL_LIST_ELEMENTS_RO(area->oiflist,node,oi)){if(lsa_pos>=oi->lsa_pos_beg
&&lsa_pos<oi->lsa_pos_end)returnoi;}returnNULL;}structospf_interface*ospf_if_loo
kup_by_local_addr(structospf*ospf,structinterface*ifp,structin_addraddress){stru
ctlistnode*node;structospf_interface*oi;for(ALL_LIST_ELEMENTS_RO(ospf->oiflist,n
ode,oi))if(oi->type!=OSPF_IFTYPE_VIRTUALLINK){if(ifp&&oi->ifp!=ifp)continue;if(I
PV4_ADDR_SAME(&address,&oi->address->u.prefix4))returnoi;}returnNULL;}structospf
_interface*ospf_if_lookup_by_prefix(structospf*ospf,structprefix_ipv4*p){structl
istnode*node;structospf_interface*oi;/*CheckeachInterface.*/for(ALL_LIST_ELEMENT
S_RO(ospf->oiflist,node,oi)){if(oi->type!=OSPF_IFTYPE_VIRTUALLINK){structprefixp
tmp;prefix_copy(&ptmp,CONNECTED_PREFIX(oi->connected));apply_mask(&ptmp);if(pref
ix_same(&ptmp,(structprefix*)p))returnoi;}}returnNULL;}/*determinereceivinginter
facebyifpandsourceaddress*/structospf_interface*ospf_if_lookup_recv_if(structosp
f*ospf,structin_addrsrc,structinterface*ifp){structroute_node*rn;structprefix_ip
v4addr;structospf_interface*oi,*match;addr.family=AF_INET;addr.prefix=src;addr.p
refixlen=IPV4_MAX_BITLEN;match=NULL;for(rn=route_top(IF_OIFS(ifp));rn;rn=route_n
ext(rn)){oi=rn->info;if(!oi)/*oicanbeNULLforPtPaliases*/continue;if(oi->type==OS
PF_IFTYPE_VIRTUALLINK)continue;if(if_is_loopback(oi->ifp)||if_is_vrf(oi->ifp))co
ntinue;if(CHECK_FLAG(oi->connected->flags,ZEBRA_IFA_UNNUMBERED))match=oi;elseif(
prefix_match(CONNECTED_PREFIX(oi->connected),(structprefix*)&addr)){if((match==N
ULL)||(match->address->prefixlen<oi->address->prefixlen))match=oi;}}returnmatch;
}staticvoidospf_if_reset_stats(structospf_interface*oi){oi->hello_in=oi->hello_o
ut=0;oi->db_desc_in=oi->db_desc_out=0;oi->ls_req_in=oi->ls_req_out=0;oi->ls_upd_
in=oi->ls_upd_out=0;oi->ls_ack_in=oi->ls_ack_out=0;}voidospf_if_stream_set(struc
tospf_interface*oi){/*setoutputfifoqueue.*/if(oi->obuf==NULL)oi->obuf=ospf_fifo_
new();}voidospf_if_stream_unset(structospf_interface*oi){structospf*ospf=oi->osp
f;if(oi->obuf){ospf_fifo_free(oi->obuf);oi->obuf=NULL;/*resetprotocolstats*/ospf
_if_reset_stats(oi);if(oi->on_write_q){listnode_delete(ospf->oi_write_q,oi);if(l
ist_isempty(ospf->oi_write_q))OSPF_TIMER_OFF(ospf->t_write);oi->on_write_q=0;}}}
staticstructospf_if_params*ospf_new_if_params(void){structospf_if_params*oip;oip
=XCALLOC(MTYPE_OSPF_IF_PARAMS,sizeof(structospf_if_params));if(!oip)returnNULL;U
NSET_IF_PARAM(oip,output_cost_cmd);UNSET_IF_PARAM(oip,transmit_delay);UNSET_IF_P
ARAM(oip,retransmit_interval);UNSET_IF_PARAM(oip,passive_interface);UNSET_IF_PAR
AM(oip,v_hello);UNSET_IF_PARAM(oip,fast_hello);UNSET_IF_PARAM(oip,v_wait);UNSET_
IF_PARAM(oip,priority);UNSET_IF_PARAM(oip,type);UNSET_IF_PARAM(oip,auth_simple);
UNSET_IF_PARAM(oip,auth_crypt);UNSET_IF_PARAM(oip,auth_type);oip->auth_crypt=lis
t_new();oip->network_lsa_seqnum=htonl(OSPF_INITIAL_SEQUENCE_NUMBER);returnoip;}v
oidospf_del_if_params(structospf_if_params*oip){list_delete_and_null(&oip->auth_
crypt);bfd_info_free(&(oip->bfd_info));XFREE(MTYPE_OSPF_IF_PARAMS,oip);}voidospf
_free_if_params(structinterface*ifp,structin_addraddr){structospf_if_params*oip;
structprefix_ipv4p;structroute_node*rn;p.family=AF_INET;p.prefixlen=IPV4_MAX_PRE
FIXLEN;p.prefix=addr;rn=route_node_lookup(IF_OIFS_PARAMS(ifp),(structprefix*)&p)
;if(!rn||!rn->info)return;oip=rn->info;route_unlock_node(rn);if(!OSPF_IF_PARAM_C
ONFIGURED(oip,output_cost_cmd)&&!OSPF_IF_PARAM_CONFIGURED(oip,transmit_delay)&&!
OSPF_IF_PARAM_CONFIGURED(oip,retransmit_interval)&&!OSPF_IF_PARAM_CONFIGURED(oip
,passive_interface)&&!OSPF_IF_PARAM_CONFIGURED(oip,v_hello)&&!OSPF_IF_PARAM_CONF
IGURED(oip,fast_hello)&&!OSPF_IF_PARAM_CONFIGURED(oip,v_wait)&&!OSPF_IF_PARAM_CO
NFIGURED(oip,priority)&&!OSPF_IF_PARAM_CONFIGURED(oip,type)&&!OSPF_IF_PARAM_CONF
IGURED(oip,auth_simple)&&!OSPF_IF_PARAM_CONFIGURED(oip,auth_type)&&listcount(oip
->auth_crypt)==0&&ntohl(oip->network_lsa_seqnum)!=OSPF_INITIAL_SEQUENCE_NUMBER){
ospf_del_if_params(oip);rn->info=NULL;route_unlock_node(rn);}}structospf_if_para
ms*ospf_lookup_if_params(structinterface*ifp,structin_addraddr){structprefix_ipv
4p;structroute_node*rn;p.family=AF_INET;p.prefixlen=IPV4_MAX_PREFIXLEN;p.prefix=
addr;rn=route_node_lookup(IF_OIFS_PARAMS(ifp),(structprefix*)&p);if(rn){route_un
lock_node(rn);returnrn->info;}returnNULL;}structospf_if_params*ospf_get_if_param
s(structinterface*ifp,structin_addraddr){structprefix_ipv4p;structroute_node*rn;
p.family=AF_INET;p.prefixlen=IPV4_MAX_PREFIXLEN;p.prefix=addr;apply_mask_ipv4(&p
);rn=route_node_get(IF_OIFS_PARAMS(ifp),(structprefix*)&p);if(rn->info==NULL)rn-
>info=ospf_new_if_params();elseroute_unlock_node(rn);returnrn->info;}voidospf_if
_update_params(structinterface*ifp,structin_addraddr){structroute_node*rn;struct
ospf_interface*oi;for(rn=route_top(IF_OIFS(ifp));rn;rn=route_next(rn)){if((oi=rn
->info)==NULL)continue;if(IPV4_ADDR_SAME(&oi->address->u.prefix4,&addr))oi->para
ms=ospf_lookup_if_params(ifp,oi->address->u.prefix4);}}intospf_if_new_hook(struc
tinterface*ifp){intrc=0;ifp->info=XCALLOC(MTYPE_OSPF_IF_INFO,sizeof(structospf_i
f_info));IF_OIFS(ifp)=route_table_init();IF_OIFS_PARAMS(ifp)=route_table_init();
IF_DEF_PARAMS(ifp)=ospf_new_if_params();SET_IF_PARAM(IF_DEF_PARAMS(ifp),transmit
_delay);IF_DEF_PARAMS(ifp)->transmit_delay=OSPF_TRANSMIT_DELAY_DEFAULT;SET_IF_PA
RAM(IF_DEF_PARAMS(ifp),retransmit_interval);IF_DEF_PARAMS(ifp)->retransmit_inter
val=OSPF_RETRANSMIT_INTERVAL_DEFAULT;SET_IF_PARAM(IF_DEF_PARAMS(ifp),priority);I
F_DEF_PARAMS(ifp)->priority=OSPF_ROUTER_PRIORITY_DEFAULT;IF_DEF_PARAMS(ifp)->mtu
_ignore=OSPF_MTU_IGNORE_DEFAULT;SET_IF_PARAM(IF_DEF_PARAMS(ifp),v_hello);IF_DEF_
PARAMS(ifp)->v_hello=OSPF_HELLO_INTERVAL_DEFAULT;SET_IF_PARAM(IF_DEF_PARAMS(ifp)
,fast_hello);IF_DEF_PARAMS(ifp)->fast_hello=OSPF_FAST_HELLO_DEFAULT;SET_IF_PARAM
(IF_DEF_PARAMS(ifp),v_wait);IF_DEF_PARAMS(ifp)->v_wait=OSPF_ROUTER_DEAD_INTERVAL
_DEFAULT;SET_IF_PARAM(IF_DEF_PARAMS(ifp),auth_simple);memset(IF_DEF_PARAMS(ifp)-
>auth_simple,0,OSPF_AUTH_SIMPLE_SIZE);SET_IF_PARAM(IF_DEF_PARAMS(ifp),auth_type)
;IF_DEF_PARAMS(ifp)->auth_type=OSPF_AUTH_NOTSET;rc=ospf_opaque_new_if(ifp);retur
nrc;}staticintospf_if_delete_hook(structinterface*ifp){intrc=0;structroute_node*
rn;rc=ospf_opaque_del_if(ifp);route_table_finish(IF_OIFS(ifp));for(rn=route_top(
IF_OIFS_PARAMS(ifp));rn;rn=route_next(rn))if(rn->info)ospf_del_if_params(rn->inf
o);route_table_finish(IF_OIFS_PARAMS(ifp));ospf_del_if_params((structospf_if_par
ams*)IF_DEF_PARAMS(ifp));XFREE(MTYPE_OSPF_IF_INFO,ifp->info);ifp->info=NULL;retu
rnrc;}intospf_if_is_enable(structospf_interface*oi){if(!(if_is_loopback(oi->ifp)
||if_is_vrf(oi->ifp)))if(if_is_up(oi->ifp))return1;return0;}voidospf_if_set_mult
icast(structospf_interface*oi){if((oi->state>ISM_Loopback)&&(oi->type!=OSPF_IFTY
PE_LOOPBACK)&&(oi->type!=OSPF_IFTYPE_VIRTUALLINK)&&(OSPF_IF_PASSIVE_STATUS(oi)==
OSPF_IF_ACTIVE)){/*TheinterfaceshouldbelongtotheOSPF-all-routersgroup.*/if(!OI_M
EMBER_CHECK(oi,MEMBER_ALLROUTERS)&&(ospf_if_add_allspfrouters(oi->ospf,oi->addre
ss,oi->ifp->ifindex)>=0))/*Settheflagonlyifthesystemcalltojoin*succeeded.*/OI_ME
MBER_JOINED(oi,MEMBER_ALLROUTERS);}else{/*TheinterfaceshouldNOTbelongtotheOSPF-a
ll-routers*group.*/if(OI_MEMBER_CHECK(oi,MEMBER_ALLROUTERS)){/*Onlyactuallydropi
fthisisthelastreference*/if(OI_MEMBER_COUNT(oi,MEMBER_ALLROUTERS)==1)ospf_if_dro
p_allspfrouters(oi->ospf,oi->address,oi->ifp->ifindex);/*Unsettheflagregardlesso
fwhetherthesystemcalltoleavethegroupsucceeded,sinceit'smuchsafertoassumethatwear
enotamember.*/OI_MEMBER_LEFT(oi,MEMBER_ALLROUTERS);}}if(((oi->type==OSPF_IFTYPE_
BROADCAST)||(oi->type==OSPF_IFTYPE_POINTOPOINT))&&((oi->state==ISM_DR)||(oi->sta
te==ISM_Backup))&&(OSPF_IF_PASSIVE_STATUS(oi)==OSPF_IF_ACTIVE)){/*Theinterfacesh
ouldbelongtotheOSPF-designated-routers*group.*/if(!OI_MEMBER_CHECK(oi,MEMBER_DRO
UTERS)&&(ospf_if_add_alldrouters(oi->ospf,oi->address,oi->ifp->ifindex)>=0))/*Se
ttheflagonlyifthesystemcalltojoin*succeeded.*/OI_MEMBER_JOINED(oi,MEMBER_DROUTER
S);}else{/*TheinterfaceshouldNOTbelongtothe*OSPF-designated-routersgroup*/if(OI_
MEMBER_CHECK(oi,MEMBER_DROUTERS)){/*droponlyiflastreference*/if(OI_MEMBER_COUNT(
oi,MEMBER_DROUTERS)==1)ospf_if_drop_alldrouters(oi->ospf,oi->address,oi->ifp->if
index);/*Unsettheflagregardlessofwhetherthesystemcalltoleavethegroupsucceeded,si
nceit'smuchsafertoassumethatwearenotamember.*/OI_MEMBER_LEFT(oi,MEMBER_DROUTERS)
;}}}intospf_if_up(structospf_interface*oi){if(oi==NULL)return0;if(oi->type==OSPF
_IFTYPE_LOOPBACK)OSPF_ISM_EVENT_SCHEDULE(oi,ISM_LoopInd);else{ospf_if_stream_set
(oi);OSPF_ISM_EVENT_SCHEDULE(oi,ISM_InterfaceUp);}return1;}intospf_if_down(struc
tospf_interface*oi){if(oi==NULL)return0;OSPF_ISM_EVENT_EXECUTE(oi,ISM_InterfaceD
own);/*deletepositioninrouterLSA*/oi->lsa_pos_beg=0;oi->lsa_pos_end=0;/*Shutdown
packetreceptionandsending*/ospf_if_stream_unset(oi);return1;}/*VirtualLinkrelate
dfunctions.*/structospf_vl_data*ospf_vl_data_new(structospf_area*area,structin_a
ddrvl_peer){structospf_vl_data*vl_data;vl_data=XCALLOC(MTYPE_OSPF_VL_DATA,sizeof
(structospf_vl_data));vl_data->vl_peer.s_addr=vl_peer.s_addr;vl_data->vl_area_id
=area->area_id;vl_data->vl_area_id_fmt=area->area_id_fmt;returnvl_data;}voidospf
_vl_data_free(structospf_vl_data*vl_data){XFREE(MTYPE_OSPF_VL_DATA,vl_data);}uns
ignedintvlink_count=0;structospf_interface*ospf_vl_new(structospf*ospf,structosp
f_vl_data*vl_data){structospf_interface*voi;structinterface*vi;charifname[INTERF
ACE_NAMSIZ];structospf_area*area;structin_addrarea_id;structconnected*co;structp
refix_ipv4*p;if(IS_DEBUG_OSPF_EVENT)zlog_debug("ospf_vl_new():Start");if(vlink_c
ount==OSPF_VL_MAX_COUNT){if(IS_DEBUG_OSPF_EVENT)zlog_debug("ospf_vl_new():Alarm:
""cannotcreatemorethanOSPF_MAX_VL_COUNTvirtuallinks");returnNULL;}if(IS_DEBUG_OS
PF_EVENT)zlog_debug("ospf_vl_new():creatingpseudozebrainterfacevrfid%u",ospf->vr
f_id);snprintf(ifname,sizeof(ifname),"VLINK%d",vlink_count);vi=if_create(ifname,
ospf->vrf_id);/**if_createsetsZEBRA_INTERFACE_LINKDETECTION*virtuallinksdon'tnee
dthis.*/UNSET_FLAG(vi->status,ZEBRA_INTERFACE_LINKDETECTION);co=connected_new();
co->ifp=vi;listnode_add(vi->connected,co);p=prefix_ipv4_new();p->family=AF_INET;
p->prefix.s_addr=0;p->prefixlen=0;co->address=(structprefix*)p;voi=ospf_if_new(o
spf,vi,co->address);if(voi==NULL){if(IS_DEBUG_OSPF_EVENT)zlog_debug("ospf_vl_new
():Alarm:OSPFintstructureisnotcreated");returnNULL;}voi->connected=co;voi->vl_da
ta=vl_data;voi->ifp->mtu=OSPF_VL_MTU;voi->type=OSPF_IFTYPE_VIRTUALLINK;vlink_cou
nt++;if(IS_DEBUG_OSPF_EVENT)zlog_debug("ospf_vl_new():Createdname:%s",ifname);if
(IS_DEBUG_OSPF_EVENT)zlog_debug("ospf_vl_new():setif->nameto%s",vi->name);area_i
d.s_addr=0;area=ospf_area_get(ospf,area_id);voi->area=area;if(IS_DEBUG_OSPF_EVEN
T)zlog_debug("ospf_vl_new():setassociatedareatothebackbone");/*Addpseudoneighbor
.*/ospf_nbr_self_reset(voi,voi->ospf->router_id);ospf_area_add_if(voi->area,voi)
;ospf_if_stream_set(voi);if(IS_DEBUG_OSPF_EVENT)zlog_debug("ospf_vl_new():Stop")
;returnvoi;}staticvoidospf_vl_if_delete(structospf_vl_data*vl_data){structinterf
ace*ifp=vl_data->vl_oi->ifp;vl_data->vl_oi->address->u.prefix4.s_addr=0;vl_data-
>vl_oi->address->prefixlen=0;ospf_if_free(vl_data->vl_oi);if_delete(ifp);vlink_c
ount--;}/*Lookupvl_dataforgivenpeer,optionallyqualifiedtobeinthe*specifiedarea.N
ULLareareturnsfirstfound..*/structospf_vl_data*ospf_vl_lookup(structospf*ospf,st
ructospf_area*area,structin_addrvl_peer){structospf_vl_data*vl_data;structlistno
de*node;if(IS_DEBUG_OSPF_EVENT){zlog_debug("%s:Lookingfor%s",__func__,inet_ntoa(
vl_peer));if(area)zlog_debug("%s:inarea%s",__func__,inet_ntoa(area->area_id));}f
or(ALL_LIST_ELEMENTS_RO(ospf->vlinks,node,vl_data)){if(IS_DEBUG_OSPF_EVENT)zlog_
debug("%s:VL%s,peer%s",__func__,vl_data->vl_oi->ifp->name,inet_ntoa(vl_data->vl_
peer));if(area&&!IPV4_ADDR_SAME(&vl_data->vl_area_id,&area->area_id))continue;if
(IPV4_ADDR_SAME(&vl_data->vl_peer,&vl_peer))returnvl_data;}returnNULL;}staticvoi
dospf_vl_shutdown(structospf_vl_data*vl_data){structospf_interface*oi;if((oi=vl_
data->vl_oi)==NULL)return;oi->address->u.prefix4.s_addr=0;oi->address->prefixlen
=0;UNSET_FLAG(oi->ifp->flags,IFF_UP);/*OSPF_ISM_EVENT_SCHEDULE(oi,ISM_InterfaceD
own);*/OSPF_ISM_EVENT_EXECUTE(oi,ISM_InterfaceDown);}voidospf_vl_add(structospf*
ospf,structospf_vl_data*vl_data){listnode_add(ospf->vlinks,vl_data);hook_call(os
pf_vl_add,vl_data);}voidospf_vl_delete(structospf*ospf,structospf_vl_data*vl_dat
a){ospf_vl_shutdown(vl_data);ospf_vl_if_delete(vl_data);hook_call(ospf_vl_delete
,vl_data);listnode_delete(ospf->vlinks,vl_data);ospf_vl_data_free(vl_data);}stat
icintospf_vl_set_params(structospf_vl_data*vl_data,structvertex*v){intchanged=0;
structospf_interface*voi;structlistnode*node;structvertex_parent*vp=NULL;unsigne
dinti;structrouter_lsa*rl;voi=vl_data->vl_oi;if(voi->output_cost!=v->distance){v
oi->output_cost=v->distance;changed=1;}for(ALL_LIST_ELEMENTS_RO(v->parents,node,
vp)){vl_data->nexthop.oi=vp->nexthop->oi;vl_data->nexthop.router=vp->nexthop->ro
uter;if(!IPV4_ADDR_SAME(&voi->address->u.prefix4,&vl_data->nexthop.oi->address->
u.prefix4))changed=1;voi->address->u.prefix4=vl_data->nexthop.oi->address->u.pre
fix4;voi->address->prefixlen=vl_data->nexthop.oi->address->prefixlen;break;/*Wet
akethefirstinterface.*/}rl=(structrouter_lsa*)v->lsa;/*useSPFdeterminedbacklinki
ndexinstructvertex*forvirtuallinkdestinationaddress*/if(vp&&vp->backlink>=0){if(
!IPV4_ADDR_SAME(&vl_data->peer_addr,&rl->link[vp->backlink].link_data))changed=1
;vl_data->peer_addr=rl->link[vp->backlink].link_data;}else{/*Thisishighlyodd,the
reisnobacklinkindex*thereshouldbeduetotheospf_spf_has_link()check*inSPF.Letswarn
andtrypickalinkanyway.*/zlog_warn("ospf_vl_set_params:Nobacklinkfor%s!",vl_data-
>vl_oi->ifp->name);for(i=0;i<ntohs(rl->links);i++){switch(rl->link[i].type){case
LSA_LINK_TYPE_VIRTUALLINK:if(IS_DEBUG_OSPF_EVENT)zlog_debug("foundbacklinkthroug
hVL");/*fallthru*/caseLSA_LINK_TYPE_TRANSIT:caseLSA_LINK_TYPE_POINTOPOINT:if(!IP
V4_ADDR_SAME(&vl_data->peer_addr,&rl->link[i].link_data))changed=1;vl_data->peer
_addr=rl->link[i].link_data;}}}if(IS_DEBUG_OSPF_EVENT)zlog_debug("%s:%speeraddre
ss:%s,cost:%d,%schanged",__func__,vl_data->vl_oi->ifp->name,inet_ntoa(vl_data->p
eer_addr),voi->output_cost,(changed?"":"un"));returnchanged;}voidospf_vl_up_chec
k(structospf_area*area,structin_addrrid,structvertex*v){structospf*ospf=area->os
pf;structlistnode*node;structospf_vl_data*vl_data;structospf_interface*oi;if(IS_
DEBUG_OSPF_EVENT){zlog_debug("ospf_vl_up_check():Start");zlog_debug("ospf_vl_up_
check():RouterIDis%s",inet_ntoa(rid));zlog_debug("ospf_vl_up_check():Areais%s",i
net_ntoa(area->area_id));}for(ALL_LIST_ELEMENTS_RO(ospf->vlinks,node,vl_data)){i
f(IS_DEBUG_OSPF_EVENT){zlog_debug("%s:consideringVL,%sinarea%s",__func__,vl_data
->vl_oi->ifp->name,inet_ntoa(vl_data->vl_area_id));zlog_debug("%s:peerID:%s",__f
unc__,inet_ntoa(vl_data->vl_peer));}if(IPV4_ADDR_SAME(&vl_data->vl_peer,&rid)&&I
PV4_ADDR_SAME(&vl_data->vl_area_id,&area->area_id)){oi=vl_data->vl_oi;SET_FLAG(v
l_data->flags,OSPF_VL_FLAG_APPROVED);if(IS_DEBUG_OSPF_EVENT)zlog_debug("ospf_vl_
up_check():thisVLmatched");if(oi->state==ISM_Down){if(IS_DEBUG_OSPF_EVENT)zlog_d
ebug("ospf_vl_up_check():VLisdown,wakingitup");SET_FLAG(oi->ifp->flags,IFF_UP);O
SPF_ISM_EVENT_EXECUTE(oi,ISM_InterfaceUp);}if(ospf_vl_set_params(vl_data,v)){if(
IS_DEBUG_OSPF(ism,ISM_EVENTS))zlog_debug("ospf_vl_up_check:VLcostchange,""schedu
lingrouterlsarefresh");if(ospf->backbone)ospf_router_lsa_update_area(ospf->backb
one);elseif(IS_DEBUG_OSPF(ism,ISM_EVENTS))zlog_debug("ospf_vl_up_check:VLcostcha
nge,nobackbone!");}}}}voidospf_vl_unapprove(structospf*ospf){structlistnode*node
;structospf_vl_data*vl_data;for(ALL_LIST_ELEMENTS_RO(ospf->vlinks,node,vl_data))
UNSET_FLAG(vl_data->flags,OSPF_VL_FLAG_APPROVED);}voidospf_vl_shut_unapproved(st
ructospf*ospf){structlistnode*node,*nnode;structospf_vl_data*vl_data;for(ALL_LIS
T_ELEMENTS(ospf->vlinks,node,nnode,vl_data))if(!CHECK_FLAG(vl_data->flags,OSPF_V
L_FLAG_APPROVED))ospf_vl_shutdown(vl_data);}intospf_full_virtual_nbrs(structospf
_area*area){if(IS_DEBUG_OSPF_EVENT){zlog_debug("countingfullyadjacentvirtualneig
hborsinarea%s",inet_ntoa(area->area_id));zlog_debug("thereare%dofthem",area->ful
l_vls);}returnarea->full_vls;}intospf_vls_in_area(structospf_area*area){structli
stnode*node;structospf_vl_data*vl_data;intc=0;for(ALL_LIST_ELEMENTS_RO(area->osp
f->vlinks,node,vl_data))if(IPV4_ADDR_SAME(&vl_data->vl_area_id,&area->area_id))c
++;returnc;}structcrypt_key*ospf_crypt_key_new(){returnXCALLOC(MTYPE_OSPF_CRYPT_
KEY,sizeof(structcrypt_key));}voidospf_crypt_key_add(structlist*crypt,structcryp
t_key*ck){listnode_add(crypt,ck);}structcrypt_key*ospf_crypt_key_lookup(structli
st*auth_crypt,uint8_tkey_id){structlistnode*node;structcrypt_key*ck;for(ALL_LIST
_ELEMENTS_RO(auth_crypt,node,ck))if(ck->key_id==key_id)returnck;returnNULL;}into
spf_crypt_key_delete(structlist*auth_crypt,uint8_tkey_id){structlistnode*node,*n
node;structcrypt_key*ck;for(ALL_LIST_ELEMENTS(auth_crypt,node,nnode,ck)){if(ck->
key_id==key_id){listnode_delete(auth_crypt,ck);XFREE(MTYPE_OSPF_CRYPT_KEY,ck);re
turn1;}}return0;}uint8_tospf_default_iftype(structinterface*ifp){if(if_is_pointo
point(ifp))returnOSPF_IFTYPE_POINTOPOINT;elseif(if_is_loopback(ifp)||if_is_vrf(i
fp))returnOSPF_IFTYPE_LOOPBACK;elsereturnOSPF_IFTYPE_BROADCAST;}voidospf_if_init
(){/*InitializeZebrainterfacedatastructure.*/hook_register_prio(if_add,0,ospf_if
_new_hook);hook_register_prio(if_del,0,ospf_if_delete_hook);}