/**ThisisanimplementationofSegmentRouting*asperdraftdraft-ietf-ospf-segment-rout
ing-extensions-24**Modulename:SegmentRouting**Author:OlivierDugeon<olivier.dugeo
n@orange.com>*Author:AnselmeSawadogo<anselmesawadogo@gmail.com>**Copyright(C)201
6-2018OrangeLabshttp://www.orange.com**Thisprogramisfreesoftware;youcanredistrib
uteitand/ormodifyit*underthetermsoftheGNUGeneralPublicLicenseaspublishedbytheFre
e*SoftwareFoundation;eitherversion2oftheLicense,or(atyouroption)*anylaterversion
.**Thisprogramisdistributedinthehopethatitwillbeuseful,butWITHOUT*ANYWARRANTY;wi
thouteventheimpliedwarrantyofMERCHANTABILITYor*FITNESSFORAPARTICULARPURPOSE.Seet
heGNUGeneralPublicLicensefor*moredetails.**YoushouldhavereceivedacopyoftheGNUGen
eralPublicLicensealong*withthisprogram;seethefileCOPYING;ifnot,writetotheFreeSof
tware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-1301USA*/#include<m
ath.h>#include<stdio.h>#include<stdlib.h>#include<zebra.h>#include"command.h"#in
clude"hash.h"#include"if.h"#include"if.h"#include"jhash.h"#include"libospf.h"/*f
orospfinterfacetypes*/#include"linklist.h"#include"log.h"#include"memory.h"#incl
ude"monotime.h"#include"network.h"#include"prefix.h"#include"sockunion.h"/*forin
et_aton()*/#include"stream.h"#include"table.h"#include"thread.h"#include"vty.h"#
include"zclient.h"#include<lib/json.h>#include"ospfd/ospfd.h"#include"ospfd/ospf
_interface.h"#include"ospfd/ospf_ism.h"#include"ospfd/ospf_asbr.h"#include"ospfd
/ospf_lsa.h"#include"ospfd/ospf_lsdb.h"#include"ospfd/ospf_neighbor.h"#include"o
spfd/ospf_nsm.h"#include"ospfd/ospf_flood.h"#include"ospfd/ospf_packet.h"#includ
e"ospfd/ospf_spf.h"#include"ospfd/ospf_dump.h"#include"ospfd/ospf_route.h"#inclu
de"ospfd/ospf_ase.h"#include"ospfd/ospf_sr.h"#include"ospfd/ospf_ri.h"#include"o
spfd/ospf_ext.h"#include"ospfd/ospf_zebra.h"/**GlobalvariabletomanageSegmentRout
ingonthisnode.*Notethatallparametervaluesarestoredinnetworkbyteorder.*/staticstr
uctospf_sr_dbOspfSR;staticvoidospf_sr_register_vty(void);staticinlinevoiddel_sid
_nhlfe(structsr_nhlfenhlfe);/**SegmentRoutingDataBasefunctions*//*Hashfunctionfo
rSegmentRoutingentry*/staticunsignedintsr_hash(void*p){conststructin_addr*rid=p;
returnjhash_1word(rid->s_addr,0);}/*Compare2RouterIDhashentriesbasedonSRNode*/st
aticintsr_cmp(constvoid*p1,constvoid*p2){conststructsr_node*srn=p1;conststructin
_addr*rid=p2;returnIPV4_ADDR_SAME(&srn->adv_router,rid);}/*FunctionstoremoveanSR
Link*/staticvoiddel_sr_link(void*val){structsr_link*srl=(structsr_link*)val;del_
sid_nhlfe(srl->nhlfe[0]);del_sid_nhlfe(srl->nhlfe[1]);XFREE(MTYPE_OSPF_SR_PARAMS
,val);}/*FunctionstoremoveanSRPrefix*/staticvoiddel_sr_pref(void*val){structsr_p
refix*srp=(structsr_prefix*)val;del_sid_nhlfe(srp->nhlfe);XFREE(MTYPE_OSPF_SR_PA
RAMS,val);}/*AllocatenewSegmentRoutinenode*/staticstructsr_node*sr_node_new(stru
ctin_addr*rid){if(rid==NULL)returnNULL;structsr_node*new;/*AllocateSegmentRoutin
gnodememory*/new=XCALLOC(MTYPE_OSPF_SR_PARAMS,sizeof(structsr_node));/*SanityChe
ck*/if(new==NULL){zlog_err("SR(%s):Abort!can'tcreatenewSRnode",__func__);returnN
ULL;}/*DefaultAlgorithm,SRGBandMSD*/for(inti=0;i<ALGORITHM_COUNT;i++)new->algo[i
]=SR_ALGORITHM_UNSET;new->srgb.range_size=0;new->srgb.lower_bound=0;new->msd=0;/
*CreateLink,PrefixandRangeTLVslist*/new->ext_link=list_new();new->ext_prefix=lis
t_new();new->ext_link->del=del_sr_link;new->ext_prefix->del=del_sr_pref;IPV4_ADD
R_COPY(&new->adv_router,rid);new->neighbor=NULL;new->instance=0;if(IS_DEBUG_OSPF
_SR)zlog_debug("|-CreatednewSRnodefor%s",inet_ntoa(new->adv_router));returnnew;}
/*DeleteSegmentRoutingnode*/staticvoidsr_node_del(structsr_node*srn){/*SanityChe
ck*/if(srn==NULL)return;/*CleanExtendedLink*/list_delete_and_null(&srn->ext_link
);/*CleanPrefixList*/list_delete_and_null(&srn->ext_prefix);XFREE(MTYPE_OSPF_SR_
PARAMS,srn);}/*GetSRNodeforagivennexthop*/staticstructsr_node*get_sr_node_by_nex
thop(structospf*ospf,structin_addrnexthop){structospf_interface*oi=NULL;structos
pf_neighbor*nbr=NULL;structlistnode*node;structroute_node*rn;structsr_node*srn;b
oolfound;/*Sanitycheck*/if(OspfSR.neighbors==NULL)returnNULL;if(IS_DEBUG_OSPF_SR
)zlog_debug("|-SearchSR-Nodefornexthop%s",inet_ntoa(nexthop));/*First,searchneig
hborRouterIDforthisnexthop*/found=false;for(ALL_LIST_ELEMENTS_RO(ospf->oiflist,n
ode,oi)){for(rn=route_top(oi->nbrs);rn;rn=route_next(rn)){nbr=rn->info;if((nbr)&
&(IPV4_ADDR_SAME(&nexthop,&nbr->src))){found=true;break;}}if(found)break;}if(!fo
und)returnNULL;if(IS_DEBUG_OSPF_SR)zlog_debug("|-FoundnexthopRouterID%s",inet_nt
oa(nbr->router_id));/*Then,searchSRNode*/srn=(structsr_node*)hash_lookup(OspfSR.
neighbors,&nbr->router_id);returnsrn;}/**SegmentRoutingInitializationfunctions*/
/*SegmentRoutingstarterfunction*/staticintospf_sr_start(structospf*ospf){structr
oute_node*rn;structospf_lsa*lsa;structsr_node*srn;intrc=0;if(IS_DEBUG_OSPF_SR)zl
og_debug("SR(%s):StartSegmentRouting",__func__);/*InitializeselfSRNode*/srn=hash
_get(OspfSR.neighbors,(void*)&(ospf->router_id),(void*)sr_node_new);/*SanityChec
k*/if(srn==NULL)returnrc;/*Complete&StoreselfSRNode*/srn->srgb.range_size=OspfSR
.srgb.range_size;srn->srgb.lower_bound=OspfSR.srgb.lower_bound;srn->algo[0]=Ospf
SR.algo[0];srn->msd=OspfSR.msd;OspfSR.self=srn;if(IS_DEBUG_OSPF_EVENT)zlog_debug
("SR(%s):UpdateSR-DBfromLSDB",__func__);/*StartbylookingtoRouterInfo&ExtendedLSA
inlsdb*/if((ospf!=NULL)&&(ospf->backbone!=NULL)){LSDB_LOOP(OPAQUE_AREA_LSDB(ospf
->backbone),rn,lsa){if(IS_LSA_MAXAGE(lsa)||IS_LSA_SELF(lsa))continue;intlsa_id=G
ET_OPAQUE_TYPE(ntohl(lsa->data->id.s_addr));switch(lsa_id){caseOPAQUE_TYPE_ROUTE
R_INFORMATION_LSA:ospf_sr_ri_lsa_update(lsa);break;caseOPAQUE_TYPE_EXTENDED_PREF
IX_LSA:ospf_sr_ext_prefix_lsa_update(lsa);break;caseOPAQUE_TYPE_EXTENDED_LINK_LS
A:ospf_sr_ext_link_lsa_update(lsa);break;default:break;}}}rc=1;returnrc;}/*StopS
egmentRouting*/staticvoidospf_sr_stop(void){if(IS_DEBUG_OSPF_SR)zlog_debug("SR(%
s):StopSegmentRouting",__func__);/**RemoveallSRNodesfromtheHashtable.PrefixandLi
nkSIDwill*beremovethoughlist_delete_and_null()call.Seesr_node_del()*/hash_clean(
OspfSR.neighbors,(void*)sr_node_del);}/**SegmentRoutinginitializefunction**@para
m-nothing**@return0ifOK,-1otherwise*/intospf_sr_init(void){intrc=-1;if(IS_DEBUG_
OSPF_SR)zlog_info("SR(%s):InitializeSRDataBase",__func__);memset(&OspfSR,0,sizeo
f(structospf_sr_db));OspfSR.enabled=false;/*OnlyAREAfloodingissupportedinthisrel
ease*/OspfSR.scope=OSPF_OPAQUE_AREA_LSA;/*InitializeSRGB,AlgorithmsandMSDTLVs*//
*OnlyAlgorithmSPFissupported*/OspfSR.algo[0]=SR_ALGORITHM_SPF;for(inti=1;i<ALGOR
ITHM_COUNT;i++)OspfSR.algo[i]=SR_ALGORITHM_UNSET;OspfSR.srgb.range_size=MPLS_DEF
AULT_MAX_SRGB_SIZE;OspfSR.srgb.lower_bound=MPLS_DEFAULT_MIN_SRGB_LABEL;OspfSR.ms
d=0;/*InitializeHashtableforneighborSRnodes*/OspfSR.neighbors=hash_create(sr_has
h,sr_cmp,"OSPF_SR");if(OspfSR.neighbors==NULL)returnrc;/*InitializeRouteTablefor
prefix*/OspfSR.prefix=route_table_init();if(OspfSR.prefix==NULL)returnrc;/*Regis
terSegmentRoutingVTYcommand*/ospf_sr_register_vty();rc=0;returnrc;}/**SegmentRou
tingterminationfunction**@param-nothing*@return-nothing*/voidospf_sr_term(void){
/*StopSegmentRouting*/ospf_sr_stop();/*ClearSRNodeTable*/if(OspfSR.neighbors)has
h_free(OspfSR.neighbors);/*ClearPrefixTable*/if(OspfSR.prefix)route_table_finish
(OspfSR.prefix);OspfSR.enabled=false;OspfSR.self=NULL;}/**SegmentRoutingfinishfu
nction**@param-nothing*@return-nothing*/voidospf_sr_finish(void){/*StopSegmentRo
uting*/ospf_sr_stop();OspfSR.enabled=false;}/**Followingfunctionsareusedtomanipu
latethe*NextHopLabelForwardingentry(NHLFE)*//*Computelabelfromindex*/staticmpls_
label_tindex2label(uint32_tindex,structsr_srgbsrgb){mpls_label_tlabel;label=srgb
.lower_bound+index;if(label>(srgb.lower_bound+srgb.range_size))returnMPLS_INVALI
D_LABEL;elsereturnlabel;}/*Getneighborfullstructurefromaddress*/staticstructospf
_neighbor*get_neighbor_by_addr(structospf*top,structin_addraddr){structospf_neig
hbor*nbr;structospf_interface*oi;structlistnode*node;structroute_node*rn;/*Sanit
yCheck*/if(top==NULL)returnNULL;for(ALL_LIST_ELEMENTS_RO(top->oiflist,node,oi))f
or(rn=route_top(oi->nbrs);rn;rn=route_next(rn)){nbr=rn->info;if(nbr)if(IPV4_ADDR
_SAME(&nbr->address.u.prefix4,&addr)||IPV4_ADDR_SAME(&nbr->router_id,&addr)){rou
te_unlock_node(rn);returnnbr;}}returnNULL;}/*GetOSPFPathfromaddress*/staticstruc
tospf_path*get_nexthop_by_addr(structospf*top,structprefix_ipv4p){structospf_rou
te*or;structospf_path*path;structlistnode*node;structroute_node*rn;/*SanityCheck
*/if(top==NULL)returnNULL;if(IS_DEBUG_OSPF_SR)zlog_debug("|-SearchNexthopforpref
ix%s/%u",inet_ntoa(p.prefix),p.prefixlen);rn=route_node_lookup(top->new_table,(s
tructprefix*)&p);/**CheckifwefoundanOSPFroute.MaybeNULLifSPFhasnot*yetpopulatero
utingtableforthisprefix.*/if(rn==NULL)returnNULL;route_unlock_node(rn);or=rn->in
fo;if(or==NULL)returnNULL;/*Thensearchpathfromthisroute*/for(ALL_LIST_ELEMENTS_R
O(or->paths,node,path))if(path->nexthop.s_addr!=INADDR_ANY||path->ifindex!=0)ret
urnpath;returnNULL;}/*ComputeNHLFEentryforExtendedLink*/staticintcompute_link_nh
lfe(structsr_link*srl){structospf*top=ospf_lookup_by_vrf_id(VRF_DEFAULT);structo
spf_neighbor*nh;intrc=0;if(IS_DEBUG_OSPF_SR)zlog_debug("|-ComputeNHLFEforlink%s/
%u",inet_ntoa(srl->nhlfe[0].prefv4.prefix),srl->nhlfe[0].prefv4.prefixlen);/*Fir
stdeterminetheOSPFNeighbor*/nh=get_neighbor_by_addr(top,srl->nhlfe[0].nexthop);/
*NeighborcouldbenotfoundwhenOSPFAdjacencyjustfireup*becauseSPFdon'tyetpopulatero
utingtable.ThisNHLFEwill*befixedlaterwhenSRSPFschedulewillbecalled.*/if(nh==NULL
)returnrc;if(IS_DEBUG_OSPF_SR)zlog_debug("|-FoundnexthopNHLFE%s",inet_ntoa(nh->r
outer_id));/*Setifindexforthisneighbor*/srl->nhlfe[0].ifindex=nh->oi->ifp->ifind
ex;srl->nhlfe[1].ifindex=nh->oi->ifp->ifindex;/*UpdateneighboraddressforLAN_ADJ_
SID*/if(srl->type==LAN_ADJ_SID){IPV4_ADDR_COPY(&srl->nhlfe[0].nexthop,&nh->src);
IPV4_ADDR_COPY(&srl->nhlfe[1].nexthop,&nh->src);}/*SetInput&OutputLabel*/if(CHEC
K_FLAG(srl->flags[0],EXT_SUBTLV_LINK_ADJ_SID_VFLG))srl->nhlfe[0].label_in=srl->s
id[0];elsesrl->nhlfe[0].label_in=index2label(srl->sid[0],srl->srn->srgb);if(CHEC
K_FLAG(srl->flags[1],EXT_SUBTLV_LINK_ADJ_SID_VFLG))srl->nhlfe[1].label_in=srl->s
id[1];elsesrl->nhlfe[1].label_in=index2label(srl->sid[1],srl->srn->srgb);srl->nh
lfe[0].label_out=MPLS_LABEL_IMPLICIT_NULL;srl->nhlfe[1].label_out=MPLS_LABEL_IMP
LICIT_NULL;rc=1;returnrc;}/**ComputeNHLFEentryforExtendedPrefix**@paramsrp-Segme
ntRoutingPrefix**@return-1ifnexthopisnotfound,0ifnexthophasnotchanged*and1ifsucc
ess*/staticintcompute_prefix_nhlfe(structsr_prefix*srp){structospf*top=ospf_look
up_by_vrf_id(VRF_DEFAULT);structospf_path*nh=NULL;structsr_node*srnext;intrc=-1;
if(IS_DEBUG_OSPF_SR)zlog_debug("|-ComputeNHLFEforprefix%s/%u",inet_ntoa(srp->nhl
fe.prefv4.prefix),srp->nhlfe.prefv4.prefixlen);/*Firstdeterminethenexthop*/nh=ge
t_nexthop_by_addr(top,srp->nhlfe.prefv4);/*NexthopcouldbenotfoundwhenOSPFAdjacen
cyjustfireup*becauseSPFdon'tyetpopulateroutingtable.ThisNHLFEwill*befixedlaterwh
enSRSPFschedulewillbecalled.*/if(nh==NULL)returnrc;/*CheckifNextHophaschangedwhe
ncallafterrunninganewSPF*/if(IPV4_ADDR_SAME(&nh->nexthop,&srp->nhlfe.nexthop)&&(
nh->ifindex==srp->nhlfe.ifindex))return0;if(IS_DEBUG_OSPF_SR)zlog_debug("|-Found
newnexthopforthisNHLFE:%s",inet_ntoa(nh->nexthop));/**GetSR-Nodeforthisnexthop.C
ouldbenotyetavailable*asExtendeLink/PrefixandRouterInformationareflooded*afterLS
AType1&2whichpopulatetheOSPFRouteTable*/srnext=get_sr_node_by_nexthop(top,nh->ne
xthop);if(srnext==NULL)returnrc;/*AndstorethisinformationforlaterupdateifSRNodei
sfound*/srnext->neighbor=OspfSR.self;if(IPV4_ADDR_SAME(&srnext->adv_router,&srp-
>adv_router))srp->nexthop=NULL;elsesrp->nexthop=srnext;/**SRNodecouldbeknown,but
SRGBcouldbenotinitialize*ThisisduetothefactthatExtendedLink/Prefixcould*bereceiv
edbeforecorrespondingRouterInformationLSA*/if((srnext==NULL)||(srnext->srgb.lowe
r_bound==0)||(srnext->srgb.range_size==0))returnrc;if(IS_DEBUG_OSPF_SR)zlog_debu
g("|-FoundSRGB%u/%ufornexthopSR-Node%s",srnext->srgb.range_size,srnext->srgb.low
er_bound,inet_ntoa(srnext->adv_router));/*Setipaddr&ifindexforthisneighbor*/IPV4
_ADDR_COPY(&srp->nhlfe.nexthop,&nh->nexthop);srp->nhlfe.ifindex=nh->ifindex;/*Co
mputeInputLabelwithselfSRGB*/srp->nhlfe.label_in=index2label(srp->sid,OspfSR.srg
b);/**andOutputLabelwithNexthopSRNodeSRGBorImplicitNulllabel*ifnexthopisthedesti
nationandrequestPHP*/if((srp->nexthop==NULL)&&(!CHECK_FLAG(srp->flags,EXT_SUBTLV
_PREFIX_SID_NPFLG)))srp->nhlfe.label_out=MPLS_LABEL_IMPLICIT_NULL;elseif(CHECK_F
LAG(srp->flags,EXT_SUBTLV_PREFIX_SID_VFLG))srp->nhlfe.label_out=srp->sid;elsesrp
->nhlfe.label_out=index2label(srp->sid,srnext->srgb);if(IS_DEBUG_OSPF_SR)zlog_de
bug("|-Computednewlabelsin:%uout:%u",srp->nhlfe.label_in,srp->nhlfe.label_out);r
c=1;returnrc;}/*SendMPLSLabelentrytoZebraforinstallationordeletion*/staticintosp
f_zebra_send_mpls_labels(intcmd,structsr_nhlfenhlfe){structstream*s;/*Resetstrea
m.*/s=zclient->obuf;stream_reset(s);zclient_create_header(s,cmd,VRF_DEFAULT);str
eam_putc(s,ZEBRA_LSP_SR);/*OSPFSegmentRoutingcurrentlysupportonlyIPv4*/stream_pu
tl(s,nhlfe.prefv4.family);stream_put_in_addr(s,&nhlfe.prefv4.prefix);stream_putc
(s,nhlfe.prefv4.prefixlen);stream_put_in_addr(s,&nhlfe.nexthop);stream_putl(s,nh
lfe.ifindex);stream_putc(s,OSPF_SR_PRIORITY_DEFAULT);stream_putl(s,nhlfe.label_i
n);stream_putl(s,nhlfe.label_out);/*Putlengthatthefirstpointofthestream.*/stream
_putw_at(s,0,stream_get_endp(s));if(IS_DEBUG_OSPF_SR)zlog_debug("|-%sLSP%u/%ufor
%s/%uvia%u",cmd==ZEBRA_MPLS_LABELS_ADD?"Add":"Delete",nhlfe.label_in,nhlfe.label
_out,inet_ntoa(nhlfe.prefv4.prefix),nhlfe.prefv4.prefixlen,nhlfe.ifindex);return
zclient_send_message(zclient);}/*Requestzebratoinstall/removeFECinFIB*/staticint
ospf_zebra_send_mpls_ftn(intcmd,structsr_nhlfenhlfe){structzapi_routeapi;structz
api_nexthop*api_nh;/*SupportonlyIPv4*/if(nhlfe.prefv4.family!=AF_INET)return-1;m
emset(&api,0,sizeof(api));api.vrf_id=VRF_DEFAULT;api.type=ZEBRA_ROUTE_OSPF;api.s
afi=SAFI_UNICAST;memcpy(&api.prefix,&nhlfe.prefv4,sizeof(structprefix_ipv4));if(
cmd==ZEBRA_ROUTE_ADD){/*Metricvalue.*/SET_FLAG(api.message,ZAPI_MESSAGE_METRIC);
api.metric=OSPF_SR_DEFAULT_METRIC;/*Nexthop*/SET_FLAG(api.message,ZAPI_MESSAGE_N
EXTHOP);api_nh=&api.nexthops[0];IPV4_ADDR_COPY(&api_nh->gate.ipv4,&nhlfe.nexthop
);api_nh->type=NEXTHOP_TYPE_IPV4_IFINDEX;api_nh->ifindex=nhlfe.ifindex;/*MPLSlab
els*/SET_FLAG(api.message,ZAPI_MESSAGE_LABEL);api_nh->labels[0]=nhlfe.label_out;
api_nh->label_num=1;api_nh->vrf_id=VRF_DEFAULT;api.nexthop_num=1;}if(IS_DEBUG_OS
PF_SR)zlog_debug("|-%sFEC%ufor%s/%uvia%u",cmd==ZEBRA_ROUTE_ADD?"Add":"Delete",nh
lfe.label_out,inet_ntoa(nhlfe.prefv4.prefix),nhlfe.prefv4.prefixlen,nhlfe.ifinde
x);returnzclient_route_send(cmd,zclient,&api);}/*AddnewNHLFEentryforSID*/statici
nlinevoidadd_sid_nhlfe(structsr_nhlfenhlfe){if((nhlfe.label_in!=0)&&(nhlfe.label
_out!=0)){ospf_zebra_send_mpls_labels(ZEBRA_MPLS_LABELS_ADD,nhlfe);if(nhlfe.labe
l_out!=MPLS_LABEL_IMPLICIT_NULL)ospf_zebra_send_mpls_ftn(ZEBRA_ROUTE_ADD,nhlfe);
}}/*RemoveNHLFEentryforSID*/staticinlinevoiddel_sid_nhlfe(structsr_nhlfenhlfe){i
f((nhlfe.label_in!=0)&&(nhlfe.label_out!=0)){ospf_zebra_send_mpls_labels(ZEBRA_M
PLS_LABELS_DELETE,nhlfe);if(nhlfe.label_out!=MPLS_LABEL_IMPLICIT_NULL)ospf_zebra
_send_mpls_ftn(ZEBRA_ROUTE_DELETE,nhlfe);}}/*UpdateNHLFEentryforSID*/staticinlin
evoidupdate_sid_nhlfe(structsr_nhlfen1,structsr_nhlfen2){del_sid_nhlfe(n1);add_s
id_nhlfe(n2);}/**FunctionstoparseandgetExtendedLink/Prefix*TLVsandSubTLVs*//*Ext
endedLinkSubTLVsGetter*/staticstructsr_link*get_ext_link_sid(structtlv_header*tl
vh){structsr_link*srl;structext_tlv_link*link=(structext_tlv_link*)tlvh;structex
t_subtlv_adj_sid*adj_sid;structext_subtlv_lan_adj_sid*lan_sid;structext_subtlv_r
mt_itf_addr*rmt_itf;structtlv_header*sub_tlvh;uint16_tlength=0,sum=0,i=0;srl=XCA
LLOC(MTYPE_OSPF_SR_PARAMS,sizeof(structsr_link));if(srl==NULL)returnNULL;/*Initi
alizeTLVbrowsing*/length=ntohs(tlvh->length)-EXT_TLV_LINK_SIZE;sub_tlvh=(structt
lv_header*)((char*)(tlvh)+TLV_HDR_SIZE+EXT_TLV_LINK_SIZE);for(;sum<length;sub_tl
vh=TLV_HDR_NEXT(sub_tlvh)){switch(ntohs(sub_tlvh->type)){caseEXT_SUBTLV_ADJ_SID:
adj_sid=(structext_subtlv_adj_sid*)sub_tlvh;srl->type=ADJ_SID;i=CHECK_FLAG(adj_s
id->flags,EXT_SUBTLV_LINK_ADJ_SID_BFLG)?1:0;srl->flags[i]=adj_sid->flags;if(CHEC
K_FLAG(adj_sid->flags,EXT_SUBTLV_LINK_ADJ_SID_VFLG))srl->sid[i]=GET_LABEL(ntohl(
adj_sid->value));elsesrl->sid[i]=ntohl(adj_sid->value);IPV4_ADDR_COPY(&srl->nhlf
e[i].nexthop,&link->link_id);break;caseEXT_SUBTLV_LAN_ADJ_SID:lan_sid=(structext
_subtlv_lan_adj_sid*)sub_tlvh;srl->type=LAN_ADJ_SID;i=CHECK_FLAG(lan_sid->flags,
EXT_SUBTLV_LINK_ADJ_SID_BFLG)?1:0;srl->flags[i]=lan_sid->flags;if(CHECK_FLAG(lan
_sid->flags,EXT_SUBTLV_LINK_ADJ_SID_VFLG))srl->sid[i]=GET_LABEL(ntohl(lan_sid->v
alue));elsesrl->sid[i]=ntohl(lan_sid->value);IPV4_ADDR_COPY(&srl->nhlfe[i].nexth
op,&lan_sid->neighbor_id);break;caseEXT_SUBTLV_RMT_ITF_ADDR:rmt_itf=(structext_s
ubtlv_rmt_itf_addr*)sub_tlvh;IPV4_ADDR_COPY(&srl->nhlfe[0].nexthop,&rmt_itf->val
ue);IPV4_ADDR_COPY(&srl->nhlfe[1].nexthop,&rmt_itf->value);break;default:break;}
sum+=TLV_SIZE(sub_tlvh);}IPV4_ADDR_COPY(&srl->nhlfe[0].prefv4.prefix,&link->link
_data);srl->nhlfe[0].prefv4.prefixlen=IPV4_MAX_PREFIXLEN;srl->nhlfe[0].prefv4.fa
mily=AF_INET;apply_mask_ipv4(&srl->nhlfe[0].prefv4);IPV4_ADDR_COPY(&srl->nhlfe[1
].prefv4.prefix,&link->link_data);srl->nhlfe[1].prefv4.prefixlen=IPV4_MAX_PREFIX
LEN;srl->nhlfe[1].prefv4.family=AF_INET;apply_mask_ipv4(&srl->nhlfe[1].prefv4);i
f(IS_DEBUG_OSPF_SR){zlog_debug("|-FoundprimaryAdj/LanSid%ufor%s/%u",srl->sid[0],
inet_ntoa(srl->nhlfe[0].prefv4.prefix),srl->nhlfe[0].prefv4.prefixlen);zlog_debu
g("|-FoundbackupAdj/LanSid%ufor%s/%u",srl->sid[1],inet_ntoa(srl->nhlfe[1].prefv4
.prefix),srl->nhlfe[1].prefv4.prefixlen);}returnsrl;}/*ExtendedPrefixSubTLVsGett
er*/staticstructsr_prefix*get_ext_prefix_sid(structtlv_header*tlvh){structsr_pre
fix*srp;structext_tlv_prefix*pref=(structext_tlv_prefix*)tlvh;structext_subtlv_p
refix_sid*psid;structtlv_header*sub_tlvh;uint16_tlength=0,sum=0;srp=XCALLOC(MTYP
E_OSPF_SR_PARAMS,sizeof(structsr_prefix));if(srp==NULL)returnNULL;/*InitializeTL
Vbrowsing*/length=ntohs(tlvh->length)-EXT_TLV_PREFIX_SIZE;sub_tlvh=(structtlv_he
ader*)((char*)(tlvh)+TLV_HDR_SIZE+EXT_TLV_PREFIX_SIZE);for(;sum<length;sub_tlvh=
TLV_HDR_NEXT(sub_tlvh)){switch(ntohs(sub_tlvh->type)){caseEXT_SUBTLV_PREFIX_SID:
psid=(structext_subtlv_prefix_sid*)sub_tlvh;if(psid->algorithm!=SR_ALGORITHM_SPF
){zlog_err("SR(%s):UnsupportedAlgorithm",__func__);XFREE(MTYPE_OSPF_SR_PARAMS,sr
p);returnNULL;}srp->type=PREF_SID;srp->flags=psid->flags;if(CHECK_FLAG(psid->fla
gs,EXT_SUBTLV_PREFIX_SID_VFLG))srp->sid=GET_LABEL(ntohl(psid->value));elsesrp->s
id=ntohl(psid->value);IPV4_ADDR_COPY(&srp->nhlfe.prefv4.prefix,&pref->address);s
rp->nhlfe.prefv4.prefixlen=pref->pref_length;srp->nhlfe.prefv4.family=AF_INET;ap
ply_mask_ipv4(&srp->nhlfe.prefv4);break;default:break;}sum+=TLV_SIZE(sub_tlvh);}
if(IS_DEBUG_OSPF_SR)zlog_debug("|-FoundSID%uforprefix%s/%u",srp->sid,inet_ntoa(s
rp->nhlfe.prefv4.prefix),srp->nhlfe.prefv4.prefixlen);returnsrp;}/**Functionstom
anipulateSegmentRoutingLink&Prefixstructures*//*ComparetwoSegmentLink:return0ife
qual,1otherwise*/staticinlineintsr_link_cmp(structsr_link*srl1,structsr_link*srl
2){if((srl1->sid[0]==srl2->sid[0])&&(srl1->sid[1]==srl2->sid[1])&&(srl1->type==s
rl2->type)&&(srl1->flags[0]==srl2->flags[0])&&(srl1->flags[1]==srl2->flags[1]))r
eturn0;elsereturn1;}/*ComparetwoSegmentPrefix:return0ifequal,1otherwise*/statici
nlineintsr_prefix_cmp(structsr_prefix*srp1,structsr_prefix*srp2){if((srp1->sid==
srp2->sid)&&(srp1->flags==srp2->flags))return0;elsereturn1;}/*UpdateSegmentLinko
fgivenSegmentRoutingNode*/staticvoidupdate_ext_link_sid(structsr_node*srn,struct
sr_link*srl,uint8_tlsa_flags){structlistnode*node;structsr_link*lk;boolfound=fal
se;/*Sanitycheck*/if((srn==NULL)||(srl==NULL))return;if(IS_DEBUG_OSPF_SR)zlog_de
bug("|-ProcessExtendedLinkAdj/Lan-SID");/*ProcessonlyLocalAdj/Lan_AdjSIDcomingfr
omLSASELF*/if(!CHECK_FLAG(srl->flags[0],EXT_SUBTLV_LINK_ADJ_SID_LFLG)||!CHECK_FL
AG(srl->flags[1],EXT_SUBTLV_LINK_ADJ_SID_LFLG)||!CHECK_FLAG(lsa_flags,OSPF_LSA_S
ELF))return;/*SearchforexistingSegmentLink*/for(ALL_LIST_ELEMENTS_RO(srn->ext_li
nk,node,lk))if(lk->instance==srl->instance){found=true;break;}if(IS_DEBUG_OSPF_S
R)zlog_debug("|-%sSRLink8.0.0.%uforSRnode%s",found?"Update":"Add",GET_OPAQUE_ID(
srl->instance),inet_ntoa(srn->adv_router));/*ifnotfound,addnewSegmentLinkandinst
allNHLFE*/if(!found){/*CompleteSR-LinkandaddittoSR-Nodelist*/srl->srn=srn;IPV4_A
DDR_COPY(&srl->adv_router,&srn->adv_router);listnode_add(srn->ext_link,srl);/*Tr
ytosetMPLStable*/if(compute_link_nhlfe(srl)){add_sid_nhlfe(srl->nhlfe[0]);add_si
d_nhlfe(srl->nhlfe[1]);}}else{if(sr_link_cmp(lk,srl)){if(compute_link_nhlfe(srl)
){update_sid_nhlfe(lk->nhlfe[0],srl->nhlfe[0]);update_sid_nhlfe(lk->nhlfe[1],srl
->nhlfe[1]);/*ReplaceSegmentList*/listnode_delete(srn->ext_link,lk);XFREE(MTYPE_
OSPF_SR_PARAMS,lk);srl->srn=srn;IPV4_ADDR_COPY(&srl->adv_router,&srn->adv_router
);listnode_add(srn->ext_link,srl);}else{/*NewNHLFEwasnotfound.*JustfreetheSRLink
*/XFREE(MTYPE_OSPF_SR_PARAMS,srl);}}else{/**ThisisjustanLSArefresh.*Stopprocessi
ngandfreeSRLink*/XFREE(MTYPE_OSPF_SR_PARAMS,srl);}}}/*UpdateSegmentPrefixofgiven
SegmentRoutingNode*/staticvoidupdate_ext_prefix_sid(structsr_node*srn,structsr_p
refix*srp){structlistnode*node;structsr_prefix*pref;boolfound=false;/*Sanitychec
k*/if(srn==NULL||srp==NULL)return;if(IS_DEBUG_OSPF_SR)zlog_debug("|-ProcessExten
dedPrefixSID%u",srp->sid);/*ProcessonlyGlobalPrefixSID*/if(CHECK_FLAG(srp->flags
,EXT_SUBTLV_PREFIX_SID_LFLG))return;/*SearchforexistingSegmentPrefix*/for(ALL_LI
ST_ELEMENTS_RO(srn->ext_prefix,node,pref))if(pref->instance==srp->instance){foun
d=true;break;}if(IS_DEBUG_OSPF_SR)zlog_debug("|-%sSRLSAID7.0.0.%uforSRnode%s",fo
und?"Update":"Add",GET_OPAQUE_ID(srp->instance),inet_ntoa(srn->adv_router));/*if
notfound,addnewSegmentPrefixandinstallNHLFE*/if(!found){/*CompleteSR-Prefixandad
dittoSR-Nodelist*/srp->srn=srn;IPV4_ADDR_COPY(&srp->adv_router,&srn->adv_router)
;listnode_add(srn->ext_prefix,srp);/*TrytosetMPLStable*/if(compute_prefix_nhlfe(
srp)==1)add_sid_nhlfe(srp->nhlfe);}else{if(sr_prefix_cmp(pref,srp)){if(compute_p
refix_nhlfe(srp)==1){update_sid_nhlfe(pref->nhlfe,srp->nhlfe);/*ReplaceSegmentPr
efix*/listnode_delete(srn->ext_prefix,pref);XFREE(MTYPE_OSPF_SR_PARAMS,pref);srp
->srn=srn;IPV4_ADDR_COPY(&srp->adv_router,&srn->adv_router);listnode_add(srn->ex
t_prefix,srp);}else{/*NewNHLFEwasnotfound.*JustfreetheSRPrefix*/XFREE(MTYPE_OSPF
_SR_PARAMS,srp);}}else{/*ThisisjustanLSArefresh.*StopprocessingandfreeSRPrefix*/
XFREE(MTYPE_OSPF_SR_PARAMS,srp);}}}/**WhenchangetheFRRSelfSRGB,updatetheNHLFEInp
utLabel*forallExtendedPrefixwithSIDindexthroughhash_iterate()*/staticvoidupdate_
in_nhlfe(structhash_backet*backet,void*args){structlistnode*node;structsr_node*s
rn=(structsr_node*)backet->data;structsr_prefix*srp;structsr_nhlfenew;/*ProcessE
veryExtendedPrefixforthisSR-Node*/for(ALL_LIST_ELEMENTS_RO(srn->ext_prefix,node,
srp)){/*ProcessSelfSRNonlyifNO-PHPisrequested*/if((srn==OspfSR.self)&&!CHECK_FLA
G(srp->flags,EXT_SUBTLV_PREFIX_SID_NPFLG))continue;/*ProcessonlySIDIndex*/if(CHE
CK_FLAG(srp->flags,EXT_SUBTLV_PREFIX_SID_VFLG))continue;/*OK.ComputenewNHLFE*/me
mcpy(&new,&srp->nhlfe,sizeof(structsr_nhlfe));new.label_in=index2label(srp->sid,
OspfSR.srgb);/*UpdateMPLSLFIB*/update_sid_nhlfe(srp->nhlfe,new);/*FinallyupdateI
nputLabel*/srp->nhlfe.label_in=new.label_in;}}/**WhenSRGBhaschanged,updateNHLFEO
utputLabelforallExtendedPrefix*withSIDindexwhichusethegivenSR-Nodeasnexthopthoug
hhash_iterate()*/staticvoidupdate_out_nhlfe(structhash_backet*backet,void*args){
structlistnode*node;structsr_node*srn=(structsr_node*)backet->data;structsr_node
*srnext=(structsr_node*)args;structsr_prefix*srp;structsr_nhlfenew;for(ALL_LIST_
ELEMENTS_RO(srn->ext_prefix,node,srp)){/*ProcessonlySIDIndexfornexthopwithoutPHP
*/if((srp->nexthop==NULL)&&(!CHECK_FLAG(srp->flags,EXT_SUBTLV_PREFIX_SID_NPFLG))
)continue;memcpy(&new,&srp->nhlfe,sizeof(structsr_nhlfe));new.label_out=index2la
bel(srp->sid,srnext->srgb);update_sid_nhlfe(srp->nhlfe,new);srp->nhlfe.label_out
=new.label_out;}}/**FollowingfunctionsarecallwhennewSegmentRoutingLSAarereceived
*-RouterInformation:ospf_sr_ri_lsa_update()&ospf_sr_ri_lsa_delete()*-ExtendedLin
k:ospf_sr_ext_link_update()&ospf_sr_ext_link_delete()*-ExtendedPrefix:ospf_ext_p
refix_update()&ospf_sr_ext_prefix_delete()*//*UpdateSegmentRoutingfromRouterInfo
rmationLSA*/voidospf_sr_ri_lsa_update(structospf_lsa*lsa){structsr_node*srn;stru
cttlv_header*tlvh;structlsa_header*lsah=(structlsa_header*)lsa->data;structri_sr
_tlv_sid_label_range*ri_srgb;structri_sr_tlv_sr_algorithm*algo;structsr_srgbsrgb
;uint16_tlength=0,sum=0;if(IS_DEBUG_OSPF_SR)zlog_debug("SR(%s):ProcessRouter""In
formationLSA4.0.0.%ufrom%s",__func__,GET_OPAQUE_ID(ntohl(lsah->id.s_addr)),inet_
ntoa(lsah->adv_router));/*Sanitycheck*/if(IS_LSA_SELF(lsa))return;if(OspfSR.neig
hbors==NULL){zlog_err("SR(%s):Abort!novalidSRDataBase",__func__);return;}/*GetSR
NodeinhashtablefromRouterID*/srn=hash_get(OspfSR.neighbors,(void*)&(lsah->adv_ro
uter),(void*)sr_node_new);/*Sanitycheck*/if(srn==NULL){zlog_err("SR(%s):Abort!ca
n'tcreateSRnodeinhashtable",__func__);return;}if((srn->instance!=0)&&(srn->insta
nce!=ntohl(lsah->id.s_addr))){zlog_err("SR(%s):Abort!Wrong""LSAID4.0.0.%uforSRno
de%s/%u",__func__,GET_OPAQUE_ID(ntohl(lsah->id.s_addr)),inet_ntoa(lsah->adv_rout
er),srn->instance);return;}/*CollectRouterInformationSubTLVs*//*InitializeTLVbro
wsing*/length=ntohs(lsah->length)-OSPF_LSA_HEADER_SIZE;srgb.range_size=0;srgb.lo
wer_bound=0;for(tlvh=TLV_HDR_TOP(lsah);(sum<length)&&(tlvh!=NULL);tlvh=TLV_HDR_N
EXT(tlvh)){switch(ntohs(tlvh->type)){caseRI_SR_TLV_SR_ALGORITHM:algo=(structri_s
r_tlv_sr_algorithm*)tlvh;inti;for(i=0;i<ntohs(algo->header.length);i++)srn->algo
[i]=algo->value[0];for(;i<ALGORITHM_COUNT;i++)srn->algo[i]=SR_ALGORITHM_UNSET;su
m+=TLV_SIZE(tlvh);break;caseRI_SR_TLV_SID_LABEL_RANGE:ri_srgb=(structri_sr_tlv_s
id_label_range*)tlvh;srgb.range_size=GET_RANGE_SIZE(ntohl(ri_srgb->size));srgb.l
ower_bound=GET_LABEL(ntohl(ri_srgb->lower.value));sum+=TLV_SIZE(tlvh);break;case
RI_SR_TLV_NODE_MSD:srn->msd=((structri_sr_tlv_node_msd*)(tlvh))->value;sum+=TLV_
SIZE(tlvh);break;default:sum+=TLV_SIZE(tlvh);break;}}/*Checkthatwecollectmandato
ryparameters*/if(srn->algo[0]==SR_ALGORITHM_UNSET||srgb.range_size==0||srgb.lowe
r_bound==0){zlog_warn("SR(%s):Missingmandatoryparameters.Abort!",__func__);hash_
release(OspfSR.neighbors,&(srn->adv_router));XFREE(MTYPE_OSPF_SR_PARAMS,srn);ret
urn;}/*CheckifitisanewSRNodeornot*/if(srn->instance==0){/*updateLSAID*/srn->inst
ance=ntohl(lsah->id.s_addr);/*CopySRGB*/srn->srgb.range_size=srgb.range_size;srn
->srgb.lower_bound=srgb.lower_bound;}/*CheckifSRGBhaschanged*/if((srn->srgb.rang
e_size!=srgb.range_size)||(srn->srgb.lower_bound!=srgb.lower_bound)){srn->srgb.r
ange_size=srgb.range_size;srn->srgb.lower_bound=srgb.lower_bound;/*UpdateNHLFEif
itisaneighborSRnode*/if(srn->neighbor==OspfSR.self)hash_iterate(OspfSR.neighbors
,(void(*)(structhash_backet*,void*))update_out_nhlfe,(void*)srn);}}/**DeleteSRNo
deentryinhashtableinformationcorrespondingtoanexpired*RouterInformationLSA*/void
ospf_sr_ri_lsa_delete(structospf_lsa*lsa){structsr_node*srn;structlsa_header*lsa
h=(structlsa_header*)lsa->data;if(IS_DEBUG_OSPF_SR)zlog_debug("SR(%s):RemoveSRno
de%sfromlsa_id4.0.0.%u",__func__,inet_ntoa(lsah->adv_router),GET_OPAQUE_ID(ntohl
(lsah->id.s_addr)));/*Sanitycheck*/if(OspfSR.neighbors==NULL){zlog_err("SR(%s):A
bort!novalidSRDataBase",__func__);return;}/*ReleaseRouterIDentryinSRDBhashtable*
/srn=hash_release(OspfSR.neighbors,&(lsah->adv_router));/*Sanitycheck*/if(srn==N
ULL){zlog_err("SR(%s):Abort!noentryinSRDBforSRNode%s",__func__,inet_ntoa(lsah->a
dv_router));return;}if((srn->instance!=0)&&(srn->instance!=ntohl(lsah->id.s_addr
))){zlog_err("SR(%s):Abort!WrongLSAID4.0.0.%uforSRnode%s",__func__,GET_OPAQUE_ID
(ntohl(lsah->id.s_addr)),inet_ntoa(lsah->adv_router));return;}/*RemoveSRnode*/sr
_node_del(srn);}/*UpdateSegmentRoutingfromExtendedLinkLSA*/voidospf_sr_ext_link_
lsa_update(structospf_lsa*lsa){structsr_node*srn;structtlv_header*tlvh;structlsa
_header*lsah=(structlsa_header*)lsa->data;structsr_link*srl;uint16_tlength,sum;i
f(IS_DEBUG_OSPF_SR)zlog_debug("SR(%s):ProcessExtendedLinkLSA8.0.0.%ufrom%s",__fu
nc__,GET_OPAQUE_ID(ntohl(lsah->id.s_addr)),inet_ntoa(lsah->adv_router));/*Sanity
check*/if(OspfSR.neighbors==NULL){zlog_err("SR(%s):Abort!novalidSRDataBase",__fu
nc__);return;}/*GetSRNodeinhashtablefromRouterID*/srn=(structsr_node*)hash_get(O
spfSR.neighbors,(void*)&(lsah->adv_router),(void*)sr_node_new);/*Sanitycheck*/if
(srn==NULL){zlog_err("SR(%s):Abort!can'tcreateSRnodeinhashtable",__func__);retur
n;}/*InitializeTLVbrowsing*/length=ntohs(lsah->length)-OSPF_LSA_HEADER_SIZE;sum=
0;for(tlvh=TLV_HDR_TOP(lsah);(sum<length)&&(tlvh!=NULL);tlvh=TLV_HDR_NEXT(tlvh))
{if(ntohs(tlvh->type)==EXT_TLV_LINK){/*GotExtendedLinkinformation*/srl=get_ext_l
ink_sid(tlvh);/*UpdateSIDifnotnull*/if(srl!=NULL){srl->instance=ntohl(lsah->id.s
_addr);update_ext_link_sid(srn,srl,lsa->flags);}}sum+=TLV_SIZE(tlvh);}}/*DeleteS
egmentRoutingfromExtendedLinkLSA*/voidospf_sr_ext_link_lsa_delete(structospf_lsa
*lsa){structlistnode*node;structsr_link*srl;structsr_node*srn;structlsa_header*l
sah=(structlsa_header*)lsa->data;uint32_tinstance=ntohl(lsah->id.s_addr);if(IS_D
EBUG_OSPF_SR)zlog_debug("SR(%s):RemoveExtendedLinkLSA8.0.0.%ufrom%s",__func__,GE
T_OPAQUE_ID(ntohl(lsah->id.s_addr)),inet_ntoa(lsah->adv_router));/*Sanitycheck*/
if(OspfSR.neighbors==NULL){zlog_err("SR(%s):Abort!novalidSRDataBase",__func__);r
eturn;}/*SearchSRNodeinhashtablefromRouterID*/srn=(structsr_node*)hash_lookup(Os
pfSR.neighbors,(void*)&(lsah->adv_router));/**SR-NodemaybeNULLifithasbeenremovep
reviouslywhen*processingRouterInformationLSAdeletion*/if(srn==NULL){zlog_warn("S
R(%s):Stop!noentryinSRDBforSRNode%s",__func__,inet_ntoa(lsah->adv_router));retur
n;}/*SearchforcorrespondingSegmentLink*/for(ALL_LIST_ELEMENTS_RO(srn->ext_link,n
ode,srl))if(srl->instance==instance)break;/*RemoveSegmentLinkiffound*/if((srl!=N
ULL)&&(srl->instance==instance)){del_sid_nhlfe(srl->nhlfe[0]);del_sid_nhlfe(srl-
>nhlfe[1]);listnode_delete(srn->ext_link,srl);XFREE(MTYPE_OSPF_SR_PARAMS,srl);}e
lse{zlog_warn("SR(%s):Didn'tfoundcorrespondingSRLink8.0.0.%u""forSRNode%s",__fun
c__,GET_OPAQUE_ID(ntohl(lsah->id.s_addr)),inet_ntoa(lsah->adv_router));}}/*Updat
eSegmentRoutingfromExtendedPrefixLSA*/voidospf_sr_ext_prefix_lsa_update(structos
pf_lsa*lsa){structsr_node*srn;structtlv_header*tlvh;structlsa_header*lsah=(struc
tlsa_header*)lsa->data;structsr_prefix*srp;uint16_tlength,sum;if(IS_DEBUG_OSPF_S
R)zlog_debug("SR(%s):ProcessExtendedPrefixLSA""7.0.0.%ufrom%s",__func__,GET_OPAQ
UE_ID(ntohl(lsah->id.s_addr)),inet_ntoa(lsah->adv_router));/*Sanitycheck*/if(Osp
fSR.neighbors==NULL){zlog_err("SR(%s):Abort!novalidSRDataBase",__func__);return;
}/*GetSRNodeinhashtablefromRouterID*/srn=(structsr_node*)hash_get(OspfSR.neighbo
rs,(void*)&(lsah->adv_router),(void*)sr_node_new);/*Sanitycheck*/if(srn==NULL){z
log_err("SR(%s):Abort!can'tcreateSRnodeinhashtable",__func__);return;}/*Initiali
zeTLVbrowsing*/length=ntohs(lsah->length)-OSPF_LSA_HEADER_SIZE;sum=0;for(tlvh=TL
V_HDR_TOP(lsah);sum<length;tlvh=TLV_HDR_NEXT(tlvh)){if(ntohs(tlvh->type)==EXT_TL
V_LINK){/*GotExtendedLinkinformation*/srp=get_ext_prefix_sid(tlvh);/*UpdateSIDif
notnull*/if(srp!=NULL){srp->instance=ntohl(lsah->id.s_addr);update_ext_prefix_si
d(srn,srp);}}sum+=TLV_SIZE(tlvh);}}/*DeleteSegmentRoutingfromExtendedPrefixLSA*/
voidospf_sr_ext_prefix_lsa_delete(structospf_lsa*lsa){structlistnode*node;struct
sr_prefix*srp;structsr_node*srn;structlsa_header*lsah=(structlsa_header*)lsa->da
ta;uint32_tinstance=ntohl(lsah->id.s_addr);if(IS_DEBUG_OSPF_SR)zlog_debug("SR(%s
):RemoveExtendedPrefixLSA7.0.0.%ufrom%s",__func__,GET_OPAQUE_ID(ntohl(lsah->id.s
_addr)),inet_ntoa(lsah->adv_router));/*Sanitycheck*/if(OspfSR.neighbors==NULL){z
log_err("SR(%s):Abort!novalidSRDataBase",__func__);return;}/*SearchSRNodeinhasht
ablefromRouterID*/srn=(structsr_node*)hash_lookup(OspfSR.neighbors,(void*)&(lsah
->adv_router));/**SR-NodemaybeNULLifithasbeenremovepreviouslywhen*processingRout
erInformationLSAdeletion*/if(srn==NULL){zlog_warn("SR(%s):Stop!noentryinSRDBforS
RNode%s",__func__,inet_ntoa(lsah->adv_router));return;}/*SearchforcorrespondingS
egmentLink*/for(ALL_LIST_ELEMENTS_RO(srn->ext_prefix,node,srp))if(srp->instance=
=instance)break;/*RemoveSegmentLinkiffound*/if((srp!=NULL)&&(srp->instance==inst
ance)){del_sid_nhlfe(srp->nhlfe);listnode_delete(srn->ext_link,srp);XFREE(MTYPE_
OSPF_SR_PARAMS,srp);}else{zlog_warn("SR(%s):Didn'tfoundcorrespondingSRPrefix""7.
0.0.%uforSRNode%s",__func__,GET_OPAQUE_ID(ntohl(lsah->id.s_addr)),inet_ntoa(lsah
->adv_router));}}/*GetLabelforExtendedLinkSID*//*TODO:TobereplacebyZebraLabelMan
ager*/uint32_tget_ext_link_label_value(void){staticuint32_tlabel=ADJ_SID_MIN-1;i
f(label<ADJ_SID_MAX)label+=1;returnlabel;}/**UpdatePrefixSID.Callbyospf_ext_pref
_ism_changeto*completeinitialCLIcommandatstartutp.**@paramifp-Loopbackinterface*
@parampref-Prefixaddressofthisinterface**@return-void*/voidospf_sr_update_prefix
(structinterface*ifp,structprefix*p){structlistnode*node;structsr_prefix*srp;/*S
anityCheck*/if((ifp==NULL)||(p==NULL))return;/**SearchifthereisaSegmentPrefixtha
tcorrespondtothis*interfaceorprefix,andupdateitiffound*/for(ALL_LIST_ELEMENTS_RO
(OspfSR.self->ext_prefix,node,srp)){if((srp->nhlfe.ifindex==ifp->ifindex)||((IPV
4_ADDR_SAME(&srp->nhlfe.prefv4.prefix,&p->u.prefix4))&&(srp->nhlfe.prefv4.prefix
len==p->prefixlen))){/*UpdateInterface&Prefixinfo*/srp->nhlfe.ifindex=ifp->ifind
ex;IPV4_ADDR_COPY(&srp->nhlfe.prefv4.prefix,&p->u.prefix4);srp->nhlfe.prefv4.pre
fixlen=p->prefixlen;srp->nhlfe.prefv4.family=p->family;IPV4_ADDR_COPY(&srp->nhlf
e.nexthop,&p->u.prefix4);/*OK.Let'sScheduleExtendedPrefixLSA*/srp->instance=ospf
_ext_schedule_prefix_index(ifp,srp->sid,&srp->nhlfe.prefv4,srp->flags);/*Install
NHLFEifNO-PHPisrequested*/if(CHECK_FLAG(srp->flags,EXT_SUBTLV_PREFIX_SID_NPFLG))
{srp->nhlfe.label_in=index2label(srp->sid,OspfSR.self->srgb);srp->nhlfe.label_ou
t=MPLS_LABEL_IMPLICIT_NULL;add_sid_nhlfe(srp->nhlfe);}}}}/**Followingfunctionsar
eusedtoupdateMPLSLFIBafteraSPFrun*/staticvoidospf_sr_nhlfe_update(structhash_bac
ket*backet,void*args){structsr_node*srn=(structsr_node*)backet->data;structlistn
ode*node;structsr_prefix*srp;structsr_nhlfeold;intrc;/*SanityCheck*/if(srn==NULL
)return;if(IS_DEBUG_OSPF_SR)zlog_debug("|-UpdatePrefixforSRNode%s",inet_ntoa(srn
->adv_router));/*SkipSelfSRNode*/if(srn==OspfSR.self)return;/*UpdateExtendedPref
ix*/for(ALL_LIST_ELEMENTS_RO(srn->ext_prefix,node,srp)){/*BackupcurrentNHLFE*/me
mcpy(&old,&srp->nhlfe,sizeof(structsr_nhlfe));/*ComputethenewNHLFE*/rc=compute_p
refix_nhlfe(srp);/*Checkcomputationresult*/switch(rc){/*nexthopisnotknow,removeo
ldNHLFEtoavoidloop*/case-1:del_sid_nhlfe(srp->nhlfe);break;/*nexthophasnotchange
d,skipit*/case0:break;/*thereisanewnexthop,updateNHLFE*/case1:update_sid_nhlfe(o
ld,srp->nhlfe);break;default:break;}}}staticintospf_sr_update_schedule(structthr
ead*t){structospf*ospf;structtimevalstart_time,stop_time;ospf=THREAD_ARG(t);ospf
->t_sr_update=NULL;if(!OspfSR.update)return0;monotime(&start_time);if(IS_DEBUG_O
SPF_SR)zlog_debug("SR(%s):StartSPFupdate",__func__);hash_iterate(OspfSR.neighbor
s,(void(*)(structhash_backet*,void*))ospf_sr_nhlfe_update,NULL);monotime(&stop_t
ime);if(IS_DEBUG_OSPF_SR)zlog_debug("SR(%s):SPFProcessingTime(usecs):%lld\n",__f
unc__,(stop_time.tv_sec-start_time.tv_sec)*1000000LL+(stop_time.tv_usec-start_ti
me.tv_usec));OspfSR.update=false;return1;}#defineOSPF_SR_UPDATE_INTERVAL1voidosp
f_sr_update_timer_add(structospf*ospf){if(ospf==NULL)return;/*Checkifanupdateisn
otalredayengage*/if(OspfSR.update)return;OspfSR.update=true;thread_add_timer(mas
ter,ospf_sr_update_schedule,ospf,OSPF_SR_UPDATE_INTERVAL,&ospf->t_sr_update);}/*
*--------------------------------------*Followingsarevtycommandfunctions.*------
--------------------------------*//**SegmentRoutingRouterconfiguration**Mustbece
ntralizeasitconcernsbothExtendedLink/PrefixLSA*andRouterInformationLSA.Choosetoc
allitfromExtendedPrefix*write_config()callback.**@paramvtyVTYoutput**@returnnone
*/voidospf_sr_config_write_router(structvty*vty){structlistnode*node;structsr_pr
efix*srp;if(OspfSR.enabled){vty_out(vty,"segment-routingon\n");if((OspfSR.srgb.l
ower_bound!=MPLS_DEFAULT_MIN_SRGB_LABEL)||(OspfSR.srgb.range_size!=MPLS_DEFAULT_
MAX_SRGB_SIZE)){vty_out(vty,"segment-routingglobal-block%u%u\n",OspfSR.srgb.lowe
r_bound,OspfSR.srgb.lower_bound+OspfSR.srgb.range_size-1);}if(OspfSR.msd!=0)vty_
out(vty,"segment-routingnode-msd%u\n",OspfSR.msd);if(OspfSR.self!=NULL){for(ALL_
LIST_ELEMENTS_RO(OspfSR.self->ext_prefix,node,srp)){vty_out(vty,"segment-routing
prefix%s/%u""index%u%s\n",inet_ntoa(srp->nhlfe.prefv4.prefix),srp->nhlfe.prefv4.
prefixlen,srp->sid,CHECK_FLAG(srp->flags,EXT_SUBTLV_PREFIX_SID_NPFLG)?"no-php-fl
ag":"");}}}}DEFUN(ospf_sr_enable,ospf_sr_enable_cmd,"segment-routingon",SR_STR"E
nableSegmentRouting\n"){VTY_DECLVAR_INSTANCE_CONTEXT(ospf,ospf);if(OspfSR.enable
d)returnCMD_SUCCESS;if(ospf->vrf_id!=VRF_DEFAULT){vty_out(vty,"SegmentRoutingiso
nlysupportedindefault""VRF\n");returnCMD_WARNING_CONFIG_FAILED;}if(IS_DEBUG_OSPF
_EVENT)zlog_debug("SR:SegmentRouting:OFF->ON");/*StartSegmentRouting*/OspfSR.ena
bled=true;if(!ospf_sr_start(ospf)){zlog_warn("SR:UnabletostartSegmentRouting.Abo
rt!");returnCMD_WARNING;}/*SetRouterInformationSRparameters*/if(IS_DEBUG_OSPF_EV
ENT)zlog_debug("SR:ActivateSRforRouterInformationLSA");ospf_router_info_update_s
r(true,OspfSR.srgb,OspfSR.msd);/*UpdateExtLSA*/if(IS_DEBUG_OSPF_EVENT)zlog_debug
("SR:ActivateSRforExtendedLink/PrefixLSA");ospf_ext_update_sr(true);returnCMD_SU
CCESS;}DEFUN(no_ospf_sr_enable,no_ospf_sr_enable_cmd,"nosegment-routing[on]",NO_
STRSR_STR"DisableSegmentRouting\n"){if(!OspfSR.enabled)returnCMD_SUCCESS;if(IS_D
EBUG_OSPF_EVENT)zlog_debug("SR:SegmentRouting:ON->OFF");/*StartbyDisablingExtend
edLink&PrefixLSA*/ospf_ext_update_sr(false);/*then,disableRouterInformationSRpar
ameters*/ospf_router_info_update_sr(false,OspfSR.srgb,OspfSR.msd);/*Finally,stop
SegmentRouting*/ospf_sr_stop();OspfSR.enabled=false;returnCMD_SUCCESS;}staticint
ospf_sr_enabled(structvty*vty){if(OspfSR.enabled)return1;if(vty)vty_out(vty,"%%O
SPFSRisnotturnedon\n");return0;}DEFUN(sr_sid_label_range,sr_sid_label_range_cmd,
"segment-routingglobal-block(0-1048575)(0-1048575)",SR_STR"SegmentRoutingGlobalB
locklabelrange\n""Lower-boundrangeindecimal(0-1048575)\n""Upper-boundrangeindeci
mal(0-1048575)\n"){uint32_tupper;uint32_tlower;uint32_tsize;intidx_low=2;intidx_
up=3;if(!ospf_sr_enabled(vty))returnCMD_WARNING_CONFIG_FAILED;/*Getlowerandupper
bound*/lower=strtoul(argv[idx_low]->arg,NULL,10);upper=strtoul(argv[idx_up]->arg
,NULL,10);size=upper-lower+1;if(size>MPLS_DEFAULT_MAX_SRGB_SIZE||size<=0){vty_ou
t(vty,"Rangesizecannotbelessthan0ormorethan%u\n",MPLS_DEFAULT_MAX_SRGB_SIZE);ret
urnCMD_WARNING_CONFIG_FAILED;}if(upper>MPLS_DEFAULT_MAX_SRGB_LABEL){vty_out(vty,
"Upper-boundcannotexceed%u\n",MPLS_DEFAULT_MAX_SRGB_LABEL);returnCMD_WARNING_CON
FIG_FAILED;}if(upper<MPLS_DEFAULT_MIN_SRGB_LABEL){vty_out(vty,"Upper-boundcannot
belowerthan%u\n",MPLS_DEFAULT_MIN_SRGB_LABEL);returnCMD_WARNING_CONFIG_FAILED;}/
*Checkifvalueshavechanged*/if((OspfSR.srgb.range_size==size)&&(OspfSR.srgb.lower
_bound==lower))returnCMD_SUCCESS;/*SetSID/LabelrangeSRGB*/OspfSR.srgb.range_size
=size;OspfSR.srgb.lower_bound=lower;if(OspfSR.self!=NULL){OspfSR.self->srgb.rang
e_size=size;OspfSR.self->srgb.lower_bound=lower;}/*SetRouterInformationSRparamet
ers*/ospf_router_info_update_sr(true,OspfSR.srgb,OspfSR.msd);/*UpdateNHLFEentrie
s*/hash_iterate(OspfSR.neighbors,(void(*)(structhash_backet*,void*))update_in_nh
lfe,NULL);returnCMD_SUCCESS;}DEFUN(no_sr_sid_label_range,no_sr_sid_label_range_c
md,"nosegment-routingglobal-block[(0-1048575)(0-1048575)]",NO_STRSR_STR"SegmentR
outingGlobalBlocklabelrange\n""Lower-boundrangeindecimal(0-1048575)\n""Upper-bou
ndrangeindecimal(0-1048575)\n"){if(!ospf_sr_enabled(vty))returnCMD_WARNING_CONFI
G_FAILED;/*ReverttodefaultSRGBvalue*/OspfSR.srgb.range_size=MPLS_DEFAULT_MIN_SRG
B_SIZE;OspfSR.srgb.lower_bound=MPLS_DEFAULT_MIN_SRGB_LABEL;if(OspfSR.self!=NULL)
{OspfSR.self->srgb.range_size=OspfSR.srgb.range_size;OspfSR.self->srgb.lower_bou
nd=OspfSR.srgb.lower_bound;}/*SetRouterInformationSRparameters*/ospf_router_info
_update_sr(true,OspfSR.srgb,OspfSR.msd);/*UpdateNHLFEentries*/hash_iterate(OspfS
R.neighbors,(void(*)(structhash_backet*,void*))update_in_nhlfe,NULL);returnCMD_S
UCCESS;}DEFUN(sr_node_msd,sr_node_msd_cmd,"segment-routingnode-msd(1-16)",SR_STR
"MaximumStackDepthforthisrouter\n""Maximumnumberoflabelthatcouldbestack(1-16)\n"
){uint32_tmsd;intidx=1;if(!ospf_sr_enabled(vty))returnCMD_WARNING_CONFIG_FAILED;
/*GetMSD*/argv_find(argv,argc,"(1-16)",&idx);msd=strtoul(argv[idx]->arg,NULL,10)
;if(msd<1||msd>MPLS_MAX_LABELS){vty_out(vty,"MSDmustbecomprisebetween1and%u\n",M
PLS_MAX_LABELS);returnCMD_WARNING_CONFIG_FAILED;}/*Checkifvaluehaschanged*/if(Os
pfSR.msd==msd)returnCMD_SUCCESS;/*SetthisrouterMSD*/OspfSR.msd=msd;if(OspfSR.sel
f!=NULL)OspfSR.self->msd=msd;/*SetRouterInformationSRparameters*/ospf_router_inf
o_update_sr(true,OspfSR.srgb,OspfSR.msd);returnCMD_SUCCESS;}DEFUN(no_sr_node_msd
,no_sr_node_msd_cmd,"nosegment-routingnode-msd[(1-16)]",NO_STRSR_STR"MaximumStac
kDepthforthisrouter\n""Maximumnumberoflabelthatcouldbestack(1-16)\n"){if(!ospf_s
r_enabled(vty))returnCMD_WARNING_CONFIG_FAILED;/*unsetthisrouterMSD*/OspfSR.msd=
0;if(OspfSR.self!=NULL)OspfSR.self->msd=0;/*SetRouterInformationSRparameters*/os
pf_router_info_update_sr(true,OspfSR.srgb,0);returnCMD_SUCCESS;}DEFUN(sr_prefix_
sid,sr_prefix_sid_cmd,"segment-routingprefixA.B.C.D/Mindex(0-65535)[no-php-flag]
",SR_STR"PrefixSID\n""IPv4PrefixasA.B.C.D/M\n""SIDindexforthisprefixindecimal(0-
65535)\n""IndexvalueinsideSRGB(lower_bound<index<upper_bound)\n""Don'trequestPen
ultimateHopPopping(PHP)\n"){intidx=0;structprefixp;uint32_tindex;structlistnode*
node;structsr_prefix*srp,*new;structinterface*ifp;if(!ospf_sr_enabled(vty))retur
nCMD_WARNING_CONFIG_FAILED;/*Getnetworkprefix*/argv_find(argv,argc,"A.B.C.D/M",&
idx);if(!str2prefix(argv[idx]->arg,&p)){vty_out(vty,"Invalidprefixformat%s\n",ar
gv[idx]->arg);returnCMD_WARNING_CONFIG_FAILED;}/*Get&verifyindexvalue*/argv_find
(argv,argc,"(0-65535)",&idx);index=strtoul(argv[idx]->arg,NULL,10);if(index>Ospf
SR.srgb.range_size-1){vty_out(vty,"Index%umustbelowerthanrangesize%u\n",index,Os
pfSR.srgb.range_size);returnCMD_WARNING_CONFIG_FAILED;}/*checkthattheindexisnota
lreadyused*/for(ALL_LIST_ELEMENTS_RO(OspfSR.self->ext_prefix,node,srp)){if(srp->
sid==index){vty_out(vty,"Index%uisalreadyused\n",index);returnCMD_WARNING_CONFIG
_FAILED;}}/*CreatenewExtendedPrefixtoSRDBifnotfound*/new=XCALLOC(MTYPE_OSPF_SR_P
ARAMS,sizeof(structsr_prefix));IPV4_ADDR_COPY(&new->nhlfe.prefv4.prefix,&p.u.pre
fix4);IPV4_ADDR_COPY(&new->nhlfe.nexthop,&p.u.prefix4);new->nhlfe.prefv4.prefixl
en=p.prefixlen;new->nhlfe.prefv4.family=p.family;new->sid=index;/*SetNOPHPflagif
presentandcomputeNHLFE*/if(argv_find(argv,argc,"no-php-flag",&idx)){SET_FLAG(new
->flags,EXT_SUBTLV_PREFIX_SID_NPFLG);new->nhlfe.label_in=index2label(new->sid,Os
pfSR.self->srgb);new->nhlfe.label_out=MPLS_LABEL_IMPLICIT_NULL;}if(IS_DEBUG_OSPF
_SR)zlog_debug("SR(%s):Addnewindex%utoPrefix%s/%u",__func__,index,inet_ntoa(new-
>nhlfe.prefv4.prefix),new->nhlfe.prefv4.prefixlen);/*GetInterfaceandcheckifitisa
Loopback*/ifp=if_lookup_prefix(&p,VRF_DEFAULT);if(ifp==NULL){/**Interfacecouldbe
notyetavailablei.e.whenthis*commandisintheconfigurationfile,OSPFisnotyet*ready.I
nthiscase,storetheprefixSIDforlatter*updateofthisExtendedPrefix*/listnode_add(Os
pfSR.self->ext_prefix,new);zlog_warn("Interfaceforprefix%s/%unotfound.DeferredLS
A""flooding",inet_ntoa(p.u.prefix4),p.prefixlen);returnCMD_SUCCESS;}if(!if_is_lo
opback(ifp)){vty_out(vty,"interface%sisnotaLoopback\n",ifp->name);XFREE(MTYPE_OS
PF_SR_PARAMS,new);returnCMD_WARNING_CONFIG_FAILED;}new->nhlfe.ifindex=ifp->ifind
ex;/*Searchifthisprefixalreadyexist*/for(ALL_LIST_ELEMENTS_RO(OspfSR.self->ext_p
refix,node,srp)){if((IPV4_ADDR_SAME(&srp->nhlfe.prefv4.prefix,&p.u.prefix4)&&srp
->nhlfe.prefv4.prefixlen==p.prefixlen))break;elsesrp=NULL;}/*UpdateorAddthisnewS
RPrefix*/if(srp){update_sid_nhlfe(srp->nhlfe,new->nhlfe);listnode_delete(OspfSR.
self->ext_prefix,srp);listnode_add(OspfSR.self->ext_prefix,new);}else{listnode_a
dd(OspfSR.self->ext_prefix,new);add_sid_nhlfe(new->nhlfe);}/*Finally,updateExten
dedPrefixLSA*/new->instance=ospf_ext_schedule_prefix_index(ifp,new->sid,&new->nh
lfe.prefv4,new->flags);if(new->instance==0){vty_out(vty,"Unabletosetindex%uforpr
efix%s/%u\n",index,inet_ntoa(p.u.prefix4),p.prefixlen);returnCMD_WARNING;}return
CMD_SUCCESS;}DEFUN(no_sr_prefix_sid,no_sr_prefix_sid_cmd,"nosegment-routingprefi
xA.B.C.D/M[index(0-65535)no-php-flag]",NO_STRSR_STR"PrefixSID\n""IPv4PrefixasA.B
.C.D/M\n""SIDindexforthisprefixindecimal(0-65535)\n""IndexvalueinsideSRGB(lower_
bound<index<upper_bound)\n""Don'trequestPenultimateHopPopping(PHP)\n"){intidx=0;
structprefixp;structlistnode*node;structsr_prefix*srp;structinterface*ifp;boolfo
und=false;intrc;/*Getnetworkprefix*/argv_find(argv,argc,"A.B.C.D/M",&idx);rc=str
2prefix(argv[idx]->arg,&p);if(!rc){vty_out(vty,"Invalidprefixformat%s\n",argv[id
x]->arg);returnCMD_WARNING_CONFIG_FAILED;}/*checkthattheprefixisalreadyset*/for(
ALL_LIST_ELEMENTS_RO(OspfSR.self->ext_prefix,node,srp))if(IPV4_ADDR_SAME(&srp->n
hlfe.prefv4.prefix,&p.u.prefix4)&&(srp->nhlfe.prefv4.prefixlen==p.prefixlen)){fo
und=true;break;}if(!found){vty_out(vty,"Prefix%sisnotfound.Abort!\n",argv[idx]->
arg);returnCMD_WARNING_CONFIG_FAILED;}/*GetInterface*/ifp=if_lookup_by_index(srp
->nhlfe.ifindex,VRF_DEFAULT);if(ifp==NULL){vty_out(vty,"interfaceforprefix%snotf
ound.\n",argv[idx]->arg);returnCMD_WARNING_CONFIG_FAILED;}/*UpdateExtendedPrefix
LSA*/if(!ospf_ext_schedule_prefix_index(ifp,0,NULL,0)){vty_out(vty,"Nocorrespond
ingloopbackinterface.Abort!\n");returnCMD_WARNING;}if(IS_DEBUG_OSPF_SR)zlog_debu
g("SR(%s):RemovePrefix%s/%uwithindex%u",__func__,inet_ntoa(srp->nhlfe.prefv4.pre
fix),srp->nhlfe.prefv4.prefixlen,srp->sid);/*DeleteNHLFEisNO-PHPisset*/if(CHECK_
FLAG(srp->flags,EXT_SUBTLV_PREFIX_SID_NPFLG))del_sid_nhlfe(srp->nhlfe);/*OK,alli
sclean,removeSRPfromSRDB*/listnode_delete(OspfSR.self->ext_prefix,srp);XFREE(MTY
PE_OSPF_SR_PARAMS,srp);returnCMD_SUCCESS;}staticvoidshow_sr_node(structvty*vty,s
tructjson_object*json,structsr_node*srn){structlistnode*node;structsr_link*srl;s
tructsr_prefix*srp;structinterface*itf;charpref[19];charsid[22];charlabel[8];jso
n_object*json_node=NULL,*json_algo,*json_obj;json_object*json_prefix=NULL,*json_
link=NULL;/*SanityCheck*/if(srn==NULL)return;if(json){json_node=json_object_new_
object();json_object_string_add(json_node,"routerID",inet_ntoa(srn->adv_router))
;json_object_int_add(json_node,"srgbSize",srn->srgb.range_size);json_object_int_
add(json_node,"srgbLabel",srn->srgb.lower_bound);json_algo=json_object_new_array
();json_object_object_add(json_node,"algorithms",json_algo);for(inti=0;i<ALGORIT
HM_COUNT;i++){if(srn->algo[i]==SR_ALGORITHM_UNSET)continue;json_obj=json_object_
new_object();chartmp[2];snprintf(tmp,2,"%u",i);json_object_string_add(json_obj,t
mp,srn->algo[i]==SR_ALGORITHM_SPF?"SPF":"S-SPF");json_object_array_add(json_algo
,json_obj);}if(srn->msd!=0)json_object_int_add(json_node,"nodeMsd",srn->msd);}el
se{vty_out(vty,"SR-Node:%s",inet_ntoa(srn->adv_router));vty_out(vty,"\tSRGB(Size
/Label):%u/%u",srn->srgb.range_size,srn->srgb.lower_bound);vty_out(vty,"\tAlgori
thm(s):%s",srn->algo[0]==SR_ALGORITHM_SPF?"SPF":"S-SPF");for(inti=1;i<ALGORITHM_
COUNT;i++){if(srn->algo[i]==SR_ALGORITHM_UNSET)continue;vty_out(vty,"/%s",srn->a
lgo[i]==SR_ALGORITHM_SPF?"SPF":"S-SPF");}if(srn->msd!=0)vty_out(vty,"\tMSD:%u",s
rn->msd);}if(!json){vty_out(vty,"\n\nPrefixorLinkLabelInLabelOut""NodeorAdj.SIDI
nterfaceNexthop\n");vty_out(vty,"-----------------------------------""----------
-----------------------------------\n");}for(ALL_LIST_ELEMENTS_RO(srn->ext_prefi
x,node,srp)){snprintf(pref,19,"%s/%u",inet_ntoa(srp->nhlfe.prefv4.prefix),srp->n
hlfe.prefv4.prefixlen);snprintf(sid,22,"SRPfx(idx%u)",srp->sid);if(srp->nhlfe.la
bel_out==MPLS_LABEL_IMPLICIT_NULL)sprintf(label,"pop");elsesprintf(label,"%u",sr
p->nhlfe.label_out);itf=if_lookup_by_index(srp->nhlfe.ifindex,VRF_DEFAULT);if(js
on){if(!json_prefix){json_prefix=json_object_new_array();json_object_object_add(
json_node,"extendedPrefix",json_prefix);}json_obj=json_object_new_object();json_
object_string_add(json_obj,"prefix",pref);json_object_int_add(json_obj,"sid",srp
->sid);json_object_int_add(json_obj,"inputLabel",srp->nhlfe.label_in);json_objec
t_string_add(json_obj,"outputLabel",label);json_object_string_add(json_obj,"inte
rface",itf?itf->name:"-");json_object_string_add(json_obj,"nexthop",inet_ntoa(sr
p->nhlfe.nexthop));json_object_array_add(json_prefix,json_obj);}else{vty_out(vty
,"%18s%8u%9s%21s%9s%15s\n",pref,srp->nhlfe.label_in,label,sid,itf?itf->name:"-",
inet_ntoa(srp->nhlfe.nexthop));}}for(ALL_LIST_ELEMENTS_RO(srn->ext_link,node,srl
)){snprintf(pref,19,"%s/%u",inet_ntoa(srl->nhlfe[0].prefv4.prefix),srl->nhlfe[0]
.prefv4.prefixlen);snprintf(sid,22,"SRAdj.(lbl%u)",srl->sid[0]);if(srl->nhlfe[0]
.label_out==MPLS_LABEL_IMPLICIT_NULL)sprintf(label,"pop");elsesprintf(label,"%u"
,srl->nhlfe[0].label_out);itf=if_lookup_by_index(srl->nhlfe[0].ifindex,VRF_DEFAU
LT);if(json){if(!json_link){json_link=json_object_new_array();json_object_object
_add(json_node,"extendedLink",json_link);}/*PrimaryLink*/json_obj=json_object_ne
w_object();json_object_string_add(json_obj,"prefix",pref);json_object_int_add(js
on_obj,"sid",srl->sid[0]);json_object_int_add(json_obj,"inputLabel",srl->nhlfe[0
].label_in);json_object_string_add(json_obj,"outputLabel",label);json_object_str
ing_add(json_obj,"interface",itf?itf->name:"-");json_object_string_add(json_obj,
"nexthop",inet_ntoa(srl->nhlfe[0].nexthop));json_object_array_add(json_link,json
_obj);/*BackupLink*/json_obj=json_object_new_object();snprintf(sid,22,"SRAdj.(lb
l%u)",srl->sid[1]);if(srl->nhlfe[1].label_out==MPLS_LABEL_IMPLICIT_NULL)sprintf(
label,"pop");elsesprintf(label,"%u",srl->nhlfe[0].label_out);json_object_string_
add(json_obj,"prefix",pref);json_object_int_add(json_obj,"sid",srl->sid[1]);json
_object_int_add(json_obj,"inputLabel",srl->nhlfe[1].label_in);json_object_string
_add(json_obj,"outputLabel",label);json_object_string_add(json_obj,"interface",i
tf?itf->name:"-");json_object_string_add(json_obj,"nexthop",inet_ntoa(srl->nhlfe
[1].nexthop));json_object_array_add(json_link,json_obj);}else{vty_out(vty,"%18s%
8u%9s%21s%9s%15s\n",pref,srl->nhlfe[0].label_in,label,sid,itf?itf->name:"-",inet
_ntoa(srl->nhlfe[0].nexthop));snprintf(sid,22,"SRAdj.(lbl%u)",srl->sid[1]);if(sr
l->nhlfe[1].label_out==MPLS_LABEL_IMPLICIT_NULL)sprintf(label,"pop");elsesprintf
(label,"%u",srl->nhlfe[1].label_out);vty_out(vty,"%18s%8u%9s%21s%9s%15s\n",pref,
srl->nhlfe[1].label_in,label,sid,itf?itf->name:"-",inet_ntoa(srl->nhlfe[1].nexth
op));}}if(json)json_object_array_add(json,json_node);elsevty_out(vty,"\n");}stat
icvoidshow_vty_srdb(structhash_backet*backet,void*args){structvty*vty=(structvty
*)args;structsr_node*srn=(structsr_node*)backet->data;show_sr_node(vty,NULL,srn)
;}staticvoidshow_json_srdb(structhash_backet*backet,void*args){structjson_object
*json=(structjson_object*)args;structsr_node*srn=(structsr_node*)backet->data;sh
ow_sr_node(NULL,json,srn);}DEFUN(show_ip_opsf_srdb,show_ip_ospf_srdb_cmd,"showip
ospfdatabasesegment-routing[adv-routerA.B.C.D|self-originate][json]",SHOW_STRIP_
STROSPF_STR"Databasesummary\n""ShowSegmentRoutingDataBase\n""AdvertisingSRnode\n
""AdvertisingSRnodeID(asanIPaddress)\n""Self-originatedSRnode\n"JSON_STR){intidx
=0;structin_addrrid;structsr_node*srn;uint8_tuj=use_json(argc,argv);json_object*
json=NULL,*json_node_array=NULL;if(!OspfSR.enabled){vty_out(vty,"SegmentRoutingi
sdisabledonthisrouter\n");returnCMD_WARNING;}if(uj){json=json_object_new_object(
);json_node_array=json_object_new_array();json_object_string_add(json,"srdbID",i
net_ntoa(OspfSR.self->adv_router));json_object_object_add(json,"srNodes",json_no
de_array);}else{vty_out(vty,"\n\t\tOSPFSegmentRoutingdatabaseforID%s\n\n",inet_n
toa(OspfSR.self->adv_router));}if(argv_find(argv,argc,"self-originate",&idx)){sr
n=OspfSR.self;show_sr_node(vty,json_node_array,srn);if(uj){vty_out(vty,"%s\n",js
on_object_to_json_string_ext(json,JSON_C_TO_STRING_PRETTY));json_object_free(jso
n);}returnCMD_SUCCESS;}if(argv_find(argv,argc,"A.B.C.D",&idx)){if(!inet_aton(arg
v[idx]->arg,&rid)){vty_out(vty,"SpecifiedRouterID%sisinvalid\n",argv[idx]->arg);
returnCMD_WARNING_CONFIG_FAILED;}/*GettheSRNodefromtheSRDB*/srn=(structsr_node*)
hash_lookup(OspfSR.neighbors,(void*)&rid);show_sr_node(vty,json_node_array,srn);
if(uj){vty_out(vty,"%s\n",json_object_to_json_string_ext(json,JSON_C_TO_STRING_P
RETTY));json_object_free(json);}returnCMD_SUCCESS;}/*Noparametershavebeenprovide
d,IteratethroughalltheSRDB*/if(uj){hash_iterate(OspfSR.neighbors,(void(*)(struct
hash_backet*,void*))show_json_srdb,(void*)json_node_array);vty_out(vty,"%s\n",js
on_object_to_json_string_ext(json,JSON_C_TO_STRING_PRETTY));json_object_free(jso
n);}else{hash_iterate(OspfSR.neighbors,(void(*)(structhash_backet*,void*))show_v
ty_srdb,(void*)vty);}returnCMD_SUCCESS;}/*InstallnewCLIcommands*/voidospf_sr_reg
ister_vty(void){install_element(VIEW_NODE,&show_ip_ospf_srdb_cmd);install_elemen
t(OSPF_NODE,&ospf_sr_enable_cmd);install_element(OSPF_NODE,&no_ospf_sr_enable_cm
d);install_element(OSPF_NODE,&sr_sid_label_range_cmd);install_element(OSPF_NODE,
&no_sr_sid_label_range_cmd);install_element(OSPF_NODE,&sr_node_msd_cmd);install_
element(OSPF_NODE,&no_sr_node_msd_cmd);install_element(OSPF_NODE,&sr_prefix_sid_
cmd);install_element(OSPF_NODE,&no_sr_prefix_sid_cmd);}