/**APImessagehandlingmoduleforOSPFdaemonandclient.*Copyright(C)2001,2002RalphKel
ler**ThisfileispartofGNUZebra.**GNUZebraisfreesoftware;youcanredistributeitand/o
rmodify*itunderthetermsoftheGNUGeneralPublicLicenseaspublished*bytheFreeSoftware
Foundation;eitherversion2,or(atyour*option)anylaterversion.**GNUZebraisdistribut
edinthehopethatitwillbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarran
tyof*MERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicens
eformoredetails.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*wi
ththisprogram;seethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51F
ranklinSt,FifthFloor,Boston,MA02110-1301USA*//*ThisfileisusedbothbytheOSPFdandcl
ientapplicationstodefinemessageformatsusedforcommunication.*/#ifndef_OSPF_API_H#
define_OSPF_API_H#defineOSPF_API_VERSION1/*MTYPEdefinitionisnotreflectedto"memor
y.h".*/#defineMTYPE_OSPF_API_MSGMTYPE_TMP#defineMTYPE_OSPF_API_FIFOMTYPE_TMP/*De
faultAPIserverporttoacceptconnectionrequestfromclient-side.*//*Thisvaluecouldbeo
verriddenby"ospfapi"entryin"/etc/services".*/#defineOSPF_API_SYNC_PORT2607/*----
-------------------------------------------------------*Genericmessages*--------
---------------------------------------------------*//*Messageheaderstructure,fi
eldsareinnetworkbyteorderandalignedtofouroctets.*/structapimsghdr{uint8_tversion
;/*OSPFAPIprotocolversion*/uint8_tmsgtype;/*Typeofmessage*/uint16_tmsglen;/*Leng
thofmessagew/oheader*/uint32_tmsgseq;/*Sequencenumber*/};/*Messagerepresentation
withheaderandbody*/structmsg{structmsg*next;/*tolinkintofifo*//*Messageheader*/s
tructapimsghdrhdr;/*Messagebody*/structstream*s;};/*Prototypesforgenericmessages
.*/externstructmsg*msg_new(uint8_tmsgtype,void*msgbody,uint32_tseqnum,uint16_tms
glen);externstructmsg*msg_dup(structmsg*msg);externvoidmsg_print(structmsg*msg);
/*XXXdebugonly*/externvoidmsg_free(structmsg*msg);structmsg*msg_read(intfd);exte
rnintmsg_write(intfd,structmsg*msg);/*Forrequests,themessagesequencenumberisbetw
eenMIN_SEQandMAX_SEQ.Fornotifications,thesequencenumberis0.*/#defineMIN_SEQ1#def
ineMAX_SEQ2147483647externvoidmsg_set_seq(structmsg*msg,uint32_tseqnr);externuin
t32_tmsg_get_seq(structmsg*msg);/*----------------------------------------------
-------------*Messagefifoqueues*------------------------------------------------
-----------*//*Messagequeuestructure.*/structmsg_fifo{unsignedlongcount;structms
g*head;structmsg*tail;};/*Prototypeformessagefifoqueues.*/externstructmsg_fifo*m
sg_fifo_new(void);externvoidmsg_fifo_push(structmsg_fifo*,structmsg*msg);externs
tructmsg*msg_fifo_pop(structmsg_fifo*fifo);externstructmsg*msg_fifo_head(structm
sg_fifo*fifo);externvoidmsg_fifo_flush(structmsg_fifo*fifo);externvoidmsg_fifo_f
ree(structmsg_fifo*fifo);/*-----------------------------------------------------
------*Specificmessagetypeandformatdefinitions*---------------------------------
--------------------------*//*MessagestoOSPFdaemon.*/#defineMSG_REGISTER_OPAQUET
YPE1#defineMSG_UNREGISTER_OPAQUETYPE2#defineMSG_REGISTER_EVENT3#defineMSG_SYNC_L
SDB4#defineMSG_ORIGINATE_REQUEST5#defineMSG_DELETE_REQUEST6/*MessagesfromOSPFdae
mon.*/#defineMSG_REPLY10#defineMSG_READY_NOTIFY11#defineMSG_LSA_UPDATE_NOTIFY12#
defineMSG_LSA_DELETE_NOTIFY13#defineMSG_NEW_IF14#defineMSG_DEL_IF15#defineMSG_IS
M_CHANGE16#defineMSG_NSM_CHANGE17structmsg_register_opaque_type{uint8_tlsatype;u
int8_topaquetype;uint8_tpad[2];/*padding*/};structmsg_unregister_opaque_type{uin
t8_tlsatype;uint8_topaquetype;uint8_tpad[2];/*padding*/};/*Power2isneededtoconve
rtLSAtypesintobitpositions,*seetypemaskbelow.Typedefinitionstartsat1,so*Power2[0
]isnotused.*/#ifdefORIGINAL_CODINGstaticconstuint16_tPower2[]={0x0,0x1,0x2,0x4,0
x8,0x10,0x20,0x40,0x80,0x100,0x200,0x400,0x800,0x1000,0x2000,0x4000,0x8000};#els
estaticconstuint16_tPower2[]={0,(1<<0),(1<<1),(1<<2),(1<<3),(1<<4),(1<<5),(1<<6)
,(1<<7),(1<<8),(1<<9),(1<<10),(1<<11),(1<<12),(1<<13),(1<<14),(1<<15)};#endif/*O
RIGINAL_CODING*/structlsa_filter_type{uint16_ttypemask;/*bitmaskforselectingLSAt
ypes(1..16)*/uint8_torigin;/*selectsaccordingtoorigin.*/#defineNON_SELF_ORIGINAT
ED0#defineSELF_ORIGINATED(OSPF_LSA_SELF)#defineANY_ORIGIN2uint8_tnum_areas;/*num
berofareasinthefilter.*//*areas,ifany,gohere.*/};structmsg_register_event{struct
lsa_filter_typefilter;};structmsg_sync_lsdb{structlsa_filter_typefilter;};struct
msg_originate_request{/*UsedforLSAtype9otherwiseignored*/structin_addrifaddr;/*U
sedforLSAtype10otherwiseignored*/structin_addrarea_id;/*LSAheaderandLSA-specific
part*/structlsa_headerdata;};structmsg_delete_request{structin_addrarea_id;/*"0.
0.0.0"forAS-externalopaqueLSAs*/uint8_tlsa_type;uint8_topaque_type;uint8_tpad[2]
;/*padding*/uint32_topaque_id;};structmsg_reply{signedcharerrcode;#defineOSPF_AP
I_OK0#defineOSPF_API_NOSUCHINTERFACE(-1)#defineOSPF_API_NOSUCHAREA(-2)#defineOSP
F_API_NOSUCHLSA(-3)#defineOSPF_API_ILLEGALLSATYPE(-4)#defineOSPF_API_OPAQUETYPEI
NUSE(-5)#defineOSPF_API_OPAQUETYPENOTREGISTERED(-6)#defineOSPF_API_NOTREADY(-7)#
defineOSPF_API_NOMEMORY(-8)#defineOSPF_API_ERROR(-9)#defineOSPF_API_UNDEF(-10)ui
nt8_tpad[3];/*paddingtofourbytealignment*/};/*Messagetotellclientapplicationthat
itospfdaemonis*readytoacceptopaqueLSAsforagiveninterfaceorarea.*/structmsg_ready
_notify{uint8_tlsa_type;uint8_topaque_type;uint8_tpad[2];/*padding*/structin_add
raddr;/*interfaceaddressorareaaddress*/};/*Thesemessageshaveadynamiclengthdepend
ingontheembodiedLSA.Theyarealignedtofouroctets.msg_lsa_change_notifyisusedforbot
hLSAupdateandLSAsdelete.*/structmsg_lsa_change_notify{/*UsedforLSAtype9otherwise
ignored*/structin_addrifaddr;/*AreaID.NotvalidforAS-ExternalandOpaque11LSAs.*/st
ructin_addrarea_id;uint8_tis_self_originated;/*1ifselforiginated.*/uint8_tpad[3]
;structlsa_headerdata;};structmsg_new_if{structin_addrifaddr;/*interfaceIPaddres
s*/structin_addrarea_id;/*areathisinterfacebelongsto*/};structmsg_del_if{structi
n_addrifaddr;/*interfaceIPaddress*/};structmsg_ism_change{structin_addrifaddr;/*
interfaceIPaddress*/structin_addrarea_id;/*areathisinterfacebelongsto*/uint8_tst
atus;/*interfacestatus(up/down)*/uint8_tpad[3];/*notused*/};structmsg_nsm_change
{structin_addrifaddr;/*attachedinterface*/structin_addrnbraddr;/*Neighborinterfa
ceaddress*/structin_addrrouter_id;/*RouterIDofneighbor*/uint8_tstatus;/*NSMstatu
s*/uint8_tpad[3];};/*WemakeuseofauniontodefineastructurethatcoversallpossibleAPI
messages.ThisallowsustofindouthowmuchmemoryneedstobereservedforthelargestAPImess
age.*/structapimsg{structapimsghdrhdr;union{structmsg_register_opaque_typeregist
er_opaque_type;structmsg_register_eventregister_event;structmsg_sync_lsdbsync_ls
db;structmsg_originate_requestoriginate_request;structmsg_delete_requestdelete_r
equest;structmsg_replyreply;structmsg_ready_notifyready_notify;structmsg_new_ifn
ew_if;structmsg_del_ifdel_if;structmsg_ism_changeism_change;structmsg_nsm_change
nsm_change;structmsg_lsa_change_notifylsa_change_notify;}u;};#defineOSPF_API_MAX
_MSG_SIZE(sizeof(structapimsg)+OSPF_MAX_LSA_SIZE)/*-----------------------------
------------------------------*Prototypesforspecificmessages*-------------------
----------------------------------------*//*Fordebuggingonly.*/externvoidapi_opa
que_lsa_print(structlsa_header*data);/*Messagessentbyclient*/externstructmsg*new
_msg_register_opaque_type(uint32_tseqnum,uint8_tltype,uint8_totype);externstruct
msg*new_msg_register_event(uint32_tseqnum,structlsa_filter_type*filter);externst
ructmsg*new_msg_sync_lsdb(uint32_tseqnum,structlsa_filter_type*filter);externstr
uctmsg*new_msg_originate_request(uint32_tseqnum,structin_addrifaddr,structin_add
rarea_id,structlsa_header*data);externstructmsg*new_msg_delete_request(uint32_ts
eqnum,structin_addrarea_id,uint8_tlsa_type,uint8_topaque_type,uint32_topaque_id)
;/*MessagessentbyOSPFdaemon*/externstructmsg*new_msg_reply(uint32_tseqnum,uint8_
trc);externstructmsg*new_msg_ready_notify(uint32_tseqnr,uint8_tlsa_type,uint8_to
paque_type,structin_addraddr);externstructmsg*new_msg_new_if(uint32_tseqnr,struc
tin_addrifaddr,structin_addrarea);externstructmsg*new_msg_del_if(uint32_tseqnr,s
tructin_addrifaddr);externstructmsg*new_msg_ism_change(uint32_tseqnr,structin_ad
drifaddr,structin_addrarea,uint8_tstatus);externstructmsg*new_msg_nsm_change(uin
t32_tseqnr,structin_addrifaddr,structin_addrnbraddr,structin_addrrouter_id,uint8
_tstatus);/*msgtypeisMSG_LSA_UPDATE_NOTIFYorMSG_LSA_DELETE_NOTIFY*/externstructm
sg*new_msg_lsa_change_notify(uint8_tmsgtype,uint32_tseqnum,structin_addrifaddr,s
tructin_addrarea_id,uint8_tis_self_originated,structlsa_header*data);/*stringpri
ntingfunctions*/externconstchar*ospf_api_errname(interrcode);externconstchar*osp
f_api_typename(intmsgtype);#endif/*_OSPF_API_H*/