/**OSPFdmainroutine.*Copyright(C)1998,99KunihiroIshiguro,ToshiakiTakada**Thisfil
eispartofGNUZebra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodifyit*un
derthetermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;e
itherversion2,or(atyouroption)any*laterversion.**GNUZebraisdistributedinthehopet
hatitwillbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHAN
TABILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredeta
ils.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogra
m;seethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,Fi
fthFloor,Boston,MA02110-1301USA*/#include<zebra.h>#include<lib/version.h>#includ
e"getopt.h"#include"thread.h"#include"prefix.h"#include"linklist.h"#include"if.h
"#include"vector.h"#include"vty.h"#include"command.h"#include"filter.h"#include"
plist.h"#include"stream.h"#include"log.h"#include"memory.h"#include"memory_vty.h
"#include"privs.h"#include"sigevent.h"#include"zclient.h"#include"vrf.h"#include
"libfrr.h"#include"ospfd/ospfd.h"#include"ospfd/ospf_interface.h"#include"ospfd/
ospf_asbr.h"#include"ospfd/ospf_lsa.h"#include"ospfd/ospf_lsdb.h"#include"ospfd/
ospf_neighbor.h"#include"ospfd/ospf_dump.h"#include"ospfd/ospf_zebra.h"#include"
ospfd/ospf_vty.h"#include"ospfd/ospf_bfd.h"/*ospfdprivileges*/zebra_capabilities
_t_caps_p[]={ZCAP_NET_RAW,ZCAP_BIND,ZCAP_NET_ADMIN,ZCAP_SYS_ADMIN};structzebra_p
rivs_tospfd_privs={#ifdefined(FRR_USER)&&defined(FRR_GROUP).user=FRR_USER,.group
=FRR_GROUP,#endif#ifdefined(VTY_GROUP).vty_group=VTY_GROUP,#endif.caps_p=_caps_p
,.cap_num_p=array_size(_caps_p),.cap_num_i=0};/*OSPFdoptions.*/structoptionlongo
pts[]={{"instance",required_argument,NULL,'n'},{"apiserver",no_argument,NULL,'a'
},{0}};/*OSPFdprogramname*//*Masterofthreads.*/structthread_master*master;#ifdef
SUPPORT_OSPF_APIexternintospf_apiserver_enable;#endif/*SUPPORT_OSPF_API*//*SIGHU
Phandler.*/staticvoidsighup(void){zlog_info("SIGHUPreceived");}/*SIGINT/SIGTERMh
andler.*/staticvoidsigint(void){zlog_notice("Terminatingonsignal");ospf_terminat
e();}/*SIGUSR1handler.*/staticvoidsigusr1(void){zlog_rotate();}structquagga_sign
al_tospf_signals[]={{.signal=SIGHUP,.handler=&sighup,},{.signal=SIGUSR1,.handler
=&sigusr1,},{.signal=SIGINT,.handler=&sigint,},{.signal=SIGTERM,.handler=&sigint
,},};FRR_DAEMON_INFO(ospfd,OSPF,.vty_port=OSPF_VTY_PORT,.proghelp="Implementatio
noftheOSPFv2routingprotocol.",.signals=ospf_signals,.n_signals=array_size(ospf_s
ignals),.privs=&ospfd_privs,)/*OSPFdmainroutine.*/intmain(intargc,char**argv){un
signedshortinstance=0;#ifdefSUPPORT_OSPF_API/*OSPFapiserverisdisabledbydefault.*
/ospf_apiserver_enable=0;#endif/*SUPPORT_OSPF_API*/frr_preinit(&ospfd_di,argc,ar
gv);frr_opt_add("n:a",longopts,"-n,--instanceSettheinstanceid\n""-a,--apiserverE
nableOSPFapiserver\n");while(1){intopt;opt=frr_getopt(argc,argv,NULL);if(opt==EO
F)break;switch(opt){case'n':ospfd_di.instance=instance=atoi(optarg);if(instance<
1)exit(0);break;case0:break;#ifdefSUPPORT_OSPF_APIcase'a':ospf_apiserver_enable=
1;break;#endif/*SUPPORT_OSPF_API*/default:frr_help_exit(1);break;}}/*Invokedbyap
riviledgeduser?--endo.*/if(geteuid()!=0){errno=EPERM;perror(ospfd_di.progname);e
xit(1);}/*OSPFmasterinit.*/ospf_master_init(frr_init());/*Initializations.*/mast
er=om->master;/*Libraryinits.*/debug_init();ospf_vrf_init();access_list_init();p
refix_list_init();/*OSPFdinits.*/ospf_if_init();ospf_zebra_init(master,instance)
;/*OSPFvtyinits.*/ospf_vty_init();ospf_vty_show_init();ospf_vty_clear_init();/*O
SPFBFDinit*/ospf_bfd_init();ospf_route_map_init();ospf_opaque_init();/*Needtoini
tializethedefaultospfstructure,sotheinterfacemodecommandscanbedulyprocessedifthe
yarereceivedbefore'routerospf',whenquagga(ospfd)isrestarted*/if(!ospf_get_instan
ce(instance)){zlog_err("OSPFinstanceinitfailed:%s",strerror(errno));exit(1);}frr
_config_fork();frr_run(master);/*Notreached.*/return(0);}