/***ospf_bfd.c:OSPFBFDhandlingroutines**@copyrightCopyright(C)2015CumulusNetwork
s,Inc.**ThisfileispartofGNUZebra.**GNUZebraisfreesoftware;youcanredistributeitan
d/ormodifyit*underthetermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftw
areFoundation;eitherversion2,or(atyouroption)any*laterversion.**GNUZebraisdistri
butedinthehopethatitwillbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwar
rantyof*MERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLic
enseformoredetails.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong
*withthisprogram;seethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,
51FranklinSt,FifthFloor,Boston,MA02110-1301USA*/#include<zebra.h>#include"comman
d.h"#include"linklist.h"#include"memory.h"#include"prefix.h"#include"thread.h"#i
nclude"buffer.h"#include"stream.h"#include"zclient.h"#include"vty.h"#include"tab
le.h"#include"bfd.h"#include"ospfd.h"#include"ospf_asbr.h"#include"ospf_lsa.h"#i
nclude"ospf_lsdb.h"#include"ospf_neighbor.h"#include"ospf_interface.h"#include"o
spf_nsm.h"#include"ospf_bfd.h"#include"ospf_dump.h"#include"ospf_vty.h"externstr
uctzclient*zclient;/**ospf_bfd_info_free-FreeBFDinfostructure*/voidospf_bfd_info
_free(void**bfd_info){bfd_info_free((structbfd_info**)bfd_info);}/**ospf_bfd_reg
_dereg_nbr-Register/DeregisteraneighborwithBFDthrough*zebraforstarting/stoppingt
hemonitoringof*theneighborrechahability.*/staticvoidospf_bfd_reg_dereg_nbr(struc
tospf_neighbor*nbr,intcommand){structospf_interface*oi=nbr->oi;structinterface*i
fp=oi->ifp;structospf_if_params*params;structbfd_info*bfd_info;/*CheckifBFDisena
bled*/params=IF_DEF_PARAMS(ifp);/*CheckifBFDisenabled*/if(!params->bfd_info)retu
rn;bfd_info=(structbfd_info*)params->bfd_info;if(IS_DEBUG_OSPF(zebra,ZEBRA_INTER
FACE))zlog_debug("%snbr(%s)withBFD.OSPFvrf%s",bfd_get_command_dbg_str(command),i
net_ntoa(nbr->src),ospf_vrf_id_to_name(oi->ospf->vrf_id));bfd_peer_sendmsg(zclie
nt,bfd_info,AF_INET,&nbr->src,NULL,ifp->name,0,0,command,0,oi->ospf->vrf_id);}/*
*ospf_bfd_trigger_event-Neighborisregistered/deregisteredwithBFDwhen*neighborsta
teischangedto/from2way.*/voidospf_bfd_trigger_event(structospf_neighbor*nbr,into
ld_state,intstate){if((old_state<NSM_TwoWay)&&(state>=NSM_TwoWay))ospf_bfd_reg_d
ereg_nbr(nbr,ZEBRA_BFD_DEST_REGISTER);elseif((old_state>=NSM_TwoWay)&&(state<NSM
_TwoWay))ospf_bfd_reg_dereg_nbr(nbr,ZEBRA_BFD_DEST_DEREGISTER);}/**ospf_bfd_reg_
dereg_all_nbr-Register/Deregisterallneighborsassociated*withainterfacewithBFDthr
ough*zebraforstarting/stoppingthemonitoringof*theneighborrechahability.*/statici
ntospf_bfd_reg_dereg_all_nbr(structinterface*ifp,intcommand){structospf_interfac
e*oi;structroute_table*nbrs;structospf_neighbor*nbr;structroute_node*irn;structr
oute_node*nrn;for(irn=route_top(IF_OIFS(ifp));irn;irn=route_next(irn)){if((oi=ir
n->info)==NULL)continue;if((nbrs=oi->nbrs)==NULL)continue;for(nrn=route_top(nbrs
);nrn;nrn=route_next(nrn)){if((nbr=nrn->info)==NULL||nbr==oi->nbr_self)continue;
if(command!=ZEBRA_BFD_DEST_DEREGISTER)ospf_bfd_info_nbr_create(oi,nbr);elsebfd_i
nfo_free((structbfd_info**)&nbr->bfd_info);if(nbr->state<NSM_TwoWay)continue;osp
f_bfd_reg_dereg_nbr(nbr,command);}}return0;}/**ospf_bfd_nbr_replay-Replayallthen
eighborsthathaveBFDenabled*tozebra*/staticintospf_bfd_nbr_replay(intcommand,stru
ctzclient*zclient,zebra_size_tlength,vrf_id_tvrf_id){structlistnode*inode,*node,
*onode;structospf*ospf;structospf_interface*oi;structroute_table*nbrs;structrout
e_node*rn;structospf_neighbor*nbr;structospf_if_params*params;if(IS_DEBUG_OSPF(z
ebra,ZEBRA_INTERFACE)){zlog_debug("Zebra:BFDDestreplayrequest");}/*Sendtheclient
registration*/bfd_client_sendmsg(zclient,ZEBRA_BFD_CLIENT_REGISTER);/*Replaythen
eighbor,ifBFDisenabledinOSPF*/for(ALL_LIST_ELEMENTS(om->ospf,node,onode,ospf)){f
or(ALL_LIST_ELEMENTS_RO(ospf->oiflist,inode,oi)){if((nbrs=oi->nbrs)==NULL)contin
ue;params=IF_DEF_PARAMS(oi->ifp);if(!params->bfd_info)continue;for(rn=route_top(
nbrs);rn;rn=route_next(rn)){if((nbr=rn->info)==NULL||nbr==oi->nbr_self)continue;
if(nbr->state<NSM_TwoWay)continue;if(IS_DEBUG_OSPF(zebra,ZEBRA_INTERFACE))zlog_d
ebug("Replayingnbr(%s)toBFD",inet_ntoa(nbr->src));ospf_bfd_reg_dereg_nbr(nbr,ZEB
RA_BFD_DEST_UPDATE);}}}return0;}/**ospf_bfd_interface_dest_update-Findtheneighbo
rforwhichtheBFDstatus*haschangedandbringdowntheneighbor*connectivityiftheBFDstat
uschangedto*down.*/staticintospf_bfd_interface_dest_update(intcommand,structzcli
ent*zclient,zebra_size_tlength,vrf_id_tvrf_id){structinterface*ifp;structospf_in
terface*oi;structospf_if_params*params;structospf_neighbor*nbr;structroute_node*
node;structprefixp;intstatus;intold_status;structbfd_info*bfd_info;structtimeval
tv;ifp=bfd_get_peer_info(zclient->ibuf,&p,NULL,&status,vrf_id);if((ifp==NULL)||(
p.family!=AF_INET))return0;if(IS_DEBUG_OSPF(zebra,ZEBRA_INTERFACE)){charbuf[PREF
IX2STR_BUFFER];prefix2str(&p,buf,sizeof(buf));zlog_debug("Zebra:interface%sbfdde
stination%s%s",ifp->name,buf,bfd_get_status_str(status));}params=IF_DEF_PARAMS(i
fp);if(!params->bfd_info)return0;for(node=route_top(IF_OIFS(ifp));node;node=rout
e_next(node)){if((oi=node->info)==NULL)continue;nbr=ospf_nbr_lookup_by_addr(oi->
nbrs,&p.u.prefix4);if(!nbr||!nbr->bfd_info)continue;bfd_info=(structbfd_info*)nb
r->bfd_info;if(bfd_info->status==status)continue;old_status=bfd_info->status;bfd
_info->status=status;monotime(&tv);bfd_info->last_update=tv.tv_sec;if((status==B
FD_STATUS_DOWN)&&(old_status==BFD_STATUS_UP)){if(IS_DEBUG_OSPF(nsm,NSM_EVENTS))z
log_debug("NSM[%s:%s]:BFDDown",IF_NAME(nbr->oi),inet_ntoa(nbr->address.u.prefix4
));OSPF_NSM_EVENT_SCHEDULE(nbr,NSM_InactivityTimer);}}return0;}/**ospf_bfd_info_
nbr_create-Create/updateBFDinformationforaneighbor.*/voidospf_bfd_info_nbr_creat
e(structospf_interface*oi,structospf_neighbor*nbr){structbfd_info*oi_bfd_info;st
ructbfd_info*nbr_bfd_info;structinterface*ifp=oi->ifp;structospf_if_params*param
s;/*CheckifBFDisenabled*/params=IF_DEF_PARAMS(ifp);/*CheckifBFDisenabled*/if(!pa
rams->bfd_info)return;oi_bfd_info=(structbfd_info*)params->bfd_info;if(!nbr->bfd
_info)nbr->bfd_info=bfd_info_create();nbr_bfd_info=(structbfd_info*)nbr->bfd_inf
o;nbr_bfd_info->detect_mult=oi_bfd_info->detect_mult;nbr_bfd_info->desired_min_t
x=oi_bfd_info->desired_min_tx;nbr_bfd_info->required_min_rx=oi_bfd_info->require
d_min_rx;}/**ospf_bfd_write_config-WritetheinterfaceBFDconfiguration.*/voidospf_
bfd_write_config(structvty*vty,structospf_if_params*params){structbfd_info*bfd_i
nfo;if(!params->bfd_info)return;bfd_info=(structbfd_info*)params->bfd_info;if(CH
ECK_FLAG(bfd_info->flags,BFD_FLAG_PARAM_CFG))vty_out(vty,"ipospfbfd%d%d%d\n",bfd
_info->detect_mult,bfd_info->required_min_rx,bfd_info->desired_min_tx);elsevty_o
ut(vty,"ipospfbfd\n");}/**ospf_bfd_show_info-ShowBFDinfostructure*/voidospf_bfd_
show_info(structvty*vty,void*bfd_info,json_object*json_obj,uint8_tuse_json,intpa
ram_only){if(param_only)bfd_show_param(vty,(structbfd_info*)bfd_info,1,0,use_jso
n,json_obj);elsebfd_show_info(vty,(structbfd_info*)bfd_info,0,1,use_json,json_ob
j);}/**ospf_bfd_interface_show-ShowtheinterfaceBFDconfiguration.*/voidospf_bfd_i
nterface_show(structvty*vty,structinterface*ifp,json_object*json_interface_sub,u
int8_tuse_json){structospf_if_params*params;params=IF_DEF_PARAMS(ifp);ospf_bfd_s
how_info(vty,params->bfd_info,json_interface_sub,use_json,1);}/**ospf_bfd_if_par
am_set-SettheconfiguredBFDparamtervaluesfor*interface.*/staticvoidospf_bfd_if_pa
ram_set(structinterface*ifp,uint32_tmin_rx,uint32_tmin_tx,uint8_tdetect_mult,int
defaults){structospf_if_params*params;intcommand=0;params=IF_DEF_PARAMS(ifp);bfd
_set_param((structbfd_info**)&(params->bfd_info),min_rx,min_tx,detect_mult,defau
lts,&command);if(command)ospf_bfd_reg_dereg_all_nbr(ifp,command);}DEFUN(ip_ospf_
bfd,ip_ospf_bfd_cmd,"ipospfbfd","IPInformation\n""OSPFinterfacecommands\n""Enabl
esBFDsupport\n"){VTY_DECLVAR_CONTEXT(interface,ifp);structospf_if_params*params;
structbfd_info*bfd_info;assert(ifp);params=IF_DEF_PARAMS(ifp);bfd_info=params->b
fd_info;if(!bfd_info||!CHECK_FLAG(bfd_info->flags,BFD_FLAG_PARAM_CFG))ospf_bfd_i
f_param_set(ifp,BFD_DEF_MIN_RX,BFD_DEF_MIN_TX,BFD_DEF_DETECT_MULT,1);returnCMD_S
UCCESS;}DEFUN(ip_ospf_bfd_param,ip_ospf_bfd_param_cmd,"ipospfbfd(2-255)(50-60000
)(50-60000)","IPInformation\n""OSPFinterfacecommands\n""EnablesBFDsupport\n""Det
ectMultiplier\n""Requiredminreceiveinterval\n""Desiredmintransmitinterval\n"){VT
Y_DECLVAR_CONTEXT(interface,ifp);intidx_number=3;intidx_number_2=4;intidx_number
_3=5;uint32_trx_val;uint32_ttx_val;uint8_tdm_val;intret;assert(ifp);if((ret=bfd_
validate_param(vty,argv[idx_number]->arg,argv[idx_number_2]->arg,argv[idx_number
_3]->arg,&dm_val,&rx_val,&tx_val))!=CMD_SUCCESS)returnret;ospf_bfd_if_param_set(
ifp,rx_val,tx_val,dm_val,0);returnCMD_SUCCESS;}DEFUN(no_ip_ospf_bfd,no_ip_ospf_b
fd_cmd,"noipospfbfd[(2-255)(50-60000)(50-60000)]",NO_STR"IPInformation\n""OSPFin
terfacecommands\n""DisablesBFDsupport\n""DetectMultiplier\n""Requiredminreceivei
nterval\n""Desiredmintransmitinterval\n"){VTY_DECLVAR_CONTEXT(interface,ifp);str
uctospf_if_params*params;assert(ifp);params=IF_DEF_PARAMS(ifp);if(params->bfd_in
fo){ospf_bfd_reg_dereg_all_nbr(ifp,ZEBRA_BFD_DEST_DEREGISTER);bfd_info_free(&(pa
rams->bfd_info));}returnCMD_SUCCESS;}voidospf_bfd_init(void){bfd_gbl_init();/*In
itializeBFDclientfunctions*/zclient->interface_bfd_dest_update=ospf_bfd_interfac
e_dest_update;zclient->bfd_dest_replay=ospf_bfd_nbr_replay;/*InstallBFDcommand*/
install_element(INTERFACE_NODE,&ip_ospf_bfd_cmd);install_element(INTERFACE_NODE,
&ip_ospf_bfd_param_cmd);install_element(INTERFACE_NODE,&no_ip_ospf_bfd_cmd);}