/*OSPFSPFcalculation.*Copyright(C)1999,2000KunihiroIshiguro,ToshiakiTakada**This
fileispartofGNUZebra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodifyit
*underthetermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundatio
n;eitherversion2,or(atyouroption)any*laterversion.**GNUZebraisdistributedintheho
pethatitwillbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERC
HANTABILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformored
etails.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthispro
gram;seethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt
,FifthFloor,Boston,MA02110-1301USA*/#include<zebra.h>#include"monotime.h"#includ
e"thread.h"#include"memory.h"#include"hash.h"#include"linklist.h"#include"prefix
.h"#include"if.h"#include"table.h"#include"log.h"#include"sockunion.h"/*forinet_
ntop()*/#include"pqueue.h"#include"ospfd/ospfd.h"#include"ospfd/ospf_interface.h
"#include"ospfd/ospf_ism.h"#include"ospfd/ospf_asbr.h"#include"ospfd/ospf_lsa.h"
#include"ospfd/ospf_lsdb.h"#include"ospfd/ospf_neighbor.h"#include"ospfd/ospf_ns
m.h"#include"ospfd/ospf_spf.h"#include"ospfd/ospf_route.h"#include"ospfd/ospf_ia
.h"#include"ospfd/ospf_ase.h"#include"ospfd/ospf_abr.h"#include"ospfd/ospf_dump.
h"#include"ospfd/ospf_sr.h"/*VariablestoensureaSPFscheduledlogmessageisprintedon
lyonce*/staticunsignedintspf_reason_flags=0;staticvoidospf_clear_spf_reason_flag
s(void){spf_reason_flags=0;}staticvoidospf_spf_set_reason(ospf_spf_reason_treaso
n){spf_reason_flags|=1<<reason;}staticvoidospf_vertex_free(void*);/*Listofalloca
tedvertices,tosimplifycleanupofSPF.*Notthread-safeobviously.Ifiteverneedstobe,it
'dhavetobe*dynamicallyallocatedatbeginofospf_spf_calculate*/staticstructlistvert
ex_list={.del=ospf_vertex_free};/*Heaprelatedfunctions,forthemanagmentofthecandi
dates,to*beusedwithpqueue.*/staticintcmp(void*node1,void*node2){structvertex*v1=
(structvertex*)node1;structvertex*v2=(structvertex*)node2;if(v1!=NULL&&v2!=NULL)
{/*networkverticesmustbechosenbeforerouterverticesof*same*costinordertofindallsh
ortestpaths*/if(((v1->distance-v2->distance)==0)&&(v1->type!=v2->type)){switch(v
1->type){caseOSPF_VERTEX_NETWORK:return-1;caseOSPF_VERTEX_ROUTER:return1;}}elser
eturn(v1->distance-v2->distance);}return0;}staticvoidupdate_stat(void*node,intpo
sition){structvertex*v=node;/*Setthestatusofthevertex,whenitspositionchanges.*/*
(v->stat)=position;}staticstructvertex_nexthop*vertex_nexthop_new(void){returnXC
ALLOC(MTYPE_OSPF_NEXTHOP,sizeof(structvertex_nexthop));}staticvoidvertex_nexthop
_free(structvertex_nexthop*nh){XFREE(MTYPE_OSPF_NEXTHOP,nh);}/*Freethecanonicaln
exthopobjectsforanarea,iethenexthopobjects*attachedtothefirst-hoproutervertices,
andanyinterveningnetwork*vertices.*/staticvoidospf_canonical_nexthops_free(struc
tvertex*root){structlistnode*node,*nnode;structvertex*child;for(ALL_LIST_ELEMENT
S(root->children,node,nnode,child)){structlistnode*n2,*nn2;structvertex_parent*v
p;/*routerverticesthroughanattachednetworkeach*haveadistinct(canonical/notinheri
ted)nexthop*whichmustbefreed.**Anetworkvertexcanonlyhaverouterverticesasits*chil
dren,soonlyonelevelofrecursionispossible.*/if(child->type==OSPF_VERTEX_NETWORK)o
spf_canonical_nexthops_free(child);/*Freechildnexthopspointingbacktothisrootvert
ex*/for(ALL_LIST_ELEMENTS(child->parents,n2,nn2,vp))if(vp->parent==root&&vp->nex
thop){vertex_nexthop_free(vp->nexthop);vp->nexthop=NULL;}}}/*TODO:Parentlistshou
ldbeexcised,infavourofmaintainingonly*vertex_nexthop,withrefcounts.*/staticstruc
tvertex_parent*vertex_parent_new(structvertex*v,intbacklink,structvertex_nexthop
*hop){structvertex_parent*new;new=XMALLOC(MTYPE_OSPF_VERTEX_PARENT,sizeof(struct
vertex_parent));if(new==NULL)returnNULL;new->parent=v;new->backlink=backlink;new
->nexthop=hop;returnnew;}staticvoidvertex_parent_free(void*p){XFREE(MTYPE_OSPF_V
ERTEX_PARENT,p);}staticstructvertex*ospf_vertex_new(structospf_lsa*lsa){structve
rtex*new;new=XCALLOC(MTYPE_OSPF_VERTEX,sizeof(structvertex));new->flags=0;new->s
tat=&(lsa->stat);new->type=lsa->data->type;new->id=lsa->data->id;new->lsa=lsa->d
ata;new->children=list_new();new->parents=list_new();new->parents->del=vertex_pa
rent_free;listnode_add(&vertex_list,new);if(IS_DEBUG_OSPF_EVENT)zlog_debug("%s:C
reated%svertex%s",__func__,new->type==OSPF_VERTEX_ROUTER?"Router":"Network",inet
_ntoa(new->lsa->id));returnnew;}staticvoidospf_vertex_free(void*data){structvert
ex*v=data;if(IS_DEBUG_OSPF_EVENT)zlog_debug("%s:Free%svertex%s",__func__,v->type
==OSPF_VERTEX_ROUTER?"Router":"Network",inet_ntoa(v->lsa->id));/*Thereshouldbeno
parentspotentiallyholdingreferencestothis*vertex*Childrenhowevermaystillbethere,
butpresumablyreferencedby*other*vertices*///assert(listcount(v->parents)==0);if(
v->children)list_delete_and_null(&v->children);if(v->parents)list_delete_and_nul
l(&v->parents);v->lsa=NULL;XFREE(MTYPE_OSPF_VERTEX,v);}staticvoidospf_vertex_dum
p(constchar*msg,structvertex*v,intprint_parents,intprint_children){if(!IS_DEBUG_
OSPF_EVENT)return;zlog_debug("%s%svertex%sdistance%uflags%u",msg,v->type==OSPF_V
ERTEX_ROUTER?"Router":"Network",inet_ntoa(v->lsa->id),v->distance,(unsignedint)v
->flags);if(print_parents){structlistnode*node;structvertex_parent*vp;for(ALL_LI
ST_ELEMENTS_RO(v->parents,node,vp)){charbuf1[BUFSIZ];if(vp){zlog_debug("parent%s
backlink%dnexthop%sinterface%s",inet_ntoa(vp->parent->lsa->id),vp->backlink,inet
_ntop(AF_INET,&vp->nexthop->router,buf1,BUFSIZ),vp->nexthop->oi?IF_NAME(vp->next
hop->oi):"NULL");}}}if(print_children){structlistnode*cnode;structvertex*cv;for(
ALL_LIST_ELEMENTS_RO(v->children,cnode,cv))ospf_vertex_dump("child:",cv,0,0);}}/
*Addavertextothelistofchildrenineachofitsparents.*/staticvoidospf_vertex_add_par
ent(structvertex*v){structvertex_parent*vp;structlistnode*node;assert(v&&v->pare
nts);for(ALL_LIST_ELEMENTS_RO(v->parents,node,vp)){assert(vp->parent&&vp->parent
->children);/*Noneedtoaddtwolinksfromthesameparent.*/if(listnode_lookup(vp->pare
nt->children,v)==NULL)listnode_add(vp->parent->children,v);}}staticvoidospf_spf_
init(structospf_area*area){structvertex*v;/*Createrootnode.*/v=ospf_vertex_new(a
rea->router_lsa_self);area->spf=v;/*ResetABRandASBRroutercounts.*/area->abr_coun
t=0;area->asbr_count=0;}/*returnindexoflinkbacktoVfromW,or-1ifnolinkfound*/stati
cintospf_lsa_has_link(structlsa_header*w,structlsa_header*v){unsignedinti,length
;structrouter_lsa*rl;structnetwork_lsa*nl;/*IncaseofWisNetworkLSA.*/if(w->type==
OSPF_NETWORK_LSA){if(v->type==OSPF_NETWORK_LSA)return-1;nl=(structnetwork_lsa*)w
;length=(ntohs(w->length)-OSPF_LSA_HEADER_SIZE-4)/4;for(i=0;i<length;i++)if(IPV4
_ADDR_SAME(&nl->routers[i],&v->id))returni;return-1;}/*IncaseofWisRouterLSA.*/if
(w->type==OSPF_ROUTER_LSA){rl=(structrouter_lsa*)w;length=ntohs(w->length);for(i
=0;i<ntohs(rl->links)&&length>=sizeof(structrouter_lsa);i++,length-=12){switch(r
l->link[i].type){caseLSA_LINK_TYPE_POINTOPOINT:caseLSA_LINK_TYPE_VIRTUALLINK:/*R
outerLSAID.*/if(v->type==OSPF_ROUTER_LSA&&IPV4_ADDR_SAME(&rl->link[i].link_id,&v
->id)){returni;}break;caseLSA_LINK_TYPE_TRANSIT:/*NetworkLSAID.*/if(v->type==OSP
F_NETWORK_LSA&&IPV4_ADDR_SAME(&rl->link[i].link_id,&v->id)){returni;}break;caseL
SA_LINK_TYPE_STUB:/*Stubcan'tleadanywhere,carryon*/continue;default:break;}}}ret
urn-1;}/*Findthenextlinkafterprev_linkfromvtow.Ifprev_linkis*NULL,returnthefirst
linkfromvtow.Ignorestubandvirtuallinks;*theselinktypeswillneverbereturned.*/stat
icstructrouter_lsa_link*ospf_get_next_link(structvertex*v,structvertex*w,structr
outer_lsa_link*prev_link){uint8_t*p;uint8_t*lim;uint8_tlsa_type=LSA_LINK_TYPE_TR
ANSIT;structrouter_lsa_link*l;if(w->type==OSPF_VERTEX_ROUTER)lsa_type=LSA_LINK_T
YPE_POINTOPOINT;if(prev_link==NULL)p=((uint8_t*)v->lsa)+OSPF_LSA_HEADER_SIZE+4;e
lse{p=(uint8_t*)prev_link;p+=(OSPF_ROUTER_LSA_LINK_SIZE+(prev_link->m[0].tos_cou
nt*OSPF_ROUTER_LSA_TOS_SIZE));}lim=((uint8_t*)v->lsa)+ntohs(v->lsa->length);whil
e(p<lim){l=(structrouter_lsa_link*)p;p+=(OSPF_ROUTER_LSA_LINK_SIZE+(l->m[0].tos_
count*OSPF_ROUTER_LSA_TOS_SIZE));if(l->m[0].type!=lsa_type)continue;if(IPV4_ADDR
_SAME(&l->link_id,&w->id))returnl;}returnNULL;}staticvoidospf_spf_flush_parents(
structvertex*w){structvertex_parent*vp;structlistnode*ln,*nn;/*deletetheexisting
nexthops*/for(ALL_LIST_ELEMENTS(w->parents,ln,nn,vp)){list_delete_node(w->parent
s,ln);vertex_parent_free(vp);}}/**Considersuppliednext-hopforinclusiontothesuppl
iedlistof*equal-costnext-hops,adjustlistasneccessary.*/staticvoidospf_spf_add_pa
rent(structvertex*v,structvertex*w,structvertex_nexthop*newhop,unsignedintdistan
ce){structvertex_parent*vp,*wp;structlistnode*node;/*wemusthaveanewhop,andadista
nce*/assert(v&&w&&newhop);assert(distance);/*IFFwhasalreadybeenassignedadistance
,thenweshouldn'tget*here*unlesscallershavedeterminedV(l)->Wisshortest/equal-shor
test*path(0isaspecialcasedistance(nodistanceyetassigned)).*/if(w->distance)asser
t(distance<=w->distance);elsew->distance=distance;if(IS_DEBUG_OSPF_EVENT){charbu
f[2][INET_ADDRSTRLEN];zlog_debug("%s:Adding%sasparentof%s",__func__,inet_ntop(AF
_INET,&v->lsa->id,buf[0],sizeof(buf[0])),inet_ntop(AF_INET,&w->lsa->id,buf[1],si
zeof(buf[1])));}/*Addingparentforanew,betterpath:flushexistingparentsfromW.*/if(
distance<w->distance){if(IS_DEBUG_OSPF_EVENT)zlog_debug("%s:distance%dbetterthan
%d,flushingexistingparents",__func__,distance,w->distance);ospf_spf_flush_parent
s(w);w->distance=distance;}/*newparentis<=existingparents,addittoparentlist(ifne
xthop*notonparentlist)*/for(ALL_LIST_ELEMENTS_RO(w->parents,node,wp)){if(memcmp(
newhop,wp->nexthop,sizeof(*newhop))==0){if(IS_DEBUG_OSPF_EVENT)zlog_debug("%s:..
.nexthopalreadyonparentlist,skippingadd",__func__);return;}}vp=vertex_parent_new
(v,ospf_lsa_has_link(w->lsa,v->lsa),newhop);listnode_add(w->parents,vp);return;}
/*16.1.1.CalculatenexthopfromrootthroughV(parent)to*vertexW(destination),withgiv
endistancefromroot->W.**ThelinkmustbesuppliedifVistherootvertex.Inallothercases*
itmaybeNULL.**Notethatthisfunctionmayfail,hencethestateofthedestination*vertex,W
,should/not/bemodifiedinadependentmanneruntil*thisfunctionreturns.Thisfunctionwi
llupdatetheWvertexwiththe*provideddistanceasappropriate.*/staticunsignedintospf_
nexthop_calculation(structospf_area*area,structvertex*v,structvertex*w,structrou
ter_lsa_link*l,unsignedintdistance,intlsa_pos){structlistnode*node,*nnode;struct
vertex_nexthop*nh;structvertex_parent*vp;structospf_interface*oi=NULL;unsignedin
tadded=0;charbuf1[BUFSIZ];charbuf2[BUFSIZ];if(IS_DEBUG_OSPF_EVENT){zlog_debug("o
spf_nexthop_calculation():Start");ospf_vertex_dump("V(parent):",v,1,1);ospf_vert
ex_dump("W(dest):",w,1,1);zlog_debug("V->Wdistance:%d",distance);}if(v==area->sp
f){/*16.1.1para4.Inthefirstcase,theparentvertex(V)istheroot(thecalculatingrouter
itself).Thismeansthatthedestinationiseitheradirectlyconnectednetworkordirectlyco
nnectedrouter.TheoutgoinginterfaceinthiscaseissimplytheOSPFinterfaceconnectingto
thedestinationnetwork/router.*//*we*must*besuppliedwiththelinkdata*/assert(l!=NU
LL);oi=ospf_if_lookup_by_lsa_pos(area,lsa_pos);if(!oi){zlog_debug("%s:OInotfound
inLSA:lsa_pos:%dlink_id:%slink_data:%s",__func__,lsa_pos,inet_ntop(AF_INET,&l->l
ink_id,buf1,BUFSIZ),inet_ntop(AF_INET,&l->link_data,buf2,BUFSIZ));return0;}if(IS
_DEBUG_OSPF_EVENT){zlog_debug("%s:consideringlink:%s""type:%dlink_id:%slink_data
:%s",__func__,oi->ifp->name,l->m[0].type,inet_ntop(AF_INET,&l->link_id,buf1,BUFS
IZ),inet_ntop(AF_INET,&l->link_data,buf2,BUFSIZ));}if(w->type==OSPF_VERTEX_ROUTE
R){/*lisalinkfromvtow*l2willbelinkfromwtov*/structrouter_lsa_link*l2=NULL;if(l->
m[0].type==LSA_LINK_TYPE_POINTOPOINT){structin_addrnexthop={.s_addr=0};/*Ifthede
stinationisarouterwhichconnectstothecalculatingrouterviaaPoint-to-MultiPointnetw
ork,thedestination'snexthopIPaddress(es)canbedeterminedbyexaminingthedestination
'srouter-LSA:eachlinkpointingbacktothecalculatingrouterandhavingaLinkDatafieldbe
longingtothePoint-to-MultiPointnetworkprovidesanIPaddressofthenexthoprouter.Atth
ispointlisalinkfromVtoW,andVistheroot("us").Ifitisapoint-to-multipointinterface,
thenlookthroughthelinksintheoppositedirection(WtoV).Ifanyofthemhaveanaddressthat
landswithinthesubnetdeclaredbythePtMPlink,thenthatlinkisaconstituentofthePtMPlin
k,anditsaddressisanexthopaddressforV.*/if(oi->type==OSPF_IFTYPE_POINTOPOINT){/*H
avingnexthop=0istempting,butNOTacceptable.ItbreaksAS-Externalrouteswithaforwardi
ngaddress,sinceospf_ase_complete_direct_routes()willmistakenlyassumewe'vereached
thelasthopandshouldplacetheforwardingaddressasnexthop.Also,usersmayconfiguremult
i-accesslinksinp2pmode,soweneedtheIPtoARPthenexthop.*/structospf_neighbor*nbr_w;
nbr_w=ospf_nbr_lookup_by_routerid(oi->nbrs,&l->link_id);if(nbr_w!=NULL){added=1;
nexthop=nbr_w->src;}}elseif(oi->type==OSPF_IFTYPE_POINTOMULTIPOINT){structprefix
_ipv4la;la.family=AF_INET;la.prefixlen=oi->address->prefixlen;/*VlinkstoWonPtMPi
nterface-findtheinterfaceaddressonW*/while((l2=ospf_get_next_link(w,v,l2))){la.p
refix=l2->link_data;if(prefix_cmp((structprefix*)&la,oi->address)!=0)continue;/*
link_dataisonourPtMP*network*/added=1;nexthop=l2->link_data;break;}}if(added){/*
foundallnecessaryinfotobuild*nexthop*/nh=vertex_nexthop_new();nh->oi=oi;nh->rout
er=nexthop;ospf_spf_add_parent(v,w,nh,distance);return1;}elsezlog_info("%s:could
notdeterminenexthopforlink%s",__func__,oi->ifp->name);}/*endpoint-to-pointlinkfr
omVtoW*/elseif(l->m[0].type==LSA_LINK_TYPE_VIRTUALLINK){structospf_vl_data*vl_da
ta;/*VLinkimplementationlimitations:*a)vl_datacanonlyreferenceonenexthop,so*noEC
MP*tobackbonethroughVLinks.Though*transit-area*summariesmaybeconsidered,andthose
can*beECMP.*b)Wecanonlyuse/one/VLink,evenif*multipleones*existthisrouterthroughm
ultiple*transit-areas.*/vl_data=ospf_vl_lookup(area->ospf,NULL,l->link_id);if(vl
_data&&CHECK_FLAG(vl_data->flags,OSPF_VL_FLAG_APPROVED)){nh=vertex_nexthop_new()
;nh->oi=vl_data->nexthop.oi;nh->router=vl_data->nexthop.router;ospf_spf_add_pare
nt(v,w,nh,distance);return1;}elsezlog_info("ospf_nexthop_calculation():""vl_data
forVLlinknotfound");}/*endvirtual-linkfromVtoW*/return0;}/*endWisaRoutervertex*/
else{assert(w->type==OSPF_VERTEX_NETWORK);nh=vertex_nexthop_new();nh->oi=oi;nh->
router.s_addr=0;/*Nexthopnotrequired*/ospf_spf_add_parent(v,w,nh,distance);retur
n1;}}/*endVistheroot*//*CheckifW'sparentisanetworkconnectedtoroot.*/elseif(v->ty
pe==OSPF_VERTEX_NETWORK){/*SeeifanyofV'sparentsaretheroot.*/for(ALL_LIST_ELEMENT
S(v->parents,node,nnode,vp)){if(vp->parent==area->spf)/*connectstoroot?*/{/*16.1
.1para5....theparentvertexisa*networkthat*directlyconnectsthecalculatingrouterto
*thedestination*router.Thelistofnexthopsisthen*determinedby*examiningthedestinat
ion'srouter-LSA...*/assert(w->type==OSPF_VERTEX_ROUTER);while((l=ospf_get_next_l
ink(w,v,l))){/*...Foreachlinkintherouter-LSA*thatpointsbacktothe*parentnetwork,t
helink'sLinkData*fieldprovidestheIP*addressofanexthoprouter.The*outgoinginterfac
eto*usecanthenbederivedfromthenext*hopIPaddress(or*itcanbeinheritedfromtheparent
*network).*/nh=vertex_nexthop_new();nh->oi=vp->nexthop->oi;nh->router=l->link_da
ta;added=1;ospf_spf_add_parent(v,w,nh,distance);}/*Notelackofreturnisdeliberate.
Seenext*comment.*/}}/*NB:Thiscodeisnon-trivial.**E.g.itisnotenoughtoknowthatVcon
nectstotheroot.It*is*alsoimportantthatthewhileabove,loopingthroughall*linksfrom*
W->Vfoundatleastonelink,sothatweknowthereis*bi-directionalconnectivitybetweenVan
dW(whichneednot*bethe*case,e.g.whenOSPFhasnotyetconvergedfully).*Otherwise,if*we
/always/returnhere,withouthavingcheckedthat*root->V->-W*actuallyresultedinavalid
nexthopbeingcreated,thenwe*wewill*preventSPFfromfinding/usinghighercostpaths.**I
tisimportant,ifroot->V->Whasnotbeenadded,thatwe*continue*throughtotheintervening
-routernexthopcodebelow.Soas*to*ensureotherpathstoVmaybeused.Thisavoidsunnecessa
ry*blackholeswhileOSPFisconvergening.**I.e.wemayhavearrivedatthisfunction,examin
ingV->W,*via*workablepathsotherthanroot->V,andit'simportantto*avoid*getting"conf
used"bynon-workingroot->V->Wpath-it's*important*to*not*losetheworkingnon-rootpat
hs,justbecauseofa*non-viableroot->V->W.**Seealsobug#330(requiredreading!),and:**
http://blogs.oracle.com/paulj/entry/the_difference_a_line_makes*/if(added)return
added;}/*16.1.1para4.Ifthereisatleastoneinterveningrouterinthe*currentshortestpa
thbetweenthedestinationandtheroot,the*destinationsimplyinheritsthesetofnexthopsf
romthe*parent.*/if(IS_DEBUG_OSPF_EVENT)zlog_debug("%s:Interveningrouters,addingp
arent(s)",__func__);for(ALL_LIST_ELEMENTS(v->parents,node,nnode,vp)){added=1;osp
f_spf_add_parent(v,w,vp->nexthop,distance);}returnadded;}/*RFC2328Section16.1(2)
.*visontheSPFtree.Examinethelinksinv'sLSA.Updatethelist*ofcandidateswithanyverti
cesnotalreadyonthelist.Ifalower-cost*pathisfoundtoavertexalreadyonthecandidateli
st,storethenewcost.*/staticvoidospf_spf_next(structvertex*v,structospf*ospf,stru
ctospf_area*area,structpqueue*candidate){structospf_lsa*w_lsa=NULL;uint8_t*p;uin
t8_t*lim;structrouter_lsa_link*l=NULL;structin_addr*r;inttype=0,lsa_pos=-1,lsa_p
os_next=0;/*Ifthisisarouter-LSA,andbitVoftherouter-LSA(seeSectionA.4.2:RFC2328)i
sset,setAreaA'sTransitCapabilitytoTRUE.*/if(v->type==OSPF_VERTEX_ROUTER){if(IS_R
OUTER_LSA_VIRTUAL((structrouter_lsa*)v->lsa))area->transit=OSPF_TRANSIT_TRUE;}if
(IS_DEBUG_OSPF_EVENT)zlog_debug("%s:Nextvertexof%svertex%s",__func__,v->type==OS
PF_VERTEX_ROUTER?"Router":"Network",inet_ntoa(v->lsa->id));p=((uint8_t*)v->lsa)+
OSPF_LSA_HEADER_SIZE+4;lim=((uint8_t*)v->lsa)+ntohs(v->lsa->length);while(p<lim)
{structvertex*w;unsignedintdistance;/*IncaseofVisRouter-LSA.*/if(v->lsa->type==O
SPF_ROUTER_LSA){l=(structrouter_lsa_link*)p;lsa_pos=lsa_pos_next;/*LSAlinkpositi
on*/lsa_pos_next++;p+=(OSPF_ROUTER_LSA_LINK_SIZE+(l->m[0].tos_count*OSPF_ROUTER_
LSA_TOS_SIZE));/*(a)Ifthisisalinktoastubnetwork,examinethenextlinkinV'sLSA.Links
tostubnetworkswillbeconsideredinthesecondstageoftheshortestpathcalculation.*/if(
(type=l->m[0].type)==LSA_LINK_TYPE_STUB)continue;/*(b)Otherwise,Wisatransitverte
x(routerortransitnetwork).LookupthevertexW'sLSA(router-LSAornetwork-LSA)inAreaA'
slinkstatedatabase.*/switch(type){caseLSA_LINK_TYPE_POINTOPOINT:caseLSA_LINK_TYP
E_VIRTUALLINK:if(type==LSA_LINK_TYPE_VIRTUALLINK){if(IS_DEBUG_OSPF_EVENT)zlog_de
bug("lookingupLSAthroughVL:%s",inet_ntoa(l->link_id));}w_lsa=ospf_lsa_lookup(osp
f,area,OSPF_ROUTER_LSA,l->link_id,l->link_id);if(w_lsa){if(IS_DEBUG_OSPF_EVENT)z
log_debug("foundRouterLSA%s",inet_ntoa(l->link_id));}break;caseLSA_LINK_TYPE_TRA
NSIT:if(IS_DEBUG_OSPF_EVENT)zlog_debug("LookingupNetworkLSA,ID:%s",inet_ntoa(l->
link_id));w_lsa=ospf_lsa_lookup_by_id(area,OSPF_NETWORK_LSA,l->link_id);if(w_lsa
)if(IS_DEBUG_OSPF_EVENT)zlog_debug("foundtheLSA");break;default:zlog_warn("Inval
idLSAlinktype%d",type);continue;}}else{/*IncaseofVisNetwork-LSA.*/r=(structin_ad
dr*)p;p+=sizeof(structin_addr);/*LookupthevertexW'sLSA.*/w_lsa=ospf_lsa_lookup_b
y_id(area,OSPF_ROUTER_LSA,*r);if(w_lsa){if(IS_DEBUG_OSPF_EVENT)zlog_debug("found
RouterLSA%s",inet_ntoa(w_lsa->data->id));}}/*(bcont.)IftheLSAdoesnotexist,oritsL
SageisequaltoMaxAge,oritdoesnothavealinkbacktovertexV,examinethenextlinkinV'sLSA
.[23]*/if(w_lsa==NULL){if(IS_DEBUG_OSPF_EVENT)zlog_debug("NoLSAfound");continue;
}if(IS_LSA_MAXAGE(w_lsa)){if(IS_DEBUG_OSPF_EVENT)zlog_debug("LSAisMaxAge");conti
nue;}if(ospf_lsa_has_link(w_lsa->data,v->lsa)<0){if(IS_DEBUG_OSPF_EVENT)zlog_deb
ug("TheLSAdoesn'thavealinkback");continue;}/*(c)IfvertexWisalreadyontheshortest-
pathtree,examinethenextlinkintheLSA.*/if(w_lsa->stat==LSA_SPF_IN_SPFTREE){if(IS_
DEBUG_OSPF_EVENT)zlog_debug("TheLSAisalreadyinSPF");continue;}/*(d)Calculatethel
inkstatecostDoftheresultingpathfromtheroottovertexW.Disequaltothesumofthelinksta
tecostofthe(alreadycalculated)shortestpathtovertexVandtheadvertisedcostofthelink
betweenverticesVandW.IfDis:*//*calculatelinkcostD.*/if(v->lsa->type==OSPF_ROUTER
_LSA)distance=v->distance+ntohs(l->m[0].metric);else/*visnotaRouter-LSA*/distanc
e=v->distance;/*IstherealreadyvertexWincandidatelist?*/if(w_lsa->stat==LSA_SPF_N
OT_EXPLORED){/*preparevertexW.*/w=ospf_vertex_new(w_lsa);/*CalculatenexthoptoW.*
/if(ospf_nexthop_calculation(area,v,w,l,distance,lsa_pos))pqueue_enqueue(w,candi
date);elseif(IS_DEBUG_OSPF_EVENT)zlog_debug("NexthopCalcfailed");}elseif(w_lsa->
stat>=0){/*Getthevertexfromcandidates.*/w=candidate->array[w_lsa->stat];/*ifDisg
reaterthan.*/if(w->distance<distance){continue;}/*equalto.*/elseif(w->distance==
distance){/*Foundanequal-costpathtoW.*CalculatenexthopoftoWfromV.*/ospf_nexthop_
calculation(area,v,w,l,distance,lsa_pos);}/*lessthan.*/else{/*Foundalower-costpa
thtoW.*nexthop_calculationisconditional,ifit*finds*validnexthopitwillcallspf_add
_parents,*which*willflushtheoldparents*/if(ospf_nexthop_calculation(area,v,w,l,d
istance,lsa_pos))/*Decreasethekeyofthenodeinthe*heap.*trickle-sortituptowardsroo
t,just*incasethis*nodeshouldnowbethenewrootdue*thecostchange.*(nextpqueu_{de,en}
queuewillfully*re-heapthequeue).*/trickle_up(w_lsa->stat,candidate);}}/*endWisal
readyonthecandidatelist*/}/*endloopoverthelinksinV'sLSA*/}staticvoidospf_spf_dum
p(structvertex*v,inti){structlistnode*cnode;structlistnode*nnode;structvertex_pa
rent*parent;if(v->type==OSPF_VERTEX_ROUTER){if(IS_DEBUG_OSPF_EVENT)zlog_debug("S
PFResult:%d[R]%s",i,inet_ntoa(v->lsa->id));}else{structnetwork_lsa*lsa=(structne
twork_lsa*)v->lsa;if(IS_DEBUG_OSPF_EVENT)zlog_debug("SPFResult:%d[N]%s/%d",i,ine
t_ntoa(v->lsa->id),ip_masklen(lsa->mask));}if(IS_DEBUG_OSPF_EVENT)for(ALL_LIST_E
LEMENTS_RO(v->parents,nnode,parent)){zlog_debug("nexthop%p%s%s",(void*)parent->n
exthop,inet_ntoa(parent->nexthop->router),parent->nexthop->oi?IF_NAME(parent->ne
xthop->oi):"NULL");}i++;for(ALL_LIST_ELEMENTS_RO(v->children,cnode,v))ospf_spf_d
ump(v,i);}/*SecondstageofSPFcalculation.*/staticvoidospf_spf_process_stubs(struc
tospf_area*area,structvertex*v,structroute_table*rt,intparent_is_root){structlis
tnode*cnode,*cnnode;structvertex*child;if(IS_DEBUG_OSPF_EVENT)zlog_debug("ospf_p
rocess_stub():processingstubsforarea%s",inet_ntoa(area->area_id));if(v->type==OS
PF_VERTEX_ROUTER){uint8_t*p;uint8_t*lim;structrouter_lsa_link*l;structrouter_lsa
*rlsa;intlsa_pos=0;if(IS_DEBUG_OSPF_EVENT)zlog_debug("ospf_process_stubs():proce
ssingrouterLSA,id:%s",inet_ntoa(v->lsa->id));rlsa=(structrouter_lsa*)v->lsa;if(I
S_DEBUG_OSPF_EVENT)zlog_debug("ospf_process_stubs():wehave%dlinkstoprocess",ntoh
s(rlsa->links));p=((uint8_t*)v->lsa)+OSPF_LSA_HEADER_SIZE+4;lim=((uint8_t*)v->ls
a)+ntohs(v->lsa->length);while(p<lim){l=(structrouter_lsa_link*)p;p+=(OSPF_ROUTE
R_LSA_LINK_SIZE+(l->m[0].tos_count*OSPF_ROUTER_LSA_TOS_SIZE));if(l->m[0].type==L
SA_LINK_TYPE_STUB)ospf_intra_add_stub(rt,l,v,area,parent_is_root,lsa_pos);lsa_po
s++;}}ospf_vertex_dump("ospf_process_stubs():afterexamininglinks:",v,1,1);for(AL
L_LIST_ELEMENTS(v->children,cnode,cnnode,child)){if(CHECK_FLAG(child->flags,OSPF
_VERTEX_PROCESSED))continue;/*thefirstlevelofroutersconnectedtotheroot*shouldhav
e'parent_is_root'set,includingthose*connectedviaanetworkvertex.*/if(area->spf==v
)parent_is_root=1;elseif(v->type==OSPF_VERTEX_ROUTER)parent_is_root=0;ospf_spf_p
rocess_stubs(area,child,rt,parent_is_root);SET_FLAG(child->flags,OSPF_VERTEX_PRO
CESSED);}}voidospf_rtrs_free(structroute_table*rtrs){structroute_node*rn;structl
ist*or_list;structospf_route*or;structlistnode*node,*nnode;if(IS_DEBUG_OSPF_EVEN
T)zlog_debug("Route:RouterRoutingTablefree");for(rn=route_top(rtrs);rn;rn=route_
next(rn))if((or_list=rn->info)!=NULL){for(ALL_LIST_ELEMENTS(or_list,node,nnode,o
r))ospf_route_free(or);list_delete_and_null(&or_list);/*Unlockthenode.*/rn->info
=NULL;route_unlock_node(rn);}route_table_finish(rtrs);}#if0staticvoidospf_rtrs_p
rint(structroute_table*rtrs){structroute_node*rn;structlist*or_list;structlistno
de*ln;structlistnode*pnode;structospf_route*or;structospf_path*path;charbuf1[BUF
SIZ];charbuf2[BUFSIZ];if(IS_DEBUG_OSPF_EVENT)zlog_debug("ospf_rtrs_print()start"
);for(rn=route_top(rtrs);rn;rn=route_next(rn))if((or_list=rn->info)!=NULL)for(AL
L_LIST_ELEMENTS_RO(or_list,ln,or)){switch(or->path_type){caseOSPF_PATH_INTRA_ARE
A:if(IS_DEBUG_OSPF_EVENT)zlog_debug("%s[%d]area:%s",inet_ntop(AF_INET,&or->id,bu
f1,BUFSIZ),or->cost,inet_ntop(AF_INET,&or->u.std.area_id,buf2,BUFSIZ));break;cas
eOSPF_PATH_INTER_AREA:if(IS_DEBUG_OSPF_EVENT)zlog_debug("%sIA[%d]area:%s",inet_n
top(AF_INET,&or->id,buf1,BUFSIZ),or->cost,inet_ntop(AF_INET,&or->u.std.area_id,b
uf2,BUFSIZ));break;default:break;}for(ALL_LIST_ELEMENTS_RO(or->paths,pnode,path)
){if(path->nexthop.s_addr==0){if(IS_DEBUG_OSPF_EVENT)zlog_debug("directlyattache
dto%s\r\n",ifindex2ifname(path->ifindex),VRF_DEFAULT);}else{if(IS_DEBUG_OSPF_EVE
NT)zlog_debug("via%s,%s\r\n",inet_ntoa(path->nexthop),ifindex2ifname(path->ifind
ex),VRF_DEFAULT);}}}zlog_debug("ospf_rtrs_print()end");}#endif/*Calculatingthesh
ortest-pathtreeforanarea.*/staticvoidospf_spf_calculate(structospf*ospf,structos
pf_area*area,structroute_table*new_table,structroute_table*new_rtrs){structpqueu
e*candidate;structvertex*v;if(IS_DEBUG_OSPF_EVENT){zlog_debug("ospf_spf_calculat
e:Start");zlog_debug("ospf_spf_calculate:runningDijkstraforarea%s",inet_ntoa(are
a->area_id));}/*Checkrouter-lsa-self.Ifself-router-lsaisnotyetallocated,returnth
isarea'scalculation.*/if(!area->router_lsa_self){if(IS_DEBUG_OSPF_EVENT)zlog_deb
ug("ospf_spf_calculate:""Skiparea%s'scalculationduetoemptyrouter_lsa_self",inet_
ntoa(area->area_id));return;}/*RFC232816.1.(1).*//*Initializethealgorithm'sdatas
tructures.*//*ThisfunctionscansalltheLSAdatabaseandsetthestatfieldto*LSA_SPF_NOT
_EXPLORED.*/ospf_lsdb_clean_stat(area->lsdb);/*Createanewheapforthecandidates.*/
candidate=pqueue_create();candidate->cmp=cmp;candidate->update=update_stat;/*Ini
tializetheshortest-pathtreetoonlytheroot(whichistherouterdoingthecalculation).*/
ospf_spf_init(area);v=area->spf;/*SetLSApositiontoLSA_SPF_IN_SPFTREE.Thisvertexi
stherootof*the*spanningtree.*/*(v->stat)=LSA_SPF_IN_SPFTREE;/*SetAreaA'sTransitC
apabilitytoFALSE.*/area->transit=OSPF_TRANSIT_FALSE;area->shortcut_capability=1;
for(;;){/*RFC232816.1.(2).*/ospf_spf_next(v,ospf,area,candidate);/*RFC232816.1.(
3).*//*Ifatthisstepthecandidatelistisempty,theshortest-pathtree(oftransitvertice
s)hasbeencompletelybuiltandthisstageoftheprocedureterminates.*/if(candidate->siz
e==0)break;/*Otherwise,choosethevertexbelongingtothecandidatelistthatisclosestto
theroot,andaddittotheshortest-pathtree(removingitfromthecandidatelistintheproces
s).*//*Extractfromthecandidatesthenodewiththelowerkey.*/v=(structvertex*)pqueue_
dequeue(candidate);/*Updatestatfieldinvertex.*/*(v->stat)=LSA_SPF_IN_SPFTREE;osp
f_vertex_add_parent(v);/*RFC232816.1.(4).*/if(v->type==OSPF_VERTEX_ROUTER)ospf_i
ntra_add_router(new_rtrs,v,area);elseospf_intra_add_transit(new_table,v,area);/*
RFC232816.1.(5).*//*IteratethealgorithmbyreturningtoStep2.*/}/*endloopuntilnomor
ecandidatevertices*/if(IS_DEBUG_OSPF_EVENT){ospf_spf_dump(area->spf,0);ospf_rout
e_table_dump(new_table);}/*SecondstageofSPFcalculationprocedure's*/ospf_spf_proc
ess_stubs(area,area->spf,new_table,0);/*Freecandidatequeue.*/pqueue_delete(candi
date);ospf_vertex_dump(__func__,area->spf,0,1);/*Freenexthopinformation,canonica
lversionsofwhichareattached*thefirstlevelofrouterverticesattachedtotherootvertex
,see*ospf_nexthop_calculation.*/ospf_canonical_nexthops_free(area->spf);/*Increm
entSPFCalculationCounter.*/area->spf_calculation++;monotime(&area->ospf->ts_spf)
;area->ts_spf=area->ospf->ts_spf;if(IS_DEBUG_OSPF_EVENT)zlog_debug("ospf_spf_cal
culate:Stop.%zdvertices",mtype_stats_alloc(MTYPE_OSPF_VERTEX));/*FreeSPFvertices
,butnotthelist.Listhasospf_vertex_free*asdeconstructor.*/list_delete_all_node(&v
ertex_list);}/*TimerforSPFcalculation.*/staticintospf_spf_calculate_timer(struct
thread*thread){structospf*ospf=THREAD_ARG(thread);structroute_table*new_table,*n
ew_rtrs;structospf_area*area;structlistnode*node,*nnode;structtimevalstart_time,
spf_start_time;intareas_processed=0;unsignedlongia_time,prune_time,rt_time;unsig
nedlongabr_time,total_spf_time,spf_time;charrbuf[32];/*reason_buf*/if(IS_DEBUG_O
SPF_EVENT)zlog_debug("SPF:Timer(SPFcalculationexpire)");ospf->t_spf_calc=NULL;mo
notime(&spf_start_time);/*Allocatenewtabletree.*/new_table=route_table_init();ne
w_rtrs=route_table_init();ospf_vl_unapprove(ospf);/*CalculateSPFforeacharea.*/fo
r(ALL_LIST_ELEMENTS(ospf->areas,node,nnode,area)){/*Dobackbonelast,soastofirstdi
scoverintra-areapaths*foranyback-bonevirtual-links*/if(ospf->backbone&&ospf->bac
kbone==area)continue;ospf_spf_calculate(ospf,area,new_table,new_rtrs);areas_proc
essed++;}/*SPFforbackbone,ifrequired*/if(ospf->backbone){ospf_spf_calculate(ospf
,ospf->backbone,new_table,new_rtrs);areas_processed++;}spf_time=monotime_since(&
spf_start_time,NULL);ospf_vl_shut_unapproved(ospf);monotime(&start_time);ospf_ia
_routing(ospf,new_table,new_rtrs);ia_time=monotime_since(&start_time,NULL);monot
ime(&start_time);ospf_prune_unreachable_networks(new_table);ospf_prune_unreachab
le_routers(new_rtrs);prune_time=monotime_since(&start_time,NULL);/*AS-external-L
SAcalculationshouldnotbeperformedhere.*//*IfnewRouterRouteisinstalled,thenschedu
lere-calculateExternalroutes.*/if(1)ospf_ase_calculate_schedule(ospf);ospf_ase_c
alculate_timer_add(ospf);if(IS_DEBUG_OSPF_EVENT)zlog_debug("%s:ospfinstallnewrou
te,vrf%sid%unew_tablecount%lu",__PRETTY_FUNCTION__,ospf_vrf_id_to_name(ospf->vrf
_id),ospf->vrf_id,new_table->count);/*Updateroutingtable.*/monotime(&start_time)
;ospf_route_install(ospf,new_table);rt_time=monotime_since(&start_time,NULL);/*U
pdateABR/ASBRroutingtable*/if(ospf->old_rtrs){/*old_rtrs'snodeholdslinkedlistofo
spf_route.--kunihiro.*//*ospf_route_delete(ospf->old_rtrs);*/ospf_rtrs_free(ospf
->old_rtrs);}ospf->old_rtrs=ospf->new_rtrs;ospf->new_rtrs=new_rtrs;monotime(&sta
rt_time);if(IS_OSPF_ABR(ospf))ospf_abr_task(ospf);abr_time=monotime_since(&start
_time,NULL);/*ScheduleSegmentRoutingupdate*/ospf_sr_update_timer_add(ospf);total
_spf_time=monotime_since(&spf_start_time,&ospf->ts_spf_duration);rbuf[0]='\0';if
(spf_reason_flags){if(spf_reason_flags&SPF_FLAG_ROUTER_LSA_INSTALL)strncat(rbuf,
"R,",sizeof(rbuf)-strlen(rbuf)-1);if(spf_reason_flags&SPF_FLAG_NETWORK_LSA_INSTA
LL)strncat(rbuf,"N,",sizeof(rbuf)-strlen(rbuf)-1);if(spf_reason_flags&SPF_FLAG_S
UMMARY_LSA_INSTALL)strncat(rbuf,"S,",sizeof(rbuf)-strlen(rbuf)-1);if(spf_reason_
flags&SPF_FLAG_ASBR_SUMMARY_LSA_INSTALL)strncat(rbuf,"AS,",sizeof(rbuf)-strlen(r
buf)-1);if(spf_reason_flags&SPF_FLAG_ABR_STATUS_CHANGE)strncat(rbuf,"ABR,",sizeo
f(rbuf)-strlen(rbuf)-1);if(spf_reason_flags&SPF_FLAG_ASBR_STATUS_CHANGE)strncat(
rbuf,"ASBR,",sizeof(rbuf)-strlen(rbuf)-1);if(spf_reason_flags&SPF_FLAG_MAXAGE)st
rncat(rbuf,"M,",sizeof(rbuf)-strlen(rbuf)-1);size_trbuflen=strlen(rbuf);if(rbufl
en>=2)rbuf[rbuflen-2]='\0';/*skipthelast","*/elserbuf[0]='\0';}if(IS_DEBUG_OSPF_
EVENT){zlog_info("SPFProcessingTime(usecs):%ld",total_spf_time);zlog_info("\tSPF
Time:%ld",spf_time);zlog_info("\tInterArea:%ld",ia_time);zlog_info("\tPrune:%ld"
,prune_time);zlog_info("\tRouteInstall:%ld",rt_time);if(IS_OSPF_ABR(ospf))zlog_i
nfo("\tABR:%ld(%dareas)",abr_time,areas_processed);zlog_info("Reason(s)forSPF:%s
",rbuf);}ospf_clear_spf_reason_flags();return0;}/*AddscheduleforSPFcalculation.T
oavoidfrequenstSPFcalc,wesettimerforSPFcalc.*/voidospf_spf_calculate_schedule(st
ructospf*ospf,ospf_spf_reason_treason){unsignedlongdelay,elapsed,ht;if(IS_DEBUG_
OSPF_EVENT)zlog_debug("SPF:calculationtimerscheduled");/*OSPFinstancedoesnotexis
t.*/if(ospf==NULL)return;ospf_spf_set_reason(reason);/*SPFcalculationtimerisalre
adyscheduled.*/if(ospf->t_spf_calc){if(IS_DEBUG_OSPF_EVENT)zlog_debug("SPF:calcu
lationtimerisalreadyscheduled:%p",(void*)ospf->t_spf_calc);return;}elapsed=monot
ime_since(&ospf->ts_spf,NULL)/1000;ht=ospf->spf_holdtime*ospf->spf_hold_multipli
er;if(ht>ospf->spf_max_holdtime)ht=ospf->spf_max_holdtime;/*GetSPFcalculationdel
aytime.*/if(elapsed<ht){/*GotaneventwithintheholdtimeoflastSPF.Weneedto*increase
thehold_multiplier,ifit'snotalreadyat/past*maximumvalue,andwasn'talreadyincrease
d..*/if(ht<ospf->spf_max_holdtime)ospf->spf_hold_multiplier++;/*alwayshonourtheS
PFinitialdelay*/if((ht-elapsed)<ospf->spf_delay)delay=ospf->spf_delay;elsedelay=
ht-elapsed;}else{/*Eventispastrequiredhold-timeoflastSPF*/delay=ospf->spf_delay;
ospf->spf_hold_multiplier=1;}if(IS_DEBUG_OSPF_EVENT)zlog_debug("SPF:calculationt
imerdelay=%ldmsec",delay);ospf->t_spf_calc=NULL;thread_add_timer_msec(master,osp
f_spf_calculate_timer,ospf,delay,&ospf->t_spf_calc);}