/**Thisisanimplementationofrfc2370.*Copyright(C)2001KDDR&DLaboratories,Inc.*http
://www.kddlabs.co.jp/**ThisfileispartofGNUZebra.**GNUZebraisfreesoftware;youcanr
edistributeitand/ormodifyit*underthetermsoftheGNUGeneralPublicLicenseaspublished
bythe*FreeSoftwareFoundation;eitherversion2,or(atyouroption)any*laterversion.**G
NUZebraisdistributedinthehopethatitwillbeuseful,but*WITHOUTANYWARRANTY;withoutev
entheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*G
eneralPublicLicenseformoredetails.**YoushouldhavereceivedacopyoftheGNUGeneralPub
licLicensealong*withthisprogram;seethefileCOPYING;ifnot,writetotheFreeSoftware*F
oundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-1301USA*/#include<zebra.h>
#include"linklist.h"#include"prefix.h"#include"if.h"#include"table.h"#include"me
mory.h"#include"command.h"#include"vty.h"#include"stream.h"#include"log.h"#inclu
de"thread.h"#include"hash.h"#include"sockunion.h"/*forinet_aton()*/#include"ospf
d/ospfd.h"#include"ospfd/ospf_interface.h"#include"ospfd/ospf_ism.h"#include"osp
fd/ospf_asbr.h"#include"ospfd/ospf_lsa.h"#include"ospfd/ospf_lsdb.h"#include"osp
fd/ospf_neighbor.h"#include"ospfd/ospf_nsm.h"#include"ospfd/ospf_flood.h"#includ
e"ospfd/ospf_packet.h"#include"ospfd/ospf_spf.h"#include"ospfd/ospf_dump.h"#incl
ude"ospfd/ospf_route.h"#include"ospfd/ospf_ase.h"#include"ospfd/ospf_zebra.h"#in
clude"ospfd/ospf_te.h"#include"ospfd/ospf_sr.h"#include"ospfd/ospf_ri.h"#include
"ospfd/ospf_ext.h"DEFINE_MTYPE_STATIC(OSPFD,OSPF_OPAQUE_FUNCTAB,"OSPFopaquefunct
iontable")DEFINE_MTYPE_STATIC(OSPFD,OPAQUE_INFO_PER_TYPE,"OSPFopaqueper-typeinfo
")DEFINE_MTYPE_STATIC(OSPFD,OPAQUE_INFO_PER_ID,"OSPFopaqueper-IDinfo")/*--------
----------------------------------------------------------------**Followingsarei
nitialize/terminatefunctionsforOpaque-LSAshandling.*----------------------------
--------------------------------------------*/#ifdefSUPPORT_OSPF_APIintospf_apis
erver_init(void);voidospf_apiserver_term(void);/*Initapiserver?It'sdisabledbydef
ault.*/intospf_apiserver_enable;#endif/*SUPPORT_OSPF_API*/staticvoidospf_opaque_
register_vty(void);staticvoidospf_opaque_funclist_init(void);staticvoidospf_opaq
ue_funclist_term(void);staticvoidfree_opaque_info_per_type(void*val);staticvoidf
ree_opaque_info_per_id(void*val);staticvoidfree_opaque_info_owner(void*val);stat
icintospf_opaque_lsa_install_hook(structospf_lsa*lsa);staticintospf_opaque_lsa_d
elete_hook(structospf_lsa*lsa);voidospf_opaque_init(void){ospf_opaque_register_v
ty();ospf_opaque_funclist_init();if(ospf_mpls_te_init()!=0)exit(1);/*SegmentRout
inginit*/if(ospf_sr_init()!=0)exit(1);if(ospf_router_info_init()!=0)exit(1);if(o
spf_ext_init()!=0)exit(1);#ifdefSUPPORT_OSPF_APIif((ospf_apiserver_enable)&&(osp
f_apiserver_init()!=0))exit(1);#endif/*SUPPORT_OSPF_API*/return;}voidospf_opaque
_term(void){ospf_mpls_te_term();ospf_router_info_term();ospf_ext_term();ospf_sr_
term();#ifdefSUPPORT_OSPF_APIospf_apiserver_term();#endif/*SUPPORT_OSPF_API*/osp
f_opaque_funclist_term();return;}voidospf_opaque_finish(void){ospf_router_info_f
inish();ospf_ext_finish();ospf_sr_finish();}intospf_opaque_type9_lsa_init(struct
ospf_interface*oi){if(oi->opaque_lsa_self!=NULL)list_delete_and_null(&oi->opaque
_lsa_self);oi->opaque_lsa_self=list_new();oi->opaque_lsa_self->del=free_opaque_i
nfo_per_type;oi->t_opaque_lsa_self=NULL;return0;}voidospf_opaque_type9_lsa_term(
structospf_interface*oi){OSPF_TIMER_OFF(oi->t_opaque_lsa_self);if(oi->opaque_lsa
_self!=NULL)list_delete_and_null(&oi->opaque_lsa_self);oi->opaque_lsa_self=NULL;
return;}intospf_opaque_type10_lsa_init(structospf_area*area){if(area->opaque_lsa
_self!=NULL)list_delete_and_null(&area->opaque_lsa_self);area->opaque_lsa_self=l
ist_new();area->opaque_lsa_self->del=free_opaque_info_per_type;area->t_opaque_ls
a_self=NULL;#ifdefMONITOR_LSDB_CHANGEarea->lsdb->new_lsa_hook=ospf_opaque_lsa_in
stall_hook;area->lsdb->del_lsa_hook=ospf_opaque_lsa_delete_hook;#endif/*MONITOR_
LSDB_CHANGE*/return0;}voidospf_opaque_type10_lsa_term(structospf_area*area){#ifd
efMONITOR_LSDB_CHANGEarea->lsdb->new_lsa_hook=area->lsdb->del_lsa_hook=NULL;#end
if/*MONITOR_LSDB_CHANGE*/OSPF_TIMER_OFF(area->t_opaque_lsa_self);if(area->opaque
_lsa_self!=NULL)list_delete_and_null(&area->opaque_lsa_self);return;}intospf_opa
que_type11_lsa_init(structospf*top){if(top->opaque_lsa_self!=NULL)list_delete_an
d_null(&top->opaque_lsa_self);top->opaque_lsa_self=list_new();top->opaque_lsa_se
lf->del=free_opaque_info_per_type;top->t_opaque_lsa_self=NULL;#ifdefMONITOR_LSDB
_CHANGEtop->lsdb->new_lsa_hook=ospf_opaque_lsa_install_hook;top->lsdb->del_lsa_h
ook=ospf_opaque_lsa_delete_hook;#endif/*MONITOR_LSDB_CHANGE*/return0;}voidospf_o
paque_type11_lsa_term(structospf*top){#ifdefMONITOR_LSDB_CHANGEtop->lsdb->new_ls
a_hook=top->lsdb->del_lsa_hook=NULL;#endif/*MONITOR_LSDB_CHANGE*/OSPF_TIMER_OFF(
top->t_opaque_lsa_self);if(top->opaque_lsa_self!=NULL)list_delete_and_null(&top-
>opaque_lsa_self);return;}staticconstchar*ospf_opaque_type_name(uint8_topaque_ty
pe){constchar*name="Unknown";switch(opaque_type){caseOPAQUE_TYPE_WILDCARD:/*This
isaspecialassignment!*/name="Wildcard";break;caseOPAQUE_TYPE_TRAFFIC_ENGINEERING
_LSA:name="TrafficEngineeringLSA";break;caseOPAQUE_TYPE_SYCAMORE_OPTICAL_TOPOLOG
Y_DESC:name="Sycamoreopticaltopologydescription";break;caseOPAQUE_TYPE_GRACE_LSA
:name="Grace-LSA";break;caseOPAQUE_TYPE_INTER_AS_LSA:name="Inter-ASTE-v2LSA";bre
ak;caseOPAQUE_TYPE_ROUTER_INFORMATION_LSA:name="RouterInformationLSA";break;case
OPAQUE_TYPE_EXTENDED_PREFIX_LSA:name="ExtendedPrefixOpaqueLSA";break;caseOPAQUE_
TYPE_EXTENDED_LINK_LSA:name="ExtendedLinkOpaqueLSA";break;default:if(OPAQUE_TYPE
_RANGE_UNASSIGNED(opaque_type))name="Unassigned";else{uint32_tbigger_range=opaqu
e_type;/**Getaroundtype-limitswarning:comparisonisalways*trueduetolimitedrangeof
datatype*/if(OPAQUE_TYPE_RANGE_RESERVED(bigger_range))name="Private/Experimental
";}break;}returnname;}/*--------------------------------------------------------
----------------**Followingsaremanagementfunctionstostoreuserspecifiedcallbacks.
*------------------------------------------------------------------------*/struc
topaque_info_per_type;/*Forwarddeclaration.*/structospf_opaque_functab{uint8_top
aque_type;structopaque_info_per_type*oipt;int(*new_if_hook)(structinterface*ifp)
;int(*del_if_hook)(structinterface*ifp);void(*ism_change_hook)(structospf_interf
ace*oi,intold_status);void(*nsm_change_hook)(structospf_neighbor*nbr,intold_stat
us);void(*config_write_router)(structvty*vty);void(*config_write_if)(structvty*v
ty,structinterface*ifp);void(*config_write_debug)(structvty*vty);void(*show_opaq
ue_info)(structvty*vty,structospf_lsa*lsa);int(*lsa_originator)(void*arg);struct
ospf_lsa*(*lsa_refresher)(structospf_lsa*lsa);int(*new_lsa_hook)(structospf_lsa*
lsa);int(*del_lsa_hook)(structospf_lsa*lsa);};/*HandleLSA-9/10/11altogether.*/st
aticstructlist*ospf_opaque_wildcard_funclist;staticstructlist*ospf_opaque_type9_
funclist;staticstructlist*ospf_opaque_type10_funclist;staticstructlist*ospf_opaq
ue_type11_funclist;staticvoidospf_opaque_del_functab(void*val){XFREE(MTYPE_OSPF_
OPAQUE_FUNCTAB,val);return;}staticvoidospf_opaque_funclist_init(void){structlist
*funclist;funclist=ospf_opaque_wildcard_funclist=list_new();funclist->del=ospf_o
paque_del_functab;funclist=ospf_opaque_type9_funclist=list_new();funclist->del=o
spf_opaque_del_functab;funclist=ospf_opaque_type10_funclist=list_new();funclist-
>del=ospf_opaque_del_functab;funclist=ospf_opaque_type11_funclist=list_new();fun
clist->del=ospf_opaque_del_functab;return;}staticvoidospf_opaque_funclist_term(v
oid){structlist*funclist;funclist=ospf_opaque_wildcard_funclist;list_delete_and_
null(&funclist);funclist=ospf_opaque_type9_funclist;list_delete_and_null(&funcli
st);funclist=ospf_opaque_type10_funclist;list_delete_and_null(&funclist);funclis
t=ospf_opaque_type11_funclist;list_delete_and_null(&funclist);return;}staticstru
ctlist*ospf_get_opaque_funclist(uint8_tlsa_type){structlist*funclist=NULL;switch
(lsa_type){caseOPAQUE_TYPE_WILDCARD:/*XXX*Thisisanuglytricktohandletype-9/10/11L
SAaltogether.*Yes,"OPAQUE_TYPE_WILDCARD(value0)"isnotanLSA-type,nor*anofficially
assignedopaque-type.*Thoughitispossiblethatthevaluemightbeofficiallyused*inthefu
ture,weuseitinternallyasaspeciallabel,for*now.*/funclist=ospf_opaque_wildcard_fu
nclist;break;caseOSPF_OPAQUE_LINK_LSA:funclist=ospf_opaque_type9_funclist;break;
caseOSPF_OPAQUE_AREA_LSA:funclist=ospf_opaque_type10_funclist;break;caseOSPF_OPA
QUE_AS_LSA:funclist=ospf_opaque_type11_funclist;break;default:zlog_warn("ospf_ge
t_opaque_funclist:UnexpectedLSA-type(%u)",lsa_type);break;}returnfunclist;}/*XXX
:suchahugeargumentlistcan/not/behealthy...*/intospf_register_opaque_functab(uint
8_tlsa_type,uint8_topaque_type,int(*new_if_hook)(structinterface*ifp),int(*del_i
f_hook)(structinterface*ifp),void(*ism_change_hook)(structospf_interface*oi,into
ld_status),void(*nsm_change_hook)(structospf_neighbor*nbr,intold_status),void(*c
onfig_write_router)(structvty*vty),void(*config_write_if)(structvty*vty,structin
terface*ifp),void(*config_write_debug)(structvty*vty),void(*show_opaque_info)(st
ructvty*vty,structospf_lsa*lsa),int(*lsa_originator)(void*arg),structospf_lsa*(*
lsa_refresher)(structospf_lsa*lsa),int(*new_lsa_hook)(structospf_lsa*lsa),int(*d
el_lsa_hook)(structospf_lsa*lsa)){structlist*funclist;structospf_opaque_functab*
new;intrc=-1;if((funclist=ospf_get_opaque_funclist(lsa_type))==NULL){zlog_warn("
ospf_register_opaque_functab:Cannotgetfunclist""forType-%uLSAs?",lsa_type);gotoo
ut;}else{structlistnode*node,*nnode;structospf_opaque_functab*functab;for(ALL_LI
ST_ELEMENTS(funclist,node,nnode,functab))if(functab->opaque_type==opaque_type){z
log_warn("ospf_register_opaque_functab:Duplicatedentry?:""lsa_type(%u),opaque_ty
pe(%u)",lsa_type,opaque_type);gotoout;}}if((new=XCALLOC(MTYPE_OSPF_OPAQUE_FUNCTA
B,sizeof(structospf_opaque_functab)))==NULL){zlog_warn("ospf_register_opaque_fun
ctab:XMALLOC:%s",safe_strerror(errno));gotoout;}new->opaque_type=opaque_type;new
->oipt=NULL;new->new_if_hook=new_if_hook;new->del_if_hook=del_if_hook;new->ism_c
hange_hook=ism_change_hook;new->nsm_change_hook=nsm_change_hook;new->config_writ
e_router=config_write_router;new->config_write_if=config_write_if;new->config_wr
ite_debug=config_write_debug;new->show_opaque_info=show_opaque_info;new->lsa_ori
ginator=lsa_originator;new->lsa_refresher=lsa_refresher;new->new_lsa_hook=new_ls
a_hook;new->del_lsa_hook=del_lsa_hook;listnode_add(funclist,new);rc=0;out:return
rc;}voidospf_delete_opaque_functab(uint8_tlsa_type,uint8_topaque_type){structlis
t*funclist;structlistnode*node,*nnode;structospf_opaque_functab*functab;if((func
list=ospf_get_opaque_funclist(lsa_type))!=NULL)for(ALL_LIST_ELEMENTS(funclist,no
de,nnode,functab)){if(functab->opaque_type==opaque_type){/*Cleanupinternalcontro
linformation,ifit*stillremains.*/if(functab->oipt!=NULL){free_opaque_info_per_ty
pe(functab->oipt);free_opaque_info_owner(functab->oipt);}/*Dequeuelistnodeentryf
romthelist.*/listnode_delete(funclist,functab);/*Avoidmisjudgementinthenextlooku
p.*/if(listcount(funclist)==0)funclist->head=funclist->tail=NULL;XFREE(MTYPE_OSP
F_OPAQUE_FUNCTAB,functab);break;}}return;}staticstructospf_opaque_functab*ospf_o
paque_functab_lookup(structospf_lsa*lsa){structlist*funclist;structlistnode*node
;structospf_opaque_functab*functab;uint8_tkey=GET_OPAQUE_TYPE(ntohl(lsa->data->i
d.s_addr));if((funclist=ospf_get_opaque_funclist(lsa->data->type))!=NULL)for(ALL
_LIST_ELEMENTS_RO(funclist,node,functab))if(functab->opaque_type==key)returnfunc
tab;returnNULL;}/*--------------------------------------------------------------
----------**Followingsaremanagementfunctionsforself-originatedLSAentries.*------
------------------------------------------------------------------*//**Opaque-LS
Acontrolinformationperopaque-type.*SingleOpaque-Typemayhavemultipleinstances;eac
hofthemwillbe*identifiedbytheiropaque-id.*/structopaque_info_per_type{uint8_tlsa
_type;uint8_topaque_type;enum{PROC_NORMAL,PROC_SUSPEND}status;/**Threadfor(re-)o
riginationschedulingforthisopaque-type.**InitialoriginationofOpaque-LSAsiscontro
lledbygeneric*Opaque-LSAhandlingmodulesothatsameopaque-typeentriesare*calledalla
toncewhencertainconditionsaremet.*However,theremightbecasesthatsomeOpaque-LSAcli
entsneed*to(re-)originatetheirownOpaque-LSAsout-of-syncwithothers.*Thisthreadisp
reparedforthatspecificpurpose.*/structthread*t_opaque_lsa_self;/**Backpointertoa
n"owner"whichisLSA-typedependent.*type-9:structospf_interface*type-10:structospf
_area*type-11:structospf*/void*owner;/*Collectionofcallbackfunctionsforthisopaqu
e-type.*/structospf_opaque_functab*functab;/*ListofOpaque-LSAcontrolinformations
peropaque-id.*/structlist*id_list;};/*Opaque-LSAcontrolinformationperopaque-id.*
/structopaque_info_per_id{uint32_topaque_id;/*Threadforrefresh/flushschedulingfo
rthisopaque-type/id.*/structthread*t_opaque_lsa_self;/*BackpointertoOpaque-LSAco
ntrolinformationperopaque-type.*/structopaque_info_per_type*opqctl_type;/*Hereco
mesanactualOpaque-LSAentryforthisopaque-type/id.*/structospf_lsa*lsa;};staticstr
uctopaque_info_per_type*register_opaque_info_per_type(structospf_opaque_functab*
functab,structospf_lsa*new);staticstructopaque_info_per_type*lookup_opaque_info_
by_type(structospf_lsa*lsa);staticstructopaque_info_per_id*register_opaque_info_
per_id(structopaque_info_per_type*oipt,structospf_lsa*new);staticstructopaque_in
fo_per_id*lookup_opaque_info_by_id(structopaque_info_per_type*oipt,structospf_ls
a*lsa);staticstructopaque_info_per_id*register_opaque_lsa(structospf_lsa*new);st
aticstructopaque_info_per_type*register_opaque_info_per_type(structospf_opaque_f
unctab*functab,structospf_lsa*new){structospf*top;structopaque_info_per_type*oip
t;if((oipt=XCALLOC(MTYPE_OPAQUE_INFO_PER_TYPE,sizeof(structopaque_info_per_type)
))==NULL){zlog_warn("register_opaque_info_per_type:XMALLOC:%s",safe_strerror(err
no));gotoout;}switch(new->data->type){caseOSPF_OPAQUE_LINK_LSA:oipt->owner=new->
oi;listnode_add(new->oi->opaque_lsa_self,oipt);break;caseOSPF_OPAQUE_AREA_LSA:oi
pt->owner=new->area;listnode_add(new->area->opaque_lsa_self,oipt);break;caseOSPF
_OPAQUE_AS_LSA:top=ospf_lookup_by_vrf_id(new->vrf_id);if(new->area!=NULL&&(top=n
ew->area->ospf)==NULL){free_opaque_info_per_type((void*)oipt);free_opaque_info_o
wner(oipt);oipt=NULL;gotoout;/*Thiscasemaynotexist.*/}oipt->owner=top;listnode_a
dd(top->opaque_lsa_self,oipt);break;default:zlog_warn("register_opaque_info_per_
type:UnexpectedLSA-type(%u)",new->data->type);free_opaque_info_per_type((void*)o
ipt);free_opaque_info_owner(oipt);oipt=NULL;gotoout;/*Thiscasemaynotexist.*/}oip
t->lsa_type=new->data->type;oipt->opaque_type=GET_OPAQUE_TYPE(ntohl(new->data->i
d.s_addr));oipt->status=PROC_NORMAL;oipt->t_opaque_lsa_self=NULL;oipt->functab=f
unctab;functab->oipt=oipt;oipt->id_list=list_new();oipt->id_list->del=free_opaqu
e_info_per_id;out:returnoipt;}/*Remove"oipt"fromitsowner'sself-originatedLSAlist
.*/staticvoidfree_opaque_info_owner(void*val){structopaque_info_per_type*oipt=(s
tructopaque_info_per_type*)val;switch(oipt->lsa_type){caseOSPF_OPAQUE_LINK_LSA:{
structospf_interface*oi=(structospf_interface*)(oipt->owner);listnode_delete(oi-
>opaque_lsa_self,oipt);break;}caseOSPF_OPAQUE_AREA_LSA:{structospf_area*area=(st
ructospf_area*)(oipt->owner);listnode_delete(area->opaque_lsa_self,oipt);break;}
caseOSPF_OPAQUE_AS_LSA:{structospf*top=(structospf*)(oipt->owner);listnode_delet
e(top->opaque_lsa_self,oipt);break;}default:zlog_warn("free_opaque_info_owner:Un
expectedLSA-type(%u)",oipt->lsa_type);break;/*Thiscasemaynotexist.*/}}staticvoid
free_opaque_info_per_type(void*val){structopaque_info_per_type*oipt=(structopaqu
e_info_per_type*)val;structopaque_info_per_id*oipi;structospf_lsa*lsa;structlist
node*node,*nnode;/*Controlinformationperopaque-idmaystillexist.*/for(ALL_LIST_EL
EMENTS(oipt->id_list,node,nnode,oipi)){if((lsa=oipi->lsa)==NULL)continue;if(IS_L
SA_MAXAGE(lsa))continue;ospf_opaque_lsa_flush_schedule(lsa);}OSPF_TIMER_OFF(oipt
->t_opaque_lsa_self);list_delete_and_null(&oipt->id_list);XFREE(MTYPE_OPAQUE_INF
O_PER_TYPE,oipt);return;}staticstructopaque_info_per_type*lookup_opaque_info_by_
type(structospf_lsa*lsa){structospf*top;structospf_area*area;structospf_interfac
e*oi;structlist*listtop=NULL;structlistnode*node,*nnode;structopaque_info_per_ty
pe*oipt=NULL;uint8_tkey=GET_OPAQUE_TYPE(ntohl(lsa->data->id.s_addr));switch(lsa-
>data->type){caseOSPF_OPAQUE_LINK_LSA:if((oi=lsa->oi)!=NULL)listtop=oi->opaque_l
sa_self;elsezlog_warn("Type-9Opaque-LSA:ReferencetoOIismissing?");break;caseOSPF
_OPAQUE_AREA_LSA:if((area=lsa->area)!=NULL)listtop=area->opaque_lsa_self;elsezlo
g_warn("Type-10Opaque-LSA:ReferencetoAREAismissing?");break;caseOSPF_OPAQUE_AS_L
SA:top=ospf_lookup_by_vrf_id(lsa->vrf_id);if((area=lsa->area)!=NULL&&(top=area->
ospf)==NULL){zlog_warn("Type-11Opaque-LSA:ReferencetoOSPFismissing?");break;/*Un
likelytohappen.*/}listtop=top->opaque_lsa_self;break;default:zlog_warn("lookup_o
paque_info_by_type:UnexpectedLSA-type(%u)",lsa->data->type);break;}if(listtop!=N
ULL)for(ALL_LIST_ELEMENTS(listtop,node,nnode,oipt))if(oipt->opaque_type==key)ret
urnoipt;returnNULL;}staticstructopaque_info_per_id*register_opaque_info_per_id(s
tructopaque_info_per_type*oipt,structospf_lsa*new){structopaque_info_per_id*oipi
;if((oipi=XCALLOC(MTYPE_OPAQUE_INFO_PER_ID,sizeof(structopaque_info_per_id)))==N
ULL){zlog_warn("register_opaque_info_per_id:XMALLOC:%s",safe_strerror(errno));go
toout;}oipi->opaque_id=GET_OPAQUE_ID(ntohl(new->data->id.s_addr));oipi->t_opaque
_lsa_self=NULL;oipi->opqctl_type=oipt;oipi->lsa=ospf_lsa_lock(new);listnode_add(
oipt->id_list,oipi);out:returnoipi;}staticvoidfree_opaque_info_per_id(void*val){
structopaque_info_per_id*oipi=(structopaque_info_per_id*)val;OSPF_TIMER_OFF(oipi
->t_opaque_lsa_self);if(oipi->lsa!=NULL)ospf_lsa_unlock(&oipi->lsa);XFREE(MTYPE_
OPAQUE_INFO_PER_ID,oipi);return;}staticstructopaque_info_per_id*lookup_opaque_in
fo_by_id(structopaque_info_per_type*oipt,structospf_lsa*lsa){structlistnode*node
,*nnode;structopaque_info_per_id*oipi;uint32_tkey=GET_OPAQUE_ID(ntohl(lsa->data-
>id.s_addr));for(ALL_LIST_ELEMENTS(oipt->id_list,node,nnode,oipi))if(oipi->opaqu
e_id==key)returnoipi;returnNULL;}staticstructopaque_info_per_id*register_opaque_
lsa(structospf_lsa*new){structospf_opaque_functab*functab;structopaque_info_per_
type*oipt;structopaque_info_per_id*oipi=NULL;if((functab=ospf_opaque_functab_loo
kup(new))==NULL)gotoout;if((oipt=lookup_opaque_info_by_type(new))==NULL&&(oipt=r
egister_opaque_info_per_type(functab,new))==NULL)gotoout;if((oipi=register_opaqu
e_info_per_id(oipt,new))==NULL)gotoout;out:returnoipi;}/*-----------------------
-------------------------------------------------**Followingsare(vty)configurati
onfunctionsforOpaque-LSAshandling.*---------------------------------------------
---------------------------*/DEFUN(capability_opaque,capability_opaque_cmd,"capa
bilityopaque","EnablespecificOSPFfeature\n""OpaqueLSA\n"){VTY_DECLVAR_INSTANCE_C
ONTEXT(ospf,ospf);/*Turnonthe"masterswitch"ofopaque-lsacapability.*/if(!CHECK_FL
AG(ospf->config,OSPF_OPAQUE_CAPABLE)){if(IS_DEBUG_OSPF_EVENT)zlog_debug("Opaquec
apability:OFF->ON");SET_FLAG(ospf->config,OSPF_OPAQUE_CAPABLE);ospf_renegotiate_
optional_capabilities(ospf);}returnCMD_SUCCESS;}DEFUN(ospf_opaque,ospf_opaque_cm
d,"ospfopaque-lsa","OSPFspecificcommands\n""EnabletheOpaque-LSAcapability(rfc237
0)\n"){returncapability_opaque(self,vty,argc,argv);}DEFUN(no_capability_opaque,n
o_capability_opaque_cmd,"nocapabilityopaque",NO_STR"EnablespecificOSPFfeature\n"
"OpaqueLSA\n"){VTY_DECLVAR_INSTANCE_CONTEXT(ospf,ospf);/*Turnoffthe"masterswitch
"ofopaque-lsacapability.*/if(CHECK_FLAG(ospf->config,OSPF_OPAQUE_CAPABLE)){if(IS
_DEBUG_OSPF_EVENT)zlog_debug("Opaquecapability:ON->OFF");UNSET_FLAG(ospf->config
,OSPF_OPAQUE_CAPABLE);ospf_renegotiate_optional_capabilities(ospf);}returnCMD_SU
CCESS;}DEFUN(no_ospf_opaque,no_ospf_opaque_cmd,"noospfopaque-lsa",NO_STR"OSPFspe
cificcommands\n""EnabletheOpaque-LSAcapability(rfc2370)\n"){returnno_capability_
opaque(self,vty,argc,argv);}staticvoidospf_opaque_register_vty(void){install_ele
ment(OSPF_NODE,&capability_opaque_cmd);install_element(OSPF_NODE,&no_capability_
opaque_cmd);install_element(OSPF_NODE,&ospf_opaque_cmd);install_element(OSPF_NOD
E,&no_ospf_opaque_cmd);return;}/*-----------------------------------------------
-------------------------**Followingsarecollectionofuser-registeredfunctioncalle
rs.*------------------------------------------------------------------------*/st
aticintopaque_lsa_new_if_callback(structlist*funclist,structinterface*ifp){struc
tlistnode*node,*nnode;structospf_opaque_functab*functab;intrc=-1;for(ALL_LIST_EL
EMENTS(funclist,node,nnode,functab))if(functab->new_if_hook!=NULL)if((*functab->
new_if_hook)(ifp)!=0)gotoout;rc=0;out:returnrc;}staticintopaque_lsa_del_if_callb
ack(structlist*funclist,structinterface*ifp){structlistnode*node,*nnode;structos
pf_opaque_functab*functab;intrc=-1;for(ALL_LIST_ELEMENTS(funclist,node,nnode,fun
ctab))if(functab->del_if_hook!=NULL)if((*functab->del_if_hook)(ifp)!=0)gotoout;r
c=0;out:returnrc;}staticvoidopaque_lsa_ism_change_callback(structlist*funclist,s
tructospf_interface*oi,intold_status){structlistnode*node,*nnode;structospf_opaq
ue_functab*functab;for(ALL_LIST_ELEMENTS(funclist,node,nnode,functab))if(functab
->ism_change_hook!=NULL)(*functab->ism_change_hook)(oi,old_status);return;}stati
cvoidopaque_lsa_nsm_change_callback(structlist*funclist,structospf_neighbor*nbr,
intold_status){structlistnode*node,*nnode;structospf_opaque_functab*functab;for(
ALL_LIST_ELEMENTS(funclist,node,nnode,functab))if(functab->nsm_change_hook!=NULL
)(*functab->nsm_change_hook)(nbr,old_status);return;}staticvoidopaque_lsa_config
_write_router_callback(structlist*funclist,structvty*vty){structlistnode*node,*n
node;structospf_opaque_functab*functab;for(ALL_LIST_ELEMENTS(funclist,node,nnode
,functab))if(functab->config_write_router!=NULL)(*functab->config_write_router)(
vty);return;}staticvoidopaque_lsa_config_write_if_callback(structlist*funclist,s
tructvty*vty,structinterface*ifp){structlistnode*node,*nnode;structospf_opaque_f
unctab*functab;for(ALL_LIST_ELEMENTS(funclist,node,nnode,functab))if(functab->co
nfig_write_if!=NULL)(*functab->config_write_if)(vty,ifp);return;}staticvoidopaqu
e_lsa_config_write_debug_callback(structlist*funclist,structvty*vty){structlistn
ode*node,*nnode;structospf_opaque_functab*functab;for(ALL_LIST_ELEMENTS(funclist
,node,nnode,functab))if(functab->config_write_debug!=NULL)(*functab->config_writ
e_debug)(vty);return;}staticintopaque_lsa_originate_callback(structlist*funclist
,void*lsa_type_dependent){structlistnode*node,*nnode;structospf_opaque_functab*f
unctab;intrc=-1;for(ALL_LIST_ELEMENTS(funclist,node,nnode,functab))if(functab->l
sa_originator!=NULL)if((*functab->lsa_originator)(lsa_type_dependent)!=0)gotoout
;rc=0;out:returnrc;}staticintnew_lsa_callback(structlist*funclist,structospf_lsa
*lsa){structlistnode*node,*nnode;structospf_opaque_functab*functab;intrc=-1;/*Th
isfunctionhandlesALLtypesofLSAs,notonlyopaqueones.*/for(ALL_LIST_ELEMENTS(funcli
st,node,nnode,functab))if(functab->new_lsa_hook!=NULL)if((*functab->new_lsa_hook
)(lsa)!=0)gotoout;rc=0;out:returnrc;}staticintdel_lsa_callback(structlist*funcli
st,structospf_lsa*lsa){structlistnode*node,*nnode;structospf_opaque_functab*func
tab;intrc=-1;/*ThisfunctionhandlesALLtypesofLSAs,notonlyopaqueones.*/for(ALL_LIS
T_ELEMENTS(funclist,node,nnode,functab))if(functab->del_lsa_hook!=NULL)if((*func
tab->del_lsa_hook)(lsa)!=0)gotoout;rc=0;out:returnrc;}/*------------------------
------------------------------------------------**Followingsaregluefunctionstoca
llOpaque-LSAspecificprocessing.*------------------------------------------------
------------------------*/intospf_opaque_new_if(structinterface*ifp){structlist*
funclist;intrc=-1;funclist=ospf_opaque_wildcard_funclist;if(opaque_lsa_new_if_ca
llback(funclist,ifp)!=0)gotoout;funclist=ospf_opaque_type9_funclist;if(opaque_ls
a_new_if_callback(funclist,ifp)!=0)gotoout;funclist=ospf_opaque_type10_funclist;
if(opaque_lsa_new_if_callback(funclist,ifp)!=0)gotoout;funclist=ospf_opaque_type
11_funclist;if(opaque_lsa_new_if_callback(funclist,ifp)!=0)gotoout;rc=0;out:retu
rnrc;}intospf_opaque_del_if(structinterface*ifp){structlist*funclist;intrc=-1;fu
nclist=ospf_opaque_wildcard_funclist;if(opaque_lsa_del_if_callback(funclist,ifp)
!=0)gotoout;funclist=ospf_opaque_type9_funclist;if(opaque_lsa_del_if_callback(fu
nclist,ifp)!=0)gotoout;funclist=ospf_opaque_type10_funclist;if(opaque_lsa_del_if
_callback(funclist,ifp)!=0)gotoout;funclist=ospf_opaque_type11_funclist;if(opaqu
e_lsa_del_if_callback(funclist,ifp)!=0)gotoout;rc=0;out:returnrc;}voidospf_opaqu
e_ism_change(structospf_interface*oi,intold_status){structlist*funclist;funclist
=ospf_opaque_wildcard_funclist;opaque_lsa_ism_change_callback(funclist,oi,old_st
atus);funclist=ospf_opaque_type9_funclist;opaque_lsa_ism_change_callback(funclis
t,oi,old_status);funclist=ospf_opaque_type10_funclist;opaque_lsa_ism_change_call
back(funclist,oi,old_status);funclist=ospf_opaque_type11_funclist;opaque_lsa_ism
_change_callback(funclist,oi,old_status);return;}voidospf_opaque_nsm_change(stru
ctospf_neighbor*nbr,intold_state){structospf*top;structlist*funclist;if((top=oi_
to_top(nbr->oi))==NULL)gotoout;if(old_state!=NSM_Full&&nbr->state==NSM_Full){if(
CHECK_FLAG(nbr->options,OSPF_OPTION_O)){if(!CHECK_FLAG(top->opaque,OPAQUE_OPERAT
ION_READY_BIT)){if(IS_DEBUG_OSPF_EVENT)zlog_debug("Opaque-LSA:Nowgetoperational!
");SET_FLAG(top->opaque,OPAQUE_OPERATION_READY_BIT);}ospf_opaque_lsa_originate_s
chedule(nbr->oi,NULL);}}elseif(old_state==NSM_Full&&nbr->state!=NSM_Full){#ifdef
NOTYET/**Ifnomoreopaque-capablefull-stateneighborremainsinthe*floodingscopewhich
correspondstoOpaque-LSAtype,periodic*LSfloodingshouldbestopped.*/#endif/*NOTYET*
/;}funclist=ospf_opaque_wildcard_funclist;opaque_lsa_nsm_change_callback(funclis
t,nbr,old_state);funclist=ospf_opaque_type9_funclist;opaque_lsa_nsm_change_callb
ack(funclist,nbr,old_state);funclist=ospf_opaque_type10_funclist;opaque_lsa_nsm_
change_callback(funclist,nbr,old_state);funclist=ospf_opaque_type11_funclist;opa
que_lsa_nsm_change_callback(funclist,nbr,old_state);out:return;}voidospf_opaque_
config_write_router(structvty*vty,structospf*ospf){structlist*funclist;if(CHECK_
FLAG(ospf->config,OSPF_OPAQUE_CAPABLE))vty_out(vty,"capabilityopaque\n");funclis
t=ospf_opaque_wildcard_funclist;opaque_lsa_config_write_router_callback(funclist
,vty);funclist=ospf_opaque_type9_funclist;opaque_lsa_config_write_router_callbac
k(funclist,vty);funclist=ospf_opaque_type10_funclist;opaque_lsa_config_write_rou
ter_callback(funclist,vty);funclist=ospf_opaque_type11_funclist;opaque_lsa_confi
g_write_router_callback(funclist,vty);return;}voidospf_opaque_config_write_if(st
ructvty*vty,structinterface*ifp){structlist*funclist;funclist=ospf_opaque_wildca
rd_funclist;opaque_lsa_config_write_if_callback(funclist,vty,ifp);funclist=ospf_
opaque_type9_funclist;opaque_lsa_config_write_if_callback(funclist,vty,ifp);func
list=ospf_opaque_type10_funclist;opaque_lsa_config_write_if_callback(funclist,vt
y,ifp);funclist=ospf_opaque_type11_funclist;opaque_lsa_config_write_if_callback(
funclist,vty,ifp);return;}voidospf_opaque_config_write_debug(structvty*vty){stru
ctlist*funclist;funclist=ospf_opaque_wildcard_funclist;opaque_lsa_config_write_d
ebug_callback(funclist,vty);funclist=ospf_opaque_type9_funclist;opaque_lsa_confi
g_write_debug_callback(funclist,vty);funclist=ospf_opaque_type10_funclist;opaque
_lsa_config_write_debug_callback(funclist,vty);funclist=ospf_opaque_type11_funcl
ist;opaque_lsa_config_write_debug_callback(funclist,vty);return;}voidshow_opaque
_info_detail(structvty*vty,structospf_lsa*lsa){structlsa_header*lsah=(structlsa_
header*)lsa->data;uint32_tlsid=ntohl(lsah->id.s_addr);uint8_topaque_type=GET_OPA
QUE_TYPE(lsid);uint32_topaque_id=GET_OPAQUE_ID(lsid);structospf_opaque_functab*f
unctab;/*Switchoutputfunctionalitybyvtyaddress.*/if(vty!=NULL){vty_out(vty,"Opaq
ue-Type%u(%s)\n",opaque_type,ospf_opaque_type_name(opaque_type));vty_out(vty,"Op
aque-ID0x%x\n",opaque_id);vty_out(vty,"Opaque-Info:%uoctetsofdata%s\n",ntohs(lsa
h->length)-OSPF_LSA_HEADER_SIZE,VALID_OPAQUE_INFO_LEN(lsah)?"":"(Invalidlength?)
");}else{zlog_debug("Opaque-Type%u(%s)",opaque_type,ospf_opaque_type_name(opaque
_type));zlog_debug("Opaque-ID0x%x",opaque_id);zlog_debug("Opaque-Info:%uoctetsof
data%s",ntohs(lsah->length)-OSPF_LSA_HEADER_SIZE,VALID_OPAQUE_INFO_LEN(lsah)?"":
"(Invalidlength?)");}/*Callindividualoutputfunctions.*/if((functab=ospf_opaque_f
unctab_lookup(lsa))!=NULL)if(functab->show_opaque_info!=NULL)(*functab->show_opa
que_info)(vty,lsa);return;}voidospf_opaque_lsa_dump(structstream*s,uint16_tlengt
h){structospf_lsalsa;lsa.data=(structlsa_header*)stream_pnt(s);show_opaque_info_
detail(NULL,&lsa);return;}staticintospf_opaque_lsa_install_hook(structospf_lsa*l
sa){structlist*funclist;intrc=-1;/**SomeOpaque-LSAusermaywanttomonitoreveryLSAin
stallation*intotheLSDB,regardlesswithtargetLSAtype.*/funclist=ospf_opaque_wildca
rd_funclist;if(new_lsa_callback(funclist,lsa)!=0)gotoout;funclist=ospf_opaque_ty
pe9_funclist;if(new_lsa_callback(funclist,lsa)!=0)gotoout;funclist=ospf_opaque_t
ype10_funclist;if(new_lsa_callback(funclist,lsa)!=0)gotoout;funclist=ospf_opaque
_type11_funclist;if(new_lsa_callback(funclist,lsa)!=0)gotoout;rc=0;out:returnrc;
}staticintospf_opaque_lsa_delete_hook(structospf_lsa*lsa){structlist*funclist;in
trc=-1;/**SomeOpaque-LSAusermaywanttomonitoreveryLSAdeletion*fromtheLSDB,regardl
esswithtargetLSAtype.*/funclist=ospf_opaque_wildcard_funclist;if(del_lsa_callbac
k(funclist,lsa)!=0)gotoout;funclist=ospf_opaque_type9_funclist;if(del_lsa_callba
ck(funclist,lsa)!=0)gotoout;funclist=ospf_opaque_type10_funclist;if(del_lsa_call
back(funclist,lsa)!=0)gotoout;funclist=ospf_opaque_type11_funclist;if(del_lsa_ca
llback(funclist,lsa)!=0)gotoout;rc=0;out:returnrc;}/*---------------------------
---------------------------------------------**FollowingsareOpaque-LSAoriginatio
n/refreshmanagementfunctions.*--------------------------------------------------
----------------------*/staticintospf_opaque_type9_lsa_originate(structthread*t)
;staticintospf_opaque_type10_lsa_originate(structthread*t);staticintospf_opaque_
type11_lsa_originate(structthread*t);staticvoidospf_opaque_lsa_reoriginate_resum
e(structlist*listtop,void*arg);voidospf_opaque_lsa_originate_schedule(structospf
_interface*oi,int*delay0){structospf*top;structospf_area*area;structlistnode*nod
e,*nnode;structopaque_info_per_type*oipt;intdelay=0;if((top=oi_to_top(oi))==NULL
||(area=oi->area)==NULL){zlog_warn("ospf_opaque_lsa_originate_schedule:Invalidar
gument?");gotoout;}/*Itmaynotarighttimetoscheduleoriginationnow.*/if(!CHECK_FLAG
(top->opaque,OPAQUE_OPERATION_READY_BIT)){if(IS_DEBUG_OSPF_EVENT)zlog_debug("osp
f_opaque_lsa_originate_schedule:Notoperational.");gotoout;/*Thisisnotanerror.*/}
if(delay0!=NULL)delay=*delay0;/**Theremightbesomeentriesthathavebeenwaitingfortr
iggering*ofperopaque-typere-originationgetresumed.*/ospf_opaque_lsa_reoriginate_
resume(oi->opaque_lsa_self,(void*)oi);ospf_opaque_lsa_reoriginate_resume(area->o
paque_lsa_self,(void*)area);ospf_opaque_lsa_reoriginate_resume(top->opaque_lsa_s
elf,(void*)top);/**Now,scheduleoriginationofallOpaque-LSAsperopaque-type.*/if(!l
ist_isempty(ospf_opaque_type9_funclist)&&list_isempty(oi->opaque_lsa_self)&&oi->
t_opaque_lsa_self==NULL){if(IS_DEBUG_OSPF_EVENT)zlog_debug("ScheduleType-9Opaque
-LSAoriginationin%dmslater.",delay);oi->t_opaque_lsa_self=NULL;thread_add_timer_
msec(master,ospf_opaque_type9_lsa_originate,oi,delay,&oi->t_opaque_lsa_self);del
ay+=top->min_ls_interval;}if(!list_isempty(ospf_opaque_type10_funclist)&&list_is
empty(area->opaque_lsa_self)&&area->t_opaque_lsa_self==NULL){/**OneAREAmaycontai
nmultipleOIs,butabove2ndand3rd*conditionspreventfromschedulingtheoriginatefuncti
on*againandagain.*/if(IS_DEBUG_OSPF_EVENT)zlog_debug("ScheduleType-10Opaque-LSAo
riginationin%dmslater.",delay);area->t_opaque_lsa_self=NULL;thread_add_timer_mse
c(master,ospf_opaque_type10_lsa_originate,area,delay,&area->t_opaque_lsa_self);d
elay+=top->min_ls_interval;}if(!list_isempty(ospf_opaque_type11_funclist)&&list_
isempty(top->opaque_lsa_self)&&top->t_opaque_lsa_self==NULL){/**OneOSPFmaycontai
nmultipleAREAs,butabove2ndand3rd*conditionspreventfromschedulingtheoriginatefunc
tion*againandagain.*/if(IS_DEBUG_OSPF_EVENT)zlog_debug("ScheduleType-11Opaque-LS
Aoriginationin%dmslater.",delay);top->t_opaque_lsa_self=NULL;thread_add_timer_ms
ec(master,ospf_opaque_type11_lsa_originate,top,delay,&top->t_opaque_lsa_self);de
lay+=top->min_ls_interval;}/**Followingsectiontreatsaspecialsituationthatthisnod
e's*opaquecapabilityhaschangedas"ON->OFF->ON".*/if(!list_isempty(ospf_opaque_typ
e9_funclist)&&!list_isempty(oi->opaque_lsa_self)){for(ALL_LIST_ELEMENTS(oi->opaq
ue_lsa_self,node,nnode,oipt)){/**removedthetestfor*(!list_isempty(oipt->id_list)
)*Handleris*alreadyactive.**becauseopaquecababilitiesON->OFF->ONresultin*list_is
empty(oipt->id_list)*notbeingempty.*/if(oipt->t_opaque_lsa_self!=NULL/*Waitingfo
rathreadcall.*/||oipt->status==PROC_SUSPEND)/*Cannotoriginatenow.*/continue;ospf
_opaque_lsa_reoriginate_schedule((void*)oi,OSPF_OPAQUE_LINK_LSA,oipt->opaque_typ
e);}}if(!list_isempty(ospf_opaque_type10_funclist)&&!list_isempty(area->opaque_l
sa_self)){for(ALL_LIST_ELEMENTS(area->opaque_lsa_self,node,nnode,oipt)){/**remov
edthetestfor*(!list_isempty(oipt->id_list))*Handleris*alreadyactive.**becauseopa
quecababilitiesON->OFF->ONresultin*list_isempty(oipt->id_list)*notbeingempty.*/i
f(oipt->t_opaque_lsa_self!=NULL/*Waitingforathreadcall.*/||oipt->status==PROC_SU
SPEND)/*Cannotoriginatenow.*/continue;ospf_opaque_lsa_reoriginate_schedule((void
*)area,OSPF_OPAQUE_AREA_LSA,oipt->opaque_type);}}if(!list_isempty(ospf_opaque_ty
pe11_funclist)&&!list_isempty(top->opaque_lsa_self)){for(ALL_LIST_ELEMENTS(top->
opaque_lsa_self,node,nnode,oipt)){/**removedthetestfor*(!list_isempty(oipt->id_l
ist))*Handleris*alreadyactive.**becauseopaquecababilitiesON->OFF->ONresultin*lis
t_isempty(oipt->id_list)*notbeingempty.*/if(oipt->t_opaque_lsa_self!=NULL/*Waiti
ngforathreadcall.*/||oipt->status==PROC_SUSPEND)/*Cannotoriginatenow.*/continue;
ospf_opaque_lsa_reoriginate_schedule((void*)top,OSPF_OPAQUE_AS_LSA,oipt->opaque_
type);}}if(delay0!=NULL)*delay0=delay;out:return;}staticintospf_opaque_type9_lsa
_originate(structthread*t){structospf_interface*oi;intrc;oi=THREAD_ARG(t);oi->t_
opaque_lsa_self=NULL;if(IS_DEBUG_OSPF_EVENT)zlog_debug("Timer[Type9-LSA]:Origina
teOpaque-LSAsforOI%s",IF_NAME(oi));rc=opaque_lsa_originate_callback(ospf_opaque_
type9_funclist,oi);returnrc;}staticintospf_opaque_type10_lsa_originate(structthr
ead*t){structospf_area*area;intrc;area=THREAD_ARG(t);area->t_opaque_lsa_self=NUL
L;if(IS_DEBUG_OSPF_EVENT)zlog_debug("Timer[Type10-LSA]:OriginateOpaque-LSAsforAr
ea%s",inet_ntoa(area->area_id));rc=opaque_lsa_originate_callback(ospf_opaque_typ
e10_funclist,area);returnrc;}staticintospf_opaque_type11_lsa_originate(structthr
ead*t){structospf*top;intrc;top=THREAD_ARG(t);top->t_opaque_lsa_self=NULL;if(IS_
DEBUG_OSPF_EVENT)zlog_debug("Timer[Type11-LSA]:OriginateAS-ExternalOpaque-LSAs")
;rc=opaque_lsa_originate_callback(ospf_opaque_type11_funclist,top);returnrc;}sta
ticvoidospf_opaque_lsa_reoriginate_resume(structlist*listtop,void*arg){structlis
tnode*node,*nnode;structopaque_info_per_type*oipt;structospf_opaque_functab*func
tab;if(listtop==NULL)gotoout;/**PickupoiptentriesthosewhichinSUSPENDstatus,andgi
ve*themachancetostartre-originationnow.*/for(ALL_LIST_ELEMENTS(listtop,node,nnod
e,oipt)){if(oipt->status!=PROC_SUSPEND)continue;oipt->status=PROC_NORMAL;if((fun
ctab=oipt->functab)==NULL||functab->lsa_originator==NULL)continue;if((*functab->
lsa_originator)(arg)!=0){zlog_warn("ospf_opaque_lsa_reoriginate_resume:Failed(op
aque-type=%u)",oipt->opaque_type);continue;}}out:return;}structospf_lsa*ospf_opa
que_lsa_install(structospf_lsa*lsa,intrt_recalc){structospf_lsa*new=NULL;structo
paque_info_per_type*oipt;structopaque_info_per_id*oipi;structospf*top;/*Don'ttak
e"rt_recalc"intoconsiderationfornow.*//*XXX*/if(!IS_LSA_SELF(lsa)){new=lsa;/*Don
'ttouchthisLSA.*/gotoout;}if(IS_DEBUG_OSPF(lsa,LSA_INSTALL))zlog_debug("InstallT
ype-%uOpaque-LSA:[opaque-type=%u,opaque-id=%x]",lsa->data->type,GET_OPAQUE_TYPE(
ntohl(lsa->data->id.s_addr)),GET_OPAQUE_ID(ntohl(lsa->data->id.s_addr)));/*Repla
cetheexistinglsawiththenewone.*/if((oipt=lookup_opaque_info_by_type(lsa))!=NULL&
&(oipi=lookup_opaque_info_by_id(oipt,lsa))!=NULL){ospf_lsa_unlock(&oipi->lsa);oi
pi->lsa=ospf_lsa_lock(lsa);}/*Registerthenewlsaentryandgetitscontrolinfo.*/elsei
f((oipi=register_opaque_lsa(lsa))==NULL){zlog_warn("ospf_opaque_lsa_install:regi
ster_opaque_lsa()?");gotoout;}/**Makeuseofacommonmechanism(ospf_lsa_refresh_walk
er)*forperiodicrefreshofself-originatedOpaque-LSAs.*/switch(lsa->data->type){cas
eOSPF_OPAQUE_LINK_LSA:if((top=oi_to_top(lsa->oi))==NULL){/*Aboveconditionsmustha
vepassed.*/zlog_warn("ospf_opaque_lsa_install:Sonmethingwrong?");gotoout;}break;
caseOSPF_OPAQUE_AREA_LSA:if(lsa->area==NULL||(top=lsa->area->ospf)==NULL){/*Abov
econditionsmusthavepassed.*/zlog_warn("ospf_opaque_lsa_install:Sonmethingwrong?"
);gotoout;}break;caseOSPF_OPAQUE_AS_LSA:top=ospf_lookup_by_vrf_id(lsa->vrf_id);i
f(lsa->area!=NULL&&(top=lsa->area->ospf)==NULL){/*Aboveconditionsmusthavepassed.
*/zlog_warn("ospf_opaque_lsa_install:Sonmethingwrong?");gotoout;}break;default:z
log_warn("ospf_opaque_lsa_install:UnexpectedLSA-type(%u)",lsa->data->type);gotoo
ut;}ospf_refresher_register_lsa(top,lsa);new=lsa;out:returnnew;}structospf_lsa*o
spf_opaque_lsa_refresh(structospf_lsa*lsa){structospf*ospf;structospf_opaque_fun
ctab*functab;structospf_lsa*new=NULL;ospf=ospf_lookup_by_vrf_id(lsa->vrf_id);if(
(functab=ospf_opaque_functab_lookup(lsa))==NULL||functab->lsa_refresher==NULL){/
**ThoughthisLSAseemstohaveoriginatedonthisnode,the*handlingmoduleforthis"lsa-typ
eandopaque-type"was*alreadydeletedsometimeago.*Anyway,thisnodestillhasaresponsib
ilitytoflushthis*LSAfromtheroutingdomain.*/if(IS_DEBUG_OSPF_EVENT)zlog_debug("LS
A[Type%d:%s]:FlushstrayOpaque-LSA",lsa->data->type,inet_ntoa(lsa->data->id));lsa
->data->ls_age=htons(OSPF_LSA_MAXAGE);ospf_lsa_flush(ospf,lsa);}elsenew=(*functa
b->lsa_refresher)(lsa);returnnew;}/*--------------------------------------------
----------------------------**Followingsarere-origination/refresh/flushoperation
sofOpaque-LSAs,*triggeredbyexternalinterventions(vtysession,signaling,etc).*----
--------------------------------------------------------------------*/#defineOSP
F_OPAQUE_TIMER_ON(T,F,L,V)thread_add_timer_msec(master,(F),(L),(V),&(T))staticst
ructospf_lsa*pseudo_lsa(structospf_interface*oi,structospf_area*area,uint8_tlsa_
type,uint8_topaque_type);staticintospf_opaque_type9_lsa_reoriginate_timer(struct
thread*t);staticintospf_opaque_type10_lsa_reoriginate_timer(structthread*t);stat
icintospf_opaque_type11_lsa_reoriginate_timer(structthread*t);staticintospf_opaq
ue_lsa_refresh_timer(structthread*t);voidospf_opaque_lsa_reoriginate_schedule(vo
id*lsa_type_dependent,uint8_tlsa_type,uint8_topaque_type){structospf*top=NULL;st
ructospf_areadummy,*area=NULL;structospf_interface*oi=NULL;structospf_lsa*lsa;st
ructopaque_info_per_type*oipt;int(*func)(structthread*t)=NULL;intdelay;switch(ls
a_type){caseOSPF_OPAQUE_LINK_LSA:if((oi=(structospf_interface*)lsa_type_dependen
t)==NULL){zlog_warn("ospf_opaque_lsa_reoriginate_schedule:""Type-9Opaque-LSA:Inv
alidparameter?");gotoout;}if((top=oi_to_top(oi))==NULL){zlog_warn("ospf_opaque_l
sa_reoriginate_schedule:OI(%s)->TOP?",IF_NAME(oi));gotoout;}if(!list_isempty(osp
f_opaque_type9_funclist)&&list_isempty(oi->opaque_lsa_self)&&oi->t_opaque_lsa_se
lf!=NULL){zlog_warn("Type-9Opaque-LSA(opaque_type=%u):""CommonoriginationforOI(%
s)hasalreadystarted",opaque_type,IF_NAME(oi));gotoout;}func=ospf_opaque_type9_ls
a_reoriginate_timer;break;caseOSPF_OPAQUE_AREA_LSA:if((area=(structospf_area*)ls
a_type_dependent)==NULL){zlog_warn("ospf_opaque_lsa_reoriginate_schedule:""Type-
10Opaque-LSA:Invalidparameter?");gotoout;}if((top=area->ospf)==NULL){zlog_warn("
ospf_opaque_lsa_reoriginate_schedule:""AREA(%s)->TOP?",inet_ntoa(area->area_id))
;gotoout;}if(!list_isempty(ospf_opaque_type10_funclist)&&list_isempty(area->opaq
ue_lsa_self)&&area->t_opaque_lsa_self!=NULL){zlog_warn("Type-10Opaque-LSA(opaque
_type=%u):""CommonoriginationforAREA(%s)hasalreadystarted",opaque_type,inet_ntoa
(area->area_id));gotoout;}func=ospf_opaque_type10_lsa_reoriginate_timer;break;ca
seOSPF_OPAQUE_AS_LSA:if((top=(structospf*)lsa_type_dependent)==NULL){zlog_warn("
ospf_opaque_lsa_reoriginate_schedule:""Type-11Opaque-LSA:Invalidparameter?");got
oout;}if(!list_isempty(ospf_opaque_type11_funclist)&&list_isempty(top->opaque_ls
a_self)&&top->t_opaque_lsa_self!=NULL){zlog_warn("Type-11Opaque-LSA(opaque_type=
%u):""Commonoriginationhasalreadystarted",opaque_type);gotoout;}/*Fake"area"topa
ss"ospf"toalookupfunctionlater.*/dummy.ospf=top;area=&dummy;func=ospf_opaque_typ
e11_lsa_reoriginate_timer;break;default:zlog_warn("ospf_opaque_lsa_reoriginate_s
chedule:""UnexpectedLSA-type(%u)",lsa_type);gotoout;}/*Itmaynotarighttimetosched
ulereoriginationnow.*/if(!CHECK_FLAG(top->opaque,OPAQUE_OPERATION_READY_BIT)){if
(IS_DEBUG_OSPF_EVENT)zlog_debug("ospf_opaque_lsa_reoriginate_schedule:Notoperati
onal.");gotoout;/*Thisisnotanerror.*/}/*Generateadummylsatobepassedforalookupfun
ction.*/lsa=pseudo_lsa(oi,area,lsa_type,opaque_type);lsa->vrf_id=top->vrf_id;if(
(oipt=lookup_opaque_info_by_type(lsa))==NULL){structospf_opaque_functab*functab;
if((functab=ospf_opaque_functab_lookup(lsa))==NULL){zlog_warn("ospf_opaque_lsa_r
eoriginate_schedule:""Noassociatedfunction?:lsa_type(%u),""opaque_type(%u)",lsa_
type,opaque_type);gotoout;}if((oipt=register_opaque_info_per_type(functab,lsa))=
=NULL){zlog_warn("ospf_opaque_lsa_reoriginate_schedule:""Cannotgetacontrolinfo?:
lsa_type(%u),""opaque_type(%u)",lsa_type,opaque_type);gotoout;}}if(oipt->t_opaqu
e_lsa_self!=NULL){if(IS_DEBUG_OSPF_EVENT)zlog_debug("Type-%uOpaque-LSAhasalready
scheduledto""RE-ORIGINATE:[opaque-type=%u]",lsa_type,GET_OPAQUE_TYPE(ntohl(lsa->
data->id.s_addr)));gotoout;}/**Differentfrominitialoriginationtime,inwhichvariou
sconditions*(opaquecapability,neighborstatusetc)areassuredbycallerof*theoriginat
ingfunction"ospf_opaque_lsa_originate_schedule()",*itishighlypossiblethattheseco
nditionsmightnotbesatisfied*atthetimeofre-originationfunctionistobecalled.*/dela
y=top->min_ls_interval;/*XXX*/if(IS_DEBUG_OSPF_EVENT)zlog_debug("ScheduleType-%u
Opaque-LSAtoRE-ORIGINATEin%d""mslater:[opaque-type=%u]",lsa_type,delay,GET_OPAQU
E_TYPE(ntohl(lsa->data->id.s_addr)));OSPF_OPAQUE_TIMER_ON(oipt->t_opaque_lsa_sel
f,func,oipt,delay);out:return;}staticstructospf_lsa*pseudo_lsa(structospf_interf
ace*oi,structospf_area*area,uint8_tlsa_type,uint8_topaque_type){staticstructospf
_lsalsa={0};staticstructlsa_headerlsah={0};uint32_ttmp;lsa.oi=oi;lsa.area=area;l
sa.data=&lsah;lsa.vrf_id=VRF_DEFAULT;lsah.type=lsa_type;tmp=SET_OPAQUE_LSID(opaq
ue_type,0);/*Opaque-IDisunusedhere.*/lsah.id.s_addr=htonl(tmp);return&lsa;}stati
cintospf_opaque_type9_lsa_reoriginate_timer(structthread*t){structopaque_info_pe
r_type*oipt;structospf_opaque_functab*functab;structospf*top;structospf_interfac
e*oi;intrc=-1;oipt=THREAD_ARG(t);oipt->t_opaque_lsa_self=NULL;if((functab=oipt->
functab)==NULL||functab->lsa_originator==NULL){zlog_warn("ospf_opaque_type9_lsa_
reoriginate_timer:Noassociatedfunction?");gotoout;}oi=(structospf_interface*)oip
t->owner;if((top=oi_to_top(oi))==NULL){zlog_warn("ospf_opaque_type9_lsa_reorigin
ate_timer:Somethingwrong?");gotoout;}if(!CHECK_FLAG(top->config,OSPF_OPAQUE_CAPA
BLE)||!ospf_if_is_enable(oi)||ospf_nbr_count_opaque_capable(oi)==0){if(IS_DEBUG_
OSPF_EVENT)zlog_debug("Suspendre-originationofType-9Opaque-LSAs(opaque-type=%u)f
orawhile...",oipt->opaque_type);oipt->status=PROC_SUSPEND;rc=0;gotoout;}if(IS_DE
BUG_OSPF_EVENT)zlog_debug("Timer[Type9-LSA]:Re-originateOpaque-LSAs(opaque-type=
%u)forOI(%s)",oipt->opaque_type,IF_NAME(oi));rc=(*functab->lsa_originator)(oi);o
ut:returnrc;}staticintospf_opaque_type10_lsa_reoriginate_timer(structthread*t){s
tructopaque_info_per_type*oipt;structospf_opaque_functab*functab;structlistnode*
node,*nnode;structospf*top;structospf_area*area;structospf_interface*oi;intn,rc=
-1;oipt=THREAD_ARG(t);oipt->t_opaque_lsa_self=NULL;if((functab=oipt->functab)==N
ULL||functab->lsa_originator==NULL){zlog_warn("ospf_opaque_type10_lsa_reoriginat
e_timer:Noassociatedfunction?");gotoout;}area=(structospf_area*)oipt->owner;if(a
rea==NULL||(top=area->ospf)==NULL){zlog_warn("ospf_opaque_type10_lsa_reoriginate
_timer:Somethingwrong?");gotoout;}/*Theremustbeatleastone"opaque-capable,full-st
ate"neighbor.*/n=0;for(ALL_LIST_ELEMENTS(area->oiflist,node,nnode,oi)){if((n=osp
f_nbr_count_opaque_capable(oi))>0)break;}if(n==0||!CHECK_FLAG(top->config,OSPF_O
PAQUE_CAPABLE)){if(IS_DEBUG_OSPF_EVENT)zlog_debug("Suspendre-originationofType-1
0Opaque-LSAs""(opaque-type=%u)forawhile...",oipt->opaque_type);oipt->status=PROC
_SUSPEND;rc=0;gotoout;}if(IS_DEBUG_OSPF_EVENT)zlog_debug("Timer[Type10-LSA]:Re-o
riginateOpaque-LSAs""(opaque-type=%u)forArea%s",oipt->opaque_type,inet_ntoa(area
->area_id));rc=(*functab->lsa_originator)(area);out:returnrc;}staticintospf_opaq
ue_type11_lsa_reoriginate_timer(structthread*t){structopaque_info_per_type*oipt;
structospf_opaque_functab*functab;structospf*top;intrc=-1;oipt=THREAD_ARG(t);oip
t->t_opaque_lsa_self=NULL;if((functab=oipt->functab)==NULL||functab->lsa_origina
tor==NULL){zlog_warn("ospf_opaque_type11_lsa_reoriginate_timer:""Noassociatedfun
ction?");gotoout;}if((top=(structospf*)oipt->owner)==NULL){zlog_warn("ospf_opaqu
e_type11_lsa_reoriginate_timer:Somethingwrong?");gotoout;}if(!CHECK_FLAG(top->co
nfig,OSPF_OPAQUE_CAPABLE)){if(IS_DEBUG_OSPF_EVENT)zlog_debug("Suspendre-originat
ionofType-11Opaque-LSAs(opaque-type=%u)forawhile...",oipt->opaque_type);oipt->st
atus=PROC_SUSPEND;rc=0;gotoout;}if(IS_DEBUG_OSPF_EVENT)zlog_debug("Timer[Type11-
LSA]:Re-originateOpaque-LSAs(opaque-type=%u).",oipt->opaque_type);rc=(*functab->
lsa_originator)(top);out:returnrc;}voidospf_opaque_lsa_refresh_schedule(structos
pf_lsa*lsa0){structopaque_info_per_type*oipt;structopaque_info_per_id*oipi;struc
tospf_lsa*lsa;structospf*top;intdelay;if((oipt=lookup_opaque_info_by_type(lsa0))
==NULL||(oipi=lookup_opaque_info_by_id(oipt,lsa0))==NULL){zlog_warn("ospf_opaque
_lsa_refresh_schedule:Invalidparameter?");gotoout;}/*Given"lsa0"andcurrent"oipi-
>lsa"maydifferent,butharmless.*/if((lsa=oipi->lsa)==NULL){zlog_warn("ospf_opaque
_lsa_refresh_schedule:Somethingwrong?");gotoout;}if(oipi->t_opaque_lsa_self!=NUL
L){if(IS_DEBUG_OSPF_EVENT)zlog_debug("Type-%uOpaque-LSAhasalreadyscheduledtoREFR
ESH:[opaque-type=%u,opaque-id=%x]",lsa->data->type,GET_OPAQUE_TYPE(ntohl(lsa->da
ta->id.s_addr)),GET_OPAQUE_ID(ntohl(lsa->data->id.s_addr)));gotoout;}/*Deletethi
slsafromneighborretransmit-list.*/switch(lsa->data->type){caseOSPF_OPAQUE_LINK_L
SA:caseOSPF_OPAQUE_AREA_LSA:ospf_ls_retransmit_delete_nbr_area(lsa->area,lsa);br
eak;caseOSPF_OPAQUE_AS_LSA:top=ospf_lookup_by_vrf_id(lsa0->vrf_id);if((lsa0->are
a!=NULL)&&(lsa0->area->ospf!=NULL))top=lsa0->area->ospf;ospf_ls_retransmit_delet
e_nbr_as(top,lsa);break;default:zlog_warn("ospf_opaque_lsa_refresh_schedule:Unex
pectedLSA-type(%u)",lsa->data->type);gotoout;}delay=ospf_lsa_refresh_delay(lsa);
if(IS_DEBUG_OSPF_EVENT)zlog_debug("ScheduleType-%uOpaque-LSAtoREFRESHin%dseclate
r:[opaque-type=%u,opaque-id=%x]",lsa->data->type,delay,GET_OPAQUE_TYPE(ntohl(lsa
->data->id.s_addr)),GET_OPAQUE_ID(ntohl(lsa->data->id.s_addr)));OSPF_OPAQUE_TIME
R_ON(oipi->t_opaque_lsa_self,ospf_opaque_lsa_refresh_timer,oipi,delay*1000);out:
return;}staticintospf_opaque_lsa_refresh_timer(structthread*t){structopaque_info
_per_id*oipi;structospf_opaque_functab*functab;structospf_lsa*lsa;if(IS_DEBUG_OS
PF_EVENT)zlog_debug("Timer[Opaque-LSA]:(Opaque-LSARefreshexpire)");oipi=THREAD_A
RG(t);oipi->t_opaque_lsa_self=NULL;if((lsa=oipi->lsa)!=NULL)if((functab=oipi->op
qctl_type->functab)!=NULL)if(functab->lsa_refresher!=NULL)(*functab->lsa_refresh
er)(lsa);return0;}voidospf_opaque_lsa_flush_schedule(structospf_lsa*lsa0){struct
opaque_info_per_type*oipt;structopaque_info_per_id*oipi;structospf_lsa*lsa;struc
tospf*top;top=ospf_lookup_by_vrf_id(lsa0->vrf_id);if((oipt=lookup_opaque_info_by
_type(lsa0))==NULL||(oipi=lookup_opaque_info_by_id(oipt,lsa0))==NULL){zlog_warn(
"ospf_opaque_lsa_flush_schedule:Invalidparameter?");gotoout;}/*Given"lsa0"andcur
rent"oipi->lsa"maydifferent,butharmless.*/if((lsa=oipi->lsa)==NULL){zlog_warn("o
spf_opaque_lsa_flush_schedule:Somethingwrong?");gotoout;}/*Deletethislsafromneig
hborretransmit-list.*/switch(lsa->data->type){caseOSPF_OPAQUE_LINK_LSA:caseOSPF_
OPAQUE_AREA_LSA:ospf_ls_retransmit_delete_nbr_area(lsa->area,lsa);break;caseOSPF
_OPAQUE_AS_LSA:if((lsa0->area!=NULL)&&(lsa0->area->ospf!=NULL))top=lsa0->area->o
spf;ospf_ls_retransmit_delete_nbr_as(top,lsa);break;default:zlog_warn("ospf_opaq
ue_lsa_flush_schedule:UnexpectedLSA-type(%u)",lsa->data->type);gotoout;}/*Dequeu
elistnodeentryfromthelist.*/listnode_delete(oipt->id_list,oipi);/*Avoidmisjudgem
entinthenextlookup.*/if(listcount(oipt->id_list)==0)oipt->id_list->head=oipt->id
_list->tail=NULL;/*Disassociateinternalcontrolinformationwiththegivenlsa.*/free_
opaque_info_per_id((void*)oipi);/*Forcegivenlsa'sagetoMaxAge.*/lsa->data->ls_age
=htons(OSPF_LSA_MAXAGE);if(IS_DEBUG_OSPF_EVENT)zlog_debug("ScheduleType-%uOpaque
-LSAtoFLUSH:[opaque-type=%u,opaque-id=%x]",lsa->data->type,GET_OPAQUE_TYPE(ntohl
(lsa->data->id.s_addr)),GET_OPAQUE_ID(ntohl(lsa->data->id.s_addr)));/*Thislsawil
lbeflushedandremovedeventually.*/ospf_lsa_flush(top,lsa);out:return;}voidospf_op
aque_self_originated_lsa_received(structospf_neighbor*nbr,structospf_lsa*lsa){st
ructospf*top;if((top=oi_to_top(nbr->oi))==NULL)return;/**SincetheseLSAentriesare
notyetinstalledintocorresponding*LSDB,justflushthemwithoutcallingospf_ls_maxage(
)afterward.*/lsa->data->ls_age=htons(OSPF_LSA_MAXAGE);switch(lsa->data->type){ca
seOSPF_OPAQUE_LINK_LSA:ospf_flood_through_area(nbr->oi->area,NULL/*inbr*/,lsa);b
reak;caseOSPF_OPAQUE_AREA_LSA:ospf_flood_through_area(nbr->oi->area,NULL/*inbr*/
,lsa);break;caseOSPF_OPAQUE_AS_LSA:ospf_flood_through_as(top,NULL/*inbr*/,lsa);b
reak;default:zlog_warn("ospf_opaque_self_originated_lsa_received:UnexpectedLSA-t
ype(%u)",lsa->data->type);return;}ospf_lsa_discard(lsa);/*List"lsas"willbedelete
dbycaller.*/}/*-----------------------------------------------------------------
-------**Followingsareutilfunctions;probablybeusedbyOpaque-LSAsonly...*---------
---------------------------------------------------------------*/structospf*oi_t
o_top(structospf_interface*oi){structospf*top=NULL;structospf_area*area;if(oi==N
ULL||(area=oi->area)==NULL||(top=area->ospf)==NULL)zlog_warn("Brokenrelationship
for\"OI->AREA->OSPF\"?");returntop;}