/**ServersideofOSPFAPI.*Copyright(C)2001,2002RalphKeller**ThisfileispartofGNUZeb
ra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodify*itunderthetermsofth
eGNUGeneralPublicLicenseaspublished*bytheFreeSoftwareFoundation;eitherversion2,o
r(atyour*option)anylaterversion.**GNUZebraisdistributedinthehopethatitwillbeusef
ul,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNE
SSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshould
havereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOP
YING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston
,MA02110-1301USA*/#include<zebra.h>#ifdefSUPPORT_OSPF_API#include"linklist.h"#in
clude"prefix.h"#include"if.h"#include"table.h"#include"memory.h"#include"command
.h"#include"vty.h"#include"stream.h"#include"log.h"#include"thread.h"#include"ha
sh.h"#include"sockunion.h"/*forinet_aton()*/#include"buffer.h"#include<sys/types
.h>#include"ospfd/ospfd.h"/*for"structthread_master"*/#include"ospfd/ospf_interf
ace.h"#include"ospfd/ospf_ism.h"#include"ospfd/ospf_asbr.h"#include"ospfd/ospf_l
sa.h"#include"ospfd/ospf_lsdb.h"#include"ospfd/ospf_neighbor.h"#include"ospfd/os
pf_nsm.h"#include"ospfd/ospf_flood.h"#include"ospfd/ospf_packet.h"#include"ospfd
/ospf_spf.h"#include"ospfd/ospf_dump.h"#include"ospfd/ospf_route.h"#include"ospf
d/ospf_ase.h"#include"ospfd/ospf_zebra.h"#include"ospfd/ospf_api.h"#include"ospf
d/ospf_apiserver.h"/*ThisisanimplementationofanAPItotheOSPFdaemonthatallows*exte
rnalapplicationstoaccesstheOSPFdaemonthroughsocket*connections.Theapplicationcan
usethisAPItoinjectitsown*opaqueLSAsandfloodthemtootherOSPFdaemons.OtherOSPF*daem
onsthenreceivetheseLSAsandinformapplicationsthroughthe*APIbysendingacorrespondin
gmessage.Theapplicationcanalso*registertoreceiveallLSAtypes(inadditiontoopaquety
pes)and*usethisinformationtoreconstructtheOSPF'sLSDB.TheOSPF*daemonsupportsmulti
pleapplicationsconcurrently.*//*Listofallactiveconnections.*/structlist*apiserve
r_list;/*-----------------------------------------------------------*Functionsto
lookupinterfaces*-----------------------------------------------------------*/st
ructospf_interface*ospf_apiserver_if_lookup_by_addr(structin_addraddress){struct
listnode*node,*nnode;structospf_interface*oi;structospf*ospf=NULL;ospf=ospf_look
up_by_vrf_id(VRF_DEFAULT);if(!ospf)returnNULL;for(ALL_LIST_ELEMENTS(ospf->oiflis
t,node,nnode,oi))if(oi->type!=OSPF_IFTYPE_VIRTUALLINK)if(IPV4_ADDR_SAME(&address
,&oi->address->u.prefix4))returnoi;returnNULL;}structospf_interface*ospf_apiserv
er_if_lookup_by_ifp(structinterface*ifp){structlistnode*node,*nnode;structospf_i
nterface*oi;structospf*ospf=NULL;ospf=ospf_lookup_by_vrf_id(VRF_DEFAULT);if(!osp
f)returnNULL;for(ALL_LIST_ELEMENTS(ospf->oiflist,node,nnode,oi))if(oi->ifp==ifp)
returnoi;returnNULL;}/*---------------------------------------------------------
--*Initialization*-----------------------------------------------------------*/u
nsignedshortospf_apiserver_getport(void){structservent*sp=getservbyname("ospfapi
","tcp");returnsp?ntohs(sp->s_port):OSPF_API_SYNC_PORT;}/*InitializeOSPFAPImodul
e.Invokedfromospf_opaque_init()*/intospf_apiserver_init(void){intfd;intrc=-1;/*C
reatenewsocketforsynchronousmessages.*/fd=ospf_apiserver_serv_sock_family(ospf_a
piserver_getport(),AF_INET);if(fd<0)gotoout;/*Schedulenewthreadthathandlesaccept
edconnections.*/ospf_apiserver_event(OSPF_APISERVER_ACCEPT,fd,NULL);/*Initialize
listthatkeepstrackofallconnections.*/apiserver_list=list_new();/*Registeropaque-
independentcallbackfunctions.ThesefunctionsareinvokedonISM,NSMchangesandLSAupdat
eandLSAdeletes*/rc=ospf_register_opaque_functab(0/*allLSAs*/,0/*allopaquetypes*/
,ospf_apiserver_new_if,ospf_apiserver_del_if,ospf_apiserver_ism_change,ospf_apis
erver_nsm_change,NULL,NULL,NULL,NULL,/*ospf_apiserver_show_info*/NULL,/*originat
or_func*/NULL,/*ospf_apiserver_lsa_refresher*/ospf_apiserver_lsa_update,ospf_api
server_lsa_delete);if(rc!=0){zlog_warn("ospf_apiserver_init:Failedtoregisteropaq
uetype[0/0]");}rc=0;out:returnrc;}/*TerminateOSPFAPImodule.*/voidospf_apiserver_
term(void){structospf_apiserver*apiserv;/*Unregisterwildcard[0/0]type*/ospf_dele
te_opaque_functab(0/*allLSAs*/,0/*allopaquetypes*/);/**Freeallclientinstances.os
pf_apiserver_freeremovesthenode*fromthelist,soweexaminetheheadofthelistaneweacht
ime.*/while(apiserver_list&&(apiserv=listgetdata(listhead(apiserver_list)))!=NUL
L)ospf_apiserver_free(apiserv);/*Freeclientlistitself*/if(apiserver_list)list_de
lete_and_null(&apiserver_list);/*Freewildcardlist*//*XXX*/}staticstructospf_apis
erver*lookup_apiserver(uint8_tlsa_type,uint8_topaque_type){structlistnode*n1,*n2
;structregistered_opaque_type*r;structospf_apiserver*apiserv,*found=NULL;/*XXX:t
hisapproachesO(n**2)*/for(ALL_LIST_ELEMENTS_RO(apiserver_list,n1,apiserv)){for(A
LL_LIST_ELEMENTS_RO(apiserv->opaque_types,n2,r))if(r->lsa_type==lsa_type&&r->opa
que_type==opaque_type){found=apiserv;gotoout;}}out:returnfound;}staticstructospf
_apiserver*lookup_apiserver_by_lsa(structospf_lsa*lsa){structlsa_header*lsah=lsa
->data;structospf_apiserver*found=NULL;if(IS_OPAQUE_LSA(lsah->type)){found=looku
p_apiserver(lsah->type,GET_OPAQUE_TYPE(ntohl(lsah->id.s_addr)));}returnfound;}/*
-----------------------------------------------------------*Followingsarefunctio
nstomanageclientconnections.*---------------------------------------------------
--------*/staticintospf_apiserver_new_lsa_hook(structospf_lsa*lsa){if(IS_DEBUG_O
SPF_EVENT)zlog_debug("API:PutLSA(%p)[%s]intoreserve,total=%ld",(void*)lsa,dump_l
sa_key(lsa),lsa->lsdb->total);return0;}staticintospf_apiserver_del_lsa_hook(stru
ctospf_lsa*lsa){if(IS_DEBUG_OSPF_EVENT)zlog_debug("API:GetLSA(%p)[%s]fromreserve
,total=%ld",(void*)lsa,dump_lsa_key(lsa),lsa->lsdb->total);return0;}/*Allocatene
wconnectionstructure.*/structospf_apiserver*ospf_apiserver_new(intfd_sync,intfd_
async){structospf_apiserver*new=XMALLOC(MTYPE_OSPF_APISERVER,sizeof(structospf_a
piserver));new->filter=XMALLOC(MTYPE_OSPF_APISERVER_MSGFILTER,sizeof(structlsa_f
ilter_type));new->fd_sync=fd_sync;new->fd_async=fd_async;/*listofregisteredopaqu
etypesthatapplicationuses*/new->opaque_types=list_new();/*Initializetemporarystr
ageforLSAinstancestoberefreshed.*/memset(&new->reserve,0,sizeof(structospf_lsdb)
);ospf_lsdb_init(&new->reserve);new->reserve.new_lsa_hook=ospf_apiserver_new_lsa
_hook;/*debug*/new->reserve.del_lsa_hook=ospf_apiserver_del_lsa_hook;/*debug*/ne
w->out_sync_fifo=msg_fifo_new();new->out_async_fifo=msg_fifo_new();new->t_sync_r
ead=NULL;#ifdefUSE_ASYNC_READnew->t_async_read=NULL;#endif/*USE_ASYNC_READ*/new-
>t_sync_write=NULL;new->t_async_write=NULL;new->filter->typemask=0;/*filterallLS
As*/new->filter->origin=ANY_ORIGIN;new->filter->num_areas=0;returnnew;}voidospf_
apiserver_event(enumeventevent,intfd,structospf_apiserver*apiserv){switch(event)
{caseOSPF_APISERVER_ACCEPT:(void)thread_add_read(master,ospf_apiserver_accept,ap
iserv,fd,NULL);break;caseOSPF_APISERVER_SYNC_READ:apiserv->t_sync_read=NULL;thre
ad_add_read(master,ospf_apiserver_read,apiserv,fd,&apiserv->t_sync_read);break;#
ifdefUSE_ASYNC_READcaseOSPF_APISERVER_ASYNC_READ:apiserv->t_async_read=NULL;thre
ad_add_read(master,ospf_apiserver_read,apiserv,fd,&apiserv->t_async_read);break;
#endif/*USE_ASYNC_READ*/caseOSPF_APISERVER_SYNC_WRITE:thread_add_write(master,os
pf_apiserver_sync_write,apiserv,fd,&apiserv->t_sync_write);break;caseOSPF_APISER
VER_ASYNC_WRITE:thread_add_write(master,ospf_apiserver_async_write,apiserv,fd,&a
piserv->t_async_write);break;}}/*Freeinstance.Firstunregisterallopaquetypesusedb
yapplication,flushopaqueLSAsinjectedbyapplicationfromnetworkandcloseconnection.*
/voidospf_apiserver_free(structospf_apiserver*apiserv){structlistnode*node;/*Can
celreadandwritethreads.*/if(apiserv->t_sync_read){thread_cancel(apiserv->t_sync_
read);}#ifdefUSE_ASYNC_READif(apiserv->t_async_read){thread_cancel(apiserv->t_as
ync_read);}#endif/*USE_ASYNC_READ*/if(apiserv->t_sync_write){thread_cancel(apise
rv->t_sync_write);}if(apiserv->t_async_write){thread_cancel(apiserv->t_async_wri
te);}/*UnregisterallopaquetypesthatapplicationregisteredandflushopaqueLSAsifstil
linLSDB.*/while((node=listhead(apiserv->opaque_types))!=NULL){structregistered_o
paque_type*regtype=listgetdata(node);ospf_apiserver_unregister_opaque_type(apise
rv,regtype->lsa_type,regtype->opaque_type);}/*CloseconnectionstoOSPFd.*/if(apise
rv->fd_sync>0){close(apiserv->fd_sync);}if(apiserv->fd_async>0){close(apiserv->f
d_async);}/*Freefifos*/msg_fifo_free(apiserv->out_sync_fifo);msg_fifo_free(apise
rv->out_async_fifo);/*CleartemporarystrageforLSAinstancestoberefreshed.*/ospf_ls
db_delete_all(&apiserv->reserve);ospf_lsdb_cleanup(&apiserv->reserve);/*Removefr
omthelistofactiveclients.*/listnode_delete(apiserver_list,apiserv);if(IS_DEBUG_O
SPF_EVENT)zlog_debug("API:Deleteapiserv(%p),total#(%d)",(void*)apiserv,apiserver
_list->count);/*Andfreeinstance.*/XFREE(MTYPE_OSPF_APISERVER,apiserv);}intospf_a
piserver_read(structthread*thread){structospf_apiserver*apiserv;structmsg*msg;in
tfd;intrc=-1;enumeventevent;apiserv=THREAD_ARG(thread);fd=THREAD_FD(thread);if(f
d==apiserv->fd_sync){event=OSPF_APISERVER_SYNC_READ;apiserv->t_sync_read=NULL;if
(IS_DEBUG_OSPF_EVENT)zlog_debug("API:ospf_apiserver_read:Peer:%s/%u",inet_ntoa(a
piserv->peer_sync.sin_addr),ntohs(apiserv->peer_sync.sin_port));}#ifdefUSE_ASYNC
_READelseif(fd==apiserv->fd_async){event=OSPF_APISERVER_ASYNC_READ;apiserv->t_as
ync_read=NULL;if(IS_DEBUG_OSPF_EVENT)zlog_debug("API:ospf_apiserver_read:Peer:%s
/%u",inet_ntoa(apiserv->peer_async.sin_addr),ntohs(apiserv->peer_async.sin_port)
);}#endif/*USE_ASYNC_READ*/else{zlog_warn("ospf_apiserver_read:Unknownfd(%d)",fd
);ospf_apiserver_free(apiserv);gotoout;}/*Readmessagefromfd.*/msg=msg_read(fd);i
f(msg==NULL){zlog_warn("ospf_apiserver_read:readfailedonfd=%d,closingconnection"
,fd);/*Performcleanup.*/ospf_apiserver_free(apiserv);gotoout;}if(IS_DEBUG_OSPF_E
VENT)msg_print(msg);/*Dispatchtocorrespondingmessagehandler.*/rc=ospf_apiserver_
handle_msg(apiserv,msg);/*Preparefornextmessage,addreadthread.*/ospf_apiserver_e
vent(event,fd,apiserv);msg_free(msg);out:returnrc;}intospf_apiserver_sync_write(
structthread*thread){structospf_apiserver*apiserv;structmsg*msg;intfd;intrc=-1;a
piserv=THREAD_ARG(thread);assert(apiserv);fd=THREAD_FD(thread);apiserv->t_sync_w
rite=NULL;/*Sanitycheck*/if(fd!=apiserv->fd_sync){zlog_warn("ospf_apiserver_sync
_write:Unknownfd=%d",fd);gotoout;}if(IS_DEBUG_OSPF_EVENT)zlog_debug("API:ospf_ap
iserver_sync_write:Peer:%s/%u",inet_ntoa(apiserv->peer_sync.sin_addr),ntohs(apis
erv->peer_sync.sin_port));/*Checkwhetherthereisreallyamessageinthefifo.*/msg=msg
_fifo_pop(apiserv->out_sync_fifo);if(!msg){zlog_warn("API:ospf_apiserver_sync_wr
ite:NomessageinSync-FIFO?");return0;}if(IS_DEBUG_OSPF_EVENT)msg_print(msg);rc=ms
g_write(fd,msg);/*Onceamessageisdequeued,itshouldbefreedanyway.*/msg_free(msg);i
f(rc<0){zlog_warn("ospf_apiserver_sync_write:writefailedonfd=%d",fd);gotoout;}/*
Ifmoremessagesareinsyncmessagefifo,schedulewritethread.*/if(msg_fifo_head(apiser
v->out_sync_fifo)){ospf_apiserver_event(OSPF_APISERVER_SYNC_WRITE,apiserv->fd_sy
nc,apiserv);}out:if(rc<0){/*Performcleanupanddisconnectwithpeer*/ospf_apiserver_
free(apiserv);}returnrc;}intospf_apiserver_async_write(structthread*thread){stru
ctospf_apiserver*apiserv;structmsg*msg;intfd;intrc=-1;apiserv=THREAD_ARG(thread)
;assert(apiserv);fd=THREAD_FD(thread);apiserv->t_async_write=NULL;/*Sanitycheck*
/if(fd!=apiserv->fd_async){zlog_warn("ospf_apiserver_async_write:Unknownfd=%d",f
d);gotoout;}if(IS_DEBUG_OSPF_EVENT)zlog_debug("API:ospf_apiserver_async_write:Pe
er:%s/%u",inet_ntoa(apiserv->peer_async.sin_addr),ntohs(apiserv->peer_async.sin_
port));/*Checkwhetherthereisreallyamessageinthefifo.*/msg=msg_fifo_pop(apiserv->
out_async_fifo);if(!msg){zlog_warn("API:ospf_apiserver_async_write:NomessageinAs
ync-FIFO?");return0;}if(IS_DEBUG_OSPF_EVENT)msg_print(msg);rc=msg_write(fd,msg);
/*Onceamessageisdequeued,itshouldbefreedanyway.*/msg_free(msg);if(rc<0){zlog_war
n("ospf_apiserver_async_write:writefailedonfd=%d",fd);gotoout;}/*Ifmoremessagesa
reinasyncmessagefifo,schedulewritethread.*/if(msg_fifo_head(apiserv->out_async_f
ifo)){ospf_apiserver_event(OSPF_APISERVER_ASYNC_WRITE,apiserv->fd_async,apiserv)
;}out:if(rc<0){/*Performcleanupanddisconnectwithpeer*/ospf_apiserver_free(apiser
v);}returnrc;}intospf_apiserver_serv_sock_family(unsignedshortport,intfamily){un
ionsockunionsu;intaccept_sock;intrc;memset(&su,0,sizeof(unionsockunion));su.sa.s
a_family=family;/*Makenewsocket*/accept_sock=sockunion_stream_socket(&su);if(acc
ept_sock<0)returnaccept_sock;/*Thisisaserver,soreuseaddressandport*/sockopt_reus
eaddr(accept_sock);sockopt_reuseport(accept_sock);/*Bindsockettoaddressandgivenp
ort.*/rc=sockunion_bind(accept_sock,&su,port,NULL);if(rc<0){close(accept_sock);/
*Closesocket*/returnrc;}/*Listensocketunderqueuelength3.*/rc=listen(accept_sock,
3);if(rc<0){zlog_warn("ospf_apiserver_serv_sock_family:listen:%s",safe_strerror(
errno));close(accept_sock);/*Closesocket*/returnrc;}returnaccept_sock;}/*Acceptc
onnectionrequestfromexternalapplications.Foreachacceptedconnectionallocateowncon
nectioninstance.*/intospf_apiserver_accept(structthread*thread){intaccept_sock;i
ntnew_sync_sock;intnew_async_sock;unionsockunionsu;structospf_apiserver*apiserv;
structsockaddr_inpeer_async;structsockaddr_inpeer_sync;unsignedintpeerlen;intret
;/*THREAD_ARG(thread)isNULL*/accept_sock=THREAD_FD(thread);/*Keephearingonsocket
forfurtherconnections.*/ospf_apiserver_event(OSPF_APISERVER_ACCEPT,accept_sock,N
ULL);memset(&su,0,sizeof(unionsockunion));/*Acceptconnectionforsynchronousmessag
es*/new_sync_sock=sockunion_accept(accept_sock,&su);if(new_sync_sock<0){zlog_war
n("ospf_apiserver_accept:accept:%s",safe_strerror(errno));return-1;}/*Getportadd
ressandportnumberofpeertomakereverseconnection.Thereversechannelusestheportnumbe
rofthepeerport+1.*/memset(&peer_sync,0,sizeof(structsockaddr_in));peerlen=sizeof
(structsockaddr_in);ret=getpeername(new_sync_sock,(structsockaddr*)&peer_sync,&p
eerlen);if(ret<0){zlog_warn("ospf_apiserver_accept:getpeername:%s",safe_strerror
(errno));close(new_sync_sock);return-1;}if(IS_DEBUG_OSPF_EVENT)zlog_debug("API:o
spf_apiserver_accept:Newpeer:%s/%u",inet_ntoa(peer_sync.sin_addr),ntohs(peer_syn
c.sin_port));/*Createnewsocketforasynchronousmessages.*/peer_async=peer_sync;pee
r_async.sin_port=htons(ntohs(peer_sync.sin_port)+1);/*Checkifremoteportnumbertom
akereverseconnectionisvalidone.*/if(ntohs(peer_async.sin_port)==ospf_apiserver_g
etport()){zlog_warn("API:ospf_apiserver_accept:Peer(%s/%u):Invalidasyncportnumbe
r?",inet_ntoa(peer_async.sin_addr),ntohs(peer_async.sin_port));close(new_sync_so
ck);return-1;}new_async_sock=socket(AF_INET,SOCK_STREAM,0);if(new_async_sock<0){
zlog_warn("ospf_apiserver_accept:socket:%s",safe_strerror(errno));close(new_sync
_sock);return-1;}ret=connect(new_async_sock,(structsockaddr*)&peer_async,sizeof(
structsockaddr_in));if(ret<0){zlog_warn("ospf_apiserver_accept:connect:%s",safe_
strerror(errno));close(new_sync_sock);close(new_async_sock);return-1;}#ifdefUSE_
ASYNC_READ#else/*USE_ASYNC_READ*//*Maketheasynchronouschannelwrite-only.*/ret=sh
utdown(new_async_sock,SHUT_RD);if(ret<0){zlog_warn("ospf_apiserver_accept:shutdo
wn:%s",safe_strerror(errno));close(new_sync_sock);close(new_async_sock);return-1
;}#endif/*USE_ASYNC_READ*//*Allocatenewserver-sideconnectionstructure*/apiserv=o
spf_apiserver_new(new_sync_sock,new_async_sock);/*Addtoactiveconnectionlist*/lis
tnode_add(apiserver_list,apiserv);apiserv->peer_sync=peer_sync;apiserv->peer_asy
nc=peer_async;/*Andaddreadthreadsfornewconnection*/ospf_apiserver_event(OSPF_API
SERVER_SYNC_READ,new_sync_sock,apiserv);#ifdefUSE_ASYNC_READospf_apiserver_event
(OSPF_APISERVER_ASYNC_READ,new_async_sock,apiserv);#endif/*USE_ASYNC_READ*/if(IS
_DEBUG_OSPF_EVENT)zlog_debug("API:Newapiserv(%p),total#(%d)",(void*)apiserv,apis
erver_list->count);return0;}/*--------------------------------------------------
---------*Sendreplywithreturncodetoclientapplication*---------------------------
--------------------------------*/staticintospf_apiserver_send_msg(structospf_ap
iserver*apiserv,structmsg*msg){structmsg_fifo*fifo;structmsg*msg2;enumeventevent
;intfd;switch(msg->hdr.msgtype){caseMSG_REPLY:fifo=apiserv->out_sync_fifo;fd=api
serv->fd_sync;event=OSPF_APISERVER_SYNC_WRITE;break;caseMSG_READY_NOTIFY:caseMSG
_LSA_UPDATE_NOTIFY:caseMSG_LSA_DELETE_NOTIFY:caseMSG_NEW_IF:caseMSG_DEL_IF:caseM
SG_ISM_CHANGE:caseMSG_NSM_CHANGE:fifo=apiserv->out_async_fifo;fd=apiserv->fd_asy
nc;event=OSPF_APISERVER_ASYNC_WRITE;break;default:zlog_warn("ospf_apiserver_send
_msg:Unknownmessagetype%d",msg->hdr.msgtype);return-1;}/*Makeacopyofthemessagean
dputinthefifo.Oncethefifogetsdrainedbythewritethread,themessagewillbefreed.*//*N
B:Given"msg"isuntouchedinthisfunction.*/msg2=msg_dup(msg);/*Enqueuemessageintoco
rrespondingfifoqueue*/msg_fifo_push(fifo,msg2);/*Schedulewritethread*/ospf_apise
rver_event(event,fd,apiserv);return0;}intospf_apiserver_send_reply(structospf_ap
iserver*apiserv,uint32_tseqnr,uint8_trc){structmsg*msg=new_msg_reply(seqnr,rc);i
ntret;if(!msg){zlog_warn("ospf_apiserver_send_reply:msg_newfailed");#ifdefNOTYET
/*Cannotallocatenewmessage.Whatshouldwedo?*/ospf_apiserver_free(apiserv);#endifr
eturn-1;}ret=ospf_apiserver_send_msg(apiserv,msg);msg_free(msg);returnret;}/*---
--------------------------------------------------------*Genericmessagedispatchi
nghandlerfunction*-----------------------------------------------------------*/i
ntospf_apiserver_handle_msg(structospf_apiserver*apiserv,structmsg*msg){intrc;/*
Callcorrespondingmessagehandlerfunction.*/switch(msg->hdr.msgtype){caseMSG_REGIS
TER_OPAQUETYPE:rc=ospf_apiserver_handle_register_opaque_type(apiserv,msg);break;
caseMSG_UNREGISTER_OPAQUETYPE:rc=ospf_apiserver_handle_unregister_opaque_type(ap
iserv,msg);break;caseMSG_REGISTER_EVENT:rc=ospf_apiserver_handle_register_event(
apiserv,msg);break;caseMSG_SYNC_LSDB:rc=ospf_apiserver_handle_sync_lsdb(apiserv,
msg);break;caseMSG_ORIGINATE_REQUEST:rc=ospf_apiserver_handle_originate_request(
apiserv,msg);break;caseMSG_DELETE_REQUEST:rc=ospf_apiserver_handle_delete_reques
t(apiserv,msg);break;default:zlog_warn("ospf_apiserver_handle_msg:Unknownmessage
type:%d",msg->hdr.msgtype);rc=-1;}returnrc;}/*----------------------------------
-------------------------*Followingarefunctionsforopaquetyperegistration*-------
----------------------------------------------------*/intospf_apiserver_register
_opaque_type(structospf_apiserver*apiserv,uint8_tlsa_type,uint8_topaque_type){st
ructregistered_opaque_type*regtype;int(*originator_func)(void*arg);intrc;switch(
lsa_type){caseOSPF_OPAQUE_LINK_LSA:originator_func=ospf_apiserver_lsa9_originato
r;break;caseOSPF_OPAQUE_AREA_LSA:originator_func=ospf_apiserver_lsa10_originator
;break;caseOSPF_OPAQUE_AS_LSA:originator_func=ospf_apiserver_lsa11_originator;br
eak;default:zlog_warn("ospf_apiserver_register_opaque_type:lsa_type(%d)",lsa_typ
e);returnOSPF_API_ILLEGALLSATYPE;}/*Registeropaquefunctiontable*//*NB:Duplicated
registrationwillbedetectedinsidethefunction.*/rc=ospf_register_opaque_functab(ls
a_type,opaque_type,NULL,/*ospf_apiserver_new_if*/NULL,/*ospf_apiserver_del_if*/N
ULL,/*ospf_apiserver_ism_change*/NULL,/*ospf_apiserver_nsm_change*/NULL,NULL,NUL
L,ospf_apiserver_show_info,originator_func,ospf_apiserver_lsa_refresher,NULL,/*o
spf_apiserver_lsa_update*/NULL/*ospf_apiserver_lsa_delete*/);if(rc!=0){zlog_warn
("Failedtoregisteropaquetype[%d/%d]",lsa_type,opaque_type);returnOSPF_API_OPAQUE
TYPEINUSE;}/*Remembertheopaquetypethatapplicationregisterssowhenconnectionshutsd
own,wecanflushallLSAsofthisopaquetype.*/regtype=XCALLOC(MTYPE_OSPF_APISERVER,siz
eof(structregistered_opaque_type));regtype->lsa_type=lsa_type;regtype->opaque_ty
pe=opaque_type;/*Addtolistofregisteredopaquetypes*/listnode_add(apiserv->opaque_
types,regtype);if(IS_DEBUG_OSPF_EVENT)zlog_debug("API:AddLSA-type(%d)/Opaque-typ
e(%d)into""apiserv(%p),total#(%d)",lsa_type,opaque_type,(void*)apiserv,listcount
(apiserv->opaque_types));return0;}intospf_apiserver_unregister_opaque_type(struc
tospf_apiserver*apiserv,uint8_tlsa_type,uint8_topaque_type){structlistnode*node,
*nnode;structregistered_opaque_type*regtype;for(ALL_LIST_ELEMENTS(apiserv->opaqu
e_types,node,nnode,regtype)){/*Checkifwereallyregisteredthisopaquetype*/if(regty
pe->lsa_type==lsa_type&&regtype->opaque_type==opaque_type){/*Yes,weregisteredthi
sopaquetype.FlushallexistingopaqueLSAsofthistype*/ospf_apiserver_flush_opaque_ls
a(apiserv,lsa_type,opaque_type);ospf_delete_opaque_functab(lsa_type,opaque_type)
;/*Removefromlistofregisteredopaquetypes*/listnode_delete(apiserv->opaque_types,
regtype);if(IS_DEBUG_OSPF_EVENT)zlog_debug("API:DelLSA-type(%d)/Opaque-type(%d)"
"fromapiserv(%p),total#(%d)",lsa_type,opaque_type,(void*)apiserv,listcount(apise
rv->opaque_types));return0;}}/*Opaquetypeisnotregistered*/zlog_warn("Failedtounr
egisteropaquetype[%d/%d]",lsa_type,opaque_type);returnOSPF_API_OPAQUETYPENOTREGI
STERED;}staticintapiserver_is_opaque_type_registered(structospf_apiserver*apiser
v,uint8_tlsa_type,uint8_topaque_type){structlistnode*node,*nnode;structregistere
d_opaque_type*regtype;/*XXX:howmanytypesarethere?iffew,whynotjustabitmap?*/for(A
LL_LIST_ELEMENTS(apiserv->opaque_types,node,nnode,regtype)){/*Checkifwereallyreg
isteredthisopaquetype*/if(regtype->lsa_type==lsa_type&&regtype->opaque_type==opa
que_type){/*Yesregistered*/return1;}}/*Notregistered*/return0;}intospf_apiserver
_handle_register_opaque_type(structospf_apiserver*apiserv,structmsg*msg){structm
sg_register_opaque_type*rmsg;uint8_tlsa_type;uint8_topaque_type;intrc=0;/*Extrac
tparametersfromregisteropaquetypemessage*/rmsg=(structmsg_register_opaque_type*)
STREAM_DATA(msg->s);lsa_type=rmsg->lsatype;opaque_type=rmsg->opaquetype;rc=ospf_
apiserver_register_opaque_type(apiserv,lsa_type,opaque_type);/*Sendareplybacktoc
lientincludingreturncode*/rc=ospf_apiserver_send_reply(apiserv,ntohl(msg->hdr.ms
gseq),rc);if(rc<0)gotoout;/*Nowinformapplicationaboutopaquetypesthatareready*/sw
itch(lsa_type){caseOSPF_OPAQUE_LINK_LSA:ospf_apiserver_notify_ready_type9(apiser
v);break;caseOSPF_OPAQUE_AREA_LSA:ospf_apiserver_notify_ready_type10(apiserv);br
eak;caseOSPF_OPAQUE_AS_LSA:ospf_apiserver_notify_ready_type11(apiserv);break;}ou
t:returnrc;}/*Notifyspecificclientaboutallopaquetypes9thatareready.*/voidospf_ap
iserver_notify_ready_type9(structospf_apiserver*apiserv){structlistnode*node,*nn
ode;structlistnode*node2,*nnode2;structospf*ospf;structospf_interface*oi;structr
egistered_opaque_type*r;ospf=ospf_lookup_by_vrf_id(VRF_DEFAULT);for(ALL_LIST_ELE
MENTS(ospf->oiflist,node,nnode,oi)){/*Checkifthisinterfaceisindeedreadyfortype9*
/if(!ospf_apiserver_is_ready_type9(oi))continue;/*Checkforregisteredopaquetype9t
ypes*//*XXX:loop-de-loop-optimiseme*/for(ALL_LIST_ELEMENTS(apiserv->opaque_types
,node2,nnode2,r)){structmsg*msg;if(r->lsa_type==OSPF_OPAQUE_LINK_LSA){/*Yes,this
opaquetypeisready*/msg=new_msg_ready_notify(0,OSPF_OPAQUE_LINK_LSA,r->opaque_typ
e,oi->address->u.prefix4);if(!msg){zlog_warn("apiserver_notify_ready_type9:msg_n
ewfailed");#ifdefNOTYET/*Cannotallocatenewmessage.What*shouldwedo?*/ospf_apiserv
er_free(apiserv);#endifgotoout;}ospf_apiserver_send_msg(apiserv,msg);msg_free(ms
g);}}}out:return;}/*Notifyspecificclientaboutallopaquetypes10thatareready.*/void
ospf_apiserver_notify_ready_type10(structospf_apiserver*apiserv){structlistnode*
node,*nnode;structlistnode*node2,*nnode2;structospf*ospf;structospf_area*area;os
pf=ospf_lookup_by_vrf_id(VRF_DEFAULT);for(ALL_LIST_ELEMENTS(ospf->areas,node,nno
de,area)){structregistered_opaque_type*r;if(!ospf_apiserver_is_ready_type10(area
)){continue;}/*Checkforregisteredopaquetype10types*//*XXX:loopinloop-optimiseme*
/for(ALL_LIST_ELEMENTS(apiserv->opaque_types,node2,nnode2,r)){structmsg*msg;if(r
->lsa_type==OSPF_OPAQUE_AREA_LSA){/*Yes,thisopaquetypeisready*/msg=new_msg_ready
_notify(0,OSPF_OPAQUE_AREA_LSA,r->opaque_type,area->area_id);if(!msg){zlog_warn(
"apiserver_notify_ready_type10:msg_newfailed");#ifdefNOTYET/*Cannotallocatenewme
ssage.What*shouldwedo?*/ospf_apiserver_free(apiserv);#endifgotoout;}ospf_apiserv
er_send_msg(apiserv,msg);msg_free(msg);}}}out:return;}/*Notifyspecificclientabou
tallopaquetypes11thatareready*/voidospf_apiserver_notify_ready_type11(structospf
_apiserver*apiserv){structlistnode*node,*nnode;structospf*ospf;structregistered_
opaque_type*r;ospf=ospf_lookup_by_vrf_id(VRF_DEFAULT);/*Cantype11beoriginated?*/
if(!ospf_apiserver_is_ready_type11(ospf))gotoout;/*Checkforregisteredopaquetype1
1types*/for(ALL_LIST_ELEMENTS(apiserv->opaque_types,node,nnode,r)){structmsg*msg
;structin_addrnoarea_id={.s_addr=0L};if(r->lsa_type==OSPF_OPAQUE_AS_LSA){/*Yes,t
hisopaquetypeisready*/msg=new_msg_ready_notify(0,OSPF_OPAQUE_AS_LSA,r->opaque_ty
pe,noarea_id);if(!msg){zlog_warn("apiserver_notify_ready_type11:msg_newfailed");
#ifdefNOTYET/*Cannotallocatenewmessage.Whatshouldwe*do?*/ospf_apiserver_free(api
serv);#endifgotoout;}ospf_apiserver_send_msg(apiserv,msg);msg_free(msg);}}out:re
turn;}intospf_apiserver_handle_unregister_opaque_type(structospf_apiserver*apise
rv,structmsg*msg){structmsg_unregister_opaque_type*umsg;uint8_tltype;uint8_totyp
e;intrc=0;/*Extractparametersfromunregisteropaquetypemessage*/umsg=(structmsg_un
register_opaque_type*)STREAM_DATA(msg->s);ltype=umsg->lsatype;otype=umsg->opaque
type;rc=ospf_apiserver_unregister_opaque_type(apiserv,ltype,otype);/*Sendareplyb
acktoclientincludingreturncode*/rc=ospf_apiserver_send_reply(apiserv,ntohl(msg->
hdr.msgseq),rc);returnrc;}/*----------------------------------------------------
-------*Followingarefunctionsforevent(filter)registration.*---------------------
--------------------------------------*/intospf_apiserver_handle_register_event(
structospf_apiserver*apiserv,structmsg*msg){structmsg_register_event*rmsg;intrc;
uint32_tseqnum;rmsg=(structmsg_register_event*)STREAM_DATA(msg->s);/*Getrequests
equencenumber*/seqnum=msg_get_seq(msg);/*Freeexistingfilterinapiserv.*/XFREE(MTY
PE_OSPF_APISERVER_MSGFILTER,apiserv->filter);/*Allocnewspaceforfilter.*/apiserv-
>filter=XMALLOC(MTYPE_OSPF_APISERVER_MSGFILTER,ntohs(msg->hdr.msglen));if(apiser
v->filter){/*copyitover.*/memcpy(apiserv->filter,&rmsg->filter,ntohs(msg->hdr.ms
glen));rc=OSPF_API_OK;}else{rc=OSPF_API_NOMEMORY;}/*Sendareplybacktoclientwithre
turncode*/rc=ospf_apiserver_send_reply(apiserv,seqnum,rc);returnrc;}/*----------
-------------------------------------------------*FollowingsarefunctionsforLSDBs
ynchronization.*-----------------------------------------------------------*/sta
ticintapiserver_sync_callback(structospf_lsa*lsa,void*p_arg,intint_arg){structos
pf_apiserver*apiserv;intseqnum;structmsg*msg;structparam_t{structospf_apiserver*
apiserv;structlsa_filter_type*filter;}*param;intrc=-1;/*Sanitycheck*/assert(lsa-
>data);assert(p_arg);param=(structparam_t*)p_arg;apiserv=param->apiserv;seqnum=(
uint32_t)int_arg;/*Checkorigininfilter.*/if((param->filter->origin==ANY_ORIGIN)|
|(param->filter->origin==(lsa->flags&OSPF_LSA_SELF))){/*DefaultareaforAS-Externa
landOpaque11LSAs*/structin_addrarea_id={.s_addr=0L};/*DefaultinterfacefornonOpaq
ue9LSAs*/structin_addrifaddr={.s_addr=0L};if(lsa->area){area_id=lsa->area->area_
id;}if(lsa->data->type==OSPF_OPAQUE_LINK_LSA){ifaddr=lsa->oi->address->u.prefix4
;}msg=new_msg_lsa_change_notify(MSG_LSA_UPDATE_NOTIFY,seqnum,ifaddr,area_id,lsa-
>flags&OSPF_LSA_SELF,lsa->data);if(!msg){zlog_warn("apiserver_sync_callback:new_
msg_updatefailed");#ifdefNOTYET/*Cannotallocatenewmessage.Whatshouldwedo?*//*osp
f_apiserver_free(apiserv);*//*DonothinghereXXX*/#endifgotoout;}/*SendLSA*/ospf_a
piserver_send_msg(apiserv,msg);msg_free(msg);}rc=0;out:returnrc;}intospf_apiserv
er_handle_sync_lsdb(structospf_apiserver*apiserv,structmsg*msg){structlistnode*n
ode,*nnode;uint32_tseqnum;intrc=0;structmsg_sync_lsdb*smsg;structospf_apiserver_
param_t{structospf_apiserver*apiserv;structlsa_filter_type*filter;}param;uint16_
tmask;structroute_node*rn;structospf_lsa*lsa;structospf*ospf;structospf_area*are
a;ospf=ospf_lookup_by_vrf_id(VRF_DEFAULT);/*Getrequestsequencenumber*/seqnum=msg
_get_seq(msg);/*Setsyncmsg.*/smsg=(structmsg_sync_lsdb*)STREAM_DATA(msg->s);/*Se
tparameterstruct.*/param.apiserv=apiserv;param.filter=&smsg->filter;/*Rememberma
sk.*/mask=ntohs(smsg->filter.typemask);/*Iterateoverallareas.*/for(ALL_LIST_ELEM
ENTS(ospf->areas,node,nnode,area)){inti;uint32_t*area_id=NULL;/*Comparearea_idwi
tharea_idsinsyncrequest.*/if((i=smsg->filter.num_areas)>0){/*Letarea_idpointtoth
elistofareaIDs,*whichisattheendofsmsg->filter.*/area_id=(uint32_t*)(&smsg->filte
r+1);while(i){if(*area_id==area->area_id.s_addr){break;}i--;area_id++;}}else{i=1
;}/*Ifareawasfound,theni>0here.*/if(i){/*Checkmsgtype.*/if(mask&Power2[OSPF_ROUT
ER_LSA])LSDB_LOOP(ROUTER_LSDB(area),rn,lsa)apiserver_sync_callback(lsa,(void*)&p
aram,seqnum);if(mask&Power2[OSPF_NETWORK_LSA])LSDB_LOOP(NETWORK_LSDB(area),rn,ls
a)apiserver_sync_callback(lsa,(void*)&param,seqnum);if(mask&Power2[OSPF_SUMMARY_
LSA])LSDB_LOOP(SUMMARY_LSDB(area),rn,lsa)apiserver_sync_callback(lsa,(void*)&par
am,seqnum);if(mask&Power2[OSPF_ASBR_SUMMARY_LSA])LSDB_LOOP(ASBR_SUMMARY_LSDB(are
a),rn,lsa)apiserver_sync_callback(lsa,(void*)&param,seqnum);if(mask&Power2[OSPF_
OPAQUE_LINK_LSA])LSDB_LOOP(OPAQUE_LINK_LSDB(area),rn,lsa)apiserver_sync_callback
(lsa,(void*)&param,seqnum);if(mask&Power2[OSPF_OPAQUE_AREA_LSA])LSDB_LOOP(OPAQUE
_AREA_LSDB(area),rn,lsa)apiserver_sync_callback(lsa,(void*)&param,seqnum);}}/*Fo
rAS-externalLSAs*/if(ospf->lsdb){if(mask&Power2[OSPF_AS_EXTERNAL_LSA])LSDB_LOOP(
EXTERNAL_LSDB(ospf),rn,lsa)apiserver_sync_callback(lsa,(void*)&param,seqnum);}/*
ForAS-externalopaqueLSAs*/if(ospf->lsdb){if(mask&Power2[OSPF_OPAQUE_AS_LSA])LSDB
_LOOP(OPAQUE_AS_LSDB(ospf),rn,lsa)apiserver_sync_callback(lsa,(void*)&param,seqn
um);}/*Sendareplybacktoclientwithreturncode*/rc=ospf_apiserver_send_reply(apiser
v,seqnum,rc);returnrc;}/*-------------------------------------------------------
----*FollowingsarefunctionstooriginateorupdateLSA*fromanapplication.*-----------
------------------------------------------------*//*CreateanewinternalopaqueLSAb
ytakingprototypeandfillinginmissingfieldssuchasage,sequencenumber,advertisingrou
ter,checksumandsoon.Theinterfaceparameterisusedfortype9LSAs,areaparameterfortype
10.Type11LSAsdoneitherneedareanorinterface.*/structospf_lsa*ospf_apiserver_opaqu
e_lsa_new(structospf_area*area,structospf_interface*oi,structlsa_header*protolsa
){structstream*s;structlsa_header*newlsa;structospf_lsa*new=NULL;uint8_toptions=
0x0;uint16_tlength;structospf*ospf;if(oi&&oi->ospf)ospf=oi->ospf;elseospf=ospf_l
ookup_by_vrf_id(VRF_DEFAULT);assert(ospf);/*CreateastreamforinternalopaqueLSA*/i
f((s=stream_new(OSPF_MAX_LSA_SIZE))==NULL){zlog_warn("ospf_apiserver_opaque_lsa_
new:stream_newfailed");returnNULL;}newlsa=(structlsa_header*)STREAM_DATA(s);/*XX
XIfthisisalink-localLSAoranAS-externalLSA,howdowehavetosetoptions?*/if(area){opt
ions=LSA_OPTIONS_GET(area);options|=LSA_OPTIONS_NSSA_GET(area);}options|=OSPF_OP
TION_O;/*Don'tforgettosetoptionbit*/if(IS_DEBUG_OSPF(lsa,LSA_GENERATE)){zlog_deb
ug("LSA[Type%d:%s]:CreatinganOpaque-LSAinstance",protolsa->type,inet_ntoa(protol
sa->id));}/*Setopaque-LSAheaderfields.*/lsa_header_set(s,options,protolsa->type,
protolsa->id,ospf->router_id);/*Setopaque-LSAbodyfields.*/stream_put(s,((uint8_t
*)protolsa)+sizeof(structlsa_header),ntohs(protolsa->length)-sizeof(structlsa_he
ader));/*DeterminelengthofLSA.*/length=stream_get_endp(s);newlsa->length=htons(l
ength);/*CreateOSPFLSA.*/if((new=ospf_lsa_new())==NULL){zlog_warn("ospf_apiserve
r_opaque_lsa_new:ospf_lsa_new()?");stream_free(s);returnNULL;}if((new->data=ospf
_lsa_data_new(length))==NULL){zlog_warn("ospf_apiserver_opaque_lsa_new:ospf_lsa_
data_new()?");ospf_lsa_unlock(&new);stream_free(s);returnNULL;}new->area=area;ne
w->oi=oi;new->vrf_id=ospf->vrf_id;SET_FLAG(new->flags,OSPF_LSA_SELF);memcpy(new-
>data,newlsa,length);stream_free(s);returnnew;}intospf_apiserver_is_ready_type9(
structospf_interface*oi){/*Type9opaqueLSAcanbeoriginatedifthereisatleastoneactiv
eopaque-capableneighborattachedtotheoutgoinginterface.*/return(ospf_nbr_count_op
aque_capable(oi)>0);}intospf_apiserver_is_ready_type10(structospf_area*area){/*T
ype10opaqueLSAcanbeoriginatedifthereisatleastoneinterfacebelongingtotheareathath
asanactiveopaque-capableneighbor.*/structlistnode*node,*nnode;structospf_interfa
ce*oi;for(ALL_LIST_ELEMENTS(area->oiflist,node,nnode,oi))/*Isthereanactiveneighb
orattachedtothisinterface?*/if(ospf_apiserver_is_ready_type9(oi))return1;/*Noact
iveneighborinarea*/return0;}intospf_apiserver_is_ready_type11(structospf*ospf){/
*Type11opaqueLSAcanbeoriginatedifthereisatleastoneinterfacethathasanactiveopaque
-capableneighbor.*/structlistnode*node,*nnode;structospf_interface*oi;for(ALL_LI
ST_ELEMENTS(ospf->oiflist,node,nnode,oi))/*Isthereanactiveneighborattachedtothis
interface?*/if(ospf_apiserver_is_ready_type9(oi))return1;/*Noactiveneighboratall
*/return0;}intospf_apiserver_handle_originate_request(structospf_apiserver*apise
rv,structmsg*msg){structmsg_originate_request*omsg;structlsa_header*data;structo
spf_lsa*new;structospf_lsa*old;structospf_area*area=NULL;structospf_interface*oi
=NULL;structospf_lsdb*lsdb=NULL;structospf*ospf;intlsa_type,opaque_type;intready
=0;intrc=0;ospf=ospf_lookup_by_vrf_id(VRF_DEFAULT);/*ExtractopaqueLSAdatafrommes
sage*/omsg=(structmsg_originate_request*)STREAM_DATA(msg->s);data=&omsg->data;/*
Determineinterfacefortype9orareafortype10LSAs.*/switch(data->type){caseOSPF_OPAQ
UE_LINK_LSA:oi=ospf_apiserver_if_lookup_by_addr(omsg->ifaddr);if(!oi){zlog_warn(
"apiserver_originate:unknowninterface%s",inet_ntoa(omsg->ifaddr));rc=OSPF_API_NO
SUCHINTERFACE;gotoout;}area=oi->area;lsdb=area->lsdb;break;caseOSPF_OPAQUE_AREA_
LSA:area=ospf_area_lookup_by_area_id(ospf,omsg->area_id);if(!area){zlog_warn("ap
iserver_originate:unknownarea%s",inet_ntoa(omsg->area_id));rc=OSPF_API_NOSUCHARE
A;gotoout;}lsdb=area->lsdb;break;caseOSPF_OPAQUE_AS_LSA:lsdb=ospf->lsdb;break;de
fault:/*Wecanonlyhandleopaquetypeshere*/zlog_warn("apiserver_originate:Cannotori
ginatenon-opaqueLSAtype%d",data->type);rc=OSPF_API_ILLEGALLSATYPE;gotoout;}/*Che
ckifweregisteredthisopaquetype*/lsa_type=data->type;opaque_type=GET_OPAQUE_TYPE(
ntohl(data->id.s_addr));if(!apiserver_is_opaque_type_registered(apiserv,lsa_type
,opaque_type)){zlog_warn("apiserver_originate:LSA-type(%d)/Opaque-type(%d):Notre
gistered",lsa_type,opaque_type);rc=OSPF_API_OPAQUETYPENOTREGISTERED;gotoout;}/*M
akesurethattheneighborsarereadybeforewecanoriginate*/switch(data->type){caseOSPF
_OPAQUE_LINK_LSA:ready=ospf_apiserver_is_ready_type9(oi);break;caseOSPF_OPAQUE_A
REA_LSA:ready=ospf_apiserver_is_ready_type10(area);break;caseOSPF_OPAQUE_AS_LSA:
ready=ospf_apiserver_is_ready_type11(ospf);break;default:break;}if(!ready){zlog_
warn("Neighborsnotreadytooriginatetype%d",data->type);rc=OSPF_API_NOTREADY;gotoo
ut;}/*CreateOSPF'sinternalopaqueLSArepresentation*/new=ospf_apiserver_opaque_lsa
_new(area,oi,data);if(!new){rc=OSPF_API_NOMEMORY;/*XXX*/gotoout;}/*DetermineifLS
Aisneworanupdateforanexistingone.*/old=ospf_lsdb_lookup(lsdb,new);if(!old){/*New
LSAinstallinLSDB.*/rc=ospf_apiserver_originate1(new);}else{/**KeepthenewLSAinsta
nceinthe"waitingplace"untilthe*next*refreshtiming.IfseveralLSAupdaterequestsfort
hesame*LSID*haveissuedbypeer,thelastonetakeseffect.*/new->lsdb=&apiserv->reserve
;ospf_lsdb_add(&apiserv->reserve,new);/*Kicktheschedulerfunction.*/ospf_opaque_l
sa_refresh_schedule(old);}out:/*Sendareplybacktoclientwithreturncode*/rc=ospf_ap
iserver_send_reply(apiserv,ntohl(msg->hdr.msgseq),rc);returnrc;}/*--------------
---------------------------------------------*FloodanLSAwithinitsfloodingscope.*
-----------------------------------------------------------*//*XXXWecanprobablyu
seospf_flood_throughinsteadofthisfunctionbutthenweneedtheneighborparameter.Ifwes
etnbrtoNULLthenospf_flood_throughcrashesduetodereferencingNULL.*/voidospf_apiser
ver_flood_opaque_lsa(structospf_lsa*lsa){assert(lsa);switch(lsa->data->type){cas
eOSPF_OPAQUE_LINK_LSA:/*Incrementcounters?XXX*//*FloodLSAthroughlocalnetwork.*/o
spf_flood_through_area(lsa->area,NULL/*nbr*/,lsa);break;caseOSPF_OPAQUE_AREA_LSA
:/*UpdateLSAoriginationcount.*/assert(lsa->area);lsa->area->ospf->lsa_originate_
count++;/*FloodLSAthrougharea.*/ospf_flood_through_area(lsa->area,NULL/*nbr*/,ls
a);break;caseOSPF_OPAQUE_AS_LSA:{structospf*ospf;ospf=ospf_lookup_by_vrf_id(VRF_
DEFAULT);assert(ospf);/*Incrementcounters?XXX*//*FloodLSAthroughAS.*/ospf_flood_
through_as(ospf,NULL/*nbr*/,lsa);break;}}}intospf_apiserver_originate1(structosp
f_lsa*lsa){structospf*ospf;ospf=ospf_lookup_by_vrf_id(VRF_DEFAULT);assert(ospf);
/*InstallthisLSAintoLSDB.*/if(ospf_lsa_install(ospf,lsa->oi,lsa)==NULL){zlog_war
n("ospf_apiserver_originate1:ospf_lsa_installfailed");return-1;}/*FloodLSAwithin
scope*/#ifdefNOTYET/**NB:Modifiedversionof"ospf_flood_though()"acceptsNULL"inbr"
*parameter,andthusitdoesnotcauseSIGSEGVerror.*/ospf_flood_through(NULL/*nbr*/,ls
a);#else/*NOTYET*/ospf_apiserver_flood_opaque_lsa(lsa);#endif/*NOTYET*/return0;}
/*OpaqueLSAsoftype9onaspecificinterfacecannowbeoriginated.Tellclientsthatregiste
redtype9.*/intospf_apiserver_lsa9_originator(void*arg){structospf_interface*oi;o
i=(structospf_interface*)arg;if(listcount(apiserver_list)>0){ospf_apiserver_clie
nts_notify_ready_type9(oi);}return0;}intospf_apiserver_lsa10_originator(void*arg
){structospf_area*area;area=(structospf_area*)arg;if(listcount(apiserver_list)>0
){ospf_apiserver_clients_notify_ready_type10(area);}return0;}intospf_apiserver_l
sa11_originator(void*arg){structospf*ospf;ospf=(structospf*)arg;if(listcount(api
server_list)>0){ospf_apiserver_clients_notify_ready_type11(ospf);}return0;}/*Per
iodicallyrefreshopaqueLSAssothattheydonotexpireinotherrouters.*/structospf_lsa*o
spf_apiserver_lsa_refresher(structospf_lsa*lsa){structospf_apiserver*apiserv;str
uctospf_lsa*new=NULL;structospf*ospf;ospf=ospf_lookup_by_vrf_id(VRF_DEFAULT);ass
ert(ospf);apiserv=lookup_apiserver_by_lsa(lsa);if(!apiserv){zlog_warn("ospf_apis
erver_lsa_refresher:LSA[%s]:Noapiserver?",dump_lsa_key(lsa));lsa->data->ls_age=h
tons(OSPF_LSA_MAXAGE);/*Flushitanyway.*/}if(IS_LSA_MAXAGE(lsa)){ospf_opaque_lsa_
flush_schedule(lsa);gotoout;}/*CheckifupdatedversionofLSAinstancehasalreadyprepa
red.*/new=ospf_lsdb_lookup(&apiserv->reserve,lsa);if(!new){/*Thisisaperiodicrefr
esh,drivenbycoreOSPFmechanism.*/new=ospf_apiserver_opaque_lsa_new(lsa->area,lsa-
>oi,lsa->data);if(!new){zlog_warn("ospf_apiserver_lsa_refresher:Cannotcreateanew
LSA?");gotoout;}}else{/*Thisisaforciblerefresh,requestedbyOSPF-APIclient.*/ospf_
lsdb_delete(&apiserv->reserve,new);new->lsdb=NULL;}/*Incrementsequencenumber*/ne
w->data->ls_seqnum=lsa_seqnum_increment(lsa);/*NewLSAisinsamearea.*/new->area=ls
a->area;SET_FLAG(new->flags,OSPF_LSA_SELF);/*InstallLSAintoLSDB.*/if(ospf_lsa_in
stall(ospf,new->oi,new)==NULL){zlog_warn("ospf_apiserver_lsa_refresher:ospf_lsa_
installfailed");ospf_lsa_unlock(&new);gotoout;}/*FloodupdatedLSAthroughinterface
,areaorAS*/#ifdefNOTYETospf_flood_through(NULL/*nbr*/,new);#endif/*NOTYET*/ospf_
apiserver_flood_opaque_lsa(new);/*Debuglogging.*/if(IS_DEBUG_OSPF(lsa,LSA_GENERA
TE)){zlog_debug("LSA[Type%d:%s]:RefreshOpaqueLSA",new->data->type,inet_ntoa(new-
>data->id));ospf_lsa_header_dump(new->data);}out:returnnew;}/*------------------
-----------------------------------------*FollowingsarefunctionstodeleteLSAs*---
--------------------------------------------------------*/intospf_apiserver_hand
le_delete_request(structospf_apiserver*apiserv,structmsg*msg){structmsg_delete_r
equest*dmsg;structospf_lsa*old;structospf_area*area=NULL;structin_addrid;intlsa_
type,opaque_type;intrc=0;structospf*ospf;ospf=ospf_lookup_by_vrf_id(VRF_DEFAULT)
;assert(ospf);/*ExtractopaqueLSAfrommessage*/dmsg=(structmsg_delete_request*)STR
EAM_DATA(msg->s);/*Lookupareaforlink-localandarea-localopaqueLSAs*/switch(dmsg->
lsa_type){caseOSPF_OPAQUE_LINK_LSA:caseOSPF_OPAQUE_AREA_LSA:area=ospf_area_looku
p_by_area_id(ospf,dmsg->area_id);if(!area){zlog_warn("ospf_apiserver_lsa_delete:
unknownarea%s",inet_ntoa(dmsg->area_id));rc=OSPF_API_NOSUCHAREA;gotoout;}break;c
aseOSPF_OPAQUE_AS_LSA:/*AS-externalopaqueLSAshavenodesignatedarea*/area=NULL;bre
ak;default:zlog_warn("ospf_apiserver_lsa_delete:Cannotdeletenon-opaqueLSAtype%d"
,dmsg->lsa_type);rc=OSPF_API_ILLEGALLSATYPE;gotoout;}/*Checkifweregisteredthisop
aquetype*/lsa_type=dmsg->lsa_type;opaque_type=dmsg->opaque_type;if(!apiserver_is
_opaque_type_registered(apiserv,lsa_type,opaque_type)){zlog_warn("ospf_apiserver
_lsa_delete:LSA-type(%d)/Opaque-type(%d):Notregistered",lsa_type,opaque_type);rc
=OSPF_API_OPAQUETYPENOTREGISTERED;gotoout;}/*opaque_idisinnetworkbyteorder*/id.s
_addr=htonl(SET_OPAQUE_LSID(dmsg->opaque_type,ntohl(dmsg->opaque_id)));/**Evenif
thetargetLSAhasoncescheduledtoflush,itremainsin*theLSDBuntilitisfinallyhandledby
themaxageremoverthread.*Therefore,thelookupfunctionbelowmayreturnnon-NULLresult.
*/old=ospf_lsa_lookup(ospf,area,dmsg->lsa_type,id,ospf->router_id);if(!old){zlog
_warn("ospf_apiserver_lsa_delete:LSA[Type%d:%s]notinLSDB",dmsg->lsa_type,inet_nt
oa(id));rc=OSPF_API_NOSUCHLSA;gotoout;}/*ScheduleflushingofLSAfromLSDB*//*NB:Mul
tipleschedulingwillproduceawarningmessage,butharmless.*/ospf_opaque_lsa_flush_sc
hedule(old);out:/*Sendreplybacktoclientincludingreturncode*/rc=ospf_apiserver_se
nd_reply(apiserv,ntohl(msg->hdr.msgseq),rc);returnrc;}/*Flushself-originatedopaq
ueLSA*/staticintapiserver_flush_opaque_type_callback(structospf_lsa*lsa,void*p_a
rg,intint_arg){structparam_t{structospf_apiserver*apiserv;uint8_tlsa_type;uint8_
topaque_type;}*param;/*Sanitycheck*/assert(lsa->data);assert(p_arg);param=(struc
tparam_t*)p_arg;/*IfLSAmatchestypeandopaquetypethendeleteit*/if(IS_LSA_SELF(lsa)
&&lsa->data->type==param->lsa_type&&GET_OPAQUE_TYPE(ntohl(lsa->data->id.s_addr))
==param->opaque_type){ospf_opaque_lsa_flush_schedule(lsa);}return0;}/*Deleteself
-originatedopaqueLSAsofagivenopaquetype.Thisfunctioniscalledwhenanapplicationunr
egistersagivenopaquetypeoraconnectiontoanapplicationclosesandallthoseopaqueLSAsn
eedtobeflushedtheLSDB.*/voidospf_apiserver_flush_opaque_lsa(structospf_apiserver
*apiserv,uint8_tlsa_type,uint8_topaque_type){structparam_t{structospf_apiserver*
apiserv;uint8_tlsa_type;uint8_topaque_type;}param;structlistnode*node,*nnode;str
uctospf*ospf;structospf_area*area;ospf=ospf_lookup_by_vrf_id(VRF_DEFAULT);assert
(ospf);/*Setparameterstruct.*/param.apiserv=apiserv;param.lsa_type=lsa_type;para
m.opaque_type=opaque_type;switch(lsa_type){structroute_node*rn;structospf_lsa*ls
a;caseOSPF_OPAQUE_LINK_LSA:for(ALL_LIST_ELEMENTS(ospf->areas,node,nnode,area))LS
DB_LOOP(OPAQUE_LINK_LSDB(area),rn,lsa)apiserver_flush_opaque_type_callback(lsa,(
void*)&param,0);break;caseOSPF_OPAQUE_AREA_LSA:for(ALL_LIST_ELEMENTS(ospf->areas
,node,nnode,area))LSDB_LOOP(OPAQUE_AREA_LSDB(area),rn,lsa)apiserver_flush_opaque
_type_callback(lsa,(void*)&param,0);break;caseOSPF_OPAQUE_AS_LSA:LSDB_LOOP(OPAQU
E_LINK_LSDB(ospf),rn,lsa)apiserver_flush_opaque_type_callback(lsa,(void*)&param,
0);break;default:break;}return;}/*----------------------------------------------
-------------*Followingsarecallbackfunctionstohandleopaquetypes*----------------
-------------------------------------------*/intospf_apiserver_new_if(structinte
rface*ifp){structospf_interface*oi;/*Forsomestrangereasonitseemspossiblethatwear
einvokedwithaninterfacethathasnoname.Thisseemstohappenduringinitialization.Retur
nifthishappens*/if(ifp->name[0]=='\0'){/*interfacehasemptyname*/zlog_warn("ospf_
apiserver_new_if:interfacehasnoname?");return0;}/*zlog_warnfordebugging*/zlog_wa
rn("ospf_apiserver_new_if");zlog_warn("ifpname=%sstatus=%dindex=%d",ifp->name,if
p->status,ifp->ifindex);if(ifp->name[0]=='\0'){/*interfacehasemptyname*/zlog_war
n("ospf_apiserver_new_if:interfacehasnoname?");return0;}oi=ospf_apiserver_if_loo
kup_by_ifp(ifp);if(!oi){/*ThisinterfaceisknowntoZebrabutnottoOSPFdaemonyet.*/zlo
g_warn("ospf_apiserver_new_if:interface%snotknowntoOSPFd?",ifp->name);return0;}a
ssert(oi);/*NewinterfaceaddedtoOSPF,tellclientsaboutit*/if(listcount(apiserver_l
ist)>0){ospf_apiserver_clients_notify_new_if(oi);}return0;}intospf_apiserver_del
_if(structinterface*ifp){structospf_interface*oi;/*zlog_warnfordebugging*/zlog_w
arn("ospf_apiserver_del_if");zlog_warn("ifpname=%sstatus=%dindex=%d\n",ifp->name
,ifp->status,ifp->ifindex);oi=ospf_apiserver_if_lookup_by_ifp(ifp);if(!oi){/*Thi
sinterfaceisknowntoZebrabutnottoOSPFdaemonanymore.Noneedtotellclientsaboutit*/re
turn0;}/*Interfacedeleted,tellclientsaboutit*/if(listcount(apiserver_list)>0){os
pf_apiserver_clients_notify_del_if(oi);}return0;}voidospf_apiserver_ism_change(s
tructospf_interface*oi,intold_state){/*Tellclientsaboutinterfacechange*//*zlog_w
arnfordebugging*/zlog_warn("ospf_apiserver_ism_change");if(listcount(apiserver_l
ist)>0){ospf_apiserver_clients_notify_ism_change(oi);}zlog_warn("oi->ifp->name=%
s",oi->ifp->name);zlog_warn("old_state=%d",old_state);zlog_warn("oi->state=%d",o
i->state);}voidospf_apiserver_nsm_change(structospf_neighbor*nbr,intold_status){
/*Neighborstatuschanged,tellclientsaboutit*/zlog_warn("ospf_apiserver_nsm_change
");if(listcount(apiserver_list)>0){ospf_apiserver_clients_notify_nsm_change(nbr)
;}}voidospf_apiserver_show_info(structvty*vty,structospf_lsa*lsa){structopaque_l
sa{structlsa_headerheader;uint8_tdata[1];/*opaquedatahavevariablelength.Thisisst
artaddress*/};structopaque_lsa*olsa;intopaquelen;olsa=(structopaque_lsa*)lsa->da
ta;if(VALID_OPAQUE_INFO_LEN(lsa->data))opaquelen=ntohs(lsa->data->length)-OSPF_L
SA_HEADER_SIZE;elseopaquelen=0;/*OutputinformationaboutopaqueLSAs*/if(vty!=NULL)
{inti;vty_out(vty,"AddedusingOSPFAPI:%uoctetsofopaquedata%s\n",opaquelen,VALID_O
PAQUE_INFO_LEN(lsa->data)?"":"(Invalidlength?)");vty_out(vty,"Opaquedata:");for(
i=0;i<opaquelen;i++){vty_out(vty,"0x%x",olsa->data[i]);}vty_out(vty,"\n");}else{
inti;zlog_debug("AddedusingOSPFAPI:%uoctetsofopaquedata%s",opaquelen,VALID_OPAQU
E_INFO_LEN(lsa->data)?"":"(Invalidlength?)");zlog_debug("Opaquedata:");for(i=0;i
<opaquelen;i++){zlog_debug("0x%x",olsa->data[i]);}zlog_debug("\n");}return;}/*--
---------------------------------------------------------*Followingsarefunctions
tonotifyclientsaboutevents*-----------------------------------------------------
------*//*Sendamessagetoallclients.Thisisusefulformessagesthatneedtobenotifiedto
allclients(suchasinterfacechanges)*/voidospf_apiserver_clients_notify_all(struct
msg*msg){structlistnode*node,*nnode;structospf_apiserver*apiserv;/*Sendmessageto
allclients*/for(ALL_LIST_ELEMENTS(apiserver_list,node,nnode,apiserv))ospf_apiser
ver_send_msg(apiserv,msg);}/*AninterfaceisnowreadytoacceptopaqueLSAs.Notifyallcl
ientsthatregisteredtousethisopaquetype*/voidospf_apiserver_clients_notify_ready_
type9(structospf_interface*oi){structlistnode*node,*nnode;structmsg*msg;structos
pf_apiserver*apiserv;assert(oi);if(!oi->address){zlog_warn("Interfacehasnoaddres
s?");return;}if(!ospf_apiserver_is_ready_type9(oi)){zlog_warn("Interfacenotready
fortype9?");return;}for(ALL_LIST_ELEMENTS(apiserver_list,node,nnode,apiserv)){st
ructlistnode*node2,*nnode2;structregistered_opaque_type*r;for(ALL_LIST_ELEMENTS(
apiserv->opaque_types,node2,nnode2,r)){if(r->lsa_type==OSPF_OPAQUE_LINK_LSA){msg
=new_msg_ready_notify(0,OSPF_OPAQUE_LINK_LSA,r->opaque_type,oi->address->u.prefi
x4);if(!msg){zlog_warn("ospf_apiserver_clients_notify_ready_type9:new_msg_ready_
notifyfailed");#ifdefNOTYET/*Cannotallocatenewmessage.What*shouldwedo?*/ospf_api
server_free(apiserv);#endifgotoout;}ospf_apiserver_send_msg(apiserv,msg);msg_fre
e(msg);}}}out:return;}voidospf_apiserver_clients_notify_ready_type10(structospf_
area*area){structlistnode*node,*nnode;structmsg*msg;structospf_apiserver*apiserv
;assert(area);if(!ospf_apiserver_is_ready_type10(area)){zlog_warn("Areanotreadyf
ortype10?");return;}for(ALL_LIST_ELEMENTS(apiserver_list,node,nnode,apiserv)){st
ructlistnode*node2,*nnode2;structregistered_opaque_type*r;for(ALL_LIST_ELEMENTS(
apiserv->opaque_types,node2,nnode2,r)){if(r->lsa_type==OSPF_OPAQUE_AREA_LSA){msg
=new_msg_ready_notify(0,OSPF_OPAQUE_AREA_LSA,r->opaque_type,area->area_id);if(!m
sg){zlog_warn("ospf_apiserver_clients_notify_ready_type10:new_msg_ready_nofityfa
iled");#ifdefNOTYET/*Cannotallocatenewmessage.What*shouldwedo?*/ospf_apiserver_f
ree(apiserv);#endifgotoout;}ospf_apiserver_send_msg(apiserv,msg);msg_free(msg);}
}}out:return;}voidospf_apiserver_clients_notify_ready_type11(structospf*top){str
uctlistnode*node,*nnode;structmsg*msg;structin_addrid_null={.s_addr=0L};structos
pf_apiserver*apiserv;assert(top);if(!ospf_apiserver_is_ready_type11(top)){zlog_w
arn("ASnotreadyfortype11?");return;}for(ALL_LIST_ELEMENTS(apiserver_list,node,nn
ode,apiserv)){structlistnode*node2,*nnode2;structregistered_opaque_type*r;for(AL
L_LIST_ELEMENTS(apiserv->opaque_types,node2,nnode2,r)){if(r->lsa_type==OSPF_OPAQ
UE_AS_LSA){msg=new_msg_ready_notify(0,OSPF_OPAQUE_AS_LSA,r->opaque_type,id_null)
;if(!msg){zlog_warn("ospf_apiserver_clients_notify_ready_type11:new_msg_ready_no
tifyfailed");#ifdefNOTYET/*Cannotallocatenewmessage.What*shouldwedo?*/ospf_apise
rver_free(apiserv);#endifgotoout;}ospf_apiserver_send_msg(apiserv,msg);msg_free(
msg);}}}out:return;}voidospf_apiserver_clients_notify_new_if(structospf_interfac
e*oi){structmsg*msg;msg=new_msg_new_if(0,oi->address->u.prefix4,oi->area->area_i
d);if(msg!=NULL){ospf_apiserver_clients_notify_all(msg);msg_free(msg);}}voidospf
_apiserver_clients_notify_del_if(structospf_interface*oi){structmsg*msg;msg=new_
msg_del_if(0,oi->address->u.prefix4);if(msg!=NULL){ospf_apiserver_clients_notify
_all(msg);msg_free(msg);}}voidospf_apiserver_clients_notify_ism_change(structosp
f_interface*oi){structmsg*msg;structin_addrifaddr={.s_addr=0L};structin_addrarea
_id={.s_addr=0L};assert(oi);assert(oi->ifp);if(oi->address){ifaddr=oi->address->
u.prefix4;}if(oi->area){area_id=oi->area->area_id;}msg=new_msg_ism_change(0,ifad
dr,area_id,oi->state);if(!msg){zlog_warn("apiserver_clients_notify_ism_change:ms
g_newfailed");return;}ospf_apiserver_clients_notify_all(msg);msg_free(msg);}void
ospf_apiserver_clients_notify_nsm_change(structospf_neighbor*nbr){structmsg*msg;
structin_addrifaddr={.s_addr=0L};structin_addrnbraddr;assert(nbr);if(nbr->oi){if
addr=nbr->oi->address->u.prefix4;}nbraddr=nbr->address.u.prefix4;msg=new_msg_nsm
_change(0,ifaddr,nbraddr,nbr->router_id,nbr->state);if(!msg){zlog_warn("apiserve
r_clients_notify_nsm_change:msg_newfailed");return;}ospf_apiserver_clients_notif
y_all(msg);msg_free(msg);}staticvoidapiserver_clients_lsa_change_notify(uint8_tm
sgtype,structospf_lsa*lsa){structmsg*msg;structlistnode*node,*nnode;structospf_a
piserver*apiserv;/*DefaultareaforAS-ExternalandOpaque11LSAs*/structin_addrarea_i
d={.s_addr=0L};/*DefaultinterfacefornonOpaque9LSAs*/structin_addrifaddr={.s_addr
=0L};if(lsa->area){area_id=lsa->area->area_id;}if(lsa->data->type==OSPF_OPAQUE_L
INK_LSA){assert(lsa->oi);ifaddr=lsa->oi->address->u.prefix4;}/*Preparemessagetha
tcanbesenttoclientsthathaveamatchingfilter*/msg=new_msg_lsa_change_notify(msgtyp
e,0L,/*nosequencenumber*/ifaddr,area_id,lsa->flags&OSPF_LSA_SELF,lsa->data);if(!
msg){zlog_warn("apiserver_clients_lsa_change_notify:msg_newfailed");return;}/*No
wsendmessagetoallclientswithamatchingfilter*/for(ALL_LIST_ELEMENTS(apiserver_lis
t,node,nnode,apiserv)){structlsa_filter_type*filter;uint16_tmask;uint32_t*area;i
nti;/*Checkfilterforthisclient.*/filter=apiserv->filter;/*CheckareaIDsincaseofno
nAS-ELSAs.*Iffilterhasareas(num_areas>0),*thenoneoftheareasmustmatchtheareaIDoft
hisLSA.*/i=filter->num_areas;if((lsa->data->type==OSPF_AS_EXTERNAL_LSA)||(lsa->d
ata->type==OSPF_OPAQUE_AS_LSA)){i=0;}if(i>0){area=(uint32_t*)(filter+1);while(i)
{if(*area==area_id.s_addr){break;}i--;area++;}}else{i=1;}if(i>0){/*Areamatch.Che
ckLSAtype.*/mask=ntohs(filter->typemask);if(mask&Power2[lsa->data->type]){/*Type
alsomatches.Checkorigin.*/if((filter->origin==ANY_ORIGIN)||(filter->origin==IS_L
SA_SELF(lsa))){ospf_apiserver_send_msg(apiserv,msg);}}}}/*Freemessagesinceitisno
tusedanymore*/msg_free(msg);}/*-------------------------------------------------
------------*FollowingsarehooksinvokedwhenLSAsareupdatedordeleted*--------------
-----------------------------------------------*/staticintapiserver_notify_clien
ts_lsa(uint8_tmsgtype,structospf_lsa*lsa){structmsg*msg;/*defaultareaforAS-Exter
nalandOpaque11LSAs*/structin_addrarea_id={.s_addr=0L};/*defaultinterfacefornonOp
aque9LSAs*/structin_addrifaddr={.s_addr=0L};/*OnlynotifythisupdateiftheLSA'sagei
ssmallerthanMAXAGE.OtherwiseclientswouldseeLSAupdateswithmaxagejustbeforetheyare
deletedfromtheLSDB.LSAdeletemessageshaveMAXAGEtoobutshouldnotbefiltered.*/if(IS_
LSA_MAXAGE(lsa)&&(msgtype==MSG_LSA_UPDATE_NOTIFY)){return0;}if(lsa->area){area_i
d=lsa->area->area_id;}if(lsa->data->type==OSPF_OPAQUE_LINK_LSA){ifaddr=lsa->oi->
address->u.prefix4;}msg=new_msg_lsa_change_notify(msgtype,0L,/*nosequencenumber*
/ifaddr,area_id,lsa->flags&OSPF_LSA_SELF,lsa->data);if(!msg){zlog_warn("notify_c
lients_lsa:msg_newfailed");return-1;}/*NotifyallclientsthatnewLSAisadded/updated
*/apiserver_clients_lsa_change_notify(msgtype,lsa);/*Clientsmadetheirowncopiesof
msgsowecanfreemsghere*/msg_free(msg);return0;}intospf_apiserver_lsa_update(struc
tospf_lsa*lsa){returnapiserver_notify_clients_lsa(MSG_LSA_UPDATE_NOTIFY,lsa);}in
tospf_apiserver_lsa_delete(structospf_lsa*lsa){returnapiserver_notify_clients_ls
a(MSG_LSA_DELETE_NOTIFY,lsa);}#endif/*SUPPORT_OSPF_API*/