/**ZebraconnectlibraryforOSPFd*Copyright(C)1997,98,99,2000KunihiroIshiguro,Toshi
akiTakada**ThisfileispartofGNUZebra.**GNUZebraisfreesoftware;youcanredistributei
tand/ormodifyit*underthetermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSo
ftwareFoundation;eitherversion2,or(atyouroption)any*laterversion.**GNUZebraisdis
tributedinthehopethatitwillbeuseful,but*WITHOUTANYWARRANTY;withouteventheimplied
warrantyof*MERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublic
Licenseformoredetails.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicenseal
ong*withthisprogram;seethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,In
c.,51FranklinSt,FifthFloor,Boston,MA02110-1301USA*/#ifndef_ZEBRA_OSPF_ZEBRA_H#de
fine_ZEBRA_OSPF_ZEBRA_H#include"vty.h"#include"hook.h"#defineEXTERNAL_METRIC_TYP
E_10#defineEXTERNAL_METRIC_TYPE_21#defineDEFAULT_ROUTEZEBRA_ROUTE_MAX#defineDEFA
ULT_ROUTE_TYPE(T)((T)==DEFAULT_ROUTE)/*OSPFdistance.*/structospf_distance{/*Dist
ancevaluefortheIPsourceprefix.*/uint8_tdistance;/*Nameoftheaccess-listtobematche
d.*/char*access_list;};/*Prototypes*/externvoidospf_zebra_add(structospf*ospf,st
ructprefix_ipv4*,structospf_route*);externvoidospf_zebra_delete(structospf*ospf,
structprefix_ipv4*,structospf_route*);externvoidospf_zebra_add_discard(structosp
f*ospf,structprefix_ipv4*);externvoidospf_zebra_delete_discard(structospf*ospf,s
tructprefix_ipv4*);externintospf_redistribute_check(structospf*,structexternal_i
nfo*,int*);externintospf_distribute_check_connected(structospf*,structexternal_i
nfo*);externvoidospf_distribute_list_update(structospf*,int,unsignedshort);exter
nintospf_is_type_redistributed(structospf*,int,unsignedshort);externvoidospf_dis
tance_reset(structospf*);externuint8_tospf_distance_apply(structospf*ospf,struct
prefix_ipv4*,structospf_route*);externstructospf_external*ospf_external_lookup(s
tructospf*,uint8_t,unsignedshort);externstructospf_external*ospf_external_add(st
ructospf*,uint8_t,unsignedshort);externvoidospf_external_del(structospf*,uint8_t
,unsignedshort);externstructospf_redist*ospf_redist_lookup(structospf*,uint8_t,u
nsignedshort);externstructospf_redist*ospf_redist_add(structospf*,uint8_t,unsign
edshort);externvoidospf_redist_del(structospf*,uint8_t,unsignedshort);externinto
spf_redistribute_set(structospf*,int,unsignedshort,int,int);externintospf_redist
ribute_unset(structospf*,int,unsignedshort);externintospf_redistribute_default_s
et(structospf*,int,int,int);externintospf_redistribute_default_unset(structospf*
);externintospf_distribute_list_out_set(structospf*,int,constchar*);externintosp
f_distribute_list_out_unset(structospf*,int,constchar*);externvoidospf_routemap_
set(structospf_redist*,constchar*);externvoidospf_routemap_unset(structospf_redi
st*);externintospf_distance_set(structvty*,structospf*,constchar*,constchar*,con
stchar*);externintospf_distance_unset(structvty*,structospf*,constchar*,constcha
r*,constchar*);externvoidospf_zebra_init(structthread_master*,unsignedshort);ext
ernvoidospf_zebra_vrf_register(structospf*ospf);externvoidospf_zebra_vrf_deregis
ter(structospf*ospf);DECLARE_HOOK(ospf_if_update,(structinterface*ifp),(ifp))DEC
LARE_HOOK(ospf_if_delete,(structinterface*ifp),(ifp))#endif/*_ZEBRA_OSPF_ZEBRA_H
*/