/***bfd.c:BFDhandlingroutines**@copyrightCopyright(C)2015CumulusNetworks,Inc.**T
hisfileispartofGNUZebra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodif
yit*underthetermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFounda
tion;eitherversion2,or(atyouroption)any*laterversion.**GNUZebraisdistributedinth
ehopethatitwillbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*M
ERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformo
redetails.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthis
program;seethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51Frankli
nSt,FifthFloor,Boston,MA02110-1301USA*/#include<zebra.h>#include"command.h"#incl
ude"memory.h"#include"prefix.h"#include"thread.h"#include"stream.h"#include"zcli
ent.h"#include"table.h"#include"vty.h"#include"bfd.h"DEFINE_MTYPE_STATIC(LIB,BFD
_INFO,"BFDinfo")intbfd_debug=0;structbfd_gblbfd_gbl;/**bfd_gbl_init-Initializeth
eBFDglobalstructure*/voidbfd_gbl_init(void){memset(&bfd_gbl,0,sizeof(structbfd_g
bl));}/**bfd_gbl_exit-Calledwhendaemonexits*/voidbfd_gbl_exit(void){SET_FLAG(bfd
_gbl.flags,BFD_GBL_FLAG_IN_SHUTDOWN);}/**bfd_info_create-AllocatetheBFDinformati
on*/structbfd_info*bfd_info_create(void){structbfd_info*bfd_info;bfd_info=XCALLO
C(MTYPE_BFD_INFO,sizeof(structbfd_info));assert(bfd_info);bfd_info->status=BFD_S
TATUS_UNKNOWN;bfd_info->type=BFD_TYPE_NOT_CONFIGURED;bfd_info->last_update=0;ret
urnbfd_info;}/**bfd_info_free-FreetheBFDinformation.*/voidbfd_info_free(structbf
d_info**bfd_info){if(*bfd_info){XFREE(MTYPE_BFD_INFO,*bfd_info);*bfd_info=NULL;}
}/**bfd_validate_param-ValidatetheBFDparamterinformation.*/intbfd_validate_param
(structvty*vty,constchar*dm_str,constchar*rx_str,constchar*tx_str,uint8_t*dm_val
,uint32_t*rx_val,uint32_t*tx_val){*dm_val=strtoul(dm_str,NULL,10);*rx_val=strtou
l(rx_str,NULL,10);*tx_val=strtoul(tx_str,NULL,10);returnCMD_SUCCESS;}/**bfd_set_
param-SettheconfiguredBFDparamtervalues*/voidbfd_set_param(structbfd_info**bfd_i
nfo,uint32_tmin_rx,uint32_tmin_tx,uint8_tdetect_mult,intdefaults,int*command){if
(!*bfd_info){*bfd_info=bfd_info_create();*command=ZEBRA_BFD_DEST_REGISTER;}else{
if(((*bfd_info)->required_min_rx!=min_rx)||((*bfd_info)->desired_min_tx!=min_tx)
||((*bfd_info)->detect_mult!=detect_mult))*command=ZEBRA_BFD_DEST_UPDATE;}if(*co
mmand){(*bfd_info)->required_min_rx=min_rx;(*bfd_info)->desired_min_tx=min_tx;(*
bfd_info)->detect_mult=detect_mult;}if(!defaults)SET_FLAG((*bfd_info)->flags,BFD
_FLAG_PARAM_CFG);elseUNSET_FLAG((*bfd_info)->flags,BFD_FLAG_PARAM_CFG);}/**bfd_p
eer_sendmsg-Formatandsendapeerregister/Unregister*commandtoZebratobeforwardedtoB
FD*/voidbfd_peer_sendmsg(structzclient*zclient,structbfd_info*bfd_info,intfamily
,void*dst_ip,void*src_ip,char*if_name,intttl,intmultihop,intcommand,intset_flag,
vrf_id_tvrf_id){structstream*s;intret;intlen;/*Individualreg/deregmessagesaresup
ressedduringshutdown.*/if(CHECK_FLAG(bfd_gbl.flags,BFD_GBL_FLAG_IN_SHUTDOWN)){if
(bfd_debug)zlog_debug("%s:SuppressingBFDpeerreg/deregmessages",__FUNCTION__);ret
urn;}/*Checksocket.*/if(!zclient||zclient->sock<0){if(bfd_debug)zlog_debug("%s:C
an'tsendBFDpeerregister,Zebraclientnot""established",__FUNCTION__);return;}s=zcl
ient->obuf;stream_reset(s);zclient_create_header(s,command,vrf_id);stream_putl(s
,getpid());stream_putw(s,family);switch(family){caseAF_INET:stream_put_in_addr(s
,(structin_addr*)dst_ip);break;caseAF_INET6:stream_put(s,dst_ip,16);break;defaul
t:break;}if(command!=ZEBRA_BFD_DEST_DEREGISTER){stream_putl(s,bfd_info->required
_min_rx);stream_putl(s,bfd_info->desired_min_tx);stream_putc(s,bfd_info->detect_
mult);}if(multihop){stream_putc(s,1);/*Multi-hopdestinationsendthesourceIPaddres
stoBFD*/if(src_ip){stream_putw(s,family);switch(family){caseAF_INET:stream_put_i
n_addr(s,(structin_addr*)src_ip);break;caseAF_INET6:stream_put(s,src_ip,16);brea
k;default:break;}}stream_putc(s,ttl);}else{stream_putc(s,0);if((family==AF_INET6
)&&(src_ip)){stream_putw(s,family);stream_put(s,src_ip,16);}if(if_name){len=strl
en(if_name);stream_putc(s,len);stream_put(s,if_name,len);}else{stream_putc(s,0);
}}stream_putw_at(s,0,stream_get_endp(s));ret=zclient_send_message(zclient);if(re
t<0){if(bfd_debug)zlog_debug("bfd_peer_sendmsg:zclient_send_message()failed");re
turn;}if(set_flag){if(command==ZEBRA_BFD_DEST_REGISTER)SET_FLAG(bfd_info->flags,
BFD_FLAG_BFD_REG);elseif(command==ZEBRA_BFD_DEST_DEREGISTER)UNSET_FLAG(bfd_info-
>flags,BFD_FLAG_BFD_REG);}return;}/**bfd_get_command_dbg_str-Convertcommandtoade
bugstring.*/constchar*bfd_get_command_dbg_str(intcommand){switch(command){caseZE
BRA_BFD_DEST_REGISTER:return"Register";caseZEBRA_BFD_DEST_DEREGISTER:return"Dere
gister";caseZEBRA_BFD_DEST_UPDATE:return"Update";default:return"Unknown";}}/**bf
d_get_peer_info-ExtractthePeerinformationforwhichtheBFDsession*wentdownfromtheme
ssagesentfromZebratoclients.*/structinterface*bfd_get_peer_info(structstream*s,s
tructprefix*dp,structprefix*sp,int*status,vrf_id_tvrf_id){unsignedintifindex;str
uctinterface*ifp=NULL;intplen;/*Getinterfaceindex.*/ifindex=stream_getl(s);/*Loo
kupindex.*/if(ifindex!=0){ifp=if_lookup_by_index(ifindex,vrf_id);if(ifp==NULL){i
f(bfd_debug)zlog_debug("zebra_interface_bfd_read:""Can'tfindinterfacebyifindex:%
d",ifindex);returnNULL;}}/*Fetchdestinationaddress.*/dp->family=stream_getc(s);p
len=prefix_blen(dp);stream_get(&dp->u.prefix,s,plen);dp->prefixlen=stream_getc(s
);/*GetBFDstatus.*/*status=stream_getl(s);if(sp){sp->family=stream_getc(s);plen=
prefix_blen(sp);stream_get(&sp->u.prefix,s,plen);sp->prefixlen=stream_getc(s);}r
eturnifp;}/**bfd_get_status_str-ConvertBFDstatustoadisplaystring.*/constchar*bfd
_get_status_str(intstatus){switch(status){caseBFD_STATUS_DOWN:return"Down";caseB
FD_STATUS_UP:return"Up";caseBFD_STATUS_UNKNOWN:default:return"Unknown";}}/**bfd_
last_update-CalculatethelastBFDupdatetimeandconvertit*intoadd:hh:mm:ssdisplayfor
mat.*/staticvoidbfd_last_update(time_tlast_update,char*buf,size_tlen){time_tcurr
;time_tdiff;structtm*tm;structtimevaltv;/*IfnoBFDsatatusupdatehaseverbeenreceive
d,print`never'.*/if(last_update==0){snprintf(buf,len,"never");return;}/*Getcurre
nttime.*/monotime(&tv);curr=tv.tv_sec;diff=curr-last_update;tm=gmtime(&diff);snp
rintf(buf,len,"%d:%02d:%02d:%02d",tm->tm_yday,tm->tm_hour,tm->tm_min,tm->tm_sec)
;}/**bfd_show_param-ShowtheBFDparameterinformation.*/voidbfd_show_param(structvt
y*vty,structbfd_info*bfd_info,intbfd_tag,intextra_space,uint8_tuse_json,json_obj
ect*json_obj){json_object*json_bfd=NULL;if(!bfd_info)return;if(use_json){if(bfd_
tag)json_bfd=json_object_new_object();elsejson_bfd=json_obj;json_object_int_add(
json_bfd,"detectMultiplier",bfd_info->detect_mult);json_object_int_add(json_bfd,
"rxMinInterval",bfd_info->required_min_rx);json_object_int_add(json_bfd,"txMinIn
terval",bfd_info->desired_min_tx);if(bfd_tag)json_object_object_add(json_obj,"pe
erBfdInfo",json_bfd);}else{vty_out(vty,"%s%sDetectMultiplier:%d,MinRxinterval:%d
,""MinTxinterval:%d\n",(extra_space)?"":"",(bfd_tag)?"BFD:":"",bfd_info->detect_
mult,bfd_info->required_min_rx,bfd_info->desired_min_tx);}}/**bfd_show_status-Sh
owtheBFDstatusinformation.*/staticvoidbfd_show_status(structvty*vty,structbfd_in
fo*bfd_info,intbfd_tag,intextra_space,uint8_tuse_json,json_object*json_bfd){char
time_buf[32];if(!bfd_info)return;bfd_last_update(bfd_info->last_update,time_buf,
32);if(use_json){json_object_string_add(json_bfd,"status",bfd_get_status_str(bfd
_info->status));json_object_string_add(json_bfd,"lastUpdate",time_buf);}else{vty
_out(vty,"%s%sStatus:%s,Lastupdate:%s\n",(extra_space)?"":"",(bfd_tag)?"BFD:":""
,bfd_get_status_str(bfd_info->status),time_buf);}}/**bfd_show_info-ShowtheBFDinf
ormation.*/voidbfd_show_info(structvty*vty,structbfd_info*bfd_info,intmultihop,i
ntextra_space,uint8_tuse_json,json_object*json_obj){json_object*json_bfd=NULL;if
(!bfd_info)return;if(use_json){json_bfd=json_object_new_object();if(multihop)jso
n_object_string_add(json_bfd,"type","multihop");elsejson_object_string_add(json_
bfd,"type","singlehop");}else{vty_out(vty,"%sBFD:Type:%s\n",(extra_space)?"":"",
(multihop)?"multihop":"singlehop");}bfd_show_param(vty,bfd_info,0,extra_space,us
e_json,json_bfd);bfd_show_status(vty,bfd_info,0,extra_space,use_json,json_bfd);i
f(use_json)json_object_object_add(json_obj,"peerBfdInfo",json_bfd);elsevty_out(v
ty,"\n");}/**bfd_client_sendmsg-Formatandsendaclientregister*commandtoZebratobef
orwardedtoBFD*/voidbfd_client_sendmsg(structzclient*zclient,intcommand){structst
ream*s;intret;/*Checksocket.*/if(!zclient||zclient->sock<0){if(bfd_debug)zlog_de
bug("%s:Can'tsendBFDclientregister,Zebraclientnot""established",__FUNCTION__);re
turn;}s=zclient->obuf;stream_reset(s);zclient_create_header(s,command,VRF_DEFAUL
T);stream_putl(s,getpid());stream_putw_at(s,0,stream_get_endp(s));ret=zclient_se
nd_message(zclient);if(ret<0){if(bfd_debug)zlog_debug("bfd_client_sendmsg%ld:zcl
ient_send_message()failed",(long)getpid());return;}return;}