/**Bufferingofoutputandinput.*Copyright(C)1998KunihiroIshiguro**Thisfileispartof
GNUZebra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodify*itundertheter
msoftheGNUGeneralPublicLicenseaspublished*bytheFreeSoftwareFoundation;eithervers
ion2,or(atyour*option)anylaterversion.**GNUZebraisdistributedinthehopethatitwill
beuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYo
rFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**You
shouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethef
ileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,
Boston,MA02110-1301USA*/#include<zebra.h>#include"memory.h"#include"buffer.h"#in
clude"log.h"#include"network.h"#include<stddef.h>DEFINE_MTYPE_STATIC(LIB,BUFFER,
"Buffer")DEFINE_MTYPE_STATIC(LIB,BUFFER_DATA,"Bufferdata")/*Buffermaster.*/struc
tbuffer{/*Datalist.*/structbuffer_data*head;structbuffer_data*tail;/*Sizeofeachb
uffer_datachunk.*/size_tsize;};/*Datacontainer.*/structbuffer_data{structbuffer_
data*next;/*Locationtoaddnewdata.*/size_tcp;/*Pointertodatanotyetflushed.*/size_
tsp;/*Actualdatastream(variablelength).*/unsignedchardata[];/*realdimensionisbuf
fer->size*/};/*Itshouldalwaysbetruethat:0<=sp<=cp<=size*//*Defaultbuffersize(use
difnonespecified).Itisroundeduptothenextpageboundery.*/#defineBUFFER_SIZE_DEFAUL
T4096#defineBUFFER_DATA_FREE(D)XFREE(MTYPE_BUFFER_DATA,(D))/*Makenewbuffer.*/str
uctbuffer*buffer_new(size_tsize){structbuffer*b;b=XCALLOC(MTYPE_BUFFER,sizeof(st
ructbuffer));if(size)b->size=size;else{staticsize_tdefault_size;if(!default_size
){longpgsz=sysconf(_SC_PAGESIZE);default_size=((((BUFFER_SIZE_DEFAULT-1)/pgsz)+1
)*pgsz);}b->size=default_size;}returnb;}/*Freebuffer.*/voidbuffer_free(structbuf
fer*b){buffer_reset(b);XFREE(MTYPE_BUFFER,b);}/*Makestringclone.*/char*buffer_ge
tstr(structbuffer*b){size_ttotlen=0;structbuffer_data*data;char*s;char*p;for(dat
a=b->head;data;data=data->next)totlen+=data->cp-data->sp;if(!(s=XMALLOC(MTYPE_TM
P,totlen+1)))returnNULL;p=s;for(data=b->head;data;data=data->next){memcpy(p,data
->data+data->sp,data->cp-data->sp);p+=data->cp-data->sp;}*p='\0';returns;}/*Retu
rn1ifbufferisempty.*/intbuffer_empty(structbuffer*b){return(b->head==NULL);}/*Cl
earandfreeallallocateddata.*/voidbuffer_reset(structbuffer*b){structbuffer_data*
data;structbuffer_data*next;for(data=b->head;data;data=next){next=data->next;BUF
FER_DATA_FREE(data);}b->head=b->tail=NULL;}/*Addbuffer_datatotheendofbuffer.*/st
aticstructbuffer_data*buffer_add(structbuffer*b){structbuffer_data*d;d=XMALLOC(M
TYPE_BUFFER_DATA,offsetof(structbuffer_data,data)+b->size);d->cp=d->sp=0;d->next
=NULL;if(b->tail)b->tail->next=d;elseb->head=d;b->tail=d;returnd;}/*Writedatatob
uffer.*/voidbuffer_put(structbuffer*b,constvoid*p,size_tsize){structbuffer_data*
data=b->tail;constchar*ptr=p;/*Weuseevenlastonebyteofdatabuffer.*/while(size){si
ze_tchunk;/*Ifthereisnodatabufferaddit.*/if(data==NULL||data->cp==b->size)data=b
uffer_add(b);chunk=((size<=(b->size-data->cp))?size:(b->size-data->cp));memcpy((
data->data+data->cp),ptr,chunk);size-=chunk;ptr+=chunk;data->cp+=chunk;}}/*Inser
tcharacterintothebuffer.*/voidbuffer_putc(structbuffer*b,uint8_tc){buffer_put(b,
&c,1);}/*Putstringtothebuffer.*/voidbuffer_putstr(structbuffer*b,constchar*c){bu
ffer_put(b,c,strlen(c));}/*Expand\nto\r\n*/voidbuffer_put_crlf(structbuffer*b,co
nstvoid*origp,size_torigsize){structbuffer_data*data=b->tail;constchar*p=origp,*
end=p+origsize,*lf;size_tsize;lf=memchr(p,'\n',end-p);/*Weuseevenlastonebyteofda
tabuffer.*/while(p<end){size_tavail,chunk;/*Ifthereisnodatabufferaddit.*/if(data
==NULL||data->cp==b->size)data=buffer_add(b);size=(lf?lf:end)-p;avail=b->size-da
ta->cp;chunk=(size<=avail)?size:avail;memcpy(data->data+data->cp,p,chunk);p+=chu
nk;data->cp+=chunk;if(lf&&size<=avail){/*wejustcopiedupto(including)a'\n'*/if(da
ta->cp==b->size)data=buffer_add(b);data->data[data->cp++]='\r';if(data->cp==b->s
ize)data=buffer_add(b);data->data[data->cp++]='\n';p++;lf=memchr(p,'\n',end-p);}
}}/*Keepflushingdatatothefduntilthebufferisemptyoranerrorisencounteredortheopera
tionwouldblock.*/buffer_status_tbuffer_flush_all(structbuffer*b,intfd){buffer_st
atus_tret;structbuffer_data*head;size_thead_sp;if(!b->head)returnBUFFER_EMPTY;he
ad_sp=(head=b->head)->sp;/*Flushalldata.*/while((ret=buffer_flush_available(b,fd
))==BUFFER_PENDING){if((b->head==head)&&(head_sp==head->sp)&&(errno!=EINTR))/*No
datawasflushed,sokernelbuffermustbefull.*/returnret;head_sp=(head=b->head)->sp;}
returnret;}/*Flushenoughdatatofillaterminalwindowofthegivenscene(usedonlybyvtyte
lnetinterface).*/buffer_status_tbuffer_flush_window(structbuffer*b,intfd,intwidt
h,intheight,interase_flag,intno_more_flag){intnbytes;intiov_alloc;intiov_index;s
tructiovec*iov;structiovecsmall_iov[3];charmore[]="--More--";charerase[]={0x08,0
x08,0x08,0x08,0x08,0x08,0x08,0x08,0x08,0x08,'','','','','','','','','','',0x08,0
x08,0x08,0x08,0x08,0x08,0x08,0x08,0x08,0x08};structbuffer_data*data;intcolumn;if
(!b->head)returnBUFFER_EMPTY;if(height<1){zlog_warn("%scalledwithnon-positivewin
dowheight%d,forcingto1",__func__,height);height=1;}elseif(height>=2)height--;if(
width<1){zlog_warn("%scalledwithnon-positivewindowwidth%d,forcingto1",__func__,w
idth);width=1;}/*Foreraseandmoredataaddtwotob'sbuffer_datacount.*/if(b->head->ne
xt==NULL){iov_alloc=array_size(small_iov);iov=small_iov;}else{iov_alloc=((height
*(width+2))/b->size)+10;iov=XMALLOC(MTYPE_TMP,iov_alloc*sizeof(*iov));}iov_index
=0;/*Previouslyprintoutisperformed.*/if(erase_flag){iov[iov_index].iov_base=eras
e;iov[iov_index].iov_len=sizeoferase;iov_index++;}/*Outputdata.*/column=1;/*Colu
mnpositionofnextcharacterdisplayed.*/for(data=b->head;data&&(height>0);data=data
->next){size_tcp;cp=data->sp;while((cp<data->cp)&&(height>0)){/*Calculatelinesre
mainingandcolumnpositionafterdisplayingthischaracter.*/if(data->data[cp]=='\r')c
olumn=1;elseif((data->data[cp]=='\n')||(column==width)){column=1;height--;}elsec
olumn++;cp++;}iov[iov_index].iov_base=(char*)(data->data+data->sp);iov[iov_index
++].iov_len=cp-data->sp;data->sp=cp;if(iov_index==iov_alloc)/*Thisshouldnotordin
arilyhappen.*/{iov_alloc*=2;if(iov!=small_iov){zlog_warn("%s:growingiovarrayto%d
;""width%d,height%d,size%lu",__func__,iov_alloc,width,height,(unsignedlong)b->si
ze);iov=XREALLOC(MTYPE_TMP,iov,iov_alloc*sizeof(*iov));}else{/*Thisshouldabsolut
elyneveroccur.*/zlog_err("%s:corruptiondetected:iov_smalloverflowed;""head%p,tai
l%p,head->next%p",__func__,(void*)b->head,(void*)b->tail,(void*)b->head->next);i
ov=XMALLOC(MTYPE_TMP,iov_alloc*sizeof(*iov));memcpy(iov,small_iov,sizeof(small_i
ov));}}}/*Incaseof`more'displayneed.*/if(b->tail&&(b->tail->sp<b->tail->cp)&&!no
_more_flag){iov[iov_index].iov_base=more;iov[iov_index].iov_len=sizeofmore;iov_i
ndex++;}#ifdefIOV_MAX/*IOV_MAXarenormallydefinedin<sys/uio.h>,Posix.1g.example:S
olaris2.6aredefinedIOV_MAXsizeat16.*/{structiovec*c_iov=iov;nbytes=0;/*Makesurei
t'sinitialized.*/while(iov_index>0){intiov_size;iov_size=((iov_index>IOV_MAX)?IO
V_MAX:iov_index);if((nbytes=writev(fd,c_iov,iov_size))<0){zlog_warn("%s:writevto
fd%dfailed:%s",__func__,fd,safe_strerror(errno));break;}/*movepointerio-vector*/
c_iov+=iov_size;iov_index-=iov_size;}}#else/*IOV_MAX*/if((nbytes=writev(fd,iov,i
ov_index))<0)zlog_warn("%s:writevtofd%dfailed:%s",__func__,fd,safe_strerror(errn
o));#endif/*IOV_MAX*//*Freeprintedbufferdata.*/while(b->head&&(b->head->sp==b->h
ead->cp)){structbuffer_data*del;if(!(b->head=(del=b->head)->next))b->tail=NULL;B
UFFER_DATA_FREE(del);}if(iov!=small_iov)XFREE(MTYPE_TMP,iov);return(nbytes<0)?BU
FFER_ERROR:(b->head?BUFFER_PENDING:BUFFER_EMPTY);}/*Thisfunction(unlikeotherbuff
er_flush*functionsabove)isdesignedtoworkwithnon-blockingsockets.Itdoesnotattempt
towriteoutallofthequeueddata,justa"big"chunk.Itreturns0ifitwasabletoemptyouttheb
ufferscompletely,1ifmoreflushingisrequiredlater,or-1onafatalwriteerror.*/buffer_
status_tbuffer_flush_available(structbuffer*b,intfd){/*Thesearejustreasonableval
uestomakesureasignificantamountofdataiswritten.There'snoneedtogocrazyandtrytowri
teitallinoneshot.*/#ifdefIOV_MAX#defineMAX_CHUNKS((IOV_MAX>=16)?16:IOV_MAX)#else
#defineMAX_CHUNKS16#endif#defineMAX_FLUSH131072structbuffer_data*d;size_twritten
;structioveciov[MAX_CHUNKS];size_tiovcnt=0;size_tnbyte=0;for(d=b->head;d&&(iovcn
t<MAX_CHUNKS)&&(nbyte<MAX_FLUSH);d=d->next,iovcnt++){iov[iovcnt].iov_base=d->dat
a+d->sp;nbyte+=(iov[iovcnt].iov_len=d->cp-d->sp);}if(!nbyte)/*Nodatatoflush:shou
ldweissueawarningmessage?*/returnBUFFER_EMPTY;/*onlyplacewherewrittenshouldbesig
ncompared*/if((ssize_t)(written=writev(fd,iov,iovcnt))<0){if(ERRNO_IO_RETRY(errn
o))/*Callingcodeshouldtryagainlater.*/returnBUFFER_PENDING;zlog_warn("%s:writeer
roronfd%d:%s",__func__,fd,safe_strerror(errno));returnBUFFER_ERROR;}/*Freeprinte
dbufferdata.*/while(written>0){structbuffer_data*d;if(!(d=b->head)){zlog_err("%s
:corruptiondetected:bufferqueueempty,""butwrittenis%lu",__func__,(unsignedlong)w
ritten);break;}if(written<d->cp-d->sp){d->sp+=written;returnBUFFER_PENDING;}writ
ten-=(d->cp-d->sp);if(!(b->head=d->next))b->tail=NULL;BUFFER_DATA_FREE(d);}retur
nb->head?BUFFER_PENDING:BUFFER_EMPTY;#undefMAX_CHUNKS#undefMAX_FLUSH}buffer_stat
us_tbuffer_write(structbuffer*b,intfd,constvoid*p,size_tsize){ssize_tnbytes;#if0
/**Shouldweattempttodrainanypreviouslybuffereddata?*Thiscouldhelpreducelatencyin
pushingoutthedataif*wearestuckinalong-runningthreadthatispreventing*themainselec
tloopfromcallingtheflushthread...*/if(b->head&&(buffer_flush_available(b,fd)==BU
FFER_ERROR))returnBUFFER_ERROR;#endifif(b->head)/*Bufferisnotempty,sodonotattemp
ttowritethenewdata.*/nbytes=0;elseif((nbytes=write(fd,p,size))<0){if(ERRNO_IO_RE
TRY(errno))nbytes=0;else{zlog_warn("%s:writeerroronfd%d:%s",__func__,fd,safe_str
error(errno));returnBUFFER_ERROR;}}/*Addanyremainingdatatothebuffer.*/{size_twri
tten=nbytes;if(written<size)buffer_put(b,((constchar*)p)+written,size-written);}
returnb->head?BUFFER_PENDING:BUFFER_EMPTY;}