/**clippy(CLIpreparatorinpython)mainexecutable*Copyright(C)2016-2017DavidLampart
erforNetDEF,Inc.**Thisprogramisfreesoftware;youcanredistributeitand/ormodifyit*u
nderthetermsoftheGNUGeneralPublicLicenseaspublishedbytheFree*SoftwareFoundation;
eitherversion2oftheLicense,or(atyouroption)*anylaterversion.**Thisprogramisdistr
ibutedinthehopethatitwillbeuseful,butWITHOUT*ANYWARRANTY;withouteventheimpliedwa
rrantyofMERCHANTABILITYor*FITNESSFORAPARTICULARPURPOSE.SeetheGNUGeneralPublicLic
ensefor*moredetails.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealon
g*withthisprogram;seethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.
,51FranklinSt,FifthFloor,Boston,MA02110-1301USA*/#include"config.h"#include<Pyth
on.h>#include<string.h>#include<stdlib.h>#include<wchar.h>#include"getopt.h"#inc
lude"command_graph.h"#include"clippy.h"#ifPY_MAJOR_VERSION>=3#definepycharwchar_
tstaticwchar_t*wconv(constchar*s){size_toutlen=mbstowcs(NULL,s,0);wchar_t*out=ma
lloc((outlen+1)*sizeof(wchar_t));mbstowcs(out,s,outlen+1);out[outlen]=0;returnou
t;}#else#definepycharchar#definewconv(x)x#endifintmain(intargc,char**argv){pycha
r**wargv;#ifPY_VERSION_HEX>=0x03040000/*3.4*/Py_SetStandardStreamEncoding("UTF-8
",NULL);#endifPy_SetProgramName(wconv(argv[0]));PyImport_AppendInittab("_clippy"
,command_py_init);Py_Initialize();wargv=malloc(argc*sizeof(pychar*));for(inti=1;
i<argc;i++)wargv[i-1]=wconv(argv[i]);PySys_SetArgv(argc-1,wargv);constchar*pyfil
e=argc>1?argv[1]:NULL;FILE*fp;if(pyfile){fp=fopen(pyfile,"r");if(!fp){fprintf(st
derr,"%s:%s\n",pyfile,strerror(errno));return1;}}else{fp=stdin;char*ver=strdup(P
y_GetVersion());char*cr=strchr(ver,'\n');if(cr)*cr='';fprintf(stderr,"clippyinte
ractiveshell\n(Python%s)\n",ver);free(ver);PyRun_SimpleString("importrlcompleter
,readline\n""readline.parse_and_bind('tab:complete')");}if(PyRun_AnyFile(fp,pyfi
le)){if(PyErr_Occurred())PyErr_Print();elseprintf("unknownpythonfailure(?)\n");r
eturn1;}Py_Finalize();#ifPY_MAJOR_VERSION>=3for(inti=1;i<argc;i++)free(wargv[i-1
]);#endiffree(wargv);return0;}/*andnowfortheuglypart...providesimplifiedloggingf
unctionssowe*don'tneedtolinklibzebra(whichwouldbeacircularbuilddep)*/#ifdef__ASS
ERT_FUNCTION#undef__ASSERT_FUNCTION#endif#include"log.h"#include"zassert.h"#defi
neZLOG_FUNC(FUNCNAME)\voidFUNCNAME(constchar*format,...)\{\va_listargs;\va_start
(args,format);\vfprintf(stderr,format,args);\fputs("\n",stderr);\va_end(args);\}
ZLOG_FUNC(zlog_err)ZLOG_FUNC(zlog_warn)ZLOG_FUNC(zlog_info)ZLOG_FUNC(zlog_notice
)ZLOG_FUNC(zlog_debug)void_zlog_assert_failed(constchar*assertion,constchar*file
,unsignedintline,constchar*function){fprintf(stderr,"Assertion`%s'failedinfile%s
,line%u,function%s",assertion,file,line,(function?function:"?"));abort();}voidme
mory_oom(size_tsize,constchar*name){abort();}