/**Zebraconfigurationcommandinterfaceroutine*Copyright(C)1997,98KunihiroIshiguro
**ThisfileispartofGNUZebra.**GNUZebraisfreesoftware;youcanredistributeitand/ormo
dify*itunderthetermsoftheGNUGeneralPublicLicenseaspublished*bytheFreeSoftwareFou
ndation;eitherversion2,or(atyour*option)anylaterversion.**GNUZebraisdistributedi
nthehopethatitwillbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyo
f*MERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicensefo
rmoredetails.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*witht
hisprogram;seethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51Fran
klinSt,FifthFloor,Boston,MA02110-1301USA*/#ifndef_ZEBRA_COMMAND_H#define_ZEBRA_C
OMMAND_H#include"vector.h"#include"vty.h"#include"lib/route_types.h"#include"gra
ph.h"#include"memory.h"#include"hash.h"#include"command_graph.h"DECLARE_MTYPE(HO
ST)DECLARE_MTYPE(COMPLETION)/*fortest-commands.c*/DECLARE_MTYPE(STRVEC)/*Hostcon
figurationvariable*/structhost{/*Hostnameofthisrouter.*/char*name;/*Domainnameof
thisrouter*/char*domainname;/*Passwordforvtyinterface.*/char*password;char*passw
ord_encrypt;/*Enablepassword*/char*enable;char*enable_encrypt;/*Systemwidetermin
allines.*/intlines;/*Logfilename.*/char*logfile;/*configfilenameofthishost*/char
*config;intnoconfig;/*Flagsforservices*/intadvanced;intencrypt;/*Bannerconfigura
tion.*/constchar*motd;char*motdfile;};/*ListofCLInodes.Pleaseremembertoupdatethe
namearrayincommand.c.*/enumnode_type{AUTH_NODE,/*Authenticationmodeofvtyinterfac
e.*/VIEW_NODE,/*Viewnode.Defaultmodeofvtyinterface.*/AUTH_ENABLE_NODE,/*Authenti
cationmodeforchangeenable.*/ENABLE_NODE,/*Enablenode.*/CONFIG_NODE,/*Confignode.
Defaultmodeofconfigfile.*/SERVICE_NODE,/*Servicenode.*/DEBUG_NODE,/*Debugnode.*/
VRF_DEBUG_NODE,/*VrfDebugnode.*/DEBUG_VNC_NODE,/*DebugVNCnode.*/AAA_NODE,/*AAAno
de.*/KEYCHAIN_NODE,/*Key-chainnode.*/KEYCHAIN_KEY_NODE,/*Key-chainkeynode.*/LOGI
CALROUTER_NODE,/*Logical-Routernode.*/VRF_NODE,/*VRFmodenode.*/INTERFACE_NODE,/*
Interfacemodenode.*/NH_GROUP_NODE,/*Nexthop-Groupmodenode.*/ZEBRA_NODE,/*zebraco
nnectionnode.*/TABLE_NODE,/*rtm_tableselectionnode.*/RIP_NODE,/*RIPprotocolmoden
ode.*/RIPNG_NODE,/*RIPngprotocolmodenode.*/BABEL_NODE,/*BABELprotocolmodenode.*/
EIGRP_NODE,/*EIGRPprotocolmodenode.*/BGP_NODE,/*BGPprotocolmodewhichincludesBGP4
+*/BGP_VPNV4_NODE,/*BGPMPLS-VPNPEexchange.*/BGP_VPNV6_NODE,/*BGPMPLS-VPNPEexchan
ge.*/BGP_IPV4_NODE,/*BGPIPv4unicastaddressfamily.*/BGP_IPV4M_NODE,/*BGPIPv4multi
castaddressfamily.*/BGP_IPV4L_NODE,/*BGPIPv4labeledunicastaddressfamily.*/BGP_IP
V6_NODE,/*BGPIPv6addressfamily*/BGP_IPV6M_NODE,/*BGPIPv6multicastaddressfamily.*
/BGP_IPV6L_NODE,/*BGPIPv6labeledunicastaddressfamily.*/BGP_VRF_POLICY_NODE,/*BGP
VRFpolicy*/BGP_VNC_DEFAULTS_NODE,/*BGPVNCnvedefaults*/BGP_VNC_NVE_GROUP_NODE,/*B
GPVNCnvegroup*/BGP_VNC_L2_GROUP_NODE,/*BGPVNCL2group*/RFP_DEFAULTS_NODE,/*RFPdef
aultsnode*/BGP_EVPN_NODE,/*BGPEVPNnode.*/OSPF_NODE,/*OSPFprotocolmode*/OSPF6_NOD
E,/*OSPFprotocolforIPv6mode*/LDP_NODE,/*LDPprotocolmode*/LDP_IPV4_NODE,/*LDPIPv4
addressfamily*/LDP_IPV6_NODE,/*LDPIPv6addressfamily*/LDP_IPV4_IFACE_NODE,/*LDPIP
v4Interface*/LDP_IPV6_IFACE_NODE,/*LDPIPv6Interface*/LDP_L2VPN_NODE,/*LDPL2VPNno
de*/LDP_PSEUDOWIRE_NODE,/*LDPPseudowirenode*/ISIS_NODE,/*ISISprotocolmode*/MASC_
NODE,/*MASCformulticast.*/IRDP_NODE,/*ICMPRouterDiscoveryProtocolmode.*/IP_NODE,
/*Staticiproutenode.*/ACCESS_NODE,/*Accesslistnode.*/PREFIX_NODE,/*Prefixlistnod
e.*/ACCESS_IPV6_NODE,/*Accesslistnode.*/ACCESS_MAC_NODE,/*MACaccesslistnode*/PRE
FIX_IPV6_NODE,/*Prefixlistnode.*/AS_LIST_NODE,/*ASlistnode.*/COMMUNITY_LIST_NODE
,/*Communitylistnode.*/RMAP_NODE,/*Routemapnode.*/SMUX_NODE,/*SNMPconfigurationn
ode.*/DUMP_NODE,/*Packetdumpnode.*/FORWARDING_NODE,/*IPforwardingnode.*/PROTOCOL
_NODE,/*protocolfilteringnode*/MPLS_NODE,/*MPLSconfignode*/PW_NODE,/*Pseudowirec
onfignode*/VTY_NODE,/*Vtynode.*/LINK_PARAMS_NODE,/*Link-parametersnode*/BGP_EVPN
_VNI_NODE,/*BGPEVPNVNI*/RPKI_NODE,/*RPKInodeforconfigurationofRPKIcacheservercon
nections.*/BGP_FLOWSPECV4_NODE,/*BGPIPv4FLOWSPECAddress-Family*/BGP_FLOWSPECV6_N
ODE,/*BGPIPv6FLOWSPECAddress-Family*/NODE_TYPE_MAX,/*maximum*/};externvectorcmdv
ec;externconstchar*node_names[];/*Nodewhichhassomecommandsandpromptstringandconf
igurationfunctionpointer.*/structcmd_node{/*Nodeindex.*/enumnode_typenode;/*Prom
ptcharacteratvtyinterface.*/constchar*prompt;/*Isthisnode'sconfigurationgoestovt
ysh?*/intvtysh;/*Node'sconfigurationwritefunction*/int(*func)(structvty*);/*Node
'scommandgraph*/structgraph*cmdgraph;/*Vectorofthisnode'scommandlist.*/vectorcmd
_vector;/*Hashedindexofcommandnodelist,forde-duppingprimarily*/structhash*cmd_ha
sh;};/*Returnvalueofthecommands.*/#defineCMD_SUCCESS0#defineCMD_WARNING1#defineC
MD_ERR_NO_MATCH2#defineCMD_ERR_AMBIGUOUS3#defineCMD_ERR_INCOMPLETE4#defineCMD_ER
R_EXEED_ARGC_MAX5#defineCMD_ERR_NOTHING_TODO6#defineCMD_COMPLETE_FULL_MATCH7#def
ineCMD_COMPLETE_MATCH8#defineCMD_COMPLETE_LIST_MATCH9#defineCMD_SUCCESS_DAEMON10
#defineCMD_ERR_NO_FILE11#defineCMD_SUSPEND12#defineCMD_WARNING_CONFIG_FAILED13#d
efineCMD_NOT_MY_INSTANCE14/*Argcmaxcounts.*/#defineCMD_ARGC_MAX256/*Turnoffthese
macroswhenuisngcppwithextract.pl*/#ifndefVTYSH_EXTRACT_PL/*helperdefinesforend-u
serDEFUN*macros*/#defineDEFUN_CMD_ELEMENT(funcname,cmdname,cmdstr,helpstr,attrs,
dnum)\staticstructcmd_elementcmdname={\.string=cmdstr,\.func=funcname,\.doc=help
str,\.attr=attrs,\.daemon=dnum,\.name=#cmdname,\};#defineDEFUN_CMD_FUNC_DECL(fun
cname)\staticintfuncname(conststructcmd_element*,structvty*,int,\structcmd_token
*[]);#defineDEFUN_CMD_FUNC_TEXT(funcname)\staticintfuncname(conststructcmd_eleme
nt*self\__attribute__((unused)),\structvty*vty__attribute__((unused)),\intargc__
attribute__((unused)),\structcmd_token*argv[]__attribute__((unused)))#defineDEFP
Y(funcname,cmdname,cmdstr,helpstr)\DEFUN_CMD_ELEMENT(funcname,cmdname,cmdstr,hel
pstr,0,0)\funcdecl_##funcname#defineDEFUN(funcname,cmdname,cmdstr,helpstr)\DEFUN
_CMD_FUNC_DECL(funcname)\DEFUN_CMD_ELEMENT(funcname,cmdname,cmdstr,helpstr,0,0)\
DEFUN_CMD_FUNC_TEXT(funcname)#defineDEFUN_ATTR(funcname,cmdname,cmdstr,helpstr,a
ttr)\DEFUN_CMD_FUNC_DECL(funcname)\DEFUN_CMD_ELEMENT(funcname,cmdname,cmdstr,hel
pstr,attr,0)\DEFUN_CMD_FUNC_TEXT(funcname)#defineDEFUN_HIDDEN(funcname,cmdname,c
mdstr,helpstr)\DEFUN_ATTR(funcname,cmdname,cmdstr,helpstr,CMD_ATTR_HIDDEN)#defin
eDEFUN_DEPRECATED(funcname,cmdname,cmdstr,helpstr)\DEFUN_ATTR(funcname,cmdname,c
mdstr,helpstr,CMD_ATTR_DEPRECATED)/*DEFUN_NOSHforcommandsthatvtyshshouldignore*/
#defineDEFUN_NOSH(funcname,cmdname,cmdstr,helpstr)\DEFUN(funcname,cmdname,cmdstr
,helpstr)/*DEFSHforvtysh.*/#defineDEFSH(daemon,cmdname,cmdstr,helpstr)\DEFUN_CMD
_ELEMENT(NULL,cmdname,cmdstr,helpstr,0,daemon)#defineDEFSH_HIDDEN(daemon,cmdname
,cmdstr,helpstr)\DEFUN_CMD_ELEMENT(NULL,cmdname,cmdstr,helpstr,CMD_ATTR_HIDDEN,\
daemon)/*DEFUN+DEFSH*/#defineDEFUNSH(daemon,funcname,cmdname,cmdstr,helpstr)\DEF
UN_CMD_FUNC_DECL(funcname)\DEFUN_CMD_ELEMENT(funcname,cmdname,cmdstr,helpstr,0,d
aemon)\DEFUN_CMD_FUNC_TEXT(funcname)/*DEFUN+DEFSHwithattributes*/#defineDEFUNSH_
ATTR(daemon,funcname,cmdname,cmdstr,helpstr,attr)\DEFUN_CMD_FUNC_DECL(funcname)\
DEFUN_CMD_ELEMENT(funcname,cmdname,cmdstr,helpstr,attr,daemon)\DEFUN_CMD_FUNC_TE
XT(funcname)#defineDEFUNSH_HIDDEN(daemon,funcname,cmdname,cmdstr,helpstr)\DEFUNS
H_ATTR(daemon,funcname,cmdname,cmdstr,helpstr,\CMD_ATTR_HIDDEN)#defineDEFUNSH_DE
PRECATED(daemon,funcname,cmdname,cmdstr,helpstr)\DEFUNSH_ATTR(daemon,funcname,cm
dname,cmdstr,helpstr,\CMD_ATTR_DEPRECATED)/*ALIASmacrowhichdefineexistingcommand
'salias.*/#defineALIAS(funcname,cmdname,cmdstr,helpstr)\DEFUN_CMD_ELEMENT(funcna
me,cmdname,cmdstr,helpstr,0,0)#defineALIAS_ATTR(funcname,cmdname,cmdstr,helpstr,
attr)\DEFUN_CMD_ELEMENT(funcname,cmdname,cmdstr,helpstr,attr,0)#defineALIAS_HIDD
EN(funcname,cmdname,cmdstr,helpstr)\DEFUN_CMD_ELEMENT(funcname,cmdname,cmdstr,he
lpstr,CMD_ATTR_HIDDEN,\0)#defineALIAS_DEPRECATED(funcname,cmdname,cmdstr,helpstr
)\DEFUN_CMD_ELEMENT(funcname,cmdname,cmdstr,helpstr,\CMD_ATTR_DEPRECATED,0)#defi
neALIAS_SH(daemon,funcname,cmdname,cmdstr,helpstr)\DEFUN_CMD_ELEMENT(funcname,cm
dname,cmdstr,helpstr,0,daemon)#defineALIAS_SH_HIDDEN(daemon,funcname,cmdname,cmd
str,helpstr)\DEFUN_CMD_ELEMENT(funcname,cmdname,cmdstr,helpstr,CMD_ATTR_HIDDEN,\
daemon)#defineALIAS_SH_DEPRECATED(daemon,funcname,cmdname,cmdstr,helpstr)\DEFUN_
CMD_ELEMENT(funcname,cmdname,cmdstr,helpstr,\CMD_ATTR_DEPRECATED,daemon)#else/*V
TYSH_EXTRACT_PL*/#defineDEFPY(funcname,cmdname,cmdstr,helpstr)\DEFUN(funcname,cm
dname,cmdstr,helpstr)#endif/*VTYSH_EXTRACT_PL*//*Somemacroes*//**Sometimes#defin
escreatemaximumvaluesthat*needtohavestringscreatedfromthemthat*allowtheparsertom
atchagainstthem.*Thesemacrosallowthat.*/#defineCMD_CREATE_STR(s)CMD_CREATE_STR_H
ELPER(s)#defineCMD_CREATE_STR_HELPER(s)#s#defineCMD_RANGE_STR(a,s)"("CMD_CREATE_
STR(a)"-"CMD_CREATE_STR(s)")"/*Commondescriptions.*/#defineSHOW_STR"Showrunnings
ysteminformation\n"#defineIP_STR"IPinformation\n"#defineIPV6_STR"IPv6information
\n"#defineNO_STR"Negateacommandorsetitsdefaults\n"#defineREDIST_STR"Redistribute
informationfromanotherroutingprotocol\n"#defineCLEAR_STR"Resetfunctions\n"#defin
eRIP_STR"RIPinformation\n"#defineEIGRP_STR"EIGRPinformation\n"#defineBGP_STR"BGP
information\n"#defineBGP_SOFT_STR"Softreconfiginboundandoutboundupdates\n"#defin
eBGP_SOFT_IN_STR"Sendroute-refreshunlessusing'soft-reconfigurationinbound'\n"#de
fineBGP_SOFT_OUT_STR"Resendalloutboundupdates\n"#defineBGP_SOFT_RSCLIENT_RIB_STR
"SoftreconfigforrsclientRIB\n"#defineOSPF_STR"OSPFinformation\n"#defineNEIGHBOR_
STR"Specifyneighborrouter\n"#defineDEBUG_STR"Debuggingfunctions(seealso'undebug'
)\n"#defineUNDEBUG_STR"Disabledebuggingfunctions(seealso'debug')\n"#defineROUTER
_STR"Enablearoutingprocess\n"#defineAS_STR"ASnumber\n"#defineMBGP_STR"MBGPinform
ation\n"#defineMATCH_STR"Matchvaluesfromroutingtable\n"#defineSET_STR"Setvaluesi
ndestinationroutingprotocol\n"#defineOUT_STR"Filteroutgoingroutingupdates\n"#def
ineIN_STR"Filterincomingroutingupdates\n"#defineV4NOTATION_STR"specifybyIPv4addr
essnotation(e.g.0.0.0.0)\n"#defineOSPF6_NUMBER_STR"Specifybynumber\n"#defineINTE
RFACE_STR"Interfaceinfomation\n"#defineIFNAME_STR"Interfacename(e.g.ep0)\n"#defi
neIP6_STR"IPv6Information\n"#defineOSPF6_STR"OpenShortestPathFirst(OSPF)forIPv6\
n"#defineOSPF6_INSTANCE_STR"(1-65535)InstanceID\n"#defineSECONDS_STR"Seconds\n"#
defineROUTE_STR"RoutingTable\n"#definePREFIX_LIST_STR"Buildaprefixlist\n"#define
OSPF6_DUMP_TYPE_LIST\"<neighbor|interface|area|lsa|zebra|config|dbex|spf|route|l
sdb|redistribute|hook|asbr|prefix|abr>"#defineISIS_STR"IS-ISinformation\n"#defin
eAREA_TAG_STR"[areatag]\n"#defineCOMMUNITY_AANN_STR"CommunitynumberwhereAAandNNa
re(0-65535)\n"#defineCOMMUNITY_VAL_STR"CommunitynumberinAA:NNformat(whereAAandNN
are(0-65535))orlocal-AS|no-advertise|no-export|internetoradditive\n"#defineMPLS_
TE_STR"MPLS-TEspecificcommands\n"#defineLINK_PARAMS_STR"Configureinterfacelinkpa
rameters\n"#defineOSPF_RI_STR"OSPFRouterInformationspecificcommands\n"#definePCE
_STR"PCERouterInformationspecificcommands\n"#defineMPLS_STR"MPLSinformation\n"#d
efineSR_STR"Segment-Routingspecificcommands\n"#defineWATCHFRR_STR"watchfrrinform
ation\n"#defineZEBRA_STR"Zebrainformation\n"#defineCONF_BACKUP_EXT".sav"/*IPv4on
lymachineshouldnotacceptIPv6addressforpeer'sIPaddress.SowereplaceVTYcommandstrin
glikebelow.*/#defineNEIGHBOR_ADDR_STR"Neighboraddress\nIPv6address\n"#defineNEIG
HBOR_ADDR_STR2"Neighboraddress\nNeighborIPv6address\nInterfacenameorneighbortag\
n"#defineNEIGHBOR_ADDR_STR3"Neighboraddress\nIPv6address\nInterfacename\n"/*Prot
otypes.*/externvoidinstall_node(structcmd_node*,int(*)(structvty*));externvoidin
stall_default(enumnode_type);externvoidinstall_element(enumnode_type,structcmd_e
lement*);/*knownissuewithuninstall_element:changestocmd_token->attr(i.e.*depreca
ted/hidden)arenotreversed.*/externvoiduninstall_element(enumnode_type,structcmd_
element*);/*Concatenatesargv[shift]throughargv[argc-1]intoasingleNUL-terminateds
tringwithaspacebetweeneachelement(allocatedusingXMALLOC(MTYPE_TMP)).ReturnsNULLi
fshift>=argc.*/externchar*argv_concat(structcmd_token**argv,intargc,intshift);/*
*Itispreferredthatyousettheindexinitialvalue*toa0.Thiswayinthefutureifyoumodifyt
he*clithenthereisnoneedtomodifytheinitial*valueoftheindex*/externintargv_find(st
ructcmd_token**argv,intargc,constchar*text,int*index);externvectorcmd_make_strve
c(constchar*);externvoidcmd_free_strvec(vector);externvectorcmd_describe_command
(vector,structvty*,int*status);externchar**cmd_complete_command(vector,structvty
*,int*status);externconstchar*cmd_prompt(enumnode_type);externintcommand_config_
read_one_line(structvty*vty,conststructcmd_element**,intuse_config_node);externi
ntconfig_from_file(structvty*,FILE*,unsignedint*line_num);externenumnode_typenod
e_parent(enumnode_type);externintcmd_execute_command(vector,structvty*,conststru
ctcmd_element**,int);externintcmd_execute_command_strict(vector,structvty*,const
structcmd_element**);externvoidcmd_init(int);externvoidcmd_terminate(void);exter
nvoidcmd_exit(structvty*vty);externintcmd_list_cmds(structvty*vty,intdo_permute)
;externintcmd_domainname_set(constchar*domainname);externintcmd_hostname_set(con
stchar*hostname);externconstchar*cmd_hostname_get(void);externconstchar*cmd_doma
inname_get(void);/*NOTsafeforgeneraluse;callthisonlyifDEV_BUILD!*/externvoidgram
mar_sandbox_init(void);externvectorcompletions_to_vec(structlist*completions);/*
Exporttypicalfunctions.*/externconstchar*host_config_get(void);externvoidhost_co
nfig_set(constchar*);externvoidprint_version(constchar*);externintcmd_banner_mot
d_file(constchar*);/*structhostglobal,ick*/externstructhosthost;structcmd_variab
le_handler{constchar*tokenname,*varname;void(*completions)(vectorout,structcmd_t
oken*token);};externvoidcmd_variable_complete(structcmd_token*token,constchar*ar
g,vectorcomps);externvoidcmd_variable_handler_register(conststructcmd_variable_h
andler*cvh);externchar*cmd_variable_comp2str(vectorcomps,unsignedshortcols);#end
if/*_ZEBRA_COMMAND_H*/