/**Debuggingutilities.*Copyright(C)2018CumulusNetworks,Inc.*QuentinYoung**Thispr
ogramisfreesoftware;youcanredistributeitand/ormodifyit*underthetermsoftheGNUGene
ralPublicLicenseaspublishedbytheFree*SoftwareFoundation;eitherversion2oftheLicen
se,or(atyouroption)*anylaterversion.**Thisprogramisdistributedinthehopethatitwil
lbeuseful,butWITHOUT*ANYWARRANTY;withouteventheimpliedwarrantyofMERCHANTABILITYo
r*FITNESSFORAPARTICULARPURPOSE.SeetheGNUGeneralPublicLicensefor*moredetails.**Yo
ushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethe
fileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor
,Boston,MA02110-1301USA*/#include<zebra.h>#include"debug.h"#include"command.h"st
aticconststructdebug_callbacks*callbacks;/*Allcodeinthissectionshouldbereentrant
andMT-safe*/DEFUN_NOSH(debug_all,debug_all_cmd,"[no]debugall",NO_STRDEBUG_STR"To
gglealldebuggingoutput\n"){boolset=strmatch(argv[0]->text,"no");uint32_tmode=DEB
UG_NODE2MODE(vty->node);if(callbacks->debug_set_all)callbacks->debug_set_all(mod
e,set);returnCMD_SUCCESS;}/*----------------------------------------------------
---------------------*/voiddebug_init(conststructdebug_callbacks*cb){callbacks=c
b;install_element(ENABLE_NODE,&debug_all_cmd);install_element(CONFIG_NODE,&debug
_all_cmd);}