/*Distributelistfunctionsheader*Copyright(C)1999KunihiroIshiguro**Thisfileispart
ofGNUZebra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodify*itunderthet
ermsoftheGNUGeneralPublicLicenseaspublished*bytheFreeSoftwareFoundation;eitherve
rsion2,or(atyour*option)anylaterversion.**GNUZebraisdistributedinthehopethatitwi
llbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILIT
YorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Y
oushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seeth
efileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloo
r,Boston,MA02110-1301USA*/#ifndef_ZEBRA_DISTRIBUTE_H#define_ZEBRA_DISTRIBUTE_H#i
nclude<zebra.h>#include"if.h"#include"filter.h"/*Disctirubtelisttypes.*/enumdist
ribute_type{DISTRIBUTE_V4_IN,DISTRIBUTE_V6_IN,DISTRIBUTE_V4_OUT,DISTRIBUTE_V6_OU
T,DISTRIBUTE_MAX};structdistribute{/*Nameoftheinterface.*/char*ifname;/*Filterna
meof`in'and`out'*/char*list[DISTRIBUTE_MAX];/*prefix-listnameof`in'and`out'*/cha
r*prefix[DISTRIBUTE_MAX];};/*Prototypesfordistribute-list.*/externvoiddistribute
_list_init(int);externvoiddistribute_list_reset(void);externvoiddistribute_list_
add_hook(void(*)(structdistribute*));externvoiddistribute_list_delete_hook(void(
*)(structdistribute*));externstructdistribute*distribute_lookup(constchar*);exte
rnintconfig_write_distribute(structvty*);externintconfig_show_distribute(structv
ty*);externenumfilter_typedistribute_apply_in(structinterface*,structprefix*);ex
ternenumfilter_typedistribute_apply_out(structinterface*,structprefix*);#endif/*
_ZEBRA_DISTRIBUTE_H*/