/**Copyright(c)2015-16DavidLamparter,forNetDEF,Inc.**Permissiontouse,copy,modify
,anddistributethissoftwareforany*purposewithorwithoutfeeisherebygranted,provided
thattheabove*copyrightnoticeandthispermissionnoticeappearinallcopies.**THESOFTWA
REISPROVIDED"ASIS"ANDTHEAUTHORDISCLAIMSALLWARRANTIES*WITHREGARDTOTHISSOFTWAREINC
LUDINGALLIMPLIEDWARRANTIESOF*MERCHANTABILITYANDFITNESS.INNOEVENTSHALLTHEAUTHORBE
LIABLEFOR*ANYSPECIAL,DIRECT,INDIRECT,ORCONSEQUENTIALDAMAGESORANYDAMAGES*WHATSOEV
ERRESULTINGFROMLOSSOFUSE,DATAORPROFITS,WHETHERINAN*ACTIONOFCONTRACT,NEGLIGENCEOR
OTHERTORTIOUSACTION,ARISINGOUTOF*ORINCONNECTIONWITHTHEUSEORPERFORMANCEOFTHISSOFT
WARE.*/#ifndef_FRR_FERR_H#define_FRR_FERR_H/************************************
************************scrolldowntotheendofthisfileforafullexample!************
************************************************/#include<stdint.h>#include<limi
ts.h>#include<errno.h>/*returntypewhenthiserrorindicationstuffisused.**guarantee
dtohavebooleanevaluationto"false"whenOK,"true"whenerror*(i.e.canbechangedtopoint
erinthefutureifneccessary)**Forchecking,alwaysuse"if(value)",nothingelse.*Do_NOT
_useanyintegerconstant(!=0),orsigncheck(<0).*/typedefintferr_r;/*roughcategoryof
errorindication*/enumferr_kind{/*noerror*/FERR_OK=0,/*somethingisn'tthewayit'ssu
pposedtobe.*(thingsthatmightotherwisebeasserts,really)*/FERR_CODE_BUG,/*user-sup
pliedparametersdon'tmakesenseorisinconsistent*ifyoucanexpressaruleforit(e.g."hol
dtime>2*keepalive"),*it'sthiscategory.*/FERR_CONFIG_INVALID,/*user-suppliedparam
etersdon'tlineupwithreality*(IPaddressorinterfacenotavailable,etc.)*NB:thesearer
eallyTODOswherethecodeneedstobefixedto*respondtofuturechanges!*/FERR_CONFIG_REAL
ITY,/*outofsomesystemresource(probablymemory)*aka"youdidn'tspendenoughmoneyerror
"*/FERR_RESOURCE,/*systemerror(permissiondenied,etc.)*/FERR_SYSTEM,/*errorreturn
fromsomeexternallibrary*(FERR_SYSTEMandFERR_LIBRARYarenotstronglydistinct)*/FERR
_LIBRARY,};structferr{/*codelocation*/constchar*file;constchar*func;intline;enum
ferr_kindkind;/*unique_idiscalculatedasachecksumofsourcefilenameanderror*message
format(*before*callingvsnprintf).Linenumberand*functionnamearenotused;thiskeepst
henumberreasonablystatic*acrosschanges.*/uint32_tunique_id;charmessage[384];/*va
lidif!=0.note"errno"mightbepreprocessorfoobar.*/interrno_val;/*validifpathname[0
]!='\0'*/charpathname[PATH_MAX];};/*geterrordetails.**NB:errval/ferr_rdoesNOTcar
rythefullerrorinformation.It'sonly*passedaroundforfutureAPIflexibility.ferr_get_
lastalwaysreturns*thelasterrorsetinthecurrentthread.*/conststructferr*ferr_get_l
ast(ferr_rerrval);/*canoptionallybecalledatstrategiclocations.*alwaysreturns0.*/
ferr_rferr_clear(void);/*doNOTcallthesefunctionsdirectly.onlyformacrouse!*/ferr_
rferr_set_internal(constchar*file,intline,constchar*func,enumferr_kindkind,const
char*text,...);ferr_rferr_set_internal_ext(constchar*file,intline,constchar*func
,enumferr_kindkind,constchar*pathname,interrno_val,constchar*text,...);#definefe
rr_ok()0/*Reportanerror.**Ifyouneedtodocleanup(freememory,etc.),savethereturnval
ueina*variableoftypeferr_r.**Don'tputa\nattheendoftheerrormessage.*/#defineferr_
code_bug(...)\ferr_set_internal(__FILE__,__LINE__,__func__,FERR_CODE_BUG,\__VA_A
RGS__)#defineferr_cfg_invalid(...)\ferr_set_internal(__FILE__,__LINE__,__func__,
FERR_CONFIG_INVALID,\__VA_ARGS__)#defineferr_cfg_reality(...)\ferr_set_internal(
__FILE__,__LINE__,__func__,FERR_CONFIG_REALITY,\__VA_ARGS__)#defineferr_cfg_reso
urce(...)\ferr_set_internal(__FILE__,__LINE__,__func__,FERR_RESOURCE,\__VA_ARGS_
_)#defineferr_system(...)\ferr_set_internal(__FILE__,__LINE__,__func__,FERR_SYST
EM,\__VA_ARGS__)#defineferr_library(...)\ferr_set_internal(__FILE__,__LINE__,__f
unc__,FERR_LIBRARY,\__VA_ARGS__)/*extendedinformationvariants*/#defineferr_syste
m_errno(...)\ferr_set_internal_ext(__FILE__,__LINE__,__func__,FERR_SYSTEM,NULL,\
errno,__VA_ARGS__)#defineferr_system_path_errno(path,...)\ferr_set_internal_ext(
__FILE__,__LINE__,__func__,FERR_SYSTEM,path,\errno,__VA_ARGS__)#include"vty.h"/*
printerrormessagetovty;$ERRisreplacedbytheerror'smessage*/voidvty_print_error(st
ructvty*vty,ferr_rerr,constchar*msg,...);#defineCMD_FERR_DO(func,action,...)\do{
\ferr_rcmd_retval=func;\if(cmd_retval){\vty_print_error(vty,cmd_retval,__VA_ARGS
__);\action;\}\}while(0)#defineCMD_FERR_RETURN(func,...)\CMD_FERR_DO(func,return
CMD_WARNING_CONFIG_FAILED,__VA_ARGS__)#defineCMD_FERR_GOTO(func,label,...)\CMD_F
ERR_DO(func,gotolabel,__VA_ARGS__)/*example:usesbogus#definetokeepindent.pyhappy
*/#ifdefTHIS_IS_AN_EXAMPLEferr_rfoo_bar_set(structobject*obj,intbar){if(bar<1||b
ar>=100)returnferr_config_invalid("barsetting(%d)mustbe0<x<100",bar);obj->bar=ba
r;if(ioctl(obj->fd,bar))returnferr_system_errno("couldn'tsetbarto%d",bar);return
ferr_ok();}DEFUN("bla"){CMD_FERR_RETURN(foo_bar_set(obj,atoi(argv[1])),"commandf
ailed:$ERR\n");returnCMD_SUCCESS;}#endif/*THIS_IS_AN_EXAMPLE*/#endif/*_FERR_H*/