/*GetoptforGNU.*NOTE:getoptisnowpartoftheClibrary,soifyoudon'tknowwhat*"Keepthis
filename-spaceclean"means,talktodrepper@gnu.org*beforechangingit!**Copyright(C)1
987,88,89,90,91,92,93,94,95,96,97,98*FreeSoftwareFoundation,Inc.**NOTE:Thecanoni
calsourceofthisfileismaintainedwiththeGNUCLibrary.*Bugscanbereportedtobug-glibc@
gnu.org.**Thisprogramisfreesoftware;youcanredistributeitand/ormodifyit*underthet
ermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eitherve
rsion2,or(atyouroption)any*laterversion.**Thisprogramisdistributedinthehopethati
twillbeuseful,*butWITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABI
LITYorFITNESSFORAPARTICULARPURPOSE.Seethe*GNUGeneralPublicLicenseformoredetails.
**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;se
ethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthF
loor,Boston,MA02110-1301USA*//*ThistellsAlphaOSF/1nottodefineagetoptprototypein<
stdio.h>.DittoforAIX3.2and<stdlib.h>.*/#ifndef_NO_PROTO#define_NO_PROTO#endif#in
clude<zebra.h>#if!defined__STDC__||!__STDC__/*Thisisaseparateconditionalsincesom
estdcsystemsreject`defined(const)'.*/#ifndefconst#defineconst#endif#endif#includ
e<stdio.h>/*CommentoutallthiscodeifweareusingtheGNUCLibrary,andarenotactuallycom
pilingthelibraryitself.ThiscodeispartoftheGNUCLibrary,butalsoincludedinmanyother
GNUdistributions.CompilingandlinkinginthiscodeisawastewhenusingtheGNUClibrary(es
peciallyifitisasharedlibrary).RatherthanhavingeveryGNUprogramunderstand`configur
e--with-gnu-libc'andomittheobjectfiles,itissimplertojustdothisinthesourceforeach
suchfile.*/#defineGETOPT_INTERFACE_VERSION2#if!defined_LIBC&&defined__GLIBC__&&_
_GLIBC__>=2#include<gnu-versions.h>#if_GNU_GETOPT_INTERFACE_VERSION==GETOPT_INTE
RFACE_VERSION#defineELIDE_CODE#endif#endif#ifndefELIDE_CODE/*Thisneedstocomeafte
rsomelibrary#includetoget__GNU_LIBRARY__defined.*/#ifdef__GNU_LIBRARY__/*Don'tin
cludestdlib.hfornon-GNUClibrariesbecausesomeofthemcontainconflictingprototypesfo
rgetopt.*/#include<stdlib.h>#include<unistd.h>#endif/*GNUClibrary.*/#ifdefVMS#in
clude<unixlib.h>#ifHAVE_STRING_H-0#include<string.h>#endif#endif#ifndef_/*Thisis
forotherGNUdistributionswithinternationalizedmessages.Whencompilinglibc,the_macr
oispredefined.*/#ifdefHAVE_LIBINTL_H#include<libintl.h>#define_(msgid)gettext(ms
gid)#else#define_(msgid)(msgid)#endif#endif/*Thisversionof`getopt'appearstotheca
llerlikestandardUnix`getopt'butitbehavesdifferentlyfortheuser,sinceitallowstheus
ertointerspersetheoptionswiththeotherarguments.As`getopt'works,itpermutestheelem
entsofARGVsothat,whenitisdone,alltheoptionsprecedeeverythingelse.Thusallapplicat
ionprogramsareextendedtohandleflexibleargumentorder.Settingtheenvironmentvariabl
ePOSIXLY_CORRECTdisablespermutation.Thenthebehavioriscompletelystandard.GNUappli
cationprogramscanuseathirdalternativemodeinwhichtheycandistinguishtherelativeord
erofoptionsandotherarguments.*/#include"getopt.h"/*Forcommunicationfrom`getopt't
othecaller.When`getopt'findsanoptionthattakesanargument,theargumentvalueisreturn
edhere.Also,when`ordering'isRETURN_IN_ORDER,eachnon-optionARGV-elementisreturned
here.*/char*optarg=NULL;/*IndexinARGVofthenextelementtobescanned.Thisisusedforco
mmunicationtoandfromthecallerandforcommunicationbetweensuccessivecallsto`getopt'
.Onentryto`getopt',zeromeansthisisthefirstcall;initialize.When`getopt'returns-1,
thisistheindexofthefirstofthenon-optionelementsthatthecallershoulditselfscan.Oth
erwise,`optind'communicatesfromonecalltothenexthowmuchofARGVhasbeenscannedsofar.
*//*1003.2saysthismustbe1beforeanycall.*/intoptind=1;/*Formerly,initializationof
getoptdependedonoptind==0,whichcausesproblemswithre-callinggetoptasprogramsgener
allydon'tknowthat.*/int__getopt_initialized=0;/*Thenextchartobescannedintheoptio
n-elementinwhichthelastoptioncharacterwereturnedwasfound.Thisallowsustopickupthe
scanwhereweleftoff.Ifthisiszero,oranullstring,itmeansresumethescanbyadvancingtot
henextARGV-element.*/staticchar*nextchar;/*Callersstorezeroheretoinhibittheerror
messageforunrecognizedoptions.*/intopterr=1;/*Settoanoptioncharacterwhichwasunre
cognized.Thismustbeinitializedonsomesystemstoavoidlinkinginthesystem'sowngetopti
mplementation.*/intoptopt='?';/*Describehowtodealwithoptionsthatfollownon-option
ARGV-elements.Ifthecallerdidnotspecifyanything,thedefaultisREQUIRE_ORDERiftheenv
ironmentvariablePOSIXLY_CORRECTisdefined,PERMUTEotherwise.REQUIRE_ORDERmeansdon'
trecognizethemasoptions;stopoptionprocessingwhenthefirstnon-optionisseen.Thisisw
hatUnixdoes.ThismodeofoperationisselectedbyeithersettingtheenvironmentvariablePO
SIXLY_CORRECT,orusing`+'asthefirstcharacterofthelistofoptioncharacters.PERMUTEis
thedefault.WepermutethecontentsofARGVaswescan,sothateventuallyallthenon-optionsa
reattheend.Thisallowsoptionstobegiveninanyorder,evenwithprogramsthatwerenotwritt
entoexpectthis.RETURN_IN_ORDERisanoptionavailabletoprogramsthatwerewrittentoexpe
ctoptionsandotherARGV-elementsinanyorderandthatcareabouttheorderingofthetwo.Wede
scribeeachnon-optionARGV-elementasifitweretheargumentofanoptionwithcharactercode
1.Using`-'asthefirstcharacterofthelistofoptioncharactersselectsthismodeofoperati
on.Thespecialargument`--'forcesanendofoption-scanningregardlessofthevalueof`orde
ring'.InthecaseofRETURN_IN_ORDER,only`--'cancause`getopt'toreturn-1with`optind'!
=ARGC.*/staticenum{REQUIRE_ORDER,PERMUTE,RETURN_IN_ORDER}ordering;/*ValueofPOSIX
LY_CORRECTenvironmentvariable.*/staticchar*posixly_correct;#ifdef__GNU_LIBRARY__
/*Wewanttoavoidinclusionofstring.hwithnon-GNUlibrariesbecausetherearemanywaysitc
ancausetrouble.Onsomesystems,itcontainsspecialmagicmacrosthatdon'tworkinGCC.*/#i
nclude<string.h>#definemy_indexstrchr#else#ifHAVE_STRING_H#include<string.h>#els
e#include<strings.h>#endif/*Avoiddependingonlibraryfunctionsorfileswhosenamesare
inconsistent.*/#ifndefgetenvexternchar*getenv();#endifstaticchar*my_index(str,ch
r)constchar*str;intchr;{while(*str){if(*str==chr)return(char*)str;str++;}return0
;}/*IfusingGCC,wecansafelydeclarestrlenthisway.IfnotusingGCC,itisoknottodeclarei
t.*/#ifdef__GNUC__/*NotethatMotorolaDelta68kR3V7comeswithGCCbutnotstddef.h.Thatw
asrelevanttocodethatwasherebefore.*/#if(!defined__STDC__||!__STDC__)&&!definedst
rlen/*gccwith-traditionaldeclaresthebuilt-instrlentoreturnint,andhasdonesoatleas
tsinceversion2.4.5.--rms.*/externintstrlen(constchar*);#endif/*not__STDC__*/#end
if/*__GNUC__*/#endif/*not__GNU_LIBRARY__*//*Handlepermutationofarguments.*//*Des
cribethepartofARGVthatcontainsnon-optionsthathavebeenskipped.`first_nonopt'isthe
indexinARGVofthefirstofthem;`last_nonopt'istheindexafterthelastofthem.*/staticin
tfirst_nonopt;staticintlast_nonopt;#ifdef_LIBC/*Bash2.0givesusanenvironmentvaria
blecontainingflagsindicatingARGVelementsthatshouldnotbeconsideredarguments.*//*D
efinedingetopt_init.c*/externchar*__getopt_nonoption_flags;staticintnonoption_fl
ags_max_len;staticintnonoption_flags_len;staticintoriginal_argc;staticchar*const
*original_argv;/*Makesuretheenvironmentvariablebash2.0putsintheenvironmentisvali
dforthegetoptcallwemustmakesurethattheARGVpassedtogetoptisthatonepassedtotheproc
ess.*/staticvoid__attribute__((unused))store_args_and_env(intargc,char*const*arg
v){/*XXXThisisnogoodsolution.Weshouldrathercopytheargssothatwecancomparethemlate
r.Butwemustnotusemalloc(3).*/original_argc=argc;original_argv=argv;}#ifdeftext_s
et_elementtext_set_element(__libc_subinit,store_args_and_env);#endif/*text_set_e
lement*/#defineSWAP_FLAGS(ch1,ch2)\if(nonoption_flags_len>0){\char__tmp=__getopt
_nonoption_flags[ch1];\__getopt_nonoption_flags[ch1]=__getopt_nonoption_flags[ch
2];\__getopt_nonoption_flags[ch2]=__tmp;\}#else/*!_LIBC*/#defineSWAP_FLAGS(ch1,c
h2)#endif/*_LIBC*//*ExchangetwoadjacentsubsequencesofARGV.Onesubsequenceiselemen
ts[first_nonopt,last_nonopt)whichcontainsallthenon-optionsthathavebeenskippedsof
ar.Theotheriselements[last_nonopt,optind),whichcontainsalltheoptionsprocessedsin
cethosenon-optionswereskipped.`first_nonopt'and`last_nonopt'arerelocatedsothatth
eydescribethenewindicesofthenon-optionsinARGVaftertheyaremoved.*/#ifdefined__STD
C__&&__STDC__staticvoidexchange(char**);#endifstaticvoidexchange(argv)char**argv
;{intbottom=first_nonopt;intmiddle=last_nonopt;inttop=optind;char*tem;/*Exchange
theshortersegmentwiththefarendofthelongersegment.Thatputstheshortersegmentintoth
erightplace.Itleavesthelongersegmentintherightplaceoverall,butitconsistsoftwopar
tsthatneedtobeswappednext.*/#ifdef_LIBC/*Firstmakesurethehandlingofthe`__getopt_
nonoption_flags'stringcanworknormally.Ourtopargumentmustbeintherangeofthestring.
*/if(nonoption_flags_len>0&&top>=nonoption_flags_max_len){/*Wemustextendthearray
.Theuserplaysgameswithusandpresentsnewarguments.*/char*new_str=malloc(top+1);if(
new_str==NULL)nonoption_flags_len=nonoption_flags_max_len=0;else{memset(__mempcp
y(new_str,__getopt_nonoption_flags,nonoption_flags_max_len),'\0',top+1-nonoption
_flags_max_len);nonoption_flags_max_len=top+1;__getopt_nonoption_flags=new_str;}
}#endifwhile(top>middle&&middle>bottom){if(top-middle>middle-bottom){/*Bottomseg
mentistheshortone.*/intlen=middle-bottom;registerinti;/*Swapitwiththetoppartofth
etopsegment.*/for(i=0;i<len;i++){tem=argv[bottom+i];argv[bottom+i]=argv[top-(mid
dle-bottom)+i];argv[top-(middle-bottom)+i]=tem;SWAP_FLAGS(bottom+i,top-(middle-b
ottom)+i);}/*Excludethemovedbottomsegmentfromfurther*swapping.*/top-=len;}else{/
*Topsegmentistheshortone.*/intlen=top-middle;registerinti;/*Swapitwiththebottomp
artofthebottomsegment.*/for(i=0;i<len;i++){tem=argv[bottom+i];argv[bottom+i]=arg
v[middle+i];argv[middle+i]=tem;SWAP_FLAGS(bottom+i,middle+i);}/*Excludethemovedt
opsegmentfromfurtherswapping.*/bottom+=len;}}/*Updaterecordsfortheslotsthenon-op
tionsnowoccupy.*/first_nonopt+=(optind-last_nonopt);last_nonopt=optind;}/*Initia
lizetheinternaldatawhenthefirstcallismade.*/#ifdefined__STDC__&&__STDC__staticco
nstchar*_getopt_initialize(int,char*const*,constchar*);#endifstaticconstchar*_ge
topt_initialize(argc,argv,optstring)intargc;char*const*argv;constchar*optstring;
{/*StartprocessingoptionswithARGV-element1(sinceARGV-element0istheprogramname);t
hesequenceofpreviouslyskippednon-optionARGV-elementsisempty.*/first_nonopt=last_
nonopt=optind;nextchar=NULL;posixly_correct=getenv("POSIXLY_CORRECT");/*Determin
ehowtohandletheorderingofoptionsandnonoptions.*/if(optstring[0]=='-'){ordering=R
ETURN_IN_ORDER;++optstring;}elseif(optstring[0]=='+'){ordering=REQUIRE_ORDER;++o
ptstring;}elseif(posixly_correct!=NULL)ordering=REQUIRE_ORDER;elseordering=PERMU
TE;#ifdef_LIBCif(posixly_correct==NULL&&argc==original_argc&&argv==original_argv
){if(nonoption_flags_max_len==0){if(__getopt_nonoption_flags==NULL||__getopt_non
option_flags[0]=='\0')nonoption_flags_max_len=-1;else{constchar*orig_str=__getop
t_nonoption_flags;intlen=nonoption_flags_max_len=strlen(orig_str);if(nonoption_f
lags_max_len<argc)nonoption_flags_max_len=argc;__getopt_nonoption_flags=(char*)m
alloc(nonoption_flags_max_len);if(__getopt_nonoption_flags==NULL)nonoption_flags
_max_len=-1;elsememset(__mempcpy(__getopt_nonoption_flags,orig_str,len),'\0',non
option_flags_max_len-len);}}nonoption_flags_len=nonoption_flags_max_len;}elsenon
option_flags_len=0;#endifreturnoptstring;}/*ScanelementsofARGV(whoselengthisARGC
)foroptioncharactersgiveninOPTSTRING.IfanelementofARGVstartswith'-',andisnotexac
tly"-"or"--",thenitisanoptionelement.Thecharactersofthiselement(asidefromtheinit
ial'-')areoptioncharacters.If`getopt'iscalledrepeatedly,itreturnssuccessivelyeac
hoftheoptioncharactersfromeachoftheoptionelements.If`getopt'findsanotheroptionch
aracter,itreturnsthatcharacter,updating`optind'and`nextchar'sothatthenextcallto`
getopt'canresumethescanwiththefollowingoptioncharacterorARGV-element.Iftherearen
omoreoptioncharacters,`getopt'returns-1.Then`optind'istheindexinARGVofthefirstAR
GV-elementthatisnotanoption.(TheARGV-elementshavebeenpermutedsothatthosethataren
otoptionsnowcomelast.)OPTSTRINGisastringcontainingthelegitimateoptioncharacters.
IfanoptioncharacterisseenthatisnotlistedinOPTSTRING,return'?'afterprintinganerro
rmessage.Ifyouset`opterr'tozero,theerrormessageissuppressedbutwestillreturn'?'.I
facharinOPTSTRINGisfollowedbyacolon,thatmeansitwantsanarg,sothefollowingtextinth
esameARGV-element,orthetextofthefollowingARGV-element,isreturnedin`optarg'.Twoco
lonsmeananoptionthatwantsanoptionalarg;ifthereistextinthecurrentARGV-element,iti
sreturnedin`optarg',otherwise`optarg'issettozero.IfOPTSTRINGstartswith`-'or`+',i
trequestsdifferentmethodsofhandlingthenon-optionARGV-elements.Seethecommentsabou
tRETURN_IN_ORDERandREQUIRE_ORDER,above.Long-namedoptionsbeginwith`--'insteadof`-
'.Theirnamesmaybeabbreviatedaslongastheabbreviationisuniqueorisanexactmatchforso
medefinedoption.Iftheyhaveanargument,itfollowstheoptionnameinthesameARGV-element
,separatedfromtheoptionnamebya`=',orelsetheinnextARGV-element.When`getopt'findsa
long-namedoption,itreturns0ifthatoption's`flag'fieldisnonzero,thevalueoftheoptio
n's`val'fieldifthe`flag'fieldiszero.TheelementsofARGVaren'treallyconst,becausewe
permutethem.Butwepretendthey'reconstintheprototypetobecompatiblewithothersystems
.LONGOPTSisavectorof`structoption'terminatedbyanelementcontaininganamewhichiszer
o.LONGINDreturnstheindexinLONGOPTofthelong-namedoptionfound.Itisonlyvalidwhenalo
ng-namedoptionhasbeenfoundbythemostrecentcall.IfLONG_ONLYisnonzero,'-'aswellas'-
-'canintroducelong-namedoptions.*/int_getopt_internal(argc,argv,optstring,longop
ts,longind,long_only)intargc;char*const*argv;constchar*optstring;conststructopti
on*longopts;int*longind;intlong_only;{optarg=NULL;if(optind==0||!__getopt_initia
lized){if(optind==0)optind=1;/*Don'tscanARGV[0],theprogramname.*/optstring=_geto
pt_initialize(argc,argv,optstring);__getopt_initialized=1;}/*TestwhetherARGV[opt
ind]pointstoanon-optionargument.Eitheritdoesnothaveoptionsyntax,orthereisanenvir
onmentflagfromtheshellindicatingitisnotanoption.Thelaterinformationisonlyusedwhe
ntheusedintheGNUlibc.*/#ifdef_LIBC#defineNONOPTION_P\(argv[optind][0]!='-'||argv
[optind][1]=='\0'\||(optind<nonoption_flags_len\&&__getopt_nonoption_flags[optin
d]=='1'))#else#defineNONOPTION_P(argv[optind][0]!='-'||argv[optind][1]=='\0')#en
difif(nextchar==NULL||*nextchar=='\0'){/*AdvancetothenextARGV-element.*//*GiveFI
RST_NONOPT&LAST_NONOPTrationalvaluesifOPTINDhasbeenmovedbackbytheuser(whomayalso
havechangedthearguments).*/if(last_nonopt>optind)last_nonopt=optind;if(first_non
opt>optind)first_nonopt=optind;if(ordering==PERMUTE){/*Ifwehavejustprocessedsome
optionsfollowingsomenon-options,exchangethemsothattheoptionscomefirst.*/if(first
_nonopt!=last_nonopt&&last_nonopt!=optind)exchange((char**)argv);elseif(last_non
opt!=optind)first_nonopt=optind;/*Skipanyadditionalnon-optionsandextendtherangeo
fnon-optionspreviouslyskipped.*/while(optind<argc&&NONOPTION_P)optind++;last_non
opt=optind;}/*ThespecialARGV-element`--'meansprematureendofoptions.Skipitlikeanu
lloption,thenexchangewithpreviousnon-optionsasifitwereanoption,thenskipeverythin
gelselikeanon-option.*/if(optind!=argc&&!strcmp(argv[optind],"--")){optind++;if(
first_nonopt!=last_nonopt&&last_nonopt!=optind)exchange((char**)argv);elseif(fir
st_nonopt==last_nonopt)first_nonopt=optind;last_nonopt=argc;optind=argc;}/*Ifweh
avedonealltheARGV-elements,stopthescanandbackoveranynon-optionsthatweskippedandp
ermuted.*/if(optind==argc){/*Setthenext-arg-indextopointatthenon-optionsthatwepr
eviouslyskipped,sothecallerwilldigestthem.*/if(first_nonopt!=last_nonopt)optind=
first_nonopt;return-1;}/*Ifwehavecometoanon-optionanddidnotpermuteit,eitherstopt
hescanordescribeittothecallerandpassitby.*/if(NONOPTION_P){if(ordering==REQUIRE_
ORDER)return-1;optarg=argv[optind++];return1;}/*Wehavefoundanotheroption-ARGV-el
ement.Skiptheinitialpunctuation.*/nextchar=(argv[optind]+1+(longopts!=NULL&&argv
[optind][1]=='-'));}/*Decodethecurrentoption-ARGV-element.*//*CheckwhethertheARG
V-elementisalongoption.Iflong_onlyandtheARGV-elementhastheform"-f",wherefisavali
dshortoption,don'tconsideritanabbreviatedformofalongoptionthatstartswithf.Otherw
isetherewouldbenowaytogivethe-fshortoption.Ontheotherhand,ifthere'salongoption"f
ubar"andtheARGV-elementis"-fu",doconsiderthatanabbreviationofthelongoption,justl
ike"--fu",andnot"-f"witharg"u".Thisdistinctionseemstobethemostusefulapproach.*/i
f(longopts!=NULL&&(argv[optind][1]=='-'||(long_only&&(argv[optind][2]||!my_index
(optstring,argv[optind][1]))))){char*nameend;conststructoption*p;conststructopti
on*pfound=NULL;intexact=0;intambig=0;intindfound=-1;intoption_index;for(nameend=
nextchar;*nameend&&*nameend!='=';nameend++)/*Donothing.*/;/*Testalllongoptionsfo
reitherexactmatchorabbreviatedmatches.*/for(p=longopts,option_index=0;p->name;p+
+,option_index++)if(!strncmp(p->name,nextchar,nameend-nextchar)){if((unsignedint
)(nameend-nextchar)==(unsignedint)strlen(p->name)){/*Exactmatchfound.*/pfound=p;
indfound=option_index;exact=1;break;}elseif(pfound==NULL){/*Firstnonexactmatchfo
und.*/pfound=p;indfound=option_index;}else/*Secondorlaternonexactmatchfound.*/am
big=1;}if(ambig&&!exact){if(opterr)fprintf(stderr,_("%s:option`%s'isambiguous\n"
),argv[0],argv[optind]);nextchar+=strlen(nextchar);optind++;optopt=0;return'?';}
if(pfound!=NULL){option_index=indfound;optind++;if(*nameend){/*Don'ttesthas_argw
ith>,becausesomeCcompilersdon'tallowittobeusedonenums.*/if(pfound->has_arg)optar
g=nameend+1;else{if(opterr){if(argv[optind-1][1]=='-')/*--option*/fprintf(stderr
,_("%s:option`--%s'doesn'tallowanargument\n"),argv[0],pfound->name);else/*+optio
nor-option*/fprintf(stderr,_("%s:option`%c%s'doesn'tallowanargument\n"),argv[0],
argv[optind-1][0],pfound->name);}nextchar+=strlen(nextchar);optopt=pfound->val;r
eturn'?';}}elseif(pfound->has_arg==1){if(optind<argc)optarg=argv[optind++];else{
if(opterr)fprintf(stderr,_("%s:option`%s'requiresanargument\n"),argv[0],argv[opt
ind-1]);nextchar+=strlen(nextchar);optopt=pfound->val;returnoptstring[0]==':'?':
':'?';}}nextchar+=strlen(nextchar);if(longind!=NULL)*longind=option_index;if(pfo
und->flag){*(pfound->flag)=pfound->val;return0;}returnpfound->val;}/*Can'tfindit
asalongoption.Ifthisisnotgetopt_long_only,ortheoptionstartswith'--'orisnotavalid
shortoption,thenit'sanerror.Otherwiseinterpretitasashortoption.*/if(!long_only||
argv[optind][1]=='-'||my_index(optstring,*nextchar)==NULL){if(opterr){if(argv[op
tind][1]=='-')/*--option*/fprintf(stderr,_("%s:unrecognizedoption`--%s'\n"),argv
[0],nextchar);else/*+optionor-option*/fprintf(stderr,_("%s:unrecognizedoption`%c
%s'\n"),argv[0],argv[optind][0],nextchar);}nextchar=(char*)"";optind++;optopt=0;
return'?';}}/*Lookatandhandlethenextshortoption-character.*/{charc=*nextchar++;c
har*temp=my_index(optstring,c);/*Increment`optind'whenwestarttoprocessitslast*ch
aracter.*/if(*nextchar=='\0')++optind;if(temp==NULL||c==':'){if(opterr){if(posix
ly_correct)/*1003.2specifiestheformatofthis*message.*/fprintf(stderr,_("%s:illeg
aloption--%c\n"),argv[0],c);elsefprintf(stderr,_("%s:invalidoption--%c\n"),argv[
0],c);}optopt=c;return'?';}/*Convenience.TreatPOSIX-Wfoosameaslongoption--foo*/i
f(temp[0]=='W'&&temp[1]==';'){char*nameend;conststructoption*p;conststructoption
*pfound=NULL;intexact=0;intambig=0;intindfound=0;intoption_index;/*Thisisanoptio
nthatrequiresanargument.*/if(*nextchar!='\0'){optarg=nextchar;/*IfweendthisARGV-
elementbytakingtherestasanarg,wemustadvancetothenextelementnow.*/optind++;}elsei
f(optind==argc){if(opterr){/*1003.2specifiestheformatofthis*message.*/fprintf(st
derr,_("%s:optionrequiresanargument--%c\n"),argv[0],c);}optopt=c;if(optstring[0]
==':')c=':';elsec='?';returnc;}else/*Wealreadyincremented`optind'once;incrementi
tagainwhentakingnextARGV-eltasargument.*/optarg=argv[optind++];/*optargisnowthea
rgument,seeifit'sinthetableoflongopts.*/for(nextchar=nameend=optarg;*nameend&&*n
ameend!='=';nameend++)/*Donothing.*/;/*Testalllongoptionsforeitherexactmatchorab
breviatedmatches.*/for(p=longopts,option_index=0;p->name;p++,option_index++)if(!
strncmp(p->name,nextchar,nameend-nextchar)){if((unsignedint)(nameend-nextchar)==
strlen(p->name)){/*Exactmatchfound.*/pfound=p;indfound=option_index;exact=1;brea
k;}elseif(pfound==NULL){/*Firstnonexactmatchfound.*/pfound=p;indfound=option_ind
ex;}else/*Secondorlaternonexact*matchfound.*/ambig=1;}if(ambig&&!exact){if(opter
r)fprintf(stderr,_("%s:option`-W%s'isambiguous\n"),argv[0],argv[optind]);nextcha
r+=strlen(nextchar);optind++;return'?';}if(pfound!=NULL){option_index=indfound;i
f(*nameend){/*Don'ttesthas_argwith>,becausesomeCcompilersdon'tallowittobeusedone
nums.*/if(pfound->has_arg)optarg=nameend+1;else{if(opterr)fprintf(stderr,_("\%s:
option`-W%s'doesn'tallowanargument\n"),argv[0],pfound->name);nextchar+=strlen(ne
xtchar);return'?';}}elseif(pfound->has_arg==1){if(optind<argc)optarg=argv[optind
++];else{if(opterr)fprintf(stderr,_("%s:option`%s'requiresanargument\n"),argv[0]
,argv[optind-1]);nextchar+=strlen(nextchar);returnoptstring[0]==':'?':':'?';}}ne
xtchar+=strlen(nextchar);if(longind!=NULL)*longind=option_index;if(pfound->flag)
{*(pfound->flag)=pfound->val;return0;}returnpfound->val;}nextchar=NULL;return'W'
;/*Lettheapplicationhandleit.*/}if(temp[1]==':'){if(temp[2]==':'){/*Thisisanopti
onthatacceptsanargument*optionally.*/if(*nextchar!='\0'){optarg=nextchar;optind+
+;}elseoptarg=NULL;nextchar=NULL;}else{/*Thisisanoptionthatrequiresanargument.*/
if(*nextchar!='\0'){optarg=nextchar;/*IfweendthisARGV-elementbytakingtherestasan
arg,wemustadvancetothenextelementnow.*/optind++;}elseif(optind==argc){if(opterr)
{/*1003.2specifiestheformat*ofthismessage.*/fprintf(stderr,_("%s:optionrequiresa
nargument--%c\n"),argv[0],c);}optopt=c;if(optstring[0]==':')c=':';elsec='?';}els
e/*Wealreadyincremented`optind'once;incrementitagainwhentakingnextARGV-eltasargu
ment.*/optarg=argv[optind++];nextchar=NULL;}}returnc;}}#ifdefREALLY_NEED_PLAIN_G
ETOPTintgetopt(argc,argv,optstring)intargc;char*const*argv;constchar*optstring;{
return_getopt_internal(argc,argv,optstring,(conststructoption*)0,(int*)0,0);}#en
dif/*REALLY_NEED_PLAIN_GETOPT*/#endif/*NotELIDE_CODE.*/#ifdefTEST/*Compilewith-D
TESTtomakeanexecutableforuseintestingtheabovedefinitionof`getopt'.*/intmain(argc
,argv)intargc;char**argv;{intc;intdigit_optind=0;while(1){intthis_option_optind=
optind?optind:1;c=getopt(argc,argv,"abc:d:0123456789");if(c==-1)break;switch(c){
case'0':case'1':case'2':case'3':case'4':case'5':case'6':case'7':case'8':case'9':
if(digit_optind!=0&&digit_optind!=this_option_optind)printf("digitsoccurintwodif
ferentargv-elements.\n");digit_optind=this_option_optind;printf("option%c\n",c);
break;case'a':printf("optiona\n");break;case'b':printf("optionb\n");break;case'c
':printf("optioncwithvalue`%s'\n",optarg);break;case'?':break;default:printf("??
getoptreturnedcharactercode0%o??\n",c);}}if(optind<argc){printf("non-optionARGV-
elements:");while(optind<argc)printf("%s",argv[optind++]);printf("\n");}exit(0);
}#endif/*TEST*/