/**TestingshimandAPIexamplesforthenewCLIbackend.**Minimalmain()torungrammar_sand
boxstandalone.*[splitoffgrammar_sandbox.c2017-01-23]*--*Copyright(C)2016CumulusN
etworks,Inc.*Copyright(C)2017DavidLamparterforNetDEF,Inc.**ThisfileispartofFreeR
angeRouting(FRR).**FRRisfreesoftware;youcanredistributeitand/ormodifyitunderthe*
termsoftheGNUGeneralPublicLicenseaspublishedbytheFreeSoftware*Foundation;eitherv
ersion2,or(atyouroption)anylaterversion.**FRRisdistributedinthehopethatitwillbeu
seful,butWITHOUTANY*WARRANTY;withouteventheimpliedwarrantyofMERCHANTABILITYorFIT
NESS*FORAPARTICULARPURPOSE.SeetheGNUGeneralPublicLicenseformore*details.**Yousho
uldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefile
COPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Bos
ton,MA02110-1301USA*/#include"command.h"#include"memory_vty.h"staticvoidvty_do_e
xit(intisexit){printf("\nend.\n");if(!isexit)exit(0);}structthread_master*master
;intmain(intargc,char**argv){structthreadthread;master=thread_master_create(NULL
);openzlog("grammar_sandbox","NONE",0,LOG_CONS|LOG_NDELAY|LOG_PID,LOG_DAEMON);zl
og_set_level(ZLOG_DEST_SYSLOG,ZLOG_DISABLED);zlog_set_level(ZLOG_DEST_STDOUT,LOG
_DEBUG);zlog_set_level(ZLOG_DEST_MONITOR,ZLOG_DISABLED);/*Libraryinits.*/cmd_ini
t(1);host.name=strdup("test");host.domainname=strdup("testdomainname");vty_init(
master);memory_init();vty_stdio(vty_do_exit);/*Fetchnextactivethread.*/while(thr
ead_fetch(master,&thread))thread_call(&thread);/*Notreached.*/exit(0);}