/**IPaddressstructure(forgenericIPv4orIPv6address)*Copyright(C)2016,2017CumulusN
etworks,Inc.**ThisfileispartofFRR.**FRRisfreesoftware;youcanredistributeitand/or
modifyit*underthetermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareF
oundation;eitherversion2,or(atyouroption)any*laterversion.**FRRisdistributedinth
ehopethatitwillbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*M
ERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformo
redetails.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicense*alongwithFRR;
seethefileCOPYING.Ifnot,writetotheFree*SoftwareFoundation,Inc.,59TemplePlace-Sui
te330,Boston,MA*02111-1307,USA.*/#ifndef__IPADDR_H__#define__IPADDR_H__#include<
zebra.h>/**GenericIPaddress-unionofIPv4andIPv6address.*/enumipaddr_type_t{IPADDR
_NONE=0,IPADDR_V4=1,/*IPv4*/IPADDR_V6=2,/*IPv6*/};structipaddr{enumipaddr_type_t
ipa_type;union{uint8_taddr;structin_addr_v4_addr;structin6_addr_v6_addr;}ip;#def
ineipaddr_v4ip._v4_addr#defineipaddr_v6ip._v6_addr};#defineIS_IPADDR_NONE(p)((p)
->ipa_type==IPADDR_NONE)#defineIS_IPADDR_V4(p)((p)->ipa_type==IPADDR_V4)#defineI
S_IPADDR_V6(p)((p)->ipa_type==IPADDR_V6)#defineSET_IPADDR_V4(p)(p)->ipa_type=IPA
DDR_V4#defineSET_IPADDR_V6(p)(p)->ipa_type=IPADDR_V6staticinlineintstr2ipaddr(co
nstchar*str,structipaddr*ip){intret;memset(ip,0,sizeof(structipaddr));ret=inet_p
ton(AF_INET,str,&ip->ipaddr_v4);if(ret>0)/*ValidIPv4address.*/{ip->ipa_type=IPAD
DR_V4;return0;}ret=inet_pton(AF_INET6,str,&ip->ipaddr_v6);if(ret>0)/*ValidIPv6ad
dress.*/{ip->ipa_type=IPADDR_V6;return0;}return-1;}staticinlinechar*ipaddr2str(s
tructipaddr*ip,char*buf,intsize){buf[0]='\0';if(ip){if(IS_IPADDR_V4(ip))inet_nto
p(AF_INET,&ip->ip.addr,buf,size);elseif(IS_IPADDR_V6(ip))inet_ntop(AF_INET6,&ip-
>ip.addr,buf,size);}returnbuf;}/**ConvertIPv4addresstoIPv4-mappedIPv6addresswhic
hisofthe*form::FFFF:<IPv4address>(RFC4291).ThisIPv6addresscanthen*beusedtorepres
enttheIPv4address,whereveronlyanIPv6address*isrequired.*/staticinlinevoidipv4_to
_ipv4_mapped_ipv6(structin6_addr*in6,structin_addrin){uint32_taddr_type=htonl(0x
FFFF);memset(in6,0,sizeof(structin6_addr));memcpy((char*)in6+8,&addr_type,sizeof
(addr_type));memcpy((char*)in6+12,&in,sizeof(structin_addr));}#endif/*__IPADDR_H
__*/