/**Zebraloggingfuncions.*Copyright(C)1997,1998,1999KunihiroIshiguro**Thisfileisp
artofGNUZebra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodifyit*undert
hetermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eithe
rversion2,or(atyouroption)any*laterversion.**GNUZebraisdistributedinthehopethati
twillbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABI
LITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.
**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;se
ethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthF
loor,Boston,MA02110-1301USA*/#ifndef_ZEBRA_LOG_PRIVATE_H#define_ZEBRA_LOG_PRIVAT
E_H#include"log.h"structzlog{constchar*ident;/*daemonname(firstargtoopenlog)*/co
nstchar*protoname;unsignedshortinstance;intmaxlvl[ZLOG_NUM_DESTS];/*maximumprior
itytosendtoassociatedloggingdestination*/intdefault_lvl;/*maxlvltouseifnoneisspe
cified*/FILE*fp;char*filename;intfacility;/*aspersyslogfacility*/intrecord_prior
ity;/*shouldmessagesloggedthroughstdioincludethepriorityofthemessage?*/intsyslog
_options;/*2ndargtoopenlog*/inttimestamp_precision;/*#ofdigitsofsubsecondprecisi
on*/};/*Defaultloggingstrucutre.*/externstructzlog*zlog_default;externconstchar*
zlog_priority[];/*Genericfunctionforzlog.*/externvoidvzlog(intpriority,constchar
*format,va_listargs);externvoidzlog(intpriority,constchar*format,...)PRINTF_ATTR
IBUTE(2,3);#endif/*_ZEBRA_LOG_PRIVATE_H*/