/**Copyright(c)2015-16DavidLamparter,forNetDEF,Inc.**Permissionisherebygranted,f
reeofcharge,toanypersonobtaininga*copyofthissoftwareandassociateddocumentationfi
les(the"Software"),*todealintheSoftwarewithoutrestriction,includingwithoutlimita
tion*therightstouse,copy,modify,merge,publish,distribute,sublicense,*and/orsellc
opiesoftheSoftware,andtopermitpersonstowhomthe*Softwareisfurnishedtodoso,subject
tothefollowingconditions:**Theabovecopyrightnoticeandthispermissionnoticeshallbe
includedin*allcopiesorsubstantialportionsoftheSoftware.**THESOFTWAREISPROVIDED"A
SIS",WITHOUTWARRANTYOFANYKIND,EXPRESSOR*IMPLIED,INCLUDINGBUTNOTLIMITEDTOTHEWARRA
NTIESOFMERCHANTABILITY,*FITNESSFORAPARTICULARPURPOSEANDNONINFRINGEMENT.INNOEVENT
SHALL*THEAUTHORSORCOPYRIGHTHOLDERSBELIABLEFORANYCLAIM,DAMAGESOROTHER*LIABILITY,W
HETHERINANACTIONOFCONTRACT,TORTOROTHERWISE,ARISING*FROM,OUTOFORINCONNECTIONWITHT
HESOFTWAREORTHEUSEOROTHER*DEALINGSINTHESOFTWARE.*/#ifndef_FRR_MODULE_H#define_FR
R_MODULE_H#include<stdint.h>#include<stdbool.h>#if!defined(__GNUC__)#errormodule
codeneedsGCCvisibilityextensions#elif__GNUC__<4#errormodulecodeneedsGCCvisibilit
yextensions#else#defineDSO_PUBLIC__attribute__((visibility("default")))#defineDS
O_SELF__attribute__((visibility("protected")))#defineDSO_LOCAL__attribute__((vis
ibility("hidden")))#endifstructfrrmod_runtime;structfrrmod_info{/*single-linefew
-wordtitle*/constchar*name;/*human-readableversionnumber,shouldnotcontainspaces*
/constchar*version;/*one-paragraphdescription*/constchar*description;int(*init)(
void);};/*primaryentrypointstructuretobepresentinloadablemoduleunder*"_frrmod_th
is_module"dlsym()name**notespaceforfutureextensionsisreservedbelow,soothermodule
s*(e.g.memorymanagement,hooks)canaddfields**constmembers/infoareinfrrmod_info.*/
structfrrmod_runtime{structfrrmod_runtime*next;conststructfrrmod_info*info;void*
dl_handle;boolfinished_loading;char*load_name;char*load_args;};/*space-reserving
foo*/struct_frrmod_runtime_size{structfrrmod_runtimer;/*thiswillbarfiffrrmod_run
timeexceeds1024bytes...*/uint8_tspace[1024-sizeof(structfrrmod_runtime)];};union
_frrmod_runtime_u{structfrrmod_runtimer;struct_frrmod_runtime_sizes;};externunio
n_frrmod_runtime_u_frrmod_this_module;#defineTHIS_MODULE(&_frrmod_this_module.r)
#defineFRR_COREMOD_SETUP(...)\staticconststructfrrmod_info_frrmod_info={__VA_ARG
S__};\DSO_LOCALunion_frrmod_runtime_u_frrmod_this_module={\.r.info=&_frrmod_info
,\};#defineFRR_MODULE_SETUP(...)\FRR_COREMOD_SETUP(__VA_ARGS__)\DSO_SELFstructfr
rmod_runtime*frr_module=&_frrmod_this_module.r;externstructfrrmod_runtime*frrmod
_list;externvoidfrrmod_init(structfrrmod_runtime*modinfo);externstructfrrmod_run
time*frrmod_load(constchar*spec,constchar*dir,char*err,size_terr_len);#if0/*noti
mplementedyet*/externvoidfrrmod_unload(structfrrmod_runtime*module);#endif#endif
/*_FRR_MODULE_H*/