/**MPLSdefinitions*Copyright2015CumulusNetworks,Inc.**ThisfileispartofGNUZebra.*
*GNUZebraisfreesoftware;youcanredistributeitand/ormodify*itunderthetermsoftheGNU
GeneralPublicLicenseaspublished*bytheFreeSoftwareFoundation;eitherversion2,or(at
your*option)anylaterversion.**GNUZebraisdistributedinthehopethatitwillbeuseful,b
ut*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFO
RAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldhave
receivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING
;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA0
2110-1301USA*/#ifndef_QUAGGA_MPLS_H#define_QUAGGA_MPLS_H#include<arpa/inet.h>#if
defMPLS_LABEL_MAX#undefMPLS_LABEL_MAX#endif/*Well-knownMPLSlabelvalues(RFC3032et
c).*/#defineMPLS_LABEL_IPV4_EXPLICIT_NULL0/*[RFC3032]*/#defineMPLS_LABEL_ROUTER_
ALERT1/*[RFC3032]*/#defineMPLS_LABEL_IPV6_EXPLICIT_NULL2/*[RFC3032]*/#defineMPLS
_LABEL_IMPLICIT_NULL3/*[RFC3032]*/#defineMPLS_LABEL_ELI7/*[RFC6790]*/#defineMPLS
_LABEL_GAL13/*[RFC5586]*/#defineMPLS_LABEL_OAM_ALERT14/*[RFC3429]*/#defineMPLS_L
ABEL_EXTENSION15/*[RFC7274]*/#defineMPLS_LABEL_MAX1048575#defineMPLS_LABEL_NONE0
xFFFFFFFF/*forinternaluseonly*//*Minimumandmaximumlabelvalues*/#defineMPLS_LABEL
_RESERVED_MIN0#defineMPLS_LABEL_RESERVED_MAX15#defineMPLS_LABEL_UNRESERVED_MIN16
#defineMPLS_LABEL_UNRESERVED_MAX1048575/*DefaultminandmaxSRGBlabelrange*//*Eveni
ftheSRGBallowstomanagedifferentLabelspacebetweenrouters,*ifanoperatorwanttouseth
esameSRGBforallitsrouter,wemustfix*acommonrange.However,CiscostartitsSRGBat16000
andJuniperends*itsSRGBat16384forOSPF.Thus,byfixingtheminimumSRGBlabelto*8000weco
ulddealwithbothCiscoandJuniper.*/#defineMPLS_DEFAULT_MIN_SRGB_LABEL8000#defineMP
LS_DEFAULT_MAX_SRGB_LABEL50000#defineMPLS_DEFAULT_MIN_SRGB_SIZE5000#defineMPLS_D
EFAULT_MAX_SRGB_SIZE20000/*Maximum#labelsthatcanbepushed.*/#defineMPLS_MAX_LABEL
S16#defineIS_MPLS_RESERVED_LABEL(label)\(label>=MPLS_LABEL_RESERVED_MIN&&label<=
MPLS_LABEL_RESERVED_MAX)#defineIS_MPLS_UNRESERVED_LABEL(label)\(label>=MPLS_LABE
L_UNRESERVED_MIN\&&label<=MPLS_LABEL_UNRESERVED_MAX)/*DefinitionsforaMPLSlabelst
ackentry(RFC3032).Thisencodesthe*label,EXP,BOSandTTLfields.*/typedefunsignedintm
pls_lse_t;#defineMPLS_LS_LABEL_MASK0xFFFFF000#defineMPLS_LS_LABEL_SHIFT12#define
MPLS_LS_EXP_MASK0x00000E00#defineMPLS_LS_EXP_SHIFT9#defineMPLS_LS_S_MASK0x000001
00#defineMPLS_LS_S_SHIFT8#defineMPLS_LS_TTL_MASK0x000000FF#defineMPLS_LS_TTL_SHI
FT0#defineMPLS_LABEL_VALUE(lse)\((lse&MPLS_LS_LABEL_MASK)>>MPLS_LS_LABEL_SHIFT)#
defineMPLS_LABEL_EXP(lse)((lse&MPLS_LS_EXP_MASK)>>MPLS_LS_EXP_SHIFT)#defineMPLS_
LABEL_BOS(lse)((lse&MPLS_LS_S_MASK)>>MPLS_LS_S_SHIFT)#defineMPLS_LABEL_TTL(lse)(
(lse&MPLS_LS_TTL_MASK)>>MPLS_LS_TTL_SHIFT)#defineIS_MPLS_LABEL_BOS(ls)(MPLS_LABE
L_BOS(ls)==1)#defineMPLS_LABEL_LEN_BITS20/*MPLSlabelvalueasa32-bit(mostlyweonlyc
areaboutthelabelvalue).*/typedefunsignedintmpls_label_t;structmpls_label_stack{u
int8_tnum_labels;uint8_treserved[3];mpls_label_tlabel[0];/*1ormorelabels*/};/*Th
eMPLSexplicit-nulllabelis0whichmeanswhenyoumemsetampls_label_t*tozeroyouhavesett
hatvariabletoexplicit-nullwhichwasprobablynot*yourintent.Thework-aroundistouseon
ebittoindicateifthe*mpls_label_thasbeensetbytheuser.MPLS_INVALID_LABELhasthisbit
clear*sothatwecanuseMPLS_INVALID_LABELtoinitializempls_label_tvariables.*/#defin
eMPLS_INVALID_LABEL0xFFFDFFFF/*LSPtypes.*/enumlsp_types_t{ZEBRA_LSP_NONE=0,/*NoL
SP.*/ZEBRA_LSP_STATIC=1,/*StaticLSP.*/ZEBRA_LSP_LDP=2,/*LDPLSP.*/ZEBRA_LSP_BGP=3
,/*BGPLSP.*/ZEBRA_LSP_SR=4,/*SegmentRoutingLSP.*/ZEBRA_LSP_SHARP=5,/*Identifierf
ortestprotocol*/};/*Functionsforbasiclabeloperations.*//*Encodealabelstackentryf
romfields;converttonetworkbyte-orderas*theNetlinkinterfaceexpectsMPLSlabelstobei
nthisformat.*/staticinlinempls_lse_tmpls_lse_encode(mpls_label_tlabel,uint32_ttt
l,uint32_texp,uint32_tbos){mpls_lse_tlse;lse=htonl((label<<MPLS_LS_LABEL_SHIFT)|
(exp<<MPLS_LS_EXP_SHIFT)|(bos?(1<<MPLS_LS_S_SHIFT):0)|(ttl<<MPLS_LS_TTL_SHIFT));
returnlse;}/*Extractthefieldsfromalabelstackentryafterconvertingtohost-byte*orde
r.Thisisexpectedtobecalledonlyformessagesreceivedoverthe*Netlinkinterface.*/stat
icinlinevoidmpls_lse_decode(mpls_lse_tlse,mpls_label_t*label,uint32_t*ttl,uint32
_t*exp,uint32_t*bos){mpls_lse_tlocal_lse;local_lse=ntohl(lse);*label=MPLS_LABEL_
VALUE(local_lse);*exp=MPLS_LABEL_EXP(local_lse);*bos=MPLS_LABEL_BOS(local_lse);*
ttl=MPLS_LABEL_TTL(local_lse);}/*Invalidlabelindexvalue(whenusedwithBGPPrefix-SI
D).Should*matchtheBGPdefinition.*/#defineMPLS_INVALID_LABEL_INDEX0xFFFFFFFF/*Pri
ntablestringforlabels(withconsiderationforreservedvalues).*/staticinlinechar*lab
el2str(mpls_label_tlabel,char*buf,size_tlen){switch(label){caseMPLS_LABEL_IPV4_E
XPLICIT_NULL:strlcpy(buf,"IPv4ExplicitNull",len);return(buf);caseMPLS_LABEL_ROUT
ER_ALERT:strlcpy(buf,"RouterAlert",len);return(buf);caseMPLS_LABEL_IPV6_EXPLICIT
_NULL:strlcpy(buf,"IPv6ExplictNull",len);return(buf);caseMPLS_LABEL_IMPLICIT_NUL
L:strlcpy(buf,"implicit-null",len);return(buf);caseMPLS_LABEL_ELI:strlcpy(buf,"E
ntropyLabelIndicator",len);return(buf);caseMPLS_LABEL_GAL:strlcpy(buf,"GenericAs
sociatedChannel",len);return(buf);caseMPLS_LABEL_OAM_ALERT:strlcpy(buf,"OAMAlert
",len);return(buf);caseMPLS_LABEL_EXTENSION:strlcpy(buf,"Extension",len);return(
buf);default:if(label<16)snprintf(buf,len,"Reserved(%u)",label);elsesnprintf(buf
,len,"%u",label);return(buf);}}#endif