/**Zebraprivileges.**Copyright(C)2003PaulJakma.*Copyright(c)2005,2011,Oracleand/
oritsaffiliates.Allrightsreserved.**ThisfileispartofGNUZebra.**GNUZebraisfreesof
tware;youcanredistributeitand/ormodifyit*underthetermsoftheGNUGeneralPublicLicen
seaspublishedbythe*FreeSoftwareFoundation;eitherversion2,or(atyouroption)any*lat
erversion.**GNUZebraisdistributedinthehopethatitwillbeuseful,but*WITHOUTANYWARRA
NTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTICULARPURPOS
E.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldhavereceivedacopyofthe
GNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;ifnot,writetotheF
reeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-1301USA*/#inc
lude<zebra.h>#include"log.h"#include"privs.h"#include"memory.h"#ifdefHAVE_CAPABI
LITIESDEFINE_MTYPE_STATIC(LIB,PRIVS,"Privilegeinformation")/*sortoutsomegenerici
nternaltypesfor:**privilegevalues(cap_value_t,priv_t)->pvalue_t*privilegeset(...
,priv_set_t)->pset_t*privilegeworkingstorage(cap_t,...)->pstorage_t**valueswethi
nkofasnumeric(they'reintsreally,butwedontknow)*setsaremostlyopaque,toholdasetofp
rivileges,relatedinsomeway.*storagebindstogetherasetofsetswe'reinterestedin.*(in
reality:cap_value_tandpriv_tareints)*/#ifdefHAVE_LCAPS/*Linuxdoesn'thavea'set'ty
pe:asetofrelatedprivileges*/struct_pset{intnum;cap_value_t*caps;};typedefcap_val
ue_tpvalue_t;typedefstruct_psetpset_t;typedefcap_tpstorage_t;#elifdefined(HAVE_S
OLARIS_CAPABILITIES)typedefpriv_tpvalue_t;typedefpriv_set_tpset_t;typedefpriv_se
t_t*pstorage_t;#else/*neitherLCAPSnorSOLARIS_CAPABILITIES*/#error"HAVE_CAPABILIT
IESdefined,butneitherLCAPSnorSolarisCapabilties!"#endif/*HAVE_LCAPS*/#endif/*HAV
E_CAPABILITIES*//*thedefaultNULLstatewereportisRAISED,butcouldbeLOWEREDif*zprivs
_terminateiscalledandtheNULLhandlerisinstalled.*/staticzebra_privs_current_tzpri
vs_null_state=ZPRIVS_RAISED;/*internalprivilegesstate*/staticstruct_zprivs_t{#if
defHAVE_CAPABILITIESpstorage_tcaps;/*workingstorage*/pset_t*syscaps_p;/*system-t
yperequestedpermittedcaps*/pset_t*syscaps_i;/*system-typerequestedinheritablecap
s*/#endif/*HAVE_CAPABILITIES*/uid_tzuid,/*uidtorunas*/zsuid;/*saveduid*/gid_tzgi
d;/*gidtorunas*/gid_tvtygrp;/*gidforvtysockets*/}zprivs_state;/*externallyexport
edbutnotdirectlyaccessedfunctions*/#ifdefHAVE_CAPABILITIESintzprivs_change_caps(
zebra_privs_ops_t);zebra_privs_current_tzprivs_state_caps(void);#endif/*HAVE_CAP
ABILITIES*/intzprivs_change_uid(zebra_privs_ops_t);zebra_privs_current_tzprivs_s
tate_uid(void);intzprivs_change_null(zebra_privs_ops_t);zebra_privs_current_tzpr
ivs_state_null(void);#ifdefHAVE_CAPABILITIES/*internalcapabilityAPI*/staticpset_
t*zcaps2sys(zebra_capabilities_t*,int);staticvoidzprivs_caps_init(structzebra_pr
ivs_t*);staticvoidzprivs_caps_terminate(void);/*MapofQuaggaabstractcapabilitiest
osystemcapabilities*/staticstruct{intnum;pvalue_t*system_caps;}cap_map[ZCAP_MAX]
={#ifdefHAVE_LCAPS/*Quagga->Linuxcapabilitiesmappings*/[ZCAP_SETID]={2,(pvalue_t
[]){CAP_SETGID,CAP_SETUID},},[ZCAP_BIND]={1,(pvalue_t[]){CAP_NET_BIND_SERVICE},}
,[ZCAP_NET_ADMIN]={1,(pvalue_t[]){CAP_NET_ADMIN},},[ZCAP_NET_RAW]={1,(pvalue_t[]
){CAP_NET_RAW},},[ZCAP_CHROOT]={1,(pvalue_t[]){CAP_SYS_CHROOT,},},[ZCAP_NICE]={1
,(pvalue_t[]){CAP_SYS_NICE},},[ZCAP_PTRACE]={1,(pvalue_t[]){CAP_SYS_PTRACE},},[Z
CAP_DAC_OVERRIDE]={1,(pvalue_t[]){CAP_DAC_OVERRIDE},},[ZCAP_READ_SEARCH]={1,(pva
lue_t[]){CAP_DAC_READ_SEARCH},},[ZCAP_SYS_ADMIN]={1,(pvalue_t[]){CAP_SYS_ADMIN},
},[ZCAP_FOWNER]={1,(pvalue_t[]){CAP_FOWNER},},#elifdefined(HAVE_SOLARIS_CAPABILI
TIES)/*HAVE_LCAPS*//*Quagga->Solarisprivilegemappings*/[ZCAP_SETID]={1,(pvalue_t
[]){PRIV_PROC_SETID},},[ZCAP_BIND]={1,(pvalue_t[]){PRIV_NET_PRIVADDR},},/*IP_CON
FIGisasubsetofNET_CONFIGandisallowedinzones*/#ifdefPRIV_SYS_IP_CONFIG[ZCAP_NET_A
DMIN]={1,(pvalue_t[]){PRIV_SYS_IP_CONFIG},},#else[ZCAP_NET_ADMIN]={1,(pvalue_t[]
){PRIV_SYS_NET_CONFIG},},#endif[ZCAP_NET_RAW]={2,(pvalue_t[]){PRIV_NET_RAWACCESS
,PRIV_NET_ICMPACCESS},},[ZCAP_CHROOT]={1,(pvalue_t[]){PRIV_PROC_CHROOT},},[ZCAP_
NICE]={1,(pvalue_t[]){PRIV_PROC_PRIOCNTL},},[ZCAP_PTRACE]={1,(pvalue_t[]){PRIV_P
ROC_SESSION},},[ZCAP_DAC_OVERRIDE]={5,(pvalue_t[]){PRIV_FILE_DAC_EXECUTE,PRIV_FI
LE_DAC_READ,PRIV_FILE_DAC_SEARCH,PRIV_FILE_DAC_WRITE,PRIV_FILE_DAC_SEARCH},},[ZC
AP_READ_SEARCH]={2,(pvalue_t[]){PRIV_FILE_DAC_SEARCH,PRIV_FILE_DAC_READ},},[ZCAP
_SYS_ADMIN]={1,(pvalue_t[]){PRIV_SYS_ADMIN},},[ZCAP_FOWNER]={1,(pvalue_t[]){PRIV
_FILE_OWNER},},#endif/*HAVE_SOLARIS_CAPABILITIES*/};#ifdefHAVE_LCAPS/*Linuxforms
ofcapabilitiesmethods*//*convertzebrasprivilegestosystemcapabilities*/staticpset
_t*zcaps2sys(zebra_capabilities_t*zcaps,intnum){pset_t*syscaps;inti,j=0,count=0;
if(!num)returnNULL;/*firstcountuphowmanysystemcapswehave*/for(i=0;i<num;i++)coun
t+=cap_map[zcaps[i]].num;if((syscaps=XCALLOC(MTYPE_PRIVS,(sizeof(pset_t)*num)))=
=NULL){fprintf(stderr,"%s:couldnotallocatesyscaps!",__func__);returnNULL;}syscap
s->caps=XCALLOC(MTYPE_PRIVS,(sizeof(pvalue_t)*count));if(!syscaps->caps){fprintf
(stderr,"%s:couldnotXCALLOCcaps!",__func__);returnNULL;}/*copythecapabilitiesove
r*/count=0;for(i=0;i<num;i++)for(j=0;j<cap_map[zcaps[i]].num;j++)syscaps->caps[c
ount++]=cap_map[zcaps[i]].system_caps[j];/*iterationsaboveshouldbeexactsameaspre
viouscount,obviously..*/syscaps->num=count;returnsyscaps;}/*setorcleartheeffecti
vecapabilitiesto/frompermitted*/intzprivs_change_caps(zebra_privs_ops_top){cap_f
lag_value_tcflag;/*shouldbenopossibilityofbeingcalledwithoutvalidcaps*/assert(zp
rivs_state.syscaps_p&&zprivs_state.caps);if(!(zprivs_state.syscaps_p&&zprivs_sta
te.caps))exit(1);if(op==ZPRIVS_RAISE)cflag=CAP_SET;elseif(op==ZPRIVS_LOWER)cflag
=CAP_CLEAR;elsereturn-1;if(!cap_set_flag(zprivs_state.caps,CAP_EFFECTIVE,zprivs_
state.syscaps_p->num,zprivs_state.syscaps_p->caps,cflag))returncap_set_proc(zpri
vs_state.caps);return-1;}zebra_privs_current_tzprivs_state_caps(void){inti;cap_f
lag_value_tval;/*shouldbenopossibilityofbeingcalledwithoutvalidcaps*/assert(zpri
vs_state.syscaps_p&&zprivs_state.caps);if(!(zprivs_state.syscaps_p&&zprivs_state
.caps))exit(1);for(i=0;i<zprivs_state.syscaps_p->num;i++){if(cap_get_flag(zprivs
_state.caps,zprivs_state.syscaps_p->caps[i],CAP_EFFECTIVE,&val)){zlog_warn("zpri
vs_state_caps:couldnotcap_get_flag,%s",safe_strerror(errno));returnZPRIVS_UNKNOW
N;}if(val==CAP_SET)returnZPRIVS_RAISED;}returnZPRIVS_LOWERED;}staticvoidzprivs_c
aps_init(structzebra_privs_t*zprivs){zprivs_state.syscaps_p=zcaps2sys(zprivs->ca
ps_p,zprivs->cap_num_p);zprivs_state.syscaps_i=zcaps2sys(zprivs->caps_i,zprivs->
cap_num_i);/*Tellkernelwewantcapsmaintainedacrossuidchanges*/if(prctl(PR_SET_KEE
PCAPS,1,0,0,0)==-1){fprintf(stderr,"privs_init:couldnotsetPR_SET_KEEPCAPS,%s\n",
safe_strerror(errno));exit(1);}/*wehavecaps,wehavenoneedtoeverchangebacktheorigi
naluser*//*onlychangeuidifwedon'thavethecorrectone*/if((zprivs_state.zuid)&&(zpr
ivs_state.zsuid!=zprivs_state.zuid)){if(setreuid(zprivs_state.zuid,zprivs_state.
zuid)){fprintf(stderr,"zprivs_init(cap):couldnotsetreuid,%s\n",safe_strerror(err
no));exit(1);}}if(!zprivs_state.syscaps_p)return;if(!(zprivs_state.caps=cap_init
())){fprintf(stderr,"privs_init:failedtocap_init,%s\n",safe_strerror(errno));exi
t(1);}if(cap_clear(zprivs_state.caps)){fprintf(stderr,"privs_init:failedtocap_cl
ear,%s\n",safe_strerror(errno));exit(1);}/*setpermittedcaps*/cap_set_flag(zprivs
_state.caps,CAP_PERMITTED,zprivs_state.syscaps_p->num,zprivs_state.syscaps_p->ca
ps,CAP_SET);/*setinheritablecaps,ifany*/if(zprivs_state.syscaps_i&&zprivs_state.
syscaps_i->num){cap_set_flag(zprivs_state.caps,CAP_INHERITABLE,zprivs_state.sysc
aps_i->num,zprivs_state.syscaps_i->caps,CAP_SET);}/*applycaps.CAP_EFFECTIVEiscle
ared.we'llraisethecapsas*andwhen,andonlywhen,theyareneeded.*/if(cap_set_proc(zpr
ivs_state.caps)){cap_tcurrent_caps;char*current_caps_text=NULL;char*wanted_caps_
text=NULL;fprintf(stderr,"privs_init:initialcap_set_procfailed:%s\n",safe_strerr
or(errno));current_caps=cap_get_proc();if(current_caps){current_caps_text=cap_to
_text(current_caps,NULL);cap_free(current_caps);}wanted_caps_text=cap_to_text(zp
rivs_state.caps,NULL);fprintf(stderr,"Wantedcaps:%s\n",wanted_caps_text?wanted_c
aps_text:"???");fprintf(stderr,"Havecaps:%s\n",current_caps_text?current_caps_te
xt:"???");if(current_caps_text)cap_free(current_caps_text);if(wanted_caps_text)c
ap_free(wanted_caps_text);exit(1);}/*setmethodsforthecallertouse*/zprivs->change
=zprivs_change_caps;zprivs->current_state=zprivs_state_caps;}staticvoidzprivs_ca
ps_terminate(void){/*clearallcapabilities*/if(zprivs_state.caps)cap_clear(zprivs
_state.caps);/*andboom,capabilitiesaregoneforever*/if(cap_set_proc(zprivs_state.
caps)){fprintf(stderr,"privs_terminate:cap_set_procfailed,%s",safe_strerror(errn
o));exit(1);}/*freeupprivatestate*/if(zprivs_state.syscaps_p->num){XFREE(MTYPE_P
RIVS,zprivs_state.syscaps_p->caps);XFREE(MTYPE_PRIVS,zprivs_state.syscaps_p);}if
(zprivs_state.syscaps_i&&zprivs_state.syscaps_i->num){XFREE(MTYPE_PRIVS,zprivs_s
tate.syscaps_i->caps);XFREE(MTYPE_PRIVS,zprivs_state.syscaps_i);}cap_free(zprivs
_state.caps);}#elifdefined(HAVE_SOLARIS_CAPABILITIES)/*!HAVE_LCAPS*//*Solarisspe
cificcapability/privilegemethods**Resources:*-the'privileges'manpage*-http://cvs
.opensolaris.org*-*http://blogs.sun.com/roller/page/gbrunett?entry=privilege_ena
bling_set_id_programs1*/staticpset_t*zprivs_caps_minimal(){pset_t*minimal;if((mi
nimal=priv_str_to_set("basic",",",NULL))==NULL){fprintf(stderr,"%s:couldn'tgetba
sicset!\n",__func__);exit(1);}/*createaminimalprivilegesetfromthebasicset*/(void
)priv_delset(minimal,PRIV_PROC_EXEC);(void)priv_delset(minimal,PRIV_PROC_INFO);(
void)priv_delset(minimal,PRIV_PROC_SESSION);(void)priv_delset(minimal,PRIV_FILE_
LINK_ANY);returnminimal;}/*convertzebrasprivilegestosystemcapabilities*/staticps
et_t*zcaps2sys(zebra_capabilities_t*zcaps,intnum){pset_t*syscaps;inti,j=0;if((sy
scaps=priv_allocset())==NULL){fprintf(stderr,"%s:couldnotallocatesyscaps!\n",__f
unc__);exit(1);}priv_emptyset(syscaps);for(i=0;i<num;i++)for(j=0;j<cap_map[zcaps
[i]].num;j++)priv_addset(syscaps,cap_map[zcaps[i]].system_caps[j]);returnsyscaps
;}/*callbackexportedtouserstoRAISEandLOWEReffectiveprivileges*fromnothingtothegi
venpermittedsetandbackdown*/intzprivs_change_caps(zebra_privs_ops_top){pset_t*pr
ivset;/*shouldbenopossibilityofbeingcalledwithoutvalidcaps*/assert(zprivs_state.
syscaps_p);if(!zprivs_state.syscaps_p){fprintf(stderr,"%s:Eek,missingprivilegedc
aps!",__func__);exit(1);}assert(zprivs_state.caps);if(!zprivs_state.caps){fprint
f(stderr,"%s:Eek,missingcaps!",__func__);exit(1);}/*toraise:copyoriginalpermitte
dasourworkingeffectiveset*tolower:copyregulareffectivesetstoredinzprivs_state.ca
ps*/if(op==ZPRIVS_RAISE)privset=zprivs_state.syscaps_p;elseif(op==ZPRIVS_LOWER)p
rivset=zprivs_state.caps;elsereturn-1;if(setppriv(PRIV_SET,PRIV_EFFECTIVE,privse
t)!=0)return-1;return0;}/*Retrievecurrentprivilegestate,isitRAISEDorLOWERED?*/ze
bra_privs_current_tzprivs_state_caps(void){zebra_privs_current_tresult;pset_t*ef
fective;if((effective=priv_allocset())==NULL){fprintf(stderr,"%s:failedtogetpriv
_allocset!%s\n",__func__,safe_strerror(errno));returnZPRIVS_UNKNOWN;}if(getppriv
(PRIV_EFFECTIVE,effective)){fprintf(stderr,"%s:failedtogetstate!%s\n",__func__,s
afe_strerror(errno));result=ZPRIVS_UNKNOWN;}else{if(priv_isequalset(effective,zp
rivs_state.syscaps_p))result=ZPRIVS_RAISED;elseif(priv_isequalset(effective,zpri
vs_state.caps))result=ZPRIVS_LOWERED;elseresult=ZPRIVS_UNKNOWN;}priv_freeset(eff
ective);returnresult;}staticvoidzprivs_caps_init(structzebra_privs_t*zprivs){pse
t_t*basic;pset_t*minimal;/*thespecifiedsets*/zprivs_state.syscaps_p=zcaps2sys(zp
rivs->caps_p,zprivs->cap_num_p);zprivs_state.syscaps_i=zcaps2sys(zprivs->caps_i,
zprivs->cap_num_i);/*nonsensicaltohavegottenherebutnothavecapabilities*/if(!zpri
vs_state.syscaps_p){fprintf(stderr,"%s:capabilitiesenabled,""butnovalidcapabilit
iessupplied\n",__func__);}/*Weretainthebasicsetinourpermittedset,asLinuxhasno*eq
uivalent.ThebasicsetonLinuxhenceisimplicit,always*there.*/if((basic=priv_str_to_
set("basic",",",NULL))==NULL){fprintf(stderr,"%s:couldn'tgetbasicset!\n",__func_
_);exit(1);}/*Addthebasicsettothepermittedset*/priv_union(basic,zprivs_state.sys
caps_p);priv_freeset(basic);/*Heykernel,weknowaboutprivileges!*thisisn'tstrictly
required,useofsetpprivshouldhavesameeffect*/if(setpflags(PRIV_AWARE,1)){fprintf(
stderr,"%s:errorsettingPRIV_AWARE!,%s\n",__func__,safe_strerror(errno));exit(1);
}/*needeithervalidoremptysetsforbothpandi..*/assert(zprivs_state.syscaps_i&&zpri
vs_state.syscaps_p);/*wehavecaps,wehavenoneedtoeverchangebacktheoriginaluser*cha
ngereal,effectiveandsavedtothespecifieduser.*//*onlychangeuidifwedon'thavethecor
rectone*/if((zprivs_state.zuid)&&(zprivs_state.zsuid!=zprivs_state.zuid)){if(set
reuid(zprivs_state.zuid,zprivs_state.zuid)){fprintf(stderr,"%s:couldnotsetreuid,
%s\n",__func__,safe_strerror(errno));exit(1);}}/*setthepermittedset*/if(setppriv
(PRIV_SET,PRIV_PERMITTED,zprivs_state.syscaps_p)){fprintf(stderr,"%s:errorsettin
gpermittedset!,%s\n",__func__,safe_strerror(errno));exit(1);}/*settheinheritable
set*/if(setppriv(PRIV_SET,PRIV_INHERITABLE,zprivs_state.syscaps_i)){fprintf(stde
rr,"%s:errorsettinginheritableset!,%s\n",__func__,safe_strerror(errno));exit(1);
}/*weneedaminimalbasicsetfor'effective',potentiallyfor*inheritabletoo*/minimal=z
privs_caps_minimal();/*nowsettheeffectivesetwithasubsetofbasicprivileges*/if(set
ppriv(PRIV_SET,PRIV_EFFECTIVE,minimal)){fprintf(stderr,"%s:errorsettingeffective
set!,%s\n",__func__,safe_strerror(errno));exit(1);}/*we'llusetheminimalsetasourw
orking-storageprivset*/zprivs_state.caps=minimal;/*setmethodsforthecallertouse*/
zprivs->change=zprivs_change_caps;zprivs->current_state=zprivs_state_caps;}stati
cvoidzprivs_caps_terminate(void){assert(zprivs_state.caps);/*clearallcapabilitie
sbyusingworking-storageprivset*/setppriv(PRIV_SET,PRIV_EFFECTIVE,zprivs_state.ca
ps);setppriv(PRIV_SET,PRIV_PERMITTED,zprivs_state.caps);setppriv(PRIV_SET,PRIV_I
NHERITABLE,zprivs_state.caps);/*freeupprivatestate*/if(zprivs_state.syscaps_p)pr
iv_freeset(zprivs_state.syscaps_p);if(zprivs_state.syscaps_i)priv_freeset(zprivs
_state.syscaps_i);priv_freeset(zprivs_state.caps);}#else/*!HAVE_LCAPS&&!HAVE_SOL
ARIS_CAPABILITIES*/#error"NeitherSolarisnorLinuxcapabilities,dazedandconfused...
"#endif/*HAVE_LCAPS*/#endif/*HAVE_CAPABILITIES*/intzprivs_change_uid(zebra_privs
_ops_top){if(zprivs_state.zsuid==zprivs_state.zuid)return0;if(op==ZPRIVS_RAISE)r
eturnseteuid(zprivs_state.zsuid);elseif(op==ZPRIVS_LOWER)returnseteuid(zprivs_st
ate.zuid);elsereturn-1;}zebra_privs_current_tzprivs_state_uid(void){return((zpri
vs_state.zuid==geteuid())?ZPRIVS_LOWERED:ZPRIVS_RAISED);}intzprivs_change_null(z
ebra_privs_ops_top){return0;}zebra_privs_current_tzprivs_state_null(void){return
zprivs_null_state;}#ifndefHAVE_GETGROUPLIST/*Solaris11hasnogetgrouplist()*/stati
cintgetgrouplist(constchar*user,gid_tgroup,gid_t*groups,int*ngroups){structgroup
*grp;size_tusridx;intpos=0,ret;if(pos<*ngroups)groups[pos]=group;pos++;setgrent(
);while((grp=getgrent())){if(grp->gr_gid==group)continue;for(usridx=0;grp->gr_me
m[usridx]!=NULL;usridx++)if(!strcmp(grp->gr_mem[usridx],user)){if(pos<*ngroups)g
roups[pos]=grp->gr_gid;pos++;break;}}endgrent();ret=(pos<=*ngroups)?pos:-1;*ngro
ups=pos;returnret;}#endif/*HAVE_GETGROUPLIST*/voidzprivs_preinit(structzebra_pri
vs_t*zprivs){structpasswd*pwentry=NULL;structgroup*grentry=NULL;if(!zprivs){fpri
ntf(stderr,"zprivs_init:calledwithNULLarg!\n");exit(1);}if(zprivs->vty_group){/*
ina"NULL"setup,thisisallowedtofailtoo,butstill*try.*/if((grentry=getgrnam(zprivs
->vty_group)))zprivs_state.vtygrp=grentry->gr_gid;elsezprivs_state.vtygrp=(gid_t
)-1;}/*NULLprivs*/if(!(zprivs->user||zprivs->group||zprivs->cap_num_p||zprivs->c
ap_num_i)){zprivs->change=zprivs_change_null;zprivs->current_state=zprivs_state_
null;return;}if(zprivs->user){if((pwentry=getpwnam(zprivs->user))==NULL){/*cantu
selog.hhereasitdependsonvty*/fprintf(stderr,"privs_init:couldnotlookupuser%s\n",
zprivs->user);exit(1);}zprivs_state.zuid=pwentry->pw_uid;zprivs_state.zgid=pwent
ry->pw_gid;}grentry=NULL;if(zprivs->group){if((grentry=getgrnam(zprivs->group))=
=NULL){fprintf(stderr,"privs_init:couldnotlookupgroup%s\n",zprivs->group);exit(1
);}zprivs_state.zgid=grentry->gr_gid;}}voidzprivs_init(structzebra_privs_t*zpriv
s){gid_tgroups[NGROUPS_MAX];inti,ngroups=0;intfound=0;/*NULLprivs*/if(!(zprivs->
user||zprivs->group||zprivs->cap_num_p||zprivs->cap_num_i))return;if(zprivs->use
r){ngroups=sizeof(groups);if(getgrouplist(zprivs->user,zprivs_state.zgid,groups,
&ngroups)<0){/*cantuselog.hhereasitdependsonvty*/fprintf(stderr,"privs_init:coul
dnotgetgrouplistforuser%s\n",zprivs->user);exit(1);}}if(zprivs->vty_group)/*Addt
hevty_grouptothesupplementarygroupssoitcanbechownedto*/{if(zprivs_state.vtygrp==
(gid_t)-1){fprintf(stderr,"privs_init:couldnotlookupvtygroup%s\n",zprivs->vty_gr
oup);exit(1);}for(i=0;i<ngroups;i++)if(groups[i]==zprivs_state.vtygrp){found++;b
reak;}if(!found){fprintf(stderr,"privs_init:user(%s)isnotpartofvtygroupspecified
(%s)\n",zprivs->user,zprivs->vty_group);exit(1);}if(i>=ngroups&&ngroups<(int)ZEB
RA_NUM_OF(groups)){groups[i]=zprivs_state.vtygrp;}}zprivs_state.zsuid=geteuid();
/*initialuid*//*addgroupsonlyifwechangeduid-otherwiseskip*/if((ngroups)&&(zprivs
_state.zsuid!=zprivs_state.zuid)){if(setgroups(ngroups,groups)){fprintf(stderr,"
privs_init:couldnotsetgroups,%s\n",safe_strerror(errno));exit(1);}}/*changegidon
lyifwechangeduid-otherwiseskip*/if((zprivs_state.zgid)&&(zprivs_state.zsuid!=zpr
ivs_state.zuid)){/*changegroupnow,forever.uidwedolater*/if(setregid(zprivs_state
.zgid,zprivs_state.zgid)){fprintf(stderr,"zprivs_init:couldnotsetregid,%s\n",saf
e_strerror(errno));exit(1);}}#ifdefHAVE_CAPABILITIESzprivs_caps_init(zprivs);#el
se/*!HAVE_CAPABILITIES*//*wedonthavecaps.we'llneedtomaintainridandsaveduid*andch
angeeuidbacktosaveduid(whowepresumehasallneccessary*privileges)wheneverweareaske
dtoraiseourprivileges.**Thisisnotworththatmuchsecuritywise,butallwecando.*/zpriv
s_state.zsuid=geteuid();/*onlychangeuidifwedon'thavethecorrectone*/if((zprivs_st
ate.zuid)&&(zprivs_state.zsuid!=zprivs_state.zuid)){if(setreuid(-1,zprivs_state.
zuid)){fprintf(stderr,"privs_init(uid):couldnotsetreuid,%s\n",safe_strerror(errn
o));exit(1);}}zprivs->change=zprivs_change_uid;zprivs->current_state=zprivs_stat
e_uid;#endif/*HAVE_CAPABILITIES*/}voidzprivs_terminate(structzebra_privs_t*zpriv
s){if(!zprivs){fprintf(stderr,"%s:noprivsstructgiven,terminating",__func__);exit
(0);}#ifdefHAVE_CAPABILITIESif(zprivs->user||zprivs->group||zprivs->cap_num_p||z
privs->cap_num_i)zprivs_caps_terminate();#else/*!HAVE_CAPABILITIES*//*onlychange
uidifwedon'thavethecorrectone*/if((zprivs_state.zuid)&&(zprivs_state.zsuid!=zpri
vs_state.zuid)){if(setreuid(zprivs_state.zuid,zprivs_state.zuid)){fprintf(stderr
,"privs_terminate:couldnotsetreuid,%s",safe_strerror(errno));exit(1);}}#endif/*H
AVE_LCAPS*/zprivs->change=zprivs_change_null;zprivs->current_state=zprivs_state_
null;zprivs_null_state=ZPRIVS_LOWERED;return;}voidzprivs_get_ids(structzprivs_id
s_t*ids){ids->uid_priv=getuid();(zprivs_state.zuid)?(ids->uid_normal=zprivs_stat
e.zuid):(ids->uid_normal=-1);(zprivs_state.zgid)?(ids->gid_normal=zprivs_state.z
gid):(ids->gid_normal=-1);(zprivs_state.vtygrp)?(ids->gid_vty=zprivs_state.vtygr
p):(ids->gid_vty=-1);return;}