/*PTMLibrary*Copyright(C)2015CumulusNetworks,Inc.**ThisfileispartofQuagga.**Quag
gaisfreesoftware;youcanredistributeitand/ormodifyit*underthetermsoftheGNUGeneral
PublicLicenseaspublishedbythe*FreeSoftwareFoundation;eitherversion2,or(atyouropt
ion)any*laterversion.**Quaggaisdistributedinthehopethatitwillbeuseful,but*WITHOU
TANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTICU
LARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldhavereceiveda
copyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;ifnot,wr
itetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-1301
USA*/#include<stdio.h>#include<stdlib.h>#include<stdbool.h>#include<stddef.h>#in
clude<string.h>#include<ctype.h>#include<unistd.h>#include<errno.h>#include<sys/
socket.h>#include"csv.h"#include"ptm_lib.h"#defineDEBUG_E0#defineDEBUG_V0#define
ERRLOG(fmt,...)\do{\if(DEBUG_E)\fprintf(stderr,"%s:%d:%s():"fmt,__FILE__,\__LINE
__,__func__,##__VA_ARGS__);\}while(0)#defineDLOG(fmt,...)\do{\if(DEBUG_V)\fprint
f(stderr,"%s:%d:%s():"fmt,__FILE__,\__LINE__,__func__,##__VA_ARGS__);\}while(0)t
ypedefstructptm_lib_msg_ctxt_s{intcmd_id;csv_t*csv;ptmlib_msg_typetype;}ptm_lib_
msg_ctxt_t;staticcsv_record_t*_ptm_lib_encode_header(csv_t*csv,csv_record_t*rec,
intmsglen,intversion,inttype,intcmd_id,char*client_name){charmsglen_buf[16],vers
_buf[16],type_buf[16],cmdid_buf[16];charclient_buf[32];csv_record_t*rec1;sprintf
(msglen_buf,"%4u",msglen);sprintf(vers_buf,"%4u",version);sprintf(type_buf,"%4u"
,type);sprintf(cmdid_buf,"%4u",cmd_id);snprintf(client_buf,17,"%16.16s",client_n
ame);if(rec){rec1=csv_encode_record(csv,rec,5,msglen_buf,vers_buf,type_buf,cmdid
_buf,client_buf);}else{rec1=csv_encode(csv,5,msglen_buf,vers_buf,type_buf,cmdid_
buf,client_buf);}return(rec1);}staticint_ptm_lib_decode_header(csv_t*csv,int*msg
len,int*version,int*type,int*cmd_id,char*client_name){char*hdr;csv_record_t*rec;
csv_field_t*fld;inti,j;csv_decode(csv,NULL);rec=csv_record_iter(csv);if(rec==NUL
L){DLOG("malformedCSV\n");return(-1);}hdr=csv_field_iter(rec,&fld);if(hdr==NULL)
{DLOG("malformedCSV\n");return(-1);}*msglen=atoi(hdr);hdr=csv_field_iter_next(&f
ld);if(hdr==NULL){DLOG("malformedCSV\n");return(-1);}*version=atoi(hdr);hdr=csv_
field_iter_next(&fld);if(hdr==NULL){DLOG("malformedCSV\n");return(-1);}*type=ato
i(hdr);hdr=csv_field_iter_next(&fld);if(hdr==NULL){DLOG("malformedCSV\n");return
(-1);}*cmd_id=atoi(hdr);hdr=csv_field_iter_next(&fld);if(hdr==NULL){DLOG("malfor
medCSV\n");return(-1);}/*removeleadingspaces*/for(i=j=0;i<csv_field_len(fld);i++
){if(!isspace((int)hdr[i])){client_name[j]=hdr[i];j++;}}client_name[j]='\0';retu
rn(0);}intptm_lib_append_msg(ptm_lib_handle_t*hdl,void*ctxt,constchar*key,constc
har*val){ptm_lib_msg_ctxt_t*p_ctxt=ctxt;csv_t*csv;csv_record_t*mh_rec,*rec;if(!p
_ctxt){ERRLOG("%s:nocontext\n",__FUNCTION__);return-1;}csv=p_ctxt->csv;mh_rec=cs
v_record_iter(csv);rec=csv_record_iter_next(mh_rec);/*appendtothehdrrecord*/rec=
csv_append_record(csv,rec,1,key);if(!rec){ERRLOG("%s:Couldnotappendkey\n",__FUNC
TION__);return-1;}rec=csv_record_iter_next(rec);/*appendtothedatarecord*/rec=csv
_append_record(csv,rec,1,val);if(!rec){ERRLOG("%s:Couldnotappendval\n",__FUNCTIO
N__);return-1;}/*updatethemsghdr*/_ptm_lib_encode_header(csv,mh_rec,(csvlen(csv)
-PTMLIB_MSG_HDR_LEN),PTMLIB_MSG_VERSION,p_ctxt->type,p_ctxt->cmd_id,hdl->client_
name);return0;}intptm_lib_init_msg(ptm_lib_handle_t*hdl,intcmd_id,inttype,void*i
n_ctxt,void**out_ctxt){ptm_lib_msg_ctxt_t*p_ctxt;ptm_lib_msg_ctxt_t*p_in_ctxt=in
_ctxt;csv_t*csv;csv_record_t*rec,*d_rec;/*Initializecsvforusingdiscreterecordbuf
fers*/csv=csv_init(NULL,NULL,PTMLIB_MSG_SZ);if(!csv){ERRLOG("%s:Couldnotallocate
csv\n",__FUNCTION__);return-1;}rec=_ptm_lib_encode_header(csv,NULL,0,PTMLIB_MSG_
VERSION,type,cmd_id,hdl->client_name);if(!rec){ERRLOG("%s:Couldnotallocaterecord
\n",__FUNCTION__);csv_clean(csv);csv_free(csv);return-1;}p_ctxt=calloc(1,sizeof(
*p_ctxt));if(!p_ctxt){ERRLOG("%s:Couldnotallocatecontext\n",__FUNCTION__);csv_cl
ean(csv);csv_free(csv);return-1;}p_ctxt->csv=csv;p_ctxt->cmd_id=cmd_id;p_ctxt->t
ype=type;*(ptm_lib_msg_ctxt_t**)out_ctxt=p_ctxt;/*callersuppliedacontexttoinitia
lizewith?*/if(p_in_ctxt){/*insertthehdrrec*/rec=csv_record_iter(p_in_ctxt->csv);
csv_clone_record(p_in_ctxt->csv,rec,&d_rec);csv_insert_record(csv,d_rec);/*inser
tthedatarec*/rec=csv_record_iter_next(rec);csv_clone_record(p_in_ctxt->csv,rec,&
d_rec);csv_insert_record(csv,d_rec);}return0;}intptm_lib_cleanup_msg(ptm_lib_han
dle_t*hdl,void*ctxt){ptm_lib_msg_ctxt_t*p_ctxt=ctxt;csv_t*csv;if(!p_ctxt){ERRLOG
("%s:nocontext\n",__FUNCTION__);return-1;}csv=p_ctxt->csv;csv_clean(csv);csv_fre
e(csv);free(p_ctxt);return0;}intptm_lib_complete_msg(ptm_lib_handle_t*hdl,void*c
txt,char*buf,int*len){ptm_lib_msg_ctxt_t*p_ctxt=ctxt;csv_t*csv;csv_record_t*rec;
if(!p_ctxt){ERRLOG("%s:nocontext\n",__FUNCTION__);return-1;}csv=p_ctxt->csv;rec=
csv_record_iter(csv);_ptm_lib_encode_header(csv,rec,(csvlen(csv)-PTMLIB_MSG_HDR_
LEN),PTMLIB_MSG_VERSION,p_ctxt->type,p_ctxt->cmd_id,hdl->client_name);/*parsecsv
contentsintostring*/if(buf&&len){if(csv_serialize(csv,buf,*len)){ERRLOG("%s:cann
otserialize\n",__FUNCTION__);return-1;}*len=csvlen(csv);}csv_clean(csv);csv_free
(csv);free(p_ctxt);return0;}intptm_lib_find_key_in_msg(void*ctxt,constchar*key,c
har*val){ptm_lib_msg_ctxt_t*p_ctxt=ctxt;csv_t*csv=p_ctxt->csv;csv_record_t*hrec,
*drec;csv_field_t*hfld,*dfld;char*hstr,*dstr;/***skipoverptmhdrifpresent*Thenext
hdristhekeys(columnname)*Thenexthdristhedata*/if(csv_num_records(csv)>2){hrec=cs
v_record_iter(csv);hrec=csv_record_iter_next(hrec);}else{hrec=csv_record_iter(cs
v);}drec=csv_record_iter_next(hrec);val[0]='\0';for(hstr=csv_field_iter(hrec,&hf
ld),dstr=csv_field_iter(drec,&dfld);(hstr&&dstr);hstr=csv_field_iter_next(&hfld)
,dstr=csv_field_iter_next(&dfld)){if(!strncmp(hstr,key,csv_field_len(hfld))){snp
rintf(val,csv_field_len(dfld)+1,"%s",dstr);return0;}}return-1;}staticint_ptm_lib
_read_ptm_socket(intfd,char*buf,intlen){intretries=0,rc;intbytes_read=0;while(by
tes_read!=len){rc=recv(fd,(void*)(buf+bytes_read),(len-bytes_read),MSG_DONTWAIT)
;if(rc<=0){if(errno&&(errno!=EAGAIN)&&(errno!=EWOULDBLOCK)){ERRLOG("fatalrecverr
or(%s),closingconnection,rc%d\n",strerror(errno),rc);return(rc);}else{if(retries
++<2){usleep(10000);continue;}DLOG("maxretries-recverror(%d-%s)bytesread%d(%d)\n
",errno,strerror(errno),bytes_read,len);return(bytes_read);}break;}else{bytes_re
ad+=rc;}}returnbytes_read;}intptm_lib_process_msg(ptm_lib_handle_t*hdl,intfd,cha
r*inbuf,intinlen,void*arg){intrc,len;charclient_name[32];intcmd_id=0,type=0,ver=
0,msglen=0;csv_t*csv;ptm_lib_msg_ctxt_t*p_ctxt=NULL;len=_ptm_lib_read_ptm_socket
(fd,inbuf,PTMLIB_MSG_HDR_LEN);if(len<=0)return(len);csv=csv_init(NULL,inbuf,PTML
IB_MSG_HDR_LEN);if(!csv){DLOG("Cannotallocatecsvforhdr\n");return(-1);}rc=_ptm_l
ib_decode_header(csv,&msglen,&ver,&type,&cmd_id,client_name);csv_clean(csv);csv_
free(csv);if(rc<0){/*couldnotdecodetheCSV-maybeitslegacycmd?*gettheentirecmdfrom
thesocketandseeifwecanprocess*it*/if(len==PTMLIB_MSG_HDR_LEN){len+=_ptm_lib_read
_ptm_socket(fd,(inbuf+PTMLIB_MSG_HDR_LEN),inlen-PTMLIB_MSG_HDR_LEN);if(len<=0)re
turn(len);}inbuf[len]='\0';/*weonlysupporttheget-statuscmd*/if(strcmp(inbuf,PTML
IB_CMD_GET_STATUS)){DLOG("unsupportedlegacycmd%s\n",inbuf);return(-1);}/*interna
llycreateacsv-stylecmd*/ptm_lib_init_msg(hdl,0,PTMLIB_MSG_TYPE_CMD,NULL,(void*)&
p_ctxt);if(!p_ctxt){DLOG("couldntallocatecontext\n");return(-1);}ptm_lib_append_
msg(hdl,p_ctxt,"cmd",PTMLIB_CMD_GET_STATUS);}else{if(msglen>inlen){DLOG("msglen[
%d]>inlen[%d]\n",msglen,inlen);return-1;}/*readtherestofthemsg*/len=_ptm_lib_rea
d_ptm_socket(fd,inbuf,msglen);if(len<=0){return(len);}inbuf[len]='\0';csv=csv_in
it(NULL,NULL,PTMLIB_MSG_SZ);if(!csv){ERRLOG("Cannotallocatecsvformsg\n");return-
1;}csv_decode(csv,inbuf);p_ctxt=calloc(1,sizeof(*p_ctxt));if(!p_ctxt){ERRLOG("%s
:Couldnotallocatecontext\n",__FUNCTION__);csv_clean(csv);csv_free(csv);return-1;
}p_ctxt->csv=csv;p_ctxt->cmd_id=cmd_id;p_ctxt->type=type;}switch(p_ctxt->type){c
asePTMLIB_MSG_TYPE_NOTIFICATION:if(hdl->notify_cb)hdl->notify_cb(arg,p_ctxt);bre
ak;casePTMLIB_MSG_TYPE_CMD:if(hdl->cmd_cb)hdl->cmd_cb(arg,p_ctxt);break;casePTML
IB_MSG_TYPE_RESPONSE:if(hdl->response_cb)hdl->response_cb(arg,p_ctxt);break;defa
ult:return-1;}csv_clean(p_ctxt->csv);csv_free(p_ctxt->csv);free(p_ctxt);returnle
n;}ptm_lib_handle_t*ptm_lib_register(char*client_name,ptm_cmd_cbcmd_cb,ptm_notif
y_cbnotify_cb,ptm_response_cbresponse_cb){ptm_lib_handle_t*hdl;hdl=calloc(1,size
of(*hdl));if(hdl){strncpy(hdl->client_name,client_name,PTMLIB_MAXNAMELEN-1);hdl-
>cmd_cb=cmd_cb;hdl->notify_cb=notify_cb;hdl->response_cb=response_cb;}returnhdl;
}voidptm_lib_deregister(ptm_lib_handle_t*hdl){if(hdl){memset(hdl,0x00,sizeof(*hd
l));free(hdl);}}