/*PTMLibrary*Copyright(C)2015CumulusNetworks,Inc.**ThisfileispartofQuagga.**Quag
gaisfreesoftware;youcanredistributeitand/ormodifyit*underthetermsoftheGNUGeneral
PublicLicenseaspublishedbythe*FreeSoftwareFoundation;eitherversion2,or(atyouropt
ion)any*laterversion.**Quaggaisdistributedinthehopethatitwillbeuseful,but*WITHOU
TANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTICU
LARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldhavereceiveda
copyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;ifnot,wr
itetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-1301
USA*/#ifndef__PTM_LIB_H__#define__PTM_LIB_H__#definePTMLIB_MSG_SZ1024#definePTML
IB_MSG_HDR_LEN37#definePTMLIB_MSG_VERSION2#definePTMLIB_MAXNAMELEN32#definePTMLI
B_CMD_GET_STATUS"get-status"#definePTMLIB_CMD_GET_BFD_CLIENT"get-bfd-client"#def
inePTMLIB_CMD_START_BFD_SESS"start-bfd-sess"#definePTMLIB_CMD_STOP_BFD_SESS"stop
-bfd-sess"typedefenum{PTMLIB_MSG_TYPE_NOTIFICATION=1,PTMLIB_MSG_TYPE_CMD,PTMLIB_
MSG_TYPE_RESPONSE,}ptmlib_msg_type;typedefenum{MODULE_BFD=0,MODULE_LLDP,MODULE_M
AX,}ptmlib_mod_type;typedefint(*ptm_cmd_cb)(void*data,void*arg);typedefint(*ptm_
notify_cb)(void*data,void*arg);typedefint(*ptm_response_cb)(void*data,void*arg);
typedefint(*ptm_log_cb)(void*data,void*arg,...);typedefstructptm_lib_handle_s{ch
arclient_name[PTMLIB_MAXNAMELEN];ptm_cmd_cbcmd_cb;ptm_notify_cbnotify_cb;ptm_res
ponse_cbresponse_cb;}ptm_lib_handle_t;/*Prototypes*/intptm_lib_process_msg(ptm_l
ib_handle_t*,int,char*,int,void*);ptm_lib_handle_t*ptm_lib_register(char*,ptm_cm
d_cb,ptm_notify_cb,ptm_response_cb);voidptm_lib_deregister(ptm_lib_handle_t*);in
tptm_lib_find_key_in_msg(void*,constchar*,char*);intptm_lib_init_msg(ptm_lib_han
dle_t*,int,int,void*,void**);intptm_lib_append_msg(ptm_lib_handle_t*,void*,const
char*,constchar*);intptm_lib_complete_msg(ptm_lib_handle_t*,void*,char*,int*);in
tptm_lib_cleanup_msg(ptm_lib_handle_t*,void*);#endif