/**Circularbufferimplementation.*Copyright(C)2017CumulusNetworks*QuentinYoung**T
hisprogramisfreesoftware;youcanredistributeitand/ormodifyit*underthetermsoftheGN
UGeneralPublicLicenseaspublishedbytheFree*SoftwareFoundation;eitherversion2ofthe
License,or(atyouroption)*anylaterversion.**Thisprogramisdistributedinthehopethat
itwillbeuseful,butWITHOUT*ANYWARRANTY;withouteventheimpliedwarrantyofMERCHANTABI
LITYor*FITNESSFORAPARTICULARPURPOSE.SeetheGNUGeneralPublicLicensefor*moredetails
.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;s
eethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,Fifth
Floor,Boston,MA02110-1301USA*/#ifndef_FRR_RINGBUF_H_#define_FRR_RINGBUF_H_#inclu
de<zebra.h>#include<stdint.h>#include"memory.h"structringbuf{size_tsize;ssize_ts
tart;ssize_tend;boolempty;uint8_t*data;};/**Createsanewringbuffer.**@paramsizebu
ffersize,inbytes*@returnthenewlycreatedbuffer*/structringbuf*ringbuf_new(size_ts
ize);/**Deletesaringbufferandfreesallassociatedresources.**@parambuftheringbuffe
rtodestroy*/voidringbuf_del(structringbuf*buf);/**Getamountofdatalefttoreadfromt
hebuffer.**@returnnumberofreadablebytes*/size_tringbuf_remain(structringbuf*buf)
;/**Getamountofspacelefttowritetothebuffer**@returnnumberofwriteablebytes*/size_
tringbuf_space(structringbuf*buf);/**Putdataintotheringbuffer.**@paramdatathedat
atoputinthebuffer*@paramsizehowmuchofdatatoputin*@returnnumberofbyteswritten;wil
lbelessthansizeiftherewasnot*enoughspace*/size_tringbuf_put(structringbuf*buf,co
nstvoid*data,size_tsize);/**Getdatafromtheringbuffer.**@paramdatawheretoputtheda
ta*@paramsizehowmuchofdatatoget*@returnnumberofbytesreadintodata;willbelessthans
izeiftherewas*notenoughdatatoread*/size_tringbuf_get(structringbuf*buf,void*data
,size_tsize);/**Peekdatafromtheringbuffer.**@paramoffsetwheretogetthedatafrom,in
bytesoffsetfromthe*startofthedata*@paramdatawheretoputthedata*@paramsizehowmuchd
atatoget*@returnnumberofbytesreadintodata;willbelessthansize*iftherewasnotenough
datatoread;willbe-1ifthe*offsetexceedstheamountofdataleftinthering*buffer*/size_
tringbuf_peek(structringbuf*buf,size_toffset,void*data,size_tsize);/**Copydatafr
omoneringbuftoanother.**@paramtodestinationringbuf*@paramfromsourceringbuf*@para
msizehowmuchdatatocopy*@returnamountofdatacopied*/size_tringbuf_copy(structringb
uf*to,structringbuf*from,size_tsize);/**Resetbuffer.Doesnotwipe.**@parambuf*/voi
dringbuf_reset(structringbuf*buf);/**Resetbuffer.Wipes.**@parambuf*/voidringbuf_
wipe(structringbuf*buf);#endif/*_FRR_RINGBUF_H_*/