/**Circularbufferimplementation.*Copyright(C)2017CumulusNetworks*QuentinYoung**T
hisprogramisfreesoftware;youcanredistributeitand/ormodifyit*underthetermsoftheGN
UGeneralPublicLicenseaspublishedbytheFree*SoftwareFoundation;eitherversion2ofthe
License,or(atyouroption)*anylaterversion.**Thisprogramisdistributedinthehopethat
itwillbeuseful,butWITHOUT*ANYWARRANTY;withouteventheimpliedwarrantyofMERCHANTABI
LITYor*FITNESSFORAPARTICULARPURPOSE.SeetheGNUGeneralPublicLicensefor*moredetails
.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;s
eethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,Fifth
Floor,Boston,MA02110-1301USA*/#include<zebra.h>#include"ringbuf.h"#include"memor
y.h"DEFINE_MTYPE_STATIC(LIB,RINGBUFFER,"Ringbuffer")structringbuf*ringbuf_new(si
ze_tsize){structringbuf*buf=XCALLOC(MTYPE_RINGBUFFER,sizeof(structringbuf));buf-
>data=XCALLOC(MTYPE_RINGBUFFER,size);buf->size=size;buf->empty=true;returnbuf;}v
oidringbuf_del(structringbuf*buf){XFREE(MTYPE_RINGBUFFER,buf->data);XFREE(MTYPE_
RINGBUFFER,buf);}size_tringbuf_remain(structringbuf*buf){ssize_tdiff=buf->end-bu
f->start;diff+=((diff==0)&&!buf->empty)?buf->size:0;diff+=(diff<0)?buf->size:0;r
eturn(size_t)diff;}size_tringbuf_space(structringbuf*buf){returnbuf->size-ringbu
f_remain(buf);}size_tringbuf_put(structringbuf*buf,constvoid*data,size_tsize){co
nstuint8_t*dp=data;size_tspace=ringbuf_space(buf);size_tcopysize=MIN(size,space)
;size_ttocopy=copysize;if(tocopy>=buf->size-buf->end){size_tts=buf->size-buf->en
d;memcpy(buf->data+buf->end,dp,ts);buf->end=0;tocopy-=ts;dp+=ts;}memcpy(buf->dat
a+buf->end,dp,tocopy);buf->end+=tocopy;buf->empty=(buf->start==buf->end)&&(buf->
empty&&!copysize);returncopysize;}size_tringbuf_get(structringbuf*buf,void*data,
size_tsize){uint8_t*dp=data;size_tremain=ringbuf_remain(buf);size_tcopysize=MIN(
remain,size);size_ttocopy=copysize;if(tocopy>=buf->size-buf->start){size_tts=buf
->size-buf->start;memcpy(dp,buf->data+buf->start,ts);buf->start=0;tocopy-=ts;dp+
=ts;}memcpy(dp,buf->data+buf->start,tocopy);buf->start=buf->start+tocopy;buf->em
pty=(buf->start==buf->end)&&(buf->empty||copysize);returncopysize;}size_tringbuf
_peek(structringbuf*buf,size_toffset,void*data,size_tsize){uint8_t*dp=data;size_
tremain=ringbuf_remain(buf);if(offset>=remain)return0;size_tcopysize=MAX(MIN(rem
ain-offset,size),(size_t)0);size_ttocopy=copysize;size_tcstart=(buf->start+offse
t)%buf->size;if(tocopy>=buf->size-cstart){size_tts=buf->size-cstart;memcpy(dp,bu
f->data+cstart,ts);cstart=0;tocopy-=ts;dp+=ts;}memcpy(dp,buf->data+cstart,tocopy
);returncopysize;}size_tringbuf_copy(structringbuf*to,structringbuf*from,size_ts
ize){size_ttocopy=MIN(ringbuf_space(to),size);uint8_t*cbuf=XCALLOC(MTYPE_TMP,toc
opy);tocopy=ringbuf_peek(from,0,cbuf,tocopy);size_tput=ringbuf_put(to,cbuf,tocop
y);XFREE(MTYPE_TMP,cbuf);returnput;}voidringbuf_reset(structringbuf*buf){buf->st
art=buf->end=0;buf->empty=true;}voidringbuf_wipe(structringbuf*buf){memset(buf->
data,0x00,buf->size);ringbuf_reset(buf);}