/*Routemapfunction.*Copyright(C)1998,1999KunihiroIshiguro**ThisfileispartofGNUZe
bra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodifyit*underthetermsoft
heGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eitherversion2,
or(atyouroption)any*laterversion.**GNUZebraisdistributedinthehopethatitwillbeuse
ful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITN
ESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshoul
dhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCO
PYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Bosto
n,MA02110-1301USA*/#include<zebra.h>#include"linklist.h"#include"memory.h"#inclu
de"vector.h"#include"prefix.h"#include"vty.h"#include"routemap.h"#include"comman
d.h"#include"log.h"#include"hash.h"#include"libfrr.h"DEFINE_MTYPE_STATIC(LIB,ROU
TE_MAP,"Routemap")DEFINE_MTYPE(LIB,ROUTE_MAP_NAME,"Routemapname")DEFINE_MTYPE_ST
ATIC(LIB,ROUTE_MAP_INDEX,"Routemapindex")DEFINE_MTYPE(LIB,ROUTE_MAP_RULE,"Routem
aprule")DEFINE_MTYPE_STATIC(LIB,ROUTE_MAP_RULE_STR,"Routemaprulestr")DEFINE_MTYP
E(LIB,ROUTE_MAP_COMPILED,"Routemapcompiled")DEFINE_MTYPE_STATIC(LIB,ROUTE_MAP_DE
P,"Routemapdependency")DEFINE_QOBJ_TYPE(route_map_index)DEFINE_QOBJ_TYPE(route_m
ap)/*Vectorforroutematchrules.*/staticvectorroute_match_vec;/*Vectorforroutesetr
ules.*/staticvectorroute_set_vec;structroute_map_match_set_hooks{/*matchinterfac
e*/int(*match_interface)(structvty*vty,structroute_map_index*index,constchar*com
mand,constchar*arg,route_map_event_ttype);/*nomatchinterface*/int(*no_match_inte
rface)(structvty*vty,structroute_map_index*index,constchar*command,constchar*arg
,route_map_event_ttype);/*matchipaddress*/int(*match_ip_address)(structvty*vty,s
tructroute_map_index*index,constchar*command,constchar*arg,route_map_event_ttype
);/*nomatchipaddress*/int(*no_match_ip_address)(structvty*vty,structroute_map_in
dex*index,constchar*command,constchar*arg,route_map_event_ttype);/*matchipaddres
sprefixlist*/int(*match_ip_address_prefix_list)(structvty*vty,structroute_map_in
dex*index,constchar*command,constchar*arg,route_map_event_ttype);/*nomatchipaddr
essprefixlist*/int(*no_match_ip_address_prefix_list)(structvty*vty,structroute_m
ap_index*index,constchar*command,constchar*arg,route_map_event_ttype);/*matchipn
exthop*/int(*match_ip_next_hop)(structvty*vty,structroute_map_index*index,constc
har*command,constchar*arg,route_map_event_ttype);/*nomatchipnexthop*/int(*no_mat
ch_ip_next_hop)(structvty*vty,structroute_map_index*index,constchar*command,cons
tchar*arg,route_map_event_ttype);/*matchipnexthopprefixlist*/int(*match_ip_next_
hop_prefix_list)(structvty*vty,structroute_map_index*index,constchar*command,con
stchar*arg,route_map_event_ttype);/*nomatchipnexthopprefixlist*/int(*no_match_ip
_next_hop_prefix_list)(structvty*vty,structroute_map_index*index,constchar*comma
nd,constchar*arg,route_map_event_ttype);/*matchipv6address*/int(*match_ipv6_addr
ess)(structvty*vty,structroute_map_index*index,constchar*command,constchar*arg,r
oute_map_event_ttype);/*nomatchipv6address*/int(*no_match_ipv6_address)(structvt
y*vty,structroute_map_index*index,constchar*command,constchar*arg,route_map_even
t_ttype);/*matchipv6addressprefixlist*/int(*match_ipv6_address_prefix_list)(stru
ctvty*vty,structroute_map_index*index,constchar*command,constchar*arg,route_map_
event_ttype);/*nomatchipv6addressprefixlist*/int(*no_match_ipv6_address_prefix_l
ist)(structvty*vty,structroute_map_index*index,constchar*command,constchar*arg,r
oute_map_event_ttype);/*matchmetric*/int(*match_metric)(structvty*vty,structrout
e_map_index*index,constchar*command,constchar*arg,route_map_event_ttype);/*nomat
chmetric*/int(*no_match_metric)(structvty*vty,structroute_map_index*index,constc
har*command,constchar*arg,route_map_event_ttype);/*matchtag*/int(*match_tag)(str
uctvty*vty,structroute_map_index*index,constchar*command,constchar*arg,route_map
_event_ttype);/*nomatchtag*/int(*no_match_tag)(structvty*vty,structroute_map_ind
ex*index,constchar*command,constchar*arg,route_map_event_ttype);/*setipnexthop*/
int(*set_ip_nexthop)(structvty*vty,structroute_map_index*index,constchar*command
,constchar*arg);/*nosetipnexthop*/int(*no_set_ip_nexthop)(structvty*vty,structro
ute_map_index*index,constchar*command,constchar*arg);/*setipv6nexthoplocal*/int(
*set_ipv6_nexthop_local)(structvty*vty,structroute_map_index*index,constchar*com
mand,constchar*arg);/*nosetipv6nexthoplocal*/int(*no_set_ipv6_nexthop_local)(str
uctvty*vty,structroute_map_index*index,constchar*command,constchar*arg);/*setmet
ric*/int(*set_metric)(structvty*vty,structroute_map_index*index,constchar*comman
d,constchar*arg);/*nosetmetric*/int(*no_set_metric)(structvty*vty,structroute_ma
p_index*index,constchar*command,constchar*arg);/*settag*/int(*set_tag)(structvty
*vty,structroute_map_index*index,constchar*command,constchar*arg);/*nosettag*/in
t(*no_set_tag)(structvty*vty,structroute_map_index*index,constchar*command,const
char*arg);};structroute_map_match_set_hooksrmap_match_set_hook;/*matchinterface*
/voidroute_map_match_interface_hook(int(*func)(structvty*vty,structroute_map_ind
ex*index,constchar*command,constchar*arg,route_map_event_ttype)){rmap_match_set_
hook.match_interface=func;}/*nomatchinterface*/voidroute_map_no_match_interface_
hook(int(*func)(structvty*vty,structroute_map_index*index,constchar*command,cons
tchar*arg,route_map_event_ttype)){rmap_match_set_hook.no_match_interface=func;}/
*matchipaddress*/voidroute_map_match_ip_address_hook(int(*func)(structvty*vty,st
ructroute_map_index*index,constchar*command,constchar*arg,route_map_event_ttype)
){rmap_match_set_hook.match_ip_address=func;}/*nomatchipaddress*/voidroute_map_n
o_match_ip_address_hook(int(*func)(structvty*vty,structroute_map_index*index,con
stchar*command,constchar*arg,route_map_event_ttype)){rmap_match_set_hook.no_matc
h_ip_address=func;}/*matchipaddressprefixlist*/voidroute_map_match_ip_address_pr
efix_list_hook(int(*func)(structvty*vty,structroute_map_index*index,constchar*co
mmand,constchar*arg,route_map_event_ttype)){rmap_match_set_hook.match_ip_address
_prefix_list=func;}/*nomatchipaddressprefixlist*/voidroute_map_no_match_ip_addre
ss_prefix_list_hook(int(*func)(structvty*vty,structroute_map_index*index,constch
ar*command,constchar*arg,route_map_event_ttype)){rmap_match_set_hook.no_match_ip
_address_prefix_list=func;}/*matchipnexthop*/voidroute_map_match_ip_next_hop_hoo
k(int(*func)(structvty*vty,structroute_map_index*index,constchar*command,constch
ar*arg,route_map_event_ttype)){rmap_match_set_hook.match_ip_next_hop=func;}/*nom
atchipnexthop*/voidroute_map_no_match_ip_next_hop_hook(int(*func)(structvty*vty,
structroute_map_index*index,constchar*command,constchar*arg,route_map_event_ttyp
e)){rmap_match_set_hook.no_match_ip_next_hop=func;}/*matchipnexthopprefixlist*/v
oidroute_map_match_ip_next_hop_prefix_list_hook(int(*func)(structvty*vty,structr
oute_map_index*index,constchar*command,constchar*arg,route_map_event_ttype)){rma
p_match_set_hook.match_ip_next_hop_prefix_list=func;}/*nomatchipnexthopprefixlis
t*/voidroute_map_no_match_ip_next_hop_prefix_list_hook(int(*func)(structvty*vty,
structroute_map_index*index,constchar*command,constchar*arg,route_map_event_ttyp
e)){rmap_match_set_hook.no_match_ip_next_hop_prefix_list=func;}/*matchipv6addres
s*/voidroute_map_match_ipv6_address_hook(int(*func)(structvty*vty,structroute_ma
p_index*index,constchar*command,constchar*arg,route_map_event_ttype)){rmap_match
_set_hook.match_ipv6_address=func;}/*nomatchipv6address*/voidroute_map_no_match_
ipv6_address_hook(int(*func)(structvty*vty,structroute_map_index*index,constchar
*command,constchar*arg,route_map_event_ttype)){rmap_match_set_hook.no_match_ipv6
_address=func;}/*matchipv6addressprefixlist*/voidroute_map_match_ipv6_address_pr
efix_list_hook(int(*func)(structvty*vty,structroute_map_index*index,constchar*co
mmand,constchar*arg,route_map_event_ttype)){rmap_match_set_hook.match_ipv6_addre
ss_prefix_list=func;}/*nomatchipv6addressprefixlist*/voidroute_map_no_match_ipv6
_address_prefix_list_hook(int(*func)(structvty*vty,structroute_map_index*index,c
onstchar*command,constchar*arg,route_map_event_ttype)){rmap_match_set_hook.no_ma
tch_ipv6_address_prefix_list=func;}/*matchmetric*/voidroute_map_match_metric_hoo
k(int(*func)(structvty*vty,structroute_map_index*index,constchar*command,constch
ar*arg,route_map_event_ttype)){rmap_match_set_hook.match_metric=func;}/*nomatchm
etric*/voidroute_map_no_match_metric_hook(int(*func)(structvty*vty,structroute_m
ap_index*index,constchar*command,constchar*arg,route_map_event_ttype)){rmap_matc
h_set_hook.no_match_metric=func;}/*matchtag*/voidroute_map_match_tag_hook(int(*f
unc)(structvty*vty,structroute_map_index*index,constchar*command,constchar*arg,r
oute_map_event_ttype)){rmap_match_set_hook.match_tag=func;}/*nomatchtag*/voidrou
te_map_no_match_tag_hook(int(*func)(structvty*vty,structroute_map_index*index,co
nstchar*command,constchar*arg,route_map_event_ttype)){rmap_match_set_hook.no_mat
ch_tag=func;}/*setipnexthop*/voidroute_map_set_ip_nexthop_hook(int(*func)(struct
vty*vty,structroute_map_index*index,constchar*command,constchar*arg)){rmap_match
_set_hook.set_ip_nexthop=func;}/*nosetipnexthop*/voidroute_map_no_set_ip_nexthop
_hook(int(*func)(structvty*vty,structroute_map_index*index,constchar*command,con
stchar*arg)){rmap_match_set_hook.no_set_ip_nexthop=func;}/*setipv6nexthoplocal*/
voidroute_map_set_ipv6_nexthop_local_hook(int(*func)(structvty*vty,structroute_m
ap_index*index,constchar*command,constchar*arg)){rmap_match_set_hook.set_ipv6_ne
xthop_local=func;}/*nosetipv6nexthoplocal*/voidroute_map_no_set_ipv6_nexthop_loc
al_hook(int(*func)(structvty*vty,structroute_map_index*index,constchar*command,c
onstchar*arg)){rmap_match_set_hook.no_set_ipv6_nexthop_local=func;}/*setmetric*/
voidroute_map_set_metric_hook(int(*func)(structvty*vty,structroute_map_index*ind
ex,constchar*command,constchar*arg)){rmap_match_set_hook.set_metric=func;}/*nose
tmetric*/voidroute_map_no_set_metric_hook(int(*func)(structvty*vty,structroute_m
ap_index*index,constchar*command,constchar*arg)){rmap_match_set_hook.no_set_metr
ic=func;}/*settag*/voidroute_map_set_tag_hook(int(*func)(structvty*vty,structrou
te_map_index*index,constchar*command,constchar*arg)){rmap_match_set_hook.set_tag
=func;}/*nosettag*/voidroute_map_no_set_tag_hook(int(*func)(structvty*vty,struct
route_map_index*index,constchar*command,constchar*arg)){rmap_match_set_hook.no_s
et_tag=func;}intgeneric_match_add(structvty*vty,structroute_map_index*index,cons
tchar*command,constchar*arg,route_map_event_ttype){intret;ret=route_map_add_matc
h(index,command,arg);switch(ret){caseRMAP_COMPILE_SUCCESS:if(type!=RMAP_EVENT_MA
TCH_ADDED){route_map_upd8_dependency(type,arg,index->map->name);}break;caseRMAP_
RULE_MISSING:vty_out(vty,"%%[%s]Can'tfindrule.\n",frr_protonameinst);returnCMD_W
ARNING_CONFIG_FAILED;break;caseRMAP_COMPILE_ERROR:vty_out(vty,"%%[%s]Argumentfor
misunsupportedormalformed.\n",frr_protonameinst);returnCMD_WARNING_CONFIG_FAILED
;break;}returnCMD_SUCCESS;}intgeneric_match_delete(structvty*vty,structroute_map
_index*index,constchar*command,constchar*arg,route_map_event_ttype){intret;intre
tval=CMD_SUCCESS;char*dep_name=NULL;constchar*tmpstr;char*rmap_name=NULL;if(type
!=RMAP_EVENT_MATCH_DELETED){/*ignorethemundane,thetypeswithoutanydependency*/if(
arg==NULL){if((tmpstr=route_map_get_match_arg(index,command))!=NULL)dep_name=XST
RDUP(MTYPE_ROUTE_MAP_RULE,tmpstr);}else{dep_name=XSTRDUP(MTYPE_ROUTE_MAP_RULE,ar
g);}rmap_name=XSTRDUP(MTYPE_ROUTE_MAP_NAME,index->map->name);}ret=route_map_dele
te_match(index,command,dep_name);switch(ret){caseRMAP_RULE_MISSING:vty_out(vty,"
%%[%s]Can'tfindrule.\n",frr_protonameinst);retval=CMD_WARNING_CONFIG_FAILED;brea
k;caseRMAP_COMPILE_ERROR:vty_out(vty,"%%[%s]Argumentformisunsupportedormalformed
.\n",frr_protonameinst);retval=CMD_WARNING_CONFIG_FAILED;break;caseRMAP_COMPILE_
SUCCESS:if(type!=RMAP_EVENT_MATCH_DELETED&&dep_name)route_map_upd8_dependency(ty
pe,dep_name,rmap_name);break;}if(dep_name)XFREE(MTYPE_ROUTE_MAP_RULE,dep_name);i
f(rmap_name)XFREE(MTYPE_ROUTE_MAP_NAME,rmap_name);returnretval;}intgeneric_set_a
dd(structvty*vty,structroute_map_index*index,constchar*command,constchar*arg){in
tret;ret=route_map_add_set(index,command,arg);switch(ret){caseRMAP_RULE_MISSING:
vty_out(vty,"%%[%s]Can'tfindrule.\n",frr_protonameinst);returnCMD_WARNING_CONFIG
_FAILED;break;caseRMAP_COMPILE_ERROR:vty_out(vty,"%%[%s]Argumentformisunsupporte
dormalformed.\n",frr_protonameinst);returnCMD_WARNING_CONFIG_FAILED;break;caseRM
AP_COMPILE_SUCCESS:break;}returnCMD_SUCCESS;}intgeneric_set_delete(structvty*vty
,structroute_map_index*index,constchar*command,constchar*arg){intret;ret=route_m
ap_delete_set(index,command,arg);switch(ret){caseRMAP_RULE_MISSING:vty_out(vty,"
%%[%s]Can'tfindrule.\n",frr_protonameinst);returnCMD_WARNING_CONFIG_FAILED;break
;caseRMAP_COMPILE_ERROR:vty_out(vty,"%%[%s]Argumentformisunsupportedormalformed.
\n",frr_protonameinst);returnCMD_WARNING_CONFIG_FAILED;break;caseRMAP_COMPILE_SU
CCESS:break;}returnCMD_SUCCESS;}/*Routemaprule.Thisrulehasboth`match'ruleand`set
'rule.*/structroute_map_rule{/*Ruletype.*/structroute_map_rule_cmd*cmd;/*Forpret
typrinting.*/char*rule_str;/*Pre-compiledmatchrule.*/void*value;/*Linkedlist.*/s
tructroute_map_rule*next;structroute_map_rule*prev;};/*Makingroutemaplist.*/stru
ctroute_map_list{structroute_map*head;structroute_map*tail;void(*add_hook)(const
char*);void(*delete_hook)(constchar*);void(*event_hook)(route_map_event_t,constc
har*);};/*Masterlistofroutemap.*/staticstructroute_map_listroute_map_master={NUL
L,NULL,NULL,NULL,NULL};structhash*route_map_master_hash=NULL;staticunsignedintro
ute_map_hash_key_make(void*p){conststructroute_map*map=p;returnstring_hash_make(
map->name);}staticintroute_map_hash_cmp(constvoid*p1,constvoid*p2){conststructro
ute_map*map1=p1;conststructroute_map*map2=p2;if(map1->deleted==map2->deleted){if
(map1->name&&map2->name){if(!strcmp(map1->name,map2->name)){return1;}}elseif(!ma
p1->name&&!map2->name){return1;}}return0;}enumroute_map_upd8_type{ROUTE_MAP_ADD=
1,ROUTE_MAP_DEL,};/*allpossibleroute-mapdependencytypes*/enumroute_map_dep_type{
ROUTE_MAP_DEP_RMAP=1,ROUTE_MAP_DEP_CLIST,ROUTE_MAP_DEP_ECLIST,ROUTE_MAP_DEP_LCLI
ST,ROUTE_MAP_DEP_PLIST,ROUTE_MAP_DEP_ASPATH,ROUTE_MAP_DEP_FILTER,ROUTE_MAP_DEP_M
AX,};structroute_map_dep{char*dep_name;structhash*dep_rmap_hash;structhash*this_
hash;/*ptrtothehashstructurethisispartof*/};/*Hashesmaintainingdependencybetween
varioussublistsusedbyroutemaps*/structhash*route_map_dep_hash[ROUTE_MAP_DEP_MAX]
;staticunsignedintroute_map_dep_hash_make_key(void*p);staticintroute_map_dep_has
h_cmp(constvoid*p1,constvoid*p2);staticvoidroute_map_clear_all_references(char*r
map_name);staticvoidroute_map_rule_delete(structroute_map_rule_list*,structroute
_map_rule*);staticintrmap_debug=0;staticvoidroute_map_index_delete(structroute_m
ap_index*,int);/*Newroutemapallocation.Pleasenoteroutemap'snamemustbespecified.*
/staticstructroute_map*route_map_new(constchar*name){structroute_map*new;new=XCA
LLOC(MTYPE_ROUTE_MAP,sizeof(structroute_map));new->name=XSTRDUP(MTYPE_ROUTE_MAP_
NAME,name);QOBJ_REG(new,route_map);returnnew;}/*Addnewnametoroute_map.*/staticst
ructroute_map*route_map_add(constchar*name){structroute_map*map;structroute_map_
list*list;map=route_map_new(name);list=&route_map_master;/*Addmaptothehash*/hash
_get(route_map_master_hash,map,hash_alloc_intern);/*Addnewentrytotheheadofthelis
ttomatchhowitisaddedinthe*hashtable.Thisistoensurethatifthesameroute-maphasbeen*
createdmorethanonceandthenmarkedfordeletion(whichcanhappen*ifpriordeletionshaven
'tcompletedasBGPhasn'tyetdonethe*route-mapprocessing),theorderoftheentitiesisthe
sameinboth*thelistandthehashtable.Otherwise,sincethereisnothingto*distinguishbet
weenthetwoentries,thewrongentrycouldgetfreed.*TODO:Thisneedstobere-examinedtohan
dleitbetter-e.g.,revive*adeletedentryiftheroute-mapiscreatedagain.*/map->prev=NU
LL;map->next=list->head;if(list->head)list->head->prev=map;list->head=map;if(!li
st->tail)list->tail=map;/*Executehook.*/if(route_map_master.add_hook){(*route_ma
p_master.add_hook)(name);route_map_notify_dependencies(name,RMAP_EVENT_CALL_ADDE
D);}returnmap;}/*thisissupposedtobecalledpostprocessingby*thedeletehookfunction.
Don'tinvokedelete_hook*againinthisroutine.*/staticvoidroute_map_free_map(structr
oute_map*map){structroute_map_list*list;structroute_map_index*index;if(map==NULL
)return;while((index=map->head)!=NULL)route_map_index_delete(index,0);list=&rout
e_map_master;QOBJ_UNREG(map);if(map->next)map->next->prev=map->prev;elselist->ta
il=map->prev;if(map->prev)map->prev->next=map->next;elselist->head=map->next;has
h_release(route_map_master_hash,map);XFREE(MTYPE_ROUTE_MAP_NAME,map->name);XFREE
(MTYPE_ROUTE_MAP,map);}/*Routemapdeletefromlist.*/staticvoidroute_map_delete(str
uctroute_map*map){structroute_map_index*index;char*name;while((index=map->head)!
=NULL)route_map_index_delete(index,0);name=map->name;map->head=NULL;/*Clearallde
pendencies*/route_map_clear_all_references(name);map->deleted=1;/*Executedeletio
nhook.*/if(route_map_master.delete_hook){(*route_map_master.delete_hook)(name);r
oute_map_notify_dependencies(name,RMAP_EVENT_CALL_DELETED);}if(!map->to_be_proce
ssed){route_map_free_map(map);}}/*Lookuproutemapbyroutemapnamestring.*/structrou
te_map*route_map_lookup_by_name(constchar*name){structroute_map*map;structroute_
maptmp_map;if(!name)returnNULL;//map.deletedis0viamemsetmemset(&tmp_map,0,sizeof
(structroute_map));tmp_map.name=XSTRDUP(MTYPE_ROUTE_MAP_NAME,name);map=hash_look
up(route_map_master_hash,&tmp_map);XFREE(MTYPE_ROUTE_MAP_NAME,tmp_map.name);retu
rnmap;}introute_map_mark_updated(constchar*name,intdel_later){structroute_map*ma
p;intret=-1;structroute_maptmp_map;if(!name)return(ret);map=route_map_lookup_by_
name(name);/*Ifwedidnotfindtheroutemapwithdeleted=0tryagain*withdeleted=1*/if(!m
ap){memset(&tmp_map,0,sizeof(structroute_map));tmp_map.name=XSTRDUP(MTYPE_ROUTE_
MAP_NAME,name);tmp_map.deleted=1;map=hash_lookup(route_map_master_hash,&tmp_map)
;XFREE(MTYPE_ROUTE_MAP_NAME,tmp_map.name);}if(map){map->to_be_processed=1;ret=0;
}return(ret);}introute_map_clear_updated(structroute_map*map){intret=-1;if(map){
map->to_be_processed=0;if(map->deleted)route_map_free_map(map);}return(ret);}/*L
ookuproutemap.Ifthereisn'troutemapcreateoneandreturnit.*/staticstructroute_map*r
oute_map_get(constchar*name){structroute_map*map;map=route_map_lookup_by_name(na
me);if(map==NULL)map=route_map_add(name);returnmap;}voidroute_map_walk_update_li
st(int(*route_map_update_fn)(char*name)){structroute_map*node;structroute_map*nn
ode=NULL;for(node=route_map_master.head;node;node=nnode){if(node->to_be_processe
d){/*DD:Shouldweaddanythreadyieldcodehere*/route_map_update_fn(node->name);nnode
=node->next;route_map_clear_updated(node);}elsennode=node->next;}}/*Returnroutem
ap'stypestring.*/staticconstchar*route_map_type_str(enumroute_map_typetype){swit
ch(type){caseRMAP_PERMIT:return"permit";break;caseRMAP_DENY:return"deny";break;d
efault:return"";break;}}staticintroute_map_empty(structroute_map*map){if(map->he
ad==NULL&&map->tail==NULL)return1;elsereturn0;}/*showroute-map*/staticvoidvty_sh
ow_route_map_entry(structvty*vty,structroute_map*map){structroute_map_index*inde
x;structroute_map_rule*rule;vty_out(vty,"%s:\n",frr_protonameinst);for(index=map
->head;index;index=index->next){vty_out(vty,"route-map%s,%s,sequence%d\n",map->n
ame,route_map_type_str(index->type),index->pref);/*Description*/if(index->descri
ption)vty_out(vty,"Description:\n%s\n",index->description);/*Matchclauses*/vty_o
ut(vty,"Matchclauses:\n");for(rule=index->match_list.head;rule;rule=rule->next)v
ty_out(vty,"%s%s\n",rule->cmd->str,rule->rule_str);vty_out(vty,"Setclauses:\n");
for(rule=index->set_list.head;rule;rule=rule->next)vty_out(vty,"%s%s\n",rule->cm
d->str,rule->rule_str);/*Callclause*/vty_out(vty,"Callclause:\n");if(index->next
rm)vty_out(vty,"Call%s\n",index->nextrm);/*ExitPolicy*/vty_out(vty,"Action:\n");
if(index->exitpolicy==RMAP_GOTO)vty_out(vty,"Goto%d\n",index->nextpref);elseif(i
ndex->exitpolicy==RMAP_NEXT)vty_out(vty,"Continuetonextentry\n");elseif(index->e
xitpolicy==RMAP_EXIT)vty_out(vty,"Exitroutemap\n");}}staticintvty_show_route_map
(structvty*vty,constchar*name){structroute_map*map;if(name){map=route_map_lookup
_by_name(name);if(map){vty_show_route_map_entry(vty,map);returnCMD_SUCCESS;}else
{vty_out(vty,"%s:'route-map%s'notfound\n",frr_protonameinst,name);returnCMD_SUCC
ESS;}}else{for(map=route_map_master.head;map;map=map->next)if(!map->deleted)vty_
show_route_map_entry(vty,map);}returnCMD_SUCCESS;}/*Newroutemapallocation.Please
noteroutemap'snamemustbespecified.*/staticstructroute_map_index*route_map_index_
new(void){structroute_map_index*new;new=XCALLOC(MTYPE_ROUTE_MAP_INDEX,sizeof(str
uctroute_map_index));new->exitpolicy=RMAP_EXIT;/*DefaulttoCisco-style*/QOBJ_REG(
new,route_map_index);returnnew;}/*Freeroutemapindex.*/staticvoidroute_map_index_
delete(structroute_map_index*index,intnotify){structroute_map_rule*rule;QOBJ_UNR
EG(index);/*Freeroutematch.*/while((rule=index->match_list.head)!=NULL)route_map
_rule_delete(&index->match_list,rule);/*Freerouteset.*/while((rule=index->set_li
st.head)!=NULL)route_map_rule_delete(&index->set_list,rule);/*Removeindexfromrou
temaplist.*/if(index->next)index->next->prev=index->prev;elseindex->map->tail=in
dex->prev;if(index->prev)index->prev->next=index->next;elseindex->map->head=inde
x->next;/*Free'char*nextrm'ifnotNULL*/if(index->nextrm)XFREE(MTYPE_ROUTE_MAP_NAM
E,index->nextrm);/*Executeeventhook.*/if(route_map_master.event_hook&&notify){(*
route_map_master.event_hook)(RMAP_EVENT_INDEX_DELETED,index->map->name);route_ma
p_notify_dependencies(index->map->name,RMAP_EVENT_CALL_ADDED);}XFREE(MTYPE_ROUTE
_MAP_INDEX,index);}/*Lookupindexfromroutemap.*/staticstructroute_map_index*route
_map_index_lookup(structroute_map*map,enumroute_map_typetype,intpref){structrout
e_map_index*index;for(index=map->head;index;index=index->next)if((index->type==t
ype||type==RMAP_ANY)&&index->pref==pref)returnindex;returnNULL;}/*Addnewindextor
outemap.*/staticstructroute_map_index*route_map_index_add(structroute_map*map,en
umroute_map_typetype,intpref){structroute_map_index*index;structroute_map_index*
point;/*Allocatenewroutemapinex.*/index=route_map_index_new();index->map=map;ind
ex->type=type;index->pref=pref;/*Comparepreference.*/for(point=map->head;point;p
oint=point->next)if(point->pref>=pref)break;if(map->head==NULL){map->head=map->t
ail=index;}elseif(point==NULL){index->prev=map->tail;map->tail->next=index;map->
tail=index;}elseif(point==map->head){index->next=map->head;map->head->prev=index
;map->head=index;}else{index->next=point;index->prev=point->prev;if(point->prev)
point->prev->next=index;point->prev=index;}/*Executeeventhook.*/if(route_map_mas
ter.event_hook){(*route_map_master.event_hook)(RMAP_EVENT_INDEX_ADDED,map->name)
;route_map_notify_dependencies(map->name,RMAP_EVENT_CALL_ADDED);}returnindex;}/*
Getroutemapindex.*/staticstructroute_map_index*route_map_index_get(structroute_m
ap*map,enumroute_map_typetype,intpref){structroute_map_index*index;index=route_m
ap_index_lookup(map,RMAP_ANY,pref);if(index&&index->type!=type){/*Deleteindexfro
mroutemap.*/route_map_index_delete(index,1);index=NULL;}if(index==NULL)index=rou
te_map_index_add(map,type,pref);returnindex;}/*Newroutemaprule*/staticstructrout
e_map_rule*route_map_rule_new(void){structroute_map_rule*new;new=XCALLOC(MTYPE_R
OUTE_MAP_RULE,sizeof(structroute_map_rule));returnnew;}/*Installrulecommandtothe
matchlist.*/voidroute_map_install_match(structroute_map_rule_cmd*cmd){vector_set
(route_match_vec,cmd);}/*Installrulecommandtothesetlist.*/voidroute_map_install_
set(structroute_map_rule_cmd*cmd){vector_set(route_set_vec,cmd);}/*Lookuprulecom
mandfrommatchlist.*/staticstructroute_map_rule_cmd*route_map_lookup_match(constc
har*name){unsignedinti;structroute_map_rule_cmd*rule;for(i=0;i<vector_active(rou
te_match_vec);i++)if((rule=vector_slot(route_match_vec,i))!=NULL)if(strcmp(rule-
>str,name)==0)returnrule;returnNULL;}/*Lookuprulecommandfromsetlist.*/staticstru
ctroute_map_rule_cmd*route_map_lookup_set(constchar*name){unsignedinti;structrou
te_map_rule_cmd*rule;for(i=0;i<vector_active(route_set_vec);i++)if((rule=vector_
slot(route_set_vec,i))!=NULL)if(strcmp(rule->str,name)==0)returnrule;returnNULL;
}/*Addmatchandsetruletorulelist.*/staticvoidroute_map_rule_add(structroute_map_r
ule_list*list,structroute_map_rule*rule){rule->next=NULL;rule->prev=list->tail;i
f(list->tail)list->tail->next=rule;elselist->head=rule;list->tail=rule;}/*Delete
rulefromrulelist.*/staticvoidroute_map_rule_delete(structroute_map_rule_list*lis
t,structroute_map_rule*rule){if(rule->cmd->func_free)(*rule->cmd->func_free)(rul
e->value);if(rule->rule_str)XFREE(MTYPE_ROUTE_MAP_RULE_STR,rule->rule_str);if(ru
le->next)rule->next->prev=rule->prev;elselist->tail=rule->prev;if(rule->prev)rul
e->prev->next=rule->next;elselist->head=rule->next;XFREE(MTYPE_ROUTE_MAP_RULE,ru
le);}/*strcmpwrapperfunctionwhichdon'tcrushevenargumentisNULL.*/staticintrulecmp
(constchar*dst,constchar*src){if(dst==NULL){if(src==NULL)return0;elsereturn1;}el
se{if(src==NULL)return1;elsereturnstrcmp(dst,src);}return1;}/*Usethistoreturnthe
alreadyspecifiedargumentforthismatch.Thisis*usefultogetthespecifiedargumentwitha
routemapmatchrulewhenthe*ruleisbeingdeletedandtheargumentisnotprovided.*/constch
ar*route_map_get_match_arg(structroute_map_index*index,constchar*match_name){str
uctroute_map_rule*rule;structroute_map_rule_cmd*cmd;/*Firstlookupruleforaddmatch
statement.*/cmd=route_map_lookup_match(match_name);if(cmd==NULL)returnNULL;for(r
ule=index->match_list.head;rule;rule=rule->next)if(rule->cmd==cmd&&rule->rule_st
r!=NULL)return(rule->rule_str);return(NULL);}/*Addmatchstatementtoroutemap.*/int
route_map_add_match(structroute_map_index*index,constchar*match_name,constchar*m
atch_arg){structroute_map_rule*rule;structroute_map_rule*next;structroute_map_ru
le_cmd*cmd;void*compile;intreplaced=0;/*Firstlookupruleforaddmatchstatement.*/cm
d=route_map_lookup_match(match_name);if(cmd==NULL)returnRMAP_RULE_MISSING;/*Next
callcompilefunctionforthismatchstatement.*/if(cmd->func_compile){compile=(*cmd->
func_compile)(match_arg);if(compile==NULL)returnRMAP_COMPILE_ERROR;}elsecompile=
NULL;/*Ifargumentiscompletelysameignoreit.*/for(rule=index->match_list.head;rule
;rule=next){next=rule->next;if(rule->cmd==cmd){route_map_rule_delete(&index->mat
ch_list,rule);replaced=1;}}/*Addnewroutemapmatchrule.*/rule=route_map_rule_new()
;rule->cmd=cmd;rule->value=compile;if(match_arg)rule->rule_str=XSTRDUP(MTYPE_ROU
TE_MAP_RULE_STR,match_arg);elserule->rule_str=NULL;/*Addnewroutematchruletolinke
dlist.*/route_map_rule_add(&index->match_list,rule);/*Executeeventhook.*/if(rout
e_map_master.event_hook){(*route_map_master.event_hook)(replaced?RMAP_EVENT_MATC
H_REPLACED:RMAP_EVENT_MATCH_ADDED,index->map->name);route_map_notify_dependencie
s(index->map->name,RMAP_EVENT_CALL_ADDED);}returnRMAP_COMPILE_SUCCESS;}/*Deletes
pecifiedroutematchrule.*/introute_map_delete_match(structroute_map_index*index,c
onstchar*match_name,constchar*match_arg){structroute_map_rule*rule;structroute_m
ap_rule_cmd*cmd;cmd=route_map_lookup_match(match_name);if(cmd==NULL)return1;for(
rule=index->match_list.head;rule;rule=rule->next)if(rule->cmd==cmd&&(rulecmp(rul
e->rule_str,match_arg)==0||match_arg==NULL)){route_map_rule_delete(&index->match
_list,rule);/*Executeeventhook.*/if(route_map_master.event_hook){(*route_map_mas
ter.event_hook)(RMAP_EVENT_MATCH_DELETED,index->map->name);route_map_notify_depe
ndencies(index->map->name,RMAP_EVENT_CALL_ADDED);}return0;}/*Can'tfindmatchedrul
e.*/return1;}/*Addroute-mapsetstatementtotheroutemap.*/introute_map_add_set(stru
ctroute_map_index*index,constchar*set_name,constchar*set_arg){structroute_map_ru
le*rule;structroute_map_rule*next;structroute_map_rule_cmd*cmd;void*compile;intr
eplaced=0;cmd=route_map_lookup_set(set_name);if(cmd==NULL)returnRMAP_RULE_MISSIN
G;/*Nextcallcompilefunctionforthismatchstatement.*/if(cmd->func_compile){compile
=(*cmd->func_compile)(set_arg);if(compile==NULL)returnRMAP_COMPILE_ERROR;}elseco
mpile=NULL;/*AddbyWJL.ifoldsetcommandofsamekindexist,deleteitfirsttoensureonlyon
esetcommandofsamekindexistunderaroute_map_index.*/for(rule=index->set_list.head;
rule;rule=next){next=rule->next;if(rule->cmd==cmd){route_map_rule_delete(&index-
>set_list,rule);replaced=1;}}/*Addnewroutemapmatchrule.*/rule=route_map_rule_new
();rule->cmd=cmd;rule->value=compile;if(set_arg)rule->rule_str=XSTRDUP(MTYPE_ROU
TE_MAP_RULE_STR,set_arg);elserule->rule_str=NULL;/*Addnewroutematchruletolinkedl
ist.*/route_map_rule_add(&index->set_list,rule);/*Executeeventhook.*/if(route_ma
p_master.event_hook){(*route_map_master.event_hook)(replaced?RMAP_EVENT_SET_REPL
ACED:RMAP_EVENT_SET_ADDED,index->map->name);route_map_notify_dependencies(index-
>map->name,RMAP_EVENT_CALL_ADDED);}returnRMAP_COMPILE_SUCCESS;}/*Deleteroutemaps
etrule.*/introute_map_delete_set(structroute_map_index*index,constchar*set_name,
constchar*set_arg){structroute_map_rule*rule;structroute_map_rule_cmd*cmd;cmd=ro
ute_map_lookup_set(set_name);if(cmd==NULL)return1;for(rule=index->set_list.head;
rule;rule=rule->next)if((rule->cmd==cmd)&&(rulecmp(rule->rule_str,set_arg)==0||s
et_arg==NULL)){route_map_rule_delete(&index->set_list,rule);/*Executeeventhook.*
/if(route_map_master.event_hook){(*route_map_master.event_hook)(RMAP_EVENT_SET_D
ELETED,index->map->name);route_map_notify_dependencies(index->map->name,RMAP_EVE
NT_CALL_ADDED);}return0;}/*Can'tfindmatchedrule.*/return1;}/*Applyroutemap'seach
indextotheobject.Thematrixforaroute-maplookslikethis:(note,thisincludesthedescri
ptionforthe"NEXT"and"GOTO"frobsnowMatch|NoMatch|permitaction|cont|--------------
----+---------------|denydeny|cont|action)-ApplySetstatements,acceptroute-IfCall
statementispresentjumptothespecifiedroute-map,ifitdeniestheroutewefinish.-IfNEXT
isspecified,gotoNEXTstatement-IfGOTOisspecified,gotothefirstclausewherepref>next
pref-Ifnothingisspecified,doasCiscoandfinishdeny)-Routeisdeniedbyroute-map.cont)
-GotoNextindexIfwegetnomatchesafterwe'veprocessedallupdates,thentherouteisdroppe
dtoo.Somenotesonthenew"CALL","NEXT"and"GOTO"callWORD-Ifthisclauseismatched,thent
hesetstatementsareexecutedandthenwejumptoroute-map'WORD'.Ifthisroute-mapdeniesth
eroute,wefinish,inothercasewedowhatevertheexitpolicy(EXIT,NEXTorGOTO)tells.on-ma
tchnext-Ifthisclauseismatched,thenthesetstatementsareexecutedandthenwedropthroug
htothenextclauseon-matchgoton-Ifthisclauseismatched,thenthesetstatmentsareexecut
edandthenwegotothenthclause,orthefirstclausegreaterthanthis.Inordertoensureroute
-maps*always*exit,youcannotjumpbackwards.Sorry;)Weneedtomakesureourroute-mapproc
essingmatchestheabove*/staticroute_map_result_troute_map_apply_match(structroute
_map_rule_list*match_list,structprefix*prefix,route_map_object_ttype,void*object
){route_map_result_tret=RMAP_NOMATCH;structroute_map_rule*match;/*Checkallmatchr
uleandifthereisnomatchrule,gotothesetstatement.*/if(!match_list->head)ret=RMAP_M
ATCH;else{for(match=match_list->head;match;match=match->next){/*Tryeachmatchstat
ementinturn,IfanydonotreturnRMAP_MATCH,return,otherwisecontinueontonextmatchstat
ement.Allmatchstatementsmustmatchforend-resulttobeamatch.*/ret=(*match->cmd->fun
c_apply)(match->value,prefix,type,object);if(ret!=RMAP_MATCH)returnret;}}returnr
et;}/*Applyroutemaptotheobject.*/route_map_result_troute_map_apply(structroute_m
ap*map,structprefix*prefix,route_map_object_ttype,void*object){staticintrecursio
n=0;intret=0;structroute_map_index*index;structroute_map_rule*set;if(recursion>R
MAP_RECURSION_LIMIT){zlog_warn("route-maprecursionlimit(%d)reached,discardingrou
te",RMAP_RECURSION_LIMIT);recursion=0;returnRMAP_DENYMATCH;}if(map==NULL)returnR
MAP_DENYMATCH;for(index=map->head;index;index=index->next){/*Applythisindex.*/re
t=route_map_apply_match(&index->match_list,prefix,type,object);/*Nowweapplythema
trixfromabove*/if(ret==RMAP_NOMATCH)/*'cont'frommatrix-continuetonextroute-map*s
equence*/continue;elseif(ret==RMAP_MATCH){if(index->type==RMAP_PERMIT)/*'action'
*/{/*permit+matchmustexecutesets*/for(set=index->set_list.head;set;set=set->next
)ret=(*set->cmd->func_apply)(set->value,prefix,type,object);/*Callanotherroute-m
apifavailable*/if(index->nextrm){structroute_map*nextrm=route_map_lookup_by_name
(index->nextrm);if(nextrm)/*Targetroute-mapfound,jumptoit*/{recursion++;ret=rout
e_map_apply(nextrm,prefix,type,object);recursion--;}/*Ifnextrmreturned'deny',fin
ish.*/if(ret==RMAP_DENYMATCH)returnret;}switch(index->exitpolicy){caseRMAP_EXIT:
returnret;caseRMAP_NEXT:continue;caseRMAP_GOTO:{/*Findthenextclausetojumpto*/str
uctroute_map_index*next=index->next;intnextpref=index->nextpref;while(next&&next
->pref<nextpref){index=next;next=next->next;}if(next==NULL){/*Noclausesmatch!*/r
eturnret;}}}}elseif(index->type==RMAP_DENY)/*'deny'*/{returnRMAP_DENYMATCH;}}}/*
Finallyroute-mapdoesnotmatchatall.*/returnRMAP_DENYMATCH;}voidroute_map_add_hook
(void(*func)(constchar*)){route_map_master.add_hook=func;}voidroute_map_delete_h
ook(void(*func)(constchar*)){route_map_master.delete_hook=func;}voidroute_map_ev
ent_hook(void(*func)(route_map_event_t,constchar*)){route_map_master.event_hook=
func;}/*Routinesforroutemapdependencylistsanddependencyprocessing*/staticintrout
e_map_rmap_hash_cmp(constvoid*p1,constvoid*p2){return(strcmp((constchar*)p1,(con
stchar*)p2)==0);}staticintroute_map_dep_hash_cmp(constvoid*p1,constvoid*p2){retu
rn(strcmp(((conststructroute_map_dep*)p1)->dep_name,(constchar*)p2)==0);}staticv
oidroute_map_clear_reference(structhash_backet*backet,void*arg){structroute_map_
dep*dep=(structroute_map_dep*)backet->data;char*rmap_name;if(dep&&arg){rmap_name
=(char*)hash_release(dep->dep_rmap_hash,(void*)arg);if(rmap_name){XFREE(MTYPE_RO
UTE_MAP_NAME,rmap_name);}if(!dep->dep_rmap_hash->count){dep=hash_release(dep->th
is_hash,(void*)dep->dep_name);hash_free(dep->dep_rmap_hash);XFREE(MTYPE_ROUTE_MA
P_NAME,dep->dep_name);XFREE(MTYPE_ROUTE_MAP_DEP,dep);}}}staticvoidroute_map_clea
r_all_references(char*rmap_name){inti;for(i=1;i<ROUTE_MAP_DEP_MAX;i++){hash_iter
ate(route_map_dep_hash[i],route_map_clear_reference,(void*)rmap_name);}}staticvo
id*route_map_dep_hash_alloc(void*p){char*dep_name=(char*)p;structroute_map_dep*d
ep_entry;dep_entry=XCALLOC(MTYPE_ROUTE_MAP_DEP,sizeof(structroute_map_dep));dep_
entry->dep_name=XSTRDUP(MTYPE_ROUTE_MAP_NAME,dep_name);dep_entry->dep_rmap_hash=
hash_create_size(8,route_map_dep_hash_make_key,route_map_rmap_hash_cmp,"RouteMap
DepHash");dep_entry->this_hash=NULL;return((void*)dep_entry);}staticvoid*route_m
ap_name_hash_alloc(void*p){return((void*)XSTRDUP(MTYPE_ROUTE_MAP_NAME,(constchar
*)p));}staticunsignedintroute_map_dep_hash_make_key(void*p){return(string_hash_m
ake((char*)p));}staticvoidroute_map_print_dependency(structhash_backet*backet,vo
id*data){char*rmap_name=(char*)backet->data;char*dep_name=(char*)data;if(rmap_na
me)zlog_debug("%s:Dependencyfor%s:%s",__FUNCTION__,dep_name,rmap_name);}staticin
troute_map_dep_update(structhash*dephash,constchar*dep_name,constchar*rmap_name,
route_map_event_ttype){structroute_map_dep*dep=NULL;char*ret_map_name;char*dname
,*rname;intret=0;dname=XSTRDUP(MTYPE_ROUTE_MAP_NAME,dep_name);rname=XSTRDUP(MTYP
E_ROUTE_MAP_NAME,rmap_name);switch(type){caseRMAP_EVENT_PLIST_ADDED:caseRMAP_EVE
NT_CLIST_ADDED:caseRMAP_EVENT_ECLIST_ADDED:caseRMAP_EVENT_ASLIST_ADDED:caseRMAP_
EVENT_LLIST_ADDED:caseRMAP_EVENT_CALL_ADDED:caseRMAP_EVENT_FILTER_ADDED:if(rmap_
debug)zlog_debug("%s:Addingdependencyfor%sin%s",__FUNCTION__,dep_name,rmap_name)
;dep=(structroute_map_dep*)hash_get(dephash,dname,route_map_dep_hash_alloc);if(!
dep){ret=-1;gotoout;}if(!dep->this_hash)dep->this_hash=dephash;hash_get(dep->dep
_rmap_hash,rname,route_map_name_hash_alloc);break;caseRMAP_EVENT_PLIST_DELETED:c
aseRMAP_EVENT_CLIST_DELETED:caseRMAP_EVENT_ECLIST_DELETED:caseRMAP_EVENT_ASLIST_
DELETED:caseRMAP_EVENT_LLIST_DELETED:caseRMAP_EVENT_CALL_DELETED:caseRMAP_EVENT_
FILTER_DELETED:if(rmap_debug)zlog_debug("%s:Deletingdependencyfor%sin%s",__FUNCT
ION__,dep_name,rmap_name);dep=(structroute_map_dep*)hash_get(dephash,dname,NULL)
;if(!dep){gotoout;}ret_map_name=(char*)hash_release(dep->dep_rmap_hash,rname);if
(ret_map_name)XFREE(MTYPE_ROUTE_MAP_NAME,ret_map_name);if(!dep->dep_rmap_hash->c
ount){dep=hash_release(dephash,dname);hash_free(dep->dep_rmap_hash);XFREE(MTYPE_
ROUTE_MAP_NAME,dep->dep_name);XFREE(MTYPE_ROUTE_MAP_DEP,dep);dep=NULL;}break;def
ault:break;}if(dep){if(rmap_debug)hash_iterate(dep->dep_rmap_hash,route_map_prin
t_dependency,dname);}out:XFREE(MTYPE_ROUTE_MAP_NAME,rname);XFREE(MTYPE_ROUTE_MAP
_NAME,dname);returnret;}staticstructhash*route_map_get_dep_hash(route_map_event_
tevent){structhash*upd8_hash=NULL;switch(event){caseRMAP_EVENT_PLIST_ADDED:caseR
MAP_EVENT_PLIST_DELETED:upd8_hash=route_map_dep_hash[ROUTE_MAP_DEP_PLIST];break;
caseRMAP_EVENT_CLIST_ADDED:caseRMAP_EVENT_CLIST_DELETED:upd8_hash=route_map_dep_
hash[ROUTE_MAP_DEP_CLIST];break;caseRMAP_EVENT_ECLIST_ADDED:caseRMAP_EVENT_ECLIS
T_DELETED:upd8_hash=route_map_dep_hash[ROUTE_MAP_DEP_ECLIST];break;caseRMAP_EVEN
T_ASLIST_ADDED:caseRMAP_EVENT_ASLIST_DELETED:upd8_hash=route_map_dep_hash[ROUTE_
MAP_DEP_ASPATH];break;caseRMAP_EVENT_LLIST_ADDED:caseRMAP_EVENT_LLIST_DELETED:up
d8_hash=route_map_dep_hash[ROUTE_MAP_DEP_LCLIST];break;caseRMAP_EVENT_CALL_ADDED
:caseRMAP_EVENT_CALL_DELETED:upd8_hash=route_map_dep_hash[ROUTE_MAP_DEP_RMAP];br
eak;caseRMAP_EVENT_FILTER_ADDED:caseRMAP_EVENT_FILTER_DELETED:upd8_hash=route_ma
p_dep_hash[ROUTE_MAP_DEP_FILTER];break;default:upd8_hash=NULL;break;}return(upd8
_hash);}staticvoidroute_map_process_dependency(structhash_backet*backet,void*dat
a){char*rmap_name;route_map_event_ttype=(route_map_event_t)(ptrdiff_t)data;rmap_
name=(char*)backet->data;if(rmap_name){if(rmap_debug)zlog_debug("%s:Notifying%so
fdependency",__FUNCTION__,rmap_name);if(route_map_master.event_hook)(*route_map_
master.event_hook)(type,rmap_name);}}voidroute_map_upd8_dependency(route_map_eve
nt_ttype,constchar*arg,constchar*rmap_name){structhash*upd8_hash=NULL;if((upd8_h
ash=route_map_get_dep_hash(type)))route_map_dep_update(upd8_hash,arg,rmap_name,t
ype);}voidroute_map_notify_dependencies(constchar*affected_name,route_map_event_
tevent){structroute_map_dep*dep;structhash*upd8_hash;char*name;if(!affected_name
)return;name=XSTRDUP(MTYPE_ROUTE_MAP_NAME,affected_name);if((upd8_hash=route_map
_get_dep_hash(event))==NULL){XFREE(MTYPE_ROUTE_MAP_NAME,name);return;}dep=(struc
troute_map_dep*)hash_get(upd8_hash,name,NULL);if(dep){if(!dep->this_hash)dep->th
is_hash=upd8_hash;hash_iterate(dep->dep_rmap_hash,route_map_process_dependency,(
void*)event);}XFREE(MTYPE_ROUTE_MAP_NAME,name);}/*VTYrelatedfunctions.*/DEFUN(ma
tch_interface,match_interface_cmd,"matchinterfaceWORD",MATCH_STR"matchfirsthopin
terfaceofroute\n""Interfacename\n"){intidx_word=2;VTY_DECLVAR_CONTEXT(route_map_
index,index);if(rmap_match_set_hook.match_interface)returnrmap_match_set_hook.ma
tch_interface(vty,index,"interface",argv[idx_word]->arg,RMAP_EVENT_MATCH_ADDED);
returnCMD_SUCCESS;}DEFUN(no_match_interface,no_match_interface_cmd,"nomatchinter
face[WORD]",NO_STRMATCH_STR"Matchfirsthopinterfaceofroute\n""Interfacename\n"){c
har*iface=(argc==4)?argv[3]->arg:NULL;VTY_DECLVAR_CONTEXT(route_map_index,index)
;if(rmap_match_set_hook.no_match_interface)returnrmap_match_set_hook.no_match_in
terface(vty,index,"interface",iface,RMAP_EVENT_MATCH_DELETED);returnCMD_SUCCESS;
}DEFUN(match_ip_address,match_ip_address_cmd,"matchipaddress<(1-199)|(1300-2699)
|WORD>",MATCH_STRIP_STR"Matchaddressofroute\n""IPaccess-listnumber\n""IPaccess-l
istnumber(expandedrange)\n""IPAccess-listname\n"){intidx_acl=3;VTY_DECLVAR_CONTE
XT(route_map_index,index);if(rmap_match_set_hook.match_ip_address)returnrmap_mat
ch_set_hook.match_ip_address(vty,index,"ipaddress",argv[idx_acl]->arg,RMAP_EVENT
_FILTER_ADDED);returnCMD_SUCCESS;}DEFUN(no_match_ip_address,no_match_ip_address_
cmd,"nomatchipaddress[<(1-199)|(1300-2699)|WORD>]",NO_STRMATCH_STRIP_STR"Matchad
dressofroute\n""IPaccess-listnumber\n""IPaccess-listnumber(expandedrange)\n""IPA
ccess-listname\n"){intidx_word=4;VTY_DECLVAR_CONTEXT(route_map_index,index);if(r
map_match_set_hook.no_match_ip_address){if(argc<=idx_word)returnrmap_match_set_h
ook.no_match_ip_address(vty,index,"ipaddress",NULL,RMAP_EVENT_FILTER_DELETED);re
turnrmap_match_set_hook.no_match_ip_address(vty,index,"ipaddress",argv[idx_word]
->arg,RMAP_EVENT_FILTER_DELETED);}returnCMD_SUCCESS;}DEFUN(match_ip_address_pref
ix_list,match_ip_address_prefix_list_cmd,"matchipaddressprefix-listWORD",MATCH_S
TRIP_STR"Matchaddressofroute\n""Matchentriesofprefix-lists\n""IPprefix-listname\
n"){intidx_word=4;VTY_DECLVAR_CONTEXT(route_map_index,index);if(rmap_match_set_h
ook.match_ip_address_prefix_list)returnrmap_match_set_hook.match_ip_address_pref
ix_list(vty,index,"ipaddressprefix-list",argv[idx_word]->arg,RMAP_EVENT_PLIST_AD
DED);returnCMD_SUCCESS;}DEFUN(no_match_ip_address_prefix_list,no_match_ip_addres
s_prefix_list_cmd,"nomatchipaddressprefix-list[WORD]",NO_STRMATCH_STRIP_STR"Matc
haddressofroute\n""Matchentriesofprefix-lists\n""IPprefix-listname\n"){intidx_wo
rd=5;VTY_DECLVAR_CONTEXT(route_map_index,index);if(rmap_match_set_hook.no_match_
ip_address_prefix_list){if(argc<=idx_word)returnrmap_match_set_hook.no_match_ip_
address_prefix_list(vty,index,"ipaddressprefix-list",NULL,RMAP_EVENT_PLIST_DELET
ED);returnrmap_match_set_hook.no_match_ip_address_prefix_list(vty,index,"ipaddre
ssprefix-list",argv[idx_word]->arg,RMAP_EVENT_PLIST_DELETED);}returnCMD_SUCCESS;
}DEFUN(match_ip_next_hop,match_ip_next_hop_cmd,"matchipnext-hop<(1-199)|(1300-26
99)|WORD>",MATCH_STRIP_STR"Matchnext-hopaddressofroute\n""IPaccess-listnumber\n"
"IPaccess-listnumber(expandedrange)\n""IPAccess-listname\n"){intidx_acl=3;VTY_DE
CLVAR_CONTEXT(route_map_index,index);if(rmap_match_set_hook.match_ip_next_hop)re
turnrmap_match_set_hook.match_ip_next_hop(vty,index,"ipnext-hop",argv[idx_acl]->
arg,RMAP_EVENT_FILTER_ADDED);returnCMD_SUCCESS;}DEFUN(no_match_ip_next_hop,no_ma
tch_ip_next_hop_cmd,"nomatchipnext-hop[<(1-199)|(1300-2699)|WORD>]",NO_STRMATCH_
STRIP_STR"Matchnext-hopaddressofroute\n""IPaccess-listnumber\n""IPaccess-listnum
ber(expandedrange)\n""IPAccess-listname\n"){intidx_word=4;VTY_DECLVAR_CONTEXT(ro
ute_map_index,index);if(rmap_match_set_hook.no_match_ip_next_hop){if(argc<=idx_w
ord)returnrmap_match_set_hook.no_match_ip_next_hop(vty,index,"ipnext-hop",NULL,R
MAP_EVENT_FILTER_DELETED);returnrmap_match_set_hook.no_match_ip_next_hop(vty,ind
ex,"ipnext-hop",argv[idx_word]->arg,RMAP_EVENT_FILTER_DELETED);}returnCMD_SUCCES
S;}DEFUN(match_ip_next_hop_prefix_list,match_ip_next_hop_prefix_list_cmd,"matchi
pnext-hopprefix-listWORD",MATCH_STRIP_STR"Matchnext-hopaddressofroute\n""Matchen
triesofprefix-lists\n""IPprefix-listname\n"){intidx_word=4;VTY_DECLVAR_CONTEXT(r
oute_map_index,index);if(rmap_match_set_hook.match_ip_next_hop_prefix_list)retur
nrmap_match_set_hook.match_ip_next_hop_prefix_list(vty,index,"ipnext-hopprefix-l
ist",argv[idx_word]->arg,RMAP_EVENT_PLIST_ADDED);returnCMD_SUCCESS;}DEFUN(no_mat
ch_ip_next_hop_prefix_list,no_match_ip_next_hop_prefix_list_cmd,"nomatchipnext-h
opprefix-list[WORD]",NO_STRMATCH_STRIP_STR"Matchnext-hopaddressofroute\n""Matche
ntriesofprefix-lists\n""IPprefix-listname\n"){intidx_word=5;VTY_DECLVAR_CONTEXT(
route_map_index,index);if(rmap_match_set_hook.no_match_ip_next_hop){if(argc<=idx
_word)returnrmap_match_set_hook.no_match_ip_next_hop(vty,index,"ipnext-hopprefix
-list",NULL,RMAP_EVENT_PLIST_DELETED);returnrmap_match_set_hook.no_match_ip_next
_hop(vty,index,"ipnext-hopprefix-list",argv[idx_word]->arg,RMAP_EVENT_PLIST_DELE
TED);}returnCMD_SUCCESS;}DEFUN(match_ipv6_address,match_ipv6_address_cmd,"matchi
pv6addressWORD",MATCH_STRIPV6_STR"MatchIPv6addressofroute\n""IPv6access-listname
\n"){intidx_word=3;VTY_DECLVAR_CONTEXT(route_map_index,index);if(rmap_match_set_
hook.match_ipv6_address)returnrmap_match_set_hook.match_ipv6_address(vty,index,"
ipv6address",argv[idx_word]->arg,RMAP_EVENT_FILTER_ADDED);returnCMD_SUCCESS;}DEF
UN(no_match_ipv6_address,no_match_ipv6_address_cmd,"nomatchipv6addressWORD",NO_S
TRMATCH_STRIPV6_STR"MatchIPv6addressofroute\n""IPv6access-listname\n"){intidx_wo
rd=4;VTY_DECLVAR_CONTEXT(route_map_index,index);if(rmap_match_set_hook.no_match_
ipv6_address)returnrmap_match_set_hook.no_match_ipv6_address(vty,index,"ipv6addr
ess",argv[idx_word]->arg,RMAP_EVENT_FILTER_DELETED);returnCMD_SUCCESS;}DEFUN(mat
ch_ipv6_address_prefix_list,match_ipv6_address_prefix_list_cmd,"matchipv6address
prefix-listWORD",MATCH_STRIPV6_STR"Matchaddressofroute\n""Matchentriesofprefix-l
ists\n""IPprefix-listname\n"){intidx_word=4;VTY_DECLVAR_CONTEXT(route_map_index,
index);if(rmap_match_set_hook.match_ipv6_address_prefix_list)returnrmap_match_se
t_hook.match_ipv6_address_prefix_list(vty,index,"ipv6addressprefix-list",argv[id
x_word]->arg,RMAP_EVENT_PLIST_ADDED);returnCMD_SUCCESS;}DEFUN(no_match_ipv6_addr
ess_prefix_list,no_match_ipv6_address_prefix_list_cmd,"nomatchipv6addressprefix-
listWORD",NO_STRMATCH_STRIPV6_STR"Matchaddressofroute\n""Matchentriesofprefix-li
sts\n""IPprefix-listname\n"){intidx_word=5;VTY_DECLVAR_CONTEXT(route_map_index,i
ndex);if(rmap_match_set_hook.no_match_ipv6_address_prefix_list)returnrmap_match_
set_hook.no_match_ipv6_address_prefix_list(vty,index,"ipv6addressprefix-list",ar
gv[idx_word]->arg,RMAP_EVENT_PLIST_DELETED);returnCMD_SUCCESS;}DEFUN(match_metri
c,match_metric_cmd,"matchmetric(0-4294967295)",MATCH_STR"Matchmetricofroute\n""M
etricvalue\n"){intidx_number=2;VTY_DECLVAR_CONTEXT(route_map_index,index);if(rma
p_match_set_hook.match_metric)returnrmap_match_set_hook.match_metric(vty,index,"
metric",argv[idx_number]->arg,RMAP_EVENT_MATCH_ADDED);returnCMD_SUCCESS;}DEFUN(n
o_match_metric,no_match_metric_cmd,"nomatchmetric[(0-4294967295)]",NO_STRMATCH_S
TR"Matchmetricofroute\n""Metricvalue\n"){intidx_number=3;VTY_DECLVAR_CONTEXT(rou
te_map_index,index);if(rmap_match_set_hook.no_match_metric){if(argc<=idx_number)
returnrmap_match_set_hook.no_match_metric(vty,index,"metric",NULL,RMAP_EVENT_MAT
CH_DELETED);returnrmap_match_set_hook.no_match_metric(vty,index,"metric",argv[id
x_number]->arg,RMAP_EVENT_MATCH_DELETED);}returnCMD_SUCCESS;}DEFUN(match_tag,mat
ch_tag_cmd,"matchtag(1-4294967295)",MATCH_STR"Matchtagofroute\n""Tagvalue\n"){in
tidx_number=2;VTY_DECLVAR_CONTEXT(route_map_index,index);if(rmap_match_set_hook.
match_tag)returnrmap_match_set_hook.match_tag(vty,index,"tag",argv[idx_number]->
arg,RMAP_EVENT_MATCH_ADDED);returnCMD_SUCCESS;}DEFUN(no_match_tag,no_match_tag_c
md,"nomatchtag[(1-4294967295)]",NO_STRMATCH_STR"Matchtagofroute\n""Tagvalue\n"){
VTY_DECLVAR_CONTEXT(route_map_index,index);intidx=0;char*arg=argv_find(argv,argc
,"(1-4294967295)",&idx)?argv[idx]->arg:NULL;if(rmap_match_set_hook.no_match_tag)
returnrmap_match_set_hook.no_match_tag(vty,index,"tag",arg,RMAP_EVENT_MATCH_DELE
TED);returnCMD_SUCCESS;}DEFUN(set_ip_nexthop,set_ip_nexthop_cmd,"setipnext-hopA.
B.C.D",SET_STRIP_STR"Nexthopaddress\n""IPaddressofnexthop\n"){intidx_ipv4=3;unio
nsockunionsu;intret;VTY_DECLVAR_CONTEXT(route_map_index,index);ret=str2sockunion
(argv[idx_ipv4]->arg,&su);if(ret<0){vty_out(vty,"%%Malformednexthopaddress\n");r
eturnCMD_WARNING_CONFIG_FAILED;}if(su.sin.sin_addr.s_addr==0||IPV4_CLASS_DE(ntoh
l(su.sin.sin_addr.s_addr))){vty_out(vty,"%%nexthopaddresscannotbe0.0.0.0,multica
storreserved\n");returnCMD_WARNING_CONFIG_FAILED;}if(rmap_match_set_hook.set_ip_
nexthop)returnrmap_match_set_hook.set_ip_nexthop(vty,index,"ipnext-hop",argv[idx
_ipv4]->arg);returnCMD_SUCCESS;}DEFUN(no_set_ip_nexthop,no_set_ip_nexthop_cmd,"n
osetipnext-hop[A.B.C.D]",NO_STRSET_STRIP_STR"Nexthopaddress\n""IPaddressofnextho
p\n"){intidx=0;VTY_DECLVAR_CONTEXT(route_map_index,index);constchar*arg=NULL;if(
argv_find(argv,argc,"A.B.C.D",&idx))arg=argv[idx]->arg;if(rmap_match_set_hook.no
_set_ip_nexthop)returnrmap_match_set_hook.no_set_ip_nexthop(vty,index,"ipnext-ho
p",arg);returnCMD_SUCCESS;}DEFUN(set_ipv6_nexthop_local,set_ipv6_nexthop_local_c
md,"setipv6next-hoplocalX:X::X:X",SET_STRIPV6_STR"IPv6next-hopaddress\n""IPv6loc
aladdress\n""IPv6addressofnexthop\n"){intidx_ipv6=4;structin6_addraddr;intret;VT
Y_DECLVAR_CONTEXT(route_map_index,index);ret=inet_pton(AF_INET6,argv[idx_ipv6]->
arg,&addr);if(!ret){vty_out(vty,"%%Malformednexthopaddress\n");returnCMD_WARNING
_CONFIG_FAILED;}if(!IN6_IS_ADDR_LINKLOCAL(&addr)){vty_out(vty,"%%Invalidlink-loc
alnexthopaddress\n");returnCMD_WARNING_CONFIG_FAILED;}if(rmap_match_set_hook.set
_ipv6_nexthop_local)returnrmap_match_set_hook.set_ipv6_nexthop_local(vty,index,"
ipv6next-hoplocal",argv[idx_ipv6]->arg);returnCMD_SUCCESS;}DEFUN(no_set_ipv6_nex
thop_local,no_set_ipv6_nexthop_local_cmd,"nosetipv6next-hoplocal[X:X::X:X]",NO_S
TRSET_STRIPV6_STR"IPv6next-hopaddress\n""IPv6localaddress\n""IPv6addressofnextho
p\n"){intidx_ipv6=5;VTY_DECLVAR_CONTEXT(route_map_index,index);if(rmap_match_set
_hook.no_set_ipv6_nexthop_local){if(argc<=idx_ipv6)returnrmap_match_set_hook.no_
set_ipv6_nexthop_local(vty,index,"ipv6next-hoplocal",NULL);returnrmap_match_set_
hook.no_set_ipv6_nexthop_local(vty,index,"ipv6next-hoplocal",argv[5]->arg);}retu
rnCMD_SUCCESS;}DEFUN(set_metric,set_metric_cmd,"setmetric<(0-4294967295)|rtt|+rt
t|-rtt|+metric|-metric>",SET_STR"Metricvaluefordestinationroutingprotocol\n""Met
ricvalue\n""Assignroundtriptime\n""Addroundtriptime\n""Subtractroundtriptime\n""
Addmetric\n""Subtractmetric\n"){intidx_number=2;VTY_DECLVAR_CONTEXT(route_map_in
dex,index);constchar*pass=(argv[idx_number]->type==RANGE_TKN)?argv[idx_number]->
arg:argv[idx_number]->text;if(rmap_match_set_hook.set_metric)returnrmap_match_se
t_hook.set_metric(vty,index,"metric",pass);returnCMD_SUCCESS;}DEFUN(no_set_metri
c,no_set_metric_cmd,"nosetmetric[(0-4294967295)]",NO_STRSET_STR"Metricvalueforde
stinationroutingprotocol\n""Metricvalue\n"){intidx_number=3;VTY_DECLVAR_CONTEXT(
route_map_index,index);if(rmap_match_set_hook.no_set_metric){if(argc<=idx_number
)returnrmap_match_set_hook.no_set_metric(vty,index,"metric",NULL);returnrmap_mat
ch_set_hook.no_set_metric(vty,index,"metric",argv[idx_number]->arg);}returnCMD_S
UCCESS;}DEFUN(set_tag,set_tag_cmd,"settag(1-4294967295)",SET_STR"Tagvalueforrout
ingprotocol\n""Tagvalue\n"){VTY_DECLVAR_CONTEXT(route_map_index,index);intidx_nu
mber=2;if(rmap_match_set_hook.set_tag)returnrmap_match_set_hook.set_tag(vty,inde
x,"tag",argv[idx_number]->arg);returnCMD_SUCCESS;}DEFUN(no_set_tag,no_set_tag_cm
d,"nosettag[(1-4294967295)]",NO_STRSET_STR"Tagvalueforroutingprotocol\n""Tagvalu
e\n"){VTY_DECLVAR_CONTEXT(route_map_index,index);intidx_number=3;if(rmap_match_s
et_hook.no_set_tag){if(argc<=idx_number)returnrmap_match_set_hook.no_set_tag(vty
,index,"tag",NULL);returnrmap_match_set_hook.no_set_tag(vty,index,"tag",argv[idx
_number]->arg);}returnCMD_SUCCESS;}DEFUN_NOSH(route_map,route_map_cmd,"route-map
WORD<deny|permit>(1-65535)","Createroute-maporenterroute-mapcommandmode\n""Route
maptag\n""Routemapdeniessetoperations\n""Routemappermitssetoperations\n""Sequenc
etoinsertto/deletefromexistingroute-mapentry\n"){intidx_word=1;intidx_permit_den
y=2;intidx_number=3;structroute_map*map;structroute_map_index*index;char*endptr=
NULL;intpermit=argv[idx_permit_deny]->arg[0]=='p'?RMAP_PERMIT:RMAP_DENY;unsigned
longpref=strtoul(argv[idx_number]->arg,&endptr,10);constchar*mapname=argv[idx_wo
rd]->arg;/*Getroutemap.*/map=route_map_get(mapname);index=route_map_index_get(ma
p,permit,pref);VTY_PUSH_CONTEXT(RMAP_NODE,index);returnCMD_SUCCESS;}DEFUN(no_rou
te_map_all,no_route_map_all_cmd,"noroute-mapWORD",NO_STR"Createroute-maporenterr
oute-mapcommandmode\n""Routemaptag\n"){intidx_word=2;constchar*mapname=argv[idx_
word]->arg;structroute_map*map;map=route_map_lookup_by_name(mapname);if(map==NUL
L){vty_out(vty,"%%Couldnotfindroute-map%s\n",mapname);returnCMD_WARNING_CONFIG_F
AILED;}route_map_delete(map);returnCMD_SUCCESS;}DEFUN(no_route_map,no_route_map_
cmd,"noroute-mapWORD<deny|permit>(1-65535)",NO_STR"Createroute-maporenterroute-m
apcommandmode\n""Routemaptag\n""Routemapdeniessetoperations\n""Routemappermitsse
toperations\n""Sequencetoinsertto/deletefromexistingroute-mapentry\n"){intidx_wo
rd=2;intidx_permit_deny=3;intidx_number=4;structroute_map*map;structroute_map_in
dex*index;char*endptr=NULL;intpermit=strmatch(argv[idx_permit_deny]->text,"permi
t")?RMAP_PERMIT:RMAP_DENY;constchar*prefstr=argv[idx_number]->arg;constchar*mapn
ame=argv[idx_word]->arg;unsignedlongpref=strtoul(prefstr,&endptr,10);/*Existence
check.*/map=route_map_lookup_by_name(mapname);if(map==NULL){vty_out(vty,"%%Could
notfindroute-map%s\n",mapname);returnCMD_WARNING_CONFIG_FAILED;}/*Lookuproutemap
index.*/index=route_map_index_lookup(map,permit,pref);if(index==NULL){vty_out(vt
y,"%%Couldnotfindroute-mapentry%s%s\n",mapname,prefstr);returnCMD_WARNING_CONFIG
_FAILED;}/*Deleteindexfromroutemap.*/route_map_index_delete(index,1);/*Ifthisrou
teruleisthelastone,deleteroutemapitself.*/if(route_map_empty(map))route_map_dele
te(map);returnCMD_SUCCESS;}DEFUN(rmap_onmatch_next,rmap_onmatch_next_cmd,"on-mat
chnext","Exitpolicyonmatches\n""Nextclause\n"){structroute_map_index*index=VTY_G
ET_CONTEXT(route_map_index);if(index){if(index->type==RMAP_DENY){/*Underadenycla
use,matchmeansit'sfinished.No*needtosetnext*/vty_out(vty,"on-matchnextnotsupport
edunderroute-mapdeny\n");returnCMD_WARNING_CONFIG_FAILED;}index->exitpolicy=RMAP
_NEXT;}returnCMD_SUCCESS;}DEFUN(no_rmap_onmatch_next,no_rmap_onmatch_next_cmd,"n
oon-matchnext",NO_STR"Exitpolicyonmatches\n""Nextclause\n"){structroute_map_inde
x*index=VTY_GET_CONTEXT(route_map_index);if(index)index->exitpolicy=RMAP_EXIT;re
turnCMD_SUCCESS;}DEFUN(rmap_onmatch_goto,rmap_onmatch_goto_cmd,"on-matchgoto(1-6
5535)","Exitpolicyonmatches\n""GotoClausenumber\n""Number\n"){intidx=0;char*num=
argv_find(argv,argc,"(1-65535)",&idx)?argv[idx]->arg:NULL;structroute_map_index*
index=VTY_GET_CONTEXT(route_map_index);intd=0;if(index){if(index->type==RMAP_DEN
Y){/*Underadenyclause,matchmeansit'sfinished.No*needtogoanywhere*/vty_out(vty,"o
n-matchgotonotsupportedunderroute-mapdeny\n");returnCMD_WARNING_CONFIG_FAILED;}i
f(num)d=strtoul(num,NULL,10);elsed=index->pref+1;if(d<=index->pref){/*Can'tallow
youtodothat,Dave*/vty_out(vty,"can'tjumpbackwardsinroute-maps\n");returnCMD_WARN
ING_CONFIG_FAILED;}else{index->exitpolicy=RMAP_GOTO;index->nextpref=d;}}returnCM
D_SUCCESS;}DEFUN(no_rmap_onmatch_goto,no_rmap_onmatch_goto_cmd,"noon-matchgoto",
NO_STR"Exitpolicyonmatches\n""GotoClausenumber\n"){structroute_map_index*index=V
TY_GET_CONTEXT(route_map_index);if(index)index->exitpolicy=RMAP_EXIT;returnCMD_S
UCCESS;}/*Cisco/GNUZebracompatibilityaliases*//*ALIAS_FIXME*/DEFUN(rmap_continue
,rmap_continue_cmd,"continue(1-65535)","Continueonadifferententrywithintheroute-
map\n""Route-mapentrysequencenumber\n"){returnrmap_onmatch_goto(self,vty,argc,ar
gv);}/*ALIAS_FIXME*/DEFUN(no_rmap_continue,no_rmap_continue_cmd,"nocontinue[(1-6
5535)]",NO_STR"Continueonadifferententrywithintheroute-map\n""Route-mapentrysequ
encenumber\n"){returnno_rmap_onmatch_goto(self,vty,argc,argv);}DEFUN(rmap_show_n
ame,rmap_show_name_cmd,"showroute-map[WORD]",SHOW_STR"route-mapinformation\n""ro
ute-mapname\n"){intidx_word=2;constchar*name=(argc==3)?argv[idx_word]->arg:NULL;
returnvty_show_route_map(vty,name);}DEFUN(rmap_call,rmap_call_cmd,"callWORD","Ju
mptoanotherRoute-Mapaftermatch+set\n""Targetroute-mapname\n"){intidx_word=1;stru
ctroute_map_index*index=VTY_GET_CONTEXT(route_map_index);constchar*rmap=argv[idx
_word]->arg;assert(index);if(index->nextrm){route_map_upd8_dependency(RMAP_EVENT
_CALL_DELETED,index->nextrm,index->map->name);XFREE(MTYPE_ROUTE_MAP_NAME,index->
nextrm);}index->nextrm=XSTRDUP(MTYPE_ROUTE_MAP_NAME,rmap);/*Executeeventhook.*/r
oute_map_upd8_dependency(RMAP_EVENT_CALL_ADDED,index->nextrm,index->map->name);r
eturnCMD_SUCCESS;}DEFUN(no_rmap_call,no_rmap_call_cmd,"nocall",NO_STR"Jumptoanot
herRoute-Mapaftermatch+set\n"){structroute_map_index*index=VTY_GET_CONTEXT(route
_map_index);if(index->nextrm){route_map_upd8_dependency(RMAP_EVENT_CALL_DELETED,
index->nextrm,index->map->name);XFREE(MTYPE_ROUTE_MAP_NAME,index->nextrm);index-
>nextrm=NULL;}returnCMD_SUCCESS;}DEFUN(rmap_description,rmap_description_cmd,"de
scriptionLINE...","Route-mapcomment\n""Commentdescribingthisroute-maprule\n"){in
tidx_line=1;structroute_map_index*index=VTY_GET_CONTEXT(route_map_index);if(inde
x){if(index->description)XFREE(MTYPE_TMP,index->description);index->description=
argv_concat(argv,argc,idx_line);}returnCMD_SUCCESS;}DEFUN(no_rmap_description,no
_rmap_description_cmd,"nodescription",NO_STR"Route-mapcomment\n"){structroute_ma
p_index*index=VTY_GET_CONTEXT(route_map_index);if(index){if(index->description)X
FREE(MTYPE_TMP,index->description);index->description=NULL;}returnCMD_SUCCESS;}/
*Configurationwritefunction.*/staticintroute_map_config_write(structvty*vty){str
uctroute_map*map;structroute_map_index*index;structroute_map_rule*rule;intfirst=
1;intwrite=0;for(map=route_map_master.head;map;map=map->next)for(index=map->head
;index;index=index->next){if(!first)vty_out(vty,"!\n");elsefirst=0;vty_out(vty,"
route-map%s%s%d\n",map->name,route_map_type_str(index->type),index->pref);if(ind
ex->description)vty_out(vty,"description%s\n",index->description);for(rule=index
->match_list.head;rule;rule=rule->next)vty_out(vty,"match%s%s\n",rule->cmd->str,
rule->rule_str?rule->rule_str:"");for(rule=index->set_list.head;rule;rule=rule->
next)vty_out(vty,"set%s%s\n",rule->cmd->str,rule->rule_str?rule->rule_str:"");if
(index->nextrm)vty_out(vty,"call%s\n",index->nextrm);if(index->exitpolicy==RMAP_
GOTO)vty_out(vty,"on-matchgoto%d\n",index->nextpref);if(index->exitpolicy==RMAP_
NEXT)vty_out(vty,"on-matchnext\n");write++;}returnwrite;}/*Routemapnodestructure
.*/staticstructcmd_nodermap_node={RMAP_NODE,"%s(config-route-map)#",1};/*Commonr
outemaprules*/void*route_map_rule_tag_compile(constchar*arg){unsignedlonginttmp;
char*endptr;route_tag_t*tag;errno=0;tmp=strtoul(arg,&endptr,0);if(arg[0]=='\0'||
*endptr!='\0'||errno||tmp>ROUTE_TAG_MAX)returnNULL;tag=XMALLOC(MTYPE_ROUTE_MAP_C
OMPILED,sizeof(*tag));*tag=tmp;returntag;}voidroute_map_rule_tag_free(void*rule)
{XFREE(MTYPE_ROUTE_MAP_COMPILED,rule);}voidroute_map_finish(void){inti;vector_fr
ee(route_match_vec);route_match_vec=NULL;vector_free(route_set_vec);route_set_ve
c=NULL;/*cleanuproute_map*/while(route_map_master.head){structroute_map*map=rout
e_map_master.head;map->to_be_processed=0;route_map_delete(map);}for(i=1;i<ROUTE_
MAP_DEP_MAX;i++){hash_free(route_map_dep_hash[i]);route_map_dep_hash[i]=NULL;}ha
sh_free(route_map_master_hash);route_map_master_hash=NULL;}staticvoidrmap_autoco
mplete(vectorcomps,structcmd_token*token){structroute_map*map;for(map=route_map_
master.head;map;map=map->next)vector_set(comps,XSTRDUP(MTYPE_COMPLETION,map->nam
e));}staticconststructcmd_variable_handlerrmap_var_handlers[]={{/*"route-mapWORD
"*/.varname="route_map",.completions=rmap_autocomplete},{.tokenname="ROUTEMAP_NA
ME",.completions=rmap_autocomplete},{.tokenname="RMAP_NAME",.completions=rmap_au
tocomplete},{.completions=NULL}};/*Initializationofroutemapvector.*/voidroute_ma
p_init(void){inti;/*Makevectorformatchandset.*/route_match_vec=vector_init(1);ro
ute_set_vec=vector_init(1);route_map_master_hash=hash_create_size(8,route_map_ha
sh_key_make,route_map_hash_cmp,"RouteMapMasterHash");for(i=1;i<ROUTE_MAP_DEP_MAX
;i++)route_map_dep_hash[i]=hash_create_size(8,route_map_dep_hash_make_key,route_
map_dep_hash_cmp,"RouteMapDepHash");cmd_variable_handler_register(rmap_var_handl
ers);/*Installroutemaptopnode.*/install_node(&rmap_node,route_map_config_write);
/*Installroutemapcommands.*/install_default(RMAP_NODE);install_element(CONFIG_NO
DE,&route_map_cmd);install_element(CONFIG_NODE,&no_route_map_cmd);install_elemen
t(CONFIG_NODE,&no_route_map_all_cmd);/*Installtheon-matchstuff*/install_element(
RMAP_NODE,&route_map_cmd);install_element(RMAP_NODE,&rmap_onmatch_next_cmd);inst
all_element(RMAP_NODE,&no_rmap_onmatch_next_cmd);install_element(RMAP_NODE,&rmap
_onmatch_goto_cmd);install_element(RMAP_NODE,&no_rmap_onmatch_goto_cmd);install_
element(RMAP_NODE,&rmap_continue_cmd);install_element(RMAP_NODE,&no_rmap_continu
e_cmd);/*Installthecontinuestuff(ALIASofon-match).*//*Installthecallstuff.*/inst
all_element(RMAP_NODE,&rmap_call_cmd);install_element(RMAP_NODE,&no_rmap_call_cm
d);/*Installdescriptioncommands.*/install_element(RMAP_NODE,&rmap_description_cm
d);install_element(RMAP_NODE,&no_rmap_description_cmd);/*Installshowcommand*/ins
tall_element(ENABLE_NODE,&rmap_show_name_cmd);install_element(RMAP_NODE,&match_i
nterface_cmd);install_element(RMAP_NODE,&no_match_interface_cmd);install_element
(RMAP_NODE,&match_ip_address_cmd);install_element(RMAP_NODE,&no_match_ip_address
_cmd);install_element(RMAP_NODE,&match_ip_address_prefix_list_cmd);install_eleme
nt(RMAP_NODE,&no_match_ip_address_prefix_list_cmd);install_element(RMAP_NODE,&ma
tch_ip_next_hop_cmd);install_element(RMAP_NODE,&no_match_ip_next_hop_cmd);instal
l_element(RMAP_NODE,&match_ip_next_hop_prefix_list_cmd);install_element(RMAP_NOD
E,&no_match_ip_next_hop_prefix_list_cmd);install_element(RMAP_NODE,&match_ipv6_a
ddress_cmd);install_element(RMAP_NODE,&no_match_ipv6_address_cmd);install_elemen
t(RMAP_NODE,&match_ipv6_address_prefix_list_cmd);install_element(RMAP_NODE,&no_m
atch_ipv6_address_prefix_list_cmd);install_element(RMAP_NODE,&match_metric_cmd);
install_element(RMAP_NODE,&no_match_metric_cmd);install_element(RMAP_NODE,&match
_tag_cmd);install_element(RMAP_NODE,&no_match_tag_cmd);install_element(RMAP_NODE
,&set_ip_nexthop_cmd);install_element(RMAP_NODE,&no_set_ip_nexthop_cmd);install_
element(RMAP_NODE,&set_ipv6_nexthop_local_cmd);install_element(RMAP_NODE,&no_set
_ipv6_nexthop_local_cmd);install_element(RMAP_NODE,&set_metric_cmd);install_elem
ent(RMAP_NODE,&no_set_metric_cmd);install_element(RMAP_NODE,&set_tag_cmd);instal
l_element(RMAP_NODE,&no_set_tag_cmd);}