/*-*Copyright2005,2007,2009ColinPercival*Allrightsreserved.**Redistributionandus
einsourceandbinaryforms,withorwithout*modification,arepermittedprovidedthatthefo
llowingconditions*aremet:*1.Redistributionsofsourcecodemustretaintheabovecopyrig
ht*notice,thislistofconditionsandthefollowingdisclaimer.*2.Redistributionsinbina
ryformmustreproducetheabovecopyright*notice,thislistofconditionsandthefollowingd
isclaimerinthe*documentationand/orothermaterialsprovidedwiththedistribution.**TH
ISSOFTWAREISPROVIDEDBYTHEAUTHORANDCONTRIBUTORS``ASIS''AND*ANYEXPRESSORIMPLIEDWAR
RANTIES,INCLUDING,BUTNOTLIMITEDTO,THE*IMPLIEDWARRANTIESOFMERCHANTABILITYANDFITNE
SSFORAPARTICULARPURPOSE*AREDISCLAIMED.INNOEVENTSHALLTHEAUTHORORCONTRIBUTORSBELIA
BLE*FORANYDIRECT,INDIRECT,INCIDENTAL,SPECIAL,EXEMPLARY,ORCONSEQUENTIAL*DAMAGES(I
NCLUDING,BUTNOTLIMITEDTO,PROCUREMENTOFSUBSTITUTEGOODS*ORSERVICES;LOSSOFUSE,DATA,
ORPROFITS;ORBUSINESSINTERRUPTION)*HOWEVERCAUSEDANDONANYTHEORYOFLIABILITY,WHETHER
INCONTRACT,STRICT*LIABILITY,ORTORT(INCLUDINGNEGLIGENCEOROTHERWISE)ARISINGINANYWA
Y*OUTOFTHEUSEOFTHISSOFTWARE,EVENIFADVISEDOFTHEPOSSIBILITYOF*SUCHDAMAGE.**$FreeBS
D:src/lib/libmd/sha256.h,v1.22006/01/1715:35:56phkExp$*/#ifndef_SHA256_H_#define
_SHA256_H_typedefstructSHA256Context{uint32_tstate[8];uint32_tcount[2];unsignedc
harbuf[64];}SHA256_CTX;typedefstructHMAC_SHA256Context{SHA256_CTXictx;SHA256_CTX
octx;}HMAC_SHA256_CTX;voidSHA256_Init(SHA256_CTX*);voidSHA256_Update(SHA256_CTX*
,constvoid*,size_t);voidSHA256_Final(unsignedchar[32],SHA256_CTX*);voidHMAC__SHA
256_Init(HMAC_SHA256_CTX*,constvoid*,size_t);voidHMAC__SHA256_Update(HMAC_SHA256
_CTX*,constvoid*,size_t);voidHMAC__SHA256_Final(unsignedchar[32],HMAC_SHA256_CTX
*);/***PBKDF2_SHA256(passwd,passwdlen,salt,saltlen,c,buf,dkLen):*ComputePBKDF2(p
asswd,salt,c,dkLen)usingHMAC-SHA256asthePRF,and*writetheoutputtobuf.ThevaluedkLe
nmustbeatmost32*(2^32-1).*/voidPBKDF2_SHA256(constuint8_t*,size_t,constuint8_t*,
size_t,uint64_t,uint8_t*,size_t);#endif/*!_SHA256_H_*/