/*Quaggasignalhandlingfunctions.*Copyright(C)2004PaulJakma,**ThisfileispartofQua
gga.**Quaggaisfreesoftware;youcanredistributeitand/ormodifyit*underthetermsofthe
GNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eitherversion2,or
(atyouroption)any*laterversion.**Quaggaisdistributedinthehopethatitwillbeuseful,
but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSF
ORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldhav
ereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYIN
G;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA
02110-1301USA*/#include<zebra.h>#include<sigevent.h>#include<log.h>#include<memo
ry.h>#ifdefSA_SIGINFO#ifdefHAVE_UCONTEXT_H#ifdefGNU_LINUX/*getREG_EIPfromucontex
t.h*/#ifndef__USE_GNU#define__USE_GNU#endif/*__USE_GNU*/#endif/*GNU_LINUX*/#incl
ude<ucontext.h>#endif/*HAVE_UCONTEXT_H*/#endif/*SA_SIGINFO*//*mastersignalsdescr
iptorstruct*/structquagga_sigevent_master_t{structthread*t;structquagga_signal_t
*signals;intsigc;volatilesig_atomic_tcaught;}sigmaster;/*Genericsignalhandler*Sc
hedulessignaleventthread*/staticvoidquagga_signal_handler(intsigno){inti;structq
uagga_signal_t*sig;for(i=0;i<sigmaster.sigc;i++){sig=&(sigmaster.signals[i]);if(
sig->signal==signo)sig->caught=1;}sigmaster.caught=1;}/*checkifsignalshavebeenca
ughtandrunappropriatehandlers*/intquagga_sigevent_process(void){structquagga_sig
nal_t*sig;inti;#ifdefSIGEVENT_BLOCK_SIGNALS/*shouldntneedtoblocksignals,butpoten
tiallymaybeneeded*/sigset_tnewmask,oldmask;/**Blockmostsignals,butbecarefulnotto
deferSIGTRAPbecause*doingsobreaksgdb,atleastonNetBSD2.0.Avoidaskingto*blockSIGKI
LL,justbecauseweshouldn'tbeabletodoso.*/sigfillset(&newmask);sigdelset(&newmask,
SIGTRAP);sigdelset(&newmask,SIGKILL);if((sigprocmask(SIG_BLOCK,&newmask,&oldmask
))<0){zlog_err("quagga_signal_timer:couldntblocksignals!");return-1;}#endif/*SIG
EVENT_BLOCK_SIGNALS*/if(sigmaster.caught>0){sigmaster.caught=0;/*mustnotreadorse
tsigmaster.caughtafterhere,*raceconditionwithper-sigcaughtflagsifonedoes*/for(i=
0;i<sigmaster.sigc;i++){sig=&(sigmaster.signals[i]);if(sig->caught>0){sig->caugh
t=0;if(sig->handler)sig->handler();}}}#ifdefSIGEVENT_BLOCK_SIGNALSif(sigprocmask
(SIG_UNBLOCK,&oldmask,NULL)<0);return-1;#endif/*SIGEVENT_BLOCK_SIGNALS*/return0;
}#ifdefSIGEVENT_SCHEDULE_THREAD/*timerthreadtochecksignals.Shouldntbeneeded*/int
quagga_signal_timer(structthread*t){structquagga_sigevent_master_t*sigm;structqu
agga_signal_t*sig;inti;sigm=THREAD_ARG(t);sigm->t=NULL;thread_add_timer(sigm->t-
>master,quagga_signal_timer,&sigmaster,QUAGGA_SIGNAL_TIMER_INTERVAL,&sigm->t);re
turnquagga_sigevent_process();}#endif/*SIGEVENT_SCHEDULE_THREAD*//*Initializatio
nofsignalhandles.*//*Signalwrapper.*/staticintsignal_set(intsigno){intret;struct
sigactionsig;structsigactionosig;sig.sa_handler=&quagga_signal_handler;sigfillse
t(&sig.sa_mask);sig.sa_flags=0;if(signo==SIGALRM){#ifdefSA_INTERRUPTsig.sa_flags
|=SA_INTERRUPT;/*SunOS*/#endif}else{#ifdefSA_RESTARTsig.sa_flags|=SA_RESTART;#en
dif/*SA_RESTART*/}ret=sigaction(signo,&sig,&osig);if(ret<0)returnret;elsereturn0
;}#ifdefSA_SIGINFO/*XXXThisfunctionshouldbeenhancedtosupportmoreplatforms(itcurr
entlyworksonlyonLinux/x86).*/staticvoid*program_counter(void*context){#ifdefHAVE
_UCONTEXT_H#ifdefGNU_LINUX/*thesearefromGNUlibc,ratherthanLinux,strictlyspeaking
*/#ifdefined(REG_EIP)#defineREG_INDEXREG_EIP#elifdefined(REG_RIP)#defineREG_INDE
XREG_RIP#elifdefined(__powerpc__)#defineREG_INDEX32#endif#elifdefined(SUNOS_5)/*
!GNU_LINUX*/#defineREG_INDEXREG_PC#endif/*GNU_LINUX*/#ifdefREG_INDEX#ifdefHAVE_U
CONTEXT_T_UC_MCONTEXT_GREGS#defineREGSgregs[REG_INDEX]#elifdefined(HAVE_UCONTEXT
_T_UC_MCONTEXT_UC_REGS)#defineREGSuc_regs->gregs[REG_INDEX]#endif/*HAVE_UCONTEXT
_T_UC_MCONTEXT_GREGS*/#endif/*REG_INDEX*/#ifdefREGSif(context)return(void*)(((uc
ontext_t*)context)->uc_mcontext.REGS);#elifdefined(HAVE_UCONTEXT_T_UC_MCONTEXT_R
EGS__NIP)/*olderLinux/structpt_regs?*/if(context)return(void*)(((ucontext_t*)con
text)->uc_mcontext.regs->nip);#endif/*REGS*/#endif/*HAVE_UCONTEXT_H*/returnNULL;
}#endif/*SA_SIGINFO*/staticvoid__attribute__((noreturn))exit_handler(intsigno#if
defSA_SIGINFO,siginfo_t*siginfo,void*context#endif){zlog_signal(signo,"exiting..
."#ifdefSA_SIGINFO,siginfo,program_counter(context)#endif);_exit(128+signo);}sta
ticvoid__attribute__((noreturn))core_handler(intsigno#ifdefSA_SIGINFO,siginfo_t*
siginfo,void*context#endif){/*makesurewedon'thanginhere.defaultforSIGALRMistermi
nate.*-ifwe'reinbacktraceformorethanasecond,abort.*/structsigactionsa_default={.
sa_handler=SIG_DFL};sigaction(SIGALRM,&sa_default,NULL);sigset_tsigset;sigemptys
et(&sigset);sigaddset(&sigset,SIGALRM);sigprocmask(SIG_UNBLOCK,&sigset,NULL);ala
rm(1);zlog_signal(signo,"aborting..."#ifdefSA_SIGINFO,siginfo,program_counter(co
ntext)#endif);/*dumpmemorystatsoncore*/log_memstats(stderr,"core_handler");abort
();}staticvoidtrap_default_signals(void){staticconstintcore_signals[]={SIGQUIT,S
IGILL,#ifdefSIGEMTSIGEMT,#endifSIGFPE,SIGBUS,SIGSEGV,#ifdefSIGSYSSIGSYS,#endif#i
fdefSIGXCPUSIGXCPU,#endif#ifdefSIGXFSZSIGXFSZ,#endif};staticconstintexit_signals
[]={SIGHUP,SIGINT,SIGALRM,SIGTERM,SIGUSR1,SIGUSR2,#ifdefSIGPOLLSIGPOLL,#endif#if
defSIGVTALRMSIGVTALRM,#endif#ifdefSIGSTKFLTSIGSTKFLT,#endif};staticconstintignor
e_signals[]={SIGPIPE,};staticconststruct{constint*sigs;unsignedintnsigs;void(*ha
ndler)(intsigno#ifdefSA_SIGINFO,siginfo_t*info,void*context#endif);}sigmap[]={{c
ore_signals,array_size(core_signals),core_handler},{exit_signals,array_size(exit
_signals),exit_handler},{ignore_signals,array_size(ignore_signals),NULL},};unsig
nedinti;for(i=0;i<array_size(sigmap);i++){unsignedintj;for(j=0;j<sigmap[i].nsigs
;j++){structsigactionoact;if((sigaction(sigmap[i].sigs[j],NULL,&oact)==0)&&(oact
.sa_handler==SIG_DFL)){structsigactionact;sigfillset(&act.sa_mask);if(sigmap[i].
handler==NULL){act.sa_handler=SIG_IGN;act.sa_flags=0;}else{#ifdefSA_SIGINFO/*Req
uestextraargumentstosignal*handler.*/act.sa_sigaction=sigmap[i].handler;act.sa_f
lags=SA_SIGINFO;#elseact.sa_handler=sigmap[i].handler;act.sa_flags=0;#endif#ifde
fSA_RESETHAND/*don'ttrytoprintbacktraces*recursively*/if(sigmap[i].handler==core
_handler)act.sa_flags|=SA_RESETHAND;#endif}if(sigaction(sigmap[i].sigs[j],&act,N
ULL)<0)zlog_warn("Unabletosetsignalhandlerforsignal%d:%s",sigmap[i].sigs[j],safe
_strerror(errno));}}}}voidsignal_init(structthread_master*m,intsigc,structquagga
_signal_tsignals[]){inti=0;structquagga_signal_t*sig;/*Firstestablishsomedefault
handlersthatcanbeoverriddenbytheapplication.*/trap_default_signals();while(i<sig
c){sig=&signals[i];if(signal_set(sig->signal)<0)exit(-1);i++;}sigmaster.sigc=sig
c;sigmaster.signals=signals;#ifdefSIGEVENT_SCHEDULE_THREADsigmaster.t=NULL;threa
d_add_timer(m,quagga_signal_timer,&sigmaster,QUAGGA_SIGNAL_TIMER_INTERVAL,&sigma
ster.t);#endif/*SIGEVENT_SCHEDULE_THREAD*/}