/**Socketunionheader.*Copyright(c)1997KunihiroIshiguro**ThisfileispartofGNUZebra
.**GNUZebraisfreesoftware;youcanredistributeitand/ormodifyit*underthetermsoftheG
NUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eitherversion2,or(
atyouroption)any*laterversion.**GNUZebraisdistributedinthehopethatitwillbeuseful
,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESS
FORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldha
vereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYI
NG;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,M
A02110-1301USA*/#ifndef_ZEBRA_SOCKUNION_H#define_ZEBRA_SOCKUNION_H#include"privs
.h"#include"if.h"#ifdef__OpenBSD__#include<netmpls/mpls.h>#endifunionsockunion{s
tructsockaddrsa;structsockaddr_insin;structsockaddr_in6sin6;#ifdef__OpenBSD__str
uctsockaddr_mplssmpls;structsockaddr_rtlabelrtlabel;#endif};enumconnect_result{c
onnect_error,connect_success,connect_in_progress};/*Defaultaddressfamily.*/#defi
neAF_INET_UNIONAF_INET6/*Sockunionaddressstringlength.SameasINET6_ADDRSTRLEN.*/#
defineSU_ADDRSTRLEN46/*MacrotosetlinklocalindextotheIPv6address.ForKAMEIPv6stack
.*/#ifdefKAME#defineIN6_LINKLOCAL_IFINDEX(a)((a).s6_addr[2]<<8|(a).s6_addr[3])#d
efineSET_IN6_LINKLOCAL_IFINDEX(a,i)\do{\(a).s6_addr[2]=((i)>>8)&0xff;\(a).s6_add
r[3]=(i)&0xff;\}while(0)#else#defineIN6_LINKLOCAL_IFINDEX(a)#defineSET_IN6_LINKL
OCAL_IFINDEX(a,i)#endif/*KAME*/#definesockunion_family(X)(X)->sa.sa_family#defin
esockunion2ip(X)(X)->sin.sin_addr.s_addr/*Prototypes.*/externintstr2sockunion(co
nstchar*,unionsockunion*);externconstchar*sockunion2str(constunionsockunion*,cha
r*,size_t);externintsockunion_cmp(constunionsockunion*,constunionsockunion*);ext
ernintsockunion_same(constunionsockunion*,constunionsockunion*);externunsignedin
tsockunion_hash(constunionsockunion*);externsize_tfamily2addrsize(intfamily);ext
ernsize_tsockunion_get_addrlen(constunionsockunion*);externconstuint8_t*sockunio
n_get_addr(constunionsockunion*);externvoidsockunion_set(unionsockunion*,intfami
ly,constuint8_t*addr,size_tbytes);externunionsockunion*sockunion_str2su(constcha
r*str);externintsockunion_accept(intsock,unionsockunion*);externintsockunion_str
eam_socket(unionsockunion*);externintsockopt_reuseaddr(int);externintsockopt_reu
seport(int);externintsockopt_v6only(intfamily,intsock);externintsockunion_bind(i
ntsock,unionsockunion*,unsignedshort,unionsockunion*);externintsockopt_ttl(intfa
mily,intsock,intttl);externintsockopt_minttl(intfamily,intsock,intminttl);extern
intsockopt_cork(intsock,intonoff);externintsockopt_mark_default(intsock,intmark,
structzebra_privs_t*);externintsockunion_socket(constunionsockunion*su);externco
nstchar*inet_sutop(constunionsockunion*su,char*str);externenumconnect_resultsock
union_connect(intfd,constunionsockunion*su,unsignedshortport,ifindex_t);externun
ionsockunion*sockunion_getsockname(int);externunionsockunion*sockunion_getpeerna
me(int);externunionsockunion*sockunion_dup(constunionsockunion*);externvoidsocku
nion_free(unionsockunion*);externvoidsockunion_init(unionsockunion*);#endif/*_ZE
BRA_SOCKUNION_H*/