/**Packetinterface*Copyright(C)1999KunihiroIshiguro**ThisfileispartofGNUZebra.**
GNUZebraisfreesoftware;youcanredistributeitand/ormodifyit*underthetermsoftheGNUG
eneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eitherversion2,or(aty
ouroption)any*laterversion.**GNUZebraisdistributedinthehopethatitwillbeuseful,bu
t*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFOR
APARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldhaver
eceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;
ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02
110-1301USA*/#ifndef_ZEBRA_STREAM_H#define_ZEBRA_STREAM_H#include"mpls.h"#includ
e"prefix.h"/**Astreamisanarbitrarybuffer,whosecontentsgenerallyareassumedto*bein
networkorder.**Astreamhasthefollowingattributesassociatedwithit:**-size:thealloc
ated,invariantsizeofthebuffer.**-getp:thegetpositionmarker,denotingtheoffsetinth
estreamwhere*thenextread(or'get')willbefrom.Thisgetpmarkeris*automaticallyadjust
edwhendataisreadfromthestream,the*usermayalsomanipulatethisoffsetastheywish,with
inlimits*(seebelow)**-endp:theendpositionmarker,denotingtheoffsetinthestreamwher
e*validdataends,andiftheuserattemptedtowrite(or*'put')datawherethatdatawouldbewr
itten(or'put')to.**Theseattributesareallsize_tvalues.**Constraints:**1.getpcanne
verexceedendp**-henceifgetpisequaltoendp,thereisnomorevaliddatathatcanbe*gottenf
romthestream(though,theusermayrepositiongetptoearlierin*thestream,iftheywish).**
2.endpcanneverexceedsize**-hence,ifendpisequaltosize,thenthestreamisfull,andnomo
re*datacanbewrittentothestream.**Inotherwordsthefollowingmustalwaysbetrue,andthe
stream*abstractionisallowedinternallytoassertthatthefollowingproperty*holdstruef
orastream,asandwhenitwishes:**getp<=endp<=size**Itistheusersresponsibilitytoensu
rethispropertyisneverviolated.**Astreamthereforecanbethoughtoflikethis:**-------
--------------------------------------------*|XXXXXXXXXXXXXXXXXXXXXXXX|*--------
-------------------------------------------*^^^*getpendpsize**Thisshowsastreamco
ntainingdata(shownas'X')uptotheendpoffset.*Thestreamisemptyfromendptosize.Withou
tadjustinggetp,thereare*stillendp-getpbytesofvaliddatatobereadfromthestream.**Me
thodsareprovidedtogetandputto/fromthestream,aswellas*retrievethevaluesofthe3mark
ersandmanipulatethegetpmarker.**Note:*Atthemoment,newlyallocatedstreamsarezerofi
lled.Hence,onecan*usestream_forward_endp()toeffectivelycreatearbitraryzero-fill*
padding.However,notethatstream_reset()does*not*zero-outthe*stream.Thispropertysh
ould**not**bereliedupon.**Bestpracticeistousestream_put(<stream*>,NULL,<size>)to
zeroout*anypartofastreamwhichisn'totherwisewrittento.*//*Streambuffer.*/structst
ream{structstream*next;/*Remainderis***private***tostream*directaccessisfrownedu
pon!*Usetheappropriatefunctions/macros*/size_tgetp;/*nextgetposition*/size_tendp
;/*lastvaliddataposition*/size_tsize;/*sizeofdatasegment*/unsignedchar*data;/*da
tapointer*/};/*Firstinfirstoutqueuestructure.*/structstream_fifo{size_tcount;str
uctstream*head;structstream*tail;};/*Utilitymacros.*/#defineSTREAM_SIZE(S)((S)->
size)/*numberofbyteswhichcanstillbewritten*/#defineSTREAM_WRITEABLE(S)((S)->size
-(S)->endp)/*numberofbytesstilltoberead*/#defineSTREAM_READABLE(S)((S)->endp-(S)
->getp)#defineSTREAM_CONCAT_REMAIN(S1,S2,size)((size)-(S1)->endp-(S2)->endp)/*de
precatedmacros-donotuseinnewcode*/#ifCONFDATE>20181128CPP_NOTICE("lib:timetoremo
vedeprecatedstream.hmacros")#endif#defineSTREAM_PNT(S)stream_pnt((S))#defineSTRE
AM_REMAIN(S)STREAM_WRITEABLE((S))/*thismacroisdeprecated,butnotslatedforremovala
nytimesoon*/#defineSTREAM_DATA(S)((S)->data)/*Streamprototypes.*Forstream_{put,g
et}S,theSsuffixmean:**c:character(unsignedbyte)*w:word(twobytes)*l:long(twowords
)*q:quad(fourwords)*/externstructstream*stream_new(size_t);externvoidstream_free
(structstream*);externstructstream*stream_copy(structstream*,structstream*src);e
xternstructstream*stream_dup(structstream*);externsize_tstream_resize(structstre
am*,size_t);externsize_tstream_get_getp(structstream*);externsize_tstream_get_en
dp(structstream*);externsize_tstream_get_size(structstream*);externuint8_t*strea
m_get_data(structstream*);/***Createanewstreamstructure;copyoffsetbytesfroms1tot
henew*stream;copys2datatothenewstream;copyrestofs1datatothe*newstream.*/externst
ructstream*stream_dupcat(structstream*s1,structstream*s2,size_toffset);externvoi
dstream_set_getp(structstream*,size_t);externvoidstream_set_endp(structstream*,s
ize_t);externvoidstream_forward_getp(structstream*,size_t);externvoidstream_forw
ard_endp(structstream*,size_t);/*steam_put:NULLsourcezeroesoutsize_tbytesofstrea
m*/externvoidstream_put(structstream*,constvoid*,size_t);externintstream_putc(st
ructstream*,uint8_t);externintstream_putc_at(structstream*,size_t,uint8_t);exter
nintstream_putw(structstream*,uint16_t);externintstream_putw_at(structstream*,si
ze_t,uint16_t);externintstream_put3(structstream*,uint32_t);externintstream_put3
_at(structstream*,size_t,uint32_t);externintstream_putl(structstream*,uint32_t);
externintstream_putl_at(structstream*,size_t,uint32_t);externintstream_putq(stru
ctstream*,uint64_t);externintstream_putq_at(structstream*,size_t,uint64_t);exter
nintstream_put_ipv4(structstream*,uint32_t);externintstream_put_in_addr(structst
ream*,structin_addr*);externintstream_put_in_addr_at(structstream*,size_t,struct
in_addr*);externintstream_put_in6_addr_at(structstream*,size_t,structin6_addr*);
externintstream_put_prefix_addpath(structstream*,structprefix*,intaddpath_encode
,uint32_taddpath_tx_id);externintstream_put_prefix(structstream*,structprefix*);
externintstream_put_labeled_prefix(structstream*,structprefix*,mpls_label_t*);ex
ternvoidstream_get(void*,structstream*,size_t);externboolstream_get2(void*data,s
tructstream*s,size_tsize);externvoidstream_get_from(void*,structstream*,size_t,s
ize_t);externuint8_tstream_getc(structstream*);externboolstream_getc2(structstre
am*s,uint8_t*byte);externuint8_tstream_getc_from(structstream*,size_t);externuin
t16_tstream_getw(structstream*);externboolstream_getw2(structstream*s,uint16_t*w
ord);externuint16_tstream_getw_from(structstream*,size_t);externuint32_tstream_g
et3(structstream*);externuint32_tstream_get3_from(structstream*,size_t);externui
nt32_tstream_getl(structstream*);externboolstream_getl2(structstream*s,uint32_t*
l);externuint32_tstream_getl_from(structstream*,size_t);externuint64_tstream_get
q(structstream*);externuint64_tstream_getq_from(structstream*,size_t);externuint
32_tstream_get_ipv4(structstream*);/*IEEE-754floats*/externfloatstream_getf(stru
ctstream*);externdoublestream_getd(structstream*);externintstream_putf(structstr
eam*,float);externintstream_putd(structstream*,double);#undefstream_read#undefst
ream_write/*Deprecated:assumesblockingI/O.Willberemoved.Usestream_read_tryinstea
d.*/externintstream_read(structstream*,int,size_t);/*Readuptosizebytesintothestr
eam.Returncode:>0:numberofbytesread0:end-of-file-1:fatalerror-2:transienterror,s
houldretrylater(i.e.EAGAINorEINTR)Thisissuitableforusewithnon-blockingfiledescri
ptors.*/externssize_tstream_read_try(structstream*s,intfd,size_tsize);externssiz
e_tstream_recvmsg(structstream*s,intfd,structmsghdr*,intflags,size_tsize);extern
ssize_tstream_recvfrom(structstream*s,intfd,size_tlen,intflags,structsockaddr*fr
om,socklen_t*fromlen);externsize_tstream_write(structstream*,constvoid*,size_t);
/*resetthestream.SeeNoteabove*/externvoidstream_reset(structstream*);externintst
ream_flush(structstream*,int);externintstream_empty(structstream*);/*isthestream
empty?*//*deprecated*/externuint8_t*stream_pnt(structstream*);/*Streamfifo.*/ext
ernstructstream_fifo*stream_fifo_new(void);externvoidstream_fifo_push(structstre
am_fifo*fifo,structstream*s);externstructstream*stream_fifo_pop(structstream_fif
o*fifo);externstructstream*stream_fifo_head(structstream_fifo*fifo);externvoidst
ream_fifo_clean(structstream_fifo*fifo);externvoidstream_fifo_free(structstream_
fifo*fifo);/*Thisisherebecause"<<24"isparticularlyproblematicinC.*Thisisbecauset
heleftoperandof<<isinteger-promoted,whichmeans*anuint8_tgetsconvertedintoa*signe
d*int.Shiftingintothesign*bitofasignedintistheoreticallyundefinedbehaviour,so-th
eleft*operandneedstobecasttounsigned.**Thisisnotaproblemfor16-or8-bitvalues(they
don'treachthesign*bit),for64-bitvalues(youneedtocastthemanyway),andneitherfor*en
coding(becauseit'sdowncasted.)*/staticinlineuint8_t*ptr_get_be32(uint8_t*ptr,uin
t32_t*out){uint32_ttmp;memcpy(&tmp,ptr,sizeof(tmp));*out=ntohl(tmp);returnptr+4;
}/**soNormalstream_getXfunctionsassert.Whichisanathema*tokeepingadaemonupandrunn
ingwhensomethinggoessouth*Provideastream_getX2functionsthatdonotassert.*Inadditi
onprovidethesemacro'sthatuponfailure*gotostream_failure.ThisismodeleduponsomeNL_
XX*macrosinthelinuxkernel.**Thischangeallowsforpropermemoryfreeing*afterwe'vedet
ectedanerror.**Inthefuturewewillberemovingtheassertin*thestreamfunctionsbutwenee
datransition*plan.*/#defineSTREAM_GETC(S,P)\do{\uint8_t_pval;\if(!stream_getc2((
S),&_pval))\gotostream_failure;\(P)=_pval;\}while(0)#defineSTREAM_GETW(S,P)\do{\
uint16_t_pval;\if(!stream_getw2((S),&_pval))\gotostream_failure;\(P)=_pval;\}whi
le(0)#defineSTREAM_GETL(S,P)\do{\uint32_t_pval;\if(!stream_getl2((S),&_pval))\go
tostream_failure;\(P)=_pval;\}while(0)#defineSTREAM_GET(P,STR,SIZE)\do{\if(!stre
am_get2((P),(STR),(SIZE)))\gotostream_failure;\}while(0)#endif/*_ZEBRA_STREAM_H*
/