/**Packetinterface*Copyright(C)1999KunihiroIshiguro**ThisfileispartofGNUZebra.**
GNUZebraisfreesoftware;youcanredistributeitand/ormodifyit*underthetermsoftheGNUG
eneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eitherversion2,or(aty
ouroption)any*laterversion.**GNUZebraisdistributedinthehopethatitwillbeuseful,bu
t*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFOR
APARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldhaver
eceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;
ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02
110-1301USA*/#include<zebra.h>#include<stddef.h>#include"stream.h"#include"memor
y.h"#include"network.h"#include"prefix.h"#include"log.h"DEFINE_MTYPE_STATIC(LIB,
STREAM,"Stream")DEFINE_MTYPE_STATIC(LIB,STREAM_DATA,"Streamdata")DEFINE_MTYPE_ST
ATIC(LIB,STREAM_FIFO,"StreamFIFO")/*Testswhetherapositionisvalid*/#defineGETP_VA
LID(S,G)((G)<=(S)->endp)#definePUT_AT_VALID(S,G)GETP_VALID(S,G)#defineENDP_VALID
(S,E)((E)<=(S)->size)/*assertingsanitychecks.Followingmustbetruebefore*streamfun
ctionsarecalled:**Followingmustalwaysbetrueofstreamelements*beforeandaftercallst
ostreamfunctions:**getp<=endp<=size**Notethatafterastreamfunctioniscalledfollowi
ngmaybetrue:*if(getp==endp)thenstreamisnolongerreadable*if(endp==size)thenstream
isnolongerwriteable**Itisvalidtoputtoanywherewithinthesizeofthestream,butonly*us
ingstream_put..._at()functions.*/#defineSTREAM_WARN_OFFSETS(S)\zlog_warn("&(stru
ctstream):%p,size:%lu,getp:%lu,endp:%lu\n",\(void*)(S),(unsignedlong)(S)->size,\
(unsignedlong)(S)->getp,(unsignedlong)(S)->endp)#defineSTREAM_VERIFY_SANE(S)\do{
\if(!(GETP_VALID(S,(S)->getp)&&ENDP_VALID(S,(S)->endp)))\STREAM_WARN_OFFSETS(S);
\assert(GETP_VALID(S,(S)->getp));\assert(ENDP_VALID(S,(S)->endp));\}while(0)#def
ineSTREAM_BOUND_WARN(S,WHAT)\do{\zlog_warn("%s:Attemptto%soutofbounds",__func__,
\(WHAT));\STREAM_WARN_OFFSETS(S);\assert(0);\}while(0)#defineSTREAM_BOUND_WARN2(
S,WHAT)\do{\zlog_warn("%s:Attemptto%soutofbounds",__func__,\(WHAT));\STREAM_WARN
_OFFSETS(S);\}while(0)/*XXX:Deprecatedmacro:donotuse*/#defineCHECK_SIZE(S,Z)\do{
\if(((S)->endp+(Z))>(S)->size){\zlog_warn(\"CHECK_SIZE:truncatingrequestedsize%l
u\n",\(unsignedlong)(Z));\STREAM_WARN_OFFSETS(S);\(Z)=(S)->size-(S)->endp;\}\}wh
ile(0);/*Makestreambuffer.*/structstream*stream_new(size_tsize){structstream*s;a
ssert(size>0);s=XCALLOC(MTYPE_STREAM,sizeof(structstream));if(s==NULL)returns;if
((s->data=XMALLOC(MTYPE_STREAM_DATA,size))==NULL){XFREE(MTYPE_STREAM,s);returnNU
LL;}s->size=size;returns;}/*Freeitnow.*/voidstream_free(structstream*s){if(!s)re
turn;XFREE(MTYPE_STREAM_DATA,s->data);XFREE(MTYPE_STREAM,s);}structstream*stream
_copy(structstream*new,structstream*src){STREAM_VERIFY_SANE(src);assert(new!=NUL
L);assert(STREAM_SIZE(new)>=src->endp);new->endp=src->endp;new->getp=src->getp;m
emcpy(new->data,src->data,src->endp);returnnew;}structstream*stream_dup(structst
ream*s){structstream*new;STREAM_VERIFY_SANE(s);if((new=stream_new(s->endp))==NUL
L)returnNULL;return(stream_copy(new,s));}structstream*stream_dupcat(structstream
*s1,structstream*s2,size_toffset){structstream*new;STREAM_VERIFY_SANE(s1);STREAM
_VERIFY_SANE(s2);if((new=stream_new(s1->endp+s2->endp))==NULL)returnNULL;memcpy(
new->data,s1->data,offset);memcpy(new->data+offset,s2->data,s2->endp);memcpy(new
->data+offset+s2->endp,s1->data+offset,(s1->endp-offset));new->endp=s1->endp+s2-
>endp;returnnew;}size_tstream_resize(structstream*s,size_tnewsize){uint8_t*newda
ta;STREAM_VERIFY_SANE(s);newdata=XREALLOC(MTYPE_STREAM_DATA,s->data,newsize);if(
newdata==NULL)returns->size;s->data=newdata;s->size=newsize;if(s->endp>s->size)s
->endp=s->size;if(s->getp>s->endp)s->getp=s->endp;STREAM_VERIFY_SANE(s);returns-
>size;}size_tstream_get_getp(structstream*s){STREAM_VERIFY_SANE(s);returns->getp
;}size_tstream_get_endp(structstream*s){STREAM_VERIFY_SANE(s);returns->endp;}siz
e_tstream_get_size(structstream*s){STREAM_VERIFY_SANE(s);returns->size;}/*Stream
structre'streampointerrelatedfunctions.*/voidstream_set_getp(structstream*s,size
_tpos){STREAM_VERIFY_SANE(s);if(!GETP_VALID(s,pos)){STREAM_BOUND_WARN(s,"setgetp
");pos=s->endp;}s->getp=pos;}voidstream_set_endp(structstream*s,size_tpos){STREA
M_VERIFY_SANE(s);if(!ENDP_VALID(s,pos)){STREAM_BOUND_WARN(s,"setendp");return;}/
**Makesurethecurrentreadpointerisnotbeyondthenewendp.*/if(s->getp>pos){STREAM_BO
UND_WARN(s,"setendp");return;}s->endp=pos;STREAM_VERIFY_SANE(s);}/*Forwardpointe
r.*/voidstream_forward_getp(structstream*s,size_tsize){STREAM_VERIFY_SANE(s);if(
!GETP_VALID(s,s->getp+size)){STREAM_BOUND_WARN(s,"seekgetp");return;}s->getp+=si
ze;}voidstream_forward_endp(structstream*s,size_tsize){STREAM_VERIFY_SANE(s);if(
!ENDP_VALID(s,s->endp+size)){STREAM_BOUND_WARN(s,"seekendp");return;}s->endp+=si
ze;}/*Copyfromstreamtodestination.*/inlineboolstream_get2(void*dst,structstream*
s,size_tsize){STREAM_VERIFY_SANE(s);if(STREAM_READABLE(s)<size){STREAM_BOUND_WAR
N2(s,"get");returnfalse;}memcpy(dst,s->data+s->getp,size);s->getp+=size;returntr
ue;}voidstream_get(void*dst,structstream*s,size_tsize){STREAM_VERIFY_SANE(s);if(
STREAM_READABLE(s)<size){STREAM_BOUND_WARN(s,"get");return;}memcpy(dst,s->data+s
->getp,size);s->getp+=size;}/*Getnextcharacterfromthestream.*/inlineboolstream_g
etc2(structstream*s,uint8_t*byte){STREAM_VERIFY_SANE(s);if(STREAM_READABLE(s)<si
zeof(uint8_t)){STREAM_BOUND_WARN2(s,"getchar");returnfalse;}*byte=s->data[s->get
p++];returntrue;}uint8_tstream_getc(structstream*s){uint8_tc;STREAM_VERIFY_SANE(
s);if(STREAM_READABLE(s)<sizeof(uint8_t)){STREAM_BOUND_WARN(s,"getchar");return0
;}c=s->data[s->getp++];returnc;}/*Getnextcharacterfromthestream.*/uint8_tstream_
getc_from(structstream*s,size_tfrom){uint8_tc;STREAM_VERIFY_SANE(s);if(!GETP_VAL
ID(s,from+sizeof(uint8_t))){STREAM_BOUND_WARN(s,"getchar");return0;}c=s->data[fr
om];returnc;}inlineboolstream_getw2(structstream*s,uint16_t*word){STREAM_VERIFY_
SANE(s);if(STREAM_READABLE(s)<sizeof(uint16_t)){STREAM_BOUND_WARN2(s,"get");retu
rnfalse;}*word=s->data[s->getp++]<<8;*word|=s->data[s->getp++];returntrue;}/*Get
nextwordfromthestream.*/uint16_tstream_getw(structstream*s){uint16_tw;STREAM_VER
IFY_SANE(s);if(STREAM_READABLE(s)<sizeof(uint16_t)){STREAM_BOUND_WARN(s,"get");r
eturn0;}w=s->data[s->getp++]<<8;w|=s->data[s->getp++];returnw;}/*Getnextwordfrom
thestream.*/uint16_tstream_getw_from(structstream*s,size_tfrom){uint16_tw;STREAM
_VERIFY_SANE(s);if(!GETP_VALID(s,from+sizeof(uint16_t))){STREAM_BOUND_WARN(s,"ge
t");return0;}w=s->data[from++]<<8;w|=s->data[from];returnw;}/*Getnext3-bytefromt
hestream.*/uint32_tstream_get3_from(structstream*s,size_tfrom){uint32_tl;STREAM_
VERIFY_SANE(s);if(!GETP_VALID(s,from+3)){STREAM_BOUND_WARN(s,"get3byte");return0
;}l=s->data[from++]<<16;l|=s->data[from++]<<8;l|=s->data[from];returnl;}uint32_t
stream_get3(structstream*s){uint32_tl;STREAM_VERIFY_SANE(s);if(STREAM_READABLE(s
)<3){STREAM_BOUND_WARN(s,"get3byte");return0;}l=s->data[s->getp++]<<16;l|=s->dat
a[s->getp++]<<8;l|=s->data[s->getp++];returnl;}/*Getnextlongwordfromthestream.*/
uint32_tstream_getl_from(structstream*s,size_tfrom){uint32_tl;STREAM_VERIFY_SANE
(s);if(!GETP_VALID(s,from+sizeof(uint32_t))){STREAM_BOUND_WARN(s,"getlong");retu
rn0;}l=(unsigned)(s->data[from++])<<24;l|=s->data[from++]<<16;l|=s->data[from++]
<<8;l|=s->data[from];returnl;}/*Copyfromstreamatspecificlocationtodestination.*/
voidstream_get_from(void*dst,structstream*s,size_tfrom,size_tsize){STREAM_VERIFY
_SANE(s);if(!GETP_VALID(s,from+size)){STREAM_BOUND_WARN(s,"getfrom");return;}mem
cpy(dst,s->data+from,size);}inlineboolstream_getl2(structstream*s,uint32_t*l){ST
REAM_VERIFY_SANE(s);if(STREAM_READABLE(s)<sizeof(uint32_t)){STREAM_BOUND_WARN2(s
,"getlong");returnfalse;}*l=(unsignedint)(s->data[s->getp++])<<24;*l|=s->data[s-
>getp++]<<16;*l|=s->data[s->getp++]<<8;*l|=s->data[s->getp++];returntrue;}uint32
_tstream_getl(structstream*s){uint32_tl;STREAM_VERIFY_SANE(s);if(STREAM_READABLE
(s)<sizeof(uint32_t)){STREAM_BOUND_WARN(s,"getlong");return0;}l=(unsigned)(s->da
ta[s->getp++])<<24;l|=s->data[s->getp++]<<16;l|=s->data[s->getp++]<<8;l|=s->data
[s->getp++];returnl;}/*Getnextquadwordfromthestream.*/uint64_tstream_getq_from(s
tructstream*s,size_tfrom){uint64_tq;STREAM_VERIFY_SANE(s);if(!GETP_VALID(s,from+
sizeof(uint64_t))){STREAM_BOUND_WARN(s,"getquad");return0;}q=((uint64_t)s->data[
from++])<<56;q|=((uint64_t)s->data[from++])<<48;q|=((uint64_t)s->data[from++])<<
40;q|=((uint64_t)s->data[from++])<<32;q|=((uint64_t)s->data[from++])<<24;q|=((ui
nt64_t)s->data[from++])<<16;q|=((uint64_t)s->data[from++])<<8;q|=((uint64_t)s->d
ata[from++]);returnq;}uint64_tstream_getq(structstream*s){uint64_tq;STREAM_VERIF
Y_SANE(s);if(STREAM_READABLE(s)<sizeof(uint64_t)){STREAM_BOUND_WARN(s,"getquad")
;return0;}q=((uint64_t)s->data[s->getp++])<<56;q|=((uint64_t)s->data[s->getp++])
<<48;q|=((uint64_t)s->data[s->getp++])<<40;q|=((uint64_t)s->data[s->getp++])<<32
;q|=((uint64_t)s->data[s->getp++])<<24;q|=((uint64_t)s->data[s->getp++])<<16;q|=
((uint64_t)s->data[s->getp++])<<8;q|=((uint64_t)s->data[s->getp++]);returnq;}/*G
etnextlongwordfromthestream.*/uint32_tstream_get_ipv4(structstream*s){uint32_tl;
STREAM_VERIFY_SANE(s);if(STREAM_READABLE(s)<sizeof(uint32_t)){STREAM_BOUND_WARN(
s,"getipv4");return0;}memcpy(&l,s->data+s->getp,sizeof(uint32_t));s->getp+=sizeo
f(uint32_t);returnl;}floatstream_getf(structstream*s){union{floatr;uint32_td;}u;
u.d=stream_getl(s);returnu.r;}doublestream_getd(structstream*s){union{doubler;ui
nt64_td;}u;u.d=stream_getq(s);returnu.r;}/*Copytosourcetostream.**XXX:ThisusesCH
ECK_SIZEandhencehasfunnysemantics->Sizewillwrap*around.Thisshouldbefixedoncethes
treamupdatesareworking.**stream_write()issaner*/voidstream_put(structstream*s,co
nstvoid*src,size_tsize){/*XXX:CHECK_SIZEhasstrangesemantics.Itshouldbedeprecated
*/CHECK_SIZE(s,size);STREAM_VERIFY_SANE(s);if(STREAM_WRITEABLE(s)<size){STREAM_B
OUND_WARN(s,"put");return;}if(src)memcpy(s->data+s->endp,src,size);elsememset(s-
>data+s->endp,0,size);s->endp+=size;}/*Putcharactertothestream.*/intstream_putc(
structstream*s,uint8_tc){STREAM_VERIFY_SANE(s);if(STREAM_WRITEABLE(s)<sizeof(uin
t8_t)){STREAM_BOUND_WARN(s,"put");return0;}s->data[s->endp++]=c;returnsizeof(uin
t8_t);}/*Putwordtothestream.*/intstream_putw(structstream*s,uint16_tw){STREAM_VE
RIFY_SANE(s);if(STREAM_WRITEABLE(s)<sizeof(uint16_t)){STREAM_BOUND_WARN(s,"put")
;return0;}s->data[s->endp++]=(uint8_t)(w>>8);s->data[s->endp++]=(uint8_t)w;retur
n2;}/*Putlongwordtothestream.*/intstream_put3(structstream*s,uint32_tl){STREAM_V
ERIFY_SANE(s);if(STREAM_WRITEABLE(s)<3){STREAM_BOUND_WARN(s,"put");return0;}s->d
ata[s->endp++]=(uint8_t)(l>>16);s->data[s->endp++]=(uint8_t)(l>>8);s->data[s->en
dp++]=(uint8_t)l;return3;}/*Putlongwordtothestream.*/intstream_putl(structstream
*s,uint32_tl){STREAM_VERIFY_SANE(s);if(STREAM_WRITEABLE(s)<sizeof(uint32_t)){STR
EAM_BOUND_WARN(s,"put");return0;}s->data[s->endp++]=(uint8_t)(l>>24);s->data[s->
endp++]=(uint8_t)(l>>16);s->data[s->endp++]=(uint8_t)(l>>8);s->data[s->endp++]=(
uint8_t)l;return4;}/*Putquadwordtothestream.*/intstream_putq(structstream*s,uint
64_tq){STREAM_VERIFY_SANE(s);if(STREAM_WRITEABLE(s)<sizeof(uint64_t)){STREAM_BOU
ND_WARN(s,"putquad");return0;}s->data[s->endp++]=(uint8_t)(q>>56);s->data[s->end
p++]=(uint8_t)(q>>48);s->data[s->endp++]=(uint8_t)(q>>40);s->data[s->endp++]=(ui
nt8_t)(q>>32);s->data[s->endp++]=(uint8_t)(q>>24);s->data[s->endp++]=(uint8_t)(q
>>16);s->data[s->endp++]=(uint8_t)(q>>8);s->data[s->endp++]=(uint8_t)q;return8;}
intstream_putf(structstream*s,floatf){union{floati;uint32_to;}u;u.i=f;returnstre
am_putl(s,u.o);}intstream_putd(structstream*s,doubled){union{doublei;uint64_to;}
u;u.i=d;returnstream_putq(s,u.o);}intstream_putc_at(structstream*s,size_tputp,ui
nt8_tc){STREAM_VERIFY_SANE(s);if(!PUT_AT_VALID(s,putp+sizeof(uint8_t))){STREAM_B
OUND_WARN(s,"put");return0;}s->data[putp]=c;return1;}intstream_putw_at(structstr
eam*s,size_tputp,uint16_tw){STREAM_VERIFY_SANE(s);if(!PUT_AT_VALID(s,putp+sizeof
(uint16_t))){STREAM_BOUND_WARN(s,"put");return0;}s->data[putp]=(uint8_t)(w>>8);s
->data[putp+1]=(uint8_t)w;return2;}intstream_put3_at(structstream*s,size_tputp,u
int32_tl){STREAM_VERIFY_SANE(s);if(!PUT_AT_VALID(s,putp+3)){STREAM_BOUND_WARN(s,
"put");return0;}s->data[putp]=(uint8_t)(l>>16);s->data[putp+1]=(uint8_t)(l>>8);s
->data[putp+2]=(uint8_t)l;return3;}intstream_putl_at(structstream*s,size_tputp,u
int32_tl){STREAM_VERIFY_SANE(s);if(!PUT_AT_VALID(s,putp+sizeof(uint32_t))){STREA
M_BOUND_WARN(s,"put");return0;}s->data[putp]=(uint8_t)(l>>24);s->data[putp+1]=(u
int8_t)(l>>16);s->data[putp+2]=(uint8_t)(l>>8);s->data[putp+3]=(uint8_t)l;return
4;}intstream_putq_at(structstream*s,size_tputp,uint64_tq){STREAM_VERIFY_SANE(s);
if(!PUT_AT_VALID(s,putp+sizeof(uint64_t))){STREAM_BOUND_WARN(s,"put");return0;}s
->data[putp]=(uint8_t)(q>>56);s->data[putp+1]=(uint8_t)(q>>48);s->data[putp+2]=(
uint8_t)(q>>40);s->data[putp+3]=(uint8_t)(q>>32);s->data[putp+4]=(uint8_t)(q>>24
);s->data[putp+5]=(uint8_t)(q>>16);s->data[putp+6]=(uint8_t)(q>>8);s->data[putp+
7]=(uint8_t)q;return8;}/*Putlongwordtothestream.*/intstream_put_ipv4(structstrea
m*s,uint32_tl){STREAM_VERIFY_SANE(s);if(STREAM_WRITEABLE(s)<sizeof(uint32_t)){ST
REAM_BOUND_WARN(s,"put");return0;}memcpy(s->data+s->endp,&l,sizeof(uint32_t));s-
>endp+=sizeof(uint32_t);returnsizeof(uint32_t);}/*Putlongwordtothestream.*/intst
ream_put_in_addr(structstream*s,structin_addr*addr){STREAM_VERIFY_SANE(s);if(STR
EAM_WRITEABLE(s)<sizeof(uint32_t)){STREAM_BOUND_WARN(s,"put");return0;}memcpy(s-
>data+s->endp,addr,sizeof(uint32_t));s->endp+=sizeof(uint32_t);returnsizeof(uint
32_t);}/*Putin_addratlocationinthestream.*/intstream_put_in_addr_at(structstream
*s,size_tputp,structin_addr*addr){STREAM_VERIFY_SANE(s);if(!PUT_AT_VALID(s,putp+
4)){STREAM_BOUND_WARN(s,"put");return0;}memcpy(&s->data[putp],addr,4);return4;}/
*Putin6_addratlocationinthestream.*/intstream_put_in6_addr_at(structstream*s,siz
e_tputp,structin6_addr*addr){STREAM_VERIFY_SANE(s);if(!PUT_AT_VALID(s,putp+16)){
STREAM_BOUND_WARN(s,"put");return0;}memcpy(&s->data[putp],addr,16);return16;}/*P
utprefixbynlritypeformat.*/intstream_put_prefix_addpath(structstream*s,structpre
fix*p,intaddpath_encode,uint32_taddpath_tx_id){size_tpsize;size_tpsize_with_addp
ath;STREAM_VERIFY_SANE(s);psize=PSIZE(p->prefixlen);if(addpath_encode)psize_with
_addpath=psize+4;elsepsize_with_addpath=psize;if(STREAM_WRITEABLE(s)<(psize_with
_addpath+sizeof(uint8_t))){STREAM_BOUND_WARN(s,"put");return0;}if(addpath_encode
){s->data[s->endp++]=(uint8_t)(addpath_tx_id>>24);s->data[s->endp++]=(uint8_t)(a
ddpath_tx_id>>16);s->data[s->endp++]=(uint8_t)(addpath_tx_id>>8);s->data[s->endp
++]=(uint8_t)addpath_tx_id;}s->data[s->endp++]=p->prefixlen;memcpy(s->data+s->en
dp,&p->u.prefix,psize);s->endp+=psize;returnpsize;}intstream_put_prefix(structst
ream*s,structprefix*p){returnstream_put_prefix_addpath(s,p,0,0);}/*PutNLRIwithla
bel*/intstream_put_labeled_prefix(structstream*s,structprefix*p,mpls_label_t*lab
el){size_tpsize;uint8_t*label_pnt=(uint8_t*)label;STREAM_VERIFY_SANE(s);psize=PS
IZE(p->prefixlen);if(STREAM_WRITEABLE(s)<(psize+3)){STREAM_BOUND_WARN(s,"put");r
eturn0;}stream_putc(s,(p->prefixlen+24));stream_putc(s,label_pnt[0]);stream_putc
(s,label_pnt[1]);stream_putc(s,label_pnt[2]);memcpy(s->data+s->endp,&p->u.prefix
,psize);s->endp+=psize;return(psize+3);}/*Readsizefromfd.*/intstream_read(struct
stream*s,intfd,size_tsize){intnbytes;STREAM_VERIFY_SANE(s);if(STREAM_WRITEABLE(s
)<size){STREAM_BOUND_WARN(s,"put");return0;}nbytes=readn(fd,s->data+s->endp,size
);if(nbytes>0)s->endp+=nbytes;returnnbytes;}ssize_tstream_read_try(structstream*
s,intfd,size_tsize){ssize_tnbytes;STREAM_VERIFY_SANE(s);if(STREAM_WRITEABLE(s)<s
ize){STREAM_BOUND_WARN(s,"put");/*Fatal(nottransient)error,sinceretryingwillnoth
elp(streamistoosmalltocontainthedesireddata).*/return-1;}if((nbytes=read(fd,s->d
ata+s->endp,size))>=0){s->endp+=nbytes;returnnbytes;}/*Error:wasittransient(retu
rn-2)orfatal(return-1)?*/if(ERRNO_IO_RETRY(errno))return-2;zlog_warn("%s:readfai
ledonfd%d:%s",__func__,fd,safe_strerror(errno));return-1;}/*Readuptosizebytesint
othestreamfromthefd,usingrecvmsgfrom*whoseargumentsmatchtheremainingargumentstot
hisfunction*/ssize_tstream_recvfrom(structstream*s,intfd,size_tsize,intflags,str
uctsockaddr*from,socklen_t*fromlen){ssize_tnbytes;STREAM_VERIFY_SANE(s);if(STREA
M_WRITEABLE(s)<size){STREAM_BOUND_WARN(s,"put");/*Fatal(nottransient)error,since
retryingwillnothelp(streamistoosmalltocontainthedesireddata).*/return-1;}if((nby
tes=recvfrom(fd,s->data+s->endp,size,flags,from,fromlen))>=0){s->endp+=nbytes;re
turnnbytes;}/*Error:wasittransient(return-2)orfatal(return-1)?*/if(ERRNO_IO_RETR
Y(errno))return-2;zlog_warn("%s:readfailedonfd%d:%s",__func__,fd,safe_strerror(e
rrno));return-1;}/*ReaduptosmallerofsizeorSIZE_REMAIN()bytestothestream,starting
*fromendp.*Firstiovecwillbeusedtoreceivethedata.*Streamneednotbeempty.*/ssize_ts
tream_recvmsg(structstream*s,intfd,structmsghdr*msgh,intflags,size_tsize){intnby
tes;structiovec*iov;STREAM_VERIFY_SANE(s);assert(msgh->msg_iovlen>0);if(STREAM_W
RITEABLE(s)<size){STREAM_BOUND_WARN(s,"put");/*Thisisalogicerrorinthecallingcode
:thestreamistoosmalltoholdthedesireddata!*/return-1;}iov=&(msgh->msg_iov[0]);iov
->iov_base=(s->data+s->endp);iov->iov_len=size;nbytes=recvmsg(fd,msgh,flags);if(
nbytes>0)s->endp+=nbytes;returnnbytes;}/*Writedatatobuffer.*/size_tstream_write(
structstream*s,constvoid*ptr,size_tsize){CHECK_SIZE(s,size);STREAM_VERIFY_SANE(s
);if(STREAM_WRITEABLE(s)<size){STREAM_BOUND_WARN(s,"put");return0;}memcpy(s->dat
a+s->endp,ptr,size);s->endp+=size;returnsize;}/*Returncurrentreadpointer.*DEPREC
ATED!*Usestream_get_pnt_toifyoumust,butdecodingstreamsproperly*ispreferred*/uint
8_t*stream_pnt(structstream*s){STREAM_VERIFY_SANE(s);returns->data+s->getp;}/*Ch
eckdoesthisstreamempty?*/intstream_empty(structstream*s){STREAM_VERIFY_SANE(s);r
eturn(s->endp==0);}/*Resetstream.*/voidstream_reset(structstream*s){STREAM_VERIF
Y_SANE(s);s->getp=s->endp=0;}/*Writestreamcontenstothefilediscriptor.*/intstream
_flush(structstream*s,intfd){intnbytes;STREAM_VERIFY_SANE(s);nbytes=write(fd,s->
data+s->getp,s->endp-s->getp);returnnbytes;}/*Streamfirstinfirstoutqueue.*/struc
tstream_fifo*stream_fifo_new(void){structstream_fifo*new;new=XCALLOC(MTYPE_STREA
M_FIFO,sizeof(structstream_fifo));returnnew;}/*Addnewstreamtofifo.*/voidstream_f
ifo_push(structstream_fifo*fifo,structstream*s){if(fifo->tail)fifo->tail->next=s
;elsefifo->head=s;fifo->tail=s;fifo->count++;}/*Deletefirststreamfromfifo.*/stru
ctstream*stream_fifo_pop(structstream_fifo*fifo){structstream*s;s=fifo->head;if(
s){fifo->head=s->next;if(fifo->head==NULL)fifo->tail=NULL;fifo->count--;}returns
;}/*Returnfirstfifoentry.*/structstream*stream_fifo_head(structstream_fifo*fifo)
{returnfifo->head;}voidstream_fifo_clean(structstream_fifo*fifo){structstream*s;
structstream*next;for(s=fifo->head;s;s=next){next=s->next;stream_free(s);}fifo->
head=fifo->tail=NULL;fifo->count=0;}voidstream_fifo_free(structstream_fifo*fifo)
{stream_fifo_clean(fifo);XFREE(MTYPE_STREAM_FIFO,fifo);}