/*Copyanull-terminatedstringtoafixed-sizebuffer,withlengthchecking.*Copyright(C)
2016FreeSoftwareFoundation,Inc.*ThisfileispartoftheGNUCLibrary.**TheGNUCLibraryi
sfreesoftware;youcanredistributeitand/or*modifyitunderthetermsoftheGNULesserGene
ralPublic*LicenseaspublishedbytheFreeSoftwareFoundation;either*version2.1oftheLi
cense,or(atyouroption)anylaterversion.**TheGNUCLibraryisdistributedinthehopethat
itwillbeuseful,*butWITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTAB
ILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*LesserGeneralPublicLicenseformored
etails.**YoushouldhavereceivedacopyoftheGNULesserGeneralPublic*Licensealongwitht
heGNUCLibrary;ifnot,see*<http://www.gnu.org/licenses/>.*//*adaptedforQuaggafromg
libcpatchsubmissionoriginallyfrom*FlorianWeimer<fweimer@redhat.com>,2016-05-18*/
#include<string.h>#include"config.h"#ifndefHAVE_STRLCPY#undefstrlcpysize_tstrlcp
y(char*__restrictdest,constchar*__restrictsrc,size_tdestsize);size_tstrlcpy(char
*__restrictdest,constchar*__restrictsrc,size_tdestsize){size_tsrc_length=strlen(
src);if(__builtin_expect(src_length>=destsize,0)){if(destsize>0){/**Copytheleadi
ngportionofthestring.Thelast*characterissubsequentlyoverwrittenwiththeNUL*termin
ator,butthedestinationdestsizeisusually*amultipleofasmallpoweroftwo,sowritingit*
twiceshouldbemoreefficientthancopyinganodd*numberofbytes.*/memcpy(dest,src,dests
ize);dest[destsize-1]='\0';}}else/*CopythestringanditsterminatingNULcharacter.*/
memcpy(dest,src,src_length+1);returnsrc_length;}#endif/*HAVE_STRLCPY*/