/*Appendanull-terminatedstringtoanotherstring,withlengthchecking.*Copyright(C)20
16FreeSoftwareFoundation,Inc.*ThisfileispartoftheGNUCLibrary.**TheGNUCLibraryisf
reesoftware;youcanredistributeitand/or*modifyitunderthetermsoftheGNULesserGenera
lPublic*LicenseaspublishedbytheFreeSoftwareFoundation;either*version2.1oftheLice
nse,or(atyouroption)anylaterversion.**TheGNUCLibraryisdistributedinthehopethatit
willbeuseful,*butWITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABIL
ITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*LesserGeneralPublicLicenseformoredet
ails.**YoushouldhavereceivedacopyoftheGNULesserGeneralPublic*Licensealongwiththe
GNUCLibrary;ifnot,see*<http://www.gnu.org/licenses/>.*//*adaptedforQuaggafromgli
bcpatchsubmissionoriginallyfrom*FlorianWeimer<fweimer@redhat.com>,2016-05-18*/#i
nclude<stdint.h>#include<string.h>#include"config.h"#ifndefHAVE_STRLCAT#undefstr
lcatsize_tstrlcat(char*__restrictdest,constchar*__restrictsrc,size_tdestsize);si
ze_tstrlcat(char*__restrictdest,constchar*__restrictsrc,size_tdestsize){size_tsr
c_length=strlen(src);/*Ourimplementationstrlcatsupportsdest==NULLifsize==0(forco
nsistencywithsnprintfandstrlcpy),butstrnlendoesnot,sowehavetocoverthiscaseexplic
itly.*/if(destsize==0)returnsrc_length;size_tdest_length=strnlen(dest,destsize);
if(dest_length!=destsize){/*Copyatmosttheremainingnumberofcharactersinthedestina
tionbuffer.LeavefortheNULterminator.*/size_tto_copy=destsize-dest_length-1;/*But
notmorethanwhatisavailableinthesourcestring.*/if(to_copy>src_length)to_copy=src_
length;char*target=dest+dest_length;memcpy(target,src,to_copy);target[to_copy]='
\0';}/*Ifthesumwrapsaround,wehavemorethanSIZE_MAX+2bytesinthetwoinputstrings(inc
ludingbothnullterminators).Ifeachbyteintheaddressspacecanbeassignedauniquesize_t
value(whichthestatic_assertchecks),thenbythepigeonholeprinciple,thetwoinputstrin
gsmustoverlap,whichisundefined.*/#if__STDC_VERSION__>=201112L_Static_assert(size
of(uintptr_t)==sizeof(size_t),"theoreticalmaximumobjectsizecoversaddressspace");
#endifreturndest_length+src_length;}#endif/*HAVE_STRLCAT*/