/**RoutingTablefunctions.*Copyright(C)1998KunihiroIshiguro**ThisfileispartofGNUZ
ebra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodifyit*underthetermsof
theGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eitherversion2
,or(atyouroption)any*laterversion.**GNUZebraisdistributedinthehopethatitwillbeus
eful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFIT
NESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshou
ldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileC
OPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Bost
on,MA02110-1301USA*/#defineFRR_COMPILING_TABLE_C#include<zebra.h>#include"prefix
.h"#include"table.h"#include"memory.h"#include"sockunion.h"DEFINE_MTYPE(LIB,ROUT
E_TABLE,"Routetable")DEFINE_MTYPE(LIB,ROUTE_NODE,"Routenode")staticvoidroute_tab
le_free(structroute_table*);staticintroute_table_hash_cmp(constvoid*a,constvoid*
b){conststructprefix*pa=a,*pb=b;returnprefix_cmp(pa,pb)==0;}/**route_table_init_
with_delegate*/structroute_table*route_table_init_with_delegate(route_table_dele
gate_t*delegate){structroute_table*rt;rt=XCALLOC(MTYPE_ROUTE_TABLE,sizeof(struct
route_table));rt->delegate=delegate;rt->hash=hash_create(prefix_hash_key,route_t
able_hash_cmp,"routetablehash");returnrt;}voidroute_table_finish(structroute_tab
le*rt){route_table_free(rt);}/*Allocatenewroutenode.*/staticstructroute_node*rou
te_node_new(structroute_table*table){returntable->delegate->create_node(table->d
elegate,table);}/*Allocatenewroutenodewithprefixset.*/staticstructroute_node*rou
te_node_set(structroute_table*table,conststructprefix*prefix){structroute_node*n
ode,*inserted;node=route_node_new(table);prefix_copy(&node->p,prefix);node->tabl
e=table;inserted=hash_get(node->table->hash,node,hash_alloc_intern);assert(inser
ted==node);returnnode;}/*Freeroutenode.*/staticvoidroute_node_free(structroute_t
able*table,structroute_node*node){if(table->cleanup)table->cleanup(table,node);t
able->delegate->destroy_node(table->delegate,table,node);}/*Freeroutetable.*/sta
ticvoidroute_table_free(structroute_table*rt){structroute_node*tmp_node;structro
ute_node*node;if(rt==NULL)return;hash_clean(rt->hash,NULL);hash_free(rt->hash);n
ode=rt->top;/*Bulkdeletionofnodesremaininginthistable.Thisfunctionisnotcalledunt
ilworkershavecompletedtheirdependencyonthistable.Afinalroute_unlock_node()willno
tbecalledforthesenodes.*/while(node){if(node->l_left){node=node->l_left;continue
;}if(node->l_right){node=node->l_right;continue;}tmp_node=node;node=node->parent
;tmp_node->table->count--;tmp_node->lock=0;/*tocauseassertifunlockedafterthis*/r
oute_node_free(rt,tmp_node);if(node!=NULL){if(node->l_left==tmp_node)node->l_lef
t=NULL;elsenode->l_right=NULL;}else{break;}}assert(rt->count==0);XFREE(MTYPE_ROU
TE_TABLE,rt);return;}/*Utilitymaskarray.*/staticconstuint8_tmaskbit[]={0x00,0x80
,0xc0,0xe0,0xf0,0xf8,0xfc,0xfe,0xff};/*Commonprefixroutegenaration.*/staticvoidr
oute_common(conststructprefix*n,conststructprefix*p,structprefix*new){inti;uint8
_tdiff;uint8_tmask;constuint8_t*np;constuint8_t*pp;uint8_t*newp;if(n->family==AF
_FLOWSPEC)returnprefix_copy(new,p);np=(constuint8_t*)&n->u.prefix;pp=(constuint8
_t*)&p->u.prefix;newp=(uint8_t*)&new->u.prefix;for(i=0;i<p->prefixlen/8;i++){if(
np[i]==pp[i])newp[i]=np[i];elsebreak;}new->prefixlen=i*8;if(new->prefixlen!=p->p
refixlen){diff=np[i]^pp[i];mask=0x80;while(new->prefixlen<p->prefixlen&&!(mask&d
iff)){mask>>=1;new->prefixlen++;}newp[i]=np[i]&maskbit[new->prefixlen%8];}}stati
cvoidset_link(structroute_node*node,structroute_node*new){unsignedintbit=prefix_
bit(&new->p.u.prefix,node->p.prefixlen);node->link[bit]=new;new->parent=node;}/*
Findmatchedprefix.*/structroute_node*route_node_match(conststructroute_table*tab
le,unionprefixconstptrpu){conststructprefix*p=pu.p;structroute_node*node;structr
oute_node*matched;matched=NULL;node=table->top;/*Walkdowntree.Ifthereismatchedro
utethenstoreittomatched.*/while(node&&node->p.prefixlen<=p->prefixlen&&prefix_ma
tch(&node->p,p)){if(node->info)matched=node;if(node->p.prefixlen==p->prefixlen)b
reak;node=node->link[prefix_bit(&p->u.prefix,node->p.prefixlen)];}/*Ifmatchedrou
tefound,returnit.*/if(matched)returnroute_lock_node(matched);returnNULL;}structr
oute_node*route_node_match_ipv4(conststructroute_table*table,conststructin_addr*
addr){structprefix_ipv4p;memset(&p,0,sizeof(structprefix_ipv4));p.family=AF_INET
;p.prefixlen=IPV4_MAX_PREFIXLEN;p.prefix=*addr;returnroute_node_match(table,(str
uctprefix*)&p);}structroute_node*route_node_match_ipv6(conststructroute_table*ta
ble,conststructin6_addr*addr){structprefix_ipv6p;memset(&p,0,sizeof(structprefix
_ipv6));p.family=AF_INET6;p.prefixlen=IPV6_MAX_PREFIXLEN;p.prefix=*addr;returnro
ute_node_match(table,(structprefix*)&p);}/*Lookupsameprefixnode.ReturnNULLwhenwe
can'tfindroute.*/structroute_node*route_node_lookup(conststructroute_table*table
,unionprefixconstptrpu){structprefixp;structroute_node*node;prefix_copy(&p,pu.p)
;apply_mask(&p);node=hash_get(table->hash,(void*)&p,NULL);return(node&&node->inf
o)?route_lock_node(node):NULL;}/*Lookupsameprefixnode.ReturnNULLwhenwecan'tfindr
oute.*/structroute_node*route_node_lookup_maynull(conststructroute_table*table,u
nionprefixconstptrpu){structprefixp;structroute_node*node;prefix_copy(&p,pu.p);a
pply_mask(&p);node=hash_get(table->hash,(void*)&p,NULL);returnnode?route_lock_no
de(node):NULL;}/*Addnodetoroutingtable.*/structroute_node*route_node_get(structr
oute_table*consttable,unionprefixconstptrpu){conststructprefix*p=pu.p;structrout
e_node*new;structroute_node*node;structroute_node*match;structroute_node*inserte
d;uint8_tprefixlen=p->prefixlen;constuint8_t*prefix=&p->u.prefix;apply_mask((str
uctprefix*)p);node=hash_get(table->hash,(void*)p,NULL);if(node&&node->info)retur
nroute_lock_node(node);match=NULL;node=table->top;while(node&&node->p.prefixlen<
=prefixlen&&prefix_match(&node->p,p)){if(node->p.prefixlen==prefixlen)returnrout
e_lock_node(node);match=node;node=node->link[prefix_bit(prefix,node->p.prefixlen
)];}if(node==NULL){new=route_node_set(table,p);if(match)set_link(match,new);else
table->top=new;}else{new=route_node_new(table);route_common(&node->p,p,&new->p);
new->p.family=p->family;new->table=table;set_link(new,node);inserted=hash_get(no
de->table->hash,new,hash_alloc_intern);assert(inserted==new);if(match)set_link(m
atch,new);elsetable->top=new;if(new->p.prefixlen!=p->prefixlen){match=new;new=ro
ute_node_set(table,p);set_link(match,new);table->count++;}}table->count++;route_
lock_node(new);returnnew;}/*Deletenodefromtheroutingtable.*/voidroute_node_delet
e(structroute_node*node){structroute_node*child;structroute_node*parent;assert(n
ode->lock==0);assert(node->info==NULL);if(node->l_left&&node->l_right)return;if(
node->l_left)child=node->l_left;elsechild=node->l_right;parent=node->parent;if(c
hild)child->parent=parent;if(parent){if(parent->l_left==node)parent->l_left=chil
d;elseparent->l_right=child;}elsenode->table->top=child;node->table->count--;has
h_release(node->table->hash,node);/*WARNING:FRAGILECODE!*route_node_freemayhavet
hesideeffectoffree'ingtheentire*table.*thisispermittedonlyiftable->countgotdecre
mentedtozeroabove,*becauseinthatcaseparentwillalsobeNULL,sothatwewon'ttry*to*del
eteanow-staleparentbelow.**cf.srcdest_srcnode_destroy()inzebra/zebra_rib.c*/rout
e_node_free(node->table,node);/*Ifparentnodeisstubthendeleteitalso.*/if(parent&&
parent->lock==0)route_node_delete(parent);}/*Getfistnodeandlockit.Thisfunctionis
usefulwhenonewanttolookupallthenodeexistintheroutingtable.*/structroute_node*rou
te_top(structroute_table*table){/*IfthereisnonodeintheroutingtablereturnNULL.*/i
f(table->top==NULL)returnNULL;/*Lockthetopnodeandreturnit.*/route_lock_node(tabl
e->top);returntable->top;}/*Unlockcurrentnodeandlocknextnodethenreturnit.*/struc
troute_node*route_next(structroute_node*node){structroute_node*next;structroute_
node*start;/*Nodemaybedeletedfromroute_unlock_nodesowehavetopreservenextnode'spo
inter.*/if(node->l_left){next=node->l_left;route_lock_node(next);route_unlock_no
de(node);returnnext;}if(node->l_right){next=node->l_right;route_lock_node(next);
route_unlock_node(node);returnnext;}start=node;while(node->parent){if(node->pare
nt->l_left==node&&node->parent->l_right){next=node->parent->l_right;route_lock_n
ode(next);route_unlock_node(start);returnnext;}node=node->parent;}route_unlock_n
ode(start);returnNULL;}/*Unlockcurrentnodeandlocknextnodeuntillimit.*/structrout
e_node*route_next_until(structroute_node*node,conststructroute_node*limit){struc
troute_node*next;structroute_node*start;/*Nodemaybedeletedfromroute_unlock_nodes
owehavetopreservenextnode'spointer.*/if(node->l_left){next=node->l_left;route_lo
ck_node(next);route_unlock_node(node);returnnext;}if(node->l_right){next=node->l
_right;route_lock_node(next);route_unlock_node(node);returnnext;}start=node;whil
e(node->parent&&node!=limit){if(node->parent->l_left==node&&node->parent->l_righ
t){next=node->parent->l_right;route_lock_node(next);route_unlock_node(start);ret
urnnext;}node=node->parent;}route_unlock_node(start);returnNULL;}unsignedlongrou
te_table_count(conststructroute_table*table){returntable->count;}/***route_node_
create**Defaultfunctionforcreatingaroutenode.*/structroute_node*route_node_creat
e(route_table_delegate_t*delegate,structroute_table*table){structroute_node*node
;node=XCALLOC(MTYPE_ROUTE_NODE,sizeof(structroute_node));returnnode;}/***route_n
ode_destroy**Defaultfunctionfordestroyingaroutenode.*/voidroute_node_destroy(rou
te_table_delegate_t*delegate,structroute_table*table,structroute_node*node){XFRE
E(MTYPE_ROUTE_NODE,node);}/**Defaultdelegate.*/staticroute_table_delegate_tdefau
lt_delegate={.create_node=route_node_create,.destroy_node=route_node_destroy};ro
ute_table_delegate_t*route_table_get_default_delegate(void){return&default_deleg
ate;}/**route_table_init*/structroute_table*route_table_init(void){returnroute_t
able_init_with_delegate(&default_delegate);}/***route_table_prefix_iter_cmp**Com
paretwoprefixesaccordingtotheorderinwhichtheyappearin*aniterationoveratree.**@re
turn-1ifp1occursbeforep2(p1<p2)*0iftheprefixesareidentical(p1==p2)*+1ifp1occursa
fterp2(p1>p2)*/introute_table_prefix_iter_cmp(conststructprefix*p1,conststructpr
efix*p2){structprefixcommon_space;structprefix*common=&common_space;if(p1->prefi
xlen<=p2->prefixlen){if(prefix_match(p1,p2)){/**p1containsp2,orisequaltoit.*/ret
urn(p1->prefixlen==p2->prefixlen)?0:-1;}}else{/**Checkifp2containsp1.*/if(prefix
_match(p2,p1))return1;}route_common(p1,p2,common);assert(common->prefixlen<p1->p
refixlen);assert(common->prefixlen<p2->prefixlen);/**Bothprefixesarelongerthanth
ecommonprefix.**Weneedtocheckthebitafterthecommonprefixlentodetermine*whichoneco
meslater.*/if(prefix_bit(&p1->u.prefix,common->prefixlen)){/**Webranchtotheright
togettop1fromthecommonprefix.*/assert(!prefix_bit(&p2->u.prefix,common->prefixle
n));return1;}/**Webranchtotherighttogettop2fromthecommonprefix.*/assert(prefix_b
it(&p2->u.prefix,common->prefixlen));return-1;}/**route_get_subtree_next**Helper
functionthatreturnsthefirstnodethatfollowsthenodes*inthesub-treeunder'node'inite
rationorder.*/staticstructroute_node*route_get_subtree_next(structroute_node*nod
e){while(node->parent){if(node->parent->l_left==node&&node->parent->l_right)retu
rnnode->parent->l_right;node=node->parent;}returnNULL;}/***route_table_get_next_
internal**Helperfunctiontofindthenodethatoccursafterthegivenprefixin*orderofiter
ation.**@seeroute_table_get_next*/staticstructroute_node*route_table_get_next_in
ternal(conststructroute_table*table,conststructprefix*p){structroute_node*node,*
tmp_node;intcmp;node=table->top;while(node){intmatch;if(node->p.prefixlen<p->pre
fixlen)match=prefix_match(&node->p,p);elsematch=prefix_match(p,&node->p);if(matc
h){if(node->p.prefixlen==p->prefixlen){/**Theprefixpexistsinthetree,justreturn*t
henext*node.*/route_lock_node(node);node=route_next(node);if(node)route_unlock_n
ode(node);return(node);}if(node->p.prefixlen>p->prefixlen){/**Nodeisinthesubtree
ofp,andhence*greaterthanp.*/returnnode;}/**pisinthesub-treeundernode.*/tmp_node=
node->link[prefix_bit(&p->u.prefix,node->p.prefixlen)];if(tmp_node){node=tmp_nod
e;continue;}/**Therearenonodesinthedirectionwherepshould*be.If*nodehasarightchil
d,thenitmustbegreaterthan*p.*/if(node->l_right)returnnode->l_right;/**Nomorechil
drentofollow,goupwardslookingfor*thenext*node.*/returnroute_get_subtree_next(nod
e);}/**Neithernodeprefixnor'p'containstheother.*/cmp=route_table_prefix_iter_cmp
(&node->p,p);if(cmp>0){/**Nodefollowspiniterationorder.Returnit.*/returnnode;}as
sert(cmp<0);/**Nodeandthesubtreeunderitcomebeforeprefixpin*iterationorder.Prefix
panditssub-treearenotpresentin*thetree.Goupwardsandfindthefirstnodethatfollowsth
e*subtree.Thatnodewillalsosucceedp.*/returnroute_get_subtree_next(node);}returnN
ULL;}/***route_table_get_next**Findthenodethatoccursafterthegivenprefixinorderof
*iteration.*/structroute_node*route_table_get_next(conststructroute_table*table,
unionprefixconstptrpu){conststructprefix*p=pu.p;structroute_node*node;node=route
_table_get_next_internal(table,p);if(node){assert(route_table_prefix_iter_cmp(&n
ode->p,p)>0);route_lock_node(node);}returnnode;}/**route_table_iter_init*/voidro
ute_table_iter_init(route_table_iter_t*iter,structroute_table*table){memset(iter
,0,sizeof(*iter));iter->state=RT_ITER_STATE_INIT;iter->table=table;}/**route_tab
le_iter_pause**Pauseaniterationoverthetable.Thisallowstheiterationtobe*resumedpo
intafterarbitraryadditions/deletionsfromthetable.*Aniterationcanberesumedbyjustc
allingroute_table_iter_next()*ontheiterator.*/voidroute_table_iter_pause(route_t
able_iter_t*iter){switch(iter->state){caseRT_ITER_STATE_INIT:caseRT_ITER_STATE_P
AUSED:caseRT_ITER_STATE_DONE:return;caseRT_ITER_STATE_ITERATING:/**Savetheprefix
thatwearecurrentlyat.Thenextcallto*route_table_iter_next()willreturnthenodeafter
this*prefix*inthetree.*/prefix_copy(&iter->pause_prefix,&iter->current->p);route
_unlock_node(iter->current);iter->current=NULL;iter->state=RT_ITER_STATE_PAUSED;
return;default:assert(0);}}/**route_table_iter_cleanup**Releaseanyresourcesheldb
ytheiterator.*/voidroute_table_iter_cleanup(route_table_iter_t*iter){if(iter->st
ate==RT_ITER_STATE_ITERATING){route_unlock_node(iter->current);iter->current=NUL
L;}assert(!iter->current);/**SetthestatetoRT_ITER_STATE_DONEtomakeany*route_tabl
e_iter_next()callsonthisiteratorreturnNULL.*/iter->state=RT_ITER_STATE_DONE;}