/**Genericvectorinterfaceheader.*Copyright(C)1997,98KunihiroIshiguro**Thisfileis
partofGNUZebra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodifyit*under
thetermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eith
erversion2,or(atyouroption)any*laterversion.**GNUZebraisdistributedinthehopethat
itwillbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTAB
ILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails
.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;s
eethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,Fifth
Floor,Boston,MA02110-1301USA*/#ifndef_ZEBRA_VECTOR_H#define_ZEBRA_VECTOR_H#inclu
de"memory.h"/*structforvector*/struct_vector{unsignedintactive;/*numberofactives
lots*/unsignedintalloced;/*numberofallocatedslot*/void**index;/*indextodata*/};t
ypedefstruct_vector*vector;#defineVECTOR_MIN_SIZE1/*(Sometimes)usefullmacros.Thi
smacroconvertindexexpressiontoarrayexpression.*//*Referenceslotatgivenindex,call
ermustensureslotisactive*/#definevector_slot(V,I)((V)->index[(I)])/*Numberofacti
veslots.*Notethatthisdiffersfromvector_count()asitthecountreturned*willincludean
yemptyslots*/#definevector_active(V)((V)->active)/*Prototypes.*/externvectorvect
or_init(unsignedintsize);externvoidvector_ensure(vectorv,unsignedintnum);externi
ntvector_empty_slot(vectorv);externintvector_set(vectorv,void*val);externintvect
or_set_index(vectorv,unsignedinti,void*val);externvoidvector_unset(vectorv,unsig
nedinti);externvoidvector_unset_value(vectorv,void*val);externunsignedintvector_
count(vectorv);externvoidvector_free(vectorv);externvectorvector_copy(vectorv);e
xternvoid*vector_lookup(vector,unsignedint);externvoid*vector_lookup_ensure(vect
or,unsignedint);#endif/*_ZEBRA_VECTOR_H*/