/**VRFfunctions.*Copyright(C)20146WINDS.A.**ThisfileispartofGNUZebra.**GNUZebrai
sfreesoftware;youcanredistributeitand/ormodify*itunderthetermsoftheGNUGeneralPub
licLicenseaspublished*bytheFreeSoftwareFoundation;eitherversion2,or(atyour*optio
n)anylaterversion.**GNUZebraisdistributedinthehopethatitwillbeuseful,but*WITHOUT
ANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTICUL
ARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldhavereceivedac
opyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;ifnot,wri
tetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-1301U
SA*/#include<zebra.h>/*forbasename*/#include<libgen.h>#include"if.h"#include"vrf
.h"#include"vrf_int.h"#include"prefix.h"#include"table.h"#include"log.h"#include
"memory.h"#include"command.h"#include"ns.h"#include"privs.h"/*defaultVRFIDvalueu
sedwhenVRFbackendisnotNETNS*/#defineVRF_DEFAULT_INTERNAL0DEFINE_MTYPE_STATIC(LIB
,VRF,"VRF")DEFINE_MTYPE_STATIC(LIB,VRF_BITMAP,"VRFbit-map")DEFINE_QOBJ_TYPE(vrf)
static__inlineintvrf_id_compare(conststructvrf*,conststructvrf*);static__inlinei
ntvrf_name_compare(conststructvrf*,conststructvrf*);RB_GENERATE(vrf_id_head,vrf,
id_entry,vrf_id_compare);RB_GENERATE(vrf_name_head,vrf,name_entry,vrf_name_compa
re);structvrf_id_headvrfs_by_id=RB_INITIALIZER(&vrfs_by_id);structvrf_name_headv
rfs_by_name=RB_INITIALIZER(&vrfs_by_name);staticintvrf_backend;staticstructzebra
_privs_t*vrf_daemon_privs;/**Turnon/offdebugcode*forvrf.*/intdebug_vrf=0;/*Holdi
ngVRFhooks*/structvrf_master{int(*vrf_new_hook)(structvrf*);int(*vrf_delete_hook
)(structvrf*);int(*vrf_enable_hook)(structvrf*);int(*vrf_disable_hook)(structvrf
*);}vrf_master={0,};staticintvrf_is_enabled(structvrf*vrf);/*VRFlistexistanceche
ckbyname.*/structvrf*vrf_lookup_by_name(constchar*name){structvrfvrf;strlcpy(vrf
.name,name,sizeof(vrf.name));return(RB_FIND(vrf_name_head,&vrfs_by_name,&vrf));}
static__inlineintvrf_id_compare(conststructvrf*a,conststructvrf*b){return(a->vrf
_id-b->vrf_id);}staticintvrf_name_compare(conststructvrf*a,conststructvrf*b){ret
urnstrcmp(a->name,b->name);}/*ifns_idisdifferentandnotVRF_UNKNOWN,*thenupdatevrf
identifier,andenableVRF*/staticvoidvrf_update_vrf_id(ns_id_tns_id,void*opaqueptr
){ns_id_tvrf_id=(vrf_id_t)ns_id;vrf_id_told_vrf_id;structvrf*vrf=(structvrf*)opa
queptr;if(!vrf)return;old_vrf_id=vrf->vrf_id;if(vrf_id==vrf->vrf_id)return;if(vr
f->vrf_id!=VRF_UNKNOWN)RB_REMOVE(vrf_id_head,&vrfs_by_id,vrf);vrf->vrf_id=vrf_id
;RB_INSERT(vrf_id_head,&vrfs_by_id,vrf);if(old_vrf_id==VRF_UNKNOWN)vrf_enable((s
tructvrf*)vrf);}intvrf_switch_to_netns(vrf_id_tvrf_id){char*name;structvrf*vrf=v
rf_lookup_by_id(vrf_id);/*VRFisdefaultVRF.silentlyignore*/if(!vrf||vrf->vrf_id==
VRF_DEFAULT)return0;/*VRFhasnoNETNSbackend.silentlyignore*/if(vrf->data.l.netns_
name[0]=='\0')return0;name=ns_netns_pathname(NULL,vrf->data.l.netns_name);if(deb
ug_vrf)zlog_debug("VRF_SWITCH:%s(%u)",name,vrf->vrf_id);returnns_switch_to_netns
(name);}intvrf_switchback_to_initial(void){intret=ns_switchback_to_initial();if(
ret==0&&debug_vrf)zlog_debug("VRF_SWITCHBACK");returnret;}/*GetaVRF.Ifnotfound,c
reateone.*Arg:*name-Thenameofthevrf.MaybeNULLifunknown.*vrf_id-Thevrf_idofthevrf
.MaybeVRF_UNKNOWNifunknown*Description:Pleasenotethatthisroutinecanbecalledwithj
ustthename*and0vrf-id*/structvrf*vrf_get(vrf_id_tvrf_id,constchar*name){structvr
f*vrf=NULL;intnew=0;if(debug_vrf)zlog_debug("VRF_GET:%s(%u)",name==NULL?"(NULL)"
:name,vrf_id);/*Nothingtosee,movealonghere*/if(!name&&vrf_id==VRF_UNKNOWN)return
NULL;/*TrytofindVRFbothbyIDandname*/if(vrf_id!=VRF_UNKNOWN)vrf=vrf_lookup_by_id(
vrf_id);if(!vrf&&name)vrf=vrf_lookup_by_name(name);if(vrf==NULL){vrf=XCALLOC(MTY
PE_VRF,sizeof(structvrf));vrf->vrf_id=VRF_UNKNOWN;QOBJ_REG(vrf,vrf);new=1;if(deb
ug_vrf)zlog_debug("VRF(%u)%siscreated.",vrf_id,(name)?name:"(NULL)");}/*Setident
ifier*/if(vrf_id!=VRF_UNKNOWN&&vrf->vrf_id==VRF_UNKNOWN){vrf->vrf_id=vrf_id;RB_I
NSERT(vrf_id_head,&vrfs_by_id,vrf);}/*Setname*/if(name&&vrf->name[0]!='\0'&&strc
mp(name,vrf->name)){RB_REMOVE(vrf_name_head,&vrfs_by_name,vrf);strlcpy(vrf->name
,name,sizeof(vrf->name));RB_INSERT(vrf_name_head,&vrfs_by_name,vrf);}elseif(name
&&vrf->name[0]=='\0'){strlcpy(vrf->name,name,sizeof(vrf->name));RB_INSERT(vrf_na
me_head,&vrfs_by_name,vrf);}if(new&&vrf_master.vrf_new_hook)(*vrf_master.vrf_new
_hook)(vrf);returnvrf;}/*DeleteaVRF.ThisiscalledwhentheunderlyingVRFgoesaway,a*p
re-configuredVRFisdeletedorwhenshuttingdown(vrf_terminate()).*/voidvrf_delete(st
ructvrf*vrf){if(debug_vrf)zlog_debug("VRF%uistobedeleted.",vrf->vrf_id);if(vrf_i
s_enabled(vrf))vrf_disable(vrf);/*IftheVRFisuserconfigured,it'llstickaround,just
remove*theIDmapping.InterfacesassignedtothisVRFshould'vebeen*removedalreadyaspar
toftheVRFgoingdown.*/if(vrf_is_user_cfged(vrf)){if(vrf->vrf_id!=VRF_UNKNOWN){/*D
eleteanyVRFinterfaces-shouldbeonly*theVRFitself,otherinterfacesshould've*beenmov
edoutoftheVRF.*/if_terminate(vrf);RB_REMOVE(vrf_id_head,&vrfs_by_id,vrf);vrf->vr
f_id=VRF_UNKNOWN;}return;}if(vrf_master.vrf_delete_hook)(*vrf_master.vrf_delete_
hook)(vrf);QOBJ_UNREG(vrf);if_terminate(vrf);if(vrf->vrf_id!=VRF_UNKNOWN)RB_REMO
VE(vrf_id_head,&vrfs_by_id,vrf);if(vrf->name[0]!='\0')RB_REMOVE(vrf_name_head,&v
rfs_by_name,vrf);XFREE(MTYPE_VRF,vrf);}/*LookupaVRFbyidentifier.*/structvrf*vrf_
lookup_by_id(vrf_id_tvrf_id){structvrfvrf;vrf.vrf_id=vrf_id;return(RB_FIND(vrf_i
d_head,&vrfs_by_id,&vrf));}/**EnableaVRF-thatis,lettheVRFbereadytouse.*TheVRF_EN
ABLE_HOOKcallbackwillbecalledtoinform*thattheycanallocateresourcesinthisVRF.**RE
TURN:1-enabledsuccessfully;otherwise,0.*/intvrf_enable(structvrf*vrf){if(vrf_is_
enabled(vrf))return1;if(debug_vrf)zlog_debug("VRF%uisenabled.",vrf->vrf_id);SET_
FLAG(vrf->status,VRF_ACTIVE);if(vrf_master.vrf_enable_hook)(*vrf_master.vrf_enab
le_hook)(vrf);return1;}/**DisableaVRF-thatis,lettheVRFbeunusable.*TheVRF_DELETE_
HOOKcallbackwillbecalledtoinform*thattheymustreleasetheresourcesintheVRF.*/voidv
rf_disable(structvrf*vrf){if(!vrf_is_enabled(vrf))return;UNSET_FLAG(vrf->status,
VRF_ACTIVE);if(debug_vrf)zlog_debug("VRF%uistobedisabled.",vrf->vrf_id);/*Tillno
w,nothingtobedoneforthedefaultVRF.*///Pending:seewhythisstatement.if(vrf_master.
vrf_disable_hook)(*vrf_master.vrf_disable_hook)(vrf);}constchar*vrf_id_to_name(v
rf_id_tvrf_id){structvrf*vrf;vrf=vrf_lookup_by_id(vrf_id);if(vrf)returnvrf->name
;return"n/a";}vrf_id_tvrf_name_to_id(constchar*name){structvrf*vrf;vrf_id_tvrf_i
d=VRF_DEFAULT;//Pending:needawaytoreturninvalid//id/routinenotused.vrf=vrf_looku
p_by_name(name);if(vrf)vrf_id=vrf->vrf_id;returnvrf_id;}/*Getthedatapointerofthe
specifiedVRF.Ifnotfound,createone.*/void*vrf_info_get(vrf_id_tvrf_id){structvrf*
vrf=vrf_get(vrf_id,NULL);returnvrf->info;}/*LookupthedatapointerofthespecifiedVR
F.*/void*vrf_info_lookup(vrf_id_tvrf_id){structvrf*vrf=vrf_lookup_by_id(vrf_id);
returnvrf?vrf->info:NULL;}/**VRFbit-map*/#defineVRF_BITMAP_NUM_OF_GROUPS1024#def
ineVRF_BITMAP_NUM_OF_BITS_IN_GROUP(UINT32_MAX/VRF_BITMAP_NUM_OF_GROUPS)#defineVR
F_BITMAP_NUM_OF_BYTES_IN_GROUP\(VRF_BITMAP_NUM_OF_BITS_IN_GROUP/CHAR_BIT+1)/*+1f
orensure*/#defineVRF_BITMAP_GROUP(_id)((_id)/VRF_BITMAP_NUM_OF_BITS_IN_GROUP)#de
fineVRF_BITMAP_BIT_OFFSET(_id)((_id)%VRF_BITMAP_NUM_OF_BITS_IN_GROUP)#defineVRF_
BITMAP_INDEX_IN_GROUP(_bit_offset)((_bit_offset)/CHAR_BIT)#defineVRF_BITMAP_FLAG
(_bit_offset)\(((uint8_t)1)<<((_bit_offset)%CHAR_BIT))structvrf_bitmap{uint8_t*g
roups[VRF_BITMAP_NUM_OF_GROUPS];};vrf_bitmap_tvrf_bitmap_init(void){return(vrf_b
itmap_t)XCALLOC(MTYPE_VRF_BITMAP,sizeof(structvrf_bitmap));}voidvrf_bitmap_free(
vrf_bitmap_tbmap){structvrf_bitmap*bm=(structvrf_bitmap*)bmap;inti;if(bmap==VRF_
BITMAP_NULL)return;for(i=0;i<VRF_BITMAP_NUM_OF_GROUPS;i++)if(bm->groups[i])XFREE
(MTYPE_VRF_BITMAP,bm->groups[i]);XFREE(MTYPE_VRF_BITMAP,bm);}voidvrf_bitmap_set(
vrf_bitmap_tbmap,vrf_id_tvrf_id){structvrf_bitmap*bm=(structvrf_bitmap*)bmap;uin
t8_tgroup=VRF_BITMAP_GROUP(vrf_id);uint8_toffset=VRF_BITMAP_BIT_OFFSET(vrf_id);i
f(bmap==VRF_BITMAP_NULL||vrf_id==VRF_UNKNOWN)return;if(bm->groups[group]==NULL)b
m->groups[group]=XCALLOC(MTYPE_VRF_BITMAP,VRF_BITMAP_NUM_OF_BYTES_IN_GROUP);SET_
FLAG(bm->groups[group][VRF_BITMAP_INDEX_IN_GROUP(offset)],VRF_BITMAP_FLAG(offset
));}voidvrf_bitmap_unset(vrf_bitmap_tbmap,vrf_id_tvrf_id){structvrf_bitmap*bm=(s
tructvrf_bitmap*)bmap;uint8_tgroup=VRF_BITMAP_GROUP(vrf_id);uint8_toffset=VRF_BI
TMAP_BIT_OFFSET(vrf_id);if(bmap==VRF_BITMAP_NULL||vrf_id==VRF_UNKNOWN||bm->group
s[group]==NULL)return;UNSET_FLAG(bm->groups[group][VRF_BITMAP_INDEX_IN_GROUP(off
set)],VRF_BITMAP_FLAG(offset));}intvrf_bitmap_check(vrf_bitmap_tbmap,vrf_id_tvrf
_id){structvrf_bitmap*bm=(structvrf_bitmap*)bmap;uint8_tgroup=VRF_BITMAP_GROUP(v
rf_id);uint8_toffset=VRF_BITMAP_BIT_OFFSET(vrf_id);if(bmap==VRF_BITMAP_NULL||vrf
_id==VRF_UNKNOWN||bm->groups[group]==NULL)return0;returnCHECK_FLAG(bm->groups[gr
oup][VRF_BITMAP_INDEX_IN_GROUP(offset)],VRF_BITMAP_FLAG(offset))?1:0;}staticvoid
vrf_autocomplete(vectorcomps,structcmd_token*token){structvrf*vrf=NULL;RB_FOREAC
H(vrf,vrf_name_head,&vrfs_by_name){if(vrf->vrf_id!=VRF_DEFAULT)vector_set(comps,
XSTRDUP(MTYPE_COMPLETION,vrf->name));}}staticconststructcmd_variable_handlervrf_
var_handlers[]={{.varname="vrf",.completions=vrf_autocomplete,},{.completions=NU
LL},};/*InitializeVRFmodule.*/voidvrf_init(int(*create)(structvrf*),int(*enable)
(structvrf*),int(*disable)(structvrf*),int(*delete)(structvrf*)){structvrf*defau
lt_vrf;/*initialiseNS,incaseVRFbackendifNETNS*/ns_init();if(debug_vrf)zlog_debug
("%s:InitializingVRFsubsystem",__PRETTY_FUNCTION__);vrf_master.vrf_new_hook=crea
te;vrf_master.vrf_enable_hook=enable;vrf_master.vrf_disable_hook=disable;vrf_mas
ter.vrf_delete_hook=delete;/*ThedefaultVRFalwaysexists.*/default_vrf=vrf_get(VRF
_DEFAULT,VRF_DEFAULT_NAME);if(!default_vrf){zlog_err("vrf_init:failedtocreatethe
defaultVRF!");exit(1);}/*EnablethedefaultVRF.*/if(!vrf_enable(default_vrf)){zlog
_err("vrf_init:failedtoenablethedefaultVRF!");exit(1);}cmd_variable_handler_regi
ster(vrf_var_handlers);}/*TerminateVRFmodule.*/voidvrf_terminate(void){structvrf
*vrf;if(debug_vrf)zlog_debug("%s:Shuttingdownvrfsubsystem",__PRETTY_FUNCTION__);
while(!RB_EMPTY(vrf_id_head,&vrfs_by_id)){vrf=RB_ROOT(vrf_id_head,&vrfs_by_id);/
*Clearconfiguredflagandinvokedelete.*/UNSET_FLAG(vrf->status,VRF_CONFIGURED);vrf
_delete(vrf);}while(!RB_EMPTY(vrf_name_head,&vrfs_by_name)){vrf=RB_ROOT(vrf_name
_head,&vrfs_by_name);/*Clearconfiguredflagandinvokedelete.*/UNSET_FLAG(vrf->stat
us,VRF_CONFIGURED);vrf_delete(vrf);}}/*CreateasocketfortheVRF.*/intvrf_socket(in
tdomain,inttype,intprotocol,vrf_id_tvrf_id,char*interfacename){intret,save_errno
,ret2;ret=vrf_switch_to_netns(vrf_id);if(ret<0)zlog_err("%s:Can'tswitchtoVRF%u(%
s)",__func__,vrf_id,safe_strerror(errno));ret=socket(domain,type,protocol);save_
errno=errno;ret2=vrf_switchback_to_initial();if(ret2<0)zlog_err("%s:Can'tswitchb
ackfromVRF%u(%s)",__func__,vrf_id,safe_strerror(errno));errno=save_errno;if(ret<
=0)returnret;ret2=vrf_bind(vrf_id,ret,interfacename);if(ret2<0){close(ret);ret=r
et2;}returnret;}intvrf_is_backend_netns(void){return(vrf_backend==VRF_BACKEND_NE
TNS);}intvrf_get_backend(void){returnvrf_backend;}voidvrf_configure_backend(intv
rf_backend_netns){vrf_backend=vrf_backend_netns;}intvrf_handler_create(structvty
*vty,constchar*vrfname,structvrf**vrf){structvrf*vrfp;if(strlen(vrfname)>VRF_NAM
SIZ){if(vty)vty_out(vty,"%%VRFname%sinvalid:lengthexceeds%dbytes\n",vrfname,VRF_
NAMSIZ);elsezlog_warn("%%VRFname%sinvalid:lengthexceeds%dbytes\n",vrfname,VRF_NA
MSIZ);returnCMD_WARNING_CONFIG_FAILED;}vrfp=vrf_get(VRF_UNKNOWN,vrfname);if(vty)
VTY_PUSH_CONTEXT(VRF_NODE,vrfp);if(vrf)*vrf=vrfp;returnCMD_SUCCESS;}intvrf_netns
_handler_create(structvty*vty,structvrf*vrf,char*pathname,ns_id_tns_id){structns
*ns=NULL;if(!vrf)returnCMD_WARNING_CONFIG_FAILED;if(vrf->vrf_id!=VRF_UNKNOWN&&vr
f->ns_ctxt==NULL){if(vty)vty_out(vty,"VRF%uisalreadyconfiguredwithVRF%s\n",vrf->
vrf_id,vrf->name);elsezlog_warn("VRF%uisalreadyconfiguredwithVRF%s\n",vrf->vrf_i
d,vrf->name);returnCMD_WARNING_CONFIG_FAILED;}if(vrf->ns_ctxt!=NULL){ns=(structn
s*)vrf->ns_ctxt;if(ns&&0!=strcmp(ns->name,pathname)){if(vty)vty_out(vty,"VRF%ual
readyconfiguredwithNETNS%s\n",vrf->vrf_id,ns->name);elsezlog_warn("VRF%ualreadyc
onfiguredwithNETNS%s",vrf->vrf_id,ns->name);returnCMD_WARNING_CONFIG_FAILED;}}ns
=ns_lookup_name(pathname);if(ns&&ns->vrf_ctxt){structvrf*vrf2=(structvrf*)ns->vr
f_ctxt;if(vrf2==vrf)returnCMD_SUCCESS;if(vty)vty_out(vty,"NS%sisalreadyconfigure
d""withVRF%u(%s)\n",ns->name,vrf2->vrf_id,vrf2->name);elsezlog_warn("NS%sisalrea
dyconfiguredwithVRF%u(%s)",ns->name,vrf2->vrf_id,vrf2->name);returnCMD_WARNING_C
ONFIG_FAILED;}ns=ns_get_created(ns,pathname,ns_id);ns->vrf_ctxt=(void*)vrf;vrf->
ns_ctxt=(void*)ns;/*updateVRFnetnsNAME*/if(vrf)strlcpy(vrf->data.l.netns_name,ba
sename(pathname),NS_NAMSIZ);if(!ns_enable(ns,vrf_update_vrf_id)){if(vty)vty_out(
vty,"CannotassociateNS%uwithNETNS%s\n",ns->ns_id,ns->name);elsezlog_warn("Cannot
associateNS%uwithNETNS%s",ns->ns_id,ns->name);returnCMD_WARNING_CONFIG_FAILED;}r
eturnCMD_SUCCESS;}intvrf_is_mapped_on_netns(vrf_id_tvrf_id){structvrf*vrf=vrf_lo
okup_by_id(vrf_id);if(!vrf||vrf->data.l.netns_name[0]=='\0')return0;if(vrf->vrf_
id==VRF_DEFAULT)return0;return1;}/*vrfCLIcommands*/DEFUN_NOSH(vrf,vrf_cmd,"vrfNA
ME","SelectaVRFtoconfigure\n""VRF'sname\n"){intidx_name=1;constchar*vrfname=argv
[idx_name]->arg;returnvrf_handler_create(vty,vrfname,NULL);}DEFUN_NOSH(no_vrf,no
_vrf_cmd,"novrfNAME",NO_STR"DeleteapseudoVRF'sconfiguration\n""VRF'sname\n"){con
stchar*vrfname=argv[2]->arg;structvrf*vrfp;vrfp=vrf_lookup_by_name(vrfname);if(v
rfp==NULL){vty_out(vty,"%%VRF%sdoesnotexist\n",vrfname);returnCMD_WARNING_CONFIG
_FAILED;}if(CHECK_FLAG(vrfp->status,VRF_ACTIVE)){vty_out(vty,"%%OnlyinactiveVRFs
canbedeleted\n");returnCMD_WARNING_CONFIG_FAILED;}/*Clearconfiguredflagandinvoke
delete.*/UNSET_FLAG(vrfp->status,VRF_CONFIGURED);vrf_delete(vrfp);returnCMD_SUCC
ESS;}structcmd_nodevrf_node={VRF_NODE,"%s(config-vrf)#",1};DEFUN_NOSH(vrf_netns,
vrf_netns_cmd,"netnsNAME","AttachVRFtoaNamespace\n""Thefilenamein"NS_RUN_DIR",or
afullpathname\n"){intidx_name=1,ret;char*pathname=ns_netns_pathname(vty,argv[idx
_name]->arg);VTY_DECLVAR_CONTEXT(vrf,vrf);if(!pathname)returnCMD_WARNING_CONFIG_
FAILED;if(vrf_daemon_privs&&vrf_daemon_privs->change(ZPRIVS_RAISE))zlog_err("%s:
Can'traiseprivileges",__func__);ret=vrf_netns_handler_create(vty,vrf,pathname,NS
_UNKNOWN);if(vrf_daemon_privs&&vrf_daemon_privs->change(ZPRIVS_LOWER))zlog_err("
%s:Can'tlowerprivileges",__func__);returnret;}DEFUN(no_vrf_netns,no_vrf_netns_cm
d,"nonetns[NAME]",NO_STR"DetachVRFfromaNamespace\n""Thefilenamein"NS_RUN_DIR",or
afullpathname\n"){structns*ns=NULL;VTY_DECLVAR_CONTEXT(vrf,vrf);if(!vrf_is_backe
nd_netns()){vty_out(vty,"VRFbackendisnotNetns.Aborting\n");returnCMD_WARNING_CON
FIG_FAILED;}if(!vrf->ns_ctxt){vty_out(vty,"VRF%s(%u)isnotconfiguredwithNetNS\n",
vrf->name,vrf->vrf_id);returnCMD_WARNING_CONFIG_FAILED;}ns=(structns*)vrf->ns_ct
xt;ns->vrf_ctxt=NULL;vrf_disable(vrf);/*vrfIDfromVRFisnecessaryforZebra*sothatpr
opagatetootherclientsisdone*/ns_delete(ns);vrf->ns_ctxt=NULL;returnCMD_SUCCESS;}
/**DebugCLIforvrf's*/DEFUN(vrf_debug,vrf_debug_cmd,"debugvrf",DEBUG_STR"VRFDebug
ging\n"){debug_vrf=1;returnCMD_SUCCESS;}DEFUN(no_vrf_debug,no_vrf_debug_cmd,"nod
ebugvrf",NO_STRDEBUG_STR"VRFDebugging\n"){debug_vrf=0;returnCMD_SUCCESS;}statici
ntvrf_write_host(structvty*vty){if(debug_vrf)vty_out(vty,"debugvrf\n");return1;}
staticstructcmd_nodevrf_debug_node={VRF_DEBUG_NODE,"",1};voidvrf_install_command
s(void){install_node(&vrf_debug_node,vrf_write_host);install_element(CONFIG_NODE
,&vrf_debug_cmd);install_element(ENABLE_NODE,&vrf_debug_cmd);install_element(CON
FIG_NODE,&no_vrf_debug_cmd);install_element(ENABLE_NODE,&no_vrf_debug_cmd);}void
vrf_cmd_init(int(*writefunc)(structvty*vty),structzebra_privs_t*daemon_privs){in
stall_element(CONFIG_NODE,&vrf_cmd);install_element(CONFIG_NODE,&no_vrf_cmd);ins
tall_node(&vrf_node,writefunc);install_default(VRF_NODE);if(vrf_is_backend_netns
()&&ns_have_netns()){/*InstallNScommands.*/vrf_daemon_privs=daemon_privs;install
_element(VRF_NODE,&vrf_netns_cmd);install_element(VRF_NODE,&no_vrf_netns_cmd);}}
vrf_id_tvrf_get_default_id(void){structvrf*vrf=vrf_lookup_by_name(VRF_DEFAULT_NA
ME);if(vrf)returnvrf->vrf_id;if(vrf_is_backend_netns())returnns_get_default_id()
;elsereturnVRF_DEFAULT_INTERNAL;}intvrf_bind(vrf_id_tvrf_id,intfd,char*name){int
ret=0;if(fd<0||name==NULL)returnfd;if(vrf_is_mapped_on_netns(vrf_id))returnfd;#i
fdefSO_BINDTODEVICEret=setsockopt(fd,SOL_SOCKET,SO_BINDTODEVICE,name,strlen(name
));if(ret<0)zlog_debug("bindtointerface%sfailed,errno=%d",name,errno);#endif/*SO
_BINDTODEVICE*/returnret;}intvrf_getaddrinfo(constchar*node,constchar*service,co
nststructaddrinfo*hints,structaddrinfo**res,vrf_id_tvrf_id){intret,ret2,save_err
no;ret=vrf_switch_to_netns(vrf_id);if(ret<0)zlog_err("%s:Can'tswitchtoVRF%u(%s)"
,__func__,vrf_id,safe_strerror(errno));ret=getaddrinfo(node,service,hints,res);s
ave_errno=errno;ret2=vrf_switchback_to_initial();if(ret2<0)zlog_err("%s:Can'tswi
tchbackfromVRF%u(%s)",__func__,vrf_id,safe_strerror(errno));errno=save_errno;ret
urnret;}intvrf_ioctl(vrf_id_tvrf_id,intd,unsignedlongrequest,char*params){intret
,saved_errno,rc;ret=vrf_switch_to_netns(vrf_id);if(ret<0){zlog_err("%s:Can'tswit
chtoVRF%u(%s)",__func__,vrf_id,safe_strerror(errno));return0;}rc=ioctl(d,request
,params);saved_errno=errno;ret=vrf_switchback_to_initial();if(ret<0)zlog_err("%s
:Can'tswitchbackfromVRF%u(%s)",__func__,vrf_id,safe_strerror(errno));errno=saved
_errno;returnrc;}intvrf_sockunion_socket(constunionsockunion*su,vrf_id_tvrf_id,c
har*interfacename){intret,save_errno,ret2;ret=vrf_switch_to_netns(vrf_id);if(ret
<0)zlog_err("%s:Can'tswitchtoVRF%u(%s)",__func__,vrf_id,safe_strerror(errno));re
t=sockunion_socket(su);save_errno=errno;ret2=vrf_switchback_to_initial();if(ret2
<0)zlog_err("%s:Can'tswitchbackfromVRF%u(%s)",__func__,vrf_id,safe_strerror(errn
o));errno=save_errno;if(ret<=0)returnret;ret2=vrf_bind(vrf_id,ret,interfacename)
;if(ret2<0){close(ret);ret=ret2;}returnret;}