/**TimerWheel*Copyright(C)2016CumulusNetworks,Inc.*DonaldSharp**Thisprogramisfre
esoftware;youcanredistributeitand/ormodify*itunderthetermsoftheGNUGeneralPublicL
icenseaspublishedby*theFreeSoftwareFoundation;eitherversion2oftheLicense,or*(aty
ouroption)anylaterversion.**Thisprogramisdistributedinthehopethatitwillbeuseful,
but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSF
ORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldhav
ereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYIN
G;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA
02110-1301USA*/#include"zebra.h"#include"linklist.h"#include"thread.h"#include"m
emory.h"#include"wheel.h"#include"log.h"DEFINE_MTYPE_STATIC(LIB,TIMER_WHEEL,"Tim
erWheel")DEFINE_MTYPE_STATIC(LIB,TIMER_WHEEL_LIST,"TimerWheelSlotList")staticint
debug_timer_wheel=0;staticintwheel_timer_thread(structthread*t){structlistnode*n
ode,*nextnode;unsignedlonglongcurr_slot;unsignedintslots_to_skip=1;structtimer_w
heel*wheel;void*data;wheel=THREAD_ARG(t);THREAD_OFF(wheel->timer);wheel->curr_sl
ot+=wheel->slots_to_skip;curr_slot=wheel->curr_slot%wheel->slots;if(debug_timer_
wheel)zlog_debug("%s:WheelSlot:%lld(%lld)count:%d",__PRETTY_FUNCTION__,wheel->cu
rr_slot,curr_slot,listcount(wheel->wheel_slot_lists[curr_slot]));for(ALL_LIST_EL
EMENTS(wheel->wheel_slot_lists[curr_slot],node,nextnode,data))(*wheel->slot_run)
(data);while(list_isempty(wheel->wheel_slot_lists[(curr_slot+slots_to_skip)%whee
l->slots])&&(curr_slot+slots_to_skip)%wheel->slots!=curr_slot)slots_to_skip++;wh
eel->slots_to_skip=slots_to_skip;thread_add_timer_msec(wheel->master,wheel_timer
_thread,wheel,wheel->nexttime*slots_to_skip,&wheel->timer);return0;}structtimer_
wheel*wheel_init(structthread_master*master,intperiod,size_tslots,unsignedint(*s
lot_key)(void*),void(*slot_run)(void*)){structtimer_wheel*wheel;size_ti;wheel=XC
ALLOC(MTYPE_TIMER_WHEEL,sizeof(structtimer_wheel));wheel->slot_key=slot_key;whee
l->slot_run=slot_run;wheel->period=period;wheel->slots=slots;wheel->curr_slot=0;
wheel->master=master;wheel->nexttime=period/slots;wheel->wheel_slot_lists=XCALLO
C(MTYPE_TIMER_WHEEL_LIST,slots*sizeof(structlistnode*));for(i=0;i<slots;i++)whee
l->wheel_slot_lists[i]=list_new();thread_add_timer_msec(wheel->master,wheel_time
r_thread,wheel,wheel->nexttime,&wheel->timer);returnwheel;}voidwheel_delete(stru
cttimer_wheel*wheel){inti;for(i=0;i<wheel->slots;i++){list_delete_and_null(&whee
l->wheel_slot_lists[i]);}THREAD_OFF(wheel->timer);XFREE(MTYPE_TIMER_WHEEL_LIST,w
heel->wheel_slot_lists);XFREE(MTYPE_TIMER_WHEEL,wheel);}intwheel_stop(structtime
r_wheel*wheel){THREAD_OFF(wheel->timer);return0;}intwheel_start(structtimer_whee
l*wheel){if(!wheel->timer)thread_add_timer_msec(wheel->master,wheel_timer_thread
,wheel,wheel->nexttime,&wheel->timer);return0;}intwheel_add_item(structtimer_whe
el*wheel,void*item){longlongslot;slot=(*wheel->slot_key)(item);if(debug_timer_wh
eel)zlog_debug("%s:Inserting%p:%lld%lld",__PRETTY_FUNCTION__,item,slot,slot%whee
l->slots);listnode_add(wheel->wheel_slot_lists[slot%wheel->slots],item);return0;
}intwheel_remove_item(structtimer_wheel*wheel,void*item){longlongslot;slot=(*whe
el->slot_key)(item);if(debug_timer_wheel)zlog_debug("%s:Removing%p:%lld%lld",__P
RETTY_FUNCTION__,item,slot,slot%wheel->slots);listnode_delete(wheel->wheel_slot_
lists[slot%wheel->slots],item);return0;}