/**ThisfileispartofQuagga.**Quaggaisfreesoftware;youcanredistributeitand/ormodif
yit*underthetermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFounda
tion;eitherversion2,or(atyouroption)any*laterversion.**Quaggaisdistributedintheh
opethatitwillbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MER
CHANTABILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformore
details.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthispr
ogram;seethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinS
t,FifthFloor,Boston,MA02110-1301USA*/#ifndef_QUAGGA_ASSERT_H#define_QUAGGA_ASSER
T_Hexternvoid_zlog_assert_failed(constchar*assertion,constchar*file,unsignedintl
ine,constchar*function)__attribute__((noreturn));#ifdefined(__STDC_VERSION__)&&_
_STDC_VERSION__>=199901L#define__ASSERT_FUNCTION__func__#elifdefined(__GNUC__)#d
efine__ASSERT_FUNCTION__FUNCTION__#else#define__ASSERT_FUNCTIONNULL#endif#define
zassert(EX)\((void)((EX)?0:(_zlog_assert_failed(#EX,__FILE__,__LINE__,\__ASSERT_
FUNCTION),\0)))#undefassert#defineassert(EX)zassert(EX)#endif/*_QUAGGA_ASSERT_H*
/