/*Zebracommonheader.*Copyright(C)1997,1998,1999,2000,2001,2002KunihiroIshiguro**
ThisfileispartofGNUZebra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodi
fyit*underthetermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFound
ation;eitherversion2,or(atyouroption)any*laterversion.**GNUZebraisdistributedint
hehopethatitwillbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*
MERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseform
oredetails.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthi
sprogram;seethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51Frankl
inSt,FifthFloor,Boston,MA02110-1301USA*/#ifndef_ZEBRA_H#define_ZEBRA_H#ifdefHAVE
_CONFIG_H#include"config.h"#endif/*HAVE_CONFIG_H*/#ifdefSUNOS_5#define_XPG4_2typ
edefunsignedintuint32_t;typedefunsignedshortuint16_t;typedefunsignedcharuint8_t;
#endif/*SUNOS_5*/#include<unistd.h>#include<stdio.h>#include<stdlib.h>#include<s
tddef.h>#include<ctype.h>#include<errno.h>#include<fcntl.h>#include<signal.h>#in
clude<string.h>#include<pwd.h>#include<grp.h>#ifdefHAVE_STROPTS_H#include<stropt
s.h>#endif/*HAVE_STROPTS_H*/#include<sys/select.h>#include<sys/stat.h>#include<s
ys/types.h>#include<sys/param.h>#ifdefHAVE_SYS_SYSCTL_H#ifdefGNU_LINUX#include<l
inux/types.h>#endif#include<sys/sysctl.h>#endif/*HAVE_SYS_SYSCTL_H*/#include<sys
/ioctl.h>#ifdefHAVE_SYS_CONF_H#include<sys/conf.h>#endif/*HAVE_SYS_CONF_H*/#ifde
fHAVE_SYS_KSYM_H#include<sys/ksym.h>#endif/*HAVE_SYS_KSYM_H*/#include<syslog.h>#
include<sys/time.h>#include<time.h>#include<sys/uio.h>#include<sys/utsname.h>#in
clude<sys/resource.h>#include<limits.h>#include<inttypes.h>#include<stdbool.h>/*
machinedependentincludes*/#ifdefSUNOS_5#include<strings.h>#endif/*SUNOS_5*//*mac
hinedependentincludes*/#ifdefHAVE_LINUX_VERSION_H#include<linux/version.h>#endif
/*HAVE_LINUX_VERSION_H*/#ifdefHAVE_ASM_TYPES_H#include<asm/types.h>#endif/*HAVE_
ASM_TYPES_H*//*miscincludegroup*/#include<stdarg.h>#if!(defined(__STDC_VERSION__
)&&__STDC_VERSION__>=199901L)/*NotC99;doweneedtodefineva_copy?*/#ifndefva_copy#i
fdef__va_copy#defineva_copy(DST,SRC)__va_copy(DST,SRC)#else/*Nowwearedesperate;t
hisshouldworkonmanytypicalplatforms.Butthisisslightlydangerous,becausethestandar
ddoesnotrequireva_copytobeamacro.*/#defineva_copy(DST,SRC)memcpy(&(DST),&(SRC),s
izeof(va_list))#warning"NotC99andnova_copymacroavailable,fallingbacktomemcpy"#en
dif/*__va_copy*/#endif/*!va_copy*/#endif/*!C99*/#ifdefHAVE_LCAPS#include<sys/cap
ability.h>#include<sys/prctl.h>#endif/*HAVE_LCAPS*/#ifdefHAVE_SOLARIS_CAPABILITI
ES#include<priv.h>#endif/*HAVE_SOLARIS_CAPABILITIES*//*networkincludegroup*/#inc
lude<sys/socket.h>#ifdefHAVE_SYS_SOCKIO_H#include<sys/sockio.h>#endif/*HAVE_SYS_
SOCKIO_H*/#ifdef__APPLE__#define__APPLE_USE_RFC_3542#endif#ifndefHAVE_LIBCRYPT#i
fdefHAVE_LIBCRYPTO#include<openssl/des.h>#definecryptDES_crypt#endif#endif#inclu
de"openbsd-tree.h"#include<netinet/in.h>#include<netinet/in_systm.h>#include<net
inet/ip.h>#include<netinet/tcp.h>#ifdefHAVE_NET_NETOPT_H#include<net/netopt.h>#e
ndif/*HAVE_NET_NETOPT_H*/#include<net/if.h>#ifdefHAVE_NET_IF_DL_H#include<net/if
_dl.h>#endif/*HAVE_NET_IF_DL_H*/#ifdefHAVE_NET_IF_VAR_H#include<net/if_var.h>#en
dif/*HAVE_NET_IF_VAR_H*/#include<net/route.h>#ifdefHAVE_NETLINK#include<linux/ne
tlink.h>#include<linux/rtnetlink.h>#include<linux/filter.h>#else#defineRT_TABLE_
MAIN0#endif/*HAVE_NETLINK*/#include<netdb.h>#include<arpa/inet.h>#ifdefHAVE_INET
_ND_H#include<inet/nd.h>#endif/*HAVE_INET_ND_H*/#ifdefHAVE_NETINET_IN_VAR_H#incl
ude<netinet/in_var.h>#endif/*HAVE_NETINET_IN_VAR_H*/#ifdefHAVE_NETINET6_IN6_VAR_
H#include<netinet6/in6_var.h>#endif/*HAVE_NETINET6_IN6_VAR_H*/#ifdefHAVE_NETINET
_IN6_VAR_H#include<netinet/in6_var.h>#endif/*HAVE_NETINET_IN6_VAR_H*/#ifdefHAVE_
NETINET6_IN_H#include<netinet6/in.h>#endif/*HAVE_NETINET6_IN_H*/#ifdefHAVE_NETIN
ET6_IP6_H#include<netinet6/ip6.h>#endif/*HAVE_NETINET6_IP6_H*/#include<netinet/i
cmp6.h>#ifdefHAVE_NETINET6_ND6_H#include<netinet6/nd6.h>#endif/*HAVE_NETINET6_ND
6_H*//*SomesystemsdonotdefineUINT32_MAX,etc..frominttypes.h*e.g.thismakeslifeeas
ierforFBSD4.11users.*/#ifndefINT8_MAX#defineINT8_MAX(127)#endif#ifndefINT16_MAX#
defineINT16_MAX(32767)#endif#ifndefINT32_MAX#defineINT32_MAX(2147483647)#endif#i
fndefUINT8_MAX#defineUINT8_MAX(255U)#endif#ifndefUINT16_MAX#defineUINT16_MAX(655
35U)#endif#ifndefUINT32_MAX#defineUINT32_MAX(4294967295U)#endif#ifdefHAVE_GLIBC_
BACKTRACE#include<execinfo.h>#endif/*HAVE_GLIBC_BACKTRACE*//*Localincludes:*/#if
!(defined(__GNUC__)||defined(VTYSH_EXTRACT_PL))#define__attribute__(x)#endif/*!_
_GNUC__||VTYSH_EXTRACT_PL*/#include"zassert.h"#ifndefHAVE_STRLCATsize_tstrlcat(c
har*__restrictdest,constchar*__restrictsrc,size_tdestsize);#endif#ifndefHAVE_STR
LCPYsize_tstrlcpy(char*__restrictdest,constchar*__restrictsrc,size_tdestsize);#e
ndif#ifdefHAVE_BROKEN_CMSG_FIRSTHDR/*ThisbugispresentinSolaris8andpre-patchSolar
is9<sys/socket.h>;pleaserefertohttp://bugzilla.quagga.net/show_bug.cgi?id=142*//
*Checkthatmsg_controllenislargeenough.*/#defineZCMSG_FIRSTHDR(mhdr)\(((size_t)((
mhdr)->msg_controllen)>=sizeof(structcmsghdr))\?CMSG_FIRSTHDR(mhdr)\:(structcmsg
hdr*)NULL)#warning"CMSG_FIRSTHDRisbrokenonthisplatform,usingaworkaround"#else/*H
AVE_BROKEN_CMSG_FIRSTHDR*/#defineZCMSG_FIRSTHDR(M)CMSG_FIRSTHDR(M)#endif/*HAVE_B
ROKEN_CMSG_FIRSTHDR*//*GCChaveprintftypeattributecheck.*/#ifdef__GNUC__#definePR
INTF_ATTRIBUTE(a,b)__attribute__((__format__(__printf__,a,b)))#else#definePRINTF
_ATTRIBUTE(a,b)#endif/*__GNUC__*//**RFC3542definesseveralmacrosforusingstructcms
ghdr.*Here,wedefinethosethatarenotpresent*//**Internaldefines,foruseonlyinthisfi
le.*ThesearelikelywrongonotherthanILP32machines,sowarn.*/#ifndef_CMSG_DATA_ALIGN
#define_CMSG_DATA_ALIGN(n)(((n)+3)&~3)#endif/*_CMSG_DATA_ALIGN*/#ifndef_CMSG_HDR
_ALIGN#define_CMSG_HDR_ALIGN(n)(((n)+3)&~3)#endif/*_CMSG_HDR_ALIGN*//**CMSG_SPAC
EandCMSG_LENarerequiredinRFC3542,butwerenewinthat*version.*/#ifndefCMSG_SPACE#de
fineCMSG_SPACE(l)\(_CMSG_DATA_ALIGN(sizeof(structcmsghdr))+_CMSG_HDR_ALIGN(l))#w
arning"assuming4-bytealignmentforCMSG_SPACE"#endif/*CMSG_SPACE*/#ifndefCMSG_LEN#
defineCMSG_LEN(l)(_CMSG_DATA_ALIGN(sizeof(structcmsghdr))+(l))#warning"assuming4
-bytealignmentforCMSG_LEN"#endif/*CMSG_LEN*//*Thedefinitionofstructin_pktinfoism
issinginoldversionofGLIBC2.1(Redhat6.1).*/#ifdefined(GNU_LINUX)&&!defined(HAVE_S
TRUCT_IN_PKTINFO)structin_pktinfo{intipi_ifindex;structin_addripi_spec_dst;struc
tin_addripi_addr;};#endif/**IP_HDRINCL/structipbyteorder**Linux:networkbyteorder
**BSD:network,exceptforlengthandoffset.(cfStevens)*SunOS:nominallyasperBSD.butbu
g:networkorderonLE.*OpenBSD:networkbyteorder,apartfromolderversionswhichareasper
**BSD*/#ifdefined(__NetBSD__)\||(defined(__FreeBSD__)&&(__FreeBSD_version<110003
0))\||(defined(__OpenBSD__)&&(OpenBSD<200311))\||(defined(__APPLE__))\||(defined
(SUNOS_5)&&defined(WORDS_BIGENDIAN))#defineHAVE_IP_HDRINCL_BSD_ORDER#endif/*Defi
neBYTE_ORDER,ifnotdefined.Usefulforcompilerconditional*code,ratherthanpreprocess
orconditional.*NotalltheworldhasthisBSDdefine.*/#ifndefBYTE_ORDER#defineBIG_ENDI
AN4321/*least-significantbytefirst(vax,pc)*/#defineLITTLE_ENDIAN1234/*most-signi
ficantbytefirst(IBM,net)*/#definePDP_ENDIAN3412/*LSBfirstinword,MSWfirstinlong(p
dp)*/#ifdefined(WORDS_BIGENDIAN)#defineBYTE_ORDERBIG_ENDIAN#else/*!WORDS_BIGENDI
AN*/#defineBYTE_ORDERLITTLE_ENDIAN#endif/*WORDS_BIGENDIAN*/#endif/*ndefBYTE_ORDE
R*//*MAX/MINarenotcommonlydefined,butuseful*//*note:glibcsys/param.hhas#defineMI
N(a,b)(((a)<(b))?(a):(b))*/#ifdefMAX#undefMAX#endif#defineMAX(a,b)\({\typeof(a)_
a=(a);\typeof(b)_b=(b);\_a>_b?_a:_b;\})#ifdefMIN#undefMIN#endif#defineMIN(a,b)\(
{\typeof(a)_a=(a);\typeof(b)_b=(b);\_a<_b?_a:_b;\})#defineZEBRA_NUM_OF(x)(sizeof
(x)/sizeof(x[0]))/*Forolddefinition.*/#ifndefIN6_ARE_ADDR_EQUAL#defineIN6_ARE_AD
DR_EQUALIN6_IS_ADDR_EQUAL#endif/*IN6_ARE_ADDR_EQUAL*//*defaultzebraTCPportforzcl
ient*/#defineZEBRA_PORT2600/*MarkervalueusedinnewZserv,inthebytelocationcorrespo
nding*thecommandvalueintheoldzservheader.Toallowoldandnew*Zservheaderstobedistin
guishedfromeachother.*/#defineZEBRA_HEADER_MARKER254/*Zebraroute'stypesaredefine
dinroute_types.h*/#include"route_types.h"/*Note:wheneveranewroute-typeorzserv-co
mmandisaddedthe*corresponding{command,route}_types[]tableinlib/log.cMUSTbe*updat
ed!*//*Maparoutetypetoastring.Forexample,ZEBRA_ROUTE_RIPNG->"ripng".*/externcons
tchar*zebra_route_string(unsignedintroute_type);/*Maparoutetypetoachar.Forexampl
e,ZEBRA_ROUTE_RIPNG->'R'.*/externcharzebra_route_char(unsignedintroute_type);/*M
apazservcommandtypetothesamestring,*e.g.ZEBRA_INTERFACE_ADD->"ZEBRA_INTERFACE_AD
D"*//*Mapaprotocolnametoitsnumber.e.g.ZEBRA_ROUTE_BGP->9*/externintproto_name2nu
m(constchar*s);/*MapredistributeXargumenttoprotocolnumber.*unlikeproto_name2num,
thisacceptsshorthandsandtakes*anAFIvaluetorestrictinput*/externintproto_redistnu
m(intafi,constchar*s);externconstchar*zserv_command_string(unsignedintcommand);#
definestrmatch(a,b)(!strcmp((a),(b)))/*Zebramessageflags*/#defineZEBRA_FLAG_ALLO
W_RECURSION0x01#defineZEBRA_FLAG_SELFROUTE0x02#defineZEBRA_FLAG_IBGP0x08#defineZ
EBRA_FLAG_SELECTED0x10#defineZEBRA_FLAG_STATIC0x40#defineZEBRA_FLAG_SCOPE_LINK0x
100#defineZEBRA_FLAG_FIB_OVERRIDE0x200#defineZEBRA_FLAG_EVPN_ROUTE0x400/*ZEBRA_F
LAG_BLACKHOLEwas0x04*//*ZEBRA_FLAG_REJECTwas0x80*//*ZebraFECflags.*/#defineZEBRA
_FEC_REGISTER_LABEL_INDEX0x1#ifndefINADDR_LOOPBACK#defineINADDR_LOOPBACK0x7f0000
01/*Internetaddress127.0.0.1.*/#endif/*AddressfamilynumbersfromRFC1700.*/typedef
enum{AFI_IP=1,AFI_IP6=2,AFI_L2VPN=3,AFI_MAX=4}afi_t;/*SubsequentAddressFamilyIde
ntifier.*/typedefenum{SAFI_UNICAST=1,SAFI_MULTICAST=2,SAFI_MPLS_VPN=3,SAFI_ENCAP
=4,SAFI_EVPN=5,SAFI_LABELED_UNICAST=6,SAFI_FLOWSPEC=7,SAFI_MAX=8}safi_t;/**Theab
oveAFIandSAFIdefinitionsareforinternaluse.Theprotocol*definitions(IANAvalues)asf
orexampleusedinBGPprotocolpackets*aredefinedbelowandthesewillgetmappedto/fromthe
internalvalues*intheappropriateplaces.*Therationaleisthattheprotocol(IANA)values
maybesparseandare*notoptimalforuseindata-structuresizing.*Note:Onlyuseful(i.e.,s
upported)valuesaredefinedbelow.*/typedefenum{IANA_AFI_RESERVED=0,IANA_AFI_IPV4=1
,IANA_AFI_IPV6=2,IANA_AFI_L2VPN=25,IANA_AFI_IPMR=128,IANA_AFI_IP6MR=129}iana_afi
_t;typedefenum{IANA_SAFI_RESERVED=0,IANA_SAFI_UNICAST=1,IANA_SAFI_MULTICAST=2,IA
NA_SAFI_LABELED_UNICAST=4,IANA_SAFI_ENCAP=7,IANA_SAFI_EVPN=70,IANA_SAFI_MPLS_VPN
=128,IANA_SAFI_FLOWSPEC=133}iana_safi_t;/*DefaultAdministrativeDistanceofeachpro
tocol.*/#defineZEBRA_KERNEL_DISTANCE_DEFAULT0#defineZEBRA_CONNECT_DISTANCE_DEFAU
LT0#defineZEBRA_STATIC_DISTANCE_DEFAULT1#defineZEBRA_RIP_DISTANCE_DEFAULT120#def
ineZEBRA_RIPNG_DISTANCE_DEFAULT120#defineZEBRA_OSPF_DISTANCE_DEFAULT110#defineZE
BRA_OSPF6_DISTANCE_DEFAULT110#defineZEBRA_ISIS_DISTANCE_DEFAULT115#defineZEBRA_I
BGP_DISTANCE_DEFAULT200#defineZEBRA_EBGP_DISTANCE_DEFAULT20#defineZEBRA_TABLE_DI
STANCE_DEFAULT15/*Flagmanipulationmacros.*/#defineCHECK_FLAG(V,F)((V)&(F))#defin
eSET_FLAG(V,F)(V)|=(F)#defineUNSET_FLAG(V,F)(V)&=~(F)#defineRESET_FLAG(V)(V)=0/*
Atomicflagmanipulationmacros.*/#defineCHECK_FLAG_ATOMIC(PV,F)\((atomic_load_expl
icit(PV,memory_order_seq_cst))&(F))#defineSET_FLAG_ATOMIC(PV,F)\((atomic_fetch_o
r_explicit(PV,(F),memory_order_seq_cst)))#defineUNSET_FLAG_ATOMIC(PV,F)\((atomic
_fetch_and_explicit(PV,~(F),memory_order_seq_cst)))#defineRESET_FLAG_ATOMIC(PV)\
((atomic_store_explicit(PV,0,memory_order_seq_cst)))/*Zebratypes.UsedinZservmess
ageheader.*/typedefuint16_tzebra_size_t;typedefuint16_tzebra_command_t;/*VRFIDty
pe.*/typedefuint32_tvrf_id_t;typedefuint32_troute_tag_t;#defineROUTE_TAG_MAXUINT
32_MAX#defineROUTE_TAG_PRIPRIu32staticinlineafi_tafi_iana2int(iana_afi_tafi){swi
tch(afi){caseIANA_AFI_IPV4:returnAFI_IP;caseIANA_AFI_IPV6:returnAFI_IP6;caseIANA
_AFI_L2VPN:returnAFI_L2VPN;default:returnAFI_MAX;}}staticinlineiana_afi_tafi_int
2iana(afi_tafi){switch(afi){caseAFI_IP:returnIANA_AFI_IPV4;caseAFI_IP6:returnIAN
A_AFI_IPV6;caseAFI_L2VPN:returnIANA_AFI_L2VPN;default:returnIANA_AFI_RESERVED;}}
staticinlinesafi_tsafi_iana2int(iana_safi_tsafi){switch(safi){caseIANA_SAFI_UNIC
AST:returnSAFI_UNICAST;caseIANA_SAFI_MULTICAST:returnSAFI_MULTICAST;caseIANA_SAF
I_MPLS_VPN:returnSAFI_MPLS_VPN;caseIANA_SAFI_ENCAP:returnSAFI_ENCAP;caseIANA_SAF
I_EVPN:returnSAFI_EVPN;caseIANA_SAFI_LABELED_UNICAST:returnSAFI_LABELED_UNICAST;
caseIANA_SAFI_FLOWSPEC:returnSAFI_FLOWSPEC;default:returnSAFI_MAX;}}staticinline
iana_safi_tsafi_int2iana(safi_tsafi){switch(safi){caseSAFI_UNICAST:returnIANA_SA
FI_UNICAST;caseSAFI_MULTICAST:returnIANA_SAFI_MULTICAST;caseSAFI_MPLS_VPN:return
IANA_SAFI_MPLS_VPN;caseSAFI_ENCAP:returnIANA_SAFI_ENCAP;caseSAFI_EVPN:returnIANA
_SAFI_EVPN;caseSAFI_LABELED_UNICAST:returnIANA_SAFI_LABELED_UNICAST;caseSAFI_FLO
WSPEC:returnIANA_SAFI_FLOWSPEC;default:returnIANA_SAFI_RESERVED;}}#endif/*_ZEBRA
_H*/