/**Copyright(C)2003YasuhiroOhara**ThisfileispartofGNUZebra.**GNUZebraisfreesoftw
are;youcanredistributeitand/ormodifyit*underthetermsoftheGNUGeneralPublicLicense
aspublishedbythe*FreeSoftwareFoundation;eitherversion2,or(atyouroption)any*later
version.**GNUZebraisdistributedinthehopethatitwillbeuseful,but*WITHOUTANYWARRANT
Y;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.
SeetheGNU*GeneralPublicLicenseformoredetails.**YoushouldhavereceivedacopyoftheGN
UGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;ifnot,writetotheFre
eSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-1301USA*/#inclu
de<zebra.h>#include"log.h"#include"memory.h"#include"linklist.h"#include"thread.
h"#include"vty.h"#include"command.h"#include"if.h"#include"prefix.h"#include"tab
le.h"#include"plist.h"#include"filter.h"#include"ospf6_proto.h"#include"ospf6_ls
a.h"#include"ospf6_lsdb.h"#include"ospf6_route.h"#include"ospf6_spf.h"#include"o
spf6_top.h"#include"ospf6_area.h"#include"ospf6_interface.h"#include"ospf6_intra
.h"#include"ospf6_abr.h"#include"ospf6_asbr.h"#include"ospf6d.h"DEFINE_MTYPE_STA
TIC(OSPF6D,OSPF6_PLISTNAME,"Prefixlistname")intospf6_area_cmp(void*va,void*vb){s
tructospf6_area*oa=(structospf6_area*)va;structospf6_area*ob=(structospf6_area*)
vb;return(ntohl(oa->area_id)<ntohl(ob->area_id)?-1:1);}/*scheduleroutingtablerec
alculation*/staticvoidospf6_area_lsdb_hook_add(structospf6_lsa*lsa){switch(ntohs
(lsa->header->type)){caseOSPF6_LSTYPE_ROUTER:caseOSPF6_LSTYPE_NETWORK:if(IS_OSPF
6_DEBUG_EXAMIN_TYPE(lsa->header->type)){zlog_debug("%sExaminLSA%s",__PRETTY_FUNC
TION__,lsa->name);zlog_debug("ScheduleSPFCalculationfor%s",OSPF6_AREA(lsa->lsdb-
>data)->name);}ospf6_spf_schedule(OSPF6_PROCESS(OSPF6_AREA(lsa->lsdb->data)->osp
f6),ospf6_lsadd_to_spf_reason(lsa));break;caseOSPF6_LSTYPE_INTRA_PREFIX:ospf6_in
tra_prefix_lsa_add(lsa);break;caseOSPF6_LSTYPE_INTER_PREFIX:caseOSPF6_LSTYPE_INT
ER_ROUTER:ospf6_abr_examin_summary(lsa,(structospf6_area*)lsa->lsdb->data);break
;default:break;}}staticvoidospf6_area_lsdb_hook_remove(structospf6_lsa*lsa){swit
ch(ntohs(lsa->header->type)){caseOSPF6_LSTYPE_ROUTER:caseOSPF6_LSTYPE_NETWORK:if
(IS_OSPF6_DEBUG_EXAMIN_TYPE(lsa->header->type)){zlog_debug("LSAdisappearing:%s",
lsa->name);zlog_debug("ScheduleSPFCalculationfor%s",OSPF6_AREA(lsa->lsdb->data)-
>name);}ospf6_spf_schedule(OSPF6_PROCESS(OSPF6_AREA(lsa->lsdb->data)->ospf6),osp
f6_lsremove_to_spf_reason(lsa));break;caseOSPF6_LSTYPE_INTRA_PREFIX:ospf6_intra_
prefix_lsa_remove(lsa);break;caseOSPF6_LSTYPE_INTER_PREFIX:caseOSPF6_LSTYPE_INTE
R_ROUTER:ospf6_abr_examin_summary(lsa,(structospf6_area*)lsa->lsdb->data);break;
default:break;}}staticvoidospf6_area_route_hook_add(structospf6_route*route){str
uctospf6_route*copy;copy=ospf6_route_copy(route);ospf6_route_add(copy,ospf6->rou
te_table);}staticvoidospf6_area_route_hook_remove(structospf6_route*route){struc
tospf6_route*copy;copy=ospf6_route_lookup_identical(route,ospf6->route_table);if
(copy)ospf6_route_remove(copy,ospf6->route_table);}staticvoidospf6_area_stub_upd
ate(structospf6_area*area){if(IS_AREA_STUB(area)){if(IS_OSPF6_DEBUG_ORIGINATE(RO
UTER))zlog_debug("Stubbingoutareaforif%s\n",area->name);OSPF6_OPT_CLEAR(area->op
tions,OSPF6_OPT_E);}elseif(IS_AREA_ENABLED(area)){if(IS_OSPF6_DEBUG_ORIGINATE(RO
UTER))zlog_debug("Normalareaforif%s\n",area->name);OSPF6_OPT_SET(area->options,O
SPF6_OPT_E);ospf6_asbr_send_externals_to_area(area);}OSPF6_ROUTER_LSA_SCHEDULE(a
rea);}staticintospf6_area_stub_set(structospf6*ospf6,structospf6_area*area){if(!
IS_AREA_STUB(area)){SET_FLAG(area->flag,OSPF6_AREA_STUB);ospf6_area_stub_update(
area);}return(1);}staticvoidospf6_area_stub_unset(structospf6*ospf6,structospf6_
area*area){if(IS_AREA_STUB(area)){UNSET_FLAG(area->flag,OSPF6_AREA_STUB);ospf6_a
rea_stub_update(area);}}staticvoidospf6_area_no_summary_set(structospf6*ospf6,st
ructospf6_area*area){if(area){if(!area->no_summary){area->no_summary=1;ospf6_abr
_range_reset_cost(ospf6);ospf6_abr_prefix_resummarize(ospf6);}}}staticvoidospf6_
area_no_summary_unset(structospf6*ospf6,structospf6_area*area){if(area){if(area-
>no_summary){area->no_summary=0;ospf6_abr_range_reset_cost(ospf6);ospf6_abr_pref
ix_resummarize(ospf6);}}}/***Makenewareastructure.**@paramarea_id-ospf6areaID*@p
aramo-ospf6instance*@paramdf-displayformatforareaID*/structospf6_area*ospf6_area
_create(uint32_tarea_id,structospf6*o,intdf){structospf6_area*oa;oa=XCALLOC(MTYP
E_OSPF6_AREA,sizeof(structospf6_area));switch(df){caseOSPF6_AREA_FMT_DECIMAL:snp
rintf(oa->name,sizeof(oa->name),"%u",ntohl(area_id));break;default:caseOSPF6_ARE
A_FMT_DOTTEDQUAD:inet_ntop(AF_INET,&area_id,oa->name,sizeof(oa->name));break;}oa
->area_id=area_id;oa->if_list=list_new();oa->lsdb=ospf6_lsdb_create(oa);oa->lsdb
->hook_add=ospf6_area_lsdb_hook_add;oa->lsdb->hook_remove=ospf6_area_lsdb_hook_r
emove;oa->lsdb_self=ospf6_lsdb_create(oa);oa->temp_router_lsa_lsdb=ospf6_lsdb_cr
eate(oa);oa->spf_table=OSPF6_ROUTE_TABLE_CREATE(AREA,SPF_RESULTS);oa->spf_table-
>scope=oa;oa->route_table=OSPF6_ROUTE_TABLE_CREATE(AREA,ROUTES);oa->route_table-
>scope=oa;oa->route_table->hook_add=ospf6_area_route_hook_add;oa->route_table->h
ook_remove=ospf6_area_route_hook_remove;oa->range_table=OSPF6_ROUTE_TABLE_CREATE
(AREA,PREFIX_RANGES);oa->range_table->scope=oa;bf_init(oa->range_table->idspace,
32);oa->summary_prefix=OSPF6_ROUTE_TABLE_CREATE(AREA,SUMMARY_PREFIXES);oa->summa
ry_prefix->scope=oa;oa->summary_router=OSPF6_ROUTE_TABLE_CREATE(AREA,SUMMARY_ROU
TERS);oa->summary_router->scope=oa;oa->router_lsa_size_limit=1024+256;/*setdefau
ltoptions*/if(CHECK_FLAG(o->flag,OSPF6_STUB_ROUTER)){OSPF6_OPT_CLEAR(oa->options
,OSPF6_OPT_V6);OSPF6_OPT_CLEAR(oa->options,OSPF6_OPT_R);}else{OSPF6_OPT_SET(oa->
options,OSPF6_OPT_V6);OSPF6_OPT_SET(oa->options,OSPF6_OPT_R);}OSPF6_OPT_SET(oa->
options,OSPF6_OPT_E);SET_FLAG(oa->flag,OSPF6_AREA_ACTIVE);SET_FLAG(oa->flag,OSPF
6_AREA_ENABLE);oa->ospf6=o;listnode_add_sort(o->area_list,oa);if(area_id==OSPF_A
REA_BACKBONE){o->backbone=oa;}returnoa;}voidospf6_area_delete(structospf6_area*o
a){structlistnode*n;structospf6_interface*oi;/*Theospf6_interfacestructsstorecon
figuration*informationwhichshouldnotbelost/resetwhen*deletinganarea.*Sojustdetac
htheinterfacefromtheareaand*keepitaround.*/for(ALL_LIST_ELEMENTS_RO(oa->if_list,
n,oi))oi->area=NULL;list_delete_and_null(&oa->if_list);ospf6_lsdb_delete(oa->lsd
b);ospf6_lsdb_delete(oa->lsdb_self);ospf6_lsdb_delete(oa->temp_router_lsa_lsdb);
ospf6_spf_table_finish(oa->spf_table);ospf6_route_table_delete(oa->spf_table);os
pf6_route_table_delete(oa->route_table);ospf6_route_table_delete(oa->range_table
);ospf6_route_table_delete(oa->summary_prefix);ospf6_route_table_delete(oa->summ
ary_router);listnode_delete(oa->ospf6->area_list,oa);oa->ospf6=NULL;/*freearea*/
XFREE(MTYPE_OSPF6_AREA,oa);}structospf6_area*ospf6_area_lookup(uint32_tarea_id,s
tructospf6*ospf6){structospf6_area*oa;structlistnode*n;for(ALL_LIST_ELEMENTS_RO(
ospf6->area_list,n,oa))if(oa->area_id==area_id)returnoa;return(structospf6_area*
)NULL;}voidospf6_area_enable(structospf6_area*oa){structlistnode*node,*nnode;str
uctospf6_interface*oi;SET_FLAG(oa->flag,OSPF6_AREA_ENABLE);for(ALL_LIST_ELEMENTS
(oa->if_list,node,nnode,oi))ospf6_interface_enable(oi);ospf6_abr_enable_area(oa)
;}voidospf6_area_disable(structospf6_area*oa){structlistnode*node,*nnode;structo
spf6_interface*oi;UNSET_FLAG(oa->flag,OSPF6_AREA_ENABLE);for(ALL_LIST_ELEMENTS(o
a->if_list,node,nnode,oi))ospf6_interface_disable(oi);ospf6_abr_disable_area(oa)
;ospf6_lsdb_remove_all(oa->lsdb);ospf6_lsdb_remove_all(oa->lsdb_self);ospf6_spf_
table_finish(oa->spf_table);ospf6_route_remove_all(oa->route_table);THREAD_OFF(o
a->thread_router_lsa);THREAD_OFF(oa->thread_intra_prefix_lsa);}voidospf6_area_sh
ow(structvty*vty,structospf6_area*oa){structlistnode*i;structospf6_interface*oi;
unsignedlongresult;if(!IS_AREA_STUB(oa))vty_out(vty,"Area%s\n",oa->name);else{if
(oa->no_summary){vty_out(vty,"Area%s[Stub,NoSummary]\n",oa->name);}else{vty_out(
vty,"Area%s[Stub]\n",oa->name);}}vty_out(vty,"NumberofAreascopedLSAsis%u\n",oa->
lsdb->count);vty_out(vty,"Interfaceattachedtothisarea:");for(ALL_LIST_ELEMENTS_R
O(oa->if_list,i,oi))vty_out(vty,"%s",oi->interface->name);vty_out(vty,"\n");if(o
a->ts_spf.tv_sec||oa->ts_spf.tv_usec){result=monotime_since(&oa->ts_spf,NULL);if
(result/TIMER_SECOND_MICRO>0){vty_out(vty,"SPFlastexecuted%ld.%ldsago\n",result/
TIMER_SECOND_MICRO,result%TIMER_SECOND_MICRO);}else{vty_out(vty,"SPFlastexecuted
%ldusago\n",result);}}elsevty_out(vty,"SPFhasnotbeenrun\n");}#defineOSPF6_CMD_AR
EA_GET(str,oa)\{\char*ep;\uint32_tarea_id=htonl(strtoul(str,&ep,10));\if(*ep&&in
et_pton(AF_INET,str,&area_id)!=1){\vty_out(vty,"MalformedArea-ID:%s\n",str);\ret
urnCMD_SUCCESS;\}\intformat=!*ep?OSPF6_AREA_FMT_DECIMAL\:OSPF6_AREA_FMT_DOTTEDQU
AD;\oa=ospf6_area_lookup(area_id,ospf6);\if(oa==NULL)\oa=ospf6_area_create(area_
id,ospf6,format);\}DEFUN(area_range,area_range_cmd,"area<A.B.C.D|(0-4294967295)>
rangeX:X::X:X/M[<advertise|not-advertise|cost(0-16777215)>]","OSPF6areaparameter
s\n""OSPF6areaIDinIPaddressformat\n""OSPF6areaIDasadecimalvalue\n""Configuredadd
ressrange\n""SpecifyIPv6prefix\n""Advertise\n""Donotadvertise\n""Userspecifiedme
tricforthisrange\n""Advertisedmetricforthisrange\n"){intidx_ipv4=1;intidx_ipv6_p
refixlen=3;intidx_type=4;intret;structospf6_area*oa;structprefixprefix;structosp
f6_route*range;uint32_tcost=OSPF_AREA_RANGE_COST_UNSPEC;OSPF6_CMD_AREA_GET(argv[
idx_ipv4]->arg,oa);ret=str2prefix(argv[idx_ipv6_prefixlen]->arg,&prefix);if(ret!
=1||prefix.family!=AF_INET6){vty_out(vty,"Malformedargument:%s\n",argv[idx_ipv6_
prefixlen]->arg);returnCMD_SUCCESS;}range=ospf6_route_lookup(&prefix,oa->range_t
able);if(range==NULL){range=ospf6_route_create();range->type=OSPF6_DEST_TYPE_RAN
GE;range->prefix=prefix;range->path.area_id=oa->area_id;range->path.cost=OSPF_AR
EA_RANGE_COST_UNSPEC;}if(argc>idx_type){if(strmatch(argv[idx_type]->text,"not-ad
vertise")){SET_FLAG(range->flag,OSPF6_ROUTE_DO_NOT_ADVERTISE);}elseif(strmatch(a
rgv[idx_type]->text,"advertise")){UNSET_FLAG(range->flag,OSPF6_ROUTE_DO_NOT_ADVE
RTISE);}else{cost=strtoul(argv[5]->arg,NULL,10);UNSET_FLAG(range->flag,OSPF6_ROU
TE_DO_NOT_ADVERTISE);}}range->path.u.cost_config=cost;zlog_debug("%s:forprefix%s
,flag=%x\n",__func__,argv[idx_ipv6_prefixlen]->arg,range->flag);if(range->rnode=
=NULL){ospf6_route_add(range,oa->range_table);}if(ospf6_is_router_abr(ospf6)){/*
Redosummariesifrequired*/ospf6_abr_prefix_resummarize(ospf6);}returnCMD_SUCCESS;
}DEFUN(no_area_range,no_area_range_cmd,"noarea<A.B.C.D|(0-4294967295)>rangeX:X::
X:X/M[<advertise|not-advertise|cost(0-16777215)>]",NO_STR"OSPF6areaparameters\n"
"OSPF6areaIDinIPaddressformat\n""OSPF6areaIDasadecimalvalue\n""Configuredaddress
range\n""SpecifyIPv6prefix\n""Advertise\n""Donotadvertise\n""Userspecifiedmetric
forthisrange\n""Advertisedmetricforthisrange\n"){intidx_ipv4=2;intidx_ipv6=4;int
ret;structospf6_area*oa;structprefixprefix;structospf6_route*range,*route;OSPF6_
CMD_AREA_GET(argv[idx_ipv4]->arg,oa);ret=str2prefix(argv[idx_ipv6]->arg,&prefix)
;if(ret!=1||prefix.family!=AF_INET6){vty_out(vty,"Malformedargument:%s\n",argv[i
dx_ipv6]->arg);returnCMD_SUCCESS;}range=ospf6_route_lookup(&prefix,oa->range_tab
le);if(range==NULL){vty_out(vty,"Range%sdoesnotexists.\n",argv[idx_ipv6]->arg);r
eturnCMD_SUCCESS;}if(ospf6_is_router_abr(oa->ospf6)){/*BlowawaytheaggregatedLSAa
ndroute*/SET_FLAG(range->flag,OSPF6_ROUTE_REMOVE);/*Redosummariesifrequired*/for
(route=ospf6_route_head(ospf6->route_table);route;route=ospf6_route_next(route))
ospf6_abr_originate_summary(route);/*purgetheoldaggregatedsummaryLSA*/ospf6_abr_
originate_summary(range);}ospf6_route_remove(range,oa->range_table);returnCMD_SU
CCESS;}voidospf6_area_config_write(structvty*vty){structlistnode*node;structospf
6_area*oa;structospf6_route*range;charbuf[PREFIX2STR_BUFFER];for(ALL_LIST_ELEMEN
TS_RO(ospf6->area_list,node,oa)){for(range=ospf6_route_head(oa->range_table);ran
ge;range=ospf6_route_next(range)){prefix2str(&range->prefix,buf,sizeof(buf));vty
_out(vty,"area%srange%s",oa->name,buf);if(CHECK_FLAG(range->flag,OSPF6_ROUTE_DO_
NOT_ADVERTISE)){vty_out(vty,"not-advertise");}else{//"advertise"isthedefaultsowe
donot//displayitif(range->path.u.cost_config!=OSPF_AREA_RANGE_COST_UNSPEC)vty_ou
t(vty,"cost%d",range->path.u.cost_config);}vty_out(vty,"\n");}if(IS_AREA_STUB(oa
)){if(oa->no_summary)vty_out(vty,"area%sstubno-summary\n",oa->name);elsevty_out(
vty,"area%sstub\n",oa->name);}if(PREFIX_NAME_IN(oa))vty_out(vty,"area%sfilter-li
stprefix%sin\n",oa->name,PREFIX_NAME_IN(oa));if(PREFIX_NAME_OUT(oa))vty_out(vty,
"area%sfilter-listprefix%sout\n",oa->name,PREFIX_NAME_OUT(oa));if(IMPORT_NAME(oa
))vty_out(vty,"area%simport-list%s\n",oa->name,IMPORT_NAME(oa));if(EXPORT_NAME(o
a))vty_out(vty,"area%sexport-list%s\n",oa->name,EXPORT_NAME(oa));}}DEFUN(area_fi
lter_list,area_filter_list_cmd,"areaA.B.C.Dfilter-listprefixWORD<in|out>","OSPF6
areaparameters\n""OSPF6areaIDinIPaddressformat\n""FilternetworksbetweenOSPF6area
s\n""FilterprefixesbetweenOSPF6areas\n""NameofanIPv6prefix-list\n""Filternetwork
ssenttothisarea\n""Filternetworkssentfromthisarea\n"){char*inout=argv[argc-1]->t
ext;char*areaid=argv[1]->arg;char*plistname=argv[4]->arg;structospf6_area*area;s
tructprefix_list*plist;OSPF6_CMD_AREA_GET(areaid,area);plist=prefix_list_lookup(
AFI_IP6,plistname);if(strmatch(inout,"in")){PREFIX_LIST_IN(area)=plist;XFREE(MTY
PE_OSPF6_PLISTNAME,PREFIX_NAME_IN(area));PREFIX_NAME_IN(area)=XSTRDUP(MTYPE_OSPF
6_PLISTNAME,plistname);ospf6_abr_reimport(area);}else{PREFIX_LIST_OUT(area)=plis
t;XFREE(MTYPE_OSPF6_PLISTNAME,PREFIX_NAME_OUT(area));PREFIX_NAME_OUT(area)=XSTRD
UP(MTYPE_OSPF6_PLISTNAME,plistname);ospf6_abr_enable_area(area);}returnCMD_SUCCE
SS;}DEFUN(no_area_filter_list,no_area_filter_list_cmd,"noareaA.B.C.Dfilter-listp
refixWORD<in|out>",NO_STR"OSPF6areaparameters\n""OSPF6areaIDinIPaddressformat\n"
"FilternetworksbetweenOSPF6areas\n""FilterprefixesbetweenOSPF6areas\n""NameofanI
Pv6prefix-list\n""Filternetworkssenttothisarea\n""Filternetworkssentfromthisarea
\n"){char*inout=argv[argc-1]->text;char*areaid=argv[2]->arg;char*plistname=argv[
5]->arg;structospf6_area*area;OSPF6_CMD_AREA_GET(areaid,area);if(strmatch(inout,
"in")){if(PREFIX_NAME_IN(area))if(!strmatch(PREFIX_NAME_IN(area),plistname))retu
rnCMD_SUCCESS;PREFIX_LIST_IN(area)=NULL;XFREE(MTYPE_OSPF6_PLISTNAME,PREFIX_NAME_
IN(area));ospf6_abr_reimport(area);}else{if(PREFIX_NAME_OUT(area))if(!strmatch(P
REFIX_NAME_OUT(area),plistname))returnCMD_SUCCESS;XFREE(MTYPE_OSPF6_PLISTNAME,PR
EFIX_NAME_OUT(area));ospf6_abr_enable_area(area);}returnCMD_SUCCESS;}voidospf6_a
rea_plist_update(structprefix_list*plist,intadd){structospf6_area*oa;structlistn
ode*n;constchar*name=prefix_list_name(plist);if(!ospf6)return;for(ALL_LIST_ELEME
NTS_RO(ospf6->area_list,n,oa)){if(PREFIX_NAME_IN(oa)&&!strcmp(PREFIX_NAME_IN(oa)
,name))PREFIX_LIST_IN(oa)=add?plist:NULL;if(PREFIX_NAME_OUT(oa)&&!strcmp(PREFIX_
NAME_OUT(oa),name))PREFIX_LIST_OUT(oa)=add?plist:NULL;}}DEFUN(area_import_list,a
rea_import_list_cmd,"areaA.B.C.Dimport-listNAME","OSPF6areaparameters\n""OSPF6ar
eaIDinIPaddressformat\n""Setthefilterfornetworksfromotherareasannouncedtothespec
ifiedone\n""Nameoftheacess-list\n"){intidx_ipv4=1;intidx_name=3;structospf6_area
*area;structaccess_list*list;OSPF6_CMD_AREA_GET(argv[idx_ipv4]->arg,area);list=a
ccess_list_lookup(AFI_IP6,argv[idx_name]->arg);IMPORT_LIST(area)=list;if(IMPORT_
NAME(area))free(IMPORT_NAME(area));IMPORT_NAME(area)=strdup(argv[idx_name]->arg)
;ospf6_abr_reimport(area);returnCMD_SUCCESS;}DEFUN(no_area_import_list,no_area_i
mport_list_cmd,"noareaA.B.C.Dimport-listNAME",NO_STR"OSPF6areaparameters\n""OSPF
6areaIDinIPaddressformat\n""Unsetthefilterfornetworksannouncedtootherareas\n""Na
meoftheaccess-list\n"){intidx_ipv4=2;structospf6_area*area;OSPF6_CMD_AREA_GET(ar
gv[idx_ipv4]->arg,area);IMPORT_LIST(area)=0;if(IMPORT_NAME(area))free(IMPORT_NAM
E(area));IMPORT_NAME(area)=NULL;ospf6_abr_reimport(area);returnCMD_SUCCESS;}DEFU
N(area_export_list,area_export_list_cmd,"areaA.B.C.Dexport-listNAME","OSPF6areap
arameters\n""OSPF6areaIDinIPaddressformat\n""Setthefilterfornetworksannouncedtoo
therareas\n""Nameoftheacess-list\n"){intidx_ipv4=1;intidx_name=3;structospf6_are
a*area;structaccess_list*list;OSPF6_CMD_AREA_GET(argv[idx_ipv4]->arg,area);list=
access_list_lookup(AFI_IP6,argv[idx_name]->arg);EXPORT_LIST(area)=list;if(EXPORT
_NAME(area))free(EXPORT_NAME(area));EXPORT_NAME(area)=strdup(argv[idx_name]->arg
);ospf6_abr_enable_area(area);returnCMD_SUCCESS;}DEFUN(no_area_export_list,no_ar
ea_export_list_cmd,"noareaA.B.C.Dexport-listNAME",NO_STR"OSPF6areaparameters\n""
OSPF6areaIDinIPaddressformat\n""Unsetthefilterfornetworksannouncedtootherareas\n
""Nameoftheaccess-list\n"){intidx_ipv4=2;structospf6_area*area;OSPF6_CMD_AREA_GE
T(argv[idx_ipv4]->arg,area);EXPORT_LIST(area)=0;if(EXPORT_NAME(area))free(EXPORT
_NAME(area));EXPORT_NAME(area)=NULL;ospf6_abr_enable_area(area);returnCMD_SUCCES
S;}DEFUN(show_ipv6_ospf6_spf_tree,show_ipv6_ospf6_spf_tree_cmd,"showipv6ospf6spf
tree",SHOW_STRIP6_STROSPF6_STR"ShortestPathFirstcaculation\n""ShowSPFtree\n"){st
ructlistnode*node;structospf6_area*oa;structospf6_vertex*root;structospf6_route*
route;structprefixprefix;OSPF6_CMD_CHECK_RUNNING();ospf6_linkstate_prefix(ospf6-
>router_id,htonl(0),&prefix);for(ALL_LIST_ELEMENTS_RO(ospf6->area_list,node,oa))
{route=ospf6_route_lookup(&prefix,oa->spf_table);if(route==NULL){vty_out(vty,"LS
entryforrootnotfoundinarea%s\n",oa->name);continue;}root=(structospf6_vertex*)ro
ute->route_option;ospf6_spf_display_subtree(vty,"",0,root);}returnCMD_SUCCESS;}D
EFUN(show_ipv6_ospf6_area_spf_tree,show_ipv6_ospf6_area_spf_tree_cmd,"showipv6os
pf6areaA.B.C.Dspftree",SHOW_STRIP6_STROSPF6_STROSPF6_AREA_STROSPF6_AREA_ID_STR"S
hortestPathFirstcaculation\n""ShowSPFtree\n"){intidx_ipv4=4;uint32_tarea_id;stru
ctospf6_area*oa;structospf6_vertex*root;structospf6_route*route;structprefixpref
ix;OSPF6_CMD_CHECK_RUNNING();ospf6_linkstate_prefix(ospf6->router_id,htonl(0),&p
refix);if(inet_pton(AF_INET,argv[idx_ipv4]->arg,&area_id)!=1){vty_out(vty,"Malfo
rmedArea-ID:%s\n",argv[idx_ipv4]->arg);returnCMD_SUCCESS;}oa=ospf6_area_lookup(a
rea_id,ospf6);if(oa==NULL){vty_out(vty,"NosuchArea:%s\n",argv[idx_ipv4]->arg);re
turnCMD_SUCCESS;}route=ospf6_route_lookup(&prefix,oa->spf_table);if(route==NULL)
{vty_out(vty,"LSentryforrootnotfoundinarea%s\n",oa->name);returnCMD_SUCCESS;}roo
t=(structospf6_vertex*)route->route_option;ospf6_spf_display_subtree(vty,"",0,ro
ot);returnCMD_SUCCESS;}DEFUN(show_ipv6_ospf6_simulate_spf_tree_root,show_ipv6_os
pf6_simulate_spf_tree_root_cmd,"showipv6ospf6simulatespf-treeA.B.C.DareaA.B.C.D"
,SHOW_STRIP6_STROSPF6_STR"ShortestPathFirstcalculation\n""ShowSPFtree\n""Specify
root'srouter-idtocalculateanotherrouter'sSPFtree\n""OSPF6areaparameters\n"OSPF6_
AREA_ID_STR){intidx_ipv4=5;intidx_ipv4_2=7;uint32_tarea_id;structospf6_area*oa;s
tructospf6_vertex*root;structospf6_route*route;structprefixprefix;uint32_trouter
_id;structospf6_route_table*spf_table;unsignedchartmp_debug_ospf6_spf=0;OSPF6_CM
D_CHECK_RUNNING();inet_pton(AF_INET,argv[idx_ipv4]->arg,&router_id);ospf6_linkst
ate_prefix(router_id,htonl(0),&prefix);if(inet_pton(AF_INET,argv[idx_ipv4_2]->ar
g,&area_id)!=1){vty_out(vty,"MalformedArea-ID:%s\n",argv[idx_ipv4_2]->arg);retur
nCMD_SUCCESS;}oa=ospf6_area_lookup(area_id,ospf6);if(oa==NULL){vty_out(vty,"Nosu
chArea:%s\n",argv[idx_ipv4_2]->arg);returnCMD_SUCCESS;}tmp_debug_ospf6_spf=conf_
debug_ospf6_spf;conf_debug_ospf6_spf=0;spf_table=OSPF6_ROUTE_TABLE_CREATE(NONE,S
PF_RESULTS);ospf6_spf_calculation(router_id,spf_table,oa);conf_debug_ospf6_spf=t
mp_debug_ospf6_spf;route=ospf6_route_lookup(&prefix,spf_table);if(route==NULL){o
spf6_spf_table_finish(spf_table);ospf6_route_table_delete(spf_table);returnCMD_S
UCCESS;}root=(structospf6_vertex*)route->route_option;ospf6_spf_display_subtree(
vty,"",0,root);ospf6_spf_table_finish(spf_table);ospf6_route_table_delete(spf_ta
ble);returnCMD_SUCCESS;}DEFUN(ospf6_area_stub,ospf6_area_stub_cmd,"area<A.B.C.D|
(0-4294967295)>stub","OSPF6areaparameters\n""OSPF6areaIDinIPaddressformat\n""OSP
F6areaIDasadecimalvalue\n""ConfigureOSPF6areaasstub\n"){intidx_ipv4_number=1;str
uctospf6_area*area;OSPF6_CMD_AREA_GET(argv[idx_ipv4_number]->arg,area);if(!ospf6
_area_stub_set(ospf6,area)){vty_out(vty,"Firstdeconfigureallvirtuallinkthroughth
isarea\n");returnCMD_WARNING_CONFIG_FAILED;}ospf6_area_no_summary_unset(ospf6,ar
ea);returnCMD_SUCCESS;}DEFUN(ospf6_area_stub_no_summary,ospf6_area_stub_no_summa
ry_cmd,"area<A.B.C.D|(0-4294967295)>stubno-summary","OSPF6stubparameters\n""OSPF
6areaIDinIPaddressformat\n""OSPF6areaIDasadecimalvalue\n""ConfigureOSPF6areaasst
ub\n""Donotinjectinter-arearoutesintostub\n"){intidx_ipv4_number=1;structospf6_a
rea*area;OSPF6_CMD_AREA_GET(argv[idx_ipv4_number]->arg,area);if(!ospf6_area_stub
_set(ospf6,area)){vty_out(vty,"Firstdeconfigureallvirtuallinkthroughthisarea\n")
;returnCMD_WARNING_CONFIG_FAILED;}ospf6_area_no_summary_set(ospf6,area);returnCM
D_SUCCESS;}DEFUN(no_ospf6_area_stub,no_ospf6_area_stub_cmd,"noarea<A.B.C.D|(0-42
94967295)>stub",NO_STR"OSPF6areaparameters\n""OSPF6areaIDinIPaddressformat\n""OS
PF6areaIDasadecimalvalue\n""ConfigureOSPF6areaasstub\n"){intidx_ipv4_number=2;st
ructospf6_area*area;OSPF6_CMD_AREA_GET(argv[idx_ipv4_number]->arg,area);ospf6_ar
ea_stub_unset(ospf6,area);ospf6_area_no_summary_unset(ospf6,area);returnCMD_SUCC
ESS;}DEFUN(no_ospf6_area_stub_no_summary,no_ospf6_area_stub_no_summary_cmd,"noar
ea<A.B.C.D|(0-4294967295)>stubno-summary",NO_STR"OSPF6areaparameters\n""OSPF6are
aIDinIPaddressformat\n""OSPF6areaIDasadecimalvalue\n""ConfigureOSPF6areaasstub\n
""Donotinjectinter-arearoutesintoarea\n"){intidx_ipv4_number=2;structospf6_area*
area;OSPF6_CMD_AREA_GET(argv[idx_ipv4_number]->arg,area);ospf6_area_stub_unset(o
spf6,area);ospf6_area_no_summary_unset(ospf6,area);returnCMD_SUCCESS;}voidospf6_
area_init(void){install_element(VIEW_NODE,&show_ipv6_ospf6_spf_tree_cmd);install
_element(VIEW_NODE,&show_ipv6_ospf6_area_spf_tree_cmd);install_element(VIEW_NODE
,&show_ipv6_ospf6_simulate_spf_tree_root_cmd);install_element(OSPF6_NODE,&area_r
ange_cmd);install_element(OSPF6_NODE,&no_area_range_cmd);install_element(OSPF6_N
ODE,&ospf6_area_stub_no_summary_cmd);install_element(OSPF6_NODE,&ospf6_area_stub
_cmd);install_element(OSPF6_NODE,&no_ospf6_area_stub_no_summary_cmd);install_ele
ment(OSPF6_NODE,&no_ospf6_area_stub_cmd);install_element(OSPF6_NODE,&area_import
_list_cmd);install_element(OSPF6_NODE,&no_area_import_list_cmd);install_element(
OSPF6_NODE,&area_export_list_cmd);install_element(OSPF6_NODE,&no_area_export_lis
t_cmd);install_element(OSPF6_NODE,&area_filter_list_cmd);install_element(OSPF6_N
ODE,&no_area_filter_list_cmd);}