/**Copyright(C)2003YasuhiroOhara**ThisfileispartofGNUZebra.**GNUZebraisfreesoftw
are;youcanredistributeitand/ormodifyit*underthetermsoftheGNUGeneralPublicLicense
aspublishedbythe*FreeSoftwareFoundation;eitherversion2,or(atyouroption)any*later
version.**GNUZebraisdistributedinthehopethatitwillbeuseful,but*WITHOUTANYWARRANT
Y;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.
SeetheGNU*GeneralPublicLicenseformoredetails.**YoushouldhavereceivedacopyoftheGN
UGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;ifnot,writetotheFre
eSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-1301USA*/#inclu
de<zebra.h>#include"log.h"#include"memory.h"#include"prefix.h"#include"command.h
"#include"vty.h"#include"routemap.h"#include"table.h"#include"plist.h"#include"t
hread.h"#include"linklist.h"#include"ospf6_proto.h"#include"ospf6_lsa.h"#include
"ospf6_lsdb.h"#include"ospf6_route.h"#include"ospf6_zebra.h"#include"ospf6_messa
ge.h"#include"ospf6_top.h"#include"ospf6_area.h"#include"ospf6_interface.h"#incl
ude"ospf6_neighbor.h"#include"ospf6_asbr.h"#include"ospf6_intra.h"#include"ospf6
_flood.h"#include"ospf6d.h"unsignedcharconf_debug_ospf6_asbr=0;#defineZROUTE_NAM
E(x)zebra_route_string(x)/*ASExternalLSAorigination*/staticvoidospf6_as_external
_lsa_originate(structospf6_route*route){charbuffer[OSPF6_MAX_LSASIZE];structospf
6_lsa_header*lsa_header;structospf6_lsa*lsa;structospf6_external_info*info=route
->route_option;structospf6_as_external_lsa*as_external_lsa;charbuf[PREFIX2STR_BU
FFER];caddr_tp;if(IS_OSPF6_DEBUG_ASBR||IS_OSPF6_DEBUG_ORIGINATE(AS_EXTERNAL)){pr
efix2str(&route->prefix,buf,sizeof(buf));zlog_debug("OriginateAS-External-LSAfor
%s",buf);}/*preparebuffer*/memset(buffer,0,sizeof(buffer));lsa_header=(structosp
f6_lsa_header*)buffer;as_external_lsa=(structospf6_as_external_lsa*)((caddr_t)ls
a_header+sizeof(structospf6_lsa_header));p=(caddr_t)((caddr_t)as_external_lsa+si
zeof(structospf6_as_external_lsa));/*FillAS-External-LSA*//*Metrictype*/if(route
->path.metric_type==2)SET_FLAG(as_external_lsa->bits_metric,OSPF6_ASBR_BIT_E);el
seUNSET_FLAG(as_external_lsa->bits_metric,OSPF6_ASBR_BIT_E);/*forwardingaddress*
/if(!IN6_IS_ADDR_UNSPECIFIED(&info->forwarding))SET_FLAG(as_external_lsa->bits_m
etric,OSPF6_ASBR_BIT_F);elseUNSET_FLAG(as_external_lsa->bits_metric,OSPF6_ASBR_B
IT_F);/*externalroutetag*/if(info->tag)SET_FLAG(as_external_lsa->bits_metric,OSP
F6_ASBR_BIT_T);elseUNSET_FLAG(as_external_lsa->bits_metric,OSPF6_ASBR_BIT_T);/*S
etmetric*/OSPF6_ASBR_METRIC_SET(as_external_lsa,route->path.cost);/*prefixlen*/a
s_external_lsa->prefix.prefix_length=route->prefix.prefixlen;/*PrefixOptions*/as
_external_lsa->prefix.prefix_options=route->path.prefix_options;/*don'tusereferL
S-type*/as_external_lsa->prefix.prefix_refer_lstype=htons(0);/*setPrefix*/memcpy
(p,&route->prefix.u.prefix6,OSPF6_PREFIX_SPACE(route->prefix.prefixlen));ospf6_p
refix_apply_mask(&as_external_lsa->prefix);p+=OSPF6_PREFIX_SPACE(route->prefix.p
refixlen);/*Forwardingaddress*/if(CHECK_FLAG(as_external_lsa->bits_metric,OSPF6_
ASBR_BIT_F)){memcpy(p,&info->forwarding,sizeof(structin6_addr));p+=sizeof(struct
in6_addr);}/*ExternalRouteTag*/if(CHECK_FLAG(as_external_lsa->bits_metric,OSPF6_
ASBR_BIT_T)){route_tag_tnetwork_order=htonl(info->tag);memcpy(p,&network_order,s
izeof(network_order));p+=sizeof(network_order);}/*FillLSAHeader*/lsa_header->age
=0;lsa_header->type=htons(OSPF6_LSTYPE_AS_EXTERNAL);lsa_header->id=route->path.o
rigin.id;lsa_header->adv_router=ospf6->router_id;lsa_header->seqnum=ospf6_new_ls
_seqnum(lsa_header->type,lsa_header->id,lsa_header->adv_router,ospf6->lsdb);lsa_
header->length=htons((caddr_t)p-(caddr_t)lsa_header);/*LSAchecksum*/ospf6_lsa_ch
ecksum(lsa_header);/*createLSA*/lsa=ospf6_lsa_create(lsa_header);/*Originate*/os
pf6_lsa_originate_process(lsa,ospf6);}intospf6_orig_as_external_lsa(structthread
*thread){structospf6_interface*oi;structospf6_lsa*lsa;uint32_ttype,adv_router;oi
=(structospf6_interface*)THREAD_ARG(thread);oi->thread_as_extern_lsa=NULL;if(oi-
>state==OSPF6_INTERFACE_DOWN)return0;type=htons(OSPF6_LSTYPE_AS_EXTERNAL);adv_ro
uter=oi->area->ospf6->router_id;for(ALL_LSDB_TYPED_ADVRTR(ospf6->lsdb,type,adv_r
outer,lsa)){if(IS_OSPF6_DEBUG_ASBR)zlog_debug("%s:SendupdateofAS-ExternalLSA%sse
q0x%x",__PRETTY_FUNCTION__,lsa->name,ntohl(lsa->header->seqnum));ospf6_flood_int
erface(NULL,lsa,oi);}return0;}staticroute_tag_tospf6_as_external_lsa_get_tag(str
uctospf6_lsa*lsa){structospf6_as_external_lsa*external;ptrdiff_ttag_offset;route
_tag_tnetwork_order;if(!lsa)return0;external=(structospf6_as_external_lsa*)OSPF6
_LSA_HEADER_END(lsa->header);if(!CHECK_FLAG(external->bits_metric,OSPF6_ASBR_BIT
_T))return0;tag_offset=sizeof(*external)+OSPF6_PREFIX_SPACE(external->prefix.pre
fix_length);if(CHECK_FLAG(external->bits_metric,OSPF6_ASBR_BIT_F))tag_offset+=si
zeof(structin6_addr);memcpy(&network_order,(caddr_t)external+tag_offset,sizeof(n
etwork_order));returnntohl(network_order);}voidospf6_asbr_update_route_ecmp_path
(structospf6_route*old,structospf6_route*route){structospf6_route*old_route;stru
ctospf6_path*ecmp_path,*o_path=NULL;structlistnode*anode,*anext;structlistnode*n
node,*rnode,*rnext;structospf6_nexthop*nh,*rnh;charbuf[PREFIX2STR_BUFFER];boolro
ute_found=false;/*checkforoldentrymatchwithnewrouteorigin,*deleteoldentry.*/for(
old_route=old;old_route;old_route=old_route->next){boolroute_updated=false;if(!o
spf6_route_is_same(old_route,route)||(old_route->path.type!=route->path.type))co
ntinue;/*CurrentandNewroutehassameorigin,*deleteoldentry.*/for(ALL_LIST_ELEMENTS
(old_route->paths,anode,anext,o_path)){/*Checkoldroutepathandroutehassame*origin
.*/if(o_path->area_id!=route->path.area_id||(memcmp(&(o_path)->origin,&(route)->
path.origin,sizeof(structospf6_ls_origin))!=0))continue;/*Costisnotsamethendelet
ecurrentpath*/if((o_path->cost==route->path.cost)&&(o_path->u.cost_e2==route->pa
th.u.cost_e2))continue;if(IS_OSPF6_DEBUG_EXAMIN(AS_EXTERNAL)){prefix2str(&old_ro
ute->prefix,buf,sizeof(buf));zlog_debug("%s:route%scostold%unew%uisnotsame,repla
ceroute",__PRETTY_FUNCTION__,buf,o_path->cost,route->path.cost);}/*Removeselecte
dcurrentroutpath'snhfrom*effectivenhlist.*/for(ALL_LIST_ELEMENTS_RO(o_path->nh_l
ist,nnode,nh)){for(ALL_LIST_ELEMENTS(old_route->nh_list,rnode,rnext,rnh)){if(!os
pf6_nexthop_is_same(rnh,nh))continue;listnode_delete(old_route->nh_list,rnh);osp
f6_nexthop_delete(rnh);route_updated=true;}}listnode_delete(old_route->paths,o_p
ath);ospf6_path_free(o_path);/*Currentroute'spath(adv_routerinfo)issimilar*torou
tebeingadded.*Replacecurrentroute'spathwithpathslisthead.*UpdateFIBwitheffective
NHs.*/if(listcount(old_route->paths)){if(old_route->path.origin.id==route->path.
origin.id&&old_route->path.origin.adv_router==route->path.origin.adv_router){str
uctospf6_path*h_path;h_path=(structospf6_path*)listgetdata(listhead(old_route->p
aths));old_route->path.origin.type=h_path->origin.type;old_route->path.origin.id
=h_path->origin.id;old_route->path.origin.adv_router=h_path->origin.adv_router;}
if(route_updated){for(ALL_LIST_ELEMENTS(old_route->paths,anode,anext,o_path)){os
pf6_merge_nexthops(old_route->nh_list,o_path->nh_list);}/*UpdateRIB/FIBwitheffec
tive*nh_list*/if(ospf6->route_table->hook_add)(*ospf6->route_table->hook_add)(ol
d_route);break;}}else{if(IS_OSPF6_DEBUG_EXAMIN(AS_EXTERNAL)){prefix2str(&old_rou
te->prefix,buf,sizeof(buf));zlog_debug("%s:route%soldcost%unewcost%u,deleteolden
try.",__PRETTY_FUNCTION__,buf,old_route->path.cost,route->path.cost);}ospf6_rout
e_remove(old_route,ospf6->route_table);break;}}if(route_updated)break;}/*Addnewr
oute*/for(old_route=old;old_route;old_route=old_route->next){/*CurrentandNewRout
eprefixorroutetype*isnotsameskipthiscurrentnode.*/if(!ospf6_route_is_same(old_ro
ute,route)||(old_route->path.type!=route->path.type))continue;/*OldRouteandNewRo
utehaveEqualCost,MergeNHs*/if((old_route->path.cost==route->path.cost)&&(old_rou
te->path.u.cost_e2==route->path.u.cost_e2)){if(IS_OSPF6_DEBUG_EXAMIN(AS_EXTERNAL
)){prefix2str(&old_route->prefix,buf,sizeof(buf));zlog_debug("%s:oldroute%spathc
ost%ue2%u",__PRETTY_FUNCTION__,buf,old_route->path.cost,old_route->path.u.cost_e
2);}route_found=true;/*checkifthispathexistsalreadyin*route->pathslist,ifso,repl
acenh_list*fromasbr_entry.*/for(ALL_LIST_ELEMENTS_RO(old_route->paths,anode,o_pa
th)){if(o_path->area_id==route->path.area_id&&(memcmp(&(o_path)->origin,&(route)
->path.origin,sizeof(structospf6_ls_origin))==0))break;}/*Ifpathisnotfoundinold_
routepaths'slist,*addanewpathtoroutepathslistandmerge*nexthopsinroute->path->nh_
list.*Otherwisereplaceexistingpath'snh_list.*/if(o_path==NULL){ecmp_path=ospf6_p
ath_dup(&route->path);/*Addanh_listtonewecmppath*/ospf6_copy_nexthops(ecmp_path-
>nh_list,route->nh_list);/*Mergenexthoptoexistingroute'snh_list*/ospf6_route_mer
ge_nexthops(old_route,route);/*UpdateRIB/FIB*/if(ospf6->route_table->hook_add)(*
ospf6->route_table->hook_add)(old_route);/*Addthenewpathtoroute'spathlist*/listn
ode_add_sort(old_route->paths,ecmp_path);if(IS_OSPF6_DEBUG_EXAMIN(AS_EXTERNAL)){
prefix2str(&route->prefix,buf,sizeof(buf));zlog_debug("%s:route%sanotherpathadde
dwithnh%u,effectivepaths%unh%u",__PRETTY_FUNCTION__,buf,listcount(ecmp_path->nh_
list),old_route->paths?listcount(old_route->paths):0,listcount(old_route->nh_lis
t));}}else{for(ALL_LIST_ELEMENTS_RO(o_path->nh_list,nnode,nh)){for(ALL_LIST_ELEM
ENTS(old_route->nh_list,rnode,rnext,rnh)){if(!ospf6_nexthop_is_same(rnh,nh))cont
inue;listnode_delete(old_route->nh_list,rnh);ospf6_nexthop_delete(rnh);}}list_de
lete_all_node(o_path->nh_list);ospf6_copy_nexthops(o_path->nh_list,route->nh_lis
t);/*Mergenexthoptoexistingroute'snh_list*/ospf6_route_merge_nexthops(old_route,
route);if(IS_OSPF6_DEBUG_EXAMIN(AS_EXTERNAL)){prefix2str(&route->prefix,buf,size
of(buf));zlog_debug("%s:existingroute%switheffectivenhcount%u",__PRETTY_FUNCTION
__,buf,old_route->nh_list?listcount(old_route->nh_list):0);}/*UpdateRIB/FIB*/if(
ospf6->route_table->hook_add)(*ospf6->route_table->hook_add)(old_route);}/*Delet
ethenewrouteitsinfoaddedtoexisting*route.*/ospf6_route_delete(route);break;}}if(
!route_found){/*Addnewroutetoexistingnodeinospf6routetable.*/ospf6_route_add(rou
te,ospf6->route_table);}}voidospf6_asbr_lsa_add(structospf6_lsa*lsa){structospf6
_as_external_lsa*external;structprefixasbr_id;structospf6_route*asbr_entry,*rout
e,*old;structospf6_path*path;charbuf[PREFIX2STR_BUFFER];external=(structospf6_as
_external_lsa*)OSPF6_LSA_HEADER_END(lsa->header);if(IS_OSPF6_DEBUG_EXAMIN(AS_EXT
ERNAL))zlog_debug("CalculateAS-Externalroutefor%s",lsa->name);if(lsa->header->ad
v_router==ospf6->router_id){if(IS_OSPF6_DEBUG_EXAMIN(AS_EXTERNAL))zlog_debug("Ig
noreself-originatedAS-External-LSA");return;}if(OSPF6_ASBR_METRIC(external)==OSP
F_LS_INFINITY){if(IS_OSPF6_DEBUG_EXAMIN(AS_EXTERNAL))zlog_debug("IgnoreLSAwithLS
InfinityMetric");return;}if(CHECK_FLAG(external->prefix.prefix_options,OSPF6_PRE
FIX_OPTION_NU)){if(IS_OSPF6_DEBUG_EXAMIN(AS_EXTERNAL))zlog_debug("IgnoreLSAwithN
UbitsetMetric");return;}ospf6_linkstate_prefix(lsa->header->adv_router,htonl(0),
&asbr_id);asbr_entry=ospf6_route_lookup(&asbr_id,ospf6->brouter_table);if(asbr_e
ntry==NULL||!CHECK_FLAG(asbr_entry->path.router_bits,OSPF6_ROUTER_BIT_E)){if(IS_
OSPF6_DEBUG_EXAMIN(AS_EXTERNAL)){prefix2str(&asbr_id,buf,sizeof(buf));zlog_debug
("ASBRentrynotfound:%s",buf);}return;}route=ospf6_route_create();route->type=OSP
F6_DEST_TYPE_NETWORK;route->prefix.family=AF_INET6;route->prefix.prefixlen=exter
nal->prefix.prefix_length;ospf6_prefix_in6_addr(&route->prefix.u.prefix6,&extern
al->prefix);route->path.area_id=asbr_entry->path.area_id;route->path.origin.type
=lsa->header->type;route->path.origin.id=lsa->header->id;route->path.origin.adv_
router=lsa->header->adv_router;route->path.prefix_options=external->prefix.prefi
x_options;if(CHECK_FLAG(external->bits_metric,OSPF6_ASBR_BIT_E)){route->path.typ
e=OSPF6_PATH_TYPE_EXTERNAL2;route->path.metric_type=2;route->path.cost=asbr_entr
y->path.cost;route->path.u.cost_e2=OSPF6_ASBR_METRIC(external);}else{route->path
.type=OSPF6_PATH_TYPE_EXTERNAL1;route->path.metric_type=1;route->path.cost=asbr_
entry->path.cost+OSPF6_ASBR_METRIC(external);route->path.u.cost_e2=0;}route->pat
h.tag=ospf6_as_external_lsa_get_tag(lsa);ospf6_route_copy_nexthops(route,asbr_en
try);path=ospf6_path_dup(&route->path);ospf6_copy_nexthops(path->nh_list,asbr_en
try->nh_list);listnode_add_sort(route->paths,path);if(IS_OSPF6_DEBUG_EXAMIN(AS_E
XTERNAL)){prefix2str(&route->prefix,buf,sizeof(buf));zlog_debug("%s:AS-External%
urouteadd%scost%u(%u)nh%u",__PRETTY_FUNCTION__,(route->path.type==OSPF6_PATH_TYP
E_EXTERNAL1)?1:2,buf,route->path.cost,route->path.u.cost_e2,listcount(route->nh_
list));}old=ospf6_route_lookup(&route->prefix,ospf6->route_table);if(!old){/*Add
thenewroutetoospf6instanceroutetable.*/ospf6_route_add(route,ospf6->route_table)
;}else{/*RFC232816.4(6)*ECMP:Keepnewequalpreferencepathincurrent*route'spathlist
,updatezebrawithneweffective*listalongwithadditionofECMPpath.*/ospf6_asbr_update
_route_ecmp_path(old,route);}}voidospf6_asbr_lsa_remove(structospf6_lsa*lsa,stru
ctospf6_route*asbr_entry){structospf6_as_external_lsa*external;structprefixprefi
x;structospf6_route*route,*nroute,*route_to_del;charbuf[PREFIX2STR_BUFFER];exter
nal=(structospf6_as_external_lsa*)OSPF6_LSA_HEADER_END(lsa->header);if(IS_OSPF6_
DEBUG_EXAMIN(AS_EXTERNAL))zlog_debug("WithdrawAS-Externalroutefor%s",lsa->name);
if(lsa->header->adv_router==ospf6->router_id){if(IS_OSPF6_DEBUG_EXAMIN(AS_EXTERN
AL))zlog_debug("Ignoreself-originatedAS-External-LSA");return;}route_to_del=ospf
6_route_create();route_to_del->type=OSPF6_DEST_TYPE_NETWORK;route_to_del->prefix
.family=AF_INET6;route_to_del->prefix.prefixlen=external->prefix.prefix_length;o
spf6_prefix_in6_addr(&route_to_del->prefix.u.prefix6,&external->prefix);route_to
_del->path.origin.type=lsa->header->type;route_to_del->path.origin.id=lsa->heade
r->id;route_to_del->path.origin.adv_router=lsa->header->adv_router;if(asbr_entry
){route_to_del->path.area_id=asbr_entry->path.area_id;if(CHECK_FLAG(external->bi
ts_metric,OSPF6_ASBR_BIT_E)){route_to_del->path.type=OSPF6_PATH_TYPE_EXTERNAL2;r
oute_to_del->path.metric_type=2;route_to_del->path.cost=asbr_entry->path.cost;ro
ute_to_del->path.u.cost_e2=OSPF6_ASBR_METRIC(external);}else{route_to_del->path.
type=OSPF6_PATH_TYPE_EXTERNAL1;route_to_del->path.metric_type=1;route_to_del->pa
th.cost=asbr_entry->path.cost+OSPF6_ASBR_METRIC(external);route_to_del->path.u.c
ost_e2=0;}}memset(&prefix,0,sizeof(structprefix));prefix.family=AF_INET6;prefix.
prefixlen=external->prefix.prefix_length;ospf6_prefix_in6_addr(&prefix.u.prefix6
,&external->prefix);route=ospf6_route_lookup(&prefix,ospf6->route_table);if(rout
e==NULL){if(IS_OSPF6_DEBUG_EXAMIN(AS_EXTERNAL)){prefix2str(&prefix,buf,sizeof(bu
f));zlog_debug("AS-Externalroute%snotfound",buf);}ospf6_route_delete(route_to_de
l);return;}if(IS_OSPF6_DEBUG_EXAMIN(AS_EXTERNAL)){prefix2str(&prefix,buf,sizeof(
buf));zlog_debug("%s:Currentroute%scost%ue2%u,routetodelcost%ue2%u",__PRETTY_FUN
CTION__,buf,route->path.cost,route->path.u.cost_e2,route_to_del->path.cost,route
_to_del->path.u.cost_e2);}for(ospf6_route_lock(route);route&&ospf6_route_is_pref
ix(&prefix,route);route=nroute){nroute=ospf6_route_next(route);if(route->type!=O
SPF6_DEST_TYPE_NETWORK)continue;/*RoutehasmultipleECMPpaths,removematching*path.
Updatecurrentroute'seffectivenhlist*afterremovalofoneofthepath.*/if(listcount(ro
ute->paths)>1){structlistnode*anode,*anext;structlistnode*nnode,*rnode,*rnext;st
ructospf6_nexthop*nh,*rnh;structospf6_path*o_path;boolnh_updated=false;/*Iterate
allpathsofroutetofindmachingwithLSA*removefromroutepathlist.Ifroute->pathissame,
*replacefrompathslist.*/for(ALL_LIST_ELEMENTS(route->paths,anode,anext,o_path)){
if((o_path->origin.type!=lsa->header->type)||(o_path->origin.adv_router!=lsa->he
ader->adv_router)||(o_path->origin.id!=lsa->header->id))continue;/*CompareLSAcos
twithcurrent*routeinfo.*/if(!asbr_entry&&(o_path->cost!=route_to_del->path.cost|
|o_path->u.cost_e2!=route_to_del->path.u.cost_e2)){if(IS_OSPF6_DEBUG_EXAMIN(AS_E
XTERNAL)){prefix2str(&prefix,buf,sizeof(buf));zlog_debug("%s:route%stodeleteisno
tsame,cost%udelcost%u.skip",__PRETTY_FUNCTION__,buf,route->path.cost,route_to_de
l->path.cost);}continue;}if(IS_OSPF6_DEBUG_EXAMIN(AS_EXTERNAL)){prefix2str(&pref
ix,buf,sizeof(buf));zlog_debug("%s:route%spathfoundwithnh%utoremove.",__PRETTY_F
UNCTION__,buf,listcount(o_path->nh_list));}/*Removefoundpath'snh_listfrom*therou
te'snh_list.*/for(ALL_LIST_ELEMENTS_RO(o_path->nh_list,nnode,nh)){for(ALL_LIST_E
LEMENTS(route->nh_list,rnode,rnext,rnh)){if(!ospf6_nexthop_is_same(rnh,nh))conti
nue;listnode_delete(route->nh_list,rnh);ospf6_nexthop_delete(rnh);}}/*Deletethep
athfromroute'spathlist*/listnode_delete(route->paths,o_path);ospf6_path_free(o_p
ath);nh_updated=true;}if(nh_updated){/*Iterateallpathsandmergenexthop,*unlesssan
yofthenexthopsimilarto*onesdeletedaspartofpathdeletion.*/for(ALL_LIST_ELEMENTS(r
oute->paths,anode,anext,o_path)){ospf6_merge_nexthops(route->nh_list,o_path->nh_
list);}if(IS_OSPF6_DEBUG_EXAMIN(AS_EXTERNAL)){prefix2str(&route->prefix,buf,size
of(buf));zlog_debug("%s:AS-External%uroute%supdatepaths%unh%u",__PRETTY_FUNCTION
__,(route->path.type==OSPF6_PATH_TYPE_EXTERNAL1)?1:2,buf,listcount(route->paths)
,listcount(route->nh_list));}/*UpdateRIB/FIBwitheffectivenh_list*/if(ospf6->rout
e_table->hook_add)(*ospf6->route_table->hook_add)(route);/*route'sprimarypathiss
imilartoLSA,*replaceroute'sprimarypathwith*route'spathslisthead.*/if(route->path
.origin.id==lsa->header->id&&route->path.origin.adv_router==lsa->header->adv_rou
ter){structospf6_path*h_path;h_path=(structospf6_path*)listgetdata(listhead(rout
e->paths));route->path.origin.type=h_path->origin.type;route->path.origin.id=h_p
ath->origin.id;route->path.origin.adv_router=h_path->origin.adv_router;}}continu
e;}else{/*CompareLSAoriginandcostwithcurrentrouteinfo.*ifanycheckfailsskipdelthi
sroutenode.*/if(asbr_entry&&(!ospf6_route_is_same_origin(route,route_to_del)||(r
oute->path.type!=route_to_del->path.type)||(route->path.cost!=route_to_del->path
.cost)||(route->path.u.cost_e2!=route_to_del->path.u.cost_e2))){if(IS_OSPF6_DEBU
G_EXAMIN(AS_EXTERNAL)){prefix2str(&prefix,buf,sizeof(buf));zlog_debug("%s:route%
stodeleteisnotsame,cost%udelcost%u.skip",__PRETTY_FUNCTION__,buf,route->path.cos
t,route_to_del->path.cost);}continue;}if((route->path.origin.type!=lsa->header->
type)||(route->path.origin.adv_router!=lsa->header->adv_router)||(route->path.or
igin.id!=lsa->header->id))continue;}if(IS_OSPF6_DEBUG_EXAMIN(AS_EXTERNAL)){prefi
x2str(&route->prefix,buf,sizeof(buf));zlog_debug("%s:AS-External%urouteremove%sc
ost%u(%u)nh%u",__PRETTY_FUNCTION__,route->path.type==OSPF6_PATH_TYPE_EXTERNAL1?1
:2,buf,route->path.cost,route->path.u.cost_e2,listcount(route->nh_list));}ospf6_
route_remove(route,ospf6->route_table);}if(route!=NULL)ospf6_route_unlock(route)
;ospf6_route_delete(route_to_del);}voidospf6_asbr_lsentry_add(structospf6_route*
asbr_entry){structospf6_lsa*lsa;uint16_ttype;uint32_trouter;if(!CHECK_FLAG(asbr_
entry->flag,OSPF6_ROUTE_BEST)){charbuf[16];inet_ntop(AF_INET,&ADV_ROUTER_IN_PREF
IX(&asbr_entry->prefix),buf,sizeof(buf));zlog_info("ignorenon-bestpath:lsentry%s
add",buf);return;}type=htons(OSPF6_LSTYPE_AS_EXTERNAL);router=ospf6_linkstate_pr
efix_adv_router(&asbr_entry->prefix);for(ALL_LSDB_TYPED_ADVRTR(ospf6->lsdb,type,
router,lsa)){if(!OSPF6_LSA_IS_MAXAGE(lsa))ospf6_asbr_lsa_add(lsa);}}voidospf6_as
br_lsentry_remove(structospf6_route*asbr_entry){structospf6_lsa*lsa;uint16_ttype
;uint32_trouter;type=htons(OSPF6_LSTYPE_AS_EXTERNAL);router=ospf6_linkstate_pref
ix_adv_router(&asbr_entry->prefix);for(ALL_LSDB_TYPED_ADVRTR(ospf6->lsdb,type,ro
uter,lsa))ospf6_asbr_lsa_remove(lsa,asbr_entry);}/*redistributefunction*/staticv
oidospf6_asbr_routemap_set(inttype,constchar*mapname){if(ospf6->rmap[type].name)
free(ospf6->rmap[type].name);ospf6->rmap[type].name=strdup(mapname);ospf6->rmap[
type].map=route_map_lookup_by_name(mapname);}staticvoidospf6_asbr_routemap_unset
(inttype){if(ospf6->rmap[type].name)free(ospf6->rmap[type].name);ospf6->rmap[typ
e].name=NULL;ospf6->rmap[type].map=NULL;}staticintospf6_asbr_routemap_update_tim
er(structthread*thread){void**arg;intarg_type;arg=THREAD_ARG(thread);arg_type=(i
nt)(intptr_t)arg[1];ospf6->t_distribute_update=NULL;if(ospf6->rmap[arg_type].nam
e)ospf6->rmap[arg_type].map=route_map_lookup_by_name(ospf6->rmap[arg_type].name)
;if(ospf6->rmap[arg_type].map){if(IS_OSPF6_DEBUG_ASBR)zlog_debug("%s:route-map%s
update,resetredist%s",__PRETTY_FUNCTION__,ospf6->rmap[arg_type].name,ZROUTE_NAME
(arg_type));ospf6_zebra_no_redistribute(arg_type);ospf6_zebra_redistribute(arg_t
ype);}XFREE(MTYPE_OSPF6_DIST_ARGS,arg);return0;}voidospf6_asbr_distribute_list_u
pdate(inttype){void**args=NULL;if(ospf6->t_distribute_update)return;args=XCALLOC
(MTYPE_OSPF6_DIST_ARGS,sizeof(void*)*2);args[0]=ospf6;args[1]=(void*)((ptrdiff_t
)type);if(IS_OSPF6_DEBUG_ASBR)zlog_debug("%s:triggerredistribute%sresetthread",_
_PRETTY_FUNCTION__,ZROUTE_NAME(type));ospf6->t_distribute_update=NULL;thread_add
_timer_msec(master,ospf6_asbr_routemap_update_timer,(void**)args,OSPF_MIN_LS_INT
ERVAL,&ospf6->t_distribute_update);}staticvoidospf6_asbr_routemap_update(constch
ar*mapname){inttype;if(ospf6==NULL)return;for(type=0;type<ZEBRA_ROUTE_MAX;type++
){if(ospf6->rmap[type].name){ospf6->rmap[type].map=route_map_lookup_by_name(ospf
6->rmap[type].name);if(mapname&&ospf6->rmap[type].map&&(strcmp(ospf6->rmap[type]
.name,mapname)==0)){if(IS_OSPF6_DEBUG_ASBR)zlog_debug("%s:route-map%supdate,rese
tredist%s",__PRETTY_FUNCTION__,mapname,ZROUTE_NAME(type));ospf6_asbr_distribute_
list_update(type);}}elseospf6->rmap[type].map=NULL;}}staticvoidospf6_asbr_routem
ap_event(route_map_event_tevent,constchar*name){inttype;if(ospf6==NULL)return;fo
r(type=0;type<ZEBRA_ROUTE_MAX;type++){if((ospf6->rmap[type].name)&&(strcmp(ospf6
->rmap[type].name,name)==0)){ospf6_asbr_distribute_list_update(type);}}}intospf6
_asbr_is_asbr(structospf6*o){returno->external_table->count;}staticvoidospf6_asb
r_redistribute_set(inttype){ospf6_zebra_redistribute(type);}staticvoidospf6_asbr
_redistribute_unset(inttype){structospf6_route*route;structospf6_external_info*i
nfo;ospf6_zebra_no_redistribute(type);for(route=ospf6_route_head(ospf6->external
_table);route;route=ospf6_route_next(route)){info=route->route_option;if(info->t
ype!=type)continue;ospf6_asbr_redistribute_remove(info->type,0,&route->prefix);}
ospf6_asbr_routemap_unset(type);}/*Whenanareaisunstubified,floodalltheexternalLS
Asinthearea*/voidospf6_asbr_send_externals_to_area(structospf6_area*oa){structos
pf6_lsa*lsa;for(ALL_LSDB(oa->ospf6->lsdb,lsa)){if(ntohs(lsa->header->type)==OSPF
6_LSTYPE_AS_EXTERNAL){zlog_debug("%s:FloodingAS-ExternalLSA%s\n",__func__,lsa->n
ame);ospf6_flood_area(NULL,lsa,oa);}}}voidospf6_asbr_redistribute_add(inttype,if
index_tifindex,structprefix*prefix,unsignedintnexthop_num,structin6_addr*nexthop
,route_tag_ttag){intret;structospf6_routetroute;structospf6_external_infotinfo;s
tructospf6_route*route,*match;structospf6_external_info*info;structprefixprefix_
id;structroute_node*node;charpbuf[PREFIX2STR_BUFFER],ibuf[16];structlistnode*lno
de,*lnnode;structospf6_area*oa;if(!ospf6_zebra_is_redistribute(type))return;mems
et(&troute,0,sizeof(troute));memset(&tinfo,0,sizeof(tinfo));if(IS_OSPF6_DEBUG_AS
BR){prefix2str(prefix,pbuf,sizeof(pbuf));zlog_debug("Redistribute%s(%s)",pbuf,ZR
OUTE_NAME(type));}/*ifroute-mapwasspecifiedbutnotfound,donotadvertise*/if(ospf6-
>rmap[type].name){if(ospf6->rmap[type].map==NULL)ospf6_asbr_routemap_update(NULL
);if(ospf6->rmap[type].map==NULL){zlog_warn("route-map\"%s\"notfound,suppressred
istributing",ospf6->rmap[type].name);return;}}/*applyroute-map*/if(ospf6->rmap[t
ype].map){troute.route_option=&tinfo;tinfo.ifindex=ifindex;tinfo.tag=tag;ret=rou
te_map_apply(ospf6->rmap[type].map,prefix,RMAP_OSPF6,&troute);if(ret==RMAP_DENYM
ATCH){if(IS_OSPF6_DEBUG_ASBR)zlog_debug("Deniedbyroute-map\"%s\"",ospf6->rmap[ty
pe].name);return;}}match=ospf6_route_lookup(prefix,ospf6->external_table);if(mat
ch){info=match->route_option;/*copyresultofroute-map*/if(ospf6->rmap[type].map){
if(troute.path.metric_type)match->path.metric_type=troute.path.metric_type;if(tr
oute.path.cost)match->path.cost=troute.path.cost;if(!IN6_IS_ADDR_UNSPECIFIED(&ti
nfo.forwarding))memcpy(&info->forwarding,&tinfo.forwarding,sizeof(structin6_addr
));info->tag=tinfo.tag;}else{/*Ifthereisnoroute-map,simplyupdatethetag*/info->ta
g=tag;}info->type=type;if(nexthop_num&&nexthop)ospf6_route_add_nexthop(match,ifi
ndex,nexthop);elseospf6_route_add_nexthop(match,ifindex,NULL);/*create/updatebin
dinginexternal_id_table*/prefix_id.family=AF_INET;prefix_id.prefixlen=32;prefix_
id.u.prefix4.s_addr=htonl(info->id);node=route_node_get(ospf6->external_id_table
,&prefix_id);node->info=match;if(IS_OSPF6_DEBUG_ASBR){inet_ntop(AF_INET,&prefix_
id.u.prefix4,ibuf,sizeof(ibuf));prefix2str(prefix,pbuf,sizeof(pbuf));zlog_debug(
"AdvertiseasAS-ExternalId:%sprefix%smetric%u",ibuf,pbuf,match->path.metric_type)
;}match->path.origin.id=htonl(info->id);ospf6_as_external_lsa_originate(match);r
eturn;}/*createnewentry*/route=ospf6_route_create();route->type=OSPF6_DEST_TYPE_
NETWORK;memcpy(&route->prefix,prefix,sizeof(structprefix));info=(structospf6_ext
ernal_info*)XCALLOC(MTYPE_OSPF6_EXTERNAL_INFO,sizeof(structospf6_external_info))
;route->route_option=info;info->id=ospf6->external_id++;/*copyresultofroute-map*
/if(ospf6->rmap[type].map){if(troute.path.metric_type)route->path.metric_type=tr
oute.path.metric_type;if(troute.path.cost)route->path.cost=troute.path.cost;if(!
IN6_IS_ADDR_UNSPECIFIED(&tinfo.forwarding))memcpy(&info->forwarding,&tinfo.forwa
rding,sizeof(structin6_addr));info->tag=tinfo.tag;}else{/*Ifthereisnoroute-map,s
implysetthetag*/info->tag=tag;}info->type=type;if(nexthop_num&&nexthop)ospf6_rou
te_add_nexthop(route,ifindex,nexthop);elseospf6_route_add_nexthop(route,ifindex,
NULL);/*create/updatebindinginexternal_id_table*/prefix_id.family=AF_INET;prefix
_id.prefixlen=32;prefix_id.u.prefix4.s_addr=htonl(info->id);node=route_node_get(
ospf6->external_id_table,&prefix_id);node->info=route;route=ospf6_route_add(rout
e,ospf6->external_table);route->route_option=info;if(IS_OSPF6_DEBUG_ASBR){inet_n
top(AF_INET,&prefix_id.u.prefix4,ibuf,sizeof(ibuf));prefix2str(prefix,pbuf,sizeo
f(pbuf));zlog_debug("AdvertiseasAS-ExternalId:%sprefix%smetric%u",ibuf,pbuf,rout
e->path.metric_type);}route->path.origin.id=htonl(info->id);ospf6_as_external_ls
a_originate(route);/*Router-Bit(ASBRFlag)mayhavetobeupdated*/for(ALL_LIST_ELEMEN
TS(ospf6->area_list,lnode,lnnode,oa))OSPF6_ROUTER_LSA_SCHEDULE(oa);}voidospf6_as
br_redistribute_remove(inttype,ifindex_tifindex,structprefix*prefix){structospf6
_route*match;structospf6_external_info*info=NULL;structroute_node*node;structosp
f6_lsa*lsa;structprefixprefix_id;charpbuf[PREFIX2STR_BUFFER],ibuf[16];structlist
node*lnode,*lnnode;structospf6_area*oa;match=ospf6_route_lookup(prefix,ospf6->ex
ternal_table);if(match==NULL){if(IS_OSPF6_DEBUG_ASBR){prefix2str(prefix,pbuf,siz
eof(pbuf));zlog_debug("Nosuchroute%stowithdraw",pbuf);}return;}info=match->route
_option;assert(info);if(info->type!=type){if(IS_OSPF6_DEBUG_ASBR){prefix2str(pre
fix,pbuf,sizeof(pbuf));zlog_debug("Originalprotocolmismatch:%s",pbuf);}return;}i
f(IS_OSPF6_DEBUG_ASBR){prefix2str(prefix,pbuf,sizeof(pbuf));inet_ntop(AF_INET,&p
refix_id.u.prefix4,ibuf,sizeof(ibuf));zlog_debug("Withdraw%s(AS-ExternalId:%s)",
pbuf,ibuf);}lsa=ospf6_lsdb_lookup(htons(OSPF6_LSTYPE_AS_EXTERNAL),htonl(info->id
),ospf6->router_id,ospf6->lsdb);if(lsa)ospf6_lsa_purge(lsa);/*removebindinginext
ernal_id_table*/prefix_id.family=AF_INET;prefix_id.prefixlen=32;prefix_id.u.pref
ix4.s_addr=htonl(info->id);node=route_node_lookup(ospf6->external_id_table,&pref
ix_id);assert(node);node->info=NULL;route_unlock_node(node);/*tofreethelookuploc
k*/route_unlock_node(node);/*tofreetheoriginallock*/ospf6_route_remove(match,osp
f6->external_table);XFREE(MTYPE_OSPF6_EXTERNAL_INFO,info);/*Router-Bit(ASBRFlag)
mayhavetobeupdated*/for(ALL_LIST_ELEMENTS(ospf6->area_list,lnode,lnnode,oa))OSPF
6_ROUTER_LSA_SCHEDULE(oa);}DEFUN(ospf6_redistribute,ospf6_redistribute_cmd,"redi
stribute"FRR_REDIST_STR_OSPF6D,"Redistribute\n"FRR_REDIST_HELP_STR_OSPF6D){intty
pe;char*proto=argv[argc-1]->text;type=proto_redistnum(AFI_IP6,proto);if(type<0)r
eturnCMD_WARNING_CONFIG_FAILED;ospf6_asbr_redistribute_unset(type);ospf6_asbr_re
distribute_set(type);returnCMD_SUCCESS;}DEFUN(ospf6_redistribute_routemap,ospf6_
redistribute_routemap_cmd,"redistribute"FRR_REDIST_STR_OSPF6D"route-mapWORD","Re
distribute\n"FRR_REDIST_HELP_STR_OSPF6D"Routemapreference\n""Routemapname\n"){in
tidx_protocol=1;intidx_word=3;inttype;char*proto=argv[idx_protocol]->text;type=p
roto_redistnum(AFI_IP6,proto);if(type<0)returnCMD_WARNING_CONFIG_FAILED;ospf6_as
br_redistribute_unset(type);ospf6_asbr_routemap_set(type,argv[idx_word]->arg);os
pf6_asbr_redistribute_set(type);returnCMD_SUCCESS;}DEFUN(no_ospf6_redistribute,n
o_ospf6_redistribute_cmd,"noredistribute"FRR_REDIST_STR_OSPF6D"[route-mapWORD]",
NO_STR"Redistribute\n"FRR_REDIST_HELP_STR_OSPF6D"Routemapreference\n""Routemapna
me\n"){intidx_protocol=2;inttype;char*proto=argv[idx_protocol]->text;type=proto_
redistnum(AFI_IP6,proto);if(type<0)returnCMD_WARNING_CONFIG_FAILED;ospf6_asbr_re
distribute_unset(type);returnCMD_SUCCESS;}intospf6_redistribute_config_write(str
uctvty*vty){inttype;for(type=0;type<ZEBRA_ROUTE_MAX;type++){if(type==ZEBRA_ROUTE
_OSPF6)continue;if(!ospf6_zebra_is_redistribute(type))continue;if(ospf6->rmap[ty
pe].name)vty_out(vty,"redistribute%sroute-map%s\n",ZROUTE_NAME(type),ospf6->rmap
[type].name);elsevty_out(vty,"redistribute%s\n",ZROUTE_NAME(type));}return0;}sta
ticvoidospf6_redistribute_show_config(structvty*vty){inttype;intnroute[ZEBRA_ROU
TE_MAX];inttotal;structospf6_route*route;structospf6_external_info*info;total=0;
for(type=0;type<ZEBRA_ROUTE_MAX;type++)nroute[type]=0;for(route=ospf6_route_head
(ospf6->external_table);route;route=ospf6_route_next(route)){info=route->route_o
ption;nroute[info->type]++;total++;}vty_out(vty,"RedistributingExternalRoutesfro
m:\n");for(type=0;type<ZEBRA_ROUTE_MAX;type++){if(type==ZEBRA_ROUTE_OSPF6)contin
ue;if(!ospf6_zebra_is_redistribute(type))continue;if(ospf6->rmap[type].name)vty_
out(vty,"%d:%swithroute-map\"%s\"%s\n",nroute[type],ZROUTE_NAME(type),ospf6->rma
p[type].name,(ospf6->rmap[type].map?"":"(notfound!)"));elsevty_out(vty,"%d:%s\n"
,nroute[type],ZROUTE_NAME(type));}vty_out(vty,"Total%droutes\n",total);}/*Routem
apFunctions*/staticroute_map_result_tospf6_routemap_rule_match_address_prefixlis
t(void*rule,structprefix*prefix,route_map_object_ttype,void*object){structprefix
_list*plist;if(type!=RMAP_OSPF6)returnRMAP_NOMATCH;plist=prefix_list_lookup(AFI_
IP6,(char*)rule);if(plist==NULL)returnRMAP_NOMATCH;return(prefix_list_apply(plis
t,prefix)==PREFIX_DENY?RMAP_NOMATCH:RMAP_MATCH);}staticvoid*ospf6_routemap_rule_
match_address_prefixlist_compile(constchar*arg){returnXSTRDUP(MTYPE_ROUTE_MAP_CO
MPILED,arg);}staticvoidospf6_routemap_rule_match_address_prefixlist_free(void*ru
le){XFREE(MTYPE_ROUTE_MAP_COMPILED,rule);}structroute_map_rule_cmdospf6_routemap
_rule_match_address_prefixlist_cmd={"ipv6addressprefix-list",ospf6_routemap_rule
_match_address_prefixlist,ospf6_routemap_rule_match_address_prefixlist_compile,o
spf6_routemap_rule_match_address_prefixlist_free,};/*`matchinterfaceIFNAME'*//*M
atchfunctionshouldreturn1ifmatchissuccesselsereturnzero.*/staticroute_map_result
_tospf6_routemap_rule_match_interface(void*rule,structprefix*prefix,route_map_ob
ject_ttype,void*object){structinterface*ifp;structospf6_external_info*ei;if(type
==RMAP_OSPF6){ei=((structospf6_route*)object)->route_option;ifp=if_lookup_by_nam
e((char*)rule,VRF_DEFAULT);if(ifp!=NULL&&ei->ifindex==ifp->ifindex)returnRMAP_MA
TCH;}returnRMAP_NOMATCH;}/*Routemap`interface'matchstatement.`arg'shouldbeinterf
acename.*/staticvoid*ospf6_routemap_rule_match_interface_compile(constchar*arg){
returnXSTRDUP(MTYPE_ROUTE_MAP_COMPILED,arg);}/*Freeroutemap'scompiled`interface'
value.*/staticvoidospf6_routemap_rule_match_interface_free(void*rule){XFREE(MTYP
E_ROUTE_MAP_COMPILED,rule);}/*Routemapcommandsforinterfacematching.*/structroute
_map_rule_cmdospf6_routemap_rule_match_interface_cmd={"interface",ospf6_routemap
_rule_match_interface,ospf6_routemap_rule_match_interface_compile,ospf6_routemap
_rule_match_interface_free};/*Matchfunctionformatchingroutetags*/staticroute_map
_result_tospf6_routemap_rule_match_tag(void*rule,structprefix*prefix,route_map_o
bject_ttype,void*object){route_tag_t*tag=rule;structospf6_route*route=object;str
uctospf6_external_info*info=route->route_option;if(type==RMAP_OSPF6&&info->tag==
*tag)returnRMAP_MATCH;returnRMAP_NOMATCH;}staticstructroute_map_rule_cmdospf6_ro
utemap_rule_match_tag_cmd={"tag",ospf6_routemap_rule_match_tag,route_map_rule_ta
g_compile,route_map_rule_tag_free,};staticroute_map_result_tospf6_routemap_rule_
set_metric_type(void*rule,structprefix*prefix,route_map_object_ttype,void*object
){char*metric_type=rule;structospf6_route*route=object;if(type!=RMAP_OSPF6)retur
nRMAP_OKAY;if(strcmp(metric_type,"type-2")==0)route->path.metric_type=2;elserout
e->path.metric_type=1;returnRMAP_OKAY;}staticvoid*ospf6_routemap_rule_set_metric
_type_compile(constchar*arg){if(strcmp(arg,"type-2")&&strcmp(arg,"type-1"))retur
nNULL;returnXSTRDUP(MTYPE_ROUTE_MAP_COMPILED,arg);}staticvoidospf6_routemap_rule
_set_metric_type_free(void*rule){XFREE(MTYPE_ROUTE_MAP_COMPILED,rule);}structrou
te_map_rule_cmdospf6_routemap_rule_set_metric_type_cmd={"metric-type",ospf6_rout
emap_rule_set_metric_type,ospf6_routemap_rule_set_metric_type_compile,ospf6_rout
emap_rule_set_metric_type_free,};staticroute_map_result_tospf6_routemap_rule_set
_metric(void*rule,structprefix*prefix,route_map_object_ttype,void*object){char*m
etric=rule;structospf6_route*route=object;if(type!=RMAP_OSPF6)returnRMAP_OKAY;ro
ute->path.cost=atoi(metric);returnRMAP_OKAY;}staticvoid*ospf6_routemap_rule_set_
metric_compile(constchar*arg){uint32_tmetric;char*endp;metric=strtoul(arg,&endp,
0);if(metric>OSPF_LS_INFINITY||*endp!='\0')returnNULL;returnXSTRDUP(MTYPE_ROUTE_
MAP_COMPILED,arg);}staticvoidospf6_routemap_rule_set_metric_free(void*rule){XFRE
E(MTYPE_ROUTE_MAP_COMPILED,rule);}structroute_map_rule_cmdospf6_routemap_rule_se
t_metric_cmd={"metric",ospf6_routemap_rule_set_metric,ospf6_routemap_rule_set_me
tric_compile,ospf6_routemap_rule_set_metric_free,};staticroute_map_result_tospf6
_routemap_rule_set_forwarding(void*rule,structprefix*prefix,route_map_object_tty
pe,void*object){char*forwarding=rule;structospf6_route*route=object;structospf6_
external_info*info=route->route_option;if(type!=RMAP_OSPF6)returnRMAP_OKAY;if(in
et_pton(AF_INET6,forwarding,&info->forwarding)!=1){memset(&info->forwarding,0,si
zeof(structin6_addr));returnRMAP_ERROR;}returnRMAP_OKAY;}staticvoid*ospf6_routem
ap_rule_set_forwarding_compile(constchar*arg){structin6_addra;if(inet_pton(AF_IN
ET6,arg,&a)!=1)returnNULL;returnXSTRDUP(MTYPE_ROUTE_MAP_COMPILED,arg);}staticvoi
dospf6_routemap_rule_set_forwarding_free(void*rule){XFREE(MTYPE_ROUTE_MAP_COMPIL
ED,rule);}structroute_map_rule_cmdospf6_routemap_rule_set_forwarding_cmd={"forwa
rding-address",ospf6_routemap_rule_set_forwarding,ospf6_routemap_rule_set_forwar
ding_compile,ospf6_routemap_rule_set_forwarding_free,};staticroute_map_result_to
spf6_routemap_rule_set_tag(void*rule,structprefix*prefix,route_map_object_ttype,
void*object){route_tag_t*tag=rule;structospf6_route*route=object;structospf6_ext
ernal_info*info=route->route_option;if(type!=RMAP_OSPF6)returnRMAP_OKAY;info->ta
g=*tag;returnRMAP_OKAY;}staticstructroute_map_rule_cmdospf6_routemap_rule_set_ta
g_cmd={"tag",ospf6_routemap_rule_set_tag,route_map_rule_tag_compile,route_map_ru
le_tag_free,};staticintroute_map_command_status(structvty*vty,intret){switch(ret
){caseRMAP_RULE_MISSING:vty_out(vty,"OSPF6Can'tfindrule.\n");returnCMD_WARNING_C
ONFIG_FAILED;break;caseRMAP_COMPILE_ERROR:vty_out(vty,"OSPF6Argumentismalformed.
\n");returnCMD_WARNING_CONFIG_FAILED;break;caseRMAP_COMPILE_SUCCESS:break;}retur
nCMD_SUCCESS;}/*add"setmetric-type"*/DEFUN(ospf6_routemap_set_metric_type,ospf6_
routemap_set_metric_type_cmd,"setmetric-type<type-1|type-2>","Setvalue\n""Typeof
metric\n""OSPF6externaltype1metric\n""OSPF6externaltype2metric\n"){VTY_DECLVAR_C
ONTEXT(route_map_index,route_map_index);intidx_external=2;intret=route_map_add_s
et(route_map_index,"metric-type",argv[idx_external]->arg);returnroute_map_comman
d_status(vty,ret);}/*delete"setmetric-type"*/DEFUN(ospf6_routemap_no_set_metric_
type,ospf6_routemap_no_set_metric_type_cmd,"nosetmetric-type[<type-1|type-2>]",N
O_STR"Setvalue\n""Typeofmetric\n""OSPF6externaltype1metric\n""OSPF6externaltype2
metric\n"){VTY_DECLVAR_CONTEXT(route_map_index,route_map_index);char*ext=(argc==
4)?argv[3]->text:NULL;intret=route_map_delete_set(route_map_index,"metric-type",
ext);returnroute_map_command_status(vty,ret);}/*add"setforwarding-address"*/DEFU
N(ospf6_routemap_set_forwarding,ospf6_routemap_set_forwarding_cmd,"setforwarding
-addressX:X::X:X","Setvalue\n""ForwardingAddress\n""IPv6Address\n"){VTY_DECLVAR_
CONTEXT(route_map_index,route_map_index);intidx_ipv6=2;intret=route_map_add_set(
route_map_index,"forwarding-address",argv[idx_ipv6]->arg);returnroute_map_comman
d_status(vty,ret);}/*delete"setforwarding-address"*/DEFUN(ospf6_routemap_no_set_
forwarding,ospf6_routemap_no_set_forwarding_cmd,"nosetforwarding-addressX:X::X:X
",NO_STR"Setvalue\n""ForwardingAddress\n""IPv6Address\n"){VTY_DECLVAR_CONTEXT(ro
ute_map_index,route_map_index);intidx_ipv6=3;intret=route_map_delete_set(route_m
ap_index,"forwarding-address",argv[idx_ipv6]->arg);returnroute_map_command_statu
s(vty,ret);}staticvoidospf6_routemap_init(void){route_map_init();route_map_add_h
ook(ospf6_asbr_routemap_update);route_map_delete_hook(ospf6_asbr_routemap_update
);route_map_event_hook(ospf6_asbr_routemap_event);route_map_set_metric_hook(gene
ric_set_add);route_map_no_set_metric_hook(generic_set_delete);route_map_match_ta
g_hook(generic_match_add);route_map_no_match_tag_hook(generic_match_delete);rout
e_map_match_ipv6_address_prefix_list_hook(generic_match_add);route_map_no_match_
ipv6_address_prefix_list_hook(generic_match_delete);route_map_match_interface_ho
ok(generic_match_add);route_map_no_match_interface_hook(generic_match_delete);ro
ute_map_install_match(&ospf6_routemap_rule_match_address_prefixlist_cmd);route_m
ap_install_match(&ospf6_routemap_rule_match_interface_cmd);route_map_install_mat
ch(&ospf6_routemap_rule_match_tag_cmd);route_map_install_set(&ospf6_routemap_rul
e_set_metric_type_cmd);route_map_install_set(&ospf6_routemap_rule_set_metric_cmd
);route_map_install_set(&ospf6_routemap_rule_set_forwarding_cmd);route_map_insta
ll_set(&ospf6_routemap_rule_set_tag_cmd);/*ASEMetricType(e.g.Type-1/Type-2)*/ins
tall_element(RMAP_NODE,&ospf6_routemap_set_metric_type_cmd);install_element(RMAP
_NODE,&ospf6_routemap_no_set_metric_type_cmd);/*ASEMetric*/install_element(RMAP_
NODE,&ospf6_routemap_set_forwarding_cmd);install_element(RMAP_NODE,&ospf6_routem
ap_no_set_forwarding_cmd);}/*Displayfunctions*/staticchar*ospf6_as_external_lsa_
get_prefix_str(structospf6_lsa*lsa,char*buf,intbuflen,intpos){structospf6_as_ext
ernal_lsa*external;structin6_addrin6;intprefix_length=0;if(lsa){external=(struct
ospf6_as_external_lsa*)OSPF6_LSA_HEADER_END(lsa->header);if(pos==0){ospf6_prefix
_in6_addr(&in6,&external->prefix);prefix_length=external->prefix.prefix_length;}
else{in6=*((structin6_addr*)((caddr_t)external+sizeof(structospf6_as_external_ls
a)+OSPF6_PREFIX_SPACE(external->prefix.prefix_length)));}if(buf){inet_ntop(AF_IN
ET6,&in6,buf,buflen);if(prefix_length)sprintf(&buf[strlen(buf)],"/%d",prefix_len
gth);}}return(buf);}staticintospf6_as_external_lsa_show(structvty*vty,structospf
6_lsa*lsa){structospf6_as_external_lsa*external;charbuf[64];assert(lsa->header);
external=(structospf6_as_external_lsa*)OSPF6_LSA_HEADER_END(lsa->header);/*bits*
/snprintf(buf,sizeof(buf),"%c%c%c",(CHECK_FLAG(external->bits_metric,OSPF6_ASBR_
BIT_E)?'E':'-'),(CHECK_FLAG(external->bits_metric,OSPF6_ASBR_BIT_F)?'F':'-'),(CH
ECK_FLAG(external->bits_metric,OSPF6_ASBR_BIT_T)?'T':'-'));vty_out(vty,"Bits:%s\
n",buf);vty_out(vty,"Metric:%5lu\n",(unsignedlong)OSPF6_ASBR_METRIC(external));o
spf6_prefix_options_printbuf(external->prefix.prefix_options,buf,sizeof(buf));vt
y_out(vty,"PrefixOptions:%s\n",buf);vty_out(vty,"ReferencedLSType:%d\n",ntohs(ex
ternal->prefix.prefix_refer_lstype));vty_out(vty,"Prefix:%s\n",ospf6_as_external
_lsa_get_prefix_str(lsa,buf,sizeof(buf),0));/*Forwarding-Address*/if(CHECK_FLAG(
external->bits_metric,OSPF6_ASBR_BIT_F)){vty_out(vty,"Forwarding-Address:%s\n",o
spf6_as_external_lsa_get_prefix_str(lsa,buf,sizeof(buf),1));}/*Tag*/if(CHECK_FLA
G(external->bits_metric,OSPF6_ASBR_BIT_T)){vty_out(vty,"Tag:%"ROUTE_TAG_PRI"\n",
ospf6_as_external_lsa_get_tag(lsa));}return0;}staticvoidospf6_asbr_external_rout
e_show(structvty*vty,structospf6_route*route){structospf6_external_info*info=rou
te->route_option;charprefix[PREFIX2STR_BUFFER],id[16],forwarding[64];uint32_ttmp
_id;prefix2str(&route->prefix,prefix,sizeof(prefix));tmp_id=ntohl(info->id);inet
_ntop(AF_INET,&tmp_id,id,sizeof(id));if(!IN6_IS_ADDR_UNSPECIFIED(&info->forwardi
ng))inet_ntop(AF_INET6,&info->forwarding,forwarding,sizeof(forwarding));elsesnpr
intf(forwarding,sizeof(forwarding),"::(ifindex%d)",ospf6_route_get_first_nh_inde
x(route));vty_out(vty,"%c%-32s%-15stype-%d%5lu%s\n",zebra_route_char(info->type)
,prefix,id,route->path.metric_type,(unsignedlong)(route->path.metric_type==2?rou
te->path.u.cost_e2:route->path.cost),forwarding);}DEFUN(show_ipv6_ospf6_redistri
bute,show_ipv6_ospf6_redistribute_cmd,"showipv6ospf6redistribute",SHOW_STRIP6_ST
ROSPF6_STR"redistributingExternalinformation\n"){structospf6_route*route;OSPF6_C
MD_CHECK_RUNNING();ospf6_redistribute_show_config(vty);for(route=ospf6_route_hea
d(ospf6->external_table);route;route=ospf6_route_next(route))ospf6_asbr_external
_route_show(vty,route);returnCMD_SUCCESS;}structospf6_lsa_handleras_external_han
dler={.lh_type=OSPF6_LSTYPE_AS_EXTERNAL,.lh_name="AS-External",.lh_short_name="A
SE",.lh_show=ospf6_as_external_lsa_show,.lh_get_prefix_str=ospf6_as_external_lsa
_get_prefix_str,.lh_debug=0};voidospf6_asbr_init(void){ospf6_routemap_init();osp
f6_install_lsa_handler(&as_external_handler);install_element(VIEW_NODE,&show_ipv
6_ospf6_redistribute_cmd);install_element(OSPF6_NODE,&ospf6_redistribute_cmd);in
stall_element(OSPF6_NODE,&ospf6_redistribute_routemap_cmd);install_element(OSPF6
_NODE,&no_ospf6_redistribute_cmd);}voidospf6_asbr_redistribute_reset(void){intty
pe;for(type=0;type<ZEBRA_ROUTE_MAX;type++){if(type==ZEBRA_ROUTE_OSPF6)continue;i
f(ospf6_zebra_is_redistribute(type))ospf6_asbr_redistribute_unset(type);}}voidos
pf6_asbr_terminate(void){/*Cleanuproutemaps*/route_map_add_hook(NULL);route_map_
delete_hook(NULL);route_map_event_hook(NULL);route_map_finish();}DEFUN(debug_osp
f6_asbr,debug_ospf6_asbr_cmd,"debugospf6asbr",DEBUG_STROSPF6_STR"DebugOSPFv3ASBR
function\n"){OSPF6_DEBUG_ASBR_ON();returnCMD_SUCCESS;}DEFUN(no_debug_ospf6_asbr,
no_debug_ospf6_asbr_cmd,"nodebugospf6asbr",NO_STRDEBUG_STROSPF6_STR"DebugOSPFv3A
SBRfunction\n"){OSPF6_DEBUG_ASBR_OFF();returnCMD_SUCCESS;}intconfig_write_ospf6_
debug_asbr(structvty*vty){if(IS_OSPF6_DEBUG_ASBR)vty_out(vty,"debugospf6asbr\n")
;return0;}voidinstall_element_ospf6_debug_asbr(){install_element(ENABLE_NODE,&de
bug_ospf6_asbr_cmd);install_element(ENABLE_NODE,&no_debug_ospf6_asbr_cmd);instal
l_element(CONFIG_NODE,&debug_ospf6_asbr_cmd);install_element(CONFIG_NODE,&no_deb
ug_ospf6_asbr_cmd);}