/**Copyright(C)2003YasuhiroOhara**ThisfileispartofGNUZebra.**GNUZebraisfreesoftw
are;youcanredistributeitand/ormodifyit*underthetermsoftheGNUGeneralPublicLicense
aspublishedbythe*FreeSoftwareFoundation;eitherversion2,or(atyouroption)any*later
version.**GNUZebraisdistributedinthehopethatitwillbeuseful,but*WITHOUTANYWARRANT
Y;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.
SeetheGNU*GeneralPublicLicenseformoredetails.**YoushouldhavereceivedacopyoftheGN
UGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;ifnot,writetotheFre
eSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-1301USA*/#ifnde
fOSPF_AREA_H#defineOSPF_AREA_H#include"ospf6_top.h"structospf6_area{/*Referencet
oTopdatastructure*/structospf6*ospf6;/*Area-ID*/uint32_tarea_id;#defineOSPF6_ARE
A_FMT_DOTTEDQUAD1#defineOSPF6_AREA_FMT_DECIMAL2/*Area-IDstring*/charname[16];/*f
lag*/uint8_tflag;/*OSPFOption*/uint8_toptions[3];/*Summaryroutestobeoriginated(i
ncludesConfiguredAddressRanges)*/structospf6_route_table*range_table;structospf6
_route_table*summary_prefix;structospf6_route_table*summary_router;/*Areatype*/i
ntno_summary;/*OSPFinterfacelist*/structlist*if_list;structospf6_lsdb*lsdb;struc
tospf6_lsdb*lsdb_self;structospf6_lsdb*temp_router_lsa_lsdb;structospf6_route_ta
ble*spf_table;structospf6_route_table*route_table;uint32_tspf_calculation;/*SPFc
alculationcount*/structthread*thread_router_lsa;structthread*thread_intra_prefix
_lsa;uint32_trouter_lsa_size_limit;/*Areaannouncelist*/struct{char*name;structac
cess_list*list;}_export;#defineEXPORT_NAME(A)(A)->_export.name#defineEXPORT_LIST
(A)(A)->_export.list/*Areaacceptancelist*/struct{char*name;structaccess_list*lis
t;}import;#defineIMPORT_NAME(A)(A)->import.name#defineIMPORT_LIST(A)(A)->import.
list/*Type3LSAAreaprefix-list*/struct{char*name;structprefix_list*list;}plist_in
;#definePREFIX_NAME_IN(A)(A)->plist_in.name#definePREFIX_LIST_IN(A)(A)->plist_in
.liststruct{char*name;structprefix_list*list;}plist_out;#definePREFIX_NAME_OUT(A
)(A)->plist_out.name#definePREFIX_LIST_OUT(A)(A)->plist_out.list/*Timestamps.*/s
tructtimevalts_spf;/*SPFcalculationtimestamp.*/uint32_tfull_nbrs;/*Fullyadjacent
neighbors.*/uint8_tintra_prefix_originate;/*Forceintra_prefixlsaoriginate*/};#de
fineOSPF6_AREA_ENABLE0x01#defineOSPF6_AREA_ACTIVE0x02#defineOSPF6_AREA_TRANSIT0x
04/*TransitCapability*/#defineOSPF6_AREA_STUB0x08#defineIS_AREA_ENABLED(oa)(CHEC
K_FLAG((oa)->flag,OSPF6_AREA_ENABLE))#defineIS_AREA_ACTIVE(oa)(CHECK_FLAG((oa)->
flag,OSPF6_AREA_ACTIVE))#defineIS_AREA_TRANSIT(oa)(CHECK_FLAG((oa)->flag,OSPF6_A
REA_TRANSIT))#defineIS_AREA_STUB(oa)(CHECK_FLAG((oa)->flag,OSPF6_AREA_STUB))/*pr
ototypes*/externintospf6_area_cmp(void*va,void*vb);externstructospf6_area*ospf6_
area_create(uint32_t,structospf6*,int);externvoidospf6_area_delete(structospf6_a
rea*);externstructospf6_area*ospf6_area_lookup(uint32_t,structospf6*);externvoid
ospf6_area_enable(structospf6_area*);externvoidospf6_area_disable(structospf6_ar
ea*);externvoidospf6_area_show(structvty*,structospf6_area*);externvoidospf6_are
a_plist_update(structprefix_list*plist,intadd);externvoidospf6_area_config_write
(structvty*vty);externvoidospf6_area_init(void);#endif/*OSPF_AREA_H*/