/**Copyright(C)2003YasuhiroOhara**ThisfileispartofGNUZebra.**GNUZebraisfreesoftw
are;youcanredistributeitand/ormodifyit*underthetermsoftheGNUGeneralPublicLicense
aspublishedbythe*FreeSoftwareFoundation;eitherversion2,or(atyouroption)any*later
version.**GNUZebraisdistributedinthehopethatitwillbeuseful,but*WITHOUTANYWARRANT
Y;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.
SeetheGNU*GeneralPublicLicenseformoredetails.**YoushouldhavereceivedacopyoftheGN
UGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;ifnot,writetotheFre
eSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-1301USA*/#inclu
de<zebra.h>#include"memory.h"#include"log.h"#include"command.h"#include"prefix.h
"#include"table.h"#include"vty.h"#include"ospf6_proto.h"#include"ospf6_lsa.h"#in
clude"ospf6_lsdb.h"#include"ospf6_route.h"#include"ospf6d.h"#include"bitfield.h"
structospf6_lsdb*ospf6_lsdb_create(void*data){structospf6_lsdb*lsdb;lsdb=XCALLOC
(MTYPE_OSPF6_LSDB,sizeof(structospf6_lsdb));if(lsdb==NULL){zlog_warn("Can'tmallo
clsdb");returnNULL;}memset(lsdb,0,sizeof(structospf6_lsdb));lsdb->data=data;lsdb
->table=route_table_init();returnlsdb;}voidospf6_lsdb_delete(structospf6_lsdb*ls
db){if(lsdb!=NULL){ospf6_lsdb_remove_all(lsdb);route_table_finish(lsdb->table);X
FREE(MTYPE_OSPF6_LSDB,lsdb);}}staticvoidospf6_lsdb_set_key(structprefix_ipv6*key
,constvoid*value,intlen){assert(key->prefixlen%8==0);memcpy((caddr_t)&key->prefi
x+key->prefixlen/8,(caddr_t)value,len);key->family=AF_INET6;key->prefixlen+=len*
8;}#ifdefDEBUGstaticvoid_lsdb_count_assert(structospf6_lsdb*lsdb){structospf6_ls
a*debug;unsignedintnum=0;for(ALL_LSDB(lsdb,debug))num++;if(num==lsdb->count)retu
rn;zlog_debug("PANIC!!lsdb[%p]->count=%d,real=%d",lsdb,lsdb->count,num);for(ALL_
LSDB(lsdb,debug))zlog_debug("%slsdb[%p]",debug->name,debug->lsdb);zlog_debug("DU
MPEND");assert(num==lsdb->count);}#defineospf6_lsdb_count_assert(t)(_lsdb_count_
assert(t))#else/*DEBUG*/#defineospf6_lsdb_count_assert(t)((void)0)#endif/*DEBUG*
/voidospf6_lsdb_add(structospf6_lsa*lsa,structospf6_lsdb*lsdb){structprefix_ipv6
key;structroute_node*current;structospf6_lsa*old=NULL;memset(&key,0,sizeof(key))
;ospf6_lsdb_set_key(&key,&lsa->header->type,sizeof(lsa->header->type));ospf6_lsd
b_set_key(&key,&lsa->header->adv_router,sizeof(lsa->header->adv_router));ospf6_l
sdb_set_key(&key,&lsa->header->id,sizeof(lsa->header->id));current=route_node_ge
t(lsdb->table,(structprefix*)&key);old=current->info;current->info=lsa;lsa->rn=c
urrent;ospf6_lsa_lock(lsa);if(!old){lsdb->count++;if(OSPF6_LSA_IS_MAXAGE(lsa)){i
f(lsdb->hook_remove)(*lsdb->hook_remove)(lsa);}else{if(lsdb->hook_add)(*lsdb->ho
ok_add)(lsa);}}else{if(OSPF6_LSA_IS_CHANGED(old,lsa)){if(OSPF6_LSA_IS_MAXAGE(lsa
)){if(lsdb->hook_remove){(*lsdb->hook_remove)(old);(*lsdb->hook_remove)(lsa);}}e
lseif(OSPF6_LSA_IS_MAXAGE(old)){if(lsdb->hook_add)(*lsdb->hook_add)(lsa);}else{i
f(lsdb->hook_remove)(*lsdb->hook_remove)(old);if(lsdb->hook_add)(*lsdb->hook_add
)(lsa);}}/*tofreethelookuplockinnodeget*/route_unlock_node(current);ospf6_lsa_un
lock(old);}ospf6_lsdb_count_assert(lsdb);}voidospf6_lsdb_remove(structospf6_lsa*
lsa,structospf6_lsdb*lsdb){structroute_node*node;structprefix_ipv6key;memset(&ke
y,0,sizeof(key));ospf6_lsdb_set_key(&key,&lsa->header->type,sizeof(lsa->header->
type));ospf6_lsdb_set_key(&key,&lsa->header->adv_router,sizeof(lsa->header->adv_
router));ospf6_lsdb_set_key(&key,&lsa->header->id,sizeof(lsa->header->id));node=
route_node_lookup(lsdb->table,(structprefix*)&key);assert(node&&node->info==lsa)
;node->info=NULL;lsdb->count--;if(lsdb->hook_remove)(*lsdb->hook_remove)(lsa);ro
ute_unlock_node(node);/*tofreethelookuplock*/route_unlock_node(node);/*tofreethe
originallock*/ospf6_lsa_unlock(lsa);ospf6_lsdb_count_assert(lsdb);}structospf6_l
sa*ospf6_lsdb_lookup(uint16_ttype,uint32_tid,uint32_tadv_router,structospf6_lsdb
*lsdb){structroute_node*node;structprefix_ipv6key;if(lsdb==NULL)returnNULL;memse
t(&key,0,sizeof(key));ospf6_lsdb_set_key(&key,&type,sizeof(type));ospf6_lsdb_set
_key(&key,&adv_router,sizeof(adv_router));ospf6_lsdb_set_key(&key,&id,sizeof(id)
);node=route_node_lookup(lsdb->table,(structprefix*)&key);if(node==NULL||node->i
nfo==NULL)returnNULL;route_unlock_node(node);return(structospf6_lsa*)node->info;
}structospf6_lsa*ospf6_lsdb_lookup_next(uint16_ttype,uint32_tid,uint32_tadv_rout
er,structospf6_lsdb*lsdb){structroute_node*node;structprefix_ipv6key;if(lsdb==NU
LL)returnNULL;memset(&key,0,sizeof(key));ospf6_lsdb_set_key(&key,&type,sizeof(ty
pe));ospf6_lsdb_set_key(&key,&adv_router,sizeof(adv_router));ospf6_lsdb_set_key(
&key,&id,sizeof(id));{charbuf[PREFIX2STR_BUFFER];prefix2str(&key,buf,sizeof(buf)
);zlog_debug("lsdb_lookup_next:key:%s",buf);}node=route_table_get_next(lsdb->tab
le,&key);/*skiptorealexistingentry*/while(node&&node->info==NULL)node=route_next
(node);if(!node)returnNULL;route_unlock_node(node);if(!node->info)returnNULL;ret
urn(structospf6_lsa*)node->info;}conststructroute_node*ospf6_lsdb_head(structosp
f6_lsdb*lsdb,intargmode,uint16_ttype,uint32_tadv_router,structospf6_lsa**lsa){st
ructroute_node*node,*end;*lsa=NULL;if(argmode>0){structprefix_ipv6key={.family=A
F_INET6,.prefixlen=0};ospf6_lsdb_set_key(&key,&type,sizeof(type));if(argmode>1)o
spf6_lsdb_set_key(&key,&adv_router,sizeof(adv_router));node=route_table_get_next
(lsdb->table,&key);if(!node||!prefix_match((structprefix*)&key,&node->p))returnN
ULL;for(end=node;end&&end->parent&&end->parent->p.prefixlen>=key.prefixlen;end=e
nd->parent);}else{node=route_top(lsdb->table);end=NULL;}while(node&&!node->info)
node=route_next_until(node,end);if(!node)returnNULL;if(!node->info){route_unlock
_node(node);returnNULL;}*lsa=node->info;ospf6_lsa_lock(*lsa);returnend;}structos
pf6_lsa*ospf6_lsdb_next(conststructroute_node*iterend,structospf6_lsa*lsa){struc
troute_node*node=lsa->rn;ospf6_lsa_unlock(lsa);donode=route_next_until(node,iter
end);while(node&&!node->info);if(node&&node->info){structospf6_lsa*next=node->in
fo;ospf6_lsa_lock(next);returnnext;}if(node)route_unlock_node(node);returnNULL;}
voidospf6_lsdb_remove_all(structospf6_lsdb*lsdb){structospf6_lsa*lsa;if(lsdb==NU
LL)return;for(ALL_LSDB(lsdb,lsa))ospf6_lsdb_remove(lsa,lsdb);}voidospf6_lsdb_lsa
_unlock(structospf6_lsa*lsa){if(lsa!=NULL){if(lsa->rn!=NULL)route_unlock_node(ls
a->rn);ospf6_lsa_unlock(lsa);}}intospf6_lsdb_maxage_remover(structospf6_lsdb*lsd
b){intreschedule=0;structospf6_lsa*lsa;for(ALL_LSDB(lsdb,lsa)){if(!OSPF6_LSA_IS_
MAXAGE(lsa))continue;if(lsa->retrans_count!=0){reschedule=1;continue;}if(IS_OSPF
6_DEBUG_LSA_TYPE(lsa->header->type))zlog_debug("RemoveMaxAge%s",lsa->name);if(CH
ECK_FLAG(lsa->flag,OSPF6_LSA_SEQWRAPPED)){UNSET_FLAG(lsa->flag,OSPF6_LSA_SEQWRAP
PED);/**lsa->header->age=0;*/lsa->header->seqnum=htonl(OSPF_MAX_SEQUENCE_NUMBER+
1);ospf6_lsa_checksum(lsa->header);THREAD_OFF(lsa->refresh);thread_execute(maste
r,ospf6_lsa_refresh,lsa,0);}else{ospf6_lsdb_remove(lsa,lsdb);}}return(reschedule
);}voidospf6_lsdb_show(structvty*vty,enumospf_lsdb_show_levellevel,uint16_t*type
,uint32_t*id,uint32_t*adv_router,structospf6_lsdb*lsdb){structospf6_lsa*lsa;cons
tstructroute_node*end=NULL;void(*showfunc)(structvty*,structospf6_lsa*)=NULL;swi
tch(level){caseOSPF6_LSDB_SHOW_LEVEL_DETAIL:showfunc=ospf6_lsa_show;break;caseOS
PF6_LSDB_SHOW_LEVEL_INTERNAL:showfunc=ospf6_lsa_show_internal;break;caseOSPF6_LS
DB_SHOW_LEVEL_DUMP:showfunc=ospf6_lsa_show_dump;break;caseOSPF6_LSDB_SHOW_LEVEL_
NORMAL:default:showfunc=ospf6_lsa_show_summary;}if(type&&id&&adv_router){lsa=osp
f6_lsdb_lookup(*type,*id,*adv_router,lsdb);if(lsa){if(level==OSPF6_LSDB_SHOW_LEV
EL_NORMAL)ospf6_lsa_show(vty,lsa);else(*showfunc)(vty,lsa);}return;}if(level==OS
PF6_LSDB_SHOW_LEVEL_NORMAL)ospf6_lsa_show_summary_header(vty);end=ospf6_lsdb_hea
d(lsdb,!!type+!!(type&&adv_router),type?*type:0,adv_router?*adv_router:0,&lsa);w
hile(lsa){if((!adv_router||lsa->header->adv_router==*adv_router)&&(!id||lsa->hea
der->id==*id))(*showfunc)(vty,lsa);lsa=ospf6_lsdb_next(end,lsa);}}uint32_tospf6_
new_ls_id(uint16_ttype,uint32_tadv_router,structospf6_lsdb*lsdb){structospf6_lsa
*lsa;uint32_tid=1,tmp_id;/*ThisroutineiscurentlyinvokedonlyforInter-PrefixLSAsfo
r*non-summarizedroutes(noarea/range).*/for(ALL_LSDB_TYPED_ADVRTR(lsdb,type,adv_r
outer,lsa)){tmp_id=ntohl(lsa->header->id);if(tmp_id<id)continue;if(tmp_id>id){os
pf6_lsdb_lsa_unlock(lsa);break;}id++;}return((uint32_t)htonl(id));}/*DecidenewLS
sequencenumbertooriginate.notereturnvalueisnetworkbyteorder*/uint32_tospf6_new_l
s_seqnum(uint16_ttype,uint32_tid,uint32_tadv_router,structospf6_lsdb*lsdb){struc
tospf6_lsa*lsa;signedlongseqnum=0;/*ifcurrentdatabasecopynotfound,returnInitialS
equenceNumber*/lsa=ospf6_lsdb_lookup(type,id,adv_router,lsdb);if(lsa==NULL)seqnu
m=OSPF_INITIAL_SEQUENCE_NUMBER;elseseqnum=(signedlong)ntohl(lsa->header->seqnum)
+1;return((uint32_t)htonl(seqnum));}