/**Copyright(C)2001YasuhiroOhara**ThisfileispartofGNUZebra.**GNUZebraisfreesoftw
are;youcanredistributeitand/ormodifyit*underthetermsoftheGNUGeneralPublicLicense
aspublishedbythe*FreeSoftwareFoundation;eitherversion2,or(atyouroption)any*later
version.**GNUZebraisdistributedinthehopethatitwillbeuseful,but*WITHOUTANYWARRANT
Y;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.
SeetheGNU*GeneralPublicLicenseformoredetails.**YoushouldhavereceivedacopyoftheGN
UGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;ifnot,writetotheFre
eSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-1301USA*/#ifnde
fOSPF6_ASBR_H#defineOSPF6_ASBR_H/*forstructospf6_prefix*/#include"ospf6_proto.h"
/*forstructospf6_lsa*/#include"ospf6_lsa.h"/*forstructospf6_route*/#include"ospf
6_route.h"/*Debugoption*/externunsignedcharconf_debug_ospf6_asbr;#defineOSPF6_DE
BUG_ASBR_ON()(conf_debug_ospf6_asbr=1)#defineOSPF6_DEBUG_ASBR_OFF()(conf_debug_o
spf6_asbr=0)#defineIS_OSPF6_DEBUG_ASBR(conf_debug_ospf6_asbr)structospf6_externa
l_info{/*Externalroutetype*/inttype;/*OriginatingLinkStateID*/uint32_tid;structi
n6_addrforwarding;route_tag_ttag;ifindex_tifindex;};/*AS-External-LSA*/#defineOS
PF6_AS_EXTERNAL_LSA_MIN_SIZE4U/*w/oIPv6prefix*/structospf6_as_external_lsa{uint3
2_tbits_metric;structospf6_prefixprefix;/*followedbynoneoroneforwardingaddress*/
/*followedbynoneoroneexternalroutetag*//*followedbynoneoronereferencedLS-ID*/};#
defineOSPF6_ASBR_BIT_Tntohl(0x01000000)#defineOSPF6_ASBR_BIT_Fntohl(0x02000000)#
defineOSPF6_ASBR_BIT_Entohl(0x04000000)#defineOSPF6_ASBR_METRIC(E)(ntohl((E)->bi
ts_metric&htonl(0x00ffffff)))#defineOSPF6_ASBR_METRIC_SET(E,C)\{\(E)->bits_metri
c&=htonl(0xff000000);\(E)->bits_metric|=htonl(0x00ffffff)&htonl(C);\}externvoido
spf6_asbr_lsa_add(structospf6_lsa*lsa);externvoidospf6_asbr_lsa_remove(structosp
f6_lsa*lsa,structospf6_route*asbr_entry);externvoidospf6_asbr_lsentry_add(struct
ospf6_route*asbr_entry);externvoidospf6_asbr_lsentry_remove(structospf6_route*as
br_entry);externintospf6_asbr_is_asbr(structospf6*o);externvoidospf6_asbr_redist
ribute_add(inttype,ifindex_tifindex,structprefix*prefix,unsignedintnexthop_num,s
tructin6_addr*nexthop,route_tag_ttag);externvoidospf6_asbr_redistribute_remove(i
nttype,ifindex_tifindex,structprefix*prefix);externintospf6_redistribute_config_
write(structvty*vty);externvoidospf6_asbr_init(void);externvoidospf6_asbr_redist
ribute_reset(void);externvoidospf6_asbr_terminate(void);externvoidospf6_asbr_sen
d_externals_to_area(structospf6_area*);externintconfig_write_ospf6_debug_asbr(st
ructvty*vty);externvoidinstall_element_ospf6_debug_asbr(void);externvoidospf6_as
br_update_route_ecmp_path(structospf6_route*old,structospf6_route*route);externv
oidospf6_asbr_distribute_list_update(inttype);#endif/*OSPF6_ASBR_H*/