/**Copyright(C)2003YasuhiroOhara**ThisfileispartofGNUZebra.**GNUZebraisfreesoftw
are;youcanredistributeitand/ormodifyit*underthetermsoftheGNUGeneralPublicLicense
aspublishedbythe*FreeSoftwareFoundation;eitherversion2,or(atyouroption)any*later
version.**GNUZebraisdistributedinthehopethatitwillbeuseful,but*WITHOUTANYWARRANT
Y;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.
SeetheGNU*GeneralPublicLicenseformoredetails.**YoushouldhavereceivedacopyoftheGN
UGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;ifnot,writetotheFre
eSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-1301USA*/#ifnde
fOSPF6_TOP_H#defineOSPF6_TOP_H#include"qobj.h"#include"routemap.h"structospf6_ma
ster{uint32_tzebra_router_id;};/*OSPFv3topleveldatastructure*/structospf6{/*myro
uterid*/uint32_trouter_id;/*staticrouterid*/uint32_trouter_id_static;structin_ad
drrouter_id_zebra;/*starttime*/structtimevalstarttime;/*listofareas*/structlist*
area_list;structospf6_area*backbone;/*ASscopelinkstatedatabase*/structospf6_lsdb
*lsdb;structospf6_lsdb*lsdb_self;structospf6_route_table*route_table;structospf6
_route_table*brouter_table;structospf6_route_table*external_table;structroute_ta
ble*external_id_table;uint32_texternal_id;/*redistributeroute-map*/struct{char*n
ame;structroute_map*map;}rmap[ZEBRA_ROUTE_MAX];uint8_tflag;/*Configuredflags*/ui
nt8_tconfig_flags;#defineOSPF6_LOG_ADJACENCY_CHANGES(1<<0)#defineOSPF6_LOG_ADJAC
ENCY_DETAIL(1<<1)/*LSAtimerparameters*/unsignedintlsa_minarrival;/*LSAminimumarr
ivalinmilliseconds.*//*SPFparameters*/unsignedintspf_delay;/*SPFdelaytime.*/unsi
gnedintspf_holdtime;/*SPFholdtime.*/unsignedintspf_max_holdtime;/*SPFmaximum-hol
dtime*/unsignedintspf_hold_multiplier;/*Adaptivemultiplierforholdtime*/unsignedi
ntspf_reason;/*reasonbitswhileschedulingSPF*/structtimevalts_spf;/*SPFcalculatio
ntimestamp.*/structtimevalts_spf_duration;/*ExecutiontimeoflastSPF*/unsignedintl
ast_spf_reason;/*LastSPFreason*//*Threads*/structthread*t_spf_calc;/*SPFcalculat
iontimer.*/structthread*t_ase_calc;/*ASEcalculationtimer.*/structthread*maxage_r
emover;structthread*t_distribute_update;/*Distirbuteupdatetimer.*/uint32_tref_ba
ndwidth;/*Distanceparameters*/uint8_tdistance_all;uint8_tdistance_intra;uint8_td
istance_inter;uint8_tdistance_external;structroute_table*distance_table;/*Useddu
ringospfinstancegoingdownsendLSDB*updatetoneighborsimmediatly*/uint8_tinst_shutd
own;QOBJ_FIELDS};DECLARE_QOBJ_TYPE(ospf6)#defineOSPF6_DISABLED0x01#defineOSPF6_S
TUB_ROUTER0x02/*globalpointerforOSPFtopdatastructure*/externstructospf6*ospf6;ex
ternstructospf6_master*om6;/*prototypes*/externvoidospf6_master_init(void);exter
nvoidospf6_top_init(void);externvoidospf6_delete(structospf6*o);externvoidospf6_
router_id_update(void);externvoidospf6_maxage_remove(structospf6*o);#endif/*OSPF
6_TOP_H*/