/**Copyright(C)2003YasuhiroOhara**ThisfileispartofGNUZebra.**GNUZebraisfreesoftw
are;youcanredistributeitand/ormodifyit*underthetermsoftheGNUGeneralPublicLicense
aspublishedbythe*FreeSoftwareFoundation;eitherversion2,or(atyouroption)any*later
version.**GNUZebraisdistributedinthehopethatitwillbeuseful,but*WITHOUTANYWARRANT
Y;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.
SeetheGNU*GeneralPublicLicenseformoredetails.**YoushouldhavereceivedacopyoftheGN
UGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;ifnot,writetotheFre
eSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-1301USA*/#inclu
de<zebra.h>/*Includeotherstuffs*/#include"log.h"#include"linklist.h"#include"vec
tor.h"#include"vty.h"#include"command.h"#include"memory.h"#include"thread.h"#inc
lude"checksum.h"#include"ospf6_proto.h"#include"ospf6_lsa.h"#include"ospf6_lsdb.
h"#include"ospf6_message.h"#include"ospf6_top.h"#include"ospf6_area.h"#include"o
spf6_interface.h"#include"ospf6_neighbor.h"#include"ospf6_flood.h"#include"ospf6
d.h"vectorospf6_lsa_handler_vector;staticintospf6_unknown_lsa_show(structvty*vty
,structospf6_lsa*lsa){uint8_t*start,*end,*current;charbyte[4];start=(uint8_t*)ls
a->header+sizeof(structospf6_lsa_header);end=(uint8_t*)lsa->header+ntohs(lsa->he
ader->length);vty_out(vty,"Unknowncontents:\n");for(current=start;current<end;cu
rrent++){if((current-start)%16==0)vty_out(vty,"\n");elseif((current-start)%4==0)
vty_out(vty,"");snprintf(byte,sizeof(byte),"%02x",*current);vty_out(vty,"%s",byt
e);}vty_out(vty,"\n\n");return0;}staticstructospf6_lsa_handlerunknown_handler={.
lh_type=OSPF6_LSTYPE_UNKNOWN,.lh_name="Unknown",.lh_short_name="Unk",.lh_show=os
pf6_unknown_lsa_show,.lh_get_prefix_str=NULL,.lh_debug=0/*Nodefaultdebug*/};void
ospf6_install_lsa_handler(conststructospf6_lsa_handler*handler){/*typeinhandleri
shostbyteorder*/intindex=handler->lh_type&OSPF6_LSTYPE_FCODE_MASK;vector_set_ind
ex(ospf6_lsa_handler_vector,index,(void*)handler);}conststructospf6_lsa_handler*
ospf6_get_lsa_handler(uint16_ttype){conststructospf6_lsa_handler*handler=NULL;un
signedintindex=ntohs(type)&OSPF6_LSTYPE_FCODE_MASK;if(index>=vector_active(ospf6
_lsa_handler_vector))handler=&unknown_handler;elsehandler=vector_slot(ospf6_lsa_
handler_vector,index);if(handler==NULL)handler=&unknown_handler;returnhandler;}c
onstchar*ospf6_lstype_name(uint16_ttype){staticcharbuf[8];conststructospf6_lsa_h
andler*handler;handler=ospf6_get_lsa_handler(type);if(handler&&handler!=&unknown
_handler)returnhandler->lh_name;snprintf(buf,sizeof(buf),"0x%04hx",ntohs(type));
returnbuf;}constchar*ospf6_lstype_short_name(uint16_ttype){staticcharbuf[8];cons
tstructospf6_lsa_handler*handler;handler=ospf6_get_lsa_handler(type);if(handler&
&handler!=&unknown_handler)returnhandler->lh_short_name;snprintf(buf,sizeof(buf)
,"0x%04hx",ntohs(type));returnbuf;}uint8_tospf6_lstype_debug(uint16_ttype){const
structospf6_lsa_handler*handler;handler=ospf6_get_lsa_handler(type);returnhandle
r->debug;}/*RFC2328:Section13.2*/intospf6_lsa_is_differ(structospf6_lsa*lsa1,str
uctospf6_lsa*lsa2){intlen;assert(OSPF6_LSA_IS_SAME(lsa1,lsa2));/*XXX,Options???*
/ospf6_lsa_age_current(lsa1);ospf6_lsa_age_current(lsa2);if(ntohs(lsa1->header->
age)==OSPF_LSA_MAXAGE&&ntohs(lsa2->header->age)!=OSPF_LSA_MAXAGE)return1;if(ntoh
s(lsa1->header->age)!=OSPF_LSA_MAXAGE&&ntohs(lsa2->header->age)==OSPF_LSA_MAXAGE
)return1;/*comparebody*/if(ntohs(lsa1->header->length)!=ntohs(lsa2->header->leng
th))return1;len=ntohs(lsa1->header->length)-sizeof(structospf6_lsa_header);retur
nmemcmp(lsa1->header+1,lsa2->header+1,len);}intospf6_lsa_is_changed(structospf6_
lsa*lsa1,structospf6_lsa*lsa2){intlength;if(OSPF6_LSA_IS_MAXAGE(lsa1)^OSPF6_LSA_
IS_MAXAGE(lsa2))return1;if(ntohs(lsa1->header->length)!=ntohs(lsa2->header->leng
th))return1;/*GoingbeyondLSAheaderstocomparethepayloadonlymakessense,*whenbothLS
Asaren'theader-only.*/if(CHECK_FLAG(lsa1->flag,OSPF6_LSA_HEADERONLY)!=CHECK_FLAG
(lsa2->flag,OSPF6_LSA_HEADERONLY)){zlog_warn("%s:onlyoneoftwo(%s,%s)LSAscompared
isheader-only",__func__,lsa1->name,lsa2->name);return1;}if(CHECK_FLAG(lsa1->flag
,OSPF6_LSA_HEADERONLY))return0;length=OSPF6_LSA_SIZE(lsa1->header)-sizeof(struct
ospf6_lsa_header);/*OnceupperlayerverifiesLSAsreceived,lengthunderrunshould*beco
meawarning.*/if(length<=0)return0;returnmemcmp(OSPF6_LSA_HEADER_END(lsa1->header
),OSPF6_LSA_HEADER_END(lsa2->header),length);}/*ospf6agefunctions*//*calculatebi
rth*/voidospf6_lsa_age_set(structospf6_lsa*lsa){structtimevalnow;assert(lsa&&lsa
->header);monotime(&now);lsa->birth.tv_sec=now.tv_sec-ntohs(lsa->header->age);ls
a->birth.tv_usec=now.tv_usec;return;}/*thisfunctioncalculatescurrentagefromitsbi
rth,thenupdateagefieldofLSAheader.returnvalueiscurrentage*/uint16_tospf6_lsa_age
_current(structospf6_lsa*lsa){structtimevalnow;uint32_tulage;uint16_tage;assert(
lsa);assert(lsa->header);/*currenttime*/monotime(&now);if(ntohs(lsa->header->age
)>=OSPF_LSA_MAXAGE){/*ospf6_lsa_premature_aging()setsagetoMAXAGE;whenusingrelati
vetime,wecannotcompareagainstlsabirthtime,sowecatchthisspecialcasehere.*/lsa->he
ader->age=htons(OSPF_LSA_MAXAGE);returnOSPF_LSA_MAXAGE;}/*calculateage*/ulage=no
w.tv_sec-lsa->birth.tv_sec;/*ifoverMAXAGE,settoit*/age=(ulage>OSPF_LSA_MAXAGE?OS
PF_LSA_MAXAGE:ulage);lsa->header->age=htons(age);returnage;}/*updateagefieldofLS
AheaderwithaddingInfTransDelay*/voidospf6_lsa_age_update_to_send(structospf6_lsa
*lsa,uint32_ttransdelay){unsignedshortage;age=ospf6_lsa_age_current(lsa)+transde
lay;if(age>OSPF_LSA_MAXAGE)age=OSPF_LSA_MAXAGE;lsa->header->age=htons(age);}void
ospf6_lsa_premature_aging(structospf6_lsa*lsa){/*log*/if(IS_OSPF6_DEBUG_LSA_TYPE
(lsa->header->type))zlog_debug("LSA:Prematureaging:%s",lsa->name);THREAD_OFF(lsa
->expire);THREAD_OFF(lsa->refresh);/**WecleartheLSAfromtheneighborretxlistsnowbe
causeit*willnotgetdeletedlater.Essentially,changingtheageto*MaxAgewillpreventthi
sLSAfrombeingmatchedwithits*existingentriesintheretxlisttherebycausingthoseentri
es*tobesilentlyreplacedwithitsMaxAgedversion,butwithever*increasingretxcountcaus
ingthisLSAtoremainforeverand*fortheMaxAgeremoverthreadtobecalledforevertoo.**The
reasonthepreviousentrysilentlydisappearsisthatwhen*entryisaddedtoaneighbor'sretx
list,itreplacestheexisting*entry.Butsincetheospf6_lsdb_add()routineisgenericandn
ot*aware*ofthespecialsemanticsofretxcount,theretxcountisnot*decrementedwhenitsre
placed.Attemptingtoaddtheincranddecr*retxcountroutinesasthehook_addandhook_remov
efortheretx*lists*haveaproblembecausethehook_removeroutineiscalledforMaxAge*entr
ies(aswillbethecaseinatraditionalLSDB,unlikeinthis*case*whereanLSDBisusedasaneff
icienttreestructuretostoreall*kinds*ofdata)thatareaddedinsteadofcallingthehook_a
ddroutine.*/ospf6_flood_clear(lsa);lsa->header->age=htons(OSPF_LSA_MAXAGE);threa
d_execute(master,ospf6_lsa_expire,lsa,0);}/*checkwhichismorerecent.ifaismorerece
nt,return-1;ifthesame,return0;otherwise(bismorerecent),return1*/intospf6_lsa_com
pare(structospf6_lsa*a,structospf6_lsa*b){int32_tseqnuma,seqnumb;uint16_tcksuma,
cksumb;uint16_tagea,ageb;assert(a&&a->header);assert(b&&b->header);assert(OSPF6_
LSA_IS_SAME(a,b));seqnuma=(int32_t)ntohl(a->header->seqnum);seqnumb=(int32_t)nto
hl(b->header->seqnum);/*comparebysequencenumber*/if(seqnuma>seqnumb)return-1;if(
seqnuma<seqnumb)return1;/*Checksum*/cksuma=ntohs(a->header->checksum);cksumb=nto
hs(b->header->checksum);if(cksuma>cksumb)return-1;if(cksuma<cksumb)return0;/*Upd
ateAge*/agea=ospf6_lsa_age_current(a);ageb=ospf6_lsa_age_current(b);/*MaxAgechec
k*/if(agea==OSPF_LSA_MAXAGE&&ageb!=OSPF_LSA_MAXAGE)return-1;elseif(agea!=OSPF_LS
A_MAXAGE&&ageb==OSPF_LSA_MAXAGE)return1;/*Agecheck*/if(agea>ageb&&agea-ageb>=OSP
F_LSA_MAXAGE_DIFF)return1;elseif(agea<ageb&&ageb-agea>=OSPF_LSA_MAXAGE_DIFF)retu
rn-1;/*neitherrecent*/return0;}char*ospf6_lsa_printbuf(structospf6_lsa*lsa,char*
buf,intsize){charid[16],adv_router[16];inet_ntop(AF_INET,&lsa->header->id,id,siz
eof(id));inet_ntop(AF_INET,&lsa->header->adv_router,adv_router,sizeof(adv_router
));snprintf(buf,size,"[%sId:%sAdv:%s]",ospf6_lstype_name(lsa->header->type),id,a
dv_router);returnbuf;}voidospf6_lsa_header_print_raw(structospf6_lsa_header*head
er){charid[16],adv_router[16];inet_ntop(AF_INET,&header->id,id,sizeof(id));inet_
ntop(AF_INET,&header->adv_router,adv_router,sizeof(adv_router));zlog_debug("[%sI
d:%sAdv:%s]",ospf6_lstype_name(header->type),id,adv_router);zlog_debug("Age:%4hu
SeqNum:%#08lxCksum:%04hxLen:%d",ntohs(header->age),(unsignedlong)ntohl(header->s
eqnum),ntohs(header->checksum),ntohs(header->length));}voidospf6_lsa_header_prin
t(structospf6_lsa*lsa){ospf6_lsa_age_current(lsa);ospf6_lsa_header_print_raw(lsa
->header);}voidospf6_lsa_show_summary_header(structvty*vty){vty_out(vty,"%-4s%-1
5s%-15s%4s%8s%30s\n","Type","LSId","AdvRouter","Age","SeqNum","Payload");}voidos
pf6_lsa_show_summary(structvty*vty,structospf6_lsa*lsa){charadv_router[16],id[16
];inttype;conststructospf6_lsa_handler*handler;charbuf[64],tmpbuf[80];intcnt=0;a
ssert(lsa);assert(lsa->header);inet_ntop(AF_INET,&lsa->header->id,id,sizeof(id))
;inet_ntop(AF_INET,&lsa->header->adv_router,adv_router,sizeof(adv_router));type=
ntohs(lsa->header->type);handler=ospf6_get_lsa_handler(lsa->header->type);if((ty
pe==OSPF6_LSTYPE_INTER_PREFIX)||(type==OSPF6_LSTYPE_INTER_ROUTER)||(type==OSPF6_
LSTYPE_AS_EXTERNAL)){vty_out(vty,"%-4s%-15s%-15s%4hu%8lx%30s\n",ospf6_lstype_sho
rt_name(lsa->header->type),id,adv_router,ospf6_lsa_age_current(lsa),(unsignedlon
g)ntohl(lsa->header->seqnum),handler->lh_get_prefix_str(lsa,buf,sizeof(buf),0));
}elseif(type!=OSPF6_LSTYPE_UNKNOWN){sprintf(tmpbuf,"%-4s%-15s%-15s%4hu%8lx",ospf
6_lstype_short_name(lsa->header->type),id,adv_router,ospf6_lsa_age_current(lsa),
(unsignedlong)ntohl(lsa->header->seqnum));while(handler->lh_get_prefix_str(lsa,b
uf,sizeof(buf),cnt)!=NULL){vty_out(vty,"%s%30s\n",tmpbuf,buf);cnt++;}}else{vty_o
ut(vty,"%-4s%-15s%-15s%4hu%8lx\n",ospf6_lstype_short_name(lsa->header->type),id,
adv_router,ospf6_lsa_age_current(lsa),(unsignedlong)ntohl(lsa->header->seqnum));
}}voidospf6_lsa_show_dump(structvty*vty,structospf6_lsa*lsa){uint8_t*start,*end,
*current;charbyte[4];start=(uint8_t*)lsa->header;end=(uint8_t*)lsa->header+ntohs
(lsa->header->length);vty_out(vty,"\n");vty_out(vty,"%s:\n",lsa->name);for(curre
nt=start;current<end;current++){if((current-start)%16==0)vty_out(vty,"\n");elsei
f((current-start)%4==0)vty_out(vty,"");snprintf(byte,sizeof(byte),"%02x",*curren
t);vty_out(vty,"%s",byte);}vty_out(vty,"\n\n");return;}voidospf6_lsa_show_intern
al(structvty*vty,structospf6_lsa*lsa){charadv_router[64],id[64];assert(lsa&&lsa-
>header);inet_ntop(AF_INET,&lsa->header->id,id,sizeof(id));inet_ntop(AF_INET,&ls
a->header->adv_router,adv_router,sizeof(adv_router));vty_out(vty,"\n");vty_out(v
ty,"Age:%4huType:%s\n",ospf6_lsa_age_current(lsa),ospf6_lstype_name(lsa->header-
>type));vty_out(vty,"LinkStateID:%s\n",id);vty_out(vty,"AdvertisingRouter:%s\n",
adv_router);vty_out(vty,"LSSequenceNumber:%#010lx\n",(unsignedlong)ntohl(lsa->he
ader->seqnum));vty_out(vty,"CheckSum:%#06hxLength:%hu\n",ntohs(lsa->header->chec
ksum),ntohs(lsa->header->length));vty_out(vty,"Flag:%x\n",lsa->flag);vty_out(vty
,"Lock:%d\n",lsa->lock);vty_out(vty,"ReTxCount:%d\n",lsa->retrans_count);vty_out
(vty,"Threads:Expire:0x%p,Refresh:0x%p\n",(void*)lsa->expire,(void*)lsa->refresh
);vty_out(vty,"\n");return;}voidospf6_lsa_show(structvty*vty,structospf6_lsa*lsa
){charadv_router[64],id[64];conststructospf6_lsa_handler*handler;structtimevalno
w,res;charduration[64];assert(lsa&&lsa->header);inet_ntop(AF_INET,&lsa->header->
id,id,sizeof(id));inet_ntop(AF_INET,&lsa->header->adv_router,adv_router,sizeof(a
dv_router));monotime(&now);timersub(&now,&lsa->installed,&res);timerstring(&res,
duration,sizeof(duration));vty_out(vty,"Age:%4huType:%s\n",ospf6_lsa_age_current
(lsa),ospf6_lstype_name(lsa->header->type));vty_out(vty,"LinkStateID:%s\n",id);v
ty_out(vty,"AdvertisingRouter:%s\n",adv_router);vty_out(vty,"LSSequenceNumber:%#
010lx\n",(unsignedlong)ntohl(lsa->header->seqnum));vty_out(vty,"CheckSum:%#06hxL
ength:%hu\n",ntohs(lsa->header->checksum),ntohs(lsa->header->length));vty_out(vt
y,"Duration:%s\n",duration);handler=ospf6_get_lsa_handler(lsa->header->type);if(
handler->lh_show!=NULL)handler->lh_show(vty,lsa);else{assert(unknown_handler.lh_
show!=NULL);unknown_handler.lh_show(vty,lsa);}vty_out(vty,"\n");}/*OSPFv3LSAcrea
tion/deletionfunction*/structospf6_lsa*ospf6_lsa_create(structospf6_lsa_header*h
eader){structospf6_lsa*lsa=NULL;structospf6_lsa_header*new_header=NULL;uint16_tl
sa_size=0;/*sizeoftheentireLSA*/lsa_size=ntohs(header->length);/*XXXvulnerable*/
/*allocatememoryforthisLSA*/new_header=(structospf6_lsa_header*)XMALLOC(MTYPE_OS
PF6_LSA_HEADER,lsa_size);/*copyLSAfromoriginalheader*/memcpy(new_header,header,l
sa_size);/*LSAinformationstructure*//*allocatememory*/lsa=(structospf6_lsa*)XCAL
LOC(MTYPE_OSPF6_LSA,sizeof(structospf6_lsa));lsa->header=(structospf6_lsa_header
*)new_header;/*dumpstring*/ospf6_lsa_printbuf(lsa,lsa->name,sizeof(lsa->name));/
*calculatebirthofthislsa*/ospf6_lsa_age_set(lsa);returnlsa;}structospf6_lsa*ospf
6_lsa_create_headeronly(structospf6_lsa_header*header){structospf6_lsa*lsa=NULL;
structospf6_lsa_header*new_header=NULL;/*allocatememoryforthisLSA*/new_header=(s
tructospf6_lsa_header*)XMALLOC(MTYPE_OSPF6_LSA_HEADER,sizeof(structospf6_lsa_hea
der));/*copyLSAfromoriginalheader*/memcpy(new_header,header,sizeof(structospf6_l
sa_header));/*LSAinformationstructure*//*allocatememory*/lsa=(structospf6_lsa*)X
CALLOC(MTYPE_OSPF6_LSA,sizeof(structospf6_lsa));lsa->header=(structospf6_lsa_hea
der*)new_header;SET_FLAG(lsa->flag,OSPF6_LSA_HEADERONLY);/*dumpstring*/ospf6_lsa
_printbuf(lsa,lsa->name,sizeof(lsa->name));/*calculatebirthofthislsa*/ospf6_lsa_
age_set(lsa);returnlsa;}voidospf6_lsa_delete(structospf6_lsa*lsa){assert(lsa->lo
ck==0);/*cancelthreads*/THREAD_OFF(lsa->expire);THREAD_OFF(lsa->refresh);/*dofre
e*/XFREE(MTYPE_OSPF6_LSA_HEADER,lsa->header);XFREE(MTYPE_OSPF6_LSA,lsa);}structo
spf6_lsa*ospf6_lsa_copy(structospf6_lsa*lsa){structospf6_lsa*copy=NULL;ospf6_lsa
_age_current(lsa);if(CHECK_FLAG(lsa->flag,OSPF6_LSA_HEADERONLY))copy=ospf6_lsa_c
reate_headeronly(lsa->header);elsecopy=ospf6_lsa_create(lsa->header);assert(copy
->lock==0);copy->birth=lsa->birth;copy->originated=lsa->originated;copy->receive
d=lsa->received;copy->installed=lsa->installed;copy->lsdb=lsa->lsdb;copy->rn=NUL
L;returncopy;}/*incrementreferencecounterofstructospf6_lsa*/voidospf6_lsa_lock(s
tructospf6_lsa*lsa){lsa->lock++;return;}/*decrementreferencecounterofstructospf6
_lsa*/voidospf6_lsa_unlock(structospf6_lsa*lsa){/*decrementreferencecounter*/ass
ert(lsa->lock>0);lsa->lock--;if(lsa->lock!=0)return;ospf6_lsa_delete(lsa);}/*osp
f6lsaexpiry*/intospf6_lsa_expire(structthread*thread){structospf6_lsa*lsa;lsa=(s
tructospf6_lsa*)THREAD_ARG(thread);assert(lsa&&lsa->header);assert(OSPF6_LSA_IS_
MAXAGE(lsa));assert(!lsa->refresh);lsa->expire=(structthread*)NULL;if(IS_OSPF6_D
EBUG_LSA_TYPE(lsa->header->type)){zlog_debug("LSAExpire:");ospf6_lsa_header_prin
t(lsa);}if(CHECK_FLAG(lsa->flag,OSPF6_LSA_HEADERONLY))return0;/*dbexchangewilldo
something...*//*reinstalllsa*/ospf6_install_lsa(lsa);/*refloodlsa*/ospf6_flood(N
ULL,lsa);/*schedulemaxageremover*/ospf6_maxage_remove(ospf6);return0;}intospf6_l
sa_refresh(structthread*thread){structospf6_lsa*old,*self,*new;structospf6_lsdb*
lsdb_self;old=(structospf6_lsa*)THREAD_ARG(thread);assert(old&&old->header);old-
>refresh=(structthread*)NULL;lsdb_self=ospf6_get_scoped_lsdb_self(old);self=ospf
6_lsdb_lookup(old->header->type,old->header->id,old->header->adv_router,lsdb_sel
f);if(self==NULL){if(IS_OSPF6_DEBUG_LSA_TYPE(old->header->type))zlog_debug("Refr
esh:couldnotfindselfLSA,flush%s",old->name);ospf6_lsa_premature_aging(old);retur
n0;}/*Resetage,incrementLSsequencenumber.*/self->header->age=htons(0);self->head
er->seqnum=ospf6_new_ls_seqnum(self->header->type,self->header->id,self->header-
>adv_router,old->lsdb);ospf6_lsa_checksum(self->header);new=ospf6_lsa_create(sel
f->header);new->lsdb=old->lsdb;new->refresh=NULL;thread_add_timer(master,ospf6_l
sa_refresh,new,OSPF_LS_REFRESH_TIME,&new->refresh);/*storeitintheLSDBforself-ori
ginatedLSAs*/ospf6_lsdb_add(ospf6_lsa_copy(new),lsdb_self);if(IS_OSPF6_DEBUG_LSA
_TYPE(new->header->type)){zlog_debug("LSARefresh:");ospf6_lsa_header_print(new);
}ospf6_install_lsa(new);ospf6_flood(NULL,new);return0;}voidospf6_flush_self_orig
inated_lsas_now(void){structlistnode*node;structospf6_area*oa;structospf6_lsa*ls
a;conststructroute_node*end=NULL;uint32_ttype,adv_router;ospf6->inst_shutdown=1;
for(ALL_LIST_ELEMENTS_RO(ospf6->area_list,node,oa)){end=ospf6_lsdb_head(oa->lsdb
_self,0,0,ospf6->router_id,&lsa);while(lsa){/*RFC2328(14.1):SetMAXAGE*/lsa->head
er->age=htons(OSPF_LSA_MAXAGE);/*FloodMAXAGELSA*/ospf6_flood(NULL,lsa);lsa=ospf6
_lsdb_next(end,lsa);}}type=htons(OSPF6_LSTYPE_AS_EXTERNAL);adv_router=ospf6->rou
ter_id;for(ALL_LSDB_TYPED_ADVRTR(ospf6->lsdb,type,adv_router,lsa)){/*RFC2328(14.
1):SetMAXAGE*/lsa->header->age=htons(OSPF_LSA_MAXAGE);ospf6_flood(NULL,lsa);}}/*
FletcherChecksum--RefertoRFC1008.*//*Alltheoffsetsarezero-based.TheoffsetsintheR
FC1008areone-based.*/unsignedshortospf6_lsa_checksum(structospf6_lsa_header*lsa_
header){uint8_t*buffer=(uint8_t*)&lsa_header->type;inttype_offset=buffer-(uint8_
t*)&lsa_header->age;/*shouldbe2*//*SkiptheAGEfield*/uint16_tlen=ntohs(lsa_header
->length)-type_offset;/*Checksumoffsetstartsfrom"type"field,notthebeginningofthe
lsa_headerstruct.Theoffsetis14,ratherthan16.*/intchecksum_offset=(uint8_t*)&lsa_
header->checksum-buffer;return(unsignedshort)fletcher_checksum(buffer,len,checks
um_offset);}intospf6_lsa_checksum_valid(structospf6_lsa_header*lsa_header){uint8
_t*buffer=(uint8_t*)&lsa_header->type;inttype_offset=buffer-(uint8_t*)&lsa_heade
r->age;/*shouldbe2*//*SkiptheAGEfield*/uint16_tlen=ntohs(lsa_header->length)-typ
e_offset;return(fletcher_checksum(buffer,len,FLETCHER_CHECKSUM_VALIDATE)==0);}vo
idospf6_lsa_init(void){ospf6_lsa_handler_vector=vector_init(0);ospf6_install_lsa
_handler(&unknown_handler);}voidospf6_lsa_terminate(void){vector_free(ospf6_lsa_
handler_vector);}staticchar*ospf6_lsa_handler_name(conststructospf6_lsa_handler*
h){staticcharbuf[64];unsignedinti;unsignedintsize=strlen(h->lh_name);if(!strcmp(
h->lh_name,"unknown")&&h->lh_type!=OSPF6_LSTYPE_UNKNOWN){snprintf(buf,sizeof(buf
),"%#04hx",h->lh_type);returnbuf;}for(i=0;i<MIN(size,sizeof(buf));i++){if(!islow
er((unsignedchar)h->lh_name[i]))buf[i]=tolower((unsignedchar)h->lh_name[i]);else
buf[i]=h->lh_name[i];}buf[size]='\0';returnbuf;}DEFUN(debug_ospf6_lsa_type,debug
_ospf6_lsa_hex_cmd,"debugospf6lsa<router|network|inter-prefix|inter-router|as-ex
ternal|link|intra-prefix|unknown>[<originate|examine|flooding>]",DEBUG_STROSPF6_
STR"DebugLinkStateAdvertisements(LSAs)\n""DisplayRouterLSAs\n""DisplayNetworkLSA
s\n""DisplayInter-Area-PrefixLSAs\n""DisplayInter-RouterLSAs\n""DisplayAs-Extern
alLSAs\n""DisplayLinkLSAs\n""DisplayIntra-Area-PrefixLSAs\n""DisplayLSAsofunknow
norigin\n""DisplaydetailsofLSAs\n""DumpLSAs\n""DisplayLSA'sinternalinformation\n
"){intidx_lsa=3;intidx_type=4;unsignedinti;structospf6_lsa_handler*handler=NULL;
for(i=0;i<vector_active(ospf6_lsa_handler_vector);i++){handler=vector_slot(ospf6
_lsa_handler_vector,i);if(handler==NULL)continue;if(strncmp(argv[idx_lsa]->arg,o
spf6_lsa_handler_name(handler),strlen(argv[idx_lsa]->arg))==0)break;if(!strcasec
mp(argv[idx_lsa]->arg,handler->lh_name))break;handler=NULL;}if(handler==NULL)han
dler=&unknown_handler;if(argc==5){if(strmatch(argv[idx_type]->text,"originate"))
SET_FLAG(handler->debug,OSPF6_LSA_DEBUG_ORIGINATE);elseif(strmatch(argv[idx_type
]->text,"examine"))SET_FLAG(handler->debug,OSPF6_LSA_DEBUG_EXAMIN);elseif(strmat
ch(argv[idx_type]->text,"flooding"))SET_FLAG(handler->debug,OSPF6_LSA_DEBUG_FLOO
D);}elseSET_FLAG(handler->debug,OSPF6_LSA_DEBUG);returnCMD_SUCCESS;}DEFUN(no_deb
ug_ospf6_lsa_type,no_debug_ospf6_lsa_hex_cmd,"nodebugospf6lsa<router|network|int
er-prefix|inter-router|as-external|link|intra-prefix|unknown>[<originate|examine
|flooding>]",NO_STRDEBUG_STROSPF6_STR"DebugLinkStateAdvertisements(LSAs)\n""Disp
layRouterLSAs\n""DisplayNetworkLSAs\n""DisplayInter-Area-PrefixLSAs\n""DisplayIn
ter-RouterLSAs\n""DisplayAs-ExternalLSAs\n""DisplayLinkLSAs\n""DisplayIntra-Area
-PrefixLSAs\n""DisplayLSAsofunknownorigin\n""DisplaydetailsofLSAs\n""DumpLSAs\n"
"DisplayLSA'sinternalinformation\n"){intidx_lsa=4;intidx_type=5;unsignedinti;str
uctospf6_lsa_handler*handler=NULL;for(i=0;i<vector_active(ospf6_lsa_handler_vect
or);i++){handler=vector_slot(ospf6_lsa_handler_vector,i);if(handler==NULL)contin
ue;if(strncmp(argv[idx_lsa]->arg,ospf6_lsa_handler_name(handler),strlen(argv[idx
_lsa]->arg))==0)break;if(!strcasecmp(argv[idx_lsa]->arg,handler->lh_name))break;
}if(handler==NULL)returnCMD_SUCCESS;if(argc==6){if(strmatch(argv[idx_type]->text
,"originate"))UNSET_FLAG(handler->debug,OSPF6_LSA_DEBUG_ORIGINATE);if(strmatch(a
rgv[idx_type]->text,"examine"))UNSET_FLAG(handler->debug,OSPF6_LSA_DEBUG_EXAMIN)
;if(strmatch(argv[idx_type]->text,"flooding"))UNSET_FLAG(handler->debug,OSPF6_LS
A_DEBUG_FLOOD);}elseUNSET_FLAG(handler->debug,OSPF6_LSA_DEBUG);returnCMD_SUCCESS
;}voidinstall_element_ospf6_debug_lsa(void){install_element(ENABLE_NODE,&debug_o
spf6_lsa_hex_cmd);install_element(ENABLE_NODE,&no_debug_ospf6_lsa_hex_cmd);insta
ll_element(CONFIG_NODE,&debug_ospf6_lsa_hex_cmd);install_element(CONFIG_NODE,&no
_debug_ospf6_lsa_hex_cmd);}intconfig_write_ospf6_debug_lsa(structvty*vty){unsign
edinti;conststructospf6_lsa_handler*handler;for(i=0;i<vector_active(ospf6_lsa_ha
ndler_vector);i++){handler=vector_slot(ospf6_lsa_handler_vector,i);if(handler==N
ULL)continue;if(CHECK_FLAG(handler->debug,OSPF6_LSA_DEBUG))vty_out(vty,"debugosp
f6lsa%s\n",ospf6_lsa_handler_name(handler));if(CHECK_FLAG(handler->debug,OSPF6_L
SA_DEBUG_ORIGINATE))vty_out(vty,"debugospf6lsa%soriginate\n",ospf6_lsa_handler_n
ame(handler));if(CHECK_FLAG(handler->debug,OSPF6_LSA_DEBUG_EXAMIN))vty_out(vty,"
debugospf6lsa%sexamine\n",ospf6_lsa_handler_name(handler));if(CHECK_FLAG(handler
->debug,OSPF6_LSA_DEBUG_FLOOD))vty_out(vty,"debugospf6lsa%sflooding\n",ospf6_lsa
_handler_name(handler));}return0;}