/**GNUZebraclienttestmainroutine.*Copyright(C)1997KunihiroIshiguro**Thisfileispa
rtofGNUZebra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodifyit*underth
etermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;either
version2,or(atyouroption)any*laterversion.**GNUZebraisdistributedinthehopethatit
willbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABIL
ITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.*
*YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;see
thefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFl
oor,Boston,MA02110-1301USA*/#include<zebra.h>#include"prefix.h"#include"stream.h
"#include"zclient.h"#include"thread.h"#include"table.h"#include"zebra/rib.h"#inc
lude"zebra/zserv.h"structthread*master;/*Zebraclientstructure.*/structzclient*zc
lient=NULL;/*Zebrasocket.*/intsock;/*IPv4routeaddanddeletetest.*/voidzebra_test_
ipv4(intcommand,inttype,char*prefix,char*gateway,uint8_tdistance){structzapi_ipv
4api;structprefix_ipv4p;structin_addrgate;structin_addr*gpnt;str2prefix_ipv4(pre
fix,&p);if(!inet_aton(gateway,&gate)){printf("Gatewayspecified:%sisillegal\n",ga
teway);return;}gpnt=&gate;api.vrf_id=VRF_DEFAULT;api.type=type;api.flags=0;api.m
essage=0;SET_FLAG(api.message,ZAPI_MESSAGE_NEXTHOP);api.nexthop_num=1;api.nextho
p=&gpnt;api.ifindex_num=0;if(distance){SET_FLAG(api.message,ZAPI_MESSAGE_DISTANC
E);api.distance=distance;}switch(command){caseZEBRA_IPV4_ROUTE_ADD:zapi_ipv4_add
(zclient,&p,&api);break;caseZEBRA_IPV4_ROUTE_DELETE:zapi_ipv4_delete(zclient,&p,
&api);break;}}/*IPv6routeaddanddeletetest.*/voidzebra_test_v6(intsock){structpre
fix_ipv6p;structin6_addrnexthop;str2prefix_ipv6("3ffe:506::2/128",&p);inet_pton(
AF_INET6,"::1",&nexthop);/*zebra_ipv6_add(sock,ZEBRA_ROUTE_STATIC,0,&p,&nexthop,
1);*/sleep(5);/*zebra_ipv6_delete(sock,ZEBRA_ROUTE_STATIC,0,&p,&nexthop,1);*/}/*
Printoutusageandexit.*/voidusage_exit(){fprintf(stderr,"Usage:clientfilename\n")
;exit(1);}structzebra_info{char*str;inttype;}zebra_type[]={{"static",ZEBRA_ROUTE
_STATIC},{"rip",ZEBRA_ROUTE_RIP},{"ripng",ZEBRA_ROUTE_RIPNG},{"ospf",ZEBRA_ROUTE
_OSPF},{"ospf6",ZEBRA_ROUTE_OSPF6},{"bgp",ZEBRA_ROUTE_BGP},{"nhrp",ZEBRA_ROUTE_N
HRP},{"pim",ZEBRA_ROUTE_PIM},{NULL,0}};/*Zebraroutesimulator.*/voidzebra_sim(FIL
E*fp){charbuf[BUFSIZ];chardistance_str[BUFSIZ];uint8_tdistance;while(fgets(buf,s
izeofbuf,fp)){inti;intret;inttype;charstr[BUFSIZ],command[BUFSIZ],prefix[BUFSIZ]
,gateway[BUFSIZ];distance=0;if(*buf=='#')continue;type=ZEBRA_ROUTE_STATIC;ret=ss
canf(buf,"%s%s%s%s%s\n",command,str,prefix,gateway,distance_str);if(ret==5){dist
ance=atoi(distance_str);}else{ret=sscanf(buf,"%s%s%s%s\n",command,str,prefix,gat
eway);if(ret!=4)continue;}for(i=0;i<10;i++){if(!zebra_type[i].str)break;if(strcm
p(zebra_type[i].str,str)==0){type=zebra_type[i].type;break;}}if(strcmp(command,"
add")==0){zebra_test_ipv4(ZEBRA_IPV4_ROUTE_ADD,type,prefix,gateway,distance);pri
ntf("%s",buf);continue;}if(strcmp(command,"del")==0){zebra_test_ipv4(ZEBRA_IPV4_
ROUTE_DELETE,type,prefix,gateway,distance);printf("%s",buf);continue;}}}/*Testze
braclientmainroutine.*/intmain(intargc,char**argv){structthread_master*master;FI
LE*fp;if(argc==1)usage_exit();master=thread_master_create(NULL);/*Establishconne
ctiontozebra.*/zclient=zclient_new_notify(master,&zclient_options_default);zclie
nt->enable=1;zclient_socket_connect(zclient);/*Opensimulationfile.*/fp=fopen(arg
v[1],"r");if(fp==NULL){fprintf(stderr,"%%Can'topenconfigurationfile%sdueto'%s'\n
",argv[1],safe_strerror(errno));exit(1);}/*Domainwork.*/zebra_sim(fp);sleep(100)
;fclose(fp);close(sock);return0;}