/***Copyright(C)2000RobertOlsson.*SwedishUniversityofAgriculturalSciences**Thisf
ileispartofGNUZebra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodifyit*
underthetermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation
;eitherversion2,or(atyouroption)any*laterversion.**GNUZebraisdistributedinthehop
ethatitwillbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCH
ANTABILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformorede
tails.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprog
ram;seethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,
FifthFloor,Boston,MA02110-1301USA*//**Thisworkincludesworkwiththefollowingcopywr
ite:**Copyright(C)1997,2000KunihiroIshiguro**//**ThankstoJensLååsatSwedishUniversityofAgriculturalSciences*forreviewingandtests.*/#include<zebra
.h>#include"if.h"#include"vty.h"#include"sockunion.h"#include"sockopt.h"#include
"prefix.h"#include"command.h"#include"memory.h"#include"zebra_memory.h"#include"
stream.h"#include"ioctl.h"#include"connected.h"#include"log.h"#include"zclient.h
"#include"thread.h"#include"privs.h"#include"libfrr.h"#include"version.h"#includ
e"zebra/interface.h"#include"zebra/rtadv.h"#include"zebra/rib.h"#include"zebra/z
serv.h"#include"zebra/redistribute.h"#include"zebra/irdp.h"#include<netinet/ip_i
cmp.h>#include"checksum.h"#include"if.h"#include"sockunion.h"#include"log.h"/*GL
OBALVARS*/externstructzebra_privs_tzserv_privs;structthread*t_irdp_raw;/*Timerin
tervalofirdp.*/intirdp_timer_interval=IRDP_DEFAULT_INTERVAL;intirdp_sock_init(vo
id){intret,i;intsave_errno;intsock;if(zserv_privs.change(ZPRIVS_RAISE))zlog_err(
"irdp_sock_init:couldnotraiseprivs,%s",safe_strerror(errno));sock=socket(AF_INET
,SOCK_RAW,IPPROTO_ICMP);save_errno=errno;if(zserv_privs.change(ZPRIVS_LOWER))zlo
g_err("irdp_sock_init:couldnotlowerprivs,%s",safe_strerror(errno));if(sock<0){zl
og_warn("IRDP:can'tcreateirdpsocket%s",safe_strerror(save_errno));returnsock;};i
=1;ret=setsockopt(sock,IPPROTO_IP,IP_TTL,(void*)&i,sizeof(i));if(ret<0){zlog_war
n("IRDP:can'tdoirdpsockopt%s",safe_strerror(errno));close(sock);returnret;};ret=
setsockopt_ifindex(AF_INET,sock,1);if(ret<0){zlog_warn("IRDP:can'tdoirdpsockopt%
s",safe_strerror(errno));close(sock);returnret;};t_irdp_raw=NULL;thread_add_read
(zebrad.master,irdp_read_raw,NULL,sock,&t_irdp_raw);returnsock;}staticintget_pre
f(structirdp_interface*irdp,structprefix*p){structlistnode*node;structAdv*adv;/*
Usedefaultpreferenceorusetheoverridepref*/if(irdp->AdvPrefList==NULL)returnirdp-
>Preference;for(ALL_LIST_ELEMENTS_RO(irdp->AdvPrefList,node,adv))if(p->u.prefix4
.s_addr==adv->ip.s_addr)returnadv->pref;returnirdp->Preference;}/*MakeICMPRouter
AdvertisementMessage.*/staticintmake_advertisement_packet(structinterface*ifp,st
ructprefix*p,structstream*s){structzebra_if*zi=ifp->info;structirdp_interface*ir
dp=zi->irdp;intsize;intpref;uint16_tchecksum;pref=get_pref(irdp,p);stream_putc(s
,ICMP_ROUTERADVERT);/*Type.*/stream_putc(s,0);/*Code.*/stream_putw(s,0);/*Checks
um.*/stream_putc(s,1);/*Numaddress.*/stream_putc(s,2);/*AddressEntrySize.*/if(ir
dp->flags&IF_SHUTDOWN)stream_putw(s,0);elsestream_putw(s,irdp->Lifetime);stream_
putl(s,htonl(p->u.prefix4.s_addr));/*Routeraddress.*/stream_putl(s,pref);/*in_ck
sumreturnnetworkbyteordervalue*/size=16;checksum=in_cksum(s->data,size);stream_p
utw_at(s,2,htons(checksum));returnsize;}staticvoidirdp_send(structinterface*ifp,
structprefix*p,structstream*s){structzebra_if*zi=ifp->info;structirdp_interface*
irdp=zi->irdp;charbuf[PREFIX_STRLEN];uint32_tdst;uint32_tttl=1;if(!irdp)return;i
f(!(ifp->flags&IFF_UP))return;if(irdp->flags&IF_BROADCAST)dst=INADDR_BROADCAST;e
lsedst=htonl(INADDR_ALLHOSTS_GROUP);if(irdp->flags&IF_DEBUG_MESSAGES)zlog_debug(
"IRDP:TXAdverton%s%sHoldtime=%dPreference=%d",ifp->name,prefix2str(p,buf,sizeofb
uf),irdp->flags&IF_SHUTDOWN?0:irdp->Lifetime,get_pref(irdp,p));send_packet(ifp,s
,dst,p,ttl);}staticvoidirdp_advertisement(structinterface*ifp,structprefix*p){st
ructstream*s;s=stream_new(128);make_advertisement_packet(ifp,p,s);irdp_send(ifp,
p,s);stream_free(s);}intirdp_send_thread(structthread*t_advert){uint32_ttimer,tm
p;structinterface*ifp=THREAD_ARG(t_advert);structzebra_if*zi=ifp->info;structird
p_interface*irdp=zi->irdp;structprefix*p;structlistnode*node,*nnode;structconnec
ted*ifc;if(!irdp)return0;irdp->flags&=~IF_SOLICIT;if(ifp->connected)for(ALL_LIST
_ELEMENTS(ifp->connected,node,nnode,ifc)){p=ifc->address;if(p->family!=AF_INET)c
ontinue;irdp_advertisement(ifp,p);irdp->irdp_sent++;}tmp=irdp->MaxAdvertInterval
-irdp->MinAdvertInterval;timer=random()%(tmp+1);timer=irdp->MinAdvertInterval+ti
mer;if(irdp->irdp_sent<MAX_INITIAL_ADVERTISEMENTS&&timer>MAX_INITIAL_ADVERT_INTE
RVAL)timer=MAX_INITIAL_ADVERT_INTERVAL;if(irdp->flags&IF_DEBUG_MISC)zlog_debug("
IRDP:Newtimerfor%ssetto%u\n",ifp->name,timer);irdp->t_advertise=NULL;thread_add_
timer(zebrad.master,irdp_send_thread,ifp,timer,&irdp->t_advertise);return0;}void
irdp_advert_off(structinterface*ifp){structzebra_if*zi=ifp->info;structirdp_inte
rface*irdp=zi->irdp;structlistnode*node,*nnode;inti;structconnected*ifc;structpr
efix*p;if(!irdp)return;if(irdp->t_advertise)thread_cancel(irdp->t_advertise);ird
p->t_advertise=NULL;if(ifp->connected)for(ALL_LIST_ELEMENTS(ifp->connected,node,
nnode,ifc)){p=ifc->address;/*OutputsomepacketswithLifetime0weshouldaddawait...*/
for(i=0;i<IRDP_LAST_ADVERT_MESSAGES;i++){irdp->irdp_sent++;irdp_advertisement(if
p,p);}}}voidprocess_solicit(structinterface*ifp){structzebra_if*zi=ifp->info;str
uctirdp_interface*irdp=zi->irdp;uint32_ttimer;if(!irdp)return;/*WhenSOLICITisact
ivewerejectfurtherincomingsolicitsthiskeepsdowntheansweringratesowedon'thavethin
kaboutDoSattackshere.*/if(irdp->flags&IF_SOLICIT)return;irdp->flags|=IF_SOLICIT;
if(irdp->t_advertise)thread_cancel(irdp->t_advertise);irdp->t_advertise=NULL;tim
er=(random()%MAX_RESPONSE_DELAY)+1;irdp->t_advertise=NULL;thread_add_timer(zebra
d.master,irdp_send_thread,ifp,timer,&irdp->t_advertise);}staticintirdp_finish(vo
id){structvrf*vrf;structinterface*ifp;structzebra_if*zi;structirdp_interface*ird
p;zlog_info("IRDP:Receivedshutdownnotification.");RB_FOREACH(vrf,vrf_id_head,&vr
fs_by_id)FOR_ALL_INTERFACES(vrf,ifp){zi=ifp->info;if(!zi)continue;irdp=zi->irdp;
if(!irdp)continue;if(irdp->flags&IF_ACTIVE){irdp->flags|=IF_SHUTDOWN;irdp_advert
_off(ifp);}}return0;}staticintirdp_init(structthread_master*master){irdp_if_init
();hook_register(frr_early_fini,irdp_finish);return0;}staticintirdp_module_init(
void){hook_register(frr_late_init,irdp_init);return0;}FRR_MODULE_SETUP(.name="ze
bra_irdp",.version=FRR_VERSION,.description="zebraIRDPmodule",.init=irdp_module_
init,)