/*Kernelcommunicationusingroutingsocket.*Copyright(C)1999KunihiroIshiguro**Thisf
ileispartofGNUZebra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodifyit*
underthetermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation
;eitherversion2,or(atyouroption)any*laterversion.**GNUZebraisdistributedinthehop
ethatitwillbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCH
ANTABILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformorede
tails.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprog
ram;seethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,
FifthFloor,Boston,MA02110-1301USA*/#include<zebra.h>#ifndefHAVE_NETLINK#include<
net/if_types.h>#ifdef__OpenBSD__#include<netmpls/mpls.h>#endif#include"if.h"#inc
lude"prefix.h"#include"sockunion.h"#include"connected.h"#include"memory.h"#inclu
de"zebra_memory.h"#include"ioctl.h"#include"log.h"#include"table.h"#include"rib.
h"#include"privs.h"#include"vrf.h"#include"zebra/rt.h"#include"zebra/interface.h
"#include"zebra/zserv.h"#include"zebra/debug.h"#include"zebra/kernel_socket.h"#i
nclude"zebra/rib.h"externstructzebra_privs_tzserv_privs;/**Historically,theBSDro
utingsockethasaligneddatafollowinga*structsockaddrtosizeof(long),whichwas4byteso
nsome*platforms,and8bytesonothers.NetBSD6changedtherouting*sockettoaligntosizeof
(uint64_t),whichis8bytes.OSX*appearstoaligntosizeof(int),whichis4bytes.**Alignme
ntofzero-sizedsockaddrsisnonsensical,buthistorically*BSDdefinesRT_ROUNDUP(0)tobe
thealignmentinterval(ratherthan*0).Wefollowthispracticewithoutquestioningit,buti
tisa*bugifquaggacallsROUNDUPwith0.*//**Becauseofthesevaryingconventions,theonlys
aneapproachisfor*the<net/route.h>headertodefinesomeflavorofROUNDUPmacro.*/#ifdef
ined(SA_SIZE)/*SAROUNDUPistheonlythingweneed,andSA_SIZEprovidesthat*/#defineSARO
UNDUP(a)SA_SIZE(a)#else/*!SA_SIZE*/#ifdefined(RT_ROUNDUP)#defineROUNDUP(a)RT_ROU
NDUP(a)#endif/*defined(RT_ROUNDUP)*/#ifdefined(SUNOS_5)/*Solarishasstructsockadd
r_in[6]definitionsat16/32bytessize,*sothewholeconceptdoesn'treallyapply.*/#defin
eROUNDUP(a)(a)#endif/**IfROUNDUPhasnotyetbeendefinedintermsofplatform-provided*d
efines,attempttocopewithheuristics.*/#if!defined(ROUNDUP)/**Ifyou'reportingtoapl
atformthatchangedRT_ROUNDUPbutdoesn't*haveitinitsheaders,thiswillbreakratherobvi
ouslyandyou'll*havetofixithere.*//*OSX(Xcodeasof2014-12)isknownnottodefineRT_ROU
NDUP*/#ifdef__APPLE__#defineROUNDUP_TYPEint#else#defineROUNDUP_TYPElong#endif#de
fineROUNDUP(a)\((a)>0?(1+(((a)-1)|(sizeof(ROUNDUP_TYPE)-1)))\:sizeof(ROUNDUP_TYP
E))#endif/*defined(ROUNDUP)*//**Givenapointer(sockaddrorvoid*),returnthenumberof
bytes*takenupbythesockaddrandanypaddingneededforalignment.*/#ifdefined(HAVE_STRU
CT_SOCKADDR_SA_LEN)#defineSAROUNDUP(X)ROUNDUP(((structsockaddr*)(X))->sa_len)#el
se/**Onewouldhopeallfixed-sizestructuredefinitionsarealigned,*butroundthemupnone
theless.*/#defineSAROUNDUP(X)\(((structsockaddr*)(X))->sa_family==AF_INET\?ROUND
UP(sizeof(structsockaddr_in))\:(((structsockaddr*)(X))->sa_family==AF_INET6\?ROU
NDUP(sizeof(structsockaddr_in6))\:(((structsockaddr*)(X))->sa_family==AF_LINK\?R
OUNDUP(sizeof(structsockaddr_dl))\:sizeof(structsockaddr))))#endif/*HAVE_STRUCT_
SOCKADDR_SA_LEN*/#endif/*!SA_SIZE*//**Weuseacalltoaninlinefunctiontocopy(PNT)to(
DEST)*1.Calculatingthelengthofthecopyrequiresan#ifdeftodetermine*ifsa_lenisafiel
dandcan'tbeuseddirectlyinsidea#define*2.Sothecompilerdoesn'tcomplainwhenDESTisNU
LL,whichisonlytrue*whenweareskippingthecopyandincrementingtothenextSA*/staticinl
inevoidrta_copy(unionsockunion*dest,caddr_tsrc){intlen;if(!dest)return;#ifdefHAV
E_STRUCT_SOCKADDR_SA_LENlen=(((structsockaddr*)src)->sa_len>sizeof(*dest))?sizeo
f(*dest):((structsockaddr*)src)->sa_len;#elselen=(SAROUNDUP(src)>sizeof(*dest))?
sizeof(*dest):SAROUNDUP(src);#endifmemcpy(dest,src,len);}#defineRTA_ADDR_GET(DES
T,RTA,RTMADDRS,PNT)\if((RTMADDRS)&(RTA)){\intlen=SAROUNDUP((PNT));\if(af_check((
(structsockaddr*)(PNT))->sa_family))\rta_copy((DEST),(PNT));\(PNT)+=len;\}#defin
eRTA_ATTR_GET(DEST,RTA,RTMADDRS,PNT)\if((RTMADDRS)&(RTA)){\intlen=SAROUNDUP((PNT
));\rta_copy((DEST),(PNT));\(PNT)+=len;\}#defineRTA_NAME_GET(DEST,RTA,RTMADDRS,P
NT,LEN)\if((RTMADDRS)&(RTA)){\uint8_t*pdest=(uint8_t*)(DEST);\intlen=SAROUNDUP((
PNT));\structsockaddr_dl*sdl=(structsockaddr_dl*)(PNT);\if(IS_ZEBRA_DEBUG_KERNEL
)\zlog_debug("%s:RTA_SDL_GETnlen%d,alen%d",\__func__,sdl->sdl_nlen,sdl->sdl_alen
);\if(((DEST)!=NULL)&&(sdl->sdl_family==AF_LINK)\&&(sdl->sdl_nlen<IFNAMSIZ)&&(sd
l->sdl_nlen<=len)){\memcpy(pdest,sdl->sdl_data,sdl->sdl_nlen);\pdest[sdl->sdl_nl
en]='\0';\(LEN)=sdl->sdl_nlen;\}\(PNT)+=len;\}else{\(LEN)=0;\}/*Routingsocketmes
sagetypes.*/conststructmessagertm_type_str[]={{RTM_ADD,"RTM_ADD"},{RTM_DELETE,"R
TM_DELETE"},{RTM_CHANGE,"RTM_CHANGE"},{RTM_GET,"RTM_GET"},{RTM_LOSING,"RTM_LOSIN
G"},{RTM_REDIRECT,"RTM_REDIRECT"},{RTM_MISS,"RTM_MISS"},{RTM_LOCK,"RTM_LOCK"},#i
fdefOLDADD{RTM_OLDADD,"RTM_OLDADD"},#endif/*RTM_OLDADD*/#ifdefRTM_OLDDEL{RTM_OLD
DEL,"RTM_OLDDEL"},#endif/*RTM_OLDDEL*/{RTM_RESOLVE,"RTM_RESOLVE"},{RTM_NEWADDR,"
RTM_NEWADDR"},{RTM_DELADDR,"RTM_DELADDR"},{RTM_IFINFO,"RTM_IFINFO"},#ifdefRTM_OI
FINFO{RTM_OIFINFO,"RTM_OIFINFO"},#endif/*RTM_OIFINFO*/#ifdefRTM_NEWMADDR{RTM_NEW
MADDR,"RTM_NEWMADDR"},#endif/*RTM_NEWMADDR*/#ifdefRTM_DELMADDR{RTM_DELMADDR,"RTM
_DELMADDR"},#endif/*RTM_DELMADDR*/#ifdefRTM_IFANNOUNCE{RTM_IFANNOUNCE,"RTM_IFANN
OUNCE"},#endif/*RTM_IFANNOUNCE*/{0}};staticconststructmessagertm_flag_str[]={{RT
F_UP,"UP"},{RTF_GATEWAY,"GATEWAY"},{RTF_HOST,"HOST"},{RTF_REJECT,"REJECT"},{RTF_
DYNAMIC,"DYNAMIC"},{RTF_MODIFIED,"MODIFIED"},{RTF_DONE,"DONE"},#ifdefRTF_MASK{RT
F_MASK,"MASK"},#endif/*RTF_MASK*/#ifdefRTF_CLONING{RTF_CLONING,"CLONING"},#endif
/*RTF_CLONING*/#ifdefRTF_XRESOLVE{RTF_XRESOLVE,"XRESOLVE"},#endif/*RTF_XRESOLVE*
/#ifdefRTF_LLINFO{RTF_LLINFO,"LLINFO"},#endif/*RTF_LLINFO*/{RTF_STATIC,"STATIC"}
,{RTF_BLACKHOLE,"BLACKHOLE"},#ifdefRTF_PRIVATE{RTF_PRIVATE,"PRIVATE"},#endif/*RT
F_PRIVATE*/{RTF_PROTO1,"PROTO1"},{RTF_PROTO2,"PROTO2"},#ifdefRTF_PRCLONING{RTF_P
RCLONING,"PRCLONING"},#endif/*RTF_PRCLONING*/#ifdefRTF_WASCLONED{RTF_WASCLONED,"
WASCLONED"},#endif/*RTF_WASCLONED*/#ifdefRTF_PROTO3{RTF_PROTO3,"PROTO3"},#endif/
*RTF_PROTO3*/#ifdefRTF_PINNED{RTF_PINNED,"PINNED"},#endif/*RTF_PINNED*/#ifdefRTF
_LOCAL{RTF_LOCAL,"LOCAL"},#endif/*RTF_LOCAL*/#ifdefRTF_BROADCAST{RTF_BROADCAST,"
BROADCAST"},#endif/*RTF_BROADCAST*/#ifdefRTF_MULTICAST{RTF_MULTICAST,"MULTICAST"
},#endif/*RTF_MULTICAST*/#ifdefRTF_MULTIRT{RTF_MULTIRT,"MULTIRT"},#endif/*RTF_MU
LTIRT*/#ifdefRTF_SETSRC{RTF_SETSRC,"SETSRC"},#endif/*RTF_SETSRC*/{0}};/*Kernelro
utingupdatesocket.*/introuting_sock=-1;/*YesI'mcheckinguglyroutingsocketbehavior
.*//*#defineDEBUG*//*Supportedaddressfamilycheck.*/staticinlineintaf_check(intfa
mily){if(family==AF_INET)return1;if(family==AF_INET6)return1;return0;}/*Dumprout
ingtableflagfordebugpurpose.*/staticvoidrtm_flag_dump(intflag){conststructmessag
e*mes;staticcharbuf[BUFSIZ];buf[0]='\0';for(mes=rtm_flag_str;mes->key!=0;mes++){
if(mes->key&flag){strlcat(buf,mes->str,BUFSIZ);strlcat(buf,"",BUFSIZ);}}zlog_deb
ug("Kernel:%s",buf);}#ifdefRTM_IFANNOUNCE/*Interfaceaddingfunction*/staticintifa
n_read(structif_announcemsghdr*ifan){structinterface*ifp;ifp=if_lookup_by_index(
ifan->ifan_index,VRF_DEFAULT);if(ifp)assert((ifp->ifindex==ifan->ifan_index)||(i
fp->ifindex==IFINDEX_INTERNAL));if((ifp==NULL)||((ifp->ifindex==IFINDEX_INTERNAL
)&&(ifan->ifan_what==IFAN_ARRIVAL))){if(IS_ZEBRA_DEBUG_KERNEL)zlog_debug("%s:cre
atinginterfaceforifindex%d,name%s",__func__,ifan->ifan_index,ifan->ifan_name);/*
CreateInterface*/ifp=if_get_by_name(ifan->ifan_name,VRF_DEFAULT,0);if_set_index(
ifp,ifan->ifan_index);if_get_metric(ifp);if_add_update(ifp);}elseif(ifp!=NULL&&i
fan->ifan_what==IFAN_DEPARTURE)if_delete_update(ifp);if_get_flags(ifp);if_get_mt
u(ifp);if_get_metric(ifp);if(IS_ZEBRA_DEBUG_KERNEL)zlog_debug("%s:interface%sind
ex%d",__func__,ifan->ifan_name,ifan->ifan_index);return0;}#endif/*RTM_IFANNOUNCE
*/#ifdefHAVE_BSD_IFI_LINK_STATE/*BSDlinkdetecttranslation*/staticvoidbsd_linkdet
ect_translate(structif_msghdr*ifm){if((ifm->ifm_data.ifi_link_state>=LINK_STATE_
UP)||(ifm->ifm_data.ifi_link_state==LINK_STATE_UNKNOWN))SET_FLAG(ifm->ifm_flags,
IFF_RUNNING);elseUNSET_FLAG(ifm->ifm_flags,IFF_RUNNING);}#endif/*HAVE_BSD_IFI_LI
NK_STATE*/staticenumzebra_link_typesdl_to_zebra_link_type(unsignedintsdlt){switc
h(sdlt){caseIFT_ETHER:returnZEBRA_LLT_ETHER;caseIFT_X25:returnZEBRA_LLT_X25;case
IFT_FDDI:returnZEBRA_LLT_FDDI;caseIFT_PPP:returnZEBRA_LLT_PPP;caseIFT_LOOP:retur
nZEBRA_LLT_LOOPBACK;caseIFT_SLIP:returnZEBRA_LLT_SLIP;caseIFT_ARCNET:returnZEBRA
_LLT_ARCNET;caseIFT_ATM:returnZEBRA_LLT_ATM;caseIFT_LOCALTALK:returnZEBRA_LLT_LO
CALTLK;caseIFT_HIPPI:returnZEBRA_LLT_HIPPI;#ifdefIFT_IEEE1394caseIFT_IEEE1394:re
turnZEBRA_LLT_IEEE1394;#endifdefault:returnZEBRA_LLT_UNKNOWN;}}/**Handlestructif
_msghdrobtainedfromreadingroutingsocketor*sysctl(frominterface_list).Theremayorm
aynotbesockaddrs*presentaftertheheader.*/intifm_read(structif_msghdr*ifm){struct
interface*ifp=NULL;structsockaddr_dl*sdl;charifname[IFNAMSIZ];shortifnlen=0;cadd
r_tcp;/*terminateifnameathead(forstrnlen)andtail(forsafety)*/ifname[IFNAMSIZ-1]=
'\0';/*paranoia:sanitycheckstructure*/if(ifm->ifm_msglen<sizeof(structif_msghdr)
){zlog_err("ifm_read:ifm->ifm_msglen%dtooshort\n",ifm->ifm_msglen);return-1;}/**
Checkforasockaddr_dlfollowingthemessage.First,pointto*whereasocakddrmightbeifone
followsthemessage.*/cp=(void*)(ifm+1);#ifdefSUNOS_5/**XXXThisbehaviorshouldbenar
rowedtoonlythekernelversions*forwhichthestructuresreturneddonotmatchtheheaders.*
*if_msghdr_ton64bitkernelsinSolaris9andearlierversions*is12byteslargerthanthe32b
itversion.*/if(((structsockaddr*)cp)->sa_family==AF_UNSPEC)cp=cp+12;#endifRTA_AD
DR_GET(NULL,RTA_DST,ifm->ifm_addrs,cp);RTA_ADDR_GET(NULL,RTA_GATEWAY,ifm->ifm_ad
drs,cp);RTA_ATTR_GET(NULL,RTA_NETMASK,ifm->ifm_addrs,cp);RTA_ADDR_GET(NULL,RTA_G
ENMASK,ifm->ifm_addrs,cp);sdl=(structsockaddr_dl*)cp;RTA_NAME_GET(ifname,RTA_IFP
,ifm->ifm_addrs,cp,ifnlen);RTA_ADDR_GET(NULL,RTA_IFA,ifm->ifm_addrs,cp);RTA_ADDR
_GET(NULL,RTA_AUTHOR,ifm->ifm_addrs,cp);RTA_ADDR_GET(NULL,RTA_BRD,ifm->ifm_addrs
,cp);#ifdefRTA_LABELRTA_ATTR_GET(NULL,RTA_LABEL,ifm->ifm_addrs,cp);#endif#ifdefR
TA_SRCRTA_ADDR_GET(NULL,RTA_SRC,ifm->ifm_addrs,cp);#endifif(IS_ZEBRA_DEBUG_KERNE
L)zlog_debug("%s:sdlifname%s",__func__,(ifnlen?ifname:"(nil)"));/**Lookuponifind
exfirst,becauseifindicesaretheprimaryhandle*for*interfacesacrosstheuser/kernelbo
undary,formostsystems.(Some*messages,suchasup/downstatuschangesonNetBSD,donotinc
ludea*sockaddr_dl).*/if((ifp=if_lookup_by_index(ifm->ifm_index,VRF_DEFAULT))!=NU
LL){/*wehaveanifp,verifythatthenamematchesassomesystems,*egSolaris,havea1:manyas
sociationofifindex:ifname*iftheydontmatch,wedonthavethecorrectifpandshould*setit
backtoNULLtoletnextcheckdolookupbyname*/if(ifnlen&&(strncmp(ifp->name,ifname,IFN
AMSIZ)!=0)){if(IS_ZEBRA_DEBUG_KERNEL)zlog_debug("%s:ifpname%sdoesntmatchsdlname%
s",__func__,ifp->name,ifname);ifp=NULL;}}/**Ifwedonthaveanifp,trylookingupbyname
.Particularlyassome*systems(Solaris)havea1:manymappingofifindex:ifname-the*ifnam
e*isthereforeouruniquehandletothatinterface.**Interfacesspecifiedintheconfigurat
ionfileforwhichtheifindex*hasnotbeendeterminedwillhaveifindex==IFINDEX_INTERNAL,
and*such*interfacesarefoundbythissearch,andthentheirifindexvalues*can*befilledin
.*/if((ifp==NULL)&&ifnlen)ifp=if_lookup_by_name(ifname,VRF_DEFAULT);/**Ififpstil
ldoesnotexistorhasaninvalidindex*(IFINDEX_INTERNAL),*createorfillinaninterface.*
/if((ifp==NULL)||(ifp->ifindex==IFINDEX_INTERNAL)){/**Tocreateorfillinaninterfac
e,asockaddr_dl(via*RTA_IFP)isrequired.*/if(!ifnlen){zlog_warn("Interfaceindex%d(
new)missingifname\n",ifm->ifm_index);return-1;}#ifndefRTM_IFANNOUNCE/*Down->Down
interfaceshouldbeignoredhere.*Seefurthercommentbelow.*/if(!CHECK_FLAG(ifm->ifm_f
lags,IFF_UP))return0;#endif/*!RTM_IFANNOUNCE*/if(ifp==NULL){/*Interfacethatzebra
wasnotpreviouslyawareof,so*create.*/ifp=if_create(ifname,VRF_DEFAULT);if(IS_ZEBR
A_DEBUG_KERNEL)zlog_debug("%s:creatingifpforifindex%d",__func__,ifm->ifm_index);
}if(IS_ZEBRA_DEBUG_KERNEL)zlog_debug("%s:updated/createdifp,ifname%s,ifindex%d",
__func__,ifp->name,ifp->ifindex);/**Fillinnewlycreatedinterfacestructure,orlarva
l*structurewithifindexIFINDEX_INTERNAL.*/if_set_index(ifp,ifm->ifm_index);#ifdef
HAVE_BSD_IFI_LINK_STATE/*translateBSDkernelmsgforlink-state*/bsd_linkdetect_tran
slate(ifm);#endif/*HAVE_BSD_IFI_LINK_STATE*/if_flags_update(ifp,ifm->ifm_flags);
#ifdefined(__bsdi__)if_kvm_get_mtu(ifp);#elseif_get_mtu(ifp);#endif/*__bsdi__*/i
f_get_metric(ifp);/**XXXsockaddr_dlcontentscanbelargerthanthestructure*definitio
n.Thereare2bigfamilieshere:*-BSDhassdl_len+sdl_data[16]+overrunssdl_data*weMUSTu
sesdl_lenhereorwe'lltruncatedata.*-Solarishasnosdl_len,butsdl_data[244]*presumab
ly,it'snotgoingtorunpastthat,sosizeof()*isfinehere.*anonzeroifnlenfromRTA_NAME_G
ET()meanssdlisvalid*/ifp->ll_type=ZEBRA_LLT_UNKNOWN;ifp->hw_addr_len=0;if(ifnlen
){#ifdefHAVE_STRUCT_SOCKADDR_DL_SDL_LENmemcpy(&((structzebra_if*)ifp->info)->sdl
,sdl,sdl->sdl_len);#elsememcpy(&((structzebra_if*)ifp->info)->sdl,sdl,sizeof(str
uctsockaddr_dl));#endif/*HAVE_STRUCT_SOCKADDR_DL_SDL_LEN*/ifp->ll_type=sdl_to_ze
bra_link_type(sdl->sdl_type);if(sdl->sdl_alen<=sizeof(ifp->hw_addr)){memcpy(ifp-
>hw_addr,LLADDR(sdl),sdl->sdl_alen);ifp->hw_addr_len=sdl->sdl_alen;}}if_add_upda
te(ifp);}else/**Interfacestructureexists.Adjuststoredflagsfrom*notification.Ifin
terfacehasup->downordown->up*transition,callstatechangeroutines(toadjustroutes,*
notifyroutingdaemons,etc.).(Otherflagchangesarestored*butapparentlydonottriggera
ction.)*/{if(ifp->ifindex!=ifm->ifm_index){zlog_warn("%s:indexmismatch,ifname%s,
ifpindex%d,""ifmindex%d",__func__,ifp->name,ifp->ifindex,ifm->ifm_index);return-
1;}#ifdefHAVE_BSD_IFI_LINK_STATE/*translateBSDkernelmsgforlink-state*/bsd_linkde
tect_translate(ifm);#endif/*HAVE_BSD_IFI_LINK_STATE*//*updateflagsandhandleopera
tive->inoperativetransition,if*any*/if_flags_update(ifp,ifm->ifm_flags);#ifndefR
TM_IFANNOUNCEif(!if_is_up(ifp)){/*NoRTM_IFANNOUNCEonthisplatform,sowecannever*di
stinguishbetween~IFF_UPanddelete.Wemust*presume*ithasbeendeleted.*Eg,Solariswill
notnotifyusofunplumb.**XXX:Fixme-thisshouldberuntimedetected*Sothatabinarycompil
edonasystemwithIFANNOUNCE*willstillbehavecorrectlyifrunonaplatform*without*/if_d
elete_update(ifp);}#endif/*RTM_IFANNOUNCE*/if(if_is_up(ifp)){#ifdefined(__bsdi__
)if_kvm_get_mtu(ifp);#elseif_get_mtu(ifp);#endif/*__bsdi__*/if_get_metric(ifp);}
}#ifdefHAVE_NET_RT_IFLISTifp->stats=ifm->ifm_data;#endif/*HAVE_NET_RT_IFLIST*/if
p->speed=ifm->ifm_data.ifi_baudrate/1000000;if(IS_ZEBRA_DEBUG_KERNEL)zlog_debug(
"%s:interface%sindex%d",__func__,ifp->name,ifp->ifindex);return0;}/*Addressreadf
romstructifa_msghdr.*/staticvoidifam_read_mesg(structifa_msghdr*ifm,unionsockuni
on*addr,unionsockunion*mask,unionsockunion*brd,char*ifname,short*ifnlen){caddr_t
pnt,end;unionsockuniondst;unionsockuniongateway;pnt=(caddr_t)(ifm+1);end=((caddr
_t)ifm)+ifm->ifam_msglen;/*Besurestructureiscleared*/memset(mask,0,sizeof(unions
ockunion));memset(addr,0,sizeof(unionsockunion));memset(brd,0,sizeof(unionsockun
ion));memset(&dst,0,sizeof(unionsockunion));memset(&gateway,0,sizeof(unionsockun
ion));/*Wefetcheachsocketvariableintosockunion.*/RTA_ADDR_GET(&dst,RTA_DST,ifm->
ifam_addrs,pnt);RTA_ADDR_GET(&gateway,RTA_GATEWAY,ifm->ifam_addrs,pnt);RTA_ATTR_
GET(mask,RTA_NETMASK,ifm->ifam_addrs,pnt);RTA_ADDR_GET(NULL,RTA_GENMASK,ifm->ifa
m_addrs,pnt);RTA_NAME_GET(ifname,RTA_IFP,ifm->ifam_addrs,pnt,*ifnlen);RTA_ADDR_G
ET(addr,RTA_IFA,ifm->ifam_addrs,pnt);RTA_ADDR_GET(NULL,RTA_AUTHOR,ifm->ifam_addr
s,pnt);RTA_ADDR_GET(brd,RTA_BRD,ifm->ifam_addrs,pnt);#ifdefRTA_LABELRTA_ATTR_GET
(NULL,RTA_LABEL,ifm->ifam_addrs,pnt);#endif#ifdefRTA_SRCRTA_ADDR_GET(NULL,RTA_SR
C,ifm->ifam_addrs,pnt);#endifif(IS_ZEBRA_DEBUG_KERNEL){intfamily=sockunion_famil
y(addr);switch(family){caseAF_INET:caseAF_INET6:{charbuf[4][INET6_ADDRSTRLEN];zl
og_debug("%s:ifindex%d,ifname%s,ifam_addrs0x%x,""ifam_flags0x%x,addr%s/%dbroad%s
dst%s""gateway%s",__func__,ifm->ifam_index,(ifnlen?ifname:"(nil)"),ifm->ifam_add
rs,ifm->ifam_flags,inet_ntop(family,&addr->sin.sin_addr,buf[0],sizeof(buf[0])),i
p_masklen(mask->sin.sin_addr),inet_ntop(family,&brd->sin.sin_addr,buf[1],sizeof(
buf[1])),inet_ntop(family,&dst.sin.sin_addr,buf[2],sizeof(buf[2])),inet_ntop(fam
ily,&gateway.sin.sin_addr,buf[3],sizeof(buf[3])));}break;default:zlog_debug("%s:
ifindex%d,ifname%s,ifam_addrs0x%x",__func__,ifm->ifam_index,(ifnlen?ifname:"(nil
)"),ifm->ifam_addrs);break;}}/*Assertreadupendpointmatchestoendpoint*/if(pnt!=en
d)zlog_warn("ifam_read()doesn'treadallsocketdata");}/*Interface'saddressinformat
ionget.*/intifam_read(structifa_msghdr*ifam){structinterface*ifp=NULL;unionsocku
nionaddr,mask,brd;charifname[INTERFACE_NAMSIZ];shortifnlen=0;charisalias=0;intfl
ags=0;ifname[0]=ifname[INTERFACE_NAMSIZ-1]='\0';/*Allocateandreadaddressinformat
ion.*/ifam_read_mesg(ifam,&addr,&mask,&brd,ifname,&ifnlen);if((ifp=if_lookup_by_
index(ifam->ifam_index,VRF_DEFAULT))==NULL){zlog_warn("%s:nointerfaceforifname%s
,index%d",__func__,ifname,ifam->ifam_index);return-1;}if(ifnlen&&strncmp(ifp->na
me,ifname,INTERFACE_NAMSIZ))isalias=1;/*N.B.Theinfoinifa_msghdrdoesnottelluswhet
hertheRTA_BRDfieldcontainsabroadcastaddressorapeeraddress,soweareforcedtorelyupo
ntheinterfacetype.*/if(if_is_pointopoint(ifp))SET_FLAG(flags,ZEBRA_IFA_PEER);#if
0/*itmightseemcutetograbtheinterfacemetrichere,however*we'reprocessinganaddressu
pdatemessage,andsosomesystems*(e.g.FBSD)dontbothertofillinifam_metric.Disabled,b
utleft*indeliberately,ascomment.*/ifp->metric=ifam->ifam_metric;#endif/*Addconne
ctedaddress.*/switch(sockunion_family(&addr)){caseAF_INET:if(ifam->ifam_type==RT
M_NEWADDR)connected_add_ipv4(ifp,flags,&addr.sin.sin_addr,ip_masklen(mask.sin.si
n_addr),&brd.sin.sin_addr,(isalias?ifname:NULL));elseconnected_delete_ipv4(ifp,f
lags,&addr.sin.sin_addr,ip_masklen(mask.sin.sin_addr),&brd.sin.sin_addr);break;c
aseAF_INET6:/*Unsetinterfaceindexfromlink-localaddresswhenIPv6stackisKAME.*/if(I
N6_IS_ADDR_LINKLOCAL(&addr.sin6.sin6_addr)){SET_IN6_LINKLOCAL_IFINDEX(addr.sin6.
sin6_addr,0);}if(ifam->ifam_type==RTM_NEWADDR)connected_add_ipv6(ifp,flags,&addr
.sin6.sin6_addr,ip6_masklen(mask.sin6.sin6_addr),(isalias?ifname:NULL));elseconn
ected_delete_ipv6(ifp,&addr.sin6.sin6_addr,ip6_masklen(mask.sin6.sin6_addr));bre
ak;default:/*Unsupportedfamilysilentlyignore...*/break;}/*Checkinterfaceflagfori
mplicitupoftheinterface.*/if_refresh(ifp);#ifdefSUNOS_5/*InadditiontolackingIFAN
NOUNCE,onSUNOSIFF_UPisstrange.*SeecommentsforSUNOS_5ininterface.c::if_flags_mang
le.**HerewetakecareofcasewheretherealIFF_UPwaspreviously*unset(askeptinstructzeb
ra_if.primary_state)andthemangled*IFF_UP(ieIFF_UPset||listcount(connected)hasnow
transitioned*tounsetduetothelostnon-primaryaddresshavingDELADDR'd.**wemustdelete
theinterface,becauseinbetweenhereandnext*eventforthisinterface-nametheadministra
torcouldunplumb*andreplumbtheinterface.*/if(!if_is_up(ifp))if_delete_update(ifp)
;#endif/*SUNOS_5*/return0;}/*Interfacefunctionforreadingkernelroutingtableinform
ation.*/staticintrtm_read_mesg(structrt_msghdr*rtm,unionsockunion*dest,unionsock
union*mask,unionsockunion*gate,char*ifname,short*ifnlen){caddr_tpnt,end;/*Pntpoi
ntsoutsocketdatastartpoint.*/pnt=(caddr_t)(rtm+1);end=((caddr_t)rtm)+rtm->rtm_ms
glen;/*rt_msghdrversioncheck.*/if(rtm->rtm_version!=RTM_VERSION)zlog_warn("Routi
ngmessageversiondifferent%dshouldbe%d.""Thismaycauseproblem\n",rtm->rtm_version,
RTM_VERSION);/*Besurestructureiscleared*/memset(dest,0,sizeof(unionsockunion));m
emset(gate,0,sizeof(unionsockunion));memset(mask,0,sizeof(unionsockunion));/*Wef
etcheachsocketvariableintosockunion.*/RTA_ADDR_GET(dest,RTA_DST,rtm->rtm_addrs,p
nt);RTA_ADDR_GET(gate,RTA_GATEWAY,rtm->rtm_addrs,pnt);RTA_ATTR_GET(mask,RTA_NETM
ASK,rtm->rtm_addrs,pnt);RTA_ADDR_GET(NULL,RTA_GENMASK,rtm->rtm_addrs,pnt);RTA_NA
ME_GET(ifname,RTA_IFP,rtm->rtm_addrs,pnt,*ifnlen);RTA_ADDR_GET(NULL,RTA_IFA,rtm-
>rtm_addrs,pnt);RTA_ADDR_GET(NULL,RTA_AUTHOR,rtm->rtm_addrs,pnt);RTA_ADDR_GET(NU
LL,RTA_BRD,rtm->rtm_addrs,pnt);#ifdefRTA_LABEL#if0unionsockunionlabel;memset(&la
bel,0,sizeof(label));RTA_ATTR_GET(&label,RTA_LABEL,rtm->rtm_addrs,pnt);#endifRTA
_ATTR_GET(NULL,RTA_LABEL,rtm->rtm_addrs,pnt);#endif#ifdefRTA_SRCRTA_ADDR_GET(NUL
L,RTA_SRC,rtm->rtm_addrs,pnt);#endif/*Ifthereisnetmaskinformationsetit'sfamilysa
measdestinationfamily*/if(rtm->rtm_addrs&RTA_NETMASK)mask->sa.sa_family=dest->sa
.sa_family;/*Assertreaduptotheendofpointer.*/if(pnt!=end)zlog_warn("rtm_read()do
esn'treadallsocketdata.");returnrtm->rtm_flags;}voidrtm_read(structrt_msghdr*rtm
){intflags;uint8_tzebra_flags;unionsockuniondest,mask,gate;charifname[INTERFACE_
NAMSIZ+1];shortifnlen=0;structnexthopnh;zebra_flags=0;/*Readdestinationandnetmas
kandgatewayfromrtmmessagestructure.*/flags=rtm_read_mesg(rtm,&dest,&mask,&gate,i
fname,&ifnlen);if(!(flags&RTF_DONE))return;if(IS_ZEBRA_DEBUG_KERNEL)zlog_debug("
%s:gotrtmoftype%d(%s)",__func__,rtm->rtm_type,lookup_msg(rtm_type_str,rtm->rtm_t
ype,NULL));#ifdefRTF_CLONED/*bsdi,netbsd1.6*/if(flags&RTF_CLONED)return;#endif#i
fdefRTF_WASCLONED/*freebsd*/if(flags&RTF_WASCLONED)return;#endifif((rtm->rtm_typ
e==RTM_ADD||rtm->rtm_type==RTM_CHANGE)&&!(flags&RTF_UP))return;/*Thisisconnected
route.*/if(!(flags&RTF_GATEWAY))return;if(flags&RTF_PROTO1)SET_FLAG(zebra_flags,
ZEBRA_FLAG_SELFROUTE);/*Thisispersistentroute.*/if(flags&RTF_STATIC)SET_FLAG(zeb
ra_flags,ZEBRA_FLAG_STATIC);memset(&nh,0,sizeof(nh));nh.vrf_id=VRF_DEFAULT;/*Thi
sisarejectorblackholeroute*/if(flags&RTF_REJECT){nh.type=NEXTHOP_TYPE_BLACKHOLE;
nh.bh_type=BLACKHOLE_REJECT;}elseif(flags&RTF_BLACKHOLE){nh.type=NEXTHOP_TYPE_BL
ACKHOLE;nh.bh_type=BLACKHOLE_NULL;}if(dest.sa.sa_family==AF_INET){structprefixp;
p.family=AF_INET;p.u.prefix4=dest.sin.sin_addr;if(flags&RTF_HOST)p.prefixlen=IPV
4_MAX_PREFIXLEN;elsep.prefixlen=ip_masklen(mask.sin.sin_addr);/*Catchselforigina
tedmessagesandmatchthemagainstour*currentRIB.*Atthesametime,ignoreunconfirmedmes
sages,theyshouldbe*tracked*byrtm_write()andkernel_rtm_ipv4().*/if(rtm->rtm_type!
=RTM_GET&&rtm->rtm_pid==pid){charbuf[PREFIX_STRLEN],gate_buf[INET_ADDRSTRLEN];in
tret;if(!IS_ZEBRA_DEBUG_RIB)return;ret=rib_lookup_ipv4_route((structprefix_ipv4*
)&p,&gate,VRF_DEFAULT);prefix2str(&p,buf,sizeof(buf));switch(rtm->rtm_type){case
RTM_ADD:caseRTM_GET:caseRTM_CHANGE:/*ThekernelnotifiesusaboutanewrouteinFIBcreat
edbyus.DowehaveacorrespondententryinourRIB?*/switch(ret){caseZEBRA_RIB_NOTFOUND:
zlog_debug("%s:%s%s:desync:RRisn'tyetinRIB,whilealreadyinFIB",__func__,lookup_ms
g(rtm_type_str,rtm->rtm_type,NULL),buf);break;caseZEBRA_RIB_FOUND_CONNECTED:case
ZEBRA_RIB_FOUND_NOGATE:inet_ntop(AF_INET,&gate.sin.sin_addr,gate_buf,INET_ADDRST
RLEN);zlog_debug("%s:%s%s:desync:RRisinRIB,butgatediffers(oursis%s)",__func__,lo
okup_msg(rtm_type_str,rtm->rtm_type,NULL),buf,gate_buf);break;caseZEBRA_RIB_FOUN
D_EXACT:/*RIBRR==FIBRR*/zlog_debug("%s:%s%s:doneOk",__func__,lookup_msg(rtm_type
_str,rtm->rtm_type,NULL),buf);rib_lookup_and_dump((structprefix_ipv4*)&p,VRF_DEF
AULT);return;break;}break;caseRTM_DELETE:/*Thekernelnotifiesusaboutaroutedeleted
byus.DowestillhaveitintheRIB?Dowehaveanythinginstead?*/switch(ret){caseZEBRA_RIB
_FOUND_EXACT:zlog_debug("%s:%s%s:desync:RRisstillinRIB,whilealreadynotinFIB",__f
unc__,lookup_msg(rtm_type_str,rtm->rtm_type,NULL),buf);rib_lookup_and_dump((stru
ctprefix_ipv4*)&p,VRF_DEFAULT);break;caseZEBRA_RIB_FOUND_CONNECTED:caseZEBRA_RIB
_FOUND_NOGATE:zlog_debug("%s:%s%s:desync:RRisstillinRIB,plusgatediffers",__func_
_,lookup_msg(rtm_type_str,rtm->rtm_type,NULL),buf);rib_lookup_and_dump((structpr
efix_ipv4*)&p,VRF_DEFAULT);break;caseZEBRA_RIB_NOTFOUND:/*RIBRR==FIBRR*/zlog_deb
ug("%s:%s%s:doneOk",__func__,lookup_msg(rtm_type_str,rtm->rtm_type,NULL),buf);ri
b_lookup_and_dump((structprefix_ipv4*)&p,VRF_DEFAULT);return;break;}break;defaul
t:zlog_debug("%s:%s:warning:loopbackRTMoftype%sreceived",__func__,buf,lookup_msg
(rtm_type_str,rtm->rtm_type,NULL));}return;}/*Change,deletetheoldprefix,wehaveno
furtherinformation*tospecifytheroutereally*/if(rtm->rtm_type==RTM_CHANGE)rib_del
ete(AFI_IP,SAFI_UNICAST,VRF_DEFAULT,ZEBRA_ROUTE_KERNEL,0,zebra_flags,&p,NULL,NUL
L,0,0,true,NULL);if(!nh.type){nh.type=NEXTHOP_TYPE_IPV4;nh.gate.ipv4=gate.sin.si
n_addr;}if(rtm->rtm_type==RTM_GET||rtm->rtm_type==RTM_ADD||rtm->rtm_type==RTM_CH
ANGE)rib_add(AFI_IP,SAFI_UNICAST,VRF_DEFAULT,ZEBRA_ROUTE_KERNEL,0,zebra_flags,&p
,NULL,&nh,0,0,0,0,0);elserib_delete(AFI_IP,SAFI_UNICAST,VRF_DEFAULT,ZEBRA_ROUTE_
KERNEL,0,zebra_flags,&p,NULL,&nh,0,0,true,NULL);}if(dest.sa.sa_family==AF_INET6)
{/*Onedaywemighthaveadebugsectionherelikeoneinthe*IPv4caseabove.Justignoreownmes
sagesatthemoment.*/if(rtm->rtm_type!=RTM_GET&&rtm->rtm_pid==pid)return;structpre
fixp;ifindex_tifindex=0;p.family=AF_INET6;p.u.prefix6=dest.sin6.sin6_addr;if(fla
gs&RTF_HOST)p.prefixlen=IPV6_MAX_PREFIXLEN;elsep.prefixlen=ip6_masklen(mask.sin6
.sin6_addr);#ifdefKAMEif(IN6_IS_ADDR_LINKLOCAL(&gate.sin6.sin6_addr)){ifindex=IN
6_LINKLOCAL_IFINDEX(gate.sin6.sin6_addr);SET_IN6_LINKLOCAL_IFINDEX(gate.sin6.sin
6_addr,0);}#endif/*KAME*//*CHANGE:deletetheoldprefix,wehavenofurtherinformation*
tospecifytheroutereally*/if(rtm->rtm_type==RTM_CHANGE)rib_delete(AFI_IP6,SAFI_UN
ICAST,VRF_DEFAULT,ZEBRA_ROUTE_KERNEL,0,zebra_flags,&p,NULL,NULL,0,0,true,NULL);i
f(!nh.type){nh.type=ifindex?NEXTHOP_TYPE_IPV6_IFINDEX:NEXTHOP_TYPE_IPV6;nh.gate.
ipv6=gate.sin6.sin6_addr;nh.ifindex=ifindex;}if(rtm->rtm_type==RTM_GET||rtm->rtm
_type==RTM_ADD||rtm->rtm_type==RTM_CHANGE)rib_add(AFI_IP6,SAFI_UNICAST,VRF_DEFAU
LT,ZEBRA_ROUTE_KERNEL,0,zebra_flags,&p,NULL,&nh,0,0,0,0,0);elserib_delete(AFI_IP
6,SAFI_UNICAST,VRF_DEFAULT,ZEBRA_ROUTE_KERNEL,0,zebra_flags,&p,NULL,&nh,0,0,true
,NULL);}}/*Interfacefunctionforthekernelroutingtableupdates.Support*forRTM_CHANG
Ewillbeneeded.*Exportedonlyforrt_socket.c*/intrtm_write(intmessage,unionsockunio
n*dest,unionsockunion*mask,unionsockunion*gate,unionsockunion*mpls,unsignedintin
dex,enumblackhole_typebh_type,intmetric){intret;caddr_tpnt;structinterface*ifp;/
*Sequencialnumberofroutingmessage.*/staticintmsg_seq=0;/*Structofrt_msghdrandbuf
ferforstoringsocket'sdata.*/struct{structrt_msghdrrtm;charbuf[512];}msg;if(routi
ng_sock<0)returnZEBRA_ERR_EPERM;/*Clearandsetrt_msghdrvalues*/memset(&msg,0,size
of(structrt_msghdr));msg.rtm.rtm_version=RTM_VERSION;msg.rtm.rtm_type=message;ms
g.rtm.rtm_seq=msg_seq++;msg.rtm.rtm_addrs=RTA_DST;msg.rtm.rtm_addrs|=RTA_GATEWAY
;msg.rtm.rtm_flags=RTF_UP;#ifdef__OpenBSD__msg.rtm.rtm_flags|=RTF_MPATH;msg.rtm.
rtm_fmask=RTF_MPLS;#endifmsg.rtm.rtm_index=index;if(metric!=0){msg.rtm.rtm_rmx.r
mx_hopcount=metric;msg.rtm.rtm_inits|=RTV_HOPCOUNT;}ifp=if_lookup_by_index(index
,VRF_DEFAULT);if(gate&&(message==RTM_ADD||message==RTM_CHANGE))msg.rtm.rtm_flags
|=RTF_GATEWAY;/*WhenRTF_CLONINGisunavailableonBSD,shouldwesetsome*otherflaginste
ad?*/#ifdefRTF_CLONINGif(!gate&&(message==RTM_ADD||message==RTM_CHANGE)&&ifp&&(i
fp->flags&IFF_POINTOPOINT)==0)msg.rtm.rtm_flags|=RTF_CLONING;#endif/*RTF_CLONING
*//*Ifnoprotocolspecificgatewayisspecified,uselinkaddressforgateway.*/if(!gate){
if(!ifp){chardest_buf[INET_ADDRSTRLEN]="NULL",mask_buf[INET_ADDRSTRLEN]="255.255
.255.255";if(dest)inet_ntop(AF_INET,&dest->sin.sin_addr,dest_buf,INET_ADDRSTRLEN
);if(mask)inet_ntop(AF_INET,&mask->sin.sin_addr,mask_buf,INET_ADDRSTRLEN);zlog_w
arn("%s:%s/%s:gate==NULLandnogatewayfoundforifindex%d",__func__,dest_buf,mask_bu
f,index);return-1;}gate=(unionsockunion*)&((structzebra_if*)ifp->info)->sdl;}if(
mask)msg.rtm.rtm_addrs|=RTA_NETMASK;elseif(message==RTM_ADD||message==RTM_CHANGE
)msg.rtm.rtm_flags|=RTF_HOST;#ifdef__OpenBSD__if(mpls){msg.rtm.rtm_addrs|=RTA_SR
C;msg.rtm.rtm_flags|=RTF_MPLS;if(mpls->smpls.smpls_label!=htonl(MPLS_LABEL_IMPLI
CIT_NULL<<MPLS_LABEL_OFFSET))msg.rtm.rtm_mpls=MPLS_OP_PUSH;}#endif/*Taggingroute
withflags*/msg.rtm.rtm_flags|=(RTF_PROTO1);switch(bh_type){caseBLACKHOLE_UNSPEC:
break;caseBLACKHOLE_REJECT:msg.rtm.rtm_flags|=RTF_REJECT;break;default:msg.rtm.r
tm_flags|=RTF_BLACKHOLE;break;}#defineSOCKADDRSET(X,R)\if(msg.rtm.rtm_addrs&(R))
{\intlen=SAROUNDUP(X);\memcpy(pnt,(caddr_t)(X),len);\pnt+=len;\}pnt=(caddr_t)msg
.buf;/*Writeeachsocketdataintortmmessagebuffer*/SOCKADDRSET(dest,RTA_DST);SOCKAD
DRSET(gate,RTA_GATEWAY);SOCKADDRSET(mask,RTA_NETMASK);#ifdef__OpenBSD__SOCKADDRS
ET(mpls,RTA_SRC);#endifmsg.rtm.rtm_msglen=pnt-(caddr_t)&msg;ret=write(routing_so
ck,&msg,msg.rtm.rtm_msglen);if(ret!=msg.rtm.rtm_msglen){if(errno==EEXIST)returnZ
EBRA_ERR_RTEXIST;if(errno==ENETUNREACH)returnZEBRA_ERR_RTUNREACH;if(errno==ESRCH
)returnZEBRA_ERR_RTNOEXIST;zlog_warn("%s:write:%s(%d)",__func__,safe_strerror(er
rno),errno);returnZEBRA_ERR_KERNEL;}returnZEBRA_ERR_NOERROR;}#include"thread.h"#
include"zebra/zserv.h"/*Fordebugpurpose.*/staticvoidrtmsg_debug(structrt_msghdr*
rtm){zlog_debug("Kernel:Len:%dType:%s",rtm->rtm_msglen,lookup_msg(rtm_type_str,r
tm->rtm_type,NULL));rtm_flag_dump(rtm->rtm_flags);zlog_debug("Kernel:messageseq%
d",rtm->rtm_seq);zlog_debug("Kernel:pid%lld,rtm_addrs0x%x",(longlong)rtm->rtm_pi
d,rtm->rtm_addrs);}/*Thisisprettygross,bettersuggestionswelcome--mhandler*/#ifnd
efRTAX_MAX#ifdefRTA_NUMBITS#defineRTAX_MAXRTA_NUMBITS#else#defineRTAX_MAX8#endif
/*RTA_NUMBITS*/#endif/*RTAX_MAX*//*Kernelroutingtableandinterfaceupdatesviarouti
ngsocket.*/staticintkernel_read(structthread*thread){intsock;intnbytes;structrt_
msghdr*rtm;/**Thismustbebigenoughforanymessagethekernelmightsend.*Ratherthandete
rmininghowmanysockaddrsofwhatsizemightbe*ineachparticularmessage,justuseRTAX_MAX
ofsockaddr_storage*foreach.Notethatthesockaddrsmustbeaftereachmessage*definition
,orratherafterwhicheverhappenstobethelargest,*sincethebufferneedstobebigenoughfo
ramessageandthe*sockaddrstogether.*/union{/*Routinginformation.*/struct{structrt
_msghdrrtm;structsockaddr_storageaddr[RTAX_MAX];}r;/*Interfaceinformation.*/stru
ct{structif_msghdrifm;structsockaddr_storageaddr[RTAX_MAX];}im;/*Interfaceaddres
sinformation.*/struct{structifa_msghdrifa;structsockaddr_storageaddr[RTAX_MAX];}
ia;#ifdefRTM_IFANNOUNCE/*Interfacearrival/departure*/struct{structif_announcemsg
hdrifan;structsockaddr_storageaddr[RTAX_MAX];}ian;#endif/*RTM_IFANNOUNCE*/}buf;/
*Fetchroutingsocket.*/sock=THREAD_FD(thread);nbytes=read(sock,&buf,sizeofbuf);if
(nbytes<=0){if(nbytes<0&&errno!=EWOULDBLOCK&&errno!=EAGAIN)zlog_warn("routingsoc
keterror:%s",safe_strerror(errno));return0;}thread_add_read(zebrad.master,kernel
_read,NULL,sock,NULL);if(IS_ZEBRA_DEBUG_KERNEL)rtmsg_debug(&buf.r.rtm);rtm=&buf.
r.rtm;/**Ensurethatwedidn'tdropanydata,sothatprocessingroutines*canassumetheyhav
ethewholemessage.*/if(rtm->rtm_msglen!=nbytes){zlog_warn("kernel_read:rtm->rtm_m
sglen%d,nbytes%d,type%d\n",rtm->rtm_msglen,nbytes,rtm->rtm_type);return-1;}switc
h(rtm->rtm_type){caseRTM_ADD:caseRTM_DELETE:caseRTM_CHANGE:rtm_read(rtm);break;c
aseRTM_IFINFO:ifm_read(&buf.im.ifm);break;caseRTM_NEWADDR:caseRTM_DELADDR:ifam_r
ead(&buf.ia.ifa);break;#ifdefRTM_IFANNOUNCEcaseRTM_IFANNOUNCE:ifan_read(&buf.ian
.ifan);break;#endif/*RTM_IFANNOUNCE*/default:if(IS_ZEBRA_DEBUG_KERNEL)zlog_debug
("UnprocessedRTM_type:%d",rtm->rtm_type);break;}return0;}/*Makeroutingsocket.*/s
taticvoidrouting_socket(structzebra_ns*zns){if(zserv_privs.change(ZPRIVS_RAISE))
zlog_err("routing_socket:Can'traiseprivileges");routing_sock=ns_socket(AF_ROUTE,
SOCK_RAW,0,(ns_id_t)zns->ns->ns_id);if(routing_sock<0){if(zserv_privs.change(ZPR
IVS_LOWER))zlog_err("routing_socket:Can'tlowerprivileges");zlog_warn("Can'tinitk
ernelroutingsocket");return;}/*XXX:SocketshouldbeNONBLOCK,howeveraswecurrently*d
iscardfailedwrites,thiswillleadtoinconsistencies.*Fornow,socketmustbeblocking.*/
/*if(fcntl(routing_sock,F_SETFL,O_NONBLOCK)<0)zlog_warn("Can'tsetO_NONBLOCKtorou
tingsocket");*/if(zserv_privs.change(ZPRIVS_LOWER))zlog_err("routing_socket:Can'
tlowerprivileges");/*kernel_readneedsrewrite.*/thread_add_read(zebrad.master,ker
nel_read,NULL,routing_sock,NULL);}/*Exportedinterfacefunction.Thisfunctionsimply
callsrouting_socket().*/voidkernel_init(structzebra_ns*zns){routing_socket(zns);
}voidkernel_terminate(structzebra_ns*zns){return;}#endif/*!HAVE_NETLINK*/