/**RoutingInformationBaseheader*Copyright(C)1997KunihiroIshiguro**Thisfileispart
ofGNUZebra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodifyit*underthet
ermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eitherve
rsion2,or(atyouroption)any*laterversion.**GNUZebraisdistributedinthehopethatitwi
llbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILIT
YorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Y
oushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seeth
efileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloo
r,Boston,MA02110-1301USA*/#ifndef_ZEBRA_RIB_H#define_ZEBRA_RIB_H#include"zebra.h
"#include"hook.h"#include"linklist.h"#include"prefix.h"#include"table.h"#include
"queue.h"#include"nexthop.h"#include"nexthop_group.h"#include"vrf.h"#include"if.
h"#include"mpls.h"#include"srcdest_table.h"#defineDISTANCE_INFINITY255#defineZEB
RA_KERNEL_TABLE_MAX252/*supportfornomorethanthisrttables*/structroute_entry{/*Li
nklist.*/structroute_entry*next;structroute_entry*prev;/*Nexthopstructure*/struc
tnexthop_groupng;/*Tag*/route_tag_ttag;/*Uptime.*/time_tuptime;/*Typefothisroute
.*/inttype;/*Sourceprotocolinstance*/unsignedshortinstance;/*VRFidentifier.*/vrf
_id_tvrf_id;/*Whichroutingtable*/uint32_ttable;/*Metric*/uint32_tmetric;/*MTU*/u
int32_tmtu;uint32_tnexthop_mtu;/*Distance.*/uint8_tdistance;/*Flagsofthisroute.*
Thisflag'sdefinitionisinlib/zebra.hZEBRA_FLAG_*andisexposed*toclientsviaZserv*/u
int32_tflags;/*RIBinternalstatus*/uint8_tstatus;#defineROUTE_ENTRY_REMOVED0x1/*t
osimplifyNHTlogicwhenNHschange,insteadofdoingaNHbyNHcmp*/#defineROUTE_ENTRY_NEXT
HOPS_CHANGED0x2#defineROUTE_ENTRY_CHANGED0x4#defineROUTE_ENTRY_LABELS_CHANGED0x8
/*Nexthopinformation.*/uint8_tnexthop_num;uint8_tnexthop_active_num;};/*meta-que
uestructure:*sub-queue0:connected,kernel*sub-queue1:static*sub-queue2:RIP,RIPng,
OSPF,OSPF6,IS-IS,EIGRP,NHRP*sub-queue3:iBGP,eBGP*sub-queue4:anyotherorigin(ifany
)*/#defineMQ_SIZE5structmeta_queue{structlist*subq[MQ_SIZE];uint32_tsize;/*sumof
lengthsofallsubqueues*/};/**Structurethatrepresentsasingledestination(prefix).*/
typedefstructrib_dest_t_{/**Backpointertotheroutenodeforthisdestination.Thishelp
s*usgettotheprefixthatthisstructureisfor.*/structroute_node*rnode;/**Doubly-link
edlistofroutesforthisprefix.*/structroute_entry*routes;structroute_entry*selecte
d_fib;/**Flags,seebelow.*/uint32_tflags;/**LinkagetoputdestontheFPMprocessingque
ue.*/TAILQ_ENTRY(rib_dest_t_)fpm_q_entries;}rib_dest_t;#defineRIB_ROUTE_QUEUED(x
)(1<<(x))//IfMQ_SIZEismodifiedthisvalueneedstobeupdated.#defineRIB_ROUTE_ANY_QUE
UED0x1F/**Themaximumqindexthatcanbeused.*/#defineZEBRA_MAX_QINDEX(MQ_SIZE-1)/**T
hisflagindicatesthatagivenprefixhasbeen'advertised'to*theFPMtobeinstalledinthefo
rwardingplane.*/#defineRIB_DEST_SENT_TO_FPM(1<<(ZEBRA_MAX_QINDEX+1))/**Thisflagi
ssetwhenweneedtosendanupdatetotheFPMabouta*dest.*/#defineRIB_DEST_UPDATE_FPM(1<<
(ZEBRA_MAX_QINDEX+2))/**Macrotoiterateovereachrouteforadestination(prefix).*/#de
fineRE_DEST_FOREACH_ROUTE(dest,re)\for((re)=(dest)?(dest)->routes:NULL;(re);(re)
=(re)->next)/**Sameasabove,butallowsthecurrentnodetobeunlinked.*/#defineRE_DEST_
FOREACH_ROUTE_SAFE(dest,re,next)\for((re)=(dest)?(dest)->routes:NULL;\(re)&&((ne
xt)=(re)->next,1);(re)=(next))#defineRNODE_FOREACH_RE(rn,re)\RE_DEST_FOREACH_ROU
TE(rib_dest_from_rnode(rn),re)#defineRNODE_FOREACH_RE_SAFE(rn,re,next)\RE_DEST_F
OREACH_ROUTE_SAFE(rib_dest_from_rnode(rn),re,next)#ifdefined(HAVE_RTADV)/*Struct
urewhichholdstatusofrouteradvertisement.*/structrtadv{intsock;intadv_if_count;in
tadv_msec_if_count;structthread*ra_read;structthread*ra_timer;};#endif/*HAVE_RTA
DV*//**rib_table_info_t**Structurethatishungoffofaroute_tablethatholdsinformatio
nabout*thetable.*/typedefstructrib_table_info_t_{/**Backpointertozebra_vrf.*/str
uctzebra_vrf*zvrf;afi_tafi;safi_tsafi;}rib_table_info_t;typedefenum{RIB_TABLES_I
TER_S_INIT,RIB_TABLES_ITER_S_ITERATING,RIB_TABLES_ITER_S_DONE}rib_tables_iter_st
ate_t;/**Structurethatholdsstateforiteratingoveralltablesinthe*RoutingInformatio
nBase.*/typedefstructrib_tables_iter_t_{vrf_id_tvrf_id;intafi_safi_ix;rib_tables
_iter_state_tstate;}rib_tables_iter_t;/*Events/reasonstriggeringaRIBupdate.*/typ
edefenum{RIB_UPDATE_IF_CHANGE,RIB_UPDATE_RMAP_CHANGE,RIB_UPDATE_OTHER}rib_update
_event_t;externstructnexthop*route_entry_nexthop_ifindex_add(structroute_entry*r
e,ifindex_tifindex,vrf_id_tnh_vrf_id);externstructnexthop*route_entry_nexthop_bl
ackhole_add(structroute_entry*re,enumblackhole_typebh_type);externstructnexthop*
route_entry_nexthop_ipv4_add(structroute_entry*re,structin_addr*ipv4,structin_ad
dr*src,vrf_id_tnh_vrf_id);externstructnexthop*route_entry_nexthop_ipv4_ifindex_a
dd(structroute_entry*re,structin_addr*ipv4,structin_addr*src,ifindex_tifindex,vr
f_id_tnh_vrf_id);externvoidroute_entry_nexthop_delete(structroute_entry*re,struc
tnexthop*nexthop);externstructnexthop*route_entry_nexthop_ipv6_add(structroute_e
ntry*re,structin6_addr*ipv6,vrf_id_tnh_vrf_id);externstructnexthop*route_entry_n
exthop_ipv6_ifindex_add(structroute_entry*re,structin6_addr*ipv6,ifindex_tifinde
x,vrf_id_tnh_vrf_id);externvoidroute_entry_nexthop_add(structroute_entry*re,stru
ctnexthop*nexthop);externvoidroute_entry_copy_nexthops(structroute_entry*re,stru
ctnexthop*nh);#defineroute_entry_dump(prefix,src,re)_route_entry_dump(__func__,p
refix,src,re)externvoid_route_entry_dump(constchar*func,unionprefixconstptrpp,un
ionprefixconstptrsrc_pp,conststructroute_entry*re);/*RPFlookupbehaviour*/enummul
ticast_mode{MCAST_NO_CONFIG=0,/*MIX_MRIB_FIRST,butnoshowinconfigwrite*/MCAST_MRI
B_ONLY,/*MRIBonly*/MCAST_URIB_ONLY,/*URIBonly*/MCAST_MIX_MRIB_FIRST,/*MRIB,ifnot
hingatallthenURIB*/MCAST_MIX_DISTANCE,/*MRIB&URIB,lowerdistancewins*/MCAST_MIX_P
FXLEN,/*MRIB&URIB,longerprefixwins*//*onequalvalue,MRIBwinsforlast2*/};externvoi
dmulticast_mode_ipv4_set(enummulticast_modemode);externenummulticast_modemultica
st_mode_ipv4_get(void);externvoidrib_lookup_and_dump(structprefix_ipv4*p,vrf_id_
tvrf_id);externvoidrib_lookup_and_pushup(structprefix_ipv4*p,vrf_id_tvrf_id);ext
ernintrib_lookup_ipv4_route(structprefix_ipv4*p,unionsockunion*qgate,vrf_id_tvrf
_id);#defineZEBRA_RIB_LOOKUP_ERROR-1#defineZEBRA_RIB_FOUND_EXACT0#defineZEBRA_RI
B_FOUND_NOGATE1#defineZEBRA_RIB_FOUND_CONNECTED2#defineZEBRA_RIB_NOTFOUND3extern
intis_zebra_valid_kernel_table(uint32_ttable_id);externintis_zebra_main_routing_
table(uint32_ttable_id);externintzebra_check_addr(structprefix*p);externvoidrib_
addnode(structroute_node*rn,structroute_entry*re,intprocess);externvoidrib_delno
de(structroute_node*rn,structroute_entry*re);externvoidrib_install_kernel(struct
route_node*rn,structroute_entry*re,structroute_entry*old);externvoidrib_uninstal
l_kernel(structroute_node*rn,structroute_entry*re);/*NOTE:*Allrib_addfunctionwil
lnotjustaddprefixintoRIB,but*alsoimplicitlywithdrawequalprefixofsametype.*/exter
nintrib_add(afi_tafi,safi_tsafi,vrf_id_tvrf_id,inttype,unsignedshortinstance,int
flags,structprefix*p,structprefix_ipv6*src_p,conststructnexthop*nh,uint32_ttable
_id,uint32_tmetric,uint32_tmtu,uint8_tdistance,route_tag_ttag);externintrib_add_
multipath(afi_tafi,safi_tsafi,structprefix*p,structprefix_ipv6*src_p,structroute
_entry*re);externvoidrib_delete(afi_tafi,safi_tsafi,vrf_id_tvrf_id,inttype,unsig
nedshortinstance,intflags,structprefix*p,structprefix_ipv6*src_p,conststructnext
hop*nh,uint32_ttable_id,uint32_tmetric,boolfromkernel,structethaddr*rmac);extern
structroute_entry*rib_match(afi_tafi,safi_tsafi,vrf_id_tvrf_id,uniong_addr*addr,
structroute_node**rn_out);externstructroute_entry*rib_match_ipv4_multicast(vrf_i
d_tvrf_id,structin_addraddr,structroute_node**rn_out);externstructroute_entry*ri
b_lookup_ipv4(structprefix_ipv4*p,vrf_id_tvrf_id);externvoidrib_update(vrf_id_tv
rf_id,rib_update_event_tevent);externvoidrib_sweep_route(void);externvoidrib_swe
ep_table(structroute_table*table);externvoidrib_close_table(structroute_table*ta
ble);externvoidrib_init(void);externunsignedlongrib_score_proto(uint8_tproto,uns
ignedshortinstance);externunsignedlongrib_score_proto_table(uint8_tproto,unsigne
dshortinstance,structroute_table*table);externvoidrib_queue_add(structroute_node
*rn);externvoidmeta_queue_free(structmeta_queue*mq);externintzebra_rib_labeled_u
nicast(structroute_entry*re);externstructroute_table*rib_table_ipv6;externvoidri
b_unlink(structroute_node*rn,structroute_entry*re);externintrib_gc_dest(structro
ute_node*rn);externstructroute_table*rib_tables_iter_next(rib_tables_iter_t*iter
);externuint8_troute_distance(inttype);/**Inlinefunctions.*//**rib_table_info*/s
taticinlinerib_table_info_t*rib_table_info(structroute_table*table){return(rib_t
able_info_t*)table->info;}/**rib_dest_from_rnode*/staticinlinerib_dest_t*rib_des
t_from_rnode(structroute_node*rn){return(rib_dest_t*)rn->info;}/**rnode_to_ribs*
*Returnsapointertothelistofroutescorrespondingtothegiven*route_node.*/staticinli
nestructroute_entry*rnode_to_ribs(structroute_node*rn){rib_dest_t*dest;dest=rib_
dest_from_rnode(rn);if(!dest)returnNULL;returndest->routes;}/**rib_dest_prefix*/
staticinlinestructprefix*rib_dest_prefix(rib_dest_t*dest){return&dest->rnode->p;
}/**rib_dest_af**Returnstheaddressfamilythatthedestinationisfor.*/staticinlineui
nt8_trib_dest_af(rib_dest_t*dest){returndest->rnode->p.family;}/**rib_dest_table
*/staticinlinestructroute_table*rib_dest_table(rib_dest_t*dest){returnsrcdest_rn
ode_table(dest->rnode);}/**rib_dest_vrf*/staticinlinestructzebra_vrf*rib_dest_vr
f(rib_dest_t*dest){returnrib_table_info(rib_dest_table(dest))->zvrf;}/**rib_tabl
es_iter_init*/staticinlinevoidrib_tables_iter_init(rib_tables_iter_t*iter){memse
t(iter,0,sizeof(*iter));iter->state=RIB_TABLES_ITER_S_INIT;}/**rib_tables_iter_s
tarted**ReturnsTRUEifthisiteratorhasstartediteratingoverthesetof*tables.*/static
inlineintrib_tables_iter_started(rib_tables_iter_t*iter){returniter->state!=RIB_
TABLES_ITER_S_INIT;}/**rib_tables_iter_cleanup*/staticinlinevoidrib_tables_iter_
cleanup(rib_tables_iter_t*iter){iter->state=RIB_TABLES_ITER_S_DONE;}DECLARE_HOOK
(rib_update,(structroute_node*rn,constchar*reason),(rn,reason))externvoidzebra_v
ty_init(void);externintstatic_config(structvty*vty,structzebra_vrf*zvrf,afi_tafi
,safi_tsafi,constchar*cmd);externvoidstatic_config_install_delayed_routes(struct
zebra_vrf*zvrf);externpid_tpid;#endif/*_ZEBRA_RIB_H*/