/**Kernelroutingtablereadupbynetlink*Copyright(C)1998KunihiroIshiguro**Thisfilei
spartofGNUZebra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodifyit*unde
rthetermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eit
herversion2,or(atyouroption)any*laterversion.**GNUZebraisdistributedinthehopetha
titwillbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTA
BILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetail
s.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;
seethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,Fift
hFloor,Boston,MA02110-1301USA*/#include<zebra.h>#ifdefGNU_LINUX#include"vty.h"#i
nclude"zebra/rt.h"#include"zebra/zebra_pbr.h"#include"zebra/rt_netlink.h"#includ
e"zebra/rule_netlink.h"voidroute_read(structzebra_ns*zns){netlink_route_read(zns
);}voidmacfdb_read(structzebra_ns*zns){netlink_macfdb_read(zns);}voidmacfdb_read
_for_bridge(structzebra_ns*zns,structinterface*ifp,structinterface*br_if){netlin
k_macfdb_read_for_bridge(zns,ifp,br_if);}voidneigh_read(structzebra_ns*zns){netl
ink_neigh_read(zns);}voidneigh_read_for_vlan(structzebra_ns*zns,structinterface*
vlan_if){netlink_neigh_read_for_vlan(zns,vlan_if);}voidkernel_read_pbr_rules(str
uctzebra_ns*zns){netlink_rules_read(zns);}#endif/*GNU_LINUX*/