/**Kernelroutingtablereadbysysctlfunction.*Copyright(C)1997,98KunihiroIshiguro**
ThisfileispartofGNUZebra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodi
fyit*underthetermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFound
ation;eitherversion2,or(atyouroption)any*laterversion.**GNUZebraisdistributedint
hehopethatitwillbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*
MERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseform
oredetails.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthi
sprogram;seethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51Frankl
inSt,FifthFloor,Boston,MA02110-1301USA*/#include<zebra.h>#if!defined(GNU_LINUX)&
&!defined(SUNOS_5)#include"memory.h"#include"zebra_memory.h"#include"log.h"#incl
ude"vrf.h"#include"zebra/rt.h"#include"zebra/kernel_socket.h"#include"zebra/zebr
a_pbr.h"/*Kernelroutingtablereadupbysysctlfunction.*/voidroute_read(structzebra_
ns*zns){caddr_tbuf,end,ref;size_tbufsiz;structrt_msghdr*rtm;#defineMIBSIZ6intmib
[MIBSIZ]={CTL_NET,PF_ROUTE,0,0,NET_RT_DUMP,0};if(zns->ns_id!=NS_DEFAULT)return;/
*Getbuffersize.*/if(sysctl(mib,MIBSIZ,NULL,&bufsiz,NULL,0)<0){zlog_warn("sysctlf
ail:%s",safe_strerror(errno));return;}/*Allocatebuffer.*/ref=buf=XMALLOC(MTYPE_T
MP,bufsiz);/*Readroutingtableinformationbycallingsysctl().*/if(sysctl(mib,MIBSIZ
,buf,&bufsiz,NULL,0)<0){zlog_warn("sysctl()failby%s",safe_strerror(errno));XFREE
(MTYPE_TMP,ref);return;}for(end=buf+bufsiz;buf<end;buf+=rtm->rtm_msglen){rtm=(st
ructrt_msghdr*)buf;/*WemustsetRTF_DONEhere,sortm_read()doesn'tignorethe*message.
*/SET_FLAG(rtm->rtm_flags,RTF_DONE);rtm_read(rtm);}/*Freebuffer.*/XFREE(MTYPE_TM
P,ref);return;}/*Onlyimplementedforthenetlinkmethod.*/voidmacfdb_read(structzebr
a_ns*zns){}voidmacfdb_read_for_bridge(structzebra_ns*zns,structinterface*ifp,str
uctinterface*br_if){}voidneigh_read(structzebra_ns*zns){}voidneigh_read_for_vlan
(structzebra_ns*zns,structinterface*vlan_if){}voidkernel_read_pbr_rules(structze
bra_ns*zns){}#endif/*!defined(GNU_LINUX)&&!defined(SUNOS_5)*/