/**ZebraPolicyBasedRouting(PBR)interactionwiththekernelusing*netlink.*Copyright(
C)2018CumulusNetworks,Inc.*DonaldSharp**ThisfileispartofFRR.**FRRisfreesoftware;
youcanredistributeitand/ormodifyit*underthetermsoftheGNUGeneralPublicLicenseaspu
blishedbythe*FreeSoftwareFoundation;eitherversion2,or(atyouroption)any*latervers
ion.**FRRisdistributedinthehopethatitwillbeuseful,but*WITHOUTANYWARRANTY;without
eventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU
*GeneralPublicLicenseformoredetails.**YoushouldhavereceivedacopyoftheGNUGeneralP
ublicLicense*alongwithFRR;seethefileCOPYING.Ifnot,writetotheFree*SoftwareFoundat
ion,Inc.,59TemplePlace-Suite330,Boston,MA*02111-1307,USA.*/#include<zebra.h>#ifn
defHAVE_NETLINK#include"if.h"#include"prefix.h"#include"vrf.h"#include"zebra/zse
rv.h"#include"zebra/zebra_ns.h"#include"zebra/zebra_vrf.h"#include"zebra/rt.h"#i
nclude"zebra/interface.h"#include"zebra/debug.h"#include"zebra/rtadv.h"#include"
zebra/kernel_netlink.h"#include"zebra/rule_netlink.h"#include"zebra/zebra_pbr.h"
voidkernel_add_pbr_rule(structzebra_pbr_rule*rule){}voidkernel_del_pbr_rule(stru
ctzebra_pbr_rule*rule){}#endif