/*zebratableManagerforroutingtableidentifiermanagement*Copyright(C)20186WIND**Th
isprogramisfreesoftware;youcanredistributeitand/ormodifyit*underthetermsoftheGNU
GeneralPublicLicenseaspublishedbytheFree*SoftwareFoundation;eitherversion2oftheL
icense,or(atyouroption)*anylaterversion.**Thisprogramisdistributedinthehopethati
twillbeuseful,butWITHOUT*ANYWARRANTY;withouteventheimpliedwarrantyofMERCHANTABIL
ITYor*FITNESSFORAPARTICULARPURPOSE.SeetheGNUGeneralPublicLicensefor*moredetails.
**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;se
ethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthF
loor,Boston,MA02110-1301USA*/#include<stdio.h>#include<string.h>#include<sys/typ
es.h>#include"zebra.h"#include"zserv.h"#include"lib/log.h"#include"lib/memory.h"
#include"lib/table.h"#include"lib/network.h"#include"lib/stream.h"#include"lib/z
client.h"#include"lib/libfrr.h"#include"lib/vrf.h"#include"zebra_vrf.h"#include"
label_manager.h"/*forNO_PROTO*/#include"table_manager.h"/*routingtableidentifier
s**/#ifdefSUNOS_5/*SunOS*/#else#if!defined(GNU_LINUX)&&!defined(SUNOS_5)/*BSDsys
tems*/#else/*LinuxSystems*/#defineRT_TABLE_ID_LOCAL255#defineRT_TABLE_ID_MAIN254
#defineRT_TABLE_ID_DEFAULT253#defineRT_TABLE_ID_COMPAT252#defineRT_TABLE_ID_UNSP
EC0#endif/*!def(GNU_LINUX)&&!defined(SUNOS_5)*/#endif/*SUNOS_5*/#defineRT_TABLE_
ID_UNRESERVED_MIN1#defineRT_TABLE_ID_UNRESERVED_MAX0xffffffffstructtable_manager
tbl_mgr;DEFINE_MGROUP(TABLE_MGR,"TableManager");DEFINE_MTYPE_STATIC(TABLE_MGR,TM
_CHUNK,"TableManagerChunk");staticvoiddelete_table_chunk(void*val){XFREE(MTYPE_T
M_CHUNK,val);}/***Inittablemanager*/voidtable_manager_enable(ns_id_tns_id){if(ns
_id!=NS_DEFAULT)return;tbl_mgr.lc_list=list_new();tbl_mgr.lc_list->del=delete_ta
ble_chunk;}/***Corefunction,assignstablechunks**Itfirstsearchesthroughthelisttoc
heckifthere'soneavailable*(previouslyreleased).Otherwiseitcreatesandassignsanewo
ne**@paramprotoDaemonprotocolofclient,toidentifytheowner*@paraminstanceInstance,
toidentifytheowner*@parasizeSizeofthetablechunk*@returnPointertotheassignedtable
chunk*/structtable_manager_chunk*assign_table_chunk(uint8_tproto,uint16_tinstanc
e,uint32_tsize){structtable_manager_chunk*tmc;structlistnode*node;uint32_tstart;
/*firstcheckifthere'soneavailable*/for(ALL_LIST_ELEMENTS_RO(tbl_mgr.lc_list,node
,tmc)){if(tmc->proto==NO_PROTO&&tmc->end-tmc->start+1==size){tmc->proto=proto;tm
c->instance=instance;returntmc;}}/*otherwisecreateanewone*/tmc=XCALLOC(MTYPE_TM_
CHUNK,sizeof(structtable_manager_chunk));if(!tmc)returnNULL;/*tableRTIDsrangeare
[1;252]and[256;0xffffffff]*-checkiftherequestedrangecanbewithinthefirstrange,*ot
herwiseelectsecondone*-TODO:vrf-liteshavetheirowntableidentifier.*Inthatcase,tab
le_idshouldberemovedfromthetablerange.*/if(list_isempty(tbl_mgr.lc_list))start=R
T_TABLE_ID_UNRESERVED_MIN;elsestart=((structtable_manager_chunk*)listgetdata(lis
ttail(tbl_mgr.lc_list)))->end+1;#ifdefSUNOS_5/*SunOS*/#else#if!defined(GNU_LINUX
)&&!defined(SUNOS_5)/*BSDsystems*/#else/*LinuxSystems*//*ifnotenoughroomspacebet
weenMINandCOMPAT,*thenbeginafterLOCAL*/if(start<RT_TABLE_ID_COMPAT&&(size>RT_TAB
LE_ID_COMPAT-RT_TABLE_ID_UNRESERVED_MIN))start=RT_TABLE_ID_LOCAL+1;#endif/*!def(
GNU_LINUX)&&!defined(SUNOS_5)*/#endif/*SUNOS_5*/tmc->start=start;if(RT_TABLE_ID_
UNRESERVED_MAX-size+1<start){zlog_err("Reachedmaxtableid.Start/Size%u/%u",start,
size);XFREE(MTYPE_TM_CHUNK,tmc);returnNULL;}tmc->end=tmc->start+size-1;tmc->prot
o=proto;tmc->instance=instance;listnode_add(tbl_mgr.lc_list,tmc);returntmc;}/***
Corefunction,releasenolongerusedtablechunks**@paramprotoDaemonprotocolofclient,t
oidentifytheowner*@paraminstanceInstance,toidentifytheowner*@paramstartFirsttabl
eRTIDofthechunk*@paramendLasttableRTIDofthechunk*@return0onsuccess,-1otherwise*/
intrelease_table_chunk(uint8_tproto,uint16_tinstance,uint32_tstart,uint32_tend){
structlistnode*node;structtable_manager_chunk*tmc;intret=-1;/*checkthatsizematch
es*/zlog_debug("Releasingtablechunk:%u-%u",start,end);/*findchunkanddisown*/for(
ALL_LIST_ELEMENTS_RO(tbl_mgr.lc_list,node,tmc)){if(tmc->start!=start)continue;if
(tmc->end!=end)continue;if(tmc->proto!=proto||tmc->instance!=instance){zlog_err(
"%s:Daemonmismatch!!",__func__);continue;}tmc->proto=NO_PROTO;tmc->instance=0;re
t=0;break;}if(ret!=0)zlog_err("%s:Tablechunknotreleased!!",__func__);returnret;}
/***Releasetablechunksfromaclient.**Calledonclientdisconnectionorreconnection.It
onlyreleaseschunks*withemptykeepvalue.**@paramprotoDaemonprotocolofclient,toiden
tifytheowner*@paraminstanceInstance,toidentifytheowner*@returnNumberofchunksrele
ased*/intrelease_daemon_table_chunks(uint8_tproto,uint16_tinstance){structlistno
de*node;structtable_manager_chunk*tmc;intcount=0;intret;for(ALL_LIST_ELEMENTS_RO
(tbl_mgr.lc_list,node,tmc)){if(tmc->proto==proto&&tmc->instance==instance){ret=r
elease_table_chunk(tmc->proto,tmc->instance,tmc->start,tmc->end);if(ret==0)count
++;}}zlog_debug("%s:Released%dtablechunks",__func__,count);returncount;}voidtabl
e_manager_disable(ns_id_tns_id){if(ns_id!=NS_DEFAULT)return;list_delete_and_null
(&tbl_mgr.lc_list);}