/*zebra_mroutecode*Copyright(C)2016CumulusNetworks,Inc.*DonaldSharp**Thisfileisp
artofQuagga**Quaggaisfreesoftware;youcanredistributeitand/ormodifyit*undertheter
msoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eithervers
ion2,or(atyouroption)any*laterversion.**Quaggaisdistributedinthehopethatitwillbe
useful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorF
ITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Yoush
ouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefil
eCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Bo
ston,MA02110-1301USA*/#include<zebra.h>#include"stream.h"#include"prefix.h"#incl
ude"vrf.h"#include"rib.h"#include"zebra/zserv.h"#include"zebra/zebra_vrf.h"#incl
ude"zebra/zebra_mroute.h"#include"zebra/rt.h"#include"zebra/debug.h"voidzebra_ip
mr_route_stats(ZAPI_HANDLER_ARGS){structmcast_route_datamroute;structstream*s;in
tsuc=-1;memset(&mroute,0,sizeof(mroute));STREAM_GET(&mroute.sg.src,msg,4);STREAM
_GET(&mroute.sg.grp,msg,4);STREAM_GETL(msg,mroute.ifindex);if(IS_ZEBRA_DEBUG_KER
NEL){charsbuf[40];chargbuf[40];strlcpy(sbuf,inet_ntoa(mroute.sg.src),sizeof(sbuf
));strlcpy(gbuf,inet_ntoa(mroute.sg.grp),sizeof(gbuf));zlog_debug("Askingfor(%s,
%s)mrouteinformation",sbuf,gbuf);}suc=kernel_get_ipmr_sg_stats(zvrf,&mroute);str
eam_failure:s=stream_new(ZEBRA_MAX_PACKET_SIZ);stream_reset(s);zclient_create_he
ader(s,ZEBRA_IPMR_ROUTE_STATS,zvrf_id(zvrf));stream_put_in_addr(s,&mroute.sg.src
);stream_put_in_addr(s,&mroute.sg.grp);stream_put(s,&mroute.lastused,sizeof(mrou
te.lastused));stream_putl(s,suc);stream_putw_at(s,0,stream_get_endp(s));zebra_se
rver_send_message(client,s);}