/**ZebraMPLSDatastructuresanddefinitions*Copyright(C)2015CumulusNetworks,Inc.**T
hisfileispartofGNUZebra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodif
yit*underthetermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFounda
tion;eitherversion2,or(atyouroption)any*laterversion.**GNUZebraisdistributedinth
ehopethatitwillbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*M
ERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformo
redetails.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthis
program;seethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51Frankli
nSt,FifthFloor,Boston,MA02110-1301USA*/#ifndef_ZEBRA_MPLS_H#define_ZEBRA_MPLS_H#
include"prefix.h"#include"table.h"#include"queue.h"#include"hash.h"#include"jhas
h.h"#include"nexthop.h"#include"vty.h"#include"memory.h"#include"mpls.h"#include
"zebra/zserv.h"#include"zebra/zebra_vrf.h"/*Definitionsandmacros.*/#defineNHLFE_
FAMILY(nhlfe)\(((nhlfe)->nexthop->type==NEXTHOP_TYPE_IPV6\||(nhlfe)->nexthop->ty
pe==NEXTHOP_TYPE_IPV6_IFINDEX)\?AF_INET6\:AF_INET)#defineMPLS_LABEL_HELPSTR\"Spe
cifylabel(s)forthisroute\nOneormore"\"labelsintherange(16-1048575)separatedby'/'
\n"/*Typedefs*/typedefstructzebra_ile_t_zebra_ile_t;typedefstructzebra_snhlfe_t_
zebra_snhlfe_t;typedefstructzebra_slsp_t_zebra_slsp_t;typedefstructzebra_nhlfe_t
_zebra_nhlfe_t;typedefstructzebra_lsp_t_zebra_lsp_t;typedefstructzebra_fec_t_zeb
ra_fec_t;/**(Outgoing)nexthoplabelforwardingentryconfiguration*/structzebra_snhl
fe_t_{/*Nexthopinformation*/enumnexthop_types_tgtype;uniong_addrgate;char*ifname
;ifindex_tifindex;/*Outlabel.*/mpls_label_tout_label;/*Backpointertobaseentry.*/
zebra_slsp_t*slsp;/*Pointerstomoreoutgoinginformationforsamein-label*/zebra_snhl
fe_t*next;zebra_snhlfe_t*prev;};/**(Outgoing)nexthoplabelforwardingentry*/struct
zebra_nhlfe_t_{/*Typeofentry-staticetc.*/enumlsp_types_ttype;/*Nexthopinformatio
n(withoutgoinglabel)*/structnexthop*nexthop;/*Backpointertobaseentry.*/zebra_lsp
_t*lsp;/*Runtimeinfo-flags,pointersetc.*/uint32_tflags;#defineNHLFE_FLAG_CHANGED
(1<<0)#defineNHLFE_FLAG_SELECTED(1<<1)#defineNHLFE_FLAG_MULTIPATH(1<<2)#defineNH
LFE_FLAG_DELETED(1<<3)#defineNHLFE_FLAG_INSTALLED(1<<4)zebra_nhlfe_t*next;zebra_
nhlfe_t*prev;uint8_tdistance;};/**Incominglabelentry*/structzebra_ile_t_{mpls_la
bel_tin_label;};/**Labelswapentrystaticconfiguration.*/structzebra_slsp_t_{/*Inc
ominglabel*/zebra_ile_tile;/*Listofoutgoingnexthopstaticconfiguration*/zebra_snh
lfe_t*snhlfe_list;};/**Labelswapentry(ile->listofnhlfes)*/structzebra_lsp_t_{/*I
ncominglabel*/zebra_ile_tile;/*ListofNHLFE,pointertobestandnumequal-cost.*/zebra
_nhlfe_t*nhlfe_list;zebra_nhlfe_t*best_nhlfe;uint32_tnum_ecmp;/*Flags*/uint32_tf
lags;#defineLSP_FLAG_SCHEDULED(1<<0)#defineLSP_FLAG_INSTALLED(1<<1)#defineLSP_FL
AG_CHANGED(1<<2)/*Address-familyofNHLFE-savedherefordelete.AllNHLFEs*//*havetobe
ofthesameAF*/uint8_taddr_family;};/**FECtolabelbinding.*/structzebra_fec_t_{/*FE
C(prefix)*/structroute_node*rn;/*In-label-eitherstaticallyboundorderivedfromlabe
lblock.*/mpls_label_tlabel;/*Labelindex(intogloballabelblock),ifvalid*/uint32_tl
abel_index;/*Flags.*/uint32_tflags;#defineFEC_FLAG_CONFIGURED(1<<0)/*Clientsinte
restedinthisFEC.*/structlist*client_list;};/*Functiondeclarations.*//**Stringtol
abelconversion,labelsseparatedby'/'.*/intmpls_str2label(constchar*label_str,uint
8_t*num_labels,mpls_label_t*labels);/**Labeltostringconversion,labelsinstringsep
aratedby'/'.*/char*mpls_label2str(uint8_tnum_labels,mpls_label_t*labels,char*buf
,intlen,intpretty);/**Add/updategloballabelblock.*/intzebra_mpls_label_block_add
(structzebra_vrf*zvrf,uint32_tstart_label,uint32_tend_label);/**Deletegloballabe
lblock.*/intzebra_mpls_label_block_del(structzebra_vrf*vrf);/**DisplayMPLSglobal
labelblockconfiguration(VTYcommandhandler).*/intzebra_mpls_write_label_block_con
fig(structvty*vty,structzebra_vrf*vrf);/**InstalldynamicLSPentry.*/intzebra_mpls
_lsp_install(structzebra_vrf*zvrf,structroute_node*rn,structroute_entry*re);/**U
ninstalldynamicLSPentry,ifany.*/intzebra_mpls_lsp_uninstall(structzebra_vrf*zvrf
,structroute_node*rn,structroute_entry*re);/**Registrationfromaclientforthelabel
bindingforaFEC.Ifabinding*alreadyexists,itisinformedtotheclient.*NOTE:Ifthereisa
manuallyconfiguredlabelbinding,thatisused.*Otherwise,ifaalabelindexisspecified,i
tmeanswehavetoallocatethe*labelfromalocallyconfiguredlabelblock(SRGB),ifoneexist
sandindex*isacceptable.*/intzebra_mpls_fec_register(structzebra_vrf*zvrf,structp
refix*p,uint32_tlabel_index,structzserv*client);/**Deregistrationfromaclientfort
helabelbindingforaFEC.TheFEC*itselfisdeletedifnootherregisteredclientsexistandth
ereisno*labelboundtotheFEC.*/intzebra_mpls_fec_unregister(structzebra_vrf*zvrf,s
tructprefix*p,structzserv*client);/**CleanupanyFECsregisteredbythisclient.*/intz
ebra_mpls_cleanup_fecs_for_client(structzebra_vrf*zvrf,structzserv*client);/**Re
turnFEC(ifany)towhichthislabelisbound.*Note:Onlyworksforper-prefixbindingandwhen
thelabelisnot*implicit-null.*TODO:Currentlywalksentiretable,canoptimizelaterwith
another*hash..*/zebra_fec_t*zebra_mpls_fec_for_label(structzebra_vrf*zvrf,mpls_l
abel_tlabel);/**InformifspecifiedlabeliscurrentlyboundtoaFECornot.*/intzebra_mpl
s_label_already_bound(structzebra_vrf*zvrf,mpls_label_tlabel);/**AddstaticFECtol
abelbinding.Ifthereareclientsregisteredforthis*FEC,notifythem.Iftherearelabeledr
outesforthisFEC,installthe*labelforwardingentry.*/intzebra_mpls_static_fec_add(s
tructzebra_vrf*zvrf,structprefix*p,mpls_label_tin_label);/**RemovestaticFECtolab
elbinding.Iftherearenoclientsregistered*forthisFEC,deletetheFEC;elsenotifyclient
s.*Note:Upondeleteofstaticbinding,iflabelindexexistsforthisFEC,*clientmayneedtob
eupdatedwithderivedlabel.*/intzebra_mpls_static_fec_del(structzebra_vrf*zvrf,str
uctprefix*p);/**DisplayMPLSFECtolabelbindingconfiguration(VTYcommandhandler).*/i
ntzebra_mpls_write_fec_config(structvty*vty,structzebra_vrf*zvrf);/**DisplayMPLS
FECtolabelbinding(VTYcommandhandler).*/voidzebra_mpls_print_fec_table(structvty*
vty,structzebra_vrf*zvrf);/**DisplayMPLSFECtolabelbindingforaspecificFEC(VTYcomm
andhandler).*/voidzebra_mpls_print_fec(structvty*vty,structzebra_vrf*zvrf,struct
prefix*p);/**Install/uninstallaFEC-To-NHLFE(FTN)binding.*/intmpls_ftn_update(int
add,structzebra_vrf*zvrf,enumlsp_types_ttype,structprefix*prefix,enumnexthop_typ
es_tgtype,uniong_addr*gate,ifindex_tifindex,uint8_tdistance,mpls_label_tout_labe
l);/**Install/updateaNHLFEforanLSPintheforwardingtable.Thismaybe*anewLSPentryora
newNHLFEforanexistingin-labeloranupdateof*theout-labelforanexistingNHLFE(updatec
ase).*/intmpls_lsp_install(structzebra_vrf*zvrf,enumlsp_types_ttype,mpls_label_t
in_label,mpls_label_tout_label,enumnexthop_types_tgtype,uniong_addr*gate,ifindex
_tifindex);/**UninstallaparticularNHLFEintheforwardingtable.Ifthisis*theonlyNHLF
E,theentireLSPforwardingentryhastobedeleted.*/intmpls_lsp_uninstall(structzebra_
vrf*zvrf,enumlsp_types_ttype,mpls_label_tin_label,enumnexthop_types_tgtype,union
g_addr*gate,ifindex_tifindex);/**UninstallallLDPNHLFEsforaparticularLSPforwardin
gentry.*IfnootherNHLFEsexist,theentrywouldbedeleted.*/voidmpls_ldp_lsp_uninstall
_all(structhash_backet*backet,void*ctxt);/**UninstallallLDPFEC-To-NHLFE(FTN)bind
ingsofthegivenaddress-family.*/voidmpls_ldp_ftn_uninstall_all(structzebra_vrf*zv
rf,intafi);/**UninstallallSegmentRoutingNHLFEsforaparticularLSPforwardingentry.*
IfnootherNHLFEsexist,theentrywouldbedeleted.*/voidmpls_sr_lsp_uninstall_all(stru
cthash_backet*backet,void*ctxt);#ifdefined(HAVE_CUMULUS)/**Checkthatthelabelvalu
esusedinLSPcreationareconsistent.The*maincriteriaisthatifthereisECMP,thelabelope
rationmuststill*beconsistent-i.e.,allpathseitherdoaswapordoPHP.Thisisdue*tocurre
ntHWrestrictions.*/intzebra_mpls_lsp_label_consistent(structzebra_vrf*zvrf,mpls_
label_tin_label,mpls_label_tout_label,enumnexthop_types_tgtype,uniong_addr*gate,
ifindex_tifindex);#endif/*HAVE_CUMULUS*//**AddstaticLSPentry.Thismaybethefirsten
tryforthisincominglabel*oranadditionalnexthop;anexistingentrymayalsohaveoutgoing
label*changed.*Note:Thelabeloperation(swaporPHP)iscommonfortheLSPentry(all*NHLFE
s).*/intzebra_mpls_static_lsp_add(structzebra_vrf*zvrf,mpls_label_tin_label,mpls
_label_tout_label,enumnexthop_types_tgtype,uniong_addr*gate,ifindex_tifindex);/*
*DeletestaticLSPentry.Thismaybethedeleteofoneparticular*NHLFEforthisincominglabe
lorthedeleteoftheentireentry(i.e.,*allNHLFEs).*NOTE:DeleteoftheonlyNHLFEwillalso
endupdeletingtheentire*LSPconfiguration.*/intzebra_mpls_static_lsp_del(structzeb
ra_vrf*zvrf,mpls_label_tin_label,enumnexthop_types_tgtype,uniong_addr*gate,ifind
ex_tifindex);/**ScheduleallMPLSlabelforwardingentriesforprocessing.*Calleduponch
angesthatmayaffectoneormoreofthemsuchas*interfaceornexthopstatechanges.*/voidzeb
ra_mpls_lsp_schedule(structzebra_vrf*zvrf);/**DisplayMPLSlabelforwardingtablefor
aspecificLSP*(VTYcommandhandler).*/voidzebra_mpls_print_lsp(structvty*vty,struct
zebra_vrf*zvrf,mpls_label_tlabel,uint8_tuse_json);/**DisplayMPLSlabelforwardingt
able(VTYcommandhandler).*/voidzebra_mpls_print_lsp_table(structvty*vty,structzeb
ra_vrf*zvrf,uint8_tuse_json);/**DisplayMPLSLSPconfigurationofallstaticLSPs(VTYco
mmandhandler).*/intzebra_mpls_write_lsp_config(structvty*vty,structzebra_vrf*zvr
f);/**CalledwhenVRFbecomesinactive,cleansupinformationbutkeeps*thetableitself.*N
OTE:CurrentlysupportedonlyfordefaultVRF.*/voidzebra_mpls_cleanup_tables(structze
bra_vrf*zvrf);/**Calleduponprocessexiting,needtodeleteLSPforwarding*entriesfromt
hekernel.*NOTE:CurrentlysupportedonlyfordefaultVRF.*/voidzebra_mpls_close_tables
(structzebra_vrf*zvrf);/**AllocateMPLStablesforthisVRF.*NOTE:Currentlysupportedo
nlyfordefaultVRF.*/voidzebra_mpls_init_tables(structzebra_vrf*zvrf);/**GlobalMPL
Sinitialization.*/voidzebra_mpls_init(void);/**MPLSVTY.*/voidzebra_mpls_vty_init
(void);/*Inlinefunctions.*//**Distance(priority)definitionforLSPNHLFE.*/staticin
lineuint8_tlsp_distance(enumlsp_types_ttype){switch(type){caseZEBRA_LSP_STATIC:r
eturn(route_distance(ZEBRA_ROUTE_STATIC));caseZEBRA_LSP_LDP:return(route_distanc
e(ZEBRA_ROUTE_LDP));caseZEBRA_LSP_BGP:return(route_distance(ZEBRA_ROUTE_BGP));ca
seZEBRA_LSP_NONE:caseZEBRA_LSP_SHARP:caseZEBRA_LSP_SR:return150;}/**Forsomereaso
ncertaincompilersdonotbelieve*thatallthecaseshavebeenhandled.And*WTFdoesthiswork
differentlythanwhenIremoved*thedefaultcase????*/return150;}/**MapRIBtypetoLSPtyp
e.Usedwhenlabeled-routesfromBGP*areconvertedintoLSPs.*/staticinlineenumlsp_types
_tlsp_type_from_re_type(intre_type){switch(re_type){caseZEBRA_ROUTE_STATIC:retur
nZEBRA_LSP_STATIC;caseZEBRA_ROUTE_BGP:returnZEBRA_LSP_BGP;caseZEBRA_ROUTE_SHARP:
returnZEBRA_LSP_SHARP;default:returnZEBRA_LSP_NONE;}}/**MapLSPtypetoRIBtype.*/st
aticinlineintre_type_from_lsp_type(enumlsp_types_tlsp_type){switch(lsp_type){cas
eZEBRA_LSP_STATIC:returnZEBRA_ROUTE_STATIC;caseZEBRA_LSP_LDP:returnZEBRA_ROUTE_L
DP;caseZEBRA_LSP_BGP:returnZEBRA_ROUTE_BGP;caseZEBRA_LSP_SR:returnZEBRA_ROUTE_OS
PF;caseZEBRA_LSP_NONE:returnZEBRA_ROUTE_KERNEL;caseZEBRA_LSP_SHARP:returnZEBRA_R
OUTE_SHARP;}/**Forsomereasoncertaincompilersdonotbelieve*thatallthecaseshavebeen
handled.And*WTFdoesthisworkdifferentlythanwhenIremoved*thedefaultcase????*/retur
nZEBRA_ROUTE_KERNEL;}/*NHLFEtypeasprintablestring.*/staticinlineconstchar*nhlfe_
type2str(enumlsp_types_tlsp_type){switch(lsp_type){caseZEBRA_LSP_STATIC:return"S
tatic";caseZEBRA_LSP_LDP:return"LDP";caseZEBRA_LSP_BGP:return"BGP";caseZEBRA_LSP
_SR:return"SR";caseZEBRA_LSP_SHARP:return"SHARP";caseZEBRA_LSP_NONE:return"Unkno
wn";}/**Forsomereasoncertaincompilersdonotbelieve*thatallthecaseshavebeenhandled
.And*WTFdoesthisworkdifferentlythanwhenIremoved*thedefaultcase????*/return"Unkno
wn";}staticinlinevoidmpls_mark_lsps_for_processing(structzebra_vrf*zvrf){if(!zvr
f)return;zvrf->mpls_flags|=MPLS_FLAG_SCHEDULE_LSPS;}staticinlinevoidmpls_unmark_
lsps_for_processing(structzebra_vrf*zvrf){if(!zvrf)return;zvrf->mpls_flags&=~MPL
S_FLAG_SCHEDULE_LSPS;}staticinlineintmpls_should_lsps_be_processed(structzebra_v
rf*zvrf){if(!zvrf)return0;return((zvrf->mpls_flags&MPLS_FLAG_SCHEDULE_LSPS)?1:0)
;}/*Globalvariables.*/externintmpls_enabled;#endif/*_ZEBRA_MPLS_H*/