/**Copyright(C)2016CumulusNetworks*DonaldSharp**ThisfileispartofQuagga**Quaggais
freesoftware;youcanredistributeitand/ormodifyit*underthetermsoftheGNUGeneralPubl
icLicenseaspublishedbythe*FreeSoftwareFoundation;eitherversion2,or(atyouroption)
any*laterversion.**Quaggaisdistributedinthehopethatitwillbeuseful,but*WITHOUTANY
WARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTICULARP
URPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldhavereceivedacopy
oftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;ifnot,writet
otheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-1301USA*
/#include<zebra.h>#include"log.h"#include"linklist.h"#include"command.h"#include
"memory.h"#include"srcdest_table.h"#include"vrf.h"#include"vty.h"#include"zebra/
debug.h"#include"zebra/zserv.h"#include"zebra/rib.h"#include"zebra/zebra_vrf.h"#
include"zebra/zebra_rnh.h"#include"zebra/router-id.h"#include"zebra/zebra_memory
.h"#include"zebra/zebra_static.h"#include"zebra/interface.h"#include"zebra/zebra
_mpls.h"#include"zebra/zebra_vxlan.h"#include"zebra/zebra_netns_notify.h"externs
tructzebra_tzebrad;staticvoidzebra_vrf_table_create(structzebra_vrf*zvrf,afi_taf
i,safi_tsafi);staticvoidzebra_rnhtable_node_cleanup(structroute_table*table,stru
ctroute_node*node);/*VRFinformationupdate.*/staticvoidzebra_vrf_add_update(struc
tzebra_vrf*zvrf){structlistnode*node,*nnode;structzserv*client;if(IS_ZEBRA_DEBUG
_EVENT)zlog_debug("MESSAGE:ZEBRA_VRF_ADD%s",zvrf_name(zvrf));for(ALL_LIST_ELEMEN
TS(zebrad.client_list,node,nnode,client))zsend_vrf_add(client,zvrf);}staticvoidz
ebra_vrf_delete_update(structzebra_vrf*zvrf){structlistnode*node,*nnode;structzs
erv*client;if(IS_ZEBRA_DEBUG_EVENT)zlog_debug("MESSAGE:ZEBRA_VRF_DELETE%s",zvrf_
name(zvrf));for(ALL_LIST_ELEMENTS(zebrad.client_list,node,nnode,client))zsend_vr
f_delete(client,zvrf);}voidzebra_vrf_update_all(structzserv*client){structvrf*vr
f;RB_FOREACH(vrf,vrf_id_head,&vrfs_by_id){if(vrf->vrf_id!=VRF_UNKNOWN)zsend_vrf_
add(client,vrf_info_lookup(vrf->vrf_id));}}/*CallbackuponcreatinganewVRF.*/stati
cintzebra_vrf_new(structvrf*vrf){structzebra_vrf*zvrf;if(IS_ZEBRA_DEBUG_EVENT)zl
og_info("VRF%screated,id%u",vrf->name,vrf->vrf_id);zvrf=zebra_vrf_alloc();vrf->i
nfo=zvrf;zvrf->vrf=vrf;router_id_init(zvrf);return0;}/*CallbackuponenablingaVRF.
*/staticintzebra_vrf_enable(structvrf*vrf){structzebra_vrf*zvrf=vrf->info;struct
route_table*stable;structroute_node*rn;structstatic_route*si;structroute_table*t
able;structinterface*ifp;afi_tafi;safi_tsafi;assert(zvrf);if(IS_ZEBRA_DEBUG_EVEN
T)zlog_debug("VRF%sid%uisnowactive",zvrf_name(zvrf),zvrf_id(zvrf));if(vrf_is_bac
kend_netns())zvrf->zns=zebra_ns_lookup((ns_id_t)vrf->vrf_id);elsezvrf->zns=zebra
_ns_lookup(NS_DEFAULT);/*InformclientsthattheVRFisnowactive.Thisisan*addforthecl
ients.*/zebra_vrf_add_update(zvrf);/*Allocatetables*/for(afi=AFI_IP;afi<=AFI_IP6
;afi++){for(safi=SAFI_UNICAST;safi<=SAFI_MULTICAST;safi++)zebra_vrf_table_create
(zvrf,afi,safi);table=route_table_init();table->cleanup=zebra_rnhtable_node_clea
nup;zvrf->rnh_table[afi]=table;table=route_table_init();table->cleanup=zebra_rnh
table_node_cleanup;zvrf->import_check_table[afi]=table;}/*Installanystaticroutes
configuredforthisVRF.*/for(afi=AFI_IP;afi<AFI_MAX;afi++)for(safi=SAFI_UNICAST;sa
fi<SAFI_MAX;safi++){stable=zvrf->stable[afi][safi];if(!stable)continue;for(rn=ro
ute_top(stable);rn;rn=route_next(rn))for(si=rn->info;si;si=si->next){si->vrf_id=
vrf->vrf_id;if(si->ifindex){ifp=if_lookup_by_name(si->ifname,si->vrf_id);if(ifp)
si->ifindex=ifp->ifindex;elsecontinue;}static_install_route(afi,safi,&rn->p,NULL
,si);}}/**Wemayhavestaticroutesthatarenowpossibleto*insertintotheappropriatetabl
es*/static_config_install_delayed_routes(zvrf);/*KickoffanyVxLAN-EVPNprocessing.
*/zebra_vxlan_vrf_enable(zvrf);return0;}/*CallbackupondisablingaVRF.*/staticintz
ebra_vrf_disable(structvrf*vrf){structzebra_vrf*zvrf=vrf->info;structroute_table
*stable;structroute_node*rn;structstatic_route*si;structroute_table*table;struct
interface*ifp;afi_tafi;safi_tsafi;unsignedi;assert(zvrf);if(IS_ZEBRA_DEBUG_EVENT
)zlog_debug("VRF%sid%uisnowinactive",zvrf_name(zvrf),zvrf_id(zvrf));/*Uninstalla
nystaticroutesconfiguredforthisVRF.*/for(afi=AFI_IP;afi<AFI_MAX;afi++)for(safi=S
AFI_UNICAST;safi<SAFI_MAX;safi++){stable=zvrf->stable[afi][safi];if(!stable)cont
inue;for(rn=route_top(stable);rn;rn=route_next(rn))for(si=rn->info;si;si=si->nex
t)static_uninstall_route(afi,safi,&rn->p,NULL,si);}/*StopanyVxLAN-EVPNprocessing
.*/zebra_vxlan_vrf_disable(zvrf);/*InformclientsthattheVRFisnowinactive.Thisisa*
deletefortheclients.*/zebra_vrf_delete_update(zvrf);/*Ifaskedtoretainroutes,ther
e'snothingmoretodo.*/if(CHECK_FLAG(zvrf->flags,ZEBRA_VRF_RETAIN))return0;/*Remov
eallroutes.*/for(afi=AFI_IP;afi<=AFI_IP6;afi++){for(safi=SAFI_UNICAST;safi<=SAFI
_MULTICAST;safi++)rib_close_table(zvrf->table[afi][safi]);}/*CleanupVxlan,MPLSan
dPWtables.*/zebra_vxlan_cleanup_tables(zvrf);zebra_mpls_cleanup_tables(zvrf);zeb
ra_pw_exit(zvrf);/*Removelink-localIPv4addressescreatedforBGPunnumberedpeering.*
/FOR_ALL_INTERFACES(vrf,ifp)if_nbr_ipv6ll_to_ipv4ll_neigh_del_all(ifp);/*clean-u
pworkqueues*/for(i=0;i<MQ_SIZE;i++){structlistnode*lnode,*nnode;structroute_node
*rnode;rib_dest_t*dest;for(ALL_LIST_ELEMENTS(zebrad.mq->subq[i],lnode,nnode,rnod
e)){dest=rib_dest_from_rnode(rnode);if(dest&&rib_dest_vrf(dest)==zvrf){route_unl
ock_node(rnode);list_delete_node(zebrad.mq->subq[i],lnode);zebrad.mq->size--;}}}
/*Cleanup(free)routingtablesandNHTtables.*/for(afi=AFI_IP;afi<=AFI_IP6;afi++){vo
id*table_info;for(safi=SAFI_UNICAST;safi<=SAFI_MULTICAST;safi++){table=zvrf->tab
le[afi][safi];table_info=table->info;route_table_finish(table);XFREE(MTYPE_RIB_T
ABLE_INFO,table_info);zvrf->table[afi][safi]=NULL;}route_table_finish(zvrf->rnh_
table[afi]);zvrf->rnh_table[afi]=NULL;route_table_finish(zvrf->import_check_tabl
e[afi]);zvrf->import_check_table[afi]=NULL;}return0;}staticintzebra_vrf_delete(s
tructvrf*vrf){structzebra_vrf*zvrf=vrf->info;structroute_table*table;afi_tafi;sa
fi_tsafi;unsignedi;assert(zvrf);if(IS_ZEBRA_DEBUG_EVENT)zlog_debug("VRF%sid%udel
eted",zvrf_name(zvrf),zvrf_id(zvrf));/*clean-upworkqueues*/for(i=0;i<MQ_SIZE;i++
){structlistnode*lnode,*nnode;structroute_node*rnode;rib_dest_t*dest;for(ALL_LIS
T_ELEMENTS(zebrad.mq->subq[i],lnode,nnode,rnode)){dest=rib_dest_from_rnode(rnode
);if(dest&&rib_dest_vrf(dest)==zvrf){route_unlock_node(rnode);list_delete_node(z
ebrad.mq->subq[i],lnode);zebrad.mq->size--;}}}/*FreeVxlanandMPLS.*/zebra_vxlan_c
lose_tables(zvrf);zebra_mpls_close_tables(zvrf);/*releaseallocatedmemory*/for(af
i=AFI_IP;afi<=AFI_IP6;afi++){void*table_info;for(safi=SAFI_UNICAST;safi<=SAFI_MU
LTICAST;safi++){table=zvrf->table[afi][safi];if(table){table_info=table->info;ro
ute_table_finish(table);XFREE(MTYPE_RIB_TABLE_INFO,table_info);}table=zvrf->stab
le[afi][safi];route_table_finish(table);}route_table_finish(zvrf->rnh_table[afi]
);route_table_finish(zvrf->import_check_table[afi]);}/*CleanupEVPNstatesforvrf*/
zebra_vxlan_vrf_delete(zvrf);list_delete_all_node(zvrf->rid_all_sorted_list);lis
t_delete_all_node(zvrf->rid_lo_sorted_list);XFREE(MTYPE_ZEBRA_VRF,zvrf);vrf->inf
o=NULL;return0;}/*ReturnifthisVRFhasanyFRRconfigurationornot.*IMPORTANT:Thisfunc
tionneedstobeupdatedwhenadditionalconfiguration*isaddedforaVRF.*/intzebra_vrf_ha
s_config(structzebra_vrf*zvrf){afi_tafi;safi_tsafi;structroute_table*stable;/*NO
TE:Thisisadon'tcareforthedefaultVRF,butwegothrough*themotionstokeepthingsconsist
ent.*//*Anystaticroutes?*/for(afi=AFI_IP;afi<AFI_MAX;afi++){for(safi=SAFI_UNICAS
T;safi<SAFI_MAX;safi++){stable=zvrf->stable[afi][safi];if(!stable)continue;if(ro
ute_table_count(stable))return1;}}/*EVPNL3-VNI?*/if(zvrf->l3vni)return1;return0;
}/*LookuptheroutingtableinaVRFbasedonbothVRF-Idandtable-id.*NOTE:Table-idisrelev
antonlyintheDefaultVRF.*/structroute_table*zebra_vrf_table_with_table_id(afi_taf
i,safi_tsafi,vrf_id_tvrf_id,uint32_ttable_id){structroute_table*table=NULL;if(af
i>=AFI_MAX||safi>=SAFI_MAX)returnNULL;if(vrf_id==VRF_DEFAULT){if(table_id==RT_TA
BLE_MAIN||table_id==zebrad.rtm_table_default)table=zebra_vrf_table(afi,safi,vrf_
id);elsetable=zebra_vrf_other_route_table(afi,table_id,vrf_id);}elsetable=zebra_
vrf_table(afi,safi,vrf_id);returntable;}voidzebra_rtable_node_cleanup(structrout
e_table*table,structroute_node*node){structroute_entry*re,*next;RNODE_FOREACH_RE
_SAFE(node,re,next){rib_unlink(node,re);}if(node->info)XFREE(MTYPE_RIB_DEST,node
->info);}staticvoidzebra_stable_node_cleanup(structroute_table*table,structroute
_node*node){structstatic_route*si,*next;if(node->info)for(si=node->info;si;si=ne
xt){next=si->next;XFREE(MTYPE_STATIC_ROUTE,si);}}staticvoidzebra_rnhtable_node_c
leanup(structroute_table*table,structroute_node*node){if(node->info)zebra_free_r
nh(node->info);}/**CreatearoutingtableforthespecificAFI/SAFIinthegivenVRF.*/stat
icvoidzebra_vrf_table_create(structzebra_vrf*zvrf,afi_tafi,safi_tsafi){rib_table
_info_t*info;structroute_table*table;assert(!zvrf->table[afi][safi]);if(afi==AFI
_IP6)table=srcdest_table_init();elsetable=route_table_init();table->cleanup=zebr
a_rtable_node_cleanup;zvrf->table[afi][safi]=table;info=XCALLOC(MTYPE_RIB_TABLE_
INFO,sizeof(*info));info->zvrf=zvrf;info->afi=afi;info->safi=safi;table->info=in
fo;}/*AllocatenewzebraVRF.*/structzebra_vrf*zebra_vrf_alloc(void){structzebra_vr
f*zvrf;afi_tafi;safi_tsafi;structroute_table*table;zvrf=XCALLOC(MTYPE_ZEBRA_VRF,
sizeof(structzebra_vrf));/*Allocatetableforstaticrouteconfiguration.*/for(afi=AF
I_IP;afi<=AFI_IP6;afi++){for(safi=SAFI_UNICAST;safi<=SAFI_MULTICAST;safi++){if(a
fi==AFI_IP6)table=srcdest_table_init();elsetable=route_table_init();table->clean
up=zebra_stable_node_cleanup;zvrf->stable[afi][safi]=table;}}zebra_vxlan_init_ta
bles(zvrf);zebra_mpls_init_tables(zvrf);zebra_pw_init(zvrf);returnzvrf;}/*Lookup
VRFbyidentifier.*/structzebra_vrf*zebra_vrf_lookup_by_id(vrf_id_tvrf_id){returnv
rf_info_lookup(vrf_id);}/*LookupVRFbyname.*/structzebra_vrf*zebra_vrf_lookup_by_
name(constchar*name){structvrf*vrf;if(!name)name=VRF_DEFAULT_NAME;vrf=vrf_lookup
_by_name(name);if(vrf)return((structzebra_vrf*)vrf->info);returnNULL;}/*Lookupth
eroutingtableinanenabledVRF.*/structroute_table*zebra_vrf_table(afi_tafi,safi_ts
afi,vrf_id_tvrf_id){structzebra_vrf*zvrf=vrf_info_lookup(vrf_id);if(!zvrf)return
NULL;if(afi>=AFI_MAX||safi>=SAFI_MAX)returnNULL;returnzvrf->table[afi][safi];}/*
LookupthestaticroutingtableinaVRF.*/structroute_table*zebra_vrf_static_table(afi
_tafi,safi_tsafi,structzebra_vrf*zvrf){if(!zvrf)returnNULL;if(afi>=AFI_MAX||safi
>=SAFI_MAX)returnNULL;returnzvrf->stable[afi][safi];}structroute_table*zebra_vrf
_other_route_table(afi_tafi,uint32_ttable_id,vrf_id_tvrf_id){structzebra_vrf*zvr
f;structzebra_ns*zns;zvrf=vrf_info_lookup(vrf_id);if(!zvrf)returnNULL;zns=zvrf->
zns;if(afi>=AFI_MAX)returnNULL;if((vrf_id==VRF_DEFAULT)&&(table_id!=RT_TABLE_MAI
N)&&(table_id!=zebrad.rtm_table_default)){returnzebra_ns_get_table(zns,zvrf,tabl
e_id,afi);}returnzvrf->table[afi][SAFI_UNICAST];}staticintvrf_config_write(struc
tvty*vty){structvrf*vrf;structzebra_vrf*zvrf;RB_FOREACH(vrf,vrf_name_head,&vrfs_
by_name){zvrf=vrf->info;if(!zvrf)continue;if(zvrf_id(zvrf)==VRF_DEFAULT){if(zvrf
->l3vni)vty_out(vty,"vni%u\n",zvrf->l3vni);vty_out(vty,"!\n");}if(vrf_is_user_cf
ged(vrf)){vty_out(vty,"vrf%s\n",zvrf_name(zvrf));if(zvrf->l3vni)vty_out(vty,"vni
%u%s\n",zvrf->l3vni,is_l3vni_for_prefix_routes_only(zvrf->l3vni)?"prefix-routes-
only":"");zebra_ns_config_write(vty,(structns*)vrf->ns_ctxt);}static_config(vty,
zvrf,AFI_IP,SAFI_UNICAST,"iproute");static_config(vty,zvrf,AFI_IP,SAFI_MULTICAST
,"ipmroute");static_config(vty,zvrf,AFI_IP6,SAFI_UNICAST,"ipv6route");if(vrf->vr
f_id!=VRF_DEFAULT)vty_out(vty,"!\n");}return0;}/*ZebraVRFinitialization.*/voidze
bra_vrf_init(void){vrf_init(zebra_vrf_new,zebra_vrf_enable,zebra_vrf_disable,zeb
ra_vrf_delete);vrf_cmd_init(vrf_config_write,&zserv_privs);}