/*zebraroutemap.*Copyright(C)2006IBMCorporation**ThisfileispartofGNUZebra.**GNUZ
ebraisfreesoftware;youcanredistributeitand/ormodifyit*underthetermsoftheGNUGener
alPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eitherversion2,or(atyouro
ption)any*laterversion.**GNUZebraisdistributedinthehopethatitwillbeuseful,but*WI
THOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPAR
TICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldhaverecei
vedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;ifno
t,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-
1301USA*/#include<zebra.h>#include"memory.h"#include"zebra_memory.h"#include"pre
fix.h"#include"rib.h"#include"vty.h"#include"routemap.h"#include"command.h"#incl
ude"filter.h"#include"plist.h"#include"nexthop.h"#include"vrf.h"#include"zebra/z
serv.h"#include"zebra/redistribute.h"#include"zebra/debug.h"#include"zebra/zebra
_rnh.h"#include"zebra/zebra_routemap.h"staticuint32_tzebra_rmap_update_timer=ZEB
RA_RMAP_DEFAULT_UPDATE_TIMER;staticstructthread*zebra_t_rmap_update=NULL;char*pr
oto_rm[AFI_MAX][ZEBRA_ROUTE_MAX+1];/*"any"==ZEBRA_ROUTE_MAX*//*NHTrackingroutema
p*/char*nht_rm[AFI_MAX][ZEBRA_ROUTE_MAX+1];/*"any"==ZEBRA_ROUTE_MAX*/char*zebra_
import_table_routemap[AFI_MAX][ZEBRA_KERNEL_TABLE_MAX];structnh_rmap_obj{structn
exthop*nexthop;vrf_id_tvrf_id;uint32_tsource_protocol;intmetric;route_tag_ttag;}
;staticvoidzebra_route_map_set_delay_timer(uint32_tvalue);/*Addzebraroutemaprule
*/staticintzebra_route_match_add(structvty*vty,constchar*command,constchar*arg,r
oute_map_event_ttype){VTY_DECLVAR_CONTEXT(route_map_index,index);intret;intretva
l=CMD_SUCCESS;ret=route_map_add_match(index,command,arg);switch(ret){caseRMAP_RU
LE_MISSING:vty_out(vty,"%%ZebraCan'tfindrule.\n");retval=CMD_WARNING_CONFIG_FAIL
ED;break;caseRMAP_COMPILE_ERROR:vty_out(vty,"%%ZebraArgumentismalformed.\n");ret
val=CMD_WARNING_CONFIG_FAILED;break;caseRMAP_COMPILE_SUCCESS:if(type!=RMAP_EVENT
_MATCH_ADDED){route_map_upd8_dependency(type,arg,index->map->name);}break;}retur
nretval;}/*Deletezebraroutemaprule.*/staticintzebra_route_match_delete(structvty
*vty,constchar*command,constchar*arg,route_map_event_ttype){VTY_DECLVAR_CONTEXT(
route_map_index,index);intret;intretval=CMD_SUCCESS;char*dep_name=NULL;constchar
*tmpstr;char*rmap_name=NULL;if(type!=RMAP_EVENT_MATCH_DELETED){/*ignorethemundan
e,thetypeswithoutanydependency*/if(arg==NULL){if((tmpstr=route_map_get_match_arg
(index,command))!=NULL)dep_name=XSTRDUP(MTYPE_ROUTE_MAP_RULE,tmpstr);}else{dep_n
ame=XSTRDUP(MTYPE_ROUTE_MAP_RULE,arg);}rmap_name=XSTRDUP(MTYPE_ROUTE_MAP_NAME,in
dex->map->name);}ret=route_map_delete_match(index,command,arg);switch(ret){caseR
MAP_RULE_MISSING:vty_out(vty,"%%ZebraCan'tfindrule.\n");retval=CMD_WARNING_CONFI
G_FAILED;break;caseRMAP_COMPILE_ERROR:vty_out(vty,"%%ZebraArgumentismalformed.\n
");retval=CMD_WARNING_CONFIG_FAILED;break;caseRMAP_COMPILE_SUCCESS:if(type!=RMAP
_EVENT_MATCH_DELETED&&dep_name)route_map_upd8_dependency(type,dep_name,rmap_name
);break;}if(dep_name)XFREE(MTYPE_ROUTE_MAP_RULE,dep_name);if(rmap_name)XFREE(MTY
PE_ROUTE_MAP_NAME,rmap_name);returnretval;}/*'matchtagTAG'*Matchfunctionreturn1i
fmatchissuccesselsereturn0*/staticroute_map_result_troute_match_tag(void*rule,st
ructprefix*prefix,route_map_object_ttype,void*object){route_tag_t*tag;structnh_r
map_obj*nh_data;if(type==RMAP_ZEBRA){tag=rule;nh_data=object;if(nh_data->tag==*t
ag)returnRMAP_MATCH;}returnRMAP_NOMATCH;}/*Routemapcommandsfortagmatching*/stati
cstructroute_map_rule_cmdroute_match_tag_cmd={"tag",route_match_tag,route_map_ru
le_tag_compile,route_map_rule_tag_free,};/*`matchinterfaceIFNAME'*//*Matchfuncti
onreturn1ifmatchissuccesselsereturnzero.*/staticroute_map_result_troute_match_in
terface(void*rule,structprefix*prefix,route_map_object_ttype,void*object){struct
nh_rmap_obj*nh_data;char*ifname=rule;ifindex_tifindex;if(type==RMAP_ZEBRA){if(st
rcasecmp(ifname,"any")==0)returnRMAP_MATCH;nh_data=object;if(!nh_data||!nh_data-
>nexthop)returnRMAP_NOMATCH;ifindex=ifname2ifindex(ifname,nh_data->vrf_id);if(if
index==0)returnRMAP_NOMATCH;if(nh_data->nexthop->ifindex==ifindex)returnRMAP_MAT
CH;}returnRMAP_NOMATCH;}/*Routemap`matchinterface'matchstatement.`arg'isIFNAMEva
lue*/staticvoid*route_match_interface_compile(constchar*arg){returnXSTRDUP(MTYPE
_ROUTE_MAP_COMPILED,arg);}/*Freeroutemap'scompiled`matchinterface'value.*/static
voidroute_match_interface_free(void*rule){XFREE(MTYPE_ROUTE_MAP_COMPILED,rule);}
/*Routemapcommandsforinterfacematching*/structroute_map_rule_cmdroute_match_inte
rface_cmd={"interface",route_match_interface,route_match_interface_compile,route
_match_interface_free};DEFUN(match_ip_address_prefix_len,match_ip_address_prefix
_len_cmd,"matchipaddressprefix-len(0-32)",MATCH_STRIP_STR"Matchprefixlengthofipa
ddress\n""Matchprefixlengthofipaddress\n""Prefixlength\n"){returnzebra_route_mat
ch_add(vty,"ipaddressprefix-len",argv[4]->arg,RMAP_EVENT_MATCH_ADDED);}DEFUN(no_
match_ip_address_prefix_len,no_match_ip_address_prefix_len_cmd,"nomatchipaddress
prefix-len[(0-32)]",NO_STRMATCH_STRIP_STR"Matchprefixlengthofipaddress\n""Matchp
refixlengthofipaddress\n""Prefixlength\n"){char*plen=(argc==6)?argv[5]->arg:NULL
;returnzebra_route_match_delete(vty,"ipaddressprefix-len",plen,RMAP_EVENT_MATCH_
DELETED);}DEFUN(match_ipv6_address_prefix_len,match_ipv6_address_prefix_len_cmd,
"matchipv6addressprefix-len(0-128)",MATCH_STRIPV6_STR"Matchprefixlengthofipv6add
ress\n""Matchprefixlengthofipv6address\n""Prefixlength\n"){returnzebra_route_mat
ch_add(vty,"ipv6addressprefix-len",argv[4]->arg,RMAP_EVENT_MATCH_ADDED);}DEFUN(n
o_match_ipv6_address_prefix_len,no_match_ipv6_address_prefix_len_cmd,"nomatchipv
6addressprefix-len[(0-128)]",NO_STRMATCH_STRIPV6_STR"Matchprefixlengthofipaddres
s\n""Matchprefixlengthofipaddress\n""Prefixlength\n"){char*plen=(argc==6)?argv[5
]->arg:NULL;returnzebra_route_match_delete(vty,"ipv6addressprefix-len",plen,RMAP
_EVENT_MATCH_DELETED);}DEFUN(match_ip_nexthop_prefix_len,match_ip_nexthop_prefix
_len_cmd,"matchipnext-hopprefix-len(0-32)",MATCH_STRIP_STR"Matchprefixlenofnexth
opipaddress\n""Matchprefixlenofgivennexthop\n""Prefixlength\n"){returnzebra_rout
e_match_add(vty,"ipnext-hopprefix-len",argv[4]->arg,RMAP_EVENT_MATCH_ADDED);}DEF
UN(no_match_ip_nexthop_prefix_len,no_match_ip_nexthop_prefix_len_cmd,"nomatchipn
ext-hopprefix-len[(0-32)]",NO_STRMATCH_STRIP_STR"Matchprefixlenofnexthopipaddres
s\n""Matchprefixlengthofnexthop\n""Prefixlength\n"){char*plen=(argc==6)?argv[5]-
>arg:NULL;returnzebra_route_match_delete(vty,"ipnext-hopprefix-len",plen,RMAP_EV
ENT_MATCH_DELETED);}DEFUN(match_source_protocol,match_source_protocol_cmd,"match
source-protocol<bgp|ospf|rip|ripng|isis|ospf6|pim|nhrp|eigrp|babel|connected|sys
tem|kernel|static>",MATCH_STR"Matchprotocolviawhichtheroutewaslearnt\n""BGPproto
col\n""OSPFprotocol\n""RIPprotocol\n""RIPNGprotocol\n""ISISprotocol\n""OSPF6prot
ocol\n""PIMprotocol\n""NHRPprotocol\n""EIGRPprotocol\n""BABELprotocol\n""Routesf
romdirectlyconnectedpeer\n""Routesfromsystemconfiguration\n""Routesfromkernel\n"
"Staticallyconfiguredroutes\n"){char*proto=argv[2]->text;inti;i=proto_name2num(p
roto);if(i<0){vty_out(vty,"invalidprotocolname\"%s\"\n",proto);returnCMD_WARNING
_CONFIG_FAILED;}returnzebra_route_match_add(vty,"source-protocol",proto,RMAP_EVE
NT_MATCH_ADDED);}DEFUN(no_match_source_protocol,no_match_source_protocol_cmd,"no
matchsource-protocol[<bgp|ospf|rip|ripng|isis|ospf6|pim|nhrp|eigrp|babel|connect
ed|system|kernel|static>]",NO_STRMATCH_STR"Nomatchprotocolviawhichtheroutewaslea
rnt\n""BGPprotocol\n""OSPFprotocol\n""RIPprotocol\n""RIPNGprotocol\n""ISISprotoc
ol\n""OSPF6protocol\n""PIMprotocol\n""NHRPprotocol\n""EIGRPprotocol\n""BABELprot
ocol\n""Routesfromdirectlyconnectedpeer\n""Routesfromsystemconfiguration\n""Rout
esfromkernel\n""Staticallyconfiguredroutes\n"){char*proto=(argc==4)?argv[3]->tex
t:NULL;returnzebra_route_match_delete(vty,"source-protocol",proto,RMAP_EVENT_MAT
CH_DELETED);}/*setfunctions*/DEFUN(set_src,set_src_cmd,"setsrc<A.B.C.D|X:X::X:X>
",SET_STR"srcaddressforroute\n""IPv4srcaddress\n""IPv6srcaddress\n"){intidx_ip=2
;uniong_addrsrc;structinterface*pif=NULL;intfamily;structprefixp;structvrf*vrf;i
f(inet_pton(AF_INET,argv[idx_ip]->arg,&src.ipv4)!=1){if(inet_pton(AF_INET6,argv[
idx_ip]->arg,&src.ipv6)!=1){vty_out(vty,"%%notavalidIPv4/v6address\n");returnCMD
_WARNING_CONFIG_FAILED;}p.family=family=AF_INET6;p.u.prefix6=src.ipv6;p.prefixle
n=IPV6_MAX_BITLEN;}else{p.family=family=AF_INET;p.u.prefix4=src.ipv4;p.prefixlen
=IPV4_MAX_BITLEN;}if(!zebra_check_addr(&p)){vty_out(vty,"%%notavalidsourceIPv4/v
6address\n");returnCMD_WARNING_CONFIG_FAILED;}RB_FOREACH(vrf,vrf_id_head,&vrfs_b
y_id){if(family==AF_INET)pif=if_lookup_exact_address((void*)&src.ipv4,AF_INET,vr
f->vrf_id);elseif(family==AF_INET6)pif=if_lookup_exact_address((void*)&src.ipv6,
AF_INET6,vrf->vrf_id);if(pif!=NULL)break;}if(!pif){vty_out(vty,"%%notalocaladdre
ss\n");returnCMD_WARNING_CONFIG_FAILED;}VTY_DECLVAR_CONTEXT(route_map_index,inde
x);returngeneric_set_add(vty,index,"src",argv[idx_ip]->arg);}DEFUN(no_set_src,no
_set_src_cmd,"nosetsrc[<A.B.C.D|X:X::X:X>]",NO_STRSET_STR"Sourceaddressforroute\
n""IPv4address\n""IPv6address\n"){char*ip=(argc==4)?argv[3]->arg:NULL;VTY_DECLVA
R_CONTEXT(route_map_index,index);returngeneric_set_delete(vty,index,"src",ip);}D
EFUN(zebra_route_map_timer,zebra_route_map_timer_cmd,"zebraroute-mapdelay-timer(
0-600)",ZEBRA_STR"Setroute-mapparameters\n""Timetowaitbeforeroute-mapupdatesarep
rocessed\n""0meansevent-drivenupdatesaredisabled\n"){intidx_number=3;uint32_trma
p_delay_timer;rmap_delay_timer=strtoul(argv[idx_number]->arg,NULL,10);zebra_rout
e_map_set_delay_timer(rmap_delay_timer);return(CMD_SUCCESS);}DEFUN(no_zebra_rout
e_map_timer,no_zebra_route_map_timer_cmd,"nozebraroute-mapdelay-timer[(0-600)]",
NO_STRZEBRA_STR"Setroute-mapparameters\n""Resetdelay-timertodefaultvalue,30secs\
n""0meansevent-drivenupdatesaredisabled\n"){zebra_route_map_set_delay_timer(ZEBR
A_RMAP_DEFAULT_UPDATE_TIMER);return(CMD_SUCCESS);}DEFUN(ip_protocol,ip_protocol_
cmd,"ipprotocol"FRR_IP_PROTOCOL_MAP_STR_ZEBRA"route-mapROUTE-MAP",IP_STR"Filterr
outinginfoexchangedbetweenzebraandprotocol\n"FRR_IP_PROTOCOL_MAP_HELP_STR_ZEBRA"
Specifyroute-map\n""Routemapname\n"){char*proto=argv[2]->text;char*rmap=argv[4]-
>arg;inti;if(strcasecmp(proto,"any")==0)i=ZEBRA_ROUTE_MAX;elsei=proto_name2num(p
roto);if(i<0){vty_out(vty,"invalidprotocolname\"%s\"\n",proto);returnCMD_WARNING
_CONFIG_FAILED;}if(proto_rm[AFI_IP][i]){if(strcmp(proto_rm[AFI_IP][i],rmap)==0)r
eturnCMD_SUCCESS;XFREE(MTYPE_ROUTE_MAP_NAME,proto_rm[AFI_IP][i]);}proto_rm[AFI_I
P][i]=XSTRDUP(MTYPE_ROUTE_MAP_NAME,rmap);if(IS_ZEBRA_DEBUG_RIB_DETAILED)zlog_deb
ug("%u:IPv4Routemapconfigforprotocol%s,schedulingRIBprocessing",VRF_DEFAULT,prot
o);rib_update(VRF_DEFAULT,RIB_UPDATE_RMAP_CHANGE);returnCMD_SUCCESS;}DEFUN(no_ip
_protocol,no_ip_protocol_cmd,"noipprotocol"FRR_IP_PROTOCOL_MAP_STR_ZEBRA"[route-
mapROUTE-MAP]",NO_STRIP_STR"Stopfilteringroutinginfobetweenzebraandprotocol\n"FR
R_IP_PROTOCOL_MAP_HELP_STR_ZEBRA"Specifyroutemap\n""Routemapname\n"){char*proto=
argv[3]->text;char*rmap=(argc==6)?argv[5]->arg:NULL;inti;if(strcasecmp(proto,"an
y")==0)i=ZEBRA_ROUTE_MAX;elsei=proto_name2num(proto);if(i<0){vty_out(vty,"invali
dprotocolname\"%s\"\n",proto);returnCMD_WARNING_CONFIG_FAILED;}if(!proto_rm[AFI_
IP][i])returnCMD_SUCCESS;if(!rmap||strcmp(rmap,proto_rm[AFI_IP][i])==0){XFREE(MT
YPE_ROUTE_MAP_NAME,proto_rm[AFI_IP][i]);proto_rm[AFI_IP][i]=NULL;if(IS_ZEBRA_DEB
UG_RIB_DETAILED)zlog_debug("%u:IPv4Routemapunconfigforprotocol%s,schedulingRIBpr
ocessing",VRF_DEFAULT,proto);rib_update(VRF_DEFAULT,RIB_UPDATE_RMAP_CHANGE);}ret
urnCMD_SUCCESS;}DEFUN(show_ip_protocol,show_ip_protocol_cmd,"showipprotocol",SHO
W_STRIP_STR"IPprotocolfilteringstatus\n"){inti;vty_out(vty,"Protocol:route-map\n
");vty_out(vty,"------------------------\n");for(i=0;i<ZEBRA_ROUTE_MAX;i++){if(p
roto_rm[AFI_IP][i])vty_out(vty,"%-10s:%-10s\n",zebra_route_string(i),proto_rm[AF
I_IP][i]);elsevty_out(vty,"%-10s:none\n",zebra_route_string(i));}if(proto_rm[AFI
_IP][i])vty_out(vty,"%-10s:%-10s\n","any",proto_rm[AFI_IP][i]);elsevty_out(vty,"
%-10s:none\n","any");returnCMD_SUCCESS;}DEFUN(ipv6_protocol,ipv6_protocol_cmd,"i
pv6protocol"FRR_IP6_PROTOCOL_MAP_STR_ZEBRA"route-mapROUTE-MAP",IP6_STR"FilterIPv
6routinginfoexchangedbetweenzebraandprotocol\n"FRR_IP6_PROTOCOL_MAP_HELP_STR_ZEB
RA"Specifyroutemap\n""Routemapname\n"){char*proto=argv[2]->text;char*rmap=argv[4
]->arg;inti;if(strcasecmp(proto,"any")==0)i=ZEBRA_ROUTE_MAX;elsei=proto_name2num
(proto);if(i<0){vty_out(vty,"invalidprotocolname\"%s\"\n",proto);returnCMD_WARNI
NG_CONFIG_FAILED;}if(proto_rm[AFI_IP6][i]){if(strcmp(proto_rm[AFI_IP6][i],rmap)=
=0)returnCMD_SUCCESS;XFREE(MTYPE_ROUTE_MAP_NAME,proto_rm[AFI_IP6][i]);}proto_rm[
AFI_IP6][i]=XSTRDUP(MTYPE_ROUTE_MAP_NAME,rmap);if(IS_ZEBRA_DEBUG_RIB_DETAILED)zl
og_debug("%u:IPv6Routemapconfigforprotocol%s,schedulingRIBprocessing",VRF_DEFAUL
T,proto);rib_update(VRF_DEFAULT,RIB_UPDATE_RMAP_CHANGE);returnCMD_SUCCESS;}DEFUN
(no_ipv6_protocol,no_ipv6_protocol_cmd,"noipv6protocol"FRR_IP6_PROTOCOL_MAP_STR_
ZEBRA"[route-mapROUTE-MAP]",NO_STRIP6_STR"StopfilteringIPv6routinginfobetweenzeb
raandprotocol\n"FRR_IP6_PROTOCOL_MAP_HELP_STR_ZEBRA"Specifyroutemap\n""Routemapn
ame\n"){constchar*proto=argv[3]->text;constchar*rmap=(argc==6)?argv[5]->arg:NULL
;inti;if(strcasecmp(proto,"any")==0)i=ZEBRA_ROUTE_MAX;elsei=proto_name2num(proto
);if(i<0){vty_out(vty,"invalidprotocolname\"%s\"\n",proto);returnCMD_WARNING_CON
FIG_FAILED;}if(!proto_rm[AFI_IP6][i])returnCMD_SUCCESS;if(!rmap||strcmp(rmap,pro
to_rm[AFI_IP6][i])==0){XFREE(MTYPE_ROUTE_MAP_NAME,proto_rm[AFI_IP6][i]);proto_rm
[AFI_IP6][i]=NULL;if(IS_ZEBRA_DEBUG_RIB_DETAILED)zlog_debug("%u:IPv6Routemapunco
nfigforprotocol%s,schedulingRIBprocessing",VRF_DEFAULT,proto);rib_update(VRF_DEF
AULT,RIB_UPDATE_RMAP_CHANGE);}returnCMD_SUCCESS;}DEFUN(show_ipv6_protocol,show_i
pv6_protocol_cmd,"showipv6protocol",SHOW_STRIP6_STR"IPv6protocolfilteringstatus\
n"){inti;vty_out(vty,"Protocol:route-map\n");vty_out(vty,"----------------------
--\n");for(i=0;i<ZEBRA_ROUTE_MAX;i++){if(proto_rm[AFI_IP6][i])vty_out(vty,"%-10s
:%-10s\n",zebra_route_string(i),proto_rm[AFI_IP6][i]);elsevty_out(vty,"%-10s:non
e\n",zebra_route_string(i));}if(proto_rm[AFI_IP6][i])vty_out(vty,"%-10s:%-10s\n"
,"any",proto_rm[AFI_IP6][i]);elsevty_out(vty,"%-10s:none\n","any");returnCMD_SUC
CESS;}DEFUN(ip_protocol_nht_rmap,ip_protocol_nht_rmap_cmd,"ipnht"FRR_IP_PROTOCOL
_MAP_STR_ZEBRA"route-mapROUTE-MAP",IP_STR"FilterNextHoptrackingrouteresolution\n
"FRR_IP_PROTOCOL_MAP_HELP_STR_ZEBRA"Specifyroutemap\n""Routemapname\n"){char*pro
to=argv[2]->text;char*rmap=argv[4]->arg;inti;if(strcasecmp(proto,"any")==0)i=ZEB
RA_ROUTE_MAX;elsei=proto_name2num(proto);if(i<0){vty_out(vty,"invalidprotocolnam
e\"%s\"\n",proto);returnCMD_WARNING_CONFIG_FAILED;}if(nht_rm[AFI_IP][i]){if(strc
mp(nht_rm[AFI_IP][i],rmap)==0)returnCMD_SUCCESS;XFREE(MTYPE_ROUTE_MAP_NAME,nht_r
m[AFI_IP][i]);}nht_rm[AFI_IP][i]=XSTRDUP(MTYPE_ROUTE_MAP_NAME,rmap);zebra_evalua
te_rnh(0,AF_INET,1,RNH_NEXTHOP_TYPE,NULL);returnCMD_SUCCESS;}DEFUN(no_ip_protoco
l_nht_rmap,no_ip_protocol_nht_rmap_cmd,"noipnht"FRR_IP_PROTOCOL_MAP_STR_ZEBRA"[r
oute-mapROUTE-MAP]",NO_STRIP_STR"FilterNextHoptrackingrouteresolution\n"FRR_IP_P
ROTOCOL_MAP_HELP_STR_ZEBRA"Specifyroutemap\n""Routemapname\n"){intidx=0;char*pro
to=argv[3]->text;char*rmap=argv_find(argv,argc,"ROUTE-MAP",&idx)?argv[idx]->arg:
NULL;inti=strmatch(proto,"any")?ZEBRA_ROUTE_MAX:proto_name2num(proto);if(i<0){vt
y_out(vty,"invalidprotocolname\"%s\"\n",proto);returnCMD_WARNING_CONFIG_FAILED;}
if(!nht_rm[AFI_IP][i])returnCMD_SUCCESS;if(!rmap||strcmp(rmap,nht_rm[AFI_IP][i])
==0){XFREE(MTYPE_ROUTE_MAP_NAME,nht_rm[AFI_IP][i]);nht_rm[AFI_IP][i]=NULL;zebra_
evaluate_rnh(0,AF_INET,1,RNH_NEXTHOP_TYPE,NULL);}returnCMD_SUCCESS;}DEFUN(show_i
p_protocol_nht,show_ip_protocol_nht_cmd,"showipnhtroute-map",SHOW_STRIP_STR"IPne
xthoptrackingtable\n""IPNextHoptrackingfilteringstatus\n"){inti;vty_out(vty,"Pro
tocol:route-map\n");vty_out(vty,"------------------------\n");for(i=0;i<ZEBRA_RO
UTE_MAX;i++){if(nht_rm[AFI_IP][i])vty_out(vty,"%-10s:%-10s\n",zebra_route_string
(i),nht_rm[AFI_IP][i]);elsevty_out(vty,"%-10s:none\n",zebra_route_string(i));}if
(nht_rm[AFI_IP][i])vty_out(vty,"%-10s:%-10s\n","any",nht_rm[AFI_IP][i]);elsevty_
out(vty,"%-10s:none\n","any");returnCMD_SUCCESS;}DEFUN(ipv6_protocol_nht_rmap,ip
v6_protocol_nht_rmap_cmd,"ipv6nht"FRR_IP6_PROTOCOL_MAP_STR_ZEBRA"route-mapROUTE-
MAP",IP6_STR"FilterNextHoptrackingrouteresolution\n"FRR_IP6_PROTOCOL_MAP_HELP_ST
R_ZEBRA"Specifyroutemap\n""Routemapname\n"){char*proto=argv[2]->text;char*rmap=a
rgv[4]->arg;inti;if(strcasecmp(proto,"any")==0)i=ZEBRA_ROUTE_MAX;elsei=proto_nam
e2num(proto);if(i<0){vty_out(vty,"invalidprotocolname\"%s\"\n",proto);returnCMD_
WARNING_CONFIG_FAILED;}if(nht_rm[AFI_IP6][i])XFREE(MTYPE_ROUTE_MAP_NAME,nht_rm[A
FI_IP6][i]);nht_rm[AFI_IP6][i]=XSTRDUP(MTYPE_ROUTE_MAP_NAME,rmap);zebra_evaluate
_rnh(0,AF_INET6,1,RNH_NEXTHOP_TYPE,NULL);returnCMD_SUCCESS;}DEFUN(no_ipv6_protoc
ol_nht_rmap,no_ipv6_protocol_nht_rmap_cmd,"noipv6nht"FRR_IP6_PROTOCOL_MAP_STR_ZE
BRA"[route-mapROUTE-MAP]",NO_STRIP6_STR"FilterNextHoptrackingrouteresolution\n"F
RR_IP6_PROTOCOL_MAP_HELP_STR_ZEBRA"Specifyroutemap\n""Routemapname\n"){char*prot
o=argv[3]->text;char*rmap=(argc==6)?argv[5]->arg:NULL;inti;if(strcasecmp(proto,"
any")==0)i=ZEBRA_ROUTE_MAX;elsei=proto_name2num(proto);if(i<0){vty_out(vty,"inva
lidprotocolname\"%s\"\n",proto);returnCMD_WARNING_CONFIG_FAILED;}if(nht_rm[AFI_I
P6][i]&&rmap&&strcmp(rmap,nht_rm[AFI_IP6][i])){vty_out(vty,"invalidroute-map\"%s
\"\n",rmap);returnCMD_WARNING_CONFIG_FAILED;}if(nht_rm[AFI_IP6][i]){XFREE(MTYPE_
ROUTE_MAP_NAME,nht_rm[AFI_IP6][i]);nht_rm[AFI_IP6][i]=NULL;}zebra_evaluate_rnh(0
,AF_INET6,1,RNH_NEXTHOP_TYPE,NULL);returnCMD_SUCCESS;}DEFUN(show_ipv6_protocol_n
ht,show_ipv6_protocol_nht_cmd,"showipv6nhtroute-map",SHOW_STRIP6_STR"NextHopfilt
eringstatus\n""Route-map\n"){inti;vty_out(vty,"Protocol:route-map\n");vty_out(vt
y,"------------------------\n");for(i=0;i<ZEBRA_ROUTE_MAX;i++){if(nht_rm[AFI_IP6
][i])vty_out(vty,"%-10s:%-10s\n",zebra_route_string(i),nht_rm[AFI_IP6][i]);elsev
ty_out(vty,"%-10s:none\n",zebra_route_string(i));}if(nht_rm[AFI_IP][i])vty_out(v
ty,"%-10s:%-10s\n","any",nht_rm[AFI_IP6][i]);elsevty_out(vty,"%-10s:none\n","any
");returnCMD_SUCCESS;}/*XXXXXXXXXXXXXXXXXXXXXXXXXXXX*//*`matchipnext-hopIP_ACCES
S_LIST'*//*Matchfunctionreturn1ifmatchissuccesselsereturnzero.*/staticroute_map_
result_troute_match_ip_next_hop(void*rule,structprefix*prefix,route_map_object_t
type,void*object){structaccess_list*alist;structnh_rmap_obj*nh_data;structprefix
_ipv4p;if(type==RMAP_ZEBRA){nh_data=object;if(!nh_data)returnRMAP_DENYMATCH;swit
ch(nh_data->nexthop->type){caseNEXTHOP_TYPE_IFINDEX:/*Interfaceroutescan'tmatchi
pnext-hop*/returnRMAP_NOMATCH;caseNEXTHOP_TYPE_IPV4_IFINDEX:caseNEXTHOP_TYPE_IPV
4:p.family=AF_INET;p.prefix=nh_data->nexthop->gate.ipv4;p.prefixlen=IPV4_MAX_BIT
LEN;break;default:returnRMAP_NOMATCH;}alist=access_list_lookup(AFI_IP,(char*)rul
e);if(alist==NULL)returnRMAP_NOMATCH;return(access_list_apply(alist,&p)==FILTER_
DENY?RMAP_NOMATCH:RMAP_MATCH);}returnRMAP_NOMATCH;}/*Routemap`ipnext-hop'matchst
atement.`arg'shouldbeaccess-listname.*/staticvoid*route_match_ip_next_hop_compil
e(constchar*arg){returnXSTRDUP(MTYPE_ROUTE_MAP_COMPILED,arg);}/*Freeroutemap'sco
mpiled`.*/staticvoidroute_match_ip_next_hop_free(void*rule){XFREE(MTYPE_ROUTE_MA
P_COMPILED,rule);}/*Routemapcommandsforipnext-hopmatching.*/staticstructroute_ma
p_rule_cmdroute_match_ip_next_hop_cmd={"ipnext-hop",route_match_ip_next_hop,rout
e_match_ip_next_hop_compile,route_match_ip_next_hop_free};/*`matchipnext-hoppref
ix-listPREFIX_LIST'*/staticroute_map_result_troute_match_ip_next_hop_prefix_list
(void*rule,structprefix*prefix,route_map_object_ttype,void*object){structprefix_
list*plist;structnh_rmap_obj*nh_data;structprefix_ipv4p;if(type==RMAP_ZEBRA){nh_
data=(structnh_rmap_obj*)object;if(!nh_data)returnRMAP_DENYMATCH;switch(nh_data-
>nexthop->type){caseNEXTHOP_TYPE_IFINDEX:/*Interfaceroutescan'tmatchipnext-hop*/
returnRMAP_NOMATCH;caseNEXTHOP_TYPE_IPV4_IFINDEX:caseNEXTHOP_TYPE_IPV4:p.family=
AF_INET;p.prefix=nh_data->nexthop->gate.ipv4;p.prefixlen=IPV4_MAX_BITLEN;break;d
efault:returnRMAP_NOMATCH;}plist=prefix_list_lookup(AFI_IP,(char*)rule);if(plist
==NULL)returnRMAP_NOMATCH;return(prefix_list_apply(plist,&p)==PREFIX_DENY?RMAP_N
OMATCH:RMAP_MATCH);}returnRMAP_NOMATCH;}staticvoid*route_match_ip_next_hop_prefi
x_list_compile(constchar*arg){returnXSTRDUP(MTYPE_ROUTE_MAP_COMPILED,arg);}stati
cvoidroute_match_ip_next_hop_prefix_list_free(void*rule){XFREE(MTYPE_ROUTE_MAP_C
OMPILED,rule);}staticstructroute_map_rule_cmdroute_match_ip_next_hop_prefix_list
_cmd={"ipnext-hopprefix-list",route_match_ip_next_hop_prefix_list,route_match_ip
_next_hop_prefix_list_compile,route_match_ip_next_hop_prefix_list_free};/*`match
ipaddressIP_ACCESS_LIST'*//*Matchfunctionshouldreturn1ifmatchissuccesselsereturn
zero.*/staticroute_map_result_troute_match_ip_address(void*rule,structprefix*pre
fix,route_map_object_ttype,void*object){structaccess_list*alist;if(type==RMAP_ZE
BRA){alist=access_list_lookup(AFI_IP,(char*)rule);if(alist==NULL)returnRMAP_NOMA
TCH;return(access_list_apply(alist,prefix)==FILTER_DENY?RMAP_NOMATCH:RMAP_MATCH)
;}returnRMAP_NOMATCH;}/*Routemap`ipaddress'matchstatement.`arg'shouldbeaccess-li
stname.*/staticvoid*route_match_ip_address_compile(constchar*arg){returnXSTRDUP(
MTYPE_ROUTE_MAP_COMPILED,arg);}/*Freeroutemap'scompiled`ipaddress'value.*/static
voidroute_match_ip_address_free(void*rule){XFREE(MTYPE_ROUTE_MAP_COMPILED,rule);
}/*Routemapcommandsforipaddressmatching.*/staticstructroute_map_rule_cmdroute_ma
tch_ip_address_cmd={"ipaddress",route_match_ip_address,route_match_ip_address_co
mpile,route_match_ip_address_free};/*`matchipaddressprefix-listPREFIX_LIST'*/sta
ticroute_map_result_troute_match_ip_address_prefix_list(void*rule,structprefix*p
refix,route_map_object_ttype,void*object){structprefix_list*plist;if(type==RMAP_
ZEBRA){plist=prefix_list_lookup(AFI_IP,(char*)rule);if(plist==NULL)returnRMAP_NO
MATCH;return(prefix_list_apply(plist,prefix)==PREFIX_DENY?RMAP_NOMATCH:RMAP_MATC
H);}returnRMAP_NOMATCH;}staticvoid*route_match_ip_address_prefix_list_compile(co
nstchar*arg){returnXSTRDUP(MTYPE_ROUTE_MAP_COMPILED,arg);}staticvoidroute_match_
ip_address_prefix_list_free(void*rule){XFREE(MTYPE_ROUTE_MAP_COMPILED,rule);}sta
ticstructroute_map_rule_cmdroute_match_ip_address_prefix_list_cmd={"ipaddresspre
fix-list",route_match_ip_address_prefix_list,route_match_ip_address_prefix_list_
compile,route_match_ip_address_prefix_list_free};/*`matchipaddressprefix-lenPREF
IXLEN'*/staticroute_map_result_troute_match_address_prefix_len(void*rule,structp
refix*prefix,route_map_object_ttype,void*object){uint32_t*prefixlen=(uint32_t*)r
ule;if(type==RMAP_ZEBRA){return((prefix->prefixlen==*prefixlen)?RMAP_MATCH:RMAP_
NOMATCH);}returnRMAP_NOMATCH;}staticvoid*route_match_address_prefix_len_compile(
constchar*arg){uint32_t*prefix_len;char*endptr=NULL;unsignedlongtmpval;/*prefixl
envalueshoudbeinteger.*/if(!all_digit(arg))returnNULL;errno=0;tmpval=strtoul(arg
,&endptr,10);if(*endptr!='\0'||errno||tmpval>UINT32_MAX)returnNULL;prefix_len=XM
ALLOC(MTYPE_ROUTE_MAP_COMPILED,sizeof(uint32_t));if(!prefix_len)returnprefix_len
;*prefix_len=tmpval;returnprefix_len;}staticvoidroute_match_address_prefix_len_f
ree(void*rule){XFREE(MTYPE_ROUTE_MAP_COMPILED,rule);}staticstructroute_map_rule_
cmdroute_match_ip_address_prefix_len_cmd={"ipaddressprefix-len",route_match_addr
ess_prefix_len,route_match_address_prefix_len_compile,route_match_address_prefix
_len_free};staticstructroute_map_rule_cmdroute_match_ipv6_address_prefix_len_cmd
={"ipv6addressprefix-len",route_match_address_prefix_len,route_match_address_pre
fix_len_compile,route_match_address_prefix_len_free};/*`matchipnexthopprefix-len
PREFIXLEN'*/staticroute_map_result_troute_match_ip_nexthop_prefix_len(void*rule,
structprefix*prefix,route_map_object_ttype,void*object){uint32_t*prefixlen=(uint
32_t*)rule;structnh_rmap_obj*nh_data;structprefix_ipv4p;if(type==RMAP_ZEBRA){nh_
data=(structnh_rmap_obj*)object;if(!nh_data||!nh_data->nexthop)returnRMAP_DENYMA
TCH;switch(nh_data->nexthop->type){caseNEXTHOP_TYPE_IFINDEX:/*Interfaceroutescan
'tmatchipnext-hop*/returnRMAP_NOMATCH;caseNEXTHOP_TYPE_IPV4_IFINDEX:caseNEXTHOP_
TYPE_IPV4:p.family=AF_INET;p.prefix=nh_data->nexthop->gate.ipv4;p.prefixlen=IPV4
_MAX_BITLEN;break;default:returnRMAP_NOMATCH;}return((p.prefixlen==*prefixlen)?R
MAP_MATCH:RMAP_NOMATCH);}returnRMAP_NOMATCH;}staticstructroute_map_rule_cmdroute
_match_ip_nexthop_prefix_len_cmd={"ipnext-hopprefix-len",route_match_ip_nexthop_
prefix_len,route_match_address_prefix_len_compile,/*reuse*/route_match_address_p
refix_len_free/*reuse*/};/*`matchsource-protocolPROTOCOL'*/staticroute_map_resul
t_troute_match_source_protocol(void*rule,structprefix*prefix,route_map_object_tt
ype,void*object){uint32_t*rib_type=(uint32_t*)rule;structnh_rmap_obj*nh_data;if(
type==RMAP_ZEBRA){nh_data=(structnh_rmap_obj*)object;if(!nh_data)returnRMAP_DENY
MATCH;return((nh_data->source_protocol==*rib_type)?RMAP_MATCH:RMAP_NOMATCH);}ret
urnRMAP_NOMATCH;}staticvoid*route_match_source_protocol_compile(constchar*arg){u
int32_t*rib_type;inti;i=proto_name2num(arg);rib_type=XMALLOC(MTYPE_ROUTE_MAP_COM
PILED,sizeof(uint32_t));*rib_type=i;returnrib_type;}staticvoidroute_match_source
_protocol_free(void*rule){XFREE(MTYPE_ROUTE_MAP_COMPILED,rule);}staticstructrout
e_map_rule_cmdroute_match_source_protocol_cmd={"source-protocol",route_match_sou
rce_protocol,route_match_source_protocol_compile,route_match_source_protocol_fre
e};/*`setsrcA.B.C.D'*//*Setsrc.*/staticroute_map_result_troute_set_src(void*rule
,structprefix*prefix,route_map_object_ttype,void*object){structnh_rmap_obj*nh_da
ta;if(type==RMAP_ZEBRA){nh_data=(structnh_rmap_obj*)object;nh_data->nexthop->rma
p_src=*(uniong_addr*)rule;}returnRMAP_OKAY;}/*setsrccompilation.*/staticvoid*rou
te_set_src_compile(constchar*arg){uniong_addrsrc,*psrc;if((inet_pton(AF_INET6,ar
g,&src.ipv6)==1)||(inet_pton(AF_INET,arg,&src.ipv4)==1)){psrc=XMALLOC(MTYPE_ROUT
E_MAP_COMPILED,sizeof(uniong_addr));*psrc=src;returnpsrc;}returnNULL;}/*Freerout
emap'scompiled`setsrc'value.*/staticvoidroute_set_src_free(void*rule){XFREE(MTYP
E_ROUTE_MAP_COMPILED,rule);}/*Setsrcrulestructure.*/staticstructroute_map_rule_c
mdroute_set_src_cmd={"src",route_set_src,route_set_src_compile,route_set_src_fre
e,};staticintzebra_route_map_update_timer(structthread*thread){zebra_t_rmap_upda
te=NULL;if(IS_ZEBRA_DEBUG_EVENT)zlog_debug("Eventdrivenroute-mapupdatetriggered"
);if(IS_ZEBRA_DEBUG_RIB_DETAILED)zlog_debug("%u:Routemapupdate-timerfired,schedu
lingRIBprocessing",VRF_DEFAULT);zebra_import_table_rm_update();rib_update(VRF_DE
FAULT,RIB_UPDATE_RMAP_CHANGE);zebra_evaluate_rnh(0,AF_INET,1,RNH_NEXTHOP_TYPE,NU
LL);zebra_evaluate_rnh(0,AF_INET6,1,RNH_NEXTHOP_TYPE,NULL);return(0);}staticvoid
zebra_route_map_set_delay_timer(uint32_tvalue){zebra_rmap_update_timer=value;if(
!value&&zebra_t_rmap_update){/*Eventdrivenroutemapupdatesisbeingdisabled*//*Butt
here'sapendingtimer.Fireitoffnow*/thread_cancel(zebra_t_rmap_update);zebra_route
_map_update_timer(zebra_t_rmap_update);}}voidzebra_route_map_write_delay_timer(s
tructvty*vty){if(vty&&(zebra_rmap_update_timer!=ZEBRA_RMAP_DEFAULT_UPDATE_TIMER)
)vty_out(vty,"zebraroute-mapdelay-timer%d\n",zebra_rmap_update_timer);return;}ro
ute_map_result_tzebra_route_map_check(intfamily,intrib_type,structprefix*p,struc
tnexthop*nexthop,vrf_id_tvrf_id,route_tag_ttag){structroute_map*rmap=NULL;route_
map_result_tret=RMAP_MATCH;structnh_rmap_objnh_obj;nh_obj.nexthop=nexthop;nh_obj
.vrf_id=vrf_id;nh_obj.source_protocol=rib_type;nh_obj.metric=0;nh_obj.tag=tag;if
(rib_type>=0&&rib_type<ZEBRA_ROUTE_MAX)rmap=route_map_lookup_by_name(proto_rm[fa
mily][rib_type]);if(!rmap&&proto_rm[family][ZEBRA_ROUTE_MAX])rmap=route_map_look
up_by_name(proto_rm[family][ZEBRA_ROUTE_MAX]);if(rmap){ret=route_map_apply(rmap,
p,RMAP_ZEBRA,&nh_obj);}return(ret);}char*zebra_get_import_table_route_map(afi_ta
fi,uint32_ttable){returnzebra_import_table_routemap[afi][table];}voidzebra_add_i
mport_table_route_map(afi_tafi,constchar*rmap_name,uint32_ttable){zebra_import_t
able_routemap[afi][table]=XSTRDUP(MTYPE_ROUTE_MAP_NAME,rmap_name);}voidzebra_del
_import_table_route_map(afi_tafi,uint32_ttable){XFREE(MTYPE_ROUTE_MAP_NAME,zebra
_import_table_routemap[afi][table]);}route_map_result_tzebra_import_table_route_
map_check(intfamily,intre_type,structprefix*p,structnexthop*nexthop,vrf_id_tvrf_
id,route_tag_ttag,constchar*rmap_name){structroute_map*rmap=NULL;route_map_resul
t_tret=RMAP_DENYMATCH;structnh_rmap_objnh_obj;nh_obj.nexthop=nexthop;nh_obj.vrf_
id=vrf_id;nh_obj.source_protocol=re_type;nh_obj.metric=0;nh_obj.tag=tag;if(re_ty
pe>=0&&re_type<ZEBRA_ROUTE_MAX)rmap=route_map_lookup_by_name(rmap_name);if(rmap)
{ret=route_map_apply(rmap,p,RMAP_ZEBRA,&nh_obj);}return(ret);}route_map_result_t
zebra_nht_route_map_check(intfamily,intclient_proto,structprefix*p,structroute_e
ntry*re,structnexthop*nexthop){structroute_map*rmap=NULL;route_map_result_tret=R
MAP_MATCH;structnh_rmap_objnh_obj;nh_obj.nexthop=nexthop;nh_obj.vrf_id=nexthop->
vrf_id;nh_obj.source_protocol=re->type;nh_obj.metric=re->metric;nh_obj.tag=re->t
ag;if(client_proto>=0&&client_proto<ZEBRA_ROUTE_MAX)rmap=route_map_lookup_by_nam
e(nht_rm[family][client_proto]);if(!rmap&&nht_rm[family][ZEBRA_ROUTE_MAX])rmap=r
oute_map_lookup_by_name(nht_rm[family][ZEBRA_ROUTE_MAX]);if(rmap){ret=route_map_
apply(rmap,p,RMAP_ZEBRA,&nh_obj);}return(ret);}staticvoidzebra_route_map_mark_up
date(constchar*rmap_name){/*rmap_update_timerof0meansdon'tdorouteupdates*/if(zeb
ra_rmap_update_timer&&!zebra_t_rmap_update){zebra_t_rmap_update=NULL;thread_add_
timer(zebrad.master,zebra_route_map_update_timer,NULL,zebra_rmap_update_timer,&z
ebra_t_rmap_update);}}staticvoidzebra_route_map_add(constchar*rmap_name){zebra_r
oute_map_mark_update(rmap_name);route_map_notify_dependencies(rmap_name,RMAP_EVE
NT_MATCH_ADDED);}staticvoidzebra_route_map_delete(constchar*rmap_name){zebra_rou
te_map_mark_update(rmap_name);route_map_notify_dependencies(rmap_name,RMAP_EVENT
_MATCH_DELETED);}staticvoidzebra_route_map_event(route_map_event_tevent,constcha
r*rmap_name){zebra_route_map_mark_update(rmap_name);route_map_notify_dependencie
s(rmap_name,RMAP_EVENT_MATCH_ADDED);}/*ipprotocolconfigurationwritefunction*/voi
dzebra_routemap_config_write_protocol(structvty*vty){inti;for(i=0;i<ZEBRA_ROUTE_
MAX;i++){if(proto_rm[AFI_IP][i])vty_out(vty,"ipprotocol%sroute-map%s\n",zebra_ro
ute_string(i),proto_rm[AFI_IP][i]);if(proto_rm[AFI_IP6][i])vty_out(vty,"ipv6prot
ocol%sroute-map%s\n",zebra_route_string(i),proto_rm[AFI_IP6][i]);if(nht_rm[AFI_I
P][i])vty_out(vty,"ipnht%sroute-map%s\n",zebra_route_string(i),nht_rm[AFI_IP][i]
);if(nht_rm[AFI_IP6][i])vty_out(vty,"ipv6nht%sroute-map%s\n",zebra_route_string(
i),nht_rm[AFI_IP6][i]);}if(proto_rm[AFI_IP][ZEBRA_ROUTE_MAX])vty_out(vty,"ipprot
ocol%sroute-map%s\n","any",proto_rm[AFI_IP][ZEBRA_ROUTE_MAX]);if(proto_rm[AFI_IP
6][ZEBRA_ROUTE_MAX])vty_out(vty,"ipv6protocol%sroute-map%s\n","any",proto_rm[AFI
_IP6][ZEBRA_ROUTE_MAX]);if(nht_rm[AFI_IP][ZEBRA_ROUTE_MAX])vty_out(vty,"ipnht%sr
oute-map%s\n","any",nht_rm[AFI_IP][ZEBRA_ROUTE_MAX]);if(nht_rm[AFI_IP6][ZEBRA_RO
UTE_MAX])vty_out(vty,"ipv6nht%sroute-map%s\n","any",nht_rm[AFI_IP6][ZEBRA_ROUTE_
MAX]);if(zebra_rmap_update_timer!=ZEBRA_RMAP_DEFAULT_UPDATE_TIMER)vty_out(vty,"z
ebraroute-mapdelay-timer%d\n",zebra_rmap_update_timer);}voidzebra_route_map_init
(){install_element(CONFIG_NODE,&ip_protocol_cmd);install_element(CONFIG_NODE,&no
_ip_protocol_cmd);install_element(VIEW_NODE,&show_ip_protocol_cmd);install_eleme
nt(CONFIG_NODE,&ipv6_protocol_cmd);install_element(CONFIG_NODE,&no_ipv6_protocol
_cmd);install_element(VIEW_NODE,&show_ipv6_protocol_cmd);install_element(CONFIG_
NODE,&ip_protocol_nht_rmap_cmd);install_element(CONFIG_NODE,&no_ip_protocol_nht_
rmap_cmd);install_element(VIEW_NODE,&show_ip_protocol_nht_cmd);install_element(C
ONFIG_NODE,&ipv6_protocol_nht_rmap_cmd);install_element(CONFIG_NODE,&no_ipv6_pro
tocol_nht_rmap_cmd);install_element(VIEW_NODE,&show_ipv6_protocol_nht_cmd);insta
ll_element(CONFIG_NODE,&zebra_route_map_timer_cmd);install_element(CONFIG_NODE,&
no_zebra_route_map_timer_cmd);route_map_init();route_map_add_hook(zebra_route_ma
p_add);route_map_delete_hook(zebra_route_map_delete);route_map_event_hook(zebra_
route_map_event);route_map_match_interface_hook(generic_match_add);route_map_no_
match_interface_hook(generic_match_delete);route_map_match_ip_address_hook(gener
ic_match_add);route_map_no_match_ip_address_hook(generic_match_delete);route_map
_match_ip_address_prefix_list_hook(generic_match_add);route_map_no_match_ip_addr
ess_prefix_list_hook(generic_match_delete);route_map_match_ip_next_hop_hook(gene
ric_match_add);route_map_no_match_ip_next_hop_hook(generic_match_delete);route_m
ap_match_ip_next_hop_prefix_list_hook(generic_match_add);route_map_no_match_ip_n
ext_hop_prefix_list_hook(generic_match_delete);route_map_match_tag_hook(generic_
match_add);route_map_no_match_tag_hook(generic_match_delete);route_map_install_m
atch(&route_match_tag_cmd);route_map_install_match(&route_match_interface_cmd);r
oute_map_install_match(&route_match_ip_next_hop_cmd);route_map_install_match(&ro
ute_match_ip_next_hop_prefix_list_cmd);route_map_install_match(&route_match_ip_a
ddress_cmd);route_map_install_match(&route_match_ip_address_prefix_list_cmd);rou
te_map_install_match(&route_match_ip_address_prefix_len_cmd);route_map_install_m
atch(&route_match_ipv6_address_prefix_len_cmd);route_map_install_match(&route_ma
tch_ip_nexthop_prefix_len_cmd);route_map_install_match(&route_match_source_proto
col_cmd);/**/route_map_install_set(&route_set_src_cmd);/**/install_element(RMAP_
NODE,&match_ip_nexthop_prefix_len_cmd);install_element(RMAP_NODE,&no_match_ip_ne
xthop_prefix_len_cmd);install_element(RMAP_NODE,&match_ip_address_prefix_len_cmd
);install_element(RMAP_NODE,&match_ipv6_address_prefix_len_cmd);install_element(
RMAP_NODE,&no_match_ipv6_address_prefix_len_cmd);install_element(RMAP_NODE,&no_m
atch_ip_address_prefix_len_cmd);install_element(RMAP_NODE,&match_source_protocol
_cmd);install_element(RMAP_NODE,&no_match_source_protocol_cmd);/**/install_eleme
nt(RMAP_NODE,&set_src_cmd);install_element(RMAP_NODE,&no_set_src_cmd);}