/*KernelroutingtableupdatesusingnetlinkoverGNU/Linuxsystem.*Copyright(C)1997,98,
99KunihiroIshiguro**ThisfileispartofGNUZebra.**GNUZebraisfreesoftware;youcanredi
stributeitand/ormodifyit*underthetermsoftheGNUGeneralPublicLicenseaspublishedbyt
he*FreeSoftwareFoundation;eitherversion2,or(atyouroption)any*laterversion.**GNUZ
ebraisdistributedinthehopethatitwillbeuseful,but*WITHOUTANYWARRANTY;withoutevent
heimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*Gene
ralPublicLicenseformoredetails.**YoushouldhavereceivedacopyoftheGNUGeneralPublic
Licensealong*withthisprogram;seethefileCOPYING;ifnot,writetotheFreeSoftware*Foun
dation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-1301USA*/#include<zebra.h>#in
clude<sys/un.h>/*forsockaddr_un*/#include<net/if.h>#include"vty.h"#include"zebra
/zserv.h"#include"zebra/interface.h"#include"zebra/debug.h"#include"zebra/zebra_
ptm.h"#include"if.h"#include"command.h"#include"stream.h"#include"ptm_lib.h"#inc
lude"network.h"#include"buffer.h"#include"zebra/zebra_ptm_redistribute.h"#includ
e"bfd.h"#include"vrf.h"#include"rib.h"#include"zebra_vrf.h"#include"version.h"#d
efineZEBRA_PTM_RECONNECT_TIME_INITIAL1/*initialreconnectis1s*/#defineZEBRA_PTM_R
ECONNECT_TIME_MAX300#definePTM_MSG_LEN4#definePTM_HEADER_LEN37constcharZEBRA_PTM
_GET_STATUS_CMD[]="get-status";constcharZEBRA_PTM_BFD_START_CMD[]="start-bfd-ses
s";constcharZEBRA_PTM_BFD_STOP_CMD[]="stop-bfd-sess";constcharZEBRA_PTM_BFD_CLIE
NT_REG_CMD[]="reg-bfd-client";constcharZEBRA_PTM_BFD_CLIENT_DEREG_CMD[]="dereg-b
fd-client";constcharZEBRA_PTM_CMD_STR[]="cmd";constcharZEBRA_PTM_CMD_STATUS_STR[
]="cmd_status";constcharZEBRA_PTM_PORT_STR[]="port";constcharZEBRA_PTM_CBL_STR[]
="cblstatus";constcharZEBRA_PTM_PASS_STR[]="pass";constcharZEBRA_PTM_FAIL_STR[]=
"fail";constcharZEBRA_PTM_BFDSTATUS_STR[]="state";constcharZEBRA_PTM_BFDSTATUS_U
P_STR[]="Up";constcharZEBRA_PTM_BFDSTATUS_DOWN_STR[]="Down";constcharZEBRA_PTM_B
FDDEST_STR[]="peer";constcharZEBRA_PTM_BFDSRC_STR[]="local";constcharZEBRA_PTM_B
FDVRF_STR[]="vrf";constcharZEBRA_PTM_INVALID_PORT_NAME[]="N/A";constcharZEBRA_PT
M_INVALID_SRC_IP[]="N/A";constcharZEBRA_PTM_INVALID_VRF[]="N/A";constcharZEBRA_P
TM_BFD_DST_IP_FIELD[]="dstIPaddr";constcharZEBRA_PTM_BFD_SRC_IP_FIELD[]="srcIPad
dr";constcharZEBRA_PTM_BFD_MIN_RX_FIELD[]="requiredMinRx";constcharZEBRA_PTM_BFD
_MIN_TX_FIELD[]="upMinTx";constcharZEBRA_PTM_BFD_DETECT_MULT_FIELD[]="detectMult
";constcharZEBRA_PTM_BFD_MULTI_HOP_FIELD[]="multiHop";constcharZEBRA_PTM_BFD_CLI
ENT_FIELD[]="client";constcharZEBRA_PTM_BFD_SEQID_FIELD[]="seqid";constcharZEBRA
_PTM_BFD_IFNAME_FIELD[]="ifName";constcharZEBRA_PTM_BFD_MAX_HOP_CNT_FIELD[]="max
HopCnt";constcharZEBRA_PTM_BFD_SEND_EVENT[]="sendEvent";constcharZEBRA_PTM_BFD_V
RF_NAME_FIELD[]="vrfName";staticptm_lib_handle_t*ptm_hdl;structzebra_ptm_cbptm_c
b;staticintzebra_ptm_socket_init(void);intzebra_ptm_sock_read(structthread*);sta
ticvoidzebra_ptm_install_commands(void);staticintzebra_ptm_handle_msg_cb(void*ar
g,void*in_ctxt);voidzebra_bfd_peer_replay_req(void);voidzebra_ptm_send_status_re
q(void);voidzebra_ptm_reset_status(intptm_disable);constcharZEBRA_PTM_SOCK_NAME[
]="\0/var/run/ptmd.socket";voidzebra_ptm_init(void){charbuf[64];memset(&ptm_cb,0
,sizeof(structzebra_ptm_cb));ptm_cb.out_data=calloc(1,ZEBRA_PTM_SEND_MAX_SOCKBUF
);if(!ptm_cb.out_data){zlog_warn("%s:Allocationofsenddatafailed",__func__);retur
n;}ptm_cb.in_data=calloc(1,ZEBRA_PTM_MAX_SOCKBUF);if(!ptm_cb.in_data){zlog_warn(
"%s:Allocationofrecvdatafailed",__func__);free(ptm_cb.out_data);return;}ptm_cb.p
id=getpid();zebra_ptm_install_commands();sprintf(buf,"%s",FRR_PTM_NAME);ptm_hdl=
ptm_lib_register(buf,NULL,zebra_ptm_handle_msg_cb,zebra_ptm_handle_msg_cb);ptm_c
b.wb=buffer_new(0);ptm_cb.reconnect_time=ZEBRA_PTM_RECONNECT_TIME_INITIAL;ptm_cb
.ptm_sock=-1;}voidzebra_ptm_finish(void){intproto;for(proto=0;proto<ZEBRA_ROUTE_
MAX;proto++)if(CHECK_FLAG(ptm_cb.client_flags[proto],ZEBRA_PTM_BFD_CLIENT_FLAG_R
EG))zebra_ptm_bfd_client_deregister(proto);buffer_flush_all(ptm_cb.wb,ptm_cb.ptm
_sock);free(ptm_hdl);if(ptm_cb.out_data)free(ptm_cb.out_data);if(ptm_cb.in_data)
free(ptm_cb.in_data);/*Releasethreads.*/if(ptm_cb.t_read)thread_cancel(ptm_cb.t_
read);if(ptm_cb.t_write)thread_cancel(ptm_cb.t_write);if(ptm_cb.t_timer)thread_c
ancel(ptm_cb.t_timer);if(ptm_cb.wb)buffer_free(ptm_cb.wb);if(ptm_cb.ptm_sock>=0)
close(ptm_cb.ptm_sock);}staticintzebra_ptm_flush_messages(structthread*thread){p
tm_cb.t_write=NULL;if(ptm_cb.ptm_sock==-1)return-1;errno=0;switch(buffer_flush_a
vailable(ptm_cb.wb,ptm_cb.ptm_sock)){caseBUFFER_ERROR:zlog_warn("%sptmsocketerro
r:%s",__func__,safe_strerror(errno));close(ptm_cb.ptm_sock);ptm_cb.ptm_sock=-1;z
ebra_ptm_reset_status(0);ptm_cb.t_timer=NULL;thread_add_timer(zebrad.master,zebr
a_ptm_connect,NULL,ptm_cb.reconnect_time,&ptm_cb.t_timer);return(-1);caseBUFFER_
PENDING:ptm_cb.t_write=NULL;thread_add_write(zebrad.master,zebra_ptm_flush_messa
ges,NULL,ptm_cb.ptm_sock,&ptm_cb.t_write);break;caseBUFFER_EMPTY:break;}return(0
);}staticintzebra_ptm_send_message(char*data,intsize){errno=0;switch(buffer_writ
e(ptm_cb.wb,ptm_cb.ptm_sock,data,size)){caseBUFFER_ERROR:zlog_warn("%sptmsockete
rror:%s",__func__,safe_strerror(errno));close(ptm_cb.ptm_sock);ptm_cb.ptm_sock=-
1;zebra_ptm_reset_status(0);ptm_cb.t_timer=NULL;thread_add_timer(zebrad.master,z
ebra_ptm_connect,NULL,ptm_cb.reconnect_time,&ptm_cb.t_timer);return-1;caseBUFFER
_EMPTY:THREAD_OFF(ptm_cb.t_write);break;caseBUFFER_PENDING:thread_add_write(zebr
ad.master,zebra_ptm_flush_messages,NULL,ptm_cb.ptm_sock,&ptm_cb.t_write);break;}
return0;}intzebra_ptm_connect(structthread*t){intinit=0;if(ptm_cb.ptm_sock==-1){
zebra_ptm_socket_init();init=1;}if(ptm_cb.ptm_sock!=-1){if(init){ptm_cb.t_read=N
ULL;thread_add_read(zebrad.master,zebra_ptm_sock_read,NULL,ptm_cb.ptm_sock,&ptm_
cb.t_read);zebra_bfd_peer_replay_req();}zebra_ptm_send_status_req();ptm_cb.recon
nect_time=ZEBRA_PTM_RECONNECT_TIME_INITIAL;}elseif(ptm_cb.reconnect_time<ZEBRA_P
TM_RECONNECT_TIME_MAX){ptm_cb.reconnect_time*=2;if(ptm_cb.reconnect_time>ZEBRA_P
TM_RECONNECT_TIME_MAX)ptm_cb.reconnect_time=ZEBRA_PTM_RECONNECT_TIME_MAX;ptm_cb.
t_timer=NULL;thread_add_timer(zebrad.master,zebra_ptm_connect,NULL,ptm_cb.reconn
ect_time,&ptm_cb.t_timer);}elseif(ptm_cb.reconnect_time>=ZEBRA_PTM_RECONNECT_TIM
E_MAX){ptm_cb.reconnect_time=ZEBRA_PTM_RECONNECT_TIME_INITIAL;}return(errno);}DE
FUN(zebra_ptm_enable,zebra_ptm_enable_cmd,"ptm-enable","Enableneighborcheckwiths
pecifiedtopology\n"){structvrf*vrf;structinterface*ifp;structzebra_if*if_data;pt
m_cb.ptm_enable=ZEBRA_IF_PTM_ENABLE_ON;RB_FOREACH(vrf,vrf_name_head,&vrfs_by_nam
e)FOR_ALL_INTERFACES(vrf,ifp)if(!ifp->ptm_enable){if_data=(structzebra_if*)ifp->
info;if(if_data&&(if_data->ptm_enable==ZEBRA_IF_PTM_ENABLE_UNSPEC)){ifp->ptm_ena
ble=ZEBRA_IF_PTM_ENABLE_ON;}/*Assignadefaultunknownstatus*/ifp->ptm_status=ZEBRA
_PTM_STATUS_UNKNOWN;}zebra_ptm_connect(NULL);returnCMD_SUCCESS;}DEFUN(no_zebra_p
tm_enable,no_zebra_ptm_enable_cmd,"noptm-enable",NO_STR"Enableneighborcheckwiths
pecifiedtopology\n"){ptm_cb.ptm_enable=ZEBRA_IF_PTM_ENABLE_OFF;zebra_ptm_reset_s
tatus(1);returnCMD_SUCCESS;}DEFUN(zebra_ptm_enable_if,zebra_ptm_enable_if_cmd,"p
tm-enable","Enableneighborcheckwithspecifiedtopology\n"){VTY_DECLVAR_CONTEXT(int
erface,ifp);structzebra_if*if_data;intold_ptm_enable;intsend_linkdown=0;if(ifp->
ifindex==IFINDEX_INTERNAL){returnCMD_SUCCESS;}old_ptm_enable=ifp->ptm_enable;ifp
->ptm_enable=ptm_cb.ptm_enable;if(if_is_no_ptm_operative(ifp))send_linkdown=1;if
(!old_ptm_enable&&ptm_cb.ptm_enable){if(!if_is_operative(ifp)&&send_linkdown){if
(IS_ZEBRA_DEBUG_EVENT)zlog_debug("%s:Bringingdowninterface%s\n",__func__,ifp->na
me);if_down(ifp);}}if_data=ifp->info;if_data->ptm_enable=ZEBRA_IF_PTM_ENABLE_UNS
PEC;returnCMD_SUCCESS;}DEFUN(no_zebra_ptm_enable_if,no_zebra_ptm_enable_if_cmd,"
noptm-enable",NO_STR"Enableneighborcheckwithspecifiedtopology\n"){VTY_DECLVAR_CO
NTEXT(interface,ifp);intsend_linkup=0;structzebra_if*if_data;if((ifp->ifindex!=I
FINDEX_INTERNAL)&&(ifp->ptm_enable)){if(!if_is_operative(ifp))send_linkup=1;ifp-
>ptm_enable=ZEBRA_IF_PTM_ENABLE_OFF;if(if_is_no_ptm_operative(ifp)&&send_linkup)
{if(IS_ZEBRA_DEBUG_EVENT)zlog_debug("%s:Bringingupinterface%s\n",__func__,ifp->n
ame);if_up(ifp);}}if_data=ifp->info;if_data->ptm_enable=ZEBRA_IF_PTM_ENABLE_OFF;
returnCMD_SUCCESS;}voidzebra_ptm_write(structvty*vty){if(ptm_cb.ptm_enable)vty_o
ut(vty,"ptm-enable\n");return;}staticintzebra_ptm_socket_init(void){intret;intso
ck;structsockaddr_unaddr;ptm_cb.ptm_sock=-1;sock=socket(PF_UNIX,SOCK_STREAM,0);i
f(sock<0)return-1;if(set_nonblocking(sock)<0){if(IS_ZEBRA_DEBUG_EVENT)zlog_debug
("%s:Unabletosetsocketnonblocking[%s]",__PRETTY_FUNCTION__,safe_strerror(errno))
;close(sock);return-1;}/*Makeserversocket.*/memset(&addr,0,sizeof(structsockaddr
_un));addr.sun_family=AF_UNIX;memcpy(&addr.sun_path,ZEBRA_PTM_SOCK_NAME,sizeof(Z
EBRA_PTM_SOCK_NAME));ret=connect(sock,(structsockaddr*)&addr,sizeof(addr.sun_fam
ily)+sizeof(ZEBRA_PTM_SOCK_NAME)-1);if(ret<0){if(IS_ZEBRA_DEBUG_EVENT)zlog_debug
("%s:Unabletoconnecttosocket%s[%s]",__func__,ZEBRA_PTM_SOCK_NAME,safe_strerror(e
rrno));close(sock);return-1;}ptm_cb.ptm_sock=sock;returnsock;}staticvoidzebra_pt
m_install_commands(void){install_element(CONFIG_NODE,&zebra_ptm_enable_cmd);inst
all_element(CONFIG_NODE,&no_zebra_ptm_enable_cmd);install_element(INTERFACE_NODE
,&zebra_ptm_enable_if_cmd);install_element(INTERFACE_NODE,&no_zebra_ptm_enable_i
f_cmd);}/*BFDsessiongoesdown,sendmessagetotheprotocols.*/staticvoidif_bfd_sessio
n_update(structinterface*ifp,structprefix*dp,structprefix*sp,intstatus,vrf_id_tv
rf_id){if(IS_ZEBRA_DEBUG_EVENT){charbuf[2][INET6_ADDRSTRLEN];if(ifp){zlog_debug(
"MESSAGE:ZEBRA_INTERFACE_BFD_DEST_UPDATE%s/%don%s""%sevent",inet_ntop(dp->family
,&dp->u.prefix,buf[0],INET6_ADDRSTRLEN),dp->prefixlen,ifp->name,bfd_get_status_s
tr(status));}else{zlog_debug("MESSAGE:ZEBRA_INTERFACE_BFD_DEST_UPDATE%s/%d""with
src%s/%dandvrf%u%sevent",inet_ntop(dp->family,&dp->u.prefix,buf[0],INET6_ADDRSTR
LEN),dp->prefixlen,inet_ntop(sp->family,&sp->u.prefix,buf[1],INET6_ADDRSTRLEN),s
p->prefixlen,vrf_id,bfd_get_status_str(status));}}zebra_interface_bfd_update(ifp
,dp,sp,status,vrf_id);}staticintzebra_ptm_handle_bfd_msg(void*arg,void*in_ctxt,s
tructinterface*ifp){charbfdst_str[32];chardest_str[64];charsrc_str[64];charvrf_s
tr[64];structprefixdest_prefix;structprefixsrc_prefix;vrf_id_tvrf_id;ptm_lib_fin
d_key_in_msg(in_ctxt,ZEBRA_PTM_BFDSTATUS_STR,bfdst_str);if(bfdst_str[0]=='\0'){r
eturn-1;}ptm_lib_find_key_in_msg(in_ctxt,ZEBRA_PTM_BFDDEST_STR,dest_str);if(dest
_str[0]=='\0'){zlog_debug("%s:Key%snotfoundinPTMmsg",__func__,ZEBRA_PTM_BFDDEST_
STR);return-1;}ptm_lib_find_key_in_msg(in_ctxt,ZEBRA_PTM_BFDSRC_STR,src_str);if(
src_str[0]=='\0'){zlog_debug("%s:Key%snotfoundinPTMmsg",__func__,ZEBRA_PTM_BFDSR
C_STR);return-1;}ptm_lib_find_key_in_msg(in_ctxt,ZEBRA_PTM_BFDVRF_STR,vrf_str);i
f(vrf_str[0]=='\0'){zlog_debug("%s:Key%snotfoundinPTMmsg",__func__,ZEBRA_PTM_BFD
VRF_STR);return-1;}if(IS_ZEBRA_DEBUG_EVENT)zlog_debug("%s:RecvPort[%s]bfdstatus[
%s]vrf[%s]""peer[%s]local[%s]",__func__,ifp?ifp->name:"N/A",bfdst_str,vrf_str,de
st_str,src_str);if(str2prefix(dest_str,&dest_prefix)==0){zlog_err("%s:Peeraddr%s
notfound",__func__,dest_str);return-1;}memset(&src_prefix,0,sizeof(structprefix)
);if(strcmp(ZEBRA_PTM_INVALID_SRC_IP,src_str)){if(str2prefix(src_str,&src_prefix
)==0){zlog_err("%s:Localaddr%snotfound",__func__,src_str);return-1;}}if(!strcmp(
ZEBRA_PTM_INVALID_VRF,vrf_str)&&ifp){vrf_id=ifp->vrf_id;}else{vrf_id=vrf_name_to
_id(vrf_str);}if(!strcmp(bfdst_str,ZEBRA_PTM_BFDSTATUS_DOWN_STR)){if_bfd_session
_update(ifp,&dest_prefix,&src_prefix,BFD_STATUS_DOWN,vrf_id);}else{if_bfd_sessio
n_update(ifp,&dest_prefix,&src_prefix,BFD_STATUS_UP,vrf_id);}return0;}staticintz
ebra_ptm_handle_cbl_msg(void*arg,void*in_ctxt,structinterface*ifp,char*cbl_str){
intsend_linkup=0;if(IS_ZEBRA_DEBUG_EVENT)zlog_debug("%s:RecvPort[%s]cblstatus[%s
]",__func__,ifp->name,cbl_str);if(!strcmp(cbl_str,ZEBRA_PTM_PASS_STR)&&(ifp->ptm
_status!=ZEBRA_PTM_STATUS_UP)){if(ifp->ptm_status==ZEBRA_PTM_STATUS_DOWN)send_li
nkup=1;ifp->ptm_status=ZEBRA_PTM_STATUS_UP;if(ifp->ptm_enable&&if_is_no_ptm_oper
ative(ifp)&&send_linkup)if_up(ifp);}elseif(!strcmp(cbl_str,ZEBRA_PTM_FAIL_STR)&&
(ifp->ptm_status!=ZEBRA_PTM_STATUS_DOWN)){ifp->ptm_status=ZEBRA_PTM_STATUS_DOWN;
if(ifp->ptm_enable&&if_is_no_ptm_operative(ifp))if_down(ifp);}return0;}/**zebra_
ptm_handle_msg_cb-Thepurposeofthiscallbackfunctionistohandle*allthecommandrespon
sesandnotificationsreceivedfromPTM.**Commandresponses:Uponestablishingconnection
withPTM,Zebrarequests*statusofallinterfacesusing'get-status'commandifglobalptm-e
nable*knobisenabled.Asaresponsetotheget-statuscommandPTMsendsstatus*ofalltheinte
rfacesascommandresponses.Allothertypeofcommand*responseswithcmd_statuskeywordare
dropped.Thesolepurposeof*registeringthisfunctionascallbackforthecommandresponses
isto*handletheresponsestoget-statuscommand.**Notifications:CablestatusandBFDsess
ionstatuschangesaresentas*notificationsbyPTM.So,thisfunctionisalsothecallbackfun
ctionfor*processingallthenotificationsfromthePTM.**/staticintzebra_ptm_handle_ms
g_cb(void*arg,void*in_ctxt){structinterface*ifp=NULL;charport_str[128];charcbl_s
tr[32];charcmd_status_str[32];ptm_lib_find_key_in_msg(in_ctxt,ZEBRA_PTM_CMD_STAT
US_STR,cmd_status_str);/*Dropcommandresponsemessages*/if(cmd_status_str[0]!='\0'
){return0;}ptm_lib_find_key_in_msg(in_ctxt,ZEBRA_PTM_PORT_STR,port_str);if(port_
str[0]=='\0'){zlog_debug("%s:Key%snotfoundinPTMmsg",__func__,ZEBRA_PTM_PORT_STR)
;return-1;}if(strcmp(ZEBRA_PTM_INVALID_PORT_NAME,port_str)){ifp=if_lookup_by_nam
e_all_vrf(port_str);if(!ifp){zlog_err("%s:%snotfoundininterfacelist",__func__,po
rt_str);return-1;}}ptm_lib_find_key_in_msg(in_ctxt,ZEBRA_PTM_CBL_STR,cbl_str);if
(cbl_str[0]=='\0'){returnzebra_ptm_handle_bfd_msg(arg,in_ctxt,ifp);}else{if(ifp)
{returnzebra_ptm_handle_cbl_msg(arg,in_ctxt,ifp,cbl_str);}else{return-1;}}}intze
bra_ptm_sock_read(structthread*thread){intsock,done=0;intrc;errno=0;sock=THREAD_
FD(thread);if(sock==-1)return-1;/*PTMcommunicatesinCSVformat*/while(!done){rc=pt
m_lib_process_msg(ptm_hdl,sock,ptm_cb.in_data,ZEBRA_PTM_MAX_SOCKBUF,NULL);if(rc<
=0)break;}if(rc<=0){if(((rc==0)&&!errno)||(errno&&(errno!=EWOULDBLOCK)&&(errno!=
EAGAIN))){zlog_warn("%sroutingsocketerror:%s(%d)bytes%d",__func__,safe_strerror(
errno),errno,rc);close(ptm_cb.ptm_sock);ptm_cb.ptm_sock=-1;zebra_ptm_reset_statu
s(0);ptm_cb.t_timer=NULL;thread_add_timer(zebrad.master,zebra_ptm_connect,NULL,p
tm_cb.reconnect_time,&ptm_cb.t_timer);return(-1);}}ptm_cb.t_read=NULL;thread_add
_read(zebrad.master,zebra_ptm_sock_read,NULL,ptm_cb.ptm_sock,&ptm_cb.t_read);ret
urn0;}/*BFDpeer/dstregister/update*/voidzebra_ptm_bfd_dst_register(ZAPI_HANDLER_
ARGS){structstream*s;structprefixsrc_p;structprefixdst_p;uint8_tmulti_hop;uint8_
tmulti_hop_cnt;uint8_tdetect_mul;unsignedintmin_rx_timer;unsignedintmin_tx_timer
;charif_name[INTERFACE_NAMSIZ];uint8_tlen;void*out_ctxt;charbuf[INET6_ADDRSTRLEN
];chartmp_buf[64];intdata_len=ZEBRA_PTM_SEND_MAX_SOCKBUF;unsignedintpid;if(hdr->
command==ZEBRA_BFD_DEST_UPDATE)client->bfd_peer_upd8_cnt++;elseclient->bfd_peer_
add_cnt++;if(IS_ZEBRA_DEBUG_EVENT)zlog_debug("bfd_dst_registermsgfromclient%s:le
ngth=%d",zebra_route_string(client->proto),hdr->length);if(ptm_cb.ptm_sock==-1){
ptm_cb.t_timer=NULL;thread_add_timer(zebrad.master,zebra_ptm_connect,NULL,ptm_cb
.reconnect_time,&ptm_cb.t_timer);return;}ptm_lib_init_msg(ptm_hdl,0,PTMLIB_MSG_T
YPE_CMD,NULL,&out_ctxt);sprintf(tmp_buf,"%s",ZEBRA_PTM_BFD_START_CMD);ptm_lib_ap
pend_msg(ptm_hdl,out_ctxt,ZEBRA_PTM_CMD_STR,tmp_buf);sprintf(tmp_buf,"%s",zebra_
route_string(client->proto));ptm_lib_append_msg(ptm_hdl,out_ctxt,ZEBRA_PTM_BFD_C
LIENT_FIELD,tmp_buf);s=msg;STREAM_GETL(s,pid);sprintf(tmp_buf,"%d",pid);ptm_lib_
append_msg(ptm_hdl,out_ctxt,ZEBRA_PTM_BFD_SEQID_FIELD,tmp_buf);STREAM_GETW(s,dst
_p.family);if(dst_p.family==AF_INET)dst_p.prefixlen=IPV4_MAX_BYTELEN;elsedst_p.p
refixlen=IPV6_MAX_BYTELEN;STREAM_GET(&dst_p.u.prefix,s,dst_p.prefixlen);if(dst_p
.family==AF_INET){inet_ntop(AF_INET,&dst_p.u.prefix4,buf,sizeof(buf));ptm_lib_ap
pend_msg(ptm_hdl,out_ctxt,ZEBRA_PTM_BFD_DST_IP_FIELD,buf);}else{inet_ntop(AF_INE
T6,&dst_p.u.prefix6,buf,sizeof(buf));ptm_lib_append_msg(ptm_hdl,out_ctxt,ZEBRA_P
TM_BFD_DST_IP_FIELD,buf);}STREAM_GETL(s,min_rx_timer);sprintf(tmp_buf,"%d",min_r
x_timer);ptm_lib_append_msg(ptm_hdl,out_ctxt,ZEBRA_PTM_BFD_MIN_RX_FIELD,tmp_buf)
;STREAM_GETL(s,min_tx_timer);sprintf(tmp_buf,"%d",min_tx_timer);ptm_lib_append_m
sg(ptm_hdl,out_ctxt,ZEBRA_PTM_BFD_MIN_TX_FIELD,tmp_buf);STREAM_GETC(s,detect_mul
);sprintf(tmp_buf,"%d",detect_mul);ptm_lib_append_msg(ptm_hdl,out_ctxt,ZEBRA_PTM
_BFD_DETECT_MULT_FIELD,tmp_buf);STREAM_GETC(s,multi_hop);if(multi_hop){sprintf(t
mp_buf,"%d",1);ptm_lib_append_msg(ptm_hdl,out_ctxt,ZEBRA_PTM_BFD_MULTI_HOP_FIELD
,tmp_buf);STREAM_GETW(s,src_p.family);if(src_p.family==AF_INET)src_p.prefixlen=I
PV4_MAX_BYTELEN;elsesrc_p.prefixlen=IPV6_MAX_BYTELEN;STREAM_GET(&src_p.u.prefix,
s,src_p.prefixlen);if(src_p.family==AF_INET){inet_ntop(AF_INET,&src_p.u.prefix4,
buf,sizeof(buf));ptm_lib_append_msg(ptm_hdl,out_ctxt,ZEBRA_PTM_BFD_SRC_IP_FIELD,
buf);}else{inet_ntop(AF_INET6,&src_p.u.prefix6,buf,sizeof(buf));ptm_lib_append_m
sg(ptm_hdl,out_ctxt,ZEBRA_PTM_BFD_SRC_IP_FIELD,buf);}STREAM_GETC(s,multi_hop_cnt
);sprintf(tmp_buf,"%d",multi_hop_cnt);ptm_lib_append_msg(ptm_hdl,out_ctxt,ZEBRA_
PTM_BFD_MAX_HOP_CNT_FIELD,tmp_buf);if(zvrf_id(zvrf)!=VRF_DEFAULT)ptm_lib_append_
msg(ptm_hdl,out_ctxt,ZEBRA_PTM_BFD_VRF_NAME_FIELD,zvrf_name(zvrf));}else{if(dst_
p.family==AF_INET6){STREAM_GETW(s,src_p.family);if(src_p.family==AF_INET)src_p.p
refixlen=IPV4_MAX_BYTELEN;elsesrc_p.prefixlen=IPV6_MAX_BYTELEN;STREAM_GET(&src_p
.u.prefix,s,src_p.prefixlen);if(src_p.family==AF_INET){inet_ntop(AF_INET,&src_p.
u.prefix4,buf,sizeof(buf));ptm_lib_append_msg(ptm_hdl,out_ctxt,ZEBRA_PTM_BFD_SRC
_IP_FIELD,buf);}else{inet_ntop(AF_INET6,&src_p.u.prefix6,buf,sizeof(buf));ptm_li
b_append_msg(ptm_hdl,out_ctxt,ZEBRA_PTM_BFD_SRC_IP_FIELD,buf);}}STREAM_GETC(s,le
n);STREAM_GET(if_name,s,len);if_name[len]='\0';ptm_lib_append_msg(ptm_hdl,out_ct
xt,ZEBRA_PTM_BFD_IFNAME_FIELD,if_name);}sprintf(tmp_buf,"%d",1);ptm_lib_append_m
sg(ptm_hdl,out_ctxt,ZEBRA_PTM_BFD_SEND_EVENT,tmp_buf);ptm_lib_complete_msg(ptm_h
dl,out_ctxt,ptm_cb.out_data,&data_len);if(IS_ZEBRA_DEBUG_SEND)zlog_debug("%s:Sen
tmessage(%d)%s",__func__,data_len,ptm_cb.out_data);zebra_ptm_send_message(ptm_cb
.out_data,data_len);return;stream_failure:ptm_lib_cleanup_msg(ptm_hdl,out_ctxt);
}/*BFDpeer/dstderegister*/voidzebra_ptm_bfd_dst_deregister(ZAPI_HANDLER_ARGS){st
ructstream*s;structprefixsrc_p;structprefixdst_p;uint8_tmulti_hop;charif_name[IN
TERFACE_NAMSIZ];uint8_tlen;charbuf[INET6_ADDRSTRLEN];chartmp_buf[64];intdata_len
=ZEBRA_PTM_SEND_MAX_SOCKBUF;void*out_ctxt;unsignedintpid;client->bfd_peer_del_cn
t++;if(IS_ZEBRA_DEBUG_EVENT)zlog_debug("bfd_dst_deregistermsgfromclient%s:length
=%d",zebra_route_string(client->proto),hdr->length);if(ptm_cb.ptm_sock==-1){ptm_
cb.t_timer=NULL;thread_add_timer(zebrad.master,zebra_ptm_connect,NULL,ptm_cb.rec
onnect_time,&ptm_cb.t_timer);return;}ptm_lib_init_msg(ptm_hdl,0,PTMLIB_MSG_TYPE_
CMD,NULL,&out_ctxt);sprintf(tmp_buf,"%s",ZEBRA_PTM_BFD_STOP_CMD);ptm_lib_append_
msg(ptm_hdl,out_ctxt,ZEBRA_PTM_CMD_STR,tmp_buf);sprintf(tmp_buf,"%s",zebra_route
_string(client->proto));ptm_lib_append_msg(ptm_hdl,out_ctxt,ZEBRA_PTM_BFD_CLIENT
_FIELD,tmp_buf);s=msg;STREAM_GETL(s,pid);sprintf(tmp_buf,"%d",pid);ptm_lib_appen
d_msg(ptm_hdl,out_ctxt,ZEBRA_PTM_BFD_SEQID_FIELD,tmp_buf);STREAM_GETW(s,dst_p.fa
mily);if(dst_p.family==AF_INET)dst_p.prefixlen=IPV4_MAX_BYTELEN;elsedst_p.prefix
len=IPV6_MAX_BYTELEN;STREAM_GET(&dst_p.u.prefix,s,dst_p.prefixlen);if(dst_p.fami
ly==AF_INET)inet_ntop(AF_INET,&dst_p.u.prefix4,buf,sizeof(buf));elseinet_ntop(AF
_INET6,&dst_p.u.prefix6,buf,sizeof(buf));ptm_lib_append_msg(ptm_hdl,out_ctxt,ZEB
RA_PTM_BFD_DST_IP_FIELD,buf);STREAM_GETC(s,multi_hop);if(multi_hop){sprintf(tmp_
buf,"%d",1);ptm_lib_append_msg(ptm_hdl,out_ctxt,ZEBRA_PTM_BFD_MULTI_HOP_FIELD,tm
p_buf);STREAM_GETW(s,src_p.family);if(src_p.family==AF_INET)src_p.prefixlen=IPV4
_MAX_BYTELEN;elsesrc_p.prefixlen=IPV6_MAX_BYTELEN;STREAM_GET(&src_p.u.prefix,s,s
rc_p.prefixlen);if(src_p.family==AF_INET)inet_ntop(AF_INET,&src_p.u.prefix4,buf,
sizeof(buf));elseinet_ntop(AF_INET6,&src_p.u.prefix6,buf,sizeof(buf));ptm_lib_ap
pend_msg(ptm_hdl,out_ctxt,ZEBRA_PTM_BFD_SRC_IP_FIELD,buf);if(zvrf_id(zvrf)!=VRF_
DEFAULT)ptm_lib_append_msg(ptm_hdl,out_ctxt,ZEBRA_PTM_BFD_VRF_NAME_FIELD,zvrf_na
me(zvrf));}else{if(dst_p.family==AF_INET6){STREAM_GETW(s,src_p.family);if(src_p.
family==AF_INET)src_p.prefixlen=IPV4_MAX_BYTELEN;elsesrc_p.prefixlen=IPV6_MAX_BY
TELEN;STREAM_GET(&src_p.u.prefix,s,src_p.prefixlen);if(src_p.family==AF_INET){in
et_ntop(AF_INET,&src_p.u.prefix4,buf,sizeof(buf));ptm_lib_append_msg(ptm_hdl,out
_ctxt,ZEBRA_PTM_BFD_SRC_IP_FIELD,buf);}else{inet_ntop(AF_INET6,&src_p.u.prefix6,
buf,sizeof(buf));ptm_lib_append_msg(ptm_hdl,out_ctxt,ZEBRA_PTM_BFD_SRC_IP_FIELD,
buf);}}STREAM_GETC(s,len);STREAM_GET(if_name,s,len);if_name[len]='\0';ptm_lib_ap
pend_msg(ptm_hdl,out_ctxt,ZEBRA_PTM_BFD_IFNAME_FIELD,if_name);}ptm_lib_complete_
msg(ptm_hdl,out_ctxt,ptm_cb.out_data,&data_len);if(IS_ZEBRA_DEBUG_SEND)zlog_debu
g("%s:Sentmessage(%d)%s",__func__,data_len,ptm_cb.out_data);zebra_ptm_send_messa
ge(ptm_cb.out_data,data_len);return;stream_failure:ptm_lib_cleanup_msg(ptm_hdl,o
ut_ctxt);}/*BFDclientregister*/voidzebra_ptm_bfd_client_register(ZAPI_HANDLER_AR
GS){structstream*s;unsignedintpid;void*out_ctxt=NULL;chartmp_buf[64];intdata_len
=ZEBRA_PTM_SEND_MAX_SOCKBUF;client->bfd_client_reg_cnt++;if(IS_ZEBRA_DEBUG_EVENT
)zlog_debug("bfd_client_registermsgfromclient%s:length=%d",zebra_route_string(cl
ient->proto),hdr->length);s=msg;STREAM_GETL(s,pid);if(ptm_cb.ptm_sock==-1){ptm_c
b.t_timer=NULL;thread_add_timer(zebrad.master,zebra_ptm_connect,NULL,ptm_cb.reco
nnect_time,&ptm_cb.t_timer);return;}ptm_lib_init_msg(ptm_hdl,0,PTMLIB_MSG_TYPE_C
MD,NULL,&out_ctxt);sprintf(tmp_buf,"%s",ZEBRA_PTM_BFD_CLIENT_REG_CMD);ptm_lib_ap
pend_msg(ptm_hdl,out_ctxt,ZEBRA_PTM_CMD_STR,tmp_buf);sprintf(tmp_buf,"%s",zebra_
route_string(client->proto));ptm_lib_append_msg(ptm_hdl,out_ctxt,ZEBRA_PTM_BFD_C
LIENT_FIELD,tmp_buf);sprintf(tmp_buf,"%d",pid);ptm_lib_append_msg(ptm_hdl,out_ct
xt,ZEBRA_PTM_BFD_SEQID_FIELD,tmp_buf);ptm_lib_complete_msg(ptm_hdl,out_ctxt,ptm_
cb.out_data,&data_len);if(IS_ZEBRA_DEBUG_SEND)zlog_debug("%s:Sentmessage(%d)%s",
__func__,data_len,ptm_cb.out_data);zebra_ptm_send_message(ptm_cb.out_data,data_l
en);SET_FLAG(ptm_cb.client_flags[client->proto],ZEBRA_PTM_BFD_CLIENT_FLAG_REG);r
eturn;stream_failure:/**IFweeveraddmoreSTREAM_GETXXXfunctionsaftertheout_ctxt*is
allocatedthenweneedtoaddthiscodebackin**if(out_ctxt)*ptm_lib_cleanup_msg(ptm_hdl
,out_ctxt);*/return;}/*BFDclientderegister*/voidzebra_ptm_bfd_client_deregister(
intproto){void*out_ctxt;chartmp_buf[64];intdata_len=ZEBRA_PTM_SEND_MAX_SOCKBUF;i
f(proto!=ZEBRA_ROUTE_OSPF&&proto!=ZEBRA_ROUTE_BGP&&proto!=ZEBRA_ROUTE_OSPF6&&pro
to!=ZEBRA_ROUTE_PIM)return;if(IS_ZEBRA_DEBUG_EVENT)zlog_err("bfd_client_deregist
ermsgforclient%s",zebra_route_string(proto));if(ptm_cb.ptm_sock==-1){ptm_cb.t_ti
mer=NULL;thread_add_timer(zebrad.master,zebra_ptm_connect,NULL,ptm_cb.reconnect_
time,&ptm_cb.t_timer);return;}ptm_lib_init_msg(ptm_hdl,0,PTMLIB_MSG_TYPE_CMD,NUL
L,&out_ctxt);sprintf(tmp_buf,"%s",ZEBRA_PTM_BFD_CLIENT_DEREG_CMD);ptm_lib_append
_msg(ptm_hdl,out_ctxt,ZEBRA_PTM_CMD_STR,tmp_buf);sprintf(tmp_buf,"%s",zebra_rout
e_string(proto));ptm_lib_append_msg(ptm_hdl,out_ctxt,ZEBRA_PTM_BFD_CLIENT_FIELD,
tmp_buf);ptm_lib_complete_msg(ptm_hdl,out_ctxt,ptm_cb.out_data,&data_len);if(IS_
ZEBRA_DEBUG_SEND)zlog_debug("%s:Sentmessage(%d)%s",__func__,data_len,ptm_cb.out_
data);zebra_ptm_send_message(ptm_cb.out_data,data_len);UNSET_FLAG(ptm_cb.client_
flags[proto],ZEBRA_PTM_BFD_CLIENT_FLAG_REG);}intzebra_ptm_get_enable_state(void)
{returnptm_cb.ptm_enable;}/**zebra_ptm_get_status_str-Convertstatustoadisplaystr
ing.*/staticconstchar*zebra_ptm_get_status_str(intstatus){switch(status){caseZEB
RA_PTM_STATUS_DOWN:return"fail";caseZEBRA_PTM_STATUS_UP:return"pass";caseZEBRA_P
TM_STATUS_UNKNOWN:default:return"n/a";}}voidzebra_ptm_show_status(structvty*vty,
structinterface*ifp){vty_out(vty,"PTMstatus:");if(ifp->ptm_enable){vty_out(vty,"
%s\n",zebra_ptm_get_status_str(ifp->ptm_status));}else{vty_out(vty,"disabled\n")
;}}voidzebra_ptm_send_status_req(void){void*out_ctxt;intlen=ZEBRA_PTM_SEND_MAX_S
OCKBUF;if(ptm_cb.ptm_enable){ptm_lib_init_msg(ptm_hdl,0,PTMLIB_MSG_TYPE_CMD,NULL
,&out_ctxt);ptm_lib_append_msg(ptm_hdl,out_ctxt,ZEBRA_PTM_CMD_STR,ZEBRA_PTM_GET_
STATUS_CMD);ptm_lib_complete_msg(ptm_hdl,out_ctxt,ptm_cb.out_data,&len);zebra_pt
m_send_message(ptm_cb.out_data,len);}}voidzebra_ptm_reset_status(intptm_disable)
{structvrf*vrf;structinterface*ifp;intsend_linkup;RB_FOREACH(vrf,vrf_id_head,&vr
fs_by_id)FOR_ALL_INTERFACES(vrf,ifp){send_linkup=0;if(ifp->ptm_enable){if(!if_is
_operative(ifp))send_linkup=1;if(ptm_disable)ifp->ptm_enable=ZEBRA_IF_PTM_ENABLE
_OFF;ifp->ptm_status=ZEBRA_PTM_STATUS_UNKNOWN;if(if_is_operative(ifp)&&send_link
up){if(IS_ZEBRA_DEBUG_EVENT)zlog_debug("%s:Bringingupinterface%s",__func__,ifp->
name);if_up(ifp);}}}}voidzebra_ptm_if_init(structzebra_if*zebra_ifp){zebra_ifp->
ptm_enable=ZEBRA_IF_PTM_ENABLE_UNSPEC;}voidzebra_ptm_if_set_ptm_state(structinte
rface*ifp,structzebra_if*zebra_ifp){if(zebra_ifp&&zebra_ifp->ptm_enable!=ZEBRA_I
F_PTM_ENABLE_UNSPEC)ifp->ptm_enable=zebra_ifp->ptm_enable;}voidzebra_ptm_if_writ
e(structvty*vty,structzebra_if*zebra_ifp){if(zebra_ifp->ptm_enable==ZEBRA_IF_PTM
_ENABLE_OFF)vty_out(vty,"noptm-enable\n");}