/**ZebraVrfHeader*Copyright(C)2016CumulusNetworks*DonaldSahrp**ThisfileispartofQ
uagga.**Quaggaisfreesoftware;youcanredistributeitand/ormodifyit*underthetermsoft
heGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eitherversion2,
or(atyouroption)any*laterversion.**Quaggaisdistributedinthehopethatitwillbeusefu
l,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNES
SFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldh
avereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPY
ING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,
MA02110-1301USA*/#if!defined(__ZEBRA_VRF_H__)#define__ZEBRA_VRF_H__#include<zebr
a/zebra_ns.h>#include<zebra/zebra_pw.h>#include<lib/vxlan.h>/*MPLS(SegmentRoutin
g)globalblock*/typedefstructmpls_srgb_t_{uint32_tstart_label;uint32_tend_label;}
mpls_srgb_t;/*Routingtableinstance.*/structzebra_vrf{/*Backpointer*/structvrf*vr
f;/*Description.*/char*desc;/*FIBidentifier.*/uint8_tfib_id;/*Flags.*/uint16_tfl
ags;#defineZEBRA_VRF_RIB_SCHEDULED(1<<0)#defineZEBRA_VRF_RETAIN(2<<0)uint32_ttab
le_id;/*Routingtable.*/structroute_table*table[AFI_MAX][SAFI_MAX];/*Staticroutec
onfiguration.*/structroute_table*stable[AFI_MAX][SAFI_MAX];/*RecursiveNexthoptab
le*/structroute_table*rnh_table[AFI_MAX];/*Importchecktable(usedmostlybyBGP*/str
uctroute_table*import_check_table[AFI_MAX];/*2ndpointertypeusedprimarilytoquella
warningon*ALL_LIST_ELEMENTS_RO*/structlist_rid_all_sorted_list;structlist_rid_lo
_sorted_list;structlist*rid_all_sorted_list;structlist*rid_lo_sorted_list;struct
prefixrid_user_assigned;/**Backpointertotheowningnamespace.*/structzebra_ns*zns;
/*MPLSLabeltohandleL3VPN<->vrfpopping*/mpls_label_tlabel[AFI_MAX];/*MPLSstaticLS
Pconfigtable*/structhash*slsp_table;/*MPLSlabelforwardingtable*/structhash*lsp_t
able;/*MPLSFECbindingtable*/structroute_table*fec_table[AFI_MAX];/*MPLSSegmentRo
utingGlobalblock*/mpls_srgb_tmpls_srgb;/*Pseudowires.*/structzebra_pw_headpseudo
wires;structzebra_static_pw_headstatic_pseudowires;/*MPLSprocessingflags*/uint16
_tmpls_flags;#defineMPLS_FLAG_SCHEDULE_LSPS(1<<0)/**VNIhashtable(forEVPN).Onlyin
defaultinstance.*/structhash*vni_table;/**WhetherEVPNisenabledornot.Onlyindefaul
tinstance.*/intadvertise_all_vni;/**Whetherweareadvertisingg/wmacipinEVPNornot.*
Onlyindefaultinstance.*/intadvertise_gw_macip;/*l3-vniinfo*/vni_tl3vni;/*RouteIn
stalls*/uint64_tinstalls;uint64_tremovals;uint64_tneigh_updates;uint64_tlsp_inst
alls;uint64_tlsp_removals;};staticinlinevrf_id_tzvrf_id(structzebra_vrf*zvrf){if
(!zvrf||!zvrf->vrf)returnVRF_UNKNOWN;returnzvrf->vrf->vrf_id;}staticinlineconstc
har*zvrf_ns_name(structzebra_vrf*zvrf){if(!zvrf->vrf||!zvrf->vrf->ns_ctxt)return
NULL;returnns_get_name((structns*)zvrf->vrf->ns_ctxt);}staticinlineconstchar*zvr
f_name(structzebra_vrf*zvrf){returnzvrf->vrf->name;}staticinlineboolzvrf_is_acti
ve(structzebra_vrf*zvrf){returnzvrf->vrf->status&VRF_ACTIVE;}structroute_table*z
ebra_vrf_table_with_table_id(afi_tafi,safi_tsafi,vrf_id_tvrf_id,uint32_ttable_id
);externvoidzebra_vrf_update_all(structzserv*client);externstructzebra_vrf*zebra
_vrf_lookup_by_id(vrf_id_tvrf_id);externstructzebra_vrf*zebra_vrf_lookup_by_name
(constchar*);externstructzebra_vrf*zebra_vrf_alloc(void);externstructroute_table
*zebra_vrf_table(afi_t,safi_t,vrf_id_t);externstructroute_table*zebra_vrf_static
_table(afi_t,safi_t,structzebra_vrf*zvrf);externstructroute_table*zebra_vrf_othe
r_route_table(afi_tafi,uint32_ttable_id,vrf_id_tvrf_id);externintzebra_vrf_has_c
onfig(structzebra_vrf*zvrf);externvoidzebra_vrf_init(void);externvoidzebra_rtabl
e_node_cleanup(structroute_table*table,structroute_node*node);#endif/*ZEBRA_VRF_
H*/