/**MainimplementationfileforinterfacetoForwardingPlaneManager.**Copyright(C)2012
byOpenSourceRouting.*Copyright(C)2012byInternetSystemsConsortium,Inc.("ISC")**Th
isfileispartofGNUZebra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodify
it*underthetermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundat
ion;eitherversion2,or(atyouroption)any*laterversion.**GNUZebraisdistributedinthe
hopethatitwillbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*ME
RCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformor
edetails.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisp
rogram;seethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51Franklin
St,FifthFloor,Boston,MA02110-1301USA*/#include<zebra.h>#include"log.h"#include"l
ibfrr.h"#include"stream.h"#include"thread.h"#include"network.h"#include"command.
h"#include"version.h"#include"zebra/rib.h"#include"zebra/zserv.h"#include"zebra/
zebra_ns.h"#include"zebra/zebra_vrf.h"#include"fpm/fpm.h"#include"zebra_fpm_priv
ate.h"/**IntervalatwhichweattempttoconnecttotheFPM.*/#defineZFPM_CONNECT_RETRY_I
VL5/**Sizesofoutgoingandincomingstreambuffersforwriting/reading*FPMmessages.*/#d
efineZFPM_OBUF_SIZE(2*FPM_MAX_MSG_LEN)#defineZFPM_IBUF_SIZE(FPM_MAX_MSG_LEN)/**T
hemaximumnumberoftimestheFPMsocketwritecallbackcancall*'write'beforeityields.*/#
defineZFPM_MAX_WRITES_PER_RUN10/**Intervaloverwhichwecollectstatistics.*/#define
ZFPM_STATS_IVL_SECS10/**Structurethatholdsstateforiteratingoverallroute_node*str
ucturesthatarecandidatesforbeingcommunicatedtotheFPM.*/typedefstructzfpm_rnodes_
iter_t_{rib_tables_iter_ttables_iter;route_table_iter_titer;}zfpm_rnodes_iter_t;
/**Statistics.*/typedefstructzfpm_stats_t_{unsignedlongconnect_calls;unsignedlon
gconnect_no_sock;unsignedlongread_cb_calls;unsignedlongwrite_cb_calls;unsignedlo
ngwrite_calls;unsignedlongpartial_writes;unsignedlongmax_writes_hit;unsignedlong
t_write_yields;unsignedlongnop_deletes_skipped;unsignedlongroute_adds;unsignedlo
ngroute_dels;unsignedlongupdates_triggered;unsignedlongredundant_triggers;unsign
edlongdests_del_after_update;unsignedlongt_conn_down_starts;unsignedlongt_conn_d
own_dests_processed;unsignedlongt_conn_down_yields;unsignedlongt_conn_down_finis
hes;unsignedlongt_conn_up_starts;unsignedlongt_conn_up_dests_processed;unsignedl
ongt_conn_up_yields;unsignedlongt_conn_up_aborts;unsignedlongt_conn_up_finishes;
}zfpm_stats_t;/**StatesfortheFPMstatemachine.*/typedefenum{/**Inthisstateweareno
tyetreadytoconnecttotheFPM.This*canhappenwhenthismoduleisdisabled,orifwe'reclean
ingup*afteraconnectionhasgonedown.*/ZFPM_STATE_IDLE,/**ReadytotalktotheFPMandper
iodicallytryingtoconnectto*it.*/ZFPM_STATE_ACTIVE,/**InthemiddleofbringingupaTCP
connection.Specifically,*waitingforaconnect()calltocompleteasynchronously.*/ZFPM
_STATE_CONNECTING,/**TCPconnectiontotheFPMisup.*/ZFPM_STATE_ESTABLISHED}zfpm_sta
te_t;/**MessageformattobeusedtocommunicatewiththeFPM.*/typedefenum{ZFPM_MSG_FORM
AT_NONE,ZFPM_MSG_FORMAT_NETLINK,ZFPM_MSG_FORMAT_PROTOBUF,}zfpm_msg_format_e;/**G
lobals.*/typedefstructzfpm_glob_t_{/**TrueiftheFPMmodulehasbeenenabled.*/intenab
led;/**Messageformattobeusedtocommunicatewiththefpm.*/zfpm_msg_format_emessage_f
ormat;structthread_master*master;zfpm_state_tstate;in_addr_tfpm_server;/**Porton
whichtheFPMisrunning.*/intfpm_port;/**Listofrib_dest_tstructurestobeprocessed*/T
AILQ_HEAD(zfpm_dest_q,rib_dest_t_)dest_q;/**StreamsockettotheFPM.*/intsock;/**Bu
ffersformessagesto/fromtheFPM.*/structstream*obuf;structstream*ibuf;/**Threadsfo
rI/O.*/structthread*t_connect;structthread*t_write;structthread*t_read;/**Thread
tocleanupaftertheTCPconnectiontotheFPMgoesdown*andthestatethatbelongstoit.*/stru
ctthread*t_conn_down;struct{zfpm_rnodes_iter_titer;}t_conn_down_state;/**Threadt
otakeactionsoncetheTCPconntotheFPMcomesup,and*thestatethatbelongstoit.*/structth
read*t_conn_up;struct{zfpm_rnodes_iter_titer;}t_conn_up_state;unsignedlongconnec
t_calls;time_tlast_connect_call_time;/**Statsfromthestartofthecurrentstatisticsi
ntervalupto*now.Thesearethecounterswetypicallyupdateinthecode.*/zfpm_stats_tstat
s;/**Statisticsthatweregatheredinthelastcollectioninterval.*/zfpm_stats_tlast_iv
l_stats;/**Cumulativestatsfromthelastcleartothestartofthecurrent*statisticsinter
val.*/zfpm_stats_tcumulative_stats;/**Statsintervaltimer.*/structthread*t_stats;
/**Ifnon-zero,thelasttimewhenstatisticswerecleared.*/time_tlast_stats_clear_time
;}zfpm_glob_t;staticzfpm_glob_tzfpm_glob_space;staticzfpm_glob_t*zfpm_g=&zfpm_gl
ob_space;staticintzfpm_trigger_update(structroute_node*rn,constchar*reason);stat
icintzfpm_read_cb(structthread*thread);staticintzfpm_write_cb(structthread*threa
d);staticvoidzfpm_set_state(zfpm_state_tstate,constchar*reason);staticvoidzfpm_s
tart_connect_timer(constchar*reason);staticvoidzfpm_start_stats_timer(void);/**z
fpm_thread_should_yield*/staticinlineintzfpm_thread_should_yield(structthread*t)
{returnthread_should_yield(t);}/**zfpm_state_to_str*/staticconstchar*zfpm_state_
to_str(zfpm_state_tstate){switch(state){caseZFPM_STATE_IDLE:return"idle";caseZFP
M_STATE_ACTIVE:return"active";caseZFPM_STATE_CONNECTING:return"connecting";caseZ
FPM_STATE_ESTABLISHED:return"established";default:return"unknown";}}/**zfpm_get_
elapsed_time**Returnsthetimeelapsed(inseconds)sincethegiventime.*/statictime_tzf
pm_get_elapsed_time(time_treference){time_tnow;now=monotime(NULL);if(now<referen
ce){assert(0);return0;}returnnow-reference;}/**zfpm_rnodes_iter_init*/staticinli
nevoidzfpm_rnodes_iter_init(zfpm_rnodes_iter_t*iter){memset(iter,0,sizeof(*iter)
);rib_tables_iter_init(&iter->tables_iter);/**Thisisahack,butitmakesimplementing
'next'easierby*ensuringthatroute_table_iter_next()willreturnNULLthefirst*timewec
allit.*/route_table_iter_init(&iter->iter,NULL);route_table_iter_cleanup(&iter->
iter);}/**zfpm_rnodes_iter_next*/staticinlinestructroute_node*zfpm_rnodes_iter_n
ext(zfpm_rnodes_iter_t*iter){structroute_node*rn;structroute_table*table;while(1
){rn=route_table_iter_next(&iter->iter);if(rn)returnrn;/**We'vemadeourwaythrough
thistable,gotothenextone.*/route_table_iter_cleanup(&iter->iter);table=rib_table
s_iter_next(&iter->tables_iter);if(!table)returnNULL;route_table_iter_init(&iter
->iter,table);}returnNULL;}/**zfpm_rnodes_iter_pause*/staticinlinevoidzfpm_rnode
s_iter_pause(zfpm_rnodes_iter_t*iter){route_table_iter_pause(&iter->iter);}/**zf
pm_rnodes_iter_cleanup*/staticinlinevoidzfpm_rnodes_iter_cleanup(zfpm_rnodes_ite
r_t*iter){route_table_iter_cleanup(&iter->iter);rib_tables_iter_cleanup(&iter->t
ables_iter);}/**zfpm_stats_init**Initializeastatisticsblock.*/staticinlinevoidzf
pm_stats_init(zfpm_stats_t*stats){memset(stats,0,sizeof(*stats));}/**zfpm_stats_
reset*/staticinlinevoidzfpm_stats_reset(zfpm_stats_t*stats){zfpm_stats_init(stat
s);}/**zfpm_stats_copy*/staticinlinevoidzfpm_stats_copy(constzfpm_stats_t*src,zf
pm_stats_t*dest){memcpy(dest,src,sizeof(*dest));}/**zfpm_stats_compose**Totalupt
hestatisticsintwostatsstructures('s1and's2')and*returntheresultinthethirdargumen
t,'result'.Notethatthe*pointer'result'maybethesameas's1'or's2'.**Forsimplicity,t
heimplementationbelowassumesthatthestats*structureiscomposedentirelyofcounters.T
hiscaneasilybe*changedwhennecessary.*/staticvoidzfpm_stats_compose(constzfpm_sta
ts_t*s1,constzfpm_stats_t*s2,zfpm_stats_t*result){constunsignedlong*p1,*p2;unsig
nedlong*result_p;inti,num_counters;p1=(constunsignedlong*)s1;p2=(constunsignedlo
ng*)s2;result_p=(unsignedlong*)result;num_counters=(sizeof(zfpm_stats_t)/sizeof(
unsignedlong));for(i=0;i<num_counters;i++){result_p[i]=p1[i]+p2[i];}}/**zfpm_rea
d_on*/staticinlinevoidzfpm_read_on(void){assert(!zfpm_g->t_read);assert(zfpm_g->
sock>=0);thread_add_read(zfpm_g->master,zfpm_read_cb,0,zfpm_g->sock,&zfpm_g->t_r
ead);}/**zfpm_write_on*/staticinlinevoidzfpm_write_on(void){assert(!zfpm_g->t_wr
ite);assert(zfpm_g->sock>=0);thread_add_write(zfpm_g->master,zfpm_write_cb,0,zfp
m_g->sock,&zfpm_g->t_write);}/**zfpm_read_off*/staticinlinevoidzfpm_read_off(voi
d){THREAD_READ_OFF(zfpm_g->t_read);}/**zfpm_write_off*/staticinlinevoidzfpm_writ
e_off(void){THREAD_WRITE_OFF(zfpm_g->t_write);}/**zfpm_conn_up_thread_cb**Callba
ckforactionstobetakenwhentheconnectiontotheFPM*comesup.*/staticintzfpm_conn_up_t
hread_cb(structthread*thread){structroute_node*rnode;zfpm_rnodes_iter_t*iter;rib
_dest_t*dest;zfpm_g->t_conn_up=NULL;iter=&zfpm_g->t_conn_up_state.iter;if(zfpm_g
->state!=ZFPM_STATE_ESTABLISHED){zfpm_debug("Connectionnotupanymore,conn_upthrea
daborting");zfpm_g->stats.t_conn_up_aborts++;gotodone;}while((rnode=zfpm_rnodes_
iter_next(iter))){dest=rib_dest_from_rnode(rnode);if(dest){zfpm_g->stats.t_conn_
up_dests_processed++;zfpm_trigger_update(rnode,NULL);}/**Yieldifneedbe.*/if(!zfp
m_thread_should_yield(thread))continue;zfpm_g->stats.t_conn_up_yields++;zfpm_rno
des_iter_pause(iter);zfpm_g->t_conn_up=NULL;thread_add_timer_msec(zfpm_g->master
,zfpm_conn_up_thread_cb,NULL,0,&zfpm_g->t_conn_up);return0;}zfpm_g->stats.t_conn
_up_finishes++;done:zfpm_rnodes_iter_cleanup(iter);return0;}/**zfpm_connection_u
p**CalledwhentheconnectiontotheFPMcomesup.*/staticvoidzfpm_connection_up(constch
ar*detail){assert(zfpm_g->sock>=0);zfpm_read_on();zfpm_write_on();zfpm_set_state
(ZFPM_STATE_ESTABLISHED,detail);/**StartthreadtopushexistingroutestotheFPM.*/ass
ert(!zfpm_g->t_conn_up);zfpm_rnodes_iter_init(&zfpm_g->t_conn_up_state.iter);zfp
m_debug("Startingconn_upthread");zfpm_g->t_conn_up=NULL;thread_add_timer_msec(zf
pm_g->master,zfpm_conn_up_thread_cb,NULL,0,&zfpm_g->t_conn_up);zfpm_g->stats.t_c
onn_up_starts++;}/**zfpm_connect_check**Checkifanasynchronousconnect()totheFPMis
complete.*/staticvoidzfpm_connect_check(void){intstatus;socklen_tslen;intret;zfp
m_read_off();zfpm_write_off();slen=sizeof(status);ret=getsockopt(zfpm_g->sock,SO
L_SOCKET,SO_ERROR,(void*)&status,&slen);if(ret>=0&&status==0){zfpm_connection_up
("asyncconnectcomplete");return;}/**getsockopt()failedorindicatedanerroronthesoc
ket.*/close(zfpm_g->sock);zfpm_g->sock=-1;zfpm_start_connect_timer("getsockopt()
afterasyncconnectfailed");return;}/**zfpm_conn_down_thread_cb**Callbackthatisinv
okedtocleanupstateaftertheTCPconnection*totheFPMgoesdown.*/staticintzfpm_conn_do
wn_thread_cb(structthread*thread){structroute_node*rnode;zfpm_rnodes_iter_t*iter
;rib_dest_t*dest;assert(zfpm_g->state==ZFPM_STATE_IDLE);zfpm_g->t_conn_down=NULL
;iter=&zfpm_g->t_conn_down_state.iter;while((rnode=zfpm_rnodes_iter_next(iter)))
{dest=rib_dest_from_rnode(rnode);if(dest){if(CHECK_FLAG(dest->flags,RIB_DEST_UPD
ATE_FPM)){TAILQ_REMOVE(&zfpm_g->dest_q,dest,fpm_q_entries);}UNSET_FLAG(dest->fla
gs,RIB_DEST_UPDATE_FPM);UNSET_FLAG(dest->flags,RIB_DEST_SENT_TO_FPM);zfpm_g->sta
ts.t_conn_down_dests_processed++;/**Checkifthedestshouldbedeleted.*/rib_gc_dest(
rnode);}/**Yieldifneedbe.*/if(!zfpm_thread_should_yield(thread))continue;zfpm_g-
>stats.t_conn_down_yields++;zfpm_rnodes_iter_pause(iter);zfpm_g->t_conn_down=NUL
L;thread_add_timer_msec(zfpm_g->master,zfpm_conn_down_thread_cb,NULL,0,&zfpm_g->
t_conn_down);return0;}zfpm_g->stats.t_conn_down_finishes++;zfpm_rnodes_iter_clea
nup(iter);/**StarttheprocessofconnectingtotheFPMagain.*/zfpm_start_connect_timer
("cleanupcomplete");return0;}/**zfpm_connection_down**Calledwhentheconnectiontot
heFPMhasgonedown.*/staticvoidzfpm_connection_down(constchar*detail){if(!detail)d
etail="unknown";assert(zfpm_g->state==ZFPM_STATE_ESTABLISHED);zlog_info("connect
iontotheFPMhasgonedown:%s",detail);zfpm_read_off();zfpm_write_off();stream_reset
(zfpm_g->ibuf);stream_reset(zfpm_g->obuf);if(zfpm_g->sock>=0){close(zfpm_g->sock
);zfpm_g->sock=-1;}/**Startthreadtocleanupstateaftertheconnectiongoesdown.*/asse
rt(!zfpm_g->t_conn_down);zfpm_debug("Startingconn_downthread");zfpm_rnodes_iter_
init(&zfpm_g->t_conn_down_state.iter);zfpm_g->t_conn_down=NULL;thread_add_timer_
msec(zfpm_g->master,zfpm_conn_down_thread_cb,NULL,0,&zfpm_g->t_conn_down);zfpm_g
->stats.t_conn_down_starts++;zfpm_set_state(ZFPM_STATE_IDLE,detail);}/**zfpm_rea
d_cb*/staticintzfpm_read_cb(structthread*thread){size_talready;structstream*ibuf
;uint16_tmsg_len;fpm_msg_hdr_t*hdr;zfpm_g->stats.read_cb_calls++;zfpm_g->t_read=
NULL;/**Checkifasyncconnectisnowdone.*/if(zfpm_g->state==ZFPM_STATE_CONNECTING){
zfpm_connect_check();return0;}assert(zfpm_g->state==ZFPM_STATE_ESTABLISHED);asse
rt(zfpm_g->sock>=0);ibuf=zfpm_g->ibuf;already=stream_get_endp(ibuf);if(already<F
PM_MSG_HDR_LEN){ssize_tnbyte;nbyte=stream_read_try(ibuf,zfpm_g->sock,FPM_MSG_HDR
_LEN-already);if(nbyte==0||nbyte==-1){if(nbyte==-1){charbuffer[1024];sprintf(buf
fer,"closedsocketinread(%d):%s",errno,safe_strerror(errno));zfpm_connection_down
(buffer);}elsezfpm_connection_down("closedsocketinread");return0;}if(nbyte!=(ssi
ze_t)(FPM_MSG_HDR_LEN-already))gotodone;already=FPM_MSG_HDR_LEN;}stream_set_getp
(ibuf,0);hdr=(fpm_msg_hdr_t*)stream_pnt(ibuf);if(!fpm_msg_hdr_ok(hdr)){zfpm_conn
ection_down("invalidmessageheader");return0;}msg_len=fpm_msg_len(hdr);/**Readout
therestofthepacket.*/if(already<msg_len){ssize_tnbyte;nbyte=stream_read_try(ibuf
,zfpm_g->sock,msg_len-already);if(nbyte==0||nbyte==-1){if(nbyte==-1){charbuffer[
1024];sprintf(buffer,"failedtoreadmessage(%d)%s",errno,safe_strerror(errno));zfp
m_connection_down(buffer);}elsezfpm_connection_down("failedtoreadmessage");retur
n0;}if(nbyte!=(ssize_t)(msg_len-already))gotodone;}zfpm_debug("Readoutafullfpmme
ssage");/**Justthrowitawayfornow.*/stream_reset(ibuf);done:zfpm_read_on();return
0;}/**zfpm_writes_pending**ReturnsTRUEifwemayhavesomethingtowritetotheFPM.*/stat
icintzfpm_writes_pending(void){/**Checkifthereisanydataintheoutboundbufferthatha
snot*beenwrittentothesocketyet.*/if(stream_get_endp(zfpm_g->obuf)-stream_get_get
p(zfpm_g->obuf))return1;/**Checkifthereareanyprefixesontheoutboundqueue.*/if(!TA
ILQ_EMPTY(&zfpm_g->dest_q))return1;return0;}/**zfpm_encode_route**Encodeamessage
totheFPMwithinformationaboutthegivenroute.**Returnsthenumberofbyteswrittentotheb
uffer.0oranegative*valueindicatesanerror.*/staticinlineintzfpm_encode_route(rib_
dest_t*dest,structroute_entry*re,char*in_buf,size_tin_buf_len,fpm_msg_type_e*msg
_type){size_tlen;#ifdefHAVE_NETLINKintcmd;#endiflen=0;*msg_type=FPM_MSG_TYPE_NON
E;switch(zfpm_g->message_format){caseZFPM_MSG_FORMAT_PROTOBUF:#ifdefHAVE_PROTOBU
Flen=zfpm_protobuf_encode_route(dest,re,(uint8_t*)in_buf,in_buf_len);*msg_type=F
PM_MSG_TYPE_PROTOBUF;#endifbreak;caseZFPM_MSG_FORMAT_NETLINK:#ifdefHAVE_NETLINK*
msg_type=FPM_MSG_TYPE_NETLINK;cmd=re?RTM_NEWROUTE:RTM_DELROUTE;len=zfpm_netlink_
encode_route(cmd,dest,re,in_buf,in_buf_len);assert(fpm_msg_align(len)==len);*msg
_type=FPM_MSG_TYPE_NETLINK;#endif/*HAVE_NETLINK*/break;default:break;}returnlen;
}/**zfpm_route_for_update**ReturnstherethatistobesenttotheFPMforagivendest.*/str
uctroute_entry*zfpm_route_for_update(rib_dest_t*dest){returndest->selected_fib;}
/**zfpm_build_updates**Processtheoutgoingqueueandwritemessagestotheoutbound*buff
er.*/staticvoidzfpm_build_updates(void){structstream*s;rib_dest_t*dest;unsignedc
har*buf,*data,*buf_end;size_tmsg_len;size_tdata_len;fpm_msg_hdr_t*hdr;structrout
e_entry*re;intis_add,write_msg;fpm_msg_type_emsg_type;s=zfpm_g->obuf;assert(stre
am_empty(s));do{/**Makesurethereisenoughspacetowriteanothermessage.*/if(STREAM_W
RITEABLE(s)<FPM_MAX_MSG_LEN)break;buf=STREAM_DATA(s)+stream_get_endp(s);buf_end=
buf+STREAM_WRITEABLE(s);dest=TAILQ_FIRST(&zfpm_g->dest_q);if(!dest)break;assert(
CHECK_FLAG(dest->flags,RIB_DEST_UPDATE_FPM));hdr=(fpm_msg_hdr_t*)buf;hdr->versio
n=FPM_PROTO_VERSION;data=fpm_msg_data(hdr);re=zfpm_route_for_update(dest);is_add
=re?1:0;write_msg=1;/**Ifthisisaroutedeletion,andwehavenotsenttheroute*to*theFPM
previously,skipit.*/if(!is_add&&!CHECK_FLAG(dest->flags,RIB_DEST_SENT_TO_FPM)){w
rite_msg=0;zfpm_g->stats.nop_deletes_skipped++;}if(write_msg){data_len=zfpm_enco
de_route(dest,re,(char*)data,buf_end-data,&msg_type);assert(data_len);if(data_le
n){hdr->msg_type=msg_type;msg_len=fpm_data_len_to_msg_len(data_len);hdr->msg_len
=htons(msg_len);stream_forward_endp(s,msg_len);if(is_add)zfpm_g->stats.route_add
s++;elsezfpm_g->stats.route_dels++;}}/**Removethedestfromthequeue,andresetthefla
g.*/UNSET_FLAG(dest->flags,RIB_DEST_UPDATE_FPM);TAILQ_REMOVE(&zfpm_g->dest_q,des
t,fpm_q_entries);if(is_add){SET_FLAG(dest->flags,RIB_DEST_SENT_TO_FPM);}else{UNS
ET_FLAG(dest->flags,RIB_DEST_SENT_TO_FPM);}/**Deletethedestinationifnecessary.*/
if(rib_gc_dest(dest->rnode))zfpm_g->stats.dests_del_after_update++;}while(1);}/*
*zfpm_write_cb*/staticintzfpm_write_cb(structthread*thread){structstream*s;intnu
m_writes;zfpm_g->stats.write_cb_calls++;zfpm_g->t_write=NULL;/**Checkifasyncconn
ectisnowdone.*/if(zfpm_g->state==ZFPM_STATE_CONNECTING){zfpm_connect_check();ret
urn0;}assert(zfpm_g->state==ZFPM_STATE_ESTABLISHED);assert(zfpm_g->sock>=0);num_
writes=0;do{intbytes_to_write,bytes_written;s=zfpm_g->obuf;/**Ifthestreamisempty
,tryfillitupwithdata.*/if(stream_empty(s)){zfpm_build_updates();}bytes_to_write=
stream_get_endp(s)-stream_get_getp(s);if(!bytes_to_write)break;bytes_written=wri
te(zfpm_g->sock,stream_pnt(s),bytes_to_write);zfpm_g->stats.write_calls++;num_wr
ites++;if(bytes_written<0){if(ERRNO_IO_RETRY(errno))break;zfpm_connection_down("
failedtowritetosocket");return0;}if(bytes_written!=bytes_to_write){/**Partialwri
te.*/stream_forward_getp(s,bytes_written);zfpm_g->stats.partial_writes++;break;}
/**We'vewrittenouttheentirecontentsofthestream.*/stream_reset(s);if(num_writes>=
ZFPM_MAX_WRITES_PER_RUN){zfpm_g->stats.max_writes_hit++;break;}if(zfpm_thread_sh
ould_yield(thread)){zfpm_g->stats.t_write_yields++;break;}}while(1);if(zfpm_writ
es_pending())zfpm_write_on();return0;}/**zfpm_connect_cb*/staticintzfpm_connect_
cb(structthread*t){intsock,ret;structsockaddr_inserv;zfpm_g->t_connect=NULL;asse
rt(zfpm_g->state==ZFPM_STATE_ACTIVE);sock=socket(AF_INET,SOCK_STREAM,0);if(sock<
0){zfpm_debug("Failedtocreatesocketforconnect():%s",strerror(errno));zfpm_g->sta
ts.connect_no_sock++;return0;}set_nonblocking(sock);/*Makeserversocket.*/memset(
&serv,0,sizeof(serv));serv.sin_family=AF_INET;serv.sin_port=htons(zfpm_g->fpm_po
rt);#ifdefHAVE_STRUCT_SOCKADDR_IN_SIN_LENserv.sin_len=sizeof(structsockaddr_in);
#endif/*HAVE_STRUCT_SOCKADDR_IN_SIN_LEN*/if(!zfpm_g->fpm_server)serv.sin_addr.s_
addr=htonl(INADDR_LOOPBACK);elseserv.sin_addr.s_addr=(zfpm_g->fpm_server);/**Con
necttotheFPM.*/zfpm_g->connect_calls++;zfpm_g->stats.connect_calls++;zfpm_g->las
t_connect_call_time=monotime(NULL);ret=connect(sock,(structsockaddr*)&serv,sizeo
f(serv));if(ret>=0){zfpm_g->sock=sock;zfpm_connection_up("connectsucceeded");ret
urn1;}if(errno==EINPROGRESS){zfpm_g->sock=sock;zfpm_read_on();zfpm_write_on();zf
pm_set_state(ZFPM_STATE_CONNECTING,"asyncconnectinprogress");return0;}zlog_info(
"can'tconnecttoFPM%d:%s",sock,safe_strerror(errno));close(sock);/**Restarttimerf
orretryingconnection.*/zfpm_start_connect_timer("connect()failed");return0;}/**z
fpm_set_state**Movestatemachineintothegivenstate.*/staticvoidzfpm_set_state(zfpm
_state_tstate,constchar*reason){zfpm_state_tcur_state=zfpm_g->state;if(!reason)r
eason="Unknown";if(state==cur_state)return;zfpm_debug("beginningstatetransition%
s->%s.Reason:%s",zfpm_state_to_str(cur_state),zfpm_state_to_str(state),reason);s
witch(state){caseZFPM_STATE_IDLE:assert(cur_state==ZFPM_STATE_ESTABLISHED);break
;caseZFPM_STATE_ACTIVE:assert(cur_state==ZFPM_STATE_IDLE||cur_state==ZFPM_STATE_
CONNECTING);assert(zfpm_g->t_connect);break;caseZFPM_STATE_CONNECTING:assert(zfp
m_g->sock);assert(cur_state==ZFPM_STATE_ACTIVE);assert(zfpm_g->t_read);assert(zf
pm_g->t_write);break;caseZFPM_STATE_ESTABLISHED:assert(cur_state==ZFPM_STATE_ACT
IVE||cur_state==ZFPM_STATE_CONNECTING);assert(zfpm_g->sock);assert(zfpm_g->t_rea
d);assert(zfpm_g->t_write);break;}zfpm_g->state=state;}/**zfpm_calc_connect_dela
y**Returnsthenumberofsecondsafterwhichweshouldattemptto*reconnecttotheFPM.*/stat
iclongzfpm_calc_connect_delay(void){time_telapsed;/**Return0ifthisisourfirstatte
mpttoconnect.*/if(zfpm_g->connect_calls==0){return0;}elapsed=zfpm_get_elapsed_ti
me(zfpm_g->last_connect_call_time);if(elapsed>ZFPM_CONNECT_RETRY_IVL){return0;}r
eturnZFPM_CONNECT_RETRY_IVL-elapsed;}/**zfpm_start_connect_timer*/staticvoidzfpm
_start_connect_timer(constchar*reason){longdelay_secs;assert(!zfpm_g->t_connect)
;assert(zfpm_g->sock<0);assert(zfpm_g->state==ZFPM_STATE_IDLE||zfpm_g->state==ZF
PM_STATE_ACTIVE||zfpm_g->state==ZFPM_STATE_CONNECTING);delay_secs=zfpm_calc_conn
ect_delay();zfpm_debug("schedulingconnectin%ldseconds",delay_secs);thread_add_ti
mer(zfpm_g->master,zfpm_connect_cb,0,delay_secs,&zfpm_g->t_connect);zfpm_set_sta
te(ZFPM_STATE_ACTIVE,reason);}/**zfpm_is_enabled**ReturnsTRUEifthezebraFPMmodule
hasbeenenabled.*/staticinlineintzfpm_is_enabled(void){returnzfpm_g->enabled;}/**
zfpm_conn_is_up**ReturnsTRUEiftheconnectiontotheFPMisup.*/staticinlineintzfpm_co
nn_is_up(void){if(zfpm_g->state!=ZFPM_STATE_ESTABLISHED)return0;assert(zfpm_g->s
ock>=0);return1;}/**zfpm_trigger_update**Thezebracodeinvokesthisfunctiontoindica
tethatweshould*sendanupdatetotheFPMaboutthegivenroute_node.*/staticintzfpm_trigg
er_update(structroute_node*rn,constchar*reason){rib_dest_t*dest;charbuf[PREFIX_S
TRLEN];/**Ignoreiftheconnectionisdown.WewillupdatetheFPMabout*alldestinationsonc
etheconnectioncomesup.*/if(!zfpm_conn_is_up())return0;dest=rib_dest_from_rnode(r
n);if(CHECK_FLAG(dest->flags,RIB_DEST_UPDATE_FPM)){zfpm_g->stats.redundant_trigg
ers++;return0;}if(reason){zfpm_debug("%striggeringupdatetoFPM-Reason:%s",prefix2
str(&rn->p,buf,sizeof(buf)),reason);}SET_FLAG(dest->flags,RIB_DEST_UPDATE_FPM);T
AILQ_INSERT_TAIL(&zfpm_g->dest_q,dest,fpm_q_entries);zfpm_g->stats.updates_trigg
ered++;/**Makesurethatwritesareenabled.*/if(zfpm_g->t_write)return0;zfpm_write_o
n();return0;}/**zfpm_stats_timer_cb*/staticintzfpm_stats_timer_cb(structthread*t
){zfpm_g->t_stats=NULL;/**Rememberthestatscollectedinthelastintervalfordisplay*p
urposes.*/zfpm_stats_copy(&zfpm_g->stats,&zfpm_g->last_ivl_stats);/**Addthecurre
ntsetofstatsintothecumulativestatistics.*/zfpm_stats_compose(&zfpm_g->cumulative
_stats,&zfpm_g->stats,&zfpm_g->cumulative_stats);/**Startcollectingstatsafreshov
erthenextinterval.*/zfpm_stats_reset(&zfpm_g->stats);zfpm_start_stats_timer();re
turn0;}/**zfpm_stop_stats_timer*/staticvoidzfpm_stop_stats_timer(void){if(!zfpm_
g->t_stats)return;zfpm_debug("Stoppingexistingstatstimer");THREAD_TIMER_OFF(zfpm
_g->t_stats);}/**zfpm_start_stats_timer*/voidzfpm_start_stats_timer(void){assert
(!zfpm_g->t_stats);thread_add_timer(zfpm_g->master,zfpm_stats_timer_cb,0,ZFPM_ST
ATS_IVL_SECS,&zfpm_g->t_stats);}/**Helpermacroforzfpm_show_stats()below.*/#defin
eZFPM_SHOW_STAT(counter)\do{\vty_out(vty,"%-40s%10lu%16lu\n",#counter,\total_sta
ts.counter,zfpm_g->last_ivl_stats.counter);\}while(0)/**zfpm_show_stats*/staticv
oidzfpm_show_stats(structvty*vty){zfpm_stats_ttotal_stats;time_telapsed;vty_out(
vty,"\n%-40s%10sLast%2dsecs\n\n","Counter","Total",ZFPM_STATS_IVL_SECS);/**Compu
tethetotalstatsuptothisinstant.*/zfpm_stats_compose(&zfpm_g->cumulative_stats,&z
fpm_g->stats,&total_stats);ZFPM_SHOW_STAT(connect_calls);ZFPM_SHOW_STAT(connect_
no_sock);ZFPM_SHOW_STAT(read_cb_calls);ZFPM_SHOW_STAT(write_cb_calls);ZFPM_SHOW_
STAT(write_calls);ZFPM_SHOW_STAT(partial_writes);ZFPM_SHOW_STAT(max_writes_hit);
ZFPM_SHOW_STAT(t_write_yields);ZFPM_SHOW_STAT(nop_deletes_skipped);ZFPM_SHOW_STA
T(route_adds);ZFPM_SHOW_STAT(route_dels);ZFPM_SHOW_STAT(updates_triggered);ZFPM_
SHOW_STAT(redundant_triggers);ZFPM_SHOW_STAT(dests_del_after_update);ZFPM_SHOW_S
TAT(t_conn_down_starts);ZFPM_SHOW_STAT(t_conn_down_dests_processed);ZFPM_SHOW_ST
AT(t_conn_down_yields);ZFPM_SHOW_STAT(t_conn_down_finishes);ZFPM_SHOW_STAT(t_con
n_up_starts);ZFPM_SHOW_STAT(t_conn_up_dests_processed);ZFPM_SHOW_STAT(t_conn_up_
yields);ZFPM_SHOW_STAT(t_conn_up_aborts);ZFPM_SHOW_STAT(t_conn_up_finishes);if(!
zfpm_g->last_stats_clear_time)return;elapsed=zfpm_get_elapsed_time(zfpm_g->last_
stats_clear_time);vty_out(vty,"\nStatswerecleared%lusecondsago\n",(unsignedlong)
elapsed);}/**zfpm_clear_stats*/staticvoidzfpm_clear_stats(structvty*vty){if(!zfp
m_is_enabled()){vty_out(vty,"TheFPMmoduleisnotenabled...\n");return;}zfpm_stats_
reset(&zfpm_g->stats);zfpm_stats_reset(&zfpm_g->last_ivl_stats);zfpm_stats_reset
(&zfpm_g->cumulative_stats);zfpm_stop_stats_timer();zfpm_start_stats_timer();zfp
m_g->last_stats_clear_time=monotime(NULL);vty_out(vty,"ClearedFPMstats\n");}/**s
how_zebra_fpm_stats*/DEFUN(show_zebra_fpm_stats,show_zebra_fpm_stats_cmd,"showze
brafpmstats",SHOW_STRZEBRA_STR"ForwardingPathManagerinformation\n""Statistics\n"
){zfpm_show_stats(vty);returnCMD_SUCCESS;}/**clear_zebra_fpm_stats*/DEFUN(clear_
zebra_fpm_stats,clear_zebra_fpm_stats_cmd,"clearzebrafpmstats",CLEAR_STRZEBRA_ST
R"ClearForwardingPathManagerinformation\n""Statistics\n"){zfpm_clear_stats(vty);
returnCMD_SUCCESS;}/**updatefpmconnectioninformation*/DEFUN(fpm_remote_ip,fpm_re
mote_ip_cmd,"fpmconnectionipA.B.C.Dport(1-65535)","fpmconnectionremoteipandport\
n""RemotefpmserveripA.B.C.D\n""Enterip"){in_addr_tfpm_server;uint32_tport_no;fpm
_server=inet_addr(argv[3]->arg);if(fpm_server==INADDR_NONE)returnCMD_ERR_INCOMPL
ETE;port_no=atoi(argv[5]->arg);if(port_no<TCP_MIN_PORT||port_no>TCP_MAX_PORT)ret
urnCMD_ERR_INCOMPLETE;zfpm_g->fpm_server=fpm_server;zfpm_g->fpm_port=port_no;ret
urnCMD_SUCCESS;}DEFUN(no_fpm_remote_ip,no_fpm_remote_ip_cmd,"nofpmconnectionipA.
B.C.Dport(1-65535)","fpmconnectionremoteipandport\n""Connection\n""Remotefpmserv
eripA.B.C.D\n""Enterip"){if(zfpm_g->fpm_server!=inet_addr(argv[4]->arg)||zfpm_g-
>fpm_port!=atoi(argv[6]->arg))returnCMD_ERR_NO_MATCH;zfpm_g->fpm_server=FPM_DEFA
ULT_IP;zfpm_g->fpm_port=FPM_DEFAULT_PORT;returnCMD_SUCCESS;}/**zfpm_init_message
_format*/staticinlinevoidzfpm_init_message_format(constchar*format){inthave_netl
ink,have_protobuf;#ifdefHAVE_NETLINKhave_netlink=1;#elsehave_netlink=0;#endif#if
defHAVE_PROTOBUFhave_protobuf=1;#elsehave_protobuf=0;#endifzfpm_g->message_forma
t=ZFPM_MSG_FORMAT_NONE;if(!format){if(have_netlink){zfpm_g->message_format=ZFPM_
MSG_FORMAT_NETLINK;}elseif(have_protobuf){zfpm_g->message_format=ZFPM_MSG_FORMAT
_PROTOBUF;}return;}if(!strcmp("netlink",format)){if(!have_netlink){zlog_err("FPM
netlinkmessageformatisnotavailable");return;}zfpm_g->message_format=ZFPM_MSG_FOR
MAT_NETLINK;return;}if(!strcmp("protobuf",format)){if(!have_protobuf){zlog_err("
FPMprotobufmessageformatisnotavailable");return;}zfpm_g->message_format=ZFPM_MSG
_FORMAT_PROTOBUF;return;}zlog_warn("Unknownfpmformat'%s'",format);}/***fpm_remot
e_srv_write**Moduletowriteremotefpmconnection**ReturnsZEROonsuccess.*/staticintf
pm_remote_srv_write(structvty*vty){structin_addrin;in.s_addr=zfpm_g->fpm_server;
if((zfpm_g->fpm_server!=FPM_DEFAULT_IP&&zfpm_g->fpm_server!=INADDR_ANY)||(zfpm_g
->fpm_port!=FPM_DEFAULT_PORT&&zfpm_g->fpm_port!=0))vty_out(vty,"fpmconnectionip%
sport%d\n",inet_ntoa(in),zfpm_g->fpm_port);return0;}/*Zebranode*/staticstructcmd
_nodezebra_node={ZEBRA_NODE,"",1};/***zfpm_init**One-timeinitializationoftheZebr
aFPMmodule.**@param[in]portportatwhichFPMisrunning.*@param[in]enableTRUEifthezeb
raFPMmoduleshouldbeenabled*@param[in]formattousetotalktotheFPM.Canbe'netink'or'p
rotobuf'.**ReturnsTRUEonsuccess.*/staticintzfpm_init(structthread_master*master)
{intenable=1;uint16_tport=0;constchar*format=THIS_MODULE->load_args;memset(zfpm_
g,0,sizeof(*zfpm_g));zfpm_g->master=master;TAILQ_INIT(&zfpm_g->dest_q);zfpm_g->s
ock=-1;zfpm_g->state=ZFPM_STATE_IDLE;zfpm_stats_init(&zfpm_g->stats);zfpm_stats_
init(&zfpm_g->last_ivl_stats);zfpm_stats_init(&zfpm_g->cumulative_stats);install
_node(&zebra_node,fpm_remote_srv_write);install_element(ENABLE_NODE,&show_zebra_
fpm_stats_cmd);install_element(ENABLE_NODE,&clear_zebra_fpm_stats_cmd);install_e
lement(CONFIG_NODE,&fpm_remote_ip_cmd);install_element(CONFIG_NODE,&no_fpm_remot
e_ip_cmd);zfpm_init_message_format(format);/**DisableFPMinterfaceifnosuitablefor
matisavailable.*/if(zfpm_g->message_format==ZFPM_MSG_FORMAT_NONE)enable=0;zfpm_g
->enabled=enable;if(!zfpm_g->fpm_server)zfpm_g->fpm_server=FPM_DEFAULT_IP;if(!po
rt)port=FPM_DEFAULT_PORT;zfpm_g->fpm_port=port;zfpm_g->obuf=stream_new(ZFPM_OBUF
_SIZE);zfpm_g->ibuf=stream_new(ZFPM_IBUF_SIZE);zfpm_start_stats_timer();zfpm_sta
rt_connect_timer("initialized");return0;}staticintzebra_fpm_module_init(void){ho
ok_register(rib_update,zfpm_trigger_update);hook_register(frr_late_init,zfpm_ini
t);return0;}FRR_MODULE_SETUP(.name="zebra_fpm",.version=FRR_VERSION,.description
="zebraFPM(ForwardingPlaneManager)module",.init=zebra_fpm_module_init,)