/**Copyright(C)2016byOpenSourceRouting.**ThisfileispartofGNUZebra.**GNUZebraisfr
eesoftware;youcanredistributeitand/ormodifyit*underthetermsoftheGNUGeneralPublic
Licenseaspublishedbythe*FreeSoftwareFoundation;eitherversion2,or(atyouroption)an
y*laterversion.**GNUZebraisdistributedinthehopethatitwillbeuseful,but*WITHOUTANY
WARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFORAPARTICULARP
URPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldhavereceivedacopy
oftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;ifnot,writet
otheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02110-1301USA*
/#include<zebra.h>#include"zebra/rt.h"#include"zebra/zebra_mpls.h"#if!defined(HA
VE_NETLINK)&&!defined(OPEN_BSD)voidkernel_add_lsp(zebra_lsp_t*lsp){return;}voidk
ernel_upd_lsp(zebra_lsp_t*lsp){return;}voidkernel_del_lsp(zebra_lsp_t*lsp){retur
n;}intmpls_kernel_init(void){return-1;};#endif/*!defined(HAVE_NETLINK)&&!defined
(OPEN_BSD)*/