/*ZebraPolicyBasedRouting(PBR)mainhandling.*Copyright(C)2018CumulusNetworks,Inc.
**ThisfileispartofFRR.**FRRisfreesoftware;youcanredistributeitand/ormodifyit*und
erthetermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;ei
therversion2,or(atyouroption)any*laterversion.**FRRisdistributedinthehopethatitw
illbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILI
TYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**
YoushouldhavereceivedacopyoftheGNUGeneralPublicLicense*alongwithFRR;seethefileCO
PYING.Ifnot,writetotheFree*SoftwareFoundation,Inc.,59TemplePlace-Suite330,Boston
,MA*02111-1307,USA.*/#include<zebra.h>#include<jhash.h>#include<hash.h>#include"
zebra/zebra_pbr.h"#include"zebra/rt.h"/*definitions*//*staticfunctiondeclaration
s*//*Privatefunctions*//*Publicfunctions*/voidzebra_pbr_rules_free(void*arg){str
uctzebra_pbr_rule*rule;rule=(structzebra_pbr_rule*)arg;kernel_del_pbr_rule(rule)
;XFREE(MTYPE_TMP,rule);}uint32_tzebra_pbr_rules_hash_key(void*arg){structzebra_p
br_rule*rule;uint32_tkey;rule=(structzebra_pbr_rule*)arg;key=jhash_3words(rule->
seq,rule->priority,rule->action.table,prefix_hash_key(&rule->filter.src_ip));if(
rule->ifp)key=jhash_1word(rule->ifp->ifindex,key);elsekey=jhash_1word(0,key);ret
urnjhash_3words(rule->filter.src_port,rule->filter.dst_port,prefix_hash_key(&rul
e->filter.dst_ip),jhash_1word(rule->unique,key));}intzebra_pbr_rules_hash_equal(
constvoid*arg1,constvoid*arg2){conststructzebra_pbr_rule*r1,*r2;r1=(conststructz
ebra_pbr_rule*)arg1;r2=(conststructzebra_pbr_rule*)arg2;if(r1->seq!=r2->seq)retu
rn0;if(r1->priority!=r2->priority)return0;if(r1->unique!=r2->unique)return0;if(r
1->action.table!=r2->action.table)return0;if(r1->filter.src_port!=r2->filter.src
_port)return0;if(r1->filter.dst_port!=r2->filter.dst_port)return0;if(!prefix_sam
e(&r1->filter.src_ip,&r2->filter.src_ip))return0;if(!prefix_same(&r1->filter.dst
_ip,&r2->filter.dst_ip))return0;if(r1->ifp!=r2->ifp)return0;return1;}structpbr_u
nique_lookup{structzebra_pbr_rule*rule;uint32_tunique;};staticintpbr_rule_lookup
_unique_walker(structhash_backet*b,void*data){structpbr_unique_lookup*pul=data;s
tructzebra_pbr_rule*rule=b->data;if(pul->unique==rule->unique){pul->rule=rule;re
turnHASHWALK_ABORT;}returnHASHWALK_CONTINUE;}staticstructzebra_pbr_rule*pbr_rule
_lookup_unique(structzebra_ns*zns,uint32_tunique){structpbr_unique_lookuppul;pul
.unique=unique;pul.rule=NULL;hash_walk(zns->rules_hash,&pbr_rule_lookup_unique_w
alker,&pul);returnpul.rule;}staticvoid*pbr_rule_alloc_intern(void*arg){structzeb
ra_pbr_rule*zpr;structzebra_pbr_rule*new;zpr=(structzebra_pbr_rule*)arg;new=XCAL
LOC(MTYPE_TMP,sizeof(*new));memcpy(new,zpr,sizeof(*zpr));returnnew;}voidzebra_pb
r_add_rule(structzebra_ns*zns,structzebra_pbr_rule*rule){structzebra_pbr_rule*un
ique=pbr_rule_lookup_unique(zns,rule->unique);(void)hash_get(zns->rules_hash,rul
e,pbr_rule_alloc_intern);kernel_add_pbr_rule(rule);/**RuleReplacesemantics,ifweh
aveanold,installthe*newrule,lookabove,andthendeletetheold*/if(unique)zebra_pbr_d
el_rule(zns,unique);}voidzebra_pbr_del_rule(structzebra_ns*zns,structzebra_pbr_r
ule*rule){structzebra_pbr_rule*lookup;lookup=hash_lookup(zns->rules_hash,rule);k
ernel_del_pbr_rule(rule);if(lookup){hash_release(zns->rules_hash,lookup);XFREE(M
TYPE_TMP,lookup);}elsezlog_warn("%s:Rulebeingdeletedweknownothingabout",__PRETTY
_FUNCTION__);}staticvoidzebra_pbr_cleanup_rules(structhash_backet*b,void*data){s
tructzebra_ns*zns=zebra_ns_lookup(NS_DEFAULT);structzebra_pbr_rule*rule=b->data;
int*sock=data;if(rule->sock==*sock){kernel_del_pbr_rule(rule);hash_release(zns->
rules_hash,rule);XFREE(MTYPE_TMP,rule);}}voidzebra_pbr_client_close_cleanup(ints
ock){structzebra_ns*zns=zebra_ns_lookup(NS_DEFAULT);hash_iterate(zns->rules_hash
,zebra_pbr_cleanup_rules,&sock);}/**Handlesuccessorfailureofrule(un)installinthe
kernel.*/voidkernel_pbr_rule_add_del_status(structzebra_pbr_rule*rule,enumsouthb
ound_resultsres){switch(res){caseSOUTHBOUND_INSTALL_SUCCESS:zsend_rule_notify_ow
ner(rule,ZAPI_RULE_INSTALLED);break;caseSOUTHBOUND_INSTALL_FAILURE:zsend_rule_no
tify_owner(rule,ZAPI_RULE_FAIL_INSTALL);break;caseSOUTHBOUND_DELETE_SUCCESS:brea
k;caseSOUTHBOUND_DELETE_FAILURE:break;}}/**Handleruledeletenotificationfromkerne
l.*/intkernel_pbr_rule_del(structzebra_pbr_rule*rule){return0;}