/*ZebraMPLSVTYfunctions*Copyright(C)2002KunihiroIshiguro**ThisfileispartofGNUZeb
ra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodifyit*underthetermsofth
eGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eitherversion2,o
r(atyouroption)any*laterversion.**GNUZebraisdistributedinthehopethatitwillbeusef
ul,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNE
SSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshould
havereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOP
YING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston
,MA02110-1301USA*/#include<zebra.h>#include"memory.h"#include"if.h"#include"pref
ix.h"#include"command.h"#include"table.h"#include"rib.h"#include"nexthop.h"#incl
ude"vrf.h"#include"mpls.h"#include"lib/json.h"#include"zebra/zserv.h"#include"ze
bra/zebra_vrf.h"#include"zebra/zebra_mpls.h"#include"zebra/zebra_rnh.h"#include"
zebra/redistribute.h"#include"zebra/zebra_routemap.h"#include"zebra/zebra_static
.h"staticintzebra_mpls_transit_lsp(structvty*vty,intadd_cmd,constchar*inlabel_st
r,constchar*gate_str,constchar*outlabel_str,constchar*flag_str){structzebra_vrf*
zvrf;intret;enumnexthop_types_tgtype;uniong_addrgate;mpls_label_tlabel;mpls_labe
l_tin_label,out_label;if(!mpls_enabled){vty_out(vty,"%%MPLSnotturnedoninkernel,i
gnoringcommand\n");returnCMD_WARNING_CONFIG_FAILED;}zvrf=vrf_info_lookup(VRF_DEF
AULT);if(!zvrf){vty_out(vty,"%%DefaultVRFdoesnotexist\n");returnCMD_WARNING_CONF
IG_FAILED;}if(!inlabel_str){vty_out(vty,"%%NoLabelInformation\n");returnCMD_WARN
ING_CONFIG_FAILED;}out_label=MPLS_LABEL_IMPLICIT_NULL;/*asinitialization*/label=
atoi(inlabel_str);if(!IS_MPLS_UNRESERVED_LABEL(label)){vty_out(vty,"%%Invalidlab
el\n");returnCMD_WARNING_CONFIG_FAILED;}if(add_cmd){if(!gate_str){vty_out(vty,"%
%NoNexthopInformation\n");returnCMD_WARNING_CONFIG_FAILED;}if(!outlabel_str){vty
_out(vty,"%%NoOutgoinglabelInformation\n");returnCMD_WARNING_CONFIG_FAILED;}}in_
label=label;gtype=NEXTHOP_TYPE_BLACKHOLE;/*asinitialization*/if(gate_str){/*Gate
wayisaIPv4orIPv6nexthop.*/ret=inet_pton(AF_INET6,gate_str,&gate.ipv6);if(ret)gty
pe=NEXTHOP_TYPE_IPV6;else{ret=inet_pton(AF_INET,gate_str,&gate.ipv4);if(ret)gtyp
e=NEXTHOP_TYPE_IPV4;else{vty_out(vty,"%%Invalidnexthop\n");returnCMD_WARNING_CON
FIG_FAILED;}}}if(outlabel_str){if(outlabel_str[0]=='i')out_label=MPLS_LABEL_IMPL
ICIT_NULL;elseif(outlabel_str[0]=='e'&&gtype==NEXTHOP_TYPE_IPV4)out_label=MPLS_L
ABEL_IPV4_EXPLICIT_NULL;elseif(outlabel_str[0]=='e'&&gtype==NEXTHOP_TYPE_IPV6)ou
t_label=MPLS_LABEL_IPV6_EXPLICIT_NULL;elseout_label=atoi(outlabel_str);}if(add_c
md){#ifdefined(HAVE_CUMULUS)/*Checkthatlabelvalueisconsistent.*/if(!zebra_mpls_l
sp_label_consistent(zvrf,in_label,out_label,gtype,&gate,0)){vty_out(vty,"%%Label
valuenotconsistent\n");returnCMD_WARNING_CONFIG_FAILED;}#endif/*HAVE_CUMULUS*/re
t=zebra_mpls_static_lsp_add(zvrf,in_label,out_label,gtype,&gate,0);}elseret=zebr
a_mpls_static_lsp_del(zvrf,in_label,gtype,&gate,0);if(ret){vty_out(vty,"%%LSPcan
notbe%s\n",add_cmd?"added":"deleted");returnCMD_WARNING_CONFIG_FAILED;}returnCMD
_SUCCESS;}DEFUN(mpls_transit_lsp,mpls_transit_lsp_cmd,"mplslsp(16-1048575)<A.B.C
.D|X:X::X:X><(16-1048575)|explicit-null|implicit-null>",MPLS_STR"Establishlabels
witchedpath\n""IncomingMPLSlabel\n""IPv4gatewayaddress\n""IPv6gatewayaddress\n""
OutgoingMPLSlabel\n""UseExplicit-Nulllabel\n""UseImplicit-Nulllabel\n"){returnze
bra_mpls_transit_lsp(vty,1,argv[2]->arg,argv[3]->arg,argv[4]->arg,NULL);}DEFUN(n
o_mpls_transit_lsp,no_mpls_transit_lsp_cmd,"nomplslsp(16-1048575)<A.B.C.D|X:X::X
:X>",NO_STRMPLS_STR"Establishlabelswitchedpath\n""IncomingMPLSlabel\n""IPv4gatew
ayaddress\n""IPv6gatewayaddress\n"){returnzebra_mpls_transit_lsp(vty,0,argv[3]->
arg,argv[4]->arg,NULL,NULL);}ALIAS(no_mpls_transit_lsp,no_mpls_transit_lsp_out_l
abel_cmd,"nomplslsp(16-1048575)<A.B.C.D|X:X::X:X><(16-1048575)|explicit-null|imp
licit-null>",NO_STRMPLS_STR"Establishlabelswitchedpath\n""IncomingMPLSlabel\n""I
Pv4gatewayaddress\n""IPv6gatewayaddress\n""OutgoingMPLSlabel\n""UseExplicit-Null
label\n""UseImplicit-Nulllabel\n")DEFUN(no_mpls_transit_lsp_all,no_mpls_transit_
lsp_all_cmd,"nomplslsp(16-1048575)",NO_STRMPLS_STR"Establishlabelswitchedpath\n"
"IncomingMPLSlabel\n"){returnzebra_mpls_transit_lsp(vty,0,argv[3]->arg,NULL,NULL
,NULL);}staticintzebra_mpls_bind(structvty*vty,intadd_cmd,constchar*prefix,const
char*label_str){structzebra_vrf*zvrf;structprefixp;uint32_tlabel;intret;zvrf=vrf
_info_lookup(VRF_DEFAULT);if(!zvrf){vty_out(vty,"%%DefaultVRFdoesnotexist\n");re
turnCMD_WARNING_CONFIG_FAILED;}memset(&p,0,sizeof(structprefix));ret=str2prefix(
prefix,&p);if(ret<=0){vty_out(vty,"%%Malformedaddress\n");returnCMD_WARNING_CONF
IG_FAILED;}if(add_cmd){if(!label_str){vty_out(vty,"%%Nolabelbindingspecified\n")
;returnCMD_WARNING_CONFIG_FAILED;}if(!strcmp(label_str,"implicit-null"))label=MP
LS_LABEL_IMPLICIT_NULL;elseif(!strcmp(label_str,"explicit-null")){if(p.family==A
F_INET)label=MPLS_LABEL_IPV4_EXPLICIT_NULL;elselabel=MPLS_LABEL_IPV6_EXPLICIT_NU
LL;}else{label=atoi(label_str);if(!IS_MPLS_UNRESERVED_LABEL(label)){vty_out(vty,
"%%Invalidlabel\n");returnCMD_WARNING_CONFIG_FAILED;}if(zebra_mpls_label_already
_bound(zvrf,label)){vty_out(vty,"%%LabelalreadyboundtoaFEC\n");returnCMD_WARNING
_CONFIG_FAILED;}}ret=zebra_mpls_static_fec_add(zvrf,&p,label);}elseret=zebra_mpl
s_static_fec_del(zvrf,&p);if(ret){vty_out(vty,"%%FECtolabelbindingcannotbe%s\n",
add_cmd?"added":"deleted");returnCMD_WARNING_CONFIG_FAILED;}returnCMD_SUCCESS;}D
EFUN(mpls_label_bind,mpls_label_bind_cmd,"mplslabelbind<A.B.C.D/M|X:X::X:X/M><(1
6-1048575)|implicit-null|explicit-null>",MPLS_STR"Labelconfiguration\n""Establis
hFECtolabelbinding\n""IPv4prefix\n""IPv6prefix\n""MPLSLabeltobind\n""UseImplicit
-NullLabel\n""UseExplicit-NullLabel\n"){returnzebra_mpls_bind(vty,1,argv[3]->arg
,argv[4]->arg);}DEFUN(no_mpls_label_bind,no_mpls_label_bind_cmd,"nomplslabelbind
<A.B.C.D/M|X:X::X:X/M>[<(16-1048575)|implicit-null>]",NO_STRMPLS_STR"Labelconfig
uration\n""EstablishFECtolabelbinding\n""IPv4prefix\n""IPv6prefix\n""MPLSLabelto
bind\n""UseImplicit-NullLabel\n"){returnzebra_mpls_bind(vty,0,argv[4]->arg,NULL)
;}/*MPLSLSPconfigurationwritefunction.*/staticintzebra_mpls_config(structvty*vty
){intwrite=0;structzebra_vrf*zvrf;zvrf=vrf_info_lookup(VRF_DEFAULT);if(!zvrf)ret
urn0;write+=zebra_mpls_write_lsp_config(vty,zvrf);write+=zebra_mpls_write_fec_co
nfig(vty,zvrf);write+=zebra_mpls_write_label_block_config(vty,zvrf);returnwrite;
}DEFUN(show_mpls_fec,show_mpls_fec_cmd,"showmplsfec[<A.B.C.D/M|X:X::X:X/M>]",SHO
W_STRMPLS_STR"MPLSFECtable\n""FECtodisplayinformationabout\n""FECtodisplayinform
ationabout\n"){structzebra_vrf*zvrf;structprefixp;intret;zvrf=vrf_info_lookup(VR
F_DEFAULT);if(!zvrf)return0;if(argc==3)zebra_mpls_print_fec_table(vty,zvrf);else
{memset(&p,0,sizeof(structprefix));ret=str2prefix(argv[3]->arg,&p);if(ret<=0){vt
y_out(vty,"%%Malformedaddress\n");returnCMD_WARNING;}zebra_mpls_print_fec(vty,zv
rf,&p);}returnCMD_SUCCESS;}DEFUN(show_mpls_table,show_mpls_table_cmd,"showmplsta
ble[json]",SHOW_STRMPLS_STR"MPLStable\n"JSON_STR){structzebra_vrf*zvrf;uint8_tuj
=use_json(argc,argv);zvrf=vrf_info_lookup(VRF_DEFAULT);zebra_mpls_print_lsp_tabl
e(vty,zvrf,uj);returnCMD_SUCCESS;}DEFUN(show_mpls_table_lsp,show_mpls_table_lsp_
cmd,"showmplstable(16-1048575)[json]",SHOW_STRMPLS_STR"MPLStable\n""LSPtodisplay
informationabout\n"JSON_STR){uint32_tlabel;structzebra_vrf*zvrf;uint8_tuj=use_js
on(argc,argv);zvrf=vrf_info_lookup(VRF_DEFAULT);label=atoi(argv[3]->arg);zebra_m
pls_print_lsp(vty,zvrf,label,uj);returnCMD_SUCCESS;}DEFUN(show_mpls_status,show_
mpls_status_cmd,"showmplsstatus",SHOW_STR"MPLSinformation\n""MPLSstatus\n"){vty_
out(vty,"MPLSsupportenabled:%s\n",(mpls_enabled)?"yes":"no(mplskernelextensionsn
otdetected)");returnCMD_SUCCESS;}staticintzebra_mpls_global_block(structvty*vty,
intadd_cmd,constchar*start_label_str,constchar*end_label_str){intret;uint32_tsta
rt_label;uint32_tend_label;structzebra_vrf*zvrf;zvrf=zebra_vrf_lookup_by_id(VRF_
DEFAULT);if(!zvrf){vty_out(vty,"%%DefaultVRFdoesnotexist\n");returnCMD_WARNING_C
ONFIG_FAILED;}if(add_cmd){if(!start_label_str||!end_label_str){vty_out(vty,"%%La
belsnotspecified\n");returnCMD_WARNING_CONFIG_FAILED;}start_label=atoi(start_lab
el_str);end_label=atoi(end_label_str);if(!IS_MPLS_UNRESERVED_LABEL(start_label)|
|!IS_MPLS_UNRESERVED_LABEL(end_label)){vty_out(vty,"%%Invalidlabel\n");returnCMD
_WARNING_CONFIG_FAILED;}if(end_label<start_label){vty_out(vty,"%%Endlabelislesst
hanStartlabel\n");returnCMD_WARNING_CONFIG_FAILED;}ret=zebra_mpls_label_block_ad
d(zvrf,start_label,end_label);}elseret=zebra_mpls_label_block_del(zvrf);if(ret){
vty_out(vty,"%%Globallabelblockcouldnotbe%s\n",add_cmd?"added":"deleted");return
CMD_WARNING_CONFIG_FAILED;}returnCMD_SUCCESS;}DEFUN(mpls_label_global_block,mpls
_label_global_block_cmd,"mplslabelglobal-block(16-1048575)(16-1048575)",MPLS_STR
"Labelconfiguration\n""Configuregloballabelblock\n""Startlabel\n""Endlabel\n"){r
eturnzebra_mpls_global_block(vty,1,argv[3]->arg,argv[4]->arg);}DEFUN(no_mpls_lab
el_global_block,no_mpls_label_global_block_cmd,"nomplslabelglobal-block[(16-1048
575)(16-1048575)]",NO_STRMPLS_STR"Labelconfiguration\n""Configuregloballabelbloc
k\n""Startlabel\n""Endlabel\n"){returnzebra_mpls_global_block(vty,0,NULL,NULL);}
/*MPLSnodeforMPLSLSP.*/staticstructcmd_nodempls_node={MPLS_NODE,"",1};/*MPLSVTY.
*/voidzebra_mpls_vty_init(void){install_element(VIEW_NODE,&show_mpls_status_cmd)
;install_node(&mpls_node,zebra_mpls_config);install_element(CONFIG_NODE,&mpls_tr
ansit_lsp_cmd);install_element(CONFIG_NODE,&no_mpls_transit_lsp_cmd);install_ele
ment(CONFIG_NODE,&no_mpls_transit_lsp_out_label_cmd);install_element(CONFIG_NODE
,&no_mpls_transit_lsp_all_cmd);install_element(CONFIG_NODE,&mpls_label_bind_cmd)
;install_element(CONFIG_NODE,&no_mpls_label_bind_cmd);install_element(CONFIG_NOD
E,&mpls_label_global_block_cmd);install_element(CONFIG_NODE,&no_mpls_label_globa
l_block_cmd);install_element(VIEW_NODE,&show_mpls_table_cmd);install_element(VIE
W_NODE,&show_mpls_table_lsp_cmd);install_element(VIEW_NODE,&show_mpls_fec_cmd);}
