/*ZebraMPLScode*Copyright(C)2013CumulusNetworks,Inc.**ThisfileispartofGNUZebra.*
*GNUZebraisfreesoftware;youcanredistributeitand/ormodifyit*underthetermsoftheGNU
GeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eitherversion2,or(at
youroption)any*laterversion.**GNUZebraisdistributedinthehopethatitwillbeuseful,b
ut*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFO
RAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldhave
receivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING
;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA0
2110-1301USA*/#include<zebra.h>#include"prefix.h"#include"table.h"#include"memor
y.h"#include"command.h"#include"if.h"#include"log.h"#include"sockunion.h"#includ
e"linklist.h"#include"thread.h"#include"workqueue.h"#include"prefix.h"#include"r
outemap.h"#include"stream.h"#include"nexthop.h"#include"lib/json.h"#include"zebr
a/rib.h"#include"zebra/rt.h"#include"zebra/zserv.h"#include"zebra/redistribute.h
"#include"zebra/debug.h"#include"zebra/zebra_memory.h"#include"zebra/zebra_vrf.h
"#include"zebra/zebra_mpls.h"DEFINE_MTYPE_STATIC(ZEBRA,LSP,"MPLSLSPobject")DEFIN
E_MTYPE_STATIC(ZEBRA,FEC,"MPLSFECobject")DEFINE_MTYPE_STATIC(ZEBRA,SLSP,"MPLSsta
ticLSPconfig")DEFINE_MTYPE_STATIC(ZEBRA,NHLFE,"MPLSnexthopobject")DEFINE_MTYPE_S
TATIC(ZEBRA,SNHLFE,"MPLSstaticnexthopobject")DEFINE_MTYPE_STATIC(ZEBRA,SNHLFE_IF
NAME,"MPLSstaticnexthopifname")intmpls_enabled;/*Defaultrtm_tableforallclients*/
externstructzebra_tzebrad;/*staticfunctiondeclarations*/staticvoidfec_evaluate(s
tructzebra_vrf*zvrf);staticuint32_tfec_derive_label_from_index(structzebra_vrf*v
rf,zebra_fec_t*fec);staticintlsp_install(structzebra_vrf*zvrf,mpls_label_tlabel,
structroute_node*rn,structroute_entry*re);staticintlsp_uninstall(structzebra_vrf
*zvrf,mpls_label_tlabel);staticintfec_change_update_lsp(structzebra_vrf*zvrf,zeb
ra_fec_t*fec,mpls_label_told_label);staticintfec_send(zebra_fec_t*fec,structzser
v*client);staticvoidfec_update_clients(zebra_fec_t*fec);staticvoidfec_print(zebr
a_fec_t*fec,structvty*vty);staticzebra_fec_t*fec_find(structroute_table*table,st
ructprefix*p);staticzebra_fec_t*fec_add(structroute_table*table,structprefix*p,m
pls_label_tlabel,uint32_tflags,uint32_tlabel_index);staticintfec_del(zebra_fec_t
*fec);staticunsignedintlabel_hash(void*p);staticintlabel_cmp(constvoid*p1,constv
oid*p2);staticintnhlfe_nexthop_active_ipv4(zebra_nhlfe_t*nhlfe,structnexthop*nex
thop);staticintnhlfe_nexthop_active_ipv6(zebra_nhlfe_t*nhlfe,structnexthop*nexth
op);staticintnhlfe_nexthop_active(zebra_nhlfe_t*nhlfe);staticvoidlsp_select_best
_nhlfe(zebra_lsp_t*lsp);staticvoidlsp_uninstall_from_kernel(structhash_backet*ba
cket,void*ctxt);staticvoidlsp_schedule(structhash_backet*backet,void*ctxt);stati
cwq_item_statuslsp_process(structwork_queue*wq,void*data);staticvoidlsp_processq
_del(structwork_queue*wq,void*data);staticvoidlsp_processq_complete(structwork_q
ueue*wq);staticintlsp_processq_add(zebra_lsp_t*lsp);staticvoid*lsp_alloc(void*p)
;staticchar*nhlfe2str(zebra_nhlfe_t*nhlfe,char*buf,intsize);staticintnhlfe_nhop_
match(zebra_nhlfe_t*nhlfe,enumnexthop_types_tgtype,uniong_addr*gate,ifindex_tifi
ndex);staticzebra_nhlfe_t*nhlfe_find(zebra_lsp_t*lsp,enumlsp_types_tlsp_type,enu
mnexthop_types_tgtype,uniong_addr*gate,ifindex_tifindex);staticzebra_nhlfe_t*nhl
fe_add(zebra_lsp_t*lsp,enumlsp_types_tlsp_type,enumnexthop_types_tgtype,uniong_a
ddr*gate,ifindex_tifindex,mpls_label_tout_label);staticintnhlfe_del(zebra_nhlfe_
t*snhlfe);staticvoidnhlfe_out_label_update(zebra_nhlfe_t*nhlfe,structmpls_label_
stack*nh_label);staticintmpls_lsp_uninstall_all(structhash*lsp_table,zebra_lsp_t
*lsp,enumlsp_types_ttype);staticintmpls_static_lsp_uninstall_all(structzebra_vrf
*zvrf,mpls_label_tin_label);staticvoidnhlfe_print(zebra_nhlfe_t*nhlfe,structvty*
vty);staticvoidlsp_print(zebra_lsp_t*lsp,void*ctxt);staticvoid*slsp_alloc(void*p
);staticintsnhlfe_match(zebra_snhlfe_t*snhlfe,enumnexthop_types_tgtype,uniong_ad
dr*gate,ifindex_tifindex);staticzebra_snhlfe_t*snhlfe_find(zebra_slsp_t*slsp,enu
mnexthop_types_tgtype,uniong_addr*gate,ifindex_tifindex);staticzebra_snhlfe_t*sn
hlfe_add(zebra_slsp_t*slsp,enumnexthop_types_tgtype,uniong_addr*gate,ifindex_tif
index,mpls_label_tout_label);staticintsnhlfe_del(zebra_snhlfe_t*snhlfe);staticin
tsnhlfe_del_all(zebra_slsp_t*slsp);staticchar*snhlfe2str(zebra_snhlfe_t*snhlfe,c
har*buf,intsize);staticintmpls_processq_init(structzebra_t*zebra);/*Staticfuncti
ons*//**HandlefailureinLSPinstall,clearflagsforNHLFE.*/staticvoidclear_nhlfe_ins
talled(zebra_lsp_t*lsp){zebra_nhlfe_t*nhlfe;structnexthop*nexthop;for(nhlfe=lsp-
>nhlfe_list;nhlfe;nhlfe=nhlfe->next){nexthop=nhlfe->nexthop;if(!nexthop)continue
;UNSET_FLAG(nhlfe->flags,NHLFE_FLAG_INSTALLED);UNSET_FLAG(nexthop->flags,NEXTHOP
_FLAG_FIB);}}/**Installlabelforwardingentrybasedonlabeled-routeentry.*/staticint
lsp_install(structzebra_vrf*zvrf,mpls_label_tlabel,structroute_node*rn,structrou
te_entry*re){structhash*lsp_table;zebra_ile_ttmp_ile;zebra_lsp_t*lsp;zebra_nhlfe
_t*nhlfe;structnexthop*nexthop;enumlsp_types_tlsp_type;charbuf[BUFSIZ];intadded,
changed;/*Lookuptable.*/lsp_table=zvrf->lsp_table;if(!lsp_table)return-1;lsp_typ
e=lsp_type_from_re_type(re->type);added=changed=0;/*LocateorallocateLSPentry.*/t
mp_ile.in_label=label;lsp=hash_get(lsp_table,&tmp_ile,lsp_alloc);if(!lsp)return-
1;/*Foreachactivenexthop,createNHLFE.Notethatwedeliberatelyskip*recursivenexthop
srightnow,becauseintermediatehopswon't*understand*thelabeladvertisedbytherecursi
venexthop(pluswedon'thavethe*logicyettopushmultiplelabels).*/for(nexthop=re->ng.
nexthop;nexthop;nexthop=nexthop->next){/*Skipinactiveandrecursiveentries.*/if(!C
HECK_FLAG(nexthop->flags,NEXTHOP_FLAG_ACTIVE))continue;if(CHECK_FLAG(nexthop->fl
ags,NEXTHOP_FLAG_RECURSIVE))continue;nhlfe=nhlfe_find(lsp,lsp_type,nexthop->type
,&nexthop->gate,nexthop->ifindex);if(nhlfe){/*Cleardeletedflag(incaseitwasset)*/
UNSET_FLAG(nhlfe->flags,NHLFE_FLAG_DELETED);if(nexthop_labels_match(nhlfe->nexth
op,nexthop))/*Nochange*/continue;if(IS_ZEBRA_DEBUG_MPLS){nhlfe2str(nhlfe,buf,BUF
SIZ);zlog_debug("LSPin-label%utype%dnexthop%s""out-labelchanged",lsp->ile.in_lab
el,lsp_type,buf);}/*Updateoutlabel,triggerprocessing.*/nhlfe_out_label_update(nh
lfe,nexthop->nh_label);SET_FLAG(nhlfe->flags,NHLFE_FLAG_CHANGED);changed++;}else
{/*AddLSPentrytothisnexthop*/nhlfe=nhlfe_add(lsp,lsp_type,nexthop->type,&nexthop
->gate,nexthop->ifindex,nexthop->nh_label->label[0]);if(!nhlfe)return-1;if(IS_ZE
BRA_DEBUG_MPLS){nhlfe2str(nhlfe,buf,BUFSIZ);zlog_debug("AddLSPin-label%utype%dne
xthop%s""out-label%u",lsp->ile.in_label,lsp_type,buf,nexthop->nh_label->label[0]
);}lsp->addr_family=NHLFE_FAMILY(nhlfe);/*MarkNHLFEaschanged.*/SET_FLAG(nhlfe->f
lags,NHLFE_FLAG_CHANGED);added++;}}/*QueueLSPforprocessingifnecessary.IfnoNHLFEg
otadded(special*case),deletetheLSPentry;thiscaseresultsinsomewhatugly*logging.*/
if(added||changed){if(lsp_processq_add(lsp))return-1;}elseif(!lsp->nhlfe_list&&!
CHECK_FLAG(lsp->flags,LSP_FLAG_SCHEDULED)){if(IS_ZEBRA_DEBUG_MPLS)zlog_debug("Fr
eeLSPin-label%uflags0x%x",lsp->ile.in_label,lsp->flags);lsp=hash_release(lsp_tab
le,&lsp->ile);if(lsp)XFREE(MTYPE_LSP,lsp);}return0;}/**Uninstallallnon-staticNHL
FEsofalabelforwardingentry.Ifall*NHLFEsareremoved,theentireentryisdeleted.*/stat
icintlsp_uninstall(structzebra_vrf*zvrf,mpls_label_tlabel){structhash*lsp_table;
zebra_ile_ttmp_ile;zebra_lsp_t*lsp;zebra_nhlfe_t*nhlfe,*nhlfe_next;charbuf[BUFSI
Z];/*Lookuptable.*/lsp_table=zvrf->lsp_table;if(!lsp_table)return-1;/*Ifentryisn
otpresent,exit.*/tmp_ile.in_label=label;lsp=hash_lookup(lsp_table,&tmp_ile);if(!
lsp||!lsp->nhlfe_list)return0;/*MarkNHLFEsfordeleteordirectlydelete,asappropriat
e.*/for(nhlfe=lsp->nhlfe_list;nhlfe;nhlfe=nhlfe_next){nhlfe_next=nhlfe->next;/*S
kipstaticNHLFEs*/if(nhlfe->type==ZEBRA_LSP_STATIC)continue;if(IS_ZEBRA_DEBUG_MPL
S){nhlfe2str(nhlfe,buf,BUFSIZ);zlog_debug("DelLSPin-label%utype%dnexthop%sflags0
x%x",label,nhlfe->type,buf,nhlfe->flags);}if(CHECK_FLAG(nhlfe->flags,NHLFE_FLAG_
SELECTED)){UNSET_FLAG(nhlfe->flags,NHLFE_FLAG_CHANGED);SET_FLAG(nhlfe->flags,NHL
FE_FLAG_DELETED);}else{nhlfe_del(nhlfe);}}/*QueueLSPforprocessing,ifneeded,elsed
elete.*/if(CHECK_FLAG(lsp->flags,LSP_FLAG_INSTALLED)){if(lsp_processq_add(lsp))r
eturn-1;}elseif(!lsp->nhlfe_list&&!CHECK_FLAG(lsp->flags,LSP_FLAG_SCHEDULED)){if
(IS_ZEBRA_DEBUG_MPLS)zlog_debug("DelLSPin-label%uflags0x%x",lsp->ile.in_label,ls
p->flags);lsp=hash_release(lsp_table,&lsp->ile);if(lsp)XFREE(MTYPE_LSP,lsp);}ret
urn0;}/**Thisfunctionisinvokeduponchangetolabelblockconfiguration;it*willwalkall
registeredFECswithlabel-indexandappropriatelyupdate*theirlocallabelsandtriggercl
ientupdates.*/staticvoidfec_evaluate(structzebra_vrf*zvrf){structroute_node*rn;z
ebra_fec_t*fec;uint32_told_label,new_label;intaf;charbuf[BUFSIZ];for(af=AFI_IP;a
f<AFI_MAX;af++){if(zvrf->fec_table[af]==NULL)continue;for(rn=route_top(zvrf->fec
_table[af]);rn;rn=route_next(rn)){if((fec=rn->info)==NULL)continue;/*Skipconfigu
redFECsandthosewithoutalabelindex.*/if(fec->flags&FEC_FLAG_CONFIGURED||fec->labe
l_index==MPLS_INVALID_LABEL_INDEX)continue;if(IS_ZEBRA_DEBUG_MPLS)prefix2str(&rn
->p,buf,BUFSIZ);/*Saveoldlabel,determinenewlabel.*/old_label=fec->label;new_labe
l=zvrf->mpls_srgb.start_label+fec->label_index;if(new_label>=zvrf->mpls_srgb.end
_label)new_label=MPLS_INVALID_LABEL;/*Iflabelhaschanged,updateFECandclients.*/if
(new_label==old_label)continue;if(IS_ZEBRA_DEBUG_MPLS)zlog_debug("Updatefec%snew
label%uuponlabelblock",buf,new_label);fec->label=new_label;fec_update_clients(fe
c);/*Updatelabelforwardingentriesappropriately*/fec_change_update_lsp(zvrf,fec,o
ld_label);}}}/**Derive(ifpossible)andupdatethelocallabelfortheFECbasedon*itslabe
lindex.Theindexis"acceptable"ifitfallswithinthe*globallyconfiguredlabelblock(SRG
B).*/staticuint32_tfec_derive_label_from_index(structzebra_vrf*zvrf,zebra_fec_t*
fec){uint32_tlabel;if(fec->label_index!=MPLS_INVALID_LABEL_INDEX&&zvrf->mpls_srg
b.start_label&&((label=zvrf->mpls_srgb.start_label+fec->label_index)<zvrf->mpls_
srgb.end_label))fec->label=label;elsefec->label=MPLS_INVALID_LABEL;returnfec->la
bel;}/**ThereisachangeforthisFEC.Installoruninstalllabelforwarding*entries,asapp
ropriate.*/staticintfec_change_update_lsp(structzebra_vrf*zvrf,zebra_fec_t*fec,m
pls_label_told_label){structroute_table*table;structroute_node*rn;structroute_en
try*re;afi_tafi;/*Uninstalllabelforwardingentry,ifpreviouslyinstalled.*/if(old_l
abel!=MPLS_INVALID_LABEL&&old_label!=MPLS_LABEL_IMPLICIT_NULL)lsp_uninstall(zvrf
,old_label);/*Installlabelforwardingentrycorr.tonewlabel,ifneeded.*/if(fec->labe
l==MPLS_INVALID_LABEL||fec->label==MPLS_LABEL_IMPLICIT_NULL)return0;afi=family2a
fi(PREFIX_FAMILY(&fec->rn->p));table=zebra_vrf_table(afi,SAFI_UNICAST,zvrf_id(zv
rf));if(!table)return0;/*Seeiflabeledrouteexists.*/rn=route_node_lookup(table,&f
ec->rn->p);if(!rn)return0;RNODE_FOREACH_RE(rn,re){if(CHECK_FLAG(re->flags,ZEBRA_
FLAG_SELECTED))break;}if(!re||!zebra_rib_labeled_unicast(re))return0;if(lsp_inst
all(zvrf,fec->label,rn,re))return-1;return0;}/**InformaboutFECtoaregisteredclien
t.*/staticintfec_send(zebra_fec_t*fec,structzserv*client){structstream*s;structr
oute_node*rn;rn=fec->rn;/*Getoutputstream.*/s=stream_new(ZEBRA_MAX_PACKET_SIZ);z
client_create_header(s,ZEBRA_FEC_UPDATE,VRF_DEFAULT);stream_putw(s,rn->p.family)
;stream_put_prefix(s,&rn->p);stream_putl(s,fec->label);stream_putw_at(s,0,stream
_get_endp(s));returnzebra_server_send_message(client,s);}/**Updateallregisteredc
lientsaboutthisFEC.Callershould'veupdated*FECandensurenoduplicateupdates.*/stati
cvoidfec_update_clients(zebra_fec_t*fec){structlistnode*node;structzserv*client;
for(ALL_LIST_ELEMENTS_RO(fec->client_list,node,client)){if(IS_ZEBRA_DEBUG_MPLS)z
log_debug("Updateclient%s",zebra_route_string(client->proto));fec_send(fec,clien
t);}}/**PrintaFEC-labelbindingentry.*/staticvoidfec_print(zebra_fec_t*fec,struct
vty*vty){structroute_node*rn;structlistnode*node;structzserv*client;charbuf[BUFS
IZ];rn=fec->rn;prefix2str(&rn->p,buf,BUFSIZ);vty_out(vty,"%s\n",buf);vty_out(vty
,"Label:%s",label2str(fec->label,buf,BUFSIZ));if(fec->label_index!=MPLS_INVALID_
LABEL_INDEX)vty_out(vty,",LabelIndex:%u",fec->label_index);vty_out(vty,"\n");if(
!list_isempty(fec->client_list)){vty_out(vty,"Clientlist:");for(ALL_LIST_ELEMENT
S_RO(fec->client_list,node,client))vty_out(vty,"%s(fd%d)",zebra_route_string(cli
ent->proto),client->sock);vty_out(vty,"\n");}}/**LocateFEC-labelbindingthatmatch
eswithpassedinfo.*/staticzebra_fec_t*fec_find(structroute_table*table,structpref
ix*p){structroute_node*rn;apply_mask(p);rn=route_node_lookup(table,p);if(!rn)ret
urnNULL;route_unlock_node(rn);return(rn->info);}/**AddaFEC.Thismaybeuponaclientr
egisteringforabinding*orwhenabindingisconfigured.*/staticzebra_fec_t*fec_add(str
uctroute_table*table,structprefix*p,mpls_label_tlabel,uint32_tflags,uint32_tlabe
l_index){structroute_node*rn;zebra_fec_t*fec;apply_mask(p);/*Lookup(oradd)routen
ode.*/rn=route_node_get(table,p);if(!rn)returnNULL;fec=rn->info;if(!fec){fec=XCA
LLOC(MTYPE_FEC,sizeof(zebra_fec_t));if(!fec)returnNULL;rn->info=fec;fec->rn=rn;f
ec->label=label;fec->client_list=list_new();}elseroute_unlock_node(rn);/*forther
oute_node_get*/fec->label_index=label_index;fec->flags=flags;returnfec;}/**Delet
eaFEC.Thismaybeuponthelastclientderegisteringfor*aFECandnobindingexistsorwhenthe
bindingisdeletedandthere*arenoregisteredclients.*/staticintfec_del(zebra_fec_t*f
ec){list_delete_and_null(&fec->client_list);fec->rn->info=NULL;route_unlock_node
(fec->rn);XFREE(MTYPE_FEC,fec);return0;}/**Hashfunctionforlabel.*/staticunsigned
intlabel_hash(void*p){constzebra_ile_t*ile=p;return(jhash_1word(ile->in_label,0)
);}/**Compare2LSPhashentriesbasedonin-label.*/staticintlabel_cmp(constvoid*p1,co
nstvoid*p2){constzebra_ile_t*ile1=p1;constzebra_ile_t*ile2=p2;return(ile1->in_la
bel==ile2->in_label);}/**CheckifanIPv4nexthopforaNHLFEisactive.Updatenexthopbase
don*thepassedflag.*NOTE:Lookingonlyforconnectedroutesrightnow.*/staticintnhlfe_n
exthop_active_ipv4(zebra_nhlfe_t*nhlfe,structnexthop*nexthop){structroute_table*
table;structprefix_ipv4p;structroute_node*rn;structroute_entry*match;structnexth
op*match_nh;table=zebra_vrf_table(AFI_IP,SAFI_UNICAST,nexthop->vrf_id);if(!table
)return0;/*LookupnexthopinIPv4routingtable.*/memset(&p,0,sizeof(structprefix_ipv
4));p.family=AF_INET;p.prefixlen=IPV4_MAX_PREFIXLEN;p.prefix=nexthop->gate.ipv4;
rn=route_node_match(table,(structprefix*)&p);if(!rn)return0;route_unlock_node(rn
);/*Locateavalidconnectedroute.*/RNODE_FOREACH_RE(rn,match){if(CHECK_FLAG(match-
>status,ROUTE_ENTRY_REMOVED)||!CHECK_FLAG(match->flags,ZEBRA_FLAG_SELECTED))cont
inue;for(match_nh=match->ng.nexthop;match_nh;match_nh=match_nh->next){if(match->
type==ZEBRA_ROUTE_CONNECT||nexthop->ifindex==match_nh->ifindex){nexthop->ifindex
=match_nh->ifindex;return1;}}}return0;}/**CheckifanIPv6nexthopforaNHLFEisactive.
Updatenexthopbasedon*thepassedflag.*NOTE:Lookingonlyforconnectedroutesrightnow.*
/staticintnhlfe_nexthop_active_ipv6(zebra_nhlfe_t*nhlfe,structnexthop*nexthop){s
tructroute_table*table;structprefix_ipv6p;structroute_node*rn;structroute_entry*
match;table=zebra_vrf_table(AFI_IP6,SAFI_UNICAST,nexthop->vrf_id);if(!table)retu
rn0;/*LookupnexthopinIPv6routingtable.*/memset(&p,0,sizeof(structprefix_ipv6));p
.family=AF_INET6;p.prefixlen=IPV6_MAX_PREFIXLEN;p.prefix=nexthop->gate.ipv6;rn=r
oute_node_match(table,(structprefix*)&p);if(!rn)return0;route_unlock_node(rn);/*
Locateavalidconnectedroute.*/RNODE_FOREACH_RE(rn,match){if((match->type==ZEBRA_R
OUTE_CONNECT)&&!CHECK_FLAG(match->status,ROUTE_ENTRY_REMOVED)&&CHECK_FLAG(match-
>flags,ZEBRA_FLAG_SELECTED))break;}if(!match||!match->ng.nexthop)return0;nexthop
->ifindex=match->ng.nexthop->ifindex;return1;}/**Checkthenexthopreachabilityfora
NHLFEandreturnifvalid(reachable)*ornot.*NOTE:EachNHLFEpointstoonly1nexthop.*/sta
ticintnhlfe_nexthop_active(zebra_nhlfe_t*nhlfe){structnexthop*nexthop;structinte
rface*ifp;nexthop=nhlfe->nexthop;if(!nexthop)//unexpectedreturn0;/*Checkonnextho
pbasedontype.*/switch(nexthop->type){caseNEXTHOP_TYPE_IFINDEX:/**Lookupifthistyp
eisspecial.The*NEXTHOP_TYPE_IFINDEXisapopand*forwardintoadifferenttablefor*proce
ssing.Assuchthisifindex*passedtousmaybeaVRFdevice*whichwillnotbeinthedefault*VRF
.Solet'slookinallofthem*/ifp=if_lookup_by_index(nexthop->ifindex,VRF_UNKNOWN);if
(ifp&&if_is_operative(ifp))SET_FLAG(nexthop->flags,NEXTHOP_FLAG_ACTIVE);elseUNSE
T_FLAG(nexthop->flags,NEXTHOP_FLAG_ACTIVE);break;caseNEXTHOP_TYPE_IPV4:caseNEXTH
OP_TYPE_IPV4_IFINDEX:if(nhlfe_nexthop_active_ipv4(nhlfe,nexthop))SET_FLAG(nextho
p->flags,NEXTHOP_FLAG_ACTIVE);elseUNSET_FLAG(nexthop->flags,NEXTHOP_FLAG_ACTIVE)
;break;caseNEXTHOP_TYPE_IPV6:if(nhlfe_nexthop_active_ipv6(nhlfe,nexthop))SET_FLA
G(nexthop->flags,NEXTHOP_FLAG_ACTIVE);elseUNSET_FLAG(nexthop->flags,NEXTHOP_FLAG
_ACTIVE);break;caseNEXTHOP_TYPE_IPV6_IFINDEX:if(IN6_IS_ADDR_LINKLOCAL(&nexthop->
gate.ipv6)){ifp=if_lookup_by_index(nexthop->ifindex,nexthop->vrf_id);if(ifp&&if_
is_operative(ifp))SET_FLAG(nexthop->flags,NEXTHOP_FLAG_ACTIVE);elseUNSET_FLAG(ne
xthop->flags,NEXTHOP_FLAG_ACTIVE);}else{if(nhlfe_nexthop_active_ipv6(nhlfe,nexth
op))SET_FLAG(nexthop->flags,NEXTHOP_FLAG_ACTIVE);elseUNSET_FLAG(nexthop->flags,N
EXTHOP_FLAG_ACTIVE);}break;default:break;}returnCHECK_FLAG(nexthop->flags,NEXTHO
P_FLAG_ACTIVE);}/**WalkthroughNHLFEsforaLSPforwardingentry,verifynexthop*reachab
ilityandselectthebest.Multipathentriesarealso*marked.ThisisinvokedwhenanLSPsched
uledforprocessing(due*tosomechange)isexamined.*/staticvoidlsp_select_best_nhlfe(
zebra_lsp_t*lsp){zebra_nhlfe_t*nhlfe;zebra_nhlfe_t*best;structnexthop*nexthop;in
tchanged=0;if(!lsp)return;best=NULL;lsp->num_ecmp=0;UNSET_FLAG(lsp->flags,LSP_FL
AG_CHANGED);/**Firstcomputethebestpath,aftercheckingnexthopstatus.Weare*only*con
cernedwithnon-deletedNHLFEs.*/for(nhlfe=lsp->nhlfe_list;nhlfe;nhlfe=nhlfe->next)
{/*Clearselectionflags.*/UNSET_FLAG(nhlfe->flags,(NHLFE_FLAG_SELECTED|NHLFE_FLAG
_MULTIPATH));if(!CHECK_FLAG(nhlfe->flags,NHLFE_FLAG_DELETED)&&nhlfe_nexthop_acti
ve(nhlfe)){if(!best||(nhlfe->distance<best->distance))best=nhlfe;}}lsp->best_nhl
fe=best;if(!lsp->best_nhlfe)return;/*MarkbestNHLFEasselected.*/SET_FLAG(lsp->bes
t_nhlfe->flags,NHLFE_FLAG_SELECTED);/**Ifbestpathexists,seeifthereisECMP.Whiledo
ingthis,noteif*a*new(uninstalled)NHLFEhasbeenselected,aninstalledentrythatis*sti
llselectedhasachangeoraninstalledentryistoberemoved.*/for(nhlfe=lsp->nhlfe_list;
nhlfe;nhlfe=nhlfe->next){intnh_chg,nh_sel,nh_inst;nexthop=nhlfe->nexthop;if(!nex
thop)//unexpectedcontinue;if(!CHECK_FLAG(nhlfe->flags,NHLFE_FLAG_DELETED)&&CHECK
_FLAG(nexthop->flags,NEXTHOP_FLAG_ACTIVE)&&(nhlfe->distance==lsp->best_nhlfe->di
stance)){SET_FLAG(nhlfe->flags,NHLFE_FLAG_SELECTED);SET_FLAG(nhlfe->flags,NHLFE_
FLAG_MULTIPATH);lsp->num_ecmp++;}if(CHECK_FLAG(lsp->flags,LSP_FLAG_INSTALLED)&&!
changed){nh_chg=CHECK_FLAG(nhlfe->flags,NHLFE_FLAG_CHANGED);nh_sel=CHECK_FLAG(nh
lfe->flags,NHLFE_FLAG_SELECTED);nh_inst=CHECK_FLAG(nhlfe->flags,NHLFE_FLAG_INSTA
LLED);if((nh_sel&&!nh_inst)||(nh_sel&&nh_inst&&nh_chg)||(nh_inst&&!nh_sel))chang
ed=1;}/*Wehavefinishedexamining,clearchangedflag.*/UNSET_FLAG(nhlfe->flags,NHLFE
_FLAG_CHANGED);}if(changed)SET_FLAG(lsp->flags,LSP_FLAG_CHANGED);}/**DeleteLSPfo
rwardingentryfromkernel,ifinstalled.Calledupon*processexit.*/staticvoidlsp_unins
tall_from_kernel(structhash_backet*backet,void*ctxt){zebra_lsp_t*lsp;lsp=(zebra_
lsp_t*)backet->data;if(CHECK_FLAG(lsp->flags,LSP_FLAG_INSTALLED))kernel_del_lsp(
lsp);}/**ScheduleLSPforwardingentryforprocessing.Calleduponchanges*thatmayimpact
LSPssuchasnexthop/connectedroutechanges.*/staticvoidlsp_schedule(structhash_back
et*backet,void*ctxt){zebra_lsp_t*lsp;lsp=(zebra_lsp_t*)backet->data;(void)lsp_pr
ocessq_add(lsp);}/**ProcessaLSPentrythatisinthequeue.RecalculatebestNHLFEand*any
multipathsandupdateordeletefromthekernel,asneeded.*/staticwq_item_statuslsp_proc
ess(structwork_queue*wq,void*data){zebra_lsp_t*lsp;zebra_nhlfe_t*oldbest,*newbes
t;charbuf[BUFSIZ],buf2[BUFSIZ];structzebra_vrf*zvrf=vrf_info_lookup(VRF_DEFAULT)
;lsp=(zebra_lsp_t*)data;if(!lsp)//unexpectedreturnWQ_SUCCESS;oldbest=lsp->best_n
hlfe;/*SelectbestNHLFE(s)*/lsp_select_best_nhlfe(lsp);newbest=lsp->best_nhlfe;if
(IS_ZEBRA_DEBUG_MPLS){if(oldbest)nhlfe2str(oldbest,buf,BUFSIZ);if(newbest)nhlfe2
str(newbest,buf2,BUFSIZ);zlog_debug("ProcessLSPin-label%uoldbest%snewbest%s""fla
gs0x%xecmp#%d",lsp->ile.in_label,oldbest?buf:"NULL",newbest?buf2:"NULL",lsp->fla
gs,lsp->num_ecmp);}if(!CHECK_FLAG(lsp->flags,LSP_FLAG_INSTALLED)){/*Notalreadyin
stalled*/if(newbest){UNSET_FLAG(lsp->flags,LSP_FLAG_CHANGED);kernel_add_lsp(lsp)
;zvrf->lsp_installs++;}}else{/*Installed,mayneedanupdateand/ordelete.*/if(!newbe
st){kernel_del_lsp(lsp);zvrf->lsp_removals++;}elseif(CHECK_FLAG(lsp->flags,LSP_F
LAG_CHANGED)){zebra_nhlfe_t*nhlfe;structnexthop*nexthop;UNSET_FLAG(lsp->flags,LS
P_FLAG_CHANGED);UNSET_FLAG(lsp->flags,LSP_FLAG_INSTALLED);/**AnyNHLFEthatwasinst
alledbutisnot*selectednowneedstohaveitsflagsupdated.*/for(nhlfe=lsp->nhlfe_list;
nhlfe;nhlfe=nhlfe->next){nexthop=nhlfe->nexthop;if(!nexthop)continue;if(CHECK_FL
AG(nhlfe->flags,NHLFE_FLAG_INSTALLED)&&!CHECK_FLAG(nhlfe->flags,NHLFE_FLAG_SELEC
TED)){UNSET_FLAG(nhlfe->flags,NHLFE_FLAG_INSTALLED);UNSET_FLAG(nexthop->flags,NE
XTHOP_FLAG_FIB);}}kernel_upd_lsp(lsp);zvrf->lsp_installs++;}}returnWQ_SUCCESS;}/
**CallbackuponprocessingcompletionofaLSPforwardingentry.*/staticvoidlsp_processq
_del(structwork_queue*wq,void*data){structzebra_vrf*zvrf;zebra_lsp_t*lsp;structh
ash*lsp_table;zebra_nhlfe_t*nhlfe,*nhlfe_next;zvrf=vrf_info_lookup(VRF_DEFAULT);
assert(zvrf);lsp_table=zvrf->lsp_table;if(!lsp_table)//unexpectedreturn;lsp=(zeb
ra_lsp_t*)data;if(!lsp)//unexpectedreturn;/*Clearflag,removeanyNHLFEsmarkedforde
letion.IfnoNHLFEs*exist,*deleteLSPentryalso.*/UNSET_FLAG(lsp->flags,LSP_FLAG_SCH
EDULED);for(nhlfe=lsp->nhlfe_list;nhlfe;nhlfe=nhlfe_next){nhlfe_next=nhlfe->next
;if(CHECK_FLAG(nhlfe->flags,NHLFE_FLAG_DELETED))nhlfe_del(nhlfe);}if(!lsp->nhlfe
_list){if(IS_ZEBRA_DEBUG_MPLS)zlog_debug("FreeLSPin-label%uflags0x%x",lsp->ile.i
n_label,lsp->flags);lsp=hash_release(lsp_table,&lsp->ile);if(lsp)XFREE(MTYPE_LSP
,lsp);}}/**Callbackuponfinishingtheprocessingofallscheduled*LSPforwardingentries
.*/staticvoidlsp_processq_complete(structwork_queue*wq){/*Nothingtodofornow.*/}/
**AddLSPforwardingentrytoqueueforsubsequentprocessing.*/staticintlsp_processq_ad
d(zebra_lsp_t*lsp){/*Ifalreadyscheduled,exit.*/if(CHECK_FLAG(lsp->flags,LSP_FLAG
_SCHEDULED))return0;if(zebrad.lsp_process_q==NULL){zlog_err("%s:work_queuedoesno
texist!",__func__);return-1;}work_queue_add(zebrad.lsp_process_q,lsp);SET_FLAG(l
sp->flags,LSP_FLAG_SCHEDULED);return0;}/**CallbacktoallocateLSPforwardingtableen
try.*/staticvoid*lsp_alloc(void*p){constzebra_ile_t*ile=p;zebra_lsp_t*lsp;lsp=XC
ALLOC(MTYPE_LSP,sizeof(zebra_lsp_t));lsp->ile=*ile;if(IS_ZEBRA_DEBUG_MPLS)zlog_d
ebug("AllocLSPin-label%u",lsp->ile.in_label);return((void*)lsp);}/**Createprinta
blestringforNHLFEentry.*/staticchar*nhlfe2str(zebra_nhlfe_t*nhlfe,char*buf,intsi
ze){structnexthop*nexthop;buf[0]='\0';nexthop=nhlfe->nexthop;switch(nexthop->typ
e){caseNEXTHOP_TYPE_IPV4:caseNEXTHOP_TYPE_IPV4_IFINDEX:inet_ntop(AF_INET,&nextho
p->gate.ipv4,buf,size);break;caseNEXTHOP_TYPE_IPV6:inet_ntop(AF_INET6,&nexthop->
gate.ipv6,buf,size);break;caseNEXTHOP_TYPE_IFINDEX:snprintf(buf,size,"Ifindex:%u
",nexthop->ifindex);default:break;}returnbuf;}/**CheckifNHLFEmatcheswithsearchin
fopassed.*/staticintnhlfe_nhop_match(zebra_nhlfe_t*nhlfe,enumnexthop_types_tgtyp
e,uniong_addr*gate,ifindex_tifindex){structnexthop*nhop;intcmp=1;nhop=nhlfe->nex
thop;if(!nhop)return1;if(nhop->type!=gtype)return1;switch(nhop->type){caseNEXTHO
P_TYPE_IPV4:caseNEXTHOP_TYPE_IPV4_IFINDEX:cmp=memcmp(&(nhop->gate.ipv4),&(gate->
ipv4),sizeof(structin_addr));if(!cmp&&nhop->type==NEXTHOP_TYPE_IPV4_IFINDEX)cmp=
!(nhop->ifindex==ifindex);break;caseNEXTHOP_TYPE_IPV6:caseNEXTHOP_TYPE_IPV6_IFIN
DEX:cmp=memcmp(&(nhop->gate.ipv6),&(gate->ipv6),sizeof(structin6_addr));if(!cmp&
&nhop->type==NEXTHOP_TYPE_IPV6_IFINDEX)cmp=!(nhop->ifindex==ifindex);break;caseN
EXTHOP_TYPE_IFINDEX:cmp=!(nhop->ifindex==ifindex);break;default:break;}returncmp
;}/**LocateNHLFEthatmatcheswithpassedinfo.*/staticzebra_nhlfe_t*nhlfe_find(zebra
_lsp_t*lsp,enumlsp_types_tlsp_type,enumnexthop_types_tgtype,uniong_addr*gate,ifi
ndex_tifindex){zebra_nhlfe_t*nhlfe;if(!lsp)returnNULL;for(nhlfe=lsp->nhlfe_list;
nhlfe;nhlfe=nhlfe->next){if(nhlfe->type!=lsp_type)continue;if(!nhlfe_nhop_match(
nhlfe,gtype,gate,ifindex))break;}returnnhlfe;}/**AddNHLFE.Baseentrymusthavebeenc
reatedandduplicate*checkdone.*/staticzebra_nhlfe_t*nhlfe_add(zebra_lsp_t*lsp,enu
mlsp_types_tlsp_type,enumnexthop_types_tgtype,uniong_addr*gate,ifindex_tifindex,
mpls_label_tout_label){zebra_nhlfe_t*nhlfe;structnexthop*nexthop;if(!lsp)returnN
ULL;nhlfe=XCALLOC(MTYPE_NHLFE,sizeof(zebra_nhlfe_t));if(!nhlfe)returnNULL;nhlfe-
>lsp=lsp;nhlfe->type=lsp_type;nhlfe->distance=lsp_distance(lsp_type);nexthop=nex
thop_new();if(!nexthop){XFREE(MTYPE_NHLFE,nhlfe);returnNULL;}nexthop_add_labels(
nexthop,lsp_type,1,&out_label);nexthop->vrf_id=VRF_DEFAULT;nexthop->type=gtype;s
witch(nexthop->type){caseNEXTHOP_TYPE_IPV4:caseNEXTHOP_TYPE_IPV4_IFINDEX:nexthop
->gate.ipv4=gate->ipv4;if(ifindex)nexthop->ifindex=ifindex;break;caseNEXTHOP_TYP
E_IPV6:caseNEXTHOP_TYPE_IPV6_IFINDEX:nexthop->gate.ipv6=gate->ipv6;if(ifindex)ne
xthop->ifindex=ifindex;break;caseNEXTHOP_TYPE_IFINDEX:nexthop->ifindex=ifindex;b
reak;default:nexthop_free(nexthop);XFREE(MTYPE_NHLFE,nhlfe);returnNULL;break;}nh
lfe->nexthop=nexthop;if(lsp->nhlfe_list)lsp->nhlfe_list->prev=nhlfe;nhlfe->next=
lsp->nhlfe_list;lsp->nhlfe_list=nhlfe;returnnhlfe;}/**DeleteNHLFE.Entrymustbepre
sentonlist.*/staticintnhlfe_del(zebra_nhlfe_t*nhlfe){zebra_lsp_t*lsp;if(!nhlfe)r
eturn-1;lsp=nhlfe->lsp;if(!lsp)return-1;/*Freenexthop.*/if(nhlfe->nexthop)nextho
p_free(nhlfe->nexthop);/*UnlinkfromLSP*/if(nhlfe->next)nhlfe->next->prev=nhlfe->
prev;if(nhlfe->prev)nhlfe->prev->next=nhlfe->next;elselsp->nhlfe_list=nhlfe->nex
t;if(nhlfe==lsp->best_nhlfe)lsp->best_nhlfe=NULL;XFREE(MTYPE_NHLFE,nhlfe);return
0;}/**UpdatelabelforNHLFEentry.*/staticvoidnhlfe_out_label_update(zebra_nhlfe_t*
nhlfe,structmpls_label_stack*nh_label){nhlfe->nexthop->nh_label->label[0]=nh_lab
el->label[0];}staticintmpls_lsp_uninstall_all(structhash*lsp_table,zebra_lsp_t*l
sp,enumlsp_types_ttype){zebra_nhlfe_t*nhlfe,*nhlfe_next;intschedule_lsp=0;charbu
f[BUFSIZ];/*MarkNHLFEsfordeleteordirectlydelete,asappropriate.*/for(nhlfe=lsp->n
hlfe_list;nhlfe;nhlfe=nhlfe_next){nhlfe_next=nhlfe->next;/*Skipnon-staticNHLFEs*
/if(nhlfe->type!=type)continue;if(IS_ZEBRA_DEBUG_MPLS){nhlfe2str(nhlfe,buf,BUFSI
Z);zlog_debug("DelLSPin-label%utype%dnexthop%sflags0x%x",lsp->ile.in_label,type,
buf,nhlfe->flags);}if(CHECK_FLAG(nhlfe->flags,NHLFE_FLAG_INSTALLED)){UNSET_FLAG(
nhlfe->flags,NHLFE_FLAG_CHANGED);SET_FLAG(nhlfe->flags,NHLFE_FLAG_DELETED);sched
ule_lsp=1;}else{nhlfe_del(nhlfe);}}/*QueueLSPforprocessing,ifneeded,elsedelete.*
/if(schedule_lsp){if(lsp_processq_add(lsp))return-1;}elseif(!lsp->nhlfe_list&&!C
HECK_FLAG(lsp->flags,LSP_FLAG_SCHEDULED)){if(IS_ZEBRA_DEBUG_MPLS)zlog_debug("Fre
eLSPin-label%uflags0x%x",lsp->ile.in_label,lsp->flags);lsp=hash_release(lsp_tabl
e,&lsp->ile);if(lsp)XFREE(MTYPE_LSP,lsp);}return0;}/**UninstallallstaticNHLFEsfo
raparticularLSPforwardingentry.*IfnootherNHLFEsexist,theentrywouldbedeleted.*/st
aticintmpls_static_lsp_uninstall_all(structzebra_vrf*zvrf,mpls_label_tin_label){
structhash*lsp_table;zebra_ile_ttmp_ile;zebra_lsp_t*lsp;/*Lookuptable.*/lsp_tabl
e=zvrf->lsp_table;if(!lsp_table)return-1;/*Ifentryisnotpresent,exit.*/tmp_ile.in
_label=in_label;lsp=hash_lookup(lsp_table,&tmp_ile);if(!lsp||!lsp->nhlfe_list)re
turn0;returnmpls_lsp_uninstall_all(lsp_table,lsp,ZEBRA_LSP_STATIC);}staticjson_o
bject*nhlfe_json(zebra_nhlfe_t*nhlfe){charbuf[BUFSIZ];json_object*json_nhlfe=NUL
L;structnexthop*nexthop=nhlfe->nexthop;json_nhlfe=json_object_new_object();json_
object_string_add(json_nhlfe,"type",nhlfe_type2str(nhlfe->type));json_object_int
_add(json_nhlfe,"outLabel",nexthop->nh_label->label[0]);json_object_int_add(json
_nhlfe,"distance",nhlfe->distance);if(CHECK_FLAG(nhlfe->flags,NHLFE_FLAG_INSTALL
ED))json_object_boolean_true_add(json_nhlfe,"installed");switch(nexthop->type){c
aseNEXTHOP_TYPE_IPV4:caseNEXTHOP_TYPE_IPV4_IFINDEX:json_object_string_add(json_n
hlfe,"nexthop",inet_ntoa(nexthop->gate.ipv4));break;caseNEXTHOP_TYPE_IPV6:caseNE
XTHOP_TYPE_IPV6_IFINDEX:json_object_string_add(json_nhlfe,"nexthop",inet_ntop(AF
_INET6,&nexthop->gate.ipv6,buf,BUFSIZ));if(nexthop->ifindex)json_object_string_a
dd(json_nhlfe,"interface",ifindex2ifname(nexthop->ifindex,nexthop->vrf_id));brea
k;default:break;}returnjson_nhlfe;}/**PrinttheNHLFEforaLSPforwardingentry.*/stat
icvoidnhlfe_print(zebra_nhlfe_t*nhlfe,structvty*vty){structnexthop*nexthop;charb
uf[BUFSIZ];nexthop=nhlfe->nexthop;if(!nexthop||!nexthop->nh_label)//unexpectedre
turn;vty_out(vty,"type:%sremotelabel:%sdistance:%d\n",nhlfe_type2str(nhlfe->type
),label2str(nexthop->nh_label->label[0],buf,BUFSIZ),nhlfe->distance);switch(next
hop->type){caseNEXTHOP_TYPE_IPV4:caseNEXTHOP_TYPE_IPV4_IFINDEX:vty_out(vty,"via%
s",inet_ntoa(nexthop->gate.ipv4));if(nexthop->ifindex)vty_out(vty,"dev%s",ifinde
x2ifname(nexthop->ifindex,nexthop->vrf_id));break;caseNEXTHOP_TYPE_IPV6:caseNEXT
HOP_TYPE_IPV6_IFINDEX:vty_out(vty,"via%s",inet_ntop(AF_INET6,&nexthop->gate.ipv6
,buf,BUFSIZ));if(nexthop->ifindex)vty_out(vty,"dev%s",ifindex2ifname(nexthop->if
index,nexthop->vrf_id));break;default:break;}vty_out(vty,"%s",CHECK_FLAG(nhlfe->
flags,NHLFE_FLAG_INSTALLED)?"(installed)":"");vty_out(vty,"\n");}/**PrintanLSPfo
rwardingentry.*/staticvoidlsp_print(zebra_lsp_t*lsp,void*ctxt){zebra_nhlfe_t*nhl
fe;structvty*vty;vty=(structvty*)ctxt;vty_out(vty,"Locallabel:%u%s\n",lsp->ile.i
n_label,CHECK_FLAG(lsp->flags,LSP_FLAG_INSTALLED)?"(installed)":"");for(nhlfe=ls
p->nhlfe_list;nhlfe;nhlfe=nhlfe->next)nhlfe_print(nhlfe,vty);}/**JSONobjectsfora
nLSPforwardingentry.*/staticjson_object*lsp_json(zebra_lsp_t*lsp){zebra_nhlfe_t*
nhlfe=NULL;json_object*json=json_object_new_object();json_object*json_nhlfe_list
=json_object_new_array();json_object_int_add(json,"inLabel",lsp->ile.in_label);i
f(CHECK_FLAG(lsp->flags,LSP_FLAG_INSTALLED))json_object_boolean_true_add(json,"i
nstalled");for(nhlfe=lsp->nhlfe_list;nhlfe;nhlfe=nhlfe->next)json_object_array_a
dd(json_nhlfe_list,nhlfe_json(nhlfe));json_object_object_add(json,"nexthops",jso
n_nhlfe_list);returnjson;}/*Returnasortedlinkedlistofthehashcontents*/staticstru
ctlist*hash_get_sorted_list(structhash*hash,void*cmp){unsignedinti;structhash_ba
cket*hb;structlist*sorted_list=list_new();sorted_list->cmp=(int(*)(void*,void*))
cmp;for(i=0;i<hash->size;i++)for(hb=hash->index[i];hb;hb=hb->next)listnode_add_s
ort(sorted_list,hb->data);returnsorted_list;}/**ComparetwoLSPsbasedontheirlabelv
alues.*/staticintlsp_cmp(zebra_lsp_t*lsp1,zebra_lsp_t*lsp2){if(lsp1->ile.in_labe
l<lsp2->ile.in_label)return-1;if(lsp1->ile.in_label>lsp2->ile.in_label)return1;r
eturn0;}/**CallbacktoallocatestaticLSP.*/staticvoid*slsp_alloc(void*p){constzebr
a_ile_t*ile=p;zebra_slsp_t*slsp;slsp=XCALLOC(MTYPE_SLSP,sizeof(zebra_slsp_t));sl
sp->ile=*ile;return((void*)slsp);}/**ComparetwostaticLSPsbasedontheirlabelvalues
.*/staticintslsp_cmp(zebra_slsp_t*slsp1,zebra_slsp_t*slsp2){if(slsp1->ile.in_lab
el<slsp2->ile.in_label)return-1;if(slsp1->ile.in_label>slsp2->ile.in_label)retur
n1;return0;}/**CheckifstaticNHLFEmatcheswithsearchinfopassed.*/staticintsnhlfe_m
atch(zebra_snhlfe_t*snhlfe,enumnexthop_types_tgtype,uniong_addr*gate,ifindex_tif
index){intcmp=1;if(snhlfe->gtype!=gtype)return1;switch(snhlfe->gtype){caseNEXTHO
P_TYPE_IPV4:cmp=memcmp(&(snhlfe->gate.ipv4),&(gate->ipv4),sizeof(structin_addr))
;break;caseNEXTHOP_TYPE_IPV6:caseNEXTHOP_TYPE_IPV6_IFINDEX:cmp=memcmp(&(snhlfe->
gate.ipv6),&(gate->ipv6),sizeof(structin6_addr));if(!cmp&&snhlfe->gtype==NEXTHOP
_TYPE_IPV6_IFINDEX)cmp=!(snhlfe->ifindex==ifindex);break;default:break;}returncm
p;}/**LocatestaticNHLFEthatmatcheswithpassedinfo.*/staticzebra_snhlfe_t*snhlfe_f
ind(zebra_slsp_t*slsp,enumnexthop_types_tgtype,uniong_addr*gate,ifindex_tifindex
){zebra_snhlfe_t*snhlfe;if(!slsp)returnNULL;for(snhlfe=slsp->snhlfe_list;snhlfe;
snhlfe=snhlfe->next){if(!snhlfe_match(snhlfe,gtype,gate,ifindex))break;}returnsn
hlfe;}/**AddstaticNHLFE.BaseLSPconfigentrymusthavebeencreated*andduplicatecheckd
one.*/staticzebra_snhlfe_t*snhlfe_add(zebra_slsp_t*slsp,enumnexthop_types_tgtype
,uniong_addr*gate,ifindex_tifindex,mpls_label_tout_label){zebra_snhlfe_t*snhlfe;
if(!slsp)returnNULL;snhlfe=XCALLOC(MTYPE_SNHLFE,sizeof(zebra_snhlfe_t));snhlfe->
slsp=slsp;snhlfe->out_label=out_label;snhlfe->gtype=gtype;switch(gtype){caseNEXT
HOP_TYPE_IPV4:snhlfe->gate.ipv4=gate->ipv4;break;caseNEXTHOP_TYPE_IPV6:caseNEXTH
OP_TYPE_IPV6_IFINDEX:snhlfe->gate.ipv6=gate->ipv6;if(ifindex)snhlfe->ifindex=ifi
ndex;break;default:XFREE(MTYPE_SNHLFE,snhlfe);returnNULL;}if(slsp->snhlfe_list)s
lsp->snhlfe_list->prev=snhlfe;snhlfe->next=slsp->snhlfe_list;slsp->snhlfe_list=s
nhlfe;returnsnhlfe;}/**DeletestaticNHLFE.Entrymustbepresentonlist.*/staticintsnh
lfe_del(zebra_snhlfe_t*snhlfe){zebra_slsp_t*slsp;if(!snhlfe)return-1;slsp=snhlfe
->slsp;if(!slsp)return-1;if(snhlfe->next)snhlfe->next->prev=snhlfe->prev;if(snhl
fe->prev)snhlfe->prev->next=snhlfe->next;elseslsp->snhlfe_list=snhlfe->next;snhl
fe->prev=snhlfe->next=NULL;if(snhlfe->ifname)XFREE(MTYPE_SNHLFE_IFNAME,snhlfe->i
fname);XFREE(MTYPE_SNHLFE,snhlfe);return0;}/**DeleteallstaticNHLFEentriesforthis
LSP(inlabel).*/staticintsnhlfe_del_all(zebra_slsp_t*slsp){zebra_snhlfe_t*snhlfe,
*snhlfe_next;if(!slsp)return-1;for(snhlfe=slsp->snhlfe_list;snhlfe;snhlfe=snhlfe
_next){snhlfe_next=snhlfe->next;snhlfe_del(snhlfe);}return0;}/**Createprintables
tringforNHLFEconfiguration.*/staticchar*snhlfe2str(zebra_snhlfe_t*snhlfe,char*bu
f,intsize){buf[0]='\0';switch(snhlfe->gtype){caseNEXTHOP_TYPE_IPV4:inet_ntop(AF_
INET,&snhlfe->gate.ipv4,buf,size);break;caseNEXTHOP_TYPE_IPV6:caseNEXTHOP_TYPE_I
PV6_IFINDEX:inet_ntop(AF_INET6,&snhlfe->gate.ipv6,buf,size);if(snhlfe->ifindex)s
trcat(buf,ifindex2ifname(snhlfe->ifindex,VRF_DEFAULT));break;default:break;}retu
rnbuf;}/**InitializeworkqueueforprocessingchangedLSPs.*/staticintmpls_processq_i
nit(structzebra_t*zebra){zebra->lsp_process_q=work_queue_new(zebra->master,"LSPp
rocessing");if(!zebra->lsp_process_q){zlog_err("%s:couldnotinitialiseworkqueue!"
,__func__);return-1;}zebra->lsp_process_q->spec.workfunc=&lsp_process;zebra->lsp
_process_q->spec.del_item_data=&lsp_processq_del;zebra->lsp_process_q->spec.erro
rfunc=NULL;zebra->lsp_process_q->spec.completion_func=&lsp_processq_complete;zeb
ra->lsp_process_q->spec.max_retries=0;zebra->lsp_process_q->spec.hold=10;return0
;}/*Publicfunctions*/voidkernel_lsp_pass_fail(zebra_lsp_t*lsp,enumsouthbound_res
ultsres){structnexthop*nexthop;zebra_nhlfe_t*nhlfe;if(!lsp)return;switch(res){ca
seSOUTHBOUND_INSTALL_FAILURE:UNSET_FLAG(lsp->flags,LSP_FLAG_INSTALLED);clear_nhl
fe_installed(lsp);zlog_warn("LSPInstallFailure:%u",lsp->ile.in_label);break;case
SOUTHBOUND_INSTALL_SUCCESS:SET_FLAG(lsp->flags,LSP_FLAG_INSTALLED);for(nhlfe=lsp
->nhlfe_list;nhlfe;nhlfe=nhlfe->next){nexthop=nhlfe->nexthop;if(!nexthop)continu
e;SET_FLAG(nhlfe->flags,NHLFE_FLAG_INSTALLED);SET_FLAG(nexthop->flags,NEXTHOP_FL
AG_FIB);}break;caseSOUTHBOUND_DELETE_SUCCESS:UNSET_FLAG(lsp->flags,LSP_FLAG_INST
ALLED);clear_nhlfe_installed(lsp);break;caseSOUTHBOUND_DELETE_FAILURE:zlog_warn(
"LSPDeletionFailure:%u",lsp->ile.in_label);break;}}/**Stringtolabelconversion,la
belsseparatedby'/'.**@paramlabel_strlabelsseparatedby/*@paramnum_labelsnumberofl
abels;zeroifconversionwasunsuccessful*@paramlabelspreallocatedmpls_label_tarrayo
fsizeMPLS_MAX_LABELS;only*modifiediftheconversionsucceeded*@return0onsuccess*-1i
fthestringcouldnotbeparsedasintegers*-2ifalabelwasinsidethereservedrange(0-15)*-
3ifthenumberoflabelsgivenexceedsMPLS_MAX_LABELS*/intmpls_str2label(constchar*lab
el_str,uint8_t*num_labels,mpls_label_t*labels){char*ostr;//copyoflabelstring(sta
rt)char*lstr;//copyoflabelstringchar*nump;//pointertonextsegmentchar*endp;//endp
ointerinti;//foriteratinglabel_strintrc;//returncodempls_label_tpl[MPLS_MAX_LABE
LS];//parsedlabels/*labelstozerountilwehaveasuccessfulparse*/ostr=lstr=XSTRDUP(M
TYPE_TMP,label_str);*num_labels=0;rc=0;for(i=0;i<MPLS_MAX_LABELS&&lstr&&!rc;i++)
{nump=strsep(&lstr,"/");pl[i]=strtoul(nump,&endp,10);/*formatcheck*/if(*endp!='\
0')rc=-1;/*validitycheck*/elseif(!IS_MPLS_UNRESERVED_LABEL(pl[i]))rc=-2;}/*exces
slabels*/if(!rc&&i==MPLS_MAX_LABELS&&lstr)rc=-3;if(!rc){*num_labels=i;memcpy(lab
els,pl,*num_labels*sizeof(mpls_label_t));}XFREE(MTYPE_TMP,ostr);returnrc;}/**Lab
eltostringconversion,labelsinstringseparatedby'/'.*/char*mpls_label2str(uint8_tn
um_labels,mpls_label_t*labels,char*buf,intlen,intpretty){charlabel_buf[BUFSIZ];i
nti;buf[0]='\0';for(i=0;i<num_labels;i++){if(i!=0)strlcat(buf,"/",len);if(pretty
)label2str(labels[i],label_buf,sizeof(label_buf));elsesnprintf(label_buf,sizeof(
label_buf),"%u",labels[i]);strlcat(buf,label_buf,len);}returnbuf;}/**Installdyna
micLSPentry.*/intzebra_mpls_lsp_install(structzebra_vrf*zvrf,structroute_node*rn
,structroute_entry*re){structroute_table*table;zebra_fec_t*fec;table=zvrf->fec_t
able[family2afi(PREFIX_FAMILY(&rn->p))];if(!table)return-1;/*Seeifthereisaconfig
uredlabelbindingforthisFEC.*/fec=fec_find(table,&rn->p);if(!fec||fec->label==MPL
S_INVALID_LABEL)return0;/*Wecannotinstallalabelforwardingentryiflocallabelisthe*
implicit-nulllabel.*/if(fec->label==MPLS_LABEL_IMPLICIT_NULL)return0;if(lsp_inst
all(zvrf,fec->label,rn,re))return-1;return0;}/**UninstalldynamicLSPentry,ifany.*
/intzebra_mpls_lsp_uninstall(structzebra_vrf*zvrf,structroute_node*rn,structrout
e_entry*re){structroute_table*table;zebra_fec_t*fec;table=zvrf->fec_table[family
2afi(PREFIX_FAMILY(&rn->p))];if(!table)return-1;/*Seeifthereisaconfiguredlabelbi
ndingforthisFEC.*/fec=fec_find(table,&rn->p);if(!fec||fec->label==MPLS_INVALID_L
ABEL)return0;/*UninstallalwaysremovesalldynamicNHLFEs.*/returnlsp_uninstall(zvrf
,fec->label);}/**RegistrationfromaclientforthelabelbindingforaFEC.Ifabinding*alr
eadyexists,itisinformedtotheclient.*NOTE:Ifthereisamanuallyconfiguredlabelbindin
g,thatisused.*Otherwise,ifalabelindexisspecified,itmeanswehavetoallocatethe*labe
lfromalocallyconfiguredlabelblock(SRGB),ifoneexistsandindex*isacceptable.*/intze
bra_mpls_fec_register(structzebra_vrf*zvrf,structprefix*p,uint32_tlabel_index,st
ructzserv*client){structroute_table*table;zebra_fec_t*fec;charbuf[BUFSIZ];intnew
_client;intlabel_change=0;uint32_told_label;table=zvrf->fec_table[family2afi(PRE
FIX_FAMILY(p))];if(!table)return-1;if(IS_ZEBRA_DEBUG_MPLS)prefix2str(p,buf,BUFSI
Z);/*LocateFEC*/fec=fec_find(table,p);if(!fec){fec=fec_add(table,p,MPLS_INVALID_
LABEL,0,label_index);if(!fec){prefix2str(p,buf,BUFSIZ);zlog_err("FailedtoaddFEC%
suponregister,client%s",buf,zebra_route_string(client->proto));return-1;}old_lab
el=MPLS_INVALID_LABEL;new_client=1;}else{/*ClientmayregistersameFECwithdifferent
labelindex.*/new_client=(listnode_lookup(fec->client_list,client)==NULL);if(!new
_client&&fec->label_index==label_index)/*Duplicateregister*/return0;/*Savecurren
tlabel,updatelabelindex*/old_label=fec->label;fec->label_index=label_index;}if(n
ew_client)listnode_add(fec->client_list,client);if(IS_ZEBRA_DEBUG_MPLS)zlog_debu
g("FEC%sLabelIndex%u%sbyclient%s",buf,label_index,new_client?"registered":"updat
ed",zebra_route_string(client->proto));/*IfnotaconfiguredFEC,derivethelocallabel
(fromlabelindex)*orresetit.*/if(!(fec->flags&FEC_FLAG_CONFIGURED)){fec_derive_la
bel_from_index(zvrf,fec);/*Ifnolabelchange,exit.*/if(fec->label==old_label)retur
n0;label_change=1;}/*Ifnewclientorlabelchange,updateclientandinstalloruninstall*
labelforwardingentryasneeded.*//*Informclientoflabel,ifneeded.*/if((new_client&&
fec->label!=MPLS_INVALID_LABEL)||label_change){if(IS_ZEBRA_DEBUG_MPLS)zlog_debug
("Updateclientlabel%u",fec->label);fec_send(fec,client);}if(new_client||label_ch
ange)returnfec_change_update_lsp(zvrf,fec,old_label);return0;}/**Deregistrationf
romaclientforthelabelbindingforaFEC.TheFEC*itselfisdeletedifnootherregisteredcli
entsexistandthereisno*labelboundtotheFEC.*/intzebra_mpls_fec_unregister(structze
bra_vrf*zvrf,structprefix*p,structzserv*client){structroute_table*table;zebra_fe
c_t*fec;charbuf[BUFSIZ];table=zvrf->fec_table[family2afi(PREFIX_FAMILY(p))];if(!
table)return-1;if(IS_ZEBRA_DEBUG_MPLS)prefix2str(p,buf,BUFSIZ);fec=fec_find(tabl
e,p);if(!fec){prefix2str(p,buf,BUFSIZ);zlog_err("FailedtofindFEC%suponunregister
,client%s",buf,zebra_route_string(client->proto));return-1;}listnode_delete(fec-
>client_list,client);if(IS_ZEBRA_DEBUG_MPLS)zlog_debug("FEC%sunregisteredbyclien
t%s",buf,zebra_route_string(client->proto));/*Ifnotaconfiguredentry,deletetheFEC
ifnootherclients.Before*deleting,seeifanyLSPneedstobeuninstalled.*/if(!(fec->fla
gs&FEC_FLAG_CONFIGURED)&&list_isempty(fec->client_list)){mpls_label_told_label=f
ec->label;fec->label=MPLS_INVALID_LABEL;/*reset*/fec_change_update_lsp(zvrf,fec,
old_label);fec_del(fec);}return0;}/**CleanupanyFECsregisteredbythisclient.*/intz
ebra_mpls_cleanup_fecs_for_client(structzebra_vrf*zvrf,structzserv*client){struc
troute_node*rn;zebra_fec_t*fec;structlistnode*node;structzserv*fec_client;intaf;
for(af=AFI_IP;af<AFI_MAX;af++){if(zvrf->fec_table[af]==NULL)continue;for(rn=rout
e_top(zvrf->fec_table[af]);rn;rn=route_next(rn)){fec=rn->info;if(!fec||list_isem
pty(fec->client_list))continue;for(ALL_LIST_ELEMENTS_RO(fec->client_list,node,fe
c_client)){if(fec_client==client){listnode_delete(fec->client_list,fec_client);i
f(!(fec->flags&FEC_FLAG_CONFIGURED)&&list_isempty(fec->client_list))fec_del(fec)
;break;}}}}return0;}/**ReturnFEC(ifany)towhichthislabelisbound.*Note:Onlyworksfo
rper-prefixbindingandwhenthelabelisnot*implicit-null.*TODO:Currentlywalksentiret
able,canoptimizelaterwithanother*hash..*/zebra_fec_t*zebra_mpls_fec_for_label(st
ructzebra_vrf*zvrf,mpls_label_tlabel){structroute_node*rn;zebra_fec_t*fec;intaf;
for(af=AFI_IP;af<AFI_MAX;af++){if(zvrf->fec_table[af]==NULL)continue;for(rn=rout
e_top(zvrf->fec_table[af]);rn;rn=route_next(rn)){if(!rn->info)continue;fec=rn->i
nfo;if(fec->label==label)returnfec;}}returnNULL;}/**Informifspecifiedlabeliscurr
entlyboundtoaFECornot.*/intzebra_mpls_label_already_bound(structzebra_vrf*zvrf,m
pls_label_tlabel){return(zebra_mpls_fec_for_label(zvrf,label)?1:0);}/**Addstatic
FECtolabelbinding.Ifthereareclientsregisteredforthis*FEC,notifythem.Iftherearela
beledroutesforthisFEC,installthe*labelforwardingentry.*/intzebra_mpls_static_fec
_add(structzebra_vrf*zvrf,structprefix*p,mpls_label_tin_label){structroute_table
*table;zebra_fec_t*fec;charbuf[BUFSIZ];mpls_label_told_label;intret=0;table=zvrf
->fec_table[family2afi(PREFIX_FAMILY(p))];if(!table)return-1;if(IS_ZEBRA_DEBUG_M
PLS)prefix2str(p,buf,BUFSIZ);/*UpdateexistingFECorcreateanewone.*/fec=fec_find(t
able,p);if(!fec){fec=fec_add(table,p,in_label,FEC_FLAG_CONFIGURED,MPLS_INVALID_L
ABEL_INDEX);if(!fec){prefix2str(p,buf,BUFSIZ);zlog_err("FailedtoaddFEC%suponconf
ig",buf);return-1;}if(IS_ZEBRA_DEBUG_MPLS)zlog_debug("Addfec%slabel%u",buf,in_la
bel);}else{fec->flags|=FEC_FLAG_CONFIGURED;if(fec->label==in_label)/*Duplicateco
nfig*/return0;/*Labelchange,updateclients.*/old_label=fec->label;if(IS_ZEBRA_DEB
UG_MPLS)zlog_debug("Updatefec%snewlabel%u",buf,in_label);fec->label=in_label;fec
_update_clients(fec);/*Updatelabelforwardingentriesappropriately*/ret=fec_change
_update_lsp(zvrf,fec,old_label);}returnret;}/**RemovestaticFECtolabelbinding.Ift
herearenoclientsregistered*forthisFEC,deletetheFEC;elsenotifyclients*Note:Uponde
leteofstaticbinding,iflabelindexexistsforthisFEC,*clientmayneedtobeupdatedwithde
rivedlabel.*/intzebra_mpls_static_fec_del(structzebra_vrf*zvrf,structprefix*p){s
tructroute_table*table;zebra_fec_t*fec;mpls_label_told_label;charbuf[BUFSIZ];tab
le=zvrf->fec_table[family2afi(PREFIX_FAMILY(p))];if(!table)return-1;fec=fec_find
(table,p);if(!fec){prefix2str(p,buf,BUFSIZ);zlog_err("FailedtofindFEC%supondelet
e",buf);return-1;}if(IS_ZEBRA_DEBUG_MPLS){prefix2str(p,buf,BUFSIZ);zlog_debug("D
eletefec%slabelindex%u",buf,fec->label_index);}old_label=fec->label;fec->flags&=
~FEC_FLAG_CONFIGURED;fec->label=MPLS_INVALID_LABEL;/*Ifnoclientexists,justdelete
theFEC.*/if(list_isempty(fec->client_list)){fec_del(fec);return0;}/*Derivetheloc
allabel(fromlabelindex)orresetit.*/fec_derive_label_from_index(zvrf,fec);/*Ifthe
reisalabelchange,updateclients.*/if(fec->label==old_label)return0;fec_update_cli
ents(fec);/*Updatelabelforwardingentriesappropriately*/returnfec_change_update_l
sp(zvrf,fec,old_label);}/**DisplayMPLSFECtolabelbindingconfiguration(VTYcommandh
andler).*/intzebra_mpls_write_fec_config(structvty*vty,structzebra_vrf*zvrf){str
uctroute_node*rn;intaf;zebra_fec_t*fec;charbuf[BUFSIZ];intwrite=0;for(af=AFI_IP;
af<AFI_MAX;af++){if(zvrf->fec_table[af]==NULL)continue;for(rn=route_top(zvrf->fe
c_table[af]);rn;rn=route_next(rn)){if(!rn->info)continue;charlstr[BUFSIZ];fec=rn
->info;if(!(fec->flags&FEC_FLAG_CONFIGURED))continue;write=1;prefix2str(&rn->p,b
uf,BUFSIZ);vty_out(vty,"mplslabelbind%s%s\n",buf,label2str(fec->label,lstr,BUFSI
Z));}}returnwrite;}/**DisplayMPLSFECtolabelbinding(VTYcommandhandler).*/voidzebr
a_mpls_print_fec_table(structvty*vty,structzebra_vrf*zvrf){structroute_node*rn;i
ntaf;for(af=AFI_IP;af<AFI_MAX;af++){if(zvrf->fec_table[af]==NULL)continue;for(rn
=route_top(zvrf->fec_table[af]);rn;rn=route_next(rn)){if(!rn->info)continue;fec_
print(rn->info,vty);}}}/**DisplayMPLSFECtolabelbindingforaspecificFEC(VTYcommand
handler).*/voidzebra_mpls_print_fec(structvty*vty,structzebra_vrf*zvrf,structpre
fix*p){structroute_table*table;structroute_node*rn;table=zvrf->fec_table[family2
afi(PREFIX_FAMILY(p))];if(!table)return;apply_mask(p);rn=route_node_lookup(table
,p);if(!rn)return;route_unlock_node(rn);if(!rn->info)return;fec_print(rn->info,v
ty);}staticboolmpls_ftn_update_nexthop(intadd,structnexthop*nexthop,enumlsp_type
s_ttype,mpls_label_tlabel){if(add&&nexthop->nh_label_type==ZEBRA_LSP_NONE)nextho
p_add_labels(nexthop,type,1,&label);elseif(!add&&nexthop->nh_label_type==type)ne
xthop_del_labels(nexthop);elsereturnfalse;returntrue;}/**Install/uninstallaFEC-T
o-NHLFE(FTN)binding.*/intmpls_ftn_update(intadd,structzebra_vrf*zvrf,enumlsp_typ
es_ttype,structprefix*prefix,enumnexthop_types_tgtype,uniong_addr*gate,ifindex_t
ifindex,uint8_tdistance,mpls_label_tout_label){structroute_table*table;structrou
te_node*rn;structroute_entry*re;structnexthop*nexthop;boolfound;/*Lookuptable.*/
table=zebra_vrf_table(family2afi(prefix->family),SAFI_UNICAST,zvrf_id(zvrf));if(
!table)return-1;/*Lookupexistingroute*/rn=route_node_get(table,prefix);RNODE_FOR
EACH_RE(rn,re){if(CHECK_FLAG(re->status,ROUTE_ENTRY_REMOVED))continue;if(re->dis
tance==distance)break;}if(re==NULL)return-1;found=false;for(nexthop=re->ng.nexth
op;nexthop;nexthop=nexthop->next){switch(nexthop->type){caseNEXTHOP_TYPE_IPV4:ca
seNEXTHOP_TYPE_IPV4_IFINDEX:if(gtype!=NEXTHOP_TYPE_IPV4&&gtype!=NEXTHOP_TYPE_IPV
4_IFINDEX)continue;if(!IPV4_ADDR_SAME(&nexthop->gate.ipv4,&gate->ipv4))continue;
if(nexthop->type==NEXTHOP_TYPE_IPV4_IFINDEX&&nexthop->ifindex!=ifindex)continue;
if(!mpls_ftn_update_nexthop(add,nexthop,type,out_label))return0;found=true;break
;caseNEXTHOP_TYPE_IPV6:caseNEXTHOP_TYPE_IPV6_IFINDEX:if(gtype!=NEXTHOP_TYPE_IPV6
&&gtype!=NEXTHOP_TYPE_IPV6_IFINDEX)continue;if(!IPV6_ADDR_SAME(&nexthop->gate.ip
v6,&gate->ipv6))continue;if(nexthop->type==NEXTHOP_TYPE_IPV6_IFINDEX&&nexthop->i
findex!=ifindex)continue;if(!mpls_ftn_update_nexthop(add,nexthop,type,out_label)
)return0;found=true;break;default:break;}}if(!found)return-1;SET_FLAG(re->status
,ROUTE_ENTRY_CHANGED);SET_FLAG(re->status,ROUTE_ENTRY_LABELS_CHANGED);rib_queue_
add(rn);return0;}/**Install/updateaNHLFEforanLSPintheforwardingtable.Thismaybe*a
newLSPentryoranewNHLFEforanexistingin-labeloranupdateof*theout-labelforanexistin
gNHLFE(updatecase).*/intmpls_lsp_install(structzebra_vrf*zvrf,enumlsp_types_ttyp
e,mpls_label_tin_label,mpls_label_tout_label,enumnexthop_types_tgtype,uniong_add
r*gate,ifindex_tifindex){structhash*lsp_table;zebra_ile_ttmp_ile;zebra_lsp_t*lsp
;zebra_nhlfe_t*nhlfe;charbuf[BUFSIZ];/*Lookuptable.*/lsp_table=zvrf->lsp_table;i
f(!lsp_table)return-1;/*Ifentryispresent,exit.*/tmp_ile.in_label=in_label;lsp=ha
sh_get(lsp_table,&tmp_ile,lsp_alloc);if(!lsp)return-1;nhlfe=nhlfe_find(lsp,type,
gtype,gate,ifindex);if(nhlfe){structnexthop*nh=nhlfe->nexthop;assert(nh);assert(
nh->nh_label);/*Cleardeletedflag(incaseitwasset)*/UNSET_FLAG(nhlfe->flags,NHLFE_
FLAG_DELETED);if(nh->nh_label->label[0]==out_label)/*Nochange*/return0;if(IS_ZEB
RA_DEBUG_MPLS){nhlfe2str(nhlfe,buf,BUFSIZ);zlog_debug("LSPin-label%utype%dnextho
p%s""out-labelchangedto%u(old%u)",in_label,type,buf,out_label,nh->nh_label->labe
l[0]);}/*Updateoutlabel,triggerprocessing.*/nh->nh_label->label[0]=out_label;}el
se{/*AddLSPentrytothisnexthop*/nhlfe=nhlfe_add(lsp,type,gtype,gate,ifindex,out_l
abel);if(!nhlfe)return-1;if(IS_ZEBRA_DEBUG_MPLS){nhlfe2str(nhlfe,buf,BUFSIZ);zlo
g_debug("AddLSPin-label%utype%dnexthop%s""out-label%u",in_label,type,buf,out_lab
el);}lsp->addr_family=NHLFE_FAMILY(nhlfe);}/*MarkNHLFE,queueLSPforprocessing.*/S
ET_FLAG(nhlfe->flags,NHLFE_FLAG_CHANGED);if(lsp_processq_add(lsp))return-1;retur
n0;}/**UninstallaparticularNHLFEintheforwardingtable.Ifthisis*theonlyNHLFE,theen
tireLSPforwardingentryhastobedeleted.*/intmpls_lsp_uninstall(structzebra_vrf*zvr
f,enumlsp_types_ttype,mpls_label_tin_label,enumnexthop_types_tgtype,uniong_addr*
gate,ifindex_tifindex){structhash*lsp_table;zebra_ile_ttmp_ile;zebra_lsp_t*lsp;z
ebra_nhlfe_t*nhlfe;charbuf[BUFSIZ];/*Lookuptable.*/lsp_table=zvrf->lsp_table;if(
!lsp_table)return-1;/*Ifentryisnotpresent,exit.*/tmp_ile.in_label=in_label;lsp=h
ash_lookup(lsp_table,&tmp_ile);if(!lsp)return0;nhlfe=nhlfe_find(lsp,type,gtype,g
ate,ifindex);if(!nhlfe)return0;if(IS_ZEBRA_DEBUG_MPLS){nhlfe2str(nhlfe,buf,BUFSI
Z);zlog_debug("DelLSPin-label%utype%dnexthop%sflags0x%x",in_label,type,buf,nhlfe
->flags);}/*MarkNHLFEfordeleteordirectlydelete,asappropriate.*/if(CHECK_FLAG(nhl
fe->flags,NHLFE_FLAG_INSTALLED)){UNSET_FLAG(nhlfe->flags,NHLFE_FLAG_CHANGED);SET
_FLAG(nhlfe->flags,NHLFE_FLAG_DELETED);if(lsp_processq_add(lsp))return-1;}else{n
hlfe_del(nhlfe);/*FreeLSPentryifnootherNHLFEsandnotscheduled.*/if(!lsp->nhlfe_li
st&&!CHECK_FLAG(lsp->flags,LSP_FLAG_SCHEDULED)){if(IS_ZEBRA_DEBUG_MPLS)zlog_debu
g("FreeLSPin-label%uflags0x%x",lsp->ile.in_label,lsp->flags);lsp=hash_release(ls
p_table,&lsp->ile);if(lsp)XFREE(MTYPE_LSP,lsp);}}return0;}/**UninstallallLDPNHLF
EsforaparticularLSPforwardingentry.*IfnootherNHLFEsexist,theentrywouldbedeleted.
*/voidmpls_ldp_lsp_uninstall_all(structhash_backet*backet,void*ctxt){zebra_lsp_t
*lsp;structhash*lsp_table;lsp=(zebra_lsp_t*)backet->data;if(!lsp||!lsp->nhlfe_li
st)return;lsp_table=ctxt;if(!lsp_table)return;mpls_lsp_uninstall_all(lsp_table,l
sp,ZEBRA_LSP_LDP);}/**UninstallallLDPFEC-To-NHLFE(FTN)bindingsofthegivenaddress-
family.*/voidmpls_ldp_ftn_uninstall_all(structzebra_vrf*zvrf,intafi){structroute
_table*table;structroute_node*rn;structroute_entry*re;structnexthop*nexthop;intu
pdate;/*Processroutesofinterestedaddress-families.*/table=zebra_vrf_table(afi,SA
FI_UNICAST,zvrf_id(zvrf));if(!table)return;for(rn=route_top(table);rn;rn=route_n
ext(rn)){update=0;RNODE_FOREACH_RE(rn,re){for(nexthop=re->ng.nexthop;nexthop;nex
thop=nexthop->next){if(nexthop->nh_label_type!=ZEBRA_LSP_LDP)continue;nexthop_de
l_labels(nexthop);SET_FLAG(re->status,ROUTE_ENTRY_CHANGED);SET_FLAG(re->status,R
OUTE_ENTRY_LABELS_CHANGED);update=1;}}if(update)rib_queue_add(rn);}}#ifdefined(H
AVE_CUMULUS)/**CheckthatthelabelvaluesusedinLSPcreationareconsistent.The*maincri
teriaisthatifthereisECMP,thelabeloperationmuststill*beconsistent-i.e.,allpathsei
therdoaswapordoPHP.Thisisdue*tocurrentHWrestrictions.*/intzebra_mpls_lsp_label_c
onsistent(structzebra_vrf*zvrf,mpls_label_tin_label,mpls_label_tout_label,enumne
xthop_types_tgtype,uniong_addr*gate,ifindex_tifindex){structhash*slsp_table;zebr
a_ile_ttmp_ile;zebra_slsp_t*slsp;zebra_snhlfe_t*snhlfe;/*Lookuptable.*/slsp_tabl
e=zvrf->slsp_table;if(!slsp_table)return0;/*Ifentryisnotpresent,exit.*/tmp_ile.i
n_label=in_label;slsp=hash_lookup(slsp_table,&tmp_ile);if(!slsp)return1;snhlfe=s
nhlfe_find(slsp,gtype,gate,ifindex);if(snhlfe){if(snhlfe->out_label==out_label)r
eturn1;/*IfnotonlyNHLFE,cannotallowlabelchange.*/if(snhlfe!=slsp->snhlfe_list||s
nhlfe->next)return0;}else{/*IfotherNHLFEsexist,labeloperationmustmatch.*/if(slsp
->snhlfe_list){intcur_op,new_op;cur_op=(slsp->snhlfe_list->out_label==MPLS_LABEL
_IMPLICIT_NULL);new_op=(out_label==MPLS_LABEL_IMPLICIT_NULL);if(cur_op!=new_op)r
eturn0;}}/*Labelvaluesaregood.*/return1;}#endif/*HAVE_CUMULUS*//**AddstaticLSPen
try.Thismaybethefirstentryforthisincominglabel*oranadditionalnexthop;anexistinge
ntrymayalsohaveoutgoinglabel*changed.*Note:Thelabeloperation(swaporPHP)iscommonf
ortheLSPentry(all*NHLFEs).*/intzebra_mpls_static_lsp_add(structzebra_vrf*zvrf,mp
ls_label_tin_label,mpls_label_tout_label,enumnexthop_types_tgtype,uniong_addr*ga
te,ifindex_tifindex){structhash*slsp_table;zebra_ile_ttmp_ile;zebra_slsp_t*slsp;
zebra_snhlfe_t*snhlfe;charbuf[BUFSIZ];/*Lookuptable.*/slsp_table=zvrf->slsp_tabl
e;if(!slsp_table)return-1;/*Ifentryispresent,exit.*/tmp_ile.in_label=in_label;sl
sp=hash_get(slsp_table,&tmp_ile,slsp_alloc);if(!slsp)return-1;snhlfe=snhlfe_find
(slsp,gtype,gate,ifindex);if(snhlfe){if(snhlfe->out_label==out_label)/*Nochange*
/return0;if(IS_ZEBRA_DEBUG_MPLS){snhlfe2str(snhlfe,buf,BUFSIZ);zlog_debug("Updst
aticLSPin-label%unexthop%s""out-label%u(old%u)",in_label,buf,out_label,snhlfe->o
ut_label);}snhlfe->out_label=out_label;}else{/*AddstaticLSPentrytothisnexthop*/s
nhlfe=snhlfe_add(slsp,gtype,gate,ifindex,out_label);if(!snhlfe)return-1;if(IS_ZE
BRA_DEBUG_MPLS){snhlfe2str(snhlfe,buf,BUFSIZ);zlog_debug("AddstaticLSPin-label%u
nexthop%sout-label%u",in_label,buf,out_label);}}/*(Re)InstallLSPinthemaintable.*
/if(mpls_lsp_install(zvrf,ZEBRA_LSP_STATIC,in_label,out_label,gtype,gate,ifindex
))return-1;return0;}/**DeletestaticLSPentry.Thismaybethedeleteofoneparticular*NH
LFEforthisincominglabelorthedeleteoftheentireentry(i.e.,*allNHLFEs).*NOTE:Delete
oftheonlyNHLFEwillalsoendupdeletingtheentire*LSPconfiguration.*/intzebra_mpls_st
atic_lsp_del(structzebra_vrf*zvrf,mpls_label_tin_label,enumnexthop_types_tgtype,
uniong_addr*gate,ifindex_tifindex){structhash*slsp_table;zebra_ile_ttmp_ile;zebr
a_slsp_t*slsp;zebra_snhlfe_t*snhlfe;/*Lookuptable.*/slsp_table=zvrf->slsp_table;
if(!slsp_table)return-1;/*Ifentryisnotpresent,exit.*/tmp_ile.in_label=in_label;s
lsp=hash_lookup(slsp_table,&tmp_ile);if(!slsp)return0;/*IsitdeleteofentireLSPora
specificNHLFE?*/if(gtype==NEXTHOP_TYPE_BLACKHOLE){if(IS_ZEBRA_DEBUG_MPLS)zlog_de
bug("DelstaticLSPin-label%u",in_label);/*UninstallentireLSPfromthemaintable.*/mp
ls_static_lsp_uninstall_all(zvrf,in_label);/*DeleteallstaticNHLFEs*/snhlfe_del_a
ll(slsp);}else{/*FindspecificNHLFE,exitifnotfound.*/snhlfe=snhlfe_find(slsp,gtyp
e,gate,ifindex);if(!snhlfe)return0;if(IS_ZEBRA_DEBUG_MPLS){charbuf[BUFSIZ];snhlf
e2str(snhlfe,buf,BUFSIZ);zlog_debug("DelstaticLSPin-label%unexthop%s",in_label,b
uf);}/*UninstallLSPfromthemaintable.*/mpls_lsp_uninstall(zvrf,ZEBRA_LSP_STATIC,i
n_label,gtype,gate,ifindex);/*DeletestaticLSPNHLFE*/snhlfe_del(snhlfe);}/*Remove
entirestaticLSPentryifnoNHLFE-validineithercase*above.*/if(!slsp->snhlfe_list){s
lsp=hash_release(slsp_table,&tmp_ile);if(slsp)XFREE(MTYPE_SLSP,slsp);}return0;}/
**ScheduleallMPLSlabelforwardingentriesforprocessing.*Calleduponchangesthatmayaf
fectoneormoreofthemsuchas*interfaceornexthopstatechanges.*/voidzebra_mpls_lsp_sc
hedule(structzebra_vrf*zvrf){if(!zvrf)return;hash_iterate(zvrf->lsp_table,lsp_sc
hedule,NULL);}/**DisplayMPLSlabelforwardingtableforaspecificLSP*(VTYcommandhandl
er).*/voidzebra_mpls_print_lsp(structvty*vty,structzebra_vrf*zvrf,mpls_label_tla
bel,uint8_tuse_json){structhash*lsp_table;zebra_lsp_t*lsp;zebra_ile_ttmp_ile;jso
n_object*json=NULL;/*Lookuptable.*/lsp_table=zvrf->lsp_table;if(!lsp_table)retur
n;/*Ifentryisnotpresent,exit.*/tmp_ile.in_label=label;lsp=hash_lookup(lsp_table,
&tmp_ile);if(!lsp)return;if(use_json){json=lsp_json(lsp);vty_out(vty,"%s\n",json
_object_to_json_string_ext(json,JSON_C_TO_STRING_PRETTY));json_object_free(json)
;}elselsp_print(lsp,(void*)vty);}/**DisplayMPLSlabelforwardingtable(VTYcommandha
ndler).*/voidzebra_mpls_print_lsp_table(structvty*vty,structzebra_vrf*zvrf,uint8
_tuse_json){charbuf[BUFSIZ];json_object*json=NULL;zebra_lsp_t*lsp=NULL;zebra_nhl
fe_t*nhlfe=NULL;structnexthop*nexthop=NULL;structlistnode*node=NULL;structlist*l
sp_list=hash_get_sorted_list(zvrf->lsp_table,lsp_cmp);if(use_json){json=json_obj
ect_new_object();for(ALL_LIST_ELEMENTS_RO(lsp_list,node,lsp))json_object_object_
add(json,label2str(lsp->ile.in_label,buf,BUFSIZ),lsp_json(lsp));vty_out(vty,"%s\
n",json_object_to_json_string_ext(json,JSON_C_TO_STRING_PRETTY));json_object_fre
e(json);}else{vty_out(vty,"InboundOutbound\n");vty_out(vty,"LabelTypeNexthopLabe
l\n");vty_out(vty,"--------------------------------------\n");for(ALL_LIST_ELEME
NTS_RO(lsp_list,node,lsp)){for(nhlfe=lsp->nhlfe_list;nhlfe;nhlfe=nhlfe->next){vt
y_out(vty,"%8d%7s",lsp->ile.in_label,nhlfe_type2str(nhlfe->type));nexthop=nhlfe-
>nexthop;switch(nexthop->type){caseNEXTHOP_TYPE_IFINDEX:{structinterface*ifp;ifp
=if_lookup_by_index(nexthop->ifindex,VRF_UNKNOWN);vty_out(vty,"%15s",ifp->name);
break;}caseNEXTHOP_TYPE_IPV4:caseNEXTHOP_TYPE_IPV4_IFINDEX:vty_out(vty,"%15s",in
et_ntoa(nexthop->gate.ipv4));break;caseNEXTHOP_TYPE_IPV6:caseNEXTHOP_TYPE_IPV6_I
FINDEX:vty_out(vty,"%15s",inet_ntop(AF_INET6,&nexthop->gate.ipv6,buf,BUFSIZ));br
eak;default:break;}if(nexthop->type!=NEXTHOP_TYPE_IFINDEX)vty_out(vty,"%8s\n",mp
ls_label2str(nexthop->nh_label->num_labels,&nexthop->nh_label->label[0],buf,BUFS
IZ,1));elsevty_out(vty,"\n");}}vty_out(vty,"\n");}list_delete_and_null(&lsp_list
);}/**DisplayMPLSLSPconfigurationofallstaticLSPs(VTYcommandhandler).*/intzebra_m
pls_write_lsp_config(structvty*vty,structzebra_vrf*zvrf){zebra_slsp_t*slsp;zebra
_snhlfe_t*snhlfe;structlistnode*node;structlist*slsp_list=hash_get_sorted_list(z
vrf->slsp_table,slsp_cmp);for(ALL_LIST_ELEMENTS_RO(slsp_list,node,slsp)){for(snh
lfe=slsp->snhlfe_list;snhlfe;snhlfe=snhlfe->next){charbuf[BUFSIZ];charlstr[30];s
nhlfe2str(snhlfe,buf,sizeof(buf));switch(snhlfe->out_label){caseMPLS_LABEL_IPV4_
EXPLICIT_NULL:caseMPLS_LABEL_IPV6_EXPLICIT_NULL:strlcpy(lstr,"explicit-null",siz
eof(lstr));break;caseMPLS_LABEL_IMPLICIT_NULL:strlcpy(lstr,"implicit-null",sizeo
f(lstr));break;default:sprintf(lstr,"%u",snhlfe->out_label);break;}vty_out(vty,"
mplslsp%u%s%s\n",slsp->ile.in_label,buf,lstr);}}list_delete_and_null(&slsp_list)
;return(zvrf->slsp_table->count?1:0);}/**Add/updategloballabelblock.*/intzebra_m
pls_label_block_add(structzebra_vrf*zvrf,uint32_tstart_label,uint32_tend_label){
zvrf->mpls_srgb.start_label=start_label;zvrf->mpls_srgb.end_label=end_label;/*Ev
aluateregisteredFECstoseeifanygetalabelornot.*/fec_evaluate(zvrf);return0;}/**De
letegloballabelblock.*/intzebra_mpls_label_block_del(structzebra_vrf*zvrf){zvrf-
>mpls_srgb.start_label=MPLS_DEFAULT_MIN_SRGB_LABEL;zvrf->mpls_srgb.end_label=MPL
S_DEFAULT_MAX_SRGB_LABEL;/*ProcessregisteredFECstocleartheirlocallabel,ifneeded.
*/fec_evaluate(zvrf);return0;}/**DisplayMPLSgloballabelblockconfiguration(VTYcom
mandhandler).*/intzebra_mpls_write_label_block_config(structvty*vty,structzebra_
vrf*zvrf){if(zvrf->mpls_srgb.start_label==0)return0;if((zvrf->mpls_srgb.start_la
bel!=MPLS_DEFAULT_MIN_SRGB_LABEL)||(zvrf->mpls_srgb.end_label!=MPLS_DEFAULT_MAX_
SRGB_LABEL)){vty_out(vty,"mplslabelglobal-block%u%u\n",zvrf->mpls_srgb.start_lab
el,zvrf->mpls_srgb.end_label);}return1;}/**CalledwhenVRFbecomesinactive,cleansup
informationbutkeeps*thetableitself.*NOTE:CurrentlysupportedonlyfordefaultVRF.*/v
oidzebra_mpls_cleanup_tables(structzebra_vrf*zvrf){hash_iterate(zvrf->lsp_table,
lsp_uninstall_from_kernel,NULL);}/**Calleduponprocessexiting,needtodeleteLSPforw
arding*entriesfromthekernel.*NOTE:CurrentlysupportedonlyfordefaultVRF.*/voidzebr
a_mpls_close_tables(structzebra_vrf*zvrf){hash_iterate(zvrf->lsp_table,lsp_unins
tall_from_kernel,NULL);hash_clean(zvrf->lsp_table,NULL);hash_free(zvrf->lsp_tabl
e);hash_clean(zvrf->slsp_table,NULL);hash_free(zvrf->slsp_table);route_table_fin
ish(zvrf->fec_table[AFI_IP]);route_table_finish(zvrf->fec_table[AFI_IP6]);}/**Al
locateMPLStablesforthisVRFanddootherinitialization.*NOTE:Currentlysupportedonlyf
ordefaultVRF.*/voidzebra_mpls_init_tables(structzebra_vrf*zvrf){if(!zvrf)return;
zvrf->slsp_table=hash_create(label_hash,label_cmp,"ZEBRASLSPtable");zvrf->lsp_ta
ble=hash_create(label_hash,label_cmp,"ZEBRALSPtable");zvrf->fec_table[AFI_IP]=ro
ute_table_init();zvrf->fec_table[AFI_IP6]=route_table_init();zvrf->mpls_flags=0;
zvrf->mpls_srgb.start_label=MPLS_DEFAULT_MIN_SRGB_LABEL;zvrf->mpls_srgb.end_labe
l=MPLS_DEFAULT_MAX_SRGB_LABEL;}/**GlobalMPLSinitialization.*/voidzebra_mpls_init
(void){mpls_enabled=0;if(mpls_kernel_init()<0){zlog_warn("DisablingMPLSsupport(n
okernelsupport)");return;}if(!mpls_processq_init(&zebrad))mpls_enabled=1;}