#!/bin/bash

ip link add DONNA type vrf table 1001
ip link add EVA type vrf table 1002

ip link add dummy0 type dummy # vrf default
ip link add dummy1 type dummy
ip link add dummy2 type dummy
ip link add dummy3 type dummy
ip link add dummy4 type dummy

ip link set dummy1 master DONNA
ip link set dummy2 master EVA
ip link set dummy3 master DONNA
ip link set dummy4 master EVA


