/**RIPngdmainroutine.*Copyright(C)1998,1999KunihiroIshiguro**ThisfileispartofGNU
Zebra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodifyit*underthetermso
ftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eitherversion
2,or(atyouroption)any*laterversion.**GNUZebraisdistributedinthehopethatitwillbeu
seful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFI
TNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Yousho
uldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefile
COPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Bos
ton,MA02110-1301USA*/#include<zebra.h>#include<lib/version.h>#include"getopt.h"#
include"vector.h"#include"vty.h"#include"command.h"#include"memory.h"#include"me
mory_vty.h"#include"thread.h"#include"log.h"#include"prefix.h"#include"if.h"#inc
lude"privs.h"#include"sigevent.h"#include"vrf.h"#include"libfrr.h"#include"ripng
d/ripngd.h"/*RIPngdoptions.*/structoptionlongopts[]={{"retain",no_argument,NULL,
'r'},{0}};/*ripngdprivileges*/zebra_capabilities_t_caps_p[]={ZCAP_NET_RAW,ZCAP_B
IND};structzebra_privs_tripngd_privs={#ifdefined(FRR_USER).user=FRR_USER,#endif#
ifdefinedFRR_GROUP.group=FRR_GROUP,#endif#ifdefVTY_GROUP.vty_group=VTY_GROUP,#en
dif.caps_p=_caps_p,.cap_num_p=2,.cap_num_i=0};/*RIPngdprogramname*//*Routeretain
modeflag.*/intretain_mode=0;/*Masterofthreads.*/structthread_master*master;stati
cstructfrr_daemon_inforipngd_di;/*SIGHUPhandler.*/staticvoidsighup(void){zlog_in
fo("SIGHUPreceived");ripng_clean();ripng_reset();/*Reloadconfigfile.*/vty_read_c
onfig(ripngd_di.config_file,config_default);/*Trytoreturntonormaloperation.*/}/*
SIGINThandler.*/staticvoidsigint(void){zlog_notice("Terminatingonsignal");if(!re
tain_mode)ripng_clean();ripng_zebra_stop();frr_fini();exit(0);}/*SIGUSR1handler.
*/staticvoidsigusr1(void){zlog_rotate();}structquagga_signal_tripng_signals[]={{
.signal=SIGHUP,.handler=&sighup,},{.signal=SIGUSR1,.handler=&sigusr1,},{.signal=
SIGINT,.handler=&sigint,},{.signal=SIGTERM,.handler=&sigint,},};FRR_DAEMON_INFO(
ripngd,RIPNG,.vty_port=RIPNG_VTY_PORT,.proghelp="ImplementationoftheRIPngrouting
protocol.",.signals=ripng_signals,.n_signals=array_size(ripng_signals),.privs=&r
ipngd_privs,)/*RIPngdmainroutine.*/intmain(intargc,char**argv){frr_preinit(&ripn
gd_di,argc,argv);frr_opt_add("r",longopts,"-r,--retainWhenprogramterminates,reta
inaddedroutebyripd.\n");while(1){intopt;opt=frr_getopt(argc,argv,NULL);if(opt==E
OF)break;switch(opt){case0:break;case'r':retain_mode=1;break;default:frr_help_ex
it(1);break;}}master=frr_init();/*Libraryinits.*/vrf_init(NULL,NULL,NULL,NULL);/
*RIPngdinits.*/ripng_init();zebra_init(master);ripng_peer_init();frr_config_fork
();frr_run(master);/*Notreached.*/return0;}