/*RIPngpeersupport*Copyright(C)2000KunihiroIshiguro<kunihiro@zebra.org>**Thisfil
eispartofGNUZebra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodifyit*un
derthetermsoftheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;e
itherversion2,or(atyouroption)any*laterversion.**GNUZebraisdistributedinthehopet
hatitwillbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHAN
TABILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredeta
ils.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogra
m;seethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,Fi
fthFloor,Boston,MA02110-1301USA*//*RIPngsupportaddedbyVincentJardin<vincent.jard
in@6wind.com>*Copyright(C)20026WIND*/#include<zebra.h>#include"if.h"#include"pre
fix.h"#include"command.h"#include"linklist.h"#include"thread.h"#include"memory.h
"#include"ripngd/ripngd.h"#include"ripngd/ripng_nexthop.h"/*LinkedlistofRIPngpee
r.*/structlist*peer_list;staticstructripng_peer*ripng_peer_new(void){returnXCALL
OC(MTYPE_RIPNG_PEER,sizeof(structripng_peer));}staticvoidripng_peer_free(structr
ipng_peer*peer){XFREE(MTYPE_RIPNG_PEER,peer);}structripng_peer*ripng_peer_lookup
(structin6_addr*addr){structripng_peer*peer;structlistnode*node,*nnode;for(ALL_L
IST_ELEMENTS(peer_list,node,nnode,peer)){if(IPV6_ADDR_SAME(&peer->addr,addr))ret
urnpeer;}returnNULL;}structripng_peer*ripng_peer_lookup_next(structin6_addr*addr
){structripng_peer*peer;structlistnode*node,*nnode;for(ALL_LIST_ELEMENTS(peer_li
st,node,nnode,peer)){if(addr6_cmp(&peer->addr,addr)>0)returnpeer;}returnNULL;}/*
RIPngpeeristimeout.*Garbagecollector.**/staticintripng_peer_timeout(structthread
*t){structripng_peer*peer;peer=THREAD_ARG(t);listnode_delete(peer_list,peer);rip
ng_peer_free(peer);return0;}/*GetRIPngpeer.Atthesametimeupdatetimeoutthread.*/st
aticstructripng_peer*ripng_peer_get(structin6_addr*addr){structripng_peer*peer;p
eer=ripng_peer_lookup(addr);if(peer){if(peer->t_timeout)thread_cancel(peer->t_ti
meout);}else{peer=ripng_peer_new();peer->addr=*addr;/*XXX*/listnode_add_sort(pee
r_list,peer);}/*Updatetimeoutthread.*/peer->t_timeout=NULL;thread_add_timer(mast
er,ripng_peer_timeout,peer,RIPNG_PEER_TIMER_DEFAULT,&peer->t_timeout);/*Lastupda
tetimeset.*/time(&peer->uptime);returnpeer;}voidripng_peer_update(structsockaddr
_in6*from,uint8_tversion){structripng_peer*peer;peer=ripng_peer_get(&from->sin6_
addr);peer->version=version;}voidripng_peer_bad_route(structsockaddr_in6*from){s
tructripng_peer*peer;peer=ripng_peer_get(&from->sin6_addr);peer->recv_badroutes+
+;}voidripng_peer_bad_packet(structsockaddr_in6*from){structripng_peer*peer;peer
=ripng_peer_get(&from->sin6_addr);peer->recv_badpackets++;}/*Displaypeeruptime.*
/staticchar*ripng_peer_uptime(structripng_peer*peer,char*buf,size_tlen){time_tup
time;structtm*tm;/*Ifthereisnoconnectionhasbeendonebeforeprint`never'.*/if(peer-
>uptime==0){snprintf(buf,len,"never");returnbuf;}/*Getcurrenttime.*/uptime=time(
NULL);uptime-=peer->uptime;tm=gmtime(&uptime);if(uptime<ONE_DAY_SECOND)snprintf(
buf,len,"%02d:%02d:%02d",tm->tm_hour,tm->tm_min,tm->tm_sec);elseif(uptime<ONE_WE
EK_SECOND)snprintf(buf,len,"%dd%02dh%02dm",tm->tm_yday,tm->tm_hour,tm->tm_min);e
lsesnprintf(buf,len,"%02dw%dd%02dh",tm->tm_yday/7,tm->tm_yday-((tm->tm_yday/7)*7
),tm->tm_hour);returnbuf;}voidripng_peer_display(structvty*vty){structripng_peer
*peer;structlistnode*node,*nnode;#defineRIPNG_UPTIME_LEN25chartimebuf[RIPNG_UPTI
ME_LEN];for(ALL_LIST_ELEMENTS(peer_list,node,nnode,peer)){vty_out(vty,"%s\n%14s%
10d%10d%10d%s\n",inet6_ntoa(peer->addr),"",peer->recv_badpackets,peer->recv_badr
outes,ZEBRA_RIPNG_DISTANCE_DEFAULT,ripng_peer_uptime(peer,timebuf,RIPNG_UPTIME_L
EN));}}staticintripng_peer_list_cmp(structripng_peer*p1,structripng_peer*p2){ret
urnaddr6_cmp(&p1->addr,&p2->addr)>0;}voidripng_peer_init(){peer_list=list_new();
peer_list->cmp=(int(*)(void*,void*))ripng_peer_list_cmp;}