/*RIPngdaemon*Copyright(C)1998,1999KunihiroIshiguro**ThisfileispartofGNUZebra.**
GNUZebraisfreesoftware;youcanredistributeitand/ormodifyit*underthetermsoftheGNUG
eneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eitherversion2,or(aty
ouroption)any*laterversion.**GNUZebraisdistributedinthehopethatitwillbeuseful,bu
t*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYorFITNESSFOR
APARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Youshouldhaver
eceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefileCOPYING;
ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,Boston,MA02
110-1301USA*/#include<zebra.h>#include"prefix.h"#include"filter.h"#include"log.h
"#include"thread.h"#include"memory.h"#include"if.h"#include"stream.h"#include"ta
ble.h"#include"command.h"#include"sockopt.h"#include"distribute.h"#include"plist
.h"#include"routemap.h"#include"if_rmap.h"#include"privs.h"#include"ripngd/ripng
d.h"#include"ripngd/ripng_route.h"#include"ripngd/ripng_debug.h"#include"ripngd/
ripng_nexthop.h"/*RIPngstructurewhichincludesmanyparametersrelatedtoRIPngprotoco
l.Ifripngcouldn'tactiveorripngdoesn'tconfigured,ripng->fdmustbenegativevalue.*/s
tructripng*ripng=NULL;enum{ripng_all_route,ripng_changed_route,};/*Prototypes.*/
voidripng_output_process(structinterface*,structsockaddr_in6*,int);intripng_trig
gered_update(structthread*);/*RIPngnexthopspecification.*/structripng_nexthop{en
umripng_nexthop_type{RIPNG_NEXTHOP_UNSPEC,RIPNG_NEXTHOP_ADDRESS}flag;structin6_a
ddraddress;};staticintripng_route_rte(structripng_info*rinfo){return(rinfo->type
==ZEBRA_ROUTE_RIPNG&&rinfo->sub_type==RIPNG_ROUTE_RTE);}/*Allocatenewripnginform
ation.*/structripng_info*ripng_info_new(){structripng_info*new;new=XCALLOC(MTYPE
_RIPNG_ROUTE,sizeof(structripng_info));returnnew;}/*Freeripnginformation.*/voidr
ipng_info_free(structripng_info*rinfo){XFREE(MTYPE_RIPNG_ROUTE,rinfo);}/*Creater
ipngsocket.*/staticintripng_make_socket(void){intret;intsock;structsockaddr_in6r
ipaddr;sock=socket(AF_INET6,SOCK_DGRAM,0);if(sock<0){zlog_err("Can'tmakeripngsoc
ket");returnsock;}setsockopt_so_recvbuf(sock,8096);ret=setsockopt_ipv6_pktinfo(s
ock,1);if(ret<0)gotoerror;#ifdefIPTOS_PREC_INTERNETCONTROLret=setsockopt_ipv6_tc
lass(sock,IPTOS_PREC_INTERNETCONTROL);if(ret<0)gotoerror;#endifret=setsockopt_ip
v6_multicast_hops(sock,255);if(ret<0)gotoerror;ret=setsockopt_ipv6_multicast_loo
p(sock,0);if(ret<0)gotoerror;ret=setsockopt_ipv6_hoplimit(sock,1);if(ret<0)gotoe
rror;memset(&ripaddr,0,sizeof(ripaddr));ripaddr.sin6_family=AF_INET6;#ifdefSIN6_
LENripaddr.sin6_len=sizeof(structsockaddr_in6);#endif/*SIN6_LEN*/ripaddr.sin6_po
rt=htons(RIPNG_PORT_DEFAULT);if(ripngd_privs.change(ZPRIVS_RAISE))zlog_err("ripn
g_make_socket:couldnotraiseprivs");ret=bind(sock,(structsockaddr*)&ripaddr,sizeo
f(ripaddr));if(ret<0){zlog_err("Can'tbindripngsocket:%s.",safe_strerror(errno));
if(ripngd_privs.change(ZPRIVS_LOWER))zlog_err("ripng_make_socket:couldnotlowerpr
ivs");gotoerror;}if(ripngd_privs.change(ZPRIVS_LOWER))zlog_err("ripng_make_socke
t:couldnotlowerprivs");returnsock;error:close(sock);returnret;}/*SendRIPngpacket
.*/intripng_send_packet(caddr_tbuf,intbufsize,structsockaddr_in6*to,structinterf
ace*ifp){intret;structmsghdrmsg;structioveciov;structcmsghdr*cmsgptr;charadata[2
56];structin6_pktinfo*pkt;structsockaddr_in6addr;if(IS_RIPNG_DEBUG_SEND){if(to)z
log_debug("sendto%s",inet6_ntoa(to->sin6_addr));zlog_debug("sendinterface%s",ifp
->name);zlog_debug("sendpacketsize%d",bufsize);}memset(&addr,0,sizeof(structsock
addr_in6));addr.sin6_family=AF_INET6;#ifdefSIN6_LENaddr.sin6_len=sizeof(structso
ckaddr_in6);#endif/*SIN6_LEN*/addr.sin6_flowinfo=htonl(RIPNG_PRIORITY_DEFAULT);/
*Whendestinationisspecified.*/if(to!=NULL){addr.sin6_addr=to->sin6_addr;addr.sin
6_port=to->sin6_port;}else{inet_pton(AF_INET6,RIPNG_GROUP,&addr.sin6_addr);addr.
sin6_port=htons(RIPNG_PORT_DEFAULT);}memset(&msg,0,sizeof(msg));msg.msg_name=(vo
id*)&addr;msg.msg_namelen=sizeof(structsockaddr_in6);msg.msg_iov=&iov;msg.msg_io
vlen=1;msg.msg_control=(void*)adata;msg.msg_controllen=CMSG_SPACE(sizeof(structi
n6_pktinfo));iov.iov_base=buf;iov.iov_len=bufsize;cmsgptr=(structcmsghdr*)adata;
cmsgptr->cmsg_len=CMSG_LEN(sizeof(structin6_pktinfo));cmsgptr->cmsg_level=IPPROT
O_IPV6;cmsgptr->cmsg_type=IPV6_PKTINFO;pkt=(structin6_pktinfo*)CMSG_DATA(cmsgptr
);memset(&pkt->ipi6_addr,0,sizeof(structin6_addr));pkt->ipi6_ifindex=ifp->ifinde
x;ret=sendmsg(ripng->sock,&msg,0);if(ret<0){if(to)zlog_err("RIPngsendfailon%sto%
s:%s",ifp->name,inet6_ntoa(to->sin6_addr),safe_strerror(errno));elsezlog_err("RI
Pngsendfailon%s:%s",ifp->name,safe_strerror(errno));}returnret;}/*ReceiveUDPRIPn
gpacketfromsocket.*/staticintripng_recv_packet(intsock,uint8_t*buf,intbufsize,st
ructsockaddr_in6*from,ifindex_t*ifindex,int*hoplimit){intret;structmsghdrmsg;str
uctioveciov;structcmsghdr*cmsgptr;structin6_addrdst={.s6_addr={0}};memset(&dst,0
,sizeof(structin6_addr));/*Ancillarydata.Thisstorecmsghdrandin6_pktinfo.Butatthi
spointIcan'tdeterminesizeofcmsghdr*/charadata[1024];/*Fillinmessageandiovec.*/me
mset(&msg,0,sizeof(msg));msg.msg_name=(void*)from;msg.msg_namelen=sizeof(structs
ockaddr_in6);msg.msg_iov=&iov;msg.msg_iovlen=1;msg.msg_control=(void*)adata;msg.
msg_controllen=sizeofadata;iov.iov_base=buf;iov.iov_len=bufsize;/*Ifrecvmsgfailr
eturnminusvalue.*/ret=recvmsg(sock,&msg,0);if(ret<0)returnret;for(cmsgptr=ZCMSG_
FIRSTHDR(&msg);cmsgptr!=NULL;cmsgptr=CMSG_NXTHDR(&msg,cmsgptr)){/*Iwantinterface
indexwhichthispacketcomesfrom.*/if(cmsgptr->cmsg_level==IPPROTO_IPV6&&cmsgptr->c
msg_type==IPV6_PKTINFO){structin6_pktinfo*ptr;ptr=(structin6_pktinfo*)CMSG_DATA(
cmsgptr);*ifindex=ptr->ipi6_ifindex;dst=ptr->ipi6_addr;if(*ifindex==0)zlog_warn(
"InterfaceindexreturnedbyIPV6_PKTINFOiszero");}/*Incomingpacket'smulticasthoplim
it.*/if(cmsgptr->cmsg_level==IPPROTO_IPV6&&cmsgptr->cmsg_type==IPV6_HOPLIMIT){in
t*phoplimit=(int*)CMSG_DATA(cmsgptr);*hoplimit=*phoplimit;}}/*Hoplimitcheckshold
bedonewhendestinationaddressismulticastaddress.*/if(!IN6_IS_ADDR_MULTICAST(&dst)
)*hoplimit=-1;returnret;}/*Dumprippacket*/voidripng_packet_dump(structripng_pack
et*packet,intsize,constchar*sndrcv){caddr_tlim;structrte*rte;constchar*command_s
tr;/*Setcommandstring.*/if(packet->command==RIPNG_REQUEST)command_str="request";
elseif(packet->command==RIPNG_RESPONSE)command_str="response";elsecommand_str="u
nknown";/*Dumppacketheader.*/zlog_debug("%s%sversion%dpacketsize%d",sndrcv,comma
nd_str,packet->version,size);/*Dumpeachroutingtableentry.*/rte=packet->rte;for(l
im=(caddr_t)packet+size;(caddr_t)rte<lim;rte++){if(rte->metric==RIPNG_METRIC_NEX
THOP)zlog_debug("nexthop%s/%d",inet6_ntoa(rte->addr),rte->prefixlen);elsezlog_de
bug("%s/%dmetric%dtag%"ROUTE_TAG_PRI,inet6_ntoa(rte->addr),rte->prefixlen,rte->m
etric,(route_tag_t)ntohs(rte->tag));}}/*RIPngnexthopaddressRTE(RouteTableEntry).
*/staticvoidripng_nexthop_rte(structrte*rte,structsockaddr_in6*from,structripng_
nexthop*nexthop){charbuf[INET6_BUFSIZ];/*LoggingbeforecheckingRTE.*/if(IS_RIPNG_
DEBUG_RECV)zlog_debug("RIPngnexthopRTEaddress%stag%"ROUTE_TAG_PRI"prefixlen%d",i
net6_ntoa(rte->addr),(route_tag_t)ntohs(rte->tag),rte->prefixlen);/*RFC20802.1.1
NextHop:TheroutetagandprefixlengthinthenexthopRTEmustbesettozeroonsendingandigno
redonreceiption.*/if(ntohs(rte->tag)!=0)zlog_warn("RIPngnexthopRTEwithnonzerotag
value%"ROUTE_TAG_PRI"from%s",(route_tag_t)ntohs(rte->tag),inet6_ntoa(from->sin6_
addr));if(rte->prefixlen!=0)zlog_warn("RIPngnexthopRTEwithnonzeroprefixlenvalue%
dfrom%s",rte->prefixlen,inet6_ntoa(from->sin6_addr));/*Specifyingavalueof0:0:0:0
:0:0:0:0intheprefixfieldofanexthopRTEindicatesthatthenexthopaddressshouldbetheor
iginatoroftheRIPngadvertisement.Anaddressspecifiedasanexthopmustbealink-localadd
ress.*/if(IN6_IS_ADDR_UNSPECIFIED(&rte->addr)){nexthop->flag=RIPNG_NEXTHOP_UNSPE
C;memset(&nexthop->address,0,sizeof(structin6_addr));return;}if(IN6_IS_ADDR_LINK
LOCAL(&rte->addr)){nexthop->flag=RIPNG_NEXTHOP_ADDRESS;IPV6_ADDR_COPY(&nexthop->
address,&rte->addr);return;}/*ThepurposeofthenexthopRTEistoeliminatepacketsbeing
routedthroughextrahopsinthesystem.ItisparticularlyusefulwhenRIPngisnotbeingrunon
alloftheroutersonanetwork.NotethatnexthopRTEis"advisory".Thatis,iftheprovidedinf
ormationisignored,apossiblysub-optimal,butabsolutelyvalid,routemaybetaken.Ifther
eceivednexthopaddressisnotalink-localaddress,itshouldbetreatedas0:0:0:0:0:0:0:0.
*/zlog_warn("RIPngnexthopRTEwithnonlink-localaddress%sfrom%s",inet6_ntoa(rte->ad
dr),inet_ntop(AF_INET6,&from->sin6_addr,buf,INET6_BUFSIZ));nexthop->flag=RIPNG_N
EXTHOP_UNSPEC;memset(&nexthop->address,0,sizeof(structin6_addr));return;}/*Ififp
hassamelink-localaddressthenreturn1.*/staticintripng_lladdr_check(structinterfac
e*ifp,structin6_addr*addr){structlistnode*node;structconnected*connected;structp
refix*p;for(ALL_LIST_ELEMENTS_RO(ifp->connected,node,connected)){p=connected->ad
dress;if(p->family==AF_INET6&&IN6_IS_ADDR_LINKLOCAL(&p->u.prefix6)&&IN6_ARE_ADDR
_EQUAL(&p->u.prefix6,addr))return1;}return0;}/*RIPngroutegarbagecollecttimer.*/s
taticintripng_garbage_collect(structthread*t){structripng_info*rinfo;structroute
_node*rp;rinfo=THREAD_ARG(t);rinfo->t_garbage_collect=NULL;/*Offtimeouttimer.*/R
IPNG_TIMER_OFF(rinfo->t_timeout);/*Getroute_nodepointer.*/rp=rinfo->rp;/*Unlockr
oute_node.*/listnode_delete(rp->info,rinfo);if(list_isempty((structlist*)rp->inf
o)){list_delete_and_null((structlist**)&rp->info);route_unlock_node(rp);}/*FreeR
IPngroutinginformation.*/ripng_info_free(rinfo);return0;}staticvoidripng_timeout
_update(structripng_info*rinfo);/*AddnewroutetotheECMPlist.*RETURN:thenewentryad
dedinthelist,orNULLifitisnotthefirst*entryandECMPisnotallowed.*/structripng_info
*ripng_ecmp_add(structripng_info*rinfo_new){structroute_node*rp=rinfo_new->rp;st
ructripng_info*rinfo=NULL;structlist*list=NULL;if(rp->info==NULL)rp->info=list_n
ew();list=(structlist*)rp->info;/*IfECMPisnotallowedandsomeentryalreadyexistsint
helist,*donothing.*/if(listcount(list)&&!ripng->ecmp)returnNULL;rinfo=ripng_info
_new();memcpy(rinfo,rinfo_new,sizeof(structripng_info));listnode_add(list,rinfo)
;if(ripng_route_rte(rinfo)){ripng_timeout_update(rinfo);ripng_zebra_ipv6_add(rp)
;}ripng_aggregate_increment(rp,rinfo);/*Settheroutechangeflagonthefirstentry.*/r
info=listgetdata(listhead(list));SET_FLAG(rinfo->flags,RIPNG_RTF_CHANGED);/*Sign
altheoutputprocesstotriggeranupdate.*/ripng_event(RIPNG_TRIGGERED_UPDATE,0);retu
rnrinfo;}/*ReplacetheECMPlistwiththenewroute.*RETURN:thenewentryaddedinthelist*/
structripng_info*ripng_ecmp_replace(structripng_info*rinfo_new){structroute_node
*rp=rinfo_new->rp;structlist*list=(structlist*)rp->info;structripng_info*rinfo=N
ULL,*tmp_rinfo=NULL;structlistnode*node=NULL,*nextnode=NULL;if(list==NULL||listc
ount(list)==0)returnripng_ecmp_add(rinfo_new);/*Getthefirstentry*/rinfo=listgetd
ata(listhead(list));/*Learntroutereplacedbyalocalone.Deleteitfromzebra.*/if(ripn
g_route_rte(rinfo)&&!ripng_route_rte(rinfo_new))if(CHECK_FLAG(rinfo->flags,RIPNG
_RTF_FIB))ripng_zebra_ipv6_delete(rp);if(rinfo->metric!=RIPNG_METRIC_INFINITY)ri
png_aggregate_decrement_list(rp,list);/*Re-usethefirstentry,anddeletetheothers.*
/for(ALL_LIST_ELEMENTS(list,node,nextnode,tmp_rinfo))if(tmp_rinfo!=rinfo){RIPNG_
TIMER_OFF(tmp_rinfo->t_timeout);RIPNG_TIMER_OFF(tmp_rinfo->t_garbage_collect);li
st_delete_node(list,node);ripng_info_free(tmp_rinfo);}RIPNG_TIMER_OFF(rinfo->t_t
imeout);RIPNG_TIMER_OFF(rinfo->t_garbage_collect);memcpy(rinfo,rinfo_new,sizeof(
structripng_info));if(ripng_route_rte(rinfo)){ripng_timeout_update(rinfo);/*TheA
DDmessageimpliesanupdate.*/ripng_zebra_ipv6_add(rp);}ripng_aggregate_increment(r
p,rinfo);/*Settheroutechangeflag.*/SET_FLAG(rinfo->flags,RIPNG_RTF_CHANGED);/*Si
gnaltheoutputprocesstotriggeranupdate.*/ripng_event(RIPNG_TRIGGERED_UPDATE,0);re
turnrinfo;}/*DeleteoneroutefromtheECMPlist.*RETURN:*null-theentryisfreed,andothe
rentriesexistinthelist*theentry-theentryisthelastoneinthelist;itsmetricisset*toI
NFINITY,andthegarbagecollectorisstartedforit*/structripng_info*ripng_ecmp_delete
(structripng_info*rinfo){structroute_node*rp=rinfo->rp;structlist*list=(structli
st*)rp->info;RIPNG_TIMER_OFF(rinfo->t_timeout);if(rinfo->metric!=RIPNG_METRIC_IN
FINITY)ripng_aggregate_decrement(rp,rinfo);if(listcount(list)>1){/*SomeotherECMP
entriesstillexist.Justdeletethisentry.*/RIPNG_TIMER_OFF(rinfo->t_garbage_collect
);listnode_delete(list,rinfo);if(ripng_route_rte(rinfo)&&CHECK_FLAG(rinfo->flags
,RIPNG_RTF_FIB))/*TheADDmessageimpliestheupdate.*/ripng_zebra_ipv6_add(rp);ripng
_info_free(rinfo);rinfo=NULL;}else{assert(rinfo==listgetdata(listhead(list)));/*
Thisistheonlyentryleftinthelist.Wemustkeepitin*thelistforgarbagecollectiontime,w
ithINFINITYmetric.*/rinfo->metric=RIPNG_METRIC_INFINITY;RIPNG_TIMER_ON(rinfo->t_
garbage_collect,ripng_garbage_collect,ripng->garbage_time);if(ripng_route_rte(ri
nfo)&&CHECK_FLAG(rinfo->flags,RIPNG_RTF_FIB))ripng_zebra_ipv6_delete(rp);}/*Sett
heroutechangeflagonthefirstentry.*/rinfo=listgetdata(listhead(list));SET_FLAG(ri
nfo->flags,RIPNG_RTF_CHANGED);/*Signaltheoutputprocesstotriggeranupdate.*/ripng_
event(RIPNG_TRIGGERED_UPDATE,0);returnrinfo;}/*TimeoutRIPngroutes.*/staticintrip
ng_timeout(structthread*t){ripng_ecmp_delete((structripng_info*)THREAD_ARG(t));r
eturn0;}staticvoidripng_timeout_update(structripng_info*rinfo){if(rinfo->metric!
=RIPNG_METRIC_INFINITY){RIPNG_TIMER_OFF(rinfo->t_timeout);RIPNG_TIMER_ON(rinfo->
t_timeout,ripng_timeout,ripng->timeout_time);}}staticintripng_filter(intripng_di
stribute,structprefix_ipv6*p,structripng_interface*ri){structdistribute*dist;str
uctaccess_list*alist;structprefix_list*plist;intdistribute=ripng_distribute==RIP
NG_FILTER_OUT?DISTRIBUTE_V6_OUT:DISTRIBUTE_V6_IN;constchar*inout=ripng_distribut
e==RIPNG_FILTER_OUT?"out":"in";/*Inputdistribute-listfiltering.*/if(ri->list[rip
ng_distribute]){if(access_list_apply(ri->list[ripng_distribute],(structprefix*)p
)==FILTER_DENY){if(IS_RIPNG_DEBUG_PACKET)zlog_debug("%s/%dfilteredbydistribute%s
",inet6_ntoa(p->prefix),p->prefixlen,inout);return-1;}}if(ri->prefix[ripng_distr
ibute]){if(prefix_list_apply(ri->prefix[ripng_distribute],(structprefix*)p)==PRE
FIX_DENY){if(IS_RIPNG_DEBUG_PACKET)zlog_debug("%s/%dfilteredbyprefix-list%s",ine
t6_ntoa(p->prefix),p->prefixlen,inout);return-1;}}/*Allinterfacefiltercheck.*/di
st=distribute_lookup(NULL);if(dist){if(dist->list[distribute]){alist=access_list
_lookup(AFI_IP6,dist->list[distribute]);if(alist){if(access_list_apply(alist,(st
ructprefix*)p)==FILTER_DENY){if(IS_RIPNG_DEBUG_PACKET)zlog_debug("%s/%dfilteredb
ydistribute%s",inet6_ntoa(p->prefix),p->prefixlen,inout);return-1;}}}if(dist->pr
efix[distribute]){plist=prefix_list_lookup(AFI_IP6,dist->prefix[distribute]);if(
plist){if(prefix_list_apply(plist,(structprefix*)p)==PREFIX_DENY){if(IS_RIPNG_DE
BUG_PACKET)zlog_debug("%s/%dfilteredbyprefix-list%s",inet6_ntoa(p->prefix),p->pr
efixlen,inout);return-1;}}}}return0;}/*ProcessRIPngrouteaccordingtoRFC2080.*/sta
ticvoidripng_route_process(structrte*rte,structsockaddr_in6*from,structripng_nex
thop*ripng_nexthop,structinterface*ifp){intret;structprefix_ipv6p;structroute_no
de*rp;structripng_info*rinfo=NULL,newinfo;structripng_interface*ri;structin6_add
r*nexthop;intsame=0;structlist*list=NULL;structlistnode*node=NULL;/*Makeprefixst
ructure.*/memset(&p,0,sizeof(structprefix_ipv6));p.family=AF_INET6;/*p.prefix=rt
e->addr;*/IPV6_ADDR_COPY(&p.prefix,&rte->addr);p.prefixlen=rte->prefixlen;/*Make
suremaskisapplied.*//*XXXWehavetochecktheprefixisvalidornotbeforecallapply_mask_
ipv6.*/apply_mask_ipv6(&p);/*Applyinputfilters.*/ri=ifp->info;ret=ripng_filter(R
IPNG_FILTER_IN,&p,ri);if(ret<0)return;memset(&newinfo,0,sizeof(newinfo));newinfo
.type=ZEBRA_ROUTE_RIPNG;newinfo.sub_type=RIPNG_ROUTE_RTE;if(ripng_nexthop->flag=
=RIPNG_NEXTHOP_ADDRESS)newinfo.nexthop=ripng_nexthop->address;elsenewinfo.nextho
p=from->sin6_addr;newinfo.from=from->sin6_addr;newinfo.ifindex=ifp->ifindex;newi
nfo.metric=rte->metric;newinfo.metric_out=rte->metric;/*XXX*/newinfo.tag=ntohs(r
te->tag);/*XXX*//*Modifyentry.*/if(ri->routemap[RIPNG_FILTER_IN]){intret;ret=rou
te_map_apply(ri->routemap[RIPNG_FILTER_IN],(structprefix*)&p,RMAP_RIPNG,&newinfo
);if(ret==RMAP_DENYMATCH){if(IS_RIPNG_DEBUG_PACKET)zlog_debug("RIPng%s/%disfilte
redbyroute-mapin",inet6_ntoa(p.prefix),p.prefixlen);return;}/*Getbacktheobject*/
if(ripng_nexthop->flag==RIPNG_NEXTHOP_ADDRESS){if(!IPV6_ADDR_SAME(&newinfo.nexth
op,&ripng_nexthop->address)){/*thenexthopgetchangedbytheroutemap*/if(IN6_IS_ADDR
_LINKLOCAL(&newinfo.nexthop))ripng_nexthop->address=newinfo.nexthop;elseripng_ne
xthop->address=in6addr_any;}}else{if(!IPV6_ADDR_SAME(&newinfo.nexthop,&from->sin
6_addr)){/*thenexthopgetchangedbytheroutemap*/if(IN6_IS_ADDR_LINKLOCAL(&newinfo.
nexthop)){ripng_nexthop->flag=RIPNG_NEXTHOP_ADDRESS;ripng_nexthop->address=newin
fo.nexthop;}}}rte->tag=htons(newinfo.tag_out);/*XXX*/rte->metric=newinfo.metric_
out;/*XXX:theroutemapusesthemetric_outfield*/}/*Oncetheentryhasbeenvalidated,upd
atethemetricby*addingthecostofthenetworkonwichthemessage*arrived.Iftheresultisgr
eaterthaninfinity,useinfinity*(RFC2453Sec.3.9.2)**//*Zebraripngdcanhandleoffset-
listin.*/ret=ripng_offset_list_apply_in(&p,ifp,&rte->metric);/*Ifoffset-listdoes
notmodifythemetricuseinterface's*one.*/if(!ret)rte->metric+=ifp->metric?ifp->met
ric:1;if(rte->metric>RIPNG_METRIC_INFINITY)rte->metric=RIPNG_METRIC_INFINITY;/*S
etnexthoppointer.*/if(ripng_nexthop->flag==RIPNG_NEXTHOP_ADDRESS)nexthop=&ripng_
nexthop->address;elsenexthop=&from->sin6_addr;/*LookupRIPngroutingtable.*/rp=rou
te_node_get(ripng->table,(structprefix*)&p);newinfo.rp=rp;newinfo.nexthop=*nexth
op;newinfo.metric=rte->metric;newinfo.tag=ntohs(rte->tag);/*Checktoseewhetherthe
reisalreadyRIPngrouteonthetable.*/if((list=rp->info)!=NULL)for(ALL_LIST_ELEMENTS
_RO(list,node,rinfo)){/*Needtocomparewithredistributedentryorlocal*entry*/if(!ri
png_route_rte(rinfo))break;if(IPV6_ADDR_SAME(&rinfo->from,&from->sin6_addr)&&IPV
6_ADDR_SAME(&rinfo->nexthop,nexthop))break;if(!listnextnode(node)){/*Notfoundint
helist*/if(rte->metric>rinfo->metric){/*Newroutehasagreatermetric.*Discardit.*/r
oute_unlock_node(rp);return;}if(rte->metric<rinfo->metric)/*Newroutehasasmallerm
etric.*ReplacetheECMPlist*withthenewoneinbelow.*/break;/*Metricsaresame.UnlessEC
MPisdisabled,*keep"rinfo"nulland*thenewrouteisaddedintheECMPlistin*below.*/if(!r
ipng->ecmp)break;}}if(rinfo){/*Redistributedroutecheck.*/if(rinfo->type!=ZEBRA_R
OUTE_RIPNG&&rinfo->metric!=RIPNG_METRIC_INFINITY){route_unlock_node(rp);return;}
/*Localstaticroute.*/if(rinfo->type==ZEBRA_ROUTE_RIPNG&&((rinfo->sub_type==RIPNG
_ROUTE_STATIC)||(rinfo->sub_type==RIPNG_ROUTE_DEFAULT))&&rinfo->metric!=RIPNG_ME
TRIC_INFINITY){route_unlock_node(rp);return;}}if(!rinfo){/*Now,checktoseewhether
thereisalreadyanexplicitrouteforthedestinationprefix.Ifthereisnosuchroute,addthi
sroutetotheroutingtable,unlessthemetricisinfinity(thereisnopointinaddingaroutewh
ichunusable).*/if(rte->metric!=RIPNG_METRIC_INFINITY)ripng_ecmp_add(&newinfo);el
seroute_unlock_node(rp);}else{/*Ifthereisanexistingroute,comparethenexthopaddres
stotheaddressoftherouterfromwhichthedatagramcame.Ifthisdatagramisfromthesamerout
erastheexistingroute,reinitializethetimeout.*/same=(IN6_ARE_ADDR_EQUAL(&rinfo->f
rom,&from->sin6_addr)&&(rinfo->ifindex==ifp->ifindex));/**RFC2080-Section2.4.2:*
"Ifthenewmetricisthesameastheoldone,examinethe*timeout*fortheexistingroute.Ifiti
satleasthalfwaytothe*expiration*point,switchtothenewroute.Thisheuristicisoptiona
l,*but*highlyrecommended".*/if(!ripng->ecmp&&!same&&rinfo->metric==rte->metric&&
rinfo->t_timeout&&(thread_timer_remain_second(rinfo->t_timeout)<(ripng->timeout_
time/2))){ripng_ecmp_replace(&newinfo);}/*Next,comparethemetrics.Ifthedatagramis
fromthesamerouterastheexistingroute,andthenewmetricisdifferentthantheoldone;or,i
fthenewmetricislowerthantheoldone;dothefollowingactions:*/elseif((same&&rinfo->m
etric!=rte->metric)||rte->metric<rinfo->metric){if(listcount(list)==1){if(newinf
o.metric!=RIPNG_METRIC_INFINITY)ripng_ecmp_replace(&newinfo);elseripng_ecmp_dele
te(rinfo);}else{if(newinfo.metric<rinfo->metric)ripng_ecmp_replace(&newinfo);els
e/*newinfo.metric>rinfo->metric*/ripng_ecmp_delete(rinfo);}}else/*same&nochange*
/ripng_timeout_update(rinfo);/*Unlocktempolarylockoftheroute.*/route_unlock_node
(rp);}}/*AddredistributedroutetoRIPngtable.*/voidripng_redistribute_add(inttype,
intsub_type,structprefix_ipv6*p,ifindex_tifindex,structin6_addr*nexthop,route_ta
g_ttag){structroute_node*rp;structripng_info*rinfo=NULL,newinfo;structlist*list=
NULL;/*Redistributeroute*/if(IN6_IS_ADDR_LINKLOCAL(&p->prefix))return;if(IN6_IS_
ADDR_LOOPBACK(&p->prefix))return;rp=route_node_get(ripng->table,(structprefix*)p
);memset(&newinfo,0,sizeof(structripng_info));newinfo.type=type;newinfo.sub_type
=sub_type;newinfo.ifindex=ifindex;newinfo.metric=1;if(tag<=UINT16_MAX)/*RIPngonl
ysupports16bittags*/newinfo.tag=tag;newinfo.rp=rp;if(nexthop&&IN6_IS_ADDR_LINKLO
CAL(nexthop))newinfo.nexthop=*nexthop;if((list=rp->info)!=NULL&&listcount(list)!
=0){rinfo=listgetdata(listhead(list));if(rinfo->type==ZEBRA_ROUTE_CONNECT&&rinfo
->sub_type==RIPNG_ROUTE_INTERFACE&&rinfo->metric!=RIPNG_METRIC_INFINITY){route_u
nlock_node(rp);return;}/*ManuallyconfiguredRIPngroutecheck.*Theyhavetheprecedenc
eonalltheotherentries.**/if(rinfo->type==ZEBRA_ROUTE_RIPNG&&((rinfo->sub_type==R
IPNG_ROUTE_STATIC)||(rinfo->sub_type==RIPNG_ROUTE_DEFAULT))){if(type!=ZEBRA_ROUT
E_RIPNG||((sub_type!=RIPNG_ROUTE_STATIC)&&(sub_type!=RIPNG_ROUTE_DEFAULT))){rout
e_unlock_node(rp);return;}}ripng_ecmp_replace(&newinfo);route_unlock_node(rp);}e
lseripng_ecmp_add(&newinfo);if(IS_RIPNG_DEBUG_EVENT){if(!nexthop)zlog_debug("Red
istributenewprefix%s/%dontheinterface%s",inet6_ntoa(p->prefix),p->prefixlen,ifin
dex2ifname(ifindex,VRF_DEFAULT));elsezlog_debug("Redistributenewprefix%s/%dwithn
exthop%sontheinterface%s",inet6_ntoa(p->prefix),p->prefixlen,inet6_ntoa(*nexthop
),ifindex2ifname(ifindex,VRF_DEFAULT));}ripng_event(RIPNG_TRIGGERED_UPDATE,0);}/
*DeleteredistributedroutetoRIPngtable.*/voidripng_redistribute_delete(inttype,in
tsub_type,structprefix_ipv6*p,ifindex_tifindex){structroute_node*rp;structripng_
info*rinfo;if(IN6_IS_ADDR_LINKLOCAL(&p->prefix))return;if(IN6_IS_ADDR_LOOPBACK(&
p->prefix))return;rp=route_node_lookup(ripng->table,(structprefix*)p);if(rp){str
uctlist*list=rp->info;if(list!=NULL&&listcount(list)!=0){rinfo=listgetdata(listh
ead(list));if(rinfo!=NULL&&rinfo->type==type&&rinfo->sub_type==sub_type&&rinfo->
ifindex==ifindex){/*Performpoisonedreverse.*/rinfo->metric=RIPNG_METRIC_INFINITY
;RIPNG_TIMER_ON(rinfo->t_garbage_collect,ripng_garbage_collect,ripng->garbage_ti
me);RIPNG_TIMER_OFF(rinfo->t_timeout);/*Aggregatecountdecrement.*/ripng_aggregat
e_decrement(rp,rinfo);rinfo->flags|=RIPNG_RTF_CHANGED;if(IS_RIPNG_DEBUG_EVENT)zl
og_debug("Poisone%s/%dontheinterface%swithan""infinitymetric[delete]",inet6_ntoa
(p->prefix),p->prefixlen,ifindex2ifname(ifindex,VRF_DEFAULT));ripng_event(RIPNG_
TRIGGERED_UPDATE,0);}}route_unlock_node(rp);}}/*Withdrawredistributedroute.*/voi
dripng_redistribute_withdraw(inttype){structroute_node*rp;structripng_info*rinfo
=NULL;structlist*list=NULL;if(!ripng)return;for(rp=route_top(ripng->table);rp;rp
=route_next(rp))if((list=rp->info)!=NULL){rinfo=listgetdata(listhead(list));if((
rinfo->type==type)&&(rinfo->sub_type!=RIPNG_ROUTE_INTERFACE)){/*Performpoisonedr
everse.*/rinfo->metric=RIPNG_METRIC_INFINITY;RIPNG_TIMER_ON(rinfo->t_garbage_col
lect,ripng_garbage_collect,ripng->garbage_time);RIPNG_TIMER_OFF(rinfo->t_timeout
);/*Aggregatecountdecrement.*/ripng_aggregate_decrement(rp,rinfo);rinfo->flags|=
RIPNG_RTF_CHANGED;if(IS_RIPNG_DEBUG_EVENT){structprefix_ipv6*p=(structprefix_ipv
6*)&rp->p;zlog_debug("Poisone%s/%dontheinterface%s[withdraw]",inet6_ntoa(p->pref
ix),p->prefixlen,ifindex2ifname(rinfo->ifindex,VRF_DEFAULT));}ripng_event(RIPNG_
TRIGGERED_UPDATE,0);}}}/*RIProutinginformation.*/staticvoidripng_response_proces
s(structripng_packet*packet,intsize,structsockaddr_in6*from,structinterface*ifp,
inthoplimit){caddr_tlim;structrte*rte;structripng_nexthopnexthop;/*RFC20802.4.2R
esponseMessages:TheResponsemustbeignoredifitisnotfromtheRIPngport.*/if(ntohs(fro
m->sin6_port)!=RIPNG_PORT_DEFAULT){zlog_warn("RIPngpacketcomesfromnonRIPngport%d
from%s",ntohs(from->sin6_port),inet6_ntoa(from->sin6_addr));ripng_peer_bad_packe
t(from);return;}/*Thedatagram'sIPv6sourceaddressshouldbecheckedtoseewhethertheda
tagramisfromavalidneighbor;thesourceofthedatagrammustbealink-localaddress.*/if(!
IN6_IS_ADDR_LINKLOCAL(&from->sin6_addr)){zlog_warn("RIPngpacketcomesfromnonlinkl
ocaladdress%s",inet6_ntoa(from->sin6_addr));ripng_peer_bad_packet(from);return;}
/*Itisalsoworthcheckingtoseewhethertheresponseisfromoneoftherouter'sownaddresses
.Interfacesonbroadcastnetworksmayreceivecopiesoftheirownmulticastsimmediately.If
arouterprocessesitsownoutputasnewinput,confusionislikely,andsuchdatagramsmustbei
gnored.*/if(ripng_lladdr_check(ifp,&from->sin6_addr)){zlog_warn("RIPngpacketcome
sfrommyownlinklocaladdress%s",inet6_ntoa(from->sin6_addr));ripng_peer_bad_packet
(from);return;}/*Asanadditionalcheck,periodicadvertisementsmusthavetheirhopcount
ssetto255,andinbound,multicastpacketssentfromtheRIPngport(i.e.periodicadvertisem
entortriggeredupdatepackets)mustbeexaminedtoensurethatthehopcountis255.*/if(hopl
imit>=0&&hoplimit!=255){zlog_warn("RIPngpacketcomeswithnon255hopcount%dfrom%s",h
oplimit,inet6_ntoa(from->sin6_addr));ripng_peer_bad_packet(from);return;}/*Updat
eRIPngpeer.*/ripng_peer_update(from,packet->version);/*Resetnexthop.*/memset(&ne
xthop,0,sizeof(structripng_nexthop));nexthop.flag=RIPNG_NEXTHOP_UNSPEC;/*SetRTEp
ointer.*/rte=packet->rte;for(lim=((caddr_t)packet)+size;(caddr_t)rte<lim;rte++){
/*Firstofall,wehavetocheckthisRTEisnexthopRTEornot.NexthopRTEiscompletelydiffere
ntwithnormalRTEsoweneedspecialtreatment.*/if(rte->metric==RIPNG_METRIC_NEXTHOP){
ripng_nexthop_rte(rte,from,&nexthop);continue;}/*RTEinformationvalidation.*//*-i
sthedestinationprefixvalid(e.g.,notamulticastprefixandnotalink-localaddress)Alin
k-localaddressshouldneverbepresentinanRTE.*/if(IN6_IS_ADDR_MULTICAST(&rte->addr)
){zlog_warn("Destinationprefixisamulticastaddress%s/%d[%d]",inet6_ntoa(rte->addr
),rte->prefixlen,rte->metric);ripng_peer_bad_route(from);continue;}if(IN6_IS_ADD
R_LINKLOCAL(&rte->addr)){zlog_warn("Destinationprefixisalink-localaddress%s/%d[%
d]",inet6_ntoa(rte->addr),rte->prefixlen,rte->metric);ripng_peer_bad_route(from)
;continue;}if(IN6_IS_ADDR_LOOPBACK(&rte->addr)){zlog_warn("Destinationprefixisal
oopbackaddress%s/%d[%d]",inet6_ntoa(rte->addr),rte->prefixlen,rte->metric);ripng
_peer_bad_route(from);continue;}/*-istheprefixlengthvalid(i.e.,between0and128,in
clusive)*/if(rte->prefixlen>128){zlog_warn("Invalidprefixlength%s/%dfrom%s%%%s",
inet6_ntoa(rte->addr),rte->prefixlen,inet6_ntoa(from->sin6_addr),ifp->name);ripn
g_peer_bad_route(from);continue;}/*-isthemetricvalid(i.e.,between1and16,inclusiv
e)*/if(!(rte->metric>=1&&rte->metric<=16)){zlog_warn("Invalidmetric%dfrom%s%%%s"
,rte->metric,inet6_ntoa(from->sin6_addr),ifp->name);ripng_peer_bad_route(from);c
ontinue;}/*Vincent:XXXShouldwecomputethedirecltyreachablenexthop*forourRIPngnetw
ork?**//*Routingtableupdates.*/ripng_route_process(rte,from,&nexthop,ifp);}}/*Re
sponsetorequestmessage.*/staticvoidripng_request_process(structripng_packet*pack
et,intsize,structsockaddr_in6*from,structinterface*ifp){caddr_tlim;structrte*rte
;structprefix_ipv6p;structroute_node*rp;structripng_info*rinfo;structripng_inter
face*ri;/*Doesnotreponsetotherequestsontheloopbackinterfaces*/if(if_is_loopback(
ifp))return;/*CheckRIPngprocessisenabledonthisinterface.*/ri=ifp->info;if(!ri->r
unning)return;/*Whenpassiveinterfaceisspecified,suppressresponses*/if(ri->passiv
e)return;/*RIPngpeerupdate.*/ripng_peer_update(from,packet->version);lim=((caddr
_t)packet)+size;rte=packet->rte;/*TheRequestisprocessedentrybyentry.Ifthereareno
entries,noresponseisgiven.*/if(lim==(caddr_t)rte)return;/*Thereisonespecialcase.
Ifthereisexactlyoneentryintherequest,andithasadestinationprefixofzero,aprefixlen
gthofzero,andametricofinfinity(i.e.,16),thenthisisarequesttosendtheentirerouting
table.Inthatcase,acallismadetotheoutputprocesstosendtheroutingtabletotherequesti
ngaddress/port.*/if(lim==((caddr_t)(rte+1))&&IN6_IS_ADDR_UNSPECIFIED(&rte->addr)
&&rte->prefixlen==0&&rte->metric==RIPNG_METRIC_INFINITY){/*Allroutewithsplithori
zon*/ripng_output_process(ifp,from,ripng_all_route);}else{/*Exceptforthisspecial
case,processingisquitesimple.ExaminethelistofRTEsintheRequestonebyone.Foreachent
ry,lookupthedestinationintherouter'sroutingdatabaseand,ifthereisaroute,putthatro
ute'smetricinthemetricfieldoftheRTE.Ifthereisnoexplicitroutetothespecifieddestin
ation,putinfinityinthemetricfield.Oncealltheentrieshavebeenfilledin,changethecom
mandfromRequesttoResponseandsendthedatagrambacktotherequestor.*/memset(&p,0,size
of(structprefix_ipv6));p.family=AF_INET6;for(;((caddr_t)rte)<lim;rte++){p.prefix
=rte->addr;p.prefixlen=rte->prefixlen;apply_mask_ipv6(&p);rp=route_node_lookup(r
ipng->table,(structprefix*)&p);if(rp){rinfo=listgetdata(listhead((structlist*)rp
->info));rte->metric=rinfo->metric;route_unlock_node(rp);}elserte->metric=RIPNG_
METRIC_INFINITY;}packet->command=RIPNG_RESPONSE;ripng_send_packet((caddr_t)packe
t,size,from,ifp);}}/*FirstentrypointofreadingRIPngpacket.*/staticintripng_read(s
tructthread*thread){intlen;intsock;structsockaddr_in6from;structripng_packet*pac
ket;ifindex_tifindex=0;structinterface*ifp;inthoplimit=-1;/*Checkripngisactivean
dalive.*/assert(ripng!=NULL);assert(ripng->sock>=0);/*Fetchthreaddataandsetreadp
ointertoemptyforeventmanaging.`sock'souldbesameasripng->sock.*/sock=THREAD_FD(th
read);ripng->t_read=NULL;/*Addmyselftothenextevent.*/ripng_event(RIPNG_READ,sock
);/*ReadRIPngpacket.*/len=ripng_recv_packet(sock,STREAM_DATA(ripng->ibuf),STREAM
_SIZE(ripng->ibuf),&from,&ifindex,&hoplimit);if(len<0){zlog_warn("RIPngrecvfromf
ailed:%s.",safe_strerror(errno));returnlen;}/*CheckRTEboundary.RTEsize(Packetlen
gth-RIPngheadersize(4))mustbemultiplesizeofoneRTEsize(20).*/if(((len-4)%20)!=0){
zlog_warn("RIPnginvalidpacketsize%dfrom%s",len,inet6_ntoa(from.sin6_addr));ripng
_peer_bad_packet(&from);return0;}packet=(structripng_packet*)STREAM_DATA(ripng->
ibuf);ifp=if_lookup_by_index(ifindex,VRF_DEFAULT);/*RIPngpacketreceived.*/if(IS_
RIPNG_DEBUG_EVENT)zlog_debug("RIPngpacketreceivedfrom%sport%don%s",inet6_ntoa(fr
om.sin6_addr),ntohs(from.sin6_port),ifp?ifp->name:"unknown");/*Loggingbeforepack
etchecking.*/if(IS_RIPNG_DEBUG_RECV)ripng_packet_dump(packet,len,"RECV");/*Packe
tcomesfromunknowninterface.*/if(ifp==NULL){zlog_warn("RIPngpacketcomesfromunknow
ninterface%d",ifindex);return0;}/*Packetversionmismatchchecking.*/if(packet->ver
sion!=ripng->version){zlog_warn("RIPngpacketversion%ddoesn'tfittomyversion%d",pa
cket->version,ripng->version);ripng_peer_bad_packet(&from);return0;}/*ProcessRIP
ngpacket.*/switch(packet->command){caseRIPNG_REQUEST:ripng_request_process(packe
t,len,&from,ifp);break;caseRIPNG_RESPONSE:ripng_response_process(packet,len,&fro
m,ifp,hoplimit);break;default:zlog_warn("InvalidRIPngcommand%d",packet->command)
;ripng_peer_bad_packet(&from);break;}return0;}/*WalkdowntheRIPngroutingtablethen
clearchangedflag.*/staticvoidripng_clear_changed_flag(void){structroute_node*rp;
structripng_info*rinfo=NULL;structlist*list=NULL;structlistnode*listnode=NULL;fo
r(rp=route_top(ripng->table);rp;rp=route_next(rp))if((list=rp->info)!=NULL)for(A
LL_LIST_ELEMENTS_RO(list,listnode,rinfo)){UNSET_FLAG(rinfo->flags,RIPNG_RTF_CHAN
GED);/*Thisflagcanbesetonlyonthefirstentry.*/break;}}/*RegularupdateofRIPngroute
.SendallroutingformationtoRIPngenabledinterface.*/staticintripng_update(structth
read*t){structvrf*vrf=vrf_lookup_by_id(VRF_DEFAULT);structinterface*ifp;structri
png_interface*ri;/*Clearupdatetimerthread.*/ripng->t_update=NULL;/*Loggingupdate
event.*/if(IS_RIPNG_DEBUG_EVENT)zlog_debug("RIPngupdatetimerexpired!");/*Supplyr
outestoeachinterface.*/FOR_ALL_INTERFACES(vrf,ifp){ri=ifp->info;if(if_is_loopbac
k(ifp)||!if_is_up(ifp))continue;if(!ri->running)continue;/*Whenpassiveinterfacei
sspecified,suppressannouncetotheinterface.*/if(ri->passive)continue;#ifRIPNG_ADV
ANCEDif(ri->ri_send==RIPNG_SEND_OFF){if(IS_RIPNG_DEBUG_EVENT)zlog_debug("[Event]
RIPngsendtoif%dissuppressedbyconfig",ifp->ifindex);continue;}#endif/*RIPNG_ADVAN
CED*/ripng_output_process(ifp,NULL,ripng_all_route);}/*Triggeredupdatesmaybesupp
ressedifaregularupdateisduebythetimethetriggeredupdatewouldbesent.*/if(ripng->t_
triggered_interval){thread_cancel(ripng->t_triggered_interval);ripng->t_triggere
d_interval=NULL;}ripng->trigger=0;/*Resetflushevent.*/ripng_event(RIPNG_UPDATE_E
VENT,0);return0;}/*Triggeredupdateintervaltimer.*/staticintripng_triggered_inter
val(structthread*t){ripng->t_triggered_interval=NULL;if(ripng->trigger){ripng->t
rigger=0;ripng_triggered_update(t);}return0;}/*Executetriggeredupdate.*/intripng
_triggered_update(structthread*t){structvrf*vrf=vrf_lookup_by_id(VRF_DEFAULT);st
ructinterface*ifp;structripng_interface*ri;intinterval;ripng->t_triggered_update
=NULL;/*Cancelintervaltimer.*/if(ripng->t_triggered_interval){thread_cancel(ripn
g->t_triggered_interval);ripng->t_triggered_interval=NULL;}ripng->trigger=0;/*Lo
ggingtriggeredupdate.*/if(IS_RIPNG_DEBUG_EVENT)zlog_debug("RIPngtriggeredupdate!
");/*SplitHorizonprocessingisdonewhengeneratingtriggeredupdatesaswellasnormalupd
ates(seesection2.6).*/FOR_ALL_INTERFACES(vrf,ifp){ri=ifp->info;if(if_is_loopback
(ifp)||!if_is_up(ifp))continue;if(!ri->running)continue;/*Whenpassiveinterfaceis
specified,suppressannouncetotheinterface.*/if(ri->passive)continue;ripng_output_
process(ifp,NULL,ripng_changed_route);}/*Onceallofthetriggeredupdateshavebeengen
erated,theroutechangeflagsshouldbecleared.*/ripng_clear_changed_flag();/*Afterat
riggeredupdateissent,atimershouldbesetforarandomintervalbetween1and5seconds.Ifot
herchangesthatwouldtriggerupdatesoccurbeforethetimerexpires,asingleupdateistrigg
eredwhenthetimerexpires.*/interval=(random()%5)+1;ripng->t_triggered_interval=NU
LL;thread_add_timer(master,ripng_triggered_interval,NULL,interval,&ripng->t_trig
gered_interval);return0;}/*Writeroutingtableentrytothestreamandreturnnextindexof
theroutingtableentryinthestream.*/intripng_write_rte(intnum,structstream*s,struc
tprefix_ipv6*p,structin6_addr*nexthop,uint16_ttag,uint8_tmetric){/*RIPngpackethe
ader.*/if(num==0){stream_putc(s,RIPNG_RESPONSE);stream_putc(s,RIPNG_V1);stream_p
utw(s,0);}/*Writeroutingtableentry.*/if(!nexthop)stream_write(s,(uint8_t*)&p->pr
efix,sizeof(structin6_addr));elsestream_write(s,(uint8_t*)nexthop,sizeof(structi
n6_addr));stream_putw(s,tag);if(p)stream_putc(s,p->prefixlen);elsestream_putc(s,
0);stream_putc(s,metric);return++num;}/*SendRESPONSEmessagetospecifieddestinatio
n.*/voidripng_output_process(structinterface*ifp,structsockaddr_in6*to,introute_
type){intret;structroute_node*rp;structripng_info*rinfo;structripng_interface*ri
;structripng_aggregate*aggregate;structprefix_ipv6*p;structlist*ripng_rte_list;s
tructlist*list=NULL;structlistnode*listnode=NULL;if(IS_RIPNG_DEBUG_EVENT){if(to)
zlog_debug("RIPngupdateroutestoneighbor%s",inet6_ntoa(to->sin6_addr));elsezlog_d
ebug("RIPngupdateroutesoninterface%s",ifp->name);}/*GetRIPnginterface.*/ri=ifp->
info;ripng_rte_list=ripng_rte_new();for(rp=route_top(ripng->table);rp;rp=route_n
ext(rp)){if((list=rp->info)!=NULL&&(rinfo=listgetdata(listhead(list)))!=NULL&&ri
nfo->suppress==0){/*Ifnoroute-mapareapplied,theRTEwillbethese*following*informat
ions.*/p=(structprefix_ipv6*)&rp->p;rinfo->metric_out=rinfo->metric;rinfo->tag_o
ut=rinfo->tag;memset(&rinfo->nexthop_out,0,sizeof(rinfo->nexthop_out));/*Inorder
toavoidsomelocalloops,*iftheRIPngroutehasanexthopviathisinterface,*keepthenextho
p,*otherwisesetitto0.Thenexthopshouldnotbe*propagated*beyondthelocalbroadcast/mu
lticastareainorder*toavoidanIGPmulti-levelrecursivelook-up.*/if(rinfo->ifindex==
ifp->ifindex)rinfo->nexthop_out=rinfo->nexthop;/*Applyoutputfilters.*/ret=ripng_
filter(RIPNG_FILTER_OUT,p,ri);if(ret<0)continue;/*Changedrouteonlyoutput.*/if(ro
ute_type==ripng_changed_route&&(!(rinfo->flags&RIPNG_RTF_CHANGED)))continue;/*Sp
lithorizon.*/if(ri->split_horizon==RIPNG_SPLIT_HORIZON){/*Weperformsplithorizonf
orRIPngroutes.*/intsuppress=0;structripng_info*tmp_rinfo=NULL;for(ALL_LIST_ELEME
NTS_RO(list,listnode,tmp_rinfo))if(tmp_rinfo->type==ZEBRA_ROUTE_RIPNG&&tmp_rinfo
->ifindex==ifp->ifindex){suppress=1;break;}if(suppress)continue;}/*Preparationfo
rroute-map.*/rinfo->metric_set=0;/*nexthop_out,*metric_out*andtag_outarealreadyi
nitialized.*//*Interfaceroute-map*/if(ri->routemap[RIPNG_FILTER_OUT]){intret;ret
=route_map_apply(ri->routemap[RIPNG_FILTER_OUT],(structprefix*)p,RMAP_RIPNG,rinf
o);if(ret==RMAP_DENYMATCH){if(IS_RIPNG_DEBUG_PACKET)zlog_debug("RIPng%s/%disfilt
eredbyroute-mapout",inet6_ntoa(p->prefix),p->prefixlen);continue;}}/*Redistribut
eroute-map.*/if(ripng->route_map[rinfo->type].name){intret;ret=route_map_apply(r
ipng->route_map[rinfo->type].map,(structprefix*)p,RMAP_RIPNG,rinfo);if(ret==RMAP
_DENYMATCH){if(IS_RIPNG_DEBUG_PACKET)zlog_debug("RIPng%s/%disfilteredbyroute-map
",inet6_ntoa(p->prefix),p->prefixlen);continue;}}/*Whentheroute-mapdoesnotsetmet
ric.*/if(!rinfo->metric_set){/*Iftheredistributemetricisset.*/if(ripng->route_ma
p[rinfo->type].metric_config&&rinfo->metric!=RIPNG_METRIC_INFINITY){rinfo->metri
c_out=ripng->route_map[rinfo->type].metric;}else{/*Iftherouteisnotconnectedorloc
alygeneratedone,usedefault-metricvalue*/if(rinfo->type!=ZEBRA_ROUTE_RIPNG&&rinfo
->type!=ZEBRA_ROUTE_CONNECT&&rinfo->metric!=RIPNG_METRIC_INFINITY)rinfo->metric_
out=ripng->default_metric;}}/*Applyoffset-list*/if(rinfo->metric_out!=RIPNG_METR
IC_INFINITY)ripng_offset_list_apply_out(p,ifp,&rinfo->metric_out);if(rinfo->metr
ic_out>RIPNG_METRIC_INFINITY)rinfo->metric_out=RIPNG_METRIC_INFINITY;/*Performsp
lit-horizonwithpoisonedreverse*forRIPngroutes.**/if(ri->split_horizon==RIPNG_SPL
IT_HORIZON_POISONED_REVERSE){structripng_info*tmp_rinfo=NULL;for(ALL_LIST_ELEMEN
TS_RO(list,listnode,tmp_rinfo))if((tmp_rinfo->type==ZEBRA_ROUTE_RIPNG)&&tmp_rinf
o->ifindex==ifp->ifindex)rinfo->metric_out=RIPNG_METRIC_INFINITY;}/*AddRTEtothel
ist*/ripng_rte_add(ripng_rte_list,p,rinfo,NULL);}/*ProcesstheaggregatedRTEentry*
/if((aggregate=rp->aggregate)!=NULL&&aggregate->count>0&&aggregate->suppress==0)
{/*Ifnoroute-mapareapplied,theRTEwillbethese*following*informations.*/p=(structp
refix_ipv6*)&rp->p;aggregate->metric_set=0;aggregate->metric_out=aggregate->metr
ic;aggregate->tag_out=aggregate->tag;memset(&aggregate->nexthop_out,0,sizeof(agg
regate->nexthop_out));/*Applyoutputfilters.*/ret=ripng_filter(RIPNG_FILTER_OUT,p
,ri);if(ret<0)continue;/*Interfaceroute-map*/if(ri->routemap[RIPNG_FILTER_OUT]){
intret;structripng_infonewinfo;/*let'scasttheaggregatestructureto*ripng_info*/me
mset(&newinfo,0,sizeof(structripng_info));/*thenexthopis::*/newinfo.metric=aggre
gate->metric;newinfo.metric_out=aggregate->metric_out;newinfo.tag=aggregate->tag
;newinfo.tag_out=aggregate->tag_out;ret=route_map_apply(ri->routemap[RIPNG_FILTE
R_OUT],(structprefix*)p,RMAP_RIPNG,&newinfo);if(ret==RMAP_DENYMATCH){if(IS_RIPNG
_DEBUG_PACKET)zlog_debug("RIPng%s/%disfilteredbyroute-mapout",inet6_ntoa(p->pref
ix),p->prefixlen);continue;}aggregate->metric_out=newinfo.metric_out;aggregate->
tag_out=newinfo.tag_out;if(IN6_IS_ADDR_LINKLOCAL(&newinfo.nexthop_out))aggregate
->nexthop_out=newinfo.nexthop_out;}/*Thereisnoredistributeroutemapfortheaggregat
ed*RTE*//*Changedrouteonlyoutput.*//*XXX,vincent,inordertoincreasetimeconvergenc
e,*itshouldbeannouncedifachildhaschanged.*/if(route_type==ripng_changed_route)co
ntinue;/*Applyoffset-list*/if(aggregate->metric_out!=RIPNG_METRIC_INFINITY)ripng
_offset_list_apply_out(p,ifp,&aggregate->metric_out);if(aggregate->metric_out>RI
PNG_METRIC_INFINITY)aggregate->metric_out=RIPNG_METRIC_INFINITY;/*AddRTEtothelis
t*/ripng_rte_add(ripng_rte_list,p,NULL,aggregate);}}/*Flushthelist*/ripng_rte_se
nd(ripng_rte_list,ifp,to);ripng_rte_free(ripng_rte_list);}/*CreatenewRIPnginstan
ceandsetittoglobalvariable.*/staticintripng_create(void){/*ripngshouldbeNULL.*/a
ssert(ripng==NULL);/*AllocasteRIPnginstance.*/ripng=XCALLOC(MTYPE_RIPNG,sizeof(s
tructripng));/*Defaultversionandtimervalues.*/ripng->version=RIPNG_V1;ripng->upd
ate_time=RIPNG_UPDATE_TIMER_DEFAULT;ripng->timeout_time=RIPNG_TIMEOUT_TIMER_DEFA
ULT;ripng->garbage_time=RIPNG_GARBAGE_TIMER_DEFAULT;ripng->default_metric=RIPNG_
DEFAULT_METRIC_DEFAULT;/*Makebuffer.*/ripng->ibuf=stream_new(RIPNG_MAX_PACKET_SI
ZE*5);ripng->obuf=stream_new(RIPNG_MAX_PACKET_SIZE);/*InitializeRIPngroutigtable
.*/ripng->table=route_table_init();ripng->route=route_table_init();ripng->aggreg
ate=route_table_init();/*Makesocket.*/ripng->sock=ripng_make_socket();if(ripng->
sock<0)returnripng->sock;/*Threads.*/ripng_event(RIPNG_READ,ripng->sock);ripng_e
vent(RIPNG_UPDATE_EVENT,1);return0;}/*SendRIPngrequesttotheinterface.*/intripng_
request(structinterface*ifp){structrte*rte;structripng_packetripng_packet;/*Inde
faultripddoesn'tsendRIP_REQUESTtotheloopbackinterface.*/if(if_is_loopback(ifp))r
eturn0;/*Ifinterfaceisdown,don'tsendRIPpacket.*/if(!if_is_up(ifp))return0;if(IS_
RIPNG_DEBUG_EVENT)zlog_debug("RIPngsendrequestto%s",ifp->name);memset(&ripng_pac
ket,0,sizeof(ripng_packet));ripng_packet.command=RIPNG_REQUEST;ripng_packet.vers
ion=RIPNG_V1;rte=ripng_packet.rte;rte->metric=RIPNG_METRIC_INFINITY;returnripng_
send_packet((caddr_t)&ripng_packet,sizeof(ripng_packet),NULL,ifp);}staticintripn
g_update_jitter(inttime){return((random()%(time+1))-(time/2));}voidripng_event(e
numripng_eventevent,intsock){intjitter=0;switch(event){caseRIPNG_READ:thread_add
_read(master,ripng_read,NULL,sock,&ripng->t_read);break;caseRIPNG_UPDATE_EVENT:i
f(ripng->t_update){thread_cancel(ripng->t_update);ripng->t_update=NULL;}/*Update
timerjitter.*/jitter=ripng_update_jitter(ripng->update_time);ripng->t_update=NUL
L;thread_add_timer(master,ripng_update,NULL,sock?2:ripng->update_time+jitter,&ri
png->t_update);break;caseRIPNG_TRIGGERED_UPDATE:if(ripng->t_triggered_interval)r
ipng->trigger=1;elsethread_add_event(master,ripng_triggered_update,NULL,0,&ripng
->t_triggered_update);break;default:break;}}/*Printoutroutesupdatetime.*/staticv
oidripng_vty_out_uptime(structvty*vty,structripng_info*rinfo){time_tclock;struct
tm*tm;#defineTIME_BUF25chartimebuf[TIME_BUF];structthread*thread;if((thread=rinf
o->t_timeout)!=NULL){clock=thread_timer_remain_second(thread);tm=gmtime(&clock);
strftime(timebuf,TIME_BUF,"%M:%S",tm);vty_out(vty,"%5s",timebuf);}elseif((thread
=rinfo->t_garbage_collect)!=NULL){clock=thread_timer_remain_second(thread);tm=gm
time(&clock);strftime(timebuf,TIME_BUF,"%M:%S",tm);vty_out(vty,"%5s",timebuf);}}
staticchar*ripng_route_subtype_print(structripng_info*rinfo){staticcharstr[3];me
mset(str,0,3);if(rinfo->suppress)strcat(str,"S");switch(rinfo->sub_type){caseRIP
NG_ROUTE_RTE:strcat(str,"n");break;caseRIPNG_ROUTE_STATIC:strcat(str,"s");break;
caseRIPNG_ROUTE_DEFAULT:strcat(str,"d");break;caseRIPNG_ROUTE_REDISTRIBUTE:strca
t(str,"r");break;caseRIPNG_ROUTE_INTERFACE:strcat(str,"i");break;default:strcat(
str,"?");break;}returnstr;}DEFUN(show_ipv6_ripng,show_ipv6_ripng_cmd,"showipv6ri
png",SHOW_STRIPV6_STR"ShowRIPngroutes\n"){structroute_node*rp;structripng_info*r
info;structripng_aggregate*aggregate;structprefix_ipv6*p;structlist*list=NULL;st
ructlistnode*listnode=NULL;intlen;if(!ripng)returnCMD_SUCCESS;/*Headerofdisplay.
*/vty_out(vty,"Codes:R-RIPng,C-connected,S-Static,O-OSPF,B-BGP\n""Sub-codes:\n""
(n)-normal,(s)-static,(d)-default,(r)-redistribute,\n""(i)-interface,(a/S)-aggre
gated/Suppressed\n\n""NetworkNextHopViaMetricTagTime\n");for(rp=route_top(ripng-
>table);rp;rp=route_next(rp)){if((aggregate=rp->aggregate)!=NULL){p=(structprefi
x_ipv6*)&rp->p;#ifdefDEBUGvty_out(vty,"R(a)%d/%d%s/%d",aggregate->count,aggregat
e->suppress,inet6_ntoa(p->prefix),p->prefixlen);#elsevty_out(vty,"R(a)%s/%d",ine
t6_ntoa(p->prefix),p->prefixlen);#endif/*DEBUG*/vty_out(vty,"\n");vty_out(vty,"%
*s",18,"");vty_out(vty,"%*s",28,"");vty_out(vty,"self%2d%3"ROUTE_TAG_PRI"\n",agg
regate->metric,(route_tag_t)aggregate->tag);}if((list=rp->info)!=NULL)for(ALL_LI
ST_ELEMENTS_RO(list,listnode,rinfo)){p=(structprefix_ipv6*)&rp->p;#ifdefDEBUGvty
_out(vty,"%c(%s)0/%d%s/%d",zebra_route_char(rinfo->type),ripng_route_subtype_pri
nt(rinfo),rinfo->suppress,inet6_ntoa(p->prefix),p->prefixlen);#elsevty_out(vty,"
%c(%s)%s/%d",zebra_route_char(rinfo->type),ripng_route_subtype_print(rinfo),inet
6_ntoa(p->prefix),p->prefixlen);#endif/*DEBUG*/vty_out(vty,"\n");vty_out(vty,"%*
s",18,"");len=vty_out(vty,"%s",inet6_ntoa(rinfo->nexthop));len=28-len;if(len>0)v
ty_out(vty,"%*s",len,"");/*from*/if((rinfo->type==ZEBRA_ROUTE_RIPNG)&&(rinfo->su
b_type==RIPNG_ROUTE_RTE)){len=vty_out(vty,"%s",ifindex2ifname(rinfo->ifindex,VRF
_DEFAULT));}elseif(rinfo->metric==RIPNG_METRIC_INFINITY){len=vty_out(vty,"kill")
;}elselen=vty_out(vty,"self");len=9-len;if(len>0)vty_out(vty,"%*s",len,"");vty_o
ut(vty,"%2d%3"ROUTE_TAG_PRI"",rinfo->metric,(route_tag_t)rinfo->tag);/*time*/if(
(rinfo->type==ZEBRA_ROUTE_RIPNG)&&(rinfo->sub_type==RIPNG_ROUTE_RTE)){/*RTEfromr
emoteRIProuters*/ripng_vty_out_uptime(vty,rinfo);}elseif(rinfo->metric==RIPNG_ME
TRIC_INFINITY){/*poisonousreversedroutes(gc)*/ripng_vty_out_uptime(vty,rinfo);}v
ty_out(vty,"\n");}}returnCMD_SUCCESS;}DEFUN(show_ipv6_ripng_status,show_ipv6_rip
ng_status_cmd,"showipv6ripngstatus",SHOW_STRIPV6_STR"ShowRIPngroutes\n""IPv6rout
ingprotocolprocessparametersandstatistics\n"){structvrf*vrf=vrf_lookup_by_id(VRF
_DEFAULT);structinterface*ifp;if(!ripng)returnCMD_SUCCESS;vty_out(vty,"RoutingPr
otocolis\"RIPng\"\n");vty_out(vty,"Sendingupdatesevery%ldsecondswith+/-50%%,",ri
png->update_time);vty_out(vty,"nextduein%luseconds\n",thread_timer_remain_second
(ripng->t_update));vty_out(vty,"Timeoutafter%ldseconds,",ripng->timeout_time);vt
y_out(vty,"garbagecollectafter%ldseconds\n",ripng->garbage_time);/*Filteringstat
usshow.*/config_show_distribute(vty);/*Defaultmetricinformation.*/vty_out(vty,"D
efaultredistributionmetricis%d\n",ripng->default_metric);/*Redistributeinformati
on.*/vty_out(vty,"Redistributing:");ripng_redistribute_write(vty,0);vty_out(vty,
"\n");vty_out(vty,"Defaultversioncontrol:sendversion%d,",ripng->version);vty_out
(vty,"receiveversion%d\n",ripng->version);vty_out(vty,"InterfaceSendRecv\n");FOR
_ALL_INTERFACES(vrf,ifp){structripng_interface*ri;ri=ifp->info;if(ri->enable_net
work||ri->enable_interface){vty_out(vty,"%-17s%-3d%-3d\n",ifp->name,ripng->versi
on,ripng->version);}}vty_out(vty,"RoutingforNetworks:\n");ripng_network_write(vt
y,0);vty_out(vty,"RoutingInformationSources:\n");vty_out(vty,"GatewayBadPacketsB
adRoutesDistanceLastUpdate\n");ripng_peer_display(vty);returnCMD_SUCCESS;}DEFUN(
clear_ipv6_rip,clear_ipv6_rip_cmd,"clearipv6ripng",CLEAR_STRIPV6_STR"ClearIPv6RI
Pdatabase\n"){structroute_node*rp;structripng_info*rinfo;structlist*list;structl
istnode*listnode;/*ClearreceivedRIPngroutes*/for(rp=route_top(ripng->table);rp;r
p=route_next(rp)){list=rp->info;if(list==NULL)continue;for(ALL_LIST_ELEMENTS_RO(
list,listnode,rinfo)){if(!ripng_route_rte(rinfo))continue;if(CHECK_FLAG(rinfo->f
lags,RIPNG_RTF_FIB))ripng_zebra_ipv6_delete(rp);break;}if(rinfo){RIPNG_TIMER_OFF
(rinfo->t_timeout);RIPNG_TIMER_OFF(rinfo->t_garbage_collect);listnode_delete(lis
t,rinfo);ripng_info_free(rinfo);}if(list_isempty(list)){list_delete_and_null(&li
st);rp->info=NULL;route_unlock_node(rp);}}returnCMD_SUCCESS;}DEFUN_NOSH(router_r
ipng,router_ripng_cmd,"routerripng","Enablearoutingprocess\n""MakeRIPnginstancec
ommand\n"){intret;vty->node=RIPNG_NODE;if(!ripng){ret=ripng_create();/*Noticetou
serwecouldn'tcreateRIPng.*/if(ret<0){zlog_warn("can'tcreateRIPng");returnCMD_WAR
NING_CONFIG_FAILED;}}returnCMD_SUCCESS;}DEFUN(no_router_ripng,no_router_ripng_cm
d,"norouterripng",NO_STR"Enablearoutingprocess\n""MakeRIPnginstancecommand\n"){i
f(ripng)ripng_clean();returnCMD_SUCCESS;}DEFUN(ripng_route,ripng_route_cmd,"rout
eIPV6ADDR","Staticroutesetup\n""SetstaticRIPngrouteannouncement\n"){intidx_ipv6a
ddr=1;intret;structprefix_ipv6p;structroute_node*rp;ret=str2prefix_ipv6(argv[idx
_ipv6addr]->arg,(structprefix_ipv6*)&p);if(ret<=0){vty_out(vty,"Malformedaddress
\n");returnCMD_WARNING_CONFIG_FAILED;}apply_mask_ipv6(&p);rp=route_node_get(ripn
g->route,(structprefix*)&p);if(rp->info){vty_out(vty,"Thereisalreadysamestaticro
ute.\n");route_unlock_node(rp);returnCMD_WARNING;}rp->info=(void*)1;ripng_redist
ribute_add(ZEBRA_ROUTE_RIPNG,RIPNG_ROUTE_STATIC,&p,0,NULL,0);returnCMD_SUCCESS;}
DEFUN(no_ripng_route,no_ripng_route_cmd,"norouteIPV6ADDR",NO_STR"Staticroutesetu
p\n""DeletestaticRIPngrouteannouncement\n"){intidx_ipv6addr=2;intret;structprefi
x_ipv6p;structroute_node*rp;ret=str2prefix_ipv6(argv[idx_ipv6addr]->arg,(structp
refix_ipv6*)&p);if(ret<=0){vty_out(vty,"Malformedaddress\n");returnCMD_WARNING_C
ONFIG_FAILED;}apply_mask_ipv6(&p);rp=route_node_lookup(ripng->route,(structprefi
x*)&p);if(!rp){vty_out(vty,"Can'tfindstaticroute.\n");returnCMD_WARNING_CONFIG_F
AILED;}ripng_redistribute_delete(ZEBRA_ROUTE_RIPNG,RIPNG_ROUTE_STATIC,&p,0);rout
e_unlock_node(rp);rp->info=NULL;route_unlock_node(rp);returnCMD_SUCCESS;}DEFUN(r
ipng_aggregate_address,ripng_aggregate_address_cmd,"aggregate-addressX:X::X:X/M"
,"SetaggregateRIPngrouteannouncement\n""Aggregatenetwork\n"){intidx_ipv6_prefixl
en=1;intret;structprefixp;structroute_node*node;ret=str2prefix_ipv6(argv[idx_ipv
6_prefixlen]->arg,(structprefix_ipv6*)&p);if(ret<=0){vty_out(vty,"Malformedaddre
ss\n");returnCMD_WARNING_CONFIG_FAILED;}/*Checkaggregatealredyexistornot.*/node=
route_node_get(ripng->aggregate,&p);if(node->info){vty_out(vty,"Thereisalreadysa
meaggregateroute.\n");route_unlock_node(node);returnCMD_WARNING;}node->info=(voi
d*)1;ripng_aggregate_add(&p);returnCMD_SUCCESS;}DEFUN(no_ripng_aggregate_address
,no_ripng_aggregate_address_cmd,"noaggregate-addressX:X::X:X/M",NO_STR"Deleteagg
regateRIPngrouteannouncement\n""Aggregatenetwork\n"){intidx_ipv6_prefixlen=2;int
ret;structprefixp;structroute_node*rn;ret=str2prefix_ipv6(argv[idx_ipv6_prefixle
n]->arg,(structprefix_ipv6*)&p);if(ret<=0){vty_out(vty,"Malformedaddress\n");ret
urnCMD_WARNING_CONFIG_FAILED;}rn=route_node_lookup(ripng->aggregate,&p);if(!rn){
vty_out(vty,"Can'tfindaggregateroute.\n");returnCMD_WARNING_CONFIG_FAILED;}route
_unlock_node(rn);rn->info=NULL;route_unlock_node(rn);ripng_aggregate_delete(&p);
returnCMD_SUCCESS;}DEFUN(ripng_default_metric,ripng_default_metric_cmd,"default-
metric(1-16)","Setametricofredistributeroutes\n""Defaultmetric\n"){intidx_number
=1;if(ripng){ripng->default_metric=atoi(argv[idx_number]->arg);}returnCMD_SUCCES
S;}DEFUN(no_ripng_default_metric,no_ripng_default_metric_cmd,"nodefault-metric[(
1-16)]",NO_STR"Setametricofredistributeroutes\n""Defaultmetric\n"){if(ripng){rip
ng->default_metric=RIPNG_DEFAULT_METRIC_DEFAULT;}returnCMD_SUCCESS;}#if0/*RIPngu
pdatetimersetup.*/DEFUN(ripng_update_timer,ripng_update_timer_cmd,"update-timerS
ECOND","SetRIPngupdatetimerinseconds\n""Seconds\n"){unsignedlongupdate;char*endp
tr=NULL;update=strtoul(argv[0],&endptr,10);if(update==ULONG_MAX||*endptr!='\0'){
vty_out(vty,"updatetimervalueerror\n");returnCMD_WARNING_CONFIG_FAILED;}ripng->u
pdate_time=update;ripng_event(RIPNG_UPDATE_EVENT,0);returnCMD_SUCCESS;}DEFUN(no_
ripng_update_timer,no_ripng_update_timer_cmd,"noupdate-timerSECOND",NO_STR"Unset
RIPngupdatetimerinseconds\n""Seconds\n"){ripng->update_time=RIPNG_UPDATE_TIMER_D
EFAULT;ripng_event(RIPNG_UPDATE_EVENT,0);returnCMD_SUCCESS;}/*RIPngtimeouttimers
etup.*/DEFUN(ripng_timeout_timer,ripng_timeout_timer_cmd,"timeout-timerSECOND","
SetRIPngtimeouttimerinseconds\n""Seconds\n"){unsignedlongtimeout;char*endptr=NUL
L;timeout=strtoul(argv[0],&endptr,10);if(timeout==ULONG_MAX||*endptr!='\0'){vty_
out(vty,"timeouttimervalueerror\n");returnCMD_WARNING_CONFIG_FAILED;}ripng->time
out_time=timeout;returnCMD_SUCCESS;}DEFUN(no_ripng_timeout_timer,no_ripng_timeou
t_timer_cmd,"notimeout-timerSECOND",NO_STR"UnsetRIPngtimeouttimerinseconds\n""Se
conds\n"){ripng->timeout_time=RIPNG_TIMEOUT_TIMER_DEFAULT;returnCMD_SUCCESS;}/*R
IPnggarbagetimersetup.*/DEFUN(ripng_garbage_timer,ripng_garbage_timer_cmd,"garba
ge-timerSECOND","SetRIPnggarbagetimerinseconds\n""Seconds\n"){unsignedlonggarbag
e;char*endptr=NULL;garbage=strtoul(argv[0],&endptr,10);if(garbage==ULONG_MAX||*e
ndptr!='\0'){vty_out(vty,"garbagetimervalueerror\n");returnCMD_WARNING_CONFIG_FA
ILED;}ripng->garbage_time=garbage;returnCMD_SUCCESS;}DEFUN(no_ripng_garbage_time
r,no_ripng_garbage_timer_cmd,"nogarbage-timerSECOND",NO_STR"UnsetRIPnggarbagetim
erinseconds\n""Seconds\n"){ripng->garbage_time=RIPNG_GARBAGE_TIMER_DEFAULT;retur
nCMD_SUCCESS;}#endif/*0*/DEFUN(ripng_timers,ripng_timers_cmd,"timersbasic(0-6553
5)(0-65535)(0-65535)","RIPngtimerssetup\n""Basictimer\n""Routingtableupdatetimer
valueinsecond.Defaultis30.\n""Routinginformationtimeouttimer.Defaultis180.\n""Ga
rbagecollectiontimer.Defaultis120.\n"){intidx_number=2;intidx_number_2=3;intidx_
number_3=4;unsignedlongupdate;unsignedlongtimeout;unsignedlonggarbage;update=str
toul(argv[idx_number]->arg,NULL,10);timeout=strtoul(argv[idx_number_2]->arg,NULL
,10);garbage=strtoul(argv[idx_number_3]->arg,NULL,10);/*Seteachtimervalue.*/ripn
g->update_time=update;ripng->timeout_time=timeout;ripng->garbage_time=garbage;/*
Resetupdatetimerthread.*/ripng_event(RIPNG_UPDATE_EVENT,0);returnCMD_SUCCESS;}DE
FUN(no_ripng_timers,no_ripng_timers_cmd,"notimersbasic[(0-65535)(0-65535)(0-6553
5)]",NO_STR"RIPngtimerssetup\n""Basictimer\n""Routingtableupdatetimervalueinseco
nd.Defaultis30.\n""Routinginformationtimeouttimer.Defaultis180.\n""Garbagecollec
tiontimer.Defaultis120.\n"){/*Seteachtimervaluetothedefault.*/ripng->update_time
=RIPNG_UPDATE_TIMER_DEFAULT;ripng->timeout_time=RIPNG_TIMEOUT_TIMER_DEFAULT;ripn
g->garbage_time=RIPNG_GARBAGE_TIMER_DEFAULT;/*Resetupdatetimerthread.*/ripng_eve
nt(RIPNG_UPDATE_EVENT,0);returnCMD_SUCCESS;}#if0DEFUN(show_ipv6_protocols,show_i
pv6_protocols_cmd,"showipv6protocols",SHOW_STRIPV6_STR"Routingprotocolinformatio
n\n"){if(!ripng)returnCMD_SUCCESS;vty_out(vty,"RoutingProtocolis\"ripng\"\n");vt
y_out(vty,"Sendingupdatesevery%ldseconds,nextduein%dseconds\n",ripng->update_tim
e,0);vty_out(vty,"Timeroutafter%ldseconds,garbagecorrect%ld\n",ripng->timeout_ti
me,ripng->garbage_time);vty_out(vty,"Outgoingupdatefilterlistforallinterfacesisn
otset");vty_out(vty,"Incomingupdatefilterlistforallinterfacesisnotset");returnCM
D_SUCCESS;}#endif/*Pleasebecarefulltousethiscommand.*/DEFUN(ripng_default_inform
ation_originate,ripng_default_information_originate_cmd,"default-informationorig
inate","Defaultrouteinformation\n""Distributedefaultroute\n"){structprefix_ipv6p
;if(!ripng->default_information){ripng->default_information=1;str2prefix_ipv6(":
:/0",&p);ripng_redistribute_add(ZEBRA_ROUTE_RIPNG,RIPNG_ROUTE_DEFAULT,&p,0,NULL,
0);}returnCMD_SUCCESS;}DEFUN(no_ripng_default_information_originate,no_ripng_def
ault_information_originate_cmd,"nodefault-informationoriginate",NO_STR"Defaultro
uteinformation\n""Distributedefaultroute\n"){structprefix_ipv6p;if(ripng->defaul
t_information){ripng->default_information=0;str2prefix_ipv6("::/0",&p);ripng_red
istribute_delete(ZEBRA_ROUTE_RIPNG,RIPNG_ROUTE_DEFAULT,&p,0);}returnCMD_SUCCESS;
}/*UpdateECMProutestozebrawhenECMPisdisabled.*/staticvoidripng_ecmp_disable(void
){structroute_node*rp;structripng_info*rinfo,*tmp_rinfo;structlist*list;structli
stnode*node,*nextnode;if(!ripng)return;for(rp=route_top(ripng->table);rp;rp=rout
e_next(rp))if((list=rp->info)!=NULL&&listcount(list)>1){rinfo=listgetdata(listhe
ad(list));if(!ripng_route_rte(rinfo))continue;/*Dropallotherentries,exceptthefir
stone.*/for(ALL_LIST_ELEMENTS(list,node,nextnode,tmp_rinfo))if(tmp_rinfo!=rinfo)
{RIPNG_TIMER_OFF(tmp_rinfo->t_timeout);RIPNG_TIMER_OFF(tmp_rinfo->t_garbage_coll
ect);list_delete_node(list,node);ripng_info_free(tmp_rinfo);}/*Updatezebra.*/rip
ng_zebra_ipv6_add(rp);/*Settheroutechangeflag.*/SET_FLAG(rinfo->flags,RIPNG_RTF_
CHANGED);/*Signaltheoutputprocesstotriggeranupdate.*/ripng_event(RIPNG_TRIGGERED
_UPDATE,0);}}DEFUN(ripng_allow_ecmp,ripng_allow_ecmp_cmd,"allow-ecmp","AllowEqua
lCostMultiPath\n"){if(ripng->ecmp){vty_out(vty,"ECMPisalreadyenabled.\n");return
CMD_WARNING;}ripng->ecmp=1;zlog_info("ECMPisenabled.");returnCMD_SUCCESS;}DEFUN(
no_ripng_allow_ecmp,no_ripng_allow_ecmp_cmd,"noallow-ecmp",NO_STR"AllowEqualCost
MultiPath\n"){if(!ripng->ecmp){vty_out(vty,"ECMPisalreadydisabled.\n");returnCMD
_WARNING;}ripng->ecmp=0;zlog_info("ECMPisdisabled.");ripng_ecmp_disable();return
CMD_SUCCESS;}/*RIPngconfigurationwritefunction.*/staticintripng_config_write(str
uctvty*vty){intripng_network_write(structvty*,int);voidripng_redistribute_write(
structvty*,int);intwrite=0;structroute_node*rp;if(ripng){/*RIPngrouter.*/vty_out
(vty,"routerripng\n");if(ripng->default_information)vty_out(vty,"default-informa
tionoriginate\n");ripng_network_write(vty,1);/*RIPngdefaultmetricconfiguration*/
if(ripng->default_metric!=RIPNG_DEFAULT_METRIC_DEFAULT)vty_out(vty,"default-metr
ic%d\n",ripng->default_metric);ripng_redistribute_write(vty,1);/*RIPoffset-listc
onfiguration.*/config_write_ripng_offset_list(vty);/*RIPngaggregateroutes.*/for(
rp=route_top(ripng->aggregate);rp;rp=route_next(rp))if(rp->info!=NULL)vty_out(vt
y,"aggregate-address%s/%d\n",inet6_ntoa(rp->p.u.prefix6),rp->p.prefixlen);/*ECMP
configuration.*/if(ripng->ecmp)vty_out(vty,"allow-ecmp\n");/*RIPngstaticroutes.*
/for(rp=route_top(ripng->route);rp;rp=route_next(rp))if(rp->info!=NULL)vty_out(v
ty,"route%s/%d\n",inet6_ntoa(rp->p.u.prefix6),rp->p.prefixlen);/*RIPngtimersconf
iguration.*/if(ripng->update_time!=RIPNG_UPDATE_TIMER_DEFAULT||ripng->timeout_ti
me!=RIPNG_TIMEOUT_TIMER_DEFAULT||ripng->garbage_time!=RIPNG_GARBAGE_TIMER_DEFAUL
T){vty_out(vty,"timersbasic%ld%ld%ld\n",ripng->update_time,ripng->timeout_time,r
ipng->garbage_time);}#if0if(ripng->update_time!=RIPNG_UPDATE_TIMER_DEFAULT)vty_o
ut(vty,"update-timer%d\n",ripng->update_time);if(ripng->timeout_time!=RIPNG_TIME
OUT_TIMER_DEFAULT)vty_out(vty,"timeout-timer%d\n",ripng->timeout_time);if(ripng-
>garbage_time!=RIPNG_GARBAGE_TIMER_DEFAULT)vty_out(vty,"garbage-timer%d\n",ripng
->garbage_time);#endif/*0*/write+=config_write_distribute(vty);write+=config_wri
te_if_rmap(vty);write++;}returnwrite;}/*RIPngnodestructure.*/staticstructcmd_nod
ecmd_ripng_node={RIPNG_NODE,"%s(config-router)#",1,};staticvoidripng_distribute_
update(structdistribute*dist){structinterface*ifp;structripng_interface*ri;struc
taccess_list*alist;structprefix_list*plist;if(!dist->ifname)return;ifp=if_lookup
_by_name(dist->ifname,VRF_DEFAULT);if(ifp==NULL)return;ri=ifp->info;if(dist->lis
t[DISTRIBUTE_V6_IN]){alist=access_list_lookup(AFI_IP6,dist->list[DISTRIBUTE_V6_I
N]);if(alist)ri->list[RIPNG_FILTER_IN]=alist;elseri->list[RIPNG_FILTER_IN]=NULL;
}elseri->list[RIPNG_FILTER_IN]=NULL;if(dist->list[DISTRIBUTE_V6_OUT]){alist=acce
ss_list_lookup(AFI_IP6,dist->list[DISTRIBUTE_V6_OUT]);if(alist)ri->list[RIPNG_FI
LTER_OUT]=alist;elseri->list[RIPNG_FILTER_OUT]=NULL;}elseri->list[RIPNG_FILTER_O
UT]=NULL;if(dist->prefix[DISTRIBUTE_V6_IN]){plist=prefix_list_lookup(AFI_IP6,dis
t->prefix[DISTRIBUTE_V6_IN]);if(plist)ri->prefix[RIPNG_FILTER_IN]=plist;elseri->
prefix[RIPNG_FILTER_IN]=NULL;}elseri->prefix[RIPNG_FILTER_IN]=NULL;if(dist->pref
ix[DISTRIBUTE_V6_OUT]){plist=prefix_list_lookup(AFI_IP6,dist->prefix[DISTRIBUTE_
V6_OUT]);if(plist)ri->prefix[RIPNG_FILTER_OUT]=plist;elseri->prefix[RIPNG_FILTER
_OUT]=NULL;}elseri->prefix[RIPNG_FILTER_OUT]=NULL;}voidripng_distribute_update_i
nterface(structinterface*ifp){structdistribute*dist;dist=distribute_lookup(ifp->
name);if(dist)ripng_distribute_update(dist);}/*Updateallinterface'sdistributelis
t.*/staticvoidripng_distribute_update_all(structprefix_list*notused){structvrf*v
rf=vrf_lookup_by_id(VRF_DEFAULT);structinterface*ifp;FOR_ALL_INTERFACES(vrf,ifp)
ripng_distribute_update_interface(ifp);}staticvoidripng_distribute_update_all_wr
apper(structaccess_list*notused){ripng_distribute_update_all(NULL);}/*deleteallt
headdedripngroutes.*/voidripng_clean(){inti;structroute_node*rp;structripng_info
*rinfo;structripng_aggregate*aggregate;structlist*list=NULL;structlistnode*listn
ode=NULL;if(ripng){/*ClearRIPngroutes*/for(rp=route_top(ripng->table);rp;rp=rout
e_next(rp)){if((list=rp->info)!=NULL){rinfo=listgetdata(listhead(list));if(ripng
_route_rte(rinfo))ripng_zebra_ipv6_delete(rp);for(ALL_LIST_ELEMENTS_RO(list,list
node,rinfo)){RIPNG_TIMER_OFF(rinfo->t_timeout);RIPNG_TIMER_OFF(rinfo->t_garbage_
collect);ripng_info_free(rinfo);}list_delete_and_null(&list);rp->info=NULL;route
_unlock_node(rp);}if((aggregate=rp->aggregate)!=NULL){ripng_aggregate_free(aggre
gate);rp->aggregate=NULL;route_unlock_node(rp);}}/*CanceltheRIPngtimers*/RIPNG_T
IMER_OFF(ripng->t_update);RIPNG_TIMER_OFF(ripng->t_triggered_update);RIPNG_TIMER
_OFF(ripng->t_triggered_interval);/*Cancelthereadthread*/if(ripng->t_read){threa
d_cancel(ripng->t_read);ripng->t_read=NULL;}/*ClosetheRIPngsocket*/if(ripng->soc
k>=0){close(ripng->sock);ripng->sock=-1;}/*StaticRIPngrouteconfiguration.*/for(r
p=route_top(ripng->route);rp;rp=route_next(rp))if(rp->info){rp->info=NULL;route_
unlock_node(rp);}/*RIPngaggregatedprefixes*/for(rp=route_top(ripng->aggregate);r
p;rp=route_next(rp))if(rp->info){rp->info=NULL;route_unlock_node(rp);}for(i=0;i<
ZEBRA_ROUTE_MAX;i++)if(ripng->route_map[i].name)free(ripng->route_map[i].name);X
FREE(MTYPE_ROUTE_TABLE,ripng->table);XFREE(MTYPE_ROUTE_TABLE,ripng->route);XFREE
(MTYPE_ROUTE_TABLE,ripng->aggregate);stream_free(ripng->ibuf);stream_free(ripng-
>obuf);XFREE(MTYPE_RIPNG,ripng);ripng=NULL;}/*if(ripng)*/ripng_clean_network();r
ipng_passive_interface_clean();ripng_offset_clean();ripng_interface_clean();ripn
g_redistribute_clean();}/*Resetallvaluestothedefaultsettings.*/voidripng_reset()
{/*Callripdrelatedresetfunctions.*/ripng_debug_reset();ripng_route_map_reset();/
*Calllibraryresetfunctions.*/vty_reset();access_list_reset();prefix_list_reset()
;distribute_list_reset();ripng_interface_reset();ripng_zclient_reset();}staticvo
idripng_if_rmap_update(structif_rmap*if_rmap){structinterface*ifp;structripng_in
terface*ri;structroute_map*rmap;ifp=if_lookup_by_name(if_rmap->ifname,VRF_DEFAUL
T);if(ifp==NULL)return;ri=ifp->info;if(if_rmap->routemap[IF_RMAP_IN]){rmap=route
_map_lookup_by_name(if_rmap->routemap[IF_RMAP_IN]);if(rmap)ri->routemap[IF_RMAP_
IN]=rmap;elseri->routemap[IF_RMAP_IN]=NULL;}elseri->routemap[RIPNG_FILTER_IN]=NU
LL;if(if_rmap->routemap[IF_RMAP_OUT]){rmap=route_map_lookup_by_name(if_rmap->rou
temap[IF_RMAP_OUT]);if(rmap)ri->routemap[IF_RMAP_OUT]=rmap;elseri->routemap[IF_R
MAP_OUT]=NULL;}elseri->routemap[RIPNG_FILTER_OUT]=NULL;}voidripng_if_rmap_update
_interface(structinterface*ifp){structif_rmap*if_rmap;if_rmap=if_rmap_lookup(ifp
->name);if(if_rmap)ripng_if_rmap_update(if_rmap);}staticvoidripng_routemap_updat
e_redistribute(void){inti;if(ripng){for(i=0;i<ZEBRA_ROUTE_MAX;i++){if(ripng->rou
te_map[i].name)ripng->route_map[i].map=route_map_lookup_by_name(ripng->route_map
[i].name);}}}staticvoidripng_routemap_update(constchar*unused){structvrf*vrf=vrf
_lookup_by_id(VRF_DEFAULT);structinterface*ifp;FOR_ALL_INTERFACES(vrf,ifp)ripng_
if_rmap_update_interface(ifp);ripng_routemap_update_redistribute();}/*Initialize
ripngstructureandsetcommands.*/voidripng_init(){/*InstallRIPNG_NODE.*/install_no
de(&cmd_ripng_node,ripng_config_write);/*Installripngcommands.*/install_element(
VIEW_NODE,&show_ipv6_ripng_cmd);install_element(VIEW_NODE,&show_ipv6_ripng_statu
s_cmd);install_element(ENABLE_NODE,&clear_ipv6_rip_cmd);install_element(CONFIG_N
ODE,&router_ripng_cmd);install_element(CONFIG_NODE,&no_router_ripng_cmd);install
_default(RIPNG_NODE);install_element(RIPNG_NODE,&ripng_route_cmd);install_elemen
t(RIPNG_NODE,&no_ripng_route_cmd);install_element(RIPNG_NODE,&ripng_aggregate_ad
dress_cmd);install_element(RIPNG_NODE,&no_ripng_aggregate_address_cmd);install_e
lement(RIPNG_NODE,&ripng_default_metric_cmd);install_element(RIPNG_NODE,&no_ripn
g_default_metric_cmd);install_element(RIPNG_NODE,&ripng_timers_cmd);install_elem
ent(RIPNG_NODE,&no_ripng_timers_cmd);#if0install_element(VIEW_NODE,&show_ipv6_pr
otocols_cmd);install_element(RIPNG_NODE,&ripng_update_timer_cmd);install_element
(RIPNG_NODE,&no_ripng_update_timer_cmd);install_element(RIPNG_NODE,&ripng_timeou
t_timer_cmd);install_element(RIPNG_NODE,&no_ripng_timeout_timer_cmd);install_ele
ment(RIPNG_NODE,&ripng_garbage_timer_cmd);install_element(RIPNG_NODE,&no_ripng_g
arbage_timer_cmd);#endif/*0*/install_element(RIPNG_NODE,&ripng_default_informati
on_originate_cmd);install_element(RIPNG_NODE,&no_ripng_default_information_origi
nate_cmd);install_element(RIPNG_NODE,&ripng_allow_ecmp_cmd);install_element(RIPN
G_NODE,&no_ripng_allow_ecmp_cmd);ripng_if_init();ripng_debug_init();/*Accesslist
install.*/access_list_init();access_list_add_hook(ripng_distribute_update_all_wr
apper);access_list_delete_hook(ripng_distribute_update_all_wrapper);/*Prefixlist
initialize.*/prefix_list_init();prefix_list_add_hook(ripng_distribute_update_all
);prefix_list_delete_hook(ripng_distribute_update_all);/*Distributelistinstall.*
/distribute_list_init(RIPNG_NODE);distribute_list_add_hook(ripng_distribute_upda
te);distribute_list_delete_hook(ripng_distribute_update);/*Route-mapforinterface
.*/ripng_route_map_init();ripng_offset_init();route_map_add_hook(ripng_routemap_
update);route_map_delete_hook(ripng_routemap_update);if_rmap_init(RIPNG_NODE);if
_rmap_hook_add(ripng_if_rmap_update);if_rmap_hook_delete(ripng_if_rmap_update);}
