/*RIPngdZebra*Copyright(C)20026WIND<vincent.jardin@6wind.com>**ThisfileispartofG
NUZebra.**GNUZebraisfreesoftware;youcanredistributeitand/ormodifyit*undertheterm
softheGNUGeneralPublicLicenseaspublishedbythe*FreeSoftwareFoundation;eitherversi
on2,or(atyouroption)any*laterversion.**GNUZebraisdistributedinthehopethatitwillb
euseful,but*WITHOUTANYWARRANTY;withouteventheimpliedwarrantyof*MERCHANTABILITYor
FITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPublicLicenseformoredetails.**Yous
houldhavereceivedacopyoftheGNUGeneralPublicLicensealong*withthisprogram;seethefi
leCOPYING;ifnot,writetotheFreeSoftware*Foundation,Inc.,51FranklinSt,FifthFloor,B
oston,MA02110-1301USA*//*ThisfileisrequiredinordertosupportproperlytheRIPngnexth
op*feature.*/#include<zebra.h>/*Forstructudphdr.*/#include<netinet/udp.h>#includ
e"linklist.h"#include"stream.h"#include"log.h"#include"memory.h"#include"vty.h"#
include"if.h"#include"prefix.h"#include"ripngd/ripngd.h"#include"ripngd/ripng_de
bug.h"#include"ripngd/ripng_nexthop.h"#defineDEBUG1#definemin(a,b)((a)<(b)?(a):(
b))structripng_rte_data{structprefix_ipv6*p;structripng_info*rinfo;structripng_a
ggregate*aggregate;};void_ripng_rte_del(structripng_rte_data*A);int_ripng_rte_cm
p(structripng_rte_data*A,structripng_rte_data*B);#defineMETRIC_OUT(a)\((a)->rinf
o?(a)->rinfo->metric_out:(a)->aggregate->metric_out)#defineNEXTHOP_OUT_PTR(a)\((
a)->rinfo?&((a)->rinfo->nexthop_out)\:&((a)->aggregate->nexthop_out))#defineTAG_
OUT(a)((a)->rinfo?(a)->rinfo->tag_out:(a)->aggregate->tag_out)structlist*ripng_r
te_new(void){structlist*rte;rte=list_new();rte->cmp=(int(*)(void*,void*))_ripng_
rte_cmp;rte->del=(void(*)(void*))_ripng_rte_del;returnrte;}voidripng_rte_free(st
ructlist*ripng_rte_list){list_delete_and_null(&ripng_rte_list);}/*DeleteRTE*/voi
d_ripng_rte_del(structripng_rte_data*A){XFREE(MTYPE_RIPNG_RTE_DATA,A);}/*Compare
RTE:*return+ifA>B*0ifA=B*-ifA<B*/int_ripng_rte_cmp(structripng_rte_data*A,struct
ripng_rte_data*B){returnaddr6_cmp(NEXTHOP_OUT_PTR(A),NEXTHOP_OUT_PTR(B));}/*Addr
outingtableentry*/voidripng_rte_add(structlist*ripng_rte_list,structprefix_ipv6*
p,structripng_info*rinfo,structripng_aggregate*aggregate){structripng_rte_data*d
ata;/*Atleastoneshouldnotbenull*/assert(!rinfo||!aggregate);data=XMALLOC(MTYPE_R
IPNG_RTE_DATA,sizeof(*data));data->p=p;data->rinfo=rinfo;data->aggregate=aggrega
te;listnode_add_sort(ripng_rte_list,data);}/*SendtheRTEwiththenexthopsupport*/vo
idripng_rte_send(structlist*ripng_rte_list,structinterface*ifp,structsockaddr_in
6*to){structripng_rte_data*data;structlistnode*node,*nnode;structin6_addrlast_ne
xthop;structin6_addrmyself_nexthop;structstream*s;intnum;intmtu;intrtemax;intret
;/*Mostofthetime,thereisnonexthop*/memset(&last_nexthop,0,sizeof(last_nexthop));
/*Usemyself_nexthopifthenexthopisnotalink-localaddress,*because*weremainarightpa
thwithoutbeeingtheoptimalone.*/memset(&myself_nexthop,0,sizeof(myself_nexthop));
/*Outputstreamgetfromripngstructre.XXXthisshouldbeinterfacestructure.*/s=ripng->
obuf;/*ResetstreamandRTEcounter.*/stream_reset(s);num=0;mtu=ifp->mtu6;if(mtu<0)m
tu=IFMINMTU;rtemax=(min(mtu,RIPNG_MAX_PACKET_SIZE)-IPV6_HDRLEN-sizeof(structudph
dr)-sizeof(structripng_packet)+sizeof(structrte))/sizeof(structrte);for(ALL_LIST
_ELEMENTS(ripng_rte_list,node,nnode,data)){/*(2.1)Nexthopsupport*/if(!IPV6_ADDR_
SAME(&last_nexthop,NEXTHOP_OUT_PTR(data))){/*Anexthopentryshouldbeatleastfollowe
dby1RTE*/if(num==(rtemax-1)){ret=ripng_send_packet((caddr_t)STREAM_DATA(s),strea
m_get_endp(s),to,ifp);if(ret>=0&&IS_RIPNG_DEBUG_SEND)ripng_packet_dump((structri
png_packet*)STREAM_DATA(s),stream_get_endp(s),"SEND");num=0;stream_reset(s);}/*A
ddthenexthop(2.1)*//*Ifthereceivednexthopaddressisnotalink-local*address,*itshou
ldbetreatedas0:0:0:0:0:0:0:0.*/if(!IN6_IS_ADDR_LINKLOCAL(NEXTHOP_OUT_PTR(data)))
last_nexthop=myself_nexthop;elselast_nexthop=*NEXTHOP_OUT_PTR(data);num=ripng_wr
ite_rte(num,s,NULL,&last_nexthop,0,RIPNG_METRIC_NEXTHOP);}else{/*Rewritethenexth
opforeachnewpacket*/if((num==0)&&!IPV6_ADDR_SAME(&last_nexthop,&myself_nexthop))
num=ripng_write_rte(num,s,NULL,&last_nexthop,0,RIPNG_METRIC_NEXTHOP);}num=ripng_
write_rte(num,s,data->p,NULL,TAG_OUT(data),METRIC_OUT(data));if(num==rtemax){ret
=ripng_send_packet((caddr_t)STREAM_DATA(s),stream_get_endp(s),to,ifp);if(ret>=0&
&IS_RIPNG_DEBUG_SEND)ripng_packet_dump((structripng_packet*)STREAM_DATA(s),strea
m_get_endp(s),"SEND");num=0;stream_reset(s);}}/*IfunwrittenRTEexist,flushit.*/if
(num!=0){ret=ripng_send_packet((caddr_t)STREAM_DATA(s),stream_get_endp(s),to,ifp
);if(ret>=0&&IS_RIPNG_DEBUG_SEND)ripng_packet_dump((structripng_packet*)STREAM_D
ATA(s),stream_get_endp(s),"SEND");stream_reset(s);}}