/*$OpenBSD$*//**Copyright(c)2014,2015RenatoWestphal<renato@openbsd.org>*Copyrigh
t(c)2009MicheleMarchetto<michele@openbsd.org>**Permissiontouse,copy,modify,anddi
stributethissoftwareforany*purposewithorwithoutfeeisherebygranted,providedthatth
eabove*copyrightnoticeandthispermissionnoticeappearinallcopies.**THESOFTWAREISPR
OVIDED"ASIS"ANDTHEAUTHORDISCLAIMSALLWARRANTIES*WITHREGARDTOTHISSOFTWAREINCLUDING
ALLIMPLIEDWARRANTIESOF*MERCHANTABILITYANDFITNESS.INNOEVENTSHALLTHEAUTHORBELIABLE
FOR*ANYSPECIAL,DIRECT,INDIRECT,ORCONSEQUENTIALDAMAGESORANYDAMAGES*WHATSOEVERRESU
LTINGFROMLOSSOFUSE,DATAORPROFITS,WHETHERINAN*ACTIONOFCONTRACT,NEGLIGENCEOROTHERT
ORTIOUSACTION,ARISINGOUTOF*ORINCONNECTIONWITHTHEUSEORPERFORMANCEOFTHISSOFTWARE.*
/#include<zebra.h>#include"ldpd.h"#include"ldpe.h"#include"log.h"#include"ldp_de
bug.h"#include"mpls.h"staticvoidenqueue_pdu(structnbr*,uint16_t,structibuf*,uint
16_t);staticintgen_label_tlv(structibuf*,uint32_t);staticintgen_reqid_tlv(struct
ibuf*,uint32_t);staticvoidlog_msg_mapping(int,uint16_t,structnbr*,structmap*);st
aticvoidenqueue_pdu(structnbr*nbr,uint16_ttype,structibuf*buf,uint16_tsize){stru
ctldp_hdr*ldp_hdr;ldp_hdr=ibuf_seek(buf,0,sizeof(structldp_hdr));ldp_hdr->length
=htons(size);evbuf_enqueue(&nbr->tcp->wbuf,buf);}/*Genericfunctionthathandlesall
LabelMessagetypes*/voidsend_labelmessage(structnbr*nbr,uint16_ttype,structmappin
g_head*mh){structibuf*buf=NULL;structmapping_entry*me;uint16_tmsg_size,size=0;in
tfirst=1;interr=0;/*nothingtosend*/if(TAILQ_EMPTY(mh))return;while((me=TAILQ_FIR
ST(mh))!=NULL){/*generatepdu*/if(first){if((buf=ibuf_open(nbr->max_pdu_len+LDP_H
DR_DEAD_LEN))==NULL)fatal(__func__);/*realsizewillbesetuplater*/err|=gen_ldp_hdr
(buf,0);size=LDP_HDR_PDU_LEN;first=0;}/*calculatesize*/msg_size=LDP_MSG_SIZE;msg
_size+=len_fec_tlv(&me->map);if(me->map.label!=NO_LABEL)msg_size+=LABEL_TLV_SIZE
;if(me->map.flags&F_MAP_REQ_ID)msg_size+=REQID_TLV_SIZE;if(me->map.flags&F_MAP_S
TATUS)msg_size+=STATUS_SIZE;/*maximumpdulengthexceeded,weneedanewldppdu*/if(size
+msg_size>nbr->max_pdu_len){enqueue_pdu(nbr,type,buf,size);first=1;continue;}siz
e+=msg_size;/*appendmessageandtlvs*/err|=gen_msg_hdr(buf,type,msg_size);err|=gen
_fec_tlv(buf,&me->map);if(me->map.label!=NO_LABEL)err|=gen_label_tlv(buf,me->map
.label);if(me->map.flags&F_MAP_REQ_ID)err|=gen_reqid_tlv(buf,me->map.requestid);
if(me->map.flags&F_MAP_PW_STATUS)err|=gen_pw_status_tlv(buf,me->map.pw_status);i
f(me->map.flags&F_MAP_STATUS)err|=gen_status_tlv(buf,me->map.st.status_code,me->
map.st.msg_id,me->map.st.msg_type);if(err){ibuf_free(buf);mapping_list_clr(mh);r
eturn;}log_msg_mapping(1,type,nbr,&me->map);/*noerrors-updateperneighbormessagec
ounters*/switch(type){caseMSG_TYPE_LABELMAPPING:nbr->stats.labelmap_sent++;break
;caseMSG_TYPE_LABELREQUEST:nbr->stats.labelreq_sent++;break;caseMSG_TYPE_LABELWI
THDRAW:nbr->stats.labelwdraw_sent++;break;caseMSG_TYPE_LABELRELEASE:nbr->stats.l
abelrel_sent++;break;caseMSG_TYPE_LABELABORTREQ:nbr->stats.labelabreq_sent++;bre
ak;default:break;}TAILQ_REMOVE(mh,me,entry);assert(me!=TAILQ_FIRST(mh));free(me)
;}enqueue_pdu(nbr,type,buf,size);nbr_fsm(nbr,NBR_EVT_PDU_SENT);}/*Genericfunctio
nthathandlesallLabelMessagetypes*/intrecv_labelmessage(structnbr*nbr,char*buf,ui
nt16_tlen,uint16_ttype){structldp_msgmsg;structtlvft;uint32_tlabel=NO_LABEL,reqi
d=0;uint32_tpw_status=0;uint8_tflags=0;intfeclen,tlen;uint16_tcurrent_tlv=1;stru
ctmapping_entry*me;structmapping_headmh;structmapmap;memcpy(&msg,buf,sizeof(msg)
);buf+=LDP_MSG_SIZE;len-=LDP_MSG_SIZE;/*FECTLV*/if(len<sizeof(ft)){session_shutd
own(nbr,S_BAD_TLV_LEN,msg.id,msg.type);return(-1);}memcpy(&ft,buf,sizeof(ft));if
(ntohs(ft.type)!=TLV_TYPE_FEC){send_notification(nbr->tcp,S_MISS_MSG,msg.id,msg.
type);return(-1);}feclen=ntohs(ft.length);if(feclen>len-TLV_HDR_SIZE){session_sh
utdown(nbr,S_BAD_TLV_LEN,msg.id,msg.type);return(-1);}buf+=TLV_HDR_SIZE;/*justad
vancetotheendofthefecheader*/len-=TLV_HDR_SIZE;TAILQ_INIT(&mh);do{memset(&map,0,
sizeof(map));map.msg_id=msg.id;if((tlen=tlv_decode_fec_elm(nbr,&msg,buf,feclen,&
map))==-1)gotoerr;if(map.type==MAP_TYPE_PWID&&!(map.flags&F_MAP_PW_ID)&&type!=MS
G_TYPE_LABELWITHDRAW&&type!=MSG_TYPE_LABELRELEASE){send_notification(nbr->tcp,S_
MISS_MSG,msg.id,msg.type);gotoerr;}/**TheWildcardFECElementcanbeusedonlyinthe*La
belWithdrawandLabelReleasemessages.*/if(map.type==MAP_TYPE_WILDCARD){switch(type
){caseMSG_TYPE_LABELMAPPING:caseMSG_TYPE_LABELREQUEST:caseMSG_TYPE_LABELABORTREQ
:session_shutdown(nbr,S_UNKNOWN_FEC,msg.id,msg.type);gotoerr;default:break;}}/**
RFC5561-Section4:*"AnLDPimplementationthatsupportstheTypedWildcard*FECElementMUS
TsupportitsuseinLabelRequest,Label*Withdraw,andLabelReleasemessages".*/if(map.ty
pe==MAP_TYPE_TYPED_WCARD){switch(type){caseMSG_TYPE_LABELMAPPING:caseMSG_TYPE_LA
BELABORTREQ:session_shutdown(nbr,S_UNKNOWN_FEC,msg.id,msg.type);gotoerr;default:
break;}}/**LDPsupportstheuseofmultipleFECElementsper*FECfortheLabelMappingmessag
eonly.*/if(type!=MSG_TYPE_LABELMAPPING&&tlen!=feclen){session_shutdown(nbr,S_BAD
_TLV_VAL,msg.id,msg.type);gotoerr;}mapping_list_add(&mh,&map);buf+=tlen;len-=tle
n;feclen-=tlen;}while(feclen>0);/*OptionalParameters*/while(len>0){structtlvtlv;
uint16_ttlv_type;uint16_ttlv_len;uint32_treqbuf,labelbuf,statusbuf;if(len<sizeof
(tlv)){session_shutdown(nbr,S_BAD_TLV_LEN,msg.id,msg.type);gotoerr;}memcpy(&tlv,
buf,TLV_HDR_SIZE);tlv_type=ntohs(tlv.type);tlv_len=ntohs(tlv.length);if(tlv_len+
TLV_HDR_SIZE>len){session_shutdown(nbr,S_BAD_TLV_LEN,msg.id,msg.type);gotoerr;}b
uf+=TLV_HDR_SIZE;len-=TLV_HDR_SIZE;/**ForLabelMappingmessagestheLabelTLVismandat
oryand*shouldappearrightaftertheFECTLV.*/if(current_tlv==1&&type==MSG_TYPE_LABEL
MAPPING&&!(tlv_type&TLV_TYPE_GENERICLABEL)){send_notification(nbr->tcp,S_MISS_MS
G,msg.id,msg.type);gotoerr;}switch(tlv_type){caseTLV_TYPE_LABELREQUEST:switch(ty
pe){caseMSG_TYPE_LABELMAPPING:caseMSG_TYPE_LABELREQUEST:if(tlv_len!=REQID_TLV_LE
N){session_shutdown(nbr,S_BAD_TLV_LEN,msg.id,msg.type);gotoerr;}flags|=F_MAP_REQ
_ID;memcpy(&reqbuf,buf,sizeof(reqbuf));reqid=ntohl(reqbuf);break;default:/*ignor
e*/break;}break;caseTLV_TYPE_HOPCOUNT:caseTLV_TYPE_PATHVECTOR:/*ignore*/break;ca
seTLV_TYPE_GENERICLABEL:switch(type){caseMSG_TYPE_LABELMAPPING:caseMSG_TYPE_LABE
LWITHDRAW:caseMSG_TYPE_LABELRELEASE:if(tlv_len!=LABEL_TLV_LEN){session_shutdown(
nbr,S_BAD_TLV_LEN,msg.id,msg.type);gotoerr;}memcpy(&labelbuf,buf,sizeof(labelbuf
));label=ntohl(labelbuf);/*donotacceptinvalidlabels*/if(label>MPLS_LABEL_MAX||(l
abel<=MPLS_LABEL_RESERVED_MAX&&label!=MPLS_LABEL_IPV4_EXPLICIT_NULL&&label!=MPLS
_LABEL_IPV6_EXPLICIT_NULL&&label!=MPLS_LABEL_IMPLICIT_NULL)){session_shutdown(nb
r,S_BAD_TLV_VAL,msg.id,msg.type);gotoerr;}break;default:/*ignore*/break;}break;c
aseTLV_TYPE_ATMLABEL:caseTLV_TYPE_FRLABEL:switch(type){caseMSG_TYPE_LABELMAPPING
:caseMSG_TYPE_LABELWITHDRAW:caseMSG_TYPE_LABELRELEASE:/*unsupported*/session_shu
tdown(nbr,S_BAD_TLV_VAL,msg.id,msg.type);gotoerr;break;default:/*ignore*/break;}
break;caseTLV_TYPE_STATUS:if(tlv_len!=STATUS_TLV_LEN){session_shutdown(nbr,S_BAD
_TLV_LEN,msg.id,msg.type);gotoerr;}/*ignore*/break;caseTLV_TYPE_PW_STATUS:switch
(type){caseMSG_TYPE_LABELMAPPING:if(tlv_len!=PW_STATUS_TLV_LEN){session_shutdown
(nbr,S_BAD_TLV_LEN,msg.id,msg.type);gotoerr;}flags|=F_MAP_PW_STATUS;memcpy(&stat
usbuf,buf,sizeof(statusbuf));pw_status=ntohl(statusbuf);break;default:/*ignore*/
break;}break;default:if(!(ntohs(tlv.type)&UNKNOWN_FLAG))send_notification_rtlvs(
nbr,S_UNKNOWN_TLV,msg.id,msg.type,tlv_type,tlv_len,buf);/*ignoreunknowntlv*/brea
k;}buf+=tlv_len;len-=tlv_len;current_tlv++;}/*notifyldeaboutthereceivedmessage.*
/while((me=TAILQ_FIRST(&mh))!=NULL){intimsg_type=IMSG_NONE;me->map.flags|=flags;
switch(me->map.type){caseMAP_TYPE_PREFIX:switch(me->map.fec.prefix.af){caseAF_IN
ET:if(label==MPLS_LABEL_IPV6_EXPLICIT_NULL){session_shutdown(nbr,S_BAD_TLV_VAL,m
sg.id,msg.type);gotoerr;}if(!nbr->v4_enabled)gotonext;break;caseAF_INET6:if(labe
l==MPLS_LABEL_IPV4_EXPLICIT_NULL){session_shutdown(nbr,S_BAD_TLV_VAL,msg.id,msg.
type);gotoerr;}if(!nbr->v6_enabled)gotonext;break;default:fatalx("recv_labelmess
age:unknownaf");}break;caseMAP_TYPE_PWID:if(label<=MPLS_LABEL_RESERVED_MAX){sess
ion_shutdown(nbr,S_BAD_TLV_VAL,msg.id,msg.type);gotoerr;}if(me->map.flags&F_MAP_
PW_STATUS)me->map.pw_status=pw_status;break;default:break;}me->map.label=label;i
f(me->map.flags&F_MAP_REQ_ID)me->map.requestid=reqid;log_msg_mapping(0,type,nbr,
&me->map);switch(type){caseMSG_TYPE_LABELMAPPING:imsg_type=IMSG_LABEL_MAPPING;br
eak;caseMSG_TYPE_LABELREQUEST:imsg_type=IMSG_LABEL_REQUEST;break;caseMSG_TYPE_LA
BELWITHDRAW:imsg_type=IMSG_LABEL_WITHDRAW;break;caseMSG_TYPE_LABELRELEASE:imsg_t
ype=IMSG_LABEL_RELEASE;break;caseMSG_TYPE_LABELABORTREQ:imsg_type=IMSG_LABEL_ABO
RT;break;default:break;}ldpe_imsg_compose_lde(imsg_type,nbr->peerid,0,&me->map,s
izeof(structmap));next:TAILQ_REMOVE(&mh,me,entry);assert(me!=TAILQ_FIRST(&mh));f
ree(me);}return(0);err:mapping_list_clr(&mh);return(-1);}/*OtherTLVrelatedfuncti
ons*/staticintgen_label_tlv(structibuf*buf,uint32_tlabel){structlabel_tlvlt;lt.t
ype=htons(TLV_TYPE_GENERICLABEL);lt.length=htons(LABEL_TLV_LEN);lt.label=htonl(l
abel);return(ibuf_add(buf,&lt,sizeof(lt)));}staticintgen_reqid_tlv(structibuf*bu
f,uint32_treqid){structreqid_tlvrt;rt.type=htons(TLV_TYPE_LABELREQUEST);rt.lengt
h=htons(REQID_TLV_LEN);rt.reqid=htonl(reqid);return(ibuf_add(buf,&rt,sizeof(rt))
);}intgen_pw_status_tlv(structibuf*buf,uint32_tstatus){structpw_status_tlvst;st.
type=htons(TLV_TYPE_PW_STATUS);st.length=htons(PW_STATUS_TLV_LEN);st.value=htonl
(status);return(ibuf_add(buf,&st,sizeof(st)));}uint16_tlen_fec_tlv(structmap*map
){uint16_tlen=TLV_HDR_SIZE;switch(map->type){caseMAP_TYPE_WILDCARD:len+=FEC_ELM_
WCARD_LEN;break;caseMAP_TYPE_PREFIX:len+=FEC_ELM_PREFIX_MIN_LEN+PREFIX_SIZE(map-
>fec.prefix.prefixlen);break;caseMAP_TYPE_PWID:len+=FEC_PWID_ELM_MIN_LEN;if(map-
>flags&F_MAP_PW_ID)len+=PW_STATUS_TLV_LEN;if(map->flags&F_MAP_PW_IFMTU)len+=FEC_
SUBTLV_IFMTU_SIZE;if(map->flags&F_MAP_PW_STATUS)len+=PW_STATUS_TLV_SIZE;break;ca
seMAP_TYPE_TYPED_WCARD:len+=FEC_ELM_TWCARD_MIN_LEN;switch(map->fec.twcard.type){
caseMAP_TYPE_PREFIX:caseMAP_TYPE_PWID:len+=sizeof(uint16_t);break;default:fatalx
("len_fec_tlv:unexpectedfectype");}break;default:fatalx("len_fec_tlv:unexpectedf
ectype");}return(len);}intgen_fec_tlv(structibuf*buf,structmap*map){structtlvft;
uint16_tfamily,len,pw_type,ifmtu;uint8_tpw_len=0,twcard_len;uint32_tgroup_id,pwi
d;interr=0;ft.type=htons(TLV_TYPE_FEC);switch(map->type){caseMAP_TYPE_WILDCARD:f
t.length=htons(sizeof(uint8_t));err|=ibuf_add(buf,&ft,sizeof(ft));err|=ibuf_add(
buf,&map->type,sizeof(map->type));break;caseMAP_TYPE_PREFIX:len=PREFIX_SIZE(map-
>fec.prefix.prefixlen);ft.length=htons(sizeof(map->type)+sizeof(family)+sizeof(m
ap->fec.prefix.prefixlen)+len);err|=ibuf_add(buf,&ft,sizeof(ft));err|=ibuf_add(b
uf,&map->type,sizeof(map->type));switch(map->fec.prefix.af){caseAF_INET:family=h
tons(AF_IPV4);break;caseAF_INET6:family=htons(AF_IPV6);break;default:fatalx("gen
_fec_tlv:unknownaf");break;}err|=ibuf_add(buf,&family,sizeof(family));err|=ibuf_
add(buf,&map->fec.prefix.prefixlen,sizeof(map->fec.prefix.prefixlen));if(len)err
|=ibuf_add(buf,&map->fec.prefix.prefix,len);break;caseMAP_TYPE_PWID:if(map->flag
s&F_MAP_PW_ID)pw_len+=FEC_PWID_SIZE;if(map->flags&F_MAP_PW_IFMTU)pw_len+=FEC_SUB
TLV_IFMTU_SIZE;len=FEC_PWID_ELM_MIN_LEN+pw_len;ft.length=htons(len);err|=ibuf_ad
d(buf,&ft,sizeof(ft));err|=ibuf_add(buf,&map->type,sizeof(uint8_t));pw_type=map-
>fec.pwid.type;if(map->flags&F_MAP_PW_CWORD)pw_type|=CONTROL_WORD_FLAG;pw_type=h
tons(pw_type);err|=ibuf_add(buf,&pw_type,sizeof(uint16_t));err|=ibuf_add(buf,&pw
_len,sizeof(uint8_t));group_id=htonl(map->fec.pwid.group_id);err|=ibuf_add(buf,&
group_id,sizeof(uint32_t));if(map->flags&F_MAP_PW_ID){pwid=htonl(map->fec.pwid.p
wid);err|=ibuf_add(buf,&pwid,sizeof(uint32_t));}if(map->flags&F_MAP_PW_IFMTU){st
ructsubtlvstlv;stlv.type=SUBTLV_IFMTU;stlv.length=FEC_SUBTLV_IFMTU_SIZE;err|=ibu
f_add(buf,&stlv,sizeof(uint16_t));ifmtu=htons(map->fec.pwid.ifmtu);err|=ibuf_add
(buf,&ifmtu,sizeof(uint16_t));}break;caseMAP_TYPE_TYPED_WCARD:len=FEC_ELM_TWCARD
_MIN_LEN;switch(map->fec.twcard.type){caseMAP_TYPE_PREFIX:caseMAP_TYPE_PWID:len+
=sizeof(uint16_t);break;default:fatalx("gen_fec_tlv:unexpectedfectype");}ft.leng
th=htons(len);err|=ibuf_add(buf,&ft,sizeof(ft));err|=ibuf_add(buf,&map->type,siz
eof(uint8_t));err|=ibuf_add(buf,&map->fec.twcard.type,sizeof(uint8_t));switch(ma
p->fec.twcard.type){caseMAP_TYPE_PREFIX:twcard_len=sizeof(uint16_t);err|=ibuf_ad
d(buf,&twcard_len,sizeof(uint8_t));switch(map->fec.twcard.u.prefix_af){caseAF_IN
ET:family=htons(AF_IPV4);break;caseAF_INET6:family=htons(AF_IPV6);break;default:
fatalx("gen_fec_tlv:unknownaf");break;}err|=ibuf_add(buf,&family,sizeof(uint16_t
));break;caseMAP_TYPE_PWID:twcard_len=sizeof(uint16_t);err|=ibuf_add(buf,&twcard
_len,sizeof(uint8_t));pw_type=htons(map->fec.twcard.u.pw_type);err|=ibuf_add(buf
,&pw_type,sizeof(uint16_t));break;default:fatalx("gen_fec_tlv:unexpectedfectype"
);}break;default:break;}return(err);}inttlv_decode_fec_elm(structnbr*nbr,structl
dp_msg*msg,char*buf,uint16_tlen,structmap*map){uint16_toff=0;uint8_tpw_len,twcar
d_len;map->type=*buf;off+=sizeof(uint8_t);switch(map->type){caseMAP_TYPE_WILDCAR
D:if(len==FEC_ELM_WCARD_LEN)return(off);else{session_shutdown(nbr,S_BAD_TLV_VAL,
msg->id,msg->type);return(-1);}break;caseMAP_TYPE_PREFIX:if(len<FEC_ELM_PREFIX_M
IN_LEN){session_shutdown(nbr,S_BAD_TLV_LEN,msg->id,msg->type);return(-1);}/*Addr
essFamily*/memcpy(&map->fec.prefix.af,buf+off,sizeof(map->fec.prefix.af));off+=s
izeof(map->fec.prefix.af);map->fec.prefix.af=ntohs(map->fec.prefix.af);switch(ma
p->fec.prefix.af){caseAF_IPV4:map->fec.prefix.af=AF_INET;break;caseAF_IPV6:map->
fec.prefix.af=AF_INET6;break;default:send_notification(nbr->tcp,S_UNSUP_ADDR,msg
->id,msg->type);return(-1);}/*PrefixLength*/map->fec.prefix.prefixlen=buf[off];o
ff+=sizeof(uint8_t);if(len<off+PREFIX_SIZE(map->fec.prefix.prefixlen)){session_s
hutdown(nbr,S_BAD_TLV_LEN,msg->id,msg->type);return(-1);}/*Prefix*/memset(&map->
fec.prefix.prefix,0,sizeof(map->fec.prefix.prefix));memcpy(&map->fec.prefix.pref
ix,buf+off,PREFIX_SIZE(map->fec.prefix.prefixlen));/*Justincase...*/ldp_applymas
k(map->fec.prefix.af,&map->fec.prefix.prefix,&map->fec.prefix.prefix,map->fec.pr
efix.prefixlen);return(off+PREFIX_SIZE(map->fec.prefix.prefixlen));caseMAP_TYPE_
PWID:if(len<FEC_PWID_ELM_MIN_LEN){session_shutdown(nbr,S_BAD_TLV_LEN,msg->id,msg
->type);return(-1);}/*PWtype*/memcpy(&map->fec.pwid.type,buf+off,sizeof(uint16_t
));map->fec.pwid.type=ntohs(map->fec.pwid.type);if(map->fec.pwid.type&CONTROL_WO
RD_FLAG){map->flags|=F_MAP_PW_CWORD;map->fec.pwid.type&=~CONTROL_WORD_FLAG;}off+
=sizeof(uint16_t);/*PWinfoLength*/pw_len=buf[off];off+=sizeof(uint8_t);if(len!=F
EC_PWID_ELM_MIN_LEN+pw_len){session_shutdown(nbr,S_BAD_TLV_LEN,msg->id,msg->type
);return(-1);}/*GroupID*/memcpy(&map->fec.pwid.group_id,buf+off,sizeof(uint32_t)
);map->fec.pwid.group_id=ntohl(map->fec.pwid.group_id);off+=sizeof(uint32_t);/*P
WID*/if(pw_len==0)return(off);if(pw_len<sizeof(uint32_t)){session_shutdown(nbr,S
_BAD_TLV_LEN,msg->id,msg->type);return(-1);}memcpy(&map->fec.pwid.pwid,buf+off,s
izeof(uint32_t));map->fec.pwid.pwid=ntohl(map->fec.pwid.pwid);map->flags|=F_MAP_
PW_ID;off+=sizeof(uint32_t);pw_len-=sizeof(uint32_t);/*OptionalInterfaceParamete
rSub-TLVs*/while(pw_len>0){structsubtlvstlv;if(pw_len<sizeof(stlv)){session_shut
down(nbr,S_BAD_TLV_LEN,msg->id,msg->type);return(-1);}memcpy(&stlv,buf+off,sizeo
f(stlv));if(stlv.length>pw_len){session_shutdown(nbr,S_BAD_TLV_LEN,msg->id,msg->
type);return(-1);}switch(stlv.type){caseSUBTLV_IFMTU:if(stlv.length!=FEC_SUBTLV_
IFMTU_SIZE){session_shutdown(nbr,S_BAD_TLV_LEN,msg->id,msg->type);return(-1);}me
mcpy(&map->fec.pwid.ifmtu,buf+off+SUBTLV_HDR_SIZE,sizeof(uint16_t));map->fec.pwi
d.ifmtu=ntohs(map->fec.pwid.ifmtu);map->flags|=F_MAP_PW_IFMTU;break;default:/*ig
nore*/break;}off+=stlv.length;pw_len-=stlv.length;}return(off);caseMAP_TYPE_TYPE
D_WCARD:if(len<FEC_ELM_TWCARD_MIN_LEN){session_shutdown(nbr,S_BAD_TLV_LEN,msg->i
d,msg->type);return(-1);}memcpy(&map->fec.twcard.type,buf+off,sizeof(uint8_t));o
ff+=sizeof(uint8_t);memcpy(&twcard_len,buf+off,sizeof(uint8_t));off+=sizeof(uint
8_t);if(len!=FEC_ELM_TWCARD_MIN_LEN+twcard_len){session_shutdown(nbr,S_BAD_TLV_L
EN,msg->id,msg->type);return(-1);}switch(map->fec.twcard.type){caseMAP_TYPE_PREF
IX:if(twcard_len!=sizeof(uint16_t)){session_shutdown(nbr,S_BAD_TLV_LEN,msg->id,m
sg->type);return(-1);}memcpy(&map->fec.twcard.u.prefix_af,buf+off,sizeof(uint16_
t));map->fec.twcard.u.prefix_af=ntohs(map->fec.twcard.u.prefix_af);off+=sizeof(u
int16_t);switch(map->fec.twcard.u.prefix_af){caseAF_IPV4:map->fec.twcard.u.prefi
x_af=AF_INET;break;caseAF_IPV6:map->fec.twcard.u.prefix_af=AF_INET6;break;defaul
t:session_shutdown(nbr,S_BAD_TLV_VAL,msg->id,msg->type);return(-1);}break;caseMA
P_TYPE_PWID:if(twcard_len!=sizeof(uint16_t)){session_shutdown(nbr,S_BAD_TLV_LEN,
msg->id,msg->type);return(-1);}memcpy(&map->fec.twcard.u.pw_type,buf+off,sizeof(
uint16_t));map->fec.twcard.u.pw_type=ntohs(map->fec.twcard.u.pw_type);/*ignoreth
ereservedbitasperRFC6667*/map->fec.twcard.u.pw_type&=~PW_TWCARD_RESERVED_BIT;off
+=sizeof(uint16_t);break;default:send_notification(nbr->tcp,S_UNKNOWN_FEC,msg->i
d,msg->type);return(-1);}return(off);default:send_notification(nbr->tcp,S_UNKNOW
N_FEC,msg->id,msg->type);break;}return(-1);}staticvoidlog_msg_mapping(intout,uin
t16_tmsg_type,structnbr*nbr,structmap*map){debug_msg(out,"%s:lsr-id%s,fec%s,labe
l%s",msg_name(msg_type),inet_ntoa(nbr->id),log_map(map),log_label(map->label));}
