/*$OpenBSD$*//**Copyright(c)2013,2016RenatoWestphal<renato@openbsd.org>*Copyrigh
t(c)2004,2005ClaudioJeker<claudio@openbsd.org>*Copyright(c)2004EsbenNorby<norby@
openbsd.org>*Copyright(c)2003,2004HenningBrauer<henning@openbsd.org>**Permission
touse,copy,modify,anddistributethissoftwareforany*purposewithorwithoutfeeishereb
ygranted,providedthattheabove*copyrightnoticeandthispermissionnoticeappearinallc
opies.**THESOFTWAREISPROVIDED"ASIS"ANDTHEAUTHORDISCLAIMSALLWARRANTIES*WITHREGARD
TOTHISSOFTWAREINCLUDINGALLIMPLIEDWARRANTIESOF*MERCHANTABILITYANDFITNESS.INNOEVEN
TSHALLTHEAUTHORBELIABLEFOR*ANYSPECIAL,DIRECT,INDIRECT,ORCONSEQUENTIALDAMAGESORAN
YDAMAGES*WHATSOEVERRESULTINGFROMLOSSOFUSE,DATAORPROFITS,WHETHERINAN*ACTIONOFCONT
RACT,NEGLIGENCEOROTHERTORTIOUSACTION,ARISINGOUTOF*ORINCONNECTIONWITHTHEUSEORPERF
ORMANCEOFTHISSOFTWARE.*/#include<zebra.h>#include"ldp.h"#include"ldpd.h"#include
"ldpe.h"#include"log.h"#include"lde.h"#include"ldp_debug.h"#include<lib/log.h>#i
nclude"memory.h"#include"privs.h"#include"sigevent.h"#include"mpls.h"#include<li
b/linklist.h>#include"zclient.h"#include"stream.h"#include"network.h"#include"li
bfrr.h"staticvoidlde_shutdown(void);staticintlde_dispatch_imsg(structthread*);st
aticintlde_dispatch_parent(structthread*);static__inlineintlde_nbr_compare(const
structlde_nbr*,conststructlde_nbr*);staticstructlde_nbr*lde_nbr_new(uint32_t,str
uctlde_nbr*);staticvoidlde_nbr_del(structlde_nbr*);staticstructlde_nbr*lde_nbr_f
ind(uint32_t);staticvoidlde_nbr_clear(void);staticvoidlde_nbr_addr_update(struct
lde_nbr*,structlde_addr*,int);static__inlineintlde_map_compare(conststructlde_ma
p*,conststructlde_map*);staticvoidlde_map_free(void*);staticintlde_address_add(s
tructlde_nbr*,structlde_addr*);staticintlde_address_del(structlde_nbr*,structlde
_addr*);staticvoidlde_address_list_free(structlde_nbr*);staticvoidzclient_sync_i
nit(unsignedshortinstance);staticvoidlde_label_list_init(void);staticintlde_get_
label_chunk(void);staticvoidon_get_label_chunk_response(uint32_tstart,uint32_ten
d);staticuint32_tlde_get_next_label(void);RB_GENERATE(nbr_tree,lde_nbr,entry,lde
_nbr_compare)RB_GENERATE(lde_map_head,lde_map,entry,lde_map_compare)structldpd_c
onf*ldeconf;structnbr_treelde_nbrs=RB_INITIALIZER(&lde_nbrs);staticstructimsgev*
iev_ldpe;staticstructimsgev*iev_main,*iev_main_sync;/*Masterofthreads.*/structth
read_master*master;/*ldeprivileges*/staticzebra_capabilities_t_caps_p[]={ZCAP_NE
T_ADMIN};staticstructzebra_privs_tlde_privs={#ifdefined(VTY_GROUP).vty_group=VTY
_GROUP,#endif.caps_p=_caps_p,.cap_num_p=array_size(_caps_p),.cap_num_i=0};/*List
ofchunksoflabelsexternallyassignedbyZebra*/staticstructlist*label_chunk_list;sta
ticstructlistnode*current_label_chunk;/*Synchronouszclienttorequestlabels*/stati
cstructzclient*zclient_sync;/*SIGINT/SIGTERMhandler.*/staticvoidsigint(void){lde
_shutdown();}staticstructquagga_signal_tlde_signals[]={{.signal=SIGHUP,/*ignore*
/},{.signal=SIGINT,.handler=&sigint,},{.signal=SIGTERM,.handler=&sigint,},};/*la
beldecisionengine*/voidlde(void){structthreadthread;#ifdefHAVE_SETPROCTITLEsetpr
octitle("labeldecisionengine");#endifldpd_process=PROC_LDE_ENGINE;log_procname=l
og_procnames[PROC_LDE_ENGINE];master=thread_master_create(NULL);/*setupsignalhan
dler*/signal_init(master,array_size(lde_signals),lde_signals);/*setuppipesandeve
nthandlerstotheparentprocess*/if((iev_main=calloc(1,sizeof(structimsgev)))==NULL
)fatal(NULL);imsg_init(&iev_main->ibuf,LDPD_FD_ASYNC);iev_main->handler_read=lde
_dispatch_parent;iev_main->ev_read=NULL;thread_add_read(master,iev_main->handler
_read,iev_main,iev_main->ibuf.fd,&iev_main->ev_read);iev_main->handler_write=ldp
_write_handler;if((iev_main_sync=calloc(1,sizeof(structimsgev)))==NULL)fatal(NUL
L);imsg_init(&iev_main_sync->ibuf,LDPD_FD_SYNC);/*createbaseconfiguration*/ldeco
nf=config_new_empty();/*Fetchnextactivethread.*/while(thread_fetch(master,&threa
d))thread_call(&thread);}voidlde_init(structldpd_init*init){/*dropprivileges*/ld
e_privs.user=init->user;lde_privs.group=init->group;zprivs_preinit(&lde_privs);z
privs_init(&lde_privs);/*starttheLIBgarbagecollector*/lde_gc_start_timer();/*Ini
tsynchronouszclientandlabellist*/frr_zclient_addr(&zclient_addr,&zclient_addr_le
n,init->zclient_serv_path);zclient_sync_init(init->instance);lde_label_list_init
();}staticvoidlde_shutdown(void){/*closepipes*/if(iev_ldpe){msgbuf_clear(&iev_ld
pe->ibuf.w);close(iev_ldpe->ibuf.fd);iev_ldpe->ibuf.fd=-1;}msgbuf_clear(&iev_mai
n->ibuf.w);close(iev_main->ibuf.fd);iev_main->ibuf.fd=-1;msgbuf_clear(&iev_main_
sync->ibuf.w);close(iev_main_sync->ibuf.fd);iev_main_sync->ibuf.fd=-1;lde_gc_sto
p_timer();lde_nbr_clear();fec_tree_clear();config_clear(ldeconf);if(iev_ldpe)fre
e(iev_ldpe);free(iev_main);free(iev_main_sync);log_info("labeldecisionengineexit
ing");exit(0);}/*imesg*/intlde_imsg_compose_parent(inttype,pid_tpid,void*data,ui
nt16_tdatalen){if(iev_main->ibuf.fd==-1)return(0);return(imsg_compose_event(iev_
main,type,0,pid,-1,data,datalen));}voidlde_imsg_compose_parent_sync(inttype,pid_
tpid,void*data,uint16_tdatalen){if(iev_main_sync->ibuf.fd==-1)return;imsg_compos
e_event(iev_main_sync,type,0,pid,-1,data,datalen);imsg_flush(&iev_main_sync->ibu
f);}intlde_imsg_compose_ldpe(inttype,uint32_tpeerid,pid_tpid,void*data,uint16_td
atalen){if(iev_ldpe->ibuf.fd==-1)return(0);return(imsg_compose_event(iev_ldpe,ty
pe,peerid,pid,-1,data,datalen));}/*ARGSUSED*/staticintlde_dispatch_imsg(structth
read*thread){structimsgev*iev=THREAD_ARG(thread);structimsgbuf*ibuf=&iev->ibuf;s
tructimsgimsg;structlde_nbr*ln;structmap*map;structlde_addr*lde_addr;structnotif
y_msg*nm;ssize_tn;intshut=0;iev->ev_read=NULL;if((n=imsg_read(ibuf))==-1&&errno!
=EAGAIN)fatal("imsg_readerror");if(n==0)/*connectionclosed*/shut=1;for(;;){if((n
=imsg_get(ibuf,&imsg))==-1)fatal("lde_dispatch_imsg:imsg_geterror");if(n==0)brea
k;switch(imsg.hdr.type){caseIMSG_LABEL_MAPPING_FULL:ln=lde_nbr_find(imsg.hdr.pee
rid);if(ln==NULL){log_debug("%s:cannotfindldeneighbor",__func__);break;}fec_snap
(ln);break;caseIMSG_LABEL_MAPPING:caseIMSG_LABEL_REQUEST:caseIMSG_LABEL_RELEASE:
caseIMSG_LABEL_WITHDRAW:caseIMSG_LABEL_ABORT:if(imsg.hdr.len-IMSG_HEADER_SIZE!=s
izeof(structmap))fatalx("lde_dispatch_imsg:wrongimsglen");map=imsg.data;ln=lde_n
br_find(imsg.hdr.peerid);if(ln==NULL){log_debug("%s:cannotfindldeneighbor",__fun
c__);break;}switch(imsg.hdr.type){caseIMSG_LABEL_MAPPING:lde_check_mapping(map,l
n);break;caseIMSG_LABEL_REQUEST:lde_check_request(map,ln);break;caseIMSG_LABEL_R
ELEASE:lde_check_release(map,ln);break;caseIMSG_LABEL_WITHDRAW:lde_check_withdra
w(map,ln);break;caseIMSG_LABEL_ABORT:/*notnecessary*/break;}break;caseIMSG_ADDRE
SS_ADD:if(imsg.hdr.len-IMSG_HEADER_SIZE!=sizeof(structlde_addr))fatalx("lde_disp
atch_imsg:wrongimsglen");lde_addr=imsg.data;ln=lde_nbr_find(imsg.hdr.peerid);if(
ln==NULL){log_debug("%s:cannotfindldeneighbor",__func__);break;}if(lde_address_a
dd(ln,lde_addr)<0){log_debug("%s:cannotaddaddress%s,it""alreadyexists",__func__,
log_addr(lde_addr->af,&lde_addr->addr));}break;caseIMSG_ADDRESS_DEL:if(imsg.hdr.
len-IMSG_HEADER_SIZE!=sizeof(structlde_addr))fatalx("lde_dispatch_imsg:wrongimsg
len");lde_addr=imsg.data;ln=lde_nbr_find(imsg.hdr.peerid);if(ln==NULL){log_debug
("%s:cannotfindldeneighbor",__func__);break;}if(lde_address_del(ln,lde_addr)<0){
log_debug("%s:cannotdeleteaddress%s,it""doesnotexist",__func__,log_addr(lde_addr
->af,&lde_addr->addr));}break;caseIMSG_NOTIFICATION:if(imsg.hdr.len-IMSG_HEADER_
SIZE!=sizeof(structnotify_msg))fatalx("lde_dispatch_imsg:wrongimsglen");nm=imsg.
data;ln=lde_nbr_find(imsg.hdr.peerid);if(ln==NULL){log_debug("%s:cannotfindldene
ighbor",__func__);break;}switch(nm->status_code){caseS_PW_STATUS:l2vpn_recv_pw_s
tatus(ln,nm);break;caseS_ENDOFLIB:/**Donothingfornow.Shouldbeusefulin*thefuturew
henweimplementLDP-IGP*Synchronization(RFC5443)andGraceful*Restart(RFC3478).*/def
ault:break;}break;caseIMSG_NEIGHBOR_UP:if(imsg.hdr.len-IMSG_HEADER_SIZE!=sizeof(
structlde_nbr))fatalx("lde_dispatch_imsg:wrongimsglen");if(lde_nbr_find(imsg.hdr
.peerid))fatalx("lde_dispatch_imsg:""neighboralreadyexists");lde_nbr_new(imsg.hd
r.peerid,imsg.data);break;caseIMSG_NEIGHBOR_DOWN:lde_nbr_del(lde_nbr_find(imsg.h
dr.peerid));break;caseIMSG_CTL_SHOW_LIB:rt_dump(imsg.hdr.pid);lde_imsg_compose_l
dpe(IMSG_CTL_END,0,imsg.hdr.pid,NULL,0);break;caseIMSG_CTL_SHOW_L2VPN_PW:l2vpn_p
w_ctl(imsg.hdr.pid);lde_imsg_compose_ldpe(IMSG_CTL_END,0,imsg.hdr.pid,NULL,0);br
eak;caseIMSG_CTL_SHOW_L2VPN_BINDING:l2vpn_binding_ctl(imsg.hdr.pid);lde_imsg_com
pose_ldpe(IMSG_CTL_END,0,imsg.hdr.pid,NULL,0);break;default:log_debug("%s:unexpe
ctedimsg%d",__func__,imsg.hdr.type);break;}imsg_free(&imsg);}if(!shut)imsg_event
_add(iev);else{/*thispipeisdead,soremovetheeventhandlersandexit*/THREAD_READ_OFF
(iev->ev_read);THREAD_WRITE_OFF(iev->ev_write);lde_shutdown();}return(0);}/*ARGS
USED*/staticintlde_dispatch_parent(structthread*thread){staticstructldpd_conf*nc
onf;structiface*iface,*niface;structtnbr*ntnbr;structnbr_params*nnbrp;staticstru
ctl2vpn*l2vpn,*nl2vpn;structl2vpn_if*lif,*nlif;structl2vpn_pw*pw,*npw;structimsg
imsg;structkif*kif;structkroute*kr;intfd;structimsgev*iev=THREAD_ARG(thread);str
uctimsgbuf*ibuf=&iev->ibuf;ssize_tn;intshut=0;structfecfec;iev->ev_read=NULL;if(
(n=imsg_read(ibuf))==-1&&errno!=EAGAIN)fatal("imsg_readerror");if(n==0)/*connect
ionclosed*/shut=1;for(;;){if((n=imsg_get(ibuf,&imsg))==-1)fatal("lde_dispatch_pa
rent:imsg_geterror");if(n==0)break;switch(imsg.hdr.type){caseIMSG_IFSTATUS:if(im
sg.hdr.len!=IMSG_HEADER_SIZE+sizeof(structkif))fatalx("IFSTATUSimsgwithwronglen"
);kif=imsg.data;iface=if_lookup_name(ldeconf,kif->ifname);if(iface){if_update_in
fo(iface,kif);break;}RB_FOREACH(l2vpn,l2vpn_head,&ldeconf->l2vpn_tree){lif=l2vpn
_if_find(l2vpn,kif->ifname);if(lif){l2vpn_if_update_info(lif,kif);break;}pw=l2vp
n_pw_find(l2vpn,kif->ifname);if(pw){l2vpn_pw_update_info(pw,kif);break;}}break;c
aseIMSG_PW_UPDATE:if(imsg.hdr.len!=IMSG_HEADER_SIZE+sizeof(structzapi_pw_status)
)fatalx("PW_UPDATEimsgwithwronglen");if(l2vpn_pw_status_update(imsg.data)!=0)log
_warnx("%s:errorupdatingPWstatus",__func__);break;caseIMSG_NETWORK_ADD:caseIMSG_
NETWORK_UPDATE:if(imsg.hdr.len!=IMSG_HEADER_SIZE+sizeof(structkroute)){log_warnx
("%s:wrongimsglen",__func__);break;}kr=imsg.data;switch(kr->af){caseAF_INET:fec.
type=FEC_TYPE_IPV4;fec.u.ipv4.prefix=kr->prefix.v4;fec.u.ipv4.prefixlen=kr->pref
ixlen;break;caseAF_INET6:fec.type=FEC_TYPE_IPV6;fec.u.ipv6.prefix=kr->prefix.v6;
fec.u.ipv6.prefixlen=kr->prefixlen;break;default:fatalx("lde_dispatch_parent:unk
nownaf");}switch(imsg.hdr.type){caseIMSG_NETWORK_ADD:lde_kernel_insert(&fec,kr->
af,&kr->nexthop,kr->ifindex,kr->priority,kr->flags&F_CONNECTED,NULL);break;caseI
MSG_NETWORK_UPDATE:lde_kernel_update(&fec);break;}break;caseIMSG_SOCKET_IPC:if(i
ev_ldpe){log_warnx("%s:receivedunexpectedimsgfd""toldpe",__func__);break;}if((fd
=imsg.fd)==-1){log_warnx("%s:expectedtoreceiveimsgfdto""ldpebutdidn'treceiveany"
,__func__);break;}if((iev_ldpe=malloc(sizeof(structimsgev)))==NULL)fatal(NULL);i
msg_init(&iev_ldpe->ibuf,fd);iev_ldpe->handler_read=lde_dispatch_imsg;iev_ldpe->
ev_read=NULL;thread_add_read(master,iev_ldpe->handler_read,iev_ldpe,iev_ldpe->ib
uf.fd,&iev_ldpe->ev_read);iev_ldpe->handler_write=ldp_write_handler;iev_ldpe->ev
_write=NULL;break;caseIMSG_INIT:if(imsg.hdr.len!=IMSG_HEADER_SIZE+sizeof(structl
dpd_init))fatalx("INITimsgwithwronglen");memcpy(&init,imsg.data,sizeof(init));ld
e_init(&init);break;caseIMSG_RECONF_CONF:if((nconf=malloc(sizeof(structldpd_conf
)))==NULL)fatal(NULL);memcpy(nconf,imsg.data,sizeof(structldpd_conf));RB_INIT(if
ace_head,&nconf->iface_tree);RB_INIT(tnbr_head,&nconf->tnbr_tree);RB_INIT(nbrp_h
ead,&nconf->nbrp_tree);RB_INIT(l2vpn_head,&nconf->l2vpn_tree);break;caseIMSG_REC
ONF_IFACE:if((niface=malloc(sizeof(structiface)))==NULL)fatal(NULL);memcpy(nifac
e,imsg.data,sizeof(structiface));RB_INSERT(iface_head,&nconf->iface_tree,niface)
;break;caseIMSG_RECONF_TNBR:if((ntnbr=malloc(sizeof(structtnbr)))==NULL)fatal(NU
LL);memcpy(ntnbr,imsg.data,sizeof(structtnbr));RB_INSERT(tnbr_head,&nconf->tnbr_
tree,ntnbr);break;caseIMSG_RECONF_NBRP:if((nnbrp=malloc(sizeof(structnbr_params)
))==NULL)fatal(NULL);memcpy(nnbrp,imsg.data,sizeof(structnbr_params));RB_INSERT(
nbrp_head,&nconf->nbrp_tree,nnbrp);break;caseIMSG_RECONF_L2VPN:if((nl2vpn=malloc
(sizeof(structl2vpn)))==NULL)fatal(NULL);memcpy(nl2vpn,imsg.data,sizeof(structl2
vpn));RB_INIT(l2vpn_if_head,&nl2vpn->if_tree);RB_INIT(l2vpn_pw_head,&nl2vpn->pw_
tree);RB_INIT(l2vpn_pw_head,&nl2vpn->pw_inactive_tree);RB_INSERT(l2vpn_head,&nco
nf->l2vpn_tree,nl2vpn);break;caseIMSG_RECONF_L2VPN_IF:if((nlif=malloc(sizeof(str
uctl2vpn_if)))==NULL)fatal(NULL);memcpy(nlif,imsg.data,sizeof(structl2vpn_if));R
B_INSERT(l2vpn_if_head,&nl2vpn->if_tree,nlif);break;caseIMSG_RECONF_L2VPN_PW:if(
(npw=malloc(sizeof(structl2vpn_pw)))==NULL)fatal(NULL);memcpy(npw,imsg.data,size
of(structl2vpn_pw));RB_INSERT(l2vpn_pw_head,&nl2vpn->pw_tree,npw);break;caseIMSG
_RECONF_L2VPN_IPW:if((npw=malloc(sizeof(structl2vpn_pw)))==NULL)fatal(NULL);memc
py(npw,imsg.data,sizeof(structl2vpn_pw));RB_INSERT(l2vpn_pw_head,&nl2vpn->pw_ina
ctive_tree,npw);break;caseIMSG_RECONF_END:merge_config(ldeconf,nconf);ldp_clear_
config(nconf);nconf=NULL;break;caseIMSG_DEBUG_UPDATE:if(imsg.hdr.len!=IMSG_HEADE
R_SIZE+sizeof(ldp_debug)){log_warnx("%s:wrongimsglen",__func__);break;}memcpy(&l
dp_debug,imsg.data,sizeof(ldp_debug));break;default:log_debug("%s:unexpectedimsg
%d",__func__,imsg.hdr.type);break;}imsg_free(&imsg);}if(!shut)imsg_event_add(iev
);else{/*thispipeisdead,soremovetheeventhandlersandexit*/THREAD_READ_OFF(iev->ev
_read);THREAD_WRITE_OFF(iev->ev_write);lde_shutdown();}return(0);}intlde_acl_che
ck(char*acl_name,intaf,unionldpd_addr*addr,uint8_tprefixlen){returnldp_acl_reque
st(iev_main_sync,acl_name,af,addr,prefixlen);}uint32_tlde_update_label(structfec
_node*fn){structfec_nh*fnh;intconnected=0;LIST_FOREACH(fnh,&fn->nexthops,entry){
if(fnh->flags&F_FEC_NH_CONNECTED){connected=1;break;}}/*shouldweallocatealabelfo
rthisfec?*/switch(fn->fec.type){caseFEC_TYPE_IPV4:if((ldeconf->ipv4.flags&F_LDPD
_AF_ALLOCHOSTONLY)&&fn->fec.u.ipv4.prefixlen!=32)return(NO_LABEL);if(lde_acl_che
ck(ldeconf->ipv4.acl_label_allocate_for,AF_INET,(unionldpd_addr*)&fn->fec.u.ipv4
.prefix,fn->fec.u.ipv4.prefixlen)!=FILTER_PERMIT)return(NO_LABEL);break;caseFEC_
TYPE_IPV6:if((ldeconf->ipv6.flags&F_LDPD_AF_ALLOCHOSTONLY)&&fn->fec.u.ipv6.prefi
xlen!=128)return(NO_LABEL);if(lde_acl_check(ldeconf->ipv6.acl_label_allocate_for
,AF_INET6,(unionldpd_addr*)&fn->fec.u.ipv6.prefix,fn->fec.u.ipv6.prefixlen)!=FIL
TER_PERMIT)return(NO_LABEL);break;default:break;}if(connected){/*chooseimplicito
rexplicit-nulldependingonconfiguration*/switch(fn->fec.type){caseFEC_TYPE_IPV4:i
f(!(ldeconf->ipv4.flags&F_LDPD_AF_EXPNULL))return(MPLS_LABEL_IMPLICIT_NULL);if(l
de_acl_check(ldeconf->ipv4.acl_label_expnull_for,AF_INET,(unionldpd_addr*)&fn->f
ec.u.ipv4.prefix,fn->fec.u.ipv4.prefixlen)!=FILTER_PERMIT)return(MPLS_LABEL_IMPL
ICIT_NULL);returnMPLS_LABEL_IPV4_EXPLICIT_NULL;caseFEC_TYPE_IPV6:if(!(ldeconf->i
pv6.flags&F_LDPD_AF_EXPNULL))return(MPLS_LABEL_IMPLICIT_NULL);if(lde_acl_check(l
deconf->ipv6.acl_label_expnull_for,AF_INET6,(unionldpd_addr*)&fn->fec.u.ipv6.pre
fix,fn->fec.u.ipv6.prefixlen)!=FILTER_PERMIT)return(MPLS_LABEL_IMPLICIT_NULL);re
turnMPLS_LABEL_IPV6_EXPLICIT_NULL;default:fatalx("lde_update_label:unexpectedfec
type");break;}}/*preservecurrentlabelifthere'snoneedtoupdateit*/if(fn->local_lab
el!=NO_LABEL&&fn->local_label>MPLS_LABEL_RESERVED_MAX)return(fn->local_label);re
turn(lde_get_next_label());}voidlde_send_change_klabel(structfec_node*fn,structf
ec_nh*fnh){structkroutekr;structzapi_pwzpw;structl2vpn_pw*pw;switch(fn->fec.type
){caseFEC_TYPE_IPV4:memset(&kr,0,sizeof(kr));kr.af=AF_INET;kr.prefix.v4=fn->fec.
u.ipv4.prefix;kr.prefixlen=fn->fec.u.ipv4.prefixlen;kr.nexthop.v4=fnh->nexthop.v
4;kr.ifindex=fnh->ifindex;kr.local_label=fn->local_label;kr.remote_label=fnh->re
mote_label;kr.priority=fnh->priority;lde_imsg_compose_parent(IMSG_KLABEL_CHANGE,
0,&kr,sizeof(kr));break;caseFEC_TYPE_IPV6:memset(&kr,0,sizeof(kr));kr.af=AF_INET
6;kr.prefix.v6=fn->fec.u.ipv6.prefix;kr.prefixlen=fn->fec.u.ipv6.prefixlen;kr.ne
xthop.v6=fnh->nexthop.v6;kr.ifindex=fnh->ifindex;kr.local_label=fn->local_label;
kr.remote_label=fnh->remote_label;kr.priority=fnh->priority;lde_imsg_compose_par
ent(IMSG_KLABEL_CHANGE,0,&kr,sizeof(kr));break;caseFEC_TYPE_PWID:pw=(structl2vpn
_pw*)fn->data;if(!pw||fn->local_label==NO_LABEL||fnh->remote_label==NO_LABEL)ret
urn;pw->enabled=true;pw2zpw(pw,&zpw);zpw.local_label=fn->local_label;zpw.remote_
label=fnh->remote_label;lde_imsg_compose_parent(IMSG_KPW_SET,0,&zpw,sizeof(zpw))
;break;}}voidlde_send_delete_klabel(structfec_node*fn,structfec_nh*fnh){structkr
outekr;structzapi_pwzpw;structl2vpn_pw*pw;switch(fn->fec.type){caseFEC_TYPE_IPV4
:memset(&kr,0,sizeof(kr));kr.af=AF_INET;kr.prefix.v4=fn->fec.u.ipv4.prefix;kr.pr
efixlen=fn->fec.u.ipv4.prefixlen;kr.nexthop.v4=fnh->nexthop.v4;kr.ifindex=fnh->i
findex;kr.local_label=fn->local_label;kr.remote_label=fnh->remote_label;kr.prior
ity=fnh->priority;lde_imsg_compose_parent(IMSG_KLABEL_DELETE,0,&kr,sizeof(kr));b
reak;caseFEC_TYPE_IPV6:memset(&kr,0,sizeof(kr));kr.af=AF_INET6;kr.prefix.v6=fn->
fec.u.ipv6.prefix;kr.prefixlen=fn->fec.u.ipv6.prefixlen;kr.nexthop.v6=fnh->nexth
op.v6;kr.ifindex=fnh->ifindex;kr.local_label=fn->local_label;kr.remote_label=fnh
->remote_label;kr.priority=fnh->priority;lde_imsg_compose_parent(IMSG_KLABEL_DEL
ETE,0,&kr,sizeof(kr));break;caseFEC_TYPE_PWID:pw=(structl2vpn_pw*)fn->data;if(!p
w)return;pw->enabled=false;pw2zpw(pw,&zpw);zpw.local_label=fn->local_label;zpw.r
emote_label=fnh->remote_label;lde_imsg_compose_parent(IMSG_KPW_UNSET,0,&zpw,size
of(zpw));break;}}voidlde_fec2map(structfec*fec,structmap*map){memset(map,0,sizeo
f(*map));switch(fec->type){caseFEC_TYPE_IPV4:map->type=MAP_TYPE_PREFIX;map->fec.
prefix.af=AF_INET;map->fec.prefix.prefix.v4=fec->u.ipv4.prefix;map->fec.prefix.p
refixlen=fec->u.ipv4.prefixlen;break;caseFEC_TYPE_IPV6:map->type=MAP_TYPE_PREFIX
;map->fec.prefix.af=AF_INET6;map->fec.prefix.prefix.v6=fec->u.ipv6.prefix;map->f
ec.prefix.prefixlen=fec->u.ipv6.prefixlen;break;caseFEC_TYPE_PWID:map->type=MAP_
TYPE_PWID;map->fec.pwid.type=fec->u.pwid.type;map->fec.pwid.group_id=0;map->flag
s|=F_MAP_PW_ID;map->fec.pwid.pwid=fec->u.pwid.pwid;break;}}voidlde_map2fec(struc
tmap*map,structin_addrlsr_id,structfec*fec){memset(fec,0,sizeof(*fec));switch(ma
p->type){caseMAP_TYPE_PREFIX:switch(map->fec.prefix.af){caseAF_INET:fec->type=FE
C_TYPE_IPV4;fec->u.ipv4.prefix=map->fec.prefix.prefix.v4;fec->u.ipv4.prefixlen=m
ap->fec.prefix.prefixlen;break;caseAF_INET6:fec->type=FEC_TYPE_IPV6;fec->u.ipv6.
prefix=map->fec.prefix.prefix.v6;fec->u.ipv6.prefixlen=map->fec.prefix.prefixlen
;break;default:fatalx("lde_map2fec:unknownaf");break;}break;caseMAP_TYPE_PWID:fe
c->type=FEC_TYPE_PWID;fec->u.pwid.type=map->fec.pwid.type;fec->u.pwid.pwid=map->
fec.pwid.pwid;fec->u.pwid.lsr_id=lsr_id;break;}}voidlde_send_labelmapping(struct
lde_nbr*ln,structfec_node*fn,intsingle){structlde_wdraw*lw;structlde_map*me;stru
ctlde_req*lre;structmapmap;structl2vpn_pw*pw;/**Weshouldn'tsendanewlabelmappingi
fwehaveapending*labelreleasetoreceive.Inthiscase,scheduletosenda*labelmappingass
oonasalabelreleaseisreceived.*/lw=(structlde_wdraw*)fec_find(&ln->sent_wdraw,&fn
->fec);if(lw){if(!fec_find(&ln->sent_map_pending,&fn->fec)){debug_evt("%s:FEC%s:
schedulingtosendlabel""mappinglater(waitingforpendinglabelrelease)",__func__,log
_fec(&fn->fec));lde_map_pending_add(ln,fn);}return;}/**ThisfunctionskipsSL.1-3an
dSL.9-14becausethelabel*allocationisdonewayearlier(becauseofthemergingnatureof*l
dpd).*/lde_fec2map(&fn->fec,&map);switch(fn->fec.type){caseFEC_TYPE_IPV4:if(!ln-
>v4_enabled)return;if(lde_acl_check(ldeconf->ipv4.acl_label_advertise_to,AF_INET
,(unionldpd_addr*)&ln->id,32)!=FILTER_PERMIT)return;if(lde_acl_check(ldeconf->ip
v4.acl_label_advertise_for,AF_INET,(unionldpd_addr*)&fn->fec.u.ipv4.prefix,fn->f
ec.u.ipv4.prefixlen)!=FILTER_PERMIT)return;break;caseFEC_TYPE_IPV6:if(!ln->v6_en
abled)return;if(lde_acl_check(ldeconf->ipv6.acl_label_advertise_to,AF_INET,(unio
nldpd_addr*)&ln->id,32)!=FILTER_PERMIT)return;if(lde_acl_check(ldeconf->ipv6.acl
_label_advertise_for,AF_INET6,(unionldpd_addr*)&fn->fec.u.ipv6.prefix,fn->fec.u.
ipv6.prefixlen)!=FILTER_PERMIT)return;break;caseFEC_TYPE_PWID:pw=(structl2vpn_pw
*)fn->data;if(pw==NULL||pw->lsr_id.s_addr!=ln->id.s_addr)/*nottheremoteendofthep
seudowire*/return;map.flags|=F_MAP_PW_IFMTU;map.fec.pwid.ifmtu=pw->l2vpn->mtu;if
(pw->flags&F_PW_CWORD)map.flags|=F_MAP_PW_CWORD;if(pw->flags&F_PW_STATUSTLV){map
.flags|=F_MAP_PW_STATUS;map.pw_status=pw->local_status;}break;}map.label=fn->loc
al_label;/*SL.6:isthereapendingrequestforthismapping?*/lre=(structlde_req*)fec_f
ind(&ln->recv_req,&fn->fec);if(lre){/*setlabelrequestmsgidinthemappingresponse.*
/map.requestid=lre->msg_id;map.flags=F_MAP_REQ_ID;/*SL.7:deleterecordofpendingre
quest*/lde_req_del(ln,lre,0);}/*SL.4:sendlabelmapping*/lde_imsg_compose_ldpe(IMS
G_MAPPING_ADD,ln->peerid,0,&map,sizeof(map));if(single)lde_imsg_compose_ldpe(IMS
G_MAPPING_ADD_END,ln->peerid,0,NULL,0);/*SL.5:recordsentlabelmapping*/me=(struct
lde_map*)fec_find(&ln->sent_map,&fn->fec);if(me==NULL)me=lde_map_add(ln,fn,1);me
->map=map;}voidlde_send_labelwithdraw(structlde_nbr*ln,structfec_node*fn,structm
ap*wcard,structstatus_tlv*st){structlde_wdraw*lw;structmapmap;structfec*f;struct
l2vpn_pw*pw;if(fn){lde_fec2map(&fn->fec,&map);switch(fn->fec.type){caseFEC_TYPE_
IPV4:if(!ln->v4_enabled)return;break;caseFEC_TYPE_IPV6:if(!ln->v6_enabled)return
;break;caseFEC_TYPE_PWID:pw=(structl2vpn_pw*)fn->data;if(pw==NULL||pw->lsr_id.s_
addr!=ln->id.s_addr)/*nottheremoteendofthepseudowire*/return;if(pw->flags&F_PW_C
WORD)map.flags|=F_MAP_PW_CWORD;break;}map.label=fn->local_label;}elsememcpy(&map
,wcard,sizeof(map));if(st){map.st.status_code=st->status_code;map.st.msg_id=st->
msg_id;map.st.msg_type=st->msg_type;map.flags|=F_MAP_STATUS;}/*SWd.1:sendlabelwi
thdraw.*/lde_imsg_compose_ldpe(IMSG_WITHDRAW_ADD,ln->peerid,0,&map,sizeof(map));
lde_imsg_compose_ldpe(IMSG_WITHDRAW_ADD_END,ln->peerid,0,NULL,0);/*SWd.2:recordl
abelwithdraw.*/if(fn){lw=(structlde_wdraw*)fec_find(&ln->sent_wdraw,&fn->fec);if
(lw==NULL)lw=lde_wdraw_add(ln,fn);lw->label=map.label;}else{structlde_map*me;RB_
FOREACH(f,fec_tree,&ft){fn=(structfec_node*)f;me=(structlde_map*)fec_find(&ln->s
ent_map,&fn->fec);if(lde_wildcard_apply(wcard,&fn->fec,me)==0)continue;lw=(struc
tlde_wdraw*)fec_find(&ln->sent_wdraw,&fn->fec);if(lw==NULL)lw=lde_wdraw_add(ln,f
n);lw->label=map.label;}}}voidlde_send_labelwithdraw_wcard(structlde_nbr*ln,uint
32_tlabel){structmapwcard;memset(&wcard,0,sizeof(wcard));wcard.type=MAP_TYPE_WIL
DCARD;wcard.label=label;lde_send_labelwithdraw(ln,NULL,&wcard,NULL);}voidlde_sen
d_labelwithdraw_twcard_prefix(structlde_nbr*ln,uint16_taf,uint32_tlabel){structm
apwcard;memset(&wcard,0,sizeof(wcard));wcard.type=MAP_TYPE_TYPED_WCARD;wcard.fec
.twcard.type=MAP_TYPE_PREFIX;wcard.fec.twcard.u.prefix_af=af;wcard.label=label;l
de_send_labelwithdraw(ln,NULL,&wcard,NULL);}voidlde_send_labelwithdraw_twcard_pw
id(structlde_nbr*ln,uint16_tpw_type,uint32_tlabel){structmapwcard;memset(&wcard,
0,sizeof(wcard));wcard.type=MAP_TYPE_TYPED_WCARD;wcard.fec.twcard.type=MAP_TYPE_
PWID;wcard.fec.twcard.u.pw_type=pw_type;wcard.label=label;lde_send_labelwithdraw
(ln,NULL,&wcard,NULL);}voidlde_send_labelwithdraw_pwid_wcard(structlde_nbr*ln,ui
nt16_tpw_type,uint32_tgroup_id){structmapwcard;memset(&wcard,0,sizeof(wcard));wc
ard.type=MAP_TYPE_PWID;wcard.fec.pwid.type=pw_type;wcard.fec.pwid.group_id=group
_id;/*wecannotappendaLabelTLVwhenusingPWidgroupwildcards.*/wcard.label=NO_LABEL;
lde_send_labelwithdraw(ln,NULL,&wcard,NULL);}voidlde_send_labelrelease(structlde
_nbr*ln,structfec_node*fn,structmap*wcard,uint32_tlabel){structmapmap;structl2vp
n_pw*pw;if(fn){lde_fec2map(&fn->fec,&map);switch(fn->fec.type){caseFEC_TYPE_IPV4
:if(!ln->v4_enabled)return;break;caseFEC_TYPE_IPV6:if(!ln->v6_enabled)return;bre
ak;caseFEC_TYPE_PWID:pw=(structl2vpn_pw*)fn->data;if(pw==NULL||pw->lsr_id.s_addr
!=ln->id.s_addr)/*nottheremoteendofthepseudowire*/return;if(pw->flags&F_PW_CWORD
)map.flags|=F_MAP_PW_CWORD;break;}}elsememcpy(&map,wcard,sizeof(map));map.label=
label;lde_imsg_compose_ldpe(IMSG_RELEASE_ADD,ln->peerid,0,&map,sizeof(map));lde_
imsg_compose_ldpe(IMSG_RELEASE_ADD_END,ln->peerid,0,NULL,0);}voidlde_send_notifi
cation(structlde_nbr*ln,uint32_tstatus_code,uint32_tmsg_id,uint16_tmsg_type){str
uctnotify_msgnm;memset(&nm,0,sizeof(nm));nm.status_code=status_code;/*'msg_id'an
d'msg_type'shouldbeinnetworkbyteorder*/nm.msg_id=msg_id;nm.msg_type=msg_type;lde
_imsg_compose_ldpe(IMSG_NOTIFICATION_SEND,ln->peerid,0,&nm,sizeof(nm));}voidlde_
send_notification_eol_prefix(structlde_nbr*ln,intaf){structnotify_msgnm;memset(&
nm,0,sizeof(nm));nm.status_code=S_ENDOFLIB;nm.fec.type=MAP_TYPE_TYPED_WCARD;nm.f
ec.fec.twcard.type=MAP_TYPE_PREFIX;nm.fec.fec.twcard.u.prefix_af=af;nm.flags|=F_
NOTIF_FEC;lde_imsg_compose_ldpe(IMSG_NOTIFICATION_SEND,ln->peerid,0,&nm,sizeof(n
m));}voidlde_send_notification_eol_pwid(structlde_nbr*ln,uint16_tpw_type){struct
notify_msgnm;memset(&nm,0,sizeof(nm));nm.status_code=S_ENDOFLIB;nm.fec.type=MAP_
TYPE_TYPED_WCARD;nm.fec.fec.twcard.type=MAP_TYPE_PWID;nm.fec.fec.twcard.u.pw_typ
e=pw_type;nm.flags|=F_NOTIF_FEC;lde_imsg_compose_ldpe(IMSG_NOTIFICATION_SEND,ln-
>peerid,0,&nm,sizeof(nm));}static__inlineintlde_nbr_compare(conststructlde_nbr*a
,conststructlde_nbr*b){return(a->peerid-b->peerid);}staticstructlde_nbr*lde_nbr_
new(uint32_tpeerid,structlde_nbr*new){structlde_nbr*ln;if((ln=calloc(1,sizeof(*l
n)))==NULL)fatal(__func__);ln->id=new->id;ln->v4_enabled=new->v4_enabled;ln->v6_
enabled=new->v6_enabled;ln->flags=new->flags;ln->peerid=peerid;fec_init(&ln->rec
v_map);fec_init(&ln->sent_map);fec_init(&ln->sent_map_pending);fec_init(&ln->rec
v_req);fec_init(&ln->sent_req);fec_init(&ln->sent_wdraw);TAILQ_INIT(&ln->addr_li
st);if(RB_INSERT(nbr_tree,&lde_nbrs,ln)!=NULL)fatalx("lde_nbr_new:RB_INSERTfaile
d");return(ln);}staticvoidlde_nbr_del(structlde_nbr*ln){structfec*f;structfec_no
de*fn;structfec_nh*fnh;structl2vpn_pw*pw;if(ln==NULL)return;/*uninstallreceivedm
appings*/RB_FOREACH(f,fec_tree,&ft){fn=(structfec_node*)f;LIST_FOREACH(fnh,&fn->
nexthops,entry){switch(f->type){caseFEC_TYPE_IPV4:caseFEC_TYPE_IPV6:if(!lde_addr
ess_find(ln,fnh->af,&fnh->nexthop))continue;break;caseFEC_TYPE_PWID:if(f->u.pwid
.lsr_id.s_addr!=ln->id.s_addr)continue;pw=(structl2vpn_pw*)fn->data;if(pw)l2vpn_
pw_reset(pw);break;default:break;}lde_send_delete_klabel(fn,fnh);fnh->remote_lab
el=NO_LABEL;}}lde_address_list_free(ln);fec_clear(&ln->recv_map,lde_map_free);fe
c_clear(&ln->sent_map,lde_map_free);fec_clear(&ln->sent_map_pending,free);fec_cl
ear(&ln->recv_req,free);fec_clear(&ln->sent_req,free);fec_clear(&ln->sent_wdraw,
free);RB_REMOVE(nbr_tree,&lde_nbrs,ln);free(ln);}staticstructlde_nbr*lde_nbr_fin
d(uint32_tpeerid){structlde_nbrln;ln.peerid=peerid;return(RB_FIND(nbr_tree,&lde_
nbrs,&ln));}structlde_nbr*lde_nbr_find_by_lsrid(structin_addraddr){structlde_nbr
*ln;RB_FOREACH(ln,nbr_tree,&lde_nbrs)if(ln->id.s_addr==addr.s_addr)return(ln);re
turn(NULL);}structlde_nbr*lde_nbr_find_by_addr(intaf,unionldpd_addr*addr){struct
lde_nbr*ln;RB_FOREACH(ln,nbr_tree,&lde_nbrs)if(lde_address_find(ln,af,addr)!=NUL
L)return(ln);return(NULL);}staticvoidlde_nbr_clear(void){structlde_nbr*ln;while(
!RB_EMPTY(nbr_tree,&lde_nbrs)){ln=RB_ROOT(nbr_tree,&lde_nbrs);lde_nbr_del(ln);}}
staticvoidlde_nbr_addr_update(structlde_nbr*ln,structlde_addr*lde_addr,intremove
d){structfec*fec;structfec_node*fn;structfec_nh*fnh;structlde_map*me;RB_FOREACH(
fec,fec_tree,&ln->recv_map){switch(fec->type){caseFEC_TYPE_IPV4:if(lde_addr->af!
=AF_INET)continue;break;caseFEC_TYPE_IPV6:if(lde_addr->af!=AF_INET6)continue;bre
ak;default:continue;}fn=(structfec_node*)fec_find(&ft,fec);if(fn==NULL)/*shouldn
'thappen*/continue;LIST_FOREACH(fnh,&fn->nexthops,entry){if(ldp_addrcmp(fnh->af,
&fnh->nexthop,&lde_addr->addr))continue;if(removed){lde_send_delete_klabel(fn,fn
h);fnh->remote_label=NO_LABEL;}else{me=(structlde_map*)fec;fnh->remote_label=me-
>map.label;lde_send_change_klabel(fn,fnh);}break;}}}static__inlineintlde_map_com
pare(conststructlde_map*a,conststructlde_map*b){return(ldp_addrcmp(AF_INET,(unio
nldpd_addr*)&a->nexthop->id,(unionldpd_addr*)&b->nexthop->id));}structlde_map*ld
e_map_add(structlde_nbr*ln,structfec_node*fn,intsent){structlde_map*me;me=calloc
(1,sizeof(*me));if(me==NULL)fatal(__func__);me->fec=fn->fec;me->nexthop=ln;if(se
nt){RB_INSERT(lde_map_head,&fn->upstream,me);me->head=&fn->upstream;if(fec_inser
t(&ln->sent_map,&me->fec))log_warnx("failedtoadd%stosentmap",log_fec(&me->fec));
/*XXXonfailuremorecleanupisneeded*/}else{RB_INSERT(lde_map_head,&fn->downstream,
me);me->head=&fn->downstream;if(fec_insert(&ln->recv_map,&me->fec))log_warnx("fa
iledtoadd%storecvmap",log_fec(&me->fec));}return(me);}voidlde_map_del(structlde_
nbr*ln,structlde_map*me,intsent){if(sent)fec_remove(&ln->sent_map,&me->fec);else
fec_remove(&ln->recv_map,&me->fec);lde_map_free(me);}staticvoidlde_map_free(void
*ptr){structlde_map*map=ptr;RB_REMOVE(lde_map_head,map->head,map);free(map);}str
uctfec*lde_map_pending_add(structlde_nbr*ln,structfec_node*fn){structfec*map;map
=calloc(1,sizeof(*map));if(map==NULL)fatal(__func__);*map=fn->fec;if(fec_insert(
&ln->sent_map_pending,map))log_warnx("failedtoadd%stosentmap(pending)",log_fec(m
ap));return(map);}voidlde_map_pending_del(structlde_nbr*ln,structfec*map){fec_re
move(&ln->sent_map_pending,map);free(map);}structlde_req*lde_req_add(structlde_n
br*ln,structfec*fec,intsent){structfec_tree*t;structlde_req*lre;t=sent?&ln->sent
_req:&ln->recv_req;lre=calloc(1,sizeof(*lre));if(lre!=NULL){lre->fec=*fec;if(fec
_insert(t,&lre->fec)){log_warnx("failedtoadd%sto%sreq",log_fec(&lre->fec),sent?"
sent":"recv");free(lre);return(NULL);}}return(lre);}voidlde_req_del(structlde_nb
r*ln,structlde_req*lre,intsent){if(sent)fec_remove(&ln->sent_req,&lre->fec);else
fec_remove(&ln->recv_req,&lre->fec);free(lre);}structlde_wdraw*lde_wdraw_add(str
uctlde_nbr*ln,structfec_node*fn){structlde_wdraw*lw;lw=calloc(1,sizeof(*lw));if(
lw==NULL)fatal(__func__);lw->fec=fn->fec;if(fec_insert(&ln->sent_wdraw,&lw->fec)
)log_warnx("failedtoadd%stosentwdraw",log_fec(&lw->fec));return(lw);}voidlde_wdr
aw_del(structlde_nbr*ln,structlde_wdraw*lw){fec_remove(&ln->sent_wdraw,&lw->fec)
;free(lw);}voidlde_change_egress_label(intaf){structlde_nbr*ln;structfec*f;struc
tfec_node*fn;/*explicitlywithdrawallnulllabels*/RB_FOREACH(ln,nbr_tree,&lde_nbrs
){lde_send_labelwithdraw_wcard(ln,MPLS_LABEL_IMPLICIT_NULL);if(ln->v4_enabled)ld
e_send_labelwithdraw_wcard(ln,MPLS_LABEL_IPV4_EXPLICIT_NULL);if(ln->v6_enabled)l
de_send_labelwithdraw_wcard(ln,MPLS_LABEL_IPV6_EXPLICIT_NULL);}/*updatelabelofco
nnectedroutes*/RB_FOREACH(f,fec_tree,&ft){fn=(structfec_node*)f;if(fn->local_lab
el>MPLS_LABEL_RESERVED_MAX)continue;switch(af){caseAF_INET:if(fn->fec.type!=FEC_
TYPE_IPV4)continue;break;caseAF_INET6:if(fn->fec.type!=FEC_TYPE_IPV6)continue;br
eak;default:fatalx("lde_change_egress_label:unknownaf");}fn->local_label=lde_upd
ate_label(fn);if(fn->local_label!=NO_LABEL)RB_FOREACH(ln,nbr_tree,&lde_nbrs)lde_
send_labelmapping(ln,fn,0);}RB_FOREACH(ln,nbr_tree,&lde_nbrs)lde_imsg_compose_ld
pe(IMSG_MAPPING_ADD_END,ln->peerid,0,NULL,0);}staticintlde_address_add(structlde
_nbr*ln,structlde_addr*lde_addr){structlde_addr*new;if(lde_address_find(ln,lde_a
ddr->af,&lde_addr->addr)!=NULL)return(-1);if((new=calloc(1,sizeof(*new)))==NULL)
fatal(__func__);new->af=lde_addr->af;new->addr=lde_addr->addr;TAILQ_INSERT_TAIL(
&ln->addr_list,new,entry);/*reevaluatethepreviouslyreceivedmappingsfromthisneigh
bor*/lde_nbr_addr_update(ln,lde_addr,0);return(0);}staticintlde_address_del(stru
ctlde_nbr*ln,structlde_addr*lde_addr){lde_addr=lde_address_find(ln,lde_addr->af,
&lde_addr->addr);if(lde_addr==NULL)return(-1);/*reevaluatethepreviouslyreceivedm
appingsfromthisneighbor*/lde_nbr_addr_update(ln,lde_addr,1);TAILQ_REMOVE(&ln->ad
dr_list,lde_addr,entry);free(lde_addr);return(0);}structlde_addr*lde_address_fin
d(structlde_nbr*ln,intaf,unionldpd_addr*addr){structlde_addr*lde_addr;TAILQ_FORE
ACH(lde_addr,&ln->addr_list,entry)if(lde_addr->af==af&&ldp_addrcmp(af,&lde_addr-
>addr,addr)==0)return(lde_addr);return(NULL);}staticvoidlde_address_list_free(st
ructlde_nbr*ln){structlde_addr*lde_addr;while((lde_addr=TAILQ_FIRST(&ln->addr_li
st))!=NULL){TAILQ_REMOVE(&ln->addr_list,lde_addr,entry);free(lde_addr);}}staticv
oidzclient_sync_init(unsignedshortinstance){/*Initializespecialzclientforsynchro
nousmessageexchanges.*/zclient_sync=zclient_new_notify(master,&zclient_options_d
efault);zclient_sync->sock=-1;zclient_sync->redist_default=ZEBRA_ROUTE_LDP;zclie
nt_sync->instance=instance;zclient_sync->privs=&lde_privs;while(zclient_socket_c
onnect(zclient_sync)<0){log_warnx("Errorconnectingsynchronouszclient!");sleep(1)
;}/*makesocketnon-blocking*/sock_set_nonblock(zclient_sync->sock);/*Connecttolab
elmanager*/while(lm_label_manager_connect(zclient_sync)!=0){log_warnx("Errorconn
ectingtolabelmanager!");sleep(1);}}staticvoidlde_del_label_chunk(void*val){free(
val);}staticintlde_get_label_chunk(void){intret;uint32_tstart,end;debug_labels("
gettinglabelchunk(size%u)",CHUNK_SIZE);ret=lm_get_label_chunk(zclient_sync,0,CHU
NK_SIZE,&start,&end);if(ret<0){log_warnx("Errorgettinglabelchunk!");return-1;}on
_get_label_chunk_response(start,end);return(0);}staticvoidlde_label_list_init(vo
id){label_chunk_list=list_new();label_chunk_list->del=lde_del_label_chunk;/*getf
irstchunk*/while(lde_get_label_chunk()!=0){log_warnx("Errorgettingfirstlabelchun
k!");sleep(1);}}staticvoidon_get_label_chunk_response(uint32_tstart,uint32_tend)
{structlabel_chunk*new_label_chunk;debug_labels("labelchunkassign:%u-%u",start,e
nd);new_label_chunk=calloc(1,sizeof(structlabel_chunk));if(!new_label_chunk){log
_warn("Errortryingtoallocatelabelchunk%u-%u",start,end);return;}new_label_chunk-
>start=start;new_label_chunk->end=end;new_label_chunk->used_mask=0;listnode_add(
label_chunk_list,(void*)new_label_chunk);/*let'supdatecurrentifneeded*/if(!curre
nt_label_chunk)current_label_chunk=listtail(label_chunk_list);}staticuint32_tlde
_get_next_label(void){structlabel_chunk*label_chunk;uint32_ti,size;uint64_tpos;u
int32_tlabel=NO_LABEL;while(current_label_chunk){label_chunk=listgetdata(current
_label_chunk);if(!label_chunk)gotoend;/*trytogetnextfreelabelincurrentlyusedlabe
lchunk*/size=label_chunk->end-label_chunk->start+1;for(i=0,pos=1;i<size;i++,pos<
<=1){if(!(pos&label_chunk->used_mask)){label_chunk->used_mask|=pos;label=label_c
hunk->start+i;gotoend;}}current_label_chunk=listnextnode(current_label_chunk);}e
nd:/*wemovedtillthelastchunk,orwerenotabletofindalabel,solet'saskforanotherone*/
if(!current_label_chunk||current_label_chunk==listtail(label_chunk_list)||label=
=NO_LABEL){if(lde_get_label_chunk()!=0)log_warn("%s:Errorgettinglabelchunk!",__f
unc__);}return(label);}