/*$OpenBSD$*//**Copyright(c)2013,2016RenatoWestphal<renato@openbsd.org>*Copyrigh
t(c)2009MicheleMarchetto<michele@openbsd.org>*Copyright(c)2004,2005,2008EsbenNor
by<norby@openbsd.org>**Permissiontouse,copy,modify,anddistributethissoftwarefora
ny*purposewithorwithoutfeeisherebygranted,providedthattheabove*copyrightnoticean
dthispermissionnoticeappearinallcopies.**THESOFTWAREISPROVIDED"ASIS"ANDTHEAUTHOR
DISCLAIMSALLWARRANTIES*WITHREGARDTOTHISSOFTWAREINCLUDINGALLIMPLIEDWARRANTIESOF*M
ERCHANTABILITYANDFITNESS.INNOEVENTSHALLTHEAUTHORBELIABLEFOR*ANYSPECIAL,DIRECT,IN
DIRECT,ORCONSEQUENTIALDAMAGESORANYDAMAGES*WHATSOEVERRESULTINGFROMLOSSOFUSE,DATAO
RPROFITS,WHETHERINAN*ACTIONOFCONTRACT,NEGLIGENCEOROTHERTORTIOUSACTION,ARISINGOUT
OF*ORINCONNECTIONWITHTHEUSEORPERFORMANCEOFTHISSOFTWARE.*/#ifndef_LDPE_H_#define_
LDPE_H_#include"queue.h"#include"openbsd-tree.h"#ifdef__OpenBSD__#include<net/pf
keyv2.h>#endif#include"ldpd.h"#definemin(x,y)((x)<=(y)?(x):(y))#definemax(x,y)((
x)>(y)?(x):(y))/*forwarddeclarations*/TAILQ_HEAD(mapping_head,mapping_entry);str
ucthello_source{enumhello_typetype;struct{structiface_af*ia;unionldpd_addrsrc_ad
dr;}link;structtnbr*target;};structadj{RB_ENTRY(adj)global_entry,nbr_entry,ia_en
try;structin_addrlsr_id;structnbr*nbr;intds_tlv;structhello_sourcesource;structt
hread*inactivity_timer;uint16_tholdtime;unionldpd_addrtrans_addr;};RB_PROTOTYPE(
global_adj_head,adj,global_entry,adj_compare)RB_PROTOTYPE(nbr_adj_head,adj,nbr_e
ntry,adj_compare)RB_PROTOTYPE(ia_adj_head,adj,ia_entry,adj_compare)structtcp_con
n{structnbr*nbr;intfd;structibuf_read*rbuf;structevbufwbuf;structthread*rev;in_p
ort_tlport;in_port_trport;};structnbr{RB_ENTRY(nbr)id_tree,addr_tree,pid_tree;st
ructtcp_conn*tcp;structnbr_adj_headadj_tree;/*adjacencies*/structthread*ev_conne
ct;structthread*keepalive_timer;structthread*keepalive_timeout;structthread*init
_timeout;structthread*initdelay_timer;structmapping_headmapping_list;structmappi
ng_headwithdraw_list;structmapping_headrequest_list;structmapping_headrelease_li
st;structmapping_headabortreq_list;uint32_tpeerid;/*uniqueIDinDB*/intaf;intds_tl
v;intv4_enabled;/*announce/processv4msgs*/intv6_enabled;/*announce/processv6msgs
*/structin_addrid;/*lsrid*/unionldpd_addrladdr;/*localaddress*/unionldpd_addrrad
dr;/*remoteaddress*/uint32_traddr_scope;/*remoteaddressscope(v6)*/time_tuptime;i
ntfd;intstate;uint32_tconf_seqnum;intidtimer_cnt;uint16_tkeepalive;uint16_tmax_p
du_len;structldp_statsstats;struct{uint8_testablished;uint32_tspi_in;uint32_tspi
_out;enumauth_methodmethod;charmd5key[TCP_MD5_KEY_LEN];}auth;intflags;};#defineF
_NBR_GTSM_NEGOTIATED0x01#defineF_NBR_CAP_DYNAMIC0x02#defineF_NBR_CAP_TWCARD0x04#
defineF_NBR_CAP_UNOTIF0x08RB_HEAD(nbr_id_head,nbr);RB_PROTOTYPE(nbr_id_head,nbr,
id_tree,nbr_id_compare)RB_HEAD(nbr_addr_head,nbr);RB_PROTOTYPE(nbr_addr_head,nbr
,addr_tree,nbr_addr_compare)RB_HEAD(nbr_pid_head,nbr);RB_PROTOTYPE(nbr_pid_head,
nbr,pid_tree,nbr_pid_compare)structpending_conn{TAILQ_ENTRY(pending_conn)entry;i
ntfd;intaf;unionldpd_addraddr;structthread*ev_timeout;};#definePENDING_CONN_TIME
OUT5structmapping_entry{TAILQ_ENTRY(mapping_entry)entry;structmapmap;};structldp
d_sysdep{uint8_tno_pfkey;uint8_tno_md5sig;};externstructldpd_conf*leconf;externs
tructldpd_sysdepsysdep;externstructnbr_id_headnbrs_by_id;externstructnbr_addr_he
adnbrs_by_addr;externstructnbr_pid_headnbrs_by_pid;/*accept.c*/voidaccept_init(v
oid);intaccept_add(int,int(*)(structthread*),void*);voidaccept_del(int);voidacce
pt_pause(void);voidaccept_unpause(void);/*hello.c*/intsend_hello(enumhello_type,
structiface_af*,structtnbr*);voidrecv_hello(structin_addr,structldp_msg*,int,uni
onldpd_addr*,structiface*,int,char*,uint16_t);/*init.c*/voidsend_init(structnbr*
);intrecv_init(structnbr*,char*,uint16_t);voidsend_capability(structnbr*,uint16_
t,int);intrecv_capability(structnbr*,char*,uint16_t);/*keepalive.c*/voidsend_kee
palive(structnbr*);intrecv_keepalive(structnbr*,char*,uint16_t);/*notification.c
*/voidsend_notification_full(structtcp_conn*,structnotify_msg*);voidsend_notific
ation(structtcp_conn*,uint32_t,uint32_t,uint16_t);voidsend_notification_rtlvs(st
ructnbr*,uint32_t,uint32_t,uint16_t,uint16_t,uint16_t,char*);intrecv_notificatio
n(structnbr*,char*,uint16_t);intgen_status_tlv(structibuf*,uint32_t,uint32_t,uin
t16_t);/*address.c*/voidsend_address_single(structnbr*,structif_addr*,int);voids
end_address_all(structnbr*,int);voidsend_mac_withdrawal(structnbr*,structmap*,ui
nt8_t*);intrecv_address(structnbr*,char*,uint16_t);/*labelmapping.c*/#definePREF
IX_SIZE(x)(((x)+7)/8)voidsend_labelmessage(structnbr*,uint16_t,structmapping_hea
d*);intrecv_labelmessage(structnbr*,char*,uint16_t,uint16_t);intgen_pw_status_tl
v(structibuf*,uint32_t);uint16_tlen_fec_tlv(structmap*);intgen_fec_tlv(structibu
f*,structmap*);inttlv_decode_fec_elm(structnbr*,structldp_msg*,char*,uint16_t,st
ructmap*);/*ldpe.c*/voidldpe(void);voidldpe_init(structldpd_init*);intldpe_imsg_
compose_parent(int,pid_t,void*,uint16_t);voidldpe_imsg_compose_parent_sync(int,p
id_t,void*,uint16_t);intldpe_imsg_compose_lde(int,uint32_t,pid_t,void*,uint16_t)
;intldpe_acl_check(char*,int,unionldpd_addr*,uint8_t);voidldpe_reset_nbrs(int);v
oidldpe_reset_ds_nbrs(void);voidldpe_remove_dynamic_tnbrs(int);voidldpe_stop_ini
t_backoff(int);structctl_conn;voidldpe_iface_ctl(structctl_conn*,unsignedint);vo
idldpe_adj_ctl(structctl_conn*);voidldpe_adj_detail_ctl(structctl_conn*);voidldp
e_nbr_ctl(structctl_conn*);voidmapping_list_add(structmapping_head*,structmap*);
voidmapping_list_clr(structmapping_head*);/*interface.c*/structiface*if_new(cons
tchar*);voidldpe_if_init(structiface*);voidldpe_if_exit(structiface*);structifac
e*if_lookup(structldpd_conf*,unsignedshort);structiface*if_lookup_name(structldp
d_conf*,constchar*);voidif_update_info(structiface*,structkif*);structiface_af*i
face_af_get(structiface*,int);voidif_addr_add(structkaddr*);voidif_addr_del(stru
ctkaddr*);voidldp_if_update(structiface*,int);voidif_update_all(int);uint16_tif_
get_hello_holdtime(structiface_af*);uint16_tif_get_hello_interval(structiface_af
*);structctl_iface*if_to_ctl(structiface_af*);in_addr_tif_get_ipv4_addr(structif
ace*);/*adjacency.c*/structadj*adj_new(structin_addr,structhello_source*,unionld
pd_addr*);voidadj_del(structadj*,uint32_t);structadj*adj_find(structin_addr,stru
cthello_source*);intadj_get_af(conststructadj*adj);voidadj_start_itimer(structad
j*);voidadj_stop_itimer(structadj*);structtnbr*tnbr_new(int,unionldpd_addr*);str
ucttnbr*tnbr_find(structldpd_conf*,int,unionldpd_addr*);structtnbr*tnbr_check(st
ructldpd_conf*,structtnbr*);voidtnbr_update(structtnbr*);voidtnbr_update_all(int
);uint16_ttnbr_get_hello_holdtime(structtnbr*);uint16_ttnbr_get_hello_interval(s
tructtnbr*);structctl_adj*adj_to_ctl(structadj*);/*neighbor.c*/intnbr_fsm(struct
nbr*,enumnbr_event);structnbr*nbr_new(structin_addr,int,int,unionldpd_addr*,uint
32_t);voidnbr_del(structnbr*);structnbr*nbr_find_ldpid(uint32_t);structnbr*nbr_f
ind_addr(int,unionldpd_addr*);structnbr*nbr_find_peerid(uint32_t);intnbr_adj_cou
nt(structnbr*,int);intnbr_session_active_role(structnbr*);voidnbr_stop_ktimer(st
ructnbr*);voidnbr_stop_ktimeout(structnbr*);voidnbr_stop_itimeout(structnbr*);vo
idnbr_start_idtimer(structnbr*);voidnbr_stop_idtimer(structnbr*);intnbr_pending_
idtimer(structnbr*);intnbr_pending_connect(structnbr*);intnbr_establish_connecti
on(structnbr*);intnbr_gtsm_enabled(structnbr*,structnbr_params*);intnbr_gtsm_set
up(int,int,structnbr_params*);intnbr_gtsm_check(int,structnbr*,structnbr_params*
);structnbr_params*nbr_params_new(structin_addr);structnbr_params*nbr_params_fin
d(structldpd_conf*,structin_addr);uint16_tnbr_get_keepalive(int,structin_addr);s
tructctl_nbr*nbr_to_ctl(structnbr*);voidnbr_clear_ctl(structctl_nbr*);/*packet.c
*/intgen_ldp_hdr(structibuf*,uint16_t);intgen_msg_hdr(structibuf*,uint16_t,uint1
6_t);intsend_packet(int,int,unionldpd_addr*,structiface_af*,void*,size_t);intdis
c_recv_packet(structthread*);intsession_accept(structthread*);voidsession_accept
_nbr(structnbr*,int);voidsession_shutdown(structnbr*,uint32_t,uint32_t,uint32_t)
;voidsession_close(structnbr*);structtcp_conn*tcp_new(int,structnbr*);voidpendin
g_conn_del(structpending_conn*);structpending_conn*pending_conn_find(int,unionld
pd_addr*);char*pkt_ptr;/*packetbuffer*//*pfkey.c*/#ifdef__OpenBSD__intpfkey_read
(int,structsadb_msg*);intpfkey_establish(structnbr*,structnbr_params*);intpfkey_
remove(structnbr*);intpfkey_init(void);#endif/*l2vpn.c*/voidldpe_l2vpn_init(stru
ctl2vpn*);voidldpe_l2vpn_exit(structl2vpn*);voidldpe_l2vpn_pw_init(structl2vpn_p
w*);voidldpe_l2vpn_pw_exit(structl2vpn_pw*);#endif/*_LDPE_H_*/