/*$OpenBSD$*//**Copyright(c)2003,2004HenningBrauer<henning@openbsd.org>**Permiss
iontouse,copy,modify,anddistributethissoftwareforany*purposewithorwithoutfeeishe
rebygranted,providedthattheabove*copyrightnoticeandthispermissionnoticeappearina
llcopies.**THESOFTWAREISPROVIDED"ASIS"ANDTHEAUTHORDISCLAIMSALLWARRANTIES*WITHREG
ARDTOTHISSOFTWAREINCLUDINGALLIMPLIEDWARRANTIESOF*MERCHANTABILITYANDFITNESS.INNOE
VENTSHALLTHEAUTHORBELIABLEFOR*ANYSPECIAL,DIRECT,INDIRECT,ORCONSEQUENTIALDAMAGESO
RANYDAMAGES*WHATSOEVERRESULTINGFROMLOSSOFUSE,DATAORPROFITS,WHETHERINAN*ACTIONOFC
ONTRACT,NEGLIGENCEOROTHERTORTIOUSACTION,ARISINGOUTOF*ORINCONNECTIONWITHTHEUSEORP
ERFORMANCEOFTHISSOFTWARE.*/#ifndefLOG_H#defineLOG_H#include<stdarg.h>externconst
char*log_procname;voidlogit(int,constchar*,...)__attribute__((__format__(printf,
2,3)));voidvlog(int,constchar*,va_list)__attribute__((__format__(printf,2,0)));v
oidlog_warn(constchar*,...)__attribute__((__format__(printf,1,2)));voidlog_warnx
(constchar*,...)__attribute__((__format__(printf,1,2)));voidlog_info(constchar*,
...)__attribute__((__format__(printf,1,2)));voidlog_notice(constchar*,...)__attr
ibute__((__format__(printf,1,2)));voidlog_debug(constchar*,...)__attribute__((__
format__(printf,1,2)));voidfatal(constchar*)__attribute__((noreturn))__attribute
__((__format__(printf,1,0)));voidfatalx(constchar*)__attribute__((noreturn))__at
tribute__((__format__(printf,1,0)));#endif/*LOG_H*/