#!/bin/bash
# Script to see if we should startup the particular
# daemon as part of systemd initialization
# If the daemon was running (set by the ExecStopPost
# action in the Unit file ) or if the daemon
# is enabled start it up
FILE="/var/run/quagga/$1.was_running"
if [ -e $FILE ]
then
    rm $FILE
    systemctl start $1
fi

systemctl is-enabled $1 > /dev/null
if [ $? -eq 0 ]
then
    systemctl start $1
fi

exit 0
