/**Testcodeforlib/command.c**Copyright(C)2013byOpenSourceRouting.*Copyright(C)20
13byInternetSystemsConsortium,Inc.("ISC")**Thisprogramreadsinalistofcommandlines
fromstdin*andcallsallthepublicfunctionsoflib/command.cfor*boththegivencommandlin
esandfuzzedversionsthereof.**Theoutputiscurrentlynotvalidatedbutonlylogged.Itcan
*bediffedtofindregressionsbetweenversions.**Quaggaisfreesoftware;youcanredistrib
uteitand/ormodifyit*underthetermsoftheGNUGeneralPublicLicenseaspublishedbythe*Fr
eeSoftwareFoundation;eitherversion2,or(atyouroption)any*laterversion.**Quaggaisd
istributedinthehopethatitwillbeuseful,but*WITHOUTANYWARRANTY;withouteventheimpli
edwarrantyof*MERCHANTABILITYorFITNESSFORAPARTICULARPURPOSE.SeetheGNU*GeneralPubl
icLicenseformoredetails.**YoushouldhavereceivedacopyoftheGNUGeneralPublicLicense
along*withthisprogram;seethefileCOPYING;ifnot,writetotheFreeSoftware*Foundation,
Inc.,51FranklinSt,FifthFloor,Boston,MA02110-1301USA*/#defineREALLY_NEED_PLAIN_GE
TOPT1#include<zebra.h>#include<stdio.h>#include<stdlib.h>#include<unistd.h>#incl
ude"command.h"#include"memory.h"#include"vector.h"#include"prng.h"externvectorcm
dvec;externstructcmd_nodevty_node;externvoidtest_init_cmd(void);/*providedintest
-commands-defun.c*/structthread_master*master;/*dummyforlibfrr*/staticvectortest
_cmds;staticchartest_buf[32768];staticstructcmd_nodebgp_node={BGP_NODE,"%s(confi
g-router)#",};staticstructcmd_noderip_node={RIP_NODE,"%s(config-router)#",};stat
icstructcmd_nodeisis_node={ISIS_NODE,"%s(config-router)#",};staticstructcmd_node
interface_node={INTERFACE_NODE,"%s(config-if)#",};staticstructcmd_nodermap_node=
{RMAP_NODE,"%s(config-route-map)#"};staticstructcmd_nodezebra_node={ZEBRA_NODE,"
%s(config-router)#"};staticstructcmd_nodebgp_vpnv4_node={BGP_VPNV4_NODE,"%s(conf
ig-router-af)#"};staticstructcmd_nodebgp_ipv4_node={BGP_IPV4_NODE,"%s(config-rou
ter-af)#"};staticstructcmd_nodebgp_ipv4m_node={BGP_IPV4M_NODE,"%s(config-router-
af)#"};staticstructcmd_nodebgp_ipv6_node={BGP_IPV6_NODE,"%s(config-router-af)#"}
;staticstructcmd_nodebgp_ipv6m_node={BGP_IPV6M_NODE,"%s(config-router-af)#"};sta
ticstructcmd_nodeospf_node={OSPF_NODE,"%s(config-router)#"};staticstructcmd_node
ripng_node={RIPNG_NODE,"%s(config-router)#"};staticstructcmd_nodeospf6_node={OSP
F6_NODE,"%s(config-ospf6)#"};staticstructcmd_nodekeychain_node={KEYCHAIN_NODE,"%
s(config-keychain)#"};staticstructcmd_nodekeychain_key_node={KEYCHAIN_KEY_NODE,"
%s(config-keychain-key)#"};staticinttest_callback(conststructcmd_element*cmd,str
uctvty*vty,intargc,structcmd_token*argv[]){intoffset;intrv;inti;offset=0;rv=snpr
intf(test_buf,sizeof(test_buf),"'%s'",cmd->string);if(rv<0)abort();offset+=rv;fo
r(i=0;i<argc;i++){rv=snprintf(test_buf+offset,sizeof(test_buf)-offset,"%s'%s'",(
i==0)?":":",",argv[i]->arg);if(rv<0)abort();offset+=rv;}returnCMD_SUCCESS;}stati
cvoidtest_load(void){charline[4096];test_cmds=vector_init(VECTOR_MIN_SIZE);while
(fgets(line,sizeof(line),stdin)!=NULL){if(strlen(line))line[strlen(line)-1]='\0'
;if(line[0]=='#')continue;vector_set(test_cmds,XSTRDUP(MTYPE_STRVEC,line));}}sta
ticvoidtest_init(void){unsignedintnode;unsignedinti;structcmd_node*cnode;structc
md_element*cmd;cmd_init(1);install_node(&bgp_node,NULL);install_node(&rip_node,N
ULL);install_node(&interface_node,NULL);install_node(&rmap_node,NULL);install_no
de(&zebra_node,NULL);install_node(&bgp_vpnv4_node,NULL);install_node(&bgp_ipv4_n
ode,NULL);install_node(&bgp_ipv4m_node,NULL);install_node(&bgp_ipv6_node,NULL);i
nstall_node(&bgp_ipv6m_node,NULL);install_node(&ospf_node,NULL);install_node(&ri
png_node,NULL);install_node(&ospf6_node,NULL);install_node(&keychain_node,NULL);
install_node(&keychain_key_node,NULL);install_node(&isis_node,NULL);install_node
(&vty_node,NULL);test_init_cmd();for(node=0;node<vector_active(cmdvec);node++)if
((cnode=vector_slot(cmdvec,node))!=NULL)for(i=0;i<vector_active(cnode->cmd_vecto
r);i++)if((cmd=vector_slot(cnode->cmd_vector,i))!=NULL){cmd->daemon=0;cmd->func=
test_callback;}test_load();vty_init_vtysh();}staticvoidtest_terminate(void){unsi
gnedinti;vty_terminate();for(i=0;i<vector_active(test_cmds);i++)XFREE(MTYPE_STRV
EC,vector_slot(test_cmds,i));vector_free(test_cmds);cmd_terminate();}staticvoidt
est_run(structprng*prng,structvty*vty,constchar*cmd,unsignedintedit_dist,unsigne
dintnode_index,intverbose){constchar*test_str;vectorvline;intret;unsignedinti;ch
ar**completions;unsignedintj;structcmd_node*cnode;vectordescriptions;intappended
_null;intno_match;test_str=prng_fuzz(prng,cmd,"abcdefghijklmnopqrstuvwxyzABCDEFG
HIJKLMNOPQRSTUVWXYZ0123456789-_:./",edit_dist);vline=cmd_make_strvec(test_str);i
f(vline==NULL)return;appended_null=0;for(i=0;i<vector_active(cmdvec);i++)if((cno
de=vector_slot(cmdvec,i))!=NULL){if(node_index!=(unsignedint)-1&&i!=node_index)c
ontinue;if(appended_null){vector_unset(vline,vector_active(vline)-1);appended_nu
ll=0;}vty->node=cnode->node;test_buf[0]='\0';ret=cmd_execute_command(vline,vty,N
ULL,0);no_match=(ret==CMD_ERR_NO_MATCH);if(verbose||!no_match)printf("executerel
axed'%s'@%d:rv==%d%s%s\n",test_str,cnode->node,ret,(test_buf[0]!='\0')?",":"",te
st_buf);vty->node=cnode->node;test_buf[0]='\0';ret=cmd_execute_command_strict(vl
ine,vty,NULL);if(verbose||!no_match)printf("executestrict'%s'@%d:rv==%d%s%s\n",t
est_str,cnode->node,ret,(test_buf[0]!='\0')?",":"",test_buf);if(isspace((int)tes
t_str[strlen(test_str)-1])){vector_set(vline,NULL);appended_null=1;}vty->node=cn
ode->node;completions=cmd_complete_command(vline,vty,&ret);if(verbose||!no_match
)printf("complete'%s'@%d:rv==%d\n",test_str,cnode->node,ret);if(completions!=NUL
L){for(j=0;completions[j]!=NULL;j++){printf("'%s'\n",completions[j]);XFREE(MTYPE
_TMP,completions[j]);}XFREE(MTYPE_TMP,completions);}vty->node=cnode->node;descri
ptions=cmd_describe_command(vline,vty,&ret);if(verbose||!no_match)printf("descri
be'%s'@%d:rv==%d\n",test_str,cnode->node,ret);if(descriptions!=NULL){for(j=0;j<v
ector_active(descriptions);j++){structcmd_token*cmd=vector_slot(descriptions,j);
printf("'%s''%s'\n",cmd->text,cmd->desc);}vector_free(descriptions);}}cmd_free_s
trvec(vline);}intmain(intargc,char**argv){intopt;structprng*prng;structvty*vty;u
nsignedintedit_distance;unsignedintmax_edit_distance;unsignedintnode_index;intve
rbose;unsignedinttest_cmd;unsignedintiteration;unsignedintnum_iterations;max_edi
t_distance=3;node_index=-1;verbose=0;while((opt=getopt(argc,argv,"e:n:v"))!=-1){
switch(opt){case'e':max_edit_distance=atoi(optarg);break;case'n':node_index=atoi
(optarg);break;case'v':verbose++;break;default:fprintf(stderr,"Usage:%s[-e<edit_
dist>][-n<node_idx>][-v]\n",argv[0]);exit(1);break;}}test_init();prng=prng_new(0
);vty=vty_new();vty->type=VTY_TERM;fprintf(stderr,"Progress:\n0/%u",vector_activ
e(test_cmds));for(test_cmd=0;test_cmd<vector_active(test_cmds);test_cmd++){for(e
dit_distance=0;edit_distance<=max_edit_distance;edit_distance++){num_iterations=
1<<edit_distance;num_iterations*=num_iterations*num_iterations;for(iteration=0;i
teration<num_iterations;iteration++)test_run(prng,vty,vector_slot(test_cmds,test
_cmd),edit_distance,node_index,verbose);}fprintf(stderr,"\r%u/%u",test_cmd+1,vec
tor_active(test_cmds));}fprintf(stderr,"\nDone.\n");vty_close(vty);prng_free(prn
g);test_terminate();return0;}