# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - graphviz

python:
  install:
    - requirements: doc/developer/requirements.txt

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/developer/conf.py
