# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
<<<<<<< HEAD
=======
  apt_packages:
    - graphviz

python:
  install:
    - requirements: doc/developer/requirements.txt
>>>>>>> 9b0b9282d (bgpd: Fix bgp core with a possible Intf delete)

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/developer/conf.py
