name: Add base branch label

on:
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
  label:
    if: github.repository == 'frrouting/frr'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Add base branch label
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          BASE_LABEL: ${{ github.event.pull_request.base.ref }}
        run: gh pr edit "$PR_NUMBER" --add-label "$BASE_LABEL"
