name: Add base branch label

on:
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
  label:
    if: github.repository == 'frrouting/frr'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Add base branch label
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr edit "${{ github.event.pull_request.number }}" \
            --add-label "${{ github.event.pull_request.base.ref }}"
