name: Add base branch label

on:
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
  label:
    if: github.repository == 'frrouting/frr'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            ${{ github.event.pull_request.base.ref }}
