name: Build daily 'master' images for Docker

on:
  schedule:
    - cron: '59 23 * * *'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker_daily_master:
    if: github.repository == 'frrouting/frr'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Custom variables
        id: vars
        run: |
          # To package a specific git commit, the date of the commit gets
          # appended to the latest release, e.g. 1.0.0_git20180204.
          # This is the requirement by APKBUILD (abuild).
          # More details: https://wiki.alpinelinux.org/wiki/APKBUILD_Reference.
          echo ::set-output name=date::$(date +'%Y%m%d')

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/alpine/Dockerfile
          push: true
          tags: quay.io/frrouting/frr:master
          build-args: PKGVER=${{ steps.vars.outputs.date }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
